### PR TITLE
sill.1.3 - via opam-publish

### PR DESCRIPTION
**Pull request by ISANobody**
Implementation of Linear Session Types
A prototype language focused on organizing concurrent programs via
communication along substructurally typed channels between processes.

---
* Homepage: https://github.com/ISANobody/sill
* Source repo: https://github.com/ISANobody/sill.git
* Bug tracker: https://github.com/ISANobody/sill/issues

---
Pull-request generated by opam-publish v0.2.1

### CODE REVIEW

**Comment by yallop** [comment]
[Missing dependency](https://travis-ci.org/ocaml/opam-repository/jobs/50499222)?

```
# ocamlfind: Package `monad-custom' not found
# W: Field 'pkg_monad_custom' is not set: Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d monad-custom > '/tmp/oasis-da6ace.txt'' terminated with error code 2
# ocamlfind: Package `mparser' not found
# W: Field 'pkg_mparser' is not set: Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d mparser > '/tmp/oasis-f13ea4.txt'' terminated with error code 2
# E: Cannot find findlib package monad-custom
# E: Cannot find findlib package mparser
# E: Failure("2 configuration errors")
````

**Comment by ISANobody** [comment]
Whoops. Fixed and resubmitted.

**Comment by yallop** [comment]
It [looks](https://travis-ci.org/ocaml/opam-repository/jobs/50505864) like there's still a dependency missing:

```
# ocamlfind: Package `monad-custom' not found
# W: Field 'pkg_monad_custom' is not set: Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d monad-custom > '/tmp/oasis-2e3cbe.txt'' terminated with error code 2
# E: Cannot find findlib package monad-custom
# E: Failure("1 configuration error")
```

**Comment by ISANobody** [comment]
Ugh. Sorry about wasting your time. Is there some sort of automatic check on my end that I should be running before using opam-publish? Either way, a hopefully fixed version should be submitted.

**Comment by yallop** [comment]
No worries.  One approach is to try out installation using a local clone of `opam-repository` using something like `opam repository set-url`.

**Comment by samoht** [comment]
You can also install Travis scripts in your repo: that's relatively easy to do now you have an `opam` file. See [the correspoding blog post](https://opam.ocaml.org/blog/opam-1-2-travisci/)

**Pull request merged**
