### PR TITLE
genet: add upper bounds on menhir and xtmpl

### PR DESCRIPTION
**Pull request by damiendoligez**

### CODE REVIEW

**Comment by samoht** [comment]
Something is wrong on 4.01 /cc @zoggy 

```
#=== ERROR while installing genet.0.1 =========================================#
# opam-version 1.2.2
# os           linux
# command      ./configure --prefix /home/travis/.opam/4.01.0
# path         /home/travis/.opam/4.01.0/build/genet.0.1
# compiler     4.01.0
# exit-code    1
# env-file     /home/travis/.opam/4.01.0/build/genet.0.1/genet-22643-d6abbe.env
# stdout-file  /home/travis/.opam/4.01.0/build/genet.0.1/genet-22643-d6abbe.out
# stderr-file  /home/travis/.opam/4.01.0/build/genet.0.1/genet-22643-d6abbe.err
### stdout ###
# [...]
# checking for config-file... ok
# checking for mysql... ok
# checking for rdf.mysql... ok
# checking for rdf.postgresql... Package rdf.postgresql not foundchecking for nethttpd... ok
# checking for pcre... ok
# checking for xtmpl... ok
# checking for lablgtk2... ok
# checking for lablgtk2-extras... ok
# checking for lablgladecc2... no
# checking for lablgladecc... no
### stderr ###
# File "utils/checkocaml.ml", line 424, characters 18-20:
# Warning 3: deprecated feature: operator (or); you should use (||) instead
# File "utils/checkocaml.ml", line 829, characters 33-35:
# Warning 3: deprecated feature: operator (or); you should use (||) instead
# ocamlfind: Package `rdf.postgresql' not found
# Cannot find lablgladecc2 or lablgladecc
```

**Comment by yallop** [comment]
The build's failing because the `dot.gtk` subpackage isn't installed.
The `dot.gtk` subpackage isn't installed because `conf-gnomecanvas` isn't installed, and because `ocamldot` needs to depend on `conf-gnomecanvas`.

**Comment by yallop** [comment]
> `ocamldot` needs to depend on `conf-gnomecanvas`

See #7491.

**Comment by yallop** [comment]
> The `dot.gtk` subpackage isn't installed because `conf-gnomecanvas` isn't installed

See ed9cf10, aeed14b.

**Comment by yallop** [comment]
`Rdf_node` was [renamed](https://github.com/zoggy/ocaml-rdf/blob/8c324b5a7475f920db0b349df201ce2c75cfa4a3/Changes#L66) in 0.7.  I've added constraints (4afcc25).

**Pull request merged**
