### PR TITLE
Upgrade a few packages from a deprecated invocation of topkg.

### PR DESCRIPTION
**Pull request by dbuenzli**

### CODE REVIEW

**Comment by dbuenzli** [comment]
The warnings are due to the recent automatic rewrite of the repo.

**Comment by dbuenzli** [comment]
Oh and camelus is right about these `topkg-care` packages that are not installable anymore this is because we have the following dependency graph (e.g. on `bos`, but this also happens with `rresult`, `logs` and `fmt`):
```
bos -----> topkg <----- topkg-care
 ^__________________________|
```
should I remove the packages that are no longer installable from the repo ?

**Comment by samoht** [comment]
> should I remove the packages that are no longer installable from the repo ?

yes please!

**Comment by OCamlPro-Henry** [comment]
@dbuenzli @Altgr the automatic rewrite was based on an heuristic that was safe but may be pessimistic in some case. It moved every build instructions that matches `.*install.*` from the `build` rule to the `install` one. If this particular invocation of `topkg` do not install any file in `.opam` but only generate a `.install` file, feel free to move it back in the `build` rule. In that case, sorry for the noise. We might also try another automatic rewrite with a better heuristic that revert the changes for package using `topkg`.

**Comment by samoht** [comment]
@OCamlPro-Henry ha yes I haven't spotted that the topkg invocation are now in the "install" field. That's wrong as `topkg` indeed generates an `.install` file. Can you please try to revert this? Thanks!

**Comment by OCamlPro-Henry** [comment]
@samoht Sure.

**Comment by dbuenzli** [comment]
Removed the versions that were no longer installable, can be merged.

**Comment by hcarty** [comment]
This seems to break installation of fmt on 4.02.3, and maybe other pre-4.03.0 version, because of the version constraint on ocamlbuild.

**Comment by dbuenzli** [comment]
Yes see https://travis-ci.org/ocaml/opam-repository/jobs/141422036

**Pull request merged**
