### PR TITLE
mlgmpidl.1.2.6-1: available for OCaml ≥ 3.12.1

### PR DESCRIPTION
**Pull request by nberth**

### CODE REVIEW

**Comment by nberth** [comment]
@avsm It seems to me that the failures with OCaml 4.06.0* are only due to the unavailability of some versions of the packages.

**Comment by rgrinberg** [comment]
Pr looks good. Does opam accept version numbers with dashes?

**Comment by gasche** [comment]
I played a bit with `opam lint` and it seems that dashes in version names are fine. Thanks @rgrinberg for noticing the potential issue.

**Comment by nberth** [comment]
@gasche @rgrinberg [The manual](https://opam.ocaml.org/doc/Manual.html#Package-Formulas) specifies that OPAM is quite liberal in terms of what it accepts as valid version strings.

**Pull request merged**
