### PR TITLE
Package errpy.0.0.10

### PR DESCRIPTION
**Pull request by jasontatton**
### `errpy.0.0.10`
Errpy: An Error Recovering Python Parser implemented in Rust
This is a new project to provide an error-recovering Python parser, implemented in Rust based on tree-sitter. Our short-term goal is to use it in the pyre type checker, in order to provide better IDE features.

---
* Homepage: https://github.com/facebook/errpy
* Source repo: git+https://github.com/facebook/errpy.git
* Bug tracker: https://github.com/facebook/errpy/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by jasontatton** [comment]
This should resolve the error raised regarding Ocaml 5.1.0. compatibility previously

**Comment by vsiles** [comment]
@jasontatton any issue I can help with to speed things up ?

**Comment by jasontatton** [comment]
@vsiles Not that I am aware of, we are just waiting for someone to review this

**Comment by mseri** [comment]
Sorry for the long wait. This looks mostly fine: it builds where it can and the error explains that you need to install a more recent rust. I would update the lower bound on ocaml though since on 4.01-4.04 it seems that ppx_deriving and dune are not behaving correctly

**Comment by mseri** [comment]
Thanks

**Pull request merged**
