### PR TITLE
Rename glpk and update to 0.1.7.

### PR DESCRIPTION
**Pull request by smimram**
* renamed ocaml-glpk to glpk
* added version 0.1.7

### CODE REVIEW

**Comment by yallop** [comment]
The 0.1.7 build is [failing](https://travis-ci.org/ocaml/opam-repository/jobs/172990729).  The end of the logs show a C compilation error;

```
### stderr ###
# [...]
# glpk_stubs.c:523:23: note: in expansion of macro ‘Lpx_val’
#    if (lpx_write_cpxlp(Lpx_val(blp), String_val(fname)))
#                        ^
# glpk_stubs.c: At top level:
# glpk_stubs.c:89:33: warning: ‘lpx_ops’ defined but not used [-Wunused-variable]
#  static struct custom_operations lpx_ops =
#                                  ^
# make[2]: *** [glpk_stubs.o] Error 2
# make[1]: *** [byte-code-library] Error 2
# make: *** [byte] Error 2
```

**Comment by smimram** [comment]
The build is failing with 0.1.6, as expected. The main purpose of this patch was to release 0.1.7, which should build correctly (I tested it locally).

**Comment by smimram** [comment]
The build is failing with 0.1.6, as expected. The main purpose of this patch was to release 0.1.7, which should build correctly (I tested it locally).

**Comment by smimram** [comment]
The build is failing with 0.1.6, as expected. The main purpose of this patch was to release 0.1.7, which should build correctly (I tested it locally).

**Comment by yallop** [comment]
Ah, right: it's the 0.1.6 build that's failing.  Is the problem due to the newew version of `libglpk-dev` on Ubuntu 14.04?

Could you please split the PR so that we can see a successful build of 0.1.7 on Travis before merging?

**Pull request closed without merging**
