### PR TITLE
Package socialpeek.1.0.0

### PR DESCRIPTION
**Pull request by erizocosmico**
### `socialpeek.1.0.0`

OCaml library to extract social information such as Twitter cards or OpenGraph data from webpages and HTML.

### Get twitter card

```ocaml
open Socialpeek

let () =
  (** you can use `from_html` instead if you already have the HTML *)
  let twitter_card = from_url "http://something.cool" |> Twitter.get_card in
  match twitter_card with
  | Twitter.Summary data -> (** Do something with data *)
  | Twitter.Summary_large_image data -> (** Do something with data *)
  | Twitter.App data -> (** Do something with data *)
  | Twitter.Player data -> (** Do something with data *)
```

Twitter cards can have 4 different shapes: `summary`, `summary_large_image`, `app` or `player` (more info about [twitter cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup)).
So the result of `Twitter.get_card` is a variant type that holds only the data a certain type of card can have.

### Get Opengraph data

```ocaml
open Socialpeek

let () =
  (** you can use `from_html` instead if you already have the HTML *)
  let og_data = from_url "http://something.cool" |> Opengraph.get_data in
  (** do something with the data *)
```

### Get twitter and opengraph data

```ocaml
open Socialpeek

let () =
  (** you can use `from_html` instead if you already have the HTML *)
  let tags = from_url "http://something.cool" in
  let og_data = Opengraph.get_data tags in
  let twitter_card = Twitter.get_card tags in
  (** do something with the data *)
```

---
* Homepage: https://github.com/erizocosmico/ocaml-socialpeek
* Source repo: https://github.com/erizocosmico/ocaml-socialpeek.git
* Bug tracker: https://github.com/erizocosmico/ocaml-socialpeek/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by rgrinberg** [comment]
You should add a minimum OCaml version on 4.01 since you use |>.

But I'd recommend a 4.02.3 minimum at least, if you aren't actually planning to test things on really old versions.

**Comment by erizocosmico** [comment]
Fixed @rgrinberg

**Comment by rgrinberg** [comment]
Where's the fix? I don't see a minimum OCaml version being set anywhere.

**Comment by erizocosmico** [comment]
@rgrinberg sorry, now it is

**Comment by rgrinberg** [comment]
Thanks.

**Pull request merged**
