### PR TITLE
7 packages from ocaml/opam at 2.1.0~beta2

### PR DESCRIPTION
**Pull request by AltGr**
This pull-request concerns:
-`opam-client.2.1.0~beta2`: opam 2.1 development libraries (client)
-`opam-core.2.1.0~beta2`: opam 2.1 development libraries (core)
-`opam-devel.2.1.0~beta2`: opam 2.1 bootstrapped binary
-`opam-format.2.1.0~beta2`: opam 2.1 development libraries (format)
-`opam-repository.2.1.0~beta2`: opam 2.1 development libraries (repository)
-`opam-solver.2.1.0~beta2`: opam 2.1 development libraries (solver)
-`opam-state.2.1.0~beta2`: opam 2.1 development libraries (state)

---
* Source repo: git+https://github.com/ocaml/opam.git
* Bug tracker: https://github.com/ocaml/opam/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by AltGr** [comment]
Just noticed we hadn't published these packages yet. WIll be interesting to see the revdeps which get broken, in any case.
Note that I excluded `opam-installer` which should be no different from v.2.0.7

**Comment by kit-ty-kate** [comment]
The build failed on OCaml 4.02. Could you have a look at it?
```
#=== ERROR while compiling opam-client.2.1.0~beta2 ============================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.02.3 | file:///home/opam/opam-repository
# path                 ~/.opam/4.02/.opam-switch/build/opam-client.2.1.0~beta2
# command              ~/.opam/4.02/bin/dune build -p opam-client -j 72
# exit-code            1
# env-file             ~/.opam/log/opam-client-23-c43ced.env
# output-file          ~/.opam/log/opam-client-23-c43ced.out
### output ###
#       ocamlc src/client/.opam_client.objs/byte/opamAdminCommand.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.02/bin/ocamlc.opt -w -40 -w +a-4-40-42-44-48 -safe-string -w -67 -g -bin-annot -I src/client/.opam_client.objs/byte -I /home/opam/.opam/4.02/lib/bytes -I /home/opam/.opam/4.02/lib/cmdliner -I /home/opam/.opam/4.02/lib/cudf -I /home/opam/.opam/4.02/lib/dose3 -I /home/opam/.opam/4.02/lib/extlib -I /home/opam/.opam/4.02/lib/mccs -I /home/opam/.opam/4.02/lib/mccs/glpk/internal -I /home/opam/.opam/4.02/lib/ocamlgraph -I /home/opam/.opam/4.02/lib/opam-core -I /home/opam/.opam/4.02/lib/opam-file-format -I /home/opam/.opam/4.02/lib/opam-format -I /home/opam/.opam/4.02/lib/opam-repository -I /home/opam/.opam/4.02/lib/opam-solver -I /home/opam/.opam/4.02/lib/opam-state -I /home/opam/.opam/4.02/lib/re -I /home/opam/.opam/4.02/lib/re/pcre -I /home/opam/.opam/4.02/lib/seq -intf-suffix .ml -no-alias-deps -o src/client/.opam_client.objs/byte/opamAdminCommand.cmo -c -impl src/client/opamAdminCommand.ml)
# File "src/client/opamAdminCommand.ml", line 36, characters 5-26:
# Error: Unbound value Manpage.s_description
#       ocamlc src/client/.opam_client.objs/byte/opamCommands.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.02/bin/ocamlc.opt -w -40 -w +a-4-40-42-44-48 -safe-string -w -67 -g -bin-annot -I src/client/.opam_client.objs/byte -I /home/opam/.opam/4.02/lib/bytes -I /home/opam/.opam/4.02/lib/cmdliner -I /home/opam/.opam/4.02/lib/cudf -I /home/opam/.opam/4.02/lib/dose3 -I /home/opam/.opam/4.02/lib/extlib -I /home/opam/.opam/4.02/lib/mccs -I /home/opam/.opam/4.02/lib/mccs/glpk/internal -I /home/opam/.opam/4.02/lib/ocamlgraph -I /home/opam/.opam/4.02/lib/opam-core -I /home/opam/.opam/4.02/lib/opam-file-format -I /home/opam/.opam/4.02/lib/opam-format -I /home/opam/.opam/4.02/lib/opam-repository -I /home/opam/.opam/4.02/lib/opam-solver -I /home/opam/.opam/4.02/lib/opam-state -I /home/opam/.opam/4.02/lib/re -I /home/opam/.opam/4.02/lib/re/pcre -I /home/opam/.opam/4.02/lib/seq -intf-suffix .ml -no-alias-deps -o src/client/.opam_client.objs/byte/opamCommands.cmo -c -impl src/client/opamCommands.ml)
# File "src/client/opamCommands.ml", line 172, characters 7-28:
# Error: Unbound value Manpage.s_description
#       ocamlc src/client/.opam_client.objs/byte/opamArg.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.02/bin/ocamlc.opt -w -40 -w +a-4-40-42-44-48 -safe-string -w -67 -g -bin-annot -I src/client/.opam_client.objs/byte -I /home/opam/.opam/4.02/lib/bytes -I /home/opam/.opam/4.02/lib/cmdliner -I /home/opam/.opam/4.02/lib/cudf -I /home/opam/.opam/4.02/lib/dose3 -I /home/opam/.opam/4.02/lib/extlib -I /home/opam/.opam/4.02/lib/mccs -I /home/opam/.opam/4.02/lib/mccs/glpk/internal -I /home/opam/.opam/4.02/lib/ocamlgraph -I /home/opam/.opam/4.02/lib/opam-core -I /home/opam/.opam/4.02/lib/opam-file-format -I /home/opam/.opam/4.02/lib/opam-format -I /home/opam/.opam/4.02/lib/opam-repository -I /home/opam/.opam/4.02/lib/opam-solver -I /home/opam/.opam/4.02/lib/opam-state -I /home/opam/.opam/4.02/lib/re -I /home/opam/.opam/4.02/lib/re/pcre -I /home/opam/.opam/4.02/lib/seq -intf-suffix .ml -no-alias-deps -o src/client/.opam_client.objs/byte/opamArg.cmo -c -impl src/client/opamArg.ml)
# File "src/client/opamArg.ml", line 234, characters 28-52:
# Error: Unbound value Manpage.s_common_options
#     ocamlopt src/client/.opam_client.objs/native/opamArg.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.02/bin/ocamlopt.opt -w -40 -w +a-4-40-42-44-48 -safe-string -w -67 -g -I src/client/.opam_client.objs/byte -I src/client/.opam_client.objs/native -I /home/opam/.opam/4.02/lib/bytes -I /home/opam/.opam/4.02/lib/cmdliner -I /home/opam/.opam/4.02/lib/cudf -I /home/opam/.opam/4.02/lib/dose3 -I /home/opam/.opam/4.02/lib/extlib -I /home/opam/.opam/4.02/lib/mccs -I /home/opam/.opam/4.02/lib/mccs/glpk/internal -I /home/opam/.opam/4.02/lib/ocamlgraph -I /home/opam/.opam/4.02/lib/opam-core -I /home/opam/.opam/4.02/lib/opam-file-format -I /home/opam/.opam/4.02/lib/opam-format -I /home/opam/.opam/4.02/lib/opam-repository -I /home/opam/.opam/4.02/lib/opam-solver -I /home/opam/.opam/4.02/lib/opam-state -I /home/opam/.opam/4.02/lib/re -I /home/opam/.opam/4.02/lib/re/pcre -I /home/opam/.opam/4.02/lib/seq -intf-suffix .ml -no-alias-deps -o src/client/.opam_client.objs/native/opamArg.cmx -c -impl src/client/opamArg.ml)
# File "src/client/opamArg.ml", line 234, characters 28-52:
# Error: Unbound value Manpage.s_common_options
```

**Comment by mseri** [comment]
Ping @AltGr

**Comment by AltGr** [comment]
Thanks for the log error & sorry for the lag, updated the version constraints, which should fix it.

**Comment by mseri** [comment]
There are weird (test?) failures in macos and freebsd. Can you have a look: https://travis-ci.org/github/ocaml/opam-repository/jobs/734012218 ?

**Comment by rjbou** [comment]
rebased + update some constraint on dependant packages: opam-bundle, opam-lock, opam-package-upgrade, opam-publish, & dune-release.1.4.0 (ping @samoth)

**Comment by rjbou** [comment]
updates: opam-format & opam-repository disable CI variable  & `opam-core.2.0.0~rc` restrained to `ocaml < 4.0.7`

**Comment by rjbou** [comment]
* `dune-release` is failing weirdly
```
- Full test results in `/usr/home/travis/.opam/ocaml-base-compiler.4.09.1/.opam-switch/build/dune-release.1.4.0/_build/default/tests/lib/_build/_tests/dune-release'.
- Test Successful in 0.000s. 64 tests run.
[ERROR] The compilation of dune-release failed at
        "/usr/home/travis/.opam/ocaml-base-compiler.4.09.1/bin/dune runtest -p
        dune-release -j 1".
```
* `opam-publish` is a solver timeout
* beta2 tests are failing under xcode, with no idea why... In the same way as alpine, if I can have the dockerfile, i'll be able to investigate

**Comment by rjbou** [comment]
On the beta2 failures, after investigating on alpine, there is two reasons: first openssl that is not installed (the tests need it), and second a system-wide installed ocaml not found. Once those two installed, the beta2 tests are green.

**Comment by mseri** [comment]
Do you know what is wrong with dune-release?

**Comment by rjbou** [comment]
Tests are successful and it errors, I guess that  it is simply a bad exit code problem.

**Comment by mseri** [comment]
I think it is time to merge then

**Pull request merged**
