### PR TITLE
latest version of obuild

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Why can't you use the opam from the obuild repo? This opam file will break pinning `--dev-repo`

**Comment by UnixJunkie** [comment]
Hmmm. Sorry, I thought I was using the obuild repo.
I try to correct,

**Comment by UnixJunkie** [comment]
I just pushed with the correct opam file this time

**Comment by UnixJunkie** [comment]
Travis is all green.

**Comment by dsheets** [comment]
It looks like the `obuild.install` file is redundant

**Comment by UnixJunkie** [comment]
On 06/29/2015 11:10 PM, David Sheets wrote:
> It looks like the |obuild.install| file is redundant

Do you want that we remove the obuild.install file?

Is there something wrong inside of it?

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocaml/opam-repository/pull/4330#issuecomment-116847275>.
>

-- 
Regards,
Francois.
"When in doubt, use more types"

**Comment by dsheets** [comment]
The `obuild.install` file is identical to the `obuild.install` file in the source archive. I don't understand why the opam-repository needs to contain it verbatim. I'd rather it be removed as it is not necessary.

**Comment by UnixJunkie** [comment]
OK, done.

**Comment by UnixJunkie** [comment]
It's all green again.

**Pull request merged**
