### PR TITLE
2 packages from issuu/ocaml-protoc-plugin at 0.9

### PR DESCRIPTION
**Pull request by andersfugmann**
This pull-request concerns:
-`conf-protoc.0.9`: Virtual package to install protoc compiler
-`ocaml-protoc-plugin.0.9`: Plugin for protoc protobuf compiler to generate ocaml definitions from a .proto file

---

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Do you have any clue why the tests fail **only** on MacOS?
```
+ /Users/travis/.opam/opam-init/hooks/sandbox.sh "build" "dune" "runtest" "-p" "ocaml-protoc-plugin" "-j" "1" (CWD=/Users/travis/.opam/ocaml-system/.opam-switch/build/ocaml-protoc-plugin.0.9)

- File "test/int_types_test.ml", line 1, characters 0-0:

-          git (internal) (exit 1)

- (cd _build/default && /usr/local/bin/git diff --no-index --color=always -u test/int_types_test.ml test/int_types_test.ml.corrected)

- diff --git a/test/int_types_test.ml b/test/int_types_test.ml.corrected

- index cc8ba0d..63209c6 100644

- --- a/test/int_types_test.ml

- +++ b/test/int_types_test.ml.corrected

- @@ -20,7 +20,12 @@ let%expect_test _ =

-    test_signed ~create (module T);

-    [%expect {|

-      Test Int_types.SInt64

- -    i: -1073741823; i: -2; i: -1; i: 1; i: 2; i: 1073741823; |}]

- +    i: -1073741823;

- +    i: -2;

- +    i: -1;

- +    i: 1;

- +    i: 2;

- +    i: 1073741823; |}]

-  

-  let%expect_test _ =

-    let module T = Int_types.SInt32 in

- @@ -28,7 +33,12 @@ let%expect_test _ =

-    test_signed ~create (module T);

-    [%expect {|

-      Test Int_types.SInt32

- -    i: -1073741823; i: -2; i: -1; i: 1; i: 2; i: 1073741823; |}]

- +    i: -1073741823;

- +    i: -2;

- +    i: -1;

- +    i: 1;

- +    i: 2;

- +    i: 1073741823; |}]

-  

-  let%expect_test _ =

-    let module T = Int_types.Int64 in

- @@ -36,7 +46,12 @@ let%expect_test _ =

-    test_signed ~create (module T);

-    [%expect {|

-      Test Int_types.Int64

- -    i: -1073741823; i: -2; i: -1; i: 1; i: 2; i: 1073741823; |}]

- +    i: -1073741823;

- +    i: -2;

- +    i: -1;

- +    i: 1;

- +    i: 2;

- +    i: 1073741823; |}]

-  

-  let%expect_test _ =

-    let module T = Int_types.Int32 in

- @@ -45,7 +60,12 @@ let%expect_test _ =

-    [%expect

-      {|

-      Test Int_types.Int32

- -    i: -1073741823; i: -2; i: -1; i: 1; i: 2; i: 1073741823; |}]

- +    i: -1073741823;

- +    i: -2;

- +    i: -1;

- +    i: 1;

- +    i: 2;

- +    i: 1073741823; |}]

-  

-  let%expect_test _ =

-    let module T = Int_types.UInt64 in

- @@ -53,7 +73,9 @@ let%expect_test _ =

-    test_unsigned ~create (module T);

-    [%expect {|

-      Test Int_types.UInt64

- -    i: 1; i: 2; i: 2147483647; |}]

- +    i: 1;

- +    i: 2;

- +    i: 2147483647; |}]

-  

-  let%expect_test _ =

-    let module T = Int_types.UInt32 in

- @@ -61,4 +83,6 @@ let%expect_test _ =

-    test_unsigned ~create (module T);

-    [%expect {|

-      Test Int_types.UInt32

- -    i: 1; i: 2; i: 2147483647; |}]

- +    i: 1;

- +    i: 2;

- +    i: 2147483647; |}]

[ERROR] The compilation of ocaml-protoc-plugin failed at

        "/Users/travis/.opam/opam-init/hooks/sandbox.sh build dune runtest -p

        ocaml-protoc-plugin -j 1".
```

**Comment by andersfugmann** [comment]
Unix commands on osx works a bit different. (I'm using `tr`and `sed`) as part of the tests. 

I'm working on a fix for the tests on osx.
Also, I have a patch to limit conf-proto to not install on ubuntu >= 18.04, as 16.04 uses a too old protoc compiler. 

These should make the build go green - i hope.

**Comment by andersfugmann** [comment]
It seems that the CI system is down :-(

**Comment by andersfugmann** [comment]
All green, and ready to merge.

**Comment by kit-ty-kate** [comment]
> Also, I have a patch to limit conf-proto to not install on ubuntu >= 18.04, as 16.04 uses a too old protoc compiler.

Some people my use a different repository for protoc and be still on 16.04 though.
I'll merge for now but I think this restriction is a bit too much. CI doesn't have to be all green all the time.

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
