### PR TITLE
[new release] camyll (0.4.1)

### PR DESCRIPTION
**Pull request by alan-j-hu**
A static site generator

- Project page: <a href="https://alan-j-hu.github.io/camyll">https://alan-j-hu.github.io/camyll</a>

##### CHANGES:

- Upgrade `calendar`, `cmdliner`, and `textmate-language` dependencies and
  replace usage of deprecated `cmdliner` API.
- Catch stray exceptions.
- Support JSON and YAML grammar files.

### CODE REVIEW

**Comment by alan-j-hu** [comment]
I'm concerned because one of my dependencies, lambdasoup, still has not been updated for OCaml 5, which is why the CI is failing. There is a PR to do so at https://github.com/aantron/lambdasoup/pull/51, but the author of the library has not been maintaining his libraries because of a loss of business due to world events: https://discuss.ocaml.org/t/the-future-of-dream/10602/5.

**Comment by kit-ty-kate** [comment]
This should be now fixed in #22417.
I'm concerned about the amount of strict constraints in this package. Is there any chance the upper-bounds and other `=` could be removed?

**Comment by alan-j-hu** [comment]
I am following the SemVer convention that a major version increment means a breaking change, except where the major version is 0, in which a minor version increment means a breaking change.

You can get rid of the upper bounds, provided that you take responsibility for adding the appropriate bound back if any of the dependencies have a major release that causes breakage for my package...

The packages `plist-xml` and `textmate-language` on my own, and since they are major version 0, I plan on incrementing the minor version upon a breaking change. Therefore, their upper bounds should be kept.

From what I can tell, the `omd` package is going through major churn right now. The working version on GitHub already appears to have a very different API than the 2.0 beta version on Opam. The `=` should be kept.

**Comment by kit-ty-kate** [comment]
Thanks. Sorry for the wait. For upper-bound we can see that for next time but SemVer doesn’t mean much for OCaml due to its module system for instance. In opam-repository we do take responsability for all the revdeps when new versions of the packages are released and usually prefer if the new released packages do not have upper-bound constraints so users are not limited in the versions they have to use.

**Pull request merged**
