### PR TITLE
Add Lwt 3.1.0 – concurrency library

### PR DESCRIPTION
**Pull request by aantron**
...providing promises and parallelized I/O.

<br/>

A major goal of this release cycle was making Lwt much easier to work on and contribute to. From the [changelog](https://github.com/ocsigen/lwt/releases/tag/3.1.0):

<br/>

> Additions
>
> - Port to Jbuilder (ocsigen/lwt#374, Andrew Ray).
> - [`Lwt_io.establish_server_with_client_address`](https://ocsigen.org/lwt/dev/api/Lwt_io#VALestablish_server_with_client_address) (ocsigen/lwt#346, Rudi Grinberg).
> - [`Lwt_unix.getcwd`](https://ocsigen.org/lwt/dev/api/Lwt_unix#VALgetcwd) (ocsigen/lwt#403, Raphaël Proust).
>
> Planned to break in 4.0.0
>
> - Delete [`lwt.simple-top`](https://github.com/ocsigen/lwt/blob/615fca15a0cdd6f57a5fc13396f754f77ec1d738/src/simple_top/lwt_simple_top.ml#L22) (ocsigen/lwt#371).
> - Delete [`Lwt_chan`](https://github.com/ocsigen/lwt/blob/615fca15a0cdd6f57a5fc13396f754f77ec1d738/src/unix/lwt_chan.mli#L25) (ocsigen/lwt#441).
>
> Fixes
>
> - Make [`Lwt_log`](https://ocsigen.org/lwt/dev/api/Lwt_log) functions tail-recursive (ocsigen/lwt#348, Jan Doms).
> - Make more of [`Lwt_list`](https://ocsigen.org/lwt/dev/api/Lwt_list) tail-recursive (ocsigen/lwt#347, Jan Doms).
> - Improve string messages in exceptions (ocsigen/lwt#368, ocsigen/lwt#382, Jan Doms, Raphaël Proust).
> - Don't call [`Unix.set_nonblock`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Unix.html#VALset_nonblock) or [`Unix.clear_nonblock`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Unix.html#VALclear_nonblock) unnecessarily on some fds (ocsigen/lwt#356, David Sheets).
> - [`Lwt_unix.sleep`](https://ocsigen.org/lwt/dev/api/Lwt_unix#VALsleep) and [`Lwt_unix.timeout`](https://ocsigen.org/lwt/dev/api/Lwt_unix#VALtimeout) returning too early when using libev (ocsigen/lwt#433, Stijn Devriendt).
> - [`Lwt_sequence.fold_r`](https://ocsigen.org/lwt/dev/api/Lwt_sequence#VALfold_r) iterating the wrong way in some cases (ocsigen/lwt#405, Stijn Devriendt).
> - Build conflicts in some cases due to duplicate `cst_to_constr` function (ocsigen/lwt#362, Jérémie Dimino).
> - Don't use deprecated [`readdir_r`](http://man7.org/linux/man-pages/man3/readdir_r.3.html) system call (ocsigen/lwt#430, Raphaël Proust).
>
> Miscellaneous
>
> - The Lwt core, [`lwt.ml`](https://github.com/ocsigen/lwt/blob/615fca15a0cdd6f57a5fc13396f754f77ec1d738/src/core/lwt.ml#L27), has been thoroughly refactored and commented (ocsigen/lwt#354, reviewed Gabriel Radanne, Edwin Török, Raphaël Proust, Jan Doms, Fabian Hemmer, Sebastien Mondet, Simon Cruanes, Anil Madhavapeddy, Pierre Chambart, and many others).
> - Lots of [tests](https://github.com/ocsigen/lwt/tree/615fca15a0cdd6f57a5fc13396f754f77ec1d738/test/core) for most of the Lwt core (ocsigen/lwt#339, ocsigen/lwt#389, ocsigen/lwt#392, ocsigen/lwt#440, ocsigen/lwt#448, ocsigen/lwt#450, Joseph Thomas, Ryan Slade).
> - Documentation fixes (including by Joseph Thomas, Raphaël Proust, Richard Degenne, Stavros Polymenis).
> - [Contributing documentation](https://github.com/ocsigen/lwt/tree/615fca15a0cdd6f57a5fc13396f754f77ec1d738#contributing) (ocsigen/lwt#379).
> - Massively adjust whitespace for legibility (ocsigen/lwt#400, ocsigen/lwt#409, ocsigen/lwt#416, Richard Degenne).
> - Improvements to CI (Etienne Millon, Raphael Rafatpanah, Zack Coker, Yotam Barnoy).
> - The additional packages [`lwt_ssl`](http://opam.ocaml.org/packages/lwt_ssl/), [`lwt_react`](http://opam.ocaml.org/packages/lwt_react/), [`lwt_glib`](http://opam.ocaml.org/packages/lwt_glib/) get new minor releases, the change being new Jbuilder build systems (ocsigen/lwt#374, Andrew Ray).

### CODE REVIEW

**Comment by avsm** [comment]
This broadly looks fine to me except for an upper bound added in https://github.com/ocaml/opam-repository/pull/9881. Remarkably good lack of breakage for a massive build system port!

**Comment by aantron** [comment]
Actually, we need to address this. I'll post more details shortly. Please don't merge this.

**Comment by aantron** [comment]
Details in https://github.com/ocsigen/lwt/issues/456.

Please submit any other reviews that can be done now, so we can avoid re-tagging Lwt 3.1.0 multiple times :)

**Comment by aantron** [comment]
Alright, as I commented in the issue, I decided not to fix it on the Lwt end – it involves some pretty big transformations of the installation and Lwt source structure, for a type of breakage that is hopefully rare, based on a usage we never supported.

**Comment by aantron** [comment]
And I will include information about this in the release announcements. If this seriously affects someone, they will have a link to the issue to follow. Otherwise, this simply does to the installation now what we will do later anyway.

If there are no other notes, I think this can be merged.

**Comment by samoht** [comment]
Thanks for that new release!

**Comment by aantron** [comment]
Thanks. I'll send out announcements on Monday.

**Pull request merged**
