### PR TITLE
Coq 8.13.0

### PR DESCRIPTION
**Pull request by gares**
CC @erikmd coq/coq#12334

### CODE REVIEW

**Comment by gares** [comment]
It seems oraclelinux does not have a working gtksourceview, should I rule it out or ignore the error?

**Comment by gares** [comment]
I've just seen:
```
x-ci-accept-failures: [
  "oraclelinux-7"
  "oraclelinux-8"
]
```
Do you want me to add it?

**Comment by kit-ty-kate** [comment]
> I've just found out:
> 
> ```
> x-ci-accept-failures: [
>   "oraclelinux-7"
>   "oraclelinux-8"
> ]
> ```
> 
> Do you want me to add it?

I've just gone ahead and done that, along with a rebase as Camelus has trouble finding zarith.1.10 on your local branch.

**Comment by kit-ty-kate** [comment]
All green. Thanks a lot!

**Comment by gares** [comment]
One hour passed and I still don't see the package online. It is normal?

**Comment by kit-ty-kate** [comment]
Mh probably. The [opam.ocaml.org/lastlog.txt](https://opam.ocaml.org/lastlog.txt) says update was last done 4 hours ago. I believe it's done every 4/5 hours (@AltGr ?)

**Comment by kit-ty-kate** [comment]
@gares If I understand the setup correctly (I'm not the one maintaining this), the coq package should land around 19:00 UTC.

**Pull request merged**
