### PR TITLE
conf-libsvm: add support for Ubuntu family and FreeBSD

### PR DESCRIPTION
**Pull request by jmid**
FreeBSD package: https://www.freshports.org/science/libsvm/

### CODE REVIEW

**Comment by jmid** [comment]
CI fails on Alpine, OpenSuse, Oracle, FreeBSD, and macOS
The first 3 are natural, as there is no current attempt to support them.
FreeBSD and macOS fails to find the svm.h header.

**Comment by jmid** [comment]
- fea0fff should add OpenSuse support whereas
- d9fd138 marks Alpine and Oracle as acceptable CI failures
- 4f5c33c and 1a804a5 add include paths on FreeBSD and macOS

**Comment by jmid** [comment]
CI was failing the file hash check. b9cf173 updates the md5sum accordingly.

**Comment by mseri** [comment]
Seems to be still failing on macos ARM and freebsd

**Comment by jmid** [comment]
Thanks.
Despite the red lights, there's progress: now both FreeBSD and macOS found the header and are instead complaining about not finding the library. 59ab3c9 therefore sets a library path.

**Comment by jmid** [comment]
This is now all green, modulo opam lint warnings about package name clashes.
It should be good to go.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
