### PR TITLE
3 packages from gitlab.inria.fr/fpottier/menhir/-/archive/20211230/archive.tar.gz

### PR DESCRIPTION
**Pull request by fpottier**
This pull-request concerns:
-`menhir.20211230`: An LR(1) parser generator
-`menhirLib.20211230`: Runtime support library for parsers generated by Menhir
-`menhirSdk.20211230`: Compile-time library for auxiliary tools related to
 Menhir

---
* Homepage: http://gitlab.inria.fr/fpottier/menhir
* Source repo: git+https://gitlab.inria.fr/fpottier/menhir.git
* Bug tracker: https://gitlab.inria.fr/fpottier/menhir/-/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mseri** [comment]
Fixes from the other PR are cherry picked and merged already :)

**Comment by fpottier** [comment]
Thanks!

**Comment by kit-ty-kate** [comment]
I’m sure we’ve missed some packages but we can fix them later, let’s not delay the release any longer. Thanks!

**Comment by fpottier** [comment]
Thanks!

**Pull request merged**
