### PR TITLE
Mirage 3.0.2

### PR DESCRIPTION
**Pull request by yomimono**
/cc @hannesm

### CODE REVIEW

**Comment by hannesm** [comment]
thank you so much.  I don't think, 3.0.1 needs to land in opam-repository.

**Comment by avsm** [comment]
>  I don't think 3.0.1 needs to land in opam-repository

Why not?

**Comment by hannesm** [comment]
@avsm since 3.0.2 is a minor improvement, and there's no reason for anyone to get 3.0.1 imho.

**Comment by avsm** [comment]
I'd prefer all of the releases to be in OPAM if possible -- users will naturally get the latest one in any case, but it's useful to be consistent with our releases for the purposes of bulk builds, etc

**Pull request merged**
