### PR TITLE
Add Z3 package

### PR DESCRIPTION
**Pull request by zkincaid**
OPAM package for Microsoft's Z3 SMT solver.

### CODE REVIEW

**Comment by Drup** [comment]
Huh, as far as I understand, redistributing Z3 is again their license. I wanted to provide an opam package, and they said no.

**Comment by Drup** [comment]
Also, does this opam package really works ? It will compile a z3 locally, install the ocaml part and throw it out of the window. When you compile the ocaml part, it will try to link against the system installed z3, which will probably not be compatible with the ml-ng branch.

**Comment by zkincaid** [comment]
@Drup [Z3's license](http://z3.codeplex.com/license) allows redistribution for non-commercial purposes.  But anyway, the package downloads the source code directly from codeplex, thereby avoiding redistribution (in the same way that, e.g., Ubuntu's package for Oracle Java does, since redistributing Java *is* against its license).

The package installs libz3.so into Opam's /lib/stublibs/.  As long as the linker finds this directory before your system installation, everything will work out.  I think this is reasonable: if the system already has an installed libz3.so which is incompatible with the ml-ng branch, we certainly don't want to over-write it.

**Comment by Drup** [comment]
I was basing my remark on [this discussion](https://z3.codeplex.com/discussions/473552). 4th message. But I suppose "download from codeplex directly" works. My license-fu is really bad, so I'm going to believe you.

Huum, ok. I may have tried it before the last fixes, where you couldn't do this kind of partial installation. I will try again. This would allow me to opamize [this](https://github.com/Drup/ocaml-z3) too, which I would really like! :)

**Comment by Drup** [comment]
You may want to replace "python" by "python2".

**Comment by avsm** [comment]
Z3 is now on GitHub and opensource.

**Comment by Drup** [comment]
Welp, I guess I need to find time to contribute my overlay back now. :)

**Comment by UnixJunkie** [comment]
@zkincaid the Travis continuous integration tests are all in failure cf.
https://travis-ci.org/ocaml/opam-repository/builds/45281110
the package will not be accepted into opam until they almost all pass

**Comment by Drup** [comment]
That's not the real issue. The ml-ng bindings (which are new ocaml bindings) are in the unstable branch but not in a release just yet, and the opam-repository doesn't accept git repo. Just wait for a release of Z3.

**Comment by zkincaid** [comment]
@Drup Changed to extdep to python2.  While we wait for an official release of Z3, I created a snapshot.
@avsm Using a tarball now that Z3 allows redistribution.

**Comment by Drup** [comment]
Please see https://github.com/ocaml/opam-repository/pull/3926#issuecomment-93695601

Also, you should use the package conf-python2.7, not an explicit depext.

**Comment by zkincaid** [comment]
@Drup The issue you solved using LD_LIBRARY_PATH can also be fixed by using "-ccopt -Wl,-rpath'path/to/stublibs" when linking with Z3, but I agree that it's not a very good solution.  I updated the Z3 snapshot to set rpath appropriately when compiling z3ml.cmxa.  Toplevel/bytecode are still broken, but I think it's better than nothing.

**Comment by Drup** [comment]
Ah, that's probably a more reliable solution, thanks.

And yeah, it's still quite broken. :(

**Comment by UnixJunkie** [comment]
it's all green except for mac

**Comment by ivg** [comment]
What is the state of this PR, will it merged or there are still some obstacles?

**Comment by Drup** [comment]
Everything @zkincaid and I said about how broken the Z3 ocaml package is still stand. If you want to ask them to fix it, go [there](https://github.com/Z3Prover/z3/issues/34).

I personally don't understand their build system. I tried to fix it myself but couldn't.

**Comment by zkincaid** [comment]
@ivg Toplevel and bytecode are broken, but the native library works fine (at least, on linux).  I think that's valuable enough, and if/when the Z3 fix these issues the package can be updated. 
@UnixJunkie Sorry, I don't have access to a mac to diagnose what's happening there...

**Comment by samoht** [comment]
Merging as it seems good enough. Improvement are welcome :-)

**Comment by samoht** [comment]
Reverting as @Drup had some concerns (especially regarding the custom patch applied on the upstream sources). I'm happy to merge a `z3` package which will make everyone happy if someone proposes a better package.

**Comment by Drup** [comment]
@zkincaid The usual policy on opam is "no dev version". The current package is based on a snapshot of unstable. 

I didn't saw you had a custom patch before. Please contribute your patch back to Z3, then we can add the next release containing it in opam.

**Pull request merged**
