### PR TITLE
Configuration package for zstd

### PR DESCRIPTION
**Pull request by xclerc**
We have pushed a library depending on zstd [here](https://github.com/janestreet/zstandard), but
I was told that it would be better to have a configuration
package rather than embed the external dependencies
in the [opam file](https://github.com/janestreet/zstandard/blob/master/zstandard.opam).

(If this package is deemed correct / useful, I will then open
another pull request to make [other packages](https://github.com/ocaml/opam-repository/tree/master/packages/zstd) depending
on `zstd` use this configuration package.)

### CODE REVIEW

**Comment by xclerc** [comment]
Looks like the package name was wrong for Fedora/CentOS;
just pushed a tentative fix.

**Comment by kit-ty-kate** [comment]
Is there no ways of testing if the library is indeed installed, using pkg-config for instance?

**Comment by kit-ty-kate** [comment]
The problem on macos seems related to the homebrew package. Merging. Thanks!

**Comment by xclerc** [comment]
Great; thanks!

I have just opened https://github.com/ocaml/opam-repository/pull/13303 to patch the dependencies
of the packages mentioned in my first message.

**Pull request merged**
