### PR TITLE
Package ladspa.0.2.0

### PR DESCRIPTION
**Pull request by toots**
### `ladspa.0.2.0`
Bindings for the LADSPA API which provides audio effects

---
* Homepage: https://github.com/savonet/ocaml-ladspa
* Source repo: git+https://github.com/savonet/ocaml-ladspa.git
* Bug tracker: https://github.com/savonet/ocaml-ladspa/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by toots** [comment]
This one is a bit tricky: LADSPA is basically just a header so I'm not sure how to compile `conf-ladspa`. Couple of notes:
* We could embed the header but it is versioned so it's better not to.
* We could detect manually the header but that implies a lot of assumption regarding the compiler
* We could re-implement the `dune-configurator` detection in `conf-ladspa`
* We could just do nothing

`ladspa` is kind of a niche package so I'm tempted to leave it as-is (last option). I might consider embedding a default version of the header in a future version of the module, to be used in case no system header can be detected and call it a day.

Let me know what y'all think..

**Comment by toots** [comment]
Hmm old on, I didn't see that we need to export a head for `dssi` when migrating to `dune`. I'll do a re-released with the default `ladspa.h` header embedded as proposed above.

**Comment by toots** [comment]
Ok, the release now installs the right headers, including a local copy of `ladspa.h`, used when no header could be found in the system. Also, `dssi` needs a proper release to support this new version.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
