### PR TITLE
[new release] conduit-lwt-tls, conduit-mirage, conduit-tls, conduit-lwt, conduit-async-tls, conduit-async, conduit, conduit-async-ssl and conduit-lwt-ssl (3.0.0)

### PR DESCRIPTION
**Pull request by dinosaure**
A portable network connection establishment library using Lwt and ocaml-tls

- Project page: <a href="https://github.com/mirage/ocaml-conduit">https://github.com/mirage/ocaml-conduit</a>

##### CHANGES:

* **breaking change** - New version of `conduit`. Most of the new API has a
  description on the pull-request
  [mirage/ocaml-conduit#311](https://github.com/mirage/ocaml-conduit/pull/311). Documentation is
  updated as well with a small HOW-TO (available
  [here](https://mirage.github.io/ocaml-conduit/conduit/howto.html)) which
  describes the new API.

### CODE REVIEW

**Comment by dinosaure** [comment]
Redo #17417.

**Comment by mseri** [comment]
Now that there are no-longer revdeps, due to the upper bounds everywhere, the only thing that needs to be checked is that `conduit-*` builds also on ocaml `4.07` (which is not tested in the conduit CI). If that is the case (I have not tried, and cannot at the moment) should we merge and release the ocaml CI?

**Comment by dinosaure** [comment]
> Now that there are no-longer revdeps, due to the upper bounds everywhere, the only thing that needs to be checked is that conduit-* builds also on ocaml 4.07 (which is not tested in the conduit CI). If that is the case (I have not tried, and cannot at the moment) should we merge and release the ocaml CI?

I'm not sure, as far as I can tell, all should works - build & tests work. So I will happy to definitely merge it (and unlock several PR). May be @kit-ty-kate has some clue about the state of the CI?

**Comment by mseri** [comment]
It’s all green!

**Pull request merged**
