### PR TITLE
ibx does not work with latest core

### PR DESCRIPTION
**Pull request by planar**

### CODE REVIEW

**Comment by avsm** [comment]
This needs an extra `quickcheck` depends as well.

**Comment by planar** [comment]
Are you sure? On my machine it compiles OK without `quickcheck`.

**Comment by avsm** [comment]
https://travis-ci.org/ocaml/opam-repository/jobs/51104072#L624

**Comment by planar** [comment]
Aha! `ibx.0.7.4` works fine without `quickcheck`.
`ibx.0.7.3`, on the other hand, needs a `Quickcheck` module, which is not provided by any of the following:
- `quickcheck`
- `qcheck`
- `batteries`
- `qtest`
- `core`

Now I'm at a loss because I'm pretty sure I managed to compile `ibx.0.7.3` at some point, but I haven't recorded the full context, so I don't know which package might provide `Quickcheck`.

**Comment by avsm** [comment]
Odd -- here is the original passing Travis for ibx.0.7.3: https://travis-ci.org/ocaml/opam-repository/jobs/28518890#L254

No quickcheck in sight there either...

**Comment by planar** [comment]
OK, I found it.

`Quickcheck` is provided by `core` in versions before 111.25.00, and by `core_extended` since 111.25.00.

`ibx.0.7.3` looks for it in `Core.Std` so it's incompatible with `core` >= 111.25.00.

**Comment by planar** [comment]
PS. Do not confuse the modules `Quickcheck` (provided by package `core_extended`) and `QuickCheck` (provided by package `quickcheck`)!

**Comment by avsm** [comment]
Thanks for tracking this down -- the only test failure was a timeout due to Core, so merging.

**Pull request merged**
