### PR TITLE
[new release] bwrap (0.1)

### PR DESCRIPTION
**Pull request by Chris00**
Use Bubblewrap to sandbox executables

- Project page: <a href="https://github.com/Chris00/ocaml-bwrap">https://github.com/Chris00/ocaml-bwrap</a>
- Documentation: <a href="https://Chris00.github.io/ocaml-bwrap/doc">https://Chris00.github.io/ocaml-bwrap/doc</a>

##### CHANGES:

- Initial release.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I fixed the issue with the tests. They won't be run as `with-test` is not set inside the `run-test` field.

I'm going to wait for the CI to finish and merge it afterwards

**Comment by Chris00** [comment]
> They won't be run as with-test is not set inside the run-test field.

Thanks.  But shouldn't `["dune" "runtest" "-p" name "-j" jobs]` stay inside `run-test`?

**Comment by Chris00** [comment]
Note that the documentation should be corrected [as it says](https://opam.ocaml.org/doc/Manual.html#Package-variables):

> Additionally, the following are limited to some package fields (depends:, depopts:, build:, install:, remove:, run-test:):
>
>    with-test: only true if tests have been enabled for this specific package
>    with-doc: similarly for documentation

**Comment by Chris00** [comment]
I have left the tests within `run-test` and marked the package Linux-only.

**Comment by Chris00** [comment]
Seems the tests are not run... but it seems to me that it is the right place to put the test instructions.

**Comment by Chris00** [comment]
Travis CI: note that, when a package is not marked available on a platform, the build should quit immediately.

**Comment by Chris00** [comment]
Correction: the tests are run on Travis — but not on ci/datakit.

**Comment by Chris00** [comment]
The tests fail on Travis because the bubblewrap package is at version 0.1.7 while the current one is 0.3.1.

**Comment by Chris00** [comment]
Well, option `--die-with-parent` is neither supported by old bwrap versions... :-(

**Comment by mseri** [comment]
The tests are failing in Travis, but I think this has to be expected:
```
- No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl  kernel.unprivileged_userns_clone=1'.
```

For what concerns me this could be merged. @Chris00 are you happy with it?

**Comment by Chris00** [comment]
> The tests are failing in Travis, but I think this has to be expected:

Yes, there is nothing I can do about this.  For me it is good to merge.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
