### PR TITLE
Release Alt-Ergo 2.3.1 (all packages)

### PR DESCRIPTION
**Pull request by OCamlPro-Coquera**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There is an issue while downloading the archive:
```
ERROR: The certificate of ‘alt-ergo.ocamlpro.com’ is not trusted.
ERROR: The certificate of ‘alt-ergo.ocamlpro.com’ has expired.
The certificate has expired
```

**Comment by kit-ty-kate** [comment]
Also dune should be constrain in each packages to `{>= "1.5"}` and each `{ = "2.3.0" }` should be change to `{ = version }`

**Comment by OCamlPro-Coquera** [comment]
> There is an issue while downloading the archive:
> 
> ```
> ERROR: The certificate of ‘alt-ergo.ocamlpro.com’ is not trusted.
> ERROR: The certificate of ‘alt-ergo.ocamlpro.com’ has expired.
> The certificate has expired
> ```

This should be good now.

**Comment by OCamlPro-Coquera** [comment]
> Also dune should be constrain in each packages to `{>= "1.5"}` and each `{ = "2.3.0" }` should be change to `{ = version }`

Thanks, this changes has been fix (https://github.com/OCamlPro/alt-ergo/commit/2147f8ca82c155574bfabb06850e022908928ac3)

**Comment by OCamlPro-Coquera** [comment]
The Travis CI Build failed but it seems that the failing is not related with this PR.

```
==> Pouring python-3.7.6_1.high_sierra.bottle.tar.gz

Error: The `brew link` step did not complete successfully

The formula built, but is not symlinked into /usr/local

Could not symlink Frameworks/Python.framework/Headers

Target /usr/local/Frameworks/Python.framework/Headers

is a symlink belonging to python@2. You can unlink it:

  brew unlink python@2

To force the link and overwrite all conflicting files:

  brew link --overwrite python

To list all files that would be deleted:

  brew link --overwrite --dry-run python

Possible conflicting files are:

/usr/local/Frameworks/Python.framework/Headers -> /usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Headers

/usr/local/Frameworks/Python.framework/Python -> /usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Python

/usr/local/Frameworks/Python.framework/Resources -> /usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Resources

/usr/local/Frameworks/Python.framework/Versions/Current -> /usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/Current
```

**Comment by OCamlPro-Coquera** [comment]
@kit-ty-kate the revdeps build seems to failed due to why3 an menhir compilation not Alt-Ergo

```
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
# Ocamlc   src/util/number.ml
# Ocamlc   src/session/xml.ml
# File "_none_", line 1:
# Error: Cannot find file menhirLib.cmo
# Ocamlc   src/util/wstdlib.mli
# make: *** [Makefile:2234: bin/why3wc.byte] Error 2
# make: *** Waiting for unfinished jobs....
# Ocamlc   src/util/plugin.mli
```

**Comment by OCamlPro-Coquera** [comment]
What do i need to do to make this PR pass all tests ?

**Comment by kit-ty-kate** [comment]
> > Also dune should be constrain in each packages to `{>= "1.5"}` and each `{ = "2.3.0" }` should be change to `{ = version }`
> 
> Thanks, this changes has been fix ([OCamlPro/alt-ergo@2147f8c](https://github.com/OCamlPro/alt-ergo/commit/2147f8ca82c155574bfabb06850e022908928ac3))

For the record the commit isn't on master and dune is tagged as a build dependency (it shouldn't be the case, see #14266)

**Comment by kit-ty-kate** [comment]
This should be good now. Thanks

**Comment by OCamlPro-Coquera** [comment]
> > > Also dune should be constrain in each packages to `{>= "1.5"}` and each `{ = "2.3.0" }` should be change to `{ = version }`
> > 
> > 
> > Thanks, this changes has been fix ([OCamlPro/alt-ergo@2147f8c](https://github.com/OCamlPro/alt-ergo/commit/2147f8ca82c155574bfabb06850e022908928ac3))
> 
> For the record the commit isn't on master and dune is tagged as a build dependency (it shouldn't be the case, see #14266)

Thanks @kit-ty-kate. I forgot to remove the build tag of dune, this will be fix for the next release. The commit will also be add to the master branch

**Pull request merged**
