### PR TITLE
datakit-ci: 0.12 still uses Cohttp_lwt_body so constrain it

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by rgrinberg** [comment]
If datakit still uses Cohttp_lwt_body, then shouldn't it have cohttp as a dependency somewhere?

**Comment by avsm** [comment]
I was wondering about that -- it's pulled in indirectly via datakit, and the conflict here is sufficient to ensure that the right version is selected.  Not sure which style is better to use -- explicit dependencies or indirect with conflicts like this.

**Comment by rgrinberg** [comment]
I think relying on transitive dependencies is bad and the offender here is datakit-ci because it doesn't include cohttp-lwt as a dependency. So that's where the constraint should go.

**Comment by jpdeplaix** [comment]
Closing, as #11268 has been merged.

**Pull request closed without merging**
