### PR TITLE
[new release] mindstorm and mindstorm-lwt (0.8)

### PR DESCRIPTION
**Pull request by Chris00**
CHANGES:

- In addition to the package `mindstorm`, a version of the interface
  using LWT promises has been developed in the package `mindstorm-lwt`.
- LWT: transactions with the LEGO© brick are atomic.
- Use [dune][] and `dune.configurator`.
- Improve the documentation

[dune]: https://github.com/ocaml/dune

### CODE REVIEW

**Comment by Chris00** [comment]
`bluetooth/bluetooth.h` is missing on opensuse.

**Comment by Chris00** [comment]
I do not understand why given that `bluez-devel` is [supposed to provide `bluetooth/bluetooth.h`](http://www.rpmfind.net/linux/rpm2html/search.php?query=%2Fusr%2Finclude%2Fbluetooth%2Fbluetooth.h&submit=Search+...&system=&arch=)

**Comment by mseri** [comment]
It's not the first time I see this kind of errors on opensuse. It would be useful to have a look at pkg-config output to see if we need additional flags in that case

**Comment by mseri** [comment]
I would not consider this a reason not to merge unless the fix is immediate

**Comment by kit-ty-kate** [comment]
That should fix the issue. That said, it would be a lot better with a conf-libbluez or something like that to avoid redundancy.

**Comment by mseri** [comment]
I keep forgetting about that difference for suse... we should probably write down clearly these subtleties somewhere visible (maybe even a secion on the opam manual)

**Comment by Chris00** [comment]
>  it would be a lot better with a conf-libbluez or something like that 

Sure.  Will try to set up one now.

**Comment by Chris00** [comment]
Once [conf-bluetooth](https://github.com/ocaml/opam-repository/pull/13708) is merged, I'll update this PR.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
