### PR TITLE
Fix sexplib deps

### PR DESCRIPTION
**Pull request by trefis**
Targets the same problem as #3841 but by pointing to fresh packages which don't depend on camlp4 anymore.

This is complementary to @yallop's patch, as the old packages are still broken with this PR.

### CODE REVIEW

**Comment by yallop** [comment]
It's [failing](https://travis-ci.org/ocaml/opam-repository/jobs/56132999) with an oasis issue::

```
# ocamlfind: Package `oasis.dynrun' not found
# ocamlfind: Package `oasis.dynrun' not found
# make: ./setup-dev.exe: Command not found
# make: *** [setup.data] Error 127
```

**Comment by trefis** [comment]
Indeed.
It should be ok now.

**Comment by yallop** [comment]
Building these new versions still seems to require Camlp4.  The problem doesn't show up on Travis, since the Travis build installs the system Camlp4 package. 

```
#=== ERROR while installing sexplib.112.24.01 =================================#
# opam-version 1.2.1~rc2
# os           linux
# command      ./configure --disable-syntax
# path         /home/jeremy/.opam/4.02.1/build/sexplib.112.24.01
# compiler     4.02.1
# exit-code    1
# env-file     /home/jeremy/.opam/4.02.1/build/sexplib.112.24.01/sexplib-413-d2c37b.env
# stdout-file  /home/jeremy/.opam/4.02.1/build/sexplib.112.24.01/sexplib-413-d2c37b.out
# stderr-file  /home/jeremy/.opam/4.02.1/build/sexplib.112.24.01/sexplib-413-d2c37b.err
### stderr ###
# W: Field 'camlp4o' is not set
# W: Not_found
# W: Not_found
# W: Not_found
# E: Cannot find external tool 'camlp4o'
# E: Failure("1 configuration error")
```

**Comment by trefis** [comment]
I missed one last reference to camlp4o in the _oasis...
This should be fixed now.

**Comment by yallop** [comment]
Thanks.

**Comment by trefis** [comment]
Thank you!

**Comment by Chris00** [comment]
@trefis Do you know you can use `oasis2opam` to make this conversion automatically?

**Pull request merged**
