### PR TITLE
Update ocaml-base-compiler.4.12.1 patch checksum

### LINKED ISSUE #23837: ocaml-base-compiler.4.12.1 patch checksum failure
The current version of ocaml-base-compiler.4.12.1 includes a patch:
https://github.com/ocaml/opam-repository/blob/6f37a6497de62e643857448205c9c201be3fac86/packages/ocaml-base-compiler/ocaml-base-compiler.4.12.1/opam#L45-L48

However, I'm experiencing that the patch returned by GitHub has a different checksum, causing the installation to fail:
```
  Processing 15/21: [ocaml-base-compiler.4.12.1/alt-signal-stack.patch: dl]
  [ERROR] Failed to get extra source "alt-signal-stack.patch" of ocaml-base-compiler.4.12.1: Bad checksum
  
  #=== ERROR while fetching sources for ocaml-base-compiler.4.12.1 ==============#
  OpamSolution.Fetch_fail("https://github.com/ocaml/ocaml/commit/1eeb0e7fe595f5f9e1ea1edbdf785ff3b49feeeb.patch (Bad checksum, expected sha256=59de25b95409c1927c4b607fb4b1218ff7623fca45474448c8e114a42853e3ad)")
```
Full CI log: https://github.com/ocaml-multicore/multicoretests/actions/runs/5120472416/jobs/9207007897

A manual HTTP request confirms the behaviour:
```
$ wget https://github.com/ocaml/ocaml/commit/1eeb0e7fe595f5f9e1ea1edbdf785ff3b49feeeb.patch
--2023-05-30 16:44:39--  https://github.com/ocaml/ocaml/commit/1eeb0e7fe595f5f9e1ea1edbdf785ff3b49feeeb.patch
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7757 (7.6K) [text/plain]
Saving to: ‘1eeb0e7fe595f5f9e1ea1edbdf785ff3b49feeeb.patch’

1eeb0e7fe595f5f9e1ea1edbdf785ff3b49feeeb.patch    100%[============================================================================================================>]   7.58K  --.-KB/s    in 0s      

2023-05-30 16:44:39 (37.1 MB/s) - ‘1eeb0e7fe595f5f9e1ea1edbdf785ff3b49feeeb.patch’ saved [7757/7757]

$ sha256sum 1eeb0e7fe595f5f9e1ea1edbdf785ff3b49feeeb.patch 
646ce670778b159759128d42d1c9d1acbd4f4492b291991e49807317168c1f16  1eeb0e7fe595f5f9e1ea1edbdf785ff3b49feeeb.patch

```

### PR DESCRIPTION
**Pull request by jmid**
PR to fix #23837

### CODE REVIEW

**Comment by mseri** [comment]
@avsm do you know why/how it changed? I think we should move the file here instead of downloading it each time. What do you think?

**Comment by avsm** [comment]
The only thing I can think of here is some CR/LF change. How can the checksum change on a fixed commit otherwise?!  We ought to pull this out of an older repo archive and see if we can find the older checksum file to compare them.

**Comment by jmid** [comment]
I've scanned my drive and unfortunately don't have an old patch file to compare against.

Digging a bit, it seems GitHub sometimes accidentally break the shasum of tar.gz files - most recently within the last two weeks: https://github.com/orgs/community/discussions/45830

**Comment by Keryan-dev** [comment]
I have one artefact of a similar patch file, here's a diff excerpt:
```diff
@@ -24,7 +24,7 @@
  5 files changed, 95 insertions(+), 13 deletions(-)

 diff --git a/otherlibs/systhreads/st_stubs.c b/otherlibs/systhreads/st_stubs.c
-index 285466edbb7..30b6680a37e 100644
+index 285466edbb78..30b6680a37ec 100644
 --- a/otherlibs/systhreads/st_stubs.c
 +++ b/otherlibs/systhreads/st_stubs.c
```

**Pull request closed without merging**
