### PR TITLE
Package mm.0.7.0

### PR DESCRIPTION
**Pull request by toots**
### `mm.0.7.0`
The mm library contains high-level to create and manipulate multimedia streams (audio, video, MIDI)

---
* Homepage: https://github.com/savonet/ocaml-mm
* Source repo: git+https://github.com/savonet/ocaml-mm.git
* Bug tracker: https://github.com/savonet/ocaml-mm/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by toots** [comment]
As far as I can tell, the missing header in `alpine` is part of `musl-dev`. I don't think `mm` should be in charge of pulling this depext. Maybe something missing the test environment setup?

**Comment by kit-ty-kate** [comment]
> As far as I can tell, the missing header in `alpine` is part of `musl-dev`. I don't think `mm` should be in charge of pulling this depext. Maybe something missing the test environment setup?

I've fixed the issue. Other packages (core, …) fix this by adding this depexts only on alpine.
On top of that there was an issue with the depopts. Constraints should almost never placed in the depopts field and placed in the conflicts field instead (the behaviour is different)

Could you return the fix upstream?

**Comment by kit-ty-kate** [comment]
All green now. Thanks!

**Comment by toots** [comment]
Fixes backported, thanks so much for your help on this!

**Pull request merged**
