### PR TITLE
Savonet's packages updates..

### PR DESCRIPTION
**Pull request by toots**
Update from savonet, includes moving source URLs from sourceforge to github...

### CODE REVIEW

**Comment by yallop** [comment]
Could you please 
* add the missing `bug-reports` and `dev-repo` fields (e.g. https://github.com/savonet/ocaml-aacplus/issues and  https://github.com/savonet/ocaml-aacplus.gitfor `aacplus`)
* change the homepage URL to the project homepage (e.g. https://github.com/savonet/ocaml-aacplus for `aacplus`)
* rebase against the master branch (to pick up the latest Travis changes)

then force-push the changes to the same branch (`toots:savonet-modules`)?

**Comment by yallop** [comment]
Actually, opening a new pull request is more likely to persuade Travis to pick up the changes.

**Comment by yallop** [comment]
All the packages up to `gstreamer` are building successfully.  The `gstreamer` build fails with

```
# configure: error: gstreamer-1.0.pc not found.. Do you need to set PKG_CONFIG_PATH?
```

perhaps because the [depext](https://github.com/ocaml/opam-repository/pull/4631/files#diff-e49b7f89a80230a52a909383492fa8e4R16) has:

```
  [["ubuntu"] ["libgstreamer0.10-dev"]]
```

but the [configure script](https://github.com/savonet/ocaml-gstreamer/blob/0.2.1/configure.ac#L9) is looking for

```
```

**Comment by yallop** [comment]
It's looking better, but some of the jobs ([e](https://travis-ci.org/ocaml/opam-repository/jobs/75834625).[g](https://travis-ci.org/ocaml/opam-repository/jobs/75834626).) are running into Travis's 50-minute limit.

**Comment by toots** [comment]
Yeah but also some of them have failed on installing dependencies for `voaacenc`:

```
Not running as root, the following command will be run through "sudo":
    apt-get install -qq -yy camlidl libvo-aacenc-dev
E: Unable to correct problems, you have held broken packages.
opam-depext: internal error, uncaught exception:
             Failure("OS package installation failed")
```

Will kick a new one, let's hope it works better..

**Comment by toots** [comment]
Okay, 4 out of the 6 required passed. Remaining two timed out. OSX test failed due to aacplus extdep. Don't think there's much more that we can do, looks like the packages are fine though.

**Comment by yallop** [comment]
Ok, I'm going to merge this.  Thank you for all the updates!

Next time It might be faster to submit separate pull requests for each package, avoiding both the Travis timeouts and the need to retest all the packages with every change.  Separate pull requests will also give us better information about which packages can be built successfully on OS X.

**Comment by toots** [comment]
:+1: Thanks for you patience too.

**Comment by samoht** [comment]
Hum:

```
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/aacplus/aacplus.0.2.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/alsa/alsa.0.2.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/bjack/bjack.0.1.5/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/cry/cry.0.3.0/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/dssi/dssi.0.1.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/dtools/dtools.0.3.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/duppy/duppy.0.5.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/faad/faad.0.3.3/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/ffmpeg/ffmpeg.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/flac/flac.0.1.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/frei0r/frei0r.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/gavl/gavl.0.1.6/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/gstreamer/gstreamer.0.2.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/ladspa/ladspa.0.1.5/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/lame/lame.0.3.3/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/lastfm/lastfm.0.3.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/lo/lo.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/mad/mad.0.4.5/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/mm/mm.0.3.0/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/ogg/ogg.0.5.0/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/opus/opus.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/portaudio/portaudio.0.2.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/pulseaudio/pulseaudio.0.1.3/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/samplerate/samplerate.0.1.3/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/schroedinger/schroedinger.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/soundtouch/soundtouch.0.1.8/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/speex/speex.0.2.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/taglib/taglib.0.3.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/theora/theora.0.3.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/voaacenc/voaacenc.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/vorbis/vorbis.0.6.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/xmlplaylist/xmlplaylist.0.1.4/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/aacplus/aacplus.0.2.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/alsa/alsa.0.2.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/bjack/bjack.0.1.5/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/cry/cry.0.3.0/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/dssi/dssi.0.1.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/dtools/dtools.0.3.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/duppy/duppy.0.5.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/faad/faad.0.3.3/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/ffmpeg/ffmpeg.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/flac/flac.0.1.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/frei0r/frei0r.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/gavl/gavl.0.1.6/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/gstreamer/gstreamer.0.2.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/ladspa/ladspa.0.1.5/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/lame/lame.0.3.3/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/lastfm/lastfm.0.3.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/lo/lo.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/mad/mad.0.4.5/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/mm/mm.0.3.0/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/ogg/ogg.0.5.0/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/opus/opus.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/portaudio/portaudio.0.2.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/pulseaudio/pulseaudio.0.1.3/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/samplerate/samplerate.0.1.3/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/schroedinger/schroedinger.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/soundtouch/soundtouch.0.1.8/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/speex/speex.0.2.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/taglib/taglib.0.3.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/theora/theora.0.3.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/voaacenc/voaacenc.0.1.1/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/vorbis/vorbis.0.6.2/url.
[WARNING] md5 is an unknown field in /home/travis/.opam/repo/default/packages/xmlplaylist/xmlplaylist.0.1.4/url.
```

**Comment by yallop** [comment]
I'll patch them up.

**Pull request merged**
