### PR TITLE
ocaml: compile with -fcommon to support gcc 10

### PR DESCRIPTION
**Pull request by avsm**
gcc 10 and upwards alters the defaults such that duplicate C symbols results in a linker error.  This PR forces compilation with the `-fcommon` flag, which preserves the pre-gcc-10 behaviour and thus compatibility with OCaml <4.09.1.

`-fcommon` has been supported from gcc 4.4 upwards, which is a reasonable base default (checked by @Octachron)

A PR to do this for ocaml-variants will follow once this is merged.

### CODE REVIEW

**Comment by avsm** [comment]
@Octachron a review of this would be appreciated

**Comment by hannesm** [comment]
just my 2 cents:
- 1. why is this needed on freebsd/openbsd/macos, where clang is used? AFAICT (at least until clang 9.x), `-fno-common` is not the default (not sure if/when they'll change it).
- 2. on the other systems (mainly linux i suspect), is gcc always installed as `cc`? doesn't the current configure logic call out to `gcc`?

**Comment by avsm** [comment]
Thanks for the review, @hannesm. llvm has also changed its defaults recently (https://reviews.llvm.org/D75056), so I'd prefer to do this change in one go for historical OCaml versions. There should be no behavioural change by setting the flag explicitly, and it'll future proof us a little.

I am looking into how to exert finer control over discriminating between gcc versions in the base packages, but that's going to take longer as there are a number of changes that are pending.

On other systems, `cc` should always be an alias for either `gcc` or `clang`, which is installed.

**Comment by Octachron** [comment]
Looking at the execution of the configure script, using `cc` rather than `gcc` disables the detection of the `-fno-tree-vrp` flag which is used to workaround the Sky/Kaby lake bug with mingw.

**Comment by avsm** [comment]
Good catch. Unfortunately, our opam discrimination of gcc/clang isn't quite there yet, so we can't just set it to gcc as a clang-using Linux distro would fail.  There's really no way just to add to BYTECCCOMPOPTS in earlier versions is there? I could just add a small patch to the opam package to add -fcommon unconditionally to the configure script, which would solve the problem without more configure gymnastics.

**Comment by Octachron** [comment]
At least for version strictly before 4.05,  there is no -fno-tree-vrp fix, and the cc redefinition is probably good enough.
`BYTECCCOMPOPTS` doesn't seem to be usable for this purpose? And only ocamltest uses it briefly past 4.06 .
A patch to configure might be the best option.

**Comment by avsm** [comment]
The test for -fno-tree-vrp sounds a bit brittle, since `cc` can always be `gcc` and only a configure test running it can determine what compiler it is.  Ideally, we want to compile just the runtime with -fcommon, and not propagate it through to the ecosystem. BYTECCCOMPOPTS (and NATIVECCCOMPOPTS) did that pre 4.06 to control options to the runtime.

Given this is just a one-off, I'll add configure patches. For modern OCaml (with the autoconf mechanism), it would be good to ensure that there's a way to append CFLAGS without modifying cc.

**Comment by Octachron** [comment]
Note that we need to patch the ocaml-secondary-compiler package too (as reported ocaml/ocaml#9679).

**Comment by avsm** [comment]
@Octachron this is now ready for review again. It was only reliably possible by patching the configure scripts. 

I tested it with this Dockerfile on both gcc9 and 10:

```
FROM fedora:31 as f31
RUN yum -y groupinstall "Development Tools"
RUN yum install -y git gcc autoconf binutils-devel ncurses-devel gdbm-devel gawk perl-interpreter util-linux chrpath diffutils file opam
RUN opam init -ya "git://github.com/avsm/opam-repository.git#fix-gcc10" --disable-sandboxing --bare
FROM fedora:32 as f32
RUN yum -y groupinstall "Development Tools"
RUN yum install -y git gcc autoconf binutils-devel ncurses-devel gdbm-devel gawk perl-interpreter util-linux chrpath diffutils file opam
RUN opam init -ya "git://github.com/avsm/opam-repository.git#fix-gcc10" --disable-sandboxing --bare

# 4.08.1
FROM f31 as ocaml-4.08.1-fcommon-gcc9
RUN opam switch create 4.08.1 ocaml-base-compiler.4.08.1
FROM f32 as ocaml-4.08.1-fcommon-gcc10
RUN opam switch create 4.08.1 ocaml-base-compiler.4.08.1

# 4.08.0
FROM f31 as ocaml-4.08.0-fcommon-gcc9
RUN opam switch create 4.08.0 ocaml-base-compiler.4.08.0
FROM f32 as ocaml-4.08.0-fcommon-gcc10
RUN opam switch create 4.08.0 ocaml-base-compiler.4.08.0

# 4.07.1
FROM f31 as ocaml-4.07.1-fcommon-gcc9
RUN opam switch create 4.07.1 ocaml-base-compiler.4.07.1
FROM f32 as ocaml-4.07.1-fcommon-gcc10
RUN opam switch create 4.07.1 ocaml-base-compiler.4.07.1

# 4.07.0
FROM f31 as ocaml-4.07.0-fcommon-gcc9
RUN opam switch create 4.07.0 ocaml-base-compiler.4.07.0
FROM f32 as ocaml-4.07.0-fcommon-gcc10
RUN opam switch create 4.07.0 ocaml-base-compiler.4.07.0

# 4.06.1
FROM f31 as ocaml-4.06.1-fcommon-gcc9
RUN opam switch create 4.06.1 ocaml-base-compiler.4.06.1
FROM f32 as ocaml-4.06.1-fcommon-gcc10
RUN opam switch create 4.06.1 ocaml-base-compiler.4.06.1

# 4.06.0
FROM f31 as ocaml-4.06.0-fcommon-gcc9
RUN opam switch create 4.06.0 ocaml-base-compiler.4.06.0
FROM f32 as ocaml-4.06.0-fcommon-gcc10
RUN opam switch create 4.06.0 ocaml-base-compiler.4.06.0

# 4.05.0
FROM f31 as ocaml-4.05.0-fcommon-gcc9
RUN opam switch create 4.05.0 ocaml-base-compiler.4.05.0
FROM f32 as ocaml-4.05.0-fcommon-gcc10
RUN opam switch create 4.05.0 ocaml-base-compiler.4.05.0

# 4.04.2
FROM f31 as ocaml-4.04.2-fcommon-gcc9
RUN opam switch create 4.04.2 ocaml-base-compiler.4.04.2
FROM f32 as ocaml-4.04.2-fcommon-gcc10
RUN opam switch create 4.04.2 ocaml-base-compiler.4.04.2

# 4.04.1
FROM f31 as ocaml-4.04.1-fcommon-gcc9
RUN opam switch create 4.04.1 ocaml-base-compiler.4.04.1
FROM f32 as ocaml-4.04.1-fcommon-gcc10
RUN opam switch create 4.04.1 ocaml-base-compiler.4.04.1

# 4.04.0
FROM f31 as ocaml-4.04.0-fcommon-gcc9
RUN opam switch create 4.04.0 ocaml-base-compiler.4.04.0
FROM f32 as ocaml-4.04.0-fcommon-gcc10
RUN opam switch create 4.04.0 ocaml-base-compiler.4.04.0

# 4.03.0
FROM f31 as ocaml-4.03.0-fcommon-gcc9
RUN opam switch create 4.03.0 ocaml-base-compiler.4.03.0
FROM f32 as ocaml-4.03.0-fcommon-gcc10
RUN opam switch create 4.03.0 ocaml-base-compiler.4.03.0

# 4.02.3
FROM f31 as ocaml-4.02.3-fcommon-gcc9
RUN opam switch create 4.02.3 ocaml-base-compiler.4.02.3
FROM f32 as ocaml-4.02.3-fcommon-gcc10
RUN opam switch create 4.02.3 ocaml-base-compiler.4.02.3

# 4.02.2
FROM f31 as ocaml-4.02.2-fcommon-gcc9
RUN opam switch create 4.02.2 ocaml-base-compiler.4.02.2
FROM f32 as ocaml-4.02.2-fcommon-gcc10
RUN opam switch create 4.02.2 ocaml-base-compiler.4.02.2

# 4.02.1
FROM f31 as ocaml-4.02.1-fcommon-gcc9
RUN opam switch create 4.02.1 ocaml-base-compiler.4.02.1
FROM f32 as ocaml-4.02.1-fcommon-gcc10
RUN opam switch create 4.02.1 ocaml-base-compiler.4.02.1

# 4.02.0
FROM f31 as ocaml-4.02.0-fcommon-gcc9
RUN opam switch create 4.02.0 ocaml-base-compiler.4.02.0
FROM f32 as ocaml-4.02.0-fcommon-gcc10
RUN opam switch create 4.02.0 ocaml-base-compiler.4.02.0

FROM fedora:32
COPY --from=ocaml-4.08.1-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.08.1-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.07.1-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.07.1-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.07.0-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.07.0-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.06.1-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.06.1-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.06.0-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.06.0-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.05.0-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.05.0-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.04.2-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.04.2-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.04.1-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.04.1-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.04.0-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.04.0-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.03.0-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.03.0-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.02.3-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.02.3-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.02.2-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.02.2-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.02.1-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.02.1-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.02.0-fcommon-gcc9 /usr/bin/opam /usr/bin/opam
COPY --from=ocaml-4.02.0-fcommon-gcc10 /usr/bin/opam /usr/bin/opam
```

it can be run with `DOCKER_BUILDKIT=1 docker build .`

**Comment by Octachron** [comment]
This seems like the right fix, and the dockerfile does build without any issues. I will run few more tests today, and then we should probably merge.

**Comment by avsm** [comment]
Thanks; let me know when you're good with it and I'll merge this.  Meanwhile, I'll prepare an extended PR that replicates the patches across the many variant branches for merging after this one is in and settled.

**Comment by avsm** [comment]
For the record, in case someone else needs to extract patches from branches for this sort of thing, the Dockerfile to test from source is:


```
FROM fedora:31 as f31
RUN yum -y groupinstall "Development Tools"
RUN yum install -y git gcc autoconf binutils-devel ncurses-devel gdbm-devel gawk perl-interpreter util-linux chrpath diffutils file
FROM fedora:32 as f32
RUN yum -y groupinstall "Development Tools"
RUN yum install -y git gcc autoconf binutils-devel ncurses-devel gdbm-devel gawk perl-interpreter util-linux chrpath diffutils file

# 4.08.1
FROM f31 as ocaml-4.08.1-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.08.1-fcommon
RUN cd ocaml && ./configure && make -j world.opt && make install
FROM f32 as ocaml-4.08.1-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.08.1-fcommon
RUN cd ocaml && ./configure && make -j world.opt && make install

# 4.07.1
FROM f31 as ocaml-4.07.1-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.07.1-fcommon
RUN cd ocaml && ./configure && make -j world.opt && make install
FROM f32 as ocaml-4.07.1-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.07.1-fcommon
RUN cd ocaml && ./configure && make -j world.opt && make install

# 4.07.0
FROM f31 as ocaml-4.07.0-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.07.0-fcommon
RUN cd ocaml && ./configure && make -j world.opt && make install
FROM f32 as ocaml-4.07.0-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.07.0-fcommon
RUN cd ocaml && ./configure && make -j world.opt && make install

# 4.06.1
FROM f31 as ocaml-4.06.1-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.06.1-fcommon
RUN cd ocaml && ./configure && make -j world.opt && make install
FROM f32 as ocaml-4.06.1-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.06.1-fcommon
RUN cd ocaml && ./configure && make -j world.opt && make install

# 4.06.0
FROM f31 as ocaml-4.06.0-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.06.0-fcommon
RUN cd ocaml && ./configure && make -j world.opt && make install
FROM f32 as ocaml-4.06.0-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.06.0-fcommon
RUN cd ocaml && ./configure && make -j world.opt && make install

# 4.05.0
FROM f31 as ocaml-4.05.0-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.05.0-fcommon
RUN cd ocaml && ./configure && make world.opt && make install
FROM f32 as ocaml-4.05.0-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.05.0-fcommon
RUN cd ocaml && ./configure && make world.opt && make install

# 4.04.2
FROM f31 as ocaml-4.04.2-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.04.2-fcommon
RUN cd ocaml && ./configure && make world.opt && make install
FROM f32 as ocaml-4.04.2-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.04.2-fcommon
RUN cd ocaml && ./configure && make world.opt && make install

# 4.04.1
FROM f31 as ocaml-4.04.1-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.04.1-fcommon
RUN cd ocaml && ./configure && make world.opt && make install
FROM f32 as ocaml-4.04.1-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.04.1-fcommon
RUN cd ocaml && ./configure && make world.opt && make install

# 4.04.0
FROM f31 as ocaml-4.04.0-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.04.0-fcommon
RUN cd ocaml && ./configure && make world.opt && make install
FROM f32 as ocaml-4.04.0-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.04.0-fcommon
RUN cd ocaml && ./configure && make world.opt && make install

# 4.03.0
FROM f31 as ocaml-4.03.0-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.03.0-fcommon
RUN cd ocaml && ./configure && make world.opt && make install
FROM f32 as ocaml-4.03.0-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.03.0-fcommon
RUN cd ocaml && ./configure && make world.opt && make install

# 4.02.3
FROM f31 as ocaml-4.02.3-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.02.3-fcommon
RUN cd ocaml && ./configure && make world.opt && make install
FROM f32 as ocaml-4.02.3-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.02.3-fcommon
RUN cd ocaml && ./configure && make world.opt && make install

# 4.02.2
FROM f31 as ocaml-4.02.2-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.02.2-fcommon
RUN cd ocaml && ./configure && make world.opt && make install
FROM f32 as ocaml-4.02.2-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.02.2-fcommon
RUN cd ocaml && ./configure && make world.opt && make install

# 4.02.1
FROM f31 as ocaml-4.02.1-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.02.1-fcommon
RUN cd ocaml && ./configure && make world.opt && make install
FROM f32 as ocaml-4.02.1-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.02.1-fcommon
RUN cd ocaml && ./configure && make world.opt && make install

# 4.02.0
FROM f31 as ocaml-4.02.0-fcommon-gcc9
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.02.0-fcommon
RUN cd ocaml && ./configure && make world.opt && make install
FROM f32 as ocaml-4.02.0-fcommon-gcc10
RUN git clone --depth=1 git://github.com/avsm/ocaml -b 4.02.0-fcommon
RUN cd ocaml && ./configure && make world.opt && make install

FROM fedora:32
COPY --from=ocaml-4.08.1-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.08.1-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.07.1-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.07.1-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.07.0-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.07.0-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.06.1-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.06.1-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.06.0-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.06.0-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.05.0-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.05.0-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.04.2-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.04.2-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.04.1-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.04.1-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.04.0-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.04.0-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.03.0-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.03.0-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.02.3-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.02.3-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.02.2-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.02.2-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.02.1-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.02.1-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.02.0-fcommon-gcc9 /usr/local/bin/ocaml /usr/bin/ocaml
COPY --from=ocaml-4.02.0-fcommon-gcc10 /usr/local/bin/ocaml /usr/bin/ocaml
```

**Comment by dra27** [comment]
@avsm - do you want to apply the patch to ocaml-secondary-compiler here too, or shall I prepare a separate PR?

**Comment by avsm** [comment]
I'll apply the patch to ocaml-secondary-compiler right after this goes in, and then to the ocaml-variants. I've got a bunch of Dockerfiles here to manually test, so easy enough for me to do it.  @Octachron have you had the chance to run the extra tests, or should I just go ahead and merge?

**Comment by Octachron** [comment]
I have not found the time yesterday, sorry. However, the patches look fine and the docker instance run fine, so let's go ahead.

**Comment by avsm** [comment]
No problem, thanks for the reviews so far!

**Pull request merged**
