### PR TITLE
[new release] saturn (2 packages) (0.4.1)

### PR DESCRIPTION
**Pull request by Sudha247**
Collection of parallelism-safe data structures for Multicore OCaml

- Project page: <a href="https://github.com/ocaml-multicore/saturn">https://github.com/ocaml-multicore/saturn</a>
- Documentation: <a href="https://ocaml-multicore.github.io/saturn/">https://ocaml-multicore.github.io/saturn/</a>

##### CHANGES:

- pop_opt, peek, peek_opt functions for queue (@lyrm)
- Remove 'name' field from benchmark results (@Sudha247)
- Better README (@lyrm, @Sudha247, @polytypic, @art-w, @christinerose, @ILeandersson, @kayceesrk)
- Add .nojekyll (@lyrm)
- Add a barrier module in tests to replace the use of Semaphore (@lyrm, @polytypic)
- Remove .merlin and .ocp-indent files. (@lyrm)
- Correct issue caused by saturn_lockfree module beeing named Lockfree (@lyrm)
- Generate opam files automatically (@sudha247)

### CODE REVIEW

**Comment by mseri** [comment]
Is there a breaking change?
Domainslib seems to be failing now:
```
#=== ERROR while compiling domainslib.0.5.1 ===================================#
# context              2.2.0~alpha3~dev | linux/x86_64 | ocaml-base-compiler.5.1.0 | file:///home/opam/opam-repository
# path                 ~/.opam/5.1/.opam-switch/build/domainslib.0.5.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p domainslib -j 71 @install
# exit-code            1
# env-file             ~/.opam/log/domainslib-7-2e874f.env
# output-file          ~/.opam/log/domainslib-7-2e874f.out
### output ###
# (cd _build/default && /home/opam/.opam/5.1/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.domainslib.objs/byte -I /home/opam/.opam/5.1/lib/domain-local-await -I /home/opam/.opam/5.1/lib/domain_shims -I /home/opam/.opam/5.1/lib/ocaml/threads -I /home/opam/.opam/5.1/lib/ocaml/unix -I /home/opam/.opam/5.1/lib/saturn -I /home/opam/.opam/5.1/lib/saturn_lockfree -I /home/opam/.opam/5.1/lib/thread-table -no-alias-deps -open Domainslib__ -o lib/.domainslib.objs/byte/domainslib__Multi_channel.cmo -c -impl lib/multi_channel.ml)
# File "lib/multi_channel.ml", line 152, characters 18-19:
# 152 |       | Some v -> v
#                         ^
# Error: This expression has type 'a but an expression was expected of type
#          'a option
#        The type variable 'a occurs inside 'a option
```

**Comment by mseri** [comment]
In this case is it expected? If not, can you add an upper bound to domainslib?

**Comment by Sudha247** [comment]
Thanks for pointing out!

> In this case is it expected? If not, can you add an upper bound to domainslib?

Yes, this needs to be fixed in domainslib. We'll make a release of domainslib with the fix. For the saturn release itself, is it ok to list lower versions of domainslib as a conflict?

**Comment by mseri** [comment]
Thanks. Don’t make a conflict please. I will add an upper bound to domainslib

**Review by christinerose — APPROVED** [review]

**Comment by mseri** [comment]
PR sent, this can be merged. Thanks

**Pull request merged**
