### PR TITLE
use sh -exc

### PR DESCRIPTION
**Pull request by hannesm**
@dsheets I guess this is for you.. :) (thanks for fixing this up)

### CODE REVIEW

**Comment by dsheets** [comment]
Oh, cool, thanks. Yes, there are more packages where this happens that I have fixed but haven't pushed, yet. Thanks for the help!

**Comment by hannesm** [comment]
I looked through my packages (`find . -maxdepth 2 -name opam | xargs grep sh`), in order to fix those invocations upstream (thus new releases won't add regression)... and encountered hkdf as the remaining one..

**Comment by hannesm** [comment]
maybe https://github.com/ocaml/opam-repository/wiki/PR-checks and/or @camelus should check that shell invocation includes `exc` arguments?

**Comment by dsheets** [comment]
I've put it on the wiki page and filed AltGr/Camelus#6.

**Pull request merged**
