### PR TITLE
[new release] gpr (1.4.1)

### PR DESCRIPTION
**Pull request by mmottl**
GPR - Library and Application for Gaussian Process Regression

- Project page: <a href="https://mmottl.github.io/gpr">https://mmottl.github.io/gpr</a>
- Documentation: <a href="https://mmottl.github.io/gpr/api">https://mmottl.github.io/gpr/api</a>

##### CHANGES:

* Updated to OPAM 2.0

### CODE REVIEW

**Comment by mmottl** [comment]
I see, this problem happened for the older version 1.22, which does not yet check for the availability of this GSL function.  What's the best way in OPAM 2.0 to deal with linking problems that are fixed in newer versions?  Can I just remove potentially failing older versions from the repository?  Or is there any better way to deactivate them, i.e. prevent their installation?

**Comment by mseri** [comment]
Would adding a bound `>= “1.24.0”` help?

**Comment by mmottl** [comment]
Oh, sorry, I thought this was about my recent gsl pull request, not about gpr.  Yes, I can add that bound to gpr.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
