### PR TITLE
solvuu_build: add bound on OCaml version and fix checksum

### PR DESCRIPTION
**Pull request by damiendoligez**
Note: the problem that prevents `solvuu_build` from compiling with 4.03 and 4.04 is already fixed upstream.

### CODE REVIEW

**Comment by samoht** [comment]
There is a spurious:

```
ocaml-verison is not a valid variable.
```

In the logs..

**Comment by damiendoligez** [comment]
The only "ocaml-verison" I found is in `lablgtk.2.18.4/opam`. See #7242

**Comment by samoht** [comment]
@damiendoligez seems that the other versions of the package also had checksum changes:

```
[ERROR] Bad checksum for
        /home/travis/.opam/packages.dev/solvuu_build.0.0.2/v0.0.2.tar.gz:
          - 16c2a467cf307e707e99abe4b0d5628f [expected result]
          - 0bd8283f14825c4a078e76c0e595535f [actual result]
```

**Comment by damiendoligez** [comment]
I have updated the checksum. The only difference between the old and new version of the tar file is the name of the directory that contains the files.

**Pull request merged**
