### PR TITLE
[new release] decoders-yojson, decoders-cbor, decoders, decoders-jsonm, decoders-ezjsonm, decoders-sexplib, decoders-bencode and decoders-msgpck (0.6.0)

### PR DESCRIPTION
**Pull request by mattjbray**
Yojson backend for decoders

- Project page: <a href="https://github.com/mattjbray/ocaml-decoders">https://github.com/mattjbray/ocaml-decoders</a>
- Documentation: <a href="https://mattjbray.github.io/ocaml-decoders/">https://mattjbray.github.io/ocaml-decoders/</a>

##### CHANGES:

* Add `Decode.of_of_string` and `Encode.of_to_string` (@mattjbray)
* Add `Decode.array` with bs-specific impl (mattjbray/ocaml-decoders#28, mattjbray/ocaml-decoders#30, @actionshrimp)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The tests fail on 32bit architectures with:
```
#=== ERROR while compiling decoders-msgpck.0.6.0 ==============================#
# context              2.1.0~beta4 | linux/arm32 | ocaml-base-compiler.4.11.2 | pinned(https://github.com/mattjbray/ocaml-decoders/releases/download/v0.6.0/decoders-v0.6.0.tbz)
# path                 ~/.opam/4.11/.opam-switch/build/decoders-msgpck.0.6.0
# command              ~/.opam/4.11/bin/dune build -p decoders-msgpck -j 31 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/decoders-msgpck-24-124d2a.env
# output-file          ~/.opam/log/decoders-msgpck-24-124d2a.out
### output ###
#         main alias test-msgpck/runtest (exit 1)
# (cd _build/default/test-msgpck && ./main.exe)
# ....F......
# ==============================================================================
# Error: msgpck:0:decoders:5:int64 conversion.
# 
# File "/home/opam/.opam/4.11/.opam-switch/build/decoders-msgpck.0.6.0/_build/default/test-msgpck/oUnit-msgpck-builder#02.log", line 11, characters 1-1:
# Error: msgpck:0:decoders:5:int64 conversion (in the log).
# 
# Raised at OUnitAssert.assert_failure in file "src/lib/ounit2/advanced/oUnitAssert.ml", line 45, characters 2-27
# Called from OUnitRunner.run_one_test.(fun) in file "src/lib/ounit2/advanced/oUnitRunner.ml", line 83, characters 13-26
# 
# Expected an int, but got 525252
# ------------------------------------------------------------------------------
# Ran: 11 tests in: 0.12 seconds.
# FAILED: Cases: 11 Tried: 11 Errors: 0 Failures: 1 Skip:  0 Todo: 0 Timeouts: 0.
```

**Comment by c-cube** [comment]
Maybe msgpck is ill-behaved on 32 bits? Maybe @vbmithr knows?

**Comment by vbmithr** [comment]
I will take a look, thanks.

**Comment by vbmithr** [comment]
I can confirm the bug is in msgpck for 32bit architectures. You can merge this, I will fix the bug in msgpck soon.

**Comment by mattjbray** [comment]
Thanks for looking @vbmithr @c-cube

**Comment by vbmithr** [comment]
I added a PR here: https://github.com/ocaml/opam-repository/pull/18369

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
