### PR TITLE
added coccinelle rc23

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by yallop** [comment]
The build's [failing with checksum errors](https://travis-ci.org/ocaml/opam-repository/jobs/56070727):

```
[ERROR] Wrong checksum for /home/travis/.opam/packages.dev/coccinelle.1.0.0-rc23/coccinelle-1.0.0-rc24.tar.gz:
- b4b12e8b8730c586891572a2518b87a5 [expected result]
- 8cbe943716a7a1033d46f8157ea986d4 [actual result]
```

**Comment by avsm** [comment]
The tar file is rc24, should be 23

**Comment by UnixJunkie** [comment]
Travis failed due to some download errors
maybe it can be relaunshed

**Comment by UnixJunkie** [comment]
I think Travis should be relaunched on this one

**Comment by dsheets** [comment]
I just did. It's running.

**Comment by UnixJunkie** [comment]
Thanks a lot!

**Pull request merged**
