### PR TITLE
4 packages from c-cube/calculon at 0.6

### PR DESCRIPTION
**Pull request by c-cube**
This pull-request concerns:
-`calculon.0.6`: Library for writing IRC bots in OCaml and a collection of plugins
-`calculon-redis.0.6`: A redis plugin for Calculon
-`calculon-redis-lib.0.6`: A library to interact with Calculon via Redis
-`calculon-web.0.6`: A collection of web plugins for Calculon

---
* Homepage: https://github.com/c-cube/calculon
* Source repo: git+https://github.com/c-cube/calculon.git
* Bug tracker: https://github.com/c-cube/calculon/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Could you expend a little? What is the diff?

**Comment by c-cube** [comment]
the diff is bugfixes and a new dep on `logs`. travis failure seems to come from `openssl` on macOS somehow.

**Comment by kit-ty-kate** [comment]
Here is the whole diff:
```
diff -ur old/CHANGELOG.md new/CHANGELOG.md
--- old/CHANGELOG.md	2019-12-17 04:29:34.000000000 +0000
+++ new/CHANGELOG.md	2020-01-15 19:37:31.000000000 +0000
@@ -1,12 +1,4 @@
 
-## 0.6
-
-- use `logs`, deprecate `Core.log` functions.
-- better irclog parser
-- fix warnings by using modern yojson
-- add `extra_args` to config parser
-- fix: do not ignore custom port in config
-
 ## 0.5
 
 - refactor: use curly for the web plugin
diff -ur old/src/core/Command.mli new/src/core/Command.mli
--- old/src/core/Command.mli	2019-12-17 04:29:34.000000000 +0000
+++ new/src/core/Command.mli	2020-01-15 19:37:31.000000000 +0000
@@ -41,7 +41,7 @@
     Returns [None] if it cannot split on ">" cleanly. *)
 
 val match_prefix1_full : prefix:string -> cmd:string -> Core.privmsg -> (string * string option) option
-(** @returns [Some (msg, hl)] if [msg] matches the regex,
+(** @return [Some (msg, hl)] if [msg] matches the regex,
    and [hl] is either [Some foo] if the message ended with "> hl",
    [None] otherwise *)
 
diff -ur old/src/core/Config.mli new/src/core/Config.mli
--- old/src/core/Config.mli	2019-12-17 04:29:34.000000000 +0000
+++ new/src/core/Config.mli	2020-01-15 19:37:31.000000000 +0000
@@ -23,7 +23,7 @@
 
   log_level: Logs.level;
   (** Level of logging.
-      @since NEXT_RELEASE *)
+      @since 0.6 *)
 
   prefix: string; (** prefix for commands *)
 }
diff -ur old/src/core/Core.mli new/src/core/Core.mli
--- old/src/core/Core.mli	2019-12-17 04:29:34.000000000 +0000
+++ new/src/core/Core.mli	2020-01-15 19:37:31.000000000 +0000
@@ -43,17 +43,23 @@
   val exit : unit Lwt.t
 
   val log : string -> unit Lwt.t
+  [@@ocaml.deprecated "use library logs instead"]
   (** Log a message (see field [irc_log] of {!Config.config}),
       typically for debugging purpose.
+      @deprecated use logs
       @since 0.5 *)
 
   val logf : ('a, Format.formatter, unit, unit Lwt.t) format4 -> 'a
+  [@@ocaml.deprecated "use library logs instead"]
   (** Pretty logger (calling {!log} to print the formatted message).
       Example: [logf "answer to %s is %d" "life" 42]
+      @deprecated use logs
       @since 0.5 *)
 
   val set_log : (string -> unit Lwt.t) -> unit
+  [@@ocaml.deprecated "use library logs instead"]
   (** Set logger (default is the empty logger) that will be used by {!log}
+      @deprecated use logs
       @since 0.5 *)
 
   val send_exit : unit -> unit
@@ -143,4 +149,4 @@
 
 val logs_src: Logs.Src.t
 (** Logs from Calculon should use this source.
-    @since NEXT_RELEASE *)
+    @since 0.6 *)
```
Please try to not change/force-push tags next time, this breaks your packages and annoys your users. Not everyone use the opam cache (CIs are one example). Related issues: https://github.com/ocaml/opam-repository/issues/10531

**Comment by c-cube** [comment]
Ah, I didn't realize it was already released, hence my puzzlement about "what is the diff?". I understand better now.

**Pull request merged**
