### PR TITLE
Package scipy.sp1.4-0.3.0

### PR DESCRIPTION
**Pull request by lehy**
### `scipy.sp1.4-0.3.0`
SciPy scientific computing library for OCaml
These are OCaml bindings to the SciPy Python library.
The SciPy library provides many
user-friendly and efficient numerical routines, such as routines for
numerical integration, interpolation, optimization, linear algebra,
and statistics.

---
* Homepage: https://github.com/lehy/ocaml-sklearn
* Source repo: git+https://github.com/lehy/ocaml-sklearn.git
* Bug tracker: https://github.com/lehy/ocaml-sklearn/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by lehy** [comment]
This is a new package, on which sklearn now depends. All three of np, scipy and sklearn are produced from the same git repo (the ocaml-sklearn one), and documented in the same place.

**Comment by lehy** [comment]
I suppose this is failing until #16620 is merged, since it depends on it. (Guessing, since I cannot see an error log above).

**Comment by hannesm** [comment]
same comment as in #16622: is the version intentional?

**Comment by lehy** [comment]
> same comment as in #16622: is the version intentional?

Yes, see details in https://github.com/ocaml/opam-repository/pull/16620#issuecomment-643162045 .

**Comment by avsm** [comment]
Please merge/rebase against master to pick up #16622

**Comment by mseri** [comment]
@lehy can you rebase against master and force push over the PR. This way the CI will pick that change and we can test the package and eventually merge

**Comment by lehy** [comment]
Yes, I will do it as soon as possible. Thank you for the reminder, apologies for keeping this open so long.

**Comment by lehy** [comment]
The Macos build failed because it failed to install python3 (which is required by pyml). I don't think there is anything I can do to fix this on my side?

**Comment by mseri** [comment]
Thanks! I am only waiting for the OCamlCI to come back online and finish the checks

**Comment by mseri** [comment]
All green! Thanks

**Pull request merged**
