### PR TITLE
Remove mpi package

### LINKED ISSUE #5023: "opam install mpi" fails on Fedora
It seems that the Fedora installation of OpenMPI does not add symbolic links of executables into /usr/bin, header files into /usr/include, and libraries into /usr/lib. The build rule for OCaml MPI therefore fails because it cannot find the necessary header files, compilers, and libraries.

### PR DESCRIPTION
**Pull request by dbuenzli**
This package is lacking minimal quality requirements, see [this comment](https://github.com/ocaml/opam-repository/issues/5023#issuecomment-312913317) for details.

Closes #5023.

### CODE REVIEW

**Comment by gasche** [comment]
My alternative proposal would be to ask Xavier for a new release, and clean up the opam packaging. I will create a `conf-mpi` package, send depext-clean `opam` file upstream as a pull request (as asked by @UnixJunkie on xavierleroy/ocamlmpi#1), then ask for a new release.

**Comment by dbuenzli** [comment]
> My alternative proposal would be to ask Xavier for a new release, and clean up the opam packaging.

I'm fine with this but I don't see any reason to keep this as it exists here. It's broken and broken things lead to bad experiences. This should be merged.

**Comment by gasche** [comment]
Well, if someone had merged this issue and closed #5023, I would have never heard of the issue, and arguably the statu quo would be worse than with the approach I propose. So sometimes leaving painful stuff open is useful!

**Comment by dbuenzli** [comment]
> So sometimes leaving painful stuff open is useful!

This is not painful stuff. It's broken stuff. The configuration seems to be specific to a machine and we don't even know who created that tarball.

> So sometimes leaving painful stuff open is useful!

Remark that it's precisely because I want to close this that you are seeing the issue... This issue has been open for almost two years...

**Comment by dbuenzli** [comment]
> Remark that it's precisely because I want to close this that you are seeing the issue... This issue has been open for almost two years...

Just to expand a bit on this. 

During the past two weeks since I got access to this repo I brought the number of issues from approximatively a hundred to under twenty --- which I have the feeling is a reasonable limit we should try to strive for. An os package system like homebrew which has approximately 4500 individual packages (opam has less than half of that) manages to have  [less than](https://github.com/Homebrew/homebrew-core/issues) twenty issues at the moment.

During this process I got empirical evidence that leaving issues open for a long time is absolutely not useful. Most of the issues fell into one of these cases:

1. Install issue that was reported, often ignored or little investigated, fixed by someone else at some point but the issue was never closed and thus potentially the initial person never warned --- sometime for *years*.
2. Install issue that was reported, often ignored or little investigated,  and never fixed, sometimes for *years*. Pinging the maintainer now usually solved the issue in a timely manner.
3. Ideas about repository administration, process/tooling improvements.

I really think that issue like 1. and 2. should absolutely not be left lingering for years and that it is very bad to have a package repository with some configurations erratically blowing in your face. Basically when someone comes with an issue we need to reproduce the issue and fix it in a *timely* manner using one of the following actions:

a. Pinging the package maintainer (if any) and let her fix the package in a reasonable timeframe.
b. If the maintainer is not responsive or there is no maintainer and a repo admin or another contributor feels she can fix the issue let her to so.
c. If a. and b. fail in a *timely* manner (let's say two weeks) an administrator should take action and put constraints so that the configuration cannot be installed. This is always easy to do by either removing offending packages or adjusting e.g. `os` availability to rule out the offending configuration. Someone can always come later to unblock the situation but the repo should not allow to install the configuration and blow in the face of users.

Regarding the kind of issue 3., there were two kind of issues: those who could be redirected to the appropriate tools that need to handle them (`camelus`, `opam`, `CI`, etc.) and others which exposed some ideas but that after a few *years* (again) of a discussion that had died and without concrete plan for action. It just didn't feel they were worth keeping open --- contributors are however always notified from the closure first and that they can reopen or ask to reopen the issue if they feel that it was wrong to close it. This didn't happen so far.

Now regarding the particular package at hand I feel quite uncomfortable to draw from a tarball it seems we don't know who created it, which doesn't even seem to come from a proper fork (https://github.com/HappyCrow/ocamlmpi is a 404) and which seems to have a hard-coded configuration. I tried to apply b. myself but it seems much more work was needed so I decided to move on with a. (I did ping at least another repo admin but he didn't respond). No package depends on this one, I don't think it should be a problem to remove it and re-add it once you managed to implement your plan of action.

Btw. if you care about removals you should also have a look at trying to advance https://github.com/ocaml/opam-repository/issues/8873.

**Comment by gasche** [comment]
I noticed the triaging work you poured in the last few weeks and I find it absolutely amazing. As someone with very irregular contribution bursts to the repository, I was always afraid to look at this wild jungle of issues, and you are making it *much* easier to come have a look and help with the triaging. Many thanks!

I think that you are *not wrong* regarding the present issue, but I am sort of phobic about removing packages and breaking things when an alternative solution with a non-infinite expected effort exists. (I *do* know that we can do both, remove now and implement the other solution later, but then the phobia-triggering removal happened for nothing! Or so the evil conservative whisperer says.) My approach to the present issue has thus been to give myself a couple days to explore my alternative route, and do as you suggest later in the week if it doesn't pan out.

(I have been somewhat slowed down by the fact that my own `conf-time` PR, #9848, has a transitive dependency closure so large that the CI is taking all day to build all these packages. I have seen Anil close PRs in similar situations in the past to free CI resources, and that would definitely have made the other changes I worked on today easier, but oh well, learning as I go.)

Note: I'm not too worried about HappyCrow turning out to be the bitcoin creator having uploaded an infected ocamlmpi package with the nefarious goal of taking over the OCaml world to replace all ocamlbuild runs by jbuilder + bitcoin mining in parallel in the same amount of time. It seems to be just a previous nickname for François Berenger from a distant past.

**Comment by samoht** [comment]
As the package is broken -- no-one seems to be able to install it! --- I am fine to remove the package. Moreover, the current maintainer (@UnixJunkie) [expressed that he is not interested](https://github.com/ocaml/opam-repository/issues/5023#issuecomment-312750831) to maintain the package anymore. A new and working release of ocamlmpi in opam is of course still very welcome!

**Comment by UnixJunkie** [comment]
FYI, I did the original tarball.
IIRC, the problem with ocamlmpi is that there was no configuration step at the time. You had to edit the Makefile. So, I did edit the Makefile to install with openmpi (there are several possible MPI flavours).

**Pull request merged**
