### PR TITLE
New version of statverif added

### PR DESCRIPTION
**Pull request by rittere**

### CODE REVIEW

**Comment by yomimono** [comment]
It looks like this package isn't yet ready for OCaml 4.06's default `-safe-string`.  Can you constrain it to OCaml versions less than 4.06.0, please?  This is done by adding an `available` field with `ocaml-version` set to `< "4.06.0"`.  If you know the minimum required OCaml version, it's best practice to set this as well, e.g. for a package compatible with OCaml 4.02.3 through 4.05.0:

`available: [ocaml-version >= "4.02.3" & ocaml-version < "4.06.0" ]`

**Comment by rittere** [comment]
I'd be grateful for hints how to make the package work on CentOS7 - it compiled fine for me with a fresh install, only downloading the packages ocaml and ocaml-findlib.

**Comment by jpdeplaix** [comment]
The CentOS image is most probably broken so it doesn't come from your package.
Could you add the missing ```dev-repo``` field ? It should look like this I believe:
```
dev-repo: "https://github.com/rittere/statverif"
```

**Comment by jpdeplaix** [comment]
Looks good now. Thanks !

**Pull request merged**
