### PR TITLE
Mark broken `ogg` packages as unavailable

### PR DESCRIPTION
**Pull request by raphael-proust**
See https://github.com/ocaml/opam-repository/pull/25179#issuecomment-1927442067

### CODE REVIEW

**Comment by mseri** [comment]
Is it really `available: false`? I think we only need an upper bound on the ocaml version

**Comment by raphael-proust** [comment]
True…

I've changed for version constraints. However, some of the packages didn't have a dependency to ocaml so I've made it a conflict. Not sure if I should just add the dependency instead.

**Comment by mseri** [comment]
They build with dune, I would say that they should depend on ocaml

**Comment by mseri** [comment]
In any case, this is a strict improvement and a conflict does the job, I don't think it is worth changing it again

**Comment by mseri** [comment]
Thanks

**Pull request merged**
