### PR TITLE
added ppx_orakuda.3.1.0

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by avsm** [comment]
fails on ocaml 4.04

```
 48/290 targets are up to date
# *** omake: failed (0.25 sec, 7/7 scans, 9/11 rules, 31/111 digests)
### stderr ###
# File OMyMakefile: line 746, characters 6-34:
# [...]
#    This expression should use a => binding.
# File "ppx_orakuda_regexp_re_pcre.ml", line 5, characters 12-29:
# Error: The module Gen is an alias for module Ppx_orakuda_regexp_gen, which is missing
# *** omake: targets were not rebuilt because of errors:
#    lib/ppx_orakuda_regexp_re_pcre.annot
#       depends on: lib/ppx_orakuda_regexp_re_pcre.ml
#    lib/ppx_orakuda_regexp_re_pcre.cmt
#       depends on: lib/ppx_orakuda_regexp_re_pcre.ml
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; unset OCAMLPARAM; omake\"' terminated with error code 2")
```

**Comment by camlspotter** [comment]
Thank you @avsm.  Probably some dependency is lost by my recent updates of OMakefiles.

**Comment by samoht** [comment]
Still failing:

```
#=== ERROR while installing ppx_orakuda.3.1.0 =================================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              ocaml setup.ml -build
# path                 /home/opam/.opam/4.04.0/build/ppx_orakuda.3.1.0
# compiler             4.04.0
# exit-code            1
# env-file             /home/opam/.opam/4.04.0/build/ppx_orakuda.3.1.0/ppx_orakuda-29-9d9583.env
# stdout-file          /home/opam/.opam/4.04.0/build/ppx_orakuda.3.1.0/ppx_orakuda-29-9d9583.out
# stderr-file          /home/opam/.opam/4.04.0/build/ppx_orakuda.3.1.0/ppx_orakuda-29-9d9583.err
### stdout ###
# [...]
# - scan ppx scan-ocaml-migrate_register.ml
# + ocamlfind ocamldep -package ocaml-compiler-libs.common,ocaml-migrate-parsetree,pcre,spotlib,ppx_tools,ppxx -modules migrate_register.ml
# - scan ppx scan-ocaml-lexrex.ml
# + ocamlfind ocamldep -package ocaml-compiler-libs.common,ocaml-migrate-parsetree,pcre,spotlib,ppx_tools,ppxx -modules lexrex.ml
# - scan ppx scan-ocaml-legacy.ml
# + ocamlfind ocamldep -package ocaml-compiler-libs.common,ocaml-migrate-parsetree,pcre,spotlib,ppx_tools,ppxx -modules legacy.ml
# - scan ppx scan-ocaml-lexformat.ml
# + ocamlfind ocamldep -package ocaml-compiler-libs.common,ocaml-migrate-parsetree,pcre,spotlib,ppx_tools,ppxx -modules lexformat.ml
# *** omake: 80/290 targets are up to date
# *** omake: failed (0.20 sec, 26/26 scans, 10/10 rules, 54/88 digests)
### stderr ###
# *** omake: targets were not rebuilt because of errors:
# [...]
#    <scanner ppx/scan-ocaml-p_regexp.ml>
#       depends on: ppx/p_regexp.ml
#    <scanner ppx/scan-ocaml-p_sprintf.ml>
#       depends on: ppx/p_sprintf.ml
#    <scanner ppx/scan-ocaml-p_top.ml>
#       depends on: ppx/p_top.ml
#    <scanner ppx/scan-ocaml-ppx.ml>
#       depends on: ppx/ppx.ml
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; unset OCAMLPARAM; omake\"' terminated with error code 2")
```

**Comment by camlspotter** [comment]
Thanks for notifying.  I have problems with subtlety of OMake build dependencies which makes build succeeed/fail undeterministicly.  I am understanding the problem but several more PRs may be required.

**Comment by camlspotter** [comment]
I finally nailed it!

**Comment by samoht** [comment]
Great! :-)

**Pull request merged**
