### PR TITLE
constrain existing packages to mirage-kv{-lwt} <2.0.0 for an upcoming…

### PR DESCRIPTION
**Pull request by hannesm**
… breaking release (https://github.com/mirage/mirage-kv/pull/14)

### CODE REVIEW

**Comment by avsm** [comment]
I think mirage-kv also needs a similar constraint

**Comment by hannesm** [comment]
@avsm I'm sorry, I don't follow. in this PR, an upper bound for all packages that depend on mirage-kv have been added. in addition, an upper bound to mirage-kv-lwt has been added. where are missing upper bounds in your opinion?

**Comment by hannesm** [comment]
CI failures are unrelated to this PR - some CI machines have solver timeouts, and some packages are broken (using cstruct.lwt/cstruct.ppx which got removed in 3.4.0). can be fixed in separate PRs.

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by avsm** [comment]
sorry, I thought I only saw mirage-kv-lwt constraints, but a second look has corrected me :)

**Pull request merged**
