### PR TITLE
ocaml-freestanding release 0.2.3

### PR DESCRIPTION
**Pull request by mato**

### CODE REVIEW

**Comment by mato** [comment]
The failing OPAM 2 builds seem to be mis-parsing `available` as: 

````
[ERROR] ocaml-freestanding = 0.2.3 unmet availability conditions: os = "linux" & (arch = "x86_64" | arch = "aarch64" | os = "freebsd") & arch = "amd64"
````

**Comment by hannesm** [comment]
@mato I find the available not very well-stapled:
```
available: [
  ocaml-version >= "4.02.3" & ocaml-version < "4.07.0" &
  ((os = "linux" & (arch = "x86_64" | arch = "aarch64") |
   (os = "freebsd" & arch = "amd64")))
] 
```

wouldn't the following be more clear (i.e. a `)` before `|`, and one less at the end)?
```
available: [
  ocaml-version >= "4.02.3" & ocaml-version < "4.07.0" &
  ((os = "linux" & (arch = "x86_64" | arch = "aarch64")) |
   (os = "freebsd" & arch = "amd64"))
] 
```

**Comment by mato** [comment]
@hannesm Sure, shall I just push the metadata change to this branch? Presumably there's no need to remake a new source tarball?

**Comment by hannesm** [comment]
yes, pushing to this branch here is perfectly fine.  should fix in ocaml-freestanding's repository as well, though :)

**Comment by mato** [comment]
With 3af97a5 it seems the OPAM 2 failures are still present:

````
ERROR] ocaml-freestanding = 0.2.3 unmet availability conditions: os = "linux" & (arch = "x86_64" | arch = "aarch64" | os = "freebsd") & arch = "amd64"
````

I can either simplify the expression to the following:

````
 available: [
   ocaml-version >= "4.02.3" & ocaml-version < "4.07.0" &
   (os = "linux" | os = "freebsd") &
   (arch = "x86_64 | arch = "amd64" | arch = "aarch64")
 ]
````

...which should parse on OPAM 2 and won't hurt right now since the dependencies for `freebsd` on `aarch64` don't exist anyway, OR we can merge this once it passes all the OPAM 1.x tests and ignore the OPAM 2 failures (and report an issue!).

**Comment by hannesm** [comment]
given what Louis said in https://github.com/ocaml/opam/issues/3111, this is likely only a datakit caching issue.  the constraint looks fine in his output.  thanks, merging.

**Pull request merged**
