### PR TITLE
spdiff: incompatible with latest menhir

### PR DESCRIPTION
**Pull request by planar**

### CODE REVIEW

**Comment by whitequark** [comment]
@AltGr https://travis-ci.org/ocaml/opam-repository/jobs/46921224:
```
Internal error:
  While installing the following files:
 - src/menhir.opt in /home/travis/.opam/system/bin
```

**Comment by planar** [comment]
The package `menhir.20130911` doesn't work at all, and this probably explains the existence of `menhir.20130912` (which installs version 20130911 of menhir...)
Should we remove it? Should we then rename 20130912 to 20130911?

**Comment by whitequark** [comment]
I think rename is fine.

**Comment by samoht** [comment]
Yes rename is fine. Or if completely broken remove is even better.

**Comment by samoht** [comment]
Closing as this has been resolved bu #3437

**Comment by planar** [comment]
I don't think this was fixed by #3437, there are two different issues:
#3437: an old version of `menhir` was broken (20130911), and another version had the wrong number (20130912)
#3375: `spdiff.0.1` doesn't work with the latest `menhir` (20141215)

You can see the problem with:
```
opam install menhir.20141215 spdiff.0.1
```

**Comment by samoht** [comment]
the patch does not apply though

**Comment by planar** [comment]
My bad, it was fixed by 4f0857c623105611827bacf549605b30f6601db4.

**Pull request closed without merging**
