### PR TITLE
oasis 0.4.7

### PR DESCRIPTION
**Pull request by gildor478**

### CODE REVIEW

**Comment by fdopen** [comment]
This commit breaks dozens of opam build instructions, because OASISFormat 0.2 and 0.1 are not longer supported.
There are packages that have oasis as build dependency and still use one of these formats (examples: bench, maildir, otto, hamt, ocaml-posix-resource, ocaml-radixtree, ...)

**Comment by gildor478** [comment]
Kind of expected (unfortunately).

First:
Released packages should not depend on oasis, except if they actually link with it (e.g oasis2debian).

Now I think OPAM packages should be fixed because I will not continue to support 0.1 and 0.2 forever. 
Solutions:
1. get rid of the dependency on oasis if setup.ml is already generated
or
2. add a version constraint like oasis < 0.4.7 to problematic packages

@fdopen can you list precisely the packages that need to be fixed and add a link to the "weather channel" to check everything is ok ?

**Comment by samoht** [comment]
Also the test dependencies are incorrect:
```
$ opam install oasis -t
The following actions will be performed:
  ∗  install ounit           2.0.0            [required by oasis]
  ∗  install conf-pkg-config 1.0              [required by conf-libpcre]
  ∗  install base-bytes      base             [required by pcre]
  ∗  install conf-libpcre    1                [required by pcre]
  ∗  install qtest           2.2              [required by batteries]
  ∗  install pcre            7.2.3            [required by oasis]
  ∗  install batteries       2.5.2            [required by expect]
  ∗  install expect          0.0.4            [required by oasis]
  ∗  install oasis           0.4.7
===== ∗  9 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[expect.0.0.4] https://forge.ocamlcore.org/frs/download.php/1289/ocaml-expect-0.0.4.tar.gz downloaded
[oasis.0.4.7] https://forge.ocamlcore.org/frs/download.php/1635/oasis-0.4.7.tar.gz downloaded
[ounit.2.0.0] http://forge.ocamlcore.org/frs/download.php/1258/ounit-2.0.0.tar.gz downloaded
[pcre.7.2.3] https://github.com/mmottl/pcre-ocaml/releases/download/v7.2.3/pcre-ocaml-7.2.3.tar.gz downloaded
[qtest.2.2] https://github.com/vincent-hugot/iTeML/archive/v2.2.tar.gz downloaded
[batteries.2.5.2] https://github.com/ocaml-batteries-team/batteries-included/archive/v2.5.2.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
∗  installed base-bytes.base
∗  installed conf-pkg-config.1.0
∗  installed conf-libpcre.1
∗  installed ounit.2.0.0
∗  installed qtest.2.2
∗  installed pcre.7.2.3
∗  installed batteries.2.5.2
∗  installed expect.0.0.4
[ERROR] The compilation of oasis failed at "ocaml setup.ml -configure --enable-tests".
Processing  9/9: [oasis: ocaml]
#=== ERROR while installing oasis.0.4.7 =======================================#
# opam-version 1.2.2
# os           darwin
# command      ocaml setup.ml -configure --enable-tests
# path         /Users/thomas/.opam/oasis/build/oasis.0.4.7
# compiler     system (4.03.0)
# exit-code    1
# env-file     /Users/thomas/.opam/oasis/build/oasis.0.4.7/oasis-57015-90b366.env
# stdout-file  /Users/thomas/.opam/oasis/build/oasis.0.4.7/oasis-57015-90b366.out
# stderr-file  /Users/thomas/.opam/oasis/build/oasis.0.4.7/oasis-57015-90b366.err
### stderr ###
# ocamlfind: Package `fileutils' not found
# W: Field 'pkg_fileutils' is not set: Command ''/Users/thomas/.opam/oasis/bin/ocamlfind' query -format %d fileutils > '/var/folders/9g/7vjfw6kn7k9bs721d_zjzn7h0000gn/T/oasis-4dceff.txt'' terminated with error code 2
# W: Field 'omake' is not set
# ocamlfind: Package `fileutils' not found
# W: Failure("Command ''/Users/thomas/.opam/oasis/bin/ocamlfind' query -format %d fileutils > '/var/folders/9g/7vjfw6kn7k9bs721d_zjzn7h0000gn/T/oasis-9f441f.txt'' terminated with error code 2")
# E: Cannot find external tool 'omake'
# E: Cannot find findlib package fileutils
# E: Cannot find findlib package fileutils (>= 0.4.2)
# E: Failure("3 configuration errors")



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions failed
  ∗  install oasis 0.4.7
The following changes have been performed
  ∗  install base-bytes      base
  ∗  install batteries       2.5.2
  ∗  install conf-libpcre    1
  ∗  install conf-pkg-config 1.0
  ∗  install expect          0.0.4
  ∗  install ounit           2.0.0
  ∗  install pcre            7.2.3
  ∗  install qtest           2.2

The former state can be restored with:
    opam switch import "~/.opam/oasis/backup/state-20160724073634.export"
```

**Comment by samoht** [comment]
See #7292 for a fix

**Comment by samoht** [comment]
An example of breakage: nocrypto.0.5.3:

https://travis-ci.org/docker/datakit/jobs/154875954#L1293

**Comment by gildor478** [comment]
The nocrypto problem is a bug: look like the propagation of the of the
AlphaFeatures is not done correctly for the document section.

I have no tests covering this case.

Can you open a bug on the forge to report that ? (so that you'll get a
followup answer when I will have fix it)
https://forge.ocamlcore.org/tracker/?atid=291&group_id=54&func=browse

You can quickly fix it, in the meantime, by adding a constraint like (oasis
<> 0.4.7 or oasis != 0.4.7) to the package.

Reporting this kind of bug will be extremely useful to me, because I can
have a list and fix them.

Regards
Sylvain

**Comment by gildor478** [comment]
I have done a short review of the various packages that were broken with 0.4.7:

E: file "_oasis", line 13, characters 0-3: extraneous blanks at the beginning of the line
[ocaml-radixtree](http://opam.ocamlpro.com/builder/html/ocaml-radixtree/ocaml-radixtree.0.0.1/3a1fbe2be8331d1b640dda9728386a34)
[maildir](http://opam.ocamlpro.com/builder/html/maildir/maildir.0.9.0/932635d0b2464853194f02baf0ea4011)
[otto](http://opam.ocamlpro.com/builder/html/otto/otto.0.0.2/bf67716cba20346f3cd30642ccd5cd1b)
[hamt](http://opam.ocamlpro.com/builder/html/hamt/hamt.0.1/f3ad72beca19ac51beea5bcd8dab764f)
[ANSITerminal](http://opam.ocamlpro.com/builder/html/ANSITerminal/ANSITerminal.0.6/9353baf9568d1311338b0af42a9542c0)

E: OASIS format version '0.2' is not supported.
[bench](http://opam.ocamlpro.com/builder/html/bench/bench.1.3/75e33aaa1531285c9a6d7683b7322c9f)

E: OASIS format version '0.1' is not supported.
[ocaml-posix-resources](
http://opam.ocamlpro.com/builder/html/ocaml-posix-resource/ocaml-posix-resource.0.0.1/349591ca8899a08ef7816c80377eeabe)

I need to go through all of the build logs to check all possible bugs, but it seems that most of the bugs are related to the new parser rather than dropping support for OASISFormat 0.1 and 0.2.

My plan:
* submit patches to bench/ocaml-posix-resources to inject a pre-generated setup.ml (those cutting the dependency with OASIS)
* fix the new parser handling of "extraneous blanks"

**Comment by gildor478** [comment]
I went through the full list on:
http://opam.ocamlpro.com/builder/html/report-full.html

Here are the list of errors:
* E: file "_oasis", line 13, characters 0-3: extraneous blanks at the beginning of the line
 * maildir
 * otto
 * hamt
 * ANSITerminal 0.6
 * bistro 0.1.0 0.0.0
 * expect 0.0.2
 * receive-mail
 * facebook-sdk
 * mqtt_client
 * sociaml-vcard
 * sociaml-facebook-api
 * ocaml-radixtree
 * simple_pam
 * sociaml-oauth-client
* E: OASIS format version '0.2' is not supported.
 * bench 1.3
 * qtest <= 2.1.1
 * optimization1d 0.5
 * root1d 0.2
 * lbfgs 0.8.3
 * sqlexpr 0.3.0
 * weberizer 0.6.1
* E: OASIS format version '0.1' is not supported.
 * ocaml-posix-resources
* Error: Unbound value MyOCamlbuildBase.env_filename
 * ctypes 0.1.1
* Error: This expression has type Lexing.lexbuf but an expression was expected of type
 Ocamlbuild_pack.Loc.source = string
 * macaque.0.6.1

I plan to submit a patch to make them conflict with oasis 0.4.7, that will make them buildable.

**Comment by gildor478** [comment]
See #7308 for a fix.

**Pull request merged**
