### PR TITLE
brotli does not compile with lwt 2.4.5

### PR DESCRIPTION
**Pull request by damiendoligez**

### CODE REVIEW

**Comment by OCamlPro-Henry** [comment]
The CI failed.

```
[ERROR] The compilation of brotli failed at "ocaml setup.ml -build".
Processing 15/15: [brotli: ocamlfind remove]
#=== ERROR while installing brotli.1.1 ========================================#
# opam-version 1.2.2
# os           linux
# command      ocaml setup.ml -build
# path         /home/travis/.opam/system/build/brotli.1.1
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/brotli.1.1/brotli-8633-ab22a1.env
# stdout-file  /home/travis/.opam/system/build/brotli.1.1/brotli-8633-ab22a1.out
# stderr-file  /home/travis/.opam/system/build/brotli.1.1/brotli-8633-ab22a1.err
### stdout ###
# make[1]: Entering directory `/home/travis/.opam/system/build/brotli.1.1/libbrotli'
# [...]
#   CXX    brotli/enc/libbrotlienc_la-compress_fragment.lo
#   CXX    brotli/enc/libbrotlienc_la-compress_fragment_two_pass.lo
#   CXXLD  libbrotlienc.la
# make[1]: Leaving directory `/home/travis/.opam/system/build/brotli.1.1/libbrotli'
# make[1]: Entering directory `/home/travis/.opam/system/build/brotli.1.1/libbrotli'
# test -z "/usr/local/lib" || /bin/mkdir -p "/usr/local/lib"
#  /bin/bash ./libtool   --mode=install /usr/bin/install -c   libbrotlidec.la libbrotlienc.la '/usr/local/lib'
# libtool: install: /usr/bin/install -c .libs/libbrotlidec.so.1.0.0 /usr/local/lib/libbrotlidec.so.1.0.0
# make[1]: Leaving directory `/home/travis/.opam/system/build/brotli.1.1/libbrotli'
### stderr ###
# Cloning into 'libbrotli'...
# Cloning into 'brotli'...
# configure.ac:8: installing `./missing'
# Makefile.am: installing `./depcomp'
# /usr/bin/install: cannot create regular file `/usr/local/lib/libbrotlidec.so.1.0.0': Permission denied
# make[1]: *** [install-libLTLIBRARIES] Error 1
# make: *** [install-am] Error 2
# E: Failure("Command 'sh prepare.sh' terminated with error code 2")
```

**Comment by damiendoligez** [comment]
Permission denied while installing? Either the package does something that's forbidden (like installing in `/usr/local/lib` instead of putting all its files under `$OPAMROOT`) or the test machine is set up wrong (not having write permission on `/usr/local`).

In either case, I can't do much to debug the problem, which doesn't seem related to my patch.

**Comment by OCamlPro-Henry** [comment]
You are right. It is not CI setup error though, I can't compile the package on my computer also. I will merge and open an issue.

**Comment by OCamlPro-Henry** [comment]
Thanks for the adding the version constraint.

**Pull request merged**
