### PR TITLE
cohttp.6.0.0~alpha0 uses the bytes library

### PR DESCRIPTION
**Pull request by emillon**
Adjust constraint accordingly.

### CODE REVIEW

**Comment by emillon** [comment]
I believe that's the right rune but it's the first time I'm doing it.

**Comment by mseri** [comment]
Do you have the log of the error, I can fix it upstream before the next release

**Comment by emillon** [comment]
Oops, sorry:

```
#=== ERROR while compiling cohttp.6.0.0~alpha0 ================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/cohttp.6.0.0~alpha0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p cohttp -j 31 --promote-install-files=false @install
# exit-code            1
# env-file             ~/.opam/log/cohttp-7-a468f1.env
# output-file          ~/.opam/log/cohttp-7-a468f1.out
### output ###
# File "cohttp/src/dune", line 19, characters 2-7:
# 19 |   bytes
#        ^^^^^
# Error: Library "bytes" not found.
# -> required by library "cohttp" in _build/default/cohttp/src
# -> required by _build/default/META.cohttp
# -> required by _build/install/default/lib/cohttp/META
# -> required by _build/default/cohttp.install
# -> required by alias install
```

So the upstream fix is likely to just remove `bytes` from `libraries`.

**Comment by mseri** [comment]
I am suprised that if fails with `dune >= 2.9`. We used the following fix in the past in the opam metadata:
```
("dune" {>= "1.4.0"} | "dune" {< "1.4.0"} & "base-bytes")
```
So this one should have worked. Does it have to do with further changes in dune?

**Comment by emillon** [comment]
I don't think so, but I'm not completely up to date about what changed in 5.0. Possibly the compiler-provided META files (that dune uses if dune >= 2.9-ish and ocaml >= 5) do not include bytes? 

In any case, this seems to be similar to #23012 for example which would fail with a recent dune too.

**Comment by mseri** [comment]
Thanks, I updated the wiki to mention the need for both changes.

**Comment by mseri** [comment]
Cohttp top fails with
```
[14:14](https://ocamllabs.slack.com/archives/C0483TAL30F/p1675948443818109)

#=== ERROR while compiling cohttp-top.1.0.0 ===================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/cohttp-top.1.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build jbuilder build -p cohttp-top -j 47
# exit-code            1
# env-file             ~/.opam/log/cohttp-top-7-495c32.env
# output-file          ~/.opam/log/cohttp-top-7-495c32.out
### output ###
# File "/home/opam/.opam/4.14/lib/cohttp/META", line 1, characters 0-0:
# Error: Library "bytes" not found.
# -> required by library "cohttp" in /home/opam/.opam/4.14/lib/cohttp
# Hint: try: jbuilder external-lib-deps --missing -p cohttp-top @install
```

**Comment by mseri** [comment]
All other failures are addressed in separate PRs

**Comment by mseri** [comment]
Thanks

**Pull request merged**
