### PR TITLE
make the why package depend on conf-autoconf

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by avsm** [comment]
bulk build results with this patch: https://github.com/avsm/opam-pr-build-results/blob/6023/README.md

**Comment by UnixJunkie** [comment]
Thanks for the details.
The problem is that many opam packages are currently broken (and you realize it when
you try to improve older packages).
I start to understand why people told that opam builds are not so reproducible.
I guess that at the time a package is published, it is OK.
But then its dependencies evolve and break it.
Maybe one way to solve this would be to check that when package P is published, all versions of all the packages that depend on P need to be rebuilt. If they cannot be rebuilt, then a version constraint
should be added to them (depends on P but with version strictly less than the current P).
Same thing for a new compiler version: all versions of all packages not compiling with the new compiler should be added an ocaml version constraint.

**Comment by samoht** [comment]
@UnixJunkie: The current infrastructure doesn't allow to run reverse dependency goals for all the package, but yes the goal is to eventually reach that point. @avsm shiny new bulk build infrastructure will help us in going forward in that direction.

**Comment by samoht** [comment]
```
#=== ERROR while installing why.2.34 ==========================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/system/build/why.2.34
# compiler     system (4.02.3)
# exit-code    2
# env-file     /home/travis/.opam/system/build/why.2.34/why-10260-f53971.env
# stdout-file  /home/travis/.opam/system/build/why.2.34/why-10260-f53971.out
# stderr-file  /home/travis/.opam/system/build/why.2.34/why-10260-f53971.err
### stdout ###
# [...]
# Ocamlopt java/java_callgraph.ml
# Ocamlopt java/java_analysis.ml
# Ocamlopt java/java_interp.ml
# Ocamlopt java/java_main.ml
# Linking  bin/krakatoa.opt
# strip    bin/krakatoa.opt
# coqc  -R lib/coq Why lib/coq/WhyInt.v
# coqc  -R lib/coq Why lib/coq/WhyArrays.v
# coqc  -R lib/coq Why lib/coq/WhyBool.v
# coqc  -R lib/coq Why lib/coq/WhyTuples.v
### stderr ###
# [...]
# Use Bytes.set instead.
# File "jc/jc_region.ml", line 48, characters 10-23:
# Warning 3: deprecated: String.create
# Use Bytes.create instead.
# File "jc/jc_region.ml", line 49, characters 37-47:
# Warning 3: deprecated: String.set
# Use Bytes.set instead.
# File "./lib/coq/WhyTuples.v", line 26, characters 23-26:
# Error: Cannot infer the implicit parameter A of fst whose type is "Type".
# make: *** [lib/coq/WhyTuples.vo] Error 1
```

**Comment by UnixJunkie** [comment]
I need to patch some coq code. I did it locally and it worked.

**Comment by samoht** [comment]
```
#=== ERROR while installing why.2.33 ==========================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/system/build/why.2.33
# compiler     system (4.01.0)
# exit-code    2
# env-file     /home/travis/.opam/system/build/why.2.33/why-10518-428508.env
# stdout-file  /home/travis/.opam/system/build/why.2.33/why-10518-428508.out
# stderr-file  /home/travis/.opam/system/build/why.2.33/why-10518-428508.err
### stdout ###
# [...]
# ocamlc.opt  -I atp -c -w Z -dtypes -g -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/travis/.opam/system/lib/lablgtk2 -I +threads -I /home/travis/.opam/system/lib/ocamlgraph src/why3_kw.mli
# ocamlopt.opt  -I atp -c -w Z -dtypes -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/travis/.opam/system/lib/lablgtk2 -I +threads -I /home/travis/.opam/system/lib/ocamlgraph -for-pack Jc src/why3_kw.ml
# ocamlc.opt  -I atp -c -w Z -dtypes -g -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/travis/.opam/system/lib/lablgtk2 -I +threads -I /home/travis/.opam/system/lib/ocamlgraph src/why3.mli
# ocamlopt.opt  -I atp -c -w Z -dtypes -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/travis/.opam/system/lib/lablgtk2 -I +threads -I /home/travis/.opam/system/lib/ocamlgraph src/why3.ml
# ocamlc.opt  -I atp -c -w Z -dtypes -g -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/travis/.opam/system/lib/lablgtk2 -I +threads -I /home/travis/.opam/system/lib/ocamlgraph src/pretty.mli
# ocamlopt.opt  -I atp -c -w Z -dtypes -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/travis/.opam/system/lib/lablgtk2 -I +threads -I /home/travis/.opam/system/lib/ocamlgraph src/pretty.ml
# ocamlopt.opt  -I atp -c -w Z -dtypes -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/travis/.opam/system/lib/lablgtk2 -I +threads -I /home/travis/.opam/system/lib/ocamlgraph src/unionfind.ml
# ocamlopt.opt  -I atp -c -w Z -dtypes -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/travis/.opam/system/lib/lablgtk2 -I +threads -I /home/travis/.opam/system/lib/ocamlgraph src/theoryreducer.ml
# ocamlopt.opt  -I atp -c -w Z -dtypes -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/travis/.opam/system/lib/lablgtk2 -I +threads -I /home/travis/.opam/system/lib/ocamlgraph src/theory_filtering.ml
# ocamlopt.opt  -I atp -c -w Z -dtypes -I src -I jc -I c -I java -I intf -I tools -I mix -I ml -I /home/travis/.opam/system/lib/lablgtk2 -I +threads -I /home/travis/.opam/system/lib/ocamlgraph src/hypotheses_filtering.ml
### stderr ###
# 1 shift/reduce conflict.
# 1 shift/reduce conflict, 24 reduce/reduce conflicts.
# /home/travis/.opam/system/lib/frama-c/share/frama-c/Makefile.dynamic:288: .depend: No such file or directory
# File "src/hypotheses_filtering.ml", line 1699, characters 32-33:
# Error: Signature mismatch:
#        ...
#        The field `edge' is required but not provided
# make: *** [src/hypotheses_filtering.cmx] Error 2
```

**Comment by UnixJunkie** [comment]
I think I will give up on that package. It has too many deps and looking by hand for version constraints
is boring, time consuming and dumb. Also, the why package is superseded by the why3 package.
I might close this pull request.

**Comment by samoht** [comment]
I'm fine to merge it as it is an improvement anyway.

**Comment by samoht** [comment]
The only issue is with the regression in 1.2.0 (which make the `why` package not available):

```
[ERROR] At ~/.opam/repo/default/packages/why/why.2.31/opam:11:64:
  Not a recognised version-control URL
[ERROR] At ~/.opam/repo/default/packages/why/why.2.32/opam:11:64:
  Not a recognised version-control URL
[ERROR] At ~/.opam/repo/default/packages/why/why.2.33/opam:12:64:
  Not a recognised version-control URL
[ERROR] At ~/.opam/repo/default/packages/why/why.2.34/opam:12:64:
  Not a recognised version-control URL
[ERROR] At ~/.opam/repo/default/packages/why/why.2.35/opam:11:64:
  Not a recognised version-control URL
```

**Comment by UnixJunkie** [comment]
Fixed.

**Comment by UnixJunkie** [comment]
@samoht  Should I do something else in here?

**Comment by lefessan** [comment]
Do you really need "autoconf" to install the package, or for dev-repo ? A lot of packages

**Comment by lefessan** [comment]
Sorry for the noise, I pushed the wrong button. Thanks anyway !

**Pull request merged**
