### PR TITLE
mirage-entropy-*: add dependency on camlp4

### PR DESCRIPTION
**Pull request by damiendoligez**
These need lwt.syntax, which implies camlp4.

### CODE REVIEW

**Comment by samoht** [comment]
weird errors, any idea @hannesm or @pqwy 

```
#=== ERROR while installing mirage-entropy-unix.0.1.6 =========================#
# opam-version 1.2.2
# os           linux
# command      make unix-build
# path         /home/travis/.opam/4.04.0+beta2/build/mirage-entropy-unix.0.1.6
# compiler     4.04.0+beta2
# exit-code    2
# env-file     /home/travis/.opam/4.04.0+beta2/build/mirage-entropy-unix.0.1.6/mirage-entropy-unix-14253-4937ca.env
# stdout-file  /home/travis/.opam/4.04.0+beta2/build/mirage-entropy-unix.0.1.6/mirage-entropy-unix-14253-4937ca.out
# stderr-file  /home/travis/.opam/4.04.0+beta2/build/mirage-entropy-unix.0.1.6/mirage-entropy-unix-14253-4937ca.err
### stdout ###
# Hint: Recursive traversal of subdirectories was not enabled for this build,
# [...]
#   '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
#   you should add the option "-r" or create an empty '_tags' file.
#   
#   To enable recursive traversal for some subdirectories only, you can use the
#   following '_tags' file:
#   
#       true: -traverse
#       <dir1> or <dir2>: traverse
#       
### stderr ###
# make: *** [unix-build] Error 10
```

**Comment by damiendoligez** [comment]
mirage-entropy-unix.0.1.6 needs module `V1_LWT.ENTROPY`, which is provided by mirage-types from 1.2.0 to 2.3.0.

**Comment by hannesm** [comment]
looks like job number 5 needs a restart...

**Comment by samoht** [comment]
Restarted!

**Comment by hannesm** [comment]
@samoht thx, now travis is also happy! \o/

**Pull request merged**
