### PR TITLE
Replace xapi-xenopsd.0.9.44 with 0.9.44.1

### PR DESCRIPTION
**Pull request by djs55**
0.9.44 had a latent missing build dependency which was only exposed when
a dependency changed its build deps.

See [xapi-project/xenopsd#161]

### CODE REVIEW

**Comment by djs55** [comment]
Since I re-released 0.9.44, I also removed the -warn-error stuff so we don't need the patch any more.

**Comment by djs55** [comment]
Looks like an intermittent travis problem?
```
W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/main/i18n/Translation-en_US  Unable to connect to www.rabbitmq.com:http:
W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/main/i18n/Translation-en  Unable to connect to www.rabbitmq.com:http:
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "bash -e .travis-ci-install.sh" failed and exited with 100 during .
```

**Comment by yallop** [comment]
I've restarted the jobs.

**Comment by djs55** [comment]
Thanks @yallop!

**Pull request merged**
