### PR TITLE
Add LLVM 3.7

### PR DESCRIPTION
**Pull request by jpdeplaix**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Mmmh it wasn't supposed to be merge yet. All tests failed

**Comment by avsm** [comment]
I've been merging these without CI due to the manual troubles with LLVM on Ubuntu 12.04 -- do you want it reverted?

**Comment by jpdeplaix** [comment]
Yes, if you can it would be nice.

**Comment by jpdeplaix** [comment]
In fact, I was to lazy to check if it works on my machine so I used travis for this.
Turns out it doesn't work at all and needs some fixes. I'm sorry.

**Pull request merged**
