### PR TITLE
Update opam for typebeat

### PR DESCRIPTION
**Pull request by dinosaure**
Typebeat need an update from `angstrom` which breaks API.

### CODE REVIEW

**Comment by jpdeplaix** [comment]
The fix doesn't seem quite right:
```
#=== ERROR while installing typebeat.0.2 ======================================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -p typebeat -j 2
# path                 /home/opam/.opam/4.05.0/build/typebeat.0.2
# compiler             4.05.0
# exit-code            1
# env-file             /home/opam/.opam/4.05.0/build/typebeat.0.2/typebeat-7-e01aa9.env
# stdout-file          /home/opam/.opam/4.05.0/build/typebeat.0.2/typebeat-7-e01aa9.out
# stderr-file          /home/opam/.opam/4.05.0/build/typebeat.0.2/typebeat-7-e01aa9.err
### stderr ###
#       ocamlc lib/.TypeBeat.objs/TypeBeat__Rfc2045.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.TypeBeat.objs -I /home/opam/.opam/4.05.0/lib/angstrom -I /home/opam/.opam/4.05.0/lib/bytes -I /home/opam/.opam/4.05.0/lib/cstruct -I /home/opam/.opam/4.05.0/lib/ocplib-endian -I /home/opam/.opam/4.05.0/lib/result -I /home/opam/.opam/4.05.0/lib/sexplib -I /home/opam/.opam/4.05.0/lib/sexplib/0 -no-alias-deps -open TypeBeat__ -o lib/.TypeBeat.objs/TypeBeat__Rfc2045.cmo -c -impl lib/rfc2045.ml)
# File "lib/rfc2045.ml", line 71, characters 8-20:
# Error: Unbound value parse_string
```

**Comment by dinosaure** [comment]
If this last commit does not work, I will replace this package by a new version.

**Comment by hannesm** [comment]
travis fails with:
```
# File "lib/typeBeat.ml", line 126, characters 23-43:
# Error: This expression has type
#          off:int -> len:int -> 'a Angstrom.Unbuffered.state
#        but an expression was expected of type 'a Angstrom.Unbuffered.state
#     ocamlopt lib/.TypeBeat.objs/typeBeat.{cmx,o} (exit 2)
# (cd _build/default && /home/travis/.opam/4.03.0/bin/ocamlopt.opt -w -40 -g -I lib/.TypeBeat.objs -I /home/travis/.opam/4.03.0/lib/angstrom -I /home/travis/.opam/4.03.0/lib/result -no-alias-deps -open TypeBeat__ -o lib/.TypeBeat.objs/typeBeat.cmx -c -impl lib/typeBeat.ml)
# File "lib/typeBeat.ml", line 126, characters 23-43:
# Error: This expression has type
#          off:int -> len:int -> 'a Angstrom.Unbuffered.state
```

**Comment by hannesm** [comment]
@dinosaure I suspect there are some `angstrom` upper bounds missing for `typebeat`, and yes, please prepare a new `typebeat` release if that works with a more modern `angstrom` :)

**Comment by dinosaure** [comment]
Ya, sorry for the delay, I will fix it tomorrow 👍

**Comment by dinosaure** [comment]
Ok same problem as before, hash is not the same ...

**Comment by hannesm** [comment]
thanks!

**Pull request merged**
