### PR TITLE
irmin-chunk with-test requires mtime

### PR DESCRIPTION
**Pull request by aantron**
See this [build log](https://ci.ocaml.org/log/saved/docker-run-3a0c071cdef49ba573c132aa881a3a2a/5e6994cb709c03eeaa17503a0ade11025f85b758).

### CODE REVIEW

**Comment by aantron** [comment]
cc @samoht

**Comment by samoht** [comment]
The tests seem to require `irmin.1.3.0` to compile, so it's probably just simpler to completely disable them here.

**Comment by kit-ty-kate** [comment]
> The tests seem to require `irmin.1.3.0` to compile, so it's probably just simpler to completely disable them here.

I don't really see why. If someone wants to test it locally they can still do it

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by samoht** [comment]
@kit-ty-kate irmin.1.4.0 + irmin-chunk.1.3.0 causes:

```
#=== ERROR while compiling irmin-chunk.1.3.0 ==================================#
# context     2.0.5 | linux/x86_64 | ocaml-system.4.09.0 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-system/.opam-switch/build/irmin-chunk.1.3.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build jbuilder runtest -p irmin-chunk
# exit-code   1
# env-file    ~/.opam/log/irmin-chunk-23039-05525a.env
# output-file ~/.opam/log/irmin-chunk-23039-05525a.out
### output ###
# [...]
# Note: You can use "dune upgrade" to convert your project to dune.
# File "test/irmin-unix/jbuild", line 1, characters 0-0:
# Warning: jbuild files are deprecated, please convert this file to a dune file
# instead.
# Note: You can use "dune upgrade" to convert your project to dune.
#       ocamlc test/common/.test.objs/byte/test_store.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /usr/local/bin/ocamlc.opt -w -40 -g -bin-annot -I test/common/.test.objs/byte -I /home/travis/.opam/ocaml-system/lib/alcotest -I /home/travis/.opam/ocaml-system/lib/astring -I /home/travis/.opam/ocaml-system/lib/bigarray-compat -I /home/travis/.opam/ocaml-system/lib/bytes -I /home/travis/.opam/ocaml-system/lib/cmdliner -I /home/travis/.opam/ocaml-system/lib/cstruct -I /h[...]
# File "test/common/test_store.ml", line 90, characters 24-27:
# 90 |     S.Tree.of_hash repo kn2 >>= function
#                              ^^^
# Error: This expression has type Graph.node = S.Tree.Hash.t
#        but an expression was expected of type S.Tree.hash`
```

**Pull request merged**
