### PR TITLE
Fix build failure with ppx_deriving_yojson.3.1 & ppx_deriving.4.2

### PR DESCRIPTION
**Pull request by jpdeplaix**
Spotted here: https://arm64.ci.ocamllabs.io/log/saved/docker-build-42232c66a676dbb042e6d1c0958b088f/f15b0ec933b40635af510546c1ec8c968128e18d

cc @gasche since it seems you are the maintainer.

### CODE REVIEW

**Comment by gasche** [comment]
Thanks for the notice. I think this is not the right fix (it's about an interference with OCaml versions, and I would feel better with an upper-bound rather than a single conflict-clause, what if we release ppx_deriving 4.2.1 later?), I'm looking at it to make a suggestion.

**Comment by gasche** [comment]
I looked deeper into the issue and I am more convinced now that your proposed fix is a correct choice :-) Still looking...

**Comment by jpdeplaix** [comment]
```ppx_deriving.4.2.1``` is already released with a fix for that so nothing to do on your side. It's just an old version that had not the right constraints.

**Comment by jpdeplaix** [comment]
Sorry I should have let you a small note that summarizes that.

**Comment by jpdeplaix** [comment]
hum actually the only thing that you can do on your side is to report the constraint in the ```ppx_deriving_yojson``` repo.

**Comment by gasche** [comment]
I managed to reproduce the issue at home. ppx_deriving_yojson.3.1 depends on https://github.com/ocaml-ppx/ppx_deriving/pull/156, which is merged in 4.1 and 4.2.1, but not in 4.2.0. (This PR makes no difference on OCaml versions 4.04 and below, it only changes type for 4.05 and above, and 4.06 was not previously supported by most ppx_deriving plugins.)

I believe your fix is correct and will reproduce it upstream. Thanks!

**Pull request merged**
