### PR TITLE
duplicate suse deps for opensuse

### LINKED ISSUE #17004: Duplicate depexts for suse/opensuse
See https://github.com/ocaml/opam-repository/pull/16864
@anuragsoni I have created this issue as a reminder, no pressure. There is no hurry

### PR DESCRIPTION
**Pull request by anuragsoni**
diff created via

```
rg 'os-family = "suse"' -l | xargs sed -i.'bak' -n 'p; s/os-family = "suse"/os-family = "opensuse"/p'
git clean -f
```
* ripgrep to search for files that contain os details for suse
* -n in sed prevents lines from printing unless it is explicitly printed
* p in the sed pattern forces printing if there is a match
* `git clean -f` to remove the backup files created by sed

closes #17004

### CODE REVIEW

**Comment by mseri** [comment]
I am trying to understand why it says “ removed installable packages (1): pa_ppx.0.01”. 
@kit-ty-kate who has access to camelus logs?

**Comment by XVilka** [comment]
What about just making it a synonym or the same family in opam. I believe, there is a minimum difference between them, like in many distributions in "debian" family.

**Comment by mseri** [comment]
@rjbou is that feasible or you think it would be better to duplicate?

**Comment by XVilka** [comment]
Nevermind, it should be already the same: https://github.com/ocaml/opam/blob/6aefe95e60084e63d01b1c7c028b6b77de1f839f/src/state/opamSysInteract.ml#L117

**Comment by rjbou** [comment]
@mseri Yes, in current implementation it is the same (code pointed by @XVilka). If in the future, there is a need to have  different depext treatment, it can be split.

**Comment by anuragsoni** [comment]
@XVilka @rjbou Thanks for pointing out the alias handling. I hadn't tried opam 2.1.0's alpha version where this aliasing seems to be present, and for some reason when i was searching in the codebase i only looked under the 2.0.7 tag 😄 

I'll close this PR, as the alias should be good. From what i've seen so far the package names have been the same on opensuse tumbleweed and opensuse leap (I think leap is what eventually becomes the commercial suse distribution so the names must be similar there as well).

If i run into any issues about this i'll open issues and work on fixing them at the opam repository.

Thanks!

**Comment by rjbou** [comment]
@anuragsoni opam 2.1.0~alpha integrated external dependencies handling opam 2.0.x, it still rely on `opam-depext` plugin, it also handles `suse` & `opensuse` the [same way](https://github.com/ocaml-opam/opam-depext/blob/2.0/depext.ml#L168).

**Comment by rjbou** [comment]
If you have the opportunity, please give a try to 2.1.0 (beta just released) & test the opensuse/suse depext handling in opam. Open an [issue](https://github.com/ocaml/opam/issues) if there things to fix. Thanks!

**Comment by anuragsoni** [comment]
Thanks @rjbou 
I'll switch to the 2.1.0 beta. I was looking forward to the newer lockfile and depext handling so this is a good time to try it :)

**Pull request closed without merging**
