### PR TITLE
2 packages from LexiFi/gen_js_api at 1.1.2

### PR DESCRIPTION
**Pull request by nojb**
This pull-request concerns:
- `gen_js_api.1.1.2`: Easy OCaml bindings for JavaScript libraries
- `ojs.1.1.2`: Runtime Library for gen_js_api generated libraries

---
* Homepage: https://github.com/LexiFi/gen_js_api
* Source repo: git+https://github.com/LexiFi/gen_js_api.git
* Bug tracker: https://github.com/LexiFi/gen_js_api/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by zeroexcuses** [comment]
Dumb question. I'm done a "opam update; opam search gen_js_api" but it still shows 1.1.1 .

Besides checking out from git, is there a way to install 1.1.2 ?

Thanks!

**Comment by nojb** [comment]
> Besides checking out from git, is there a way to install 1.1.2 ?

Yes: waiting for this PR to be merged and then re-doing `opam update; opam install gen_js_api` :)

**Comment by nojb** [comment]
By the way, the CI seems somewhat stuck...

**Comment by zeroexcuses** [comment]
Will install via git. Thanks!

**Comment by zeroexcuses** [comment]
Is some variant of:
```
opam pin add gen_js_api https://github.com/LexiFi/gen_js_api/tree/v1.1.2
```
possible ? I.e. I want to pin the git repo, but not the most recent commit, and version 1.1.2 instead

**Comment by zeroexcuses** [comment]
Progress: how do I get ojs 

```
 opam pin add gen_js_api https://github.com/LexiFi/gen_js_api.git#v1.1.2
[gen_js_api.1.1.1] synchronised (git+https://github.com/LexiFi/gen_js_api.git#v1.1.2)
gen_js_api is now pinned to git+https://github.com/LexiFi/gen_js_api.git#v1.1.2 (version 1.1.2)

[NOTE] External dependency handling not supported for OS family 'nixos'.
       You can disable this check using 'opam option --global depext=false'
[ERROR] Package conflict!
  * Missing dependency:
    - ojs >= 1.1.2
    no matching version

[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

**Comment by nojb** [comment]
> Progress: how do I get ojs

It is available in the same repository.

**Comment by raphael-proust** [comment]
The CI failures are all installation of system packages and are unrelated to the code here. I think one of them looks weird and might warrant a closer look (see below) but shouldn't stop merging this PR.

```

The following system packages will first need to be installed:
    npm

<><> Handling external dependencies <><><><><><><><><><><><><><><><><><><><><><>

opam believes some required external dependencies are missing. opam can:
> 1. Run apk to install them (may need root/sudo access)
  2. Display the recommended apk command and wait while you run it manually (e.g. in another terminal)
  3. Attempt installation anyway, and permanently register that this external dependency is present, but not detectable
  4. Abort the installation

[1/2/3/4] 1

+ /usr/bin/sudo "apk" "add" "npm"
- (1/6) Installing c-ares (1.18.1-r0)
- (2/6) Installing icu-data-en (71.1-r2)
- Executing icu-data-en-71.1-r2.post-install
- *
- * If you need ICU with non-English locales and legacy charset support, install
- * package icu-data-full.
- *
- (3/6) Installing icu-libs (71.1-r2)
- (4/6) Installing libuv (1.44.1-r0)
- (5/6) Installing nodejs-current (18.9.1-r0)
- (6/6) Installing npm (8.10.0-r0)
- Executing busybox-1.35.0-r17.trigger
- OK: 277 MiB in 80 packages

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of conf-npm.1 failed at "npm --version".
```

Maybe the definition of `conf-npm` is wrong for alpine?

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
