### PR TITLE
brotli.0.1 - via opam-publish

### PR DESCRIPTION
**Pull request by fxfactorial**
Bindings to Google's Brotli compresion algorithm

Source: https://github.com/google/brotli/
RFC: http://www.ietf.org/id/draft-alakuijala-brotli

Comes with command line tool called brozip

---
* Homepage: http://hyegar.com
* Source repo: https://github.com/fxfactorial/ocaml-brotli.git
* Bug tracker: https://github.com/fxfactorial/ocaml-brotli/issues

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by fxfactorial** [comment]
@avsm The build machines seriously don't have python3!?

**Comment by avsm** [comment]
Why's this closed?

**Comment by fxfactorial** [comment]
I forgot about the trick to redo tagging.

**Comment by avsm** [comment]
> @avsm The build machines seriously don't have python3!?

The build VMs use Travis CI, which only provides Ubuntu Precise at this time.  There is a new Docker-based container infrastructure available now that should allow Trusty to be used, but we're still testing it.  So in the meanwhile, just specifying the Ubuntu Precise `python3` package in the `depexts` field for Ubuntu will make it available.

**Comment by fxfactorial** [comment]
I don't specifically need python3, I just try to default to it on any new python code.

**Pull request closed without merging**
