### PR TITLE
Package zarith.1.11

### PR DESCRIPTION
**Pull request by antoinemine**
### `zarith.1.11`
Implements arithmetic and logical operations over arbitrary-precision integers
The Zarith library implements arithmetic and logical operations over
arbitrary-precision integers. It uses GMP to efficiently implement
arithmetic over big integers. Small integers are represented as Caml
unboxed integers, for speed and space economy.

---
* Homepage: https://github.com/ocaml/Zarith
* Source repo: git+https://github.com/ocaml/Zarith.git
* Bug tracker: https://github.com/ocaml/Zarith/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by mseri** [comment]
Thanks! I'll wait for the CI on the other PR before merging then

**Comment by hhugo** [comment]
fixes https://github.com/ocaml/Zarith/issues/82

**Comment by mseri** [comment]
There is only one failure which seems unrelated: https://ci.ocaml.org/log/saved/docker-run-d1484d1d0fecb2706a6a3f6ee1ae7e38/e7cea079b43788197c5800e46625e5e5a38bfab4
Can you also have a look?

**Comment by hhugo** [comment]
@mseri, this is just breaking a test reported here https://github.com/Dean177/reason-standard/issues/10

**Comment by antoinemine** [comment]
OK, I see the problem. We changed `of_string` in Zarith 1.11 to be accept strings with underscores. I consider this an improvement as it brings compatibility with the `int_of_string` from OCaml. But it can introduce incompatibilities with 1.10... 
Reason tests that Zarith does not accept string `123_456` as valid; it did not, now it does. 
We have to see with the folks at Reason how we should proceed about this. Hopefully, they can accept the new behavior and change the test.

**Comment by kit-ty-kate** [comment]
All green now. Thanks!

**Pull request merged**
