### PR TITLE
iocaml 0.4.9

### PR DESCRIPTION
**Pull request by andrewray**
compatibility with cohttp.0.21.0

### CODE REVIEW

**Comment by avsm** [comment]
woops crossed the beams with #6876 -- are the earlier versions of iocaml compatible with 0.21.0?

**Comment by andrewray** [comment]
Almost certainly not, but I'm not yet sure exactly what bounds are appropriate (< 0.4.7).  I'm working through a few different builds to find out.

**Comment by andrewray** [comment]
It seems not to matter for the earlier packages - they depend on websocket.0.9.x which constrains us to older cohttp anyway.

**Comment by OCamlPro-Henry** [comment]
The CI failure is a timeout on macOS. Merging.

**Pull request merged**
