### PR TITLE
added packages/molenc/molenc.7.0.1

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
CI tests are failing; I will cut the dependency to parmap.

**Comment by kit-ty-kate** [comment]
Your package fails to build with OCaml < 4.08:
```

#=== ERROR while compiling molenc.7.0.0 =======================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.04.2 | pinned(https://github.com/UnixJunkie/molenc/archive/v7.0.0.tar.gz)
# path                 ~/.opam/4.04/.opam-switch/build/molenc.7.0.0
# command              ~/.opam/4.04/bin/dune build -p molenc -j 72
# exit-code            1
# env-file             ~/.opam/log/molenc-23-0b28de.env
# output-file          ~/.opam/log/molenc-23-0b28de.out
### output ###
#       ocamlc src/.encoder.eobjs/byte/decoder.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.04/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.encoder.eobjs/byte -I /home/opam/.opam/4.04/lib/batteries -I /home/opam/.opam/4.04/lib/bst -I /home/opam/.opam/4.04/lib/bytes -I /home/opam/.opam/4.04/lib/cpm -I /home/opam/.opam/4.04/lib/cpu -I /home/opam/.opam/4.04/lib/dokeysto -I /home/opam/.opam/4.04/lib/dolog -I /home/opam/.opam/4.04/lib/equeue -I /home/opam/.opam/4.04/lib/extunix -I /home/opam/.opam/4.04/lib/minicli -I /home/opam/.opam/4.04/lib/netcamlbox -I /home/opam/.opam/4.04/lib/netmulticore -I /home/opam/.opam/4.04/lib/netplex -I /home/opam/.opam/4.04/lib/netstring -I /home/opam/.opam/4.04/lib/netsys -I /home/opam/.opam/4.04/lib/num -I /home/opam/.opam/4.04/lib/ocaml/threads -I /home/opam/.opam/4.04/lib/parany -I /home/opam/.opam/4.04/lib/rpc -I src/.molenc.objs/byte -I src/.molenc.objs/native -no-alias-deps -o src/.encoder.eobjs/byte/decoder.cmo -c -impl src/decoder.ml)
# File "src/decoder.ml", line 153, characters 17-31:
# Error: Unbound module Option

-       ocamlc src/.encoder.eobjs/byte/decoder.{cmi,cmo,cmt} (exit 2)
- (cd _build/default && /home/opam/.opam/4.04/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.encoder.eobjs/byte -I /home/opam/.opam/4.04/lib/batteries -I /home/opam/.opam/4.04/lib/bst -I /home/opam/.opam/4.04/lib/bytes -I /home/opam/.opam/4.04/lib/cpm -I /home/opam/.opam/4.04/lib/cpu -I /home/opam/.opam/4.04/lib/dokeysto -I /home/opam/.opam/4.04/lib/dolog -I /home/opam/.opam/4.04/lib/equeue -I /home/opam/.opam/4.04/lib/extunix -I /home/opam/.opam/4.04/lib/minicli -I /home/opam/.opam/4.04/lib/netcamlbox -I /home/opam/.opam/4.04/lib/netmulticore -I /home/opam/.opam/4.04/lib/netplex -I /home/opam/.opam/4.04/lib/netstring -I /home/opam/.opam/4.04/lib/netsys -I /home/opam/.opam/4.04/lib/num -I /home/opam/.opam/4.04/lib/ocaml/threads -I /home/opam/.opam/4.04/lib/parany -I /home/opam/.opam/4.04/lib/rpc -I src/.molenc.objs/byte -I src/.molenc.objs/native -no-alias-deps -o src/.encoder.eobjs/byte/decoder.cmo -c -impl src/decoder.ml)
- File "src/decoder.ml", line 153, characters 17-31:
- Error: Unbound module Option
```

**Comment by UnixJunkie** [comment]
This should be solved now.
Option -> BatOption.
I retagged the software to 7.0.1.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
