### PR TITLE
Add Why3 0.88.0

### PR DESCRIPTION
**Pull request by silene**

### CODE REVIEW

**Comment by silene** [comment]
For the "Common Distros" tests, CentOS7 fails because `yum` says "No package gtksourceview2-devel available", I don't think there is anything I can do about that. For the "All Distros" tests, I have no idea what "depfail" means. Finally, all the `opam lint` warnings are about old Why3 packages and not about Why3 0.88.0.

**Comment by gasche** [comment]
In fact marking your packages `< 4.06` when they don't support `-safe-string` is not very good for me, because it means that I will not be able to test them with beta releases of 4.06 (right now I do testing using the `-default-unsafe-string` which builds frama-C just fine, except for a regression that I wouldn't have caught if framaC had been marked "< 4.06"). Could you send just the 0.88 package for now? I'll ask people that know more about opam-packaging than I do about a better way to advertize that a package is not safe-string-compatible.

**Comment by gasche** [comment]
( I opened the issue #10420 to discuss the `< 4.06` issue. )

**Comment by silene** [comment]
> Could you send just the 0.88 package for now?

Note that there are two commits. The first one adds 0.88 without forcing it to be `< 4.6` only.

**Comment by gasche** [comment]
Yes, but I don't think I have the flexibility to pick only one commit if I click "merge", and tyran maintainers like to offload tedious git work to the submitters.

**Comment by silene** [comment]
I have now removed the second commit.

**Pull request merged**
