### PR TITLE
added packages/orxgboost/orxgboost.1.0.1

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Is this the same issue as with ```orsvm_e1071``` ?

**Comment by UnixJunkie** [comment]
It installs on the Mac at least.
At work, I use this package under Ubuntu.
I should probably add some conf-* packages because some of the R packages compile things (C or C++ or Fortran, depending on the R package). So, we should check for the presence of such compilers.
I am not at work these days so I cannot do it but I might in the following weeks.

**Comment by UnixJunkie** [comment]
can't this be accepted?

**Comment by kit-ty-kate** [comment]
Ok merging. If you could, later on, fix the package on linux it would be awesome !

**Comment by UnixJunkie** [comment]
I will look at it, but only for Debian/Ubuntu.
Interested users should contribute in order to support whatever exotic distro they fancy to use.

**Pull request merged**
