### PR TITLE
New project, new package: dune-deps 1.0.0

### PR DESCRIPTION
**Pull request by mjambon**
The project is at https://github.com/mjambon/dune-deps

### CODE REVIEW

**Comment by mjambon** [comment]
I see `Error: Unbound value Hashtbl.find_opt` on older ocaml versions. I'm on it.

**Comment by kit-ty-kate** [comment]
Your `dune-project` tells us that this project requires at least dune 2.1, moreover the use of `dune install` (previously called by `make install` in not necessary and should be avoided as much as possible as it uses ocamlfind internally amongst other issues).

This should be good to merge once the CI finishes. Could you return the fixes upstream?

**Comment by kit-ty-kate** [comment]
All good now. Thanks!

**Comment by mjambon** [comment]
Great. Thanks for the fixes!

**Pull request merged**
