### PR TITLE
2 packages from LexiFi/gen_js_api at 1.0.7

### PR DESCRIPTION
**Pull request by mlasson**
This pull-request concerns:
-`gen_js_api.1.0.7`: Easy OCaml bindings for JavaScript libraries
-`ojs.1.0.7`: Runtime Library for gen_js_api generated libraries

---
* Homepage: https://github.com/LexiFi/gen_js_api
* Source repo: git+https://github.com/LexiFi/gen_js_api.git
* Bug tracker: https://github.com/LexiFi/gen_js_api/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by mlasson** [comment]
I think the failure reported by opam-ci should be acceptable.

**Comment by kit-ty-kate** [comment]
i had a look at the remaining failures and the failure in `ocaml-js-stdlib` looks like a bug on `gen_js_api`'s side.
The code that fails is generated by `gen_js_api`, worked fine with `gen_js_api.1.0.6` but not with this new release.

The code is generated through a GADT https://github.com/dannywillems/ocaml-js-stdlib/blob/master/js_dom.mli#L203, are there things that changed between 1.0.6 and 1.0.7 in this part of the code?

**Comment by kit-ty-kate** [comment]
I've also sent a PR to fix the tests on Ubuntu 16.04 (and Centos 7 probably) https://github.com/LexiFi/gen_js_api/pull/141

**Comment by mlasson** [comment]
> i had a look at the remaining failures and the failure in `ocaml-js-stdlib` looks like a bug on `gen_js_api`'s side.
> The code that fails is generated by `gen_js_api`, worked fine with `gen_js_api.1.0.6` but not with this new release.
> The code is generated through a GADT https://github.com/dannywillems/ocaml-js-stdlib/blob/master/js_dom.mli#L203, are there things that changed between 1.0.6 and 1.0.7 in this part of the code?

Thanks for the detective work. 
I was aware of this issue ; I should have tell it to spare you the work. 
It is actually more a "Bug Fix" than a "Bug" ; the generated code was wrong even when it was compiling. 
This type should be removed from js_stdlib. 

Would it be possible to add a conflict with "gen_js_api > 1.0.6" in ocaml-js-stdlib ?

There's no support for GADT in gen_js_api. 

> I've also sent a PR to fix the tests on Ubuntu 16.04 (and Centos 7 probably): LexiFi/gen_js_api#141

For some reason, it breaks "macos-latest" CI: 
```
 dune build @runtest
File "node-test/test1/dune", line 12, characters 7-13:
12 |   (run nodejs %{dep:./test.bc.js})))
            ^^^^^^
Error: Program nodejs not found in the tree or in PATH
 (context: default)
```

Note that the node test requires a very recent version 
of node anyway ; so you will only allow the tests to 
fail (with an error message telling to upgrade to node 
> 12 ).

**Comment by mseri** [comment]
What is the state of this?Should we add an upper bound to `ocaml-js-stdlib` and merge? @kit-ty-kate would it be ok for you?

**Comment by kit-ty-kate** [comment]
Thanks! Sorry for the delay

**Pull request merged**
