### PR TITLE
Add proj4 0.9.2

### PR DESCRIPTION
**Pull request by hcarty**
Build updated to work with OCaml 4.06.0

### CODE REVIEW

**Comment by gasche** [comment]
@hcarty would you fix the opam-lint warning? Most github-hosted projects use the URL to their `/issues` page.

**Comment by hcarty** [comment]
@gasche Done, thanks!  And added an upper bound on the OCaml version for the older/existing release.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Comment by hcarty** [comment]
@avsm Done - thanks for the suggestion!

**Pull request merged**
