### PR TITLE
[new release] thread-local-storage (0.2)

### PR DESCRIPTION
**Pull request by c-cube**
Efficient thread local storage for OCaml

- Project page: <a href="https://github.com/c-cube/thread-local-storage">https://github.com/c-cube/thread-local-storage</a>
- Documentation: <a href="https://c-cube.github.io/thread-local-storage">https://c-cube.github.io/thread-local-storage</a>

##### CHANGES:

- Incompatible API change, making things simpler.
- It is now safe to read TLS from asynchronous callbacks (e.g. memprof
  callbacks).

### CODE REVIEW

**Comment by dinosaure** [comment]
Not sure how to interpret error but this release seems to introduce a breaking change for few packages. Should we put an upper bound on these package?

**Comment by c-cube** [comment]
Yes please, it is indeed a breaking API change.

**Comment by avsm** [comment]
Would you be able to push those upper bounds to this PR, @c-cube ?

**Comment by c-cube** [comment]
I thought y'all had tools for that :/

**Comment by shonfeder** [comment]
I don't have perms to add to this branch, nor is GitHub letting me make a PR into your fork @c-cube (not sure why), but you can merge in this branch to add the upper bounds here: https://github.com/shonfeder/opam-repository/tree/release-thread-local-storage-v0.2

That is created just by checking out your package release branch and running `opam admin add-constraint 'thread-local-storage<0.2'`

**Comment by c-cube** [comment]
thank you @shonfeder, I could do the same locally :)

**Comment by c-cube** [comment]
some of the failures are flaky tests, but I'm not sure why others still try to install, say, moonpool 0.6 when it's been marked as conflicting…

**Comment by avsm** [comment]
You also need to reapply the `dune subst` fixes from the other PR which have disappeared from this one... (see the lint failure)

**Comment by c-cube** [comment]
It's just a useless lint, can we bypass it please?

**Comment by dinosaure** [comment]
> It's just a useless lint, can we bypass it please?

Unfortunately, in order to offer a quality repository, this type of error must be avoided, as described here: https://github.com/ocaml/opam-repository/wiki/PR-checks#some-common-failures. 

We can ignore errors such as the moonpool error, which don't concern this release (but the package itself), but we feel it's essential to respect the `dune subst` rule to be as consistent as possible with what we've imposed on other contributors.

**Comment by c-cube** [comment]
Then stop imposing this particular lint to everyone! I'd bet that in 95% of cases it's only there because someone isn't imposing a recent version of dune, so the lint has no impact.

**Comment by dinosaure** [comment]
> It's just a useless lint, can we bypass it please?

> Then stop imposing this particular lint to everyone! I'd bet that in 95% of cases it's only there because someone isn't imposing a recent version of dune, so the lint has no impact.

To be more precise, the linter failed on your new `thread-local-storage` package and, like all new packages, we have to do a series of [checks][pr-check] before merging your pull-request - the linter is there to help us maintain a consistent repository (a feature far more important than this specific release). These checks apply to everyone (including myself) and there has never been any question of “bypassing” these tests for anyone. I'd also like to point out that I added a change myself to finally consider this release ready to be merged.

However, I'd like to point out that your answer isn't really appropriate and that, even though a release can take a long time (and can be a source of frustration):
1) I'd like to point out that, for many of us, we're doing this work for free and in our spare time.
2) our aim is to assist contributors, not to do their releases for them (e.g., identify a breaking-change and modify the repository accordingly)

I hope you'll keep these 2 points in mind for your next contributions, so as to have a minimum of consideration for our reviews and our merge process, which I invite you to read: [here][pr-check] and [here][policies]. If you have a specific problem with the various checks we make and/or our merge policy, I invite you to make an issue to discuss it more calmly.

[pr-check]: https://github.com/ocaml/opam-repository/wiki/PR-checks
[policies]: https://github.com/ocaml/opam-repository/wiki/Policies

**Comment by c-cube** [comment]
I appreciate the work of the opam repository volunteers, genuinely. At the same time it seems like this process is painful for everyone for totally avoidable reasons, including:
- overtly nitpicky _lints_ that are straight up conflicting with some existing tools (eg some versions of dune, like it's the case here)
- a culture of not adding upper bounds explicitly or proactively
- a culture of not enforcing semver like npm or cargo do, meaning tools cannot address this kind of breakage automatically.

I release my packages on opam-repo like I've done for more than a decade but I just wish it was less painful for me and volunteers is all.

**Pull request merged**
