### PR TITLE
Add ppx_bitstring 1.3.1

### PR DESCRIPTION
**Pull request by xguerin**

### CODE REVIEW

**Comment by yallop** [comment]
There's something wrong with the configuration: `make install` is trying to install into `/usr/local`

**Comment by xguerin** [comment]
That's odd. I'll look into it.

**Comment by xguerin** [comment]
Fixed, some black wizardry semantic interpret `[make "install"]` differently from `[make install]`.

**Comment by yallop** [comment]
> Fixed, some black wizardry semantic interpret [make "install"] differently from [make install].

It's fixed, but it's not working as it appears.

Unquoted names (like `make` or `install`, but not `"install"`) are treated as variables.  The variable `make` expands to whatever name the system uses for GNU make.  The variable `install` expands to nothing, since it's not defined.  So `make install` is just running `make` again.

Despite this, the package is successfully installed because there's a file `ppx_bitstring.install` in the top-level directory.

If you remove the `install` step from the `opam` file then I'm happy to merge this.

**Comment by xguerin** [comment]
Actually it looks like I was not using the right `opam` file. Sorry about that.

**Comment by xguerin** [comment]
I'll resubmit once I found the problem...

**Pull request closed without merging**
