### PR TITLE
Topiary v0.5.1

### PR DESCRIPTION
**Pull request by Niols**
Website: https://topiary.tweag.io/
Repository: https://github.com/tweag/topiary
Release: https://github.com/tweag/topiary/releases/tag/v0.5.1
Change log: https://github.com/tweag/topiary/blob/v0.5.1/CHANGELOG.md

### CODE REVIEW

**Comment by shonfeder** [comment]
Thanks for publishing the update! We have CI failures on all platforms due to

```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> retrieved conf-rust-2021.1  (cached)
-> installed conf-rust-2021.1
-> retrieved topiary.0.5.1  (https://github.com/tweag/topiary-opam/releases/download/v0.5.1/source-code-with-submodules.tar.xz)
[ERROR] The compilation of topiary.0.5.1 failed at "cargo build --release --package topiary-cli".

#=== ERROR while compiling topiary.0.5.1 ======================================#
# context              2.4.0~alpha1~dev | linux/x86_64 | ocaml-base-compiler.4.02.3 | pinned(https://github.com/tweag/topiary-opam/releases/download/v0.5.1/source-code-with-submodules.tar.xz)
# path                 ~/.opam/4.02/.opam-switch/build/topiary.0.5.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build cargo build --release --package topiary-cli
# exit-code            101
# env-file             ~/.opam/log/topiary-7-d9cb7b.env
# output-file          ~/.opam/log/topiary-7-d9cb7b.out
### output ###
# error: failed to select a version for `env_logger`.
#     ... required by package `test-log v0.2.16`
#     ... which satisfies dependency `test-log = "^0.2"` (locked to 0.2.16) of package `topiary-core v0.5.1 (/home/opam/.opam/4.02/.opam-switch/build/topiary.0.5.1/topiary/topiary-core)`
#     ... which satisfies path dependency `topiary-core` (locked to 0.5.1) of package `topiary-cli v0.5.1 (/home/opam/.opam/4.02/.opam-switch/build/topiary.0.5.1/topiary/topiary-cli)`
# versions that meet the requirements `^0.11` (locked to 0.11.3) are: 0.11.3
# 
# the package `test-log` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
#  It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
# 
# 
# failed to select a version for `env_logger` which could resolve this conflict
```

**Comment by Niols** [comment]
Indeed, those errors look very similar to the ones of [previous PRs](https://github.com/ocaml/opam-repository/pull/24727). They come from those platforms having a version of Rust that is too old to compile Topiary. These platforms should be ignored or skipped.

Every time, this raises the question of whether we should have a package `conf-rust-170` (or whatever the right version is), or maybe instead as many versions of the `conf-rust` package as needed (`conf-rust.1.59`, `conf-rust.1.70` etc.), all checking that Rust is at least in the version they correspond to. Previously, we decided that it was basically too much of a hassle, but I am happy to implement any of those solutions!

**Comment by shonfeder** [comment]
> Indeed, those errors look very similar to the ones of [previous PRs](https://github.com/ocaml/opam-repository/pull/24727). They come from those platforms having a version of Rust that is too old to compile Topiary. These platforms should be ignored or skipped.

Thanks very much for looking at the CI results and for taking the time to provide context :)

**Comment by Niols** [comment]
Thank you :-)

**Pull request merged**
