### PR TITLE
biocaml.0.4.0 - via opam-publish

### PR DESCRIPTION
**Pull request by pveber**
The OCaml Bioinformatics Library
Biocaml aims to be a high-performance user-friendly library for
Bioinformatics. See the [website](http://biocaml.org) for detailed API
documentation. We welcome contributors and feedback from users. Please
contact us with any comments and suggestions for features you would
like added.

---
* Homepage: http://biocaml.org
* Source repo: https://github.com/biocaml/biocaml.git
* Bug tracker: https://github.com/biocaml/biocaml/issues

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by dsheets** [comment]
Travis seems to have missed this. Toggling state.

**Comment by pveber** [comment]
Sorry, I found a couple of things to fix, so you can ignore the PR for now.

**Comment by pveber** [comment]
Alright I have fixed the opam file. How should I proceed now? Can I simply `opam-publish submit` again?

**Comment by pveber** [comment]
ok, it's written in the documentation, let me retry then

**Comment by dsheets** [comment]
Yes, it will update this PR.

**Comment by pveber** [comment]
Thanks for the suggestion, I'll go with the simple solution and remove the `-j` flag!

**Comment by pveber** [comment]
Thank you all for the help in publishing the package. I must say the whole release process on opam-repository rocks!

**Pull request merged**
