### PR TITLE
jingoo: upgrade to version 1.2.19

### PR DESCRIPTION
**Pull request by tategakibunko**

### CODE REVIEW

**Comment by pmetzger** [comment]
Just an FYI, but it's rather difficult for someone reading this commit message to know _what_ was upgraded to 1.2.19. It would be better if the commit messages said:

```
jingoo: upgrade to version 1.2.19
```

**Comment by tategakibunko** [comment]
Thanks for your advice!

**Comment by mseri** [comment]
The `url` file is still using the opam 1.2 syntax, please update that as well

**Comment by tategakibunko** [comment]
Thanks!

**Pull request merged**
