### PR TITLE
merge conf-ncurses.1 and ncurses.1+system

### PR DESCRIPTION
**Pull request by avsm**
It's unnecessary to have the solver for this, when one package can express the right dependencies fine.  This in turns helps with static analysis of a packages dependencies when we run opam on a host other than the distribution target.

### CODE REVIEW

**Comment by avsm** [comment]
@dra27 does this look ok to you?

**Comment by dra27** [comment]
The existence of these two packages was a hangover from opam 1.x days - see #5898

**Comment by dra27** [comment]
LGTM, yes

**Comment by avsm** [comment]
Thanks!

**Pull request merged**
