### PR TITLE
ppx_deriving_yojson.3.2

### PR DESCRIPTION
**Pull request by gasche**

### CODE REVIEW

**Comment by gasche** [comment]
@kit-ty-kate thanks for the fix!

The only remaining failure in the CI is on MacOS ([logs](https://travis-ci.org/ocaml/opam-repository/jobs/467996128)), and it seems to be unrelated to our project: it looks like the installation of `opam` failed. Is there a known configuration issue for the OSX CI?

**Comment by anmonteiro** [comment]
It also looks like revdeps is failing and some packages will need upper bounds on `ppx_deriving_yojson`.

3.2 introduces a new (generated) function, and people using the attribute in interface files are getting those errors.

**Comment by gasche** [comment]
Hm... Maybe we should try to fix https://github.com/ocaml-ppx/ppx_deriving_yojson/issues/76 to improve backward-compatibility, and scratch the current release... @anmonteiro, what do you think?

**Comment by anmonteiro** [comment]
I'm OK with improving backwards compatibility

**Comment by gasche** [comment]
I'll close this for now, then.

**Pull request closed without merging**
