### PR TITLE
[new release] merlin (5.1-502) and ocaml-index (1.0) and ocaml-lsp-server preview update

### PR DESCRIPTION
**Pull request by voodoos**
## [new release] merlin (3 packages) (5.1-502)

CHANGES:

Tue Jun 18 12:00:42 CEST 2024

  + merlin binary
    - Support project-wide occurrences queries using index files (ocaml/merlin#1766)
      - The file format is described in library `Merlin_lib.index_format`
      - Two new configuration directives are introduced:
        - `SOURCE_ROOT` that is used to resolve relative paths found in the
          indexes.
        - `INDEX` that is used to declare the list of index files Merlin should
          use when looking for occurrences.
    - A new `UNIT_NAME` configuration directive that can be used to tell Merlin
      the correct name of the current unit in the presence of wrapping (ocaml/merlin#1776)
    - Perform incremental indexation of the buffer when typing. (ocaml/merlin#1777)
    - `merlin-lib.commands`: Add a `find_command_opt` alternative to
      `find_command` that does not raise (ocaml/merlin#1778)
    - Prevent uid clashes by not returning PWO for defs located in the current
      interface file (ocaml/merlin#1781)
    - Reset uid counters when restoring the typer cache so that uids are stable
      across re-typing (ocaml/merlin#1779)
    - Improve the behavior on occurrences when the cursor is on a label /
      constructor declaration (ocaml/merlin#1785)
  + editor modes
    - emacs: add basic support for project-wide occurrences (ocaml/merlin#1766)
    - vim: add basic support for project-wide occurrences (ocaml/merlin#1767, @Julow)

## [new release] ocaml-index (1.0)

CHANGES:

### Added

- Initial release.
- The `aggregate` command that finishes reduction of shapes in cmt files and
  store the output in a single index file.
- The `stats` command that prints information about an index file.
- The `dump` command that prints all locs of an index.

### CODE REVIEW

**Comment by voodoos** [comment]
I find the linter a bit unfair :-) 

image

**Comment by raphael-proust** [comment]
Ideally the linter would emit a warning as a comment on the PR instead of a failure in the CI… the aim is just to help maintainers catch cases similar to what had happened in the past where two package differed only by `-`/`_`.

In this case it's fine.

**Comment by voodoos** [comment]
The CI error for [merlin.5.0-502](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/b8b9dc35419691d514c08d0132c8793cd37f8fff/variant/compilers,5.2,dot-merlin-reader.5.0-502,revdeps,merlin.5.0-502) is not related to this release. A recent improvement in Dune changed a test result (in a good direction). Should I do something about it ?

**Comment by mseri** [comment]
Thanks, for now it's not a problem. If we see it clutters too much the CI I will disable the tests

**Pull request merged**
