### PR TITLE
Added FreeBSD depext to conf-libX11.1

### PR DESCRIPTION
**Pull request by mtelvers**
Hope this is ok.  It works for me using `opam pin add conf-libX11.1 opam-repository/packages/conf-libX11/conf-libX11.1` with the updated file.

### CODE REVIEW

**Comment by haochenx** [comment]
CI was having some unrelated transient errors (ubuntu-22.10-ocaml-4.14 & ubuntu-22.10-ocaml-5.0 failed to install native package due to network error) but succeeded most related checks (freebsd-ocaml-4.14-amd64 & freebsd-ocaml-5.0-amd64). I have restarted the failed jobs but their results are not significant.

This PR looks mergeable to me.

**Comment by mtelvers** [comment]
Thank you.

Ubuntu 22.10 fails because it is EOL.  https://github.com/ocurrent/opam-repo-ci/pull/236 will remove it once it is deployed.

**Comment by haochenx** [comment]
> Ubuntu 22.10 fails because it is EOL.

Ah, i see. That make more sense that the jobs failed again.

**Comment by tmcgilchrist** [comment]
@mtelvers that fix has been deployed for opam-repo-ci. Everything is green now 🟢

**Comment by mseri** [comment]
Thanks

**Pull request merged**
