### PR TITLE
Add new library ofx 0.1.5

### PR DESCRIPTION
**Pull request by mvalle**

### CODE REVIEW

**Comment by dsheets** [comment]
Hello,

I don't see

```
available: [ ocaml-version >= "4.01.0" ]
```

in this `opam` file. Perhaps you made your code backward compatible?

**Comment by dsheets** [comment]
Thanks!

**Comment by mvalle** [comment]
I didn't know opam-publish prepare doesn't use the opam file from the archive. Thanks for your help @dsheets!

**Comment by dsheets** [comment]
Yes, I was also bitten by that issue recently and I didn't look into the opam-publish issue tracker to see if it's already been reported. Perhaps you could report it?

Also, I wonder are you using `opam publish submit`? If not, why not?

**Comment by mvalle** [comment]
Hi, I initially used `opam publish submit`, but ran into an authentication issue. Honestly, I never investigated the authentication issue, but went straight to the manual option.

**Pull request merged**
