### PR TITLE
Add '"-p" name' to several packages missing it

### PR DESCRIPTION
**Pull request by hcarty**
I ran into issues with this while working with local switches within a repository using dune.  The build steps for some packages would attempt to build outside of their sandbox.

This is untested, mostly `sed`-based updates.  I tried to catch all the obvious cases!  The changes here shouldn't break anything that isn't already broken.  And it should make it possible to build these packages from a local switch.

### CODE REVIEW

**Comment by hcarty** [comment]
This touches a lot of packages - apologies for the CI churn!

**Comment by hcarty** [comment]
The zipperposition failure is unrelated to this PR.

**Comment by hcarty** [comment]
The Travis failures also seem to be unrelated to this PR, though the logs aren't consistently loading for me.

If there are no objections I'll merge this this evening or tomorrow morning.

**Comment by mseri** [comment]
No objections for me

**Comment by kit-ty-kate** [comment]
Seems like `zipperposition.1.5` breaks with this change. cc @c-cube 
```
#=== ERROR while compiling zipperposition.1.5 =================================#
# context              2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.0 | pinned(https://github.com/c-cube/zipperposition/archive/1.5.tar.gz)
# path                 ~/.opam/4.07/.opam-switch/build/zipperposition.1.5
# command              ~/.opam/4.07/bin/jbuilder build -p zipperposition
# exit-code            1
# env-file             ~/.opam/log/zipperposition-19-07344c.env
# output-file          ~/.opam/log/zipperposition-19-07344c.out
### output ###
# File "src/main/jbuild", line 10, characters 15-20:
# 10 |    (libraries (logtk libzipperposition.phases))
#                     ^^^^^
# Error: Library "logtk" not found.
# Hint: try: dune external-lib-deps --missing -p zipperposition @install
```
There seem to be a local `logtk` library which seems to be required. I'm not sure it's the name thing as the opam package.

**Comment by c-cube** [comment]
Regarding zipperposition, I'll switch to `-p name` in the next release but it needs to pin several packages in the same repo (including logtk, which used to be in its own repo but is now along zipperposition). Could you undo  this change temporarily?

**Comment by hcarty** [comment]
@c-cube Sure - I'll be in front of a computer in a few minutes. I'll revert the change for zipperposition then merge if that is OK with @mseri and @kit-y-kate

**Comment by c-cube** [comment]
Sure. Sorry for my packages being so… high maintenance :roll_eyes:

**Comment by hcarty** [comment]
@c-cube I wouldn't have come across this issue if I wasn't getting utility from your code so - I have limited complaints :-)

**Comment by c-cube** [comment]
wait, do you get utility from… zipperposition? :sweat_smile:

**Comment by hcarty** [comment]
oseq and gen - In this case, zipperposition was caught in the `grep` and `sed` I went through to see if there were other packages with similar local switch issues.

**Comment by hcarty** [comment]
@kit-ty-kate Thank you for catching the zipperposition breakage, btw.

**Comment by hcarty** [comment]
Thanks everyone!

**Comment by kit-ty-kate** [comment]
mmh there was still a failure with the same problem with `osbx.1.0.0` and `osbx.1.0.0`
```
#=== ERROR while compiling osbx.1.0.1 =========================================#
# context              2.0.0 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/darrenldl/ocaml-SeqBox/archive/1.0.1.tar.gz)
# path                 ~/.opam/4.03/.opam-switch/build/osbx.1.0.1
# command              ~/.opam/4.03/bin/jbuilder build -p osbx
# exit-code            1
# env-file             ~/.opam/log/osbx-19-bba736.env
# output-file          ~/.opam/log/osbx-19-bba736.out
### output ###
# File "src/jbuild", line 5, characters 19-29:
# 5 |   (libraries      (crcccitt_c stdint nocrypto nocrypto.unix angstrom core hex ctypes ctypes.foreign cmdliner))
#                        ^^^^^^^^^^
# Error: Library "crcccitt_c" not found.
# Hint: try: dune external-lib-deps --missing -p osbx @install
```

**Comment by hcarty** [comment]
@kit-ty-kate Ah, sorry.  PR to revert the changes incoming.

**Pull request merged**
