### PR TITLE
multiple domain, tls 0.6.0, workdir storage

### PR DESCRIPTION
**Pull request by gregtatcam**

### CODE REVIEW

**Comment by samoht** [comment]
The failing job is due to an issue with `ocaml-dns`, with a fix here: https://github.com/mirage/ocaml-dns/pull/79

**Comment by gregtatcam** [comment]
Is another dns release coming out soon?

**Comment by dsheets** [comment]
Probably.

**Comment by dsheets** [comment]
Out now: dns 0.15.2 in #4377

**Comment by gregtatcam** [comment]
Thanks!

**Pull request merged**
