### PR TITLE
Package mock-ounit.0.1.0

### PR DESCRIPTION
**Pull request by emillon**
### `mock-ounit.0.1.0`

Configurable functions to test impure code

This package provides "mocks", fake functions that can be configured to return
values or raise exception. It is possible to inspect their arguments after their
execution. The API is greatly inspired by [unittest.mock] in Python.

There is no magic under the hood, it is "just" a reference to a function, but
it makes it possible to have pleasant output like this in your tests:

> expected f to be called once, but it was called 3 times

A wrapper for `OUnit2` is available as `mock-ounit`.

[unittest.mock]: https://docs.python.org/3/library/unittest.mock.html

---
* Homepage: https://github.com/cryptosense/ocaml-mock
* Source repo: https://github.com/cryptosense/ocaml-mock.git
* Bug tracker: https://github.com/cryptosense/ocaml-mock/issues

---

---
v0.1.0
======

Initial release.
:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by emillon** [comment]
This depends on #11589, I'm not sure how to do that with `topkg opam` since it's my first multi-opam project, so tips appreciated if there's a way to open a single PR :)

**Comment by jpdeplaix** [comment]
I can't help you with topkg (apart from ccing @dbuenzli) but in the general case you can always do a "manual" PR where you just have to copy files and use md5sum to get the checksum.
With the CI we are now able to test the package after an other one has been merged so there will be no problems on this side.

**Comment by emillon** [comment]
It looks like a manual step is required indeed. Thanks for the tip!

**Comment by jpdeplaix** [comment]
Looks good. Thanks ! :)

**Pull request merged**
