### PR TITLE
Package ocamlformat.0.8

### PR DESCRIPTION
**Pull request by jberdine**
### `ocamlformat.0.8`
Auto-formatter for OCaml code
OCamlFormat is a tool to automatically format OCaml code in a uniform style.

---
* Homepage: https://github.com/ocaml-ppx/ocamlformat
* Source repo: git+https://github.com/ocaml-ppx/ocamlformat.git
* Bug tracker: https://github.com/ocaml-ppx/ocamlformat/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
But the archive is not listed in the opam file so of course the file cannot be found since it's not extracted in the first place

**Comment by jberdine** [comment]
Thanks. I guess I am just now learning what `opam publish prepare` used to do now that it's gone. :-/

**Comment by jberdine** [comment]
Is `Failure("openssl error")` a known problem for the osx build?

**Comment by mseri** [comment]
Yes, that can be ignored, it’s being fixed at opam level

**Comment by mseri** [comment]
Looks good now

**Pull request merged**
