### PR TITLE
[new release] atds, atdpy, atdj, atdgen, atdgen-runtime, atdgen-codec-runtime and atd (2.3.3)

### PR DESCRIPTION
**Pull request by mjambon**
ATD Code generator for Scala

- Project page: <a href="https://github.com/ahrefs/atd">https://github.com/ahrefs/atd</a>

##### CHANGES:

* Prevent incorrect validation errors for annotations of the form
  `<ocaml field_prefix=...>` and a few others (ahrefs/atd#258)

### CODE REVIEW

**Comment by mjambon** [comment]
@mseri is there an easy way to copy the opam files from a previous release except for the URL and checksum?

**Comment by mjambon** [comment]
This release 2.3.3 should now be identical to the previous one (2.3.2 https://github.com/ocaml/opam-repository/pull/20905) except for the bottom part of the opam files (`url {` line and below).

**Comment by mseri** [comment]
> @mseri is there an easy way to copy the opam files from a previous release except for the URL and checksum?

Imho the easiest way is to let `dune-package` generate the opam files (it seems what you are doing). Otherwise, if you have the opam files handwritten and checked in, tools like dune-release and opam-publish will automatically use them and add the relevant urls

**Comment by mseri** [comment]
To have multiple bounds, e.g. for `menhir` you can modify
https://github.com/ahrefs/atd/blob/17a414355fc3678791b942620ae82cf72a24cd57/dune-project#L38
as follows
```
(menhir (and (>= 20180523) (< "20211215")))
```

**Comment by mjambon** [comment]
> > @mseri is there an easy way to copy the opam files from a previous release except for the URL and checksum?
> 
> Imho the easiest way is to let `dune-package` generate the opam files (it seems what you are doing). Otherwise, if you have the opam files handwritten and checked in, tools like dune-release and opam-publish will automatically use them and add the relevant urls

The opam files are generated from `dune-project` in the atd repo each time we run `dune build`. For the opam release, I used `dune-release` which I think uses whichever opam packages are there (without running `dune build`). We keep the release instructions in [`CONTRIBUTING.md`](https://github.com/ahrefs/atd/blob/master/CONTRIBUTING.md#releasing-atd).

Since the opam files generated from `dune-project` need patching, I wonder what to do. I'll figure something out.

**Comment by mjambon** [comment]
I think we're all caught up on the atd repo side: https://github.com/ahrefs/atd/pull/261#issuecomment-1071943849

**Comment by mjambon** [comment]
I pushed fixes that should eliminate the build errors of the reverse dependencies (atdj, atds, gitlab packages).

**Comment by mseri** [comment]
Thanks!

**Comment by mjambon** [comment]
Thanks a lot @mseri for your assistance all along!

**Pull request merged**
