### PR TITLE
Higher 0.3.0

### PR DESCRIPTION
**Pull request by yallop**

### CODE REVIEW

**Comment by dbuenzli** [comment]
I suspect this will have a META file that advertises version 0.2.1 (This is why I automate these things, but I never cleaned it up sufficiently to document the thing in topkg).

**Comment by yallop** [comment]
Indeed.  Fixed now; thanks!

**Comment by avsm** [comment]
Is the lack of `ocamlfind` in `depends` deliberate?  I guess if it installed a `META` there is no hard dependency on findlib.

**Comment by yallop** [comment]
@avsm: it's deliberate.  See https://github.com/ocamllabs/higher/pull/7#discussion_r47285960 and https://github.com/ocamllabs/higher/commit/4fb2cdc2686cea3b3a7f5600cd1c6badf5f63067

**Comment by avsm** [comment]
excellent, thanks!

**Pull request merged**
