### PR TITLE
Package lp.0.2.0

### PR DESCRIPTION
**Pull request by ktahar**
New release of package [lp](https://github.com/ktahar/ocaml-lp).

- Added an interface to Gurobi (commercial MIP solver)
- Fix many bugs on the parser etc.

### CODE REVIEW

**Comment by ktahar** [comment]
CI is failing only on Alpine for the same reason on previous release https://github.com/ocaml/opam-repository/pull/16392#issuecomment-626184705.

**Comment by kit-ty-kate** [comment]
The failure on 4.10 seems to be transient, but is it fixable?
```
#=== ERROR while compiling lp.0.2.0 ===========================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://github.com/ktahar/ocaml-lp/archive/0.2.0.tar.gz)
# path                 ~/.opam/4.10/.opam-switch/build/lp.0.2.0
# command              ~/.opam/4.10/bin/dune runtest -p lp -j 72
# exit-code            1
# env-file             ~/.opam/log/lp-29-dbb69b.env
# output-file          ~/.opam/log/lp-29-dbb69b.out
### output ###
#    test_poly alias test/lp/runtest (exit 125)
# (cd _build/default/test/lp && ./test_poly.exe --color=always)
# test_poly.exe: internal error, uncaught exception:
#                Unix.Unix_error(Unix.EEXIST, "symlink", "/home/opam/.opam/4.10/.opam-switch/build/lp.0.2.0/_build/default/test/lp/_build/_tests/latest")
```

**Comment by ktahar** [comment]
> The failure on 4.10 seems to be transient, but is it fixable?
> 
> ```
> #=== ERROR while compiling lp.0.2.0 ===========================================#
> # context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://github.com/ktahar/ocaml-lp/archive/0.2.0.tar.gz)
> # path                 ~/.opam/4.10/.opam-switch/build/lp.0.2.0
> # command              ~/.opam/4.10/bin/dune runtest -p lp -j 72
> # exit-code            1
> # env-file             ~/.opam/log/lp-29-dbb69b.env
> # output-file          ~/.opam/log/lp-29-dbb69b.out
> ### output ###
> #    test_poly alias test/lp/runtest (exit 125)
> # (cd _build/default/test/lp && ./test_poly.exe --color=always)
> # test_poly.exe: internal error, uncaught exception:
> #                Unix.Unix_error(Unix.EEXIST, "symlink", "/home/opam/.opam/4.10/.opam-switch/build/lp.0.2.0/_build/default/test/lp/_build/_tests/latest")
> ```

I think it's transient too. And I have no idea to fix it because it was OK in previous commit cd0c8b68375483f5762543513269d6dc40bf8445 (the only difference is my silly mistake on archive checksum).
I tried to re-run that part of CI but it's pending for a while.

**Comment by kit-ty-kate** [comment]
Thanks! Sorry for the time this took, our CI was experiencing some problems

**Pull request merged**
