### PR TITLE
Update hevea

### PR DESCRIPTION
**Pull request by pirbo**

### CODE REVIEW

**Comment by yallop** [comment]
There are some [problems with the uninstall script](https://travis-ci.org/ocaml/opam-repository/jobs/56218897):

```
[WARNING] failure in package uninstall script, some files may remain:
# opam-version 1.1.2-rc3
# os linux
# command rm /home/travis/.opam/system/bin/hevea /home/travis/.opam/system/bin/hacha /home/travis/.opam/system/bin/esponja /home/travis/.opam/system/bin/bibhva
# path /home/travis/.opam/system/build/hevea.2.23
# compiler system (4.02.1)
# exit-code 1
# env-file /home/travis/.opam/system/build/hevea.2.23/hevea-9647-58c514.env
# stdout-file /home/travis/.opam/system/build/hevea.2.23/hevea-9647-58c514.out
# stderr-file /home/travis/.opam/system/build/hevea.2.23/hevea-9647-58c514.err
### stderr ###
# rm: cannot remove `/home/travis/.opam/system/bin/hevea': No such file or directory
# rm: cannot remove `/home/travis/.opam/system/bin/hacha': No such file or directory
# rm: cannot remove `/home/travis/.opam/system/bin/esponja': No such file or directory
# rm: cannot remove `/home/travis/.opam/system/bin/bibhva': No such file or directory
```

**Comment by pirbo** [comment]
Indeed the problem is that for some reason opam 1.1 does not respect
```install: [make "PREFIX=%{prefix}%" "install"]```
I'll try to understand why. Maybe you've got an idea.

**Comment by pirbo** [comment]
Ok why is trivial : opam 1.1 does not know about ```install:``` if I understand correctly

What is the better fix ?
* set ```opam-version: "1.2"```
* move ```[make "PREFIX=%{prefix}%" "install"]``` in the ```build:``` phase

**Comment by avsm** [comment]
Setting `opam-version` to `1.2`.  There are automatic rewrite scripts that will make the backwards compatible 1.1 version, so you dont need to worry about that.

**Comment by pirbo** [comment]
The failure is a connection issue. I do not know if it is possible to ask travis to retry a build.

**Comment by yallop** [comment]
I've restarted the job.

**Pull request merged**
