### PR TITLE
+lwt.3.0.0 - concurrency library (the real PR)

### PR DESCRIPTION
**Pull request by aantron**
#8929, but without `lwt_ssl`, `lwt_react`, and `lwt_glib`.

### CODE REVIEW

**Comment by aantron** [comment]
The failure in Alpine looks related to ocamlfind, not Lwt. Some revdeps failed to build due to Lwt. I'll add constraints this evening or tomorrow.

**Comment by avsm** [comment]
That weird, conf-m4 should pull in the binary. Looking...

**Comment by aantron** [comment]
Added constraints.

`conduit` `dns` `lwt-parallel` `protocol-9p` `tcpip` don't build against Lwt 3.0.0 because `Lwt_unix.bind` now evaluates to a `unit Lwt.t` instead of just `unit`. Attn.: @rgrinberg @hannesm @yomimono @djs55 @ivg @talex5. `conduit` in particular is blocking a large number of packages.

`lambda-term` `obus` `ocsigenserver` don't build because they use package name `lwt.react` instead of `lwt_react`. Since they won't build until we merge in the new `lwt_react`, I won't ping the maintainers for now.

I think everyone pinged has already seen https://github.com/ocsigen/lwt/issues/308, but linked it again for easy reference.

**Comment by aantron** [comment]
Ok, it looks like the remaining revdeps failures are not caused by Lwt.

**Comment by bactrian** [comment]
That's a very satisfying amount of green in the revdeps. Thanks for all the effort with the upper bounds. I've fixed a minor one in #8967 and reported several of the other failures to upstream maintainers.  What's the next step to merge?

**Comment by aantron** [comment]
:D I love the bot's full name.

I guess this PR could be merged now, but I'd rather merge the extra packages at the same time, so that Lwt 3.0.0 doesn't become installable without them. This is slightly important, as then people using the older package names (`lwt.ssl`) can immediately change them to `lwt_ssl` – even though the number of people that are actually likely to be affected by a small gap in the packages' availability is probably zero.

I think we should decide what to do about depexts on `glib`. Previously, `lwt_glib` relied on `lablgtk`, which has a depext on `gtk`, which pulls in `glib`. Maybe we should create `conf-glib` and/or `conf-gtk` packages? Alternatively, I could just make `lwt_glib` depend on `lablgtk` again for the time being.

I'll then add the extra packages (into this PR?), wait for another revdeps build, and add any required constraints.

**Comment by aantron** [comment]
The `pkg-config` name of `glib` is `glib-2.0`, and this choice makes me wonder if an OPAM package should be `glib` or `glib-2.0`. The GLib people might be communicating some kind of intent with the explicit `-2.0`.

**Comment by aantron** [comment]
I've made a `conf-glib-2` package locally, and so far it's working with Homebrew. I'll test it on Alpine, Ubuntu, and maybe some other distros later.

However, I looked in the build logs, and as of right before I pushed the above two commits, `lambda-term.1.6` was failing due to missing `lwt.syntax`. I added the missing dependency. I then added the two extra packages `lwt_ssl` and `lwt_react`. This should only affect building of `0install`, so it should be pretty low-impact. I'll wait to see the build outputs for these, then add the `conf-` package and the `lwt_glib` that depends on it.

**Comment by aantron** [comment]
(the remaining failures looked unrelated to Lwt)

**Comment by aantron** [comment]
AFAICT this is ready for merge.

- The build is now broken due to old versions of `conduit`, `dns`, `tcpip`, over issues that don't look related to Lwt.
- The last revdeps build that ran showed no errors apparently related to Lwt.
- I've since added the extra packages to this PR, but only one package depends on them: `0install` on `lwt_react` and `lwt_glib`. `0install`'s build system makes reference to `lwt.glib`, which doesn't exist in Lwt 3.0.0. I added the appropriate constraints (cc @talex5), so I think we could expect a revdeps build to succeed.

We can force a revdeps build to run with the extra packages, by merging the constraints on `conduit`, `dns`, `tcpip` separately, but I think we've learned what we can from the CI at this point. With the `0install` constraints, there are no packages that depend on the new versions of the extra packages.

I'm a little worried that the latest CI build isn't building the `0install` packages whose `opam` files were changed, however.

**Comment by avsm** [comment]
Thanks! Merging this -- I'll fix up the unrelated issues you found separately.

**Comment by aantron** [comment]
Many thanks!

**Comment by aantron** [comment]
Pinging @diml @vouillon @vasilisp about `obus` and `ocsigenserver` above – these need to depend on OPAM package `lwt_react`, and refer to Findlib package `lwt_react` instead of `lwt.react` to be compatible with Lwt. I was wrong above about not building until 3.0.0 is merged – Findlib package `lwt_react` requires Lwt >= 2.7.0 and any version of OPAM package `lwt_react`. What changed in Lwt 3.0.0 is `lwt.react` no longer exists.

@djs55 already submitted an appropriate PR for `lambda-term` (thanks!).

**Pull request merged**
