### PR TITLE
stringext: older versions are not safe-string compatible

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by rgrinberg** [comment]
What about all the versions in between? 1.1.0 to be exact.

**Comment by avsm** [comment]
yeah constrained 1.0.0 in a43ea8db2e6fdb5c995c40c220bbc0ae20a9119a

**Comment by avsm** [comment]
oh i see, it didnt show up in the obi analysis as there was a transient failure that caused the non-safe-string version to also fail

**Comment by rgrinberg** [comment]
I see. OK I'll squash and merge.

**Pull request merged**
