### PR TITLE
OCanren

### PR DESCRIPTION
**Pull request by Kakadu**

### CODE REVIEW

**Comment by Kakadu** [comment]
There are issues related to oracle linux that should be ignored because of #17897

**Comment by kit-ty-kate** [comment]
Dune and Camlp5 should not be tagged as build dependencies and the requires lowest version of dune is 2.5. Could you return the fix upstream?

I also have one question about this package. It seems to be a fork from Jetbrain, is there an agreement to release this written somewhere? Is upstream ok with this?

**Comment by Kakadu** [comment]
> Dune and Camlp5 should not be tagged as build dependencies and the requires lowest version of dune is 2.5. Could you return the fix upstream?
> 
> I also have one question about this package. It seems to be a fork from Jetbrain, is there an agreement to release this written somewhere? Is upstream ok with this?

Everything is fixed now. @kit-ty-kate, please recheck

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
