### PR TITLE
aws-cloudtrail.0.1.0 - via opam-publish

### PR DESCRIPTION
**Pull request by seliopou**
AWS CloudTrail

---
* Homepage: https://github.com/inhabitedtype/ocaml-aws
* Source repo: https://github.com/inhabitedtype/ocaml-aws.git
* Bug tracker: https://github.com/inhabitedtype/ocaml-aws/issues

---
### opam-lint failures
- **WARNING** 97 long description unspecified

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by seliopou** [comment]
One of the builds is failing. It should be fixed after either #6121 or #6132 is merged.

**Comment by yallop** [comment]
Does the package need an additional version constraint?

**Comment by seliopou** [comment]
This is due to the AWS runtime library failing due to a missing version constraint. Restarting the build should fix it now that #6132 and #6121 are merged.

**Comment by yallop** [comment]
I've restarted the job.

**Pull request merged**
