### PR TITLE
Package radis.0.1

### PR DESCRIPTION
**Pull request by dinosaure**
### `radis.0.1`

---
* Homepage: https://github.com/dinosaure/radis
* Source repo: git://github.com/dinosaure/radis.git
* Bug tracker: https://github.com/dinosaure/radis/issues

---
v0.1 2018-05-07 Paris (France)
----------------------------------------

- First release of `radis`

---
:camel: Pull-request generated by opam-publish v2.0.0~beta

### CODE REVIEW

**Comment by dinosaure** [comment]
Hmmhmm, `opam-publish` has a bug, or me ...

**Comment by dinosaure** [comment]
Hmmhmm, it seems I produce an opam package for `opam.2.0`, I'm not sure if it's what maintainers want.

**Comment by yomimono** [comment]
The master branch of the repository currently hosts version 1.2 files, so indeed one of those would be preferred.  I'm not an opam-publish user but perhaps pinning version 0.3.5 (the last release before `2.0.0~beta` would do it?

**Comment by dinosaure** [comment]
Close by #11980

**Pull request closed without merging**
