### PR TITLE
Cordova plugin datepicker/device motion/globalization: remove ocaml-j…

### LINKED ISSUE #9273: missing package: ocaml-js-stdlib
The following packages have a dependency on `ocaml-js-stdlib`, which does not exist in `opam-repository`. Is this on purpose?

* `cordova-plugin-datepicker.1.0`
* `cordova-plugin-device-motion.1.0`
* `cordova-plugin-globalization.1.0`

cc @dannywillems

### PR DESCRIPTION
**Pull request by dannywillems**
…s-stdlib dependency. Fix #9273

### CODE REVIEW

**Comment by avsm** [comment]
Ah, I thought these were an optional dependency. It looks like the build is failing entirely, so we may need to remove the failing packages from opam until the dependency is also ready for import.

```
#=== ERROR while installing cordova-plugin-datepicker.1.0 =====================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              make build
# path                 /home/opam/.opam/4.03.0/build/cordova-plugin-datepicker.1.0
# compiler             4.03.0
# exit-code            2
# env-file             /home/opam/.opam/4.03.0/build/cordova-plugin-datepicker.1.0/cordova-plugin-datepicker-29-2f8173.env
# stdout-file          /home/opam/.opam/4.03.0/build/cordova-plugin-datepicker.1.0/cordova-plugin-datepicker-29-2f8173.out
# stderr-file          /home/opam/.opam/4.03.0/build/cordova-plugin-datepicker.1.0/cordova-plugin-datepicker-29-2f8173.err
### stdout ###
# ocamlfind gen_js_api/gen_js_api cordova_datepicker.mli
# ocamlfind ocamlc -c -package gen_js_api -package ocaml-js-stdlib cordova_datepicker.mli
# Makefile:15: recipe for target 'build' failed
### stderr ###
# ocamlfind: Package `ocaml-js-stdlib' not found
# make: *** [build] Error 2

```

**Comment by avsm** [comment]
@dannywillems should these packages be removed?

**Comment by dannywillems** [comment]
No they shouldn't. Sorry for the delay. I will do it tomorrow or tonight. I will add ocaml-js-stdlib.

**Comment by dannywillems** [comment]
I close it because I will add ocaml-js-stdlib.

**Pull request closed without merging**
