### PR TITLE
Package glfw-ocaml (3.2.1-1)

### PR DESCRIPTION
**Pull request by SylvainBoilard**
CHANGES:

* Fixed build when the GLFW headers are not in /usr/include.

### CODE REVIEW

**Comment by mseri** [comment]
Ubuntu 16.04:
```
- -> stderr:
- which: pkg-config
- -> found: /usr/bin/pkg-config
- run: /usr/bin/pkg-config --print-errors glfw3
- -> process exited with code 0
- -> stdout:
- -> stderr:
- run: /usr/bin/pkg-config --cflags glfw3
- -> process exited with code 0
- -> stdout:
-  | -I/usr/include/libdrm
- -> stderr:
- run: /usr/bin/pkg-config --libs glfw3
- -> process exited with code 0
- -> stdout:
-  | -lglfw
- -> stderr:
- Fatal error: exception Sys_error("/usr/include/libdrm/GLFW/glfw3.h: No such file or directory")
[ERROR] The compilation of glfw-ocaml failed at "/home/opam/.opam/4.07/bin/dune build -p glfw-ocaml -j 71".
```

**Comment by mseri** [comment]
All the rest is perfectly good

**Comment by SylvainBoilard** [comment]
I think this is ready to be merged, I would just like to see if the MacOS build passes to be sure.

**Comment by SylvainBoilard** [comment]
The MacOS build passed, the other failures are due to Ubuntu 16.04 packaging an older version of GLFW than that which this package is for.

**Comment by mseri** [comment]
Thanks

**Comment by SylvainBoilard** [comment]
Thank you!

**Pull request merged**
