### PR TITLE
Add ocamlnet.4.1.4

### PR DESCRIPTION
**Pull request by jpdeplaix**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
@gerdstolpmann it seems that your use of ```-opaque``` requires OCaml >= 4.03.0.

**Comment by gerdstolpmann** [comment]
yes, true. Do we need support for < 4.03? I can create a patch if needed, looks easy to do.

**Comment by jpdeplaix** [comment]
As you wish. I just did patch for the OPAM package but my notice was just so you can either specify the new version constraint somewhere (```_oasis``` seems to be the only place I found such a constraint) or disable ```-opaque``` when OCaml < 4.03 depending on what you want to do.
I personally don't require OCaml < 4.03 but maybe someone else do.

**Comment by gerdstolpmann** [comment]
when you unconditionally remove `-opaque` you get tons of warnings when using the libraries. I'll prepare a proper patch, hopefully today.

**Comment by jpdeplaix** [comment]
The patch I added is only applied when OCaml < 4.03 so I believe there is no problems here.

**Comment by gerdstolpmann** [comment]
ok, then, did not see that.

Nevertheless, I released a fixed version, `4.1.4`, not requiring a patch. If you like, pick it.

**Comment by jpdeplaix** [comment]
Perfect ! Thanks a lot ! :)

**Comment by avsm** [comment]
Is there a changelog available for the release? It's a very common base dependency so worth looking over it for potential manual tests to run.

**Comment by jpdeplaix** [comment]
@avsm 
```
Release 4.1.4:
  * Fix: incompatibility for OCaml < 4.03 because of -opaque
Release 4.1.3:
  * Building modules with -opaque flag when we don't install the cmx file
  * Fix: incompatbility with OCaml-4.05 (O_KEEPEXEC flag)
  * Fix: the local cppo built has been made compatible with -safe-string
```

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
