### PR TITLE
+lwt.2.7.0 - concurrency library

### PR DESCRIPTION
**Pull request by aantron**
See the [changelog](https://github.com/ocsigen/lwt/releases/tag/2.7.0). This release prepares Lwt for some minor breaking changes around 1 April. See [notice](https://github.com/ocsigen/lwt/issues/308).

### CODE REVIEW

**Comment by avsm** [comment]
notes from the revdeps build in CI:

- cowabloga fails to build due to deprecation warnings, so needs upper bound:
```
# File "lib_test/site.ml", line 20, characters 2-14:
# Warning 3: deprecated: Lwt_unix.run
#  Use Lwt_main.run.
# File "lib_test/site.ml", line 1:
# Error: Some fatal warnings were triggered (1 occurrences)
# Command exited with code 2.
# Makefile:18: recipe for target 'all' failed
```

same problem for dog:

```
# File "src/main.ml", line 51, characters 2-14:
# Warning 3: deprecated: Lwt_unix.run
#  Use Lwt_main.run.
# File "src/main.ml", line 1:
# Error: Some fatal warnings were triggered (1 occurrences)
```

iocamljs-kernel may need an upper bound too:

```
# File "iocaml.ml", line 220, characters 18-31:
# Warning 3: deprecated: String.create
# Use Bytes.create instead.
# File "iocaml.ml", line 222, characters 12-19:
# Warning 3: deprecated: String.set
# Use Bytes.set instead.
# Error for package iocaml
# Fatal error: exception Fl_package_base.No_such_package("iocaml", "")
# Fatal error: exception Failure("Error: jsoo_mkcmis -o exported-unit.cmis.js iocaml /home/opam/.opam/4.04.0/lib/ocaml/compiler-libs/outcometree.cmi /home/opam/.opam/4.04.0/lib/ocaml/compiler-libs/topdirs.cmi /home/opam/.opam/4.04.0/lib/ocaml/compiler-libs/toploop.cmi")
# make: *** [min] Error 2
```

revdep build continues at https://ci.ocaml.io/ocaml/opam-repository/pr/8195

**Comment by aantron** [comment]
Will add bounds on `cowabloga` and `dog`. FTR these packages were noticed in https://github.com/ocsigen/lwt/pull/107#issuecomment-215804344, Lwt 2.7.0 just adds an actual deprecation warning to go with the pre-existing deprecation of `Lwt_unix.run`. The `iocamljs-kernel` warning does not look related to Lwt.

**Comment by avsm** [comment]
The OPAM2 CI failures are due to https://github.com/ocaml/opam/issues/2806

**Comment by aantron** [comment]
I looked through the logs, and in addition to `dog` and `cowabloga`, also found failures to build due to new deprecation warnings for `release`, `tlstunnel`, `vpnkit`. These packages were also noticed in ocsigen/lwt#308. I added a `< "2.7.0"` bound for each release of these packages that didn't already have a narrower bound.

cc @andrenth @djs55 @hannesm @avsm (hi!) @samoht

I already plan to ping the maintainers there again, in addition to maintainers of packages that still build with the warnings.

```
- File "lib/core/release_socket.ml", line 10, characters 2-15:
- Warning 3: deprecated: Lwt_unix.bind
-  This function will soon evaluate to a promise (-> unit Lwt.t), because the
-  bind system call can block for Unix domain sockets. See
-    https://github.com/ocsigen/lwt/issues/230
-  This will be a breaking change in Lwt 3.0.0.
-  If you don't use Unix domain sockets and use Lwt_unix.bind ... ; rather than
-  let () = Lwt_unix.bind ... in, you can ignore this warning.
-  To retain the current signature, use Lwt_unix.Versioned.bind_1
-  To use the new non-blocking version immediately, use Lwt_unix.Versioned.bind_2
-  Both alternatives require Lwt >= 2.7.0.
- File "lib/core/release_socket.ml", line 1:
- Error: Some fatal warnings were triggered (1 occurrences)
```

```
- File "tlstunnel.ml", line 120, characters 6-10:
- Warning 3: deprecated: Lwt_unix.bind
-  This function will soon evaluate to a promise (-> unit Lwt.t), because the
-  bind system call can block for Unix domain sockets. See
-    https://github.com/ocsigen/lwt/issues/230
-  This will be a breaking change in Lwt 3.0.0.
-  If you don't use Unix domain sockets and use Lwt_unix.bind ... ; rather than
-  let () = Lwt_unix.bind ... in, you can ignore this warning.
-  To retain the current signature, use Lwt_unix.Versioned.bind_1
-  To use the new non-blocking version immediately, use Lwt_unix.Versioned.bind_2
-  Both alternatives require Lwt >= 2.7.0.
- File "tlstunnel.ml", line 1:
- Error: Some fatal warnings were triggered (1 occurrences)
```

```
- File "src/hostnet/host_lwt_unix.ml", line 630, characters 12-25:
- Warning 3: deprecated: Lwt_unix.bind
-  This function will soon evaluate to a promise (-> unit Lwt.t), because the
-  bind system call can block for Unix domain sockets. See
-    https://github.com/ocsigen/lwt/issues/230
-  This will be a breaking change in Lwt 3.0.0.
-  If you don't use Unix domain sockets and use Lwt_unix.bind ... ; rather than
-  let () = Lwt_unix.bind ... in, you can ignore this warning.
-  To retain the current signature, use Lwt_unix.Versioned.bind_1
-  To use the new non-blocking version immediately, use Lwt_unix.Versioned.bind_2
-  Both alternatives require Lwt >= 2.7.0.
- File "src/hostnet/host_lwt_unix.ml", line 1:
- Error: Some fatal warnings were triggered (3 occurrences)
```

---

In addition, `usb` and `xe` have build failures due to missing dependencies on
`camlp4`, which causes `lwt.syntax` not to be built. I added the dependencies.

cc @diml @djs55

---

Several packages don't build due to dependency constraints involving Lwt. I noticed `mirage-http-unix` and `mirage-www`.

**Comment by aantron** [comment]
Ok, `usb` and `xe` now build, and the bot didn't attempt to build the five packages with new constraints (presumably this is the expected behavior).

**Comment by aantron** [comment]
Closing this in favor of #8196, since that PR has all the commits of this PR and more, and works just fine. Hope that's fine.

**Pull request closed without merging**
