### PR TITLE
commonjs_of_ocaml.0.1.0 - via opam-publish

### PR DESCRIPTION
**Pull request by AngryLawyer**
Import and export CommonJS modules in js_of_ocaml
Helper PPX and functions for ease of interfacing with other CommonJS
modules when building a project through js_of_ocaml

---
* Homepage: https://github.com/angrylawyer/commonjs_of_ocaml
* Source repo: https://github.com/angrylawyer/commonjs_of_ocaml.git
* Bug tracker: https://github.com/angrylawyer/commonjs_of_ocaml/issues

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by yallop** [comment]
The build's [failing](https://travis-ci.org/ocaml/opam-repository/jobs/129255531), apparently due to a missing `js_of_ocaml` dependency:

```
# W: Field 'pkg_js_of_ocaml_ppx' is not set: Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d js_of_ocaml.ppx > '/tmp/oasis-9b1ac4.txt'' terminated with error code 2
# E: Cannot find findlib package js_of_ocaml (>= 2.6)
# E: Cannot find findlib package js_of_ocaml.ppx (>= 2.6)
# E: Failure("2 configuration errors")
```

**Comment by AngryLawyer** [comment]
Huh. I'll look into it.

**Comment by yallop** [comment]
The `js_of_ocaml` problem is resolved, but there's a [new failure](https://travis-ci.org/ocaml/opam-repository/jobs/129369722):

```
### stderr ###
# Installed /home/travis/.opam/system/lib/commonjs_ppx/META
# E: Failure("Cannot find file 'lib/META' for findlib library commonjs")
```

**Comment by AngryLawyer** [comment]
Yeah, currently cracking away at it in my lunch break; think I've got a handle on this one.

**Comment by AngryLawyer** [comment]
Looks like I'm now down to one issue, which is a version discrepancy in the way ASTs work. I'll see if I can get something hammered out over the next few days.

**Comment by AngryLawyer** [comment]
And we're now cleanly building! Should be okay.

**Pull request merged**
