### PR TITLE
add why3 1.0.0

### PR DESCRIPTION
**Pull request by silene**

### CODE REVIEW

**Comment by mseri** [comment]
The debian failure is probably due to an out of date apt repository. I don’t think it can be solved by us, ping @kit-ty-kat

**Comment by kit-ty-kate** [comment]
i don't know where the failures come from but it's definitely unrelated. Thanks.

**Comment by mseri** [comment]
@kit-ty-kate usually you get that kind of error if you `apt-get install` something with an out of date local repository, and the fix is just to run `apt-get update` before the install

**Comment by mseri** [comment]
mmh weird. Sorry, I had missed that in the logs from the ipad

**Pull request merged**
