### PR TITLE
2 packages from c-cube/ocaml-avro at 0.1

### PR DESCRIPTION
**Pull request by c-cube**
This pull-request concerns:
-`avro.0.1`: Runtime library for encoding/decoding Avro
-`avro-compiler.0.1`: Schema compiler for Avro

---
* Homepage: https://github.com/c-cube/ocaml-avro
* Source repo: git+https://github.com/c-cube/ocaml-avro.git
* Bug tracker: https://github.com/c-cube/ocaml-avro/issues/

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks! Could you return the fix in the opam file upstream? (if you want to keep the opam file autogeneration from dune, you just have to upgrade to dune >= 2.7)

**Comment by c-cube** [comment]
hmm I use dune 2.9.1 locally, how comes?

**Comment by kit-ty-kate** [comment]
yes sorry that's what i meant, you need at least (lang dune 2.7)

**Comment by c-cube** [comment]
if it's a bug in dune, why isn't it fixed regardless of `(lang …)`? :/

**Comment by kit-ty-kate** [comment]
because it would be a nightmare if different people with different versions of dune were to commit different conflicting changes to the same opam file since it is autogenerated and promoted every time `dune build` is called, sadly.

**Pull request merged**
