### PR TITLE
Add ocp-build.1.99.19-beta

### PR DESCRIPTION
**Pull request by lefessan**
Yet another hot fix for 1.99.19-beta

### CODE REVIEW

**Comment by hhugo** [comment]
Why hotifixes compare to new versions ?
Hotfixes generate useless breaks:  
Bad checksum for /home/hheuzard/.opam/packages.dev/ocp-build.1.99.19-beta/1.99.19-beta.tar.gz:
          - ac7000cfff5a0d94970050fa86f93667 [expected result]
          - e4d5e3bc256091b5907a43613c33411c [actual result]

**Comment by lefessan** [comment]
New versions increase the number of versions, which degrades the speed of the dependency solver, and since the current opam-repository policy is to forbid the removal of versions, hot fixing is the only way to avoid having too many versions, among which many are known to be broken.

**Comment by avsm** [comment]
I'm afraid hotfixing is the optimally bad solution, as users who haven't updated will break a formerly working installation.

> New versions increase the number of versions, which degrades the speed of the dependency solver

This is not a concern in practise -- only in specific shapes of dependencies (such as the packages-as-versions in opam2).  More versions are fine and encouraged for packages like ocp-build.

> since the current opam-repository policy is to forbid the removal of versions, hot fixing is the only way to avoid having too many versions, among which many are known to be broken

this is a guideline rather than a rule, since opam 1.2 doesn't handle package removal well in some circumstances (again, fixed in opam2). It is vastly preferable to have many minor releases and removal of known-broken older versions, and use the constraint solver for the purpose it was created.

The current hotfixing of the upstream packages should not be necessary and actively breaks many of the assumptions in OPAM packaging and results in more build failures for end users of your packages.

**Comment by lefessan** [comment]
> I'm afraid hotfixing is the optimally bad solution, as users who haven't updated will break a formerly working installation.
Not updating before installing is wrong anyway. Even Debian/Ubuntu fail in such cases.

> this is a guideline rather than a rule
Well, it seems that some repo maintainers are not aware of this distinction...

> The current hotfixing of the upstream packages should not be necessary and actively breaks many of the assumptions in OPAM packaging and results in more build failures for end users of your packages.

ocp-build.1.99.19-beta was released less than a week ago. I am only hot-fixing during this week and for compatibility breaking problems. It's likely that more end-users have problems with the bugs than problems with the temporary hot-fixes.

**Comment by avsm** [comment]
> I am only hot-fixing during this week and for compatibility breaking problems.

It's really up to you.  This bug is a prime example of the problems it creates -- fdopen's windows remote lags your hotfixes. It's far easier to keep track of version updates than it is of metadata updates. 

I'm not telling you how to maintain your packages -- however, I am correcting some of the misconceptions in your justification for your hotfixing for others who read this thread. There is no problem with frequent version updates from an OPAM solver perspective, and this really helps the CI which can test each version independently and in combination.

If you really want to do a hotfix, another alternative is to do a removal/addition of a package with a different version number. This would at least help downstream maintainers like fdopen keep in sync by just the version number of ocp-build.  You mentioned Ubuntu and Debian earlier -- this is also in line with their versioning scheme which bumps the epoch rather than just replace a binary package in-place.

**Comment by lefessan** [comment]
> however, I am correcting some of the misconceptions in your justification for your hotfixing for others who read this thread. There is no problem with frequent version updates from an OPAM solver perspective.

Then, let me correct your own misconceptions : In this article http://www.dicosmo.org/Articles/2012-AbateDiCosmoTreinenZacchiroli-Jss.pdf , written by the authors of `dose3`, used by `opam`, there are some measurements of the time spent by different solvers, including `aspcud`, depending on the number of versions. For example, page 17, table 3, increasing the number of versions by a factor of 4 (i.e. 4 repos instead of 1), `aspcud` spends 3000s instead of 68s, i.e. a factor of 44, to solve a set of requests.

So, I agree that users should be encouraged to use minor version updates instead of hot fixing when possible, but it means that we should deprecate old versions more aggressively,  and that would only be possible if opam 1.2 is deprecated and opam 2.0, which is now stable, becomes the official version.

**Comment by dbuenzli** [comment]
Regardless of the `opam`/solver issue, once you put a tarball on the internet you put a name and associated data in a distributed system. It shouldn't be too hard to see the value of having them immutable. 

Your tarball will be absorbed by other automated systems, repackaged, etc. By altering the contents of the tarball, issues become difficult to track and you are creating trouble to people who try to further value and advertise your work.

**Comment by lefessan** [comment]
> Regardless of the opam/solver issue, [...]

The `opam`/solver issue is the reason why I'm doing hot-fixing like that, just after the release. Regardless of this reason, I am pretty sure we all have the same opinion.

**Comment by avsm** [comment]
@lefessan said:
> Then, let me correct your own misconceptions : In this article http://www.dicosmo.org/Articles/2012-AbateDiCosmoTreinenZacchiroli-Jss.pdf , written by the authors of dose3, used by opam, there are some measurements of the time spent by different solvers, including aspcud, depending on the number of versions. For example, page 17, table 3, increasing the number of versions by a factor of 4 (i.e. 4 repos instead of 1), aspcud spends 3000s instead of 68s, i.e. a factor of 44, to solve a set of requests.

Indeed, let's read that excellent paper. Increasing total packages by a factor of 4 makes a difference. Meanwhile, you are adding probably an additional 5-10 packages due to hotfixing, which will synchronously make no practical difference to solver times.  The overall opam repository growth can be handled in a number of ways : for example by deprecating all OCaml <4.00.1 packages from the default remote (leaving them available in an archived one). 

> only be possible if opam 1.2 is deprecated and opam 2.0, which is now stable, becomes the official version.

Not true unfortunately -- the compilers-as-packages feature _did_ put a lot of pressure on the opam2 solver, so opam2-alphas were slower to use day-to-day. @altgr has done a lot of work on this, and recent betas are far better, but opam 1.2 currently has found a nice sweet spot for interactive speed.

I have suggested an answer in the thread above that will work immediately:
> @avsm: If you really want to do a hotfix, another alternative is to do a removal/addition of a package with a different version number.

Do you see the irony of not versioning your packages in order to fix a perceived problem with a versioning system that you maintain? :-)

To be clear, at no point do we refuse to remove packages if a maintainer doesn't want them in the tree anymore. We simply recommend that they not be removed, but several maintainers have in the past requested and removed their packages, and ocp-build is welcome to do so as well if you think that's the best way to serve your users.

**Comment by lefessan** [comment]
> Increasing total packages by a factor of 4 makes a difference. Meanwhile, you are adding probably an additional 5-10 packages due to hotfixing, which will synchronously make no practical difference to solver times.

Of course, if I am the only one adding versions for hot fixes, it will make no difference. But if everybody adds one or two minor versions per release, it will add a factor of 2 or 3...

**Comment by AltGr** [comment]
Just a note on the error:
```
Bad checksum for /home/hugo/.opam/packages.dev/ocp-build.1.99.19-beta/1.99.19-beta.tar.gz:
          - ac7000cfff5a0d94970050fa86f93667 [expected result]
          - e4d5e3bc256091b5907a43613c33411c [actual result]
```

opam 2 has a per-hash cache, and the server will keep the older file corresponding to the package for a while. This means that even people who didn't `opam update` will still be able to get the (older) file, without error.

**Pull request merged**
