### PR TITLE
Let's use `conf-{expat,gtk2,udunits}`

### PR DESCRIPTION
**Pull request by OCamlPro-Henry**
In a ongoing effort to regroup `depext` into "virtual" packages named `conf-*`, this PR updates the `opam` file for:

- lablgtk (\cc @garrigue )
- udunits (\cc @hcarty )

### CODE REVIEW

**Comment by hcarty** [comment]
Looks good to me, thanks!

**Comment by OCamlPro-Henry** [comment]
Hmm, the existing `conf-expat` is failing in the CI because the Ubuntu package `libexpat`-dev` on Precise does not provide a proper pkg-config file.

I will look for an alternative test.

**Comment by dsheets** [comment]
From Ubuntu Precise:

```
# dpkg -L libexpat1-dev
/.
/usr
/usr/share
/usr/share/doc-base
/usr/share/doc-base/expat
/usr/share/aclocal
/usr/share/aclocal/expat.m4
/usr/share/doc
/usr/share/doc/libexpat1-dev
/usr/share/doc/libexpat1-dev/examples
/usr/share/doc/libexpat1-dev/examples/elements.c
/usr/share/doc/libexpat1-dev/examples/outline.c
/usr/share/doc/libexpat1-dev/expat.html
/usr/share/doc/libexpat1-dev/expat.html/reference.html
/usr/share/doc/libexpat1-dev/expat.html/xmlwf.1.gz
/usr/share/doc/libexpat1-dev/expat.html/style.css
/usr/share/doc/libexpat1-dev/expat.html/expat.png
/usr/share/doc/libexpat1-dev/expat.html/xmlwf.sgml.gz
/usr/share/doc/libexpat1-dev/expat.html/valid-xhtml10.png
/usr/share/doc/libexpat1-dev/copyright
/usr/share/doc/libexpat1-dev/README.gz
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libexpat.la
/usr/lib/x86_64-linux-gnu/libexpatw.la
/usr/lib/x86_64-linux-gnu/libexpat.a
/usr/lib/x86_64-linux-gnu/libexpatw.a
/usr/include
/usr/include/expat.h
/usr/include/expat_config.h
/usr/include/expat_external.h
/usr/share/doc/libexpat1-dev/expat.html/index.html
/usr/share/doc/libexpat1-dev/changelog.Debian.gz
/usr/lib/x86_64-linux-gnu/libexpatw.so
/usr/lib/x86_64-linux-gnu/libexpat.so
```

But Debian seems to actually ship the `.pc` file. I think `conf-expat.1` should maybe be called `conf-expat.2` since it seems to actually install version 2.0 on most of the platforms. OS X ships with expat 1.5.

**Comment by samoht** [comment]
@OCamlPro-Henry what should we do with this PR?

**Comment by OCamlPro-Henry** [comment]
I intend to fix this this.

**Pull request closed without merging**
