### PR TITLE
lutin: Use conf-* packages instead of custom depexts

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Picked from #19031 
cc @jahierwan

### CODE REVIEW

**Comment by mseri** [comment]
There are a number of extra failures. Do you want to try and fix them?

**Comment by jahierwan** [comment]
I cannot push on your branch, so I've created a new PR (as you asked, if I've understood correctly)
 https://github.com/ocaml/opam-repository/pull/19091

**Comment by mseri** [comment]
Oh, I was asking @kit-ty-kate. Thanks for picking it up @jahierwan 
I am closing this since it is superseded by the other PR

**Comment by jahierwan** [comment]
No problem. I was actually answering to him too, so we are even :)
Thanks anyway.

**Comment by mseri** [comment]
her*

**Comment by jahierwan** [comment]
oups...

**Pull request closed without merging**
