### PR TITLE
Add a constraint on encore.0.3 to not compile with OCaml >= 4.07

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by samoht** [comment]
Seems broken on 4.07: https://ci.ocaml.org/log/saved/docker-run-1431c98911b51cf4593de1ea787e414f/705c55fb8da1e5716e64c876f395e5ed753861ac

```
#=== ERROR while compiling encore.0.3 =========================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/mirage/encore/releases/download/v0.3/encore-v0.3.tbz)
# path                 ~/.opam/4.07/.opam-switch/build/encore.0.3
# command              ~/.opam/4.07/bin/dune runtest -p encore -j 2
# exit-code            1
# env-file             ~/.opam/log/encore-29-cec83f.env
# output-file          ~/.opam/log/encore-29-cec83f.out
### output ###
#     ocamlopt test/test.exe (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlopt.opt -w -40 -g -o test/test.exe -I /home/opam/.opam/4.07/lib/alcotest -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/cmdliner -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/uuidm -I lib -I lib/butils /home/opam/.opam/4.07/lib/stdlib-shims/stdlib_shims.cmxa /home/opam/.opam/4.07/lib/fmt/fmt.cmxa /home/opam/.opam/4.07/lib/astring/astring.cmxa /home/opam/.opam/4.07/lib/result/result.cmxa /home/opam/.opam/4.07/lib/cmdliner/cmdliner.cmxa /home/opam/.opam/4.07/lib/fmt/fmt_cli.cmxa /home/opam/.opam/4.07/lib/ocaml/unix.cmxa /home/opam/.opam/4.07/lib/fmt/fmt_tty.cmxa /home/opam/.opam/4.07/lib/uuidm/uuidm.cmxa /home/opam/.opam/4.07/lib/alcotest/alcotest.cmxa lib/butils/butils.cmxa /home/opam/.opam/4.07/lib/bigarray-compat/bigarray_compat.cmxa /home/opam/.opam/4.07/lib/ke/ke.cmxa /home/opam/.opam/4.07/lib/bigstringaf/bigstringaf.cmxa /home/opam/.opam/4.07/lib/angstrom/angstrom.cmxa lib/Encore.cmxa test/.test.eobjs/native/test.cmx)
# File "_none_", line 1:
# Error: No implementations provided for the following modules:
#          Bigarray referenced from lib/Encore.cmxa(Encore__Lole)
```

**Comment by dinosaure** [comment]
Fixed!

**Comment by kit-ty-kate** [comment]
I think it would be better to add this constraint at the same time than releasing `encore.0.4` (or 0.3.1 or something)

**Comment by kit-ty-kate** [comment]
This package is not strictly broken with 4.07 and up, only the tests and some of the uses.

**Comment by samoht** [comment]
if only the tests are broken on 4.07, maybe just add this constraint to the test stanza.

**Comment by dinosaure** [comment]
According [OCaml 4.07.0](https://github.com/ocaml/ocaml/blob/trunk/Changes#L1819) the error reported when we compile tests is not only local and may triggered by end-user (as @andreas has reported [here](https://github.com/ocaml/ocaml/blob/trunk/Changes#L1819) and included into `0.4`). I would like to be conservative in this specific problem.

**Comment by kit-ty-kate** [comment]
Sorry for not seeing that encore.0.4 had been released already. Merging, thanks.

**Pull request merged**
