### PR TITLE
added clangml.0.5.2 which works fine with OCaml 4.02.3

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I am trying to get rid of all warnings and errors right now

**Comment by UnixJunkie** [comment]
Is there a simple way to say the package is not supposed to compile with a system switch?

**Comment by samoht** [comment]
See `preinstalled` in the [manual](https://opam.ocaml.org/doc/manual/dev-manual.html). You can use:

```
available: [ !preinstalled ]
```

**Comment by UnixJunkie** [comment]
cool, thanks for the tip!

**Comment by UnixJunkie** [comment]
I restarted from fresh in here https://github.com/ocaml/opam-repository/pull/4697

**Pull request closed without merging**
