### PR TITLE
GT.0.4.0

### PR DESCRIPTION
**Pull request by Kakadu**

### CODE REVIEW

**Comment by Kakadu** [comment]
There are issues related to oracle linux that should be ignored because of https://github.com/ocaml/opam-repository/issues/17897

**Comment by kit-ty-kate** [comment]
I cleaned up the file a bit, could this be returned upstream?

It should be good to go once CI is done (just to double-check). Thanks!

**Comment by Kakadu** [comment]
@kit-ty-kate I added more precise version of dune back (because version 2.7.0 has an important bug). Other changes are OK to me.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
