### PR TITLE
Allow ocamlformat.0.19.0 to be compiled on OCaml 4.14

### PR DESCRIPTION
**Pull request by kit-ty-kate**
cc @gpetiot does that looks ok to you? I’m not seeing any errors or warnings when compiling and the [changelog](https://github.com/ocaml/ocaml/blob/trunk/Changes) only lists things that should not require special code in ocamlformat (at least from what I can guess):
```
### Language features:

- #10462: Add attribute to produce a compiler error for polls.

- #10437: Allow explicit binders for type variables.

- #10441: Remove unnecessary parentheses surrounding immediate objects.
  Allow 'object ... end # f', 'f object ... end', etc.

- #181, #9760: opt-in tail-modulo-cons (TMC) transformation
    let[@tail_mod_cons] rec map f li = ...
 ```

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @emillon

**Comment by gpetiot** [comment]
> - #10462: Add attribute to produce a compiler error for polls.

There is nothing to do


> - #10437: Allow explicit binders for type variables.

This should work with https://github.com/ocaml-ppx/ocamlformat/pull/1757


> - #10441: Remove unnecessary parentheses surrounding immediate objects.
>   Allow 'object ... end # f', 'f object ... end', etc.

This should work with https://github.com/ocaml-ppx/ocamlformat/pull/1934


> - #181, #9760: opt-in tail-modulo-cons (TMC) transformation
>    let[@tail_mod_cons] rec map f li = ...

There is nothing to do

**Comment by kit-ty-kate** [comment]
Ok fair enough. I'll close this then. Could you make a new release of ocamlformat? It looks like everything is ready.

Thanks a lot!

**Comment by emillon** [comment]
In addition, I believe it's fine to let 0.19.0 build with ocaml 4.14. It won't be able to format certain 4.14 files but that's expected. Having 4.14 build more than 0.20+ can possibly help ocaml-ci with lint-fmt jobs too.

**Pull request closed without merging**
