### PR TITLE
Update yurt and ezsqlite

### PR DESCRIPTION
**Pull request by zshipko**

### CODE REVIEW

**Comment by mseri** [comment]
Looks good to me. I dont understand what is wrong with camelus

**Comment by zshipko** [comment]
Hmm, I'm not sure what to do about camelus since there are no logs or anything that I can see. What does "broken" mean here?

**Comment by mseri** [comment]
I don’t know. I checked again and seems all fine. Merging

**Comment by zshipko** [comment]
Thanks!

**Pull request merged**
