### PR TITLE
Remove all pinned dependency from opam-repository

### LINKED ISSUE #14978: Usage of `pin-depends` in opam-repository released packages
Dear valued maintainers,

opam packages released to opam-repository contain checksums of tarballs to ensure that the same tarball is used for installation as intended by the person doing a release. opam packages which point to a branch / tag are generally not accepted AFAICT.

opam 2.0 introduced a `pin-depends` stanza to specify dependencies of certain off-trunk dependencies (i.e. a custom version of yyy). I just discovered that the opam-repository contains few packages with `pin-depends`, which I assume should not be there, applying the same rule above.

```bash
# git grep -A1 pin-depends
packages/emile/emile.0.5/opam:pin-depends: [
packages/emile/emile.0.5/opam-  [ "mrmime.dev" "git+https://github.com/mirage/mrmime.git" ]
--
packages/mirage-block-xen/mirage-block-xen.1.6.2/opam:pin-depends: [
packages/mirage-block-xen/mirage-block-xen.1.6.2/opam-  ["mirage-xen.dev" "git+https://github.com/mirage/mirage-xen"]
--
packages/mrmime/mrmime.0.1.0/opam:pin-depends: [
packages/mrmime/mrmime.0.1.0/opam-  [ "crowbar.dev" "git+https://github.com/stedolan/crowbar.git" ]
--
packages/sendmail-lwt/sendmail-lwt.0.1.0/opam:pin-depends: [
packages/sendmail-lwt/sendmail-lwt.0.1.0/opam-  [ "crowbar.dev" "git+https://github.com/stedolan/crowbar.git" ]
--
packages/sendmail/sendmail.0.1.0/opam:pin-depends: [
packages/sendmail/sendmail.0.1.0/opam-  [ "crowbar.dev" "git+https://github.com/stedolan/crowbar.git" ]
```

//cc @kit-ty-kate @AltGr  @camelus maybe camelus should discover and warn the usage thereof? (it could as well warn/error if there's no checksum)

//cc @dinosaure (who's the maintainer of most packages above)

(see #14977 for a fix of mirage-block-xen)

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes #14978

cc @hannesm

### CODE REVIEW

**Comment by hannesm** [comment]
thanks!

**Comment by kit-ty-kate** [comment]
cc @dinosaure there is an issue on emile with ocaml 4.07. It is unrelated to this PR and won't influence the merge but it's worth looking into it
```
#=== ERROR while compiling emile.0.5 ==========================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/dinosaure/emile/releases/download/v0.5/emile-v0.5.tbz)
# path                 ~/.opam/4.07/.opam-switch/build/emile.0.5
# command              ~/.opam/4.07/bin/dune runtest -p emile -j 2
# exit-code            1
# env-file             ~/.opam/log/emile-29-384e1f.env
# output-file          ~/.opam/log/emile-29-384e1f.out
### output ###
#     ocamlopt test/test.exe (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlopt.opt -w -40 -w -14 -g -o test/test.exe -I /home/opam/.opam/4.07/lib/alcotest -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/base64 -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/cmdliner -I /home/opam/.opam/4.07/lib/domain-name -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/ipaddr -I /home/opam/.opam/4.07/lib/macaddr -I /home/opam/.opam/4.07/lib/pecu -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/uchar -I /home/opam/.opam/4.07/lib/uuidm -I /home/opam/.opam/4.07/lib/uutf -I lib /home/opam/.opam/4.07/lib/stdlib-shims/stdlib_shims.cmxa /home/opam/.opam/4.07/lib/fmt/fmt.cmxa /home/opam/.opam/4.07/lib/astring/astring.cmxa /home/opam/.opam/4.07/lib/result/result.cmxa /home/opam/.opam/4.07/lib/cmdliner/cmdliner.cmxa /home/opam/.opam/4.07/lib/fmt/fmt_cli.cmxa /home/opam/.opam/4.07/lib/ocaml/unix.cmxa /home/opam/.opam/4.07/lib/fmt/fmt_tty.cmxa /home/opam/.opam/4.07/lib/uuidm/uuidm.cmxa /home/opam/.opam/4.07/lib/alcotest/alcotest.cmxa /home/opam/.opam/4.07/lib/base64/base64.cmxa /home/opam/.opam/4.07/lib/bigarray-compat/bigarray_compat.cmxa /home/opam/.opam/4.07/lib/bigstringaf/bigstringaf.cmxa /home/opam/.opam/4.07/lib/angstrom/angstrom.cmxa /home/opam/.opam/4.07/lib/uutf/uutf.cmxa /home/opam/.opam/4.07/lib/pecu/pecu.cmxa /home/opam/.opam/4.07/lib/macaddr/macaddr.cmxa /home/opam/.opam/4.07/lib/domain-name/domain_name.cmxa /home/opam/.opam/4.07/lib/ipaddr/ipaddr.cmxa lib/emile.cmxa test/.test.eobjs/native/test.cmx)
# File "_none_", line 1:
# Error: No implementations provided for the following modules:
#          Bigarray referenced from lib/emile.cmxa(Emile)
```

**Comment by kit-ty-kate** [comment]
There is also an issue with sendmail on ocaml 4.06:
```
#=== ERROR while compiling sendmail.0.1.0 =====================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.06.1 | pinned(https://github.com/dinosaure/colombe/releases/download/v0.1.0/colombe-v0.1.0.tbz)
# path                 ~/.opam/4.06/.opam-switch/build/sendmail.0.1.0
# command              ~/.opam/4.06/bin/dune build -p sendmail -j 2
# exit-code            1
# env-file             ~/.opam/log/sendmail-23-cdb742.env
# output-file          ~/.opam/log/sendmail-23-cdb742.out
### output ###
#       ocamlc sendmail/.sendmail_tls.objs/byte/sendmail_tls.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlc.opt -w -40 -g -bin-annot -I sendmail/.sendmail_tls.objs/byte -I /home/opam/.opam/4.06/lib/angstrom -I /home/opam/.opam/4.06/lib/asn1-combinators -I /home/opam/.opam/4.06/lib/astring -I /home/opam/.opam/4.06/lib/base/caml -I /home/opam/.opam/4.06/lib/base64 -I /home/opam/.opam/4.06/lib/bigarray-compat -I /home/opam/.opam/4.06/lib/bigstringaf -I /home/opam/.opam/4.06/lib/bytes -I /home/opam/.opam/4.06/lib/colombe -I /home/opam/.opam/4.06/lib/colombe/auth -I /home/opam/.opam/4.06/lib/colombe/enhanced_status_codes -I /home/opam/.opam/4.06/lib/colombe/mime -I /home/opam/.opam/4.06/lib/colombe/starttls -I /home/opam/.opam/4.06/lib/cstruct -I /home/opam/.opam/4.06/lib/cstruct-sexp -I /home/opam/.opam/4.06/lib/domain-name -I /home/opam/.opam/4.06/lib/fmt -I /home/opam/.opam/4.06/lib/gmap -I /home/opam/.opam/4.06/lib/hxd/core -I /home/opam/.opam/4.06/lib/hxd/string -I /home/opam/.opam/4.06/lib/ipaddr -I /home/opam/.opam/4.06/lib/logs -I /home/opam/.opam/4.06/lib/macaddr -I /home/opam/.opam/4.06/lib/nocrypto -I /home/opam/.opam/4.06/lib/parsexp -I /home/opam/.opam/4.06/lib/ppx_deriving/runtime -I /home/opam/.opam/4.06/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.06/lib/ptime -I /home/opam/.opam/4.06/lib/result -I /home/opam/.opam/4.06/lib/rresult -I /home/opam/.opam/4.06/lib/seq -I /home/opam/.opam/4.06/lib/sexplib -I /home/opam/.opam/4.06/lib/sexplib0 -I /home/opam/.opam/4.06/lib/stdlib-shims -I /home/opam/.opam/4.06/lib/tls -I /home/opam/.opam/4.06/lib/x509 -I /home/opam/.opam/4.06/lib/zarith -I sendmail/.sendmail.objs/byte -I sendmail/.sendmail.objs/native -no-alias-deps -o sendmail/.sendmail_tls.objs/byte/sendmail_tls.cmo -c -impl sendmail/sendmail_tls.ml)
# File "sendmail/sendmail_tls.ml", line 141, characters 17-23:
# Error: The GADT constructor PP_220 of type Send_mail_tls_p.t
#        must be qualified in this pattern.
```

**Comment by dinosaure** [comment]
Thanks, I will look into them this end of week :+1: !

**Pull request merged**
