### PR TITLE
[new release] xdg, stdune, ordering, ocamlc-loc, fiber, dyn, dune, dune-site, dune-rpc, dune-rpc-lwt, dune-private-libs, dune-glob, dune-configurator, dune-build-info, dune-action-plugin and chrome-trace (3.4.0)

### PR DESCRIPTION
**Pull request by emillon**
XDG Base Directory Specification

- Project page: <a href="https://github.com/ocaml/dune">https://github.com/ocaml/dune</a>
- Documentation: <a href="https://dune.readthedocs.io/">https://dune.readthedocs.io/</a>

##### CHANGES:

- Make `dune describe` correctly handle overlapping implementations
  for virtual libraries (ocaml/dune#5971, fixes ocaml/dune#5747, @esope)

- Building the `@check` alias should make sure the libraries and executables
  don't have dependency cycles (ocaml/dune#5892, @rgrinberg)

- [ctypes] Add support for the `errno` parameter using the `errno_policy` field
  in the ctypes settings. (ocaml/dune#5827, @droyo)

- Fix `dune coq top` when it is invoked on files from a subdirectory of the
  directory containing the associated stanza (ocaml/dune#5784, fixes ocaml/dune#5552, @ejgallego,
  @rlepigre, @Alizter)

- Fix hint when an invalid module name is found. (ocaml/dune#5922, fixes ocaml/dune#5273, @emillon)

- The `(cat)` action now supports several files. (ocaml/dune#5928, fixes ocaml/dune#5795, @emillon)

- Dune no longer uses shimmed `META` files for OCaml 5.x, solely using the ones
  installed by the compiler. (ocaml/dune#5916, @dra27)

- Fix handling of the `(deps)` field in `(test)` stanzas when there is an
  `.expected` file. (ocaml/dune#5952, ocaml/dune#5951, fixes ocaml/dune#5950, @emillon)

- Ignore insignificant filesystem events. This stops RPC in watch mode from
  flashing errors on insignificant file system events such as changes in the
  `.git/` directory. (ocaml/dune#5953, @rgrinberg)

- Fix parsing more error messages emitted by the OCaml compiler. In
  particular, messages where the excerpt line number started with a blank
  character were skipped. (ocaml/dune#5981, @rgrinberg)

- env stanza: warn if some rules are ignored because they appear after a
  wildcard rule. (ocaml/dune#5898, fixes ocaml/dune#5886, @emillon)

- On Windows, XDG_CACHE_HOME is taken to be the `FOLDERID_InternetCache` if
  unset, and XDG_CONFIG_HOME and XDG_DATA_HOME are both taken to be
  `FOLDERID_LocalAppData` if unset.  (ocaml/dune#5943, fixes ocaml/dune#5808, @nojb)

### CODE REVIEW

**Comment by emillon** [comment]
I compared the revdeps failures to the ones of 5465bdd91925e9de144860d4024f0076c0156da3 which introduced 3.3.0.
Here are the packages that used to build but don't build anymore (I did that in a spreadsheet but let me know if you have better tools to do this like healthcheck).
I think that this is the list we have to investigate.

- [ ] alcotest-async.1.1.0
- [ ] alcotest-lwt.1.1.0
- [ ] bap-ghidra.2.5.0
- [ ] combine.0.6
- [ ] curve-sampling.0.2.1
- [ ] fadbadml.0.1.2
- [ ] ffmpeg-swresample.1.0.0
- [ ] ffmpeg-swresample.1.0.0
- [ ] gsl.1.24.3
- [ ] lambda-term.2.0.3
- [ ] ocamlog.0.2
- [ ] orpie.1.6.1
- [ ] pareto.0.3
- [ ] phylogenetics.0.0.0
- [ ] phylogenetics.0.1.0
- [ ] prbnmcn-dagger-gsl.0.0.2
- [ ] prbnmcn-dagger-test.0.0.1
- [ ] prbnmcn-dagger-test.0.0.2
- [ ] prc.0.1.0
- [ ] revops.2.5
- [ ] ubpf.0.1

**Comment by emillon** [comment]
the gsl one looks like an actual issue

**Comment by emillon** [comment]
actually, no it looks like an issue with gsl itself. it's not correctly handling the case where pkg-config is installed but not libgsl

**Comment by emillon** [comment]
Alright, I had a look at all of them and none seem to be related to dune 3.4.0.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
