### PR TITLE
Update hiredis, resp-server. Add hiredis-value.

### PR DESCRIPTION
**Pull request by zshipko**

### CODE REVIEW

**Comment by zshipko** [comment]
Sorry, it looks like I need to fix the tests for the resp-server release.

**Comment by zshipko** [comment]
Okay, should be fixed now. It seems like the remaining errors are due to issues with 4.07 not being availabe for Alpine Linux yet.

**Comment by kit-ty-kate** [comment]
The error on Alpine is unrelated don't worry.
Could you add `"-p" name` to you test commands ? It would avoid problems in the future if you, for instance, add tests for `hiredis-value`.

**Comment by zshipko** [comment]
Yeah, no problem. I've add `"-p" name` for both `hiredis` and `resp-server`. Let me know if there's anything else that needs attention.

**Comment by kit-ty-kate** [comment]
It's all good. Thanks a lot!

**Pull request merged**
