### PR TITLE
+base,stdio and ocaml-compiler-libs v0.11.0

### PR DESCRIPTION
**Pull request by trefis**

### CODE REVIEW

**Comment by trefis** [comment]
I had forgotten some dependencies in my first commit, that's why camelus complained. This is now fixed.

**Comment by trefis** [comment]
I don't really understand the ci failures.
Looking at [async_ssl revdep failure](https://ci.ocamllabs.io/log/saved/docker-run-9ae58d5300363f7962ccefcf79bb9c1c/07876438645bf5ed97baaa0aa81ef032b63790f6) for example:
- it's trying to install async_ssl v0.10
- it fails to install some v0.10 ppxs, because of some error in ppx_inline_test.dune (where does that file come from? we still have jbuild files in the sources AFAIK)

Am I wrong if I assume this is a problem with jbuilder?

Ping @diml , @rgrinberg , @avsm .

**Comment by trefis** [comment]
I added a commit to conflict with jbuilder beta19. (I also added that conflict on ppx_inline_test which seemed to be the first source of trouble, although there are probably others lying around).

**Comment by trefis** [comment]
ocamlformat and tensorflow are not compatible with base v0.11 and I updated their opam file with the right constraints.

That's the only revdep failures there were.

**Comment by trefis** [comment]
The "Distros" failure seems to be on alpine with things that appear completely unrelated to this PR, cf. [this log](https://ci.ocamllabs.io/log/saved/docker-build-470bd9c2c955cec953a479d73405a749/d47707fc13b451742a3448bfe7a8a90fd5b2b513), and in particular:

```
=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  - install jsonm       1.0.1  
  - install ocamlfind   1.7.3-1
  - install topkg       0.9.1  
  - install travis-opam 1.2.0  
  - install uutf        1.0.1  
The following actions failed
  - install conf-m4 1
The following changes have been performed
  - remove  travis-opam 1.0.3     
  - install jbuilder    1.0+beta19
  - install result      1.3       
  - install uchar       0.0.2     

=-=- conf-m4.1 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing.
   `opam depext conf-m4.1' may help you find the correct installation for your
   system.
```

**Comment by jpdeplaix** [comment]
Don't worry about the alpine failures. It's quite a long standing bug(s)

**Comment by trefis** [comment]
> is it normal to have a new package `sexplib0` ?

Yes.

**Comment by hcarty** [comment]
@trefis Can the jbuilder conflict be removed now that beta19 has been pulled from opam?

**Comment by trefis** [comment]
Done.

FTR the previous CI logs are [here](https://arm64.ci.ocamllabs.io/ocaml/opam-repository/pr/11591?history=69f14e54df6e0159192d3e26b3dd5ee8f30f09e9&test=2%20arm64%20V2.0%20Revdeps) and the failure still appear unrelated to this PR.

**Comment by trefis** [comment]
Some of the current failures seem to be transient random failures, e.g.
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - cohttp-lwt-unix.0.99.0
```

**Comment by hcarty** [comment]
Thank you @trefis!

@jpdeplaix Ok to merge?

**Comment by jpdeplaix** [comment]
Yes, all green. Thanks a lot !

**Pull request merged**
