### PR TITLE
8 packages from savonet/ocaml-ffmpeg at 1.2.1

### PR DESCRIPTION
**Pull request by toots**
This pull-request concerns:
- `ffmpeg.1.2.1`: Bindings for the ffmpeg libraries
- `ffmpeg-av.1.2.1`: Bindings for the ffmpeg libraries -- top-level helpers
- `ffmpeg-avcodec.1.2.1`: Bindings for the ffmpeg avcodec library
- `ffmpeg-avdevice.1.2.1`: Bindings for the ffmpeg avdevice library
- `ffmpeg-avfilter.1.2.1`: Bindings for the ffmpeg avfilter library
- `ffmpeg-avutil.1.2.1`: Bindings for the ffmpeg avutil libraries
- `ffmpeg-swresample.1.2.1`: Bindings for the ffmpeg swresample library
- `ffmpeg-swscale.1.2.1`: Bindings for the ffmpeg swscale library

---
* Homepage: https://github.com/savonet/ocaml-ffmpeg
* Source repo: git+https://github.com/savonet/ocaml-ffmpeg.git
* Bug tracker: https://github.com/savonet/ocaml-ffmpeg/issues

---
:camel: Pull-request generated by opam-publish v2.3.0

### CODE REVIEW

**Comment by shonfeder** [comment]
Most platforms are failing CI here:

<details>

```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> retrieved csexp.1.5.2  (cached)
-> installed conf-pkg-config.3
-> installed conf-ffmpeg.1
-> retrieved dune.3.16.0, dune-configurator.3.16.0  (cached)
-> retrieved ffmpeg-av.1.2.1, ffmpeg-avcodec.1.2.1, ffmpeg-avutil.1.2.1  (cached)
-> installed dune.3.16.0
-> installed csexp.1.5.2
-> installed dune-configurator.3.16.0
[ERROR] The compilation of ffmpeg-avutil.1.2.1 failed at "dune build -p ffmpeg-avutil -j 31 @install".

#=== ERROR while compiling ffmpeg-avutil.1.2.1 ================================#
# context              2.4.0~alpha1~dev | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/ffmpeg-avutil.1.2.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ffmpeg-avutil -j 31 @install
# exit-code            1
# env-file             ~/.opam/log/ffmpeg-avutil-7-edb5f4.env
# output-file          ~/.opam/log/ffmpeg-avutil-7-edb5f4.out
### output ###
# File "avutil/dune", line 7, characters 9-21:
# 7 |   (names avutil_stubs)
#              ^^^^^^^^^^^^
# (cd _build/default/avutil && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -I/usr/include/x86_64-linux-gnu -g -I /home/opam/.opam/4.14/lib/ocaml -I /home/opam/.opam/4.14/lib/ocaml/threads -o avutil_stubs.o -c avutil_stubs.c)
# In file included from avutil_stubs.c:21:
# avutil_stubs.h:65:1: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#    65 | AVChannelLayout *caml_avutil_alloc_custom_channel_layout(value *v);
#       | ^~~~~~~~~~~~~~~
#       | AVChannelLayout_val
# avutil_stubs.h:66:46: error: unknown type name 'AVChannelLayout'
#    66 | void value_of_channel_layout(value *v, const AVChannelLayout *);
#       |                                              ^~~~~~~~~~~~~~~
# avutil_stubs.c: In function 'finalize_channel_layout':
# avutil_stubs.c:331:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#   331 |   AVChannelLayout *channel_layout = AVChannelLayout_val(v);
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# In file included from avutil_stubs.c:21:
# avutil_stubs.h:63:32: warning: initialization of 'int *' from incompatible pointer type 'struct AVChannelLayout *' [-Wincompatible-pointer-types]
#    63 | #define AVChannelLayout_val(v) (*(struct AVChannelLayout **)Data_custom_val(v))
#       |                                ^
# avutil_stubs.c:331:37: note: in expansion of macro 'AVChannelLayout_val'
#   331 |   AVChannelLayout *channel_layout = AVChannelLayout_val(v);
#       |                                     ^~~~~~~~~~~~~~~~~~~
# avutil_stubs.c:332:3: warning: implicit declaration of function 'av_channel_layout_uninit'; did you mean 'av_get_channel_layout_string'? [-Wimplicit-function-declaration]
#   332 |   av_channel_layout_uninit(channel_layout);
#       |   ^~~~~~~~~~~~~~~~~~~~~~~~
#       |   av_get_channel_layout_string
# avutil_stubs.c: At top level:
# avutil_stubs.c:341:1: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#   341 | AVChannelLayout *caml_avutil_alloc_custom_channel_layout(value *ret) {
#       | ^~~~~~~~~~~~~~~
#       | AVChannelLayout_val
# avutil_stubs.c: In function 'caml_avutil_alloc_custom_channel_layout':
# avutil_stubs.c:342:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#   342 |   AVChannelLayout *ch_layout;
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# avutil_stubs.c:345:33: error: 'AVChannelLayout' undeclared (first use in this function); did you mean 'Val_ChannelLayout'?
#   345 |   ch_layout = av_mallocz(sizeof(AVChannelLayout));
#       |                                 ^~~~~~~~~~~~~~~
#       |                                 Val_ChannelLayout
# avutil_stubs.c:345:33: note: each undeclared identifier is reported only once for each function it appears in
# avutil_stubs.c:351:70: error: expected expression before ')' token
#   351 |       caml_alloc_custom(&channel_layout_ops, sizeof(AVChannelLayout *), 0, 1);
#       |                                                                      ^
# avutil_stubs.c:352:29: warning: assignment to 'struct AVChannelLayout *' from incompatible pointer type 'int *' [-Wincompatible-pointer-types]
#   352 |   AVChannelLayout_val(*ret) = ch_layout;
#       |                             ^
# avutil_stubs.c: At top level:
# avutil_stubs.c:358:36: error: unknown type name 'AVChannelLayout'
#   358 |                              const AVChannelLayout *channel_layout) {
#       |                                    ^~~~~~~~~~~~~~~
# avutil_stubs.c: In function 'value_of_channel_layout':
# avutil_stubs.c:359:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#   359 |   AVChannelLayout *ch_layout = caml_avutil_alloc_custom_channel_layout(ret);
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# avutil_stubs.c:362:9: warning: implicit declaration of function 'av_channel_layout_copy' [-Wimplicit-function-declaration]
#   362 |   err = av_channel_layout_copy(ch_layout, channel_layout);
#       |         ^~~~~~~~~~~~~~~~~~~~~~
# avutil_stubs.c: In function 'ocaml_avutil_get_standard':
# avutil_stubs.c:403:9: error: unknown type name 'AVChannelLayout'
#   403 |   const AVChannelLayout *channel_layout = av_channel_layout_standard(opaque);
#       |         ^~~~~~~~~~~~~~~
# avutil_stubs.c:403:43: warning: implicit declaration of function 'av_channel_layout_standard'; did you mean 'av_get_channel_layout_string'? [-Wimplicit-function-declaration]
#   403 |   const AVChannelLayout *channel_layout = av_channel_layout_standard(opaque);
#       |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
#       |                                           av_get_channel_layout_string
# avutil_stubs.c:403:43: warning: initialization of 'const int *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
# avutil_stubs.c: In function 'ocaml_avutil_compare_channel_layout':
# avutil_stubs.c:420:13: warning: implicit declaration of function 'av_channel_layout_compare' [-Wimplicit-function-declaration]
#   420 |   int ret = av_channel_layout_compare(AVChannelLayout_val(_layout1),
#       |             ^~~~~~~~~~~~~~~~~~~~~~~~~
# avutil_stubs.c: In function 'ocaml_avutil_get_channel_native_id':
# avutil_stubs.c:433:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#   433 |   AVChannelLayout *channel_layout = AVChannelLayout_val(_channel_layout);
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# In file included from avutil_stubs.c:21:
# avutil_stubs.h:63:32: warning: initialization of 'int *' from incompatible pointer type 'struct AVChannelLayout *' [-Wincompatible-pointer-types]
#    63 | #define AVChannelLayout_val(v) (*(struct AVChannelLayout **)Data_custom_val(v))
#       |                                ^
# avutil_stubs.c:433:37: note: in expansion of macro 'AVChannelLayout_val'
#   433 |   AVChannelLayout *channel_layout = AVChannelLayout_val(_channel_layout);
#       |                                     ^~~~~~~~~~~~~~~~~~~
# avutil_stubs.c:435:21: error: request for member 'order' in something not a structure or union
#   435 |   if (channel_layout->order != AV_CHANNEL_ORDER_NATIVE)
#       |                     ^~
# avutil_stubs.c:435:32: error: 'AV_CHANNEL_ORDER_NATIVE' undeclared (first use in this function)
#   435 |   if (channel_layout->order != AV_CHANNEL_ORDER_NATIVE)
#       |                                ^~~~~~~~~~~~~~~~~~~~~~~
# In file included from avutil_stubs.c:12:
# avutil_stubs.c:439:53: error: request for member 'u' in something not a structure or union
#   439 |   Store_field(ans, 0, caml_copy_int64(channel_layout->u.mask));
#       |                                                     ^~
# /home/opam/.opam/4.14/lib/ocaml/caml/memory.h:475:27: note: in definition of macro 'Store_field'
#   475 |   value caml__temp_val = (val); \
#       |                           ^~~
# avutil_stubs.c: In function 'ocaml_avutil_get_channel_layout_description':
# avutil_stubs.c:447:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#   447 |   AVChannelLayout *channel_layout = AVChannelLayout_val(_channel_layout);
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# In file included from avutil_stubs.c:21:
# avutil_stubs.h:63:32: warning: initialization of 'int *' from incompatible pointer type 'struct AVChannelLayout *' [-Wincompatible-pointer-types]
#    63 | #define AVChannelLayout_val(v) (*(struct AVChannelLayout **)Data_custom_val(v))
#       |                                ^
# avutil_stubs.c:447:37: note: in expansion of macro 'AVChannelLayout_val'
#   447 |   AVChannelLayout *channel_layout = AVChannelLayout_val(_channel_layout);
#       |                                     ^~~~~~~~~~~~~~~~~~~
# avutil_stubs.c:448:13: warning: implicit declaration of function 'av_channel_layout_describe'; did you mean 'av_get_channel_layout_string'? [-Wimplicit-function-declaration]
#   448 |   int err = av_channel_layout_describe(channel_layout, buf, sizeof(buf));
#       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
#       |             av_get_channel_layout_string
# avutil_stubs.c: In function 'ocaml_avutil_get_channel_layout_nb_channels':
# avutil_stubs.c:459:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#   459 |   AVChannelLayout *channel_layout = AVChannelLayout_val(_channel_layout);
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# In file included from avutil_stubs.c:21:
# avutil_stubs.h:63:32: warning: initialization of 'int *' from incompatible pointer type 'struct AVChannelLayout *' [-Wincompatible-pointer-types]
#    63 | #define AVChannelLayout_val(v) (*(struct AVChannelLayout **)Data_custom_val(v))
#       |                                ^
# avutil_stubs.c:459:37: note: in expansion of macro 'AVChannelLayout_val'
#   459 |   AVChannelLayout *channel_layout = AVChannelLayout_val(_channel_layout);
#       |                                     ^~~~~~~~~~~~~~~~~~~
# In file included from avutil_stubs.c:12:
# avutil_stubs.c:460:36: error: request for member 'nb_channels' in something not a structure or union
#   460 |   CAMLreturn(Val_int(channel_layout->nb_channels));
#       |                                    ^~
# /home/opam/.opam/4.14/lib/ocaml/caml/memory.h:462:29: note: in definition of macro 'CAMLreturnT'
#   462 |   type caml__temp_result = (result); \
#       |                             ^~~~~~
# avutil_stubs.c:460:3: note: in expansion of macro 'CAMLreturn'
#   460 |   CAMLreturn(Val_int(channel_layout->nb_channels));
#       |   ^~~~~~~~~~
# /home/opam/.opam/4.14/lib/ocaml/caml/mlvalues.h:79:20: note: in expansion of macro 'Val_long'
#    79 | #define Val_int(x) Val_long(x)
#       |                    ^~~~~~~~
# avutil_stubs.c:460:14: note: in expansion of macro 'Val_int'
#   460 |   CAMLreturn(Val_int(channel_layout->nb_channels));
#       |              ^~~~~~~
# avutil_stubs.c: In function 'ocaml_avutil_get_default_channel_layout':
# avutil_stubs.c:466:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#   466 |   AVChannelLayout *channel_layout =
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# avutil_stubs.c:469:3: warning: implicit declaration of function 'av_channel_layout_default' [-Wimplicit-function-declaration]
#   469 |   av_channel_layout_default(channel_layout, Int_val(_nb_channels));
#       |   ^~~~~~~~~~~~~~~~~~~~~~~~~
# avutil_stubs.c: In function 'ocaml_avutil_get_channel_layout':
# avutil_stubs.c:477:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#   477 |   AVChannelLayout *channel_layout =
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# avutil_stubs.c:480:13: warning: implicit declaration of function 'av_channel_layout_from_string'; did you mean 'av_get_channel_layout_string'? [-Wimplicit-function-declaration]
#   480 |   int err = av_channel_layout_from_string(channel_layout, String_val(_name));
#       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#       |             av_get_channel_layout_string
# avutil_stubs.c: In function 'ocaml_avutil_audio_create_frame':
# avutil_stubs.c:897:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#   897 |   AVChannelLayout *channel_layout = AVChannelLayout_val(_channel_layout);
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# In file included from avutil_stubs.c:21:
# avutil_stubs.h:63:32: warning: initialization of 'int *' from incompatible pointer type 'struct AVChannelLayout *' [-Wincompatible-pointer-types]
#    63 | #define AVChannelLayout_val(v) (*(struct AVChannelLayout **)Data_custom_val(v))
#       |                                ^
# avutil_stubs.c:897:37: note: in expansion of macro 'AVChannelLayout_val'
#   897 |   AVChannelLayout *channel_layout = AVChannelLayout_val(_channel_layout);
#       |                                     ^~~~~~~~~~~~~~~~~~~
# avutil_stubs.c:909:40: error: 'AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
#   909 |   ret = av_channel_layout_copy(&frame->ch_layout, channel_layout);
#       |                                        ^~~~~~~~~
#       |                                        channel_layout
# In file included from avutil_stubs.c:12:
# avutil_stubs.c: In function 'ocaml_avutil_audio_frame_get_channels':
# avutil_stubs.c:946:29: error: 'AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
#   946 |   CAMLreturn(Val_int(frame->ch_layout.nb_channels));
#       |                             ^~~~~~~~~
# /home/opam/.opam/4.14/lib/ocaml/caml/memory.h:462:29: note: in definition of macro 'CAMLreturnT'
#   462 |   type caml__temp_result = (result); \
#       |                             ^~~~~~
# avutil_stubs.c:946:3: note: in expansion of macro 'CAMLreturn'
#   946 |   CAMLreturn(Val_int(frame->ch_layout.nb_channels));
#       |   ^~~~~~~~~~
# /home/opam/.opam/4.14/lib/ocaml/caml/mlvalues.h:79:20: note: in expansion of macro 'Val_long'
#    79 | #define Val_int(x) Val_long(x)
#       |                    ^~~~~~~~
# avutil_stubs.c:946:14: note: in expansion of macro 'Val_int'
#   946 |   CAMLreturn(Val_int(frame->ch_layout.nb_channels));
#       |              ^~~~~~~
# avutil_stubs.c: In function 'ocaml_avutil_audio_frame_get_channel_layout':
# avutil_stubs.c:954:48: error: 'AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
#   954 |   value_of_channel_layout(&_ch_layout, &frame->ch_layout);
#       |                                                ^~~~~~~~~
#       |                                                channel_layout
# avutil_stubs.c: In function 'ocaml_avutil_audio_frame_copy_samples':
# avutil_stubs.c:978:23: error: 'AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
#   978 |   int channels = dst->ch_layout.nb_channels;
#       |                       ^~~~~~~~~
#       |                       channel_layout
# avutil_stubs.c:983:39: error: 'AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
#   983 |       av_channel_layout_compare(&dst->ch_layout, &src->ch_layout))
#       |                                       ^~~~~~~~~
#       |                                       channel_layout
# avutil_stubs.c:983:56: error: 'AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
#   983 |       av_channel_layout_compare(&dst->ch_layout, &src->ch_layout))
#       |                                                        ^~~~~~~~~
#       |                                                        channel_layout
# avutil_stubs.c: In function 'ocaml_avutil_get_opt':
# avutil_stubs.c:1198:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#  1198 |   AVChannelLayout *channel_layout;
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# avutil_stubs.c:1303:11: warning: implicit declaration of function 'av_opt_get_chlayout'; did you mean 'av_opt_get_channel_layout'? [-Wimplicit-function-declaration]
#  1303 |     err = av_opt_get_chlayout((void *)obj, (const char *)String_val(name),
#       |           ^~~~~~~~~~~~~~~~~~~
#       |           av_opt_get_channel_layout
# avutil_stubs.c: In function 'ocaml_avutil_av_opt_iter':
# avutil_stubs.c:1342:3: error: unknown type name 'AVChannelLayout'; did you mean 'AVChannelLayout_val'?
#  1342 |   AVChannelLayout *channel_layout;
#       |   ^~~~~~~~~~~~~~~
#       |   AVChannelLayout_val
# avutil_stubs.c:1419:8: error: 'AV_OPT_TYPE_CHLAYOUT' undeclared (first use in this function); did you mean 'AV_OPT_TYPE_COLOR'?
#  1419 |   case AV_OPT_TYPE_CHLAYOUT:
#       |        ^~~~~~~~~~~~~~~~~~~~
#       |        AV_OPT_TYPE_COLOR



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ffmpeg-avutil 1.2.1
+- 
+- The following changes have been performed (the rest was aborted)
| - install conf-ffmpeg       1
| - install conf-pkg-config   3
| - install csexp             1.5.2
| - install dune              3.16.0
| - install dune-configurator 3.16.0
+- 
# To update the current shell environment, run: eval $(opam env)
```

</details>

**Comment by toots** [comment]
Worth noting: this package depends on the most recent FFmpeg channels API and will fail to build on distributions that have FFmpeg 6.x or less.

**Comment by toots** [comment]
> Most platforms are failing CI here:

Looks like we posted at the same time! See above..

**Comment by shonfeder** [comment]
> > Most platforms are failing CI here:
> 
> Looks like we posted at the same time! See above..

I see! Thanks :) Do you think a post-install message would be warranted to guide users in case of build failure here?

**Comment by toots** [comment]
> > > Most platforms are failing CI here:
> > 
> > 
> > Looks like we posted at the same time! See above..
> 
> I see! Thanks :) Do you think a post-install message would be warranted to guide users in case of build failure here?

That's an excellent idea, I'll do that.

**Comment by toots** [comment]
> > > Most platforms are failing CI here:
> > 
> > 
> > Looks like we posted at the same time! See above..
> 
> I see! Thanks :) Do you think a post-install message would be warranted to guide users in case of build failure here?

Done!

**Comment by shonfeder** [comment]
> > > > Most platforms are failing CI here:
> > > 
> > > 
> > > Looks like we posted at the same time! See above..
> > 
> > 
> > I see! Thanks :) Do you think a post-install message would be warranted to guide users in case of build failure here?
> 
> Done!

It's a very polite message, and I can imagine it saving users some hours in the future. Thanks again for publishing your work! :)

**Pull request merged**
