### PR TITLE
mlgmpidl.1.2.6

### PR DESCRIPTION
**Pull request by nberth**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks good. The CI failure seems transitive.

**Comment by nberth** [comment]
By the way I've discovered a small bug in the package, so I'll push some changes very soon to avoid too many releases.

**Comment by nberth** [comment]
@avsm I think this new release of mlgmpidl triggers the same infinite loops during compilation on alpine/docker as we encountered with apron before.

**Comment by avsm** [comment]
Thanks for checking in the overlayfs workaround as well! The CentOS 7 issue is transient CI, so this is is good to merge.

**Pull request merged**
