### PR TITLE
Rewrite patch files so that they can be applied with -p1

### PR DESCRIPTION
**Pull request by AltGr**
See #6998

### CODE REVIEW

**Comment by AltGr** [comment]
Merging this would help me move opam forwards. Build failures seem unrelated and are found by opam-builder already.

**Comment by samoht** [comment]
I am opening new PRs to fix the issues found by your PR.

**Comment by yallop** [comment]
I've restarted the build now that #7651 is merged.

**Comment by samoht** [comment]
I've fixed few easy build errors, so I'm happy to merge now.

**Pull request merged**
