### PR TITLE
Update the lbfgs packages (camlp4, bug-reports, depext)

### PR DESCRIPTION
**Pull request by Chris00**
Supersedes https://github.com/ocaml/opam-repository/pull/7193

### CODE REVIEW

**Comment by samoht** [comment]
0.8.3 seems pretty broken:

```
#=== ERROR while installing lbfgs.0.8.3 =======================================#
# opam-version 1.2.2
# os           linux
# command      ocaml setup.ml -configure --prefix /home/travis/.opam/4.01.0
# path         /home/travis/.opam/4.01.0/build/lbfgs.0.8.3
# compiler     4.01.0
# exit-code    1
# env-file     /home/travis/.opam/4.01.0/build/lbfgs.0.8.3/lbfgs-18245-f936b0.env
# stdout-file  /home/travis/.opam/4.01.0/build/lbfgs.0.8.3/lbfgs-18245-f936b0.out
# stderr-file  /home/travis/.opam/4.01.0/build/lbfgs.0.8.3/lbfgs-18245-f936b0.err
### stdout ###
# [...]
# Remove a file.: ..................................... rm -f
# Remove a directory.: ................................ rm -rf
# Turn ocaml debug flag on: ........................... true
# Turn ocaml profile flag on: ......................... false
# Compiler support generation of .cmxs.: .............. true
# OCamlbuild additional flags: ........................ 
# Whether the lacaml findlib package is installed.: ... false
# pkg_bigarray: ....................................... /home/travis/.opam/4.01.0/lib/ocaml
# ocamldoc: ........................................... /home/travis/.opam/4.01.0/bin/ocamldoc
# 
### stderr ###
# E: Failure("No variable lbfgsb_wa_coef_n1 defined when trying to expand \"let wa_min_size n m = ($(lbfgsb_wa_coef_n1)) * n + $(lbfgsb_wa_coef_n0)\".")
```

**Comment by Chris00** [comment]
I've seen that.  I'll need more time to investigate (patch or remove 
it).

Is there a reason the other versions are not tested?

**Comment by Chris00** [comment]
The problem came from commit 92266de99fa31e74ee94e254bb3e157951c69668 which _removed_ `setup.ml`, thereby removing the specific code to configure the project as well.

**Comment by Chris00** [comment]
Only the MacOSX build is failing because it does not know the [-lgfortan](https://travis-ci.org/ocaml/opam-repository/jobs/154216354#L1943) library.  May someone with OSX tell me which library (if any) I should use?  @samoht ?  Just change [setup.ml](https://github.com/Chris00/L-BFGS-ocaml/blob/master/setup.ml#L71) to specify the lib (`""` means none).

**Comment by samoht** [comment]
I managed to compile the library successfully on my Mac (with `-lgfortran`). Looking at the various StackOverflow threads it seems that the problem could be caused by a wrong version of XCode. Not sure it is worth digging more. I'll merge the PR soon if I don't find any good/easy fix.

**Pull request merged**
