### PR TITLE
new package 'time'

### PR DESCRIPTION
**Pull request by mwweissmann**
implementing POSIX time and clock functions and/or bindings from time.h

### CODE REVIEW

**Comment by samoht** [comment]
This name is kind of very generic, so I'm afraid of namespace clashes. Do other maintainers have any opinion of merging this?

**Comment by samoht** [comment]
ping @yallop, @avsm, @dsheets and @whitequark

**Comment by whitequark** [comment]
This package does not work on Windows and OS X (see descr). I would prefer if this was renamed to `posix-time`, which also describes its nature much better.

**Comment by avsm** [comment]
Likewise, a more specific name, if the maintainer doesn't mind.

**Comment by mwweissmann** [comment]
You're probably right -- I'll think about a new name; probably [posix-realtime](http://www.unix.org/version2/whatsnew/realtime.html)

**Pull request closed without merging**
