### PR TITLE
Package fix.20230505

### PR DESCRIPTION
**Pull request by fpottier**
### `fix.20230505`
Algorithmic building blocks for memoization, recursion, and more

---
* Homepage: https://gitlab.inria.fr/fpottier/fix
* Source repo: git+https://gitlab.inria.fr/fpottier/fix.git
* Bug tracker: francois.pottier@inria.fr

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by fpottier** [comment]
Hello, why is a check still "pending" after 5 days?

**Comment by fpottier** [comment]
Hello?

**Comment by mseri** [comment]
The CI was busted by one PR, it recently restarted working but it will take some more time before all the PRs are re-tested. I hope in one or two days we will be able to review and merge this

**Comment by mseri** [comment]
The failures are due to the way old ocamlformat run tests on their man pages, so they don't affect the merge

**Comment by fpottier** [comment]
Thanks!

**Pull request merged**
