### PR TITLE
Package glicko2.1.0.0

### PR DESCRIPTION
**Pull request by bruce-ricard**
### `glicko2.1.0.0`

Implementation of the Glicko2 algorithm.

This library implements the Glicko2 algorithm. It is composed of 3 modules to be used independently, depending on your needs:

- A low level module which allows to rate multiple games within a rating period, the exact algorithm described in the paper.
- A single game convenience module which is easy to use and allows you to rate games one by one, as they are played, and get new ratings for the players involved.
- A functor which allows you to specify low level variables from the Glicko2 paper, and some other properties.

Wikipedia article: https://en.wikipedia.org/wiki/Glicko_rating_system
Glicko2 paper: http://www.glicko.net/glicko/glicko2.pdf

---
* Homepage: https://github.com/bruce-ricard/glicko2
* Source repo: git@github.com:bruce-ricard/glicko2.git
* Bug tracker: https://github.com/bruce-ricard/glicko2/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Your package seems to require a constraint to OCaml >= 4.02:
```
#=== ERROR while installing glicko2.1.0.0 =====================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/4.01.0/build/glicko2.1.0.0
# compiler     4.01.0
# exit-code    2
# env-file     /home/travis/.opam/4.01.0/build/glicko2.1.0.0/glicko2-17851-98d1f9.env
# stdout-file  /home/travis/.opam/4.01.0/build/glicko2.1.0.0/glicko2-17851-98d1f9.out
# stderr-file  /home/travis/.opam/4.01.0/build/glicko2.1.0.0/glicko2-17851-98d1f9.err
### stdout ###
# [...]
# /home/travis/.opam/4.01.0/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -package logs -package logs.fmt -package threads -thread -I src -o src/glicko2.cmx src/glicko2.ml
# /home/travis/.opam/4.01.0/bin/ocamlfind ocamlopt -a src/default_values.cmx src/glicko2_types.cmx src/glicko_internal.cmx src/internalLogs.cmx src/glicko2.cmx -o src/glicko2.cmxa
# /home/travis/.opam/4.01.0/bin/ocamlfind ocamlopt -shared src/glicko2.cmxa src/default_values.cmx src/glicko2_types.cmx src/glicko_internal.cmx src/internalLogs.cmx src/glicko2.cmx -o src/glicko2.cmxs
# /home/travis/.opam/4.01.0/bin/ocamlfind ocamldep -package logs -package logs.fmt -package threads -modules example/main.ml > example/main.ml.depends
# /home/travis/.opam/4.01.0/bin/ocamlfind ocamldep -package logs -package logs.fmt -package threads -modules example/functor.ml > example/functor.ml.depends
# /home/travis/.opam/4.01.0/bin/ocamlfind ocamldep -package logs -package logs.fmt -package threads -modules example/low_level.ml > example/low_level.ml.depends
# + /home/travis/.opam/4.01.0/bin/ocamlfind ocamldep -package logs -package logs.fmt -package threads -modules example/low_level.ml > example/low_level.ml.depends
# File "example/low_level.ml", line 41, characters 10-11:
# Error: Syntax error
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/home/travis/.opam/4.01.0/bin/ocamlbuild' src/glicko2.cma src/glicko2.cmxa src/glicko2.a src/glicko2.cmxs example/main.native -tag debug' terminated with error code 10")
# make: *** [build] Error 1
```

**Comment by bruce-ricard** [comment]
@kit-ty-kate indeed thank you. What is the recommended process here? Should I fix my build, delete this PR and rerun the `opam publish` command, or should I update this PR?

**Comment by bruce-ricard** [comment]
@kit-ty-kate fixed!

**Comment by kit-ty-kate** [comment]
All green. Thanks!

**Pull request merged**
