### PR TITLE
Frama c.30.0

### PR DESCRIPTION
**Pull request by vprevosto**
Packages for Frama-C 30.0 Zinc release and its associated plug-ins frama-clang and frama-c-metacsl

This PR also adds `x-maintenance-intent` fields for the three packages.

### CODE REVIEW

**Comment by mseri** [comment]
Thanks. All failures seem to be related to dependencies not building or too old LLVM. I'd say that it is good to merge. 

Can you double check if I missed something?

**Comment by vprevosto** [comment]
Thanks for your comment. I agree with you that most failures are indeed usual issues with getting a coherent set of packages for llvm and libclang installed through depext. Do you think it could be I worth it if I try to propose something in this area (in a separate PR, and this is not a strong commitment :sweat_smile: )? In particular, I'd say that the version detection algorithm should be unified (and probably `conf-libclang` should simply rely on `conf-llvm` to get its version number). I don't see how it would be possible to have a working configuration of `conf-llvm.x` and `conf-libclang.y` with `x!=y`.

Back to `frama-c*` packages, there's one failure that worries me a bit, namely [opam-2.0,ocaml-5.2](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/71ded5f52bc36f0bd95eab261effae1e7c4de5ee/variant/extras,opam-2.0-ocaml-5.2,frama-c.30.0) which apparently is caused by the absence of `autoconf`. `conf-autoconf` is only an indirect dependency of frama-c, but shouldn't have it been installed by  the `opam depext` step?

**Comment by mseri** [comment]
The conf-autoconf failure seem to happen only with the old opam 2.0, maybe it is due to some bug in a older opam-depext version. I would not worry about that since every distribution ships more recent opam versions

**Comment by mseri** [comment]
Let's merge this. It would indeed be nice if we can harmonize clang and llvm conf packages, but this can be done separately

**Pull request merged**
