### PR TITLE
5 packages from zoggy.frama.io/ocaml-stk/releases/ocaml-stk-0.2.0.tar.bz2

### PR DESCRIPTION
**Pull request by zoggy**
This pull-request concerns:
- `stk.0.2.0`: SDL-based GUI toolkit
- `stk_iconv.0.2.0`: Bindings to GNU libiconv
- `stk_ocf.0.2.0`: Utils to build GUI above Ocf
- `stk_ppx.0.2.0`: PPX used for debug logging in Stk
- `stk_rdf.0.2.0`: Utilities to display and edit RDF data

---
* Homepage: https://zoggy.frama.io/ocaml-stk/
* Source repo: git+https://framagit.org/zoggy/ocaml-stk.git
* Bug tracker: https://framagit.org/zoggy/ocaml-stk/issues

---
:camel: Pull-request generated by opam-publish v2.4.0

### CODE REVIEW

**Comment by zoggy** [comment]
The opam-ci reports errors and stops but these are warning about possible name conflicts with other packages, but there is no conflict actually.

**Comment by zoggy** [comment]
I need to add a constraint on stk_ppx.

**Comment by zoggy** [comment]
It seems ok to me.

**Comment by shonfeder** [comment]
I agree that the conflict collision detection aren't relevant. In fact, it is unhelpfully comparing with packages that are being published as part of the same source :) We can fix that.

Thanks for the updates!

In case you don't already have this planned, you may consider a fresh announcement on https://discuss.ocaml.org/  :)

**Comment by zoggy** [comment]
thanks ! I will publish an announce tomorrow.

**Pull request merged**
