### PR TITLE
2 packages from smimram/ocaml-dblp at 0.1.1

### PR DESCRIPTION
**Pull request by smimram**
This pull-request concerns:
- `dblp.0.1.1`: Commandline program do query the DBLP bibliographic database
- `dblp-api.0.1.1`: Library to query the DBLP bibliographic database

---
* Homepage: https://github.com/smimram/ocaml-dblp
* Source repo: git+https://github.com/smimram/ocaml-dblp.git
* Bug tracker: https://github.com/smimram/ocaml-dblp/issues

---
:camel: Pull-request generated by opam-publish v2.4.0

### CODE REVIEW

**Comment by shonfeder** [comment]
The name collision lint fail is a false positive. (And should be disabled or made more lax, as per https://github.com/ocurrent/opam-repo-ci/issues/378)

**Comment by shonfeder** [comment]
Everything looks great here (modulo solver timeouts, which are an issue with opam/the CI, not your package)!

Thanks very much for the fixes and, again, for sharing this useful work!

**Comment by shonfeder** [comment]
Please consider announcing the package on https://discuss.ocaml.org/c/community !

**Comment by smimram** [comment]
Thanks for your help! The announce is here: https://discuss.ocaml.org/t/ann-dblp-query-program-and-library/15385

**Comment by shonfeder** [comment]
Thanks!

**Pull request merged**
