### PR TITLE
[new release] randoml (0.1.1)

### PR DESCRIPTION
**Pull request by mimoo**
Generating cryptographically-secure random numbers

- Project page: <a href="https://github.com/mimoo/randoml">https://github.com/mimoo/randoml</a>

##### CHANGES:

Fix opam installation (by vendoring rust dependencies) for release

### CODE REVIEW

**Comment by avsm** [comment]
Failing CI due to cargo breaking the sandbox

```
Processing  1/2: [randoml: dune build]
+ /home/opam/.opam/opam-init/hooks/sandbox.sh "build" "dune" "build" "-p" "randoml" "-j" "47" "@install" (CWD=/home/opam/.opam/4.12/.opam-switch/build/randoml.0.1.1)
-        cargo lib/rand/dllrand.so,lib/rand/librand.a (exit 101)
- (cd _build/default/lib/rand && /usr/bin/cargo build --release)
- error: failed to load source for a dependency on `ocaml`
- 
- Caused by:
-   Unable to update registry `https://github.com/rust-lang/crates.io-index`
- 
- Caused by:
-   failed to create directory `/home/opam/.cargo/registry/index/github.com-1ecc6299db9ec823`
- 
- Caused by:
-   Read-only file system (os error 30)
```

Would it be possible for the release archive to include the cargo packages as vendored directories?

**Comment by mseri** [comment]
They are already vendored, I think it is only missing some extra configuration in `.cargo/config`. In the tezos package that I linked in the other PR they have something like
```
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
```

**Comment by mimoo** [comment]
sorry I saw that and was a bit slow to fix! Indeed this is the fix :) I'll create a new PR that should work, thanks for the help!

**Comment by mimoo** [comment]
https://github.com/ocaml/opam-repository/pull/19049 here it is

**Pull request closed without merging**
