### PR TITLE
added packages/lbvs_consent/lbvs_consent.2.0.0

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Nothing is expected. Travis CI results are always full of surprises. :)
Some of the Linux tests have the same error.
I don't understand: there is a src directory in there https://github.com/UnixJunkie/consent
So, after unpacking the tarball, it should still be there?!
I will do some more tests on my side.

**Comment by kit-ty-kate** [comment]
oh.

well the error was very easy in fact. You didn't specified the url of your archive ^^

**Comment by mseri** [comment]
@UnixJunkie `url` and `description` (and/or `synopsis`) are missing from the opam file

**Comment by UnixJunkie** [comment]
My bad, I added the missing section.
I was not yet used to this new format, everything in one file, but it's neat.

**Comment by UnixJunkie** [comment]
It looks like some CI tests have stalled, or some other strange errors like camlp4 failed to compile?!

**Comment by kit-ty-kate** [comment]
Seems ok. Thanks a lot!

**Pull request merged**
