### PR TITLE
index: Add missing constraints

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Detected in https://github.com/ocaml/opam-repository/pull/18761

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @CraigFe

**Comment by CraigFe** [comment]
Thanks @kit-ty-kate. Upstreamed here: https://github.com/mirage/index/pull/327

**Comment by kit-ty-kate** [comment]
@CraigFe Wait a little bit before merging it, there might be other ones to add ^^ (`fmt >= 0.8.5` for instance)

**Comment by kit-ty-kate** [comment]
Ok it looks good now!

**Pull request merged**
