### PR TITLE
Package archetype.0.1.3

### PR DESCRIPTION
**Pull request by guillaumeduhamel**
### `archetype.0.1.3`
Archetype language compiler
Archetype is a domain-specific language (DSL) to develop smart contracts on the Tezos blockchain,
with a specific focus on contract security

---
* Homepage: https://github.com/edukera/archetype-lang
* Source repo: git+https://github.com/edukera/archetype-lang.git
* Bug tracker: https://github.com/edukera/archetype-lang/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by guillaumeduhamel** [comment]
It seems to work!
Our CI script checks more versions now
I remove as far as possible constraints on dependencies version.

I think digestif 0.7.4 is not compatible with OCaml 4.08.1
so I downgrade it and forced to use 0.7.3.

Fell free to tell me if something goes wrong

**Comment by kit-ty-kate** [comment]
> I think digestif 0.7.4 is not compatible with OCaml 4.08.1
> so I downgrade it and forced to use 0.7.3.

Are you sure? It seems to compile on 4.08 and 4.09:
* http://check.ocamllabs.io/log/1568558996-3394ff39238589fe9271e2531f6ae13e5f7aa2f6/4.08/good/digestif.0.7.4
http://check.ocamllabs.io/log/1568558996-3394ff39238589fe9271e2531f6ae13e5f7aa2f6/4.09/good/digestif.0.7.4

**Comment by kit-ty-kate** [comment]
cc @dinosaure

**Comment by dinosaure** [comment]
digestif.0.7.4 is a (special) compatibility version for Mirage 3 (without dune variants), to fix it, you have two solution:
* add a conflict with this special version
* handle both and explicitly depend on digestif.c or digestif.ocaml on your dune file

**Comment by guillaumeduhamel** [comment]
Thank you for your answer,
I add a conflict with this version.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
