### PR TITLE
8 packages from ocaml/opam at 2.0.1

### PR DESCRIPTION
**Pull request by rjbou**
This pull-request concerns:
-`opam-client.2.0.1`
-`opam-core.2.0.1`
-`opam-devel.2.0.1`
-`opam-format.2.0.1`
-`opam-installer.2.0.1`
-`opam-repository.2.0.1`
-`opam-solver.2.0.1`
-`opam-state.2.0.1`

---
* Source repo: git+https://github.com/ocaml/opam.git
* Bug tracker: https://github.com/ocaml/opam/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by mseri** [comment]
Are the many tests failure expected?

```
- /usr/bin/make --no-print-directory REPOKIND=local run
-   00 init                 ..................................... [ OK ]
-   01 upload               ..................................... [FAIL]
-   02 install-remove       ..................................... [FAIL]
-   03 list                 ..................................... [ OK ]
-   04 install-opt          ..................................... [FAIL]
-   05 list                 ..................................... [ OK ]
-   06 install              ..................................... [FAIL]
-   07 list                 ..................................... [ OK ]
-   08 reinstall            ..................................... [FAIL]
-   09 list                 ..................................... [ OK ]
-   10 upload-new           ..................................... [ OK ]
-   11 list                 ..................................... [ OK ]
-   12 upgrade              ..................................... [FAIL]
-   13 list                 ..................................... [ OK ]
-   14 downgrade            ..................................... [FAIL]
-   15 list                 ..................................... [ OK ]
-   16 switch-alias         ..................................... [FAIL]
-   17 list                 ..................................... [ OK ]
-   18 switch-env-packages  ..................................... [FAIL]
-   19 repo                 ..................................... [FAIL]
-   20 list                 ..................................... [ OK ]
- FAILED! Logs in /home/travis/.opam/4.05.0/.opam-switch/build/opam-devel.2.0.1/_build/default/tests/failed-local.log
- make[2]: *** [run] Error 1
- make[1]: *** [local] Error 2
- make[1]: Leaving directory `/home/travis/.opam/4.05.0/.opam-switch/build/opam-devel.2.0.1/_build/default/tests'
-         make alias tests/runtest (exit 2)
```

**Comment by rjbou** [comment]
> Are the many tests failure expected?

Kind of, when I pushed, I didn't know from where the error comes. Now, yes: `ocaml-ci-scripts` don't install a system ocaml if it's used with opam2, while opam internal tests can't be successful if there is no system ocaml. cf https://github.com/ocaml/ocaml-ci-scripts/issues/253.

Anyway, for the moment, *not* to merge yet.

**Comment by rjbou** [comment]
Go to merge for me!

For the error problem, proposed a PR https://github.com/ocaml/ocaml-ci-scripts/pull/256 to fix system ocaml install.

**Comment by mseri** [comment]
Ok, thanks!

**Comment by mseri** [comment]
@rjbou are you going to announce the release on the discourse forum?

**Comment by rjbou** [comment]
Yes, once available in opam.ocaml.org (next build)

**Pull request merged**
