### PR TITLE
+wamp.1.0

### PR DESCRIPTION
**Pull request by vbmithr**

### CODE REVIEW

**Comment by dsheets** [comment]
It looks like you're missing a dependency on `yojson` which may be transitively installed in some configurations but fails on 4.02 and OS X.

**Comment by vbmithr** [comment]
@dbuenzli Any idea why this fails? As far as I understand yojson and msgpck are optional dependencies of this library, and they should not be required.

**Comment by samoht** [comment]
@vbmithr you need to pass the right `--with-X` arguments to the `topkg` invocation. See for instance https://github.com/ocaml/opam-repository/blob/master/packages/irmin-watcher/irmin-watcher.0.1.4/opam#L21-L24

**Comment by dbuenzli** [comment]
See also the [documentation](http://erratique.ch/software/topkg/doc/Topkg.html#installcond) about conditional installs.

**Comment by vbmithr** [comment]
Ok thanks :)

**Pull request merged**
