### PR TITLE
Package ppx_nanocaml.0.1

### PR DESCRIPTION
**Pull request by OhadRau**
### `ppx_nanocaml.0.1`

Framework for writing nanopass-style compilers

A PPX-based toolkit that eases compiler writing
by automatically generating the code needed to
write a compiler. Nanocaml is designed for the
nanopass-style of writing compilers, which
emphasizes the use of many small passes that
only perform one change to the AST, rather than
only a few large passes.

---
* Homepage: https://github.com/nanocaml/nanocaml
* Source repo: git+https://github.com/nanocaml/nanocaml.git
* Bug tracker: https://github.com/nanocaml/nanocaml/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by OhadRau** [comment]
Any explanation for the errors? Is the `ocaml-version` error because of no `available` field in the OPAM file? Not really sure how to proceed here...

**Comment by yomimono** [comment]
I think the `ocaml-version` error in the Travis test for OCaml 4.06.0 is a particularly weird manifestation of a network failure.  I've restarted the test and it appears to be chugging along as expected, beyond the point at which it previously failed.

**Comment by yomimono** [comment]
If you need `jbuilder` only for building `nanopass`, can you please mark the dependency with `{build}`?  Then upgrading `jbuilder` won't cause `opam` to rebuild `nanopass`.

**Comment by OhadRau** [comment]
@yomimono Cool. Not sure if I did something wrong, I added `{ build }` after jbuilder...

**Comment by yomimono** [comment]
Looks great to me, I'll merge this. :)

You might want to consider announcing this on the [discuss.ocaml.org](https://discuss.ocaml.org) forum, too!

**Comment by OhadRau** [comment]
Thanks! I'll go ahead and post it in a little bit!

**Pull request merged**
