### PR TITLE
Relax constraints on JaneStreet packages (v0.13)

### PR DESCRIPTION
**Pull request by kit-ty-kate**
cc @xclerc

### CODE REVIEW

**Comment by xclerc** [comment]
Thanks a lot!

**Comment by kit-ty-kate** [comment]
I reran a check and all the failures are unrelated. Good to go.

**Comment by kit-ty-kate** [comment]
Oops I forgot to ping the maintainers affected, sorry:
* cc @briancaine for `amf`
* cc @edwintorok for `anycache-async`
* cc @pveber for `bistro`
* cc @nosman for `bson2` and `ocamlapi`
* cc @paurkedal for `caqti-async`
* cc @agarwal for `cfstream`
* cc @olgu for `gnuplot`
* cc @arenadotio for `mssql` and `pgx`
* cc @jnfoster for `petr4`
* cc @na4zagin3 for `satyrographos`
* cc @kandu for `tidy`
* cc @RosalesJ for `tldr`

Reasons for breakage are stated in the commit messages.

**Comment by xclerc** [comment]
@agarwal @arenadotio @jnfoster @na4zagin3 @nosman @olgu @paurkedal
I have tentative patches for `bson2`, `caqti-async`, `cfstream`, `gnuplot`, `petr4`,
`pgx`, and `satyrographos`.

**Pull request merged**
