### PR TITLE
Package baguette_base.2.0.2

### PR DESCRIPTION
**Pull request by coco33920**
### `baguette_base.2.0.2`
The Baguette# Base
Create the basis for the language. The Tokens are defined here, the Tokenizers (also called lexers) are 
 both implemented here too. Finally the parser is also in this package. Used in baguette_functions, baguette_sharp, and baguette-sharp

---
* Homepage: https://baguettesharp.fr
* Source repo: git+https://github.com/coco33920/ocaml-baguettesharp-interpreter.git
* Bug tracker: https://github.com/coco33920/ocaml-baguettesharp-interpreter/issues

---
Sorry for the doubly quadruple PR - i'm new to publishing on OPAM
Baguette# is an exotic programming language based on french pastries
Baguette_base contains the Lexer/Parser
Baguette_functions contains the Conditions/Math/Array/String modules and manipulation of the language (the Baguette# Standard Library) 
and the function modules who's job is to match function from their pastry name to real name
Baguette_sharp is the interpreter while
Baguette-sharp is the executable file for the REPL

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I’ve fixed a couple of mistakes in the opam file, however It will not work as is I’m guessing. I’m not seeing the `baguette_base` package anywhere in the source repository. Is that meant to be publicly available? I’m only seeing`baguette-sharp` as public package.

**Comment by coco33920** [comment]
Yup I think I should rework the work tree a bit currently it's like this

- src/
  - base/
    -  parser.ml
    -  lexer.ml
    -  dune
    -  dune-package
  - functions/
    - [ml files]
    - dune
    - dune-package
  - main/
    - baguette_sharp_interpreter.ml
    - dune 
  - dune-project
  - dune
  - interpreter.ml
- dune-project

What i wanted to do is this : 
- The executable is on src/main and the root dune-project is to build it, to be public (the executable is baguette-sharp)
- Publishing the library baguette_sharp (the interpreter the src/dune-project) however for it to be public i think I needed the dependencies src/base (baguette_base) and src/functions (baguette_functions).

I'm sorry i'm _very_ new to publish thing and using dune altogether (and i'm quite new with OCaml tbh). Based on your answer I infer a better solution exist though.

Thanks you,
Charlotte

**Comment by coco33920** [comment]
I found a _much_ better way, i should have read better the stanza reference. I'm sorry for these errors.

**Comment by coco33920** [comment]
I'm reopening this because I may have closed it a bit too early;
I changed the file tree like this
- src/
  - base/
    - parser.ml
    - lexer.ml
    - token.ml
  - functions/
    - [ml files]
  - main/
    - baguette_sharp_interpreter
    - dune
  - dune
  - dune-project
  - baguette_sharp.opam
- dune-project
- baguette-sharp.opam

The root opam/dune-project file is for baguette-sharp which is defined in src/main
The other have the stanza `(include_subdirs unqualified)` 
The root baguette-sharp.opam stills depends on baguette_sharp.opam though I let that just because I think it's wiser to separate the Language itself (which in the future may be useful to expand it?) rather than the REPL file, but what are your thought about that?

I pushed this new tree on the [dune-tree](https://github.com/coco33920/ocaml-baguettesharp-interpreter/tree/dune-tree) branch.
Thanks you for your help,
Charlotte.

**Pull request closed without merging**
