### PR TITLE
Package apero-core.0.3.0

### PR DESCRIPTION
**Pull request by kydos**
### `apero-core.0.3.0`

---
* Homepage: https://github.com/atolab
* Source repo: git://github.com/atolab/apero-core.git
* Bug tracker: https://github.com/atolab/apero-core/issues/

---
:camel: Pull-request generated by opam-publish v2.0.0~beta

### CODE REVIEW

**Comment by mseri** [comment]
Looks like it is missing a dependency on `yojson`:
```
[ERROR] The compilation of apero-core failed at "/home/opam/.opam/4.07/bin/jbuilder build --only apero-core --root . -j 127 @install".
- File "lib/dune", line 5, characters 71-77:
- Error: Library "yojson" not found.
- Hint: try: dune external-lib-deps --missing --root . --only-packages apero-core @install
```

**Comment by kit-ty-kate** [comment]
Could you also use a more standard `jbuilder build` call? (see other libraries in the opam-repository using jbuilder/dune) And also annotate the dependency to `dune` with `{build}` ?

**Comment by kit-ty-kate** [comment]
ping @kydos

**Comment by kydos** [comment]
@kit-ty-kate, will resolve the pending issues early this week. Thanks for the ping :-)

**Comment by UnixJunkie** [comment]
It would be nice to have a high level description of what apero-core is.

PS: Ca me donne envie d'aller boire l'apero, d'ailleurs. :)

**Comment by kit-ty-kate** [comment]
I'm closing this. Please feel free to reopen it once it's fixed

**Pull request closed without merging**
