### PR TITLE
frama-c: fix for OCaml 4.03

### PR DESCRIPTION
**Pull request by maroneze**
Fix compilation issues with Frama-C Magnesium when using OCaml >= 4.03

### CODE REVIEW

**Comment by dsheets** [comment]
Has this patch been sent upstream?

**Comment by maroneze** [comment]
Frama-C does not have a public development repository; what should be put in "dev-repo" in that case?

That patch has already been applied to the current development version of Frama-C, and is thus only necessary for the 20151002 version in opam.

**Comment by dsheets** [comment]
`dev-repo` should either be left blank or be the official (or unofficial) public source mirror. It's good to hear that the fix is already included in the source.

**Comment by maroneze** [comment]
If I try `opam lint` on the modified `opam` file with an empty dev-repo (i.e. `dev-repo: ""`), I get:

    Errors found in ~/git/opam-repository/packages/frama-c-base/frama-c-base.20151002/opam:
        error  2: File format error: at ~/git/opam-repository/packages/frama-c-base/frama-c-base.20151002/opam:31:11, Bad url format ""

There is currently a "snapshot" repository of Frama-C, but it contains only a mirror of the official .tar.gz releases, without actual git commit history (so it's not actually a "development" repository). Would that be considered fine as a "dev-repo" URL, or would it be better to leave it empty in that case?

**Comment by dsheets** [comment]
Sorry, I wasn't clear earlier. Either `dev-repo` should not be set or it should be set to the "best" version-controlled upstream for the package source. `dev-repo` is meant to support the `opam pin --dev-repo` functionality which lets users pin the package against the "trunk" or "HEAD" version of the package development. It's also fine to include a commented-out `dev-repo` field with content explaining that the development of the package is closed.

**Comment by maroneze** [comment]
Ok, thanks for the clarification, we'll test if the snapshot repository would work fine as dev-repo, and if so, add it to the next release of Frama-C.

**Comment by dbuenzli** [comment]
> There is currently a "snapshot" repository of Frama-C, but it contains only a mirror of the official .tar.gz releases, without actual git commit history (so it's not actually a "development" repository). Would that be considered fine as a "dev-repo" URL, or would it be better to leave it empty in that case?

It seems fine. I think you should do this, it allows you to push hot-fixes before actually making a release and ask your users to test them via a simple `opam pin frama-c --dev-repo`

**Pull request merged**
