### PR TITLE
Add ocamldap 2.3.0

### PR DESCRIPTION
**Pull request by jpdeplaix**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Seems like depext doesn't work very well with OpenSUSE. Here is a fix: https://github.com/ocaml/opam-depext/pull/67

**Comment by dbuenzli** [comment]
Unless @avsm wants to check with the new depext release this is good to go.

**Comment by jpdeplaix** [comment]
I just rebased my branch against master so that the new depext can be tested.

**Comment by jpdeplaix** [comment]
Ok there is still something broken elsewhere. ```--non-interactive``` seems to require to be set directly after the command and not after the subcommand (```install``` in this case)

**Comment by jpdeplaix** [comment]
Does somebody can you reopen this ?

**Comment by avsm** [comment]
There's no need to block this on opensuse -- will fix that asynchronously. Thanks for the contribution! You may also want to post it on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
