### PR TITLE
[new release] xdg, stdune, ordering, ocamlc-loc, fiber, dyn, dune, dune-site, dune-rpc, dune-rpc-lwt, dune-private-libs, dune-glob, dune-configurator, dune-build-info, dune-action-plugin and chrome-trace (3.4.1)

### PR DESCRIPTION
**Pull request by emillon**
XDG Base Directory Specification

- Project page: <a href="https://github.com/ocaml/dune">https://github.com/ocaml/dune</a>
- Documentation: <a href="https://dune.readthedocs.io/">https://dune.readthedocs.io/</a>

##### CHANGES:

- Fix build on cygwin/i686-w64-mingw32 (ocaml/dune#6008, @kit-ty-kate)

### CODE REVIEW

**Comment by emillon** [comment]
I added a conflict with alpha0 since it's still available. What is the right way to make 3.4.0 uninstallable on cygwin/i686-w64-mingw32?

**Comment by kit-ty-kate** [comment]
Adding
```
available: !(os = "win32" & arch = "x86_32")
```
would do the job. Even if it’s a slight approximation, in practice i don’t think it really matters given the current support of windows in opam.

**Comment by kit-ty-kate** [comment]
oh nevermind:
```
available: !(os = "cygwin" & arch = "x86_32")
```
actually works apparently

**Comment by emillon** [comment]
Allright, I'll let CI do its job and add this.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
