### PR TITLE
vchan 2.0.2 works with lwt 2.5.0

### PR DESCRIPTION
**Pull request by rgrinberg**
@vbmithr did you add this constraint by mistake? It's working fine for me.

### CODE REVIEW

**Comment by dsheets** [comment]
So is the constraint necessary?

**Comment by rgrinberg** [comment]
It's not. I think I closed this PR accidentally.

**Comment by vbmithr** [comment]
I don't see why it would work. Lots of functions in vchan use the ~buffer_size argument that does not exist anymore. According to this, I would say there is no way it can work.

**Comment by vbmithr** [comment]
So, anyway, if you manage to compile this without Lwt 2.5.0, please explain me what happens about the codes that contains the ~buffer_size argument in it :)

**Comment by rgrinberg** [comment]
@vbmithr hmm you're right. Must be something wrong with my system because it compiles :O

**Pull request closed without merging**
