### PR TITLE
cairo2 - add missing upper&lower bounds for ocaml

### PR DESCRIPTION
**Pull request by haochenx**

### CODE REVIEW

**Comment by raphael-proust** [comment]
AFAICT the CI errors are unrelated to this PR.

**Comment by mseri** [comment]
The failures with ocaml 5 are of the form:
```
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -w -58 -alert -deprecated -g -o src/scripting/doc.exe /home/opam/.opam/5.0/lib/ocaml/unix/unix.cmxa /home/opam/.opam/5.0/lib/ocaml/str/str.cmxa /home/opam/.opam/5.0/lib/logs/logs.cmxa /home/opam/.opam/5.0/lib/readline/readline.cmxa -I /home/opam/.opam/5.0/lib/readline /home/opam/.opam/5.0/lib/menhirLib/menhirLib.cmxa /home/opam/.opam/5.0/lib/ANSITerminal/ANSITerminal.cmxa -I /home/opam/.opam/5.0/lib/ANSITerminal /home/opam/.opam/5.0/lib/fmt/fmt.cmxa /home/opam/.opam/5.0/lib/logs/logs_fmt.cmxa /home/opam/.opam/5.0/lib/fmt/fmt_tty.cmxa /home/opam/.opam/5.0/lib/mtime/mtime.cmxa /home/opam/.opam/5.0/lib/mtime/clock/os/mtime_clock.cmxa -I /home/opam/.opam/5.0/lib/mtime/clock/os /home/opam/.opam/5.0/lib/easy-format/easy_format.cmxa /home/opam/.opam/5.0/lib/camlp-streams/camlp_streams.cmxa /home/opam/.opam/5.0/lib/biniou/biniou.cmxa /home/opam/.opam/5.0/lib/yojson/yojson.cmxa /home/opam/.opam/5.0/lib/gen/gen.cmxa /home/opam/.opam/5.0/lib/sedlex/sedlex.cmxa src/utils/utilsLib.cmxa src/logic/logic.cmxa src/datalog.prover/datalogLib.cmxa /home/opam/.opam/5.0/lib/stdlib-shims/stdlib_shims.cmxa /home/opam/.opam/5.0/lib/ocamlgraph/graph.cmxa src/magicRewriting/magicRewriting.cmxa src/acg-data/acgData.cmxa src/grammars/grammars.cmxa /home/opam/.opam/5.0/lib/cairo2/cairo.cmxa -I /home/opam/.opam/5.0/lib/cairo2 src/graph/svg_rendering.cmxa src/utils/dump.cmxa src/scripting/scripting.cmxa src/scripting/.doc.eobjs/native/dune__exe__Doc.cmx)
# /usr/bin/ld: /home/opam/.opam/5.0/lib/cairo2/libcairo_stubs.a(cairo_stubs.o): in function `caml_cairo_create':
# /home/opam/.opam/5.0/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_stubs.c:53: undefined reference to `alloc_custom'
```

**Comment by mseri** [comment]
I think this can be merged, since it is a strict improvement over the past.
However we should probably investigate if we can understand what is conflicting between cairo2 and lablgtk3, and if we can solve it in some way:
```
# /usr/bin/ld: /home/opam/.opam/4.14/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/opam/.opam/4.14/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_ocaml.h:53: multiple definition of `caml_cairo_font_type'; /home/opam/.opam/4.14/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o):/home/opam/.opam/4.14/lib/cairo2/cairo_ocaml.h:53: first defined here
# /usr/bin/ld: /home/opam/.opam/4.14/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/opam/.opam/4.14/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_ocaml.h:28: multiple definition of `caml_cairo_ops'; /home/opam/.opam/4.14/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o):/home/opam/.opam/4.14/lib/cairo2/cairo_ocaml.h:28: first defined here
# /usr/bin/ld: /home/opam/.opam/4.14/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/opam/.opam/4.14/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_ocaml.h:70: multiple definition of `caml_surface_ops'; /home/opam/.opam/4.14/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o):/home/opam/.opam/4.14/lib/cairo2/cairo_ocaml.h:70: first defined here
# /usr/bin/ld: /home/opam/.opam/4.14/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/opam/.opam/4.14/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_ocaml.h:36: multiple definition of `caml_pattern_ops'; /home/opam/.opam/4.14/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o):/home/opam/.opam/4.14/lib/cairo2/cairo_ocaml.h:36: first defined here
# /usr/bin/ld: /home/opam/.opam/4.14/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/opam/.opam/4.14/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_ocaml.h:96: multiple definition of `caml_path_ops'; /home/opam/.opam/4.14/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o):/home/opam/.opam/4.14/lib/cairo2/cairo_ocaml.h:96: first defined here
# /usr/bin/ld: /home/opam/.opam/4.14/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/opam/.opam/4.14/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_ocaml.h:48: multiple definition of `caml_font_options_ops'; /home/opam/.opam/4.14/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o):/home/opam/.opam/4.14/lib/cairo2/cairo_ocaml.h:48: first defined here
# /usr/bin/ld: /home/opam/.opam/4.14/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/opam/.opam/4.14/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_ocaml.h:64: multiple definition of `caml_scaled_font_ops'; /home/opam/.opam/4.14/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o):/home/opam/.opam/4.14/lib/cairo2/cairo_ocaml.h:64: first defined here
# /usr/bin/ld: /home/opam/.opam/4.14/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/opam/.opam/4.14/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_ocaml.h:154: multiple definition of `caml_cairo_ft_library_ops'; /home/opam/.opam/4.14/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o):/home/opam/.opam/4.14/lib/cairo2/cairo_ocaml.h:154: first defined here
# /usr/bin/ld: /home/opam/.opam/4.14/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/opam/.opam/4.14/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_ocaml.h:157: multiple definition of `caml_cairo_ft_face_ops'; /home/opam/.opam/4.14/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o):/home/opam/.opam/4.14/lib/cairo2/cairo_ocaml.h:157: first defined here
# collect2: error: ld returned 1 exit status
# File "caml_startup", line 1:
# Error: Error during linking (exit code 1)
```

**Comment by haochenx** [comment]
Thanks!

> For these kinds of fixes, we try to include the error message we observed inside the description of the PR. 

Noted. Will do so in the future.

**Comment by haochenx** [comment]
>However we should probably investigate if we can understand what is conflicting between cairo2 and lablgtk3, and if we can solve it in some way:

I tried to spend about 5min in investigating, but it was evident finding a solution would take way more time so I stopped there. If it's a priority I can spend some more time on it. It seemed to me not a high-priority problem since it involved previous versions (if I'm understanding it correctly).

**Comment by mseri** [comment]
Definitely not a priority. Sometimes with these issues we keep stumbling on them until for random reasons we can finally figure them out and fix them

**Pull request merged**
