### PR TITLE
[new release] zeit (v0.1.0)

### PR DESCRIPTION
**Pull request by emillon**
Client for the Zeit API and now.sh

- Project page: <a href="https://github.com/emillon/ocaml-zeit">https://github.com/emillon/ocaml-zeit</a>
- Documentation: <a href="https://emillon.github.io/ocaml-zeit/doc">https://emillon.github.io/ocaml-zeit/doc</a>

##### CHANGES:

Initial release.

### CODE REVIEW

**Comment by mseri** [comment]
The master branch has moved to `opam2`, please update the `opam` files. You can use the new `opam-publish 2.0.0` or just upgrade the files using `opam-package-upgrade`

**Comment by emillon** [comment]
:heavy_check_mark: done!

**Comment by mseri** [comment]
Thanks. The `url` file also needs an update, the checksum syntax has changed slightly. And now the `url` and `descr` files can also all be merged in the opam file, but I don't think we are strict about that

**Comment by mseri** [comment]
I don't know... when I made the PR for cohttp, it was all automatic. I think you just need to replace what you have with
```
src: "https://github.com/emillon/ocaml-zeit/releases/download/v0.1.0/zeit-0.1.0.tbz"
checksum: [ "md5=5da8524b892f5e37c296766e81f7d418" ]
```

**Comment by emillon** [comment]
Sure, let's try that!

**Comment by mseri** [comment]
It fails to run the tests on ocaml 4.03. Do you know why?

```
#=== ERROR while compiling zeit.0.1.0 =========================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.03.0 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/4.03.0/.opam-switch/build/zeit.0.1.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p zeit -j 1
# exit-code   1
# env-file    ~/.opam/log/zeit-28794-a3393d.env
# output-file ~/.opam/log/zeit-28794-a3393d.out
### output ###
# Attribute `deriving' was not used
# [...]
# (cd _build/default && .ppx/ppx_deriving.std+ppx_deriving_yojson+ppx_let/ppx.exe --cookie 'library-name="zeit"' -o lib/deployment.pp.mli --intf lib/deployment.mli --dump-ast)
# File "lib/deployment.mli", line 11, characters 3-11:
# Attribute `deriving' was not used
#          ppx lib/error.pp.mli (exit 1)
# (cd _build/default && .ppx/ppx_deriving.std+ppx_deriving_yojson+ppx_let/ppx.exe --cookie 'library-name="zeit"' -o lib/error.pp.mli --intf lib/error.mli --dump-ast)
# File "lib/error.mli", line 5, characters 3-11:
# Attribute `deriving' was not used
#          ppx lib/scale.pp.mli (exit 1)
# (cd _build/default && .ppx/ppx_deriving.std+ppx_deriving_yojson+ppx_let/ppx.exe --cookie 'library-name="zeit"' -o lib/scale.pp.mli --intf lib/scale.mli --dump-ast)
# File "lib/scale.mli", line 5, characters 3-11:
# Attribute `deriving' was not used
```

**Comment by mseri** [comment]
Everything else is fine

**Comment by emillon** [comment]
It's picking an old version of `ppx_driver` & related packages. I've seen this before, it's an incompatibility between ppx_deriving, ppx_driver and maybe another package. I don't think this matters too much, this can be solved at the application level. Or I can add a constraint so that it's only available on >= 4.04.0 if you'd prefer.

**Comment by mseri** [comment]
It’s ok, let’s merge and try to figure out how to fix that incompatibility in general once and for all

**Pull request merged**
