### PR TITLE
omake 0.10.1 release

### PR DESCRIPTION
**Pull request by rgrinberg**
All the patches applied to the previous version are no longer valid.
Should be reported as issues to the upstream repo if you have any
questions about the patches.

### CODE REVIEW

**Comment by fdopen** [comment]
`omake.install` is dubious. `omake.opt` doesn't necessarily exist (eg. byte code only switches).

**Comment by rgrinberg** [comment]
How can I test building omake without the native compiler available? I'd like to
test that situation to see if/where the bytecode binary is generated.

**Comment by fdopen** [comment]
You can try the `4.02.3+bytecode-only` switch.

**Comment by rgrinberg** [comment]
Looks like omake 0.10.1 doesn't yet support bootstrapping on bytecode only
systems.

https://github.com/ocaml-omake/omake/issues/55

cc'ing @gerdstolpmann just in case. It probably isn't worth it to block the
release for the majority of users that have ocamlopt

**Comment by rgrinberg** [comment]
How do I restrict the package to be native only? This version of omake doesn't work on bytecode only systems.

**Comment by AltGr** [comment]
aaah, my migration script to 2.0 is going to choke on this :(
(it's completely valid according to 1.2 rules though)

**Comment by rgrinberg** [comment]
@AltGr @andersfugmann OK this is ready. You can squash when merging if you want.

**Comment by avsm** [comment]
@Altgr should I merge this then, or wait for the 2.0 to be fixed?

**Comment by avsm** [comment]
@altgr: ping

**Comment by rgrinberg** [comment]
@AltGr ping

**Comment by samoht** [comment]
@AltGr ping

**Comment by avsm** [comment]
Risking breaking 2.0; this is too long to block a package merge

**Pull request merged**
