### PR TITLE
[new release] textmate-language (0.1.0)

### PR DESCRIPTION
**Pull request by dosaylazy**
Parsing source code with TextMate grammars

- Project page: <a href="https://github.com/dosaylazy/ocaml-textmate-language">https://github.com/dosaylazy/ocaml-textmate-language</a>
- Documentation: <a href="https://dosaylazy.github.io/ocaml-textmate-language/">https://dosaylazy.github.io/ocaml-textmate-language/</a>

##### CHANGES:

Initial release.

### CODE REVIEW

**Comment by dosaylazy** [comment]
Oops, it looks like the build failed for some earlier versions of OCaml because I used the Int module. Should I add the OCaml version to the package constraints, or use the functions (`string_of_int` and `int_of_string_opt`) in Stdlib instead?

**Comment by mseri** [comment]
You could also use stdlib-shims if you want to support older versions. Any of the solutions will be fine, pick your favorite. I think the easiest is to have a lower hound on ocaml in this release and fix it for the next, But it is your call.

**Comment by dosaylazy** [comment]
I just checked stdlib-shims: https://github.com/ocaml/stdlib-shims According to its README, it handles the switch from Pervasives to Stdlib, but doesn't accommodate the new modules.

I checked my code, and I also use the Int module as an argument to Map.Make. I don't feel like rewriting my code to accommodate earlier versions of OCaml, so I think I will add a version constraint.

**Comment by mseri** [comment]
Thanks. Feel free to announce this on the discuss.ocaml.org forum. We have a community category and an announcement tag for this purpose

**Pull request merged**
