### PR TITLE
jsoo 3.2.0

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
still in progress. I've updated the archive. Let's see what tests say.

**Comment by hhugo** [comment]
- hardcaml, stog, vg, ocplib-json-typed are just related to 4.06
- eliom 6.3.0 : I don't understand, I see lines where it succeed and lines where does not.
  @avsm, @kit-ty-kate, can you help me understand what's going on here ?

**Comment by hhugo** [comment]
was probably just a missing opt-dep

**Comment by hhugo** [comment]
Updated again. I expect the test to be good (but hardcaml, stog, vg, ocplib-json-typed as mention above).
Ready to be merge after tests run

**Comment by kit-ty-kate** [comment]
All good. Thanks!

**Pull request merged**
