### PR TITLE
added packages/orsvm_e1071/orsvm_e1071.3.0.1

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
If I recall correctly this package should at least build on the macos CI but it doesn't this time. Is there anything wrong or should I just go ahead and merge it?

**Comment by UnixJunkie** [comment]
Yes you are right, it used to work at least in Travis for the Mac.
I wonder if the sandboxing thing broke the install on Mac.
The R scripts are supposed to install R libraries the package relies on.
I will test more on a Mac and on Linux.

**Comment by UnixJunkie** [comment]
I simplified the package.
It should compile everywhere now.
Note that the user needs to interact with R so that he will be able to use the library (R needs to install two libraries).

**Comment by kit-ty-kate** [comment]
The `dolog` library doesn't seem to be a test dependency:
```
#=== ERROR while compiling orsvm_e1071.3.0.1 ==================================#
# context              2.0.1 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/UnixJunkie/orsvm-e1071/archive/v3.0.1.tar.gz)
# path                 ~/.opam/4.07/.opam-switch/build/orsvm_e1071.3.0.1
# command              ~/.opam/4.07/bin/jbuilder build -p orsvm_e1071 -j 127
# exit-code            1
# env-file             ~/.opam/log/orsvm_e1071-19-053f1c.env
# output-file          ~/.opam/log/orsvm_e1071-19-053f1c.out
### output ###
# File "src/jbuild", line 7, characters 14-19:
# 7 |   (libraries (dolog))))
#                   ^^^^^
# Error: Library "dolog" not found.
# Hint: try: dune external-lib-deps --missing -p orsvm_e1071 @install
```

**Comment by UnixJunkie** [comment]
You are right, thanks for the heads up, I fixed it.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
