### PR TITLE
Add ctypes 0.15.0

### PR DESCRIPTION
**Pull request by yallop**
Closes ocamllabs/ocaml-ctypes#605

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There is an issue in `pkcs11 < 0.18.0`:
```
# ocamlfind: Package `ctypes.foreign.unthreaded' not found - required by `ctypes.foreign'
```
Do you know where the problem is?

**Comment by kit-ty-kate** [comment]
(also check.ocamllabs.io says there weren't failing before)

**Comment by kit-ty-kate** [comment]
`zbar.0.9` also has the same issue

**Comment by kit-ty-kate** [comment]
Otherwise the rest of the dependencies seem to be ok

**Comment by yallop** [comment]
I think the problem is that `pkcs11` [has the following optional dependencies](https://github.com/ocaml/opam-repository/blob/aa6c2114cecc1d52cdc6d01d59eb81e21573d9e2/packages/pkcs11/pkcs11.0.17.1/opam#L40-L41):

```
"ctypes"
"ctypes-foreign"
```

but it actually requires exactly both or neither of `ctypes` and `ctypes-foreign` to be installed.  If `ctypes` is installed but `ctypes-foreign` is not then `pkcs11` will try and fail to build the optional driver component.

**Comment by yallop** [comment]
The issue with `zbar` appears to be similar.

**Comment by kit-ty-kate** [comment]
Fair enough then. Thanks!

**Pull request merged**
