### PR TITLE
mirage-block-unix 2.7.0: add missing io-page-unix dependency

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
The revdeps errors should be fixed by #11918

**Comment by kit-ty-kate** [comment]
This package doesn't seem to be compatible with safe-strings.
```
#=== ERROR while installing mirage-block-unix.2.7.0 ===========================#
# opam-version 1.2.2
# os           darwin
# command      ocaml setup.ml -build
# path         /Users/travis/.opam/system/build/mirage-block-unix.2.7.0
# compiler     system (4.06.1)
# exit-code    1
# env-file     /Users/travis/.opam/system/build/mirage-block-unix.2.7.0/mirage-block-unix-21135-a398ce.env
# stdout-file  /Users/travis/.opam/system/build/mirage-block-unix.2.7.0/mirage-block-unix-21135-a398ce.out
# stderr-file  /Users/travis/.opam/system/build/mirage-block-unix.2.7.0/mirage-block-unix-21135-a398ce.err
### stdout ###
# [...]
# /Users/travis/.opam/system/bin/ocamlfind ocamlopt -shared -I lib -I lib lib/mirage_block_unix.cmxa lib/block.cmx -o lib/mirage_block_unix.cmxs
# /Users/travis/.opam/system/bin/ocamlfind ocamldep -package cstruct -package cstruct.lwt -package io-page -package io-page.unix -package logs -package logs.fmt -package lwt -package lwt.unix -package mirage-block-lwt -package oUnit -package rresult -package uri -modules lib_test/test.ml > lib_test/test.ml.depends
# /Users/travis/.opam/system/bin/ocamlfind ocamldep -package cstruct -package cstruct.lwt -package io-page -package io-page.unix -package logs -package logs.fmt -package lwt -package lwt.unix -package mirage-block-lwt -package oUnit -package rresult -package uri -modules lib_test/utils.ml > lib_test/utils.ml.depends
# /Users/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -package cstruct -package cstruct.lwt -package io-page -package io-page.unix -package logs -package logs.fmt -package lwt -package lwt.unix -package mirage-block-lwt -package oUnit -package rresult -package uri -I lib_test -I lib -o lib_test/utils.cmo lib_test/utils.ml
# + /Users/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -package cstruct -package cstruct.lwt -package io-page -package io-page.unix -package logs -package logs.fmt -package lwt -package lwt.unix -package mirage-block-lwt -package oUnit -package rresult -package uri -I lib_test -I lib -o lib_test/utils.cmo lib_test/utils.ml
# ocamlfind: [WARNING] Package `threads': Linking problems may arise because of the missing -thread or -vmthread switch
# File "lib_test/utils.ml", line 102, characters 27-30:
# Error: This expression has type string but an expression was expected of type
#          bytes
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/Users/travis/.opam/system/bin/ocamlbuild' lib/libmirage_block_unix_stubs.a lib/dllmirage_block_unix_stubs.so lib/mirage_block_unix.cma lib/mirage_block_unix.cmxa lib/mirage_block_unix.a lib/mirage_block_unix.cmxs lib_test/benchmark.native lib_test/test.native -tag debug -tag tests' terminated with error code 10")
```
Could you add the appropriate constraint ?

Also on 4.05.0 for some reason the tests fail with:
```
#=== ERROR while installing mirage-block-unix.2.7.0 ===========================#
# opam-version 1.2.2
# os           linux
# command      ocaml setup.ml -test
# path         /home/travis/.opam/4.03.0/build/mirage-block-unix.2.7.0
# compiler     4.03.0
# exit-code    1
# env-file     /home/travis/.opam/4.03.0/build/mirage-block-unix.2.7.0/mirage-block-unix-19702-f936b0.env
# stdout-file  /home/travis/.opam/4.03.0/build/mirage-block-unix.2.7.0/mirage-block-unix-19702-f936b0.out
# stderr-file  /home/travis/.opam/4.03.0/build/mirage-block-unix.2.7.0/mirage-block-unix-19702-f936b0.err
### stdout ###
# Error: block:4:test parse(print(x)) == x for file://C%3A%5Ccygwin?buffered=1&sync=none (in the log).
# [...]
# Raised at file "src/oUnitAssert.ml", line 45, characters 8-27
# Called from file "src/oUnit.ml", line 86, characters 13-17
# Called from file "src/oUnit.ml", line 97, characters 13-17
# Called from file "src/oUnitRunner.ml", line 46, characters 13-26
# 
# expected: C:\cygwin but got: 
# ------------------------------------------------------------------------------
# Ran: 10 tests in: 0.38 seconds.
# FAILED: Cases: 10 Tried: 10 Errors: 0 Failures: 1 Skip:  0 Todo: 0 Timeouts: 0.
### stderr ###
# rm /tmp/mirage-block-test.20994.2
# rm /tmp/mirage-block-test.20994.2
# rm /tmp/mirage-block-test.20994.2
# W: Test 'test' fails: Command '/home/travis/.opam/4.03.0/build/mirage-block-unix.2.7.0/_build/lib_test/test.native -runner sequential' terminated with error code 1
# E: Failure("Tests had a 100.00% failure rate")
```

**Comment by samoht** [comment]
Ha yes I am confused; the error only appear in TravisCI because it's the only place where we are running the tests. Thanks for noticing :-)

**Comment by kit-ty-kate** [comment]
All green ! Thanks a lot !! :)

**Pull request merged**
