### PR TITLE
+flowtype.0.87.0

### PR DESCRIPTION
**Pull request by panagosg7**

### CODE REVIEW

**Comment by mseri** [comment]
The opam repository has moved to opam2 a few months ago. Please upgrade the PR to use a unique opam2 opam file. You can use `opam-publish`, `opam-package-upgrade` or `dune-release` to automate this task.

**Comment by panagosg7** [comment]
Thanks @mseri! I updated the PR.

**Comment by panagosg7** [comment]
Given this failure https://travis-ci.org/ocaml/opam-repository/jobs/461363021 I also restricted the version of ocaml to < 4.07

**Comment by mseri** [comment]
Thanks

**Pull request merged**
