### PR TITLE
Package coccinelle.1.0.8

### PR DESCRIPTION
**Pull request by XVilka**
### `coccinelle.1.0.8`
Coccinelle is a C source code matching and transformation engine
Coccinelle provides the language SmPL (Semantic Patch Language) for specifying
desired matches and transformations in C code.

---
* Homepage: http://coccinelle.lip6.fr/
* Source repo: git://github.com/coccinelle/coccinelle
* Bug tracker: cocci@systeme.lip6.fr

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by XVilka** [comment]
The [OS X Travis error](https://travis-ci.org/ocaml/opam-repository/jobs/638398825?utm_medium=notification&utm_source=github_status) seems unrelated:
```
... package available.
# Detecting depexts using vars: arch=x86_64, os=macos, os-distribution=homebrew, os-family=homebrew
# The following system packages are needed:
autoconf
pcre
pkg-config
python3
# The following new OS packages need to be installed: python3
Error: python 3.7.5 is already installed
To upgrade to 3.7.6_1, run `brew upgrade python`.
OS package installation failed
The command "bash -e .travis-ci.sh" exited with 1.
```

**Comment by XVilka** [comment]
The build failure for CentOS and OpenSUSE seems unrelated to coccinelle and instead conf-python3-dev should be fixed:
```
#=== ERROR while compiling conf-python-3-dev.1 ================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.09.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.09/.opam-switch/build/conf-python-3-dev.1
# command              /usr/bin/make
# exit-code            2
# env-file             ~/.opam/log/conf-python-3-dev-20-f9e6ac.env
# output-file          ~/.opam/log/conf-python-3-dev-20-f9e6ac.out
### output ###
# cc `python3-config --includes` -o test test.c
# /bin/sh: python3-config: command not found
# test.c:1:10: fatal error: Python.h: No such file or directory
#  #include "Python.h"
#           ^~~~~~~~~~
# compilation terminated.
# make: *** [Makefile:2: build] Error 1
```

**Comment by kit-ty-kate** [comment]
@XVilka if you have some time, could you return this fix upstream?

Should be good to go once CI is complete

**Comment by XVilka** [comment]
Sure, I will.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
