### PR TITLE
added packages/lz4_chans/lz4_chans.1.0.0

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
You can use them as drop-in replacement for the ones of the stdlib.
Cf. https://github.com/UnixJunkie/lz4-chans/blob/master/src/lz4_chans.mli

**Comment by UnixJunkie** [comment]
all CI tests are green.
And, it is Friday evening in here! Have a nice week-end! :smile:

**Comment by mseri** [comment]
Have a nice weekend!

**Comment by mseri** [comment]
Consider announcing this on the discuss forum if you havn't already done it.

**Pull request merged**
