### PR TITLE
Get rid of oasis.ocamlcore.org URL.

### PR DESCRIPTION
**Pull request by gildor478**

### CODE REVIEW

**Comment by gildor478** [comment]
@Chris00 please have look: I have remove some of your package.

**Comment by Chris00** [comment]
@gildor478 Thanks for letting me know. `weberizer` is not a problem because there is a newer version (0.7.7).  For `odepack`, I need to make a new release.  Since [a few people use it](https://opam.ocaml.org/packages/odepack/), please let me make a new release and let people upgrade before removing it.

**Comment by Chris00** [comment]
See https://github.com/ocaml/opam-repository/pull/8402

**Comment by gildor478** [comment]
@Chris00 This PR only removes odepack 0.6.4, which has been installed once in the last month. This should be OK, since there are versions after and before this one.

**Comment by Chris00** [comment]
Right but why is it so — other versions also mention forge.ocamlcore.org

**Comment by gildor478** [comment]
@Chris00 I am talking about OASIS.ocamlcore.org ;-)

https://forge.ocamlcore.org/forum/forum.php?forum_id=959

**Comment by Chris00** [comment]
Right — I am leaping too far into the future! 😊

**Pull request merged**
