### PR TITLE
[new release] bwrap (0.1)

### PR DESCRIPTION
**Pull request by Chris00**
Use Bubblewrap to sandbox executables

- Project page: <a href="https://github.com/Chris00/ocaml-bwrap">https://github.com/Chris00/ocaml-bwrap</a>
- Documentation: <a href="https://Chris00.github.io/ocaml-bwrap/doc">https://Chris00.github.io/ocaml-bwrap/doc</a>

##### CHANGES:

- Initial release.

### CODE REVIEW

**Comment by Chris00** [comment]
DO NOT MERGE YET, I'll update this release.

**Comment by Chris00** [comment]
The lower bound on the version worked for Ubuntu but [not for CentOS](https://ci.ocamllabs.io/log/saved/docker-build-3e122375413d30cde913c05341662ab9/d47e98312ef7d70e65b889f24ab42ac7d7e70e97).  The package seems to be [available on CentOS 7](https://centos.pkgs.org/7/epel-x86_64/bubblewrap-0.3.0-1.el7.x86_64.rpm.html) however.

**Comment by kit-ty-kate** [comment]
On CentOS the `bubblewrap` package is in the `EPEL` repository. I just fixed it, it should work now.

**Comment by avsm** [comment]
Is it worth constraining this to `os=linux` only?

**Comment by Chris00** [comment]
We could, although the lower bounds for some distro are needed.

**Comment by Chris00** [comment]
Aargh, any idea what I should do for openSUSE?

**Comment by avsm** [comment]
I'll be updating the opensuse containers to the latest release soon, so it's ok to leave it broken for now :)

**Comment by Chris00** [comment]
OK, I'll revert the changes.  `os-version >= "15"` should work, right?

**Comment by Chris00** [comment]
@kit-ty-kate My fate — well at least the package one — is in your hands! :-)

**Pull request closed without merging**
