### PR TITLE
[new release] ppx_irmin, irmin-unix, irmin, irmin-pack and irmin-graphql (2.1.0)

### PR DESCRIPTION
**Pull request by pascutto**
Irmin

- Project page: <a href="https://github.com/mirage/irmin">https://github.com/mirage/irmin</a>

#### Added

- **ppx_irmin** (_new_):
  - Created a new package, `ppx_irmin`, which provides a PPX deriving plugin
    for generating Irmin generics.

- **irmin-unix**:
  - Added a `--hash` parameter to the command-line interface, allowing the hash
    function to be specified. For BLAKE2b and BLAKE2s, the bit-length may be
    specified with a trailing slash, as in `--hash=blake2b/16`. The `hash`
    function may also be specified in the configuration file. (CraigFe/ppx_irmin#898, @craigfe)
 
- **irmin**:
  - Added `Irmin.Hash.Make_BLAKE2B` and `Irmin.Hash.Make_BLAKE2S` functors for
    customizing the bit-length of these hash functions. (CraigFe/ppx_irmin#898, @craigfe)
  - Added `iter` function over a closure graph (CraigFe/ppx_irmin#912, @ioana)
  - Added `Type.pp_ty` for pretty-printing Irmin generics. (CraigFe/ppx_irmin#926, @craigfe)
  - Added `Merge.with_conflict` for modifying the conflict error message of a
    merge function. (CraigFe/ppx_irmin#926, @craigfe)

#### Changed

- **irmin-pack**:
  - Changed the bit-length of serialized hashes from 60 to 30. (CraigFe/ppx_irmin#897,
    @icristescu)
  - `integrity_check` can now try to repair corrupted values. (CraigFe/ppx_irmin#947, @pascutto)

- **irmin-graphql**:
  - Changed default GraphQL type names to ensure uniqueness. (CraigFe/ppx_irmin#944, @andreas)

### CODE REVIEW

**Comment by CraigFe** [comment]
Something weird going on with the PR links here: they should be linking to `mirage/irmin` rather than `CraigFe/ppx_irmin`. I would guess it's an artefact of https://github.com/mirage/irmin/pull/952.

**Comment by kit-ty-kate** [comment]
Could you look into this build failure?
```
#=== ERROR while compiling irmin-unix.2.1.0 ===================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://github.com/mirage/irmin/releases/download/2.1.0/irmin-2.1.0.tbz)
# path                 ~/.opam/4.10/.opam-switch/build/irmin-unix.2.1.0
# command              ~/.opam/4.10/bin/dune build -p irmin-unix -j 72
# exit-code            1
# env-file             ~/.opam/log/irmin-unix-23-0a4083.env
# output-file          ~/.opam/log/irmin-unix-23-0a4083.out
### output ###
#       ocamlc src/irmin-unix/.irmin_unix.objs/byte/irmin_unix__Resolver.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt -w -40 -g -bin-annot -I src/irmin-unix/.irmin_unix.objs/byte -I /home/opam/.opam/4.10/lib/angstrom -I /home/opam/.opam/4.10/lib/astring -I /home/opam/.opam/4.10/lib/base -I /home/opam/.opam/4.10/lib/base/base_internalhash_types -I /home/opam/.opam/4.10/lib/base/caml -I /home/opam/.opam/4.10/lib/base/shadow_stdlib -I /home/opam/.opam/4.10/lib/base64 -I /home/opam/.opam/4.10/lib/bigarray-compat -I /home/opam/.opam/4.10/lib/bigstringaf -I /home/opam/.opam/4.10/lib/biniou -I /home/opam/.opam/4.10/lib/bytes -I /home/opam/.opam/4.10/lib/checkseum -I /home/opam/.opam/4.10/lib/cmdliner -I /home/opam/.opam/4.10/lib/cohttp -I /home/opam/.opam/4.10/lib/cohttp-lwt -I /home/opam/.opam/4.10/lib/cohttp-lwt-unix -I /home/opam/.opam/4.10/lib/conduit -I /home/opam/.opam/4.10/lib/conduit-lwt -I /home/opam/.opam/4.10/lib/conduit-lwt-unix -I /home/opam/.opam/4.10/lib/cstruct -I /home/opam/.opam/4.10/lib/ctypes -I /home/opam/.opam/4.10/lib/decompress -I /home/opam/.opam/4.10/lib/decompress/impl -I /home/opam/.opam/4.10/lib/digestif -I /home/opam/.opam/4.10/lib/dispatch -I /home/opam/.opam/4.10/lib/domain-name -I /home/opam/.opam/4.10/lib/duff -I /home/opam/.opam/4.10/lib/easy-format -I /home/opam/.opam/4.10/lib/encore -I /home/opam/.opam/4.10/lib/encore/butils -I /home/opam/.opam/4.10/lib/eqaf -I /home/opam/.opam/4.10/lib/fieldslib -I /home/opam/.opam/4.10/lib/fmt -I /home/opam/.opam/4.10/lib/fpath -I /home/opam/.opam/4.10/lib/git -I /home/opam/.opam/4.10/lib/git-http -I /home/opam/.opam/4.10/lib/git-unix -I /home/opam/.opam/4.10/lib/graphql -I /home/opam/.opam/4.10/lib/graphql-cohttp -I /home/opam/.opam/4.10/lib/graphql-lwt -I /home/opam/.opam/4.10/lib/graphql_parser -I /home/opam/.opam/4.10/lib/hex -I /home/opam/.opam/4.10/lib/index -I /home/opam/.opam/4.10/lib/index/unix -I /home/opam/.opam/4.10/lib/integers -I /home/opam/.opam/4.10/lib/ipaddr -I /home/opam/.opam/4.10/lib/ipaddr-sexp -I /home/opam/.opam/4.10/lib/ipaddr/unix -I /home/opam/.opam/4.10/lib/irmin -I /home/opam/.opam/4.10/lib/irmin-fs -I /home/opam/.opam/4.10/lib/irmin-git -I /home/opam/.opam/4.10/lib/irmin-graphql -I /home/opam/.opam/4.10/lib/irmin-http -I /home/opam/.opam/4.10/lib/irmin-mem -I /home/opam/.opam/4.10/lib/irmin-pack -I /home/opam/.opam/4.10/lib/irmin-watcher -I /home/opam/.opam/4.10/lib/jsonm -I /home/opam/.opam/4.10/lib/ke -I /home/opam/.opam/4.10/lib/logs -I /home/opam/.opam/4.10/lib/lru -I /home/opam/.opam/4.10/lib/lwt -I /home/opam/.opam/4.10/lib/lwt/unix -I /home/opam/.opam/4.10/lib/macaddr -I /home/opam/.opam/4.10/lib/magic-mime -I /home/opam/.opam/4.10/lib/mmap -I /home/opam/.opam/4.10/lib/ocaml/threads -I /home/opam/.opam/4.10/lib/ocamlgraph -I /home/opam/.opam/4.10/lib/ocplib-endian -I /home/opam/.opam/4.10/lib/optint -I /home/opam/.opam/4.10/lib/parsexp -I /home/opam/.opam/4.10/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.10/lib/psq -I /home/opam/.opam/4.10/lib/ptime -I /home/opam/.opam/4.10/lib/re -I /home/opam/.opam/4.10/lib/re/posix -I /home/opam/.opam/4.10/lib/re/str -I /home/opam/.opam/4.10/lib/result -I /home/opam/.opam/4.10/lib/rresult -I /home/opam/.opam/4.10/lib/seq -I /home/opam/.opam/4.10/lib/sexplib -I /home/opam/.opam/4.10/lib/sexplib0 -I /home/opam/.opam/4.10/lib/stdlib-shims -I /home/opam/.opam/4.10/lib/stringext -I /home/opam/.opam/4.10/lib/uchar -I /home/opam/.opam/4.10/lib/uri -I /home/opam/.opam/4.10/lib/uri-sexp -I /home/opam/.opam/4.10/lib/uri/services -I /home/opam/.opam/4.10/lib/uutf -I /home/opam/.opam/4.10/lib/webmachine -I /home/opam/.opam/4.10/lib/yaml -I /home/opam/.opam/4.10/lib/yaml/bindings -I /home/opam/.opam/4.10/lib/yaml/bindings/types -I /home/opam/.opam/4.10/lib/yaml/c -I /home/opam/.opam/4.10/lib/yaml/ffi -I /home/opam/.opam/4.10/lib/yaml/types -I /home/opam/.opam/4.10/lib/yojson -intf-suffix .ml -no-alias-deps -open Irmin_unix__ -o src/irmin-unix/.irmin_unix.objs/byte/irmin_unix__Resolver.cmo -c -impl src/irmin-unix/resolver.ml)
# File "src/irmin-unix/resolver.ml", line 141, characters 20-43:
# 141 |             (module Irmin.Hash.Make_BLAKE2B : SIZEABLE)
#                           ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Irmin.Hash.Make_BLAKE2B
#     ocamlopt src/irmin-unix/.irmin_unix.objs/native/irmin_unix__Resolver.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.10/bin/ocamlopt.opt -w -40 -g -I src/irmin-unix/.irmin_unix.objs/byte -I src/irmin-unix/.irmin_unix.objs/native -I /home/opam/.opam/4.10/lib/angstrom -I /home/opam/.opam/4.10/lib/astring -I /home/opam/.opam/4.10/lib/base -I /home/opam/.opam/4.10/lib/base/base_internalhash_types -I /home/opam/.opam/4.10/lib/base/caml -I /home/opam/.opam/4.10/lib/base/shadow_stdlib -I /home/opam/.opam/4.10/lib/base64 -I /home/opam/.opam/4.10/lib/bigarray-compat -I /home/opam/.opam/4.10/lib/bigstringaf -I /home/opam/.opam/4.10/lib/biniou -I /home/opam/.opam/4.10/lib/bytes -I /home/opam/.opam/4.10/lib/checkseum -I /home/opam/.opam/4.10/lib/cmdliner -I /home/opam/.opam/4.10/lib/cohttp -I /home/opam/.opam/4.10/lib/cohttp-lwt -I /home/opam/.opam/4.10/lib/cohttp-lwt-unix -I /home/opam/.opam/4.10/lib/conduit -I /home/opam/.opam/4.10/lib/conduit-lwt -I /home/opam/.opam/4.10/lib/conduit-lwt-unix -I /home/opam/.opam/4.10/lib/cstruct -I /home/opam/.opam/4.10/lib/ctypes -I /home/opam/.opam/4.10/lib/decompress -I /home/opam/.opam/4.10/lib/decompress/impl -I /home/opam/.opam/4.10/lib/digestif -I /home/opam/.opam/4.10/lib/dispatch -I /home/opam/.opam/4.10/lib/domain-name -I /home/opam/.opam/4.10/lib/duff -I /home/opam/.opam/4.10/lib/easy-format -I /home/opam/.opam/4.10/lib/encore -I /home/opam/.opam/4.10/lib/encore/butils -I /home/opam/.opam/4.10/lib/eqaf -I /home/opam/.opam/4.10/lib/fieldslib -I /home/opam/.opam/4.10/lib/fmt -I /home/opam/.opam/4.10/lib/fpath -I /home/opam/.opam/4.10/lib/git -I /home/opam/.opam/4.10/lib/git-http -I /home/opam/.opam/4.10/lib/git-unix -I /home/opam/.opam/4.10/lib/graphql -I /home/opam/.opam/4.10/lib/graphql-cohttp -I /home/opam/.opam/4.10/lib/graphql-lwt -I /home/opam/.opam/4.10/lib/graphql_parser -I /home/opam/.opam/4.10/lib/hex -I /home/opam/.opam/4.10/lib/index -I /home/opam/.opam/4.10/lib/index/unix -I /home/opam/.opam/4.10/lib/integers -I /home/opam/.opam/4.10/lib/ipaddr -I /home/opam/.opam/4.10/lib/ipaddr-sexp -I /home/opam/.opam/4.10/lib/ipaddr/unix -I /home/opam/.opam/4.10/lib/irmin -I /home/opam/.opam/4.10/lib/irmin-fs -I /home/opam/.opam/4.10/lib/irmin-git -I /home/opam/.opam/4.10/lib/irmin-graphql -I /home/opam/.opam/4.10/lib/irmin-http -I /home/opam/.opam/4.10/lib/irmin-mem -I /home/opam/.opam/4.10/lib/irmin-pack -I /home/opam/.opam/4.10/lib/irmin-watcher -I /home/opam/.opam/4.10/lib/jsonm -I /home/opam/.opam/4.10/lib/ke -I /home/opam/.opam/4.10/lib/logs -I /home/opam/.opam/4.10/lib/lru -I /home/opam/.opam/4.10/lib/lwt -I /home/opam/.opam/4.10/lib/lwt/unix -I /home/opam/.opam/4.10/lib/macaddr -I /home/opam/.opam/4.10/lib/magic-mime -I /home/opam/.opam/4.10/lib/mmap -I /home/opam/.opam/4.10/lib/ocaml/threads -I /home/opam/.opam/4.10/lib/ocamlgraph -I /home/opam/.opam/4.10/lib/ocplib-endian -I /home/opam/.opam/4.10/lib/optint -I /home/opam/.opam/4.10/lib/parsexp -I /home/opam/.opam/4.10/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.10/lib/psq -I /home/opam/.opam/4.10/lib/ptime -I /home/opam/.opam/4.10/lib/re -I /home/opam/.opam/4.10/lib/re/posix -I /home/opam/.opam/4.10/lib/re/str -I /home/opam/.opam/4.10/lib/result -I /home/opam/.opam/4.10/lib/rresult -I /home/opam/.opam/4.10/lib/seq -I /home/opam/.opam/4.10/lib/sexplib -I /home/opam/.opam/4.10/lib/sexplib0 -I /home/opam/.opam/4.10/lib/stdlib-shims -I /home/opam/.opam/4.10/lib/stringext -I /home/opam/.opam/4.10/lib/uchar -I /home/opam/.opam/4.10/lib/uri -I /home/opam/.opam/4.10/lib/uri-sexp -I /home/opam/.opam/4.10/lib/uri/services -I /home/opam/.opam/4.10/lib/uutf -I /home/opam/.opam/4.10/lib/webmachine -I /home/opam/.opam/4.10/lib/yaml -I /home/opam/.opam/4.10/lib/yaml/bindings -I /home/opam/.opam/4.10/lib/yaml/bindings/types -I /home/opam/.opam/4.10/lib/yaml/c -I /home/opam/.opam/4.10/lib/yaml/ffi -I /home/opam/.opam/4.10/lib/yaml/types -I /home/opam/.opam/4.10/lib/yojson -intf-suffix .ml -no-alias-deps -open Irmin_unix__ -o src/irmin-unix/.irmin_unix.objs/native/irmin_unix__Resolver.cmx -c -impl src/irmin-unix/resolver.ml)
# File "src/irmin-unix/resolver.ml", line 141, characters 20-43:
# 141 |             (module Irmin.Hash.Make_BLAKE2B : SIZEABLE)
#                           ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Irmin.Hash.Make_BLAKE2B
```

**Comment by kit-ty-kate** [comment]
Would it be possible to sync up all the irmin subpackages? (i.e. replacing the constraints on the irmin packages to `{= version}` instead of `{>= "2.0.0"}`)

**Comment by CraigFe** [comment]
> Would it be possible to sync up all the irmin subpackages? (i.e. replacing the constraints on the irmin packages to `{= version}` instead of `{>= "2.0.0"}`)

The current state is part of a concerted effort to avoid needing to release all Irmin packages in lock-step (https://github.com/mirage/irmin/pull/887/commits/4a22e3d5a5a3f3fedbaedc487a03813930175fd5).

**Comment by kit-ty-kate** [comment]
All green. Thanks! Could you return the fix upstream?

**Pull request merged**
