### PR TITLE
New package pattern.0.1.0

### PR DESCRIPTION
**Pull request by thierry-martinez**
pattern is a PPX extension that generates functions from patterns that explain match failures by returning the common context and the list of differences between a pattern and a value.

### CODE REVIEW

**Comment by mseri** [comment]
It's green!

**Comment by thierry-martinez** [comment]
Thanks! What should I do before merging?

**Comment by mseri** [comment]
Nothing, I was waiting for your reaction to see if you needed to further work on it for some reasons

**Comment by thierry-martinez** [comment]
Thank you very much! (For this merge and for all the other ones!)

**Comment by mseri** [comment]
If you have not yet done it, please consider announcing this on the discuss.ocaml.org forum. We have a community category and an announcement tag for this purpose.

**Pull request merged**
