### PR TITLE
Release Alba 0.4.3

### PR DESCRIPTION
**Pull request by hbr**

### CODE REVIEW

**Comment by avsm** [comment]
Camelus indicating this package is uninstallable is worrying...

**Comment by hbr** [comment]
> Camelus indicating this package is uninstallable is worrying...

Where can I find information why Camelus thinks the package in *uninstallable*? Can anybody give me a hint on how to investigate.

Thanks
Helmut

**Comment by avsm** [comment]
@altgr would you have any logs for this?

**Comment by mseri** [comment]
Could it be related to this?

```
[ERROR] No solution for alba.0.4.3: The following dependencies couldn't be met:
          - alba → js_of_ocaml → ocaml < 4.09.0
              base of this switch (use `--unlock-base' to force)
          - alba → js_of_ocaml → js_of_ocaml-compiler >= 3.5.0 → ocaml < 4.11
              base of this switch (use `--unlock-base' to force)
```

**Comment by hbr** [comment]
> Could it be related to this?
> 
> ```
> [ERROR] No solution for alba.0.4.3: The following dependencies couldn't be met:
>           - alba → js_of_ocaml → ocaml < 4.09.0
>               base of this switch (use `--unlock-base' to force)
>           - alba → js_of_ocaml → js_of_ocaml-compiler >= 3.5.0 → ocaml < 4.11
>               base of this switch (use `--unlock-base' to force)
> ```

I cannot relate this message to the dependencies of my project. The required dependencies are
```
depends: [
  "ocaml"            {>= "4.08.0"}
  "dune"             {>= "1.10.0"}
  "linenoise"
  "js_of_ocaml-ppx"
  "menhir"           {build}
  "js_of_ocaml"      {build}
  "ppx_inline_test"  {build}
  "odoc"             {with-doc}
]
```
What is in there which cannot be met?

**Comment by hbr** [comment]
Now I have made nearly all dependencies explicit. Camelus is still thinking that the package is not installable despite the fact that all tests show that the package is installable.

I am running out of ideas on how to make Camelus happy. Can anybody give me a hint?

**Comment by mseri** [comment]
Let’s see if @AltGr can provide us the logs, otherwise we will merge

**Comment by hbr** [comment]
> Let’s see if @AltGr can provide us the logs, otherwise we will merge

Hopefully it is possible to nail down the problem. On each release of my package, Camelus is complaining in one or another way. Usually somebody from the opam team makes Camelus happy. If I understood what is causing the problem, I would fix it myself without bothering others. However Camelus just says **no** without giving any explanation.

**Comment by hbr** [comment]
Can anybody help me?

I have no idea, why Camelus is marking the package as uninstallable. Is there a possibility to see some logs to investigate the problem?

**Comment by mseri** [comment]
Sorry for the long silence, I am in holiday and did not connect for a while. Let’s merge, if some metadata needs to be fixed we will do it separately. This has been pending for quite a while now

**Pull request merged**
