### PR TITLE
+httpaf.0.6.6

### PR DESCRIPTION
**Pull request by seliopou**

### CODE REVIEW

**Comment by seliopou** [comment]
It's unfortunate but for the CI to go green an upper bound needs to be added to angstrom so that the tests pass. Not sure if that's what should live in OPAM or not.

**Comment by kit-ty-kate** [comment]
This should fix the issue. Does that sound ok for you?

**Comment by seliopou** [comment]
I didn’t know you could do that. Looks good!

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
