### PR TITLE
Lemonade Sqlite v0.1.0

### PR DESCRIPTION
**Pull request by michipili**

### CODE REVIEW

**Comment by dsheets** [comment]
```
 wget https://github.com/michipili/lemonade-sqlite/releases/download/v0.1.0/lemonade-0.1.0.tar.xz
--2016-03-18 14:45:35--  https://github.com/michipili/lemonade-sqlite/releases/download/v0.1.0/lemonade-0.1.0.tar.xz
Resolving github.com... 192.30.252.129
Connecting to github.com|192.30.252.129|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-18 14:45:35 ERROR 404: Not Found.
```

**Comment by michipili** [comment]
Fixed :)

**Comment by dsheets** [comment]
#5960 would help to at least test on OS X. All other issues are expected. Thanks!

**Comment by michipili** [comment]
Yep, I'll try to work on this soon, thanks for your time!

**Pull request merged**
