### PR TITLE
[new release] riot (4 packages) (0.0.8)

### PR DESCRIPTION
**Pull request by leostera**
An actor-model multi-core scheduler for OCaml 5

- Project page: <a href="https://github.com/riot-ml/riot">https://github.com/riot-ml/riot</a>

## 0.0.8

This is the largest Riot release yet, and we are splitting the package into 4 sub-packages:

* the Riot runtime+library
* Bytestring – efficient and ergonomic bytestring manipulation
* Gluon – a low-level, efficient async I/O engine
* Rio – composable I/O streams for vectored operations

### Riot Runtime

* Improved performance and memory usage by creating 95% smaller processes,
  ensuring fibers are always properly discontinued to release their resources,
  and moving to Weak references for processes to ensure they get garbage
  collected timely.

* Introduce Process Priorities – the scheduler has been improved to support
  processes with different priorities (High, Normal, and Low). Thanks
  @LeedsJohn for the contribution! 👏

* Introduce `receive` Timeouts – you can now call `receive ~after:10L ()` and
  if there are messages fetched in 10 microseconds `receive` will raise a
  `Receive_timeout` exception that you can match on.

* Introduce `syscall` Timeouts – any syscall being made now can specify a
  timeout for an answer. If the syscall isn't ready to retry within the timeout
  period, a `Syscall_timeout` exception will be raised.

* Improve `Timer_wheel` with support for clearing timers, iterating timers
  in the order in which they were created, and a MinHeap backend.

### Riot Lib

* New `Dynamic_supervisor` to dynamically allocate pools of processes up to a
  maximum.

* New `Runtime.Stats` server can be started to periodically print out
  statistics about the runtime and the garbage collector.

* The `Net.Socket` module is now split into a `Tcp_listener` and a
  `Tcp_stream`, with their corresponding functions for listening, connecting,
  sending, and receiving. These also include support for timeouts.

* New File and File Descriptor operations for seeking. Thanks to @diogomqbm! 👏

* Introduce SSL module to turn sockets into SSL-backed Reader/Writer streams.
  This includes making a `Net.Socket.stream_socket` into a client or a server
  SSL-backed stream pair.

* Introduce `Task` to quickly spin up processes that we can await. This is the
  closest we have to a future. A `Task` is typed, executes a single function,
  and MUST be awaited with `Task.await ?timeout task`.

* Introduce `Crypto.Random` module with high-level utilities for creating
  random data of different types, including integers of different sizes,
  strings, bytestrings, bytes, characters, and ASCII strings.

* Introduce new named pid functions `Process.where_is` and `Porcess.await_name`
  to make it easier to find pids by name, and await a name to be registered.

* New `Process.is_alive` predicate to check if a process is alive

* Improve logging on most modules with namespaces

* Initializing the Riot runtime twice results in a runtime exception – thanks
  @julien-leclercq for the contribution! 👏

* Introduce `Ref.cast` to do type-safe type-casting based on runtime
  information of a Ref at its instantiation time.

* Introduce a `Stream` module that extends the stdlib Seq with a `reduce_while` combinator.

* Introduce inmemory key-value `Store` that works in a process-friendly
  fashion, similar to Erlang's ETS.

### Bytestring

* First implementation of efficient immutable byte strings with cheap view and
  concat operations. Thanks to @felipecrv for contributing! 👏

* Iterators and Transient builders for efficiently examining, destructuring,
  and constructing byte strings from different sources.

* Preliminary Bytestrings syntax support (via a ppx) for constructions and
  efficient pattern matching using the `%b` sigil.

### Gluon

* First implementation of an efficient, low-level async I/O engine inspired by
  Rust's Mio. Gluon uses an opaque Token based approach that lets you directly
  reference an OCaml value as part of the polled events from the underlying
  async engine. Thanks to @diogomqbm and @emilpriver for contributing! 👏

* Preliminary support for epoll on Linux and kqueue on macOS with conditional
  compilation via the `config` package.

### Rio

* First implementation of composable I/O streams via a Read/Write interface
  inspired by Rust's Read/Write traits.

### CODE REVIEW

**Comment by leostera** [comment]
This release depends on #25074 and #25068.

**Comment by dinosaure** [comment]
Several tests don't work on some distributions such as Ubuntu 23.10 with OCaml 5.1:
```
- File "test/dune", line 112, characters 7-26:
- 112 |  (name link_processes_test)
-              ^^^^^^^^^^^^^^^^^^^
- (cd _build/default/test && ./link_processes_test‧exe)
- 2024-02-17 00:03:03.55563Z ERROR [thread=107] Scheduler‧run exception: Core.Process.Process_reviving_is_forbidden(_) due to: 
```

Can you fix them?

**Comment by mseri** [comment]
One of the issues on mac seems likely due to the sandbox:
```
# File "test/dune", line 9, characters 7-15:
# 9 |  (name ssl_test)
#            ^^^^^^^^
# (cd _build/default/test && ./ssl_test.exe)
# 2024-02-21 11:17:44.38554Z ERROR [thread=0] Process <0.1.0> died with unhandled exception Port_finder.No_ports_available:
# Raised by primitive operation at Gluon__Net.Socket.make in file "gluon/net.ml", line 81, characters 13-62
# Called from Gluon__Net.Tcp_listener.bind.(fun) in file "gluon/net.ml", line 96, characters 13-46
# Called from Gluon_common.syscall in file "gluon/common/gluon_common.ml", line 21, characters 8-13
# 
```

The other failure seem more relevant, it does not happen all the time but it consistently appears in some builds alongside another one:
```
# File "test/dune", line 118, characters 7-32:
# 118 |  (name process_registration_test)
#              ^^^^^^^^^^^^^^^^^^^^^^^^^
# (cd _build/default/test && ./process_registration_test.exe)
# 10:51:52.69048Z [error] process_registration_test: send to dead process by name should've raised!
[...]
# File "test/dune", line 112, characters 7-26:
# 112 |  (name link_processes_test)
#              ^^^^^^^^^^^^^^^^^^^
# (cd _build/default/test && ./link_processes_test.exe)
# 2024-02-21 10:51:53.05228Z ERROR [thread=22] Scheduler.run exception: Core.Process.Process_reviving_is_forbidden(_) due to: 
```

**Comment by mseri** [comment]
Looks good, I think we just need to add upper bounds to atacama 0.0.4 and minttea 0.2.0. Do you agree?

**Comment by leostera** [comment]
Thanks @mseri, yup!  I had them but the `dune-release` flow is merciless and, well, it force pushed. So I'll add them again as soon as we get a passing build. The riscv64-* jobs are taking a while.

**Comment by mseri** [comment]
I'll patch libc opam file in a separate PR. This looks fine

**Comment by leostera** [comment]
Haha i was just opening the PR to see how CI did! Thanks @mseri 🙏🏼

**Pull request merged**
