### PR TITLE
Package ocsigen-toolkit.4.0.0

### PR DESCRIPTION
**Pull request by balat**
### `ocsigen-toolkit.4.0.0`
Reusable UI components for Eliom applications (client only, or client-server)
The Ocsigen Toolkit is a set of user interface widgets that facilitate the development of Eliom applications.

---
* Homepage: http://www.ocsigen.org
* Source repo: git+https://github.com/ocsigen/ocsigen-toolkit.git
* Bug tracker: https://github.com/ocsigen/ocsigen-toolkit/issues/

---
:camel: Pull-request generated by opam-publish v2.3.0

### CODE REVIEW

**Comment by balat** [comment]
Requires https://github.com/ocaml/opam-repository/pull/26466

**Comment by shonfeder** [comment]
We're seeing a failure here on arm32 (https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/e18a90358931158280216a8e7740834a00cd6afa/variant/extras,arm32-ocaml-5.2,ocsigen-toolkit.4.0.0):


```
#=== ERROR while compiling ocsigen-toolkit.4.0.0 ==============================#
# context              2.3.0~alpha~dev | linux/arm32 | ocaml-base-compiler.5.2.0 | pinned(https://github.com/ocsigen/ocsigen-toolkit/archive/refs/tags/4.0.0.tar.gz)
# path                 ~/.opam/5.2/.opam-switch/build/ocsigen-toolkit.4.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build make -j79
# exit-code            2
# env-file             ~/.opam/log/ocsigen-toolkit-7-594d29.env
# output-file          ~/.opam/log/ocsigen-toolkit-7-594d29.out
### output ###
# mkdir -p _deps
# mkdir -p _deps/src/widgets/
<snip>
# File "_none_", line 1:
# Error: Cannot load js_of_ocaml-ppx_deriving_json: this object file uses
#        unsafe features
# Makefile:174: .depend: No such file or directory
# make: *** [Makefile:185: _deps/src/widgets/ot_pulltorefresh.eliomi.server] Error 2
# make: *** Waiting for unfinished jobs....
<snip>
# Error: Cannot load js_of_ocaml-ppx_deriving_json: this object file uses
#        unsafe features
# make: *** [Makefile:185: _deps/src/widgets/ot_tip.eliomi.server] Error 2


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ocsigen-toolkit 4.0.0
+- 
```

**Comment by balat** [comment]
I guess this package won't be available on 32 bit architectures for now. The problem seems to come from js_of_ocaml_deriving. I've added a constraint in the opam file

**Comment by balat** [comment]
@shonfeder It should be ok now :)

**Comment by mseri** [comment]
Thanks

**Pull request merged**
