### PR TITLE
easy-format 1.3.0, now uses jbuilder

### PR DESCRIPTION
**Pull request by mjambon**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Hi @mjambon . I believe you need to rename the current `opam` file in this PR and rename `easy-format.opam` to `opam`.

**Comment by avsm** [comment]
There are some reverse dependency failures coming up from this, or possibly from a cppo upgrade:

```
#=== ERROR while compiling bisect_ppx.1.2.0 ===================================#
# context              2.0.0~beta3 | linux/x86_64 | ocaml-base-compiler.4.04.2 | file:///home/opam/src
# path                 ~/.opam/ocaml-base-compiler.4.04.2/.opam-switch/build/bisect_ppx.1.2.0
# command              make build
# exit-code            2
# env-file             ~/.opam/log/bisect_ppx-78-548b09.env
# output-file          ~/.opam/log/bisect_ppx-78-548b09.out
### output ###
# ocamlbuild -use-ocamlfind -no-links -byte-plugin -plugin-tag 'package(cppo_ocamlbuild)'  src/syntax/bisect_ppx.native  src/report/report.native src/bisect.cma src/bisect.cmxa  src/ocamlbuild/bisect_ppx_plugin.cma  src/ocamlbuild/bisect_ppx_plugin.cmxa
# ocamlfind ocamlc -package unix -package ocamlbuild -linkpkg -package cppo_ocamlbuild myocamlbuild.ml /home/opam/.opam/ocaml-base-compiler.4.04.2/lib/ocamlbuild/ocamlbuild.cmo -o myocamlbuild
# + ocamlfind ocamlc -package unix -package ocamlbuild -linkpkg -package cppo_ocamlbuild myocamlbuild.ml /home/opam/.opam/ocaml-base-compiler.4.04.2/lib/ocamlbuild/ocamlbuild.cmo -o myocamlbuild
# ocamlfind: Package `cppo_ocamlbuild' not found
# Command exited with code 2.
# Makefile:99: recipe for target 'build' failed
# make: *** [build] Error 10
```

**Comment by rgrinberg** [comment]
> There are some reverse dependency failures coming up from this, or possibly from a cppo upgrade:

Good catch. cppo_ocamlbuild is now a separate package and needs to be submitted as well. The failed packages need their dependencies updated.

**Comment by rgrinberg** [comment]
@avsm where can i see the list of rev deps that failed to build?

**Comment by avsm** [comment]
This is continued in #10047

**Comment by rgrinberg** [comment]
@avsm Why does this need maintainer action? I think this is safe to merge and has nothing to do with the cppo_ocamlbuild packaging change.

**Comment by avsm** [comment]
This does looks fine, thanks!

**Pull request merged**
