### PR TITLE
Package ocsigen-start.7.0.0

### PR DESCRIPTION
**Pull request by balat**
### `ocsigen-start.7.0.0`
Higher-level library for developing Web and mobile applications with users, registration, notifications, etc
Ocsigen Start is a set of higher-level libraries for building client-server Web and mobile applications with Ocsigen (Js_of_ocaml and Eliom).
It provides modules for user management (session management, registration, activation keys, ...), managing groups of users, displaying tips, and easily sending notifications to the users.
Ocsigen Start comes with an eliom-distillery template for an app with a database, user management, and session management.
This template is intended to serve as a basis for quickly building the Minimum Viable Product for Web and mobile applications with users.
The goal is to enable the programmer to concentrate on the core of the app, and not on user management.

---
* Homepage: https://ocsigen.org/ocsigen-start/
* Source repo: git+https://github.com/ocsigen/ocsigen-start.git
* Bug tracker: https://github.com/ocsigen/ocsigen-start/issues

---
:camel: Pull-request generated by opam-publish v2.3.0

### CODE REVIEW

**Comment by mseri** [comment]
Requires https://github.com/ocaml/opam-repository/pull/26466

**Comment by mseri** [comment]
I have restarted the CI

**Comment by shonfeder** [comment]
The failures remaining are either from deps (windows) or solver timeouts. LGTM Thanks :)

**Comment by balat** [comment]
Thank you @shonfeder :partying_face:

**Pull request merged**
