### PR TITLE
[new release] coq-lsp (0.1.0)

### PR DESCRIPTION
**Pull request by ejgallego**
Language Server Protocol native server for Coq

- Project page: <a href="https://github.com/ejgallego/coq-lsp">https://github.com/ejgallego/coq-lsp</a>
- Documentation: <a href="https://ejgallego.github.io/coq-lsp/">https://ejgallego.github.io/coq-lsp/</a>

##### CHANGES:

-----------------------

 - Location-aware cache for incremental Coq interpretation (@ejgallego)
 - Smart, structure-aware error recovery (@ejgallego)
 - Configure flags reading _CoqProject file (@artagnon, ejgallego/coq-lsp#3)
 - Interruption support (@ejgallego , @Alizter, ejgallego/coq-lsp#27, ejgallego/coq-lsp#32, ejgallego/coq-lsp#34)
 - Markdown support (@ejgallego, ejgallego/coq-lsp#62)
 - Goal display (@ejgallego @corwin-of-amber, ejgallego/coq-lsp#69)
 - User-side configuration (@ejgallego, ejgallego/coq-lsp#67)
 - Allow to configure before/after goal display (@ejgallego, ejgallego/coq-lsp#78)
 - Allow requests to interrupt checking (@ejgallego, ejgallego/coq-lsp#76)

### CODE REVIEW

**Comment by ejgallego** [comment]
CI is fine, except for the 32bit build, which I can't reproduce locally and it is the same problem than we have seen with coq-serapi many other times.

**Comment by ejgallego** [comment]
To be clear, this fails in the 32 bit build due to deps failing, not to the package itself so imho it is ready

**Comment by ejgallego** [comment]
Thanks a lot to you @kit-ty-kate ! I'll be good if I could debug the 32bit problem with Serapi, but so far I've failed to reproduce, should I bring this to some slack channel?

**Comment by kit-ty-kate** [comment]
maybe on `#compiler` or `#general`

**Pull request merged**
