### PR TITLE
added ppx_meta_conv.2.6.0

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
ci tells:  "[ERROR] Actions cancelled because of Sys_error("No space left on device")"

**Comment by camlspotter** [comment]
ppx_test requires an update for ppxx

**Comment by camlspotter** [comment]
No space left on device.

**Comment by camlspotter** [comment]
@avsm  Could you or someone check the failures please?  The disk seems to be full.

**Comment by camlspotter** [comment]
The code itself has a problem, too.

```
# *** omake error:
#    File /home/travis/.opam/4.04.0/lib/omake/build/OCaml.om: line 1196, characters 4-70
#    Do not know how to build "ocaml/ocaml.o" required for "tests/variantrecord.opt"
```

**Comment by camlspotter** [comment]
Travis CI build finally succeeded.  Other failures seem to be due to "No space left on device".

**Comment by avsm** [comment]
sorry about the space issues on CI infrastructure -- that'll be sorted soon.

**Comment by avsm** [comment]
@camlspotter: I'm getting a bad checksum on ppx_meta_conv.2.5.0:

```
[ERROR] Bad checksum for /home/opam/.opam/packages.dev/ppx_meta_conv.2.5.0/2.5.0.tar.gz:
          - 2cd5055d7267c0e762c7220568d3b5e6 [expected result]
          - 6fc5428ec4d8d9a12128f9a3f0d254dc [actual result]
        This may be fixed by running `opam update`.
```

**Comment by camlspotter** [comment]
@avsm The following commit has already fixed the checksum issue...
https://github.com/ocaml/opam-repository/pull/8928/commits/f6fad9cc939a72682d149420c8754539d0ee1967

**Comment by avsm** [comment]
thanks! ppx_meta_conv.2.5.0 also fails to compile on ocaml.4.04, so a constraint may be in order...

```
- File "ocaml.mli", line 1:
- Error: Corrupted compiled interface
- ../lib/meta_conv.cmi
- *** omake: 152/385 targets are up to date
```

**Comment by camlspotter** [comment]
Thanks!

**Comment by camlspotter** [comment]
```
- File "ocaml.mli", line 1:
- Error: Corrupted compiled interface
```

This was due to the disk full I think.

**Pull request merged**
