### PR TITLE
[new release] dns, dns-stub, dns-certify, dns-mirage, dns-resolver, dns-client, dns-server, dns-tsig and dns-cli (5.0.0)

### PR DESCRIPTION
**Pull request by hannesm**
An opinionated Domain Name System (DNS) library

- Project page: <a href="https://github.com/mirage/ocaml-dns">https://github.com/mirage/ocaml-dns</a>
- Documentation: <a href="https://mirage.github.io/ocaml-dns/">https://mirage.github.io/ocaml-dns/</a>

##### CHANGES:

* IPv6 support for client and server (Mirage, Unix, Lwt) (mirage/ocaml-dns#249 mirage/ocaml-dns#252 @hannesm)
  This results in breaking changes, especially in the Mirage boilerplate,
  since now a Mirage_stack.V4V6 is needed instead of a Mirage_stack.V4.
* dns-certify: support EC private keys, now that X509 0.12.0 supports them
  (mirage/ocaml-dns#252 @hannesm)

### CODE REVIEW

**Comment by hannesm** [comment]
//cc @dinosaure

**Comment by kit-ty-kate** [comment]
The failures on OCaml 4.13 are due to a bug in the type-checker: https://github.com/ocaml/ocaml/issues/10271

**Comment by hannesm** [comment]
failures:
- capnp-rpc-mirage (@talex5)
- conduit-mirage (@samoht @dinosaure @hannesm) -- patch at https://github.com/mirage/ocaml-conduit/pull/380
- dkim (@dinosaure)
- git-mirage (@dinosaure)

**Comment by hannesm** [comment]
I looked through the CI failures, and they are unrelated. This is good to be merged.

**Comment by talex5** [comment]
Note sure why the builds on `pima` were failing. I restarted a few and they seemed fine the second time.

**Comment by hannesm** [comment]
Thanks @talex5. I pushed a commit to restrict "resp-mirage" to conduit-mirage <2.3.0 to fix a CI issue that @kit-ty-kate was curious about.

**Comment by hannesm** [comment]
looks like resp-mirage 0.10.0 is still in a non-working state. I doubt the root cause is a release of dns, and don't have the motivation to investigate further.

what can I do to get this PR merged?

**Comment by hannesm** [comment]
I force-pushed a fix for resp-mirage -- it requires conduit-mirage 2.3.0 or later (not below, and not above 2.0.0). now CI has various other temporary issues.

**Comment by mseri** [comment]
Looks fine, the remaining jobs are all timing out (which is not surprising imho given the amount of things this PR is testing). I think this can be merged

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by hannesm** [comment]
thanks!

**Pull request merged**
