### PR TITLE
Add opam-depext 1.1.0 (renamed from 'depext'). This is the opam 2.0 version

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by avsm** [comment]
The CI failures are expected here due to special-case pins for opam2 depext.

**Comment by avsm** [comment]
`depext.1.0.1` appears to require a cmdliner<1.0 constraint @AltGr 

```
#=== ERROR while installing depext.1.0.1 ======================================#
# opam-version 1.2.2
# os           linux
# command      ocamlopt -I /home/travis/.opam/4.06.0/lib/cmdliner unix.cmxa cmdliner.cmxa -o opam-depext depext.ml
# path         /home/travis/.opam/4.06.0/build/depext.1.0.1
# compiler     4.06.0
# exit-code    2
# env-file     /home/travis/.opam/4.06.0/build/depext.1.0.1/depext-29640-57f057.env
# stdout-file  /home/travis/.opam/4.06.0/build/depext.1.0.1/depext-29640-57f057.out
# stderr-file  /home/travis/.opam/4.06.0/build/depext.1.0.1/depext-29640-57f057.err
### stderr ###
# [...]
# File "depext.ml", line 151, characters 17-33:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "depext.ml", line 169, characters 24-40:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "depext.ml", line 539, characters 50-53:
# Error: The function applied to this argument has type
#          ?docv:string -> ?doc:string -> Cmdliner.Arg.info
# This argument cannot be applied with label ?env
```

**Comment by AltGr** [comment]
Not sure I get it, `1.0.1` has `depends: [ "cmdliner" {build & <= "0.9.8"} ]`

**Comment by avsm** [comment]
Let's test that independently; i'll get this in so that the depext pins can be fixed up in CI while I'm doing the transition.

**Pull request merged**
