### PR TITLE
2 packages from sapristi/easy_logging at 0.5.2

### PR DESCRIPTION
**Pull request by sapristi**
This pull-request concerns:
-`easy_logging.0.5.2`: Module to log messages. Aimed at being both powerful and easy to use
-`easy_logging_yojson.0.5.2`: Configuration loader for easy_logging with yojson backend

---
* Homepage: https://sapristi.github.io/easy_logging/
* Source repo: git+https://github.com/sapristi/easy_logging.git
* Bug tracker: https://github.com/sapristi/easy_logging/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by mseri** [comment]
Does the old `easy_logging_yojson` need an upper bound on `easy_logging`?
```
#=== ERROR while compiling easy_logging_yojson.0.5 ============================#
# context              2.0.4 | linux/x86_64 | ocaml-variants.4.08.1+trunk | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.08/.opam-switch/build/easy_logging_yojson.0.5
# command              ~/.opam/4.08/bin/dune build -p easy_logging_yojson -j 2
# exit-code            1
# env-file             ~/.opam/log/easy_logging_yojson-17-c60d31.env
# output-file          ~/.opam/log/easy_logging_yojson-17-c60d31.out
### output ###
#       ocamlc conf_loader_modules/yojson/.easy_logging_yojson.objs/byte/easy_logging_yojson.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -w -g -bin-annot -I conf_loader_modules/yojson/.easy_logging_yojson.objs/byte -I /home/opam/.opam/4.08/lib/biniou -I /home/opam/.opam/4.08/lib/easy-format -I /home/opam/.opam/4.08/lib/easy_logging -I /home/opam/.opam/4.08/lib/ocaml-migrate-parsetree -I /home/opam/.opam/4.08/lib/ocaml/compiler-libs -I /home/opam/.opam/4.08/lib/ppx_derivers -I /home/opam/.opam/4.08/lib/ppx_deriving/api -I /home/opam/.opam/4.08/lib/ppx_deriving/runtime -I /home/opam/.opam/4.08/lib/ppx_deriving_yojson -I /home/opam/.opam/4.08/lib/ppx_deriving_yojson/runtime -I /home/opam/.opam/4.08/lib/ppx_tools -I /home/opam/.opam/4.08/lib/result -I /home/opam/.opam/4.08/lib/yojson -no-alias-deps -o conf_loader_modules/yojson/.easy_logging_yojson.objs/byte/easy_logging_yojson.cmo -c -impl conf_loader_modules/yojson/easy_logging_yojson.pp.ml)
# File "conf_loader_modules/yojson/easy_logging_yojson.ml", line 5, characters 17-28:
# 5 | type log_level = E.log_level
#                      ^^^^^^^^^^^
# Error: Unbound type constructor E.log_level
```

**Comment by sapristi** [comment]
Yes you're right @mseri . Should I fix the 0.5 version before I can make this pull request ?

**Comment by mseri** [comment]
@sapristi if you can add the upper bound it would be great. You can do it as part of this PR if ypu want

**Comment by sapristi** [comment]
Ok, it took me some time to find out how to modify the PR, but this should do it I guess.

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
