### PR TITLE
Add ocaml jupyter kernel 2.7.8

### PR DESCRIPTION
**Pull request by akabe**
https://github.com/akabe/ocaml-jupyter/releases/tag/v2.7.8

### CODE REVIEW

**Comment by mseri** [comment]
Ocaml 4.04 to 4.09 fails to compile with
```
# (cd _build/default && /home/opam/.opam/4.04/bin/ocamlc.opt -ppx '/home/opam/.opam/4.04/lib/lwt_ppx/./ppx.exe --as-ppx' -ppx '/home/opam/.opam/4.04/lib/ppx_deriving/./ppx_deriving package:ppx_deriving_yojson' -short-paths -safe-string -strict-sequence -strict-formats -w A-4-31-33-34-39-41-42-43-44-45-48-49-50-58 -g -bin-annot -I jupyter/src/repl/.jupyter_repl.objs/byte -I /home/opam/.opam/4.04/lib/bigarray-compat -I /home/opam/.opam/4.04/lib/biniou -I /home/opam/.opam/4.04/lib/easy-format -I /home/opam/.opam/4.04/lib/logs -I /home/opam/.opam/4.04/lib/lwt -I /home/opam/.opam/4.04/lib/lwt/unix -I /home/opam/.opam/4.04/lib/mmap -I /home/opam/.opam/4.04/lib/ocaml/compiler-libs -I /home/opam/.opam/4.04/lib/ocaml/threads -I /home/opam/.opam/4.04/lib/ocplib-endian -I /home/opam/.opam/4.04/lib/ocplib-endian/bigstring -I /home/opam/.opam/4.04/lib/ppx_deriving/runtime -I /home/opam/.opam/4.04/lib/ppx_deriving_yojson/runtime -I /home/opam/.opam/4.04/lib/result -I /home/opam/.opam/4.04/lib/seq -I /home/opam/.opam/4.04/lib/uuidm -I /home/opam/.opam/4.04/lib/yojson -I jupyter/src/core/.jupyter.objs/byte -I jupyter/src/log/.jupyter_log.objs/byte -no-alias-deps -open Jupyter_repl__ -o jupyter/src/repl/.jupyter_repl.objs/byte/jupyter_repl__Dir_trace.cmo -c -impl jupyter/src/repl/dir_trace.pp.ml)
# File "jupyter/src/repl/dir_trace.ml", line 38, characters 8-30:
# Error: Unbound value Env.find_value_by_name
```
Should we change the bound on ocaml or some other library, or you want to fix this in some other way?

**Comment by akabe** [comment]
@mseri Thanks for the notification. I fixed my opam file.

**Comment by akabe** [comment]
Hmm. CI keeps failing yet, but it seems the cause of its failure is not an added opam file.

**Comment by mseri** [comment]
Those are infrastructure related, you can ignore them. 

Thanks!

**Pull request merged**
