### PR TITLE
+websocket-async.2.11

### PR DESCRIPTION
**Pull request by vbmithr**

### CODE REVIEW

**Comment by rgrinberg** [comment]
@avsm what's wrong with Camelus here? The submission seems fine.

**Comment by jpdeplaix** [comment]
@rgrinberg The submission is fine as far as the linting goes. However the CI highlights that ```websocket-async.2.11``` cannot be installed on any switches.

**Comment by jpdeplaix** [comment]
@vbmithr any idea what's wrong with that ?

**Comment by vbmithr** [comment]
no clue

**Comment by samoht** [comment]
Looks good now, thanks for the fix.

**Pull request merged**
