### PR TITLE
[new release] redirect.0.2.0

### PR DESCRIPTION
**Pull request by thierry-martinez**
Add `string_of_channel`, `add_file` and `string_of_file`.

### CODE REVIEW

**Comment by thierry-martinez** [comment]
I think that the reported error currently reported by OCaml CI is transient:
```
    redirect.0.2.0 (failed: Error: Could not update repository "beta": "/usr/bin/git fetch -q" exited with code 128 "fatal: unable to look up github.com (port 9418) (Temporary failure in name resolution)")
```

Should I make a dummy commit to check if it is now fixed? Many thanks.

**Comment by thierry-martinez** [comment]
I just saw (again?) that there is a "Rebuild" button. It is all green now!

**Comment by dinosaure** [comment]
Seems good to me, thanks!

**Comment by thierry-martinez** [comment]
Thank you, @dinosaure !

**Pull request merged**
