### PR TITLE
[new release] dune (1.9.1)

### PR DESCRIPTION
**Pull request by rgrinberg**
CHANGES:

- Fix invocation of odoc to add previously missing include paths, impacting
  mld files that are not in directories containing libraries (ocaml/dune#2016, fixes
  ocaml/dune#2007, @jonludlam)

cc @avsm who was interested in this fix.

### CODE REVIEW

**Comment by mseri** [comment]
The only surprising failures are `git` and `utop`. They should not be related but can you please double check before I merge?

**Comment by mseri** [comment]
Git should be fixed by https://github.com/ocaml/opam-repository/pull/13891

**Comment by mseri** [comment]
The utop failure is due to camomile failing to build. This was succeeding on the last dune PR, @yoriyuki have you seen the failure in the ci in the Past?

**Comment by kit-ty-kate** [comment]
The camomile failure is indeed weird, I've seen previous versions of it failing randomly in [check.ocamllabs.io](http://check.ocamllabs.io) though. I've relaunched it, let's see if it's random or if it's a real failure. If it passes, I'll go ahead and merge this.

**Comment by kit-ty-kate** [comment]
yep, it's an intermittent failure. Thanks!

**Pull request merged**
