### PR TITLE
Add obuild 0.1.9

### PR DESCRIPTION
**Pull request by jpdeplaix**
This release fixes the incompatibility with safe-string.

### CODE REVIEW

**Comment by gasche** [comment]
@mseri: if "mseri self-requested a review 27 minutes ago" is you trying to signal that you are working on  the issue around the proposal I made of assigning issues to ourselves, note that it does not work, you need to *assign* the issue for something to be visible in the global [list of Pull Requets](https://github.com/ocaml/opam-repository/pulls).

**Comment by mseri** [comment]
@gasche yes, I was trying to signal that I was on it. I'll assign it, thanks

**Comment by mseri** [comment]
Anyways, it looks good. Three more builds to go and we know if it can be merged

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
