### PR TITLE
llvmgraph.0.2 - via opam-publish

### PR DESCRIPTION
**Pull request by Drup**
Ocamlgraph overlay for llvm

This overlay allows you to read and walk (but not write) the control flow graph of an llvm function using the same interface as an ocamlgraph. In particular, read-only ocamlgraph's algorithm can be applied.
---
* Homepage: https://github.com/Drup/llvmgraph
* Source repo: https://github.com/Drup/llvmgraph.git
* Bug tracker: https://github.com/Drup/llvmgraph/issues

---
Now require llvm>=3.6

* Bugfix for fold_succ_e
* Restore compat with ocamlgraph 1.8.6
* Add Llvm's uses as label on edges.

---
Pull-request generated by opam-publish v0.2.1

### CODE REVIEW

**Comment by Drup** [comment]
I'm afraid CI is not going to be very useful here.

**Comment by avsm** [comment]
It would be good to fix that rather than ignore it...

**Comment by Drup** [comment]
Here are the important pieces to be able to install llvm 3.6 in travis : https://github.com/Drup/llvmgraph/blob/master/.travis-ci.sh#L11-L16

I'm not sure how to modify the script to install llvm only when necessary. Do we want the ability to install different llvm version ?

**Comment by Drup** [comment]
The CI opam script should use a modified solver to always pick the *oldest* version of dependencies, to force people to put inferior bounds. :D

Apparently, opam 1.2.1's internal solver doesn't pick the same version than 1.2.0.

llvm 3.1 seems completely broken, do I remove it ? Is llvm 3.2 still ok ? llvm 3.4 seem to work.

cc @jpdeplaix

**Comment by jpdeplaix** [comment]
I don't know about 3.1 and 3.2 but yeah maybe we should remove them

**Comment by Drup** [comment]
I removed llvm 3.1 and 3.2, It works ! 

There is a weird ppa failure on one of the job, but it's on 4.00.1 where neither version of llvmgraph is installable.

**Pull request merged**
