### PR TITLE
Package ocamlformat.v0.1

### PR DESCRIPTION
**Pull request by jberdine**
### `ocamlformat.v0.1`

Auto-formatter for OCaml code

OCamlFormat is a tool to automatically format OCaml code in a uniform style.

---
* Homepage: https://github.com/ocaml-ppx/ocamlformat
* Source repo: https://github.com/ocaml-ppx/ocamlformat.git
* Bug tracker: https://github.com/ocaml-ppx/ocamlformat/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by avsm** [comment]
I think this needs a constraint on ocaml-version >= 4.04.0 or higher due to

```
#=== ERROR while installing ocamlformat.v0.1 ==================================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              make
# path                 /home/opam/.opam/4.03.0/build/ocamlformat.v0.1
# compiler             4.03.0
# exit-code            2
# env-file             /home/opam/.opam/4.03.0/build/ocamlformat.v0.1/ocamlformat-29-8b0e80.env
# stdout-file          /home/opam/.opam/4.03.0/build/ocamlformat.v0.1/ocamlformat-29-8b0e80.out
# stderr-file          /home/opam/.opam/4.03.0/build/ocamlformat.v0.1/ocamlformat-29-8b0e80.err
### stdout ###
# sed -e "s|@OPAM_SWITCH[@]|$(opam switch show)|g" src/jbuild-workspace.in > src/jbuild-workspace
# curl -s https://raw.githubusercontent.com/ocaml/ocaml/4.04.2/stdlib/format.ml > src/format/format.ml
# patch -s -d src/format -i format.ml.patch -o format_.ml
# curl -s https://raw.githubusercontent.com/ocaml/ocaml/4.04.2/stdlib/format.mli > src/format/format.mli
# patch -s -d src/format -i format.mli.patch -o format_.mli
# patching file src/Version.ml
# jbuilder build --root=src -j 4 ocamlformat.exe
# Makefile:55: recipe for target 'exe' failed
### stderr ###
# Options are:
# [...]
#   -dparsetree  (undocumented)
#   -dtypedtree  (undocumented)
#   -drawlambda  (undocumented)
#   -dlambda  (undocumented)
#   -dinstr  (undocumented)
#   -dtimings  Print timings
#   -help  Display this list of options
#   --help  Display this list of options
# make: *** [exe] Error 1
``` 

on 4.03.0

The 4.06.0 failure is unrelated due to sexplib -- @trefis is cutting a point release of that for 4.06 compatibility

**Comment by jberdine** [comment]
Note that on ocaml-ppx/ocamlformat#18 @dbuenzli noticed an issue where building ocamlformat accesses the network in order to download and patch the stdlib Format module.

Perhaps this means that this PR should not be merged.

**Comment by dbuenzli** [comment]
I think it would be better if this didn't happen see my comment [here](https://github.com/ocaml-ppx/ocamlformat/issues/18#issuecomment-3383855999).

**Comment by jpdeplaix** [comment]
I see that ocamlformat provides an emacs plugin but it doesn't seem to be installed by this package. Is this intended ?

**Comment by jberdine** [comment]
It is "intended" in that I realize that it's not installed, but that is only because I have not looked into how to install it in the right way. I'm no emacs or opam guru, and it seems that the right thing to do involves opam-user-setup, which I'm not familiar with.

**Comment by jpdeplaix** [comment]
Mmh I'm not sure of what opam-user-setup is but I would suggest to mimic the solutions from ```merlin``` and ```ocp-indent```, that is to put it in ```%{share_root}%/emacs/```:
* https://github.com/ocaml/merlin/blob/master/merlin.install
* https://github.com/OCamlPro/ocp-indent/blob/rewind/ocp-indent.install

**Comment by jberdine** [comment]
Good idea, thanks for the suggestion! I'll add [it](https://github.com/ocaml-ppx/ocamlformat/commit/b074dd9331e3580d1218951b64abd8c7f094713c) to the next update of this PR.

**Comment by gasche** [comment]
Should I close this PR or do you plan to rebase the branch with the new metadata?

(I'll go try to ping Pierre about 1229...)

**Comment by jberdine** [comment]
I am in the process of discussing with legal about creating a separate package with the patched version of format.ml and format.mli. I have not rebased with updated metadata in order to save CI bandwidth when there are known issues that would preclude merging anyhow. I'm fine for this to be closed and I'll reopen later if it helps the process.

**Comment by gasche** [comment]
On my side I did what I could to get you a review for the patch.

**Pull request closed without merging**
