### PR TITLE
github.com/diml -> github.com/jeremiedimino

### PR DESCRIPTION
**Pull request by jeremiedimino**
I changed my github username from "diml" to "jeremiedimino". According to github the old URLs should still work, but we might as well use the new ones.

This PR replaces all references to "diml" by "jeremiedimino" in the repo.

### CODE REVIEW

**Comment by avsm** [comment]
Thanks @jeremiedimino!

One limitation of this username migration: if you had previously transferred something to another org, then the original `diml -> <org>` redirection no longer works.

So some packages like `pp` are broken, since they use:

```
https://github.com/jeremiedimino/pp/releases/download/1.0.1/pp-1.0.1.tbz
```

but only

```
https://github.com/ocaml-dune/pp/releases/download/1.0.1/pp-1.0.1.tbz
```

works. If you could push changes for those (the CI jobs are failing), then this is good to merge.

**Comment by jeremiedimino** [comment]
Sure, I'm going to update these!

**Comment by jeremiedimino** [comment]
Alright, I think I got them all

**Comment by kit-ty-kate** [comment]
Looks good. Thanks a lot!

**Pull request merged**
