### PR TITLE
[coq-serapi] New release 8.7.2+0.4.13

### PR DESCRIPTION
**Pull request by ejgallego**
Fixes build with newer (>= v0.11) ppx_sexp_conv.

### CODE REVIEW

**Comment by ejgallego** [comment]
CI summary:
- Travis is OK
- v1.2 common distros fails in Alpine due to missing m4.
- v2.0 seems stuck in a different version [old bug?]

**Comment by ejgallego** [comment]
CI summary:
- Travis is OK
- v1.2 common distros fails in Alpine due to missing m4.
- v2.0 seems stuck in a different version [old bug?]

**Comment by kit-ty-kate** [comment]
> Fixes build with newer (>= v0.11) ppx_sexp_conv.

It's really weird this failure wasn't spotted before :/
Could you add the appropriate constraints to the older versions as well, then ? Otherwise CI is indeed fine.

**Comment by ejgallego** [comment]
> It's really weird this failure wasn't spotted before :/

Well `ppx_sexp_conv` v0.11.0 introduces a new ocamlfind package that becomes a hard runtime dependency. So `v0.11.0` is now a runtime dependency of SerAPI, however `v0.10.0` was only a _build_-time one. I guess that could explain the lack of rev-dep testing?

> Could you add the appropriate constraints to the older versions as well, then ?

Just to be sure, you want me to add an upper bound `< v0.11.0` to all previous versions?

**Comment by kit-ty-kate** [comment]
> Just to be sure, you want me to add an upper bound ```< v0.11.0``` to all previous versions?

If you can, yes.

**Comment by ejgallego** [comment]
Sure @kit-ty-kate , will do.

**Comment by ejgallego** [comment]
Ok, commit adding the upper bounds pushed, I am not sure how testing will work in this case.

**Comment by kit-ty-kate** [comment]
Looks good. Thanks a lot !

**Pull request merged**
