### PR TITLE
Detect graphics.cmi in system compiler

### PR DESCRIPTION
**Pull request by dra27**
Re-run of #11946.

cc @damiendoligez, @gasche - this affects the release scripts for ocaml.

### CODE REVIEW

**Comment by gasche** [comment]
I'm not completely sure I follow, how does that change the release process?

**Comment by dra27** [comment]
@gasche - if the creation of the new `ocaml-system` package for the released version involves copying the previous one, then you're fine ... but if it's done from a template, then that template needs updating (see the changes in anyone of the gen scripts in this PR)

**Comment by dra27** [comment]
I'm not totally clear why some build jobs succeeded on Travis and some didn't - but equally the script change is the same on all versions and Travis can't test system compiler packages anyway.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
