### PR TITLE
Package profiling.1.5.5

### PR DESCRIPTION
**Pull request by aryx**
### `profiling.1.5.5`
Small library to help profile code
This is a small library of utilities used by Semgrep and
a few other projects developed at r2c to monitor and profile
functions.

---
* Homepage: https://semgrep.dev
* Source repo: git+https://github.com/returntocorp/semgrep
* Bug tracker: https://github.com/returntocorp/semgrep/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by aryx** [comment]
stuck again on those macos jobs

**Comment by aryx** [comment]
I clicked rebuild all, but still stucked, waiting for workers on those macos jobs

**Comment by aryx** [comment]
yeah! all green!

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
