### PR TITLE
Add ppx_jsobject_conv 0.7.0 and 0.8.0

### PR DESCRIPTION
**Pull request by little-arhat**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
`ppx_jsobject_conv.0.8.0` doesn't compile:
```
#=== ERROR while compiling ppx_jsobject_conv.0.8.0 ============================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.04.2 | pinned(https://github.com/little-arhat/ppx_jsobject_conv/archive/v0.8.0.tar.gz)
# path                 ~/.opam/4.04/.opam-switch/build/ppx_jsobject_conv.0.8.0
# command              ~/.opam/4.04/bin/dune build -p ppx_jsobject_conv -j 72
# exit-code            1
# env-file             ~/.opam/log/ppx_jsobject_conv-23-1ea1f3.env
# output-file          ~/.opam/log/ppx_jsobject_conv-23-1ea1f3.out
### output ###
#       ocamlc src/.ppx_jsobject_conv.objs/byte/ppx_jsobject_conv.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.04/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I src/.ppx_jsobject_conv.objs/byte -I /home/opam/.opam/4.04/lib/base -I /home/opam/.opam/4.04/lib/base/caml -I /home/opam/.opam/4.04/lib/base/shadow_stdlib -I /home/opam/.opam/4.04/lib/ocaml-compiler-libs/common -I /home/opam/.opam/4.04/lib/ocaml-compiler-libs/shadow -I /home/opam/.opam/4.04/lib/ocaml-migrate-parsetree -I /home/opam/.opam/4.04/lib/ocaml/compiler-libs -I /home/opam/.opam/4.04/lib/ppx_derivers -I /home/opam/.opam/4.04/lib/ppxlib -I /home/opam/.opam/4.04/lib/ppxlib/ast -I /home/opam/.opam/4.04/lib/ppxlib/print_diff -I /home/opam/.opam/4.04/lib/ppxlib/traverse_builtins -I /home/opam/.opam/4.04/lib/result -I /home/opam/.opam/4.04/lib/sexplib0 -I /home/opam/.opam/4.04/lib/stdio -no-alias-deps -o src/.ppx_jsobject_conv.objs/byte/ppx_jsobject_conv.cmo -c -impl src/ppx_jsobject_conv.pp.ml)
# File "src/ppx_jsobject_conv.ml", line 363, characters 8-30:
# Error: The constructor Rtag expects 4 argument(s),
#        but is applied here to 3 argument(s)
```

**Comment by little-arhat** [comment]
@kit-ty-kate yes, I don't properly use migrate-parsetree, so 0.8.0 works with ocaml >4.0.8 (I believe). In the repo I have [constraint](https://github.com/little-arhat/ppx_jsobject_conv/blob/master/ppx_jsobject_conv.opam#L21) but looks like those were removed from `opam-repository`, so I didn't add them. 

What are the current guidelines? 

(And I guess I have to integrate migrate-parsetree... %))

**Comment by kit-ty-kate** [comment]
Ah, I see what is your issue. Your opam files are still using the opam1.2 format. I'll add the constraint for you.

What did you use to upgrade the format? I'm a bit surprise that the tool you used didn't correctly transfer the `ocaml-version` constraint.

**Comment by kit-ty-kate** [comment]
Looks like it wasn't the compiler constraint anyway afterall, just the one on ppxlib.

**Comment by kit-ty-kate** [comment]
It looks like it works now. Thanks!

**Pull request merged**
