### PR TITLE
[new release] owl-zoo, owl-top, owl-base, owl and owl-plplot (1.0.1)

### PR DESCRIPTION
**Pull request by jzstark**
OCaml Scientific and Engineering Computing - Zoo

- Project page: <a href="https://github.com/owlbarn/owl">https://github.com/owlbarn/owl</a>
- Documentation: <a href="https://owlbarn.github.io/">https://owlbarn.github.io/</a>

##### CHANGES:

* Add eighth-order finite difference approximation
* Fix bug in Jacobian with different input/output dimensions (owlbarn/owl#557)
* Fix bug in nested grads (owlbarn/owl#558)
* Update to ocamlformat.0.16.0 (thanks @gpetiot owlbarn/owl#556)
* Add get_fancy to AD
* Check input and output type of `diff` operation
* Fix bug in `build_info` of aiso pattern in AD
* Implement split forward mode and check max tag of `build_info` 
* Add initial implementation of fft2 and ifft2
* Add nonsymmetric qs suppport for continuous and discrete time lyapunov gradients
* Improve `care` and `dare` operations in AD
* Improve forward mode efficiency for sylv, clyap and dlyap operations in AD

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
`owl.1.0.1`'s tests seem to fail on OCaml 4.11:
```
# ┌──────────────────────────────────────────────────────────────────────────────┐
# │ [FAIL]        algodiff matrix              0   reverse mode.                 │
# └──────────────────────────────────────────────────────────────────────────────┘
# [failure] 
# failed reverse mode operations
#        sylvester (1/20)
# 
# Logs saved to `~/.opam/4.11/.opam-switch/build/owl.1.0.1/_build/default/test/_build/_tests/Owl/algodiff matrix.000.output'.
#  ──────────────────────────────────────────────────────────────────────────────
# 
# Full test results in `~/.opam/4.11/.opam-switch/build/owl.1.0.1/_build/default/test/_build/_tests/Owl'.
# 1 failure! in 2.000s. 1396 tests run.
```
Could you have a look into it?

**Comment by jzstark** [comment]
Thanks Kate! We'll look into this issue.

**Comment by jzstark** [comment]
@kit-ty-kate Hopefully the problem is fixed now. Should I close this PR and make a new one?

**Comment by kit-ty-kate** [comment]
since you're using dune-release, I think so. Don't forget to delete your branch before calling dune-release again since it doesn't work well when a branch already exists

**Comment by mseri** [comment]
Hi, sorry for disappearing so long. Fwiw, in the past we used to disable tests before merging the submission, using the CI to check that the only failures were spurious known tests or missing dependencies.

In that case I usually pointed this out and added a commit to disable tests after checking that everything else was fine. Good to see that there is a fix, even though I think that we should think at something different from fixing a seed. I'll comment on owl asap.

**Pull request closed without merging**
