### PR TITLE
redis.0.3.4 - via opam-publish

### PR DESCRIPTION
**Pull request by aluuu**
Bindings for the key-value cache and store redis.

---
* Homepage: https://github.com/0xffea/ocaml-redis
* Source repo: https://github.com/0xffea/ocaml-redis.git
* Bug tracker: https://github.com/0xffea/ocaml-redis/issues

---
### opam-lint failures
- **WARNING** 97 long description unspecified

---

Pull-request generated by opam-publish v0.3.4

### CODE REVIEW

**Comment by rgrinberg** [comment]
What about redis-lwt? :)

**Comment by aluuu** [comment]
Hi @rgrinberg,

While fighting with CI failures I've added lwt as a dependency in redis.opam. In previous setup './configure --enable-lwt' worked for purpose of distinguishing sync and lwt versions of redis.

If we'll switch to three separate packages (redis, redis-lwt and redis-sync, according to opam files) we won't be able to setup redis like `opam install redis`, right?

What's the right way to make such things now?

**Comment by rgrinberg** [comment]
The right way to make such thing work is to have users install backends
manually. So a user that wants to use redis with let will install  and
depend on redis-lwt. This is desirable and an improvement. Which means that
your redis package should publish 3 opam packages simultaneously. See how
lwt does it for example.

Do you think there are problems with this setup?

**Comment by aluuu** [comment]
Thank you very much for clarification. It definitely makes sense, but just differs a bit from publishing process I had with oasis + make setup.

Thank you.

**Pull request closed without merging**
