### PR TITLE
Package merlin.3.0.3

### PR DESCRIPTION
**Pull request by let-def**
### `merlin.3.0.3`

Editor helper, provides completion, typing and source browsing in Vim and Emacs

Merlin is an assistant for editing OCaml code. It aims to provide the features available in modern IDEs: error reporting, auto completion, source browsing and much more.

---
* Homepage: https://github.com/ocaml/merlin
* Source repo: https://github.com/ocaml/merlin.git
* Bug tracker: https://github.com/ocaml/merlin/issues

---
### opam-lint failures
- **WARNING** 41 Some packages are mentionned in package scripts of features, but there is no dependency or depopt toward them: "user-setup"

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by yallop** [comment]
I've cancelled the Travis build; we can restart it once findlib/ocamlfind is available again (#10383).

**Comment by jpdeplaix** [comment]
I restarted ci.opam.io but I don't have the rights to restart travis. Can someone restart it ?

**Comment by yallop** [comment]
I've restarted the Travis builds.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
