### PR TITLE
old opam file fixes

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by yallop** [comment]
[More checksum problems](https://travis-ci.org/ocaml/opam-repository/jobs/129149009):

```
[ERROR] Bad checksum for
        /home/travis/.opam/packages.dev/ppx_meta_conv.2.3.0/2.3.0.tar.gz:
          - fa6c852eec4959ef687f6f174d1ec9c7 [expected result]
          - 059c85952cba15f8c8f8924d5862f0f8 [actual result]
        This may be fixed by running `opam update`.
```

**Comment by camlspotter** [comment]
ok old opam of ppx_meta_conv requires fixes first.

**Comment by yallop** [comment]
The `treeprint.2.0.0` build [is failing](https://travis-ci.org/ocaml/opam-repository/jobs/129451379); perhaps a missing dependency?

```
# ocamlfind: Package `ppx_ocaml_conv' not found
# *** omake: targets were not rebuilt because of errors:
#    <scanner lib/scan-ocaml-aprinter.mli>
#       depends on: lib/aprinter.mli
# E: Failure("Command 'cp OMakeroot.in OMakeroot; PREFIX=/home/travis/.opam/system omake' terminated with error code 2")
```

**Comment by camlspotter** [comment]
Build #10466.4 went crazy at preparing OCaml

**Comment by yallop** [comment]
The OPAM 1.1.2 build is broken (but fixed in #6530).  Besides that, this looks fine.

**Pull request merged**
