### PR TITLE
Package glfw-ocaml (3.2.1-3)

### PR DESCRIPTION
**Pull request by SylvainBoilard**
CHANGES:

* Added missing AutoIconify window attribute.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
All the failures seem to come from an unavailable or outdated version of glfw. They can be ignored

**Comment by kit-ty-kate** [comment]
The package itself looks good otherwise.

**Comment by kit-ty-kate** [comment]
All good now, thanks!

**Comment by SylvainBoilard** [comment]
Thank you!

**Pull request merged**
