### PR TITLE
mosquitto 0.2

### PR DESCRIPTION
**Pull request by mwweissmann**

### CODE REVIEW

**Comment by gasche** [comment]
Hi @mwweissmann. Would it be possible for you to split the `depext` part of the package into a "virtual" `conf-libmosquitto` package (see `conf-libpng` for example) on which your `mosquitto` package would depend? This has several benefits (see #5791 for a discussion):

- instead of duplicating your `depexts` in each of your version, you point to a single definition point. If we fix depexts for a system or add new depexts to `conf-mosquitto`, all your released versions instantly benefit.
- this allows other packages that would like to depend on the system library but not on your binding to reuse your `depext`-gathering work

**Comment by mwweissmann** [comment]
ok... can I specify OS-releases as depexts? Ubuntu-trusty does not seem to have libmosquitto while later releases do. Otherwise I'd have to drop ubuntu completely from the depexts to avoid failing builds.

**Comment by dbuenzli** [comment]
> ok... can I specify OS-releases as depexts? Ubuntu-trusty does not seem to have libmosquitto while later releases do. Otherwise I'd have to drop ubuntu completely from the depexts to avoid failing builds.

You can't at the moment, see https://github.com/ocaml/opam-depext/issues/43. Just specify the depext, and if/when you see a failure due to that just tell us in the comment. It won't block merge.

**Comment by gasche** [comment]
Thanks for the change. Note that the CI is also [catching a 4.02.3-specific failure](https://ci.ocaml.io/log/saved/docker-build-613721d8b0690a784806f214be235bd6/8572485e954b1b670d3f26df4add6aadd92a90b0) that seems to be related to C89 vs. C99 coding style. Before OCaml 4.03.0, the OCaml compiler would not require --std=gnu99, so if you use `ocaml` to compile your C files you probably need to add `--std=gnu99` to your `CCOpt` in _oasis.

**Comment by mwweissmann** [comment]
Does having no "depext" for a specific OS mean everything is fine or that it is unavailable for that OS? CentOS does not have a package for libmosquitto but it would work with a manually installed one.

**Comment by gasche** [comment]
My understanding is that (1) the CI will not automatically install the system package if the depext is missing (see @dbuenzli's comment above, this is not blocking) and (2) users will be able to use the package, but they will have less guidance if things fail -- hopefully your own OCaml package produces configure-script errors that clarify the cause of failure.

One thing one can do is to add a `build` step in the `conf-*` package that checks whether the depext is installed -- then installation will fail there if the library is missing, and user will know what is wrong. This works relatively well for binaries, but it tends to be a pain for libraries: if all packages properly provide `pkg-config` support its easy, but otherwise it can be fairly tricky/fragile. In that case it is justified, in my opinion, to be pragmatic and not have a test.

**Comment by mwweissmann** [comment]
Well, the conf-mosquitto package has a "ls /usr/include/mosquitto.h" test -- fairly horrible, but there is no pkg-config support.
Can the CI be reset? It desperately tries to build v0.2 -- which I pulled and supplanted with v0.2.1 to fix the C99 issue. Or should I just withdraw the pull request and initiate a fresh one?

**Comment by gasche** [comment]
I tried to reset the Travis CI build. Because the other parts of the CI ("All distros" tests many different distributions, "Compilers" tests many different OCaml versions) work fine, I believe that there is nothing wrong with the package and would be tempted to go ahead and merge if it remains stuck on 0.2.0.

**Comment by mwweissmann** [comment]
great, thanks!

**Comment by gasche** [comment]
Merged; thanks for your reactivity.

**Pull request merged**
