### PR TITLE
Sundials/ML: new release v2.6.2p0

### PR DESCRIPTION
**Pull request by tbrk**
Major update to Sundials/ML.

### CODE REVIEW

**Comment by tbrk** [comment]
The Linux travis builds fail because the version of Ubuntu (12.04) is too old: the sundials package is for version 2.4, but Sundials/ML requires 2.5 (the latest is 2.6).

**Comment by avsm** [comment]
bulk build results across multiple distros: https://github.com/avsm/opam-pr-build-results/blob/6022/README.md

**Comment by tbrk** [comment]
OK. Thanks for the build results. I learnt some docker this afternoon.
alpine, centos, oraclelinux: no sundials package (how can I indicate this in the opam package?)
fedora: needed an additional dependency (reported upstream)

**Comment by tbrk** [comment]
Update on different Linux builds.
centos: fixed (gets sundials from EPEL repository, lapack-devel in centos repository)
oraclelinux: depexts not supported (lapack-devel package not in oracle or EPEL repositories)
alpine: depexts not supported (no sundials package in alpine repository)

**Comment by avsm** [comment]
Thanks for taking the effort to look into the other distros!  We'll add the ability to do 'negative support' at some point

**Pull request merged**
