### PR TITLE
Constraints for Lwt 5.0.0

### PR DESCRIPTION
**Pull request by aantron**
Release PR is https://github.com/ocaml/opam-repository/pull/15541.

### CODE REVIEW

**Comment by aantron** [comment]
Details here: https://github.com/ocaml/opam-repository/pull/15541#issuecomment-566065188

**Comment by talex5** [comment]
I'm not sure just removing all the failing tests is a good idea. How do we know these packages work correctly with the new Lwt if we're no longer testing them?

**Comment by hannesm** [comment]
I agree with @talex5 and am in favour for packages I maintain to use an upper bound for lwt `< 5.0.0`, and fixing in upcoming releases, than to remove the tests.

**Comment by aantron** [comment]
I agree that removing the tests is not optimal, but I am also hesitant about adding a constraint. The fact that it was the *tests* that failed indicates that the packages themselves compiled against Lwt, and given the conservative nature of breakage, there is plenty of reason to think that if they compiled, they still work if and only if they worked before. That would make new constraints excessive, and could be a burden on transitive users of the packages, for whom the *tests* are not in the dependency graph.

I don't know what the right thing to do here is, or how to properly express the constraints. Is it possible to add a partially redundant `"lwt" {with-test & < "5.0.0"}`?

**Comment by hannesm** [comment]
@aantron I think adding `"lwt" {with-test & < "5.0.0"}` should work and would be fine with me. thanks.

**Comment by talex5** [comment]
> The fact that it was the tests that failed to compile indicates that the packages themselves compiled against Lwt (and in some cases I verified this), and given the conservative nature of the breakage, there is plenty of reason to think that if they compiled, they still work if and only if they worked before.

But once the packages have been stripped of their tests, they are vulnerable to bugs in *any* new versions of their upstream packages, not just Lwt 5.0.0.

In any case, mirage-logs should be removed from this PR (I assume it works with the updated Lwt release).

**Comment by aantron** [comment]
Ok, I updated the patch not to remove any tests, but only to add `with-test & < "5.0.0"` constraints or `with-test & >= "5.0.0"` conflicts for packages whose tests got broken. I tested that this kind of constraint works locally with a local opam repo.

`mirage-logs` is excluded from the patch. It will work with the retagged Lwt 5.0.0; I checked this locally. Thanks again @talex5. I also checked tests of `noise`, the other package whose tests triggered an exception due to nested `Lwt_main.run`. These tests still trigger that exception with the patched Lwt 5.0.0, so `noise` tests get a constraint.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Comment by aantron** [comment]
Thanks! I was just checking the CI failures, but none of them seem related to these constraints, nor would they be, as the constraints should have no material effect on the repo at the moment.

I will fix the build of `markup-lwt` 0.5.0 against `markup` 0.7.5, one of the packages that failed, since I maintain that. It probably just needs a constraint, because `markup` 0.7.5 still included the code of `markup-lwt`, and the two were never meant to be installed together. I'll send a PR for that later.

**Pull request merged**
