### PR TITLE
Package fluent-logger.1.1.0

### PR DESCRIPTION
**Pull request by komamitsu**
### `fluent-logger.1.1.0`
Structured logger for Fluentd (OCaml)
Structured logger for Fluentd (OCaml)

---
* Homepage: https://github.com/komamitsu/fluent-logger-ocaml
* Source repo: git+https://github.com/komamitsu/fluent-logger-ocaml.git
* Bug tracker: https://github.com/komamitsu/fluent-logger-ocaml/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I think the name of the library is `oUnit` not `ounit`:
```
#=== ERROR while compiling fluent-logger.1.1.0 ================================#
# context     2.0.0 | linux/x86_64 | ocaml-system.4.06.1 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-system/.opam-switch/build/fluent-logger.1.1.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p fluent-logger -j 1
# exit-code   1
# env-file    ~/.opam/log/fluent-logger-15236-6aa130.env
# output-file ~/.opam/log/fluent-logger-15236-6aa130.out
### output ###
# File "test/dune", line 3, characters 19-24:
# 3 |  (libraries extlib ounit fluent_logger))
#                        ^^^^^
# Error: Library "ounit" not found.
# Hint: try: dune external-lib-deps --missing -j 1 -p fluent-logger @runtest
```

**Comment by mseri** [comment]
I understand correctly that if we have `{with-test}` inside a `run-test` stanza, the tests are not run? If this is the case we should probably block this at the camelus linting stage

**Comment by kit-ty-kate** [comment]
> I understand correctly that if we have `{with-test}` inside a `run-test` stanza, the tests are not run? If this is the case we should probably block this at the camelus linting stage

yes. I agree, that'd be nice indeed

**Comment by mseri** [comment]
@AltGr @nojb would it be hard to add that?

**Comment by kit-ty-kate** [comment]
Filled an issue: https://github.com/AltGr/Camelus/issues/27

**Comment by komamitsu** [comment]
Thanks for taking care of the PR.

> `# 3 |  (libraries extlib ounit fluent_logger))`

`ounit` seems valid here as well as `oUnit`.

The problem is `"ounit" {with-test}` in `depends` in `fluent-logger.opam` wasn't installed. I think `opam install . --deps-only -t` was needed in advance.
Sorry for my silly question, but `opam install . --deps-only -t` should be explicitly written in `fluent-logger.opam`?

**Comment by kit-ty-kate** [comment]
> `ounit` seems valid here as well as `oUnit`.

Not for ocamlfind or dune. The package name is different from its `findlib name`:
```
# #require "ounit";;
No such package: ounit
# #require "oUnit";;
/home/kit_ty_kate/.opam/4.07.1/lib/ocaml/unix.cma: loaded
/home/kit_ty_kate/.opam/4.07.1/lib/bytes: added to search path
/home/kit_ty_kate/.opam/4.07.1/lib/oUnit: added to search path
/home/kit_ty_kate/.opam/4.07.1/lib/oUnit/oUnitAdvanced.cma: loaded
/home/kit_ty_kate/.opam/4.07.1/lib/oUnit/oUnit.cma: loaded
```

**Comment by kit-ty-kate** [comment]
ping @komamitsu

**Comment by komamitsu** [comment]
Updated this pull request with
- https://github.com/komamitsu/fluent-logger-ocaml/commit/2f0716a7df24e91b5f13452fd749cb6bbb931766
- https://github.com/komamitsu/fluent-logger-ocaml/commit/cfea30fef694234ded8e0df09dbbb930eca13034

**Comment by mseri** [comment]
Thanks

**Comment by komamitsu** [comment]
Thanks guys!

**Pull request merged**
