### PR TITLE
Add prettiest.0.0.1

### PR DESCRIPTION
**Pull request by andreasfrom**

### CODE REVIEW

**Comment by hcarty** [comment]
A build failure - not sure of the cause.  Maybe a version constraint is needed somewhere?
```
#=== ERROR while installing prettiest.0.0.1 ===================================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -p prettiest -j 2
# path                 /home/opam/.opam/4.03.0/build/prettiest.0.0.1
# compiler             4.03.0
# exit-code            1
# env-file             /home/opam/.opam/4.03.0/build/prettiest.0.0.1/prettiest-7-012887.env
# stdout-file          /home/opam/.opam/4.03.0/build/prettiest.0.0.1/prettiest-7-012887.out
# stderr-file          /home/opam/.opam/4.03.0/build/prettiest.0.0.1/prettiest-7-012887.err
### stderr ###
# [...]
#     ocamldep lib/prettiest.depends.ocamldep-output
#       ocamlc lib/prettiest.{cmi,cmti}
#       ocamlc lib/prettiest.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.03.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/opam/.opam/4.03.0/lib/base -I /home/opam/.opam/4.03.0/lib/base/caml -I /home/opam/.opam/4.03.0/lib/base/shadow_stdlib -I /home/opam/.opam/4.03.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.03.0/lib/sexplib/0 -no-alias-deps -I lib -o lib/prettiest.cmo -c -impl lib/prettiest.pp.ml)
# File "lib/prettiest.ml", line 68, characters 43-48:
# Error: Unbound value force
#     ocamlopt lib/prettiest.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.03.0/bin/ocamlopt.opt -w -40 -g -I /home/opam/.opam/4.03.0/lib/base -I /home/opam/.opam/4.03.0/lib/base/caml -I /home/opam/.opam/4.03.0/lib/base/shadow_stdlib -I /home/opam/.opam/4.03.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.03.0/lib/sexplib/0 -no-alias-deps -I lib -o lib/prettiest.cmx -c -impl lib/prettiest.pp.ml)
# File "lib/prettiest.ml", line 68, characters 43-48:
# Error: Unbound value force
```

**Comment by andreasfrom** [comment]
Thank you. I haven't tried this before so any help is greatly appreciated.
I don't understand the V2.0 Build failure: Something about docker.
Any idea what causes the "depfail"?

**Comment by hcarty** [comment]
I'm not sure what is causing those docker failures/crashes but I don't think it has anything to do with this PR.  All of the datakit checks which actually start have passed so just waiting on the Travis builds now!

**Comment by mseri** [comment]
That's a known issue, and independent of this PR. Should be fixed in the next few days. If Travis is successful, this is good to go

**Comment by hcarty** [comment]
Passed on everything except Mac which we are still waiting on.  According to [their site](https://www.traviscistatus.com/) the Mac builds were having issues today which should be resolved now.  There are currently ~3000 builds in the Mac backlog according to the graphs on that page.

**Pull request merged**
