### PR TITLE
Release ocaml-jupyter 1.0.0

### PR DESCRIPTION
**Pull request by akabe**
https://github.com/akabe/ocaml-jupyter/releases/tag/v1.0.0

### CODE REVIEW

**Comment by akabe** [comment]
This package depends on cppo ocamlbuild plugin, but it will be split into `cppo` and `cppo_ocamlbuild`: #10047 . Could you merge this PR after release of the new version of cppo? I need to add `"cppo_ocamlbuild" {build}` line to opam file.

**Comment by avsm** [comment]
Sure; when #10047 is merged, you will need to merge you branch with the `master` branch of opam-repository as well so that it picks up the new packages

**Comment by dbuenzli** [comment]
Ping @akabe, #10047 has been merged, please rebase.

**Comment by akabe** [comment]
@dbuenzli Thanks for notification. I rebased the current master to this branch.

**Comment by akabe** [comment]
Hmm. It seems that `ppx_deriving_yojson` doesn't support OCaml 4.05+.

**Comment by akabe** [comment]
@whitequark `ppx_deriving_yojson.3.0` cannot be built in OCaml 4.05 due to incompatible data structure definition in compiler-libs, reported at https://github.com/ocaml-ppx/ppx_deriving_yojson/issues/56. I added `ocaml-version < "4.05.0"` condition to the opam file of `ppx_deriving_yojson.3.0`.

**Comment by akabe** [comment]
@avsm @dbuenzli Thanks for waiting. I added `cppo_ocamlbuild` and rebased the current master branch. Please merge this PR.

**Comment by akabe** [comment]
@avsm @dbuenzli Ping. Please merge this PR if it has no problem.

**Comment by dbuenzli** [comment]
I'll let @avsm do this. I don't do merges.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
