### PR TITLE
cohttp: add missing js_of_ocaml constraints

### PR DESCRIPTION
**Pull request by samoht**
We missed these because we don't test depopts :-/

/cc @hhugo

### CODE REVIEW

**Comment by hhugo** [comment]
thanks

**Comment by samoht** [comment]
One of the depfail is extremely weird and I can reproduce it:

```
$ opam install cohttp.0.22.0 git-unix.1.11.0 # works
$ opam install cohttp.0.21.0 git-unix.1.11.0 # fail with unrelated error
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Logs_fmt referenced from src/git-unix/ogit/main.cmx
```

Any idea @diml or @rgrinberg? Maybe an issue with the way `jbuilder` parses meta file?

**Comment by diml** [comment]
@samoht do you mean that jbuilder is adding a findlib dependency that it shouldn't add? In any case that wouldn't cause `main.cmx` to reference the implementation of `Logs_fmt` if it doesn't use it.

**Comment by samoht** [comment]
>  In any case that wouldn't cause main.cmx to reference the implementation of Logs_fmt if it doesn't use it.

I didn't have time to investigate the issue, but yes, it seems that it was that was happening. I don't really understand how this is possible ...

**Pull request merged**
