### PR TITLE
omp 1.4.0: refresh checksum due to changed upstream tarball

### LINKED ISSUE #15281: bad checksum for ocaml-migrate-parsetree
I use opam in a docker container to install some packages but I recently got this error in my CI:

[topkg.1.0.1] downloaded from http://erratique.ch/software/topkg/releases/topkg-1.0.1.tbz
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocaml-migrate-parsetree.1.4.0: Bad checksum

Anyway I can fix that?

Here is the line in the Dockerfile:
Step 6/18 : RUN git pull && opam update && opam switch 4.07 &&   opam install dune yaml &&   opam install pfff pfff.0.39.3

I run this in the docker image FROM ocaml/opam2:alpine

### PR DESCRIPTION
**Pull request by avsm**
fixes #15281

### CODE REVIEW

**Comment by samoht** [comment]
unrelated to the checksum fix, but it's broken on 4.02:

```
#=== ERROR while compiling ocaml-migrate-parsetree.1.4.0 ======================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.02.3 | pinned(https://github.com/ocaml-ppx/ocaml-migrate-parsetree/releases/download/v1.4.0/ocaml-migrate-parsetree-v1.4.0.tbz)
# path                 ~/.opam/4.02/.opam-switch/build/ocaml-migrate-parsetree.1.4.0
# command              ~/.opam/4.02/bin/dune build -p ocaml-migrate-parsetree -j 2
# exit-code            1
# env-file             ~/.opam/log/ocaml-migrate-parsetree-23-a274f9.env
# output-file          ~/.opam/log/ocaml-migrate-parsetree-23-a274f9.out
### output ###
#       ocamlc src/.migrate_parsetree.objs/byte/migrate_parsetree__Migrate_parsetree_409_410_migrate.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.02/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.migrate_parsetree.objs/byte -I /home/opam/.opam/4.02/lib/ocaml/compiler-libs -I /home/opam/.opam/4.02/lib/ppx_derivers -I /home/opam/.opam/4.02/lib/result -no-alias-deps -open Migrate_parsetree__ -o src/.migrate_parsetree.objs/byte/migrate_parsetree__Migrate_parsetree_409_410_migrate.cmo -c -impl src/migrate_parsetree_409_410_migrate.pp.ml)
# File "src/migrate_parsetree_409_410_migrate.ml", line 22, characters 18-28:
# Error: Unbound module Option
#       ocamlc src/.migrate_parsetree.objs/byte/migrate_parsetree__Migrate_parsetree_410_409_migrate.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.02/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.migrate_parsetree.objs/byte -I /home/opam/.opam/4.02/lib/ocaml/compiler-libs -I /home/opam/.opam/4.02/lib/ppx_derivers -I /home/opam/.opam/4.02/lib/result -no-alias-deps -open Migrate_parsetree__ -o src/.migrate_parsetree.objs/byte/migrate_parsetree__Migrate_parsetree_410_409_migrate.cmo -c -impl src/migrate_parsetree_410_409_migrate.pp.ml)
# File "src/migrate_parsetree_410_409_migrate.ml", line 28, characters 17-27:
# Error: Unbound module Option
```

**Comment by samoht** [comment]
From https://github.com/ocaml-ppx/ocaml-migrate-parsetree/releases it seem that:

omd 1.4.0 works only with 4.08, 4.09 and 4.10
omd 1.4.1 restores compat with older compiler

So I'll add bounds for >= 4.08.

**Comment by samoht** [comment]
Merging this quickly to unlock other CIs -- the revdeps errors are unrelated.

**Comment by hannesm** [comment]
FWIW here's a diff of the old tarball (231fbdc205187b3ee266b535d9cfe44b599067b2f6e97883c782ea7bb577d3b8) and the new one.

[omp-140.diff.txt](https://github.com/ocaml/opam-repository/files/3852017/omp-140.diff.txt)

**Comment by samoht** [comment]
See #15300 for a new tentative fix. I completly forgot that  the previous archive would be available in the cache, so I followed @hannesm's advice and modified the url instead of picking a new archive.

@diml this will need some more investigation from your side to understand which archive you really want to release for 1.4.0 (the previous one or the new one :p)

**Comment by avsm** [comment]
I think I know what happened here -- dune-release will overwrite an existing tag if the CHANGES file hasn't been updated. The same happened for `uri` for me recently. That accounts for the changes in the tarballs also (its the same as the diff from 1.4.0 to 1.4.1).  Pointing to the cache until @diml is available to look into the upstream fix is the right solution indeed.

**Comment by ygrek** [comment]
I don't agree with the fix, 1.4.0 original compiled find on 4.07 for example. 1.4.0 with new checksum does not - I believe it is some commit between 1.4.0 tag and 1.4.1 tag. I think opam repo should revert to previous archive and previous checksum (that's what I did in local opam mirror).

**Comment by ygrek** [comment]
> From https://github.com/ocaml-ppx/ocaml-migrate-parsetree/releases it seem that:
> omd 1.4.0 works only with 4.08, 4.09 and 4.10

that page was modified yesterday, 1.4.0 was released to opam in
`c4941bfcca 2019-07-04 Jeremie Dimino [new release] ocaml-migrate-parsetree (1.4.0)`
and since then until yesteday it built fine with 4.07

**Comment by diml** [comment]
Just catching up on emails. I indeed overwrote the 1.4.0 release of omp by accident (cf https://github.com/ocaml/opam-repository/pull/15280#issuecomment-554959337).

I propose to restore the 1.4.0 release of omp by restoring the original archive. Let me know if that's a bad idea for some reason.

**Comment by mseri** [comment]
@diml that's a good idea, in the meantime we had pointed the opam file to the opam cache sources of the old tarball

**Comment by samoht** [comment]
@ygrek 
> I don't agree with the fix, 1.4.0 original compiled find on 4.07 for example. 1.4.0 with new checksum does not - I believe it is some commit between 1.4.0 tag and 1.4.1 tag. I think opam repo should revert to previous archive and previous checksum (that's what I did in local opam mirror).

For the record, I agree, it was a mistake that I have fixed a few hours later: https://github.com/ocaml/opam-repository/pull/15300

**Pull request merged**
