### PR TITLE
charrua-unix.0.{5,6} requires cstruct < 3.0.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Detected with [check.ocamllabs.io](http://check.ocamllabs.io)

### CODE REVIEW

**Comment by mseri** [comment]
The failures are resolutions timeout. Feel free to merge

**Comment by mseri** [comment]
The failures are resolutions timeout. Are you sure about the bound `cstruct-unix=0` here?

**Comment by kit-ty-kate** [comment]
yeah, the package `cstruct-unix.0` is just a metapackage that constrain `cstruct < 3.0.0` and requires `base-unix`

**Comment by kit-ty-kate** [comment]
those are old versions anyway. They will appear if something is really wrong in the next run on [check.ocamllabs.io](http://check.ocamllabs.io)

**Pull request merged**
