### PR TITLE
remove bencode-rpc

### PR DESCRIPTION
**Pull request by c-cube**
this has always been a toy project, in retrospect, and there are many more serious alternatives these days.

### CODE REVIEW

**Comment by mseri** [comment]
Does not break dependencies, I would be happy to merge. Will https://opam.ocaml.org/packages/bencode_rpc be automatically removed if we merge or we need to do something for that?

**Comment by c-cube** [comment]
I have no idea, sorry.

**Comment by kit-ty-kate** [comment]
Removing packages is not something opam-repository maintainers agree on.
For now the consensus seems to be to switch the packages to "remove" to `available: false` instead of removing them from the repository.

**Comment by c-cube** [comment]
Why not? I'm pretty sure no one depends on it, and it just pollutes the list of results for `rpc`…

**Comment by kit-ty-kate** [comment]
I don't know, I personally don't care but other people from @ocaml/opam-repository might have arguments against it.

**Comment by samoht** [comment]
If that's a toy project that no one is depending on, I am fine to remove it :-)

**Comment by hcarty** [comment]
One downside that will hopefully go away as opam2 spreads is that an opam1 user's switch can end up in a broken state if a definition for an installed package disappears from the repository. opam2 does not have the same problem as far as I understand.

**Pull request merged**
