### PR TITLE
Package service-registry.0.1.0

### PR DESCRIPTION
**Pull request by XnuKernPoll**
### `service-registry.0.1.0`

Short
A simple service registry 
Long
A modular and extensible service registry using Irmin for persistence

---
* Homepage: https://github.com/XnuKernPoll/service-registry
* Source repo: https://github.com/XnuKernPoll/service-registry.git
* Bug tracker: https://github.com/XnuKernPoll/service-registry/issues

---
### opam-lint failures
- **WARNING** 99 should not contain 'name' or 'version' fields

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by mseri** [comment]
I am tempted to merge this. @avsm is the following error on ocaml 4.03 something known or with a known fix?

```
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
[ERROR] Sorry, resolution of the request timed out.
        Try to specify a simpler request, use a different solver, or increase the allowed time by setting OPAMSOLVERTIMEOUT to a bigger value (currently, it is set to 60.0 seconds).
Command failed: opam list --readonly --external  --resolve=service-registry.0.1.0 returned 60
```

**Comment by jpdeplaix** [comment]
There is an issue appearing with OCaml 4.02 only (see travis for more details):
```
#=== ERROR while installing service-registry.0.1.0 ============================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p service-registry -j 4
# path         /home/travis/.opam/system/build/service-registry.0.1.0
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/service-registry.0.1.0/service-registry-7085-8c37bd.env
# stdout-file  /home/travis/.opam/system/build/service-registry.0.1.0/service-registry-7085-8c37bd.out
# stderr-file  /home/travis/.opam/system/build/service-registry.0.1.0/service-registry-7085-8c37bd.err
### stderr ###
# Error: External library "irmin-unix" not found.
# -> required by "lib/jbuild (context default)"
# Hint: try: jbuilder external-lib-deps --missing -p service-registry @install
```
Could you fix this and I'll be happy to merge it ?

**Comment by jpdeplaix** [comment]
ping @XnuKernPoll

**Comment by yomimono** [comment]
I suspect that `irmin-unix`'s version needs to be constrained, as it has undergone breaking changes at least once.  

@XnuKernPoll we will likely close this PR soon unless you push new changes to the branch or let us know what the status of this package is -- you will be welcome to resubmit at any time with additional changes, of course.

**Comment by kit-ty-kate** [comment]
Feel free to reopen it later.

**Pull request closed without merging**
