### PR TITLE
[new release] Package tldr.0.3.0

### PR DESCRIPTION
**Pull request by RosalesJ**
### `tldr.0.3.0`
An ocaml tldr client.

#### v0.3.0 - 5/24/2020
--------------------
- Change version numbers to be semantic versioning compliant
- Changed to using `cmdliner` for command line parsing
- Cut down on some large dependencies
- Generate manpage on install

---
* Homepage: https://github.com/RosalesJ/tldr-ocaml/
* Source repo: git+https://github.com/RosalesJ/tldr-ocaml.git
* Bug tracker: https://github.com/RosalesJ/tldr-ocaml/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by RosalesJ** [comment]
Ocaml `4.03` failed because of `angstrom`. It looks like [angstrom >= 0.14.0](https://opam.ocaml.org/packages/angstrom/angstrom.0.14.1/) specifies `ocaml >= 4.04`, I'm using `angstrom 0.14.0` features so I should specify that anyways. Will that result in the 4.03 tests not running?

**Comment by kit-ty-kate** [comment]
Could you return the fix upstream? Dune is not compatible with the `{build}` tag (see https://github.com/ocaml/dune/issues/2147) and your `dune-project` file says this package requires at least dune 1.2

**Comment by kit-ty-kate** [comment]
Otherwise it's good to go now. Thanks!

**Comment by RosalesJ** [comment]
Thanks for the info, I'll get that changed upstream.

**Pull request merged**
