### PR TITLE
Update bitstring and ppx_bitstring to 4.1.0

### PR DESCRIPTION
**Pull request by xguerin**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The tag seems to have been modified since:
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - bitstring.4.1.0:
            https://github.com/xguerin/bitstring/archive/v4.1.0.tar.gz (Bad checksum, expected md5=5ef783b736837f6f3d0ef0af8eef6582)
```

**Comment by xguerin** [comment]
Thanks, that should be addressed now.

**Comment by kit-ty-kate** [comment]
Thanks! I spotted an issue: `ppxlib` shouldn't be tagged as a build dependency as it is used in the runtime and having it unsync would result in a failure. Could you return the fix upstream?

**Comment by xguerin** [comment]
Sure, will do. Thanks !

**Pull request merged**
