### PR TITLE
BAP 1.6 Release

### PR DESCRIPTION
**Pull request by gitoleg**
Release notes
=====

### Features

- PR#893  adds integration with ida 7
- PR#892  implements helper functions for creating and manipulating partitions
- PR#906  makes dead code elimination less conservative
- PR#914  preserves brancher information in the BIL code of an instruction
- PR#820  Jane Street 0.11.x library compatibility + minor fixes
- PR#922  few x86 enhancements
- PR#923  SSE XMM0 ABI
- PR#933  enables bap-elf
- PR#934  adds the compiler option to byteweight
- PR#932  enables memory sharing between instructions
- PR#938  removed upper bound for llvm version, compatibility with LLVM 8.0
- PR#926  enables functions with multiple entry

### Bug fixes

- PR#907  fixes the free-vars-by-dominators computation algorithm
- PR#915  fixed building on travis
- PR#920  fix the i64 import error
- PR#927  fixes ADT printer
- PR#939  fixes the order of arguments in the callsites plugin
- PR#937  fixes TOCTOU bug in bap log
- PR#941  fixes a dependency bug in primus lisp docs

### CODE REVIEW

**Comment by ivg** [comment]
# Summary of failures

* bap-fsi-benchmark.1.6.0, conf-ida.0.2, bap-ida-python.1.6.0, bap-ida.1.6.0 - absence of IDA Pro, an expected failure. 
* bap-std.1.6.0 - curl error 35 while downloading a package from janestreet.com (restart queued)
* bap-term-mapper.1.6.0, again curl 35, but now from github.com (restart queued)
* bap-veri.0.2.3 -  [some CI failure][1]

[1]: https://ci.ocamllabs.io/log/saved/docker-build-bffc3c90eeb36f3e35fbff604b5b2f3e/481ababb67be9cfc5da37e962116000d1f0f0040

**Comment by ivg** [comment]
After I've hit the rebuild button the errors turned into the [CI failures][1]. 

[1]: https://ci.ocamllabs.io/log/saved/docker-build-a773fa8f57cc49734874092f32a26935/c5c3edffffc0f267d651f7767f287febbf08570b

**Comment by gitoleg** [comment]
And considering `camelus` complain:
>  error 52: Package is needlessly flagged "light-uninstall", since it has no remove instructions

it looks like it's a manifestation of the issue: https://github.com/ocaml/opam/issues/3625,  since  `conf-bap-llvm` and `conf-ida` don't use `light-uninstall` flag at all

**Comment by gitoleg** [comment]
Also, you can take a look at our own CI: https://travis-ci.org/BinaryAnalysisPlatform/bap/builds/515876134
that builds bap against many compilers, and many runs tests as well

**Comment by mseri** [comment]
Please ignore the camelus lint tests. And thanks for triaging the issues

**Comment by mseri** [comment]
That’s a massive release, some timeouts are not surprising. It seems all fine

**Pull request merged**
