### PR TITLE
Ocamlbuild revdep fixes

### PR DESCRIPTION
**Pull request by gasche**
metadata update for the first N=6 packages in ocamlbuild reverse dependencies that require an ocaml version bound, mostly because they need `-unsafe-string`.

### CODE REVIEW

**Comment by gasche** [comment]
Re. camelus: I won't fix all opam files (they were missing fields before, it's just fine), but I will look at the argon2 issues.

**Comment by hannesm** [comment]
@gasche argon2 issue is your usage of `&&`, which should be `&` afaict

**Comment by gasche** [comment]
Indeed! I just fixed and rebased, thanks @hannesm.

**Comment by gasche** [comment]
I checked the Debian failures in the CI, they come from GTK/cairo packaging issues that are beyond my control. Merging.

**Pull request merged**
