### PR TITLE
kinetic-client.0.0.9

### PR DESCRIPTION
**Pull request by toolslive**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
`cmdliner` is likely to be a missing dependency:
```
#=== ERROR while installing kinetic-client.0.0.9 ==============================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              make
# path                 /home/opam/.opam/4.05.0/build/kinetic-client.0.0.9
# compiler             4.05.0
# exit-code            2
# env-file             /home/opam/.opam/4.05.0/build/kinetic-client.0.0.9/kinetic-client-21-08e3fd.env
# stdout-file          /home/opam/.opam/4.05.0/build/kinetic-client.0.0.9/kinetic-client-21-08e3fd.out
# stderr-file          /home/opam/.opam/4.05.0/build/kinetic-client.0.0.9/kinetic-client-21-08e3fd.err
### stdout ###
# piqi of-proto src/kinetic.proto -o src/kinetic.proto.piqi
# piqic-ocaml --embed-piqi -C src src/kinetic.proto.piqi
# ocamlbuild -use-ocamlfind test_it.native
# ocamlfind ocamldep -package ppx_deriving.std -package cmdliner -package cryptokit -package lwt.unix -package lwt_log -package lwt_ssl -package lwt -modules examples/test_it.ml > examples/test_it.ml.depends
# + ocamlfind ocamldep -package ppx_deriving.std -package cmdliner -package cryptokit -package lwt.unix -package lwt_log -package lwt_ssl -package lwt -modules examples/test_it.ml > examples/test_it.ml.depends
# ocamlfind: Package `cmdliner' not found
# Command exited with code 2.
# Makefile:13: recipe for target 'example' failed
### stderr ###
# make: *** [example] Error 10
```

**Comment by kit-ty-kate** [comment]
Same with `lwt_ssl`:
```
#=== ERROR while installing kinetic-client.0.0.9 ==============================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              make
# path                 /home/opam/.opam/4.05.0/build/kinetic-client.0.0.9
# compiler             4.05.0
# exit-code            2
# env-file             /home/opam/.opam/4.05.0/build/kinetic-client.0.0.9/kinetic-client-21-81614a.env
# stdout-file          /home/opam/.opam/4.05.0/build/kinetic-client.0.0.9/kinetic-client-21-81614a.out
# stderr-file          /home/opam/.opam/4.05.0/build/kinetic-client.0.0.9/kinetic-client-21-81614a.err
### stdout ###
# piqi of-proto src/kinetic.proto -o src/kinetic.proto.piqi
# piqic-ocaml --embed-piqi -C src src/kinetic.proto.piqi
# ocamlbuild -use-ocamlfind test_it.native
# ocamlfind ocamldep -package ppx_deriving.std -package cmdliner -package cryptokit -package lwt.unix -package lwt_log -package lwt_ssl -package lwt -modules examples/test_it.ml > examples/test_it.ml.depends
# + ocamlfind ocamldep -package ppx_deriving.std -package cmdliner -package cryptokit -package lwt.unix -package lwt_log -package lwt_ssl -package lwt -modules examples/test_it.ml > examples/test_it.ml.depends
# ocamlfind: Package `lwt_ssl' not found
# Command exited with code 2.
# Makefile:13: recipe for target 'example' failed
### stderr ###
# make: *** [example] Error 10
```

**Comment by toolslive** [comment]
Thx. I'm following the output of the checks too. (and iterating)

**Comment by kit-ty-kate** [comment]
Seems good so far. I think it would be good to move the depexts into their own package `conf-protobuf-compiler`. It would remove redundancy with the `riakc` and `riak-pb` packages.

**Comment by kit-ty-kate** [comment]
Those are known unrelated failures. I'll go ahead and merge this. If you are bored some day please consider to create this `conf-protobuf-compiler`. I'll be happy to merge such improvement.

Thanks.

**Pull request merged**
