### PR TITLE
opam packages for OCaml 4.14.1

### PR DESCRIPTION
**Pull request by Octachron**
This PR adds the package for tomorrow release of OCaml 4.14.:

- ocaml-base-compiler.4.14.1
- ocaml-system.4.14.1
- ocaml-variants.4.14.1+options
- ocaml-src.4.14.1

and the `ocaml.4.14.2` meta-package.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I think we also need to move the `ocaml-variants.4.14.1+trunk` package to `ocaml-variants.4.14.2+trunk`

**Comment by kit-ty-kate** [comment]
ah, apparently it was also missing from the 5.0.0 release #22723

**Comment by Octachron** [comment]
The OCaml version should be changed in the `synopsis` and `depends` fields.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
