### PR TITLE
Add typerex-lldb.1.1

### PR DESCRIPTION
**Pull request by lefessan**
Compatibility with 4.03.0

### CODE REVIEW

**Comment by yallop** [comment]
> Compatibility with 4.03.0

Is the version constraint correct?

```
available: [ocaml-version >= "4.01.0" & ocaml-version < "4.03" ]
```

**Comment by lefessan** [comment]
@yallop Thanks !

**Comment by dsheets** [comment]
depext is unavailable on Ubuntu 12.04 so merging. @lefessan it would be good to add the `ubuntu` and `osx` depexts to `conf-lldb.3.5`.

**Comment by lefessan** [comment]
@dsheets Thanks for merging! For depexts, unfortunately, I have no Ubuntu or OSX system at hands.

**Pull request merged**
