### PR TITLE
Package blake3.0.3

### PR DESCRIPTION
**Pull request by camlspotter**
### `blake3.0.3`
Blake3 cryptography

---
* Homepage: https://github.com/camlspotter/ocaml-blake3
* Source repo: git+https://github.com/camlspotter/ocaml-blake3.git
* Bug tracker: https://github.com/camlspotter/ocaml-blake3/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by camlspotter** [comment]
The original is at https://github.com/proof-ninja/ocaml-blake3 but my PR there seems not be merged for long.  Diverged.

**Comment by camlspotter** [comment]
CI fails for ocaml 5 but the opam files excludes it.  It seems to fail due to the disk full.

**Comment by mseri** [comment]
I cannot merge this without the approval of the library maintainers. Ping @kazkob or @yoshihiro503 is it possible for you to get in touch with @camlspotter and agree on how to proceed?

**Comment by camlspotter** [comment]
@mseri yeah, I understand it.  That's why I wrote "The original is at https://github.com/proof-ninja/ocaml-blake3 but my PR there seems not be merged for long. Diverged."

@kazkob and @yoshihiro503 are my team mates and it is easy for us to agree how to proceed.

**Comment by mseri** [comment]
Thanks for pointing it out and taking action on this!

**Comment by yoshihiro503** [comment]
@camlspotter, thank you  for taking over this project.  I agree with having you take this project forward.

**Comment by mseri** [comment]
Should we change the repository to this fork or will @camlspotter get access to the original one?

**Comment by yoshihiro503** [comment]
Ether way is fine.

**Comment by camlspotter** [comment]
Please merge this release.  I will maintain my fork.

**Pull request merged**
