### PR TITLE
hello_core.0.1 - via opam-publish

### PR DESCRIPTION
**Pull request by yminsky**
A hello-world for Core and Aysnc

A few simple examples demonstrating the use of Core and Async, along
with jbuilder. Includes three simple projects, two of which are simple
client/server applications.

---
* Homepage: https://bitbucket.com/yminsky/core-hello-world
* Source repo: https://bitbucket.com/yminsky/core-hello-world
* Bug tracker: https://bitbucket.org/yminsky/core-hello-world/issues

---

Pull-request generated by opam-publish v0.3.4

### CODE REVIEW

**Comment by yminsky** [comment]
Sorry, I wasn't thinking: it's too early to submit this. This only makes sense once the 0.9 release of the Jane Street packages hits.

**Comment by diml** [comment]
@yminsky since jbuilder 1.0+beta7, you can simplify the `build: ...` line to:

```
build: [["jbuilder" "build" "-p" name "-j" jobs]]
```

**Comment by avsm** [comment]
this just needs an Async v0.9 update now that #9132 is merged cc @diml

**Comment by avsm** [comment]
@yminsky if you merge against the master branch of opam-repository and push, this should now build. See @diml's comment above about simplifying the opam file with latest jbuilder.

**Comment by yminsky** [comment]
This is a stupid question, but how do I merge against the master branch? I'm a bit of a git noob, and don't see obvious instructions for cloning and merging the PR.

**Comment by avsm** [comment]
@yminsky you need to manually merge, which opam-publish doesn't support yet.  So you probably need to

```
git clone git@github.com:yminsky/opam-repository -b opam-publish/hello_core.0.1
cd opam-repository
git remote add upstream git://github.com/ocaml/opam-repository
git pull upstream master
git push origin opam-publish/hello_core.0.1
```

so easy you wonder why you didn't git it all by yourself, huh :-)

**Comment by avsm** [comment]
It's probably actually easier to resubmit this rather than keep a very old PR around, so I'll close this for now.

**Pull request closed without merging**
