### PR TITLE
Update systemverilog repo information

### PR DESCRIPTION
**Pull request by xguerin**

### CODE REVIEW

**Comment by mseri** [comment]
Is it possible to upload the old archive as a github release artifact instead of changing the checksums?

**Comment by xguerin** [comment]
Sadly no. I did not anticipate it to be a problem and closed the original repos. I will keep that in mind for next time.

**Comment by mseri** [comment]
We have the artefacts available in the opam cache:

https://opam.ocaml.org/cache/md5/c0/c088ec4d1a8fddd0d4eb14d797beaaac <- systemverilog.0.0.1
https://opam.ocaml.org/cache/md5/a2/a24fe433fd21a1ff4764caf10b013b65 <- systemverilog.0.0.2

If you don't mind, can you download those and replace the artefacts so that we can keep the checksum? Otherwise I need to diff their contents before merging, and I will not be able to do it before a couple of days

**Comment by xguerin** [comment]
Perfect, thanks. I'll take care of this right away.

**Comment by mseri** [comment]
Thank you very much. I'll wait for the CI, and if all goes well I'll merge

**Comment by mseri** [comment]
Looks good, thanks

**Pull request merged**
