### PR TITLE
[new release] x509 (0.13.0)

### PR DESCRIPTION
**Pull request by hannesm**
Public Key Infrastructure (RFC 5280, PKCS) purely in OCaml

- Project page: <a href="https://github.com/mirleft/ocaml-x509">https://github.com/mirleft/ocaml-x509</a>
- Documentation: <a href="https://mirleft.github.io/ocaml-x509/doc">https://mirleft.github.io/ocaml-x509/doc</a>

##### CHANGES:

* FEATURE support for RFC 5915 "BEGIN EC PRIVATE KEY" pem encoded private keys
  (mirleft/ocaml-x509#147 @hannesm, requested by @ulrikstrid)
* BREAKING remove EC_pub _ from Public_key.t and EC _ from Certificate.key_type
  (mirleft/ocaml-x509#147 by @hannesm)
* BREAKING move Certificate.key_type to Key_type.t (mirleft/ocaml-x509#147 @hannesm)
* FEATURE some private key utilities (of_cstruct, generate, sign), and
  Public_key.verify (#report mirleft/ocaml-x509#146, fix mirleft/ocaml-x509#147 @hannesm)
* BREAKING rename hash_whitelist to allowed_hashes (mirleft/ocaml-x509#147 @hannesm)
* BREAKING provide Key_type.signature_scheme and use across the API
  (mirleft/ocaml-x509#147 @hannesm)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
`ca-certs` seems to be broken by this release:
```
#=== ERROR while compiling ca-certs.0.2.0 =====================================#
# context              2.0.8 | linux/x86_64 | ocaml-base-compiler.4.12.0 | file:///src
# path                 ~/.opam/4.12/.opam-switch/build/ca-certs.0.2.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ca-certs -j 31 @install
# exit-code            1
# env-file             ~/.opam/log/ca-certs-15-835ba5.env
# output-file          ~/.opam/log/ca-certs-15-835ba5.out
### output ###
#       ocamlc lib/.ca_certs.objs/byte/ca_certs.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.12/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.ca_certs.objs/byte -I /home/opam/.opam/4.12/lib/asn1-combinators -I /home/opam/.opam/4.12/lib/astring -I /home/opam/.opam/4.12/lib/base/caml -I /home/opam/.opam/4.12/lib/base64 -I /home/opam/.opam/4.12/lib/bigarray-compat -I /home/opam/.opam/4.12/lib/bos -I /home/opam/.opam/4.12/lib/bytes -I /home/opam/.opam/4.12/lib/cstruct -I /home/opam/.opam/4.12/lib/domain-name -I /home/opam/.opam/4.12/lib/eqaf -I /home/opam/.opam/4.12/lib/eqaf/bigstring -I /home/opam/.opam/4.12/lib/eqaf/cstruct -I /home/opam/.opam/4.12/lib/fmt -I /home/opam/.opam/4.12/lib/fpath -I /home/opam/.opam/4.12/lib/gmap -I /home/opam/.opam/4.12/lib/logs -I /home/opam/.opam/4.12/lib/mirage-crypto -I /home/opam/.opam/4.12/lib/mirage-crypto-ec -I /home/opam/.opam/4.12/lib/mirage-crypto-pk -I /home/opam/.opam/4.12/lib/mirage-crypto-rng -I /home/opam/.opam/4.12/lib/parsexp -I /home/opam/.opam/4.12/lib/pbkdf -I /home/opam/.opam/4.12/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.12/lib/ptime -I /home/opam/.opam/4.12/lib/ptime/os -I /home/opam/.opam/4.12/lib/result -I /home/opam/.opam/4.12/lib/rresult -I /home/opam/.opam/4.12/lib/seq -I /home/opam/.opam/4.12/lib/sexplib -I /home/opam/.opam/4.12/lib/sexplib0 -I /home/opam/.opam/4.12/lib/stdlib-shims -I /home/opam/.opam/4.12/lib/x509 -I /home/opam/.opam/4.12/lib/zarith -intf-suffix .ml -no-alias-deps -o lib/.ca_certs.objs/byte/ca_certs.cmo -c -impl lib/ca_certs.ml)
# File "lib/ca_certs.ml", line 122, characters 54-68:
# 122 |   | _ -> Ok (X509.Authenticator.chain_of_trust ?crls ?hash_whitelist ~time cas)
#                                                             ^^^^^^^^^^^^^^
# Error: The function applied to this argument has type
#          ?allowed_hashes:Mirage_crypto.Hash.hash list ->
#          host:[ `host ] Domain_name.t option ->
#          X509.Certificate.t list ->
#          ((X509.Certificate.t list * X509.Certificate.t) option,
#           X509.Validation.validation_error)
#          result
# This argument cannot be applied with label ?hash_whitelist
#     ocamlopt lib/.ca_certs.objs/native/ca_certs.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.12/bin/ocamlopt.opt -w -40 -g -I lib/.ca_certs.objs/byte -I lib/.ca_certs.objs/native -I /home/opam/.opam/4.12/lib/asn1-combinators -I /home/opam/.opam/4.12/lib/astring -I /home/opam/.opam/4.12/lib/base/caml -I /home/opam/.opam/4.12/lib/base64 -I /home/opam/.opam/4.12/lib/bigarray-compat -I /home/opam/.opam/4.12/lib/bos -I /home/opam/.opam/4.12/lib/bytes -I /home/opam/.opam/4.12/lib/cstruct -I /home/opam/.opam/4.12/lib/domain-name -I /home/opam/.opam/4.12/lib/eqaf -I /home/opam/.opam/4.12/lib/eqaf/bigstring -I /home/opam/.opam/4.12/lib/eqaf/cstruct -I /home/opam/.opam/4.12/lib/fmt -I /home/opam/.opam/4.12/lib/fpath -I /home/opam/.opam/4.12/lib/gmap -I /home/opam/.opam/4.12/lib/logs -I /home/opam/.opam/4.12/lib/mirage-crypto -I /home/opam/.opam/4.12/lib/mirage-crypto-ec -I /home/opam/.opam/4.12/lib/mirage-crypto-pk -I /home/opam/.opam/4.12/lib/mirage-crypto-rng -I /home/opam/.opam/4.12/lib/parsexp -I /home/opam/.opam/4.12/lib/pbkdf -I /home/opam/.opam/4.12/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.12/lib/ptime -I /home/opam/.opam/4.12/lib/ptime/os -I /home/opam/.opam/4.12/lib/result -I /home/opam/.opam/4.12/lib/rresult -I /home/opam/.opam/4.12/lib/seq -I /home/opam/.opam/4.12/lib/sexplib -I /home/opam/.opam/4.12/lib/sexplib0 -I /home/opam/.opam/4.12/lib/stdlib-shims -I /home/opam/.opam/4.12/lib/x509 -I /home/opam/.opam/4.12/lib/zarith -intf-suffix .ml -no-alias-deps -o lib/.ca_certs.objs/native/ca_certs.cmx -c -impl lib/ca_certs.ml)
# File "lib/ca_certs.ml", line 122, characters 54-68:
# 122 |   | _ -> Ok (X509.Authenticator.chain_of_trust ?crls ?hash_whitelist ~time cas)
#                                                             ^^^^^^^^^^^^^^
# Error: The function applied to this argument has type
#          ?allowed_hashes:Mirage_crypto.Hash.hash list ->
#          host:[ `host ] Domain_name.t option ->
#          X509.Certificate.t list ->
#          ((X509.Certificate.t list * X509.Certificate.t) option,
#           X509.Validation.validation_error)
#          result
# This argument cannot be applied with label ?hash_whitelist
```
Is that expected?

**Comment by hannesm** [comment]
thanks @kit-ty-kate, give me 5 minutes. I'll (a) rename to 0.13.0 (b) constrain ca-certs.

yes, indeed the `hash_whitelist` is now `allowed_hashes` (to remove discriminating words in API).

**Comment by hannesm** [comment]
not sure what to do about (in https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/ce58e594265f3fcc00f6053a9c016a13c6c92e6f/variant/compilers,4.08,ca-certs-nss.3.59,tests):
```
time="2021-04-22T12:16:17+02:00" level=warning msg="exit status 1"
time="2021-04-22T12:16:17+02:00" level=error msg="container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting \"/etc/resolv.conf\" to rootfs at \"/var/cache/obuilder/result-tmp/aec4a87228a7bbc556a5decef9a5fac5fd2030d0f6d81cf493acc31291b7ca61/rootfs/etc/resolv.conf\" caused: no such file or directory"
"/bin/bash" "-c" "opam depext -yu" failed with exit status 1
2021-04-22 10:17.10: Job failed: Failed: Build failed
```

**Comment by hannesm** [comment]
remaining issues are "the usual broken packages" (KaSim / azure-cosmos-db / kappa-server / quests), and various timeouts ("cancelled"). imho good to merge (and would unblock some other releases I have in the pipeline). thanks.

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by hannesm** [comment]
thanks @kit-ty-kate

**Pull request merged**
