### PR TITLE
Manually update md5 checksum for mirage-build.sh

### PR DESCRIPTION
**Pull request by adamsteen**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by kit-ty-kate** [comment]
I wonder how it was broken in the first place though :/ cc @rjbou @AltGr

**Comment by rjbou** [comment]
Indeed, camelus should have raised a `mismatching extra-files` error on the original PR #12569.

**Comment by rjbou** [comment]
My mistake, it's camelus 2.0 that check for extra-files not camelus 1.2.

**Pull request merged**
