### PR TITLE
zarith-freestanding.1.6 + zarith-xen.1.6

### PR DESCRIPTION
**Pull request by hannesm**
this adds the two above mentioned packages.  in order to build zarith-freestanding (at least on FreeBSD), gmp-freestanding and gmp-xen needs to pass `--with-pic` during configuration phase (which enables `-fPIC`).

//cc @mato

### CODE REVIEW

**Comment by mato** [comment]
@hannesm Didn't you want to upgrade `gmp` to `6.1.2` also or is that forthcoming in a separate PR? If that's the case, perhaps do the -fPIC change there only and depend on the newer gmp in the newer zarith?

(Possibly I'm being too paranoid here, but I'm not 100% sure about any side-effects of the -fPIC change and don't have the bandwidth to test right now)

**Comment by hannesm** [comment]
@mato well, gmp.6.1.2 turns out to need more C symbols -- which also means modifications to ocaml-freestanding (already merged) and the ocaml-xen stuff.

I did a full end-to-end test using ukvm and FreeBSD with the mirage-skeleton `static_website_tls` unikernel, and gmp-freestanding.6.0.0 (and zarith-freestanding.1.6) -- and this works fine!

**Comment by mato** [comment]
@hannesm I guess my point is that this _changes_ the build of `gmp` subtly, without changing the version number. In the interests of not accidentally breaking something I'd prefer that the change include a new version of `gmp`. What you could do is do this for `freestanding` only and keep `xen` on `6.0.0`, leaving someone else to upgrade that.

/cc @avsm @yomimono for opinions

**Comment by hannesm** [comment]
so, are there any opinions how to move forward here?  travis passes fine!  has anyone a clue why opam1 and opam2 behave differently in respect to solo5 and depext?

**Comment by avsm** [comment]
@hannesm @mato - we could enable pic on a minor version bump of the package (add "a" or something to the suffix to denote it rather than changing the existing package). Then version constraints will let zarith-freestanding pick up the pic versions, but also address @mato's concern about changing an existing library without a version bump.

**Comment by hannesm** [comment]
@avsm sounds like a good idea.  I used `6.0.0-1` (which is AFAICT what Debian also does), and depend on `> 6.0.0` in the `zarith-*.1.6` packages.

**Comment by hannesm** [comment]
CI failures indicate that ocamlfind is not available (502 - bad gateway)...

**Comment by yallop** [comment]
I've cancelled the Travis build; we can restart it once findlib/ocamlfind is available again (#10383).

**Comment by hannesm** [comment]
I rebased upon current master, and travis is happy again! :) (the MacOSX build is rather pointless anyways since neither of these packages will work there)

**Comment by hannesm** [comment]
failures for debian unstable & testing are due to a fresh gcc, which are fixed upstream in solo5 (https://github.com/Solo5/solo5/commit/48f8c4f732f72b1fc12912cf3779623973342de9)

**Comment by hannesm** [comment]
ping. CI seems to be happy, apart from the above mentioned problem with released solo5 and gcc7.

**Comment by mato** [comment]
I just ran a manual smoketest with `static_website_tls` using the released version of solo5-kernel-ukvm (`v0.2.2`) and the branch for this PR and all seems fine, so looks good to me.

Unfortunately there's not a lot we can easily do right now about the gcc7 failures, is that a problem for merging this?

**Comment by hannesm** [comment]
@mato thx!  what we could do is to include a patch into opam-repository which removes `-Werror` from the solo5 build system..  but I'm not sure whether it is worth it, given that there's a new solo5 release on the horizon.

**Comment by mato** [comment]
@hannesm Well, "on the horizon" is more like "some time this month", so patching `v0.2.2` in opam to remove `-Werror` is a good idea. I can look into that if you like.

**Comment by hannesm** [comment]
@mato done in 59073a426ac019d82f4b61bbc0d8dcac9211ca6d

**Comment by mato** [comment]
@hannesm Thanks. Nit: You should probably call those packages `0.2.2-1` in opam, since we just had that discussion in this PR :-)

**Comment by hannesm** [comment]
@mato thx, done (0.2.2-1) in b0ae925348082357a01bae26470b61f4bf03d733

**Comment by mato** [comment]
@hannesm Thanks, tested, LGTM!

**Comment by hannesm** [comment]
according to https://packages.debian.org/search?searchon=contents&keywords=asm%2Fmsr-index.h&mode=exactfilename&suite=unstable&arch=any Debian unstable/testing/experimental provides the file `asm/msr-index.h` from linux-libc-dev and linux-headers-XX-common.  I've no clue how to express this in opam atm (and am done with this PR here, take it or leave it).

**Comment by cfcs** [comment]
It looks like that header is [not shipped in Debian](https://www.mail-archive.com/debian-bugs-rc@lists.debian.org/msg471809.html) (anymore)?
FWIW I do have this:
```
$ dpkg -S msr.h
linux-libc-dev:amd64: /usr/include/x86_64-linux-gnu/asm/msr.h
```

**Comment by mato** [comment]
@cfcs `asm/msr-index.h` does indeed seem to be gone in Debian testing/unstable, at least it's not in the `linux-libc-dev` package. In fact, the entire `/usr/include/asm/` symlink is also gone. ISTR there was an email about transitioning how the kernel headers are packaged, but I can't find it now :-(

Will keep looking to see if I can find a solution. Up to the opam-repository maintainers to decide if this can go in with the new distros (Debian testing, unstable, Fedora 25) failing.

**Comment by mato** [comment]
@hannesm After some discussion, it's unclear what the situation with `#include <asm/msr-index.h>` from userspace is, but given that file is included solely to get the value of a single constant, and that code has since been fixed on ukvm `master`, the best plan right now would be to add the attached small patch to this PR.
[ukvm-msr-index.h.patch.txt](https://github.com/ocaml/opam-repository/files/1355938/ukvm-msr-index.h.patch.txt)

**Comment by hannesm** [comment]
@mato thanks, added in 36a6c1a2eb59c751aea1a7eda29b686de27e7ac4

**Comment by hannesm** [comment]
this is finally green again and ready for merge.  to sum up the changes:
- new packages `zarith-freestanding.1.6` and `zarith-xen.1.6` (which follow along `zarith.1.6`)
- `gmp-xen.6.0.0`: fixed opam file (added `authors`) and dependency on `conf-m4`
- `gmp-xen.6.0.0-1`: new package, which is `gmp-xen.6.0.0` copied, the only difference is `--with-pic` being passed to configure (required by newer `zarith`)
- `gmp-freestanding.6.0.0`: added dependency on `conf-m4`
- `gmp-freestanding.6.0.0-1`: new package, same as `gmp-freestanding.6.0.0`, but configure with `--with-pic`
- `solo5-kernel-ukvm.0.2.2-1`: new package, which is `solo5-kernel-ukvm.0.2.2` copied, but with two additional patches: (a) remove `-Werror` (which fails with newer gcc), and (b) remove `#include <asm/msr-index.h>` which debian (unstable & testing) decided to no longer ship with `linux-libc-dev`
- `solo5-kernel-virtio.0.2.2-1`: new package, which is `solo5-kernel-virtio.0.2.2` copied, but with the same patch removing `-Werror`

I didn't intended to go this deep down here, but I'm glad that the resulting repository is installable on a wide variety of Linux distributions.  The patches for `solo5` are already upstreamed.

If someone would be so kind to merge this PR, I'd be glad (and can finally have my binaries where the stack is non-executable).  Thanks!

**Comment by samoht** [comment]
Many thanks for leading this PR to its conclusion :-)

**Pull request merged**
