### PR TITLE
removing dev-repo field

### PR DESCRIPTION
**Pull request by davidpichardie**

### CODE REVIEW

**Comment by davidpichardie** [comment]
My project is not on github. I don't know what to do with de dev-repo field.

**Comment by gasche** [comment]
Well first, you might want to consider putting your software on a platform that actually encourages people to contribute instead of discouraging them (gforge is dead, gitlab.inria.fr is not usable by external contributors, so if you want to avoid github I think that gitlab.com is your best choice).

(For example, when looking at the compatibility of packages for new OCaml versions, it is rather common for me to send pull-requests to those packages to improve compatibility. Having a publicly visible development repository that is not unusable is a requirement for this.)

I don't know for sure what the automated lint tool expects from the `dev-repo` field. I think that you could use either https://gforge.inria.fr/projects/javalib/ or https://gforge.inria.fr/scm/browser.php?group_id=686 -- note that the SCM link you used in the first version of your pull request is wrong, because it contains your username and brings me to a LDAP authentification page.

If the automated lint keeps failing, we can still ignore it and merge your PR; let's make sure that morally the best thing is there and move on.

**Comment by davidpichardie** [comment]
Gabriel, we were indeed thinking of migrating to github. You message add arguments for that. 

I'm not sure to understand if the current commit passes all the check. If yes, could we publish this update ?

**Comment by gasche** [comment]
The PR fails some of the automated checks:
- the lint (quality of package metadata) fails because the `dev-repo` field is missing
- the build test under the upcoming 4.06.0 release because your `cmdliner` dependency was not yet updated

Those are both understandable and I'll merge it now. Note that I don't know whether your library will work under 4.06.0, in particular if it compiles correctly with the new `-safe-string` default setting (you can test this by just adding the `-safe-string` flag to compilation under any recent OCaml version). If not, it might be worth making a additional release for this support in the future.

**Comment by davidpichardie** [comment]
Thanks. I will work on the compatibility with ocaml 4.06 soon.

**Pull request merged**
