### PR TITLE
Octez 16.0~rc2 packages

### PR DESCRIPTION
**Pull request by killian-delarue**
Packages for the second release candidate for Octez v16.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Should https://github.com/ocaml/opam-repository/pull/22996 be closed in favour of this one?

**Comment by killian-delarue** [comment]
> Should #22996 be closed in favour of this one?

Yes, I closed it

**Comment by raphael-proust** [comment]
Inventory of CI errors:
- Some internal revdeps job got Cancelled due to timeout. This is not a concern because those same packages are also built in their own job.
- Some errors related to https://github.com/ocaml/ocaml/issues/11948 (tezos-webassembly-interpreter-extra on 4.14 with arm32 or ppc64)
- Some issues related to availability of ocamlopt (everything that's "No rule found for ….exe" and "uutf.cmxa" and "hacl-star-raw").
- Some macos failures. It seems there are actual issues here and AFAIK @killian-delarue is looking into this.

@kit-ty-kate What's the proper/recommended fix re: ocamlopt availability?

**Comment by kit-ty-kate** [comment]
@raphael-proust it depends where it's actually needed but it's either
```
build: [...] {!ocaml:native}
```
or
```
conflicts: ["ocaml-option-bytecode-only"]
```

**Comment by kit-ty-kate** [comment]
Closing while this gets looked at to avoid blocking the other PRs. Feel free to reopen whenever it's ready.

Btw are there any plans to reduce the number of packages? It would be really appreciated

**Pull request closed without merging**
