### PR TITLE
ppx_netblob.1.0 - via opam-publish

### PR DESCRIPTION
**Pull request by chrismamo1**
fill strings with data collected from the internet

this package is based on ppx_blob, except it uses cohttp to fetch blobs from
the internet rather than from the local file system
---
- Homepage: https://github.com/chrismamo1/ppx_netblob
- Source repo: https://github.com/chrismamo1/ppx_netblob.git
- Bug tracker: https://github.com/chrismamo1/ppx_netblob/issues/
---

Pull-request generated by opam-publish v0.3.2

### CODE REVIEW

**Comment by yallop** [comment]
The build is [failing](https://travis-ci.org/ocaml/opam-repository/jobs/168089551) with what appears to be a dependency issue:

```
# ocamlfind: Package `cohttp.lwt' not found
# make[1]: *** [ppx_netblob.cmx] Error 2
# make: *** [native-code] Error 2
```

**Comment by avsm** [comment]
Interesting extension!

**Comment by chrismamo1** [comment]
@yallop I'm not sure how to fix the build failure, since it seems like the problem seems exclusive to the `4.04` version

**Comment by avsm** [comment]
could you modify the constraint on `available` to mark this version as <4.04 as well?

**Comment by chrismamo1** [comment]
@avsm modified the constraint, now it appears to be passing the 4.04 build.

**Comment by yallop** [comment]
Thanks!

**Pull request merged**
