### PR TITLE
Package sid.1.1

### PR DESCRIPTION
**Pull request by phi-gamma**
### `sid.1.1`
Handle security identfiers

---
* Homepage: https://gitlab.com/phgsng/ocaml-sid
* Source repo: git+https://gitlab.com/phgsng/ocaml-sid.git
* Bug tracker: https://gitlab.com/phgsng/ocaml-sid

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
`ocamlfind` must be listed as a dependency as it is used by OASIS

**Comment by kit-ty-kate** [comment]
Could you return the fix upstream as well?

**Comment by phi-gamma** [comment]
2018-11-06 (Tuesday), notifications@github.com (Kate):

> Could you return the fix upstream as well?

I just did, thanks!

Philipp

**Comment by kit-ty-kate** [comment]
Seems like this package requires OCaml >= 4.03
```
#=== ERROR while compiling sid.1.1 ============================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.02.3 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-base-compiler.4.02.3/.opam-switch/build/sid.1.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml setup.ml -build
# exit-code   1
# env-file    ~/.opam/log/sid-18317-0c525f.env
# output-file ~/.opam/log/sid-18317-0c525f.out
### output ###
# /home/travis/.opam/ocaml-base-compiler.4.02.3/bin/ocamlopt.opt unix.cmxa -I /home/travis/.opam/ocaml-base-compiler.4.02.3/lib/ocaml/ocamlbuild /home/travis/.opam/ocaml-base-compiler.4.02.3/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/travis/.opam/ocaml-base-compiler.4.02.3/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/travis/.opam/ocaml-base-compiler.4.02.3/bin/ocamlfind ocamldep -package oUnit -package stdint -modules sid.mli > sid.mli.depends
# /home/travis/.opam/ocaml-base-compiler.4.02.3/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package oUnit -package stdint -o sid.cmi sid.mli
# + /home/travis/.opam/ocaml-base-compiler.4.02.3/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package oUnit -package stdint -o sid.cmi sid.mli
# File "sid.mli", line 32, characters 27-45:
# Error: Unbound type constructor result
# Command exited with code 2.
# E: Failure("Command ''/home/travis/.opam/ocaml-base-compiler.4.02.3/bin/ocamlbuild' sid.cma sid.cmxa sid.a sid.cmxs sid_test.byte util/sidparse.native -tag debug -tag tests' terminated with error code 10")
```

**Comment by kit-ty-kate** [comment]
Could you also return this fix upstream?

**Comment by kit-ty-kate** [comment]
All good now. Thanks!

**Comment by phi-gamma** [comment]
2018-11-06 (Tuesday), notifications@github.com (Kate):

> Could you also return this fix upstream?

I did, thanks a lot for your effort!

Philipp

**Pull request merged**
