### PR TITLE
**don't merge** testing the opam-ci reporting

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by AltGr** [comment]
w00t

**Comment by AltGr** [comment]
What is fun is that I don't even checkout the files to disk: I gather the opam file contents directly from the git blobs, load the universe from that and compute the instability from there.

**Comment by avsm** [comment]
Nice!

**Comment by dsheets** [comment]
Is the codebase that runs this online somewhere?

**Comment by AltGr** [comment]
Right just now, I was just adding some readme and license stuff :)
https://github.com/AltGr/opam-ci

**Comment by AltGr** [comment]
Now making it live on opam.ocaml.org (i.e. not through a custom reverse proxy...)

**Comment by AltGr** [comment]
Note of caution: I should have mentionned it needs really bleeding edge versions of several dependencies (ones that I even haven't merged yet)

**Pull request closed without merging**
