### PR TITLE
ocephes.0.8.1 - via opam-publish

### PR DESCRIPTION
**Pull request by rleonid**
Bindings to special math functions from the Cephes library

Ctypes bindings to some of the functions in this common C
mathematical functions library.

---
* Homepage: https://github.com/rleonid/ocephes
* Source repo: https://github.com/rleonid/ocephes.git
* Bug tracker: https://github.com/rleonid/ocephes/issues

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by rleonid** [comment]
I think that I invalidated the previous md5's by renaming the Github repo (Oce... -> oce...). Should I update all of the md5's manually or is there a more robust mechanism?

**Comment by samoht** [comment]
> I think that I invalidated the previous md5's by renaming the Github repo (Oce... -> oce...). Should I update all of the md5's manually or is there a more robust mechanism?

unfortunately I think there is no robust mechanism for this. Would be better to not rely on GH md5s at all I guess.

**Comment by rleonid** [comment]
I don't know why travis is missing the `cmti` file on `4.00`. Do you guys restart the build in this case?

**Comment by yallop** [comment]
Support for `bin_annot` was only added to ocamlbuild in the OCaml 4.01.0 release.

A possible workaround: ignore the fact that the `cmti`files are missing by marking them `-optional`in the `ocamlfind` invocation in your Makefile.

**Comment by rleonid** [comment]
Thank you, I've followed your suggestion.

**Comment by yallop** [comment]
It's looking better!  But I think you need to make both `.cmt` and `.cmti` files optional.

My understanding of `-optional` is that all of the files which follow the flag are allowed to be absent; if that's correct then you probably need

```
-optional _build/src/lib/ocephes.cmti _build/src/lib/ocephes.cmt
```

to appear at the very end of the `ocamlfind install` command

**Pull request merged**
