### PR TITLE
Package 1801bd8447d430ef3e9287f8c2e59218-ocaml-iri-0.5.0.tar.bz2

### PR DESCRIPTION
**Pull request by zoggy**
### `1801bd8447d430ef3e9287f8c2e59218-ocaml-iri-0.5.0.tar.bz2`
Implementation of Internationalized Resource Identifiers (IRIs)

---
* Homepage: https://framagit.org/zoggy/ocaml-iri
* Source repo: git+https://framagit.org/zoggy/ocaml-iri.git
* Bug tracker: https://framagit.org/zoggy/ocaml-iri/-/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The name of the package should be `iri` not `1801bd8447d430ef3e9287f8c2e59218-ocaml-iri-0`

**Comment by kit-ty-kate** [comment]
I would suggest you to either add a `name:` field or rename the file to `iri.opam` to your opam file upstream and use opam-publish again

**Comment by zoggy** [comment]
Regarding the name: ok, I will change to "iri".
Regarding the ``name:`` field, opam-publish removed it from my ``opam`` file... 
Also fixed the license id.

**Comment by zoggy** [comment]
And so opam-publish created a different PR again :-(
https://github.com/ocaml/opam-repository/pull/18629

**Comment by kit-ty-kate** [comment]
> Regarding the `name:` field, opam-publish removed it from my `opam` file...

Yes that's expected though, in opam-repository `name:` is redundant, but in your repository, opam has no way to know what the name of your project is. So that's why it is needed.

**Pull request closed without merging**
