### PR TITLE
Package cfml.20220112

### PR DESCRIPTION
**Pull request by fpottier**
### `cfml.20220112`
The CFML program verification tool

---
* Homepage: https://gitlab.inria.fr/charguer/cfml2
* Source repo: git+https://gitlab.inria.fr/charguer/cfml2.git
* Bug tracker: https://gitlab.inria.fr/charguer/cfml2/-/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
It looks like cfml takes an unusual amount of time to compile with flambda enabled (more than 30 minutes). Is that expected?

**Comment by fpottier** [comment]
I don't know, I haven't tried. I may try it tomorrow if I find some time.

**Comment by fpottier** [comment]
I have compiled `cfml` under `4.13.1+flambda` and noticed nothing special; compilation takes about 15 seconds.

**Comment by fpottier** [comment]
That said, you are right: `opam install cfml` is very slow (at least several minutes, not finished yet). Is there any way of monitoring what it is doing?

**Comment by fpottier** [comment]
It is very slow under `4.13.1` (without `flambda`).

**Comment by kit-ty-kate** [comment]
> Is there any way of monitoring what it is doing?

`dune build -p cfml -j 1 --verbose` should be able to help

**Comment by kit-ty-kate** [comment]
oh you meant with opam? Mmh, I’ve tried:
```
opam pin add cfml https://gitlab.inria.fr/charguer/cfml2/-/archive/20220112/archive.tar.gz
```
but it takes 4 seconds for me with OCaml 4.13.1 (macOS/arm64 though)

**Comment by mseri** [comment]
On MacOS 12, ocaml 4.13.1, x86_64, for me `opam pin add cfml https://gitlab.inria.fr/charguer/cfml2/-/archive/20220112/archive.tar.gz` takes also a handful of seconds

**Comment by fpottier** [comment]
It's fast on my Mac as well. Not sure what is going on. Could you accept this PR? Thanks!

**Comment by kit-ty-kate** [comment]
sure, thanks!

**Pull request merged**
