### PR TITLE
Add conf-openssl-bin

### PR DESCRIPTION
**Pull request by kit-ty-kate**
In #14591 the CI fails because the `certify` package requires `openssl` but the `conf-openssl` package is not the right package, it does not pull the `openssl` binary but `libssl` instead. The reason it works on some systems is that either openssl is already installed by default, or there is only one package that installs both `libssl` and `openssl`.

* To remedy this, this PR creates a new `conf-openssl-bin` package and specify in the description of `conf-openssl` that it installs only the library. This is the least invasive change, but in my opinion, not the best.
* The other option would be to just rename `conf-openssl` to `conf-libssl` and rename the `conf-openssl-bin` created by this PR to `conf-openssl`. This is a bit more invasive because it requires changing the packages using it, but the `conf-openssl` package should have been correctly named `conf-libssl` from the beginning in my opinion.

What do people think about the two different proposals?
(pinging maintainers of packages using `conf-openssl`)
cc @yomimono @xclerc @savonet @constfun

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Does anyone have any opinion on the matter?

**Comment by xclerc** [comment]
I don't, but @tiash might.

**Comment by hannesm** [comment]
I like clean names, i.e. renaming `conf-openssl` to `conf-libssl`; and introducing this new package as `conf-openssl`. since the current `conf-openssl` is not used much, I wouldn't be afraid of the invasive change.

**Comment by hcarty** [comment]
Renaming a package would break anything using `opam lock` with a lockfile pointing at `conf-openssl`.  Those would live outside of opam-repository so they wouldn't be visible from the local CI.

**Comment by kit-ty-kate** [comment]
@hcarty what if we create a new version for `conf-openssl`? (`conf-openssl.2`) and then comment the first one by saying not to use it and that it is only there for opam lock users?

**Comment by hcarty** [comment]
@kit-ty-kate That sounds like a very good solution to me - thank you!

**Comment by kit-ty-kate** [comment]
I made the necessary changes to the packages using `conf-openssl`. Thanks everyone for your inputs (and sorry to have let this drag on)

**Pull request merged**
