### PR TITLE
[new release] ipaddr-cstruct, macaddr, macaddr-sexp, ipaddr, ipaddr-sexp and macaddr-cstruct (5.0.0)

### PR DESCRIPTION
**Pull request by avsm**
A library for manipulation of IP address representations using Cstructs

- Project page: <a href="https://github.com/mirage/ocaml-ipaddr">https://github.com/mirage/ocaml-ipaddr</a>
- Documentation: <a href="https://mirage.github.io/ocaml-ipaddr/">https://mirage.github.io/ocaml-ipaddr/</a>

##### CHANGES:

* Do not zero out the non-prefix-length part of the address in
  `{V4,V6}.Prefix.t` (mirage/ocaml-ipaddr#99 @hannesm)
  Removed `{V4,V6}.Prefix.of_address_string{,_exn}` and
  `{V4,V6}.Prefix.to_address_{string.buffer}`

  To port code:
  - if you rely on `Prefix.of_string` to zero out the non-prefix-length address
    bits, call `Prefix.prefix : t -> t` subsequently.
  - `Prefix.of_address_string{,_exn}` can be replaced by
    `Prefix.of_string{,_exn}`, to retrieve the address use
    `Prefix.address : t -> addr`.
  - The `Prefix.to_address_{string,buffer}` can be replaced by
    `Prefix.to_{string,buffer}`, where `Prefix.t` already contains the IP
    address to be printed.
  - Instead of passing `{V4,V6}.t * {V4,V6}.Prefix.t` for an
    address and subnet configuration, `{V4,V6}.Prefix.t` is sufficient.

* Implement `{V4,V6,}.succ`, `{V4,V6,}.pred`, `{V4,V6}.Prefix.first`, and
  `{V4,V6}.Prefix.last` functions (mirage/ocaml-ipaddr#94 @NightBlues)

* Rename `Prefix.of_netmask` to `Prefix.of_netmask_exn` with labelled
  arguments (~netmask and ~address), provide `Prefix.of_netmask` which returns
  a (t, [> `Msg of string ]) result value (mirage/ocaml-ipaddr#95 @hannesm)

* Fix undefined behaviour of `V4.Prefix.mem` with a CIDR with prefix length 0
  (mirage/ocaml-ipaddr#98 @verbosemode)

* Use stdlib-shims to prevent deprecation warnings on OCaml 4.08
  (@avsm)

* Remove unnecessary "sexplib0" dependency (mirage/ocaml-ipaddr#95 @hannesm)

* Remove "{build}" directive from "dune" dependency (mirage/ocaml-ipaddr#93 @CraigFe)

### CODE REVIEW

**Comment by hannesm** [comment]
I opened https://github.com/ocaml/opam-repository/pull/16646 which fixes most of the reverse dependency. It does not fix colombe, eliom, mrmime which failures are unrelated to this release.

**Comment by kit-ty-kate** [comment]
I relaunched the CI following the merge of https://github.com/ocaml/opam-repository/pull/16646

**Comment by kit-ty-kate** [comment]
The `dune-project` file indicates that these packages require at least dune 1.9. I've also added the appropriate constraint to sync up all the subpackages together as were `ipaddr.4.0.0`. It seems the fixes weren't sent upstream. Could someone do that?

I'm just waiting for Camelus to update (should take 40 minutes) to check I haven't made any mistake in my edits, and this is good to merge.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Comment by hannesm** [comment]
> It seems the fixes weren't sent upstream. Could someone do that?

Thanks for updating the opam files here, I adapted your changes upstream in https://github.com/mirage/ocaml-ipaddr/pull/100/commits/966b06279805000db2f21bfae33fdbc8e3191243 :)

**Pull request merged**
