### PR TITLE
Package ocsigen-start.2.2.2

### PR DESCRIPTION
**Pull request by balat**
### `ocsigen-start.2.2.2`
An Eliom application skeleton ready to use to build your own application with users, (pre)registration, notifications, etc
Ocsigen Start is a set of higher-level libraries for building client-server web applications with Ocsigen (Js_of_ocaml and Eliom). It provides modules for user management (session management, registration, activation keys, ...), managing groups of users, displaying tips, and easily sending notifications to the users. Ocsigen Start comes with an eliom-distillery template for an app with a database, user management, and session management. This template is intended to serve as a basis for quickly building the Minimum Viable Product for web applications with users. The goal is to enable the programmer to concentrate on the core of the app, and not on user management.

---
* Homepage: https://ocsigen.org/ocsigen-start/
* Source repo: git+https://github.com/ocsigen/ocsigen-start.git
* Bug tracker: https://github.com/ocsigen/ocsigen-start/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by mseri** [comment]
No solution for ocaml 4.07.0:
```
[ERROR] No solution for ocsigen-start.2.2.2: The following dependencies couldn't be met:
          - ocsigen-start → cohttp-lwt-unix → logs → mtime → ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → logs → ocaml < 4.04.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → uri < 1.5.0 → ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → uri < 1.5.0 → sexplib < 113.01.00 → ocaml < 4.03.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → sexplib < 113.01.00 → ocaml < 4.03.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → pa_fields_conv → ocaml < 4.03
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → fieldslib < 113.01.00 → ocaml < 4.03
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → fieldslib < 113.01.00 → type_conv < 109.20.00 → ocaml < 4.03.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → cstruct < 0.6.0 → ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → conduit < 0.16.0 → pa_sexp_conv < v0.9.0 → ocaml < 4.03
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → conduit < 0.16.0 → ppx_driver < v0.10.0 → ppx_core < v0.10 → base < v0.10 → ocaml < 4.07.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → conduit < 0.16.0 → ppx_driver < v0.10.0 → ppx_core < v0.10 → ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → conduit < 0.16.0 → ppx_driver < v0.10.0 → ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → cohttp-lwt-unix → cohttp-lwt < 1.0 → cohttp < 1.0 → conduit < 0.16.0 → sexplib < 113.24.00 → ocaml < 4.03.0
              base of this switch (use `--unlock-base' to force)
          - ocsigen-start → js_of_ocaml >= 3.4.0
        Your request can't be satisfied:
          - logs = 0.6.2 is in conflict with js_of_ocaml >= 3.4.0
          - mtime >= 0.8.4 is in conflict with js_of_ocaml >= 3.4.0
```

Should I proceed anyways?

**Comment by balat** [comment]
I think you can proceed.
The problem is that when trying to compile with option --with-test
it tries to install mtime which conflicts with js_of_ocaml.
mtime should be updated to fix that, but it won't prevent from installing Ocsigen Start (without --with-test option).

**Comment by balat** [comment]
There is already an issue for mtime here: https://github.com/dbuenzli/mtime/pull/33

**Comment by mseri** [comment]
Thanks

**Pull request merged**
