### PR TITLE
Add mirage-console*.2.3.2 and mirage-block-xen.1.5.2

### PR DESCRIPTION
**Pull request by djs55**
This fixes some missing dependency and other linking errors uncovered by releases of other packages.

Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by djs55** [comment]
I'm having to hit `rebuild` quite a lot because of source code download failures on datakit.

**Comment by avsm** [comment]
Thanks -- do older packages need constraints to stop them being picked?

**Comment by djs55** [comment]
Mirage-console-xen.2.3.0 is broken (missing a module) should I remove it
altogether?

**Comment by avsm** [comment]
yes just pull it from the repository in a separate PR, thanks!

**Pull request merged**
