### PR TITLE
Solo5: Release 0.4.1, various Mirage/Solo5 updates

### PR DESCRIPTION
**Pull request by mato**
/cc mirage/mirage#939

### CODE REVIEW

**Comment by mato** [comment]
Reopened and force-pushed 41f2e360a227649ce4ca0132cc05c67a5f1ab952, this will hopefully work now.

**Comment by mato** [comment]
It looks like `alpine` is failing due to either the `linux-headers` depext on `solo5-bindings-hvt` being wrong or not getting installed. I can't tell from the log which.

**Comment by mato** [comment]
... it seems to be the latter, running from an `alpine:latest` docker image `apk add build-base linux-headers` is sufficient to get `make hvt` to complete successfully.

**Comment by mato** [comment]
@avsm AFAICT the Alpine CI is not running a `depext` step at all. Unclear where to report issues with the Datakit-based CIs, can you look into it please?

**Comment by kit-ty-kate** [comment]
> @avsm AFAICT the Alpine CI is not running a `depext` step at all. Unclear where to report issues with the Datakit-based CIs, can you look into it please?

Mmh no the only failure on Alpine is for `mirage-net-solo5.0.4.0` and this package doesn't have `linux-headers` as a depexts, so of course it won't be installed.

**Comment by hannesm** [comment]
@kit-ty-kate AFAIU: mirage-net-solo5 depends on mirage-solo5 (which provides the C symbols) -- and this one depends on a disjunction of solo5-bindings-* -- where the one selected here (solo5-bindings-hvt) has a depext on linux-headers. the compilation of solo5-bindings-hvt fails (due to missing linux/if.h). not sure what the root of the issue is (and mirage-solo5-block is very similar in terms of dependencies, but this one compiles fine)

**Comment by kit-ty-kate** [comment]
Oh... I see where is the problem. It must be somewhere inside opam-depext.. Not sure how to fix it though. I'll look at it after lunch.

**Comment by rjbou** [comment]
Internally,  `opam depext` calls `opam list --resolve` to get all their external dependencies and then calls `opam install`. The thing is that opam list and install don't call the solver the same way, with the same universe (install take into account current switch) , it results on two different choices between them.

**Comment by hannesm** [comment]
thanks for looking into this @rjbou. how should we move forward?
I tried to click on `rebuild` on the CI, which now leads to a different error message which I don't fully understand `pull access denied for sha256, repository does not exist or may require 'docker login'`

since the issue only happens sometimes on alpine (or will it happen always on alpine? why are other distributions not affected?), I'd suggest to merge this PR as is, and open an issue on the opam issue tracker (or opam-depext) regarding @rjbou comment "opam list and install don't call the solver the same way, with the same universe (install take into account current switch) , it results on two different choices between them" -- which IIUC should be fixed to avoid potential problems in the future (with the universe getting bigger, my intuition is that there will be more divergence).

WDYT? especially, I can't see a way to apply any fix on this PR for the issue at hand.

**Comment by kit-ty-kate** [comment]
Should be fine to merge I guess. We can test this later anyway. The reason this only fails on Alpine is that on all other distro the required headers are already installed by default.
The reason for the mysterious second error message is that docker seems to remove the base images after some time (I have no idea why) and the base images are not accessible anymore. One way to fix that is to rebuild up to the base image of the branch you want to test (the rebuild button one step above most of the time)

Anyway, thanks!

**Pull request merged**
