### PR TITLE
Rename ocaml-migrate-parsetree 1.3.0 --> 1.3.0~4.08.0+beta2

### PR DESCRIPTION
**Pull request by kit-ty-kate**
cc @xclerc

### CODE REVIEW

**Comment by xclerc** [comment]
This change seems fine; thanks!

**Comment by kit-ty-kate** [comment]
**do not merge**

**Comment by kit-ty-kate** [comment]
as discussed with @avsm let's rename this test package. Do we agree on this one?

**Comment by avsm** [comment]
lgtm!

**Pull request merged**
