### PR TITLE
Added constraint: dose 3.2 fails to compile with latest ocamlgraph

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by avsm** [comment]
```
[ERROR] curl: code 404 while downloading https://gforge.inria.fr/frs/download.php/33607/dose3-3.2-rc2.tar.gz
[ERROR] https://gforge.inria.fr/frs/download.php/33607/dose3-3.2-rc2.tar.gz is not available
```

**Comment by AltGr** [comment]
Ok, let's just remove the package then ?

**Comment by avsm** [comment]
This can be closed, right?

**Comment by AltGr** [comment]
Nope, still needed (I rebased it)

**Pull request merged**
