### PR TITLE
Release owl-ode, owl-ode-sundials 0.0.9

### PR DESCRIPTION
**Pull request by mseri**
This pull-request concerns:
-`owl-ode.0.0.9`: Owl's ODE solvers
-`owl-ode-sundials.0.0.9`: Owl's ODE solvers, interface with SundialsML

---
* Homepage: https://github.com/owlbarn/owl_ode
* Source repo: git+https://github.com/owlbarn/owl_ode.git
* Bug tracker: https://github.com/owlbarn/owl_ode/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

CHANGES: 

- cleaned up and simplified interface
- last release before moving to current owl trunk

### CODE REVIEW

**Comment by mseri** [comment]
Don’t merge. I want to fix the revdeps first and consider to backport a fix to avoid the creation of the `.owl` folder

**Comment by mseri** [comment]
The tests are going to fail, but there is nothing we can do to stop them do it (I will try to avoid the issue by fixing it in owl). If you want I can disable them for opam for now.

Some builds will fail due to lack or incorrect version of sundials.

**Comment by kit-ty-kate** [comment]
There seems to be a missing dependency:
```
#=== ERROR while compiling owl-ode-sundials.0.0.9 =============================#
# context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/owlbarn/owl_ode/archive/V0.0.9.tar.gz)
# path                 ~/.opam/4.07/.opam-switch/build/owl-ode-sundials.0.0.9
# command              ~/.opam/4.07/bin/dune build -p owl-ode-sundials -j 71
# exit-code            1
# env-file             ~/.opam/log/owl-ode-sundials-15-a6f3a5.env
# output-file          ~/.opam/log/owl-ode-sundials-15-a6f3a5.out
### output ###
# File "src/sundials/dune", line 4, characters 25-32:
# 4 |  (libraries bigarray owl owl-ode sundialsml))
#                              ^^^^^^^
# Error: Library "owl-ode" not found.
# Hint: try: dune external-lib-deps --missing -j 71 -p owl-ode-sundials @@default

- File "src/sundials/dune", line 4, characters 25-32:
- 4 |  (libraries bigarray owl owl-ode sundialsml))
-                              ^^^^^^^
- Error: Library "owl-ode" not found.
- Hint: try: dune external-lib-deps --missing -j 71 -p owl-ode-sundials @@default
```

**Comment by mseri** [comment]
Thanks! There was a typo in the corresponding opam file

**Comment by mseri** [comment]
All the remaining failure are unavoidable. They either boil down to the lack of packaged sundials/plplot or to the fact that owl is trying to generate a configuration file escaping the sandbox.

**Comment by kit-ty-kate** [comment]
Could you disable them instead?

**Comment by kit-ty-kate** [comment]
It can be done later I guess, merging for now. Thanks!

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
