### PR TITLE
Add vchan{,-unix,-xen}.3.0.0

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by djs55** [comment]
I think I've accidentally required `cstruct.3.0.0` -- I'll make another minor release and update.

**Comment by djs55** [comment]
It looks like `mirage-qubes.0.1` and `mirage-cubes.0.2` fail to build with a syntax error. `mirage-cubes.0.3` fails to build with a missing `mirage-types.lwt` package. Should we ignore these failures? (/cc @talex5).

**Comment by talex5** [comment]
Would be nice to add some bounds to the qubes packages so they don't break, but I guess it's not this PR's fault.

**Comment by avsm** [comment]
Lets fix mirage-qubes in a separate PR

**Pull request merged**
