### PR TITLE
plist.0.1 - via opam-publish

### PR DESCRIPTION
**Pull request by fxfactorial**
Simple way to create Apple plists.

```ocaml
open Plist

let () = 
  print_endline (to_string (Array [Dict [("Hey", (String "Arnold"))]]))
```

---
* Homepage: https://github.com/fxfactorial/ocaml-plist
* Source repo: https://github.com/fxfactorial/ocaml-plist.git
* Bug tracker: https://github.com/fxfactorial/ocaml-plist/issues

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by samoht** [comment]
```
[ERROR] Bad checksum for /home/travis/.opam/packages.dev/plist.0.1/v0.1.tar.gz:
          - fef51a31f782d9f3d62d10560832c6d3 [expected result]
          - ebfd29c4ff04a6df231ab1c1f6de00e8 [actual result]
        This may be fixed by running `opam update`.
```

**Comment by fxfactorial** [comment]
@samoht Pretty sure its correct now, just did and it seems like the correct one.

```shell
curl https://github.com/fxfactorial/ocaml-plist/archive/v0.1.tar.gz | md5sum
```

**Comment by dsheets** [comment]
You need to pass `curl -L` to get it to follow the HTTP redirect otherwise you will hash some HTML telling you that you are being redirected.

**Comment by samoht** [comment]
```
$ md5sum v0.1.tar.gz
ebfd29c4ff04a6df231ab1c1f6de00e8  v0.1.tar.gz
```

Maybe your proxy is caching an old archive? try `wget --no-cache`?

**Comment by fxfactorial** [comment]
@samoht Ah, this is my bad, will get to it soon.

**Comment by fxfactorial** [comment]
@samoht Possible to kick it off again?

**Comment by dsheets** [comment]
Looks like you also depend on some version of `lambdasoup` and `yojson`.

**Comment by fxfactorial** [comment]
@dsheets Okay, fixed it methinks.

**Comment by dsheets** [comment]
It looks like `plist` uses the alternative syntax for string literals `{|...|}` to quote an XML fragment on line 42 of `plist.ml`. This syntax was introduced in OCaml 4.02.0 so you need to put `available: [ ocaml-version >= "4.02.0" ]` in your `opam` file.

**Comment by fxfactorial** [comment]
@dsheets ahh, this is death by a thousand cuts. fixed.

**Comment by avsm** [comment]
@fxfactorial I'm working on a local workflow right now that'll make this slightly easier than this back-and-forth. Should have something soon...

**Comment by fxfactorial** [comment]
@avsm @dsheets Ah, i hope so, it will definetly help. I actually need to remove that junk, so hold up one second please.

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
