### PR TITLE
malfunction v0.3

### PR DESCRIPTION
**Pull request by stedolan**
As well as adding malfunction v0.3, this PR also removes the base-flambda package: it was only ever used by malfunction, and malfunction no longer has a hard dependency on flambda. (The relevant version constraints were inlined directly in the opam files of old versions of malfunction, so nothing changes there).

### CODE REVIEW

**Comment by gasche** [comment]
I'm happy to learn about a new release of malfunction, do you plan to someday describe the changes in the language somewhere? Here is what I can gather from the github commit log:

- support for OCaml 4.04 to 4.07 (dropped support for 4.03)
- support for non-flambda setups
- support for Lazy
- some floating-point support

Have you considered writing, like, release notes, and telling people about it?

**Comment by stedolan** [comment]
The build failure on travis is due to zarith producing a spurious warning on OS X (see https://github.com/ocaml/dune/issues/883, https://github.com/ocaml/opam-repository/issues/3000). It's only breaking here because the malfunction tests check exact command output, and some of them include this warning.

Since this isn't a bug in malfunction, and the malfunction command works fine even with the bug (although you get a spurious warning), I don't think this should block merging. Any maintainers agree/disagree?

@gasche 
> Have you considered writing, like, release notes,

There's a CHANGES.md file in the repo (which contains nothing more than what you've gleaned from git logs), and `docs/spec.md` is kept in sync with language changes.

> and telling people about it?

This is a dangerous move, and runs a serious risk of acquiring users :)

**Comment by gasche** [comment]
Thanks for the CI analysis. Merging.

**Comment by stedolan** [comment]
Thanks!

**Pull request merged**
