### PR TITLE
added ocamltter.4.1.0

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by yallop** [comment]
It's not building, because it depends on `orakuda 3.0.0`, which isn't yet in the repository:


```
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Checking for availability...
The following dependencies couldn't be met:
  - ocamltter -> orakuda >= 3.0.0
Your request can't be satisfied:
  - No package matches orakuda>=3.0.0.
```

**Comment by camlspotter** [comment]
its ppx_orakuda...

**Comment by dsheets** [comment]
Why didn't this fail @camelus's installability check?

**Comment by yallop** [comment]
Perhaps the installability check tests against 4.02, and it's disabled by the `available` constraint on this package.

**Comment by yallop** [comment]
```
### stderr ###
# [...]
# *** omake: targets were not rebuilt because of errors:
#    src/ppx_meta_conv.cmi
#       depends on: src/ppx_meta_conv.ml
#    src/ppx_meta_conv.cmo
#       depends on: src/ppx_meta_conv.ml
#    src/ppx_meta_conv.cmx
#       depends on: src/ppx_meta_conv.ml
#    src/ppx_meta_conv.o
#       depends on: src/ppx_meta_conv.ml
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=\"' terminated with error code 2")
```

**Comment by camlspotter** [comment]
Damn, it is ppx_meta_conv.2.3.0 not 2.2.0

**Comment by camlspotter** [comment]
Local opam pin test passed.  I hope it passes CI too.

**Comment by yallop** [comment]
It does!

**Pull request merged**
