### PR TITLE
Core 112.06.02

### PR DESCRIPTION
**Pull request by bmillwood**
Mostly fixes for 32-bit linux.

I haven't yet included the patches that have since shown up for ocaml trunk compatibility.

### CODE REVIEW

**Comment by bmillwood** [comment]
Oop, should mention. This is just rc1. Please don't merge it, just test and tell me and I'll put the final together on Monday.

**Comment by avsm** [comment]
bignum fails:


```
#=== ERROR while installing bignum.112.06.02 ==================================#
# opam-version 1.2.0
# os           linux
# command      make
# path         /home/travis/.opam/system/build/bignum.112.06.02
# compiler     system (4.02.1)
# exit-code    2
# env-file     /home/travis/.opam/system/build/bignum.112.06.02/bignum-18157-062a54.env
# stdout-file  /home/travis/.opam/system/build/bignum.112.06.02/bignum-18157-062a54.out
# stderr-file  /home/travis/.opam/system/build/bignum.112.06.02/bignum-18157-062a54.err
### stdout ###
# ...[truncated]
#                       - Building lib/bignum.ml:
#                           - Failed to build all of these:
#                               - Building lib/bignum.mly
#                               - Building lib/bignum.mll
#                       - Building lib/bignum.mli:
#                           - Building lib/bignum.mly
#                       - Building lib/bignum.mlpack
#                       - Building lib/bignum.mli:
#                           - Building lib/bignum.mly
#               - Building lib/bignum.mllib
### stderr ###
# W: Cannot find source file matching module 'bignum' in library bignum
# E: Failure("Command ''/usr/bin/ocamlbuild' lib/bignum.cma lib/bignum.cmxa lib/bignum.a lib/bignum.cmxs -use-ocamlfind -tag debug' terminated with error code 6")
# make: *** [build] Error 1

```

**Comment by bmillwood** [comment]
Sorry, I messed up the packaging. Pushed an rc3 for bignum (the rc1 was actually an rc2)

**Comment by avsm** [comment]
Final please.  my tests are still building the full set, but it looks good.

**Pull request merged**
