### PR TITLE
posix-semaphore v0.5.0

### PR DESCRIPTION
**Pull request by mwweissmann**

### CODE REVIEW

**Comment by yallop** [comment]
The build is [failing](https://ci.ocaml.io/log/saved/docker-build-eb09b6ff140c106f219b4f35931a9150/c65a3a49cdddac6b62836d46a78a1b6fd83c948d) on Alpine:

```
 In file included from src/semaphore.c:19:0:
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:57:30: error: return type is an incomplete type
 static inline struct timeval timeval_val(value v) {
                              ^~~~~~~~~~~
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:57:30: error: conflicting types for 'timeval_val'
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:31:30: note: previous declaration of 'timeval_val' was here
 static inline struct timeval timeval_val(value v);
                              ^~~~~~~~~~~
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h: In function 'timeval_val':
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:59:5: error: unknown field 'tv_sec' specified in initializer
     .tv_sec = Int64_val(Field(v, 0)),
     ^
In file included from src/semaphore.c:11:0:
/home/opam/.opam/4.04.2/lib/ocaml/caml/mlvalues.h:302:22: warning: excess elements in struct initializer
 #define Int64_val(v) (*((int64_t *) Data_custom_val(v)))
                      ^
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:59:15: note: in expansion of macro 'Int64_val'
     .tv_sec = Int64_val(Field(v, 0)),
               ^~~~~~~~~
/home/opam/.opam/4.04.2/lib/ocaml/caml/mlvalues.h:302:22: note: (near initialization for '(anonymous)')
 #define Int64_val(v) (*((int64_t *) Data_custom_val(v)))
                      ^
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:59:15: note: in expansion of macro 'Int64_val'
     .tv_sec = Int64_val(Field(v, 0)),
               ^~~~~~~~~
In file included from src/semaphore.c:19:0:
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:60:5: error: unknown field 'tv_usec' specified in initializer
     .tv_usec = Int64_val(Field(v, 1))
     ^
In file included from src/semaphore.c:11:0:
/home/opam/.opam/4.04.2/lib/ocaml/caml/mlvalues.h:302:22: warning: excess elements in struct initializer
 #define Int64_val(v) (*((int64_t *) Data_custom_val(v)))
                      ^
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:60:16: note: in expansion of macro 'Int64_val'
     .tv_usec = Int64_val(Field(v, 1))
                ^~~~~~~~~
/home/opam/.opam/4.04.2/lib/ocaml/caml/mlvalues.h:302:22: note: (near initialization for '(anonymous)')
 #define Int64_val(v) (*((int64_t *) Data_custom_val(v)))
                      ^
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:60:16: note: in expansion of macro 'Int64_val'
     .tv_usec = Int64_val(Field(v, 1))
                ^~~~~~~~~
In file included from src/semaphore.c:19:0:
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:61:3: error: invalid use of undefined type 'struct timeval'
   };
   ^
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:58:10: warning: 'return' with a value, in function returning void
   return (struct timeval){
          ^
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:57:30: note: declared here
 static inline struct timeval timeval_val(value v) {
                              ^~~~~~~~~~~
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h: At top level:
/home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:64:57: error: parameter 1 ('t') has incomplete type
 CAMLprim static inline value val_timeval(struct timeval t) {
                                                         ^
Command exited with code 2.
```

**Comment by mwweissmann** [comment]
The problem seems to be Alpine's libc "musl" which does not have 'struct timeval' in 'time.h' but in 'sys/time.h' -- I added the missing #include in the posix-time package, breaking the poor buildbot with the second commit.
Should I restart and first commit posix-time, wait and then add posix-semaphore?

**Comment by yallop** [comment]
I think the build failed because the CI machine was out of disk space.  I've restarted it now.

**Comment by mwweissmann** [comment]
nice, thanks

**Pull request merged**
