### PR TITLE
Do not compile ocamlfind in native if absent

### PR DESCRIPTION
**Pull request by samoht**
Also clean-up the opam file

### CODE REVIEW

**Comment by dsheets** [comment]
`bug-reports` should be URL of `mailto:gerd@...`?

**Comment by yallop** [comment]
Excellent; thanks!  I've checked that OCamlfind works with the multicore compiler after this change.

**Comment by samoht** [comment]
I've added @dsheets suggestions. Not sure if it is worth doing that change on older versions of ocamlfind as well.

**Pull request merged**
