### PR TITLE
Reason 3.6.0

### PR DESCRIPTION
**Pull request by anmonteiro**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This package fails with OCaml 4.02:
```
#=== ERROR while compiling reason.3.6.0 =======================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.02.3 | pinned(https://registry.npmjs.org/@esy-ocaml/reason/-/reason-3.6.0.tgz)
# path                 ~/.opam/4.02/.opam-switch/build/reason.3.6.0
# command              ~/.opam/4.02/bin/dune build -p reason -j 72
# exit-code            1
# env-file             ~/.opam/log/reason-23-c24d45.env
# output-file          ~/.opam/log/reason-23-c24d45.out
### output ###
#       ocamlc src/menhir-recover/.main.eobjs/byte/main.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.02/bin/ocamlc.opt -w -40 -g -bin-annot -I src/menhir-recover/.main.eobjs/byte -I /home/opam/.opam/4.02/lib/fix -I /home/opam/.opam/4.02/lib/menhirLib -I /home/opam/.opam/4.02/lib/menhirSdk -no-alias-deps -o src/menhir-recover/.main.eobjs/byte/main.cmo -c -impl src/menhir-recover/main.ml)
# File "src/menhir-recover/main.ml", line 22, characters 41-42:
# Error: Signature mismatch:
#        ...
#        Type declarations do not match:
#          type terminal = G.terminal
#        is not included in
#          type terminal = private int
```

**Comment by kit-ty-kate** [comment]
From this commit https://github.com/facebook/reason/commit/8f71db0b88c31842d866d46a18b71a1ce1709567 I see that you increased your minimum version. So I'm assuming it is safe to just increase the lower-bound. I'll do that now and merge it right after

**Comment by kit-ty-kate** [comment]
After reflection I'll wait for your approval. There are conflicting commits in the source code (CI for 4.02 is disabled but some code specific for 4.02 are still around)

**Comment by anmonteiro** [comment]
Hey @kit-ty-kate please go ahead. I forgot to bump the lower bound.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
