### PR TITLE
new file:   packages/pardi/pardi.3.1.1/opam

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Somehow the opam file used wasn't the one from your source repository and the following failure appeared when building:
```
#=== ERROR while compiling pardi.3.1.1 ========================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://github.com/UnixJunkie/pardi/archive/v3.1.1.tar.gz)
# path                 ~/.opam/4.10/.opam-switch/build/pardi.3.1.1
# command              ~/.opam/4.10/bin/dune build -p pardi -j 72
# exit-code            1
# env-file             ~/.opam/log/pardi-23-1b6da6.env
# output-file          ~/.opam/log/pardi-23-1b6da6.out
### output ###
#       ocamlc src/.pardi.eobjs/byte/pardi.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.pardi.eobjs/byte -I /home/opam/.opam/4.10/lib/batteries -I /home/opam/.opam/4.10/lib/bytes -I /home/opam/.opam/4.10/lib/cpu -I /home/opam/.opam/4.10/lib/cryptokit -I /home/opam/.opam/4.10/lib/ctypes -I /home/opam/.opam/4.10/lib/dolog -I /home/opam/.opam/4.10/lib/integers -I /home/opam/.opam/4.10/lib/lz4 -I /home/opam/.opam/4.10/lib/minicli -I /home/opam/.opam/4.10/lib/num -I /home/opam/.opam/4.10/lib/ocaml/threads -I /home/opam/.opam/4.10/lib/parany -I /home/opam/.opam/4.10/lib/stdint -I /home/opam/.opam/4.10/lib/zarith -I /home/opam/.opam/4.10/lib/zmq -I src/.sec_chan.objs/byte -I src/.sec_chan.objs/native -no-alias-deps -o src/.pardi.eobjs/byte/pardi.cmo -c -impl src/pardi.ml)
# File "src/pardi.ml", line 217, characters 14-22:
# 217 |   Parany.run ~preserve ~csize:1 nprocs
#                     ^^^^^^^^
# Error: The function applied to this argument has type
#          verbose:bool -> nprocs:int -> unit
# This argument cannot be applied with label ~preserve
```

**Comment by UnixJunkie** [comment]
ok, I'll check both opam files are synchronized

**Comment by UnixJunkie** [comment]
the constraint is ok:
```
"parany" {>= "11.0.0"}
```

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
