### PR TITLE
Add liquidsoap-daemon.1.0.0

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Could you use ```%{share_root}%``` and ```%{bin}%``` instead of ```%{prefix}%/share``` and ```%{prefix}%/bin``` ? Also I'm pretty sure the first mkdir is not necessary.

**Comment by toots** [comment]
Done! Let's see if the CI tests pass now.

**Comment by toots** [comment]
Hey @jpdeplaix, it looks like `share_root` is only used in `.install` files. I'm gonna revert this part and rebase the PR.

**Comment by jpdeplaix** [comment]
Oops, yes. Sorry about that, I always forget the difference.
Could you tell why you removed ```liquidsoap.1.0.1-full``` ? Also @camelus is telling you that your liquidsoap package fixes use a wrong syntax. I think you should use ```&``` instead of ```&&```.

**Comment by toots** [comment]
Whoops, fixed!

I've remove old version of liquidsoap that are outdated and will not build anyway (I'm also upstream on this project).

**Comment by jpdeplaix** [comment]
Look fine then. Sorry for the delay. Thanks !

**Pull request merged**
