### PR TITLE
fix checksum for lz4.1.0.0

### PR DESCRIPTION
**Pull request by lefessan**

### CODE REVIEW

**Comment by samoht** [comment]
@yallop  missing depext?

```
#=== ERROR while installing ctypes.0.3.4 ======================================#
# opam-version 1.2.2
# os           darwin
# command      make
# path         /Users/travis/.opam/system/build/ctypes.0.3.4
# compiler     system (4.02.3)
# exit-code    2
# env-file     /Users/travis/.opam/system/build/ctypes.0.3.4/ctypes-2979-ebe0e0.env
# stdout-file  /Users/travis/.opam/system/build/ctypes.0.3.4/ctypes-2979-ebe0e0.out
# stderr-file  /Users/travis/.opam/system/build/ctypes.0.3.4/ctypes-2979-ebe0e0.err
### stdout ###
# [...]
# ocamlfind ocamlc -c -o _build/src/ctypes-foreign-base/libffi_abi.cmi    -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/libffi_abi.mli
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/libffi_abi.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/libffi_abi.ml
# ocamlfind ocamlc -c -o _build/src/ctypes-foreign-base/weakRef.cmi    -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/weakRef.mli
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/weakRef.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/weakRef.ml
# ocamlfind ocamlc -c -o _build/src/ctypes-foreign-base/ffi.cmi    -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/ffi.mli
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/ffi.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/ffi.ml
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/foreign_basis.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/foreign_basis.ml
# ocamlfind ocamlc -a   -cclib -lctypes-foreign-base_stubs -dllib -lctypes-foreign-base_stubs   -o _build/ctypes-foreign-base.cma _build/src/ctypes-foreign-base/closure_properties.cmo _build/src/ctypes-foreign-base/dl.cmo _build/src/ctypes-foreign-base/ffi_stubs.cmo _build/src/ctypes-foreign-base/libffi_abi.cmo _build/src/ctypes-foreign-base/weakRef.cmo _build/src/ctypes-foreign-base/ffi.cmo _build/src/ctypes-foreign-base/foreign_basis.cmo 
# cd _build/src/ctypes-foreign-base && ocamlfind ocamlc -c -ccopt -fPIC -ccopt -Wall -ccopt -O3 -ccopt -I -ccopt /Users/travis/build/ocaml/opam-repository/src -ccopt -I -ccopt /Users/travis/build/ocaml/opam-repository/tests -o dl_stubs.o  /Users/travis/.opam/system/build/ctypes.0.3.4/src/ctypes-foreign-base/dl_stubs.c
# cd _build/src/ctypes-foreign-base && ocamlfind ocamlc -c -ccopt -fPIC -ccopt -Wall -ccopt -O3 -ccopt -I -ccopt /Users/travis/build/ocaml/opam-repository/src -ccopt -I -ccopt /Users/travis/build/ocaml/opam-repository/tests -o ffi_call_stubs.o  /Users/travis/.opam/system/build/ctypes.0.3.4/src/ctypes-foreign-base/ffi_call_stubs.c
### stderr ###
# Exception: End_of_file.
# /Users/travis/.opam/system/build/ctypes.0.3.4/src/ctypes-foreign-base/ffi_call_stubs.c:21:10: fatal error: 'ffi.h' file not found
# #include <ffi.h>
#          ^
# 1 error generated.
# make: *** [_build/src/ctypes-foreign-base/ffi_call_stubs.o] Error 2
```

**Comment by yallop** [comment]
No; there were problems with the configuration step on OSX in 0.3.4.  We might as well merge this.

**Comment by samoht** [comment]
As so that's a missing `available` constraint for ctype.0.3.4 then :-)

**Comment by yallop** [comment]
Some people have apparently managed to use the ctypes 0.3.4 OPAM package on OSX, even if it doesn't build on Travis (which [didn't support](https://travis-ci.org/ocaml/opam-repository/builds/44889288) OSX when the package was submitted).  I expect it depends on exactly how pkg-config, Homebrew, etc. are installed.

**Comment by samoht** [comment]
ok no pb, just checking :-)

**Pull request merged**
