### PR TITLE
bap.1.0.0

### PR DESCRIPTION
**Pull request by ivg**
This is a public release of BAP platform. 

The platform consists of about 60 packages, so I'm not sure how CI will handle this. Unfortunately, it wouldn't be possible to release each package separately, as the Platform must be released all at once.

### CODE REVIEW

**Comment by avsm** [comment]
Thanks Ivan!  Dont worry about the large PR; we can test it using a manual build once Travis does a few iterations.

**Comment by ivg** [comment]
In-house, we test opam installation using [docker][1] and [vagrant][2]. The former is run on every PR. Also, we're running our  [opam/opam]  file on the Travis docker infrastructure. It doesn't check the `opam-repository` files, but runs tests, and checks components, that are optional and are not included in base bap package. 

[1]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/docker/Dockerfile
[2]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/vagrant/trusty64/Vagrantfile
[3]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/opam/opam

**Comment by avsm** [comment]
@ivg: this test infrastructure sounds really excellent!  If you get a chance, a note about how it works (and any code) on ocaml/opam#2686 would be useful

**Comment by avsm** [comment]
Things are currently failing on depexts. Is there any way to improve the `conf-ada` and `conf-llvm` situation?

**Comment by ivg** [comment]
Well, `conf-ida` is optional, as IDA is a proprietary software, so it doesn't come into play (we are not trying to test any IDA related stuff on any CI server, as doing it will violate the license). 

With `conf-llvm` things are more interesting. Currently, BAP supports only `llvm-3.4` and `llvm-3.8`, these are the two versions, that are shipped by default on two latest Ubuntu LTS. Unfortunately, it is not possible in opam to say, that we need either this or that. Yes, that there is an `|` operator, that will indeed accept both versions if one is already installed. However during the computation of the dependencies, the `|` operator is ignored, and only one (with the latest version) is taken. Then, during the installation, we're failing on `llvm-conf.<max-version>`, as it may not be available on the system. Of course, at this point opam can't backtrack and try to install another universe of packages. 

So, we decided to address this with the following approach, there are specific packages `llvm-conf.3.x` which are only installable if the system package of the specific version is installable (and depex'es are listed correspondingly). Also, we have `llvm-conf.system`, that installs a system default version of  `llvm`, e.g., on Ubuntu it just installs `llvm-dev`. And we put `conf-llvm` as a dependency on `bap-llvm`. With this setup we can do `opam install bap` on those systems, where the default llvm is 3.4 or 3.8. On other system, a user can specify a version of llvm explicitly, e.g., `opam install bap conf-llvm=3.4`.

We are currently working on installation issues on other systems, like debian, arch, and macbrew. But this requires tedious updating of all upstream dependencies (mainly the depexts). We will soon contribute them back. 

Also, we came with the idea, that `depext` flags may also include distribution version along with the distribution name. It will facilitate a precise control of system dependencies, as dependencies may actually depend on a particular version of a distribution. Also, some distributions do change package names and availability between releases.

**Comment by AltGr** [comment]
>So, we decided to address this with the following approach, there are specific packages llvm-conf.3.x which are only installable if the system package of the specific version is installable (and depex'es are listed correspondingly). Also, we have llvm-conf.system, that installs a system default version of llvm, e.g., on Ubuntu it just installs llvm-dev. And we put conf-llvm as a dependency on bap-llvm. With this setup we can do opam install bap on those systems, where the default llvm is 3.4 or 3.8. On other system, a user can specify a version of llvm explicitly, e.g., opam install bap conf-llvm=3.4.

Clever! This is similar to the problem we had with handling system OCaml distributions. In opam 2.0, the solution adopted is generic and might be adopted for llvm too (although it probably wouldn't scale to any number of packages):
- In opam's global config, you are allowed to define (lazy) variables bound to the output of a given command. E.g.

        eval-variables: [
          sys-ocaml-version ["ocamlc" "-vnum"]
          "OCaml version present on your system independently of opam, if any"
        ]
- That variable can be used in the `available:` field of packages. This way, although there is one instance of the `ocaml-system` package for each released version, only the one present on the system, if any, will be visible as available.
- It will be evaluated every time the universe is computed; otoh, that means opam will adapt to changes to the system installation
- The variable can currently be defined in one of the following ways:
    - by editing the config file by hand
    - by being specified in `/etc/opamrc` or `~/.opamrc` before `opam init` is done
    - by being in opam's [built-in](https://github.com/ocaml/opam/blob/master/src/client/opamInitDefaults.ml) default `opamrc`
- The main reason for this is that, for security reasons, we don't want packages to be able to execute code without having ever been requested by the user.

> Also, we came with the idea, that depext flags may also include distribution version along with the distribution name. It will facilitate a precise control of system dependencies, as dependencies may actually depend on a particular version of a distribution. Also, some distributions do change package names and availability between releases. 

Yes, it is quite limited at the moment, feel free to propose improvements.

**Comment by ivg** [comment]
So, guys, will we merge it?

**Comment by AltGr** [comment]
Finally managed to get Camelus running on this (ported to newest git/github). You can ignore warn 41, I need to backport the fix.

**Pull request merged**
