### PR TITLE
Add guessable dev_repo fields

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by avsm** [comment]
Would there be any chance this could be split into two commits: one to do the reformatting, and another to add `dev-repo`?  merging the formatting changes first will make the latter much easier to review.

**Comment by amirmc** [comment]
I think this is a result of how the opam tool now behaves (otherwise it likely would have been just the dev-repo lines and opam 1.2). 

If it needs to be split, then we may have to wait as the author has other things to do first ;)

Best wishes,
Amir

--
Sent via mobile

**Comment by samoht** [comment]
I don't really like to merge such big patches in one go. See a similar PR https://github.com/ocaml/opam-repository/pull/3140. Would be good to normalise the description at one point though, so maybe we could do it soon -- but at least we should advertise that fact on opam-devel and as we are modifying a lot of packages, hopefully we won't hit any build (and opam will not trigger the recompilation of all the user packages, as we are only modifying the opam file and not the url file).

**Comment by AltGr** [comment]
I can trick the script to split the patch:
 1. normalise all files that _would_ be modified, but without making the change
 2. add the new field

some sed magic could also be used to turn the patch into pure addition of `dev-repo` fields, if really needed.

**Comment by AltGr** [comment]
Duplicate of #3140, see the remarks there !

**Comment by AltGr** [comment]
Also, need to check, but I think camelus gets blocked because of a comment-length limitation on github for such huge patches.
(it raised a `Github_core.Make(Time)(CL).Message(578388242, _)`)
We could limit to a short summary in case it gets too long.

**Comment by dsheets** [comment]
I'd love to see the actual error raised in that failure case.

**Comment by AltGr** [comment]
@dsheets: yes, I'll try to reproduce as soon as I get the time!

**Comment by Chris00** [comment]
I have replaced the changes with minimal ones — did that during a travel with no (good) connection! :-)

**Comment by avsm** [comment]
Cant merge this until #3140 is resolved (specifically the issue of depopt constraints and 1.1 compatibility)

**Comment by samoht** [comment]
can you sync with @AltGr on #5190 to find the best way to merge this?

**Comment by Chris00** [comment]
@samoht Is your comment for me or for @avsm ?

**Comment by samoht** [comment]
@Chris00 for you I think :-)

**Comment by Chris00** [comment]
@samoht Well, I do not really see what to sync about.  His proposal is supposed to supersede mine.  How can I help?

**Comment by AltGr** [comment]
@Chris00 I don't know, my PR only changes 1212 files, while yours has >2000. I must have missed something...

**Comment by samoht** [comment]
> @samoht Well, I do not really see what to sync about. His proposal is supposed to supersede mine. How can I help?

ok, so I'm closing this PR.

**Pull request closed without merging**
