### PR TITLE
aws-rds.0.1.0 - via opam-publish

### PR DESCRIPTION
**Pull request by seliopou**
Amazon Relational Database Service

---
* Homepage: https://github.com/inhabitedtype/ocaml-aws
* Source repo: https://github.com/inhabitedtype/ocaml-aws.git
* Bug tracker: https://github.com/inhabitedtype/ocaml-aws/issues

---
### opam-lint failures
- **WARNING** 97 long description unspecified

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by yallop** [comment]
[Here](https://travis-ci.org/ocaml/opam-repository/jobs/118877397)'s the error message from the Travis build:

```
# File "lib/describeAccountAttributes.mli", line 2, characters 13-47:
# Error: Unbound module DescribeAccountAttributesMessage
# Command exited with code 2.
```

**Comment by avsm** [comment]
https://github.com/avsm/opam-pr-build-results/blob/6128/README.md

**Comment by seliopou** [comment]
There's a problem with the inliner. I'll try and disable it for these libraries.

**Comment by samoht** [comment]
ping @seliopou

**Comment by samoht** [comment]
ping ping @seliopou

**Comment by seliopou** [comment]
May be a while before I get to this, so closing for now.

**Pull request closed without merging**
