### PR TITLE
[new release] electrod (0.2.0)

### PR DESCRIPTION
**Pull request by grayswandyr**
Formal analysis for the Electrod formal pivot language

- Project page: <a href="https://grayswandyr.github.io/electrod">https://grayswandyr.github.io/electrod</a>
- Documentation: <a href="https://grayswandyr.github.io/electrod/api">https://grayswandyr.github.io/electrod/api</a>

##### CHANGES:

- migration to OPAM 2.0
- migration to Dune 1.4 (for better handling of Menhir)
- handle SIGTERM properly
- feature grayswandyr/electrod#993: add BMC mode
- bug grayswandyr/electrod#978: handle nested "always" in INVAR field

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Compilation fails with:
```
#=== ERROR while compiling electrod.0.2.0 =====================================#
# context              2.0.1 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/grayswandyr/electrod/releases/download/0.2.0/electrod-0.2.0.tbz)
# path                 ~/.opam/4.07/.opam-switch/build/electrod.0.2.0
# command              ~/.opam/4.07/bin/dune build -p electrod -j 127
# exit-code            1
# env-file             ~/.opam/log/electrod-19-1f65f5.env
# output-file          ~/.opam/log/electrod-19-1f65f5.out
### output ###
# Module Parser in directory _build/default/src depends on Libelectrod.
# This doesn't make sense to me.
# 
# Libelectrod is the main module of the library and is the only module exposed 
# outside of the library. Consequently, it should be the one depending 
# on all the other modules in the library.
```

**Comment by pmetzger** [comment]
`https://grayswandyr.github.io/electrod/` gives me a 404 not found error.

**Comment by grayswandyr** [comment]
@pmetzger This is fixed.

I also fixed the OPAM file that entailed CI failures. I still have a Camelus error but I don't know what the error is, there's no link pointing to error details... what should I do?

**Comment by grayswandyr** [comment]
Actually I think there is a deeper problem. Closing this PR while looking into it.

**Pull request closed without merging**
