### PR TITLE
[new release] irmin project (3.2.0)

### PR DESCRIPTION
**Pull request by icristescu**
### Added

- **irmin-pack**
  - Add `forbid_empty_dir_persistence` in store configuration. (mirage/irmin#1789,
    @ngoguey42)
  - Add `Store.Snapshot` to expose the inodes for tezos snapshots (mirage/irmin#1757,
    @icristescu).

### Changed

- **irmin**
  - Add error types in the API or proof verifiers. (mirage/irmin#1791, @icristescu)
  - Reduced the memory footprint of ``Tree.fold ~uniq:`True`` by a factor of 2.
    (mirage/irmin#1770, @CraigFe)

### CODE REVIEW

**Comment by samoht** [comment]
> [](https://github.com/mirage/irmin)PPX deriver for Irmin type representations

@NathanReb that doesn't seem to be the right description picked in. Do you know what is happening?

**Comment by icristescu** [comment]
> > PPX deriver for Irmin type representations
> 
> @NathanReb that doesn't seem to be the right description picked in. Do you know what is happening with `dune-release`?

I change the text manually to unblock merging this.

**Comment by icristescu** [comment]
the failing tests seems to be only on `macos-homebrew (experimental)`, I think this can be merged

**Comment by NathanReb** [comment]
Yes it's a known bug in multi opam repos, we'll look into it!

**Comment by mseri** [comment]
Looks good, thanks

**Pull request merged**
