### PR TITLE
added packages/clangml-transforms/clangml-transforms.0.20

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I need to update the check.sh shell script and not require a +PIC compiler to be present for recent ocaml versions

**Comment by UnixJunkie** [comment]
In fact, I think this can be merged: the package did not install in Travis because either the conf-pic-switch package could not be installed or because the following constraint could not be met:
  - clangml is not available because your system doesn't comply with ocaml-version >= "4.02.3" & !preinstalled.
Which are all valid reasons to not install the package.

**Comment by UnixJunkie** [comment]
What can I do to make this pull request accepted?

**Comment by samoht** [comment]
> What can I do to make this pull request accepted?

An option would be to volunteer to help triaging and merging pull requests and improve the CI system :-)

**Pull request merged**
