### PR TITLE
make zarith-xen and zarith-freestanding coinstallable

### PR DESCRIPTION
**Pull request by hannesm**
I'm pretty sure there are nicer solutions for this, but it might be worth having this now!? //cc @avsm @mato

### CODE REVIEW

**Comment by hannesm** [comment]
using this, I can install `mirage-solo5` and `mirage-xen` in parallel, and when I install `nocrypto` afterwards, I get:

```
-rw-r--r--  1 hannes hannes 294118 Nov  2 21:46 libnocrypto_stubs.a
-rw-r--r--  1 hannes hannes 285542 Nov  2 21:46 libnocrypto_stubs+mirage-freestanding.a
-rw-r--r--  1 hannes hannes 285726 Nov  2 21:46 libnocrypto_stubs+mirage-xen.a
```

which looks pretty sane to me.

**Comment by hannesm** [comment]
the MacOSX build died for unknown reason, could someone please restart that?

**Comment by samoht** [comment]
restarted

**Comment by avsm** [comment]
this lgtm for now and the coinstallability is very useful.

**Pull request merged**
