### PR TITLE
why.2.34 does not work with latest ocamlgraph

### PR DESCRIPTION
**Pull request by planar**

### CODE REVIEW

**Comment by dsheets** [comment]
Looks like warnings-as-errors also makes why.2.34 fail with OCaml 4.02.1 on a deprecation.

**Comment by planar** [comment]
What's the standard way to deal with that? Should I change the `opam` file or make a patch?

**Comment by dsheets** [comment]
We should probably contact the maintainer (@claudemarche?) and restrict the version in the meanwhile. If you feel like patching, I'm sure upstream would appreciate it (as well as an upstream patch). Without any action, users will be able to attempt the install but will always fail.

**Comment by planar** [comment]
The problem is that "why development is frozen", which means it may be a long time before the next release. In the meantime, we can use the trick implemented in my second commit here. Is that acceptable?

**Comment by avsm** [comment]
Setting `OCAMLPARAM` means that it'll override any custom settings we do in bulk builds, but we can special case `why` in the interests of getting it to build right now.  So I'm ok with this...

**Comment by claudemarche** [comment]
Feel free to push your changes in the opam config file to fix those dependency problem.

About the next Why release: since there is now a release candidate for Frama-C Sodium, a new release of Why will indeed come quite soon, a good opportunity to make it compatible with ocaml 4.02 and current ocamlgraph.

**Comment by planar** [comment]
@asvm, I'll do a patch, it's not that hard.

@claudemarche, If you need help, let me know

**Pull request merged**
