### PR TITLE
+cstruct.2.0.0

### PR DESCRIPTION
**Pull request by avsm**
I'll merge this one myself as I need to push a vast number of upper bounds to the repository as well, but getting this travis tested first...

### CODE REVIEW

**Comment by avsm** [comment]
Argh, this isn't ready to merge as the upper bounds not done yet...

**Comment by dsheets** [comment]
Oh my, very sorry. I wasn't paying attention to your PR text. :-/

**Comment by dsheets** [comment]
I've now reverted it.

**Comment by avsm** [comment]
thanks!

**Pull request merged**
