### PR TITLE
ocaml-top: fails to link against Thread on newer ocaml

### PR DESCRIPTION
**Pull request by avsm**
cc @altgr 

e.g. https://ci.ocaml.io/log/saved/docker-run-41304521e481f263087c2b45aaca7647/063b86cc6aab49e319d4be80c18f6b7aeaab0b8c

```
# [57.1] Command failed: '/home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlc.opt' '-thread' '-o' './_obuild/ocaml-top/ocaml-top.byte' './_obuild/ocaml-top/sigint_unix.o' '-I' './_obuild/ocaml-top' '-I' './src' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-index/lib' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/lib' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/utils' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/lexer' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/lablgtk2' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml/compiler-libs' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml/unix.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml/compiler-libs/ocamlcommon.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/lablgtk2/lablgtk.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/lablgtk2/lablgtksourceview2.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/lexer/ocp-indent.lexer.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/utils/ocp-indent.utils.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/lib/ocp-indent.lib.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-index/lib/ocp-index-lib.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml/str.cma' '-custom' './_obuild/ocaml-top/tools.cmo' './_obuild/ocaml-top/cfg.cmo' './_obuild/ocaml-top/ocamlBuffer.cmo' './_obuild/ocaml-top/completion.cmo' './_obuild/ocaml-top/top.cmo' './_obuild/ocaml-top/topUi.cmo' './_obuild/ocaml-top/gui.cmo' './_obuild/ocaml-top/main.cmo'
# -- stderr for ./_obuild/ocaml-top/ocaml-top.byte --
# File "_none_", line 1:
# Error: Error while linking ./_obuild/ocaml-top/top.cmo:
# Reference to undefined global `Thread'
# 0.16s _obuild/ocaml-top/main.cmx                                       [ done ]
# 2 errors in 1.05s. 38 jobs (parallelism 3.1x), 50 files generated.
# Error log:
# Error:
# [57.1] '/home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlc.opt' '-thread' '-o' './_obuild/ocaml-top/ocaml-top.byte' './_obuild/ocaml-top/sigint_unix.o' '-I' './_obuild/ocaml-top' '-I' './src' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-index/lib' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/lib' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/utils' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/lexer' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/lablgtk2' '-I' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml/compiler-libs' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml/unix.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml/compiler-libs/ocamlcommon.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/lablgtk2/lablgtk.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/lablgtk2/lablgtksourceview2.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/lexer/ocp-indent.lexer.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/utils/ocp-indent.utils.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-indent/lib/ocp-indent.lib.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocp-index/lib/ocp-index-lib.cma' '/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml/str.cma' '-custom' './_obuild/ocaml-top/tools.cmo' './_obuild/ocaml-top/cfg.cmo' './_obuild/ocaml-top/ocamlBuffer.cmo' './_obuild/ocaml-top/completion.cmo' './_obuild/ocaml-top/top.cmo' './_obuild/ocaml-top/topUi.cmo' './_obuild/ocaml-top/gui.cmo' './_obuild/ocaml-top/main.cmo'
# 
# File "_none_", line 1:
# Error: Error while linking ./_obuild/ocaml-top/top.cmo:
# Reference to undefined global `Thread'
# 
# Error:
```

### CODE REVIEW

**Comment by dbuenzli** [comment]
This should be merged I'm seeing the error.

**Comment by dbuenzli** [comment]
Well in fact it doesn't work on macosx on 4.02.3 either. 

```
# opam-version 1.2.2
# os           darwin
# command      ocp-build ocaml-top
# path         /Users/dbuenzli/.opam/bla/build/ocaml-top.1.1.3
# compiler     4.02.3
# exit-code    2
# env-file     /Users/dbuenzli/.opam/bla/build/ocaml-top.1.1.3/ocaml-top-43050-b3b647.env
# stdout-file  /Users/dbuenzli/.opam/bla/build/ocaml-top.1.1.3/ocaml-top-43050-b3b647.out
# stderr-file  /Users/dbuenzli/.opam/bla/build/ocaml-top.1.1.3/ocaml-top-43050-b3b647.err
### stderr ###
# [...]
# Error log:
# Error:
# [57.1] '/Users/dbuenzli/.opam/bla/bin/ocamlc.opt' '-thread' '-o' './_obuild/ocaml-top/ocaml-top.byte' './_obuild/ocaml-top/sigint_unix.o' '-I' './_obuild/ocaml-top' '-I' './src' '-I' '/Users/dbuenzli/.opam/bla/lib/ocaml' '-I' '/Users/dbuenzli/.opam/bla/lib/ocp-index/lib' '-I' '/Users/dbuenzli/.opam/bla/lib/ocp-indent/lib' '-I' '/Users/dbuenzli/.opam/bla/lib/ocp-indent/utils' '-I' '/Users/dbuenzli/.opam/bla/lib/ocp-indent/lexer' '-I' '/Users/dbuenzli/.opam/bla/lib/lablgtk2' '-I' '/Users/dbuenzli/.opam/bla/lib/ocaml/compiler-libs' '/Users/dbuenzli/.opam/bla/lib/ocaml/unix.cma' '/Users/dbuenzli/.opam/bla/lib/ocaml/compiler-libs/ocamlcommon.cma' '/Users/dbuenzli/.opam/bla/lib/lablgtk2/lablgtk.cma' '/Users/dbuenzli/.opam/bla/lib/lablgtk2/lablgtksourceview2.cma' '/Users/dbuenzli/.opam/bla/lib/ocp-indent/lexer/ocp-indent.lexer.cma' '/Users/dbuenzli/.opam/bla/lib/ocp-indent/utils/ocp-indent.utils.cma' '/Users/dbuenzli/.opam/bla/lib/ocp-indent/lib/ocp-indent.lib.cma' '/Users/dbuenzli/.opam/bla/lib/ocp-index/lib/ocp-index-lib.cma' '/Users/dbuenzli/.opam/bla/lib/ocaml/str.cma' '-custom' './_obuild/ocaml-top/tools.cmo' './_obuild/ocaml-top/cfg.cmo' './_obuild/ocaml-top/ocamlBuffer.cmo' './_obuild/ocaml-top/completion.cmo' './_obuild/ocaml-top/top.cmo' './_obuild/ocaml-top/topUi.cmo' './_obuild/ocaml-top/gui.cmo' './_obuild/ocaml-top/main.cmo'
# 
# File "_none_", line 1:
# Error: Error while linking ./_obuild/ocaml-top/top.cmo:
# Reference to undefined global `Thread'
# 
# Error:
# rule 57: target ./_obuild/ocaml-top/ocaml-top.byte not built
```

**Comment by dbuenzli** [comment]
This is affecting users see #9773

**Comment by AltGr** [comment]
I've a version using `jbuilder` that should fix these issues; but it needs #9782 first. This can be merged in the meantime, thanks!

**Pull request merged**
