### PR TITLE
Package lmdb.0.1

### PR DESCRIPTION
**Pull request by Drup**
### `lmdb.0.1`
Bindings for LMDB, a fast in-file database with ACID transactions

---
* Homepage: https://github.com/Drup/ocaml-lmdb
* Source repo: git+https://github.com/Drup/ocaml-lmdb.git
* Bug tracker: https://github.com/Drup/ocaml-lmdb/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by Drup** [comment]
The library doesn't currently has any versioning for the underlying C library, and is likely to fail for distributions that use old versions of lmdb (debian, ubuntu, ...).

**Comment by Drup** [comment]
So, Centos doesn't have a package for lmdb, and for some reason, alpine doesn't install the `.h`.

**Comment by Drup** [comment]
As far as I'm concerned, this is as green as it will ever be.

**Comment by hannesm** [comment]
thanks

**Pull request merged**
