### PR TITLE
Async_extended v0.9.0 and it's dependencies

### PR DESCRIPTION
**Pull request by diml**

### CODE REVIEW

**Comment by diml** [comment]
The travis build failure are due to the time limits. Most of the datakit ones seems to be due to camlzip:

```
=-=- camlzip.1.07 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing. `opam depext camlzip.1.07' may help you find the correct installation for your system.
```

**Comment by avsm** [comment]
This can be merged once the linked PRs are merged with upper bounds

**Comment by avsm** [comment]
I filed https://github.com/janestreet/core_extended/issues/15 for the Alpine breakage but am inclined to merge this; do you think a patch is possible for Alpine support @diml?

**Comment by avsm** [comment]
Also it would be useful to have `ocaml-version < 4.05.0` constraints due to
```
# File "src/core_unix.mli", line 398, characters 0-858:
# Error: This variant or record definition does not match that of type
#          Unix.open_flag
#        The field O_KEEPEXEC is only present in the original definition.
```

**Comment by diml** [comment]
For core_extended yh we need to start using configurator to avoid future issues. I'll prepare a minor release for the core issue

**Pull request merged**
