### PR TITLE
Package quick_print.0.11

### PR DESCRIPTION
**Pull request by mikefreno**
### `quick_print.0.11`
Quick and easy printing for lists, arrays, etc
Allows quick printing for lists, arrays, Hashtables etc. Useful for learning/ quick debugging

---
* Homepage: https://github.com/mikefreno/quick_print
* Source repo: git+https://github.com/mikefreno/quick_print.git
* Bug tracker: https://github.com/mikefreno/quick_print/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by haochenx** [comment]
Thanks!

The opam file looks good to me and it seems that the CI machine is having a hard time.
Let's wait for a bit longer to see whether CI can conclude.

Just wondering: is there a particular reason you chose the version number 0.11?

**Comment by mikefreno** [comment]
> Thanks!
> 
> 
> 
> The opam file looks good to me and it seems that the CI machine is having a hard time.
> 
> Let's wait for a bit longer to see whether CI can conclude.
> 
> 
> 
> Just wondering: is there a particular reason you chose the version number 0.11?

No good reason for the version number, my mind was on other things when I tagged it. Meant to do 0.1.1 but it's not terribly important so just rolling with it.

**Comment by haochenx** [comment]
The CI itself seems to have some troubles with a platforms (s390 and macOS) but I don't think they will find anything blocking. Let's wait the CI for a little longer but IMO this PR is mergeable even if the CI cannot finish.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
