### PR TITLE
add xtmpl 0.13.0, higlo 0.5, ojs-base 0.4.0, stog{,-writing,-rdf} 0.16.0

### PR DESCRIPTION
**Pull request by zoggy**

### CODE REVIEW

**Comment by zoggy** [comment]
Is there some tool to convert opam files from version 1 into version 1.2 ?

**Comment by zoggy** [comment]
The CI process does not take into account new archives immedialtely, so commits 861e36 failed. Commit 09c4ebf restarts the tests but (failed) job https://travis-ci.org/ocaml/opam-repository/jobs/93349501 has been used instead of a new one.

**Comment by zoggy** [comment]
What am I supposed to do now ? Some checks fail by timeout. Regarding opam file format, do I have to convert all by hand ?

**Comment by zoggy** [comment]
Ping ?

**Comment by dsheets** [comment]
Yes, you need to convert the opam files manually. It should take only a minute or two per file. You can use `opam lint` to check their correctness. I recommend using `opam-publish` in the future for submitting package publications. It would also be helpful to separate the packages into individual pull requests so they can be tested independently and the test system will be less likely to time out. If there are dependencies between new packages, you can either submit them in order or submit the dependency stack for the higher-level packages.

**Comment by zoggy** [comment]
Thanks for the opam lint tip. Regarding making one pull-request per package, I was hoping to win some time not having to wait for each one to be accepted before submitting the following one.
I'll have a look at opam-publish.

**Comment by dsheets** [comment]
Regarding dependent requests, you can make all the requests simultaneously and then once the dependency requests are merged, the tests for the dependent request can be re-run.

**Comment by zoggy** [comment]
Ok, I'll go for opam-publish for my next release. Thanks for the tips.

**Comment by dsheets** [comment]
Failures are timeouts.

**Pull request merged**
