### PR TITLE
Package process_limits.1.5.5

### PR DESCRIPTION
**Pull request by aryx**
### `process_limits.1.5.5`
Setting time and memory limits for your program
This is a small library of utilities used by Semgrep and
a few other projects developed at r2c to control the
time and memory used by Semgrep.

---
* Homepage: https://semgrep.dev
* Source repo: git+https://github.com/returntocorp/semgrep
* Bug tracker: https://github.com/returntocorp/semgrep/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by aryx** [comment]
The error seems unrelated @kit-ty-kate 
```
2023-01-25 20:51.39: Got resource from pool OCluster
Building on i7-worker-03
fatal: Unable to create '/private/var/lib/ocluster-worker/git/opam-repository.git-b322f7b18d276db68487afc3dfc5a5befdd45818/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git-reset failed with exit-code 128
2023-01-25 20:51.40: Job failed: Failed: Build failed2023-01-25 20:51.39: Got resource from pool OCluster
Building on i7-worker-03
fatal: Unable to create '/private/var/lib/ocluster-worker/git/opam-repository.git-b322f7b18d276db68487afc3dfc5a5befdd45818/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git-reset failed with exit-code 128
2023-01-25 20:51.40: Job failed: Failed: Build failed
```

**Comment by aryx** [comment]
seems stuck in macos CI runners

**Comment by aryx** [comment]
still stuck, even if I clicked on 'rebuild all' @kit-ty-kate

**Comment by kit-ty-kate** [comment]
All green. Thanks!

**Pull request merged**
