### PR TITLE
Enable again tests on oasis 0.4.8

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
@AltGr Doesn't writing `build & test` means that the dependency is required _both_ for `build` and also for `test` (a logical "_or_" for the predicate)?

**Comment by gildor478** [comment]
Please fix the dev-repo, it should be "git://github.com/ocaml/oasis.git#opam/testing"

**Comment by Chris00** [comment]
On 2016-12-08, Sylvain Le Gall wrote:
>
> Please fix the dev-repo, it should be 
> "git://github.com/ocaml/oasis.git#opam/testing"

Done.  Any reason why it is not in sync with `_oasis`?

**Comment by gildor478** [comment]
Your question is: why the branch opam/testing is a few version away from master for the repository git://github.com/ocaml/oasis.git ?

If this is your question, the answer is:
The job to promote master (-> opam/unstable) -> opam/testing was not run yesterday and has only been triggered this morning. It is actually still running (it builds all the reverse dependencies of OASIS). If everything is good, it will be promoted in a few hours.

**Comment by Chris00** [comment]
My question was more: if you insist that `opam/testing` is the right dev-repo for OPAM, why doesn't the `_oasis` file in the tarball says the same (in the `SourceRepository`).

**Comment by gildor478** [comment]
See oasis2opam#32

**Comment by Chris00** [comment]
@gildor478 The bug report field is declared in `opam` as
```
bug-reports: "http://oasis.forge.ocamlcore.org/"
```
but, given the `_oasis` one, should be
```
bug-reports: "https://forge.ocamlcore.org/tracker/?func=add&group_id=54&atid=291"
```
If you agree, I'll update this PR (the latest `oasis2opam` uses `BugReports` when present).

**Comment by gildor478** [comment]
Yes, thanks.

**Comment by Chris00** [comment]
Ping?

**Comment by gildor478** [comment]
@Chris00 sorry to ask but who are you pinging (me or opam-repository maintainer?)

**Comment by avsm** [comment]
Sorry, not had a chance to test this over the holidays. Will do shortly.

**Pull request merged**
