### PR TITLE
qfs.0.6 - via opam-publish

### PR DESCRIPTION
**Pull request by ygrek**
bindings to libqfs - client library to access QFS
QFS is a distributed fault-tolerant filesystem by Quantcast

---
- Homepage: https://github.com/ahrefs/ocaml-qfs
- Source repo: git://github.com/ahrefs/ocaml-qfs.git
- Bug tracker: https://github.com/ahrefs/ocaml-qfs/issues

---
### opam-lint failures
- **WARNING** 92 extra file "findlib"

---

Pull-request generated by opam-publish v0.3.2

### CODE REVIEW

**Comment by dsheets** [comment]
It looks like this package is trying to run `sudo` and install things globally:

```
+sudo ln -s /home/travis/build/ocaml/opam-repository/qfs/build/release/include/kfs /usr/include/kfs
+pwd
+sudo cp /home/travis/build/ocaml/opam-repository/qfs/build/release/lib/*.so /usr/local/lib
cp: cannot stat ‘/home/travis/build/ocaml/opam-repository/qfs/build/release/lib/*.so’: No such file or directory
Command "curl -L \"https://gist.githubusercontent.com/ygrek/7bb217d6ab7b25a765b7/raw\" | sh -ex -" failed
```

Is it possible to use regular opam installation mechanisms?

**Comment by ygrek** [comment]
This is a depext install script that builds qfs from source and installs shared objects - I am not sure it is possible to do without using ldconfig which requires root. This is the same script that was used for all previous builds btw. I haven't fluly investigated why build fails yet.

**Comment by ygrek** [comment]
qfs Makefile was changed to build debug target, while script assumed release. Fixed build script, please trigger the build again

**Comment by ygrek** [comment]
build failure is due to Mac OS, I have no idea how to build libqfs there but it should possible so I don't want to blacklist it in opam file

**Comment by yallop** [comment]
`qfs` is [apparently not in homebrew yet](https://github.com/Homebrew/homebrew-core/pull/896), but since it can probably be built from source on OS X I'm happy to merge this.

**Comment by ygrek** [comment]
It builds fine on travis on linux (apparently it allows sudo) and the problem was not with sudo, but the path in libqfs build script was wrong. Even if sudo is disallowed - it is not the problem for the bindings, but for the libqfs build itself (it has to be somehow made available for linking system-wide and it is system administrator problem, beyond the scope of the bindings).
Please merge.

**Comment by dsheets** [comment]
We would like to merge this. Could you please include a `failure` `post-messages` field which describes the dependency and provides a link to a script which will install the dependency? We're really not keen on having `source` depexts in opam-repository especially if they require superuser privileges. Thank you and sorry for the extreme delay.

**Comment by ygrek** [comment]
Sorry for the late action.

(Actually I would be glad to  remove "source" "linux" entry from depext altogether - I don't feel comfortable encouraging users to run script downloaded behind their back from internet)

**Comment by ygrek** [comment]
anything else to do here?

**Comment by ygrek** [comment]
ping..

**Comment by yallop** [comment]
@dsheets: are you happy for this to be merged?

**Comment by dsheets** [comment]
Could you remove the `"source" "linux"` entry in `depexts`? It still references a URL which includes `sudo` commands.

**Comment by ygrek** [comment]
done

**Comment by dsheets** [comment]
Great, thanks! Sorry for the delay.

**Pull request merged**
