### PR TITLE
Package mccs.1.1+12

### PR DESCRIPTION
**Pull request by AltGr**
### `mccs.1.1+12`
MCCS (which stands for Multi Criteria CUDF Solver) is a CUDF problem solver
developed at UNS during the European MANCOOSI project

---
* Homepage: http://www.i3s.unice.fr/~cpjm/misc/
* Source repo: git+https://github.com/AltGr/ocaml-mccs.git
* Bug tracker: https://github.com/AltGr/ocaml-mccs/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Are these GCC warning expected?
```
- src/glpk/misc/wclique1.c: In function '_glp_wclique1':
- src/glpk/misc/wclique1.c:111:7: warning: 'memset' specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
- src/glpk/misc/wclique1.c:113:7: warning: 'memset' specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
```

**Comment by kit-ty-kate** [comment]
These have been reported in https://github.com/AltGr/ocaml-mccs/issues/31

**Comment by kit-ty-kate** [comment]
Same with https://github.com/AltGr/ocaml-mccs/pull/30 but that's more cosmetic

**Comment by kit-ty-kate** [comment]
I'll ignore those warnings as `mccs.1.1+11` had the same issues. However could you return the fixes made to the opam file upstream?

Thanks a lot!

**Comment by AltGr** [comment]
Ok, disabled the warning in mccs (the issue would have to be reported to upstream GLPK, but it seems to me like a spurious warning)

**Pull request merged**
