### PR TITLE
Package sedlex.3.0

### PR DESCRIPTION
**Pull request by toots**
### `sedlex.3.0`
An OCaml lexer generator for Unicode
sedlex is a lexer generator for OCaml. It is similar to ocamllex, but supports
Unicode. Unlike ocamllex, sedlex allows lexer specifications within regular
OCaml source files. Lexing specific constructs are provided via a ppx syntax
extension.

---
* Homepage: https://github.com/ocaml-community/sedlex
* Source repo: git+https://github.com/ocaml-community/sedlex.git
* Bug tracker: https://github.com/ocaml-community/sedlex/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mseri** [comment]
Do the failing revdeps require upper bounds on the new sedlex?

**Comment by mseri** [comment]
The upper bound have been added to #21401 as well as the incorrect lower bound in the gen dependency

**Comment by toots** [comment]
Thanks for checking this out!

**Comment by jberdine** [comment]
Is the changed bound on ocaml due to the removal of Genlex and Stream? If so, it would be better to still allow 4.14.0 since they are still there, but won't be in 4.14.1.

**Comment by Atry** [comment]
This PR is a regression. I think it's better to revert it. I created #21405.

**Pull request merged**
