### PR TITLE
Package teash.0.1.0

### PR DESCRIPTION
**Pull request by neochrome**
### `teash.0.1.0`

TEA for the shell

A library for developing shell/terminal applications using an
interpretation of The Elm Architecture.

---
* Homepage: https://github.com/neochrome/teash
* Source repo: git+https://github.com/neochrome/teash.git
* Bug tracker: https://github.com/neochrome/teash/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by neochrome** [comment]
So it seems like the osx build failed for ssl reasons?

https://travis-ci.org/ocaml/opam-repository/jobs/428114277
> <><>Gathering sources><><><><><><><><><><><><><><><><><><><><><><><><><><>🐫
: http][ERROR] The sources of the following couldn't be obtained, aborting:
          - teash.0.1.0:
            Failure("openssl error")
'opam install -t -v teash.0.1.0' failed.

Does anyone know how to proceed with this?

**Comment by mseri** [comment]
I am rerunning the test, this could be just an infrastructure issue.

Please announce the package on the [discourse forum](discuss.ocaml.org) once merged, there is a community `Category` and an `announce` tag for this.

**Comment by mseri** [comment]
The error seems to be raised by https://github.com/ocaml/opam/blob/c35eb977d19457d3f13b31c1aa60de4fb210865d/src/core/opamHash.ml#L96 but the hash looks good to me

**Comment by neochrome** [comment]
@mseri I'll make sure to make an announcement once it's sorted. :+1: 

Is there anything obvious that I could have gotten wrong in the package file or something? This is my very first contribution to the OCaml community and any pointers to get me in the right direction is much appreciated.

**Comment by mseri** [comment]
One thing that needs to be fixed, is that the package is being published on the opam-2.0.0 branch. But I would like this PR to stay open to see if the `openssl error` is a known issue in opam2 or if it needs to be raised as such.

Can you please open a new PR, using opam-publish for opam 1.2 (the opam file will be slightly different), and targeting the `master` branch?

**Comment by mseri** [comment]
> I could have go at it - I went with the 2.0.0 branch because I thought the 1.2 one was soon being deprecated or something :)

Thanks. We should move "soon" to opam 2.0.0, in the meanwhile the 2.0.0 opam files are automatically updated/generated when we merge changes in the master branch

**Comment by rjbou** [comment]
Didn't saw it before, but It reminds me PR https://github.com/ocaml/opam/pull/3516 which point that `openssl sha512` is not available on some macOS versions.

**Comment by neochrome** [comment]
oh, I'm so sorry - I think I've managed to update this PR for some reason.
I switched to `opam-publish.1.2`, fixed the opam file, and submitted - but it seems it hijacked this PR :(

**Comment by mseri** [comment]
It's ok, don't worry

**Comment by rjbou** [comment]
Don't have a macOS to test, but after looking more closely, seems to be the case: openssl found & error on openssl output & exit code = 0 are the condition to raise this error, and it is also  the behaviour of `openssl 512` on macos according the previous PR. Fix pushed.
Thanks for the notif!

**Comment by kit-ty-kate** [comment]
Constraints to `lwt`, `lwt_ppx` and `notty` seem pretty harsh. Any reasons why?

**Comment by neochrome** [comment]
> Constraints to `lwt`, `lwt_ppx` and `notty` seem pretty harsh. Any reasons why?

Hmm, that should probably be `>=`, not just `=`, I'll have to fix that - thanks for spotting!

**Comment by neochrome** [comment]
btw changes like that - what is the preferred way - update the existing version/PR or bump the version and re-submit?

**Comment by kit-ty-kate** [comment]
> btw, with changes like that - what is the preferred way - update the existing version/PR or bump the version and re-submit?

this doesn't change the package itself at all so the preferred way is to update the existing PR and report upstream

**Comment by mseri** [comment]
Thanks

**Pull request merged**
