### PR TITLE
conf-expat: Add freebsd support

### PR DESCRIPTION
**Pull request by sacerdot**
freebsd should work as well

### CODE REVIEW

**Comment by sacerdot** [comment]
All tests pass, but I don't know if the PR actually fixes the problem with ocaml-expat not compiling on freebsd. How to force recompilation of ocaml-expat in a clean way?

**Comment by haochenx** [comment]
Thank you for the PR!

Actually, for conf packages, we'd rather patch the existing version (`packages/conf-expat/conf-expat.1/opam` in this case) rather than creating a new version.

Could you please modify the PR to do that?

**Comment by sacerdot** [comment]
@haochenx done, thank you!

**Review by haochenx — APPROVED** [review]
The CI infrastructure seems to have some trouble.. But I believe this PR is a pure improvement (and the CI ran successfully on the previous commit.) Therefore this PR looks perfectly good to me.

**Comment by avsm** [comment]
Thanks!

**Pull request merged**
