### PR TITLE
OCaml 4.12.0, and 4.11.2

### PR DESCRIPTION
**Pull request by Octachron**
This PR contains the usual packages for 4.11.2: base,system, src, and all the variants (except BER). The `4.12.0` commit uses the new packaging scheme: base, system, *one* variant, src, manual and the virtual package for `4.12.1` .

The 4.12.0+options variant package is a merge between the 4.11 template and the pre-release template, it probably warrants more scrutiny.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Something weird is happening for `ocaml.4.11.2`:
```
#=== ERROR while compiling ocaml.4.11.2 =======================================#
# context              2.1.0~beta4 | linux/arm32 | ocaml-base-compiler.4.11.2 | file:///src
# path                 ~/.opam/4.11/.opam-switch/build/ocaml.4.11.2
# command              ~/.opam/4.11/bin/ocaml /home/opam/.opam/4.11/share/ocaml-config/gen_ocaml_config.ml 4.11.2 ocaml
# exit-code            1
# env-file             ~/.opam/log/ocaml-19-4a3793.env
# output-file          ~/.opam/log/ocaml-19-4a3793.out
### output ###
# OCaml version mismatch: 4.11.1, expected 4.11.2
```

**Comment by kit-ty-kate** [comment]
There is also a number of checksum failures:
```
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+spacetime:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+no-flat-float-array:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+musl+static+flambda:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+musl+flambda:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+fp+flambda:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+fp:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+flambda+no-flat-float-array:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+flambda:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+default-unsafe-string:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+bytecode-only:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+afl:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-variants.4.11.2+32bit:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-src.4.11.2:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
2021-02-24 14:50.24: Error in ocaml-base-compiler.4.11.2:              error 60: Upstream check failed: "The archive doesn't match checksum: { sha256=cd3cd55d465028b161c8c33bafc14ee6ae1d91b5efe51098350f8e8a5f454baf }."
```

**Comment by Octachron** [comment]
I failed to update the 4.11.2 checksum... I am not completely sure how this triggered the version mismatch on `ocaml-base-compiler` but this seems fixed for me locally.

**Comment by kit-ty-kate** [comment]
Indeed, it looks good now. Thanks a lot!

**Pull request merged**
