### PR TITLE
git-{mirage, unix}: lower bound on mirage-clock

### PR DESCRIPTION
**Pull request by mseri**
From the lower bound checks in https://github.com/ocaml/opam-repository/pull/20304

### CODE REVIEW

**Comment by mseri** [comment]
@dinosaure I mimicked what you did in the other PR and knowing the failure on 3.3, I added the lower bounds to all packages since. Let me know if I need to drop some of them

**Comment by mseri** [comment]
Looks like it is not enough:
```
#=== ERROR while compiling git-unix.3.3.2 =====================================#
# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(https://github.com/mirage/ocaml-git/releases/download/3.3.2/git-3.3.2.tbz)
# path                 ~/.opam/4.08/.opam-switch/build/git-unix.3.3.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p git-unix -j 31
# exit-code            1
# env-file             ~/.opam/log/git-unix-17531-37c189.env
# output-file          ~/.opam/log/git-unix-17531-37c189.out
### output ###
# File "/home/opam/.opam/4.08/lib/mirage-profile/mirage-profile.dune", line 1, characters 0-0:
# Warning: .dune files are ignored since 2.0. Reinstall the library with dune
# >= 2.0 to get rid of this warning and enable support for the subsystem this
# library provides.
#     ocamlopt src/git-top/.git_top.objs/native/git_top.{cmx,o}
# File "_none_", line 1:
# Warning 58: no cmx file was found in path for module Toploop, and its interface was not compiled with -opaque
#       ocamlc src/git-unix/ogit-fetch/.main.eobjs/byte/dune__exe__Main.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git-unix/ogit-fetch/.main.eobjs/byte -I /home/opam/.opam/4.08/lib/awa -I /home/opam/.opam/4.08/lib/awa-mirage -I /home/opam/.opam/4.08/lib/cmdliner -I /home/opam/.opam/4.08/lib/cohttp-lwt-unix -I /home/opam/.opam/4.08/lib/domain-name -I /home/opam/.opam/4.08/lib/fmt -I /home/opam/.opam/4.08/lib/fpath -I /home/opam/.opam/4.08/lib/git -I /home/opam/.opam/4.08/lib/git-cohttp-unix -I /home/opam/.opam/4.08/lib/git/nss/git -I /home/opam/.opam/4.08/lib/ipaddr -I /home/opam/.opam/4.08/lib/ipaddr/unix -I /home/opam/.opam/4.08/lib/logs -I /home/opam/.opam/4.08/lib/lwt -I /home/opam/.opam/4.08/lib/lwt/unix -I /home/opam/.opam/4.08/lib/mimic -I /home/opam/.opam/4.08/lib/mirage-clock -I /home/opam/.opam/4.08/lib/mirage-clock-unix -I /home/opam/.opam/4.08/lib/mirage-flow -I /home/opam/.opam/4.08/lib/mtime -I /home/opam/.opam/4.08/lib/mtime/os -I /home/opam/.opam/4.08/lib/result -I /home/opam/.opam/4.08/lib/rresult -I /home/opam/.opam/4.08/lib/tcpip/stack-socket -I src/git-unix/.git_unix.objs/byte -I src/git-unix/.git_unix.objs/native -no-alias-deps -o src/git-unix/ogit-fetch/.main.eobjs/byte/dune__exe__Main.cmo -c -impl src/git-unix/ogit-fetch/main.ml)
# File "src/git-unix/ogit-fetch/main.ml", line 98, characters 57-63:
# 98 |   include Awa_mirage.Make (Tcpip_stack_socket.V4V6.TCP) (Mclock)
#                                                               ^^^^^^
# Error: Unbound module Mclock
```

**Comment by dinosaure** [comment]
It requires `mirage-clock-unix.4.0.0` too for `git-unix` :+1:.

**Comment by mseri** [comment]
It is already installing mirage-clock and mirage-clock-unix 4.0.0 in the lower bounds check, but still fails

**Comment by mseri** [comment]
Have a look at the failing lower bounds in https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/c50c6adf42d631ff6b1af6721fe26b739a8f4221

**Comment by mseri** [comment]
Failures are all from the infrastructure, looks good now

**Pull request merged**
