### PR TITLE
cppo_ocamlbuild: Remove failing tests

### PR DESCRIPTION
**Pull request by jpdeplaix**
Related to #11428 and #11424

### CODE REVIEW

**Comment by rgrinberg** [comment]
I don't see how this is correct. cppo_ocamlbuild doesn't even have tests so this should be a no-op.

**Comment by jpdeplaix** [comment]
Mmh, I'm not sure. How do you explain this then ? https://travis-ci.org/ocaml/opam-repository/jobs/343465355

**Comment by yomimono** [comment]
> cppo_ocamlbuild doesn't even have tests

But it shares a repository with `cppo` which does have them, and I get different behavior from `jbuilder runtest -p cppo_ocamlbuild` in a directory cloned from that repo depending on my `jbuilder` version:
 
```
$ jbuilder --version
1.0+beta18-8-g032cb62af
~/cppo_ocamlbuild$ jbuilder runtest -p cppo_ocamlbuild --verbose
# Workspace root: /home/user/cppo_ocamlbuild
Running[0]: /home/user/.opam/4.05.0+afl/bin/ocamlfind printconf path > /tmp/jbuilda4fb5e.output
Running[1]: /home/user/.opam/4.05.0+afl/bin/ocamlc.opt -config > /tmp/jbuild66945a.output
# # Workspace root: /home/user/cppo_ocamlbuild
# Jbuilder context:
#  ((name default)
#   (kind default)
#   (merlin true)
#   (for_host ())
#   (build_dir _build/default)
#   (toplevel_path (/home/user/.opam/4.05.0+afl/lib/toplevel))
#   (ocaml_bin /home/user/.opam/4.05.0+afl/bin)
#   (ocaml /home/user/.opam/4.05.0+afl/bin/ocaml)
#   (ocamlc /home/user/.opam/4.05.0+afl/bin/ocamlc.opt)
#   (ocamlopt (/home/user/.opam/4.05.0+afl/bin/ocamlopt.opt))
#   (ocamldep /home/user/.opam/4.05.0+afl/bin/ocamldep.opt)
#   (ocamlmklib /home/user/.opam/4.05.0+afl/bin/ocamlmklib.opt)
#   (env ())
#   (findlib_path (/home/user/.opam/4.05.0+afl/lib))
#   (arch_sixtyfour true)
#   (natdynlink_supported true)
#   (opam_vars ())
#   (ocamlc_config
#    ((architecture amd64)
#     (asm as)
#     (asm_cfi_supported true)
#     (ast_impl_magic_number Caml1999M020)
#     (ast_intf_magic_number Caml1999N018)
#     (bytecomp_c_compiler
#      gcc -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC)
#     (bytecomp_c_libraries -lm  -ldl  -lpthread                  )
#     (cc_profile -pg)
#     (ccomp_type cc)
#     (cma_magic_number Caml1999A012)
#     (cmi_magic_number Caml1999I021)
#     (cmo_magic_number Caml1999O011)
#     (cmt_magic_number Caml2012T009)
#     (cmx_magic_number Caml1999Y015)
#     (cmxa_magic_number Caml1999Z014)
#     (cmxs_magic_number Caml2007D002)
#     (default_executable_name a.out)
#     (exec_magic_number Caml1999X011)
#     (ext_asm .s)
#     (ext_dll .so)
#     (ext_exe "")
#     (ext_lib .a)
#     (ext_obj .o)
#     (flambda false)
#     (host x86_64-unknown-linux-gnu)
#     (int_size 63)
#     (model default)
#     (native_c_compiler
#      gcc -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT)
#     (native_c_libraries -lm  -ldl)
#     (native_pack_linker ld -r  -o )
#     (os_type Unix)
#     (profiling true)
#     (ranlib ranlib)
#     (safe_string false)
#     (spacetime false)
#     (standard_library /home/user/.opam/4.05.0+afl/lib/ocaml)
#     (standard_library_default /home/user/.opam/4.05.0+afl/lib/ocaml)
#     (standard_runtime /home/user/.opam/4.05.0+afl/bin/ocamlrun)
#     (system linux)
#     (systhread_supported true)
#     (target x86_64-unknown-linux-gnu)
#     (version 4.05.0)
#     (with_frame_pointers false)
#     (word_size 64)))
#   (which
#    ((ocaml (/home/user/.opam/4.05.0+afl/bin/ocaml))
#     (ocamlc (/home/user/.opam/4.05.0+afl/bin/ocamlc.opt))
#     (ocamlfind (/home/user/.opam/4.05.0+afl/bin/ocamlfind)))))
$
```

vs 

```
$ jbuilder --version
1.0+beta17
$ jbuilder runtest -p cppo_ocamlbuild
        cppo test/loc.out
        cppo test/cond.out
        cppo test/unmatched.out
        cppo test/paren_arg.out
        cppo test/version.out
        cppo test/tuple.out
        cppo test/comments.out
        cppo test/ext.out
        cppo alias test/runtest
```

**Comment by rgrinberg** [comment]
@yomimono Yeah, that's a bit weird. I wonder why beta18 is smart enough to detect that the tests don't belong to the package but beta17 isn't. So we can either proceed with this PR or bump minimum dependency on jbuilder beta18.

I suggest we just proceed with this PR then. I'll investigate the difference in behavior between the 2 versions of jbuilder.

**Pull request merged**
