### PR TITLE
New release of jbuilder, base and stdio

### PR DESCRIPTION
**Pull request by diml**
jbuilder 1.0+beta1
base     0.2.alpha1
stdio    0.2.alpha1

### CODE REVIEW

**Comment by diml** [comment]
I removed the 0.1.alpha1 versions. I don't understand why they failed and I'm not interested in maintaining them

**Comment by avsm** [comment]
They failed in the reverse dependency test -- this can be safely ignored.

**Comment by diml** [comment]
@avsm should I restore the 0.1.alpha1 versions or can this PR be merged as it?

**Comment by avsm** [comment]
it can be merged :)

**Pull request merged**
