### PR TITLE
added spotlib.4.0.3

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks good. Do you actually need to depend on ocamlfind however? Jbuilder doesn't it and only depends on it to avoid race conditions when both are installed at the same time.

**Comment by camlspotter** [comment]
Is jbuilder ocamlfind free?  I did not know it!

**Comment by rgrinberg** [comment]
Yes, jbuilder reimplements parsing META files on its own. I should also say that it will run `ocamlfind printconf` if it's available to get some variables, whenever `opam` isn't available. But ocamlfind is totally unnecessary to build anything.

**Comment by camlspotter** [comment]
Thanks, cool!

**Pull request merged**
