### PR TITLE
Package ezjs_min.0.2

### PR DESCRIPTION
**Pull request by ocpmax**
### `ezjs_min.0.2`
A bunch of js_of_ocaml shortcuts
A bunch of js_of_ocaml shortcuts

---
* Homepage: https://github.com/ocamlpro/ezjs_min
* Source repo: git+https://github.com/ocamlpro/ezjs_min.git
* Bug tracker: https://github.com/ocamlpro/ezjs_min/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There was an issue in `ezjs_fetch`:
```
#=== ERROR while compiling ezjs_fetch.0.1 =====================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.11.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.11/.opam-switch/build/ezjs_fetch.0.1
# command              ~/.opam/4.11/bin/dune build -p ezjs_fetch -j 72 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/ezjs_fetch-25-865888.env
# output-file          ~/.opam/log/ezjs_fetch-25-865888.out
### output ###
#       ocamlc src/.ezjs_fetch.objs/byte/ezjs_fetch__Fetch.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.11/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.ezjs_fetch.objs/byte -I /home/opam/.opam/4.11/lib/ezjs_min -I /home/opam/.opam/4.11/lib/js_of_ocaml -I /home/opam/.opam/4.11/lib/stdlib-shims -I /home/opam/.opam/4.11/lib/uchar -no-alias-deps -open Ezjs_fetch -o src/.ezjs_fetch.objs/byte/ezjs_fetch__Fetch.cmo -c -impl src/fetch.pp.ml)
# File "src/fetch.ml", line 208, characters 17-25:
# 208 | let (>>=?) x f = Lwt.bind x @@ function
#                        ^^^^^^^^
# Error: Unbound module Lwt
```
lwt was not an explicitly dependency and was pull from this package, however now that lwt is an optional dependency the package failed. I fixed this but could you return that fix upstream if you have the rights on the `ezjs_fetch` repository?

**Comment by mseri** [comment]
I think the ezjs_fetch  package is not linking against lwt

**Comment by ocpmax** [comment]
I fixed the ezjs_fetch repository with the ezjs_min < 0.2 dependency.
I will release ezjs_fetch.0.2 compatible with ezjs_min.0.2

**Comment by kit-ty-kate** [comment]
All green. Thanks!

**Pull request merged**
