### PR TITLE
latest dolog

### PR DESCRIPTION
**Pull request by UnixJunkie**
I don't want current users to be impacted by the change in the interface
so I added a version constraint to current users

### CODE REVIEW

**Comment by samoht** [comment]
Did you check that the new version breaks with all of these packages?

**Comment by UnixJunkie** [comment]
No, but there was an interface change so it might.

**Comment by samoht** [comment]
I would rather not change the metada for my packages then: upper-bound constraint caused the "Cabal" hell where it is very hard to co-install large sets of packages together. The metada in opam-repository aims to represent the minimal constraint possible to make most of the package compile together: please do not add arbitrary constraint there.

**Comment by UnixJunkie** [comment]
OK, I will submit the new package alone then.

**Comment by UnixJunkie** [comment]
This pull request should be ignored, the correct one is there:
https://github.com/ocaml/opam-repository/pull/4976

**Pull request closed without merging**
