### PR TITLE
Ctypes 0.4.0 iocaml fix

### PR DESCRIPTION
**Pull request by yallop**
See #3719.

/cc @andrewray

### CODE REVIEW

**Comment by avsm** [comment]
odd...

```
# ocamlfind: Package `iocaml' not found
```

**Comment by andrewray** [comment]
Hmmm....some of the older iocaml versions are not working anymore (they need various constraints to older packages).  

In particular this one is installing; iocaml-kernel.0.4.6 and iocaml.0.4.3 which are not compatible with each other (around 0.4.4 the iocaml ocamlfind package got renamed to iocaml-kernel due to some opam/ocamlfind package name conflict issues).

I can either try to fix all the old packages, or we could get rid of everything below 0.4.6.

**Comment by avsm** [comment]
Just adding conflicts (even over-generous ones) would be preferable to deleting the older versions, as we often use the full package corpus for static analysis purposes.

In this case, one conflict on iocaml-kernel.0.4.6 and iocaml.0.4.3 sounds like it'll fix a bunch of problems..

**Comment by yallop** [comment]
I've tightened the constraints to tie iocaml and iocaml-kernel 0.4.0 together, and similarly for 0.4.3 (bc9e786).  I've also fixed a js_of_ocaml/lwt dependency problem (f21afcb).  The remaining problems (e.g. [Job 6086.8](https://travis-ci.org/ocaml/opam-repository/jobs/54741023)) seem to be due to zmq installation problems unrelated to this change.

**Comment by andrewray** [comment]
Thanks for the fixes Jeremy.  I've gone through and tried to fix all the remaining issues in #3768

**Comment by yallop** [comment]
> I've also fixed a js_of_ocaml/lwt dependency problem (f21afcb).

/cc @hhugo @drup

**Comment by hhugo** [comment]
ack. updated upstream

**Pull request merged**
