### PR TITLE
Big new year cleanup

### PR DESCRIPTION
**Pull request by AltGr**
This is probably not to be merged as is, but may be useful to open some discussions, and make some benches and tests.

What this patch does is remove any package that
- has a version in the form 'MAJOR.MINOR.PATCH'
- is the non-latest patch revision of the non-latest minor revision

In other words, we keep only the latest patch revision of all versions but the current one.

For example, if you have 1.1.0, 1.2.1, 1.2.2, 1.3.0 and 1.3.1, only 1.2.1 will be removed.

### CODE REVIEW

**Comment by AltGr** [comment]
Interesting fact that this removed 17 packages that were already not installable :)
Seems that this doesn't work very well with Janestreet's versionning scheme though.

And this is very rough in many areas. For example, quick testing revealed like `magic-mime` broke compatibility with OCaml 4.02.3 in patch version 1.0.1, meaning that with the cleanup older compilers will get much older versions than necessary.

**Comment by jpdeplaix** [comment]
That sounds like a nice thing to do ! ❤️ 
One question I would have however is: how `opam switch import` is handled with OPAM 2.0 if it tries to install deleted packages ? Right now OPAM 1.2.2 just prints a warning which seems rather limited.

**Comment by avsm** [comment]
I definitely think these should *not* be deleted, but moved to another opam remote (with the git history) for archival.  This way patch releases can be accessed if necessary for historical releases.

**Comment by hannesm** [comment]
TBH I'm not sure which way is easier: (a) trying to figure out which bits and pieces to remove from the main opam-repository and leave everything in place (b) start a new repo from scratch with (1) opam 2.0 and (2) ocaml 4.06 and start an initially empty repository, pick only libraries which are requested (and have 4.06 support) in their latest release.  at point X, switch X to opam-repository and archive opam-repository.  certainly we can also move forward with removing patch releases, but since there is no common semantic versioning, some packages may introduce (as discovered by altgr) new dependencies / bump ocaml support / ...

maybe in the same effort of (b) we could formulate properties on how to get your package into that well-maintained repository (maybe code coverage? documentation has to exist? https://github.com/mirage/mirage-www/pull/562 has a list of ideas from the mirage community).  I'm still not sure whether (b) is a good goal, but certainly getting rid of releases is worthwhile in the long run.

i'm working on reviving the opam-signing effort and my plan for getting this up and running is to collect experience with a small repository, before scaling up to the main repository...

**Comment by mseri** [comment]
I like (b), it would provide a great deal of cleanup and start enforcing some minimal good practices.

In that case I'd also suggest to split the packages in alphabet sub-folder (`packages/0/[packages_whose_name_starts_with_a_number]`, `packages/a/[packages_whose_name_starts_with_a]`, `packages/b/[packages_whose_name_starts_with_b]`, ...) to make it easier to navigate through github.

**Comment by AltGr** [comment]
I am not against a separate curated repository, but I think the goals diverge, as it would take a very long time to replace the current repo.
Keeping the removed packages into a "legacy" repo is a very good idea: it's very easy for anyone to configure both repositories and get back all older patch releases when needed, while still removing all the noise the rest of the time.

As for the cleanup itself: yes, I didn't really expect the above approach to work, but wanted to see how it would fare. Another, more complicated way would be, instead of just looking at version numbers, to check package relationships.

For example, we may be able to define equivalent versions of a package (same dependencies, no dependent packages discriminate between the two versions), and keep only the max of every equivalence class.

Another, completely different approach would be to look at opam.ocaml.org's logs and kill any older version that hasn't been used in the past month or so. And any combination could work, like the semver approach, while keeping packages with enough liveness (and their dependencies).

**Comment by AltGr** [comment]
> One question I would have however is: how opam switch import is handled with OPAM 2.0 if it tries to install deleted packages ? Right now OPAM 1.2.2 just prints a warning which seems rather limited.

opam 2 has a few fallback strategies, including ditching the version constraints when they can't be satisfied. `--best-effort` may also be of great help there.

**Comment by avsm** [comment]
I'll close this PR until we reach consensus on the right way to handle this. It's overloading the CI.

**Comment by paurkedal** [comment]
Rather than splitting up the repository, maybe it would be better if opam supported masks?  The idea is that any masked package versions would be filtered out before dependency analysis and CI testing, so they would not contribute to the complexity.  Examples of masked would be

- `obsolete` for package versions which should no longer be needed. A bot might submit a PR once in a while according to the logic of the PR, when there are sufficient number of changes to justify a review.
- `beta` for beta versions. Developers may have this permanently unmasked to discover issues early.
- `insecure` for package versions with known security issues, to be applied on discovery. Users gets a message on `opam update` if any installed packages is masked. Unmasking may be okay depending on use.

CI test could  check that any package versions includes at least the masks of its dependencies. This would involve work on both opam and CI, though we might save work in moving packages between repos.

**Pull request closed without merging**
