### PR TITLE
Add version 0.0.2 of systemverilog package

### PR DESCRIPTION
**Pull request by xguerin**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The compilation fails with:
```
#=== ERROR while compiling systemverilog.0.0.2 ================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://git.sr.ht/~xguerin/ocaml-systemverilog/archive/0.0.2.tar.gz)
# path                 ~/.opam/4.10/.opam-switch/build/systemverilog.0.0.2
# command              ~/.opam/4.10/bin/dune build -p systemverilog -j 72 @install
# exit-code            1
# env-file             ~/.opam/log/systemverilog-23-d8e452.env
# output-file          ~/.opam/log/systemverilog-23-d8e452.out
### output ###
# Error: I don't know about package systemverilog (passed through -p)
# Hint: did you mean Systemverilog?
```
The following commit seems to fix this issue: https://git.sr.ht/~xguerin/ocaml-systemverilog/commit/4ce763781d23ed9d12fe2cc7adabedcdf4d28c2a. Could you retag the release to include it and update this PR?

**Comment by xguerin** [comment]
Sure, will do now. Sorry for the trouble.

**Comment by kit-ty-kate** [comment]
mh, you removed the `url` field. Without it opam cannot know where to get the archive from (see my previous commit for its syntax: https://github.com/ocaml/opam-repository/commit/6cb1a99b6e748ce34e37093d3ad07537c70d8f1d

In the same commit I also remove unnecessary fields and comments and untagged dune (not compatible with the build tag, see https://github.com/ocaml/dune/issues/2147) and menhir as build dependencies.

Could you put them back?

**Comment by kit-ty-kate** [comment]
@fpottier have you ever seen this type of error?
```
#=== ERROR while compiling systemverilog.0.0.2 ================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.02.3 | pinned(https://git.sr.ht/~xguerin/ocaml-systemverilog/archive/0.0.2.tar.gz)
# path                 ~/.opam/4.02/.opam-switch/build/systemverilog.0.0.2
# command              ~/.opam/4.02/bin/dune build -p systemverilog -j 72 @install
# exit-code            1
# env-file             ~/.opam/log/systemverilog-23-cd6339.env
# output-file          ~/.opam/log/systemverilog-23-cd6339.out
### output ###
# Error: Module Parser in directory _build/default/src depends on
# Systemverilog.
# This doesn't make sense to me.
# 
# Systemverilog is the main module of the library and is the only module
# exposed outside of the library. Consequently, it should be the one depending
# on all the other modules in the library.
```
I can reproduce it locally and I had a look at the code and I can't find any the `Systemverilog` module in the `Parser` module as the error message suggests. However looking at the code generated by menhir, there are indeed references to the `Systemverilog` module:
```
    | SEMICOLON ->
        let _menhir_stack = Obj.magic _menhir_stack in
        let (_menhir_stack, _menhir_s, (e : (Grammar.ParamAssignment.t list))) = _menhir_stack in
        let _v : (Systemverilog.Grammar_types.ParamAssignment.t list) =
# 58 "src/parser.mly"
```
The weird thing is that the error only appears on OCaml 4.02. Something to do with inference maybe?

**Comment by fpottier** [comment]
Hi @kit-ty-kate , this reminds me of the problem that they have in electrod. It is a problem with an incorrect dependency computation (which I don't understand). They have worked around it by adding a dummy module at the beginning of their [parser.mly](https://github.com/fpottier/electrod/blob/master/src/Parser.mly):
```
(* fixes issue between Menhir and dune *)
(* https://github.com/ocaml/dune/issues/2450 *)
module Libelectrod = struct end
```

**Comment by xguerin** [comment]
Thanks @fpottier @kit-ty-kate . I added the fix and retagged the source.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
