### PR TITLE
Package tip-parser.0.4

### PR DESCRIPTION
**Pull request by c-cube**
### `tip-parser.0.4`

Parser for TIP (Tons of Inductive Problems)

A simple AST and parser/printer for TIP (https://tip-org.github.io/), a simple
format for writing problems in a typed logic with computable functions,
datatypes, and axioms.

---
* Homepage: https://github.com/c-cube/tip-parser/
* Source repo: https://github.com/c-cube/tip-parser.git
* Bug tracker: https://github.com/c-cube/tip-parser/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by c-cube** [comment]
some packages (smbc and zipperposition) need an upper bound.

**Comment by c-cube** [comment]
Don't the opam-repo maintainers have tools to do that automatically? :confused:

**Comment by mseri** [comment]
Not that I am aware of, sadly. Afaik we rely on the good will of people. It's a small change, I am happy to add the bounds in a separate PR if you don't have time

**Comment by c-cube** [comment]
It's ok, I'll do it tonight hopefully.

**Comment by c-cube** [comment]
Travis tries to reinstall super old versions of some packages, I don't know why

**Comment by mseri** [comment]
Something is going wrong while it is trying to test all the old releases of smbc without recreating the environment. I think we can rely on the CI, I wuldn't worry about that in this case.

**Comment by mseri** [comment]
Thanks for the help

**Pull request merged**
