### PR TITLE
[new release] atdgen-codec-runtime, atd, atdgen-runtime, atds, atdj and atdgen (2.1.0)

### PR DESCRIPTION
**Pull request by rgrinberg**
Runtime for atdgen generated bucklescript converters

- Project page: <a href="https://github.com/ahrefs/atd">https://github.com/ahrefs/atd</a>

##### CHANGES:

* Fix bug preventing generated code from compiling when using
  json adapters on recursive types.

* Improve automatic error messages shown in case of failed validation.
  Now include the validator's name or code.

* Add support for json adapters in the bucklescript backend. (ahrefs/atd#153)

### CODE REVIEW

**Comment by mseri** [comment]
There are multiple different build failures, can you have a look?

**Comment by avsm** [comment]
Looks like tests are one

```
#=== ERROR while compiling atdgen.2.1.0 =======================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.09.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.09/.opam-switch/build/atdgen.2.1.0
# command              ~/.opam/4.09/bin/dune build -p atdgen -j 2 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/atdgen-25-008a77.env
# output-file          ~/.opam/log/atdgen-25-008a77.out
### output ###
# File "atdgen/test/spec_js/dune", line 29, characters 20-40:
# 29 |  (libraries spec_js atdgen-codec-runtime))
#                          ^^^^^^^^^^^^^^^^^^^^
# Error: Library "atdgen-codec-runtime" not found.
# Hint: try: dune external-lib-deps --missing -p atdgen -j 2 @install @runtest
# File "atdgen/test/spec_js/dune", line 4, characters 27-47:
# 4 |  (libraries atdgen-runtime atdgen-codec-runtime))
#                                ^^^^^^^^^^^^^^^^^^^^
# Error: Library "atdgen-codec-runtime" not found.
# Hint: try: dune external-lib-deps --missing -p atdgen -j 2 @install @runtest
# File "atdgen/test/bucklescript/dune", line 19, characters 12-32:
# 19 |  (libraries atdgen-codec-runtime)
#                  ^^^^^^^^^^^^^^^^^^^^
# Error: Library "atdgen-codec-runtime" not found.
# Hint: try: dune external-lib-deps --missing -p atdgen -j 2 @install @runtest
# test_atdgen_main alias atdgen/test/runtest
# Warning: skipping field b2 (def: File "test.atd", line 98, characters 12-40)
# Warning: skipping field b3 (def: File "test.atd", line 98, characters 12-40)
# Warning: skipping field b4 (def: File "test.atd", line 98, characters 12-40)
# Warning: skipping field b5 (def: File "test.atd", line 98, characters 12-40)
```

and then a valid looking error on 4.09 for atdj

```

#=== ERROR while compiling atdj.2.0.0 =========================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.09.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.09/.opam-switch/build/atdj.2.0.0
# command              ~/.opam/4.09/bin/jbuilder build -p atdj -j 2
# exit-code            1
# env-file             ~/.opam/log/atdj-25-b36dbe.env
# output-file          ~/.opam/log/atdj-25-b36dbe.out
### output ###
#       ocamlc atdj/src/.atdj_main.eobjs/atdj_util.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.09/bin/ocamlc.opt -w -40 -w -27 -safe-string -g -bin-annot -I atdj/src/.atdj_main.eobjs -I /home/opam/.opam/4.09/lib/atd -I /home/opam/.opam/4.09/lib/easy-format -I /home/opam/.opam/4.09/lib/re -I /home/opam/.opam/4.09/lib/seq -no-alias-deps -o atdj/src/.atdj_main.eobjs/atdj_util.cmo -c -impl atdj/src/atdj_util.ml)
# File "atdj/src/atdj_util.ml", line 29, characters 26-27:
# 29 |               norm_ty env x
#                                ^
# Error: This expression has type Atd.Ast.type_expr option
#        but an expression was expected of type Atd.Ast.type_expr
```

**Comment by XVilka** [comment]
This one important for Dune 2.0, since previous version (2.0.0) blocks the upgrade through jbuilder.transition dependency

**Comment by kit-ty-kate** [comment]
Should all tests be simply disabled or is this highlighting an underlying issue?

**Comment by rgrinberg** [comment]
I would just drop all the tests. They’re not properly organized into packages and have a lot of external deps

**Comment by XVilka** [comment]
Also `atdj-2.0.0` should be marked as incompatible with these 2.1.0 in the opam file, since `atdj-2.1.0` seems to work fine.

**Comment by rgrinberg** [comment]
Superseded by #15967

**Pull request closed without merging**
