### PR TITLE
fix ocp-index problems with ocp-build

### PR DESCRIPTION
**Pull request by lefessan**
* Remove buggy versions of ocp-build (1.99.9-beta to 1.99.12-beta, all replaced by 1.99.13-beta)
* Remove constraints forcing 1.99.6-beta
* Remove constraints forcing a version below 1.99.8-beta
* Add missing constraints on ocp-indent and lambda-term

### CODE REVIEW

**Comment by dsheets** [comment]
From #5678, removing old versions, in particular `9`, which has been the latest version in the repository for almost a year, produces a bad user experience. Many users will have installed `ocp-indent` with `ocp-build.1.99.9-beta`, which is not marked as a `{build}` dependency, and they will be *forced* to upgrade to `ocp-build.1.99.13-beta` which may cause them further issues. If those users are operating fine with the "buggy" version `9`, they should be able to continue to operate with that version. We should archive the metadata that reflects how to install and remove that version indefinitely because it may be of use to existing installations or downgrading if issues are found in `13`. I don't believe it is our place to cause metadata to disappear and put opam into a conflict state on users' installations -- the user experience comes first.

**Comment by dsheets** [comment]
Also, please add the constraint that `ocp-index.0.{1,2,3}.0` don't build with `ocp-build.1.99.9-beta`.

**Comment by dsheets** [comment]
You could also introduce `{build}` annotations on `ocp-build` dependencies if you are so inclined.

**Comment by lefessan** [comment]
I am still a bit puzzled by your reply: should the opam repository keep metadata for ages about packages that nobody is using anymore ? Is it really worth spending time fixing ocp-index.0.1.0, when there is a much better 1.5.0 ? I am not sure what the best user experience, believing that software is crap because you are stuck with old versions, or upgrading from time to time and discovering that bugs have been fixed...

**Comment by avsm** [comment]
> I am still a bit puzzled by your reply: should the opam repository keep metadata for ages about packages that nobody is using anymore ?

One of the original design constraints in OPAM was that package metadata should be as immutable as possible, so that the choice of version pinning could be controlled by both the package maintainer *and* the developer.  It is often the case that a developer wants to pin back a package for their own reasons (regressions in new versions, long term support for their own software, etc...).

So in the public OPAM repository, we try to maintain all versions of software uploaded here, with the minimum number of upper bounds required to get it to build.  Too many upper bounds results in making it difficult for a user to pin software easily to develop a new version.

Placing an upper bound on older libraries because they no longer build is usually enough to satisfy all of the usecases:
- a normal user of the library (with no constraints) will get the latest version
- a pinned developer of the old one will keep the old one, and older dependencies (thanks to an upper bound)
- new packages that do not want the old software establish a lower bound when submitted to the repository.

This works pretty well across the repository for even big releases like Core.  A natural point of forking seems to be when they drop support for an older compiler revision.  At this point, the old compiler switch becomes a place to detect missing upper bounds as new software versions are released, and we've been going through manually and doing this from bulk build runs.

If as a package maintainer you are convinced that noone uses the old version, and that it is broken in all usecases, it should be removed.  It's difficult to figure out what is and isnt pinned by users though -- I am always surprised by the complaints I get when updating Cohttp for example.

**Comment by dsheets** [comment]
The point is that we should not *force* users to upgrade by removing metadata which effectively says "this version of the software *no longer exists*". It should be their choice to upgrade and not a side effect of getting new metadata.

Regarding `ocp-index.0.{1,2,3}.0`, I don't think these versions do need much maintenance. A few simple constraints should make them buildable.

**Comment by lefessan** [comment]
I agree that users should be able to decide when to upgrade or not. However, isn't it the purpose of versioning the repository ? If you want to keep a version, you can pin the commit of the repository you want to use. Then, a given commit of the repository should only contain versions that are up-to-date at that commit, or needed to build some other packages that would not be available otherwise.
Moreover, you cannot control if the archives specified in the metadata are still available or not, since they are not archived in the repository itself.

**Comment by avsm** [comment]
> However, isn't it the purpose of versioning the repository ? If you want to keep a version, you can pin the commit of the repository you want to use.

No, this is not the purpose of versioning the repository.  Pins are switch-local and remotes are installation-global.  OPAM provides a sophisticated pinning scheme, and a barebones repository management scheme (priorities).

Do you actually manage your own OPAM repositories like this, without using pins?

**Comment by lefessan** [comment]
We have our own local repositories, where we clone only the metadata of the version of each package that we use, and its archive. To upgrade, we use opam on the global repository to provide a list of suitable versions, and we import these versions to replace the former ones.

**Comment by lefessan** [comment]
> Pins are switch-local and remotes are installation-global.

I would have preferred switch-local remotes, and no pining mechanism.

**Comment by avsm** [comment]
Global remotes were almost certainly a mistake.  Pins are still necessary unless you wish to explain to users how to manually constraint solve Git branches in their head.

**Comment by avsm** [comment]
> We have our own local repositories, where we clone only the metadata of the version of each package that we use, and its archive. To upgrade, we use opam on the global repository to provide a list of suitable versions, and we import these versions to replace the former ones.

More tooling around repository management would be very useful.  This sort of "deployment export" of a set of concrete package versions and archives has been requested several times in the past.  It would also fit in well with reproducible Docker builds.

**Comment by dsheets** [comment]
One of the benefits of a version-controlled repository is that it can easily be merged. Most individual users are not mixing and matching their local repositories from various versions of the central repository. By far, the simplest, lowest overhead way to use opam is to occasionally run `opam update` with the single, default repository and then run `opam install` or `opam remove` or `opam upgrade`. For developers, this is closely followed by using a single local git repository which tracks `ocaml/opam-repository`. Removing package metadata from the central repository doesn't make sense in these use cases.

Additionally, I don't see why, if you curate your local repository so extensively, you are concerned with users have a source of metadata describing how to install and uninstall old versions. If the packages have a buildable configuration, why should users have to grapple through old repository versions to get their metadata?

**Comment by lefessan** [comment]
> Additionally, I don't see why, if you curate your local repository so extensively, you are concerned with users have a source of metadata describing how to install and uninstall old versions. If the packages have a buildable configuration, why should users have to grapple through old repository versions to get their metadata?

I don't contribute to the opam-repository for my own use, but to improve the UX of OCaml users. And I am concerned that (1) the cost of maintaining the repository will keep increasing with the quantity of metadata to manage, until it becomes unbearable and nobody will take care of it, and (2) users trying to choose a correct version of what they want in a set of tens of versions, among which it is not even clear which ones are actually building in their environment.

**Comment by dsheets** [comment]
1. Encouraging maintainer and developer participation and increasing use of automation will help us manage the maintenance task. We have a number of tools for this; some of which need more work. Do you see a current problem with the magnitude of the maintenance task?
2. I believe the current default solver preferences pick the most recent version. If this does not build, it should be reported. Perhaps we should use the `repo` metadata file to prompt users to submit issues? Do you have some evidence of user confusion when it comes to having multiple versions available?

**Comment by lefessan** [comment]
> (1) Encouraging maintainer and developer participation 

Do you have any statistics on that ? My concern here is that a lot of people publish new versions of their packages, but do not care about old versions.

> and increasing use of automation will help us manage the maintenance task.

What's the current status on that side ? Last bulk reports are dated from Aug 2015, and they don't show all versions.

> We have a number of tools for this; some of which need more work. Do you see a current problem with the magnitude of the maintenance task?

Yes, I just tried to update the `ocp-indent` packages metadata, there are 22 of them. I created only 3 patches, but I can't imagine doing that for 1000 packages with 50 versions each, even with a better tooling.

> (2) I believe the current default solver preferences pick the most recent version. If this does not build, it should be reported. Perhaps we should use the repo metadata file to prompt users to submit issues? Do you have some evidence of user confusion when it comes to having multiple versions available?

Yes, I have the evidence of myself, trying to fix constraints on ocp-indent. I had to `git blame` ocaml to know when a function was introduced, and I was lucky that OCaml is well documented, and that all versions are compiling. Imagine doing that for a package that you don't know well, with some broken versions in the middle...

**Comment by dsheets** [comment]
If there is no demand, no action is necessary. When old version builds are attempted, adding contemporaneous constraints are often sufficient to get the version to build. Yes, this means that old versions of packages may appear broken if no one has tried to build them with recent versions of dependencies because their constraints are too lenient.

What is wrong with lazily evaluating constraints?

**Comment by lefessan** [comment]
Travis seems to fail because log is too long.

**Comment by dsheets** [comment]
The 50 minute time limit was exceeded and so the tests on old opam versions and OS X terminated before completion.

**Pull request merged**
