### PR TITLE
Package menhir.20190613

### PR DESCRIPTION
**Pull request by fpottier**
### `menhir.20190613`
An LR(1) parser generator

---
* Homepage: http://gitlab.inria.fr/fpottier/menhir
* Source repo: git+https://gitlab.inria.fr/fpottier/menhir.git
* Bug tracker: menhir@inria.fr

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by jhjourdan** [comment]
The reverse dependency failures seem unrelated to the new version of Menhir. The packages were probably already broken with previous versions.

**Comment by jhjourdan** [comment]
I don't understand the opam lint warning : 

>  warning 58: Found doc variable, predefined one is with-doc

According to https://opam.ocaml.org/doc/Manual.html#pkgvar-dirs, `doc` is a valid variable.

**Comment by fpottier** [comment]
Also, the warning `warning 58: Found doc variable, predefined one is with-doc` is strange: I have checked in the opam documentation that the variable `doc` exists.

**Comment by rjbou** [comment]
It is an error in linting, the warning is supposed to be specific to deprecated `doc` variable in filters (replaced by `with-doc`).

**Comment by kit-ty-kate** [comment]
The `remove` field is unnecessary with opam 2.0. Could you return the fix in the upstream opam file?

**Comment by fpottier** [comment]
@Kate, thanks, I have removed the `remove:` field in our opam file.

**Comment by fpottier** [comment]
Is there something that prevents this PR from being accepted?

**Comment by kit-ty-kate** [comment]
> Is there something that prevents this PR from being accepted?

None, sorry for the delay

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by fpottier** [comment]
Thanks!

**Pull request merged**
