### PR TITLE
[new release] coq-serapi (8.9.0+0.6.0)

### PR DESCRIPTION
**Pull request by ejgallego**
CHANGES:

* [general] support Coq 8.9,
 * [general] SerAPI now uses Dune as a build system,
 * [opam]   install `sertop.el`,
 * [serlib] support to serialize kernel environments,
 * [serapi] new query `Env` that tries to print the current kernel environment,
 * [serlib] correct field names for `CAst`,
 * [serlib] more robust support for opaque / non-serializable types (ejgallego/coq-serapi#61, ejgallego/coq-serapi#68).
            Thanks to @palmskog,
 * [serlib] new option `--exn_on_opaque` to raise an exception on
            non-serializable types; closes ejgallego/coq-serapi#68, thanks to @palmskog,
 * [serlib] serialization test-suite from
            https://github.com/proofengineering/serapi-tests, thanks to
            @palmskog,
 * [sercomp] add `--mode` option to better control output,
 * [sercomp] add `compser` for deserialization (inverse of `sercomp`)
             (@palmskog),
 * [serapi]  Allow custom document creation using the `NewDoc` call.
             Use the `--no_init` option to avoid automatic creation
             on init. (@ejgallego)
 * [sercomp] Allow compilers to output `.vo` (@ejgallego , suggested by
             @palmskog)
 * [sercomp] Serialize top-level vernaculars with their syntactic
             attributes (such as location) (@ejallego)
 * [serapi]  Add `Assumptions` query, at the suggestion of @Armael
             (@ejgallego)
 * [sercomp] Disable error resilience mode in compilers; semantics are
             a bit dubious see coq/coq#9204 also ejgallego/coq-serapi#94.
             (@ejgallego, report by @palmskog)
 * [sercomp] Add `check` mode to compilers to check all proofs without
             outputting `.vo`. (@palmskog)
 * [sercomp] Add "hacky" `--quick` option to skip checking of opaque
             proofs. (@ejgallego, request by @palmskog)
 * [sercomp] Add `--async_workers` option to set maximum number
             of parallel async workers. (@palmskog)
 * [sertop] Stop linking Coq plugins statically and load `serlib`
            plugins when Coq plugins are loaded instead (@ejgallego,
            review by @palmskog)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Seems like the archive doesn't exist yet:
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - coq-serapi.8.9.0+0.6.0:
            https://github.com/ejgallego/coq-serapi/releases/download/8.9.0+0.6.0/coq-serapi-8.9.0+0.6.0.tbz (curl: code 404 while downloading https://github.com/ejgallego/coq-serapi/releases/download/8.9.0+0.6.0/coq-serapi-8.9.0+0.6.0.tbz)
```

**Comment by ejgallego** [comment]
> Seems like the archive doesn't exist yet:

Indeed it seems like something very strange is going on with Github, the URL:

https://api.github.com/repos/ejgallego/coq-serapi/releases

List no releases for coq-serapi, strange...

**Comment by ejgallego** [comment]
Fails on OSX due to a timeout, but it seems to work fine:
https://travis-ci.org/ocaml/opam-repository/jobs/485524049

**Comment by ejgallego** [comment]
Thanks to you!

**Comment by ejallego** [comment]
I'm sorry but why do I get notifications for these commits/changes?

**Comment by ejgallego** [comment]
> I'm sorry but why do I get notifications for these commits/changes?

Typo in commit username, sorry for that!

**Pull request merged**
