### PR TITLE
zed 1.4

### PR DESCRIPTION
**Pull request by diml**

### CODE REVIEW

**Comment by yallop** [comment]
Hmm, that's odd.  Travis seems to have missed this one.  I'm going to try ~~turning it off and on again~~ closing and reopening the request to see if that triggers the build.

**Comment by yallop** [comment]
That seems to have done the trick.

**Comment by yallop** [comment]
It's failing on [OCaml versions below 4.02](https://travis-ci.org/ocaml/opam-repository/jobs/46219339):

```
# File "src/zed_utf8.ml", line 19, characters 23-39:
# Error: Unbound module Bytes
# Command exited with code 2.
```

Perhaps you need to add Bytes to [BuildDepends](https://github.com/diml/zed/blob/441b1855372e83388e82752c0e23ce92230968a2/_oasis#L36):

```
BuildDepends: react, camomile (>= 0.8)
```

**Comment by diml** [comment]
Indeed, I updated the dependencies.

**Comment by yallop** [comment]
Thanks!

**Pull request merged**
