### PR TITLE
Package git-split.0.0.2

### PR DESCRIPTION
**Pull request by Artamus**
### `git-split.0.0.2`
A tool to split a git commit into multiple
When one commit becomes too large and needs to be split up, the general git workflow that involves resetting the commit and then using interactive staging to generate multiple commits from it can be quite cumbersome. In addition to that, the git interactive staging tool's UX can be quite bad, therefore this tools aims to provide this functionality in a nicer way.

---
* Homepage: https://github.com/Artamus/git-split
* Source repo: git+https://github.com/Artamus/git-split.git
* Bug tracker: https://github.com/Artamus/git-split/issues

---
:camel: Pull-request generated by opam-publish v2.4.0

### CODE REVIEW

**Comment by Artamus** [comment]
Please pardon the two different users, unfortunately the automation does not deal super well with having multiple different ssh keys for different users on the same machine.

I actually changed the name of the package from `git_split` to `git-split`, because I'm still figuring out where dune allows hyphens and where must they be underscores.
I figured I would later send a PR that deletes the original `git_split@0.0.1` OPAM package, since there's practically no functional difference between the initial release and this one - please let me know if that is undesirable.

**Comment by dinosaure** [comment]
> I figured I would later send a PR that deletes the original git_split@0.0.1 OPAM package, since there's practically no functional difference between the initial release and this one - please let me know if that is undesirable.

The policy suggests that no package should disappear from the repository - see https://github.com/ocaml/opam-repository/wiki/Policies#1-removal-of-packages-should-be-avoided. Cleaning and archiving phases are performed, but answer to another (longer) cycle. You can mark your old package as unavailable (`available: false`), which will help us later to consider it as an archive that absolutely nobody has installed.

**Comment by shonfeder** [comment]
Looks good to me:

- Windows failure is due to notty, not this backage.
- The opam-ci failure is just a collision warning with the other package name.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
