### PR TITLE
Add llvm and conf-llvm for 14.0.6.

### PR DESCRIPTION
**Pull request by jubnzv**
Hi,

I created an opam package for the latest stable version of LLVM: 14.0.6.

Here is a list of changes from the `llvm-13.0.0` opam package:
* The only change related to bindings is https://github.com/llvm/llvm-project/commit/fe2b2cb58ebb57427c0a12e54a4ed63553c397ab. It adds `.cmt` and `.cmti` files, implementing functionality of [add-cmt-for-llvm-13.patch](https://github.com/ocaml/opam-repository/blob/81f989bd145d1e3b58da418f4e6c5feded5e40f6/packages/llvm/llvm.13.0.0/files/add-cmt-for-llvm-13.patch). So, we don't need this patch anymore.
* [Common LLVM CMake modules](https://github.com/llvm/llvm-project/blob/f28c006a5895fc0e329fe15fead81e37457cb1d1/cmake/README.rst) were moved to the separate directory: `cmake/Modules`. Previously this logic was inlined in files in `llvm/cmake/modules`. So, for now we have two directories in the [`llvm-src` release archive](https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-14.0.6.src.tar.xz): `llvm-14.0.6.src` and `cmake`. Thit means that we cannot install from this archive with `opam` anymore, because [it forbids having multiple root directories in it](https://github.com/ocaml/opam/blob/b2f41ca039144ae39abcb1c41bfb62d15b554415/src/core/opamSystem.ml#L1038). So, I decided to download the whole [`llvm-project-src` sources](https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-project-14.0.6.src.tar.xz) and to work inside the `llvm` subdirectory when installing it.
* There was [a change](https://reviews.llvm.org/D112012) in `llvm/cmake/modules/AddOCaml.cmake` that made it not possible to build the bindings using only [llvm-14.0.6.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-14.0.6.src.tar.xz) when `-DLLVM_INCLUDE_BENCHMARKS` is `TRUE`. The problem is that [we need](https://github.com/llvm/llvm-project/tree/f28c006a5895fc0e329fe15fead81e37457cb1d1/llvm/CMakeLists.txt#L1256) the whole `llvm-project` sources, because we use `../third-party` directory when building `llvm`. But for now we work the `llvm-project` source archive which contains `third-party` subdirectory as well, so this problem is solved.

Other changes that doesn't require the modification of the opam package:
* Commits in the OCaml bindings between 13.0.0 and 14.0.6 in LLVM tree: https://github.com/llvm/llvm-project/commit/6a713120502abc0a42b8d518edea345b60e829f3 and https://github.com/llvm/llvm-project/commit/ec501f15a8b8ace2b283732740d6d65d40d82e09. Both are no functional, so we don't need to update anything in this package.
* `conf-llvm-14` package is exactly the same as `conf-llvm-13`, only version numbers were changed.

Here is the complete diff between `llvm-13.0.0` and `llvm-14.0.6`:

<details>
  <summary>diff</summary>

```diff
diff -r llvm.13.0.0/files/fix-macos.patch llvm.14.0.6/files/fix-macos.patch
8c8
<  llvm/cmake/modules/AddOCaml.cmake | 4 ++--
---
>  llvm-project/llvm/cmake/modules/AddOCaml.cmake | 4 ++--
11c11
< diff --git a/llvm/cmake/modules/AddOCaml.cmake b/llvm/cmake/modules/AddOCaml.cmake
---
> diff --git a/llvm-project/llvm/cmake/modules/AddOCaml.cmake b/llvm-project/llvm/cmake/modules/AddOCaml.cmake
13,14c13,14
< --- a/cmake/modules/AddOCaml.cmake
< +++ b/cmake/modules/AddOCaml.cmake
---
> --- a/llvm/cmake/modules/AddOCaml.cmake
> +++ b/llvm/cmake/modules/AddOCaml.cmake
diff -r llvm.13.0.0/files/fix-rhel.patch llvm.14.0.6/files/fix-rhel.patch
13,14c13,14
< --- a/cmake/modules/AddOCaml.cmake
< +++ b/cmake/modules/AddOCaml.cmake
---
> --- a/llvm/cmake/modules/AddOCaml.cmake
> +++ b/llvm/cmake/modules/AddOCaml.cmake
diff -r llvm.13.0.0/files/fix-shared.patch llvm.14.0.6/files/fix-shared.patch
13,14c13,14
< --- a/cmake/modules/AddOCaml.cmake
< +++ b/cmake/modules/AddOCaml.cmake
---
> --- a/llvm/cmake/modules/AddOCaml.cmake
> +++ b/llvm/cmake/modules/AddOCaml.cmake
diff -r llvm.13.0.0/files/install.sh llvm.14.0.6/files/install.sh
13a14,18
>     cd llvm
> 
>     # Copy the required Common LLVM CMake modules to the source tree
>     cp ../cmake/Modules/* cmake/
> 
28c33
<     cd ..
---
>     cd ../..
31a37
>   cd llvm
43a50
>   cd ..
diff -r llvm.13.0.0/files/link-META.patch llvm.14.0.6/files/link-META.patch
1c1
< diff --git a/bindings/ocaml/backends/META.llvm_backend.in b/bindings/ocaml/backends/META.llvm_backend.in
---
> diff --git a/llvm/bindings/ocaml/backends/META.llvm_backend.in b/llvm/bindings/ocaml/backends/META.llvm_backend.in
3,4c3,4
< --- a/bindings/ocaml/backends/META.llvm_backend.in
< +++ b/bindings/ocaml/backends/META.llvm_backend.in
---
> --- a/llvm/bindings/ocaml/backends/META.llvm_backend.in
> +++ b/llvm/bindings/ocaml/backends/META.llvm_backend.in
14c14
< diff --git a/bindings/ocaml/llvm/META.llvm.in b/bindings/ocaml/llvm/META.llvm.in
---
> diff --git a/llvm/bindings/ocaml/llvm/META.llvm.in b/llvm/bindings/ocaml/llvm/META.llvm.in
16,17c16,17
< --- a/bindings/ocaml/llvm/META.llvm.in
< +++ b/bindings/ocaml/llvm/META.llvm.in
---
> --- a/llvm/bindings/ocaml/llvm/META.llvm.in
> +++ b/llvm/bindings/ocaml/llvm/META.llvm.in
diff -r llvm.13.0.0/files/META.patch llvm.14.0.6/files/META.patch
1c1
< diff --git a/bindings/ocaml/backends/META.llvm_backend.in b/bindings/ocaml/backends/META.llvm_backend.in
---
> diff --git a/llvm/bindings/ocaml/backends/META.llvm_backend.in b/llvm/bindings/ocaml/backends/META.llvm_backend.in
3,4c3,4
< --- a/bindings/ocaml/backends/META.llvm_backend.in
< +++ b/bindings/ocaml/backends/META.llvm_backend.in
---
> --- a/llvm/bindings/ocaml/backends/META.llvm_backend.in
> +++ b/llvm/bindings/ocaml/backends/META.llvm_backend.in
16c16
< diff --git a/bindings/ocaml/llvm/META.llvm.in b/bindings/ocaml/llvm/META.llvm.in
---
> diff --git a/llvm/bindings/ocaml/llvm/META.llvm.in b/llvm/bindings/ocaml/llvm/META.llvm.in
18,19c18,19
< --- a/bindings/ocaml/llvm/META.llvm.in
< +++ b/bindings/ocaml/llvm/META.llvm.in
---
> --- a/llvm/bindings/ocaml/llvm/META.llvm.in
> +++ b/llvm/bindings/ocaml/llvm/META.llvm.in
diff -r llvm.13.0.0/opam llvm.14.0.6/opam
29d28
<   "add-cmt-for-llvm-13.patch"
36,42c35,40
<   ["link-META.patch" "md5=53dc8e72917585d235b9bbb3e06eed2b"]
<   ["install.sh" "md5=f318260916581cbf0a8e7aa2903ac6d2"]
<   ["fix-shared.patch" "md5=818e192b6b54c0e392f2cdb2106b2e6f"]
<   ["add-cmt-for-llvm-13.patch" "md5=248ec7d17ebd1592fc99848016d9452b"]
<   ["META.patch" "md5=4c3cf99d06d2044e2ce5a853e5a16d5e"]
<   ["fix-macos.patch" "md5=ff33b723048e1f1a2d26505f272c8ae9"]
<   ["fix-rhel.patch" "md5=ba4142dbfc65a4b1a09ee7233048c0bf"]
---
>   ["link-META.patch" "md5=bbb99db647b80baaa34054e1a957f218"]
>   ["install.sh" "md5=2db75a6673ad476cdb464dd90021d51a"]
>   ["META.patch" "md5=c63515a9c59101ebf71ecf83ddf6ec9f"]
>   ["fix-macos.patch" "md5=86664021a2819e4a0a9ebe5f3cafe819"]
>   ["fix-shared.patch" "md5=bdc3f688681e9c56d92514ba4ef68cb9"]
>   ["fix-rhel.patch" "md5=e1db49b76f8795f3d3e276fd9e10db72"]
45,46c43,44
<   src: "https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/llvm-13.0.0.src.tar.xz"
<   checksum: "sha256=408d11708643ea826f519ff79761fcdfc12d641a2510229eec459e72f8163020"
---
>   src: "https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-project-14.0.6.src.tar.xz"
>   checksum: "sha256=8b3cfd7bc695bd6cea0f37f53f0981f34f87496e79e2529874fd03a2f9dd3a8a"
```

</details>

### CODE REVIEW

**Comment by jubnzv** [comment]
It seems, that it passes CI on distributions that have the `llvm-14-dev` package. I tested it locally on my Debian testing, and everything seems good as well.

**Comment by kit-ty-kate** [comment]
> * There was [a change](https://reviews.llvm.org/D112012) in `llvm/cmake/modules/AddOCaml.cmake` that made it not possible to build the bindings using only [llvm-14.0.6.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-14.0.6.src.tar.xz) when `-DLLVM_INCLUDE_BENCHMARKS` is `TRUE`. The problem is that [we need](https://github.com/llvm/llvm-project/tree/f28c006a5895fc0e329fe15fead81e37457cb1d1/llvm/CMakeLists.txt#L1256) the whole `llvm-project` sources, because we use `../third-party` directory when building `llvm`. But for now we work the `llvm-project` source archive which contains `third-party` subdirectory as well, so this problem is solved.

if `-DLLVM_INCLUDE_BENCHMARKS` is the only issue then why is this a problem for the package? I’m not sure to understand this.

**Comment by jubnzv** [comment]
> if -DLLVM_INCLUDE_BENCHMARKS is the only issue then why is this a problem for the package? I’m not sure to understand this.

Ah, yes, this looks confusing after [919ca56](https://github.com/ocaml/opam-repository/pull/21932/commits/919ca56a63e3a77b3ee03f3ba968d3eda865a74c). This is not a problem for now, because I use [llvm-project-14.0.6.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-project-14.0.6.src.tar.xz) to build the package. It contains the `third-party` directory and everything works well.

**Comment by kit-ty-kate** [comment]
i mean if everyone has to download the whole llvm-project tree, this is a bit of an issue for me in the current state. Could you revert this commit?

**Comment by jubnzv** [comment]
> i mean if everyone has to download the whole llvm-project tree, this is a bit of an issue for me in the current state. Could you revert this commit?

I'm not sure how to do this, because [llvm-14.0.6.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-14.0.6.src.tar.xz) contains two subdirectories: `llvm` and `cmake`. So, `opam` cannot install a package from this archive because of [this error](https://github.com/ocaml/opam/blob/b2f41ca039144ae39abcb1c41bfb62d15b554415/src/core/opamSystem.ml#L1038).

Maybe there are some workarounds for this?

**Comment by kit-ty-kate** [comment]
wow wtf. Sorry i missed this when i read the description. Mmh, sigh.. oh well. It’s a pretty weird decision for them to do but there is nothing we can do apart remaking the archive ourselves.

Sorry for the mistake and the delay. Thanks!

**Pull request merged**
