### PR TITLE
Package apronext.1.0.3

### PR DESCRIPTION
**Pull request by ghilesZ**
### `apronext.1.0.3`
Apron extension
An extension for the OCaml interface of the Apron library

---
* Homepage: https://github.com/ghilesZ/apronext
* Source repo: git+https://github.com/ghilesZ/apronext
* Bug tracker: https://github.com/ghilesZ/apronext/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This release breaks one of the package's reverse dependency:
```
#=== ERROR while compiling picasso.0.1 ========================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.11.1 | file:///src
# path                 ~/.opam/4.11/.opam-switch/build/picasso.0.1
# command              ~/.opam/4.11/bin/dune build -p picasso -j 31
# exit-code            1
# env-file             ~/.opam/log/picasso-15-000417.env
# output-file          ~/.opam/log/picasso-15-000417.out
### output ###
#       ocamlc src/.picasso.objs/byte/picasso__Drawable.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.11/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.picasso.objs/byte -I /home/opam/.opam/4.11/lib/apron -I /home/opam/.opam/4.11/lib/apronext -I /home/opam/.opam/4.11/lib/gmp -I /home/opam/.opam/4.11/lib/lablgtk2 -I /home/opam/.opam/4.11/lib/ocaml/threads -no-alias-deps -open Picasso__ -o src/.picasso.objs/byte/picasso__Drawable.cmo -c -impl src/drawable.ml)
# File "src/drawable.ml", line 18, characters 17-39:
# 18 | let of_gens gl =[Apol.of_generator_list (List.hd gl |> G.get_env) gl]
#                       ^^^^^^^^^^^^^^^^^^^^^^
# Error: This function has type
#          Apron.Generator1.t list -> Polka.strict Polka.t Apronext.Apol.A.t
#        It is applied to too many arguments; maybe you forgot a `;'.
```
Is that expected for such a minor release?

**Comment by ghilesZ** [comment]
Yes that is expected, and i'm about to release a new version of the picasso package right after.

**Comment by kit-ty-kate** [comment]
Ok. For next time, please consider bumping the minor version instead of micro when changing the API (e.g. in this case: `1.1.0`)

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
