### PR TITLE
+faraday.0.5.0

### PR DESCRIPTION
**Pull request by seliopou**

### CODE REVIEW

**Comment by seliopou** [comment]
Failures seem to be related to some OS package installation failure:

```
# OS package update successful
The following command needs to be run through "sudo":
    yum install -y m4
Redirecting to '/usr/bin/dnf install -y m4' (see 'man yum2dnf')

error: db5 error(-30969) from dbenv->open: BDB0091 DB_VERSION_MISMATCH: Database environment version mismatch
error: cannot open Packages index using db5 -  (-30969)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed
OS package installation failed
Removing intermediate container c247c92b5368
The command '/bin/sh -c opam-ci-install faraday.0.5.0' returned a non-zero code: 1
[2017-10-05 12:32.36] Failed: Command "sh" "-c" "docker build --label com.docker.datakit.digest=09c3db5f96988d9650526d5698c47e6d --label com.docker.datakit.builton=1507206619.23 --rm --force-rm - < /tmp/tmp-2f7a4186/Dockerfile" exited with status 1
```

**Comment by seliopou** [comment]
@dinosaure Added a version constraint to farfadet. The only output format supported now is bigstring.

**Comment by seliopou** [comment]
Pretty sure all the problems with this are going to get fixed by #10286

**Comment by gasche** [comment]
The 4.06 failure seems to come from `sexplib`.

**Pull request merged**
