### PR TITLE
package Coq 8.12.1

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by Zimmi48** [comment]
On Travis, the macOS failure is a timeout, and the FreeBSD failure is due to the adwaita-icon-theme package not existing.
On CentOS, the issue is the gtksourceview3-devel package not existing.
I have no idea why these are new failures compared to the previous versions.
But in any case, these are all CoqIDE build issues, so if it takes time to resolve them, then splitting the Coq update part in a separate PR should ensure that at least this part of the update gets in quickly.

**Comment by RalfJung** [comment]
Yeah I can split them if necessary (though I did test the package locally and it works) -- let's see what the maintainers are saying.

**Comment by Zimmi48** [comment]
I'm going to announce the release very soon. It would be great if this could be merged before, or at least the Coq part (without CoqIDE if it must wait). @kit-ty-kate: What should we do?

**Comment by kit-ty-kate** [comment]
I fixed the `conf-adwaita-icon-theme` package in https://github.com/ocaml/opam-repository/pull/17631 yesterday. I was just waiting for the CI to merge it

**Comment by kit-ty-kate** [comment]
Ok, merging now and I'm creating a draft PR to check if everything went ok for coqide. Thanks!

**Pull request merged**
