### PR TITLE
conf-fswatch fswatch fswatch_lwt

### PR DESCRIPTION
**Pull request by kandu**
* conf-fswatch virtual package
* bindings for the [fswatch](https://emcrisostomo.github.io/fswatch/doc/) library
* lwt extension for the bindings

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I'm not too sure to understand the version scheme `11-0.1.0`. Is it intended?

**Comment by kit-ty-kate** [comment]
I'm not too sure to understand the version scheme `11-0.1.0`. Is it intended?

**Comment by kit-ty-kate** [comment]
Your library does not actually install anything:
```
#=== ERROR while compiling fswatch_lwt.11-0.1.0 ===============================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.09.0 | pinned(https://github.com/kandu/ocaml-fswatch/archive/11-0.1.0.tar.gz)
# path                 ~/.opam/4.09/.opam-switch/build/fswatch_lwt.11-0.1.0
# command              ~/.opam/4.09/bin/dune build -p fswatch_lwt -j 2
# exit-code            1
# env-file             ~/.opam/log/fswatch_lwt-23-c2a9db.env
# output-file          ~/.opam/log/fswatch_lwt-23-c2a9db.out
### output ###
# File "fswatch_lwt/src/dune", line 5, characters 13-20:
# 5 |   (libraries fswatch lwt.unix)
#                  ^^^^^^^
# Error: Library "fswatch" not found.
# Hint: try: dune external-lib-deps --missing -p fswatch_lwt -j 2 @install
```
`dune-project`, opam files and `dune-workspace` files should be in the root directory, otherwise `.install` files necessary for opam to know what to install are not in the right place

**Comment by kandu** [comment]
> I'm not too sure to understand the version scheme `11-0.1.0`. Is it intended?

The lib version, or API version of the lastest two releases of fswatch, 1.13, 1.14 is 11:0:0 and 11:1:0
So yes, it's intended, to better trace the changes of the API we are binding to and the bindings itself :)

**Comment by kandu** [comment]
> `dune-project`, opam files and `dune-workspace` files should be in the root directory, otherwise `.install` files necessary for opam to know what to install are not in the right place

Ah, thank you, Kate. This is my first time releasing several packages bundled together in one tarball ;)

**Comment by kandu** [comment]
And libfswatch is a new library, only some recent new distributions include it, so it's not available in some build host(like ubuntu 16.04)

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
