### PR TITLE
sparrow.0.1 - via opam-publish

### PR DESCRIPTION
**Pull request by KihongHeo**
A Static Analyzer for C 
Sparrow is a state-of-the-art static analyzer that aims to verify 
the absence of fatal bugs in C source. Sparrow is designed by 
Abstract Interpretation and the analysis is sound in design. 
Sparrow adopts a number of well-founded static analysis techniques 
for scalability, precision, and user convenience.

---
* Homepage: https://github.com/ropas/sparrow
* Source repo: http://github.com/ropas/sparrow.git
* Bug tracker: https://github.com/ropas/sparrow/issues

---

Pull-request generated by opam-publish v0.3.4

### CODE REVIEW

**Comment by samoht** [comment]
It seems to be missing a dependency to `ppx_deriving`?

```
#=== ERROR while installing sparrow.0.1 =======================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/4.03.0/build/sparrow.0.1
# compiler     4.03.0
# exit-code    2
# env-file     /home/travis/.opam/4.03.0/build/sparrow.0.1/sparrow-14800-2afd62.env
# stdout-file  /home/travis/.opam/4.03.0/build/sparrow.0.1/sparrow-14800-2afd62.out
# stderr-file  /home/travis/.opam/4.03.0/build/sparrow.0.1/sparrow-14800-2afd62.err
### stdout ###
# ocaml setup.ml -build 
# /home/travis/.opam/4.03.0/bin/ocamlopt.opt unix.cmxa -I /home/travis/.opam/4.03.0/lib/ocamlbuild /home/travis/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/travis/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/travis/.opam/4.03.0/bin/ocamlfind ocamldep -package apron -package apron.octMPQ -package batteries -package cil -package lymp -package ocamlgraph -package ppx_compare -package yojson -modules src/core/main.ml > src/core/main.ml.depends
# + /home/travis/.opam/4.03.0/bin/ocamlfind ocamldep -package apron -package apron.octMPQ -package batteries -package cil -package lymp -package ocamlgraph -package ppx_compare -package yojson -modules src/core/main.ml > src/core/main.ml.depends
# ocamlfind: Package `ppx_deriving' not found - required by `ppx_compare.deprecated-ppx-method'
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/home/travis/.opam/4.03.0/bin/ocamlbuild' src/core/main.native src/core/vis.native -tag debug' terminated with error code 10")
# make: *** [build] Error 1
```

**Comment by samoht** [comment]
Seem to be working better now. The new errors are missing depext specifications on `alpine`:

```
#=== ERROR while installing conf-mpfr.1 =======================================#
# opam-version         1.2.2
# os                   linux
# command              cc test.c -I/usr/local/include -L/usr/local/lib -lgmp -lmpfr
# path                 /home/opam/.opam/4.03.0/build/conf-mpfr.1
# compiler             4.03.0
# exit-code            1
# env-file             /home/opam/.opam/4.03.0/build/conf-mpfr.1/conf-mpfr-29-e0259d.env
# stdout-file          /home/opam/.opam/4.03.0/build/conf-mpfr.1/conf-mpfr-29-e0259d.out
# stderr-file          /home/opam/.opam/4.03.0/build/conf-mpfr.1/conf-mpfr-29-e0259d.err
### stderr ###
# test.c:2:18: fatal error: mpfr.h: No such file or directory
#  #include <mpfr.h>
#                   ^
# compilation terminated.
```

I will fix that in an other PR and re-run your tests.

**Comment by samoht** [comment]
#8903 is now merged, so let's see how it goes.

**Comment by samoht** [comment]
@KihongHeo would you mind rebasing that PR to `master`? This will pick the changes that I've just merged.

**Comment by KihongHeo** [comment]
Hi @samoht , 
Thanks for your help. I rebased it but it still seems to have some problems.

**Comment by samoht** [comment]
Tentative fix in https://github.com/ocaml/opam-repository/pull/8907

**Comment by avsm** [comment]
I'll go ahead and merge this as it's working on the majority of distros.  Further PRs can refine the musl/alpine and CentOS support.

**Pull request merged**
