### PR TITLE
Websocket 0.9.1

### PR DESCRIPTION
**Pull request by vbmithr**

### CODE REVIEW

**Comment by yallop** [comment]
[4.02 incompatibility](https://travis-ci.org/ocaml/opam-repository/jobs/45776453):

```
# File "lib/websocket.ml", line 120, characters 30-33:
# Error: This expression has type bytes but an expression was expected of type
# string
# Command exited with code 2.
```

**Comment by avsm** [comment]
Any reason to move 0.9?

**Comment by vbmithr** [comment]
On 03/01/2015 17:20, Anil Madhavapeddy wrote:
> Any reason to move 0.9?

Yeah, it has a critical bug in it, 0.9.1 is the fix.

-- 
Vincent

**Comment by avsm** [comment]
Vincent any chance of a fix that works with 4.02.1 and I can merge?

**Comment by avsm** [comment]
If it'll take a while I'll just add a compiler constraint to this one.

**Comment by vbmithr** [comment]
Ha, got it, this is because it depends on an unreleased Lwt version. Leave it like that, I'm releasing Lwt first.

**Pull request merged**
