### PR TITLE
[new release] reason (2 packages) (3.12.0)

### PR DESCRIPTION
**Pull request by anmonteiro**
Reason: Syntax & Toolchain for OCaml

- Project page: <a href="https://reasonml.github.io/">https://reasonml.github.io/</a>

##### CHANGES:

- Add `\u{hex-escape}` syntax (@anmonteiro,
  [reasonml/reason#2738](https://github.com/reasonml/reason/pull/2738))
- Support local open and let bindings (@SanderSpies) [reasonml/reason#2716](https://github.com/reasonml/reason/pull/2716)
- outcome printer: change the printing of `@bs.*` to `@mel.*` (@anmonteiro, [reasonml/reason#2755](https://github.com/reasonml/reason/pull/2755))
- Fix outcome printing of optional arguments on OCaml 5.2 (@anmonteiro, [reasonml/reason#2753](https://github.com/reasonml/reason/pull/2753))
- support parsing and printing of `external%extension` (@anmonteiro, [reasonml/reason#2750](https://github.com/reasonml/reason/pull/2750), [reasonml/reason#2766](https://github.com/reasonml/reason/pull/2766), [reasonml/reason#2767](https://github.com/reasonml/reason/pull/2767))
- install `refmt` manpage (@anmonteiro, [reasonml/reason#2760](https://github.com/reasonml/reason/pull/2760))
- add support for parsing / printing of refutation clause in `switch` (@anmonteiro, [reasonml/reason#2765](https://github.com/reasonml/reason/pull/2765))
- support `let%ppx` in signatures (@anmonteiro, [reasonml/reason#2770](https://github.com/reasonml/reason/pull/2770))

### CODE REVIEW

**Comment by anmonteiro** [comment]
@mseri thanks for bumping the ocaml constraint but I think we want to find a fix upstream to still support OCaml 4.03. I'll update our decision here in a few days.

**Comment by mseri** [comment]
As you prefer. If it can help, all the actively maintained linux distributions are shipping 4.08+ at this point

**Comment by anmonteiro** [comment]
> As you prefer. I put a do not merge tag to avoid mistakes from our side.
> 
> If it can help, all the actively maintained linux distributions are shipping 4.08+ at this point

that makes sense, let's go ahead and merge then. we can drop support for 4.03 and 4.04

**Comment by mseri** [comment]
Do you know if this error is related to the release?
```

#=== ERROR while compiling melange.4.0.0-52 ===================================#
# context              2.3.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.2.0 | file:///home/opam/opam-repository
# path                 ~/.opam/5.2/.opam-switch/build/melange.4.0.0-52
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p melange -j 255 @install
# exit-code            1
# env-file             ~/.opam/log/melange-7-d0d2cb.env
# output-file          ~/.opam/log/melange-7-d0d2cb.out
### output ###
# (cd _build/default/jscomp/core && /usr/bin/bash -e -u -o pipefail -c 'echo let version = \"$(git rev-parse --verify HEAD)\"') > _build/default/jscomp/core/git_commit.ml
# fatal: not a git repository (or any parent up to mount point /)
# Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
# (cd _build/default/jscomp/core && /usr/bin/bash -e -u -o pipefail -c 'echo let short_version = \"$(git rev-parse --short HEAD)\"') > _build/default/jscomp/core/git_commit.ml
# fatal: not a git repository (or any parent up to mount point /)
# Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
# File "jscomp/others/.belt.objs/melange/_unknown_", line 1, characters 0-0:
# (cd _build/default && bin/melc.exe -w -40 -w -49 -nopervasives -nostdlib -g -bin-annot -bin-annot-occurrences -I jscomp/others/.belt.objs/melange --bs-stop-after-cmj --bs-package-output . --bs-module-name belt__ --bs-package-name melange.belt -no-alias-deps -o jscomp/others/.belt.objs/melange/belt__.cmj -c -impl jscomp/others/belt__.ml-gen)
# melc: unknown option '--bin-annot-occurrences'.
# Usage: melc [OPTION]… [filenames]…
# Try 'melc --help' for more information.
# File "jscomp/others/.dom.objs/melange/_unknown_", line 1, characters 0-0:
# (cd _build/default && bin/melc.exe -w -40 -w -49 -nopervasives -nostdlib -g -bin-annot -bin-annot-occurrences -I jscomp/others/.dom.objs/melange --bs-stop-after-cmj --bs-package-output . --bs-module-name dom__ --bs-package-name melange.dom -no-alias-deps -o jscomp/others/.dom.objs/melange/dom__.cmj -c -impl jscomp/others/dom__.ml-gen)
# melc: unknown option '--bin-annot-occurrences'.
# Usage: melc [OPTION]… [filenames]…
# Try 'melc --help' for more information.
# File "jscomp/runtime/.melange_mini_stdlib.objs/melange/_unknown_", line 1, characters 0-0:
# (cd _build/default && bin/melc.exe -w -40 -nostdlib -nopervasives -bin-annot -bin-annot-occurrences -I jscomp/runtime/.melange_mini_stdlib.objs/melange --bs-stop-after-cmj --bs-package-output . --bs-module-name melange_mini_stdlib --bs-package-name melange.__private__.melange_mini_stdlib -no-alias-deps -o jscomp/runtime/.melange_mini_stdlib.objs/melange/melange_mini_stdlib.cmj -c -impl jscomp/runtime/melange_mini_stdlib.pp.ml)
# melc: unknown option '--bin-annot-occurrences'.
# Usage: melc [OPTION]… [filenames]…
# Try 'melc --help' for more information.
```

**Comment by anmonteiro** [comment]
@mseri that's not related to this release, and was fixed in Melange 4.0.1-52. we could likely even disable that release.

**Comment by anmonteiro** [comment]
disabled in https://github.com/ocaml/opam-repository/pull/26301

**Comment by mseri** [comment]
Thanks

**Pull request merged**
