### PR TITLE
Litiom 4.0 will not work with Eliom 5.0

### PR DESCRIPTION
**Pull request by darioteixeira**

### CODE REVIEW

**Comment by darioteixeira** [comment]
The current `js_of_ocaml` package is broken, which is why Travis can't complete the test.  Please restart Travis once the `js_of_ocaml` issue gets fixed.

**Comment by dsheets** [comment]
`reactiveData` is an optional dependency of `js_of_ocaml` 2.7 so it was not tested by the CI (hmm maybe we should work some more on those tests). Reported upstream at ocsigen/js_of_ocaml#412.

**Comment by hhugo** [comment]
fix for js_of_ocaml https://github.com/ocaml/opam-repository/pull/5496

**Comment by dsheets** [comment]
@darioteixeira please remove the `camlhighlight` package from this PR branch.

**Comment by darioteixeira** [comment]
> @darioteixeira please remove the camlhighlight package from this PR branch.

Yeah, I forgot that Github adds subsequent commits to any open PR.  But how do I tell it not to?

**Comment by darioteixeira** [comment]
I simply reverted the last commit.  Hopefully this won't confuse Travis...

**Comment by dsheets** [comment]
The PR tracks the branch. You need to use a different branch if you want to have multiple PRs in flight simultaneously. Also, you can simply force-push to the branch and GitHub will track that correctly in the PR.

**Comment by darioteixeira** [comment]
@dsheets: Ah, makes sense, thanks!  Anyway, Travis will need to be restarted after the issue with `js_of_ocaml` gets fixed.

**Pull request merged**
