### PR TITLE
+ ubpf 0.1

### PR DESCRIPTION
**Pull request by cyberhuman**
OCaml bindings for the [Userspace eBPF VM](https://github.com/iovisor/ubpf).

### CODE REVIEW

**Comment by avsm** [comment]
very cool! if you ever have an interest in building a DSL to generate eBPF code, I would be interested in using it :-)

**Comment by cyberhuman** [comment]
@avsm we have a simple dsl and an assembler, will be releasing it soon, too.

**Comment by avsm** [comment]
Great! On this PR, it looks like some versions of C compilers shipped with Ubuntu 16.04, Alpine and CentOS are having compilation errors.  E.g.:

```
# bpf.h:15:10: error: expected ',' or '...' before '&&' token
#    bpf(bpf&&);
#           ^
# bpf.h:15:12: error: invalid constructor; you probably meant 'ubpf::bpf (const ubpf::bpf&)'
#    bpf(bpf&&);
#             ^
# bpf.h:16:21: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
#    bpf(const bpf&) = delete;
#                      ^
```

Are these something you can look at upstream, or should we constrain the package to not try to install on these distributions?

**Comment by cyberhuman** [comment]
I'd prefer not to look into the ancient compiler issue (it's 2018, why full support C++11 is not there?). I don't know how to limit the distributions though.
But I saw there was another case of byte order functions missing, will have another look later today.

**Comment by kit-ty-kate** [comment]
Looks good. There is just a failure on macos. Would you know where it comes from? I don't know which package gives `endian.h`:
```
#=== ERROR while compiling ubpf.0.1 ===========================================#
# context     2.0.1 | macos/x86_64 | ocaml-base-compiler.4.06.1 | file:///Users/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-base-compiler.4.06.1/.opam-switch/build/ubpf.0.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ubpf -j 1
# exit-code   1
# env-file    ~/.opam/log/ubpf-95268-a71bb4.env
# output-file ~/.opam/log/ubpf-95268-a71bb4.out
### output ###
#         make src/ubpf_c/dllubpf_c_stubs.so,src/ubpf_c/libubpf_c_stubs.a (exit 2)
# (cd _build/default/src/ubpf_c/ubpf/vm && /usr/bin/make)
# gcc -Wall -Werror -Iinc -O2 -g -fPIC   -c -o ubpf_vm.o ubpf_vm.c
# ubpf_vm.c:18:10: fatal error: 'endian.h' file not found
# #include <endian.h>
#          ^
# 1 error generated.
# make: *** [ubpf_vm.o] Error 1
```

**Comment by cyberhuman** [comment]
There is some issue with CI, could you please restart it.

**Comment by cyberhuman** [comment]
Eh, I'll limit package not to be available on macos, since ubpf does not support it (think linux-specific headers, elf dependency, etc).

**Comment by cyberhuman** [comment]
CI issues again...

**Comment by mseri** [comment]
Thanks. Seems to be working fine now

**Pull request merged**
