### PR TITLE
2 packages from c-cube/tiny_httpd at 0.12

### PR DESCRIPTION
**Pull request by c-cube**
This pull-request concerns:
-`tiny_httpd.0.12`: Minimal HTTP server using good old threads
-`tiny_httpd_camlzip.0.12`: Interface to camlzip for tiny_httpd

---
* Homepage: https://github.com/c-cube/tiny_httpd/
* Source repo: git+https://github.com/c-cube/tiny_httpd.git
* Bug tracker: https://github.com/c-cube/tiny_httpd/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The error persists

**Comment by c-cube** [comment]
It's in a submodule, but maybe dune didn't copy it?

**Comment by kit-ty-kate** [comment]
ah, submodules are not included in the archives autogenerated by git/github. You need to upload the archive yourself (or using dune-release --include-submodules for example)

**Comment by kit-ty-kate** [comment]
What’s the reason for vendoring curly instead of depending on it? Is this a fork for a special feature or something?

**Comment by c-cube** [comment]
damnit, the sandbox breaks tests :/

**Comment by c-cube** [comment]
well, actually a bug :sweat_smile:

**Comment by kit-ty-kate** [comment]
Awesome! Thanks!

**Pull request merged**
