### PR TITLE
vorbis.0.7.1

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by toots** [comment]
The revdep checks failed on outdated packages. I can remove them but it doesn't seem like this is the usual way to proceed. Let me know!

**Comment by mseri** [comment]
Looks good. Please add `available: [ocaml-version >= "4.03"]` to the opam files

**Comment by mseri** [comment]
It would also be great if you can add the necessary upper bounds to the outdated packages

**Comment by toots** [comment]
I'll do what I can. I think `schroedinger` should be removed, the upstream library has been sunset now.

**Comment by toots** [comment]
Ok, I've added the `[ocaml-version >= "4.03"]`. I've tried to add upper-bound and such for the outdated modules but it's pushing them further into the CI, with reveps and distros testing. I really think these old packages should be left as they are or simply removed. There's no need to keep maintaining them, they're mostly and only deps for liquidsoap.

**Comment by mseri** [comment]
I think it is fine as it is, I’ll see what we can do for the rest. Thanks for the help.

**Comment by toots** [comment]
Thanks!

**Pull request merged**
