### PR TITLE
ppx_regexp 0.3.2

### PR DESCRIPTION
**Pull request by paurkedal**
This is a minor update to make ppx_regexp compatible with re 1.7.2 (cf. #11502).

### CODE REVIEW

**Comment by paurkedal** [comment]
It looks like m4 is missing on the Alpine image.

**Comment by jpdeplaix** [comment]
Yes it is to be expected, sorry for that.
Hum, could you add the appropriate constraints to the older versions that have the issue mentioned in #11502 ?

**Comment by paurkedal** [comment]
Good idea. It seems the re change happen in version 1.7.1, so I push an update accordingly.

**Comment by paurkedal** [comment]
I made the wrong call on the version requirement, as I had tested with re.1.7.1 pinned to the dev repo without noticing.  So, this release will require re 1.7.2.  I think the best thing to do then is that I send a separate PR for the constraint of the old packages to be applied before #11502 and then I rebase and fix the constraint of this PR after.

**Comment by jpdeplaix** [comment]
@paurkedal mmh are you talking about the ```~``` suffix to ```"re" {< "1.7.1~"}``` ?

**Comment by paurkedal** [comment]
@jpdeplaix No that has no effect, since there are no beta-release, rather I missed that the API change was in 1.7.2 since I had pinned my 1.7.1 version to the dev repo.  I created a separate PR for constraining the old versions as reference above.

**Comment by jpdeplaix** [comment]
Looks good. Thanks a lot !

**Pull request merged**
