### PR TITLE
+ docker 0.1

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by samoht** [comment]
Would it be possible to use a slightly less ambiguous name? :-)

**Comment by Chris00** [comment]
Why is it ambiguous?  (Or do you consider the [Docker](https://www.docker.com/) project has actually such a name?)

**Comment by avsm** [comment]
Is this related to https://github.com/arjunguha/ocaml-docker's bindings at all?

**Comment by arjunguha** [comment]
Mine are sort of defunct at the moment. I'm looking forward to some up to date bindings!

**Comment by avsm** [comment]
Thanks @arjunguha!

@Chris00 @samoht there are a few bindings, floating around:

- avsm/ocaml-dockerfile: a eDSL for generating `Dockerfiles`
- avsm/ocaml-docker-scripts: generate containers for OCaml base images

How about calling this package `docker-api`? That would make it obvious that it's not anything to do with Dockerfiles or the CI stuff, and still show up on searches for `opam search docker`.

**Comment by Chris00** [comment]
On Tue, 23 Feb 2016 03:41:21 -0800, Anil Madhavapeddy wrote:
> 
> Is this related to https://github.com/arjunguha/ocaml-docker's bindings at all?

No, I was unaware of the above.  This was extracted from a project that was started at about the same time as the repo you mention was created.  It does not seem to be much developed BTW (but supports Lwt which I do not ATM — I intend to eventually...).

**Comment by Chris00** [comment]
On Tue, 23 Feb 2016 03:55:24 -0800, Anil Madhavapeddy wrote:
> 
> Thanks @arjunguha!
> 
> @Chris00 @samoht there are a few bindings, floating around:
> 
>   * avsm/ocaml-dockerfile: a eDSL for generating Dockerfiles
>   * avsm/ocaml-docker-scripts: generate containers for OCaml base images
> 
> How about calling this package docker-api? That would make it obvious that it's not anything to do with Dockerfiles or the CI stuff, and still show up on searches for opam search docker.

I'm OK with renaming it docker-api.  Is it a problem that the module is named Docker or should I change that as well?

**Comment by Chris00** [comment]
I've renamed the package (but *not* the module `Docker`) to `docker-api` as requested.

**Comment by avsm** [comment]
Much appreciated! Naming the module `Docker` sounds right to me... this is just to disambiguate the various Docker-related libraries.

**Comment by OCamlPro-Henry** [comment]
Would it be worth renaming the ocamlfind package ? Not sure about this, what's the current policy ?

**Comment by avsm** [comment]
That's up to the package maintainer -- OPAM is only really concerned about the OPAM metadata, and anything else is just a recommendation.  In this case, making the `Docker` module name match the `docker` ocamlfind package seems reasonable...

**Pull request merged**
