### PR TITLE
+hidapi.1.0

### PR DESCRIPTION
**Pull request by vbmithr**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Build fails with:
```
#=== ERROR while installing hidapi.1.0 ========================================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -j 2 -p hidapi @install
# path                 /home/opam/.opam/4.05.0/build/hidapi.1.0
# compiler             4.05.0
# exit-code            1
# env-file             /home/opam/.opam/4.05.0/build/hidapi.1.0/hidapi-7-8387e2.env
# stdout-file          /home/opam/.opam/4.05.0/build/hidapi.1.0/hidapi-7-8387e2.out
# stderr-file          /home/opam/.opam/4.05.0/build/hidapi.1.0/hidapi-7-8387e2.err
### stderr ###
# File "src/jbuild", line 5, characters 20-33:
# Error: Library "ppx_sexp_conv" not found.
# Hint: try: jbuilder external-lib-deps --missing -p hidapi @install
# Error: I couldn't find 'ocaml-migrate-parsetree.driver-main'.
# I need this library in order to use ppx rewriters.
# See the manual for details.
# Hint: opam install ocaml-migrate-parsetree
```

**Comment by vbmithr** [comment]
This will not work on macOS as well…

**Comment by kit-ty-kate** [comment]
I've added support for Alpine & CentOS that were missing.
For the record you can look for where to find the list of available packages here: https://github.com/ocaml/opam-depext/blob/master/README.md

**Comment by vbmithr** [comment]
There is still an issue with `pkg-config` files that are not installed with all packages… as it is, this will still fail.

**Comment by kit-ty-kate** [comment]
Pretty much all green. Alpine is failing because the `hidapi-dev` package is only available on the `edge` version. Thanks!

**Pull request merged**
