### PR TITLE
ocaml-monadic 0.1.1

### PR DESCRIPTION
**Pull request by zepalmer**
Updating ocaml-monadic to v0.1.1.

### CODE REVIEW

**Comment by zepalmer** [comment]
Hm; the CI build seems to have failed due to an apt repository configuration error on the test machine.  Anything I should do?

**Comment by avsm** [comment]
I've restarted the failing job.

**Comment by zepalmer** [comment]
Thanks; it seems to be good now.  :)

**Comment by avsm** [comment]
This also fails on OCaml trunk with: (https://travis-ci.org/ocaml/opam-repository/jobs/76852785)

```
# Error: This expression has type string but an expression was expected of type
#          Asttypes.arg_label
# Command exited with code 2.
```

If you could add

```
available: [ocaml-version < "4.03.0"]
```

that will restrict it appropriately.

**Comment by zepalmer** [comment]
I've submitted that as a different pull request.  Thanks for the help.  Let's hope the data type for the AST stabilizes soon!  :)

**Pull request closed without merging**
