### PR TITLE
Adds cpdf v2.5

### PR DESCRIPTION
**Pull request by johnwhitington**

### CODE REVIEW

**Comment by johnwhitington** [comment]
Then the CamlPDF dependency has not been installed at all on those machines, it seems. The OPAM file uses the "version" idiom:

```
depends: [
   "ocaml" {>= "4.10.0"}
   "ocamlfind" {build}
   "camlpdf" {= version}
 ]
```

Perhaps something is going wrong with 'version'?

**Comment by kit-ty-kate** [comment]
It’s camlpdf.cmxa that is missing. I found the issue. camlpdf’s Makefile uses `which`, which is not a standard posix tool and not available on those distributions: https://github.com/johnwhitington/camlpdf/blob/master/Makefile#L24

**Comment by kit-ty-kate** [comment]
I’ve fixed it in https://github.com/ocaml/opam-repository/pull/20488/commits/9d4282269f5f061e0fcc898ae6b12006cdf54c8e

If you could avoid using `which` altogether in future releases that would be awesome as well (simply calling `ocamlopt -version` is an equally simple test to detect if it is there)

**Comment by johnwhitington** [comment]
Thanks. Fixed for the future in  https://github.com/johnwhitington/camlpdf/commit/b56d0103ca863fad26668d1dc30027b54887d2c7

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
