### PR TITLE
Add graphql_parser.0.13.0

### PR DESCRIPTION
**Pull request by andreas**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I think the older versions of `graphql` need some constraints on `graphql_parser`:
Screenshot from 2019-10-09 11-37-48
Could you confirm that? They fail during tests, for instance:
```
# -- schema.004 [select operation (one operation, no operation name).] Failed --
# in /home/opam/.opam/4.09/.opam-switch/build/graphql.0.4.0/_build/default/graphql/test/_build/_tests/3ADB7508-0F1F-49CA-9C9D-0568837A61E6/schema.004.output:
# [failure] Line 1 col 1: Syntax error
# 
# The full test results are available in `/home/opam/.opam/4.09/.opam-switch/build/graphql.0.4.0/_build/default/graphql/test/_build/_tests/3ADB7508-0F1F-49CA-9C9D-0568837A61E6`.
# 6 errors! in 0.005s. 43 tests run.
```

**Comment by andreas** [comment]
> I think the older versions of `graphql` need some constraints on `graphql_parser`: [...]
> Could you confirm that?

Yes, I agree with that assessment. I'm surprised why it hasn't shown up sooner though. I've added constraints to the failing versions of `graphql`.

**Comment by samoht** [comment]
still broken with graphql-lwt.0.7.0:

```
# Note: You can use "dune upgrade" to convert your project to dune.
#       ocamlc graphql-lwt/test/.lwt_test.eobjs/byte/lwt_test.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.09/bin/ocamlc.opt -w -40 -g -bin-annot -I graphql-lwt/test/.lwt_test.eobjs/byte -I /home/opam/.opam/4.09/lib/alcotest -I /home/opam/.opam/4.09/lib/angstrom -I /home/opam/.opam/4.09/lib/astring -I /home/opam/.opam/4.09/lib/base -I /home/opam/.opam/4.09/lib/base/caml -I /home/opam/.opam/4.09/lib/base/shadow_stdlib -I /home/opam/.opam/4.09/lib/base64 -I /home/opam/.opam/4.09/lib/bigarray-compat -I /home/opam/.opam/4.09/lib/bigstringaf -I /home/opam/.opam/4.09/lib/biniou -I /home/opam/.opam/4.09/lib/bytes -I /home/opam/.opam/4.09/lib/cmdliner -I /home/opam/.opam/4.09/lib/cohttp -I /home/opam/.opam/4.09/lib/cohttp-lwt -I /home/opam/.opam/4.09/lib/cohttp-lwt-unix -I /home/opam/.opam/4.09/lib/conduit -I /home/opam/.opam/4.09/lib/conduit-lwt -I /home/opam/.opam/4.09/lib/conduit-lwt-unix -I /home/opam/.opam/4.09/lib/domain-name -I /home/opam/.opam/4.09/lib/easy-format -I /home/opam/.opam/4.09/lib/fieldslib -I /home/opam/.opam/4.09/lib/fmt -I /home/opam/.opam/4.09/lib/graphql -I /home/opam/.opam/4.09/lib/graphql_parser -I /home/opam/.opam/4.09/lib/ipaddr -I /home/opam/.opam/4.09/lib/ipaddr-sexp -I /home/opam/.opam/4.09/lib/ipaddr/unix -I /home/opam/.opam/4.09/lib/logs -I /home/opam/.opam/4.09/lib/lwt -I /home/opam/.opam/4.09/lib/lwt/unix -I /home/opam/.opam/4.09/lib/macaddr -I /home/opam/.opam/4.09/lib/magic-mime -I /home/opam/.opam/4.09/lib/mmap -I /home/opam/.opam/4.09/lib/ocaml/threads -I /home/opam/.opam/4.09/lib/ocplib-endian -I /home/opam/.opam/4.09/lib/parsexp -I /home/opam/.opam/4.09/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.09/lib/re -I /home/opam/.opam/4.09/lib/re/posix -I /home/opam/.opam/4.09/lib/result -I /home/opam/.opam/4.09/lib/rresult -I /home/opam/.opam/4.09/lib/seq -I /home/opam/.opam/4.09/lib/sexplib -I /home/opam/.opam/4.09/lib/sexplib0 -I /home/opam/.opam/4.09/lib/stdlib-shims -I /home/opam/.opam/4.09/lib/stringext -I /home/opam/.opam/4.09/lib/uri -I /home/opam/.opam/4.09/lib/uri/services -I /home/opam/.opam/4.09/lib/uri/sexp -I /home/opam/.opam/4.09/lib/uuidm -I /home/opam/.opam/4.09/lib/yojson -I graphql-lwt/src/.graphql_lwt.objs/byte -I graphql-lwt/src/.graphql_lwt.objs/native -no-alias-deps -o graphql-lwt/test/.lwt_test.eobjs/byte/lwt_test.cmo -c -impl graphql-lwt/test/lwt_test.ml)
# File "graphql-lwt/test/lwt_test.ml", line 11, characters 38-55:
# 11 | end : Alcotest.TESTABLE with type t = Yojson.Basic.json)
```

**Comment by andreas** [comment]
Added a constraint to `graphql-lwt.0.7.0` to fix the error.

**Comment by kit-ty-kate** [comment]
thanks a lot!

**Pull request merged**
