### PR TITLE
+ mysql 1.2.4

### PR DESCRIPTION
**Pull request by ygrek**
build is expected to fail due to depext (see explanation in post-messages)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I've been a bit puzzled for a few months about what to do with this package. I could see it fails in the CIs and I was unsure what to do about it.

I'd really like to have this issue fixed if possible as it might also be repulsive and confusing for users as well. I would have one questions: how many forks does this package support? If it's only a handful I think it would be good to split this package into a small number of sub-package (one for every fork supported) but pointing to the same code. It would be a bit less cryptic for users (if it is actually doable) I think

**Comment by hcarty** [comment]
One positive aspect of the current name is that it is clear what the package provides - a library for communicating with mysql (compatible) servers.  It would be nice to keep that clarity if possible.

Would sub-packages help in practice?  The issue, as I understand it, is that there are four or more potential packages to rely on to provide the necessary C client library which are all external to opam: mysql, mysql c connector, mariadb, mariadb c connector.  Each OS may support and provide packages for multiple of those.  _And_ the specific packages available vary by OS/distribution version.  Do we have a clean way to represent that kind of open-ended dependency in opam?  Does it make things clearer if a user has to pick from `mysql-mysql`, `mysql-mariadb` and maybe more versus installing `mysql` directly?

I have found it useful that this single package works across different versions of the mysql/mariadb client libraries.  It makes it much easier to have a codebase which compiles and works across macos and various flavors of Linux which each have their own combination of C client libraries available.

Subpackages wouldn't break that if they all point to the same code.  I'm not sure which would be more confusing/concerning though - seeing that `mysql-mysql` is being installed by opam (and it works!) when some flavor of mariadb is installed locally.  Or always installing `mysql` with opam, regardless of the local client library being bound to, and having the opam CI never properly turn green.

**Comment by hcarty** [comment]
We also may be able to improve the CI situation once opam 2.1.x lands as, if I recall correctly, it integrates depext with some improvements which should allow us to specify different system package requirements based on distribution version.

**Comment by ygrek** [comment]
ftr the root of the problem originally was that opam didn't handle alternatives well (installed all of them, instead of being satisfied by one). Let me try pushing with conf-* alternatives dep, seems it works better now.

PS some rambling before trying to actually fix issue: 
I dont think splitting this will make it easier for users. Conceptually what this library does is binds to mysql api which can be implemented by many libraries, for today those are libmysqlclient from Oracle Mysql, old libmysqlclient from original mysql (some users still have it), mysql compatible layer provided by mariadb connector/c which was at different times shipped as libmysqlclient then libmariadbclient and now libmariadb in debian. This already causes enough troubles when upgrading, changing name of package to match that will not help.
Maybe we can solve this by having some opam package overlay for CI - ie ability to specify depext for CI. It could be x- field or a separate (partial) opam file or just a shell script to run before installing this package? The latter is easiest and hackiest from tooling effort I guess, would be my preferred method :)

**Comment by ygrek** [comment]
travis now succeeds.
datakit shows that conf-mysql is not installable on new OS which is expected but it works for travis image which apparently has older distro?

**Comment by kit-ty-kate** [comment]
Sorry for taking so much time. I think this is an acceptable partial fix for the moment. It doesn't work on debian stable but it works on debian unstable that I use on [check.ocamllabs.io](http://check.ocamllabs.io). Sorry again, thanks!

**Comment by hcarty** [comment]
Adding the conf-* requirement has broken builds on macos + homebrew.  It should work with conf-mariadb but the pkg-config check should be `pkg-config libmariadb` rather than `pkg-config mariadb` at https://github.com/ocaml/opam-repository/blob/master/packages/conf-mariadb/conf-mariadb.1/opam#L8.

I'd like to unbreak this if at all possible.  Is it possible to select the build command with the same granularity as the depext fields are specified?

**Comment by kit-ty-kate** [comment]
@hcarty yes, this should be fixable with `["pkg-config" "libmariadb" {os = "macos"} "mariadb" {os != "macos"}]` or something like that. I'm creating a PR right now.

**Comment by hcarty** [comment]
Thank you @kit-ty-kate!

**Pull request merged**
