### PR TITLE
added packages/molenc/molenc.2.0.0

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There are various problems in system rdkit packages but the package seems good enough (according to the Travis checks)

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by UnixJunkie** [comment]
Its strange: I updated conf-rdkit recently so I guess it was working on most systems at that time.
But thanks for merging.

**Comment by kit-ty-kate** [comment]
debian stable has been upgraded, this is maybe why

**Pull request merged**
