### PR TITLE
added packages/orandforest/orandforest.1.0.0

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by samoht** [comment]
```
he following dependencies couldn't be met:
  - orandforest -> oc45
Your request can't be satisfied:
  - No package named oc45 found.
```

**Comment by samoht** [comment]
Can you rebase this PR to master? I've merged your oc45 submission.

**Comment by UnixJunkie** [comment]
maintainers should be able to do that within github...

**Comment by UnixJunkie** [comment]
superseeded by https://github.com/ocaml/opam-repository/pull/11417

**Pull request closed without merging**
