### PR TITLE
[new release] raylib (0.5.1)

### PR DESCRIPTION
**Pull request by tjammer**
CHANGES:

* Expose ctypes type value
* Expose audio-related fields
* Add rlgl bindings (module Raylib.Rlgl)
* Upgrade raylib to 4.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Your dune-configure script doesn’t seem to support linux/s390x:
```
#=== ERROR while compiling raylib.0.5.0 =======================================#
# context              2.1.2 | linux/s390x | ocaml-base-compiler.4.13.1 | pinned(https://github.com/tjammer/raylib-ocaml/releases/download/0.5.0/raylib-0.5.0.tbz)
# path                 ~/.opam/4.13/.opam-switch/build/raylib.0.5.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p raylib -j 3 @install
# exit-code            1
# env-file             ~/.opam/log/raylib-8141-6e7e04.env
# output-file          ~/.opam/log/raylib-8141-6e7e04.out
### output ###
# (cd _build/default/src/c && config/configure.exe)
# Error: unsupported system: elf
```
See https://github.com/ocaml/ocaml/issues/10613 for more details about the `%{system}` variable

**Comment by tjammer** [comment]
If I understand correctly, this will be fixed if I identify the "elf" system variable as linux, right?

**Comment by kit-ty-kate** [comment]
yes

**Comment by tjammer** [comment]
Ah, the C lib doesn't build. Guess the message about not being supported was correct after all

**Comment by kit-ty-kate** [comment]
I believe you also need to add `elf` here: https://github.com/tjammer/raylib-ocaml/blob/76955c30d0a776138daeb93bfc73b104aefc6f6d/src/c/dune#L68

**Comment by kit-ty-kate** [comment]
It worked! :tada:

**Comment by tjammer** [comment]
Perfect, many thanks

**Pull request merged**
