### PR TITLE
Package prbnmcn-ucb1.0.0.1

### PR DESCRIPTION
**Pull request by igarnier**
### `prbnmcn-ucb1.0.0.1`
UCB1 algorithm for multi-armed bandits
UCB1 algorithm for multi-armed bandits

---
* Homepage: http://github.com/igarnier/prbnmcn-ucb1
* Source repo: git+https://gitlab.com/igarnier/monorepo.git
* Bug tracker: http://github.com/igarnier/prbnmcn-ucb1

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by igarnier** [comment]
I see that `dune` botched my opam files :(
I can close this PR and reopen another one, if that's the best way forward. Let me know!

**Comment by kit-ty-kate** [comment]
> I see that `dune` botched my opam files :(
> I can close this PR and reopen another one, if that's the best way forward. Let me know!

that's ok, the dune file inside the archive doesn't really matter for opam-repository. However would it be possible for you to upgrade to at least `(lang dune 2.7)` and remove dune from the list of manually set dependencies (dune adds it already and there is a known issue in dune when it is manually defined)

**Comment by igarnier** [comment]
Thanks a lot for fixing the `.opam`. I'll do what you suggest and fix my `dune-project`s (both dune version and spurious constraint). That should also fix the generated `.opam`.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
