### PR TITLE
conf-libsvm for libsvm v3

### PR DESCRIPTION
**Pull request by akabe**
This package only checks libsvm is installed on the system (for [libsvm-ocaml](https://bitbucket.org/ogu/libsvm-ocaml/)).

Related PR: https://github.com/ocaml/opam-repository/pull/10186

### CODE REVIEW

**Comment by UnixJunkie** [comment]
ok, I see it now.

**Comment by UnixJunkie** [comment]
why not using libsvm-devel for centos?

**Comment by UnixJunkie** [comment]
I would suggest this for gentoo:

      [["gentoo"] ["sci-libs/libsvm"]]

and this for archlinux:

      [["archlinux"] ["libsvm"]]

**Comment by UnixJunkie** [comment]
Why not this for osx?

      [["homebrew" "osx"] ["libsvm"]]

**Comment by akabe** [comment]
@UnixJunkie Thank you for advices. I'll add centos, gentoo and archlinux. libsvm in osx homebrew is installed at a strange place: /usr/local/Cellar/3.22. A path depending to a library version number is hassle to use. I need to pass `-I`, `-L` flags according to the version.

**Comment by UnixJunkie** [comment]
Are you sure there are no things installed or soft linked in
/usr/local/include and usr/local/lib ?
I think this is where user installed things go on osx/darwin.

**Comment by akabe** [comment]
@UnixJunkie I know, but I have no simple idea for getting the version-dependent prefix path (e.g., `/usr/local/Cellar/libsvm/3.22`) of libsvm. Do you know?

**Comment by dbuenzli** [comment]
> @UnixJunkie I know, but I have no simple idea for getting the version-dependent prefix path (e.g., /usr/local/Cellar/libsvm/3.22) of libsvm. Do you know?

As @UnixJunkie mentioned this will be linked under /usr/local/lib so there's no need to hunt it there.

**Comment by akabe** [comment]
Oh. Sorry, I misunderstood. I checked libsvm.dylib is installed in /usr/local/lib. I fix it.

**Comment by akabe** [comment]
I added archlinux and gentoo packages, but centos and osx still uses a script by the following reasons:

- centos: the standard repository doesn't have `libsvm-devel`. `epel-release` needs to be installed **before** `libsvm-devel`.
- osx: `svm.h` is installed in `/usr/local/include`, not `/usr/local/include/libsvm`. I created a symbolic link for compatibility with other environments.

**Comment by UnixJunkie** [comment]
Would it be possible for centos to list both epel-release and libsvm-devel (in that order) as depexts ?

**Comment by UnixJunkie** [comment]
Sorry for asking many changes: I really don't like the source lines in opam files (they look like a huge security breach).

**Comment by akabe** [comment]
I agree. Actually I don't want to use `source`. However, `["epel-release" "libsvm-devel"]` won't work, i.e., `yum install epel-release libsvm-devel` fails but `yum install epel-release; yum install libsvm-devel` works well. `epel-release` is a virtual package to add an extra repository. It should be installed **before** libsvm-devel, not at the same time.

**Comment by akabe** [comment]
Please tell me if you have a good idea :-)

**Comment by UnixJunkie** [comment]
I have an idea but I need to ask the opam maintainers something.

**Comment by UnixJunkie** [comment]
The dirty fix proposal that comes first out of my head:
in the build section, as the first line, put something like this:

    ["sh" "-c" "test -f /etc/centos-release && sudo yum install epel-release && sudo yum install libsvm-devel"]

then remove the line for centos in the depext section.

**Comment by avsm** [comment]
I'll take a look at https://github.com/ocaml/opam-repository/pull/10195 shortly, which should add epel support into opam depext.

**Comment by akabe** [comment]
Oh! opam-depext will support epel-release: https://github.com/ocaml/opam-depext/pull/77

**Comment by akabe** [comment]
@avsm @UnixJunkie `conf-libsvm`  uses `source` only on `centos` and `alpine` now. https://github.com/ocaml/opam-depext/pull/77 solves the `centos` case, but I guess that it will take a little more time to be merged. I propose to merge this PR for now, and migrate all `conf-*` packages using `epel-release` (.e.g., `conf-zmq`, `conf-hdf5`) after https://github.com/ocaml/opam-depext/pull/77 is merged. What do you think about my idea?

**Comment by akabe** [comment]
I agree. You are right, but `depexts` section doesn't support execution of local scripts. I think it takes a time to implement local file execution and ocaml/opam-depext#77 in `opam depext`. Should I wait the implemetation?

**Comment by UnixJunkie** [comment]
It is ok, we can always improve the package later. Thanks.

**Comment by UnixJunkie** [comment]
If this is accepted, then I will update https://github.com/ocaml/opam-repository/pull/10186
to take into account this new package

**Comment by UnixJunkie** [comment]
all CI tests are green so it looks OK to merge

**Comment by akabe** [comment]
@avsm Please merge this PR.

**Comment by samoht** [comment]
done, thanks for all your efforts!

**Pull request merged**
