### PR TITLE
[new release] x509 (1.0.4)

### PR DESCRIPTION
**Pull request by hannesm**
Public Key Infrastructure (RFC 5280, PKCS) purely in OCaml

- Project page: <a href="https://github.com/mirleft/ocaml-x509">https://github.com/mirleft/ocaml-x509</a>
- Documentation: <a href="https://mirleft.github.io/ocaml-x509/doc">https://mirleft.github.io/ocaml-x509/doc</a>

##### CHANGES:

* **breaking change** Allow decoding of negative serial numbers (mirleft/ocaml-x509#177 @hannesm)
  Now, `serial` returns the entire (integer) value as a string - previously the
  potentially leading 0 byte was removed. So:
  -serial d795 49bd 1a67 1751
  +serial 00d7 9549 bd1a 6717  51
* Add alternate SHA1RSA OID 1.3.14.3.2.29 (mirleft/ocaml-x509#176 @mefyl)
* Allow custom pretty printers for unknown X509 extensions (mirleft/ocaml-x509#175 @reynir)
* Minor code cleanups: remove unused algorithms, remove `def` and `def'`
  (mirleft/ocaml-x509#177 @hannesm)

### CODE REVIEW

**Comment by hannesm** [comment]
hmm hmm, looks like the tls-miou-unix issue may be a regression... maybe @dinosaure has an idea about that? looks to me that the fuzzer has some invariants about the x509 certificate being generated/used!?

**Comment by dinosaure** [comment]
The test on `tls-miou-unix` tries to generate a new certificate. It seems that `x509` randomly generate a `serial_number`, see [this line](https://github.com/mirleft/ocaml-x509/blob/45c189ad4aa85ee500e11261462df1f2a7fd7eb3/lib/signing_request.ml#L190). However, on the `asn1-combinators` fails on [few specific values](https://github.com/mirleft/ocaml-asn1-combinators/blob/2f80f3495ccfa88a506d83b811d74f0a2bd63114/src/asn_prim.ml#L99). It will be nice to ensure that `x509` don't generate bad certificates.

**Comment by avsm** [comment]
Nice debugging, and a nice case of the CI tests finding a real regression!

**Comment by hannesm** [comment]
do not merge yet, I'll have an updated release later today

**Comment by hannesm** [comment]
fine to merge from our side now, once CI is fine :)

**Comment by hannesm** [comment]
err, but now finally we should be in a good shape. I finally tested this locally and couldn't find any issue anymore :)

**Comment by hannesm** [comment]
CI looks good, all failures that are unrelated :) please merge

**Comment by dinosaure** [comment]
Thanks!

**Pull request merged**
