### PR TITLE
Update starterkit descr

### PR DESCRIPTION
**Pull request by fxfactorial**

### CODE REVIEW

**Comment by samoht** [comment]
```
#=== ERROR while installing stringext.1.4.1 ===================================#
# opam-version 1.2.2
# os           linux
# command      ocaml setup.ml -build
# path         /home/travis/.opam/system/build/stringext.1.4.1
# compiler     system (4.00.1)
# exit-code    1
# env-file     /home/travis/.opam/system/build/stringext.1.4.1/stringext-8466-27656f.env
# stdout-file  /home/travis/.opam/system/build/stringext.1.4.1/stringext-8466-27656f.out
# stderr-file  /home/travis/.opam/system/build/stringext.1.4.1/stringext-8466-27656f.err
### stdout ###
# /usr/bin/ocamlopt.opt -I /usr/lib/ocaml/ocamlbuild unix.cmxa /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/travis/.opam/system/bin/ocamlfind ocamldep -package bytes -modules lib/stringext.mli > lib/stringext.mli.depends
# /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -package bytes -I lib -o lib/stringext.cmi lib/stringext.mli
# /home/travis/.opam/system/bin/ocamlfind ocamldep -package bytes -modules lib/stringext.ml > lib/stringext.ml.depends
# /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -package bytes -I lib -o lib/stringext.cmo lib/stringext.ml
# + /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -package bytes -I lib -o lib/stringext.cmo lib/stringext.ml
# File "lib/stringext.ml", line 242, characters 26-36:
# Error: Unbound value Bytes.init
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/usr/bin/ocamlbuild' lib/stringext.cma lib/stringext.cmxa lib/stringext.a lib/stringext.cmxs -tag debug' terminated with error code 10")
```

**Comment by fxfactorial** [comment]
@samoht Uh, that's odd.

**Comment by rgrinberg** [comment]
I guess `Bytes.init` doesn't exist in 4.00. Will make a point release for stringext.

**Comment by samoht** [comment]
A new one:

```
#=== ERROR while installing ocp-index.1.1.2 ===================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/system/build/ocp-index.1.1.2
# compiler     system (4.00.1)
# exit-code    2
# env-file     /home/travis/.opam/system/build/ocp-index.1.1.2/ocp-index-8458-4a3a17.env
# stdout-file  /home/travis/.opam/system/build/ocp-index.1.1.2/ocp-index-8458-4a3a17.out
# stderr-file  /home/travis/.opam/system/build/ocp-index.1.1.2/ocp-index-8458-4a3a17.err
### stdout ###
# ocp-build -init 
# ocp-build ocp-index-lib 
# ocp-build ocp-index 
# ocp-build ocp-grep 
# ocp-build ocp-browser 
### stderr ###
# [...]
# [99.1] '/usr/bin/ocamlc.opt' '-g' '-w' '+1..39-4-9-37-40' '-bin-annot' '-c' '-o' '_obuild/40d5942759a5d4928a0aa903bcfb282c/browserMain.cmo' '-I' './_obuild/ocp-browser' '-I' './src' '-I' '/home/travis/.opam/system/lib/lambda-term' '-I' '/home/travis/.opam/system/lib/zed' '-I' '/home/travis/.opam/system/lib/lwt' '-I' '/home/travis/.opam/system/lib/camomile' '-I' './_obuild/ocp-index-lib' '-I' '/usr/lib/ocaml/compiler-libs' '-I' '/usr/lib/ocaml' '-I' '/home/travis/.opam/system/lib/ocp-indent/utils' '-I' '/home/travis/.opam/system/lib/bytes' '-I' '/home/travis/.opam/system/lib/ocp-indent/lexer' '-I' '/home/travis/.opam/system/lib/react' '-I' '/home/travis/.opam/system/lib/cmdliner' 'src/browserMain.ml'
# 
# File "src/browserMain.ml", line 20, characters 6-11:
# Error: Unbound constructor Value
# 
# Error:
# Target _obuild/ocp-browser/browserMain.cmi not built
# Error:
# Target _obuild/ocp-browser/browserMain.cmo not built
# make: *** [ocp-browser] Error 2
```

@AltGr @OCamlPro-Henry any idea what's up?

**Comment by fxfactorial** [comment]
@samoht does this need to stay stalled because other packages don't install on this machine? 1) Its just a package description update and 2) I use this on work ubuntu machines with no problems installing...

**Comment by samoht** [comment]
I was hoping to see either @AltGr or @OCamlPro-Henry say something, but as they are not I'm merging this anyway. Sorry for the delay and thanks for your efforts.

**Pull request merged**
