### PR TITLE
Fix typo in packages/conf-pam/conf-pam.1/opam

### PR DESCRIPTION
**Pull request by xclerc**
In order to properly support Alpine.

### CODE REVIEW

**Comment by gasche** [comment]
The PR title says "fix typo in", but the diff suggests that the package is completely new, did not exist before. What am I missing?

**Comment by mseri** [comment]
My understanding now is that `conf-pam` was introduced here https://github.com/ocaml/opam-repository/pull/13452/files#diff-12ad48b7494e436a58ec94608c9505e3 with a typo, and this PR is fixing the typo of that PR and releasing the package. @xclerc do you prefer to add this patch to your big PR or to merge this and remove the broken `conf-pam` from there?

**Comment by xclerc** [comment]
@mseri Please do what you prefer, I am fine with both options;
I think @avsm mentioned a [sequence of merges](https://github.com/ocaml/opam-repository/pull/13452#issuecomment-468018640) but I am not sure.
 
(I did not fix it in https://github.com/ocaml/opam-repository/pull/13452 in order to avoid a CI re-run on that PR,
but as soon as we are at the merge state it doesn't matter anymore.)

**Comment by xclerc** [comment]
"Please do what you prefer": sorry I just realized it might need
an action on my end, so understand it as "tell me what you prefer"...

**Comment by mseri** [comment]
Let's introduce `conf-pam` then. Please remove it from the other PR. Now you can re-run the tests before we merge that

**Comment by xclerc** [comment]
@mseri Thanks!

(`conf-pam` removed from https://github.com/ocaml/opam-repository/pull/13452)

**Pull request merged**
