### PR TITLE
Add ctypes.0.12.0.

### PR DESCRIPTION
**Pull request by yallop**

### CODE REVIEW

**Comment by avsm** [comment]
There are a bunch of revdep failures; not triaged them all but here is one

```
#=== ERROR while compiling memcpy.0.2.0 =======================================#
# command              make
# path                 /home/opam/.opam/ocaml-base-compiler.4.03.0/.opam-switch/build/memcpy.0.2.0
# exit-code            2
# env-file             /home/opam/.opam/log/memcpy-26-d0f245.env
# output-file          /home/opam/.opam/log/memcpy-26-d0f245.out
### output ###
# Error: This expression has type
# [...]
#        but an expression was expected of type
#          < ba_repr : 'a; bigarray : 'b; carray : 'c; dims : 'd; element : 'e;
#            layout : 'f >
#          Ctypes.bigarray_class =
#            < ba_repr : 'a; bigarray : 'b; carray : 'c; dims : 'd;
#              element : 'e; layout : 'f >
#            Ctypes_static.bigarray_class
#        The first object type has no method layout
# Command exited with code 2.
# Makefile:29: recipe for target 'build' failed
# make: *** [build] Error 10
```

**Comment by yallop** [comment]
Thanks!  I'll work through these and submit separate prs as necessary.

**Comment by yallop** [comment]
The [`eigen` errors](https://ci.ocaml.io/log/saved/docker-run-c5a0521219cba0264db4abc4ff0d5738/bd2c157edc2ec6bdcc703a9308768c390741c5a5) may be network issues:

```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - oasis.0.4.8
          - ocamlmod.0.0.8
```

**Comment by avsm** [comment]
There are a lot of network issues on github today, unfortunately.

**Comment by yallop** [comment]
I'll check the revdeps again once the build's finished.  Please don't merge in the meantime.

**Comment by avsm** [comment]
restarted all builds last night

**Comment by yallop** [comment]
I've just restarted some of the builds again.  The [`eigen` build](https://ci.ocaml.io/log/saved/docker-run-12cafa1256c1b1116a93dff7faf73843/8e2e4c2ef110d1a3afa16d4a91fecd2aa4bf74bc) is finally succeeding.

**Comment by yallop** [comment]
There are a few remaining revdep failures, but they're almost all down to depext issues:

* [`hardcaml-llvsim`](https://ci.ocaml.io/log/saved/docker-run-7ed24d39d38389a925ab8285a9bd06f9/03bf166eceb2f26857b80777f30abf085d8596db) and [`llvm`](https://ci.ocaml.io/log/saved/docker-run-47b032f8827288f86288b0bef0eefaac/389e36dba7464bd995ed0a0857af9597fa85c1f1) are missing `llvm-4.0-dev`
* [`hardcaml-vpi`](https://ci.ocaml.io/log/saved/docker-run-e1fc5756459bf52f0a1fb423c8c92777/25d9f9d49be4fc233b43465feebb204c818f89a2) is missing `iverilog-vpi`
* [`mariadb`](https://ci.ocaml.io/log/saved/docker-run-cfa2220e75732de260708dc0bac2c3bf/6044f402ed6ea9d4f7160367e9308975841452e5) is missing a MariaDB client library
* [`owl`](https://ci.ocaml.io/log/saved/docker-run-b1a0538104e3b87db985bda110306db7/a15ea38ffbdfc0cd1debd5aff3a15236bfa23d15) is missing `<gsl/gsl_spmatrix.h>`
* [`sodium`](https://ci.ocaml.io/log/saved/docker-run-f363ebb26991ff790b095049be794a46/9f7a38cbf5dbfac8ef0e446be17f9e7e30d342c4) needs a more recent version of the `sodium` library
* [`tsdl`](https://ci.ocaml.io/log/saved/docker-run-04df5a5e51bc289f53b17cca181f14fb/f855ac4c1e76d16d81a91a4b63fca2f143a6cdf4), [`tsdl-image`](https://ci.ocaml.io/log/saved/docker-run-6db1afb0421581364ee95c57ec934a6d/df9931263ed92baa85b95d8b9068fce4f686f077), [`tsdl-mixer`](https://ci.ocaml.io/log/saved/docker-run-2c22ab7316ffc583d9c353ce60302fd2/3b40280fe405173c42a7ef5f5033bd5ba3b167ac), and [`tsdl-ttf`](https://ci.ocaml.io/log/saved/docker-run-134f0de791b28b921dd9b540e123ed7c/007499d03645a78c79524e89520f23dc1ce08f1c) need a more recent version of the SDL library
* [`xxhash`](https://ci.ocaml.io/log/saved/docker-run-b32bc1b0b499ddb933509324b542690b/b38657587eb32edba43930ba7f7b0e63cef5a501) is missing `<xxhash.h>`
* [`zstd`](https://ci.ocaml.io/log/saved/docker-run-fff7a88ad27e69eb9c538244e96c0fe0/d3c4244e3360283b33bc6a051d34ed8b20f3b279) is missing `libzstd-dev`

A couple of non depext issues:
* [`memcpy`](https://ci.ocaml.io/log/saved/docker-run-60ba554c4371cb30ae243b63dc53fb5f/796682bd8f90310fb3420b5e99f64ad612fa3eb1) is fixed in #9248
* [`iocaml`](https://ci.ocaml.io/log/saved/docker-run-542a2a897ae3d3a1849e8e065c015e10/b5742531df43109dfb942fb4f92c0fe7deed70d3) has an Lwt compatibility issue.  I'll open a separate PR, but it shouldn't block merging this.

So this PR is now ready to be merged.

**Comment by yallop** [comment]
> * [`iocaml`](https://ci.ocaml.io/log/saved/docker-run-542a2a897ae3d3a1849e8e065c015e10/b5742531df43109dfb942fb4f92c0fe7deed70d3) has an Lwt compatibility issue.  I'll open a separate PR

See #9268

**Pull request merged**
