### PR TITLE
[new release] docker-api (0.2)

### PR DESCRIPTION
**Pull request by Chris00**
Binding to the Docker Remote API

- Project page: <a href="https://github.com/Chris00/ocaml-docker">https://github.com/Chris00/ocaml-docker</a>
- Documentation: <a href="https://Chris00.github.io/ocaml-docker/doc">https://Chris00.github.io/ocaml-docker/doc</a>

##### CHANGES:

- Upgrade to API v1.29.
- New signature of `Container.create`.
- Add functions `Container.wait` and `Container.changes`.
- Handle errors `409 Conflict`.
- New exceptions `Docker.Failure` and `Docker.No_such_container`.
- Rename `Docker.Images` as `Docker.Image` and add the `create`
  function to pull images.
- Documentation improvements.
- New tests `ls` and `ps` and improve the other ones.
- Use [Dune](https://github.com/ocaml/dune) and
  [dune-release](https://github.com/samoht/dune-release).

### CODE REVIEW

**Comment by Chris00** [comment]
See https://github.com/ocaml/opam-repository/pull/12789

**Comment by Chris00** [comment]
For now, I made the tests _not fail_ when Docker is not present...

**Comment by mseri** [comment]
Please add a description or a synopsis. Once that is done, I think this is fine for merge. I don't know what could be a good solution for docker and conf-docker to be honest

**Comment by Chris00** [comment]
@mseri Done.  Shouldn't @camelus be extended to warn about this?

**Comment by mseri** [comment]
Yes, afaik this should be fixed once `opam 2.0.1` is released

**Pull request merged**
