### PR TITLE
Add google-drive-ocamlfuse 0.6.10

### PR DESCRIPTION
**Pull request by astrada**

### CODE REVIEW

**Comment by yallop** [comment]
The [4.00](https://travis-ci.org/ocaml/opam-repository/jobs/190736873) and [3.12](https://travis-ci.org/ocaml/opam-repository/jobs/190736874) builds are failing because the package uses record label disambiguation:

```
# File "src/bufferPool.ml", line 57, characters 11-210:
# Error: The record field label mutex belongs to the type t
#        but is mixed here with labels of type buffer
# Command exited with code 2.
```

Could you please add an OCaml version constraint as follows (or update the package so that it doesn't use record label disambiguation), @astrada?

```
available: [ ocaml-version >= "4.01.0" ]
```

**Comment by astrada** [comment]
Oops, that was unintentional. I must have missed the warning. Will fix upstream, thanks!

**Comment by yallop** [comment]
The flambda build is failing, but should be fixed by #8246, so we'll rebuild this PR when that's merged.

**Comment by yallop** [comment]
Merging (cf. https://github.com/ocaml/opam-repository/pull/8243#issuecomment-271821119)

**Pull request merged**
