### PR TITLE
add x-maintenance-intent to some packages I maintain

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
Please note that I checked the lint issues manually:
"Error in otr.1.0.0: Your dune-project file indicates that this package requires at least dune 2.0 but your opam file only requires dune >= 1.0.0. Please check which requirement is the right one, and fix the other."

Hold one, the dune-project file has "(lang dune 1.0)" -- how did you conclude "2.0"?

"Error in logs-syslog.0.4.1: Your dune-project file indicates that this package requires at least dune 2.0 but your opam file only requires dune >= 1.1.0. Please check which requirement is the right one, and fix the other."

Hold one, the dune-project file has "(lang dune 1.1)" -- how did you conclude "2.0"?

"Error in letsencrypt-mirage.1.0.0: Your dune-project file indicates that this package requires at least dune 2.0 but your opam file only requires dune >= 1.2.0. Please check which requirement is the right one, and fix the other.
Error in letsencrypt-dns.1.0.0: Your dune-project file indicates that this package requires at least dune 2.0 but your opam file only requires dune >= 1.2.0. Please check which requirement is the right one, and fix the other.
Error in letsencrypt-app.1.0.0: Your dune-project file indicates that this package requires at least dune 2.0 but your opam file only requires dune >= 1.2.0. Please check which requirement is the right one, and fix the other.
Error in letsencrypt.1.0.0: Your dune-project file indicates that this package requires at least dune 2.0 but your opam file only requires dune >= 1.2.0. Please check which requirement is the right one, and fix the other."

Hold one, the dune-project file has "(lang dune 1.2)" -- how did you conclude "2.0"?

"Error in kdf.1.0.0: Your dune-project file indicates that this package requires at least dune 2.0 but your opam file only requires dune >= 1.8.0. Please check which requirement is the right one, and fix the other."

Hold one, the dune-project file has "(lang dune 1.8)" -- how did you conclude "2.0"?

"Error in icalendar.0.1.9: Your dune-project file indicates that this package requires at least dune 2.0 but your opam file only requires dune >= 1.3. Please check which requirement is the right one, and fix the other."

Hold one, the dune-project file has "(lang dune 1.3)" -- how did you conclude "2.0"?

"Error in duration.0.2.1: Your dune-project file indicates that this package requires at least dune 2.0 but your opam file only requires dune >= 1.0. Please check which requirement is the right one, and fix the other."

Hold one, the dune-project file has "(lang dune 1.0)" -- how did you conclude "2.0"?

"Error in asn1-combinators.0.3.2: Your dune-project file indicates that this package requires at least dune 2.0 but your opam file only requires dune >= 1.2.0. Please check which requirement is the right one, and fix the other."

Hold one, the dune-project file has "(lang dune 1.2)" -- how did you conclude "2.0"?

So, I think there's something wonky in your CI. Or I don't quite understand it (then I'd suggest to make your error message slightly easier to understand). Or I'm just wrong and didn't sleep enough ;)

**Comment by hannesm** [comment]
I reported the issue mentioned above upstream, with a diagnosis what there likely fails https://github.com/ocurrent/opam-repo-ci/issues/405

**Comment by mseri** [comment]
Thanks a lot!

**Comment by punchagan** [comment]
Apologies for the bug eating into your opam repository maintenance time, @hannesm! A fix has now been deployed and the lint on this PR is passing. Thanks for debugging it and for your detailed bug reports.

**Comment by hannesm** [comment]
@punchagan and @shonfeder thanks for running and fixing opam-repo-ci! <3

**Comment by mseri** [comment]
Thanks

**Pull request merged**
