### PR TITLE
orakuda.1.2.x fixes

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
orakuda 1.2.0 fails to install case Error: Unbound module Spotlib.Spot.Unix.Command

**Comment by camlspotter** [comment]
orakuda 1.2.0 fails to install: failed at pa_hash (p4 is not in the dependency?)

**Comment by camlspotter** [comment]
orakuda 1.2.0 still fails to compile.  It said `Error: Unbound module Spotlib.Spot.Unix.Command`.  spotlib must be >= 2.2.0

**Comment by camlspotter** [comment]
Troubles of checksums and Travis's network issue :-(

**Comment by camlspotter** [comment]
Finally!

**Comment by OCamlPro-Henry** [comment]
Thanks for taking the time for updating old packages !

Just a small question: you changed the required compiler version from 4.02.0 to 4.00.0, is that intentional ?

Still merging anyway.

**Pull request merged**
