### PR TITLE
Add new Coq version 8.16.0

### PR DESCRIPTION
**Pull request by palmskog**
New release of Coq.

cc: @MSoegtropIMC @ppedrot

### CODE REVIEW

**Comment by palmskog** [comment]
Looks like the only CI failure is a reverse dependency (`frama-c.24.0`). I don't think they are expected to work.

**Comment by MSoegtropIMC** [comment]
Coq is a depopt of frama-c. Can one put in version restrictions in depopts (anyway it would require a PR to the main opam repo, we don't want to wait for).

**Comment by MSoegtropIMC** [comment]
@palmskog : since I need coq and coqide in the Coq Platform patch repo: do you plan to change anything in the coqide opam file beyond the URL and SHA?

**Comment by palmskog** [comment]
@MSoegtropIMC the version of the coqide package I'll submit (after this PR is merged) only has URL and SHA changed from 8.16+rc1. But as we've seen before, an opam file may have to be substantially rewritten to pass CI.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
