### PR TITLE
Fix `with-test` filter on depends field

### PR DESCRIPTION
**Pull request by rjbou**
Correct filter is [`with-test`](https://opam.ocaml.org/doc/Manual.html#pkgvar-with-test), not `test`.

### CODE REVIEW

**Comment by rjbou** [comment]
removed `nocrypto.0.5.4-1` modification because at build opam tries to patch the unmodified opam file that is in the archive using the modified patch file . ping @pqwy

**Comment by rjbou** [comment]
ping @Drup for [`tree_layout` error](https://travis-ci.org/ocaml/opam-repository/jobs/436113027#L2607).

**Comment by Drup** [comment]
Strange. It should go away if you remove the line for `--enable-benchmark` or add a test dependency towards `benchmark`. I would tend to favor the first solution.

**Comment by Drup** [comment]
Ah, that means it should be `tyxml < 4.0` ! It seems test deps are bit undertested. :(

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
