### PR TITLE
ocaml-top: add upper constraint on ocp-index

### PR DESCRIPTION
**Pull request by AltGr**
as reported in https://github.com/OCamlPro/ocaml-top/issues/56

### CODE REVIEW

**Comment by AltGr** [comment]
Why wasn't this merged yet ? I just added an upper version bound to a dependency!

**Comment by AltGr** [comment]
Ok, no response, merging myself...

**Comment by samoht** [comment]
Because the CI was red? ocaml-top.1.1.1 seems pretty broken :-/

**Comment by AltGr** [comment]
Indeed :( — this PR goes in the way of less broken though...

**Pull request merged**
