### PR TITLE
Updated GSL and Lacaml

### PR DESCRIPTION
**Pull request by mmottl**

### CODE REVIEW

**Comment by avsm** [comment]
```
# /home/opam/.opam/4.03.0/build/gsl.1.19.2/_build/src/mlgsl_sf.c:484: undefined reference to `gsl_sf_legendre_array_n'
# /home/opam/.opam/4.03.0/build/gsl.1.19.2/_build/src/mlgsl_sf.c:487: undefined reference to `gsl_sf_legendre_array'
# src/libgsl_stubs.a(mlgsl_sf.o): In function `ml_gsl_sf_legendre_array_n':
# /home/opam/.opam/4.03.0/build/gsl.1.19.2/_build/src/mlgsl_sf.c:494: undefined reference to `gsl_sf_legendre_array_n'
# src/libgsl_stubs.a(mlgsl_sf.o): In function `ml_gsl_sf_legendre_array_index':
# /home/opam/.opam/4.03.0/build/gsl.1.19.2/_build/src/mlgsl_sf.c:495: undefined reference to `gsl_sf_legendre_array_index'
# collect2: error: ld returned 1 exit status
# File "caml_startup", line 1:
```

is this the version of the library in CI?

**Comment by mmottl** [comment]
It seems the GSL library is not recent enough on the CI platforms.  I'm not sure how to best deal with situations where third party libraries are out of date.  The required functions have been available in GSL for at least three years.  Would it be possible to upgrade GSL on the failing platforms?  If not, what would be the preferred way of dealing with third party library versions within the OPAM framework?

**Comment by avsm** [comment]
@mmottl it's a good question. With the Docker containers, we can control the distro pretty well, but we don't control our end users :-) A failure here will be what a user sees when they try to install on their chosen OS.  One way out is to have a more sophisticated depext system that can discriminate based on library versions, or a `conf-` package that outputs a better error message. This has yet to be designed and integrated into `opam-depext` though, and is a post-OPAM 2.0 problem.  Thoughts on it are welcome, however...

**Comment by mmottl** [comment]
@avsm That's certainly a tricky problem to solve, because system packages are not managed via OPAM.

Maybe something like this could work: `conf-` packages could map detected system features (library versions, etc.) to virtual OPAM packages, thus allowing constraint solving on installable OPAM packages.  Since system dependencies can change, e.g. old libraries getting removed, there would have to be an OPAM command to rescan `conf-` packages (individually or all) and to update, downgrade or remove OPAM packages as required.

Anyway, thanks for maintaining the CI infrastructure!

**Pull request merged**
