### PR TITLE
Add ppx_tools.5.2+4.08.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**
~Testing the revdeps for now~

This is the official release of ppx_tools.5.2 which adds support for OCaml 4.08

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
ppx_deriving.4.3 doesn't seem to be compatible with OCaml 4.08. cc @gasche I'll try to have a PR ready asap

**Comment by gasche** [comment]
@kit-ty-kate the ppx_deriving trunk works with 4.08, I can send a release opam-repo PR as soon as ppx_tools is merged.

(I understand the PR you mention would add an upper bound on current releases; that would be an excellent idea, and I can also do it if you prefer.)

**Comment by kit-ty-kate** [comment]
ping for maintainers whose latest versions are incompatible with OCaml >= 4.08
* @philipdexter for `aperf`
* @zoggy for `ocf`
* @yallop for `omonad`
* @darioteixeira for `pgocaml`
* @bobatkey for `ppx_monoid`
* @andrenth for `sequoia`

**Comment by yallop** [comment]
Thanks for the ping, @kit-ty-kate.  I've opened #14452 with a new 4.08.0-compatible release of `omonad`.

**Pull request merged**
