### PR TITLE
[new release] coq-serapi (8.10.0+0.7.0)

### PR DESCRIPTION
**Pull request by ejgallego**
Serialization library and protocol for machine interaction with the Coq proof assistant

- Project page: <a href="https://github.com/ejgallego/coq-serapi">https://github.com/ejgallego/coq-serapi</a>
- Documentation: <a href="https://ejgallego.github.io/coq-serapi/">https://ejgallego.github.io/coq-serapi/</a>

##### CHANGES:

* [general] (!) support Coq 8.10,
 * [serapi]  (!) `Goals` query return type has been modified due to
             upstream changes. (@ejgallego)
 * [serlib]  Complete (hopefully) serialization for ssreflect ASTs.
             (ejgallego/coq-serapi#73 @ejgallego)
 * [general] Drop support for OCaml < 4.07 (ejgallego/coq-serapi#140 @ejgallego)
 * [serlib ] JSON serialization for kernel and AST terms (@ejgallego)
 * [serapi ] Add `Complete` support (@ejgallego
             c.f. https://github.com/coq/coq/pull/8766)
 * [serlib ] Serlib is now built as a wrapped module (@ejgallego)
 * [serapi ] (!) Goals info has been extended to print name metadata if available,
             cc ejgallego/coq-serapi#151 (@ejgallego , suggested by @cpitclaudel)
 * [serlib ] JSON support for vernac_expr (@ejgallego)
 * [sertop ] (!) Do as Coq upstream and load Coq's stdlib with `-R` (closes ejgallego/coq-serapi#56)
 * [sertop ] Follow Coq upstream and unset `indices_matter` (closes ejgallego/coq-serapi#157,
             thanks to @palmskog for the report)
 * [serapi ] (!) Improve CoqExn answer to have pretty-printed message (improves ejgallego/coq-serapi#162,
             thanks to @cpitclaudel for the request)
 * [serlib ] (!) Fix capitalization conventions for a few types in `Names`
             (closes ejgallego/coq-serapi#167 thanks to @corwin-of-amber for the report)
 * [serapi ] (!) Add bullet suggest information to goal query (@corwin-of-amber)
 * [sertop ] Add `--no_prelude` option (closes ejgallego/coq-serapi#176, @ejgallego, request of @darbyhaller)
 * [serlib ] (!) Add index to `MBId` serialization (fixes ejgallego/coq-serapi#150, @ejgallego)
 * [serapi ] (!) Add `sid` parameter to `Print` (helps ejgallego/coq-serapi#150, @ejgallego, reported by @cpitclaudel)
 * [sertop ] Add `sertok` program for batch serialization of tokens and their source locations (@palmskog)
 * [serapi ] (!) Add string-formatted messages to `CoqExn` and `Message`
             (@ejgallego closes ejgallego/coq-serapi#184 , closes ejgallego/coq-serapi#162)

### CODE REVIEW

**Comment by ejgallego** [comment]
Ouch, it seems that the line:
```
  "coq"                 { !pinned & >= "8.10.0" & < "8.11" }
```
doesn't work; I have been using it in SerAPI's CI tho without a problem, as to signal to ignore the coq dependency whenever Coq has been pinned.

I wonder what's the right idiom to do that [before I start spamming the CI]

**Comment by ejgallego** [comment]
OSX failure seems spurious.

**Comment by kit-ty-kate** [comment]
All good. Thanks!

**Comment by ejgallego** [comment]
Thanks again!

**Pull request merged**
