### PR TITLE
added virtual package for ocamlbrowser

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I'm not too sure about having a virtual package like this. At least the versioning seems a bit off as it feels like it's a normal version number but it can pull any versions of labltk

**Comment by UnixJunkie** [comment]
Well, it is a virtual package for the moment.
I guess that if people want a special version of labltk, they know how to do this.

**Comment by garrigue** [comment]
This should not be a virtual package, rather labltk should be split two packages, since ocamlbrowser shouldn't depend on the labltk version, and labltk shouldn't depend on the OCaml version. If anybody is interested to help, tell me.

**Comment by kit-ty-kate** [comment]
I agree with @garrigue. Closing

**Pull request closed without merging**
