### PR TITLE
added version constraints for old camlimages opam files

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
Ok, I have to use `conflicts`.  Salvaging old opam files are always painful.

**Comment by camlspotter** [comment]
All the failures are due to ocaml version constraints...  Are they ok ?

**Comment by hannesm** [comment]
@camlspotter I looked into travis CI built - and the 4.06 build errors when compiling camlimages.4.1.2 with:
```
# File "mstring.ml", line 154, characters 13-17:
# Error: This expression has type bytes but an expression was expected of type
#          string
```

I suspect 4.1.2 needs an available of `ocaml-version < "4.06.0"`.

**Comment by hannesm** [comment]
thanks!

**Pull request merged**
