### PR TITLE
[new release] biniou (1.2.2)

### PR DESCRIPTION
**Pull request by tmattio**
Binary data format designed for speed, safety, ease of use and backward compatibility as protocols evolve

- Project page: <a href="https://github.com/mjambon/biniou">https://github.com/mjambon/biniou</a>
- Documentation: <a href="https://mjambon.github.io/biniou/">https://mjambon.github.io/biniou/</a>

##### CHANGES:

- 5.0 compatibilty. Depend on camlp-streams explicitly (mjambon/biniou#31)

### CODE REVIEW

**Comment by tmattio** [comment]
cc @rgrinberg

**Comment by kit-ty-kate** [comment]
- `merlin` is using `(implicit_transitive_deps false)` and thus failing to pick up the right `Stream` module.. cc @trefis @voodoos 
- in `coq-serapi`: There is an incompatibility between `Stream.t` from `camlp-streams` coming from `binou` and `Stdlib.Stream.t` required by `Pcoq.Parsable.make`. `coq` master replaces it with yet another different type in https://github.com/coq/coq/pull/15867 which will continue to cause issues. cc @ejgallego

**Comment by ejgallego** [comment]
Hi Kate, how come Stdlib.Stream.t and camlp-stremas Stream.t are not the same type? That will cause issues in every project actually?

Coq's master forked Stream.t but it is under Gramlib.Stream.t so it should be ok I think, but none of that code is in opal yet so I'll continue discussion in Coq's PR

**Comment by kit-ty-kate** [comment]
> I am not sure about what we should do concerning the breakage of the current version of Merlin due to this new version of `biniou`. Should we add a upper-bound on biniou's version ?

yes, I’m doing it right now.

**Comment by Leonidas-from-XIV** [comment]
I'm confused why camlp-streams chose to go this way. Wouldn't it make sense that in the case of older OCaml versions the package would pass through the `Stream` module (in the case of OCaml 4.14 dropping the deprecation warnings)? Thus packages can use it as drop-in implementation of `Stream` for both OCaml 4 and 5? Somewhat similar to how the `seq` package adds `Seq` for _older_ versions of OCaml and is a no-op on newer versions?

This also solves the issue of "accidental poisoning" via transitive dependencies as in the Merlin case since it doesn't matter as the types are identical in cases where the compiler comes with streams.

I'm probably missing something, so I'd appreciate being enlightened:-)

**Comment by ejgallego** [comment]
I share @Leonidas-from-XIV view, the current setup is otherwise very brittle not even CI can catch problems, as these depend on build ordering. For example, on a machine with enough jobs, installing coq-serapi may trigger the build of camlp-streams before Coq, thus thinks would work.

**Comment by kit-ty-kate** [comment]
> I share @Leonidas-from-XIV view, the current setup is otherwise very brittle not even CI can catch problems, as these depend on build ordering. For example, on a machine with enough jobs, installing coq-serapi may trigger the build of camlp-streams before Coq, thus thinks would work.

`camlp-streams` is a normal findlib package, it does *not* install modules in `%{lib}%/ocaml/` so there is no issue with build ordering.

**Comment by Leonidas-from-XIV** [comment]
No, but on 4.14 (and older) it is possible to mix `Stream` from the compiler (by packages that predate the move out of the Stdlib, they get deprecation warnings but compile) with `Stream` from `camlp-streams` (like biniou in this case, but I also considered using `camlp-streams` in Yojson to be compatible across 4.x and 5.x) so programs might end up having two identical but incompatible `Stream.t` types?

**Comment by dra27** [comment]
#21656 releases camlp-streams 5.0.1. In OCaml terms, this should be a drop-in 5.x compatibility replacement for anything which uses `Stream.t` - for 4.08-4.14, the library re-exports `Stdlib.Stream`/`Stdlib.Genlex` as `Stream`/`Genlex` (with strengthened types), so the mixing of camlp-streams and non-camlp-streams libraries is transparent. For 4.07 and earlier it is definitely a drop-in replacement, as it's an empty library.

The only "gotcha" is the limitations of `implicit_transitive_deps false` in Dune, but this is more down to the usability of `implicit_transitive_deps` than a problem with the library approach. The 4.14 version of camlp-streams _has_ to shadow  `Stdlib.Stream` and `Stdlib.Genlex` in order to suppress the deprecation warnings.

**Comment by Leonidas-from-XIV** [comment]
Thanks @dra27, this looks excellent! I appreciate how the older version of camlp-streams is restricted to OCaml 5.0+ where it is still safe to use while resolving the problems for most packages on older versions :+1:

**Comment by kit-ty-kate** [comment]
Thanks, sorry for the delay

**Pull request merged**
