### PR TITLE
Record the absolute path of llvm-config when found in PATH

### PR DESCRIPTION
**Pull request by jberdine**
When conf-llvm finds the llvm-config executable in PATH, currently the config var only records the basename of the executable. If the PATH later changes, dependent packages can fail to build, or be built with the wrong `llvm-config`. This patch adds the absolute path the the found llvm-config executable to the config var to avoid this instability.

Cc: @kit-ty-kate

### CODE REVIEW

**Comment by jberdine** [comment]
Thanks for the update @kit-ty-kate! This LGTM, though I haven't tested the old versions.

**Comment by jberdine** [comment]
@mseri if you wanted to test to see if this resolves the failure you observed, it would be very helpful.

**Comment by avsm** [comment]
@jberdine might you have a view on how to progress this?  The opam-repo maintainers are all a bit overloaded with PRs at the moment...

**Comment by jberdine** [comment]
In the projects I am involved in that use llvm, a vendored version of conf-llvm using this change is used with no trouble. As far as I understand, @mseri saw some issues with just the first commit [ea11b7e](https://github.com/ocaml/opam-repository/commit/ea11b7e1b58486355749c42586533ea694d99df6) of this PR after it was force-pushed, but I am unaware of any issue with the PR including both commits.

For how to proceed, I would merge unless someone volunteers more testing.

**Comment by mseri** [comment]
Shouldn’t the quotes be removed from all the configuree.sh files? I would imagine the same failure may happen with the others on certain systems (cannot check the logs anynlonger unfortunately)

**Comment by jberdine** [comment]
Oh yes, you are right. I forgot that I only removed them in the latest version to get feedback from @kit-ty-kate as I was changing her code. This makes me realize that a few versions have been released in the meantime that also need updating.

**Comment by shonfeder** [comment]
Hello! I hope this isn't an unwelcome ping, but I wonder if we can either mover this PR forward or close it. WDYT?

**Comment by mseri** [comment]
I’d be fine for merging it if it is fixed and the new patches are moved to the opam-source-archive in agreement with the new policy

**Comment by shonfeder** [comment]
I am going to close this issue, provisionally. Given the accrued merge conflicts, and the fact that it has been stalled for 2 years, it seems pretty clear no one has the motivation or bandwidth to land this as is.

If I am in error, please re-open, open will an alternative fix, or open an issue to track the unmet need here.

Thanks!

**Pull request closed without merging**
