### PR TITLE
Install sdl2.ba.

### PR DESCRIPTION
**Pull request by smimram**
This adds support for the `sdl2.ba` module.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @fccm

**Comment by mseri** [comment]
Even if accepted, I'd suggest to release into a separate version: `ocamlsdl2.0.03-1`

**Comment by kit-ty-kate** [comment]
Agreed

**Comment by fccm** [comment]
To compile with BAs isn't it different with different OCaml versions?
In this case is it possible to patch the Makefile based on different OCaml versions?

**Comment by kit-ty-kate** [comment]
Closing this for lack of response. Please reopen a PR when ready. Thanks!

**Pull request closed without merging**
