### PR TITLE
jbuilder: -p requires >= 1.0+beta7

### PR DESCRIPTION
**Pull request by emillon**
The -p option was only added in 1.0+beta7, so this adjusts the constraints of all the packages that use it.

### CODE REVIEW

**Comment by dra27** [comment]
These days, opam-repo-ci should survive being asked to do more revdeps 💪

**Comment by emillon** [comment]
All right, let's see how this goes!

**Comment by emillon** [comment]
Some context on this PR: I've started fixing #15943 in #21381 and saw some failures on the lower bounds runs, so here's a fix. There are probably more related ones so that depends how deep we want to fix jbuilder packages but these two ones seem important to fix.

**Comment by mseri** [comment]
Thanks, looks fine. Fixing all the lower bounds is out of scope for this PR

**Pull request merged**
