### PR TITLE
Remove Ocaml 4.08 upper version constraint

### PR DESCRIPTION
**Pull request by rossberg**

### CODE REVIEW

**Comment by avsm** [comment]
It fails to build on higher versions though:

```
#=== ERROR while compiling wasm.1.0 ===========================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://github.com/WebAssembly/spec/archive/v1.0.zip)
# path                 ~/.opam/4.10/.opam-switch/build/wasm.1.0
# command              /usr/bin/make -C interpreter opt unopt
# exit-code            2
# env-file             ~/.opam/log/wasm-23-835ba5.env
# output-file          ~/.opam/log/wasm-23-835ba5.out
### output ###
# make: Entering directory '/home/opam/.opam/4.10/.opam-switch/build/wasm.1.0/interpreter'
# echo >_tags "true: bin_annot"
# echo >>_tags "<{util,syntax,binary,text,valid,runtime,exec,script,host,main}/*.cmx>: for-pack(Wasm)"
# ocamlbuild -cflags '-w +a-4-27-42-44-45 -warn-error +a' -I util -I syntax -I binary -I text -I valid -I runtime -I exec -I script -I host -I main -libs bigarray -quiet main.native
# + /home/opam/.opam/4.10/bin/ocamlc.opt -c -w +a-4-27-42-44-45 -warn-error +a -bin-annot -I exec -I syntax -I runtime -I text -I binary -I host -I main -I util -I script -I valid -o exec/float.cmo exec/float.ml
# File "exec/float.ml", line 134, characters 22-37:
# 134 |   let sqrt  x = unary Pervasives.sqrt x
#                             ^^^^^^^^^^^^^^^
# Error (alert deprecated): module Stdlib.Pervasives
# Use Stdlib instead.
# 
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
# File "exec/float.ml", line 136, characters 22-37:
# 136 |   let ceil  x = unary Pervasives.ceil x
#                             ^^^^^^^^^^^^^^^
# Error (alert deprecated): module Stdlib.Pervasives
# Use Stdlib instead.
# 
```

The issue is that you have `-warn-error` in your released build rules. Highly recommend turning that off...

**Comment by rossberg** [comment]
Thanks @avsm, I created a new tag to point to, seems to work now.

**Comment by avsm** [comment]
Thanks; rather than deleting the wasm.1.0, I moved your patch over to a new wasm.1.0.1 package (since the source code has changed -- opam releases are immutable aside from the metadata).  Does this diff look ok to you?

**Comment by rossberg** [comment]
@avsm, sounds good, thanks!

**Comment by kit-ty-kate** [comment]
I could've retriggered travis manually, or just ignore it for the record. Thanks!

**Pull request merged**
