### PR TITLE
Try making a conf-oniguruma package

### PR DESCRIPTION
**Pull request by alan-j-hu**
I am writing bindings for the oniguruma library, so I need a conf-oniguruma package. However, I am not sure if I am making it properly, so I want to test the CI and see what happens.

I searched up the Oniguruma development packages on https://pkgs.org. I do not actually run all of these operating systems. So, I might have made a mistake.

### CODE REVIEW

**Comment by alan-j-hu** [comment]
Looks like the FreeBSD build failed, since I didn't specify a system package for FreeBSD.

I searched up a FreeBSD package on https://pkgs.org/search/?q=oniguruma.h&on=provides, but there were no results.

**Comment by alan-j-hu** [comment]
Looks like the MacOS Travis build failed because of some error generating the build script.

**Comment by alan-j-hu** [comment]
Looks like the CentOS build failed because oniguruma-devel is in the Powertools repository. This has happened for one other package, but the package was still allowed to be published: https://github.com/ocaml/opam-repository/pull/16401

I need to figure out what happened with OpenSUSE.

**Comment by alan-j-hu** [comment]
Okay, I did `os-distribution = opensuse`, but the CI's `os-distribution` reported `opensuse-leap`. I should have done `os-family = suse`.

**Comment by alan-j-hu** [comment]
The MacOS build failed again due to an error generating the build script.

**Comment by alan-j-hu** [comment]
This PR should be good to merge...

1. The only reason the Mac build failed in the most recent Travis CI was an error on Travis CI's part.
2. The reason why the CentOS build failed in the big CI is that the powertools repository is needed. There is prior precedent for accepting packages with external dependencies from the powertools repository (https://github.com/ocaml/opam-repository/pull/16401, https://github.com/ocaml/opam-repository/pull/17551).

**Comment by alan-j-hu** [comment]
Are the `oniguruma` packages for the BSDs correct? At least according to https://freebsd.pkgs.org/13/freebsd-aarch64/oniguruma-6.9.5.r1_1.txz.html, on `FreeBSD` the `oniguruma` package only installs the `.so` file, but the `.h` file is also needed for bindings to compile.

Maybe I will add a test `.c` file to compile to make sure that the necessary files are installed,

**Review by alan-j-hu — COMMENTED** [review]
Are the oniguruma packages for the BSDs correct? At least according to https://freebsd.pkgs.org/13/freebsd-aarch64/oniguruma-6.9.5.r1_1.txz.html, on FreeBSD the oniguruma package only installs the `.so` file, but the `.h` file is also needed for bindings to compile.

Maybe I will add a test `.c` file to compile to make sure that the necessary files are installed.

**Comment by kit-ty-kate** [comment]
Are you sure? The freshports page (https://www.freshports.org/devel/oniguruma/) is listing the `.h`, `.so` and `.pc`

**Comment by alan-j-hu** [comment]
I am not an expert on BSD, but according to my cursory research, a BSD "port" is how you build packages from source, and it's separate from the package manager.

https://www.freebsd.org/ports/

https://www.freebsd.org/doc/handbook/ports.html

**Comment by alan-j-hu** [comment]
Okay, so the development package should also install the `.pc` file. Since the build step uses `pkg-config`, if any of the packages listed in the opam file only installs the shared object file, the build should fail.

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by alan-j-hu** [comment]
(To clarify what I meant: By "development package," I meant the packages (usually named `libname-dev` or `libname-devel`) that install the `.h` and `.pc` files, among other files and which are distinct from `libname`. `libname` usually only installs the `.so` file. When I wrote the opam file, I checked to make sure I was specifying the development package. I suspect that the BSD packages you added will only install the `.so` file, which will lead to a build failure if a user tries to install the dependency with `opam depext`. The libraries you found that contained the header file were BSD "ports," which are a different concept from BSD packages installable with the package manager.)

**Comment by kit-ty-kate** [comment]
> The libraries you found that contained the header file were BSD "ports," which are a different concept from BSD packages installable with the package manager.

Mh, are you sure? I'm a FreeBSD user and I'm a bit confused here.

**Comment by alan-j-hu** [comment]
I don't use FreeBSD, so I will trust your knowledge.

**Pull request merged**
