### PR TITLE
[new release] atd (9 packages) (2.13.0)

### PR DESCRIPTION
**Pull request by mjambon**
Parser for the ATD data format description language

- Project page: <a href="https://github.com/ahrefs/atd">https://github.com/ahrefs/atd</a>

##### CHANGES:

* atdts: Stop compiler errors on generated typescript (ahrefs/atd#348)
* atdts: Don't fail on `wrap` constructs (ahrefs/atd#353)
* atdcat: New option `-remove-wraps` which pretty-prints the type
  definitions without `wrap` constructs (ahrefs/atd#353)
* atdd: Add `dlang` backend to generate D code from ATD definitions (ahrefs/atd#349)
* new tool: atddiff. Compares two versions of an ATD file and reports
  possible incompatibilities in the JSON data. Atddiff ships as part of the
  `atd` package together with `atdcat` (ahrefs/atd#352, ahrefs/atd#358)

### CODE REVIEW

**Comment by mjambon** [comment]
We _might_ have to bump the version constraint on the `atd` package for some of the other atd* packages. I'm not sure, though. I prefer to let CI run and enjoy my Sunday evening.

**Comment by mjambon** [comment]
`conf-atdpy` is [failing](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/663a38319cfed8360c32205690c457ea0a01c567/variant/freebsd,freebsd-ocaml-4.14-amd64,atdpy.2.13.0,tests).

Some context:
Atdpy's opam dependencies include
```
"conf-python-3" {with-test}
```
which isn't new. Python is needed for testing atdpy but not for building, installing or running the `atdpy` command. Users can normally figure out their Python install without opam.

**Comment by mseri** [comment]
This is a problem in conf-python and freebsd, no action is needed on your part

**Comment by mseri** [comment]
Thanka

**Pull request merged**
