### PR TITLE
gasoline v0.5.0

### PR DESCRIPTION
**Pull request by michipili**

### CODE REVIEW

**Comment by OCamlPro-Henry** [comment]
`bmake` is not available in Ubuntu precise, hence the CI failures for Linux.

Still, it fails to compile on macOS:
```
#=== ERROR while installing gasoline.0.5.0 ====================================#
# opam-version 1.2.2
# os           darwin
# command      /usr/local/bin/bmake -I/Users/travis/.opam/4.02.3/share/bsdowl all
# path         /Users/travis/.opam/4.02.3/build/gasoline.0.5.0
# compiler     4.02.3
# exit-code    1
# env-file     /Users/travis/.opam/4.02.3/build/gasoline.0.5.0/gasoline-14010-384e1f.env
# stdout-file  /Users/travis/.opam/4.02.3/build/gasoline.0.5.0/gasoline-14010-384e1f.out
# stderr-file  /Users/travis/.opam/4.02.3/build/gasoline.0.5.0/gasoline-14010-384e1f.err
### stdout ###
# [...]
# Stop.
# bmake[2]: stopped in /Users/travis/.opam/4.02.3/build/gasoline.0.5.0/application
# *** Error code 1
# 
# Stop.
# bmake[1]: stopped in /Users/travis/.opam/4.02.3/build/gasoline.0.5.0
# *** Error code 1
# 
# Stop.
# bmake: stopped in /Users/travis/.opam/4.02.3/build/gasoline.0.5.0
### stderr ###
# File "gasoline_Generic_Application.ml", line 71, characters 42-55:
# Error: Unbound value Success.error
```

If it is inteded, you should add the following line into the `opam` file.

```
available: [ os != "darwin" ]
```

**Comment by michipili** [comment]
Hi Henry, thank you for testing. The problem you encountered is caused by an obsolete version of **lemonade** which is incompatible with **gasoline**. I advertised this in the *opam* file. If you give it a try again, it should be fixed.

**Comment by OCamlPro-Henry** [comment]
It seems that there is now contradiction in the version contraints: 
```
Package is unavailable on this configuration, skipping:
The following dependencies couldn't be met:
  - gasoline -> getopts >= 0.3.2 -> lemonade < 0.4.0
  - gasoline -> lemonade >= 0.6.0
Your request can't be satisfied:
  - Conflicting version constraints for lemonade
```

@AltGr camelus should have caught that one ?

**Comment by OCamlPro-Henry** [comment]
You may have to release a new version of `getopts` that is compatible with `lemonade >= 0.6`

**Comment by michipili** [comment]
Thank you Grégoire for your patience! I have prepared a release of getopts, see #6910. On my development system I have

~~~ console
✗ opam list     
# Installed packages for system:
base-bigarray            base  Bigarray library distributed with the OCaml compi
base-threads             base  Threads library distributed with the OCaml compil
base-unix                base  Unix library distributed with the OCaml compiler
broken                  0.4.2  The Broken package is a simple testsuite framewor
bsdowl         3.0.0-20150830  This collection of BSD Make directives aims at pr
camomile                0.8.5  A comprehensive Unicode library
conf-bmake                1.0  Virtual package relying on a BSD Make compatible 
conf-m4                     1  Virtual package relying on m4
configuration           0.4.1  Analyse configuration files
gasoline                0.5.0  Unix-ish application development framework
getopts                 0.4.0  Analyse command line arguments
lemonade                0.6.0  A monad library with bubbles
mixture                 1.0.0  The Mixture package is a mixin library for the mo
ocamlfind               1.6.2  A library manager for OCaml
~~~

**Comment by OCamlPro-Henry** [comment]
Buld succeed on OSX. Thanks for updating the PR.

**Comment by michipili** [comment]
Fantastic, thanks!

**Pull request merged**
