### PR TITLE
Added BLAS/LAPACK configuration packages

### PR DESCRIPTION
**Pull request by mmottl**
As requested by @dsheets.  I will make use of these packages in future LACAML releases.

### CODE REVIEW

**Comment by dsheets** [comment]
Thanks for doing this, @mmottl!

A few comments:

1. Could you please specify `GPL-2.0` or `GPL-3.0`? We're trying to use the spdx names but don't have linter support, yet, due to some obscure licenses in use.
2. `sh -c` invocations take a single argument which is the command string to interpret.
3. In some circumstances, shell invocations can fail but the shell can return successfully. Also, it helps future debugging to have the shell explain what it executed. For these reasons, please use `sh -exc` to execute your shell expression.

**Comment by dbuenzli** [comment]
> We're trying to use the spdx names but don't have linter support, yet, due to some obscure licenses in use.

Isn't the purpose of the linter to get away with this obscurity ?

**Comment by dsheets** [comment]
@dbuenzli, yes, and we should update either `opam lint` or `Camelus` to use SPDX where possible and otherwise settle on a convention for the unusual licenses. In particular, I believe there was some friction in the past regarding "LGPL2 with OCaml linking exception" as it was not well-defined and not an SPDX license.

**Comment by dbuenzli** [comment]
Note that they seem quite keen [on adding it](http://lists.linux-foundation.org/pipermail/spdx-legal/2016-January/001619.html). So I think we should proceed with the tooling with the expected outcomes.

**Comment by mmottl** [comment]
@dsheets Thanks for the hints, I have addressed all issues.  The license is now GPL-2.0, and the shell invocation starts with `sh -exc`.  I had to read the OPAM documentation in more detail to understand how rules are constructed.  Platform-dependent rules are now completely separate and guarded by a platform check.  This is a lot more readable, too.

**Comment by OCamlPro-Henry** [comment]
The CI failed for `blas-config` with the following error (despite `libblas-dev` being installed)

```
### stderr ###
# +cc -lblas test.c
# /tmp/ccPEZlkO.o: In function `main':
# test.c:(.text+0x5a): undefined reference to `dnrm2_'
# collect2: ld returned 1 exit status
```

**Comment by OCamlPro-Henry** [comment]
The package seems to work on a recent Debian. Unfortunatly, I am not able to access an UbuntuPrecise right now, in order to further investigate the CI error.

**Comment by mmottl** [comment]
@OCamlPro-Henry Please feel free to update the `blas/lapack-config` packages directly if you figure out what dependencies they need on the broken platform.

**Comment by OCamlPro-Henry** [comment]
@mmottl after a quick investigation, it seems than using `cc $CFLAGS test.c -lblas` instead of `cc -lblas $CFLAGS test.c` fixes the package on platform with older gcc.

I haven't the time the package now. Might do it later, if you don't find spare time either.

**Comment by mmottl** [comment]
@OCamlPro-Henry Thanks, makes sense.  I had forgotten that older GCCs were more picky about argument order.

**Comment by dsheets** [comment]
LGTM. Merging this for great justice. Thanks, everyone! @mmottl do you think it would be reasonable to convert lacaml's depexts for existing versions to use these depexts? I don't expect you to do it but it will probably be done eventually as maintainance on the repository and it would be nice to know if you foresee any issues.

**Comment by mmottl** [comment]
@dsheets I don't foresee any issues with such a conversion.  I assume you already have tools to easily convert/patch package specifications.  It would be quite difficult and time consuming to maintain such large repositories otherwise.

**Pull request merged**
