### PR TITLE
[new release] coin (v0.1.0)

### PR DESCRIPTION
**Pull request by dinosaure**
Coin

- Project page: <a href="https://github.com/dinosaure/coin">https://github.com/dinosaure/coin</a>
- Documentation: <a href="https://dinosaure.github.io/coin/">https://dinosaure.github.io/coin/</a>

##### CHANGES:

* First release

### CODE REVIEW

**Comment by pmetzger** [comment]
A side comment: the documentation page gives me a 404 error.

**Comment by dinosaure** [comment]
@pmetzger I'm not aware about GitHub stuff but on my side, I correctly push documentation on my `gh-pages` branch and the `index.html` should be available on https://dinosaure.github.io/coin/_html/index.html. If you have any idea about that, I will happy to fix it.

**Comment by kit-ty-kate** [comment]
Tests are failing
```
#=== ERROR while installing coin.0.1.0 ========================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder runtest -p coin -j 4
# path         /home/travis/.opam/system/build/coin.0.1.0
# compiler     system (4.07.0)
# exit-code    1
# env-file     /home/travis/.opam/system/build/coin.0.1.0/coin-21800-2913ab.env
# stdout-file  /home/travis/.opam/system/build/coin.0.1.0/coin-21800-2913ab.out
# stderr-file  /home/travis/.opam/system/build/coin.0.1.0/coin-21800-2913ab.err
### stderr ###
# [...]
# -       (action (run ${exe:../gen/generate.exe} maps/KOI8-U.TXT KOI8_U.ml))))
# -
#  (rule ((targets (KOI8_R.ml))
#         (deps (maps/KOI8-R.TXT))
#         (action (run ${exe:../gen/generate.exe} maps/KOI8-R.TXT KOI8_R.ml))))
#  
# +(rule ((targets (KOI8_U.ml))
# +       (deps (maps/KOI8-U.TXT))
# +       (action (run ${exe:../gen/generate.exe} maps/KOI8-U.TXT KOI8_U.ml))))
# +
```

**Comment by anuragsoni** [comment]
@dinosaure Github-pages uses jekyll to build the website. By default any folder/file starting with an underscore is ignored by jekyll.

https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

**Comment by dinosaure** [comment]
Fixed, thx @anuragsoni

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
