### PR TITLE
fix for unmagic.1.0.4

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Something seems to have changed between the two archives:
```
Only in camlspotter-unmagic-c29f85013830: .hg_archival.txt
diff -ru camlspotter-unmagic-c29f85013830/.hgtags unmagic-1.0.4/.hgtags
--- camlspotter-unmagic-c29f85013830/.hgtags	2018-01-23 15:29:42.000000000 +0000
+++ unmagic-1.0.4/.hgtags	2018-01-24 00:40:31.000000000 +0000
@@ -15,5 +15,3 @@
 32234347c64434c9e12ea2315aa4ddbcda591b74 1.0.2
 874d28e0920c551332924d29d113d822320b16b9 1.0.3
 31bc6c43fb8e86e76cff6c73864d43ee8a6b0ec5 1.0.4
-31bc6c43fb8e86e76cff6c73864d43ee8a6b0ec5 1.0.4
-efa624b46d7dd9bf5eb370c5bfd29d902f088c18 1.0.4
diff -ru camlspotter-unmagic-c29f85013830/opam/opam unmagic-1.0.4/opam/opam
--- camlspotter-unmagic-c29f85013830/opam/opam	2018-01-23 15:29:42.000000000 +0000
+++ unmagic-1.0.4/opam/opam	2018-01-24 00:40:31.000000000 +0000
@@ -8,9 +8,10 @@
 dev-repo: "hg://https://bitbucket.org/camlspotter/unmagic"
 build: ["jbuilder" "build" "-p" name "-j" jobs]
 depends: [
-  "jbuilder"
+  "jbuilder" {build}
   "spotlib"
   "typerep" {>= "v0.10.0"}
   "ppx_typerep_conv" {build}
+  "ppx_deriving"
 ]
 available: [ocaml-version >= "4.06.0"]
diff -ru camlspotter-unmagic-c29f85013830/src/jbuild unmagic-1.0.4/src/jbuild
--- camlspotter-unmagic-c29f85013830/src/jbuild	2018-01-23 15:29:42.000000000 +0000
+++ unmagic-1.0.4/src/jbuild	2018-01-24 00:40:31.000000000 +0000
@@ -3,6 +3,5 @@
   (public_name unmagic)
   (wrapped false)
   (preprocess (pps (ppx_typerep_conv)))
-  (libraries ( spotlib typerep ))))
-
+  (libraries ( spotlib typerep ppx_deriving ))))
 
diff -ru camlspotter-unmagic-c29f85013830/unmagic.opam unmagic-1.0.4/unmagic.opam
--- camlspotter-unmagic-c29f85013830/unmagic.opam	2018-01-23 15:29:42.000000000 +0000
+++ unmagic-1.0.4/unmagic.opam	2018-01-24 00:40:31.000000000 +0000
@@ -8,9 +8,10 @@
 dev-repo: "hg://https://bitbucket.org/camlspotter/unmagic"
 build: ["jbuilder" "build" "-p" name "-j" jobs]
 depends: [
-  "jbuilder"
+  "jbuilder" {build}
   "spotlib"
   "typerep" {>= "v0.10.0"}
   "ppx_typerep_conv" {build}
+  "ppx_deriving"
 ]
 available: [ocaml-version >= "4.06.0"]
```

**Comment by camlspotter** [comment]
Somehow, I found the current version in the repo is not compilable.  The diff is minimum and not worth for providing a patch for this Mercurial to Git migration which has to change the hash anyway.

**Comment by mseri** [comment]
I am not sure I understand. @camlspotter does this mean that we should close this PR?

**Comment by camlspotter** [comment]
@mseri, oh sorry for my confusing comment.  Please proceed.  The code has some changes but I do not care.  I am forced to move my  repos from Mercurial to Git and it is very hard to keep the same source since hashes are not compatible.

**Comment by kit-ty-kate** [comment]
Ok fine then. Thanks!

**Pull request merged**
