### PR TITLE
[new release] biocaml (0.11.2)

### PR DESCRIPTION
**Pull request by pveber**
The OCaml Bioinformatics Library

- Project page: <a href="https://github.com/biocaml/biocaml/">https://github.com/biocaml/biocaml/</a>

##### CHANGES:

* fixed incompatibilities with version 4.13 of the compiler

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I just saw the failure on biocaml.0.11.1 today and was going to look into it.
Are you sure this is not a compiler bug? The fix seems suspicious

**Comment by kit-ty-kate** [comment]
It looks like this was fixed by https://github.com/ocaml/ocaml/pull/10529. Could you confirm?

**Comment by pveber** [comment]
Thanks a lot for looking into this @kit-ty-kate! I was too shy when I saw the compile error and thought this was the result of a recent change I had missed. Ok then, so I have to work on a new release for biocaml excluding the changes related to this. BTW I've recently started to use `dune-release` and sometimes it reopens a new PR when I force-push a new version of a release sometimes it doesn't. I couldn't find how to make sure I was using the same PR so sorry the same release jumps to another PR!

**Comment by pveber** [comment]
Actually, if this problem is fixed in the compiler, releasing now is a lot less useful. Let's save that for another time. Thanks again!

**Comment by kit-ty-kate** [comment]
No worries, i should've looked into it a month ago but i was busy with something else and didn't have the time

**Pull request closed without merging**
