### PR TITLE
h2 0.10.0 revdeps

### PR DESCRIPTION
**Pull request by anmonteiro**
Revdeps for h2 0.10.0. Found while validating https://github.com/ocaml/opam-repository/pull/23533

### CODE REVIEW

**Comment by mseri** [comment]
Failures:
```
#=== ERROR while compiling paf.0.4.0 ==========================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/paf.0.4.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p paf -j 127
# exit-code            1
# env-file             ~/.opam/log/paf-7-3dbdcb.env
# output-file          ~/.opam/log/paf-7-3dbdcb.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.paf.objs/byte -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/cstruct -I /home/opam/.opam/5.0/lib/faraday -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/ke -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/mimic -I /home/opam/.opam/5.0/lib/mirage-flow -intf-suffix .ml -no-alias-deps -o lib/.paf.objs/byte/paf.cmo -c -impl lib/paf.ml)
# File "lib/paf.ml", line 131, characters 10-22:
# 131 |           Cstruct.copy (Cstruct.of_bigarray buffer ~off ~len) 0 len)
#                 ^^^^^^^^^^^^
# Alert deprecated: Cstruct.copy
# this is just like [to_string] without defaults, were you looking for [sub_copy]?
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.alpn.objs/byte -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/cstruct -I /home/opam/.opam/5.0/lib/faraday -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/h2 -I /home/opam/.opam/5.0/lib/hpack -I /home/opam/.opam/5.0/lib/httpaf -I /home/opam/.opam/5.0/lib/ke -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/mimic -I /home/opam/.opam/5.0/lib/mirage-flow -I /home/opam/.opam/5.0/lib/psq -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/seq -I lib/.paf.objs/byte -intf-suffix .ml -no-alias-deps -o lib/.alpn.objs/byte/alpn.cmo -c -impl lib/alpn.ml)
# File "lib/alpn.ml", line 231, characters 37-41:
# 231 |         H2.Client_connection.request conn request ~error_handler
#                                            ^^^^
# Error: This expression has type unit -> H2.Client_connection.t
#        but an expression was expected of type H2.Client_connection.t
#        Hint: Did you forget to provide `()' as argument?
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I lib/.paf.objs/byte -I lib/.paf.objs/native -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/cstruct -I /home/opam/.opam/5.0/lib/faraday -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/ke -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/mimic -I /home/opam/.opam/5.0/lib/mirage-flow -intf-suffix .ml -no-alias-deps -o lib/.paf.objs/native/paf.cmx -c -impl lib/paf.ml)
# File "lib/paf.ml", line 131, characters 10-22:
# 131 |           Cstruct.copy (Cstruct.of_bigarray buffer ~off ~len) 0 len)
#                 ^^^^^^^^^^^^
# Alert deprecated: Cstruct.copy
# this is just like [to_string] without defaults, were you looking for [sub_copy]?
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I lib/.alpn.objs/byte -I lib/.alpn.objs/native -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/cstruct -I /home/opam/.opam/5.0/lib/faraday -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/h2 -I /home/opam/.opam/5.0/lib/hpack -I /home/opam/.opam/5.0/lib/httpaf -I /home/opam/.opam/5.0/lib/ke -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/mimic -I /home/opam/.opam/5.0/lib/mirage-flow -I /home/opam/.opam/5.0/lib/psq -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/seq -I lib/.paf.objs/byte -I lib/.paf.objs/native -intf-suffix .ml -no-alias-deps -o lib/.alpn.objs/native/alpn.cmx -c -impl lib/alpn.ml)
# File "lib/alpn.ml", line 231, characters 37-41:
# 231 |         H2.Client_connection.request conn request ~error_handler
#                                            ^^^^
# Error: This expression has type unit -> H2.Client_connection.t
#        but an expression was expected of type H2.Client_connection.t
#        Hint: Did you forget to provide `()' as argument?
```

```

#=== ERROR while compiling http-lwt-client.0.2.2 ==============================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/http-lwt-client.0.2.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p http-lwt-client -j 255
# exit-code            1
# env-file             ~/.opam/log/http-lwt-client-7-9968d7.env
# output-file          ~/.opam/log/http-lwt-client-7-9968d7.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.http_lwt_client.objs/byte -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/asn1-combinators -I /home/opam/.opam/5.0/lib/astring -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bos -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/ca-certs -I /home/opam/.opam/5.0/lib/cstruct -I /home/opam/.opam/5.0/lib/dns -I /home/opam/.opam/5.0/lib/dns-client -I /home/opam/.opam/5.0/lib/dns-client-lwt -I /home/opam/.opam/5.0/lib/dns-client/resolvconf -I /home/opam/.opam/5.0/lib/dns/cache -I /home/opam/.opam/5.0/lib/domain-name -I /home/opam/.opam/5.0/lib/duration -I /home/opam/.opam/5.0/lib/eqaf -I /home/opam/.opam/5.0/lib/eqaf/bigstring -I /home/opam/.opam/5.0/lib/eqaf/cstruct -I /home/opam/.opam/5.0/lib/faraday -I /home/opam/.opam/5.0/lib/faraday-lwt -I /home/opam/.opam/5.0/lib/faraday-lwt-unix -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/fpath -I /home/opam/.opam/5.0/lib/gmap -I /home/opam/.opam/5.0/lib/h2 -I /home/opam/.opam/5.0/lib/happy-eyeballs -I /home/opam/.opam/5.0/lib/happy-eyeballs-lwt -I /home/opam/.opam/5.0/lib/hkdf -I /home/opam/.opam/5.0/lib/hpack -I /home/opam/.opam/5.0/lib/httpaf -I /home/opam/.opam/5.0/lib/ipaddr -I /home/opam/.opam/5.0/lib/ipaddr/unix -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lru -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/lwt/unix -I /home/opam/.opam/5.0/lib/macaddr -I /home/opam/.opam/5.0/lib/metrics -I /home/opam/.opam/5.0/lib/mirage-crypto -I /home/opam/.opam/5.0/lib/mirage-crypto-ec -I /home/opam/.opam/5.0/lib/mirage-crypto-pk -I /home/opam/.opam/5.0/lib/mirage-crypto-rng -I /home/opam/.opam/5.0/lib/mirage-crypto-rng-lwt -I /home/opam/.opam/5.0/lib/mirage-crypto-rng/unix -I /home/opam/.opam/5.0/lib/mtime -I /home/opam/.opam/5.0/lib/mtime/clock/os -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocplib-endian -I /home/opam/.opam/5.0/lib/ocplib-endian/bigstring -I /home/opam/.opam/5.0/lib/pbkdf -I /home/opam/.opam/5.0/lib/psq -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/ptime/clock/os -I /home/opam/.opam/5.0/lib/randomconv -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/rresult -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/tls -I /home/opam/.opam/5.0/lib/tls-lwt -I /home/opam/.opam/5.0/lib/x509 -I /home/opam/.opam/5.0/lib/zarith -intf-suffix .ml -no-alias-deps -open Http_lwt_client__ -o src/.http_lwt_client.objs/byte/http_lwt_client.cmo -c -impl src/http_lwt_client.ml)
# File "src/http_lwt_client.ml", line 227, characters 33-43:
# 227 |     H2.Client_connection.request connection req ~error_handler ~response_handler
#                                        ^^^^^^^^^^
# Error: This expression has type unit -> H2.Client_connection.t
#        but an expression was expected of type H2.Client_connection.t
#        Hint: Did you forget to provide `()' as argument?
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I src/.http_lwt_client.objs/byte -I src/.http_lwt_client.objs/native -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/asn1-combinators -I /home/opam/.opam/5.0/lib/astring -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bos -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/ca-certs -I /home/opam/.opam/5.0/lib/cstruct -I /home/opam/.opam/5.0/lib/dns -I /home/opam/.opam/5.0/lib/dns-client -I /home/opam/.opam/5.0/lib/dns-client-lwt -I /home/opam/.opam/5.0/lib/dns-client/resolvconf -I /home/opam/.opam/5.0/lib/dns/cache -I /home/opam/.opam/5.0/lib/domain-name -I /home/opam/.opam/5.0/lib/duration -I /home/opam/.opam/5.0/lib/eqaf -I /home/opam/.opam/5.0/lib/eqaf/bigstring -I /home/opam/.opam/5.0/lib/eqaf/cstruct -I /home/opam/.opam/5.0/lib/faraday -I /home/opam/.opam/5.0/lib/faraday-lwt -I /home/opam/.opam/5.0/lib/faraday-lwt-unix -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/fpath -I /home/opam/.opam/5.0/lib/gmap -I /home/opam/.opam/5.0/lib/h2 -I /home/opam/.opam/5.0/lib/happy-eyeballs -I /home/opam/.opam/5.0/lib/happy-eyeballs-lwt -I /home/opam/.opam/5.0/lib/hkdf -I /home/opam/.opam/5.0/lib/hpack -I /home/opam/.opam/5.0/lib/httpaf -I /home/opam/.opam/5.0/lib/ipaddr -I /home/opam/.opam/5.0/lib/ipaddr/unix -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lru -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/lwt/unix -I /home/opam/.opam/5.0/lib/macaddr -I /home/opam/.opam/5.0/lib/metrics -I /home/opam/.opam/5.0/lib/mirage-crypto -I /home/opam/.opam/5.0/lib/mirage-crypto-ec -I /home/opam/.opam/5.0/lib/mirage-crypto-pk -I /home/opam/.opam/5.0/lib/mirage-crypto-rng -I /home/opam/.opam/5.0/lib/mirage-crypto-rng-lwt -I /home/opam/.opam/5.0/lib/mirage-crypto-rng/unix -I /home/opam/.opam/5.0/lib/mtime -I /home/opam/.opam/5.0/lib/mtime/clock/os -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocplib-endian -I /home/opam/.opam/5.0/lib/ocplib-endian/bigstring -I /home/opam/.opam/5.0/lib/pbkdf -I /home/opam/.opam/5.0/lib/psq -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/ptime/clock/os -I /home/opam/.opam/5.0/lib/randomconv -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/rresult -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/tls -I /home/opam/.opam/5.0/lib/tls-lwt -I /home/opam/.opam/5.0/lib/x509 -I /home/opam/.opam/5.0/lib/zarith -intf-suffix .ml -no-alias-deps -open Http_lwt_client__ -o src/.http_lwt_client.objs/native/http_lwt_client.cmx -c -impl src/http_lwt_client.ml)
# File "src/http_lwt_client.ml", line 227, characters 33-43:
# 227 |     H2.Client_connection.request connection req ~error_handler ~response_handler
#                                        ^^^^^^^^^^
# Error: This expression has type unit -> H2.Client_connection.t
#        but an expression was expected of type H2.Client_connection.t
#        Hint: Did you forget to provide `()' as argument?
```

```
#=== ERROR while compiling h2-lwt.0.9.0 =======================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/h2-lwt.0.9.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p h2-lwt -j 255
# exit-code            1
# env-file             ~/.opam/log/h2-lwt-7-3f087f.env
# output-file          ~/.opam/log/h2-lwt-7-3f087f.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lwt/.h2_lwt.objs/byte -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/faraday -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/gluten -I /home/opam/.opam/5.0/lib/gluten-lwt -I /home/opam/.opam/5.0/lib/h2 -I /home/opam/.opam/5.0/lib/hpack -I /home/opam/.opam/5.0/lib/httpaf -I /home/opam/.opam/5.0/lib/ke -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/psq -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/seq -intf-suffix .ml -no-alias-deps -open H2_lwt__ -o lwt/.h2_lwt.objs/byte/h2_lwt.cmo -c -impl lwt/h2_lwt.ml)
# File "lwt/h2_lwt.ml", line 83, characters 6-16:
# 83 |       connection
#            ^^^^^^^^^^
# Error: This expression has type unit -> H2.Client_connection.t
#        but an expression was expected of type H2.Client_connection.t
#        Hint: Did you forget to provide `()' as argument?
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I lwt/.h2_lwt.objs/byte -I lwt/.h2_lwt.objs/native -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/faraday -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/gluten -I /home/opam/.opam/5.0/lib/gluten-lwt -I /home/opam/.opam/5.0/lib/h2 -I /home/opam/.opam/5.0/lib/hpack -I /home/opam/.opam/5.0/lib/httpaf -I /home/opam/.opam/5.0/lib/ke -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/psq -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/seq -intf-suffix .ml -no-alias-deps -open H2_lwt__ -o lwt/.h2_lwt.objs/native/h2_lwt.cmx -c -impl lwt/h2_lwt.ml)
# File "lwt/h2_lwt.ml", line 83, characters 6-16:
# 83 |       connection
#            ^^^^^^^^^^
# Error: This expression has type unit -> H2.Client_connection.t
#        but an expression was expected of type H2.Client_connection.t
#        Hint: Did you forget to provide `()' as argument?
```

**Comment by mseri** [comment]
In the logs, it looks like `http-mirage-client` only fails due to `paf` failing. Do you have a specific failure for those packages?

**Comment by anmonteiro** [comment]
@mseri reverted that.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
