### PR TITLE
2 packages from LesBoloss-es/xoshiro at 0.1

### PR DESCRIPTION
**Pull request by Niols**
This pull-request concerns:
-`make-random.0.1`: Helper to build a module similar to Stdlib.Random
-`xoshiro.0.1`: Xoshiro PRNGs as drop-in replacements for Stdlib.Random

---
* Homepage: https://github.com/LesBoloss-es/xoshiro
* Source repo: git+https://github.com/LesBoloss-es/xoshiro.git
* Bug tracker: https://github.com/LesBoloss-es/xoshiro/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
`make-random`'s tests fail with:
```
+ /home/opam/.opam/opam-init/hooks/sandbox.sh "build" "dune" "build" "-p" "make-random" "-j" "47" "@install" "@runtest" (CWD=/home/opam/.opam/4.02/.opam-switch/build/make-random.0.1)
- File "splitmix64/test/crusher/dune", line 3, characters 20-43:
- 3 |  (libraries crusher xoshiro.splitmix64.pure))
-                         ^^^^^^^^^^^^^^^^^^^^^^^
- Error: Library "xoshiro.splitmix64.pure" not found.
- Hint: try:
-   dune external-lib-deps --missing -p make-random -j 47 @install @runtest
- File "xoshiro256plusplus/test/crusher/dune", line 3, characters 20-38:
- 3 |  (libraries crusher xoshiro.256++.pure))
-                         ^^^^^^^^^^^^^^^^^^
- Error: Library "xoshiro.256++.pure" not found.
- Hint: try:
-   dune external-lib-deps --missing -p make-random -j 47 @install @runtest
- File "xoshiro256plusplus/test/same-bits/dune", line 5, characters 21-43:
- 5 |   xoshiro.256++.pure xoshiro.256++.bindings))
-                          ^^^^^^^^^^^^^^^^^^^^^^
- Error: Library "xoshiro.256++.bindings" not found.
- Hint: try:
-   dune external-lib-deps --missing -p make-random -j 47 @install @runtest
-     sameBits alias make-random/test/same-bits/runtest
```
I believe a fix would be to replace the public names from xoshiro by its local name (from their `(name ...)`)

**Comment by Niols** [comment]
Hey @kit-ty-kate! Thank you very much for the help!

Thing is, these tests do not make sense for the package `make-random` and should only be run as part of the package `xoshiro`. I tried adding `(package xoshiro)` to them but Dune complains that "this field is useless without a (public_name ...) field." This is the first time I try to have several packages in the same repository and I am unsure how to explain that to Dune.

I guess your solution would work by running those tests nonetheless for the `make-random` package, right? I figure that would work just fine. Should I proceed with that?

**Comment by mseri** [comment]
Thanks

**Comment by Niols** [comment]
Thank you **very much** for your help!

**Pull request merged**
