### PR TITLE
Package mysql8.1.0

### PR DESCRIPTION
**Pull request by chrisnevers**
### `mysql8.1.0`
OCaml interface for mysql-connector-c

---
* Homepage: https://github.com/chrisnevers/mysql8
* Source repo: git://github.com/chrisnevers/mysql8.git
* Bug tracker: https://github.com/chrisnevers/mysql8/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
`ppx_inline_test` doesn't seem to be a test dependency:
```

#=== ERROR while compiling mysql8.1.0 =========================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://github.com/chrisnevers/mysql8/archive/0.11.tar.gz)
# path                 ~/.opam/4.10/.opam-switch/build/mysql8.1.0
# command              ~/.opam/4.10/bin/dune build -p mysql8 -j 72
# exit-code            1
# env-file             ~/.opam/log/mysql8-23-de7515.env
# output-file          ~/.opam/log/mysql8-23-de7515.out
### output ###
# File "lib/dune", line 9, characters 7-22:
# 9 |   (pps ppx_inline_test)))
#            ^^^^^^^^^^^^^^^
# Error: Library "ppx_inline_test" not found.
# Hint: try: dune external-lib-deps --missing -p mysql8 -j 72 @install
```
I removed it. If you would prefer to do things differently (I don't see many packages with it as test dependency though) please comment here, otherwise this PR should be good to go.

**Comment by chrisnevers** [comment]
Okay, its fine to remove. Thank you!

**Comment by chrisnevers** [comment]
Is there a specific C standard that the stubs need to compile to? 

Locally, I'm compiling the C fine with Dune v2.3.0. Could that be the issue if my `dune-project` specifies `1.11`?

**Comment by kit-ty-kate** [comment]
> Is there a specific C standard that the stubs need to compile to?
> 
> Locally, I'm compiling the C fine with Dune v2.3.0. Could that be the issue if my `dune-project` specifies `1.11`?

No there is no issue. Dune is generally well backward compatible in that regard.

Concerning the PR it seems that MySQL is either not available, obsolete or a compatibility package on most distributions and instead point to MariaDB. I'm trying to fix the Meta-package dealing with MySQL, let's see what the CI will say to that

**Comment by mseri** [comment]
It’s a pity that we cannot reallytest this. Can we merge it @kit-ty-kate ?

**Comment by mseri** [comment]
Let’s merge. If fixes are needed to the metadata for some reason, users will tell us

**Pull request merged**
