### PR TITLE
Remove all bindings to npm packages by Edgar.

### PR DESCRIPTION
**Pull request by fxfactorial**
I am removing js_of_ocaml bindings for: 

1. nodemailer
2. colors_js 
3. socket_io
4. reactjs
5. nodejs
6. express
7. xss_filters 
8. electron

### CODE REVIEW

**Comment by dsheets** [comment]
Why do you want to remove these packages?

**Comment by fxfactorial** [comment]
1. Because it is my desire
2. Because it is crap code
3. Because I do not want to support js_of_ocaml ecosystem anymore.

**Comment by avsm** [comment]
Sorry to see these packages go -- I'd been playing with the nodemailer package to send myself personal reminders from my email scripts :-)  Just need to double check that there are no dangling reverse dependencies before doing the removal and can merge these. You also have the option of removing your "maintainer" status in case someone else wants to step up and take over, as an alternative to removing a working package from the repository.

If you wish to resubmit them in the future, please feel free -- thanks for taking the trouble to package up this code in the first place!

**Comment by fxfactorial** [comment]
@avsm thanks. I don't there there are any reverse dependencies. 

I might redo the bindings, but using BuckleScript which I think uses `npm` and not `opam`, so you could find it there when I redo it. `nodemailer` was the easiest way for me to send an email in OCaml, still is I think.

**Comment by bobzhang** [comment]
Just to clarify a little bit, eventually Bucklescript wants to support opam too. currently opam directory layout does not fit well with common js module system, but we are also working on google module system, which is path independent. I think both opam and npm are great package managers and we want to support both in the future.

**Comment by fxfactorial** [comment]
For any opam maintainer, it has been five days since I opened up the PR at probably at least 10 PRs have been merged since that time. Is there a reason for a delay?

**Comment by dsheets** [comment]
It is disappointing to see working packages disappear over disagreements with upstream maintainers. Removing these packages will not only hurt the js_of_ocaml community (the intent) but also the OCaml/opam community.

I merge this with sadness.

**Comment by fxfactorial** [comment]
@dsheets

It is never my intent to hurt the greater OCaml community, and I don't think anyone could say I have ever had such a desire. I hosted OCaml office hours every week in San Francisco, provided endless amounts of help and direction. 

If anything this is an opportunity, especially relevant as we grow, that we need to be nice to people that give up so much of their time and efforts towards open source. Nastiness, belittlement often gets a pass in coding when the coder is talented and 'valuable' and unfortunately this community has a few people like that. To say i did this because of a disagreement is disingenuous at best.

**Comment by dsheets** [comment]
I'm not saying you have a desire to hurt the OCaml community but removing these packages does have that effect. They are useful for the OCaml web community. I'm well aware that you've done a lot to evangelize OCaml and I really appreciate it.

I'm sorry if you've been belittled or bullied. That kind of behavior is sadly too prevalent in most online communities, unfortunately. I think it needs to be recognized as toxic and discouraged whenever possible as it really has effects further ranging (e.g. this PR) than the action at the time which are often invisible (projects don't even get started or stop before their first release).

With that said, you made this PR of your own choice and I feel that it has hurt the community. I wish that that weren't the case but this entire episode has made me sad. Is it possible to let bygones be bygones?

**Comment by fxfactorial** [comment]
Of course, I don't hold any lasting ill feelings towards anyone, you're all my heroes! I'll try to redo these with bucklescript which is geared towards the web from the get go.

**Comment by michipili** [comment]
Edgar, I am sorry to read all this, especially you being belittled and bullied. 

> If anything this is an opportunity, especially relevant as we grow, that we need to be nice to people that give up so much of their time and efforts towards open source. Nastiness, belittlement often gets a pass in coding when the coder is talented and 'valuable' and unfortunately this community has a few people like that. To say i did this because of a disagreement is disingenuous at best.

You are definitely right about this. Did it happen on IRC or elsewhere? We, as a community, should voice up when something like this happens.

**Comment by fxfactorial** [comment]
@michipili I don't want to dredge up anything or call out names, the public logs on IRC are available. Like dsheets asked, let bygones be bygones, just let's all try harder next time.

**Comment by michipili** [comment]
@fxfactorial I hope you will find nicer people to interact with and a more welcoming environment. All the best!

**Pull request merged**
