### PR TITLE
Sawja release : ocaml 4.06 compatibility 

### PR DESCRIPTION
**Pull request by davidpichardie**

### CODE REVIEW

**Comment by davidpichardie** [comment]
I'm not sure to understand the compilation errors. Any help?

(regarding the dev-repo warning, Sawja should migrate to GitHub for the next major release)

**Comment by davidpichardie** [comment]
Maybe I could try to force the ocaml version to be {>= 4.06} in the opam file?

**Comment by jpdeplaix** [comment]
@jberdine This seems to be caused by the fact that the repository that is making the PR is not up-to-date. The ARM64 CI should have that right by merging our master and your branch but for some reason the github bridge is down again :( (related issue https://github.com/avsm/mirage-ci/pull/13)

Could you rebase your PR on top of ocaml/opam-repository#master please ?

**Comment by jpdeplaix** [comment]
Why did you close this PR ?

**Comment by davidpichardie** [comment]
I reset the whole thing: close my branch and started a new one.
The new PR is #11533

**Comment by jpdeplaix** [comment]
You didn't need to do that for a rebase but as you wish.

**Pull request closed without merging**
