### PR TITLE
Package pyml_bindgen.0.2.0

### PR DESCRIPTION
**Pull request by mooreryan**
### `pyml_bindgen.0.2.0`
Generate pyml bindings from OCaml value specifications

---
* Homepage: https://github.com/mooreryan/ocaml_python_bindgen
* Source repo: git+https://github.com/mooreryan/ocaml_python_bindgen.git
* Bug tracker: https://github.com/mooreryan/ocaml_python_bindgen/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mseri** [comment]
I believe the failures below have to do with a too-old python version on the three CI envs:
```
#=== ERROR while compiling pyml_bindgen.0.2.0 =================================#
# context              2.0.10 | linux/x86_64 | ocaml-base-compiler.4.13.1 | pinned(https://github.com/mooreryan/ocaml_python_bindgen/archive/0.2.0.tar.gz)
# path                 ~/.opam/4.13/.opam-switch/build/pyml_bindgen.0.2.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p pyml_bindgen -j 71 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/pyml_bindgen-10797-5f1023.env
# output-file          ~/.opam/log/pyml_bindgen-10797-5f1023.out
### output ###
# File "examples/embedding_python_source/test/run.t", line 1, characters 0-0:
#          git (internal) (exit 1)
# (cd _build/.sandbox/21db4fdf6544d8898adcd3870b5a31f4/default && /usr/bin/git --no-pager diff --no-index --color=always -u ../../../default/examples/embedding_python_source/test/run.t examples/embedding_python_source/test/run.t.corrected)
# diff --git a/../../../default/examples/embedding_python_source/test/run.t b/examples/embedding_python_source/test/run.t.corrected
# index 239735d..d2cc287 100644
# --- a/../../../default/examples/embedding_python_source/test/run.t
# +++ b/examples/embedding_python_source/test/run.t.corrected
# @@ -1,3 +1,5 @@
#  Run the executable.
#  
#    $ ../run.exe
# +  Fatal error: exception E (<type 'exceptions.TypeError'>, 'optimize' is an invalid keyword argument for this function)
# +  [2]
# File "examples/importing_modules/test/run.t", line 1, characters 0-0:
#          git (internal) (exit 1)
# (cd _build/.sandbox/9f5aaa9f1e8d1168d2da9a052051e46c/default && /usr/bin/git --no-pager diff --no-index --color=always -u ../../../default/examples/importing_modules/test/run.t examples/importing_modules/test/run.t.corrected)
# diff --git a/../../../default/examples/importing_modules/test/run.t b/examples/importing_modules/test/run.t.corrected
# index 89940b7..eb2fbf7 100644
# --- a/../../../default/examples/importing_modules/test/run.t
# +++ b/examples/importing_modules/test/run.t.corrected
# @@ -1,3 +1,5 @@
#  Run the executable.
#  
#    $ PYTHONPATH=$(pwd)/../py ../run.exe
# +  Fatal error: exception E (<type 'exceptions.ImportError'>, No module named silly_math.adder.add)
# +  [2]
# File "test/embed_source.t/run.t", line 1, characters 0-0:
#          git (internal) (exit 1)
# (cd _build/.sandbox/2ef5e88503d8a3b896fe8bdae0f1edf2/default && /usr/bin/git --no-pager diff --no-index --color=always -u ../../../default/test/embed_source.t/run.t test/embed_source.t/run.t.corrected)
# diff --git a/../../../default/test/embed_source.t/run.t b/test/embed_source.t/run.t.corrected
# index 310e098..d3bb4e4 100644
# --- a/../../../default/test/embed_source.t/run.t
# +++ b/test/embed_source.t/run.t.corrected
# @@ -2,7 +2,7 @@ Non-embedded works.
#  
#    $ pyml_bindgen person_specs.txt person Person -r no_check > person.ml
#    $ dune exec ./person_runner.exe 2> /dev/null
# -  Person -- name: Hagrid, age: 111
# +  [2]
#  
#  Embedded works.
#  
# @@ -69,7 +69,8 @@ Check the generated source.
#  And run it.
#  
#    $ dune exec ./person_runner.exe
# -  Person -- name: Hagrid, age: 111
# +  Fatal error: exception E (<type 'exceptions.TypeError'>, 'optimize' is an invalid keyword argument for this function)
# +  [2]
#  
#  Now try a module inside a package.
#  
# @@ -126,7 +127,8 @@ Now try a module inside a package.
#  Run it.
#  
#    $ dune exec ./person2_runner.exe
# -  Person -- name: Hagrid, age: 111
# +  Fatal error: exception E (<type 'exceptions.TypeError'>, 'optimize' is an invalid keyword argument for this function)
# +  [2]
#  
#  Finally, let's combine an embedded Python module with a non-embedded
#  one in the same OCaml module and see that it works.
# @@ -247,8 +249,8 @@ And run it.
#        @@ Py.Callable.to_function_with_keywords callable [||] kwargs
#    end
#    $ dune exec ./person_thing_runner.exe
# -  Person -- name: Hagrid, age: 111
# -  Thing -- color: orange
# +  Fatal error: exception E (<type 'exceptions.SyntaxError'>, invalid syntax (person.py, line 7))
# +  [2]
#  
#  Watch out...if your Python code uses the reserved string literal
#  syntax that pyml_bindgen uses, it will break.  However, we use
```

**Comment by mooreryan** [comment]
Thanks, I will be able to do some digging on this this weekend.

**Comment by mseri** [comment]
Ok, then I’ll wait for your answer before merging

**Comment by UnixJunkie** [comment]
Maybe adding a lower bound version constraint on pyml would do the trick?
The current version in opam is 20211015.

**Comment by mseri** [comment]
It's not a lower bound issue, the package is already built with the latest pyml in those systems, so I don't think that would make any difference.

The failure appears on the tests in centos7 and oraclelinux7, which is why I believe is due to ancient python (centos8 works fine) and that we could probably merge this:

- centos-7, pyml_bindgen.0.2.0, [tests (failed: Error: The compilation of pyml_bindgen.0.2.0 failed at "dune build -p pyml_bindgen -j 127 @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/dfe4e34a0eeddc5fb10cc51acd51ef16c80c92df/variant/opam-2.1,distributions,centos-7,pyml_bindgen.0.2.0,tests)
- oraclelinux-7, pyml_bindgen.0.2.0, [tests (failed: Error: The compilation of pyml_bindgen.0.2.0 failed at "dune build -p pyml_bindgen -j 71 @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/dfe4e34a0eeddc5fb10cc51acd51ef16c80c92df/variant/opam-2.1,distributions,oraclelinux-7,pyml_bindgen.0.2.0,tests)

**Comment by UnixJunkie** [comment]
Ok, those are just test errors, not build errors.

**Comment by mseri** [comment]
Yes, sorry, I was very vague in my original comment

**Comment by mooreryan** [comment]
If you (@mseri) think it's fine for merging as is, then the min python version issue could be taken care of in the next release.  (I can try to pinpoint the minimum Python version needed before merging if you would prefer that as well.)

**Pull request merged**
