### PR TITLE
[new release] Add CoqIDE 8.10.2

### PR DESCRIPTION
**Pull request by Blaisorblade**
Builds on #15416.
(This is only a draft waiting for test results and/or #15416 to be merged).

### CODE REVIEW

**Comment by Blaisorblade** [comment]
All current failures are spurious and run into `Error: System error: "No space left on device"`, at different places, so it seems a problem of the runners.
@kit-ty-kate do you happen to know who to ping?

**Comment by kit-ty-kate** [comment]
@Blaisorblade This should not happen anymore, I've delt with that and pressed the rebuild button

**Comment by Blaisorblade** [comment]
Regarding the Travis failure (https://travis-ci.org/ocaml/opam-repository/jobs/618632295) on Mac, that's a timeout but please hold the merge!

CoqIDE builds on my Mac, and works with lablgtk3.3.0.beta6 (which I used last time), but crashes with lablgtk3.3.0.beta7.

I guess I should blacklist the latest release and investigate? I'm asking on coq gitter.

**Comment by kit-ty-kate** [comment]
Looks good. Thanks!

**Pull request merged**
