### PR TITLE
added packages/conf-liblinear-tools/conf-liblinear-tools.1.0.0

### PR DESCRIPTION
**Pull request by UnixJunkie**
I could not find the related package on exotic Linux distros (arch and alpine, for example).

I will submit to the opam repository a software that relies on them very soon.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The version number is incorrect. I believe this should be `conf-liblinear-tools.1` (or 1.0.0 if you really prefer), the separation between version number and package name is done by the first dot encountered, not an hyphen.

**Comment by UnixJunkie** [comment]
Sorry, my mistake, renamed.

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by kit-ty-kate** [comment]
arf, I noticed you removed my commit: https://github.com/ocaml/opam-repository/pull/14976/commits/7f3702f2620cfcfdd4f4662db3f4763786431e6c I'll fix that.

**Comment by kit-ty-kate** [comment]
Fixed in 87764496c9

**Comment by UnixJunkie** [comment]
My opam (2.0.1) lint told me the conf flag is an error, sorry.

**Pull request merged**
