### PR TITLE
Update package overview of camlp5 to move from GForge to GitHub

### PR DESCRIPTION
**Pull request by smorimoto**
Some versions are not yet available on GitHub, so this PR is still WIP.

Related issue: #19757

### CODE REVIEW

**Comment by mseri** [comment]
Any update on this?

**Comment by chetmurthy** [comment]
what update?  Last I looked at this, it appears that this is for very, very old versions of camlp5.  is there a reason these should be supported?  Are there users who still rely on these versions ?

**Comment by chetmurthy** [comment]
Ah, ok, maybe the thing that needs to be done, is to remove the 6.xx versions of camlp5 from opam-repository?  If so, I can do that.

**Comment by mseri** [comment]
We should not remove them. If there is no way to obtain the tarball, we should mark them as unavailable imo
Ping @smorimoto who opened the PR, can you check/ask if the tarball is in the opam cache backup?

**Comment by chetmurthy** [comment]
OK, looking deeper into this issue, I see that release 614 has a tag ("rel614") but the other releases don't even have tags in github.  I don't know what happened to them: this was all 8 years ago, long before I took over maintenance.  Given how old these releases are, I don't understand the utility of keeping them around.  There are no log-comments for releases earlier than 6.12, but there are these:

6.12: bd79ec5b5b47c4f118ed020d341ea1152574a511
6.13: c2fa935b7dcfb164c8b87e5c4d4954720695aa16
6.15: 524b6b93e829cf91b378d53c6178c4c7ca4ee07b
6.16: 059c6046d717de2e88249995d44ce2f9e6632167

It isn't even clear that these commits correspond to the named releases.

So I'm not sure what to do here.  If you can explain to me how to mark them as unavailable, I'm happy to do so and submit a PR.  Honestly, why anybody would use any camlp5 prior to the 7.xx series is ..... a mystery to me.

**Comment by Kakadu** [comment]
> So I'm not sure what to do here. If you can explain to me how to mark them as unavailable,

You could try to add `available: false` to the recipe

**Comment by mseri** [comment]
Sorry update ping was meant to @smorimoto. In any case, I am checking if there is a cache backup with the missing tarballs, otherwise I will mark them as unavailable and merge

**Comment by mseri** [comment]
They are all there now

**Pull request merged**
