### PR TITLE
jsoo3

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
@avsm, I've done a proper release and added checksums. I consider this PR ready to be merged, just waiting for CI.

**Comment by samoht** [comment]
The only revdeps issue is on `hardcaml-examples` which I am not sure have anything to do with that release but might be worth checking, /cc @andrewray 

```
# File "src/cordic.ml", line 1:
# Error: The implementation src/cordic.ml
#        does not match the interface src/cordic.cmi:
#        ...
#        At position module Design : sig module Make(B)(H)(T) : <here> end
#        Values do not match:
#          val tb : '_a Sim.cyclesim -> B.t ref I.t -> '_b -> unit
#        is not included in
#          val tb :
#            B.t HardCaml.Cyclesim.Api.cyclesim ->
#            B.t ref I.t -> B.t ref O.t -> unit
#        File "src/cordic.ml", line 488, characters 8-10: Actual declaration
```

Otherwise, looks good to merge to me.

**Comment by andrewray** [comment]
Do you have the hardcaml-examples version / ocaml version this happens on?  

It seems unlikely that it's anything to do with js_of_ocaml.

**Comment by samoht** [comment]
@andrewray: see for instance https://ci.ocaml.io/log/saved/docker-run-2192acb8ef87e878d8b4151a6f1d15ba/69bf79f8f8f805f5e8364475bcf75b29e76f067e

**Comment by samoht** [comment]
Actually, the logs show that the revdeps are not testing the right version of `js_of_ocaml` with `hardcaml-examples`, probably because of the constraints already put in place. I've reported that error on the CI tracker: https://github.com/avsm/mirage-ci/issues/3

So all seems good, I'll merge the PR pretty soon.

**Comment by andrewray** [comment]
It seems to be a constraint issue when using the new hardcaml packages against the previous version of hardcaml (1.1.1).

**Pull request merged**
