### PR TITLE
[new release] bytepdf (0.1)

### PR DESCRIPTION
**Pull request by Drup**
Tool to create PDFs that are also OCaml bytecodes

- Project page: <a href="https://github.com/Drup/bytepdf">https://github.com/Drup/bytepdf</a>

##### CHANGES:

Plop

### CODE REVIEW

**Comment by Drup** [comment]
Wait for https://github.com/ocaml/opam-repository/pull/12538

**Comment by pmetzger** [comment]
This is an essential tool for self-documenting code.

**Comment by mseri** [comment]
Interesting, now it is not building:

```
[bytepdf: dune build] Command started
+ dune "build" "-p" "bytepdf" "-j" "2" (CWD=/home/opam/.opam/4.05.0/build/bytepdf.0.1)
- File "dune", line 5, characters 31-39:
- Error: Library "cmdliner" not found.
- Hint: try: dune external-lib-deps --missing -p bytepdf @@default
[ERROR] The compilation of bytepdf failed at "dune build -p bytepdf -j 2".
```

**Comment by Drup** [comment]
All green now!

**Pull request merged**
