### PR TITLE
maybe better opam file

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks for that !!
I'm not totally sure it would work but what about adding `& os = "darwin"` to the post-message ?

**Comment by UnixJunkie** [comment]
I think I tried but it did not parse (I use opam-2.0).

**Comment by kit-ty-kate** [comment]
Let's try that. If it doesn't work I'll revert it.

**Comment by kit-ty-kate** [comment]
Looks like it's working. Are you ok with the new message ?

**Comment by UnixJunkie** [comment]
I updated the post-message, thanks.

**Comment by kit-ty-kate** [comment]
Oops, sorry. Thanks a lot !!

**Pull request merged**
