### PR TITLE
dolog {>= "4.0.0"} --> dolog {= "4.0.0"}

### PR DESCRIPTION
**Pull request by UnixJunkie**
because dolog 5.0.0 has a new API that is incompatible, in some use cases

### CODE REVIEW

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml/opam-repository/pull/17846

**Comment by kit-ty-kate** [comment]
equality should be avoided here in case a patch release is made. Could you add `& < "5.0.0"` instead?

**Comment by UnixJunkie** [comment]
ok, I'll do that.

**Comment by UnixJunkie** [comment]
superseded by https://github.com/ocaml/opam-repository/pull/17870

**Pull request closed without merging**
