### PR TITLE
bibtex2html 1.99: do not compile doc

### PR DESCRIPTION
**Pull request by backtracking**

### CODE REVIEW

**Comment by mseri** [comment]
Please can you make this change in a new patch package `bibtex2html.1.99-1`: practically you would just need to copy the `opam` file to `packages/bibtex2html/bibtex2html.1.99-1/opam` and making the change there

**Comment by backtracking** [comment]
Sure, no problem. Do I need to include `files/` from `bitex2html-1.99` as well?

**Comment by mseri** [comment]
You can avoid doing that if you remove lines 20-23 in the file, that is you drop both `patches` and `remove`. 

This should be fine since with opam2 the `remove` section is in most cases redundant: the new opam tracks changes at install time and uses this information to know what to remove

**Comment by backtracking** [comment]
Thanks! Then I guess I should also remove lines 25--29 about extra files, right?

**Comment by mseri** [comment]
Yes, indeed!

**Comment by backtracking** [comment]
Thanks. Done.

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
