### PR TITLE
[new release] tar, tar-unix and tar-mirage (2.2.1)

### PR DESCRIPTION
**Pull request by hannesm**
Decode and encode tar format files in pure OCaml

- Project page: <a href="https://github.com/mirage/ocaml-tar">https://github.com/mirage/ocaml-tar</a>
- Documentation: <a href="https://mirage.github.io/ocaml-tar/">https://mirage.github.io/ocaml-tar/</a>

##### CHANGES:

- `tar-mirage`: fix writing of data, previously the end_of_archive was set 512 bytes short (mirage/ocaml-tar#99 @hannesm @reynir)

### CODE REVIEW

**Comment by hannesm** [comment]
CI errors are weird /cc @kit-ty-kate 
```
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
[ERROR] No solution for tar-mirage.2.2.1: The actions to process have cyclic dependencies:
          - install ocaml.4.14.0 -> install ocaml-config.2 -> install ocaml.4.14.0


Command failed: opam list --readonly --external '--resolve=tar-mirage.2.2.1' returned 20
"/bin/bash" "-c"
"opam depext tar-mirage.2.2.1 && opam reinstall tar-mirage.2.2.1;
        res=$?;
        test "$res" != 31 && exit "$res";
        export OPAMCLI=2.0;
        build_dir=$(opam var prefix)/.opam-switch/build;
        failed=$(ls "$build_dir");
        for pkg in $failed; do
          if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"debian-11\""; then
            echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field.";
          fi;
        done;
        exit 1" failed with exit status 20
2022-10-28 13:07.41: Job failed: Failed: Build failed
2022-10-28 13:07.41: Log analysis:
2022-10-28 13:07.41: >>> 
[ERROR] In the opam file for base.v0.15.1~5.0preview:
 (score = 20)
2022-10-28 13:07.41: >>> 
[ERROR] In the opam file for caravan.0.0.2:
 (score = 20)
```

**Comment by kit-ty-kate** [comment]
Your PR is removing the `repo` file for some reason:
```
/home/opam: (run (shell "opam repository set-url --strict default opam-repository/"))
[default] Initialised
[WARNING] The repository 'default' at file:///home/opam/opam-repository doesn't have a 'repo' file, and might not be compatible with this version of opam.
```

**Comment by hannesm** [comment]
thanks for investigating and sorry, force-pushed the last commit to not remove `repo`.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
