### PR TITLE
[new release] docteur (0.0.1)

### PR DESCRIPTION
**Pull request by dinosaure**
A simple read-only Key/Value from Git to MirageOS

- Project page: <a href="https://github.com/dinosaure/docteur">https://github.com/dinosaure/docteur</a>
- Documentation: <a href="https://dinosaure.github.io/docteur/">https://dinosaure.github.io/docteur/</a>

##### CHANGES:

- First release

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Could you have a look why it fails with opam 2.1?
```
#=== ERROR while compiling docteur.0.0.1 ======================================#
# context              2.1.0~beta4 | linux/arm64 | ocaml-base-compiler.4.12.0 | pinned(https://github.com/dinosaure/docteur/releases/download/v0.0.1/docteur-v0.0.1.tbz)
# path                 ~/.opam/4.12/.opam-switch/build/docteur.0.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p docteur -j 31
# exit-code            1
# env-file             ~/.opam/log/docteur-23-af4c20.env
# output-file          ~/.opam/log/docteur-23-af4c20.out
### output ###
# File "test/simple.t", line 1, characters 0-0:
# File "test/git-simple.t", line 1, characters 0-0:
#          git (internal) (exit 1)
# (cd _build/.sandbox/0454e4d18251e772bad1de771c27ca26/default && /usr/bin/git --no-pager diff --no-index --color=always -u ../../../default/test/git-simple.t test/git-simple.t.corrected)
# diff --git a/../../../default/test/git-simple.t b/test/git-simple.t.corrected
# index 180082e..0e14eba 100644
# --- a/../../../default/test/git-simple.t
# +++ b/test/git-simple.t.corrected
# @@ -14,6 +14,7 @@ Simple Git disk.img
#    $ cd ../unikernel/
#    $ mirage configure -t unix --disk disk.img
#    $ make depends > /dev/null 2> /dev/null
# +  [2]
#    $ mirage build > /dev/null 2> /dev/null
#    $ ./simple --filename /README.md > out.result
#    $ cd -
#          git (internal) (exit 1)
# (cd _build/.sandbox/1c7d04ae7a92957ba66f67a3df424a37/default && /usr/bin/git --no-pager diff --no-index --color=always -u ../../../default/test/simple.t test/simple.t.corrected)
# diff --git a/../../../default/test/simple.t b/test/simple.t.corrected
# index 2c9ec99..f6f0617 100644
# --- a/../../../default/test/simple.t
# +++ b/test/simple.t.corrected
# @@ -10,6 +10,7 @@ Simple disk.img
#    $ cd ../unikernel/
#    $ mirage configure -t unix --disk disk.img
#    $ make depends > /dev/null 2> /dev/null
# +  [2]
#    $ mirage build > /dev/null 2> /dev/null
#    $ ./simple --filename /README.md > out.result
#    $ cd -
```

**Comment by dinosaure** [comment]
May be related to #18580 but I'm not sure. `make depends` (which runs an `opam pin`) should be fine and I can not reproduce it with `opam.2.1.0~beta4` 😕 .

**Comment by dinosaure** [comment]
Ok this time, it should work :+1:.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
