### PR TITLE
Package comby.1.2.1

### PR DESCRIPTION
**Pull request by rvantonder**
### `comby.1.2.1`
A tool for structural code search and replace that supports ~every language
Comby is a tool designed to make it easy to match change syntax for basically
every language. You can think of it like grep/sed, but with added ability to
recognize code blocks, expressions, and strings delimited by parentheses,
braces, quotes, and so on.

---
* Homepage: https://github.com/comby-tools/comby
* Source repo: git+https://github.com/comby-tools/comby.git
* Bug tracker: https://github.com/comby-tools/comby/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by rvantonder** [comment]
Hey `opam` friends 👋 . I've done as much local testing against compiler versions as I could for this initial packaging. Let's see how things go from here :-)

**Comment by rvantonder** [comment]
Two failures for distributions:

1. `oraclelinux-8`:
```
comby.1.2.1 (failed: The compilation of conf-libev failed at "/usr/bin/sh ./build.sh".)
#       The following recquired C libraries are missing: libev.
# Please install them and retry. If they are installed in a non-standard location, set the environment variables C_INCLUDE_PATH and LIBRARY_PATH accordingly and retry.
```

Not sure how to solve this one--looks like `libev` didn't install on `oraclelinux-8` but succeeded on `oraclelinux-7`. Any idea?

2.  `extras,x86_32`:

Failing tests, seeing

> Error initializing: Operation not permitted

coming from somewhere, still debugging.

**Comment by rvantonder** [comment]
Alright, for `extras,x86_32`, the error is coming from a `mmap` operation being attempted and failing. This test/command shouldn't need to reach the code doing an `mmap` so I'm thinking I can update and bump the patch version, let me know if this is the right move :-)

**Comment by kit-ty-kate** [comment]
> Let me know if the right move is to bump a patch version.

this shouldn't be necessary. As long as you haven't released the package somewhere already (be it opam or something else), overwriting the tag and calling opam publish again should be enough.

**Comment by rvantonder** [comment]
Ah, so there's already a PR open on `brew` for this version (calling out to the GH release zip) and it's going to be icky to update that. So if I did already release this package, I'm thinking I can (a) close this PR (b) bump the patch version (c) tag and run `opam publish`? 

(this time, I won't create a release on GH for homebrew until it works on opam)

**Comment by kit-ty-kate** [comment]
> Ah, so there's already a PR open on `brew` for this version (calling out to the GH release zip) and it's going to be icky to update that. So if I did already release this package, I'm thinking I can (a) close this PR (b) bump the patch version (c) tag and run `opam publish`?
> 
> (this time, I won't create a release on GH for homebrew until it works on opam)

Sounds good ^_^ Thanks!

**Comment by rvantonder** [comment]
Thanks @kit-ty-kate. Closed in favor of #18264

**Pull request closed without merging**
