### PR TITLE
Add Z3 4.13.3

### PR DESCRIPTION
**Pull request by wintersteiger**

### CODE REVIEW

**Comment by mseri** [comment]
Merged in opam-source-archives

**Comment by mseri** [comment]
You need to add [this](https://github.com/ocaml/opam-source-archives/pull/33/files) as extra patch right?

**Comment by wintersteiger** [comment]
Yes, but only on ubuntu-20 and opensuse and I haven't figured out how to encode that in the opam file.

**Comment by wintersteiger** [comment]
All done, I think this one's ready too.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
