### PR TITLE
Install coq with camlp4 only if camlp5 is not installed

### PR DESCRIPTION
**Pull request by chambart**
related to issue https://github.com/ocaml/opam-repository/issues/3631

### CODE REVIEW

**Comment by chambart** [comment]
Hmm... It seems like opam 1.1.0 does not like this syntax.

**Comment by chambart** [comment]
To summarize the current situation with coq:
Coq can build with camlp4 or camlp5 but:
* camlp5 is not available on trunk
* coq built with camlp4 cannot be linked with why3 ( I do not know if it is a packaging problem or a why3 problem )
* And I don't know any syntax accepted in opam 1.1.0 to build with camlp4 only if camlp5 is not available. 

One solution would be to have 2 coq package, one for trunk using camlp4 and one for other versions using camlp5 (using the 'available' field). But this is kind of ugly an may have an heavy maintenance cost.
@samoht, @avsm do you see any other reasonable solution for this ?

**Comment by samoht** [comment]
@chambart can you rebase this to master?

**Comment by chambart** [comment]
I can but this won't solve the problem with opam 1.1.0

**Comment by chambart** [comment]
Also I wanted to add a constraint to why3 preventing installing it with coq without camlp5.
I tried adding a conflict:
```( "coq" & ( ! "camlp5" ) )```
but opam lint is complaining (about the `!`):
   ```error: File format error: at ~/OCamlPro/git/opam-repository/packages/why3/why3.0.85/opam:42:14, Expected a formula list of the form [ "item" {condition}... ]```
according to https://opam.ocaml.org/doc/manual/dev-manual.html#sec7 it should effectively not accept it, 
but it seems that it accepts a bit too much (it should fail at the first parenthesis). It would accept the syntax `( "coq" & "camlp5" )` that is not in the documented language.

And added as a dependency where the syntax should be accepted, it is still rejected:
```depends: [
  ! ( "coq" & ( ! "camlp5" ) )
]```
opam complains about the first `!`

**Comment by avsm** [comment]
Not sure how to test this one.  Do the `coq` maintainers who have contributed patches (@clarus @brabalan) have any thoughts?

**Comment by brabalan** [comment]
I'm not a coq maintainer … everything is working for me since #3662 was merged. Is this still needed?

**Comment by chambart** [comment]
This problem is not fixed. There is no version of camlp5 for ocaml 4.03.0

**Comment by samoht** [comment]
@chambart the patch doesn't apply anymore.

**Comment by chambart** [comment]
Since it seems that it is not possible to encode the correct set of constraints, I will propose a version with 2 packages.

**Comment by samoht** [comment]
That seems sensible.

**Comment by chambart** [comment]
That seems to work (the failed travis build is due to a timeout)

**Comment by chambart** [comment]
@samoht is there any objection against merging this pr ?

**Comment by samoht** [comment]
None :p Just check with upstream they are aware of the new package and they are fine with it.

**Comment by chambart** [comment]
@clarus Do you have any objection to this change ? (Notice that I put you as the maintainer of the camlp4 version of the package, do you mind ?)

**Comment by clarus** [comment]
No problem for being the maintainer of this package, but the problem is that this version will be considered as the latest and installed by default. Could we use instead `~camlp4`?

**Comment by chambart** [comment]
Effectively, I didn't consider that.

**Pull request merged**
