### PR TITLE
Caqti 0.11.0.

### PR DESCRIPTION
**Pull request by paurkedal**
## Change Log for 0.11.0

Added and improved:

- Compliance with Lwt 4.0 contributed by Brendan Long.
- Switched to the logs library for logging.
- Strengthen detection of concurrent use of connection.
- Support microsecond precision for timestamps for PostgreSQL and
  millisecond for Sqlite3.
- Use float for time spans in Sqlite3.
- Map the `octets` type to BLOBs for MariaDB and Sqlite3.
- Log recoverable errors for MariaDB and Sqlite3.

Removed:

- The v1 API is now removed.

Ecosystem:

- CI setup contributed by Brendan Long.
- Various documentation updates.

### CODE REVIEW

**Comment by paurkedal** [comment]
I'll need to strengthen some internal version constraints.

**Comment by samoht** [comment]
You forgot a few constraint for ppx_sexp_conv (the new packages have a runtime library as well).

```
#=== ERROR while installing caqti-driver-sqlite3.0.10.2 =======================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p caqti-driver-sqlite3 -j 4
# path         /home/travis/.opam/system/build/caqti-driver-sqlite3.0.10.2
# compiler     system (4.06.1)
# exit-code    1
# env-file     /home/travis/.opam/system/build/caqti-driver-sqlite3.0.10.2/caqti-driver-sqlite3-7959-e0259d.env
# stdout-file  /home/travis/.opam/system/build/caqti-driver-sqlite3.0.10.2/caqti-driver-sqlite3-7959-e0259d.out
# stderr-file  /home/travis/.opam/system/build/caqti-driver-sqlite3.0.10.2/caqti-driver-sqlite3-7959-e0259d.err
### stderr ###
# File "/home/travis/.opam/system/lib/uri/META", line 1, characters 0-0:
# Error: Library "ppx_sexp_conv.runtime-lib" not found.
# -> required by library "uri" in /home/travis/.opam/system/lib/uri
# Hint: try: jbuilder external-lib-deps --missing -p caqti-driver-sqlite3 @install
#=== ERROR while installing caqti-dynload.0.10.2 ==============================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p caqti-dynload -j 4
# path         /home/travis/.opam/system/build/caqti-dynload.0.10.2
# compiler     system (4.06.1)
# exit-code    1
# env-file     /home/travis/.opam/system/build/caqti-dynload.0.10.2/caqti-dynload-7959-6d487c.env
# stdout-file  /home/travis/.opam/system/build/caqti-dynload.0.10.2/caqti-dynload-7959-6d487c.out
# stderr-file  /home/travis/.opam/system/build/caqti-dynload.0.10.2/caqti-dynload-7959-6d487c.err
### stderr ###
# File "/home/travis/.opam/system/lib/uri/META", line 1, characters 0-0:
# Error: Library "ppx_sexp_conv.runtime-lib" not found.
# -> required by library "uri" in /home/travis/.opam/system/lib/uri
# Hint: try: jbuilder external-lib-deps --missing -p caqti-dynload @install
```

**Comment by paurkedal** [comment]
> You forgot a few constraint for ppx_sexp_conv (the new packages have a runtime library as well).

Caqti does not use ppx_sexp_conv directly.  The missing dependency belongs to uri, and this is covered by the larger issue #11852.

**Comment by kit-ty-kate** [comment]
Ok, I investigated the `ppx_sexp_conv.runtime-lib` issue today and I can't explain it. Everything was at the right place and dependencies were correctly set. I can't explain how relaunching the Travis runs fixed the problem either…

The problem was that `ppx_sexp_conv` was installed after `caqti-dynload` and others, so I guess a dependency was missing somewhere but I couldn't find the cause.

Oh well, seems ok now. Merging. Thanks!

**Comment by paurkedal** [comment]
@kit-ty-kate Thanks! I actually triggered the rebuild by a rebase on the current master, integrating the ppx dependency fix, so that should explain why the problem went away. As for how it broke in the first place, the uri library was probably upgraded (maybe due to the version constraint), which triggered a reinstall, which can fail when there is a wrong `{build}` in the constraints, as illustrated by the issue.

**Comment by kit-ty-kate** [comment]
@paurkedal mmh, when did you triggered the rebuild ?

**Comment by paurkedal** [comment]
@kit-ty-kate Today at 17:11:56 UTC.

**Comment by kit-ty-kate** [comment]
Mmh that might be it but I also triggered a rebuild around this time and that should have had the same effect ^^"

**Comment by paurkedal** [comment]
No, merely triggering a rebuild should not affect the outcome in this case.  If you rebuilt before the rebase, the branch used would still include the ppx dependency bug.

**Pull request merged**
