### PR TITLE
Package forester.2.2

### PR DESCRIPTION
**Pull request by jonsterling**
### `forester.2.2`
A tool for tending mathematical forests

---
* Homepage: https://github.com/jonsterling/ocaml-forester
* Source repo: git+https://github.com/jonsterling/ocaml-forester.git
* Bug tracker: https://github.com/jonsterling/ocaml-forester/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The failure in domainslib will be fixed by https://github.com/ocaml/opam-repository/pull/24161

**Comment by kit-ty-kate** [comment]
The lower-bounds checker fails with:
```

#=== ERROR while compiling forester.2.2 =======================================#
# context              2.2.0~alpha2~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | pinned(https://git.sr.ht/~jonsterling/ocaml-forester/archive/2.2.tar.gz)
# path                 ~/.opam/5.0/.opam-switch/build/forester.2.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p forester -j 71 @install
# exit-code            1
# env-file             ~/.opam/log/forester-7-17a1d1.env
# output-file          ~/.opam/log/forester-7-17a1d1.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/frontend/.Forester.objs/byte -I /home/opam/.opam/5.0/lib/algaeff -I /home/opam/.opam/5.0/lib/bwd -I /home/opam/.opam/5.0/lib/domainslib -I /home/opam/.opam/5.0/lib/ocaml/str -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocamlgraph -I /home/opam/.opam/5.0/lib/ppx_deriving/runtime -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/stdlib-shims -I /home/opam/.opam/5.0/lib/xmlm -I /home/opam/.opam/5.0/lib/yuujinchou -I lib/core/.Core.objs/byte -I lib/prelude/.Prelude.objs/byte -I lib/render/.Render.objs/byte -intf-suffix .ml -no-alias-deps -open Forester -o lib/frontend/.Forester.objs/byte/forester__LaTeXQueue.cmo -c -impl lib/frontend/LaTeXQueue.pp.ml)
# File "lib/frontend/LaTeXQueue.ml", line 36, characters 41-43:
# 36 |     let pool = T.setup_pool ~num_domains:10 () in
#                                               ^^
# Error: The function applied to this argument has type
#          ?name:string -> num_additional_domains:int -> Domainslib__Task.pool
# This argument cannot be applied with label ~num_domains
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/frontend/.Forester.objs/byte -I /home/opam/.opam/5.0/lib/algaeff -I /home/opam/.opam/5.0/lib/bwd -I /home/opam/.opam/5.0/lib/domainslib -I /home/opam/.opam/5.0/lib/ocaml/str -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocamlgraph -I /home/opam/.opam/5.0/lib/ppx_deriving/runtime -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/stdlib-shims -I /home/opam/.opam/5.0/lib/xmlm -I /home/opam/.opam/5.0/lib/yuujinchou -I lib/core/.Core.objs/byte -I lib/prelude/.Prelude.objs/byte -I lib/render/.Render.objs/byte -no-alias-deps -open Forester -o lib/frontend/.Forester.objs/byte/forester__Parser.cmi -c -intf lib/frontend/Parser.pp.mli)
# File "lib/frontend/Parser.mli", line 51, characters 56-64:
# 51 | val main: (Lexing.lexbuf -> token) -> Lexing.lexbuf -> (Code.doc)
#                                                              ^^^^^^^^
# Error: Unbound module Code
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I lib/frontend/.Forester.objs/byte -I lib/frontend/.Forester.objs/native -I /home/opam/.opam/5.0/lib/algaeff -I /home/opam/.opam/5.0/lib/bwd -I /home/opam/.opam/5.0/lib/domainslib -I /home/opam/.opam/5.0/lib/ocaml/str -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocamlgraph -I /home/opam/.opam/5.0/lib/ppx_deriving/runtime -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/stdlib-shims -I /home/opam/.opam/5.0/lib/xmlm -I /home/opam/.opam/5.0/lib/yuujinchou -I lib/core/.Core.objs/byte -I lib/core/.Core.objs/native -I lib/prelude/.Prelude.objs/byte -I lib/prelude/.Prelude.objs/native -I lib/render/.Render.objs/byte -I lib/render/.Render.objs/native -intf-suffix .ml -no-alias-deps -open Forester -o lib/frontend/.Forester.objs/native/forester__LaTeXQueue.cmx -c -impl lib/frontend/LaTeXQueue.pp.ml)
# File "lib/frontend/LaTeXQueue.ml", line 36, characters 41-43:
# 36 |     let pool = T.setup_pool ~num_domains:10 () in
#                                               ^^
# Error: The function applied to this argument has type
#          ?name:string -> num_additional_domains:int -> Domainslib__Task.pool
# This argument cannot be applied with label ~num_domains
```
Could you add those lower-bound constraints to your list of dependencies? (it looks like at least `domainslib` and whichever package introduces a module named `Code`, need some constraints)

**Comment by kit-ty-kate** [comment]
Using opam >= 2.2~alpha, `opam install --solver=builtin-0install "--criteria=+count[version-lag,solution]" .` on a fresh local switch should do the trick.

In case you haven't installed 2.2.0~alpha2 yet, you can do it using:
```
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh) --version 2.2.0~alpha2"
```

**Comment by jonsterling** [comment]
thanks so much! I'll test it with these commands and get an updated version to you soon.

**Comment by jonsterling** [comment]
@kit-ty-kate Hmm, I get a completely different failure from a different library when I do this.

**Comment by jonsterling** [comment]
Ah, I think I had somehow created my new switch incorrectly and now I can reproduce the error detected by the CI. Will investigate.

**Comment by jonsterling** [comment]
OK, I have now got things updated to the point that the command supplied by @kit-ty-kate succeeds. Because I have already released this version as a tag, I'm just going to close the PR and release a new version with a new PR.

**Pull request closed without merging**
