### PR TITLE
Package kafka.0.3

### PR DESCRIPTION
**Pull request by didier-wenzek**
### `kafka.0.3`

OCaml bindings for Kafka

Kafka is a high-throughput distributed messaging system.

---
* Homepage: https://github.com/didier-wenzek/ocaml-kafka
* Source repo: https://github.com/didier-wenzek/ocaml-kafka.git
* Bug tracker: https://github.com/didier-wenzek/ocaml-kafka/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by didier-wenzek** [comment]
I added the missing dependency `base-unix`.

**Comment by didier-wenzek** [comment]
The `(optional)` field of jbuilder seems not working as I expected :-(

Nonetheless I have to rework the package to remove a dependencies to cmdliner (used only optional binaries).

**Comment by didier-wenzek** [comment]
Checks failed because of `"No space left on device"`

**Comment by didier-wenzek** [comment]
The version of librdkafka which is installed by the travis CI is quit old (02/2014) and indeed not supported by these ocaml bindings.

**Comment by avsm** [comment]
Is there an Ubuntu release that does have the right version packaged? We can put that into the Datakit CI

**Comment by didier-wenzek** [comment]
The 16LTS/xenial release of Ubuntu comes with the 0.8.6 version of librdkafka which is enough.

How to configure the Datakit CI for a specific pull request ?

**Comment by didier-wenzek** [comment]
I added a missing `depexts` to zlib (which is not installed by default on debian). This fixes most builds.

The CentOS build is still failing (I don't understand why the `librdkafka-devel` package is not found).

I added the constraint `available: [  ocaml-version >= "4.02.3" ]` for jbuilder.

**Comment by didier-wenzek** [comment]
Can I do something for this pull request to make progress ?

The current package [kafka 0.2](http://opam.ocaml.org/packages/kafka/) comes with the constraint `ocaml-version < "4.03.0"`, which is a pitty.

I really wish to fix that before proceeding with the recent kafka features.

**Comment by avsm** [comment]
sorry about the delay -- we've had a backlog of PRs that I'll work through next week.

**Comment by didier-wenzek** [comment]
Thanks a lot to the whole OPAM team !

I fully understand that some pull requests are more important than others.
However, when a PR is stuck, this is a bit unclear if we only have to be patient or if we have to make some action.

**Pull request merged**
