### PR TITLE
[new release] sihl-web, sihl-session, sihl-email, sihl-persistence, sihl-contract, sihl-token, sihl-core, sihl-queue, sihl-user, sihl-storage, sihl-facade and sihl (0.3.0-rc1)

### PR DESCRIPTION
**Pull request by jerben**
Sihl HTTP service and middlewares

- Project page: <a href="https://github.com/oxidizing/sihl">https://github.com/oxidizing/sihl</a>
- Documentation: <a href="https://oxidizing.github.io/sihl/">https://oxidizing.github.io/sihl/</a>

### Fixed
- Replace functor based approach with service facade pattern based approach to increase ergonomy

### Added
- Implement MariaDB and PostgreSql backends for all services except storage service
- JSON Web Token backend for the token service
- Default middlewares for server side rendered forms and JSON API

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The version number isn't right. `0.3.0-rc1` will be chosen above `0.3.0`. What you want is for `0.3.0` to be chosen instead, the `~` separator is made for that.

Could you re-release sihl to the version `0.3.0~rc1` instead?

See the opam documentation on version ordering: https://opam.ocaml.org/doc/Manual.html#version-ordering

**Comment by jerben** [comment]
Thanks for the heads-up. I am using `dune-release` which seems to create the PR for opam-repository based on the git tag. Since `~` is not allowed in git tags, would `0.3.0+rc1` also work? I found this example https://opam.ocaml.org/packages/ocaml-variants/ocaml-variants.4.11.0+rc1/

**Comment by jerben** [comment]
I created a new PR with that approach, let me know if that is ok: https://github.com/ocaml/opam-repository/pull/17952

**Comment by kit-ty-kate** [comment]
Sorry I forgot to reply but no that's not a solution. + is not the right separator (see manual above). I'm not sure how to deal with that automatically using dune-release (cc @NathanReb) but if it's ok with you it's reasonably easy to deal with it manually with a simple `git mv` on this PR

**Comment by kit-ty-kate** [comment]
If you don't have the time I'll do it when I'll be back from this weekend break

**Comment by jerben** [comment]
Thanks for the help, I quickly did the rename.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
