### PR TITLE
+ prometheus.0.5

### PR DESCRIPTION
**Pull request by talex5**

### CODE REVIEW

**Comment by talex5** [comment]
prometheus-app.0.4 failed on 4.06 because it requires a version of cohttp that doesn't support 4.06. This isn't an error.

(also, it would be a lot clearer if the two CIs had different names and didn't fight for the status)

**Comment by gasche** [comment]
I'm concerned with the Travis failure, which fails on 4.06 but also on 4.05 while installing cohttp 0.20.1 with the following:

```
# Error: Multiple definition of the module name Fields.
#        Names must be unique in a given structure or signature.
# Command exited with code 2.
```

This is not an error due to your packages, but it seems to suggest a quality problem in the opam-repository, I'll try to investigate.

**Comment by hannesm** [comment]
@gasche I ran into a similar issue with 4.05.0 and cohttp -- you may want to have a look at https://github.com/mirage/ocaml-cohttp/pull/591 and https://github.com/mirage/ocaml-cohttp/issues/590 for investigation

**Comment by gasche** [comment]
Thanks @hannesm, that is very useful information -- it looks like my https://github.com/ocaml/opam-repository/pull/11085 was a bit misguided if that is a bug in ppx-land rather than in the cohttp codebase itself.

**Comment by hannesm** [comment]
@gasche I'm not completely sure what the root of the issue is.  I'm neither familiar with ppx nor with the cohttp codebase.

**Comment by gasche** [comment]
#11086 hopefully fixes the cohttp build issue, so I just restarted the failing Travis tests to see if it works better now.

**Comment by talex5** [comment]
It still seems to be failing.

**Comment by gasche** [comment]
Ah, it select `ppx_deriving.4.2.1` this time and that seems to be the problem. I will rinse and repeat with a broader conflict clause.

**Comment by talex5** [comment]
Great - it worked this time!

**Comment by gasche** [comment]
Merged. Apologies for keeping your PR hostage for this issue that affected other packages, but it's hard to debug these things without the CI support.

**Pull request merged**
