### PR TITLE
quota support is linux only, thus apply the patch disabling it also on FreeBSD

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
there is an upstream issue open since > 2 years, and nobody seem to care too much about it https://github.com/janestreet/core_extended/issues/2 @dch

**Comment by lpw25** [comment]
I think that the patch I gave [here](https://github.com/ocaml/opam-repository/pull/4696#issuecomment-136360350) might fix the issue on FreeBSD, but I have no way to test it.

**Comment by dch** [comment]
it works - thanks all so much!

```
dch   ~ ❯❯❯uname -a
FreeBSD wintermute.skunkwerks.at 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
dch   ~ ❯❯❯opam install core_extended
The following actions will be performed:
  ∗  install core_extended 112.35.00

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] https://opam.ocaml.org/archives/core_extended.112.35.00+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed core_extended.112.35.00
Done.
```

**Pull request merged**
