### PR TITLE
added packages/sklml/sklml.2.0+pl1

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by dsheets** [comment]
It looks like there are some problems with the OCaml version and also the bin path for `camlp5`.

**Comment by UnixJunkie** [comment]
The build errors were reported to the sklml devel mailing list.

**Comment by samoht** [comment]
@UnixJunkie any update? Should we close that PR and wait for upstream fixes?

**Comment by UnixJunkie** [comment]
ok

**Pull request closed without merging**
