### PR TITLE
[new release] anthill (0.1)

### PR DESCRIPTION
**Pull request by martindemello**
Word search library and utility

- Project page: <a href="https://github.com/martindemello/anthill">https://github.com/martindemello/anthill</a>
- Documentation: <a href="https://martindemello.github.io/anthill/">https://martindemello.github.io/anthill/</a>

##### CHANGES:

* Initial release

### CODE REVIEW

**Comment by martindemello** [comment]
it's my first opam package, yes :) happy to fix whatever details i got wrong!

**Comment by kit-ty-kate** [comment]
Your package looks good apart from the tiny change needed in the dependencies.
Dune should not be tagged as a build dependency due to a long-standing issue in dune (see https://github.com/ocaml/dune/issues/2147 and #14266)

Also one personal side-note from myself: when starting a project I'd recommand starting with the `base` library rather than `core` if you want to stay with Jane-Street style libraries. `core` pulls a lot of unnecessary dependencies, in most cases you just need base (I think they mostly have a compatible interface).

Thanks!

**Comment by kit-ty-kate** [comment]
Oh also could you return the fix I made upstream?

**Comment by martindemello** [comment]
should i send a new pull request with your fixes merged in?

**Comment by kit-ty-kate** [comment]
yes please! you might also have to retag the 0.1 (or a new version) though.

**Pull request merged**
