### PR TITLE
Add wasm-1.1.1

### PR DESCRIPTION
**Pull request by rossberg**
Includes new multi values, bit extension, and saturating conversions features.

### CODE REVIEW

**Comment by rossberg** [comment]
Btw, is it possible to update existing opam packages in a purely administrative manner? We'd like to clean up our git labels in the Wasm repo, which means that the zip file names and MD5's would have to change in this repo (though not their src content). Is that considered okay?

**Comment by kit-ty-kate** [comment]
Thanks!

> Btw, is it possible to update existing opam packages in a purely administrative manner? We'd like to clean up our git labels in the Wasm repo, which means that the zip file names and MD5's would have to change in this repo (though not their src content). Is that considered okay?

It is possible. If the checksums are the same this should be an easy PR to merge. However if the checksums are not the same we have to check that the changes are not major.

In any case the tags used by opam today should only be removed **after** (ideally give it a few days) the PR is being merged.

**Comment by rossberg** [comment]
@kit-ty-kate, the only thing that would change _inside_ the zip (and affects the checksum) is the name of the top-level directory everything is zipped into, because of the way GitHub creates these zip files. All the actual files inside that would remain identical. It sounds like that would be okay?

**Comment by kit-ty-kate** [comment]
Unless zip files generation are different in this regard, the top-level directory should not change name and the checksum should thus not be affected. They are only based on the name of the repository/organisation as far as I know. But even if they were, as long as the original archive/tag are not removed before the PR is merged I don't see any issues with this.

**Comment by rossberg** [comment]
Thanks, I'll create a PR then. (Except for `master`, the repo zip file generated by GH mangles the tag/branch name into the dir name, for example `xyz-abc` for tag `abc` in repo `xyz`.)

**Pull request merged**
