### PR TITLE
[new release] ocamlformat-lib, ocamlformat and ocamlformat-rpc-lib (0.26.2)

### PR DESCRIPTION
**Pull request by Julow**
CHANGES:

### Changed

- Compatible with OCaml 5.2.0 (ocaml-ppx/ocamlformat#2510, @gpetiot, @Julow)

### CODE REVIEW

**Comment by mseri** [comment]
I think it was a CI issue, I have restarted it.
You can ignore the lint issue, we are testing some new lints to prevent name clashes but it is still to fine

**Comment by raphael-proust** [comment]
Looks good, the CI is ok.

@Julow just out of curiosity, the LGPL mention is because of the vendored libraries?

**Comment by Julow** [comment]
@raphael-proust Yes, we vendor parts of the compiler which are LGPL. The rest of the code is under MIT.

**Comment by Julow** [comment]
@mseri Thanks! The CI is now passing, except for the lint step.

**Comment by raphael-proust** [comment]
Thanks a lot!

**Pull request merged**
