### PR TITLE
added packages/coccinelle/coccinelle.1.0.2

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
There is only one stalled build in error now.
So, Travis is happy but moody.

**Comment by UnixJunkie** [comment]
don't merge yet

**Comment by UnixJunkie** [comment]
we might change the configure options

**Comment by UnixJunkie** [comment]
all good except a failure to download in one case

**Comment by UnixJunkie** [comment]
I think this can be merged

**Comment by avsm** [comment]
thanks!

**Pull request merged**
