### PR TITLE
Release Caqti 1.7.0.

### PR DESCRIPTION
**Pull request by paurkedal**
It's time for a [new release of Caqti](https://github.com/paurkedal/ocaml-caqti/releases/tag/v1.7.0).

### CODE REVIEW

**Comment by paurkedal** [comment]
Added some missing version constraints. Apart from that CI revdeps detected the issue
```ocaml
[ERROR] No solution for sihl.0.3.0~rc2: The actions to process have cyclic dependencies:
          - install sihl.0.3.0~rc2 -> install sihl-token.0.3.0~rc2 -> install sihl-user.0.3.0~rc2 -> install sihl.0.3.0~rc2
          - install sihl.0.3.0~rc2 -> install sihl-token.0.3.0~rc2 -> install sihl.0.3.0~rc2


Command failed: opam list --readonly --with-test --external '--resolve=sihl.0.3.0~rc2' returned 20
```
and similar for related packages, which will probably turn up again.

**Comment by smorimoto** [comment]
The failures are unlikely to be directly related to this release, although they seem to be failures that need to be addressed. It would be better to take care of it with another PR.

**Review by smorimoto — APPROVED** [review]

**Comment by mseri** [comment]
The failure happen only on opam 2.0, they are known and fixed in 2.1. Indeed, don’t worry about those

**Comment by paurkedal** [comment]
Thanks for the help with sorting out the failures.

**Pull request merged**
