### PR TITLE
Bump ocamlformat's Jane Street dependencies to include 0.15

### PR DESCRIPTION
**Pull request by cgaebel**
Ref: https://github.com/ocaml-ppx/ocamlformat/pull/2059

### CODE REVIEW

**Comment by mseri** [comment]
The lower bound failure is unrelated (for the moment):
```
#=== ERROR while compiling ocp-build.1.99.21 ==================================#
# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.11.2 | file:///home/opam/opam-repository
# path                 ~/.opam/4.11/.opam-switch/build/ocp-build.1.99.21
# command              ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code            2
# env-file             ~/.opam/log/ocp-build-23-8390d5.env
# output-file          ~/.opam/log/ocp-build-23-8390d5.out
### output ###
# make create-booter
# make[1]: Entering directory '/home/opam/.opam/4.11/.opam-switch/build/ocp-build.1.99.21'
# cp -f libs/ocplib-compat/4.03.0/ocpCompat.ml \
# 	libs/ocplib-compat/string-compat/ocpCompat.ml
# ocamllex.opt libs/ocplib-lang/ocamllexer.mll
# 82 states, 1371 transitions, table size 5976 bytes
# ocamlyacc tools/ocp-build/lang-ocp/buildOCPParser.mly
# 12 shift/reduce conflicts, 22 reduce/reduce conflicts.
# ocamllex.opt tools/ocp-build/lang-ocp2/buildOCP2Lexer.mll
# 82 states, 1404 transitions, table size 6108 bytes
# ocamlyacc tools/ocp-build/lang-ocp2/buildOCP2Parser.mly
# echo "let version=\"1.99.21-beta\"" > tools/ocp-build/buildVersion.ml
# ocamllex.opt tools/ocp-build/meta/metaLexer.mll
# 22 states, 692 transitions, table size 2900 bytes
# ocamlopt.opt -c -o libs/ocplib-compat/string-compat/ocpCompat.cmx -I /home/opam/.opam/4.11/lib/cmdliner -I /home/opam/.opam/4.11/lib/re   -I libs/ocplib-debug  -I libs/ocplib-lang  -I libs/ocplib-maxunix  -I libs/ocplib-file  -I libs/ocplib-system  -I libs/ocplib-config  -I libs/ocplib-compat/string-compat -I tools/ocp-build -I libs/ezcmd -I tools/ocp-build/misc -I tools/ocp-build/lang-ocp -I tools/ocp-build/lang-ocp2 -I tools/ocp-build/engine -I tools/ocp-build/actions -I tools/ocp-build/meta -I tools/ocp-build/ocaml  libs/ocplib-compat/string-compat/ocpCompat.ml
# ocamlc.opt -c -o libs/ezcmd/ezcmd.cmi -I /home/opam/.opam/4.11/lib/cmdliner -I /home/opam/.opam/4.11/lib/re   -I libs/ocplib-debug  -I libs/ocplib-lang  -I libs/ocplib-maxunix  -I libs/ocplib-file  -I libs/ocplib-system  -I libs/ocplib-config  -I libs/ocplib-compat/string-compat -I tools/ocp-build -I libs/ezcmd -I tools/ocp-build/misc -I tools/ocp-build/lang-ocp -I tools/ocp-build/lang-ocp2 -I tools/ocp-build/engine -I tools/ocp-build/actions -I tools/ocp-build/meta -I tools/ocp-build/ocaml  libs/ezcmd/ezcmd.mli
# ocamlopt.opt -c -o libs/ezcmd/ezcmd.cmx -I /home/opam/.opam/4.11/lib/cmdliner -I /home/opam/.opam/4.11/lib/re   -I libs/ocplib-debug  -I libs/ocplib-lang  -I libs/ocplib-maxunix  -I libs/ocplib-file  -I libs/ocplib-system  -I libs/ocplib-config  -I libs/ocplib-compat/string-compat -I tools/ocp-build -I libs/ezcmd -I tools/ocp-build/misc -I tools/ocp-build/lang-ocp -I tools/ocp-build/lang-ocp2 -I tools/ocp-build/engine -I tools/ocp-build/actions -I tools/ocp-build/meta -I tools/ocp-build/ocaml  libs/ezcmd/ezcmd.ml
# File "libs/ezcmd/ezcmd.ml", line 17, characters 13-35:
# 17 |   type env = Cmdliner.Term.env_info
#                   ^^^^^^^^^^^^^^^^^^^^^^
# Alert deprecated: Cmdliner.Term.env_info
# Use Cmd.Env.info instead.
# File "libs/ezcmd/ezcmd.ml", line 58, characters 10-23:
# 58 | let env = Term.env_info
#                ^^^^^^^^^^^^^
# Alert deprecated: Cmdliner.Term.env_info
# Use Cmd.Env.info instead.
# File "libs/ezcmd/ezcmd.ml", line 150, characters 16-34:
# 150 | let cmd_exits = Term.default_exits
#                       ^^^^^^^^^^^^^^^^^^
# Alert deprecated: Cmdliner.Term.default_exits
# Use Cmd.Exit.defaults or Cmd.info's defaults ~exits value instead.
# File "libs/ezcmd/ezcmd.ml", line 157, characters 2-11:
# 157 |   Term.info sub.cmd_name ?version ~doc
#         ^^^^^^^^^
# Alert deprecated: Cmdliner.Term.info
# Use Cmd.info instead.
# File "libs/ezcmd/ezcmd.ml", line 192, characters 2-11:
# 192 |   Term.info "help" ~doc ~exits:Term.default_exits ~man
#         ^^^^^^^^^
# Alert deprecated: Cmdliner.Term.info
# Use Cmd.info instead.
# File "libs/ezcmd/ezcmd.ml", line 192, characters 31-49:
# 192 |   Term.info "help" ~doc ~exits:Term.default_exits ~man
#                                      ^^^^^^^^^^^^^^^^^^
# Alert deprecated: Cmdliner.Term.default_exits
# Use Cmd.Exit.defaults or Cmd.info's defaults ~exits value instead.
# File "libs/ezcmd/ezcmd.ml", line 196, characters 14-32:
# 196 |   let exits = Term.default_exits in
#                     ^^^^^^^^^^^^^^^^^^
# Alert deprecated: Cmdliner.Term.default_exits
# Use Cmd.Exit.defaults or Cmd.info's defaults ~exits value instead.
# File "libs/ezcmd/ezcmd.ml", line 198, characters 2-11:
# 198 |   Term.info name ?version ~doc ~sdocs ~exits ~man
#         ^^^^^^^^^
# Alert deprecated: Cmdliner.Term.info
# Use Cmd.info instead.
# File "libs/ezcmd/ezcmd.ml", line 230, characters 8-24:
# 230 |   match Term.eval_choice ~catch:false ~argv default_cmd cmds with
#               ^^^^^^^^^^^^^^^^
# Alert deprecated: Cmdliner.Term.eval_choice
# Use Cmd.group and one of Cmd.eval* instead.
# File "libs/ezcmd/ezcmd.ml", line 232, characters 9-18:
# 232 |   | t -> Term.exit t
#                ^^^^^^^^^
# Alert deprecated: Cmdliner.Term.exit
# Use Stdlib.exit and Cmd.eval instead.
# File "libs/ezcmd/ezcmd.ml", line 236, characters 16-25:
# 236 |           match Term.eval ~catch:false ?argv cmd with
#                       ^^^^^^^^^
# Alert deprecated: Cmdliner.Term.eval
# Use Cmd.v and one of Cmd.eval* instead.
# File "libs/ezcmd/ezcmd.ml", line 239, characters 17-26:
# 239 |           | t -> Term.exit t
#                        ^^^^^^^^^
# Alert deprecated: Cmdliner.Term.exit
# Use Stdlib.exit and Cmd.eval instead.
# File "libs/ezcmd/ezcmd.ml", line 283, characters 18-26:
# 283 |                   cmd_args;
#                         ^^^^^^^^
# Error: This expression has type
#          (string list * spec *
#           (?deprecated:string ->
#            ?absent:string -> string list -> Cmdliner.Arg.info))
#          list
#        but an expression was expected of type
#          arg_list = (string list * spec * info) list
#        Type
#          ?deprecated:string ->
#          ?absent:string -> string list -> Cmdliner.Arg.info
#        is not compatible with type info = string list -> Cmdliner.Arg.info 
# make[1]: *** [Makefile:349: libs/ezcmd/ezcmd.cmx] Error 2
# make[1]: Leaving directory '/home/opam/.opam/4.11/.opam-switch/build/ocp-build.1.99.21'
# make: *** [Makefile:215: boot/ocp-build.asm] Error 2
```

**Comment by mseri** [comment]
I think `dump_ocamlformat` needs a bound on core_unix:
```
#=== ERROR while compiling dump_ocamlformat.0.2.2 =============================#
# context              2.1.2 | linux/x86_64 | ocaml-variants.4.14.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/dump_ocamlformat.0.2.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p dump_ocamlformat -j 31 @install
# exit-code            1
# env-file             ~/.opam/log/dump_ocamlformat-7954-2a0a20.env
# output-file          ~/.opam/log/dump_ocamlformat-7954-2a0a20.out
### output ###
# (cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.dump_ocamlformat.objs/byte -I /home/opam/.opam/4.14/lib/base -I /home/opam/.opam/4.14/lib/base/base_internalhash_types -I /home/opam/.opam/4.14/lib/base/caml -I /home/opam/.opam/4.14/lib/base/md5 -I /home/opam/.opam/4.14/lib/base/shadow_stdlib -I /home/opam/.opam/4.14/lib/base_bigstring -I /home/opam/.opam/4.14/lib/base_quickcheck -I /home/opam/.opam/4.14/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/opam/.opam/4.14/lib/bin_prot -I /home/opam/.opam/4.14/lib/bin_prot/shape -I /home/opam/.opam/4.14/lib/core -I /home/opam/.opam/4.14/lib/core/base_for_tests -I /home/opam/.opam/4.14/lib/core/validate -I /home/opam/.opam/4.14/lib/fieldslib -I /home/opam/.opam/4.14/lib/int_repr -I /home/opam/.opam/4.14/lib/jane-street-headers -I /home/opam/.opam/4.14/lib/parsexp -I /home/opam/.opam/4.14/lib/ppx_assert/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_bench/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_expect/collector -I /home/opam/.opam/4.14/lib/ppx_expect/common -I /home/opam/.opam/4.14/lib/ppx_expect/config -I /home/opam/.opam/4.14/lib/ppx_expect/config_types -I /home/opam/.opam/4.14/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_here/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_inline_test/config -I /home/opam/.opam/4.14/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_log/types -I /home/opam/.opam/4.14/lib/ppx_module_timer/runtime -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/sexplib -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/splittable_random -I /home/opam/.opam/4.14/lib/stdio -I /home/opam/.opam/4.14/lib/time_now -I /home/opam/.opam/4.14/lib/typerep -I /home/opam/.opam/4.14/lib/variantslib -intf-suffix .ml -no-alias-deps -open Dump_ocamlformat -o lib/.dump_ocamlformat.objs/byte/dump_ocamlformat__Dump.cmo -c -impl lib/dump.pp.ml)
# File "lib/dump.ml", line 6, characters 12-32:
# 6 |   let inp = Unix.open_process_in "ocamlformat --version" in
#                 ^^^^^^^^^^^^^^^^^^^^
# Alert deprecated: module Core.Unix
# [since 2020-03] Core shadows Unix. Use Core_unix, which overrides some of Unix's behavior. If necessary, Unix is available and unshadowed as Caml_unix.
# File "lib/dump.ml", line 6, characters 12-32:
# 6 |   let inp = Unix.open_process_in "ocamlformat --version" in
#                 ^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value Unix.open_process_in
# (cd _build/default && /home/opam/.opam/4.14/bin/ocamlopt.opt -w -40 -g -I lib/.dump_ocamlformat.objs/byte -I lib/.dump_ocamlformat.objs/native -I /home/opam/.opam/4.14/lib/base -I /home/opam/.opam/4.14/lib/base/base_internalhash_types -I /home/opam/.opam/4.14/lib/base/caml -I /home/opam/.opam/4.14/lib/base/md5 -I /home/opam/.opam/4.14/lib/base/shadow_stdlib -I /home/opam/.opam/4.14/lib/base_bigstring -I /home/opam/.opam/4.14/lib/base_quickcheck -I /home/opam/.opam/4.14/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/opam/.opam/4.14/lib/bin_prot -I /home/opam/.opam/4.14/lib/bin_prot/shape -I /home/opam/.opam/4.14/lib/core -I /home/opam/.opam/4.14/lib/core/base_for_tests -I /home/opam/.opam/4.14/lib/core/validate -I /home/opam/.opam/4.14/lib/fieldslib -I /home/opam/.opam/4.14/lib/int_repr -I /home/opam/.opam/4.14/lib/jane-street-headers -I /home/opam/.opam/4.14/lib/parsexp -I /home/opam/.opam/4.14/lib/ppx_assert/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_bench/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_expect/collector -I /home/opam/.opam/4.14/lib/ppx_expect/common -I /home/opam/.opam/4.14/lib/ppx_expect/config -I /home/opam/.opam/4.14/lib/ppx_expect/config_types -I /home/opam/.opam/4.14/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_here/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_inline_test/config -I /home/opam/.opam/4.14/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_log/types -I /home/opam/.opam/4.14/lib/ppx_module_timer/runtime -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/sexplib -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/splittable_random -I /home/opam/.opam/4.14/lib/stdio -I /home/opam/.opam/4.14/lib/time_now -I /home/opam/.opam/4.14/lib/typerep -I /home/opam/.opam/4.14/lib/variantslib -intf-suffix .ml -no-alias-deps -open Dump_ocamlformat -o lib/.dump_ocamlformat.objs/native/dump_ocamlformat__Dump.cmx -c -impl lib/dump.pp.ml)
# File "lib/dump.ml", line 6, characters 12-32:
# 6 |   let inp = Unix.open_process_in "ocamlformat --version" in
#                 ^^^^^^^^^^^^^^^^^^^^
# Alert deprecated: module Core.Unix
# [since 2020-03] Core shadows Unix. Use Core_unix, which overrides some of Unix's behavior. If necessary, Unix is available and unshadowed as Caml_unix.
# File "lib/dump.ml", line 6, characters 12-32:
# 6 |   let inp = Unix.open_process_in "ocamlformat --version" in
#                 ^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value Unix.open_process_in
```

**Comment by mseri** [comment]
And the ocamlformat_rpc failure seems to be related to cmdliner
```
#=== ERROR while compiling ocamlformat-rpc.0.21.0 =============================#
# context              2.1.2 | linux/x86_64 | ocaml-variants.4.14.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/ocamlformat-rpc.0.21.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlformat-rpc -j 31 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/ocamlformat-rpc-477-869dfa.env
# output-file          ~/.opam/log/ocamlformat-rpc-477-869dfa.out
### output ###
# File "ocamlformat-rpc-help.txt", line 1, characters 0-0:
# /usr/bin/git --no-pager diff --no-index --color=always -u _build/default/ocamlformat-rpc-help.txt _build/default/ocamlformat-rpc-help.actual
# diff --git a/_build/default/ocamlformat-rpc-help.txt b/_build/default/ocamlformat-rpc-help.actual
# index 20d01e5..dc50803 100644
# --- a/_build/default/ocamlformat-rpc-help.txt
# +++ b/_build/default/ocamlformat-rpc-help.actual
# @@ -3,7 +3,7 @@ NAME
#         code.
#  
#  SYNOPSIS
# -       ocamlformat-rpc [OPTION]… 
# +       ocamlformat-rpc [OPTION]…
#  
#  DESCRIPTION
#         ocamlformat-rpc listens to RPC requests, provided on the standard
```

**Comment by cgaebel** [comment]
dump_ocamlformat and ocamlformat_rpc should be fixed now, I think.

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
