### PR TITLE
First alpha release for OCaml 5.1.0

### PR DESCRIPTION
**Pull request by Octachron**
This PR adds the base and variants+option package for the first alpha release of OCaml 5.1.0.
The ocaml metapackage has also been updated to allow installing the vanilla compiler.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by avsm** [comment]
Something's not quite right here; I'm getting this after testing this:

image

**Comment by avsm** [comment]
(The actual compiler installed is `ocaml.5.0.0` and `ocaml-base-compiler.5.0.0`)

**Comment by kit-ty-kate** [comment]
@avsm That sounds like an opam issue (the message isn't correct). Could you open a ticket there with a reproduction case?

Otherwise to upgrade to the new alpha compiler you need to install it explicitly (`opam upgrade` will not do it for you) as they have been tagged with `avoid-version` to avoid everyone upgrading to the alpha versions:
```
opam install ocaml-base-compiler.5.1.0~alpha1
```

**Pull request merged**
