### PR TITLE
3 packages from gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz

### PR DESCRIPTION
**Pull request by fpottier**
This pull-request concerns:
-`menhir.20211128`: An LR(1) parser generator
-`menhirLib.20211128`: Runtime support library for parsers generated by Menhir
-`menhirSdk.20211128`: Compile-time library for auxiliary tools related to
 Menhir

---
* Homepage: http://gitlab.inria.fr/fpottier/menhir
* Source repo: git+https://gitlab.inria.fr/fpottier/menhir.git
* Bug tracker: https://gitlab.inria.fr/fpottier/menhir/-/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mseri** [comment]
There seems to be only 4 unusual failures.
Two are unrelated I think, and I am sending a separate PR for them.
Do you know if these two are related to menhir?

- [obelisk.0.2.0](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/207e5f0919ce08eb408a4a911562da1494f5ac2c/variant/opam-2.0,compilers,4.13,menhir.20211128,revdeps,obelisk.0.2.0)
- [obelisk.0.3.0](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/207e5f0919ce08eb408a4a911562da1494f5ac2c/variant/opam-2.0,compilers,4.13,menhir.20211128,revdeps,obelisk.0.3.0)

**Comment by kit-ty-kate** [comment]
We should probably double-check all the revdeps works with OCaml < 4.11 first before merging.

**Comment by fpottier** [comment]
Hello, does this release look good? Can it be merged?

**Comment by mseri** [comment]
Looks good but we are trying to get a revdeps test on ocaml < 4.11 before merging (@kit-ty-kate were you able to run it?)

**Comment by fpottier** [comment]
Thanks. Anyway, I have tried compiling `obelisk` with various versions of OCaml (4.08, 4.13) and Menhir 20211125 and 20211128, and did not notice any problem.

**Comment by smorimoto** [comment]
At least, with my eyes grep opam-ci, revdeps looks fine.

**Review by smorimoto — APPROVED** [review]

**Comment by mseri** [comment]
They are but they are tested with the latest compiler, we wanted to have a separate check for 4.08 4.09 or 4.10 since the previous issue affected a number of packages and went undetected

**Comment by smorimoto** [comment]
Oh, I got the point. That's certainly an important point.

**Comment by kit-ty-kate** [comment]
Sorry I got distracted by something else and forgot to launch the test. It’s done and I’m not seeing any issues. Thanks and sorry for the delay

**Pull request merged**
