### PR TITLE
[new release] xdg, stdune, ordering, ocamlc-loc, fiber, dyn, dune, dune-site, dune-rpc, dune-rpc-lwt, dune-private-libs, dune-glob, dune-configurator, dune-build-info, dune-action-plugin and chrome-trace (3.6.2)

### PR DESCRIPTION
**Pull request by emillon**
XDG Base Directory Specification

- Project page: <a href="https://github.com/ocaml/dune">https://github.com/ocaml/dune</a>
- Documentation: <a href="https://dune.readthedocs.io/">https://dune.readthedocs.io/</a>

##### CHANGES:

- Fix configurator when using the MSVC compiler (ocaml/dune#6538, fixes ocaml/dune#6537, @nojb)

- Fix running the RPC server on windows (ocaml/dune#6721 fixes ocaml/dune#6720, @rgrinberg)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
We'd gladly take some more hands to fix all the failures on OCaml 5.0 if you have some spare time

**Comment by emillon** [comment]
Wouldn't call it spare time but I should pull my weight :)

**Comment by mseri** [comment]
@emillon thanks a lot for the many PRs.

As a rule of thumb, also to optimize your time, don't worry about backporting fixes to old packages. We kept this PR open mostly to add upper bounds to ocaml 5 where needed and check that there are no extra _unusual_ failures due to this release, some common errors in the CI are not a problem and would not prevent the merge

**Comment by emillon** [comment]
OK! I was at first worried about disabling tests for ocaml 5 but I understand that it's better to skip tests in that situation. As I was telling @kit-ty-kate, my priorities with these PRs are:
- making sure actual errors are not lost in the middle of ocaml 5 errors
- fix "known failures" for dune releases so that we don't have to diff manually at each release. this used to be around 360 errors, now it's more than 1000 so it'll be good to clear that as well.

**Comment by emillon** [comment]
As for this particular PR: I'm not particularly worried that there are regressions in this point release (it only contains 2 windows-only fixes on top of 3.6.1) but we plan on releasing 3.7.0 in a couple weeks and this one has riskier changes in it.

To pick my favorite technical debt analogy, we're in a kitchen and about to serve a lot of plates so I don't mind cleaning the kitchen before :)

**Comment by emillon** [comment]
To opam-repository maintainers: this PR is a useful list to iterate on the ocaml 5 failures, so it's useful to keep it open for a little while (I'm not sure we can easily hit "rebuild failed" once it's merged).

**Comment by emillon** [comment]
This is now good to go as far as I'm concerned - especially since I'm going to publish 3.7 soon (including an alpha to test regressions very soon).

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
