### PR TITLE
Add bitstring and ppx_bitstring v4.0.0

### PR DESCRIPTION
**Pull request by xguerin**

### CODE REVIEW

**Comment by xguerin** [comment]
From what I can tell the failures are not related to `bitstring`.

**Comment by kit-ty-kate** [comment]
> From what I can tell the failures are not related to `bitstring`.

All the failures are related:
* Here is a fix for FreeBSD: https://github.com/xguerin/bitstring/pull/23
* The revdep failures are all related to the fact that `bitstring.ppx` is not provided anymore. I assume this is an expected change, I'll add a commit to fix this in a minute.

**Comment by kit-ty-kate** [comment]
>     * The revdep failures are all related to the fact that `bitstring.ppx` is not provided anymore. I assume this is an expected change, I'll add a commit to fix this in a minute.

Actually, after re-reading the result, this breaks every single packages that is currently using `bitstring`. Is that expected or do you prefer to re-add this for compatibility? It's not a blocker but I just want to be sure before.

**Comment by xguerin** [comment]
I see. Thanks. Let me see what I can do.

**Comment by kit-ty-kate** [comment]
Hm, I'm not entirely sure what happened here. Why has my commit been removed from your branch?

**Comment by xguerin** [comment]
Not quite sure. It's on my master. I suspected a wrong hash/package path so I repushed everything.

**Comment by xguerin** [comment]
@kit-ty-kate It does not look like the FreeBSD Travis worker is picking your change. Would the old package be cached somehow?

**Comment by kit-ty-kate** [comment]
FreeBSD fails because it also tests the other packages changed in this PR and these now require bitstring < 4.0.0 which isn't compatible with FreeBSD.

Sorry for all the time this took to handle this PR. Thanks a lot for your work!

**Comment by xguerin** [comment]
Thank you !

**Pull request merged**
