### PR TITLE
Make Reason 1.13.7 work with latest topkg

### PR DESCRIPTION
**Pull request by hcarty**
The changes are build tweaks, backported from upstream's master branch.

### CODE REVIEW

**Comment by hcarty** [comment]
Discussed with @chenglou on discord.

**Comment by chenglou** [comment]
Cc @jordwalke @hcarty is patching 1.13.7 to support broader deps versions. Should work

**Comment by hcarty** [comment]
"It Works For Me"

And apologies @jordwalke - I should have @'d you as well initially!

**Comment by jordwalke** [comment]
what do you mean by "patching"? Is he submitting a PR to reason?

**Comment by hcarty** [comment]
@jordwalke PR already submitted.  This is a backport of that PR - https://github.com/facebook/reason/pull/1438

**Comment by gasche** [comment]
This looks fine once the CI completes. @hcarty do you plan to also test 4.06?

**Comment by hcarty** [comment]
@gasche I do, thanks for checking. When I tested+submitted this there were still dependencies which were not installable under 4.06.0 due to the safe-string changes. Once those get fixed and I'm able to test I'll submit another PR.

**Pull request merged**
