### PR TITLE
Package telegraml.2.2.0

### PR DESCRIPTION
**Pull request by OhadRau**
### `telegraml.2.2.0`

Telegram Bot API for OCaml
An implementation of the Telegram Bot API in 100% OCaml,
using Lwt for asynchronous operations and Cohttp for networking.
Implements most basic functionality present in the API, plus
convenience modules for error handling and defining commands.

---
* Homepage: https://github.com/nv-vn/telegraml
* Source repo: https://github.com/nv-vn/telegraml.git
* Bug tracker: https://github.com/nv-vn/telegraml/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by nv-vn** [comment]
Transferring ownership to @OhadRau, hope that's okay. In the future he will likely be the full-time maintainer of this project.

**Comment by mseri** [comment]
Is this really only supporting ocaml-4.06? From the Travis build it looks like it works for all the compiler versions _except_ 4.06.

**Comment by OhadRau** [comment]
@mseri seems like it should work with earlier versions so I dropped the requirement down to `>= 4.03`. Not sure why it's not working on 4.06 as it seemed okay to me but I will try with a fresh install

**Comment by mseri** [comment]
I had a look. You use ‘cohttp.let’ that does no longer exist since version 0.99, however you ask for cohttp >= 1.

You need to use cohttp <= 0.22 (or <0.99). Alternatively you need to add cohttp-lwt to the depndency and change the jbuild file to use cohttp-lwt in place of cohttp.lwt

**Comment by OhadRau** [comment]
Ok hopefully that worked? Not really sure how to do this stuff, pretty new to using OPAM

**Comment by mseri** [comment]
It is good now. Thanks for the package!

You may want to announce this on https://discuss.ocaml.org, where we have a Community category and an announce tag for this purpose.

**Pull request merged**
