### PR TITLE
delete bleeding edge 4.08 compilers as they might be selected by default

### PR DESCRIPTION
**Pull request by avsm**
temporary solution for https://github.com/ocaml/opam/issues/3510

these bleeding edge compilers will move into a new remote so they
are still accessible to advanced users, but this PR just removes
them for now as it is opam 2.0.0 release day :)

### CODE REVIEW

**Comment by mseri** [comment]
Let's merge then. Will you need to remove the other `+fature` variants for older compilers as well before the merge?

**Comment by mseri** [comment]
Also, do you need to remove https://github.com/ocaml/opam-repository/tree/2.0.0/packages/ocaml/ocaml.4.08.0 (and `ocaml-compiler.4.08.0*` and `ocaml-compiler-libs-4.08.0*`) now that there is no more an `ocaml-variant` for `ocaml` `4.08.0`?

**Comment by mseri** [comment]
Done. I'll double check with camelus and if it's ok merge

**Comment by avsm** [comment]
thanks @mseri !

**Pull request merged**
