### PR TITLE
Bap 1.2.0 Release

### PR DESCRIPTION
**Pull request by ivg**
The main features of release:
- Total C-bindings (over than 2000+ functions)
- Binary distribution (deb, rpm, tgz)

Other changes:
- support for OCaml 4.04.0
- more robust dynamic loading (independent on the runtime presence ocamlfind)
- rectified error handling in the LLVM backend
- new tool: beagle - obfuscated string solver (or strings on steroids)
- more robust (and simple) handling of comments in IDA Pro

### CODE REVIEW

**Comment by ivg** [comment]
I see that we have a new cool and shiny CI system. Much better than Travis! The problem is BAP's configuration is unable to detect what kind of system it is and so it requests llvm-3.8 package that is not available. I, myself, can't detect it either, it looks like some kind of Debian based docker machine. So the question is:

1. Can we install llvm-3.8 on it?
2. If not, can we install llvm-3.4?

These are the two versions that bap supports. 


Also, the CI started so many jobs that GitHub started to backtrack it, e.g.,

```
[bap-future: http] Command started
[ERROR] curl: code 429 while downloading
        https://github.com/BinaryAnalysisPlatform/bap/archive/v1.2.0.tar.gz
```

Where code 429 means "Too many requests". Probably, opam-ci should retry (with a delay) instead of failing. Too many requests is not an error, it is a request to limit the rate of requests.

**Comment by avsm** [comment]
> Where code 429 means "Too many requests". Probably, opam-ci should retry (with a delay) instead of failing. Too many requests is not an error, it is a request to limit the rate of requests

@altgr -- is this something that should be an OPAM2 feature request -- I can open an issue if so.  We can't control HTTP error code handling in the CI except via OPAM.

**Comment by avsm** [comment]
The shiny new CI can take arbitrary action inside Docker containers, but sadly `opam-depext` doesnt have enough metadata yet to specify custom Debian packages. We really need to fix it, but it won't happen for this PR.  I'm happy to merge this if you have done manual testing and are satisfied with the partial CI results.

**Comment by ivg** [comment]
Oh, yeah, we have our own CI, that includes [Docker][1] builds of the whole opam infrastructure, and the travis builds that run tests, so we are quite confident.  But of course, we are really looking forward to the integration with the opam's CI. If we can help somehow then please advice! 


[1]: https://hub.docker.com/r/binaryanalysisplatform/bap/builds/

**Comment by avsm** [comment]
thanks! I've noted down BAP as one of the prime projects to test the new functionality when it's implemented in opam-depext.

**Pull request merged**
