### PR TITLE
Add protocol-9p.0.4

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave.scott@docker.com>

### CODE REVIEW

**Comment by dsheets** [comment]
I think the opam file needs to be updates to match the one in the repository to remove `./configure` and similar. Also, this release looks like it is called 0.4.0 from the change log but the tag is 0.4.

**Comment by dsheets** [comment]
Did the version get updated? Still says `0.4` in the `opam` file, the directory name, and the `url`.

**Comment by djs55** [comment]
Oh sorry... did you intend to add the .0 to this release? I tagged it as
v0.4 by accident. Would you rather re-tag as v0.4.0 and use 0.4.0
throughout?

On Mon, Jan 25, 2016 at 9:33 PM, David Sheets <notifications@github.com>
wrote:

> Did the version get updated? Still says 0.4 in the opam file, the
> directory name, and the url.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocaml/opam-repository/pull/5490#issuecomment-174671944>
> .
>



-- 
Dave Scott

**Comment by dsheets** [comment]
Yes, I intended 0.4.0 as it gives us a little more runway for versions before 1.0 and provides a way to indicate new functionality vs bug fixes/optimizations.

**Pull request merged**
