### PR TITLE
[new release] mimic (0.0.4)

### PR DESCRIPTION
**Pull request by dinosaure**
A simple protocol dispatcher

- Project page: <a href="https://github.com/dinosaure/mimic">https://github.com/dinosaure/mimic</a>
- Documentation: <a href="https://dinosaure.github.io/mimic/">https://dinosaure.github.io/mimic/</a>

##### CHANGES:

- Use `Cstruct.length` instead of `Cstruct.len` (@dinosaure, dinosaure/mimic#2)
- Remove unnucessary `bigarray-compat` dependency (@hannesm, dinosaure/mimic#3)
- Remove `rresult` (@hannesm, dinosaure/mimic#4)
- Be able to introspect values produced by mimic (@dinosaure, dinosaure/mimic#5)
- Improve documentation (@dinosaure, dinosaure/mimic#6 & dinosaure/mimic#7)

### CODE REVIEW

**Comment by dinosaure** [comment]
Hmmhmm, the error is due to the `rresult` package which does not appear as a dependency on `paf`/`git-paf`/etc. The best should to constraint these packages to be in conflict with `mimic.0.0.4`?

**Comment by kit-ty-kate** [comment]
> The best should to constraint these packages to be in conflict with `mimic.0.0.4`?

yes, indeed

**Comment by dinosaure** [comment]
The error about `lower-bounds` is strange. I believed that in any case, OCaml will take the `Result` module from the `Stdlib` but it seems that it prefers to take the `result` package. I'm not sure how to properly fix that. Should I make a new release which explicitly use `Stdlib.Result` or should I put a new constraint on `mimic` to require, at least, `result.1.5.0`?

**Comment by kit-ty-kate** [comment]
yes, adding a conflict is much easier. That’s what i did in https://github.com/ocaml/opam-repository/pull/20169/commits/95fc0e5de8e7f44304b62ae4d16011e289b39676

**Comment by mseri** [comment]
Looks good now

**Pull request merged**
