### PR TITLE
Package: fswatch.11-0.1.1

### PR DESCRIPTION
**Pull request by kandu**
11-0.1.1 (2022-07-14)
----------------------

compatible with pthread on mac

### CODE REVIEW

**Comment by kandu** [comment]
build failure on debian and ubuntu is expected, the current packages of fswatch on these systems are buggy, waiting to be fixed.

**Comment by dinosaure** [comment]
> build failure on debian and ubuntu is expected, the current packages of fswatch on these systems are buggy, waiting to be fixed.

Can you add:
```
available: [ os = "macos" ]
```

And confirm that your package should be only available on MacOS?

**Comment by kandu** [comment]
[buster (oldstable](https://packages.debian.org/buster/libfswatch-dev)

Thanks. I'll add the this constraint when buster is out of its lifecycle. (I hope they'll have fixed this issue by then)

**Comment by kit-ty-kate** [comment]
conf-fswatch should be updated at some point to support more distributions (see https://github.com/ocaml/opam-repository/issues/22256) but it can be merged in the meantime. Thanks and sorry for this extremely long delay.

**Comment by kandu** [comment]
https://github.com/ocaml/opam-repository/issues/22256#issuecomment-1278523088

**Pull request merged**
