### PR TITLE
Package sid.1

### PR DESCRIPTION
**Pull request by phi-gamma**
### `sid.1`
Handle security identfiers

---
* Homepage: https://gitlab.com/phgsng/ocaml-sid
* Source repo: git+https://gitlab.com/phgsng/ocaml-sid.git
* Bug tracker: https://gitlab.com/phgsng/ocaml-sid

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by mseri** [comment]
```
#=== ERROR while compiling sid.1 ==============================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.1 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-base-compiler.4.07.1/.opam-switch/build/sid.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml setup.ml -configure --prefix /home/travis/.opam/ocaml-base-compiler.4.07.1 --enable-tests
# exit-code   1
# env-file    ~/.opam/log/sid-19233-6aa130.env
# output-file ~/.opam/log/sid-19233-6aa130.out
### output ###
# ocamlfind: Package `cmdliner' not found
# W: Field 'pkg_cmdliner' is not set: Command ''/home/travis/.opam/ocaml-base-compiler.4.07.1/bin/ocamlfind' query -format %d cmdliner > '/tmp/oasis-868663.txt'' terminated with error code 2
# E: Cannot find findlib package cmdliner
# E: Failure("1 configuration error")
```

**Comment by mseri** [comment]
Also consider using longer version numbers, like `1.0.0`

**Comment by phi-gamma** [comment]
2018-11-05 (Monday), notifications@github.com (Marcello Seri):

> ```
> #=== ERROR while compiling sid.1 ==============================================#
> # context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.1 | file:///home/travis/build/ocaml/opam-repository
> # path        ~/.opam/ocaml-base-compiler.4.07.1/.opam-switch/build/sid.1
> # command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml setup.ml -configure --prefix /home/travis/.opam/ocaml-base-compiler.4.07.1 --enable-tests
> # exit-code   1
> # env-file    ~/.opam/log/sid-19233-6aa130.env
> # output-file ~/.opam/log/sid-19233-6aa130.out
> ### output ###
> # ocamlfind: Package `cmdliner' not found
> # W: Field 'pkg_cmdliner' is not set: Command ''/home/travis/.opam/ocaml-base-compiler.4.07.1/bin/ocamlfind' query -format %d cmdliner > '/tmp/oasis-868663.txt'' terminated with error code 2
> # E: Cannot find findlib package cmdliner
> # E: Failure("1 configuration error")
> ```

Fixed, thank you!

> Also consider using longer version numbers, like `1.0.0`

I switched to the x.y scheme (“monotonic versioning”) and
published v1.1. At this point I don’t see an advantage in semver.

See https://github.com/ocaml/opam-repository/pull/12935

Best regards,
Philipp

**Comment by phi-gamma** [comment]
Fixed and submitted v1.1.

**Pull request closed without merging**
