### PR TITLE
[open] fix homepage; more lenient jbuilder constraint

### PR DESCRIPTION
**Pull request by smolkaj**

### CODE REVIEW

**Comment by hannesm** [comment]
Thanks for your PR.  The Travis CI fails while running the 0.2.0 tests:
```
[ERROR] The compilation of open failed at "jbuilder runtest -p open -j 4".
#=== ERROR while installing open.0.2.0 ========================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder runtest -p open -j 4
# path         /home/travis/.opam/system/build/open.0.2.0
# compiler     system (4.06.1)
# exit-code    1
# env-file     /home/travis/.opam/system/build/open.0.2.0/open-15973-c61e7b.env
# stdout-file  /home/travis/.opam/system/build/open.0.2.0/open-15973-c61e7b.out
# stderr-file  /home/travis/.opam/system/build/open.0.2.0/open-15973-c61e7b.err
### stderr ###
#       ocamlc examples/basic/.basic.eobjs/basic.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /usr/local/bin/ocamlc.opt -w -40 -g -bin-annot -I examples/basic/.basic.eobjs -I src/.open.objs -no-alias-deps -o examples/basic/.basic.eobjs/basic.cmo -c -impl examples/basic/basic.ml)
# File "examples/basic/basic.ml", line 6, characters 2-26:
# Error: This expression has type bool but an expression was expected of type
#          unit
```

could you fix this (likely needs another release).

**Comment by smolkaj** [comment]
Woops...should be fixed now.

**Comment by smolkaj** [comment]
@hannesm: I think this can be merged now.

**Comment by smolkaj** [comment]
@kit-ty-kate: I don’t understand. Is the version field not needed?

**Comment by kit-ty-kate** [comment]
Here the version field was outdated (0.1 being != to 0.1.0) and yes this is needed as the version is already given in the directory name. Version fields are required only when this information is unavailable (in dev repos for example).

Merging, thanks.

**Comment by smolkaj** [comment]
Makes sense. Thanks!

**Pull request merged**
