### PR TITLE
Package nocoiner.0.0.1

### PR DESCRIPTION
**Pull request by marcoonroad**
### `nocoiner.0.0.1`
A Commitment Scheme library for Coin Flipping/Tossing algorithms and sort
This project implements Commitment Schemes using the
Galois/Counter Mode (GCM) of secret-key encryption. Because this AES
encryption mode provides both Message Confidentiality and Integrity, it fits
perfectly the Hiding and Binding properties of Commitment Schemes.
Confidentiality protects the message against passive attacks while integrity
protects it from active attacks. GCM, so, works as an
Authenticated Encryption where it roughly works as an encryption algorithm
with MAC signatures on cipher data.

---
* Homepage: https://github.com/marcoonroad/nocoiner
* Source repo: git+https://github.com/marcoonroad/nocoiner.git
* Bug tracker: https://github.com/marcoonroad/nocoiner/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by marcoonroad** [comment]
:thinking: Somehow, the line 20 seems to be the root of problem:

```
  ["dune" "build" "-p" name]
```

I will figure out if this is really the case later.

**Comment by mseri** [comment]
There is no url field pointing at the sources to build. That is why it fails to build at the moment

**Comment by kit-ty-kate** [comment]
oops i messed up for the last commit message. You're requiring dune 1.9 as your `dune-package` contains:
```
(lang dune 1.9)
```
I'll squash my changes when I'll be merged. In the meantime could you return the fixes upstream?

**Comment by marcoonroad** [comment]
@kit-ty-kate, thank you!

Should I as well add the parallel/jobs flags on the OPAM file inside the nocoiner's project/repository?

**Comment by marcoonroad** [comment]
I've made the changes to support parallel builds on the nocoiner's repository accordingly.

**Comment by marcoonroad** [comment]
Oops, I forgot this part:

```
  "dune" {build & >= "1.9"}
```

:sweat_smile:

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
