### PR TITLE
OcLaunch version 0.2.2

### PR DESCRIPTION
**Pull request by leowzukw**

### CODE REVIEW

**Comment by dsheets** [comment]
```
# W: Failure("Command ''/home/lwzukw/.opam/4.01.0/bin/ocamlfind' query -format %d threads > '/tmp/oasis-d73d37.txt'' terminated with error code 127")
# sh: 1: /home/lwzukw/.opam/4.01.0/bin/ocamlfind: not found
# W: Failure("Command ''/home/lwzukw/.opam/4.01.0/bin/ocamlfind' query -format %d core_extended > '/tmp/oasis-09d31f.txt'' terminated with error code 127")
# sh: 1: /home/lwzukw/.opam/4.01.0/bin/ocamlfind: not found
# W: Failure("Command ''/home/lwzukw/.opam/4.01.0/bin/ocamlfind' query -format %d atdgen > '/tmp/oasis-d4a5e4.txt'' terminated with error code 127")
# E: Cannot find findlib package atdgen
# E: Cannot find findlib package core
# E: Cannot find findlib package core_extended
# E: Cannot find findlib package threads
# E: Failure("4 configuration errors")
```

It looks like you've put your oasis-computed configuration `setup.data` into your archive. See <https://gitlab.com/WzukW/oclaunch/blob/master/setup.data>.

**Comment by leowzukw** [comment]
I'm going to fix it

**Comment by samoht** [comment]
I've restarted the failing jobs

**Comment by leowzukw** [comment]
Thanks

**Pull request merged**
