### PR TITLE
Added ocamltter.4.0.0

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
Travis black x again. What should I do? Is it restarted automatically?

**Comment by samoht** [comment]
I've relaunched your failed run.

**Comment by samoht** [comment]
Can you add a checksum to the url file? Thanks!

**Comment by camlspotter** [comment]
ohh. checksum. Need to write a script to automate...

**Comment by camlspotter** [comment]
Added checksum. Thanks for pointing it out!

**Comment by Chris00** [comment]
@camlspotter You may want to have a look to [oasis2opam](https://github.com/ocaml/oasis2opam) which does this for you (and create a install file so the executable gets removed without the need to do anything special in the `remove` OPAM target).

**Comment by samoht** [comment]
Hum:
```
opam list -s -a ocamltter.4.0.0 | grep -v "No packages found."
Skipping ocamltter.4.0.0 as not installable
```

Not sure what is blocking here ...

**Pull request merged**
