### PR TITLE
jsoo.3.0 (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
@avsm, @diml, any idea why this errors out 

- (cd _build/default && /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/bytes -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/camlp4 -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/js_of_ocaml -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/js_of_ocaml-compiler -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml/compiler-libs -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/uchar -I toplevel/lib -no-alias-deps -I toplevel/lib/camlp4 -o toplevel/lib/camlp4/js_of_ocaml_toplevel_camlp4.cmo -c -impl toplevel/lib/camlp4/js_of_ocaml_toplevel_camlp4.pp.ml)
- File "toplevel/lib/camlp4/js_of_ocaml_toplevel_camlp4.ml", line 14, characters 5-11:
- Error: Unbound module Camlp4

**Comment by hhugo** [comment]
@avsm 
```
opam: "mkdir" failed on /tmp/opam-29-2c871f: No space left on device
```

**Comment by avsm** [comment]
@hhugo I'm not sure... camlp4 is available there...

**Comment by avsm** [comment]
closing this temporarily to clear a CI queue -- @hhugo could you reopen with the latest opam-repository changeset as well, so that the fixes will all be tested?

**Pull request closed without merging**
