### PR TITLE
raygun4ocaml needs cohttp

### PR DESCRIPTION
**Pull request by damiendoligez**

### CODE REVIEW

**Comment by toots** [comment]
As far as I know, `cohttp` is only an optional dependency, along with `lwt`.

**Comment by damiendoligez** [comment]
But it doesn't compile when `lwt` is present and `cohttp` is absent. Here is a better fix.

**Comment by toots** [comment]
:thumbsup:

**Comment by UnixJunkie** [comment]
all green in travis and camelus

**Pull request merged**
