### PR TITLE
[new release] curses (1.0.10)

### PR DESCRIPTION
**Pull request by mbacarella**
Bindings to ncurses

- Project page: <a href="https://github.com/mbacarella/curses">https://github.com/mbacarella/curses</a>

##### CHANGES:

* Updated to dune-lang 2.7, so that we don't have that generated .opam file
  bug anymore.

### CODE REVIEW

**Comment by mbacarella** [comment]
Actual changes
* Fix build on Arch Linux, and also more broadly on MacOS and Windows

**Comment by kit-ty-kate** [comment]
For the record the additional dependency is required because it failed with Homebrew:
```
#=== ERROR while compiling curses.1.0.10 ======================================#
# context              2.1.1 | macos/x86_64 | ocaml-system.4.13.1 | pinned(https://github.com/mbacarella/curses/releases/download/1.0.10/curses-1.0.10.tbz)
# path                 ~/.opam/default/.opam-switch/build/curses.1.0.10
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p curses -j 11 @install
# exit-code            1
# env-file             ~/.opam/log/curses-71814-168ac5.env
# output-file          ~/.opam/log/curses-71814-168ac5.out
### output ###
#     discover _config.h,c_flags.sexp,c_library_flags.sexp,config.ml (exit 1)
# (cd _build/default && ./discover.exe)
# which: pkg-config
# -> not found
# Error: 'pkg-config' missing
```

**Comment by kit-ty-kate** [comment]
Is the failure on Ubuntu 18.04 expected?
```
-   ocamlmklib dllcurses_stubs.so,libcurses_stubs.a (exit 2)
- (cd _build/default && /home/opam/.opam/4.13/bin/ocamlmklib.opt -g -o curses_stubs ml_curses.o -lncursesw)
- /usr/bin/ld: cannot find -lncursesw
- collect2: error: ld returned 1 exit status
```

**Comment by mbacarella** [comment]
> Is the failure on Ubuntu 18.04 expected?

No. It built successfully with ocaml-setup ubuntu-latest?  https://github.com/mbacarella/curses/runs/4279233327?check_suite_focus=true

**Comment by kit-ty-kate** [comment]
> > Is the failure on Ubuntu 18.04 expected?
> 
> No. It built successfully with ocaml-setup ubuntu-latest? https://github.com/mbacarella/curses/runs/4279233327?check_suite_focus=true

yes it sucessfully built with 20.04 here as well. Is that something you want to do something about or should we ignore the error? If so do you know the origin of the problem?

**Comment by mbacarella** [comment]
I'm content to ignore the Ubuntu 18 build error until someone complains, especially since it works in future builds.

Linking to ncurses is kind of a mess due to UNIX history and I've already sunk much more time into resolving this in a cross-platform way than I had budgeted.

**Comment by kit-ty-kate** [comment]
Thanks! Sorry for the wait

**Pull request merged**
