### PR TITLE
ocsigen-toolkit: upper version bound on js_of_ocaml(-lwt)

### PR DESCRIPTION
**Pull request by jrochel**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Checksums for ocsigen-toolkit 2.1.0, 2.2.0 and 2.3.1 are not matching, could you tag the right commit back to where there were before, if this works?

**Comment by jrochel** [comment]
@kit-ty-kate Are you alright with me removing unsupported versions of the package?

**Comment by jrochel** [comment]
@kit-ty-kate *bump* (Sorry, I'd really like to release eliom.6.9.2.)

**Comment by kit-ty-kate** [comment]
Sorry to leave you hanging. We usually don't delete packages, what if we I take over the maintenance for those releases?

**Comment by kit-ty-kate** [comment]
Alternatively they can be marked as `available: false` to effectively disable them but I'm not sure if it makes any sense if the archives are not available anymore

**Comment by kit-ty-kate** [comment]
Ok, `available: false` will do for now. I'll merge this as soon as the CI is green, sorry for the delay.

**Comment by kit-ty-kate** [comment]
@thomasblanc is Camelus not saying when a package is not available anymore? The `Installability check` is empty but packages were removed. I'm pretty sure it used to say `not installable anymore` or something like that.

**Comment by kit-ty-kate** [comment]
Thanks, sorry again.

**Comment by jrochel** [comment]
No worries, I don't have any sense of entitlement.
In any case, the archives are still available (or rather: available again).
Thanks. I'll stick to the `available: false` approach in the future.

**Pull request merged**
