### PR TITLE
[new release] mirage (4 packages) (4.4.2)

### PR DESCRIPTION
**Pull request by hannesm**
The MirageOS library operating system

- Project page: <a href="https://github.com/mirage/mirage">https://github.com/mirage/mirage</a>
- Documentation: <a href="https://mirage.github.io/mirage/">https://mirage.github.io/mirage/</a>

##### CHANGES:

- Fix GC documentation (space overhead is 120 since best-fit is default)
  (mirage/mirage#1491 @hannesm)
- use Option in printing of GC keys (mirage/mirage#1491 @hannesm)
- allow to use git 3.15 (mirage/mirage#1491 @hannesm)
- allow empty noop job (addresses an issue with mirage/mirage#1428)
  solves an issue reported by @MisterDA in mirage/mirage-www#815
  (mirage/mirage#1491 @hannesm)

### CODE REVIEW

**Comment by hannesm** [comment]
The CI issue (macOS testing with 4.14) shows errors such as:

```
# File "test/functoria/e2e/build.t", line 1, characters 0-0:
# /opt/homebrew/bin/git --no-pager diff --no-index --color=always -u _build/.sandbox/2bf1378694068514738c69cb9e60c30f/default/test/functoria/e2e/build.t _build/.sandbox/2bf1378694068514738c69cb9e60c30f/default/test/functoria/e2e/build.t.corrected
# diff --git a/_build/.sandbox/2bf1378694068514738c69cb9e60c30f/default/test/functoria/e2e/build.t b/_build/.sandbox/2bf1378694068514738c69cb9e60c30f/default/test/functoria/e2e/build.t.corrected
# index a9f2c75..91df9d9 100644
# --- a/_build/.sandbox/2bf1378694068514738c69cb9e60c30f/default/test/functoria/e2e/build.t
# +++ b/_build/.sandbox/2bf1378694068514738c69cb9e60c30f/default/test/functoria/e2e/build.t.corrected
# @@ -17,6 +17,8 @@ Build an application.
#                         vote=cat (default),
#                         warn_error=false (default)
#    config.exe: [INFO] dune build --root .
# +  ld: warning: -undefined suppress is deprecated
# +  ld: warning: -undefined suppress is deprecated
#    $ ls -a app/
#    .
#    ..
# @@ -66,6 +68,8 @@ Test `--output`:
#                         vote=cat (default),
#                         warn_error=false (default)Output     toto
#    config.exe: [INFO] dune build --root .
# +  ld: warning: -undefined suppress is deprecated
# +  ld: warning: -undefined suppress is deprecated
#    $ ls -a app/
#    .
#    ..

```

Now, I neither have a mac, nor am I a fan of "expect tests" -- but I also observe that the same tests are running fine with OCaml 5 on macOS. I wonder what should be done here, any suggestion? I'm fine to restrict the tests to `os != "macos"`, although that is an over-approximation. Any ideas?

**Comment by hannesm** [comment]
I took the liberty to restrict the e2e tests of functoria to `os != "macos"`.

**Comment by mseri** [comment]
I think it is fine. As of XCode 15 there is a new linker and some flags have been deprecated. On [stackoverflow](https://stackoverflow.com/questions/77525544/apple-linker-warning-ld-warning-undefined-error-is-deprecated) I read:

> the default treatment for -undefined is error - you can simply cancel this explicit flag setup in cmake.
> Also keep in mind that you still can explicitly request the old/classic linker with the flag -ld64.

**Comment by mseri** [comment]
seems that the failure is still there, for me you can just drop the change and we merge with  failing tests: it takes a second looking at the log to see that the issue is not problematic and revdeps are running on linux anyay

**Comment by hannesm** [comment]
@mseri I force-pushed removing my recent commit. Thanks a lot.

**Pull request merged**
