### PR TITLE
[new release] cohttp-async and cohttp-mirage (2.1.1)

### PR DESCRIPTION
**Pull request by avsm**
CoHTTP implementation for the Js_of_ocaml JavaScript compiler

- Project page: <a href="https://github.com/mirage/ocaml-cohttp">https://github.com/mirage/ocaml-cohttp</a>
- Documentation: <a href="https://mirage.github.io/ocaml-cohttp/">https://mirage.github.io/ocaml-cohttp/</a>

##### CHANGES:

- `cohttp-mirage`: remove dependency on the `result` module
  (mirage/ocaml-cohttp#662 @hannesm)
- Support Async v0.12.0 and higher (mirage/ocaml-cohttp#661 @copy)

### CODE REVIEW

**Comment by mseri** [comment]
@avsm ionly cohttp-mirage and cohttp-async changed, should we limit the release to only those two?

**Comment by avsm** [comment]
@mseri -- i'm going with the convention of releasing everything for convenience for now. It makes the constraints so much easier to manage and ensures versions don't get out sync.  I agree we should improve dune-release to make the single-package case easier though!

**Comment by avsm** [comment]
I could rm the extra packages here from this branch though...

**Comment by mseri** [comment]
I used to skip versdion numbers to make sure releases were always incremental but avoiding forcing rebuilds. In principle I am fine with either choice, I just wanted to double check.

**Comment by avsm** [comment]
ive pushed a changeset to remove the unchanged packages and tighten constraints

**Comment by mseri** [comment]
Thanks

**Pull request merged**
