### PR TITLE
Frenetic add bound

### PR DESCRIPTION
**Pull request by damiendoligez**
Add an upper bound on `openflow` version for old versions of `frenetic`.

### CODE REVIEW

**Comment by samoht** [comment]
@arjunguha seems that openflow has a missing dependency to camlp4:

```
#=== ERROR while installing openflow.0.1.1 ====================================#
# opam-version 1.2.2
# os           linux
# command      ocaml setup.ml -configure
# path         /home/travis/.opam/4.01.0/build/openflow.0.1.1
# compiler     4.01.0
# exit-code    1
# env-file     /home/travis/.opam/4.01.0/build/openflow.0.1.1/openflow-17798-be72be.env
# stdout-file  /home/travis/.opam/4.01.0/build/openflow.0.1.1/openflow-17798-be72be.out
# stderr-file  /home/travis/.opam/4.01.0/build/openflow.0.1.1/openflow-17798-be72be.err
### stderr ###
# ocamlfind: Package `lwt.syntax' not found
# W: Field 'pkg_lwt_syntax' is not set: Command ''/home/travis/.opam/4.01.0/bin/ocamlfind' query -format %d lwt.syntax > '/tmp/oasis-a90546.txt'' terminated with error code 2
# E: Cannot find findlib package lwt.syntax
# E: Failure("1 configuration error")
```

The cstruct.0.7.0  is fixed by #7288

**Comment by samoht** [comment]
The openflow errors are fixed by #7289

**Comment by samoht** [comment]
I've restarted the jobs now that #7289 are in

**Comment by arjunguha** [comment]
Thanks!

**Pull request merged**
