### PR TITLE
ppx_deriving 4.0 breaks compat with ppx_type_conv

### PR DESCRIPTION
**Pull request by rgrinberg**
cc @diml @whitequark

### CODE REVIEW

**Comment by samoht** [comment]
I've restarted the failed jobs

**Comment by rgrinberg** [comment]
The remaining failing job is on 3.12 which isn't relevant to this PR anyway.

**Comment by samoht** [comment]
Thanks!

**Comment by lpw25** [comment]
This only updated the latest ppx_type_conv. I think the other versions need fixing as well, otherwise if `ppx_deriving.4.0` is already installed then opam just picks an older version of `ppx_type_conv`.

**Comment by whitequark** [comment]
Perhaps this is better addressed as a conflicts clause on ppx_deriving.4.0?

**Comment by samoht** [comment]
@lpw25 I was hoping that you or @diml had script to update all the constraints automatically. I've quickly merged that PR because it seems to break a lot of automated tests running on 4.03.

@whitequark we usually don't use the conflict field for these kind of constraint as it put pressure on the solver (it is not optimised to solve complex conflict expressions) so I think it is better to not do it. I'm happy to be contradicted by any solver expert though :-)

**Comment by rgrinberg** [comment]
Should I add the constraints for older ppx_type_conv as well or is someone is already on it?

**Comment by lpw25** [comment]
If you could that would be great. If not I'll try to find time tomorrow.

**Pull request merged**
