### PR TITLE
musl+static+flambba ocaml: disable shared libraries in compiler config

### PR DESCRIPTION
**Pull request by avsm**
this fixes relocation errors when building on some distributions
(ocaml/ocaml#9131 #15344)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by copy** [comment]
@avsm This reverts https://github.com/ocaml/opam-repository/pull/14664 and thus breaks `ppx_deriving` on static switches again (https://github.com/ocaml/opam-repository/issues/14663). The problem is that Dynlink is disabled when `--disable-shared` is given and  `ppx_deriving` uses Dynlink.

Also note that musl+static+flambda doesn't create static executables by default (`-ccopt -static` needs to be passed to ocamlopt), so in https://github.com/ocaml/opam-repository/pull/14664 we created a musl+flambda switch, which may also be affected by this.

As a side note, I create my switches using `CC=/opt/x86_64-linux-musl-native/bin/gcc opam switch create 4.10.0+flambda` these days, which is not broken by this change.

**Comment by mseri** [comment]
I think we shuld put a note on the image meaning/content and the hint about the switch shared by @copy somewhere reachable, like the switch itself or a page in ocamlverse. Any thought?

**Comment by avsm** [comment]
Sorry about that @copy - I agree that putting a clearer marker on these description files would be very helpful @mseri.

But how do we fix this? There's a build error on PIE distributions if `.so` files are built and relocated currently.

**Comment by copy** [comment]
> But how do we fix this? There's a build error on PIE distributions if .so files are built and relocated currently.

I don't really understand the issue, in particular why it happens with musl-gcc but not regular gcc. It seems to be independent of `-static`, i.e. `./configure CC=musl-gcc && make` fails on Ubuntu, so I think this should be fixed in the compiler. If not, we could at least add the `--disable-shared` flag only on PIE distributions.

**Comment by avsm** [comment]
I tracked this down. Turns out that the version of musl in Ubuntu 18.04 (1.1.19) has a bug with static linking, so I backported 1.1.24 and created a PPA with it.

Doing

```
# add-apt-repository -y ppa:avsm/musl
# apt-get -y install musl-tools
# opam switch create foo ocaml-variants.4.10.0+musl+static+flambda
```

Now works on ubuntu 18.04. I'll test it a bit more and then add a messages to the opam file to point to these instructions on failure.  Incidentally ubuntu-18.04 is useful since its the default Linux VM for GitHub Actions, so now we can [build static binaries from there too](https://github.com/ocamllabs/duniverse/runs/512220645?check_suite_focus=true).

**Pull request merged**
