### PR TITLE
fix url.src for higlo

### PR DESCRIPTION
**Pull request by zapashcanon**
@zoggy fyi

### CODE REVIEW

**Comment by zoggy** [comment]
Higlo has moved to framagit: https://framagit.org/zoggy/higlo and has a correct opam file now.

**Comment by dra27** [comment]
The URLs also work with `github.io` instead of `github.com`, e.g. http://zoggy.github.io/higlo/higlo-0.5.tar.gz

**Comment by zapashcanon** [comment]
done :)

**Comment by mseri** [comment]
Thanks

**Comment by zoggy** [comment]
All urls should be fixed in https://github.com/ocaml/opam-repository/pull/20186 .

**Pull request merged**
