### PR TITLE
OPAM package for Alt-Ergo 2.2.0

### PR DESCRIPTION
**Pull request by OCamlPro-Iguernlala**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Looks alright but there are some a problem with uninstallation:
```
# OCAMLFIND_DESTDIR=/home/opam/.opam/4.05.0/lib \
#   ocamlfind install alt-ergo altErgoLib.* META
# ocamlfind: Package alt-ergo is already installed
#  - (file /home/opam/.opam/4.05.0/lib/alt-ergo/META already exists)
# Makefile.users:259: recipe for target 'install-lib' failed
# make: *** [install-lib] Error 2
```
It seems that you uninstallation script doesn't remove the `alt-ergo` library but rather `alt-ergo-lib` (which doesn't seem to exist :/)

**Comment by OCamlPro-Iguernlala** [comment]
Thanks,

another weired error, with Travis this time
```

**Comment by kit-ty-kate** [comment]
I just relaunched the OSX build. I'll merge it as soon as it succeed :)

**Comment by kit-ty-kate** [comment]
All good. Thanks !

**Pull request merged**
