### PR TITLE
Fixes for package brotli

### PR DESCRIPTION
**Pull request by aantron**
Fix checksums for brotli [1.0](https://ci.ocaml.org/log/saved/docker-run-933c30df330efb810f8fc7c069e4b09d/d5a8e7dcef7b0fa9dbe5d8063d6cbc1134ebfaae), [1.1](https://ci.ocaml.org/log/saved/docker-run-ef3daf14977c1c65528d9ea63c169a86/ac3c4d121d8ef77e1024ab429160e4f4fe4ac68a), [2.0.2](https://ci.ocaml.org/log/saved/docker-run-904babafd71b5144aa59bdfc6d91ecab/902d2b4b5f3b7d43a50f10f97a82f65c73668908). Other versions are probably also affected. Are the original archives available in a cache somewhere, so we can link them instead of changing the checksums?

cc @fxfactorial

@avsm, I'm beginning to suspect that the checksum change is related to renaming the repo. Perhaps that is when GitHub repacks releases?

Lambda Soup used to be `lambda-soup`, and now it is `lambdasoup`, while brotli used to be `ocaml-brotli`, but is now `reason-brotli`.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
> I'm beginning to suspect that the checksum change is related to renaming the repo. Perhaps that is when GitHub repacks releases?

It is the case

**Comment by aantron** [comment]
Added constraints from brotli on package lwt: brotli [1.0](https://ci.ocaml.org/log/saved/docker-build-9984a5cfd06c83f6530ff4c23e59af2a/5f4329df78676321ce651445c3a9ce1a2a5b5947), [1.1](https://ci.ocaml.org/log/saved/docker-build-afbdc727e59d304b5b2222587a8ab3f1/d43eb2c3a5e2b8d12707047d6955953ed87c4d84) use `lwt.ppx`, which was [removed](https://github.com/ocsigen/lwt/releases/tag/4.0.0) in Lwt 4.0.0.

There is at least one more issue to resolve, I'll ping when this is ready for review. I should have marked this PR WIP.

**Comment by aantron** [comment]
> It is the case

Can we report this to GitHub somewhere?

**Comment by aantron** [comment]
brotli 2.0.2 [assumes](https://ci.ocaml.org/log/saved/docker-build-b39df0a026718ae3ce7b6ba04e07a1dd/680a731bf4466ea99386ccc073c17d591bf31bee) equality between `string` and `bytes`.

**Comment by aantron** [comment]
Should be ready for review/merge. The Compilers failures seem to be due to missing system dependencies in the respective containers.

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
