### PR TITLE
New release of datakit

### PR DESCRIPTION
**Pull request by samoht**
CHANGES:

- all: update to latest version of alcotest, conduit, session, ocaml-github,
  ocaml-github-hooks and cohttp (moby/datakit#612, @samoht and @djs55)

- github: make `User.t` abstract (moby/datakit#594, @samoht)
- github: turn `Webhook.events` into a promise (moby/datakit#598, @samoht)
- github: add a `Comment` module to model PR and issue comments (moby/datakit#595, @samoht)
- github: change `PR.owner` to be of type `User.t` (moby/datakit#599, @samoht)

- github-bridge: add the ability to sync PR's coments (moby/datakit#595, @samoht)

- go-client: handle large values when reading / writing in 9db (moby/datakit#292, @simonferquel)
- go-client: fix the handling of defaults over upgrade (moby/datakit#605, @djs55)
- go-client: improve transaction API (moby/datakit#606, @djs55)

### CODE REVIEW

**Comment by samoht** [comment]
cohttp.0.99 failure on 4.03:

```
[31m#===[m [01mERROR[m [01mwhile installing cohttp.0.99.0[m [31m=====================================#[m
[33m#[m [33mopam-version[m 1.2.2
[33m#[m [33mos[m           linux
[33m#[m [33mcommand[m      jbuilder build -p cohttp -j 4
[33m#[m [33mpath[m         /home/travis/.opam/4.03.0/build/cohttp.0.99.0
[33m#[m [33mcompiler[m     4.03.0
[33m#[m [33mexit-code[m    1
[33m#[m [33menv-file[m     /home/travis/.opam/4.03.0/build/cohttp.0.99.0/cohttp-30047-ab0078.env
[33m#[m [33mstdout-file[m  /home/travis/.opam/4.03.0/build/cohttp.0.99.0/cohttp-30047-ab0078.out
[33m#[m [33mstderr-file[m  /home/travis/.opam/4.03.0/build/cohttp.0.99.0/cohttp-30047-ab0078.err
[33m### stderr ###
[m[33m# [m[...]
[33m# [mFile "cohttp/src/link.ml", line 123, characters 10-11:
[33m# [mError: Multiple definition of the module name Fields.
[33m# [m       Names must be unique in a given structure or signature.
[33m# [m    ocamlopt cohttp/src/cohttp__Link.{cmx,o} (exit 2)
[33m# [m(cd _build/default && /home/travis/.opam/4.03.0/bin/ocamlopt.opt -w -40 -g -I /home/travis/.opam/4.03.0/lib/base -I /home/travis/.opam/4.03.0/lib/base/caml -I /home/travis/.opam/4.03.0/lib/base/shadow_stdlib -I /home/travis/.opam/4.03.0/lib/base64 -I /home/travis/.opam/4.03.0/lib/bytes -I /home/travis/.opam/4.03.0/lib/fieldslib -I /home/travis/.opam/4.03.0/lib/ocaml -I /home/travis/.opam/4.03.0/lib/ppx_deriving -I /home/travis/.opam/4.03.0/lib/re -I /home/travis/.opam/4.03.0/lib/result -I /home/travis/.opam/4.03.0/lib/sexplib -I /home/travis/.opam/4.03.0/lib/sexplib/0 -I /home/travis/.opam/4.03.0/lib/stringext -I /home/travis/.opam/4.03.0/lib/uri -no-alias-deps -I cohttp/src -open Cohttp -o cohttp/src/cohttp__Link.cmx -c -impl cohttp/src/link.pp.ml)
[33m# [mFile "cohttp/src/link.ml", line 123, characters 10-11:
[33m# [mError: Multiple definition of the module name Fields.
[33m# [m       Names must be unique in a given structure or signature.
[33m# [m
[33m# [mWaiting for 1 job to finish.
```
Note sure what this means ...
All the datakit issues are due to the constraint solver timing out.

**Comment by samoht** [comment]
Ha yes, the issue is https://github.com/ocaml-ppx/ppx_deriving/issues/147

So I guess cohttp needs an upper bound on the ppx_deriving to use.

**Comment by hannesm** [comment]
@samoht shouldn't instead the `ppx_deriving` versions which generate duplicated code have an `available != 4.03.0`?  or is the issue only with deriving and cohttp?

**Comment by samoht** [comment]
@hannesm that's probably the right fix indeed!

**Comment by samoht** [comment]
I guess that's the same issue as https://github.com/ocaml/opam-repository/pull/10807

**Comment by samoht** [comment]
Rebased on top of master to get the fix from #10807

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
