### PR TITLE
[campl5] New release, compatible up to 4.06.2

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
It seems that camlp5 upstream is itself broken: https://github.com/camlp5/camlp5/issues/19

Dunno how they released without testing it.

**Comment by gasche** [comment]
My understanding is that this release should not go into the repository, and that Daniel just did a new release. @ejgallego, please complain if I got this wrong :-)

**Comment by ejgallego** [comment]
Well I was going to update this PR with the new, fixed release, but I'll submit a new PR if you want.

**Comment by gasche** [comment]
Updating the PR also works, sorry. I just reopened.

**Comment by ejgallego** [comment]
Oh no worries, thanks!

**Comment by ejgallego** [comment]
Looks good to go, CI fails on unrelated stuff:
```
### stderr ###
# + echo
# + m4
# sh: m4: not found
```

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
