### PR TITLE
[new release] mirage, mirage-runtime, functoria and functoria-runtime (4.2.0)

### PR DESCRIPTION
**Pull request by hannesm**
The MirageOS library operating system

- Project page: <a href="https://github.com/mirage/mirage">https://github.com/mirage/mirage</a>
- Documentation: <a href="https://mirage.github.io/mirage/">https://mirage.github.io/mirage/</a>

#### Fixed

- Remove non-existing mirage-repo-add and mirage-repo-rm from PHONY in generated
  Makefile (mirage/mirage#1332, @hannesm)
- Update deprecated references (mirage/mirage#1337, @reynir)

#### Changed

- Prepare for reproducing unikernels with generated opam file (mirage/mirage#1335, @hannesm)
  - split x-mirage-configure (mirage configure), x-mirage-pre-build
    (make lock pull), and build instructions in opam file
  - embed x-mirage-extra-repo (a list of opam repositories to use)
  - take relative paths up to git repository into account
  - include x-mirage-opam-lock-location (relative to git repository root)
- Adapt constraints for mirage-solo5 0.9.0 and mirage-xen 8.0.0 (ocaml-solo5
  0.8.1 with trim and improved memory metrics) (mirage/mirage#1338, @hannesm, based on
  @palainp work)
- Require opam-monorepo 0.3.2 (mirage/mirage#1332 mirage/mirage#1334, @hannesm @dinosaure)
- Use OPAMVAR_monorepo instead of OPAMVAR_switch in generated opam file (mirage/mirage#1332,
  @hannesm)
- Remove name from opam file (mirage/mirage#1332, @hannesm)

### CODE REVIEW

**Comment by hannesm** [comment]
CI looks to have some spurious failures, including out of disk space...

**Comment by hannesm** [comment]
I force-pushed, remaining CI issues are unrelated, apart from the "expect test":

```
#=== ERROR while compiling mirage.4.2.0 =======================================#
# context              2.1.2 | macos/x86_64 | ocaml.4.14.0 | pinned(https://github.com/mirage/mirage/releases/download/v4.2.0/mirage-4.2.0.tbz)
# path                 ~/.opam/default/.opam-switch/build/mirage.4.2.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p mirage -j 11
# exit-code            1
# env-file             ~/.opam/log/mirage-67543-6504b4.env
# output-file          ~/.opam/log/mirage-67543-6504b4.out
### output ###
# (cd _build/default/test/mirage && ./test.exe)
# Testing `mirage'.
# This run has ID `27538NG6'.
# 
#   [OK]          basic          0   pp.
# 
# Full test results in `~/.opam/default/.opam-switch/build/mirage.4.2.0/_build/default/test/mirage/_build/_tests/mirage'.
# Test Successful in 0.000s. 1 test run.
# File "test/mirage/query/run.t", line 1, characters 0-0:
# /usr/bin/git --no-pager diff --no-index --color=always -u _build/.sandbox/15c2ed09e9f0f4404677e4f674252a1d/default/test/mirage/query/run.t _build/.sandbox/15c2ed09e9f0f4404677e4f674252a1d/default/test/mirage/query/run.t.corrected
# diff --git a/_build/.sandbox/15c2ed09e9f0f4404677e4f674252a1d/default/test/mirage/query/run.t b/_build/.sandbox/15c2ed09e9f0f4404677e4f674252a1d/default/test/mirage/query/run.t.corrected
# index 68f685f..6d06585 100644
# --- a/_build/.sandbox/15c2ed09e9f0f4404677e4f674252a1d/default/test/mirage/query/run.t
# +++ b/_build/.sandbox/15c2ed09e9f0f4404677e4f674252a1d/default/test/mirage/query/run.t.corrected
# @@ -36,7 +36,7 @@ Query opam file
#      "opam-monorepo" { build & >= "0.3.2" }
#    ]
#    
# -  x-mirage-opam-lock-location: "mirage/noop-unix.opam.locked"
# +  x-mirage-opam-lock-location: "mirage/noop-macosx.opam.locked"
#    
#    x-mirage-configure: ["sh" "-exc" "mirage configure --no-extra-repo"]
#    
```

Any opinion @TheLortex @samoht on how to address this? In this PR, I'll disable the tests on macos, but in the mirage codebase we should find a more sustainable solution.

**Comment by hannesm** [comment]
would be great to get this merged. If there's anything that needs to be done from my side, please let me know.

**Comment by dinosaure** [comment]
I think it's fine, thanks!

**Pull request merged**
