### PR TITLE
added packages/parany/parany.10.0.2

### PR DESCRIPTION
**Pull request by UnixJunkie**
The parallelization performance is significantly better than in previous versions
(and better on Linux than on Mac/*BSDs).

Also, we don't depend on ocamlnet anymore.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
do not merge, I have a bug fix in v10.0.1 already...

**Comment by UnixJunkie** [comment]
It should be OK to merge.
I just corrected the revdeps also.

**Comment by kit-ty-kate** [comment]
Your package fails to build with OCaml < 4.04. Is this intended?
```
#=== ERROR while compiling parany.10.0.1 ======================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/UnixJunkie/parany/archive/v10.0.1.tar.gz)
# path                 ~/.opam/4.03/.opam-switch/build/parany.10.0.1
# command              ~/.opam/4.03/bin/dune build -p parany -j 72
# exit-code            1
# env-file             ~/.opam/log/parany-23-442377.env
# output-file          ~/.opam/log/parany-23-442377.out
### output ###
#     ocamldep src/.parany.objs/parany.ml.d (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamldep.opt -modules -impl src/parany.ml) > _build/default/src/.parany.objs/parany.ml.d
# File "src/parany.ml", line 37, characters 14-15:
# Error: Syntax error
```

**Comment by UnixJunkie** [comment]
I'll correct this.

**Comment by UnixJunkie** [comment]
I re-tagged to 10.0.2.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
