### PR TITLE
Add jasmin.2023.06.1

### PR DESCRIPTION
**Pull request by vbgl**
https://github.com/jasmin-lang/jasmin/releases/tag/v2023.06.1

### CODE REVIEW

**Comment by avsm** [comment]
There seem to be a lot of build failures on non-Debian distributions (like Fedora 38), but I've not had a chance to triage further.

**Comment by vbgl** [comment]
I don’t see any build failure. Some dependencies may fail (e.g., apron or ppl), but that’s unrelated.

**Comment by mseri** [comment]
Indeed, the few failures are due to some dependencies failing to build.
The rest looks good, I am going to merge, thanks

**Comment by vbgl** [comment]
Thanks.

**Pull request merged**
