### PR TITLE
Restore ocamlmpi

### PR DESCRIPTION
**Pull request by tbrk**

### CODE REVIEW

**Comment by tbrk** [comment]
The failure seems to be due to the fact that manual intervention is required to install a required library:
```
The following command needs to be run through "sudo":
    apk add m4 openmpi-dev
```
I'm not sure that I can do a lot about that from my end.

**Comment by mseri** [comment]
One failure I think is una oidable, due to the lack of openmpi-dev in the alpine cersion used by the ocaml CI:
```
ERROR: unsatisfiable constraints:
  openmpi-dev (missing):
```

The one in Travis seems more serious though:
```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[mpi: make all] Command started
+ make "all" "opt" "MPIINCDIR=" "MPILIBDIR=" "MPICC=mpicc" "MPIRUN=mpirun" (CWD=/home/travis/.opam/system/build/mpi.1.03)
- gcc -I`ocamlc -where` -I -O2 -g -Wall   -c -o init.o init.c
- init.c:18:17: fatal error: mpi.h: No such file or directory
-  #include <mpi.h>
-                  ^
- compilation terminated.
- make: *** [init.o] Error 1
[ERROR] The compilation of mpi failed at "make all opt MPIINCDIR= MPILIBDIR=
        MPICC=mpicc MPIRUN=mpirun".
[mpi: make uninstall] Command started
+ make "uninstall" (CWD=/home/travis/.opam/system/build/mpi.1.03)
- ocamlfind remove mpi
- ocamlfind: [WARNING] No such file: /home/travis/.opam/system/lib/mpi/META
#=== ERROR while installing mpi.1.03 ==========================================#
# opam-version 1.2.2
# os           linux
# command      make all opt MPIINCDIR= MPILIBDIR= MPICC=mpicc MPIRUN=mpirun
# path         /home/travis/.opam/system/build/mpi.1.03
# compiler     system (4.06.1)
# exit-code    2
# env-file     /home/travis/.opam/system/build/mpi.1.03/mpi-14657-a00279.env
# stdout-file  /home/travis/.opam/system/build/mpi.1.03/mpi-14657-a00279.out
# stderr-file  /home/travis/.opam/system/build/mpi.1.03/mpi-14657-a00279.err
### stdout ###
# gcc -I`ocamlc -where` -I -O2 -g -Wall   -c -o init.o init.c
### stderr ###
# init.c:18:17: fatal error: mpi.h: No such file or directory
#  #include <mpi.h>
#                  ^
# compilation terminated.
# make: *** [init.o] Error 1
```

**Comment by tbrk** [comment]
You're right @mseri, I missed that. Thanks. Somehow `conf-mpi` is not setting `includedir` and `libdir` properly on ubuntu. I'll try to figure out why tomorrow.

**Comment by tbrk** [comment]
Awaiting accept of #12344 before retesting.

**Comment by tbrk** [comment]
I think it looks a bit better now (maybe more thanks to updates to the CI than to the package?).

**Comment by kit-ty-kate** [comment]
Looks ok. Thanks a lot!

**Comment by tbrk** [comment]
Great. Thanks for the merge.

**Pull request merged**
