### PR TITLE
modelica_ml.0.2.0 - via opam-publish

### PR DESCRIPTION
**Pull request by choeger**
Modelica abstract syntax and parser

Modelica.ml is a Modelica frontend implemented in OCaml.
It is written with compilation in mind, but should also be
useful for other applications.

Currently, abstract syntax, parsing, pretty printing and
a form of lookup analysis are implemented. Patches welcome!
---
* Homepage: https://github.com/choeger/modelica.ml
* Source repo: https://github.com/choeger/modelica.ml.git
* Bug tracker: https://github.com/choeger/modelica.ml/issues

---
Pull-request generated by opam-publish v0.2.1

### CODE REVIEW

**Comment by yallop** [comment]
Closing and reopening to persuade Travis to build this.

**Comment by dsheets** [comment]
It looks like there are some missing dependencies:

```
# E: Cannot find findlib package ocamlgraph
# E: Cannot find findlib package ppx_deriving_yojson
# E: Cannot find findlib package ppx_import
# E: Cannot find findlib package ppx_monadic
```

**Comment by choeger** [comment]
I fixed the opam files. Shall I run opam-publish again, or can you re-check this pull-request?

**Comment by choeger** [comment]
Nevermind. Just noted, that to do so, I would have to update the files in my fork manually.

**Pull request closed without merging**
