### PR TITLE
merlin v3.1.0

### PR DESCRIPTION
**Pull request by trefis**
CHANGELOG extract:

  - backend
    + new "polarity search" feature: provides a Hoogle-like type-based search
      for libraries that are in merlin's scope.
      See https://github.com/ocaml/merlin/blob/master/doc/features.md#polarity-search
    + new "open refactoring" feature: helps cleaning the code in the scope of an
      open statement.
      See https://github.com/ocaml/merlin/blob/master/doc/features.md#open-refactoring
    + spell-checking: a simple spell-checker has been added to suggest
      corrections when nothing can be directly completed.
    + type-driven record completion: merlin will now make use of type
      information from the context for narrowing and refining completion
      candidates.
    + support for `#require` directive in a source file, and will treat it as a
      package use
    + Add support for OCaml 4.07
    + locate: various minor bugfixes, as well as the following general
      improvements:
      - improved context detection
      - better tracking of namespaces
      - fixed support for local bindings
      - fixed support of disambiguated record fields and variant constructors
      - improved support for functors: merlin will now jump through functor
        application to the functor definitions and in some cases go back to the
        argument that was given (if it is simply reexported).
    + backport fixes of OCaml 4.06.1 to the 4.06 backend
    + various minor bugfixes

  - editor modes
    + emacs
      - proper handling of multibyte strings
      - bind "q" to close type buffer
      - make goto-point encoding independent
      - add reason-mode to the guessed favorite mode list
      - sped up some tight loops
      - add support for x-ref backend
    + vim
      - fix support for Neomake
      - fix encoding issues in filepaths
      - fix handling of enclosing-type cache
      - add <silent> to prevent flashing when highlighting an enclosing

### CODE REVIEW

**Comment by mseri** [comment]
The CI issue is unrelated. What worries me is the CI failure:
```
====== Installing package ======
The following dependencies couldn't be met:
  - merlin -> cram
Your request can't be satisfied:
  - No package named cram found.
```

**Comment by kit-ty-kate** [comment]
It seems to require the unreleased: https://github.com/realworldocaml/ocaml-cram

**Comment by trefis** [comment]
That's right.
My hope was that since it's used only for tests I could leave this in (so that when cram appears on the repo, then ocamllabs ci will magically start running tests or something), but I'm happy to remove it if it poses problem.

**Comment by kit-ty-kate** [comment]
@trefis gave me permission to disable tests until `cram` is released. Let's see if everything passes (it should) and I'll merge it afterwards)

**Pull request merged**
