### PR TITLE
added ppx_meta_conv.2.0.2

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
I do not understand why commit f444962 is included in my PR...

**Comment by camlspotter** [comment]
Oops. travis initialization failuire.

**Comment by yallop** [comment]
I've restarted the jobs.

**Comment by camlspotter** [comment]
Installation failure of ppx_deriving 2.2, not ppx_meta_conv itself

```
=-=-= Installing ppx_deriving.2.2 =-=-=
ppx_deriving.2.2 Downloading https://github.com/whitequark/ppx_deriving/archive/v2.2.tar.gz
[ERROR] global-config does not define the variable version.
```

**Comment by yataketa9056** [comment]
Oh, CI init failure again. Too lot.

**Comment by camlspotter** [comment]
CI init failure again.  Too often... :-(

**Comment by AltGr** [comment]
Please use `git rebase -i origin/master` to get rid of the unwanted commit. Thanks!

**Comment by camlspotter** [comment]
@AltGR thanks, I do it.

**Comment by camlspotter** [comment]
Geez something screwed.

**Pull request closed without merging**
