### PR TITLE
3 packages from gitlab.inria.fr/fpottier/menhir/-/archive/20230608/archive.tar.gz

### PR DESCRIPTION
**Pull request by fpottier**
This pull-request concerns:
- `menhir.20230608`: An LR(1) parser generator
- `menhirLib.20230608`: Runtime support library for parsers generated by Menhir
- `menhirSdk.20230608`: Compile-time library for auxiliary tools related to
  Menhir

---
* Homepage: http://gitlab.inria.fr/fpottier/menhir
* Source repo: git+https://gitlab.inria.fr/fpottier/menhir.git
* Bug tracker: https://gitlab.inria.fr/fpottier/menhir/-/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by fpottier** [comment]
Hello! Some checks have failed, but it is not clear to me whether this has anything to do with Menhir.

**Comment by avsm** [comment]
I've triggered a rebuild just to make sure it's not a heisenbug; will try to repro later on.  But it's also an older version of liquidsoap, so not a blocker to merging this PR (just wanted to check it wasn't an unexpected regression).

**Comment by fpottier** [comment]
It seems that `liquidsoap` is built using `dune` when building inside the repository, but is built using `make` once released. In the latter case, `menhir` is invoked without `--infer`. This requires either providing the type of every symbol via `%type` declarations, or restricting to `menhir < 20211230`.

**Comment by fpottier** [comment]
Dear Anil,

The developers have added `%type` declarations on January 3, 2022 (commit `073e40a1e93f3c294749b28a49667ae5e7911785` and following).

Version 2.0.6 was released in June 2022, yet does *not* have this commit.
Version 2.0.7 does not have it either.
Version 2.1.0 is the first version that has it.

The bottom line is, all versions of `liquidsoap` below 2.1.0 should have the constraint `menhir { < "20211230" }`.

Do you know how to make this change in `opam-repository`? Writing a script to do this is beyond my skills.

**Comment by avsm** [comment]
Thank you for the detective work @fpottier!  I had a look at the constraints, and it seems that menhir was only used by liquidsoap >2.0, and all the other 2.0.x releases have the constraint _except_ for 2.0.6 (which is why it slipped through the constraint solver and got caught in CI).  I've taken the liberty of pushing that one new constraint to this PR, so it should be good to merge now.

You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Comment by fpottier** [comment]
Thanks!

**Pull request merged**
