### PR TITLE
[new release] Add Coq 8.11.1

### PR DESCRIPTION
**Pull request by anton-trunov**
Adapted from the PR https://github.com/ocaml/opam-repository/pull/15764 introducing Coq 8.11.0.

CoqIDE 8.11.1 will be added in a separate PR to avoid holding Coq up in case of issues.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Thanks! Note coq/coq#11178 where it was suggested to disable native-compute on macOS in the opam package. I have no idea whether opam supports system-specific build instructions though!

**Comment by anton-trunov** [comment]
I'm wondering if there is a shorter way to express `"-native-compiler" {os = "macos"} "no" {os = "macos"}`.

**Comment by kit-ty-kate** [comment]
> I'm wondering if there is a shorter way to express `"-native-compiler" {os = "macos"} "no" {os = "macos"}`.

I'm unsure, maybe. But for now i think this will be perfect.

Thanks!

**Comment by anton-trunov** [comment]
@kit-ty-kate Awesome, thank you!

**Comment by anton-trunov** [comment]
FWIW, it turns out that filters work on "per-line" basis, see https://github.com/ocaml/opam/issues/4127

**Pull request merged**
