### PR TITLE
ketrew.3.1.0 - via opam-publish

### PR DESCRIPTION
**Pull request by smondet**
A Workflow Engine for Computational Experiments

Ketrew is:

1. An OCaml library providing an EDSL API to define complex and
convoluted workflows (interdependent steps/programs using a lot of
data, with many parameter variations, running on different hosts with
various schedulers).
2. A client-server application to interact with these workflows. The
engine at heart of the server takes care of orchestrating workflows,
and keeps track of everything that succeeds, fails, or gets lost.
The clients interact with an API and with two user-interfaces: a
terminal-app and a WebUI.

---
* Homepage: http://www.hammerlab.org/docs/ketrew/master/index.html
* Source repo: https://github.com/hammerlab/ketrew.git
* Bug tracker: https://github.com/hammerlab/ketrew/issues

---

Pull-request generated by opam-publish v0.3.4

### CODE REVIEW

**Comment by smondet** [comment]
The error in the [logs](https://ci.ocaml.io/log/saved/docker-build-ca4eb5ceaa9c5023db8c6a1affeb5bb3/eb2218a6dfe3b987024a0ef7348e715a2388cb71) is:

```
# + ocamlfind ocamlc -package sosa,nonstd,docout,pvem,yojson,uri,cohttp,ppx_deriving_yojson,ppx_deriving.std,react,reactiveData,threads,pvem_lwt_unix,cmdliner,cohttp.lwt,conduit,dynlink,findlib,lwt.react -bin-annot -thread -short-paths -g -strict-formats -strict-sequence -w +9 -safe-string -bin-annot -for-pack Ketrew -g -I . -I ../pure -c unix_process.mli
# File "unix_process.mli", line 1:
# Error: Corrupted compiled interface
```

I had not seen that one before (?)

**Comment by smondet** [comment]
Heads-up on this one.

Are we waiting on something from us?

Travis is happy:

image

The datakit errors seem to be file-system problems?
(OOC is it the same or similar infrastructure as the DockerHub? I got a bunch of weird failures there also — unrelated to this package though).

**Comment by samoht** [comment]
Any idea what is causing:

```
#=== ERROR while installing ketrew.3.1.0 ======================================#
# command              omake WITH_POSTGRESQL=false
# path                 /home/opam/.opam/ocaml-base-compiler.4.04.0/.opam-switch/build/ketrew.3.1.0
# exit-code            2
# env-file             /home/opam/.opam/log/ketrew-31-d79b75.env
# output-file          /home/opam/.opam/log/ketrew-31-d79b75.out
### output ###
# [...]
# --- Checking if ocamldep understands -modules... (yes)
# - build . _build/style.css
# + Shell.echo("'Building _build/style.css'")
# Building _build/style.css
# - build _build/src/lib command_line.cmo
# + ocamlfind ocamlc -package sosa,nonstd,docout,pvem,yojson,uri,cohttp,ppx_deriving_yojson,ppx_deriving.std,react,reactiveData,threads,pvem_lwt_unix,cmdliner,cohttp.lwt,conduit,dynlink,findlib,lwt.react -bin-annot -thread -short-paths -g -strict-formats -strict-sequence -w +9 -safe-string -bin-annot -for-pack Ketrew -g -I . -I ../pure -c command_line.ml
# File "command_line.ml", line 529, characters 25-33:
# Error: Unbound value env_info
# *** omake: 336/395 targets are up to date
# *** omake: failed (4.53 sec, 77/77 scans, 102/137 rules, 312/342 digests)
# *** omake: targets were not rebuilt because of errors:
#    _build/src/lib/command_line.cmo
```

(see https://ci.ocaml.io/log/saved/docker-build-bb149699cb211a4bb6eaf72d04705018/c845aa8f124a19207d1c44d9ceb567fdf466ed5c)

regarding your question: we are testing much more OS and reverse dependencies on https://ci.ocaml.io than TravisCI does, but that infra is not completely stable yet so we are keeping both systems.

**Comment by smondet** [comment]
@samoht good catch, that one is because it picked an older version of `cmdliner`, adding a constraint now.

**Comment by smondet** [comment]
The one failing says:

```
# + ocamlfind ocamlc -package sosa,nonstd,docout,pvem,yojson,uri,cohttp,ppx_deriving_yojson,ppx_deriving.std,react,reactiveData,js_of_ocaml,js_of_ocaml.ppx,js_of_ocaml.tyxml -bin-annot -thread -short-paths -g -strict-formats -strict-sequence -w +9 -safe-string -g -I . -I ../pure -c reactive_html5.mli
# File "reactive_html5.mli", line 1:
# Error: Corrupted compiled interface
# ../pure/ketrew_pure.cmi
```

**Comment by samoht** [comment]
Not sure what this means ... Merging as it's all green for all other tests.

**Pull request merged**
