### PR TITLE
[new release] current_slack, current_rpc, current_examples, current_docker, current_incr, current_git, current_web, current_github and current (0.5)

### PR DESCRIPTION
**Pull request by talex5**
Slack plugin for OCurrent

- Project page: <a href="https://github.com/ocurrent/ocurrent">https://github.com/ocurrent/ocurrent</a>

##### CHANGES:

Web UI:

- Space and color rows in query page (@MisterDA ocurrent/ocurrent#265).

- Duplicate the Rebuild selected button on top (@MisterDA ocurrent/ocurrent#265).

- Add a 'select-all' checkbox to the query page (@MisterDA ocurrent/ocurrent#265).

- Better printing of job duration (@MisterDA ocurrent/ocurrent#252, @ewanmellor ocurrent/ocurrent#259).

- Speed up rendering of the Query page (@talex5 ocurrent/ocurrent#262).

Windows support:

- Remove RO bit on Windows file when deleting tmpdir (@MisterDA ocurrent/ocurrent#270).

- Use `open_in_bin` instead of `open_in` to open log files (@MisterDA ocurrent/ocurrent#246).

- Support Windows file separators (@MisterDA ocurrent/ocurrent#246).

API:

- GitHub: add `staleness` argument to allow ignoring inactive branches (@patricoferris ocurrent/ocurrent#231).

- GitHub: add `default_ref` to get the default branch name (@patricoferris ocurrent/ocurrent#231).

- Git: expose `Current_git.Local.repo` (@ewanmellor ocurrent/ocurrent#257).
  This means that callers can use this for debugging or labelling.

Other:

- Log a message when cancelling a job finishes (@talex5 ocurrent/ocurrent#261).
  This avoids the confusing situation where the job finishes as you cancel, and you see the success message from the build as the last thing in the log, even though the job actually failed.

- Move ANSI parser to its own repository (@talex5 ocurrent/ocurrent#267, @MisterDA ocurrent/ocurrent#268).
  It's now at https://github.com/ocurrent/ansi

- `current_git` depends on `conf-git` (@MisterDA ocurrent/ocurrent#253).

- Update Dockerfile to latest opam-repository (@ewanmellor ocurrent/ocurrent#251).

- Fix typo in doc-strings (@tatchi ocurrent/ocurrent#250).

- Replace deprecated `Fmt` functions (@MisterDA ocurrent/ocurrent#245).

- Update to latest x509 API changes (@talex5 ocurrent/ocurrent#264).

- Use mirage-crypto for id-of-repo digests (@talex5 ocurrent/ocurrent#243).

### CODE REVIEW

**Comment by talex5** [comment]
The lower-bounds checker did:
```
downgrade seq                     base to 0.2.2
```
I think that caused the failures:
```
#        Type Re.Group.t Stdlib.Seq.t = unit -> Re.Group.t Stdlib.Seq.node
#        is not compatible with type Re__Core.Group.t Seq/1.t
```
Should non-base versions of seq conflict with OCaml >= 4.07?

**Comment by kit-ty-kate** [comment]
The implementation of the `seq` library makes it an alias of `Stdlib.Seq` with OCaml >= 4.07, so this should be correct.
This is failing here because ocurrent uses `(implicit_transitive_deps false)` and `seq` is not part of the explicit dependencies so that causes the compiler to transform `Seq.t` to an abstract type.

I'm not sure what's the best thing to do here. Probably adding:
```
conflicts: [
  "seq" {< "base"} # enforced by (implicit_transitive_deps false)
]
```
should be good. Though maybe the `seq.base` package should install a META file itself

**Comment by talex5** [comment]
OK, I added that. I'll remove the transitive dependencies thing upstream for next time.

**Comment by kit-ty-kate** [comment]
Looks good now. Thanks!

**Pull request merged**
