### PR TITLE
BAP 1.1.0 Release

### PR DESCRIPTION
**Pull request by ivg**
Bug fixes
=========

BinaryAnalysisPlatform/bap#586 segfault with short or damaged files fed to bap.
BinaryAnalysisPlatform/bap#590 llvm 3.8 specific issues
BinaryAnalysisPlatform/bap#592 a bug in lifting x86 PSHUFD/PSHUFB instructions
BinaryAnalysisPlatform/bap#595 bap exit status
BinaryAnalysisPlatform/bap#596 most of the compilation warnings

Features
========

BinaryAnalysisPlatform/bap#593 bapbundle: it is no longer needed to specify the .plugin extension
BinaryAnalysisPlatform/bap#597 API pass will stop processing in case of the error
BinaryAnalysisPlatform/bap#599 print backtraces from passes
BinaryAnalysisPlatform/bap#600 documented memory interface

### CODE REVIEW

**Comment by ivg** [comment]
Heh, we've found a bug, one of the packages is not installable. We will resubmit the PR as soon as the bug is fixed.

**Comment by ivg** [comment]
applied a hotfix, 
Happy holidays!

**Comment by samoht** [comment]
`regular` doesn't seem to work on 4.04:
```
#=== ERROR while installing regular.1.1.0 =====================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/4.04.0/build/regular.1.1.0
# compiler     4.04.0
# exit-code    2
# env-file     /home/travis/.opam/4.04.0/build/regular.1.1.0/regular-18501-56405a.env
# stdout-file  /home/travis/.opam/4.04.0/build/regular.1.1.0/regular-18501-56405a.out
# stderr-file  /home/travis/.opam/4.04.0/build/regular.1.1.0/regular-18501-56405a.err
### stdout ###
# [...]
# /home/travis/.opam/4.04.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -short-paths -package core_kernel -package ppx_jane -pp 'ppx-jane -dump-ast -inline-test-lib bap' -predicates ppx_driver -I lib/regular -o lib/regular/regular_cache.cmo lib/regular/regular_cache.ml
# + /home/travis/.opam/4.04.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -short-paths -package core_kernel -package ppx_jane -pp 'ppx-jane -dump-ast -inline-test-lib bap' -predicates ppx_driver -I lib/regular -o lib/regular/regular_bytes.cmo lib/regular/regular_bytes.ml
# File "lib/regular/regular_bytes.ml", line 1:
# Error: The implementation lib/regular/regular_bytes.ml
#        does not match the interface lib/regular/regular_bytes.cmi:
#        Values do not match:
#          external create : int -> t = "caml_create_bytes"
#        is not included in
#          external create : int -> t = "caml_create_string"
```

**Comment by ivg** [comment]
Yeah, we should add 4.04 to our CI. I've constraint the upper bound so far, we will fix the issue in the next release, see BinaryAnalysisPlatfrom/bap#606.

**Comment by samoht** [comment]
Same issue with regular 1.0.0:

```
31m#===[m [01mERROR[m [01mwhile installing regular.1.0.0[m [31m=====================================#[m
[33m#[m [33mopam-version[m 1.2.2
[33m#[m [33mos[m           linux
[33m#[m [33mcommand[m      make
[33m#[m [33mpath[m         /home/travis/.opam/4.04.0/build/regular.1.0.0
[33m#[m [33mcompiler[m     4.04.0
[33m#[m [33mexit-code[m    2
[33m#[m [33menv-file[m     /home/travis/.opam/4.04.0/build/regular.1.0.0/regular-18484-f33159.env
[33m#[m [33mstdout-file[m  /home/travis/.opam/4.04.0/build/regular.1.0.0/regular-18484-f33159.out
[33m#[m [33mstderr-file[m  /home/travis/.opam/4.04.0/build/regular.1.0.0/regular-18484-f33159.err
[33m### stdout ###
[m[33m# [m[...]
[33m# [mFile "lib/regular/regular_bytes.ml", line 104, characters 2-82:
[33m# [mWarning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
[33m# [mFile "lib/regular/regular_bytes.ml", line 1:
[33m# [mError: The implementation lib/regular/regular_bytes.ml
[33m# [m       does not match the interface lib/regular/regular_bytes.cmi:
[33m# [m       Values do not match:
[33m# [m         external create : int -> t = "caml_create_bytes"
[33m# [m       is not included in
[33m# [m         external create : int -> t = "caml_create_string"
[33m# [mCommand exited with code 2.
[33m### stderr ###
[m[33m# [mmake: *** [build] Error 1
```

**Comment by ivg** [comment]
> Same issue with regular 1.0.0

Yep, regular.1.0.0 was released before the 4.04, I've retrospectively constrained the upper bound.

**Comment by samoht** [comment]
The CI doesn't have the right llvm packages to tests, so merging.

**Pull request merged**
