### PR TITLE
[new release] mirage-crypto-pk, mirage-crypto, mirage-crypto-rng and mirage-crypto-rng-mirage (0.8.3)

### PR DESCRIPTION
**Pull request by hannesm**
CHANGES:

* Fix ppc64le cycle_counter (add missing Val_long) (mirage/mirage-crypto#78 @hannesm)
  - test_entropy is now test_entropy_collection
  - test_entropy checks timer and bootstrap functions
* Avoid polluting symbol table with global non-prefixed symbols
  (reported by @anmonteiro in mirage/mirage-crypto#77, fixed mirage/mirage-crypto#78 @hannesm (suggested by @dinosaure))
* Avoid "caml_" prefix in entropy_stubs, use "mc_" instead (mirage/mirage-crypto#78 @hannesm)

### CODE REVIEW

**Comment by avsm** [comment]
A temporary CI hitch due to overload. @kit-ty-kate is restarting them.

**Comment by hannesm** [comment]
@avsm ok, what should we do with the 0.8.2 release? it may lead to broken execution on ppc64le, would it be fine with you to remove it from opam-repository, or mark it with `available: false`?

**Comment by mseri** [comment]
`available:false` sounds good imo

**Comment by mseri** [comment]
You want to disable them all or only `available: arch != "ppc64"` as done here: https://github.com/ocaml/opam-repository/pull/16873 ?

**Comment by kit-ty-kate** [comment]
I've changed the last commit and done as #16873 did and only disabled in on ppc64. Thanks!

**Pull request merged**
