### PR TITLE
[coq-serapi] New upstream release.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
Travis failing due to: https://github.com/ocaml/opam-repository/pull/11458

**Comment by yomimono** [comment]
I've merged https://github.com/ocaml/opam-repository/pull/11458 and restarted the failing Travis builds.

**Comment by ejgallego** [comment]
Thanks @yomimono ! Indeed Travis now seems OK. Alpine still fails with:

```
# sh: m4: not found
```

but that seems to be the case for PRs depending on `conf-m4`.

**Comment by yomimono** [comment]
Looks fine to me! Congratulations on the release. :)

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
