### PR TITLE
ppx_seq 0.3.1

### PR DESCRIPTION
**Pull request by hyphenrf**
now with range syntax :D

### CODE REVIEW

**Comment by hyphenrf** [comment]
please hold off merge, I'll fix `Option` compat and resubmit

**Comment by hyphenrf** [comment]
btw, is there something that can help me figure out compat matrix as a developer when i can't afford my own ci infra?

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by hyphenrf** [comment]
excellent, always a joy to see that green ✅

wrt ci, I guess a more manual way is to just have a local switch pointing to the lowest bound compiler version and just test on that before releasing. fits my scale fine :P

**Comment by kit-ty-kate** [comment]
the lower-bound can be tested with opam with the opam-0install-cudf solver enabled and a custom criteria (you can look in the logs for the specific criteria).

I’m working on an opam plugin to do all the checking automatically but it’s not ready yet infortunetly: https://github.com/kit-ty-kate/opam-build/pull/2 (I’m hoping to have it fixed and released by next month)

**Pull request merged**
