### PR TITLE
Genprint v0.3

### PR DESCRIPTION
**Pull request by progman1**
library for printing of values vis a vis the ocaml interpreter, but from within compilation units.

### CODE REVIEW

**Comment by progman1** [comment]
is there an alternative to re-submitting the PR when only a checksum needs updating?

**Comment by kit-ty-kate** [comment]
The diff between the two archive is really large:
```
$ diff -qr genprintlib-0.3a genprintlib-0.3
Files genprintlib-0.3a/CHANGES.md and genprintlib-0.3/CHANGES.md differ
Only in genprintlib-0.3: debugger
Files genprintlib-0.3a/README.md and genprintlib-0.3/README.md differ
Files genprintlib-0.3a/src/genprint.cppo.ml and genprintlib-0.3/src/genprint.cppo.ml differ
Files genprintlib-0.3a/src/genprint.mli and genprintlib-0.3/src/genprint.mli differ
Files genprintlib-0.3a/src/genprintval.ml-10 and genprintlib-0.3/src/genprintval.ml-10 differ
Files genprintlib-0.3a/src/ppx_genprint.cppo.ml and genprintlib-0.3/src/ppx_genprint.cppo.ml differ

$ diff -ru genprintlib-0.3a genprintlib-0.3 | wc -l
862
```
Could you please say why those files do not change the behaviour of this version of your program?
If the behaviour changes please publish a new version (e.g. `0.4`) instead.

**Comment by progman1** [comment]
there never was an installable version of v0.3 on opam
due to checksum issue. so I have continued to develop.
it wouldn't make any sense to go to 0.4 without a 0.3 release.

**Comment by progman1** [comment]
which is a question in addition to the one above: why does the release mechanism pass
a release whose checksum is wrong?

**Comment by kit-ty-kate** [comment]
> there never was an installable version of v0.3 on opam due to checksum issue. so I have continued to develop. it wouldn't make any sense to go to 0.4 without a 0.3 release.

Sorry but `genprint.0.3` **is** installable:
```
The following actions will be performed:
  - install genprint 0.3

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[genprint.0.3] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed genprint.0.3
Done.
```

**Comment by progman1** [comment]
you can see I am having problems with this.
I did test install and it failed with a checksum error.
I will make a v0.4 release as you wsh.
but how about helping me out with my question?
re: is there a way to update the checksum without creating another PR?
thanks

**Comment by kit-ty-kate** [comment]
> you can see I am having problems with this. I did test install and it failed with a checksum error.

This is surprising. What is the output of `opam remote` and `opam pin`?

> re: is there a way to update the checksum without creating another PR?

The checksum is here to make sure releases stay the same. In rare cases (e.g. github changing the archive when renaming a repository for example) it can be changed but only if nothing significant has changed in the archive.

I'm not sure to understand what you mean by `without creating another PR`. `opam-repository` is a git repository and cannot be changed without one of us maintainers merging a PR or committing a change. If you wish to update a checksum you need to create a PR and give a good reason as stated above.

**Pull request closed without merging**
