### PR TITLE
[new release] passage (0.1.2)

### PR DESCRIPTION
**Pull request by thatportugueseguy**
Passage - used to store and manage access to shared secrets

- Project page: <a href="https://github.com/ahrefs/passage">https://github.com/ahrefs/passage</a>

##### CHANGES:

- Update test config and add opam ci exclusions

### CODE REVIEW

**Comment by mseri** [comment]
Looks all right. I'll try to re-run the builds in which the CI disconnected.

Do you know why x86_32 fails with
```
#=== ERROR while compiling passage.0.1.2 ======================================#
# context              2.3.0~alpha~dev | linux/x86_32 | ocaml-base-compiler.4.14.2 | pinned(https://github.com/ahrefs/passage/releases/download/0.1.2/passage-0.1.2.tbz)
# path                 ~/.opam/4.14/.opam-switch/build/passage.0.1.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p passage -j 255 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/passage-7-7ff922.env
# output-file          ~/.opam/log/passage-7-7ff922.out
### output ###
# File "lib_test/dune", line 10, characters 1-15:
# 10 |  (inline_tests)
#       ^^^^^^^^^^^^^^
# (cd _build/.sandbox/a28aa5aee5cdcc4da0c0e007ecdeab9b/default/lib_test && .passage_test.inline-tests/inline_test_runner_passage_test.exe inline-test-runner passage_test -source-tree-root .. -diff-cmd -)
# Fatal error: exception File "network.ml", line 3, characters 9-15: Assertion failed
# Raised at Devkit_core__Network in file "network.ml", line 3, characters 9-36
```
?

**Comment by mseri** [comment]
If the rest of the library is usable, that's all right. I think it may be worth adding an error message in devkit instead of abruptly failing though.

**Comment by mseri** [comment]
Thanks

**Comment by thatportugueseguy** [comment]
> I think it may be worth adding an error message in devkit instead of abruptly failing though.

Makes sense, will see to it 👌

**Pull request merged**
