### PR TITLE
added unmagic.1.0.2

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by avsm** [comment]
```
#=== ERROR while installing unmagic.1.0.2 =====================================#
# opam-version 1.2.2
# os           linux
# command      ocaml setup.ml -build
# path         /home/travis/.opam/4.04.0/build/unmagic.1.0.2
# compiler     4.04.0
# exit-code    1
# env-file     /home/travis/.opam/4.04.0/build/unmagic.1.0.2/unmagic-13758-d4bb2a.env
# stdout-file  /home/travis/.opam/4.04.0/build/unmagic.1.0.2/unmagic-13758-d4bb2a.out
# stderr-file  /home/travis/.opam/4.04.0/build/unmagic.1.0.2/unmagic-13758-d4bb2a.err
### stdout ###
# *** omake: reading OMakefiles
# --- Checking for ocamlfind... (found /home/travis/.opam/4.04.0/bin/ocamlfind)
# --- Checking for ocamlc.opt... (found /home/travis/.opam/4.04.0/bin/ocamlc.opt)
# --- Checking for ocamlopt.opt... (found /home/travis/.opam/4.04.0/bin/ocamlopt.opt)
# --- Checking for ocamldep.opt... (found /home/travis/.opam/4.04.0/bin/ocamldep.opt)
# --- Checking for ocamllex.opt... (found /home/travis/.opam/4.04.0/bin/ocamllex.opt)
# --- Checking whether ocamlc understands the "z" warnings... (yes)
# --- Checking whether ocamlopt can create cmxs plugins... (yes)
### stderr ###
# File OMyMakefile: line 239, characters 3-26:
# [...]
#    This expression should use a => binding.
# File OMyMakefile: line 753, characters 6-34:
#    Warning: old-style foreach expression.
#    This expression should use a => binding.
# PREFIX=/home/travis/.opam/4.04.0
# *** omake error:
#    File src/OMakefile: line 13, characters 0-36
#    unbound variable: global.MyOCamlfindInstall
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; unset OCAMLPARAM; omake\"' terminated with error code 123")
```

**Comment by camlspotter** [comment]
Something get pretty wrong in hg repo...

**Comment by camlspotter** [comment]
This is because I made one branch named 1.0.2 and one tag named 1.0.2.  The download URL points to branch 1.0.2, which is old.  It must download tag 1.0.2.  Trying to find how to remove the branch from bitbucket completely.

**Comment by camlspotter** [comment]
Now hit by the issue between Jane and ppx_deriving

**Comment by avsm** [comment]
looks good now, thanks!

**Pull request merged**
