### PR TITLE
Add gapi-ocaml 0.4.5 and google-drive-ocamlfuse 0.7.31

### PR DESCRIPTION
**Pull request by astrada**

### CODE REVIEW

**Comment by mseri** [comment]
Looks like it fails to link when compiled with ocaml 5.1. It works fine with ocaml 4.14

**Comment by astrada** [comment]
Yes, the problem is caused by camlidl 1.11. It should be fixed in version 1.12 that is still not on opam.

**Comment by mseri** [comment]
Should we mark camlidl 1.11 as not available on ocaml 5 in the meantime?

**Comment by astrada** [comment]
Yes, I think it's a good idea. It needs pull request xavierleroy/camlidl#25 to work with OCaml 5.

**Comment by mseri** [comment]
Looks like the release was there already, but never sent here. I opened a PR

**Comment by astrada** [comment]
OK, I'm converting this to draft, because I have to cut another release because I had a test that tried to modify a string.

**Comment by astrada** [comment]
Now I have failures only on lower-bounds checks with OCaml 5.0 and 5.1. Is there a way to express different lower bounds for dependencies based on current OCaml version?

**Comment by astrada** [comment]
If it's not possible, I think it's good to merge. Thanks!

**Comment by avsm** [comment]
@astrada what's the lower bound you're trying to describe? We can try to describe it with a &| formula

**Comment by astrada** [comment]
I'd like to set camlidl >= 1.12 if OCaml version >= 5.0 and similarly a version of ocurl that compiles with OCaml >= 5.0. Thanks!

**Comment by mseri** [comment]
I need to add lower bounds to previous camlidl versions, then I’ll check ocurl

**Comment by astrada** [comment]
Thanks a lot!

**Comment by mseri** [comment]
The remaining failures are CI or ocurl issues. The only one still relevant for this package are the multiple failures on macos (all compiler versions). Are these expected?
```
#=== ERROR while compiling gapi-ocaml.0.4.5 ===================================#
# context              2.2.0~alpha2 | macos/x86_64 | ocaml-base-compiler.4.14.1 | pinned(https://github.com/astrada/gapi-ocaml/archive/v0.4.5-opam.tar.gz)
# path                 ~/.opam/4.14.1/.opam-switch/build/gapi-ocaml.0.4.5
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p gapi-ocaml -j 11
# exit-code            1
# env-file             ~/.opam/log/gapi-ocaml-60690-214820.env
# output-file          ~/.opam/log/gapi-ocaml-60690-214820.out
### output ###
# File "src/netsys/dune", line 6, characters 92-110:
# 6 |  (foreign_stubs (language c) (names netsys_c netsys_c_clock netsys_c_event netsys_c_fadvise netsys_c_fallocate netsys_c_gprof netsys_c_htab netsys_c_ioprio netsys_c_ip6 netsys_c_locale netsys_c_mem netsys_c_multicast netsys_c_poll netsys_c_queue netsys_c_sem netsys_c_shm netsys_c_spawn netsys_c_subprocess netsys_c_syslog netsys_c_win32 netsys_c_xdr))
#                                                                                                 ^^^^^^^^^^^^^^^^^^
# (cd _build/default/src/netsys && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -pthread -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -g -I /Users/mac1000/.opam/4.14.1/lib/ocaml -o netsys_c_fallocate.o -c netsys_c_fallocate.c)
# netsys_c_fallocate.c:38:9: error: call to undeclared function 'posix_fallocate'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
#     r = posix_fallocate(Int_val(fd), start_off, len_off);
#         ^
# netsys_c_fallocate.c:38:9: note: did you mean 'netsys_fallocate'?
# netsys_c_fallocate.c:20:16: note: 'netsys_fallocate' declared here
# CAMLprim value netsys_fallocate(value fd, value start, value len) {
#                ^
# 1 error generated.
# File "src/netsys/dune", line 6, characters 45-59:
# 6 |  (foreign_stubs (language c) (names netsys_c netsys_c_clock netsys_c_event netsys_c_fadvise netsys_c_fallocate netsys_c_gprof netsys_c_htab netsys_c_ioprio netsys_c_ip6 netsys_c_locale netsys_c_mem netsys_c_multicast netsys_c_poll netsys_c_queue netsys_c_sem netsys_c_shm netsys_c_spawn netsys_c_subprocess netsys_c_syslog netsys_c_win32 netsys_c_xdr))
#                                                  ^^^^^^^^^^^^^^
# (cd _build/default/src/netsys && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -pthread -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -g -I /Users/mac1000/.opam/4.14.1/lib/ocaml -o netsys_c_clock.o -c netsys_c_clock.c)
# netsys_c_clock.c:14:10: fatal error: 'sys/timerfd.h' file not found
# #include <sys/timerfd.h>
#          ^~~~~~~~~~~~~~~
# 1 error generated.
# File "src/netsys/dune", line 6, characters 60-74:
# 6 |  (foreign_stubs (language c) (names netsys_c netsys_c_clock netsys_c_event netsys_c_fadvise netsys_c_fallocate netsys_c_gprof netsys_c_htab netsys_c_ioprio netsys_c_ip6 netsys_c_locale netsys_c_mem netsys_c_multicast netsys_c_poll netsys_c_queue netsys_c_sem netsys_c_shm netsys_c_spawn netsys_c_subprocess netsys_c_syslog netsys_c_win32 netsys_c_xdr))
#                                                                 ^^^^^^^^^^^^^^
# (cd _build/default/src/netsys && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -pthread -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -g -I /Users/mac1000/.opam/4.14.1/lib/ocaml -o netsys_c_event.o -c netsys_c_event.c)
# netsys_c_event.c:9:10: fatal error: 'sys/eventfd.h' file not found
# #include <sys/eventfd.h>
#          ^~~~~~~~~~~~~~~
# 1 error generated.
# File "src/netsys/dune", line 6, characters 75-91:
# 6 |  (foreign_stubs (language c) (names netsys_c netsys_c_clock netsys_c_event netsys_c_fadvise netsys_c_fallocate netsys_c_gprof netsys_c_htab netsys_c_ioprio netsys_c_ip6 netsys_c_locale netsys_c_mem netsys_c_multicast netsys_c_poll netsys_c_queue netsys_c_sem netsys_c_shm netsys_c_spawn netsys_c_subprocess netsys_c_syslog netsys_c_win32 netsys_c_xdr))
#                                                                                ^^^^^^^^^^^^^^^^
# (cd _build/default/src/netsys && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -pthread -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -g -I /Users/mac1000/.opam/4.14.1/lib/ocaml -o netsys_c_fadvise.o -c netsys_c_fadvise.c)
# netsys_c_fadvise.c:32:31: error: use of undeclared identifier 'POSIX_FADV_NORMAL'
#     case 0: case 6: adv_int = POSIX_FADV_NORMAL; break;
#                               ^
# netsys_c_fadvise.c:33:31: error: use of undeclared identifier 'POSIX_FADV_SEQUENTIAL'
#     case 1: case 7: adv_int = POSIX_FADV_SEQUENTIAL; break;
#                               ^
# netsys_c_fadvise.c:34:31: error: use of undeclared identifier 'POSIX_FADV_RANDOM'
#     case 2: case 8: adv_int = POSIX_FADV_RANDOM; break;
#                               ^
# netsys_c_fadvise.c:35:31: error: use of undeclared identifier 'POSIX_FADV_NOREUSE'
#     case 3: case 9: adv_int = POSIX_FADV_NOREUSE; break;
#                               ^
# netsys_c_fadvise.c:36:32: error: use of undeclared identifier 'POSIX_FADV_WILLNEED'
#     case 4: case 10: adv_int = POSIX_FADV_WILLNEED; break;
#                                ^
# netsys_c_fadvise.c:37:32: error: use of undeclared identifier 'POSIX_FADV_DONTNEED'
#     case 5: case 11: adv_int = POSIX_FADV_DONTNEED; break;
#                                ^
# netsys_c_fadvise.c:52:9: error: call to undeclared function 'posix_fadvise'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
#     r = posix_fadvise(Int_val(fd), start_off, len_off, adv_int);
#         ^
# 7 errors generated.
```

**Comment by astrada** [comment]
Thanks!

> Are these expected?

Yes, I imported what I used from ocamlnet to get rid of the dependency that was blocking the upgrade to OCaml 5. I tried to import the minimum code I needed but there is a lot of C that needs autoconf (that I removed to simplify the build) to be cross platform. And I don't have access to a macos box to test the package. So, it's probably smarter to remove macos from the opam file of gapi-ocaml.

**Comment by mseri** [comment]
The remaining failures show that we need some bounds on ocurl. I'll do that separately. Thanks

We need to postpone merges for some time but once we can merge again later, I'll marge this

**Comment by astrada** [comment]
Great! Thanks for your support!

**Comment by mseri** [comment]
Thanks, sorry for the wait

**Comment by astrada** [comment]
No problem!

**Pull request merged**
