### PR TITLE
[new release] rfsm (1.6-alpha-3)

### PR DESCRIPTION
**Pull request by jserot**
A toolset for describing and simulating StateChart-like state diagrams

- Project page: <a href="github.com/jserot/rfsm">github.com/jserot/rfsm</a>
- Documentation: <a href="http://jserot.github.io/rfsm">http://jserot.github.io/rfsm</a>

### CODE REVIEW

**Comment by jserot** [comment]
Oops. I've forgotten to add `ocamlgraph` to the list of package dependencies :(
How do i fix this (w/o starting another PR) ?

**Comment by jserot** [comment]
Also `lascar (>= 0.6)`...

**Comment by mseri** [comment]
If you used `opam-publish` you should find the clone of the repo with your PR here: `~/.opam/plugins/opam-publish/repos/ocaml%opam-repository` unless you have specified a different folder

**Comment by jserot** [comment]
I used `dune-release`

**Comment by mseri** [comment]
Run this `dune-release opam submit --dry-run -v` and it will show you where the repo is under
```[-] Preparing pull request to ocaml/opam-repository```

**Comment by jserot** [comment]
Ok. Located it. There's a directory `.../opam-repository/packages/rfsm.1.6-alpha-3` there, containing a single `opam` file.
What should i do now ?

**Comment by mseri** [comment]
Modify the opam file with the changes you need, commit the changes and push them to the `jserot:release-rfsm-1.6-alpha-3` branch

**Comment by jserot** [comment]
Ok, changes applied and comitted.

From my local `opam-repository`, `git remote -v` gives:
```
origin	https://github.com/jserot/opam-repository.git (fetch)
origin	https://github.com/jserot/opam-repository.git (push) 
```
Will simply pushing to `origin` be ok or do i have to specify the aforementionned branch ?

**Comment by mseri** [comment]
That should be enough. If it does not work, try `git push origin release-rfsm-1.6-alpha-3`

**Comment by jserot** [comment]
```
$ git push origin
fatal: The current branch release-rfsm-1.6-alpha-3 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin release-rfsm-1.6-alpha-3
```

Ok.

```
$ git push --set-upstream origin release-rfsm-1.6-alpha-3
To https://github.com/jserot/opam-repository.git
 ! [rejected]              release-rfsm-1.6-alpha-3 -> release-rfsm-1.6-alpha-3 (non-fast-forward)
error: failed to push some refs to 'https://github.com/jserot/opam-repository.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

`git` is just driving me crazy...

**Comment by mseri** [comment]
Mmh, I would need access to check. 

But I got an idea: you can click on `Files changes` on this PR page, click on the `...` on the corner of the file preview, and `Edit`. This will allow to edit the file and commit straight from the web interface

**Comment by jserot** [comment]
Ok. Done. Let's see if it solves the problem.
Otherwise, i will close this PR, fix my local repo and re-open a new PR with dune-release..

**Comment by jserot** [comment]
Thx for the typo fix. Seems I'm getting tired ;-)

**Comment by mseri** [comment]
Thanks! Seems to be working

**Comment by kit-ty-kate** [comment]
This version didn't have the right format for an alpha package. It should've been `1.6~alpha-3` (the tilde positions it before 1.6 and not after as it is currently the case

**Comment by mseri** [comment]
Should we rename it?

**Comment by mseri** [comment]
Or promote 1.6 to 1.7 instead?

**Pull request merged**
