### PR TITLE
ppx_blob.0.2: Required for compatibility with 4.03, but also works with 4.02

### PR DESCRIPTION
**Pull request by johnwhitington**
This is a new version of ppx_blob which works with the upcoming 4.03. But is also works for 4.02 (the changes in the parse tree have been abstracted by relying on ppx_tools). This is the work of Anton Bachin.

Forgive me for presenting this as a manual pull request yet again, but I still can't get the pin-based testing workflow (and thus opam-publish) to work. It seems to try to install the old (v0.1) version...

```
feast:ppx_blob.0.2 john$ opam pin add ppx_blob .
[NOTE] Package ppx_blob is already path-pinned to
       /Users/john/repos/opam-repository/packages/ppx_blob/ppx_blob.0.2.
       This will erase any previous custom definition.
Proceed ? [Y/n] Y

[ppx_blob] /Users/john/repos/opam-repository/packages/ppx_blob/ppx_blob.0.2/ synchronized
[ppx_blob] Installing new package description from
/Users/john/repos/opam-repository/packages/ppx_blob/ppx_blob.0.2

ppx_blob needs to be installed.
The following actions will be performed:
  ∗  install ppx_blob 0.1*
Do you want to continue ? [Y/n] n
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

### CODE REVIEW

**Comment by samoht** [comment]
```
[ERROR] Bad checksum for
        /home/travis/.opam/packages.dev/ppx_blob.0.2/v0.2.tar.gz:
          - 46a9d06b8037ca217fdcc3f2888b04b5 [expected result]
          - c25401923d7e6efe6af400f1100c7923 [actual result]
        This may be fixed by running `opam update`.
```

**Comment by johnwhitington** [comment]
Thanks. Fixed. I have no idea why this occurs. I calculated the md5 from the v0.2 .gz before.

**Comment by yallop** [comment]
There's [apparently](https://travis-ci.org/ocaml/opam-repository/jobs/124814574) a missing dependency on `ppx_tools`:

```
### stderr ###
# ocamlfind: Package `ppx_tools' not found
# make[1]: *** [ppx_blob.cmx] Error 2
# make: *** [native-code] Error 2
```

**Comment by johnwhitington** [comment]
Thanks. Done. I also updated the file to include the 'name' and 'version' fields.

**Comment by yallop** [comment]
Thanks!

**Pull request merged**
