### PR TITLE
Add package for Lambdoc 1.0-beta3

### PR DESCRIPTION
**Pull request by darioteixeira**

### CODE REVIEW

**Comment by darioteixeira** [comment]
Hmm, OPAM does not like the contents of the `lambdoc.install` file.  The syntax seems correct -- or am I missing something?

**Comment by avsm** [comment]
Possibly because they're directories? Not sure. Most of the testing infrastructure is down due to the ongoing GitHub DDOS atm :-/

**Comment by darioteixeira** [comment]
Yeah, I thought about the directory thingy, but figured OPAM would be smart enough to tell.  Oh well, it might be nothing.  Let us indeed wait for the DDoS to end...

**Comment by AltGr** [comment]
.install doesn't allow directories at the moment; see https://github.com/ocaml/opam/issues/1428

**Comment by darioteixeira** [comment]
@AltGr: Okay, mystery solved.  Quick question: if I were to put in `lambdoc.install` the relative paths of all the files, would OPAM reconstruct the directory structure based on those paths?  In other words, can I just put in `lambdoc.install` the contents of `find css examples -type f`?

**Comment by dbuenzli** [comment]
@darioteixeira yes. See "General remarks" here http://opam.ocaml.org/doc/manual/dev-manual.html#sec25

**Pull request merged**
