### PR TITLE
Websocket 0.9.3.

### PR DESCRIPTION
**Pull request by vbmithr**

### CODE REVIEW

**Comment by avsm** [comment]
Hm, it selected cohttp.0.12 and failed:
```
#=== ERROR while installing websocket.0.9.3 ===================================#
# opam-version 1.2.0
# os           linux
# command      make
# path         /home/travis/.opam/system/build/websocket.0.9.3
# compiler     system (4.02.1)
# exit-code    2
# env-file     /home/travis/.opam/system/build/websocket.0.9.3/websocket-18205-4345db.env
# stdout-file  /home/travis/.opam/system/build/websocket.0.9.3/websocket-18205-4345db.out
# stderr-file  /home/travis/.opam/system/build/websocket.0.9.3/websocket-18205-4345db.err
### stdout ###
# ocaml pkg/build.ml native=true native-dynlink=true
# ocamlfind ocamldep -package lwt -package lwt.ppx -package tls.lwt -package uri -package cohttp.lwt -modules tests/wscat.ml > tests/wscat.ml.depends
# + ocamlfind ocamldep -package lwt -package lwt.ppx -package tls.lwt -package uri -package cohttp.lwt -modules tests/wscat.ml > tests/wscat.ml.depends
# ocamlfind: Package `cohttp.lwt' not found
# Command exited with code 2.
### stderr ###
# make: *** [build] Error 10
```

Up the version constraint to 0.14.0? That addressed the cohttp.lwt selection. Wonder why the constraint solver picked the older Cohttp though..

**Comment by vbmithr** [comment]
On 24/03/2015 09:15, Anil Madhavapeddy wrote:
> Up the version constraint to 0.14.0? That addressed the cohttp.lwt
> selection. Wonder why the constraint solver picked the older Cohttp though..

I can do that, but this solver issue is really worrying nevertheless.

-- 
Vincent

**Comment by avsm** [comment]
@AltGr @samoht can you spot anything in the Travis log for why an older Cohttp was selected?  This should be normal aspcud and non 4.02.1 seem to be fine.

**Comment by samoht** [comment]
maybe related to tls and conduit co-instability? Do you have the latest changes in your repo @vbmithr? Otherwise who knows what the solver thinks ...

**Comment by vbmithr** [comment]
On 24/03/2015 11:44, Thomas Gazagnaire wrote:
> Do you have the latest changes in your repo @vbmithr
> 

Not sure what you mean by that. Added constraints in ocaml-websocket.

-- 
Vincent

**Comment by dbuenzli** [comment]
Le mardi, 24 mars 2015 à 13:34, Vincent Bernardoff a écrit :
> Not sure what you mean by that. Added constraints in ocaml-websocket.

`opam update` I guess.  

Daniel

**Comment by avsm** [comment]
Everything seems ok. I'll merge and run some checks on iocaml to see if any solver oddnesses come up.

**Comment by samoht** [comment]
@avsm The solver is always right :p 

```
$ opam install cohttp.0.15.2 tls.0.4.0
[NOTE] Package tls is already installed (current version is 0.4.0).
The following dependencies couldn't be met:
  - cohttp -> conduit >= 0.7.0
Your request can't be satisfied:
  - conduit.0.7.0 is in conflict with tls.0.4.0
  - conduit.0.7.1 is in conflict with tls.0.4.0
  - conduit.0.7.2 is in conflict with tls.0.4.0

No solution found, exiting
```

**Comment by samoht** [comment]
@avsm and the PR you've just merged just adds a uninstallable package!

**Comment by avsm** [comment]
Ah yes, I have a conduit pin here that snuck in. Sigh...

**Comment by avsm** [comment]
Not a big problem though -- the conduit 0.8 release will make it installable again, and it shouldn't break anything now.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/3818

**Pull request merged**
