### PR TITLE
Package cfml.20211215

### PR DESCRIPTION
**Pull request by fpottier**
### `cfml.20211215`
The CFML program verification tool

---
* Homepage: https://gitlab.inria.fr/charguer/cfml2
* Source repo: git+https://gitlab.inria.fr/charguer/cfml2.git
* Bug tracker: https://gitlab.inria.fr/charguer/cfml2/-/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The opam file seems to be missing in the upstream repository. This makes dune fail:
```
#=== ERROR while compiling cfml.20211215 ======================================#
# context              2.0.10 | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(https://gitlab.inria.fr/charguer/cfml2/-/archive/20211215/archive.tar.gz)
# path                 ~/.opam/4.08/.opam-switch/build/cfml.20211215
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p cfml -j 31
# exit-code            1
# env-file             ~/.opam/log/cfml-3847-0a5907.env
# output-file          ~/.opam/log/cfml-3847-0a5907.out
### output ###
# File "generator/dune", line 32, characters 11-15:
# 32 |   (package cfml)
#                 ^^^^
# Error: You cannot declare items to be installed without adding a
# <package>.opam file at the root of your project.
# To declare elements to be installed as part of package "cfml", add a
# "cfml.opam" file at the root of your project.
# Root of the project as discovered by dune: .
```

**Comment by fpottier** [comment]
My bad, the file `cfml.opam` was mistakenly omitted in the archive. I have fixed the archive and updated the checksums in the PR.

**Comment by kit-ty-kate** [comment]
For the record, just in case you want to fix that in future releases:
```
#=== ERROR while compiling cfml.20211215 ======================================#
# context              2.1.1 | linux/arm32 | ocaml-base-compiler.4.13.1 | pinned(https://gitlab.inria.fr/charguer/cfml2/-/archive/20211215/archive.tar.gz)
# path                 ~/.opam/4.13/.opam-switch/build/cfml.20211215
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p cfml -j 159
# exit-code            1
# env-file             ~/.opam/log/cfml-3548-cc97f5.env
# output-file          ~/.opam/log/cfml-3548-cc97f5.out
### output ###
#     ocamlopt generator/.cfmlc.eobjs/native/dune__exe__Print_type.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.13/bin/ocamlopt.opt -w -40 -g -g -I generator/.cfmlc.eobjs/byte -I generator/.cfmlc.eobjs/native -I /home/opam/.opam/4.13/lib/pprint -intf-suffix .ml -no-alias-deps -open Dune__exe -o generator/.cfmlc.eobjs/native/dune__exe__Print_type.cmx -c -impl generator/print_type.ml)
# File "generator/print_type.ml", line 46, characters 17-28:
# 46 | let used_level = 11111111111
#                       ^^^^^^^^^^^
# Error: Integer literal exceeds the range of representable integers of type int
```

**Comment by fpottier** [comment]
Thanks!

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
