### PR TITLE
[new release] dolmen_type, dolmen_bin, dolmen_loop, dolmen_lsp and dolmen (0.5)

### PR DESCRIPTION
**Pull request by Gbury**
A typechecker for automated deduction languages

- Project page: <a href="https://github.com/Gbury/dolmen">https://github.com/Gbury/dolmen</a>
- Documentation: <a href="http://gbury.github.io/dolmen">http://gbury.github.io/dolmen</a>

### Additions

- Added a functorized typechecker for all language supported by Dolmen
- Added a LSP server for all language ssupported by Dolmen

### CODE REVIEW

**Comment by Gbury** [comment]
I've added stricter bounds on `dolmen` for the `archsat` and `msat` packages (all of which are authored by me).
I've also changed the release (and thus associated commit hash and checksums of release archives) to include a fix for 32-bit architectures.

**Comment by mseri** [comment]
Thank you very much

**Comment by Gbury** [comment]
The new errors actually relate to the `msat` and `archsat` packages that I had to modify, notably:
- linting errors
  - `msat` and `archsat` apparently refers to themselves and it doesn't please the linter
  - `archsat`'s license doesn't respect the license formatting
- `archsat` includes the same code that made `dolmen` fail on 32-bit archs (because it features a `1_000_000_000` constant).

Should I try and fix the linting errors ? The build error of archsat on 32-bit cannot be fixed without a new release, and it is already present in the repo without this PR; is there a way to add a constraint to prevent it from being installed on a 32-bit arch ?

**Comment by mseri** [comment]
There seems not to be an equivalent for `"Apache-1.0+"` in spdx, I would not know what to put there.
If you can fix the licenses lint errors you do us a favour, you can ignore the other lints

**Comment by Gbury** [comment]
The last commit should fix the license format for `archsat`

**Comment by mseri** [comment]
Thanks again!

**Pull request merged**
