### PR TITLE
[new release] atacama (0.0.4)

### PR DESCRIPTION
**Pull request by leostera**
Modern, pure OCaml socket pool for Riot

- Project page: <a href="https://github.com/leostera/atacama">https://github.com/leostera/atacama</a>

## 0.0.4

* Upgrade to Riot 0.0.6
* Introduce benchmarks in Go, Elixir, Erlang, Eio, and Rust
* Refactor Transport/Socket interfaces to reuse buffers
* Add `echo_test` to verify integrity of data
* Add working TCP echo server example

### CODE REVIEW

**Comment by leostera** [comment]
Depends on https://github.com/ocaml/opam-repository/pull/24984

**Comment by arbipher** [comment]
No idea about the four timeout CI cases. Otherwise, it looks good to me to merge.

**Comment by mseri** [comment]
I need to check if I can reproduce the issues locally, mybe something is wrong with kqueue, the library or the tests

**Comment by leostera** [comment]
Hi folks! I'm looking into this :) thanks for the review. I think all dep issues should've been fixed, and I've disabled the I/O test.

**Comment by leostera** [comment]
Looks like the only failing job now is the freebsd kqueue one, which we know from the same failure on the riot PRs 🙌🏼

**Comment by mseri** [comment]
Thanks

**Pull request merged**
