### PR TITLE
camltc: add dev-repo field

### PR DESCRIPTION
**Pull request by aantron**
cc @toolslive

### CODE REVIEW

**Comment by dsheets** [comment]
On 4.03.0:

```
# + ocamlfind ocamlc -g -ccopt -I../3rd-party/tokyocabinet -ccopt -O2 -package lwt.preemptive -package lwt.unix -package lwt -package oUnit -c otc_wrapper.c
# ocamlfind: Error from package `threads': Missing -thread or -vmthread switch
# Command exited with code 2.
# make: Leaving directory `/home/travis/.opam/4.03.0/build/camltc.0.9.2/src'
```

It may be a 4.03 issue or it may be an ocamlbuild 0.9.1 issue.

**Comment by samoht** [comment]
@dsheets I'm tempted to merge the PR anyway as it just update some metadata. 

@aantron or @toolslive if you have time to investigate the breakage with 4.03 and open a new PR with a fix, that'd be great. Thanks!

**Comment by toolslive** [comment]
There'a pending camltc.0.9.3 but I'll have a look at the issues with 4.03

**Comment by dsheets** [comment]
Restricting it to < 4.03.0 would be fine, I think, given the new 0.9.3.

**Comment by aantron** [comment]
I can amend the commit, if @toolslive concurs.

**Comment by toolslive** [comment]
go ahead, I don't mind.

**Comment by toolslive** [comment]
basically the `_tags` file lacks a `true:thread`. I'll update the pull request for camltc.0.9.3

**Comment by yallop** [comment]
I'm merging this now that it's building successfully.  A separate PR with camltc.0.9.3 will be very welcome.

**Comment by toolslive** [comment]
@yallop: #6408

**Pull request merged**
