### PR TITLE
ppx_repr: add ppx_deriving dependency (for non-dune users)

### PR DESCRIPTION
**Pull request by hannesm**
/cc @CraigFe @dinosaure 

see https://github.com/roburio/dns-primary-git/pull/2 https://github.com/mirage/repr/pull/36

### CODE REVIEW

**Comment by hannesm** [comment]
sorry, I'm not sure about the revdeps failure and won't investigate.

**Comment by dinosaure** [comment]
> sorry, I'm not sure about the revdeps failure and won't investigate.

I think it's a missing constraint between `index` and `index-bench` (which should require the `{= version}` constraint). Any idea @CraigFe?

**Comment by CraigFe** [comment]
@dinosaure: agreed. PR here: https://github.com/ocaml/opam-repository/pull/18036

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
