### PR TITLE
tentative to add z3

### PR DESCRIPTION
**Pull request by UnixJunkie**
cd build in the build commands fails while there is a build directory

### CODE REVIEW

**Comment by Drup** [comment]
Your script is broken. I have an almost working script [here](https://github.com/termite-analyser/opam-termite/blob/master/packages/Z3/Z3.dev/opam) but really, z3's ocaml binding is really broken at the moment (you need to set env variables, it's broken for bytecode, for toplevel, ...) so it's pointless to package it for opam.

**Comment by Drup** [comment]
Btw, the reason your package doesn't work is because all the commands executed by opam are done at the root of the build directory, you can't cd to something. If you want to move around, you need to launch a script. In this case you don't need to since `make -C` works fine.

**Comment by UnixJunkie** [comment]
@Drup thanks for the tip

**Comment by UnixJunkie** [comment]
It is easier to update a package than create one from scratch.
If in the future there are new releases of z3, it will be easy to update the url file.

**Comment by Drup** [comment]
> It is easier to update a package than create one from scratch.

Sure, but I did a package already, and mine is more complete. Did you even tried your package ? The ml bindings are not even enabled and the install will try to put things in `/usr/lib/python2.7/site-packages`! Please just use mine for the time being. In the next release of z3, when things are in a better shape, we can add it to the main opam repository.

**Comment by UnixJunkie** [comment]
Where is your package?

**Comment by UnixJunkie** [comment]
Of course I try things.
This package can install and uninstall and there is a z3 executable in the PATH after install.
Which looks like a good start to me.

**Comment by Drup** [comment]
I linked it in my first message, It's here: https://github.com/termite-analyser/opam-termite/blob/master/packages/Z3/Z3.dev/opam

You can add the whole repository in opam and try it.

**Comment by Drup** [comment]
And no, having z3 in the path is useless. We don't want to package z3's binary, we want z3's ml bindings.

Z3 is not an ocaml software, the binary should not be installed through opam.

**Comment by UnixJunkie** [comment]
@Drup will probably contribute a better version of this package some day

**Pull request closed without merging**
