### PR TITLE
crunch.2.0.0: tests need older io-page

### PR DESCRIPTION
**Pull request by avsm**
spotted revdeps for #14001

### CODE REVIEW

**Comment by mseri** [comment]
This fails with
```
#=== ERROR while compiling crunch.2.0.0 =======================================#
# context     2.0.3 | linux/x86_64 | ocaml-base-compiler.4.03.0 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-base-compiler.4.03.0/.opam-switch/build/crunch.2.0.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --pinned false --tests true
# exit-code   1
# env-file    ~/.opam/log/crunch-17127-1c6298.env
# output-file ~/.opam/log/crunch-17127-1c6298.out
### output ###
# ocamlfind ocamlopt -shared -linkall -package 'cmdliner unix' -I src src/crunch.cmxa -o src/crunch.cmxs
# ocamlfind ocamldep -package 'bos cstruct lwt io-page io-page.unix mirage-kv-lwt rresult' -modules test/test.ml > test/test.ml.depends
# + ocamlfind ocamldep -package 'bos cstruct lwt io-page io-page.unix mirage-kv-lwt rresult' -modules test/test.ml > test/test.ml.depends
# ocamlfind: Package `io-page-unix' not found - required by `io-page.unix'
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'src/crunch.a' 'src/crunch.cmxs' 'src/crunch.cmxa'
#      'src/crunch.cma' 'src/crunch.cmx' 'src/crunch.cmi' 'src/crunch.mli'
#      'src/main.native' 'test/test.native']: exited with 10
```

**Comment by avsm** [comment]
This is still installing io-page 2.2.0 despite the conflict line in the PR.

@altgr @rjbou am I misunderstanding how the with-test conflict should work. I'm intending this line:

```
conflicts: [ "io-page" {>="2.0.0" & with-test} ]
```

to prevent an io-page>=2.0.0 to be installed if tests are requested since they fail (but the main package builds fine). But then in the CI, `opam install -t crunch` still installs io-page.2.2.0 with this constraint: https://ci.ocamllabs.io/log/saved/docker-build-551fb1825b8e27caff7c8a82863fd2d8/1c075f902aa40db67dd853635c170bea10505792

**Comment by rjbou** [comment]
I think that `with-test` variable is not resolved at `conflict` handling.
As `io-page` is only needed for test, why don't you directly restrain its version in the `depends` field?

**Comment by avsm** [comment]
ah thanks @rjbou! What's the right syntax for doing it directly?

```
depends: [
 "io-page" {>="1.4.0"}
 "io-page" {>="2.0.0" & with-test}
]
```

i.e. is repeating it ok or is there a combined formula?

I'll create an opam issue for the lack of linting of variables in conflicts -- if it's ignored its confusing if opam accepts the formula silently.

**Comment by rjbou** [comment]
> i.e. is repeating it ok or is there a combined formula?

You can repeat the packages filtering, testing one will only be taken into account with the test option.
But here, you don't need to repeat, no ? There is no other restriction on `io-page` expect with tests...

> I'll create an opam issue for the lack of linting of variables in conflicts -- if it's ignored its confusing if opam accepts the formula silently.

Yes please. Plus when I tested locally with a pin edit, I had a lint warning concerning `run-test` field... Variable check is not well contained.

**Pull request merged**
