### PR TITLE
Package rfsm.1.4

### PR DESCRIPTION
**Pull request by jserot**
### `rfsm.1.4`
A toolset for describing and simulating StateChart-like state diagrams

---
* Homepage: http://cloud.ip.uca.fr/~serot/rfsm/
* Source repo: git://github.com/jserot/rfsm.git
* Bug tracker: jocelyn.serot@uca.fr

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This package doesn't have a `url` section. Also the `remove` section is not necessary since opam 2.0 if it only removes files that have been installed

**Comment by jserot** [comment]
In a previous [PR](https://github.com/ocaml/opam-repository/pull/13789), @mseri indicated that the URL section was not necessary as soon as a release with a matching tag can be found on `github` - which is the case [here](https://github.com/jserot/rfsm/releases).

**Comment by mseri** [comment]
That is not what I meant: I meant that the local opam file in the repository should not need one because in the case of a properly tagged repository `opam-publish` should be smart enough to add the correct url/hash field to the pull request. But it looks like it failed again to do it.

**Comment by jserot** [comment]
Ok. I've added (resp. suppressed) the `url` (resp. `remove`) section in the `.opam` file and resubmitted.

**Comment by mseri** [comment]
Thanks. The CI failure is only due to missing pandoc on the CI image:
```
- make[1]: Leaving directory '/home/opam/.opam/4.07/.opam-switch/build/rfsm.1.4/src/lib'
- rm -f doc/lib/*
- cp src/lib/rfsm.docdir/* doc/lib
- (cd doc/um; make; cp rfsm.pdf ..)
- make[1]: Entering directory '/home/opam/.opam/4.07/.opam-switch/build/rfsm.1.4/doc/um'
- pdflatex rfsm.tex > pdflatex.log
- /bin/sh: 1: pdflatex: not found
- Makefile:6: recipe for target 'rfsm.pdf' failed
- make[1]: *** [rfsm.pdf] Error 127
- make[1]: Leaving directory '/home/opam/.opam/4.07/.opam-switch/build/rfsm.1.4/doc/um'
- cp: cannot stat 'rfsm.pdf': No such file or directory
- Makefile:77: recipe for target 'opam-doc' failed
- make: *** [opam-doc] Error 1
[ERROR] The compilation of rfsm failed at "/usr/bin/make opam".
```

It should be fixable by adding `"conf-pandoc"` as a build dependency

**Comment by jserot** [comment]
Ok. Meanwhile, i disabled doc building.

**Pull request closed without merging**
