### PR TITLE
Package ocamlformat.0.10

### PR DESCRIPTION
**Pull request by gpetiot**
### `ocamlformat.0.10`
Auto-formatter for OCaml code
OCamlFormat is a tool to automatically format OCaml code in a uniform style.

---
* Homepage: https://github.com/ocaml-ppx/ocamlformat
* Source repo: git+https://github.com/ocaml-ppx/ocamlformat.git
* Bug tracker: https://github.com/ocaml-ppx/ocamlformat/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Compilation fails on 4.06 with:
```
#=== ERROR while compiling ocamlformat.0.10 ===================================#
# context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.06.1 | pinned(https://github.com/ocaml-ppx/ocamlformat/archive/0.10.tar.gz)
# path                 ~/.opam/4.06/.opam-switch/build/ocamlformat.0.10
# command              ~/.opam/4.06/bin/dune build -p ocamlformat -j 71
# exit-code            1
# env-file             ~/.opam/log/ocamlformat-15-1c67ba.env
# output-file          ~/.opam/log/ocamlformat-15-1c67ba.out
### output ###
#       ocamlc vendor/ocamlformat_support/.format_.objs/byte/format_.{cmi,cmti} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlc.opt -w -40 -g -bin-annot -I vendor/ocamlformat_support/.format_.objs/byte -no-alias-deps -open Format___ -o vendor/ocamlformat_support/.format_.objs/byte/format_.cmi -c -intf vendor/ocamlformat_support/format_.mli)
# File "vendor/ocamlformat_support/format_.mli", line 753, characters 15-33:
# Error: Unbound module Stdlib
```
and on 4.07 with:
```

#=== ERROR while compiling ocamlformat.0.10 ===================================#
# context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/ocaml-ppx/ocamlformat/archive/0.10.tar.gz)
# path                 ~/.opam/4.07/.opam-switch/build/ocamlformat.0.10
# command              ~/.opam/4.07/bin/dune build -p ocamlformat -j 71
# exit-code            1
# env-file             ~/.opam/log/ocamlformat-15-1c67ba.env
# output-file          ~/.opam/log/ocamlformat-15-1c67ba.out
### output ###
#     ocamlopt vendor/ocamlformat_support/.format_.objs/native/format_.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlopt.opt -w -40 -g -I vendor/ocamlformat_support/.format_.objs/byte -I vendor/ocamlformat_support/.format_.objs/native -intf-suffix .ml -no-alias-deps -open Format___ -o vendor/ocamlformat_support/.format_.objs/native/format_.cmx -c -impl vendor/ocamlformat_support/format_.ml)
# File "vendor/ocamlformat_support/format_.ml", line 313, characters 8-21:
# Error: Unbound value Stack.top_opt
```

**Comment by avsm** [comment]
Holding off merging this until blog post ready.

**Comment by gpetiot** [comment]
> Holding off merging this until blog post ready.

The blog post is ready.

**Comment by kit-ty-kate** [comment]
thanks!

**Pull request merged**
