### PR TITLE
Package cudajit.0.6.1

### PR DESCRIPTION
**Pull request by lukstafi**
### `cudajit.0.6.1`
Bindings to the `cuda` and `nvrtc` libraries with a unified interface
Bindings to manually selected parts of `lcuda` and `lnvrtc`, with a few types and conversion functions to facilitate use.

---
* Homepage: https://github.com/lukstafi/ocaml-cudajit
* Source repo: git+https://github.com/lukstafi/ocaml-cudajit.git
* Bug tracker: https://github.com/lukstafi/ocaml-cudajit/issues

---
:camel: Pull-request generated by opam-publish v2.4.0

### CODE REVIEW

**Comment by lukstafi** [comment]
CI runs:
- [(ubuntu-22.04, 4.13.x)](https://github.com/lukstafi/ocaml-cudajit/actions/runs/12141364700/job/33853294311#logs)
- [(ubuntu-22.04, 5.2.x)](https://github.com/lukstafi/ocaml-cudajit/actions/runs/12141364700/job/33853294846#logs)

**Comment by avsm** [comment]
Can we fix `conf-cuda` here or is that difficult for some reason?

**Comment by lukstafi** [comment]
> Can we fix `conf-cuda` here or is that difficult for some reason?

We cannot have `conf-cuda` install the CUDA libraries, because `depext` does not support variable substitution:
https://github.com/ocaml/opam/pull/5455
Instead, when `conf-cuda` fails it provides instructions on how to install CUDA on a given system.

**Comment by mseri** [comment]
For the time being, that is the best we can do. I am going to merge in the meantime

**Pull request merged**
