### PR TITLE
some packages forgot the 'v' in their ppx_expect bounds

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
this is fine to merge, just some cosmetical changes that should improve the opam-repository :)

**Comment by mseri** [comment]
Let me fix separately the lwt lower (or upper) bounds issues that appeared with this, then I’ll re-test and merge. Thanks!

**Comment by hannesm** [comment]
ok @mseri I separated the lwt diff as #27111

**Comment by mseri** [comment]
Thnks

**Pull request merged**
