### PR TITLE
Package zarith.release-1.11

### PR DESCRIPTION
**Pull request by antoinemine**
### `zarith.release-1.11`
Implements arithmetic and logical operations over arbitrary-precision integers
The Zarith library implements arithmetic and logical operations over
arbitrary-precision integers. It uses GMP to efficiently implement
arithmetic over big integers. Small integers are represented as Caml
unboxed integers, for speed and space economy.

---
* Homepage: https://github.com/ocaml/Zarith
* Source repo: git+https://github.com/ocaml/Zarith.git
* Bug tracker: https://github.com/ocaml/Zarith/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I believe the version number should be `1.11` instead of `release-1.11`

**Comment by antoinemine** [comment]
You're right! I'm sorry for the mistake. Do you want me to `opam publish -v 1.11`, or is there a better solution?

**Comment by mseri** [comment]
@antoinemine yes, either a manual rename on your PR branch or just re-run opam publish with the `-v` option, thanks!

**Comment by mseri** [comment]
Closing in favour of #17606

**Pull request closed without merging**
