### PR TITLE
add switches for 4.06.1+rc1

### PR DESCRIPTION
**Pull request by damiendoligez**
I've just tagged OCaml 4.06.1+rc1, so here are the opam switches.

### CODE REVIEW

**Comment by jpdeplaix** [comment]
The ```+safe-string``` variant shouldn't be here. It has been replaced by ```+force-safe-string``` and ```+default-unsafe-string``` in ```4.06.0```.

**Comment by jpdeplaix** [comment]
Ping @damiendoligez

**Comment by avsm** [comment]
There's been a showstopper bug in 4.06.1 found, so there will definitely be at least one more rc

**Comment by jpdeplaix** [comment]
Do we want to merge this right now ? I know some people want to use it. I can do an other PR to fix the ```safe-string``` packages.

**Comment by avsm** [comment]
Create another PR with this commit included, and your fix. @damiendoligez is on vacation for 2 weeks and so won't be able to push fixes.  Closing this one...

**Pull request closed without merging**
