### PR TITLE
Add `conf-libsodium` and add `depext` for alpine

### PR DESCRIPTION
**Pull request by OCamlPro-Henry**

### CODE REVIEW

**Comment by OCamlPro-Henry** [comment]
cc @dsheets

**Comment by dsheets** [comment]
SFTM but I wonder if the `post-messages` should stay in the user packages as the user has the library version constraint?

**Comment by avsm** [comment]
ping @OCamlPro-Henry regarding @dsheets' comment above.

**Comment by OCamlPro-Henry** [comment]
Just updated the PR, leaving the post-message in the `sodium` package, as suggested by @dsheets.

**Comment by avsm** [comment]
thanks!

**Pull request merged**
