### PR TITLE
Included ocamlbuild is not available with 4.03

### PR DESCRIPTION
**Pull request by chambart**

### CODE REVIEW

**Comment by chambart** [comment]
As discussed in https://github.com/ocaml/opam-repository/pull/5363 the lint errors shouldn't be fixed

**Comment by avsm** [comment]
Since this changeset, `opam switch 4.03.0+trunk` no longer works since the base-ocamlbuild package is not installable.  Is there an associated PR to add an ocamlbuild.4.03 that installs the external tool? Thanks! /cc @gasche

**Comment by dsheets** [comment]
`ocamlbuild` is available as a package that installs the external tool. https://github.com/ocaml/opam-repository/commit/2a2fc05964d2b6702f29d9f46b5d08d915cfde01 added the base package to all the switches but 4.03 recently removed the tool from the distro. The base package now needs to be removed from the 4.03 switches.

**Comment by avsm** [comment]
Got it! I'll update the PR syncher as well.

**Comment by gasche** [comment]
Apologies. I should of course have sent a PR to do this at the same time as the upstream ocamlbuild removal, but forgot to do so. Thanks @dsheets and @avsm for your work and reactivity.

**Pull request merged**
