### PR TITLE
Eliom: do not allow js_of_ocaml-lwt.3.2.0 (buggy)

### PR DESCRIPTION
**Pull request by balat**

### CODE REVIEW

**Comment by mseri** [comment]
Is it just 3.2.0 a problem, or also previous or later versions?

**Comment by mseri** [comment]
Oh, I see, it's related to this: https://discuss.ocaml.org/t/error-with-js-of-eliom/2280/3

**Comment by mseri** [comment]
Now it fails with
```
# Error: Files ../baselib/baselib.cma(Ocsigen_commandline)
#        and ../baselib/parsecommandline.cma(Ocsigen_getcommandline)
#        make inconsistent assumptions over interface Ocsigen_getcommandline
```

See also https://discuss.ocaml.org/t/ocsigen-not-installing-in-opam-with-ocaml-4-07/2309

**Comment by kit-ty-kate** [comment]
ping @balat

**Comment by vasilisp** [comment]
Solved in `ocsigenserver` `master` (https://github.com/ocsigen/ocsigenserver/pull/152). Release pending!

**Pull request merged**
