### PR TITLE
added packages/parany/parany.1.0.2

### PR DESCRIPTION
**Pull request by UnixJunkie**
use POSIX semaphores instead of Unix.sleepf; like real men ;)

### CODE REVIEW

**Comment by avsm** [comment]
It looks like this isn't portable to Alpine 3.6 due to posix-semaphore

```
#=== ERROR while installing posix-semaphore.0.4.0-0 ===========================#
# opam-version         1.2.2
# os                   linux
# command              ocaml setup.ml -build
# path                 /home/opam/.opam/4.04.2/build/posix-semaphore.0.4.0-0
# compiler             4.04.2
# exit-code            1
# env-file             /home/opam/.opam/4.04.2/build/posix-semaphore.0.4.0-0/posix-semaphore-29-ece7a3.env
# stdout-file          /home/opam/.opam/4.04.2/build/posix-semaphore.0.4.0-0/posix-semaphore-29-ece7a3.out
# stderr-file          /home/opam/.opam/4.04.2/build/posix-semaphore.0.4.0-0/posix-semaphore-29-ece7a3.err
### stdout ###
# /home/opam/.opam/4.04.2/lib/posix-time/posix-time.h:64:57: error: parameter 1 ('t') has incomplete type
# [...]
#                                                          ^
# Command exited with code 2.
```

this isn't strictly dependent on this PR though... I'm not sure if it's fixable in this or we can go ahead and merge.

**Comment by UnixJunkie** [comment]
Interesting, I might as well use the semaphores from netsys_posix (part of ocamlnet); this would remove some code plus I don't like the interface of posix-semaphores anyway and that would cut this dependency out.

**Comment by UnixJunkie** [comment]
this PR will be superseded by somehting better soon

**Comment by UnixJunkie** [comment]
Finally, I removed the dependency to posix-semaphore and retagged the software.

**Comment by UnixJunkie** [comment]
The only failure is "OS package installation failed" on open suse.
I guess the CI tests are broken in there; it doesn't look like an opam or ocaml related error.

**Comment by samoht** [comment]
> The only failure is "OS package installation failed" on open suse.
> I guess the CI tests are broken in there; it doesn't look like an opam or ocaml related error.

Indeed and this is already reported here: https://github.com/avsm/mirage-ci/issues/4

I am merging your package, thanks for your contribution!

**Pull request merged**
