### PR TITLE
Update extlib urls

### PR DESCRIPTION
**Pull request by yallop**
/cc @ygrek 

```
$ wget -qS http://ocaml-extlib.googlecode.com/files/extlib-1.5.2.tar.gz
  HTTP/1.1 404 Not Found
  Content-Type: text/html; charset=UTF-8
  Content-Length: 1586
  Date: Wed, 07 Sep 2016 11:01:42 GMT
```

```
$ wget -qS http://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ocaml-extlib/extlib-1.5.2.tar.gz -O - | md5sum
  HTTP/1.1 200 OK
  X-GUploader-UploadID: AEnB2UrVZPswZTr68BeOGEmsk-bYMQ0BI71XboMC7gVPV5AMc6PCG0H4nFARcE2ZqXoj7Nj69KRdddr0ONGFBBuYjx0Mz7z7JQ
  Expires: Wed, 07 Sep 2016 12:00:55 GMT
  Date: Wed, 07 Sep 2016 11:00:55 GMT
  Last-Modified: Sat, 23 Jan 2016 04:33:25 GMT
  ETag: "839f9bf5a971fa07935c96ba7e209f86"
  x-goog-generation: 1453523605724000
  x-goog-metageneration: 1
  x-goog-stored-content-encoding: identity
  x-goog-stored-content-length: 70197
  Content-Type: application/octet-stream
  x-goog-hash: crc32c=IEQRaA==
  x-goog-hash: md5=g5+b9alx+geTXJa6fiCfhg==
  x-goog-storage-class: NEARLINE
  Accept-Ranges: bytes
  Content-Length: 70197
  Server: UploadServer
  Cache-Control: public, max-age=3600
  Age: 51
839f9bf5a971fa07935c96ba7e209f86  -
```

### CODE REVIEW

**Comment by ygrek** [comment]
Thanks for taking care of this. Should probably also add `mirrors: ["http://ygrek.org.ua/p/release/ocaml-extlib/extlib-1.5.2.tar.gz"]` etc

**Comment by yallop** [comment]
The GitHub-mirrored versions don't all have the same checksums as the `googlecode` versions (apparently because only the GitHub tarballs contain the tests):

```
$ wget -q  https://github.com/ygrek/ocaml-extlib/archive/1.5.4.tar.gz -O  - | md5sum
4846ee0afefe6628ff82a78e8f13db12  -
$ wget -q http://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ocaml-extlib/extlib-1.5.4.tar.gz -O  - | md5sum
329041625309b9e49051e5b097a9185d  -
```

So we can either
* leave them unmirrored, retaining the original checksums, or  
* switch to the GitHub versions.

Do you have a preference?

**Comment by ygrek** [comment]
Not github, but ygrek.org.ua which have the same exact tarball uploaded (verified md5). I can make a PR for mirrors later if anything.

**Comment by yallop** [comment]
Oops -- I read that too quickly!   I've added `ygrek.org.ua` mirrors now (258098b6).

**Pull request merged**
