### PR TITLE
Package ocaml-diff.0.1.2

### PR DESCRIPTION
**Pull request by jhrdina**
### `ocaml-diff.0.1.2`
Symmetric Diffs for OCaml stdlib and ReasonML

---
* Homepage: http://github.com/jhrdina/ocaml-diff
* Bug tracker: http://github.com/jhrdina/ocaml-diff/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by mseri** [comment]
Thanks

**Comment by hannesm** [comment]
hmm, I'm not sure, but [wasn't there](https://github.com/ocaml/opam-repository/wiki/PR-checks#names) the guideline to avoid `ocaml` as prefix or postfix for a package name?

**Comment by mseri** [comment]
Sorry about that. That is indeed the case, I am going to revert the merge. Please @jhrdina can you rename the package and remove “ocaml” from the name?

**Comment by jhrdina** [comment]
Oh, I'm sorry, I didn't know about the rule... my original intent was to match naming of the [same package published at NPM](https://www.npmjs.com/package/ocaml-diff). Here is the renamed version: #14144. Thank you for your time!

**Comment by mseri** [comment]
Thank you very much for acting so fast! It's a relatively recent rule, I also had completely forgotten about that.

**Pull request merged**
