### PR TITLE
apero-net 0.4.7

### PR DESCRIPTION
**Pull request by JEnoch**
Hi,
this PR add [apero-net](https://github.com/atolab/apero-net).

### CODE REVIEW

**Comment by JEnoch** [comment]
Hi,
it seems the Travis CI build failed because of missing OpenSSL library. See the log:
```
#  | /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/ocaml-configurator031fdb/c-test-2/test.c:2:10: fatal error: 'openssl/ssl.h' file not found
#  | #include <openssl/ssl.h>
#  |          ^~~~~~~~~~~~~~~
#  | 1 error generated.
```

**Comment by avsm** [comment]
Add a dependency on the opam `conf-openssl` package, and it'll be installed by the CI through the `opam depext` mechanism.

**Comment by JEnoch** [comment]
> Add a dependency on the opam `conf-openssl` package, and it'll be installed by the CI through the `opam depext` mechanism.

Thanks for the tip! Done.

**Comment by kit-ty-kate** [comment]
The dependency was not needed as the build failure is in the `ssl` package and not in the package that is being added here. We have an ongoing issue on this already.

I'm gonna remove the unnecessary dependency and merge this PR. Thanks!

**Comment by kit-ty-kate** [comment]
ah nevermind you disabled the option for me to modify your PR. Could you reset to the previous commit?

**Comment by JEnoch** [comment]
> ah nevermind you disabled the option for me to modify your PR. Could you reset to the previous commit?

I didn't know there was such option... 😄. I just reverted the previous commit 🤞

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
