### PR TITLE
New release of ACGtk

### PR DESCRIPTION
**Pull request by Nyavlys**
This pull request include:
+ a modification on acgtk-1.3.1 opam file to ensure it is compiled with yojson-version < 1.4.0 and easy-format <1.3.0, otherwise compilation fails (because linked files changed)
+ a new release compatible with yojson-version >= 1.4.0 and easy-format >=1.3.0. The build now relies on jbuilder
+ a patch for bolt in order to allow for compiling with ocaml-version >= 4.06.0 (the tarball uses String instead of Bytes)

### CODE REVIEW

**Comment by Nyavlys** [comment]
As far as I can see, the problems are:
- installation of acgtk requires ocaml-version >= 4.03.0, so it fails with earlier versions of ocaml
- installation of acgtk 1.3.2 fails with ocaml 4.06.0 because dypgen installation fails. I guess the later will be updated soon. But bolt patch seems to work.
- installation of acgtk 1.3.1 fails with ocaml 4.06.0 because it requires versions of yojson (via ocf) that require ocaml < 4.06.0

**Comment by rgrinberg** [comment]
IMO we should really avoid patching packages without the consent of upstream like this. Especially if they're non essential like this one. Can't you just not use bolt instead of doing this? E.g. using Logs or something.

**Comment by gasche** [comment]
@rgrinberg I don't see the problem with fixing bolt to support newer OCaml releases, but I agree that the maintainers should be notified, and that it is better if the patch is integrated upstream in the first place.

@xclerc, as the maintainer of bolt, what do you think would be the best way forward here? Is the darcs repo at <http://bolt.x9c.fr/_darcs> still active, and in what format would you expect a patch? (Would you need someone else, for example @Nyavlys, to take care of releasing a 1.4.1 on opam?)

@Nyavlys: is it ok if we wait to see what's the status of the bolt change before going further with the PR? In general it's not such a good idea to patch already-released software on opam (it can change `.cmx` hashes, etc.), so it is worth waiting to know if a new release can be made soon.

**Comment by rgrinberg** [comment]
> I don't see the problem with fixing bolt to support newer OCaml releases, but I agree that the maintainers should be notified, and that it is better if the patch is integrated upstream in the first place.

Of course I don't see a problem with fixing bolt either. I kind of assumed @Nyavlys already asked upstream. Choosing to create a patch in opam-repository rather than upstream is kind of strange. I do think that discouraging the use of camlp4 is a good thing, and it doesn't hurt to do it when you have an occasion to do so.

**Comment by gasche** [comment]
I think there is a difference between discouraging Camlp4 for new projects (which sounds reasonable and is best done by good communication on the advantages of the proposed alternatives, as for example your very nice recent blog post) and explaining to user that, to release a new version of their existing software, they should rather completely swap out a library that they are using instead of making a five-line patches to fix one of their dependency (and, in turn, help all other users of the dependency).

**Comment by rgrinberg** [comment]
I'm not forcing anyone, merely trying to nudge people in what I consider to be the right direction :) Logging is usually an inessential part of a library, and is often fairly easy to replace (depending how good you are with sed). Of course, people can use whatever they want, but I think the circumstances here deserve a question to be raised about the choice.

**Comment by Nyavlys** [comment]
You're right, pushing the commit with the modifications of the bolt package was a bad idea. I'll remove this part (or if you prefer I close this pull request and open another one only with the acgtk stuff).

For some reasons, I thought (possibly wrongly) that bolt was not maintained anymore. Anyway, changing the log library and removing the dependency on camlp4 is on my todo list, but not with the highest priority.

**Comment by xclerc** [comment]
Sorry for the late answer, and thanks to @gasche that
just pinged me (I definitely have trouble using the Github
notifications...).

The aforementioned repository has not been active for years.
While I expect to be able to revisit the project at some point,
it will not happen before at least next Spring. 

Would it be easier for you to have the repository on github?
(as it is not time-consuming, I can definitely perform the move.)
Otherwise, feel free to do what is best/simplest for you -- I
will not feel offended.

**Comment by gasche** [comment]
Yes, as much as I like darcs myself, I think that the community dynamics today (not only in the OCaml world) make it easier to work with a git repository. If you had the time to create a repository, for example on github or gitlab, I think it would be easy for @Nyavlys to send a PR there (or for you to integrate the patch) and to make a new release. (The fact that either github or gitlab create .tar.gz out of git tags automatically is in fact quite convenient to cut on the release work.) Let me know if I can help to perform some of those tasks.

**Comment by gasche** [comment]
So a point on the current state: the PR as-is is fine, but because bolt is not updated (yet) it does not meet its goal of working under 4.06 -- but we have reasonable confidence that, if we merge it now, and later we improve bolt, then it would work under 4.06.

I think the easiest thing to do is to wait for bolt to be updated to work under 4.06 (or for an ACGtk version using a different library), to merge the present PR, so that we can use the correct version bound on `bolt` right away -- otherwise we would have to patch the metadata later to refine the `bolt` version, which is more work.

**Comment by Nyavlys** [comment]
Actually, there is another package on which ACGtk depends, and that doesn't yet compile with 4.06.0 (dypgen. I'll tell the author).

So, anyway, ACGtk would not yet be available for 4.06.0. So I'd prefer the new version to be published, so that at least it is available with earliest version of yojson and easy-format and OCaml <4.06.0.

Currently, users that want to install it have to pin these packages. It's of course not that difficult, but for users not running 4.06.0 (all the cases I'm aware so far), it would even be simpler.

**Comment by gasche** [comment]
Sure, merged. Thanks for the work.

**Pull request merged**
