### PR TITLE
logtk: seems to need containers.data, so add containers constraint

### PR DESCRIPTION
**Pull request by avsm**
seen in revdeps for #9320 cc @c-cube

### CODE REVIEW

**Comment by c-cube** [comment]
Looks like it also needs `sequence < 0.9`

**Comment by avsm** [comment]
thanks, pushed in fd360721ddbd79b3e467e16266095a2d4d9bbf15

**Comment by avsm** [comment]
still failing with
```
# File "src/base/logtkSubsts.ml", line 206, characters 9-435:
# Error: The function applied to this argument has type
#          'a M.t -> 'a CCPersistentHashtbl.Make(TermInt).t
```

**Comment by avsm** [comment]
any idea about this @c-cube ?

**Comment by c-cube** [comment]
Containers <= 0.16, it seems (there were some signature changes in the module mentioned above…)

**Comment by avsm** [comment]
no problem, trying this in ef0e3a1a21b31c19a84e3d5f181c9f0749c220f0

**Comment by avsm** [comment]
still broken I'm afraid.

**Pull request closed without merging**
