### PR TITLE
Add message-switch.0.10.5

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave.scott@citrix.com>

### CODE REVIEW

**Comment by avsm** [comment]
```
# File "core/protocol.mli", line 171, characters 12-23:
# Error: Unbound module Cohttp.IO
# Command exited with code 2.
```

That needs to be `Cohttp.S.IO` ...

**Comment by avsm** [comment]
Pinging this one in case you missed it while travelling @djs55...

**Comment by djs55** [comment]
Oops, it looks like the url file still references 0.10.4

**Comment by djs55** [comment]
Thanks!

**Pull request merged**
