### PR TITLE
git.1.7.1 - via opam-publish

### PR DESCRIPTION
**Pull request by samoht**
Low-level Git bindings in pure OCaml

Support for on-disk and in-memory Git stores. Can read and write all
the Git objects: the usual blobs, trees, commits and tags but also the
pack files, pack indexes and the index file (where the staging area
lives).

All the objects share a consistent API, and convenience functions are
provided to manipulate the different objects. For instance, it is
possible to make a pack file position independant (as the Zlib
compression might change the relative offsets between the packed
objects), to generate pack indexes from pack files, or to expand
the filesystem of a given commit.

The library comes with a command-line tool called `ogit` which shares
a similar interface with `git`, but where all operations are mapped to
the API exposed `ocaml-git` (and hence using only OCaml code).

---
* Homepage: https://github.com/mirage/ocaml-git
* Source repo: https://github.com/mirage/ocaml-git.git
* Bug tracker: https://github.com/mirage/ocaml-git/issues

---

Pull-request generated by opam-publish v0.3.0

### CODE REVIEW

**Comment by yallop** [comment]
Is there a mismatch between the [`major.minor` `OCAML_VERSION` format in travis-ci-skeleton](https://github.com/ocaml/ocaml-travisci-skeleton/blob/b424e189b0ad30e41c28de4c974c522d2beda4e4/.travis-ocaml.sh#L27-L30) (e.g. `4.02`) and the [`major.minor.patch` `OCAML_VERSION` format in opam-repository](https://github.com/ocaml/opam-repository/blob/a7eeb1973aaf094527821960761ad6ba1d268586/.travis.yml#L8-L22), (e.g. `4.02.1`)?

**Comment by samoht** [comment]
indeed, I'm trying to fix this. I think we don't really need to keep the minor version number in the env variable. What do you think?

I've asked Travis CI support to enable OSX testing on ocaml-travisci-skeleton so I can test the changes.

**Comment by yallop** [comment]
I think dropping the patch number is fine.

**Comment by avsm** [comment]
Dropping the patch number is fine.

**Pull request merged**
