### PR TITLE
jwt: 0.1

### PR DESCRIPTION
**Pull request by dannywillems**

### CODE REVIEW

**Comment by samoht** [comment]
```
#=== ERROR while installing ocaml-jwt.0.1 =====================================#
# opam-version 1.2.2
# os           linux
# command      make build
# path         /home/travis/.opam/4.04.0+beta2/build/ocaml-jwt.0.1
# compiler     4.04.0+beta2
# exit-code    2
# env-file     /home/travis/.opam/4.04.0+beta2/build/ocaml-jwt.0.1/ocaml-jwt-14307-f936b0.env
# stdout-file  /home/travis/.opam/4.04.0+beta2/build/ocaml-jwt.0.1/ocaml-jwt-14307-f936b0.out
# stderr-file  /home/travis/.opam/4.04.0+beta2/build/ocaml-jwt.0.1/ocaml-jwt-14307-f936b0.err
### stdout ###
# ocamlfind ocamlc -c -o jwt.cmi -package base64 -package yojson -package cryptokit -package re.str -linkpkg jwt.mli
### stderr ###
# ocamlfind: Package `re.str' not found
# make: *** [jwt.cmi] Error 2
```

**Comment by dannywillems** [comment]
@samoht I thought it was in standard library.
About `depext` (last build), do I need to do something?

**Comment by samoht** [comment]
`re.str` is in the `re` library.

**Comment by samoht** [comment]
For the depext issue, can you try to the line:
```
[["homebrew"] ["lzlib"]]
```
to `conf-zlib`? Thanks!

**Comment by dannywillems** [comment]
@samoht In the `conf-zlib` opam repository ([here](https://github.com/ocaml/opam-repository/blob/master/packages/conf-zlib/conf-zlib.1/opam)) ?

**Comment by samoht** [comment]
Yes. Note: I am not sure why the depext issue was not reported/seen before, so not sure it will change anything. I am not sure what changed, though.

**Comment by dannywillems** [comment]
I fix the syntax `|>` to be compatible with `OCaml <= 4.0.0`.
I don't understand the error for Mac.

**Comment by dannywillems** [comment]
I didn't see I named the repo `ocaml-jwt` instead of `jwt` (there is no reason to prefix with `ocaml` because it's not a binding).

**Comment by dannywillems** [comment]
@samoht It remains the error for depext.

**Comment by samoht** [comment]
Sorry my fault. Could you try with:

```
[["homebrew" "osx"] ["lzlib"]]
```

**Comment by dannywillems** [comment]
@samoht It remains broken :(.

**Comment by samoht** [comment]
ok thanks for your efforts, merging.

**Comment by dsheets** [comment]
I don't think `lzlib` is `zlib` (<http://www.nongnu.org/lzip/lzlib.html>). OS X contains `/usr/include/zlib.h` but I'm not sure if that satisfies the `conf-zlib` semantics.

**Pull request merged**
