### PR TITLE
[new release] irmin et al. (2.7.0)

### PR DESCRIPTION
**Pull request by CraigFe**
### Fixed

- **irmin**
  - Added `Store.Tree.length`. (mirage/irmin#1316, @Ngoguey42)
  - Fixed fold for non-persisted, cleared trees (mirage/irmin#1442, @samoht, @Ngoguey42)

- **irmin-layers**
  - Do not fail on double-close errors for private nodes (mirage/irmin#1421, @samoht)

- **irmin-pack**
  - Do not clear and bump the generation for empty files (mirage/irmin#1420, @samoht)

### Added

- **irmin-pack**
  - Added `Irmin_pack.Version.{V1,V2}` modules for convenience. (mirage/irmin#1457,
    @CraigFe)
  - Added a `irmin-pack.mem` package (mirage/irmin#1436, @icristescu, @craigfe)

- **irmin-graphql**
  - Added `last_modified` field to GraphQL interface (mirage/irmin#1393, @kluvin)

### Changed

- **irmin-layers**
  - Remove `copy_in_upper` from the repo configuration. The default is now to
    copy. (mirage/irmin#1322, @Ngoguey42)
  - Simplify the API of `freeze`. It is now possible to specify two distinct
    commit closures for the copy to lower and the copy to next upper.
    (mirage/irmin#1322, @Ngoguey42)
  - Renamed `Irmin_layered_pack.Make` and Irmin_layers.Make` into
    `Irmin_layered_pack.Maker` and `Irmin_layers.Maker` (mirage/irmin#1369, @samoht)
  - Renamed `Irmin_layered_pack.Make_ext` and and Irmin_layers.Make_ext` into
    into `Irmin_layered_pack.Maker_ext` and `Irmin_layers.Maker_ext`
    (mirage/irmin#1369, @samoht)
  - Renamed `Irmin_layered_pack.Config` into `Irmin_layered_pack.Conf`
    (mirage/irmin#1370, @samoht)
  - Readonly instances can check for an ongoing freeze (mirage/irmin#1382, @icristescu,
    @Ngoguey42)

- **irmin-pack**
  - It is no longer possible to modify an `inode` that doesn't point to the root
    of a directory. (mirage/irmin#1292, @Ngoguey42)
  - When configuring a store, is it no longer possible to set `entries` to a
    value larger than `stable_hash`. (mirage/irmin#1292, @Ngoguey42)
  - Added number of objects to the output of `stat-pack` command in
    `irmin-fsck`. (mirage/irmin#1311, @icristescu)
  - Renamed the `Version` module type into `Version.S` and `io_version` into
    `version`. The `Pack.File` and `Atomic_write` functors now take
    `Version` as their first parameter (mirage/irmin#1352, @samoht)
  - Renamed `Irmin_pack.Make` into `Irmin_pack.V1` (mirage/irmin#1369, @samoht)
  - Renamed `Irmin_pack.Config` into `Irmin_pack.Conf` (mirage/irmin#1370, @samoht)
  - Renamed `Irmin_pack.Pack` into `Irmin_pack.Content_addressable` and
    `Irmin_pack.Pack.File` into `Irmin_pack.Content_addressable.Maker`
    (mirage/irmin#1377, @samoht)
  - Moved `Irmin_pack.Store.Atomic_write` into its own module (mirage/irmin#1378, @samoht)
  - `Checks.Reconstruct_index.run` now takes an optional `index_log_size`
    parameter for customising the interval between merges during
    reconstruction. (mirage/irmin#1459, @CraigFe)

### CODE REVIEW

**Comment by CraigFe** [comment]
This will require https://github.com/ocaml/opam-repository/pull/18877 to be merged before the CI will pass.

**Comment by samoht** [comment]
The lower bounds issue with yaml should be fixed by https://github.com/ocaml/opam-repository/pull/18913

**Comment by samoht** [comment]
The yojson issue should be fixed by https://github.com/ocaml/opam-repository/pull/18914

**Comment by samoht** [comment]
the re issue should be fixed by https://github.com/ocaml/opam-repository/pull/18917

**Comment by kit-ty-kate** [comment]
Thanks a lot! Sorry for all the delays. Could you return the fixes to the opam files upstream?

Also, the `irmin-git` tests don't seem to run on 32bit architectures:
```
#=== ERROR while compiling irmin-git.2.7.0 ====================================#
# context              2.1.0~rc | linux/arm32 | ocaml-base-compiler.4.12.0 | pinned(https://github.com/mirage/irmin/releases/download/2.7.0/irmin-2.7.0.tbz)
# path                 ~/.opam/4.12/.opam-switch/build/irmin-git.2.7.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p irmin-git -j 31
# exit-code            1
# env-file             ~/.opam/log/irmin-git-8708-4520fd.env
# output-file          ~/.opam/log/irmin-git-8708-4520fd.out
### output ###
#         test alias test/irmin-git/runtest (exit 125)
# (cd _build/default/test/irmin-git && ./test.exe -q --color=always)
# +75232us tls.config      [INFO] client with ((ciphers
#   (AES_128_GCM_SHA256 AES_256_GCM_SHA384 CHACHA20_POLY1305_SHA256
#    AES_128_CCM_SHA256 DHE_RSA_WITH_AES_256_GCM_SHA384
#    DHE_RSA_WITH_AES_128_GCM_SHA256 DHE_RSA_WITH_AES_256_CCM
#    DHE_RSA_WITH_AES_128_CCM DHE_RSA_WITH_CHACHA20_POLY1305_SHA256
#    ECDHE_RSA_WITH_AES_128_GCM_SHA256 ECDHE_RSA_WITH_AES_256_GCM_SHA384
#    ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
#    ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
#    ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256))
#  (protocol_versions (TLS_1_2 TLS_1_3))
#  (signature_algorithms
#   (ECDSA_SECP256R1_SHA256 ECDSA_SECP384R1_SHA384 ECDSA_SECP521R1_SHA512
#    ED25519 RSA_PSS_RSAENC_SHA256 RSA_PSS_RSAENC_SHA384 RSA_PSS_RSAENC_SHA512
#    RSA_PKCS1_SHA256 RSA_PKCS1_SHA384 RSA_PKCS1_SHA512 RSA_PKCS1_SHA224
#    ECDSA_SECP256R1_SHA1 RSA_PKCS1_SHA1 RSA_PKCS1_MD5))
#  (use_reneg false) (authenticator (Authenticator)) (peer_name ())
#  (own_certificates None) (acceptable_cas ()) (session_cache SESSION_CACHE)
#  (ticket_cache TICKET_CACHE) (cached_session ()) (cached_ticket ())
#  (alpn_protocols ())
#  (groups
#   (X25519 P384 P256 P521 FFDHE2048 FFDHE3072 FFDHE4096 FFDHE6144 FFDHE8192))
#  (zero_rtt 0))
# +79538us bos             [EXEC:8816] ['uname' '-s']
# +100570us ca-certs        [WARNING] Failed to decode a trust anchor No certificate.
# +100599us ca-certs        [DEBUG] Full certificate:
# 
# -----END CERTIFICATE-----
# +100710us irmin.git       [DEBUG] Tree.encode_bin
# +101693us irmin.git       [DEBUG] Tree.encode_bin
# +102125us irmin.git       [DEBUG] Tree.encode_bin
# +104357us irmin.git       [DEBUG] Tree.encode_bin
# +105206us irmin.git       [DEBUG] Tree.encode_bin
# +106081us irmin.git       [DEBUG] Tree.encode_bin
# Testing `irmin-git'.
# This run has ID `FB778744-94E1-4C7E-A4FB-5D233E7A0653'.
# 
#   [OK]          GIT                          0   Basic operations on contents.
#   [OK]          GIT                          1   Basic operations on nodes.
#   [OK]          GIT                          2   Basic operations on commits.
#   [OK]          GIT                          3   Basic operations on branches.
#   [OK]          GIT                          4   Hash operations on trees.
#   [OK]          GIT                          5   Basic merge operations.
#   [OK]          GIT                          6   Basic operations on slices.
#   [OK]          GIT                          7   Test merges on tree updates.
#   [OK]          GIT                          8   Tree caches and hashconsing.
#   [OK]          GIT                          9   Complex histories.
#   [OK]          GIT                         10   Empty stores.
#   [OK]          GIT                         11   Private node manipulation.
#   [OK]          GIT                         12   High-level store operations.
#   [OK]          GIT                         13   High-level operations on trees.
#   [OK]          GIT                         14   High-level store synchronisa...
#   [OK]          GIT                         15   High-level store merges.
#   [OK]          GIT                         16   Unrelated merges.
#   [OK]          GIT                         17   Low-level concurrency.
#   [OK]          GIT                         18   Concurrent updates.
#   [OK]          GIT                         19   with_tree strategies.
#   [OK]          GIT                         20   Concurrent head updates.
#   [OK]          GIT                         21   Concurrent merges.
#   [OK]          GIT                         22   Shallow objects.
#   [OK]          GIT                         23   Closure with disconnected co...
#   [OK]          GIT                         24   Clear.
#   [OK]          GIT                         25   Graph.Iter.
#   [OK]          GIT                         26   Watch.Callbacks and exceptions.
#   [OK]          GIT                         27   Watch.Basic operations.
#   [OK]          GIT.generic                  0   Basic operations on contents.
#   [OK]          GIT.generic                  1   Basic operations on nodes.
#   [OK]          GIT.generic                  2   Basic operations on commits.
#   [OK]          GIT.generic                  3   Basic operations on branches.
#   [OK]          GIT.generic                  4   Hash operations on trees.
#   [OK]          GIT.generic                  5   Basic merge operations.
#   [OK]          GIT.generic                  6   Basic operations on slices.
#   [OK]          GIT.generic                  7   Test merges on tree updates.
#   [OK]          GIT.generic                  8   Tree caches and hashconsing.
#   [OK]          GIT.generic                  9   Complex histories.
#   [OK]          GIT.generic                 10   Empty stores.
#   [OK]          GIT.generic                 11   Private node manipulation.
#   [OK]          GIT.generic                 12   High-level store operations.
#   [OK]          GIT.generic                 13   High-level operations on trees.
#   [OK]          GIT.generic                 14   High-level store synchronisa...
#   [OK]          GIT.generic                 15   High-level store merges.
#   [OK]          GIT.generic                 16   Unrelated merges.
#   [OK]          GIT.generic                 17   Low-level concurrency.
#   [OK]          GIT.generic                 18   Concurrent updates.
#   [OK]          GIT.generic                 19   with_tree strategies.
#   [OK]          GIT.generic                 20   Concurrent head updates.
#   [OK]          GIT.generic                 21   Concurrent merges.
#   [OK]          GIT.generic                 22   Shallow objects.
#   [OK]          GIT.generic                 23   Closure with disconnected co...
#   [OK]          GIT.generic                 24   Clear.
#   [OK]          GIT.generic                 25   Graph.Iter.
#   [OK]          GIT.generic                 26   Watch.Callbacks and exceptions.
#   [OK]          GIT.generic                 27   Watch.Basic operations.
# > [FAIL]        SLOW_GIT                     0   Commit wide node.
#   [SKIP]        SLOW_GIT                     1   Wide nodes.
#   [FAIL]        SLOW_GIT.generic             0   Commit wide node.
#   [SKIP]        SLOW_GIT.generic             1   Wide nodes.
#   [OK]          misc                         0   Testing sort order.
#   [OK]          misc                         1   Testing sort order (generic).
#   [OK]          misc                         2   Testing listing refs.
#   [OK]          misc                         3   git -> mem.
#   [OK]          misc                         4   git blobs.
# test.exe: internal error, uncaught exception:
#           (Invalid_argument Bytes.create)
#           Raised by primitive operation at Astring_string.concat in file "src/astring_string.ml", line 68, characters 12-32
#           Called from Alcotest_engine__Core.Make.read_tail in file "src/alcotest-engine/core.ml", line 157, characters 6-43
#           Called from Fmt.append in file "src/fmt.ml" (inlined), line 69, characters 31-42
#           Called from Alcotest_engine__Core.Make.pp_error in file "src/alcotest-engine/core.ml", line 210, characters 6-188
#           Called from Fmt.append in file "src/fmt.ml" (inlined), line 69, characters 31-42
#           Called from Alcotest_engine__Core.Make.pp_error in file "src/alcotest-engine/core.ml", line 209, characters 4-225
#           Called from Stdlib__list.iter in file "list.ml", line 110, characters 12-15
#           Called from Alcotest_engine__Pp.Make.suite_results in file "src/alcotest-engine/pp.ml", line 232, characters 8-94
#           Called from Alcotest_engine__Core.Make.run_tests.(fun) in file "src/alcotest-engine/core.ml", line 413, characters 4-42
#           Called from Alcotest_engine__Monad.Extend.Infix.(>|=).(fun) in file "src/alcotest-engine/monad.ml", line 32, characters 46-51
#           Called from Alcotest_engine__Core.Make.run_with_args in file "src/alcotest-engine/core.ml", line 438, characters 4-357
#           Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 25, characters 19-24
#           Called from Cmdliner.Term.run in file "cmdliner.ml", line 117, characters 32-39
#   [OK]          misc                         5   git blobs of generic.
# 
# ┌──────────────────────────────────────────────────────────────────────────────┐
# │ [FAIL]        SLOW_GIT                     0   Commit wide node.             │
# └──────────────────────────────────────────────────────────────────────────────┘
```
Could you have a look at it?

**Pull request merged**
