### PR TITLE
Coq 8.9.0

### PR DESCRIPTION
**Pull request by silene**

### CODE REVIEW

**Comment by mseri** [comment]
`osx` build is failing with
```
#=== ERROR while compiling coq.8.9.0 ==========================================#
# context     2.0.2 | macos/x86_64 | ocaml-system.4.07.1 | file:///Users/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-system/.opam-switch/build/coq.8.9.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j1
# exit-code   2
# env-file    ~/.opam/log/coq-22808-6cc03f.env
# output-file ~/.opam/log/coq-22808-6cc03f.out
### output ###
# [...]
# OCAMLOPT -pack -o plugins/ssr/ssreflect_plugin.cmx
# OCAMLOPT -shared -o plugins/ssr/ssreflect_plugin.cmxs
# COQC      plugins/ssr/ssreflect.v
# COQC      plugins/ssr/ssrfun.v
# COQC      plugins/ssr/ssrbool.v
# MD5SUM cic.mli
# OCAMLOPT -a -o checker/check.cmxa
# OCAMLOPT -o bin/coqchk
# File "checker/main.ml", line 2, characters 8-21:
# Error: Unbound module Checker
# make[1]: *** [bin/coqchk] Error 2
# make: *** [submake] Error 2
```

**Comment by gares** [comment]
I'm trying to reproduce the failure on OSX locally but I can't (same OSX, same compiler...), it works reliably here.
The log is very weird, as if a file disappeared just before the build.

Would you mind running the OSX job again?

**Comment by kit-ty-kate** [comment]
> Would you mind running the OSX job again?

done

**Comment by RalfJung** [comment]
@gares @silene there are a few differences between this `opam` file and the one for `coq.8.9.dev` (over at https://github.com/coq/opam-coq-archive/):

```diff
--- coq.8.9.dev/opam	2019-01-22 10:09:53.140150226 +0100
+++ coq.8.9.0/opam	2019-01-22 10:16:28.955129649 +0100
@@ -1,6 +1,6 @@
 opam-version: "2.0"
 maintainer: "coqdev@inria.fr"
-authors: "The Coq development team, INRIA, CNRS, and contributors."
+authors: "The Coq development team, INRIA, CNRS, University Paris Sud, University Paris 7, Ecole Polytechnique."
 homepage: "https://coq.inria.fr/"
 bug-reports: "https://github.com/coq/coq/issues"
 dev-repo: "git+https://github.com/coq/coq.git"
@@ -47,11 +47,18 @@
   "%{man}%/man1/coqtop.opt.1"
   "%{man}%/man1/coqwc.1"
   "%{share}%/texmf/tex/latex/misc/coqdoc.sty"
+  "%{share}%/emacs/site-lisp/coq-font-lock.el"
+  "%{share}%/emacs/site-lisp/coq-inferior.el"
+  "%{share}%/emacs/site-lisp/gallina-db.el"
+  "%{share}%/emacs/site-lisp/gallina.el"
+  "%{share}%/emacs/site-lisp/gallina-syntax.el"
   ]
 ]
-synopsis: "Formal proof management system."
+synopsis: "Formal proof management system"
 flags: light-uninstall
 extra-files: ["coq.install" "md5=a5d0f9a35ef24aa3948a6960e657b206"]
 url {
-  src: "git+https://github.com/coq/coq.git#v8.9"
+  src: "https://github.com/coq/coq/archive/V8.9.0.tar.gz"
+  checksum: "md5=490c89609c1271fe7f20e6ea1bd107b5"
 }
+
```

These used to be in sync last time I checked. Do you know who updated them where, and which update should be carried over to the other side?

**Comment by kit-ty-kate** [comment]
> > Would you mind running the OSX job again?
> 
> done

The rerun gives the same error. Anybody know what's wrong?

**Comment by silene** [comment]
> The rerun gives the same error. Anybody know what's wrong?

Yes, it is a bug in Coq's build system, which was unfortunately missed by our own regression testing, as its reproducibility depends on make's version.

**Comment by kit-ty-kate** [comment]
> Yes, it is a bug in Coq's build system, which was unfortunately missed by our own regression testing, as its reproducibility depends on make's version.

should I wait for a new release or merge this one now?

**Comment by RalfJung** [comment]
IMO this should reflect the edits done at <https://github.com/coq/opam-coq-archive/commit/77dec9974222a16f5d3c9124be95a04e779e999d>, and remove the emacs uninstall bits -- those files are no longer installed with this version.  (Seems like the opam file from 8.8.0 was used as basis, instead of the one from 8.9.dev, hence all the changes already made got lost.)

**Comment by mseri** [comment]
Ping @silene

**Comment by silene** [comment]
I don't have time to take care of that right now, so closing.

**Comment by RalfJung** [comment]
I can resubmit this later, but right now the Coq team is investigating the macOS build failure.

**Pull request closed without merging**
