### PR TITLE
2 packages from returntocorp/semgrep

### PR DESCRIPTION
**Pull request by aryx**
This pull-request concerns:
- `ast_generic.1.8.0`: Abstract Syntax Tree (AST) supporting 31 programming languages
- `lib_parsing.1.12.0`: Small library to help writing parsers

---
* Homepage: https://semgrep.dev
* Source repo: git+https://github.com/returntocorp/semgrep
* Bug tracker: https://github.com/returntocorp/semgrep/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by aryx** [comment]
macos runner errors seem unrelated

**Comment by aryx** [comment]
@kit-ty-kate all errors seem like internal errors. What should we do in those cases? I should manually retrigger the CI jobs
or reviewers look at those CI job details and can see when the issue is legitimate vs internal error?

**Comment by kit-ty-kate** [comment]
You can click the `Rebuild failed` button to restart those jobs.

**Comment by aryx** [comment]
yeah! all green.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
