### PR TITLE
[new release] goblint-cil (2.0.2)

### PR DESCRIPTION
**Pull request by sim642**
A front-end for the C programming language that facilitates program analysis and transformation

- Project page: <a href="https://github.com/goblint/cil">https://github.com/goblint/cil</a>

##### CHANGES:

* Rename `Rmtmps` to `RmUnused` (goblint/cil#135).
* Add option to add return statement to `noreturn` functions (goblint/cil#129).
* Fix empty `if`s being removed (goblint/cil#140).
* Fix `_Float128` support (goblint/cil#118, goblint/cil#119).
* Fix C11 `_Alignas` computation (goblint/cil#130).
* Fix renaming and merging of `inline` functions based on C standard (goblint/cil#120, goblint/cil#124).
* Fix `Pretty` not resetting all global state between calls (goblint/cil#133, goblint/cil#134).
* Fix `fundec` location in merger (goblint/cil#139).
* Fix `cilly` patcher (goblint/cil#128).
* Disable basename by default in parser.

### CODE REVIEW

**Comment by sim642** [comment]
CI failures:

1. goblint revdeps: `failed: Unbound module Rmtmps`.

    I'll add upper bounds.

2. oraclelinux-9: `# Can't locate FindBin.pm in @INC (you may need to install the FindBin module)`.

    Ruby seems somehow broken on Oraclelinux 9. There was a fix to conf-ruby previously (#22003), but Oraclelinux 9 is new since then. The oraclelinux-8 CI jobs work fine.

3. freebsd:
    ```
    #=== ERROR while compiling conf-gcc.1.0 =======================================#
    "gcc": command not found.
    ```
    Depexts don't seem to install gcc on FreeBSD.

4. fedora-38-ocaml-5.0: `Could not update repository "default": /usr/bin/opam: "rmdir" failed on /home/opam/.opam/repo/default.new: No such file or directory`.

    Seems to be some CI problem.

**Comment by mseri** [comment]
Fixes for the failing tests have been presented here: https://github.com/ocaml/opam-repository/pull/24406/files
Perhaps you want to include them in 2.0.2?

**Comment by sim642** [comment]
The patches are for goblint, not goblint-cil.

**Comment by mseri** [comment]
A you are right. I guess we have to live with the oraclelinux failures then.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
