### PR TITLE
new file:   packages/batteries/batteries.3.6.0/opam

### PR DESCRIPTION
**Pull request by UnixJunkie**
do not merge; for CI tests only currently

### CODE REVIEW

**Comment by mseri** [comment]
Tests look good fwiw

**Comment by UnixJunkie** [comment]
issued the final tag; you can remove the do-not-merge label and merge this PR if everything is OK

**Comment by UnixJunkie** [comment]
this is the first official release of batteries which is ocaml-5 compatible

**Comment by mseri** [comment]
I have fixed the broken revdeps separately (they are not broken by to this release anyway)

**Pull request merged**
