### PR TITLE
[new release] decoders, decoders-ezjsonm and decoders-yojson (0.1.0)

### PR DESCRIPTION
**Pull request by mattjbray**
Elm-inspired decoders for Ocaml

- Project page: <a href="https://github.com/mattjbray/ocaml-decoders">https://github.com/mattjbray/ocaml-decoders</a>
- Documentation: <a href="https://mattjbray.github.io/ocaml-decoders/decoders">https://mattjbray.github.io/ocaml-decoders/decoders</a>

##### CHANGES:

Initial release.

### CODE REVIEW

**Comment by mattjbray** [comment]
Continued from #12704

**Comment by mseri** [comment]
Looks good. I can see that you have test dependencies but no `run-test` stanza. Have you disable the test on purpose/do you want to enable them?

**Comment by mattjbray** [comment]
@mseri good spot, it was missing from `decoders-yojson.opam`

**Comment by mseri** [comment]
Looks good. Thanks!

**Pull request merged**
