### PR TITLE
[new release] ounit-lwt and ounit (2.1.2)

### PR DESCRIPTION
**Pull request by gildor478**
OUnit testing framework (Lwt)

- Project page: <a href="https://github.com/gildor478/ounit">https://github.com/gildor478/ounit</a>
- Documentation: <a href="https://gildor478.github.io/ounit/">https://gildor478.github.io/ounit/</a>

### Fixed                                                                       
- Fix assert_raises type, which has been inadvertently changed during the       
  migration to dune.                                                            
- Add unix dependency to ounit.advanced.

### CODE REVIEW

**Comment by mseri** [comment]
The only one that may have something to do with ounit is qml failure. All the rest seems to be unrelated (and a good source for fixing opam files)

**Comment by gildor478** [comment]
Summary of failures:
- diet.0.2 -> deprecation warnings turned into errors
- dtoa.0.1 -> no remote tarball
- gapi-ocaml.0.3.5 -> monad-custom missing
- gapi-ocaml.0.3.6 -> missing netsys modules
- hamt.1.0.0 -> missing core_bench package
- key-parsers.0.9.2 -> type error
- lambdasoup.0.6.2 -> bad remote checksum
- llvm.* -> version mismatch with installed C library
- markup.0.7.6 -> missing lwt.unix library
- mecab.0.0.0 -> failing tests (running with ounit, but failing)
- mustache.3.0.0 -> type error (string vs byte)
- mustache.3.0.2 -> type error (string vs byte)
- osc.0.1.4 -> missing exec sclang
- pcap-format.0.5.0 -> missing Array1.map_file
- pgx_lwt.0.1 ->  failing tests (running with ounit, but failing)
- qcow.0.10.0 ->  failing tests (running with ounit, but failing)
- sanlock.0.0.9 -> sanlock daemon isn't running
- scid.1.0 -> missing file lib_test/suite.mly
- semver.0.1.0 -> bad oasis test (No variable test_semverh defined)
- session.0.1.0 -> missing postgresql package
- yices2.0.0.2 -> fail to run /usr/bin/make ""
- yices2.0.0.3 -> fail to run /usr/bin/make ""
- zmq.3.2-0 -> C stub fails to compile
- zmq.3.2-1 -> C stub fails to compile
- zmq.3.2-2 -> C stub fails to compile
- zmq.5.0.0 ->   failing tests (running with ounit, but failing)

**Comment by mseri** [comment]
Thanks!

**Comment by gildor478** [comment]
Argh! I have a pending change with the fix for 10 packages.

**Comment by mseri** [comment]
Opa. Can you send it on a new PR?

**Comment by gildor478** [comment]
Working on the fix in a new PR

I can also provide list of possible solutions for the packages that actually have an error.

**Comment by gildor478** [comment]
See #14890 for the extra fixes.

Remediations for other packages:
- Remove the package
  - dtoa.0.1 -> no remote tarball
  - lambdasoup.0.6.2 -> bad remote checksum
- Fix the package (simple fix):
  -  gapi-ocaml.0.3.5 -> monad-custom missing
  - gapi-ocaml.0.3.6 -> missing netsys modules
  - hamt.1.0.0 -> missing core_bench package
  - markup.0.7.6 -> missing lwt.unix library
  - session.0.1.0 -> missing postgresql package
- Stop running tests:
  - diet.0.2 -> deprecation warnings turned into errors
  - osc.0.1.4 -> missing exec sclang
  - pgx_lwt.0.1 -> failing tests (running with ounit, but failing)
  - qcow.0.10.0 -> failing tests (running with ounit, but failing)
  - sanlock.0.0.9 -> sanlock daemon isn't running
  - key-parsers.0.9.2 -> type error
  - mecab.0.0.0 -> failing tests (running with ounit, but failing)
  - yices2.0.0.2 -> fail to run /usr/bin/make ""
  - yices2.0.0.3 -> fail to run /usr/bin/make ""
  - zmq.5.0.0 -> failing tests (running with ounit, but failing)
- Limit OCaml version:
  - mustache.3.0.0 -> type error (string vs byte)
  - mustache.3.0.2 -> type error (string vs byte)
  - pcap-format.0.5.0 -> missing Array1.map_file
  - zmq.3.2-0 -> C stub fails to compile
  - zmq.3.2-1 -> C stub fails to compile
  - zmq.3.2-2 -> C stub fails to compile

Don't know section:
llvm.* -> version mismatch with installed C library
scid.1.0 -> missing file lib_test/suite.mly
semver.0.1.0 -> bad oasis test (No variable test_semverh defined)

**Comment by gildor478** [comment]
@mseri let me know what you want to do with the possible remediations. I am willing to fix some of them -- so that the next version of OUnit will be faster to release.

**Comment by mseri** [comment]
Wow, thank you very much. And thanks for offering to fix some of those packages, it will release us from a lot of work!

I have some suggestions:

- For the ones incompatible with safe strings we can add a dependency on `base-unsafe-string` instead of adding a bound on ocaml.

- For `zmq` let's ping @andersfugmann or @Leonidas-from-XIV 

- For `lambdasoup` and `dtoa` let's ping @aantron and @mroch: do you know what happened to the tarball? Is it possible to re-upload it?

- We don't need to do anything about llvm

- We can also disable semver 0.1.0 tests

- For `scid` let's ping @vbmithr

**Comment by aantron** [comment]
I don't know why the lambdasoup checksum would be wrong. It's the normal GitHub release archive, it's still there, and it hasn't changed, to my knowledge.

**Comment by avsm** [comment]
@aantron, it looks like you are using the github-generated archive:

```
  src: "https://github.com/aantron/lambda-soup/archive/0.6.3.tar.gz"
```

instead of a release asset which you uploaded (as done by, e.g. dune-release).  The github-generated ones seem vulnerable to being repacked whenever they change their infrastructure...

**Comment by mseri** [comment]
@avsm I can never remember how to do that, but I think we can get it from the opam cache somewhere and re-upload it, right?

**Comment by andersfugmann** [comment]
Zmq 3.x is quite old, so we should limit the ocaml version. Should I create a PR?

**Comment by avsm** [comment]
@mseri or just generate a release archive via dune-release; could do a dummy `p1` release as @aantron prefers.

**Comment by fdopen** [comment]
Your workaround for renaming oUnit doesn't work on windows and probably with other filesystems that are case insensitive. (Sorry to report it here, but you've closed the issues page, although it is mentioned inside the opam file)
- https://github.com/gildor478/ounit/blob/d0e06a99cc2afa0ba29abd99c2b1f7e228f75ab0/Makefile#L54 will install a directory called oUnit
- https://github.com/gildor478/ounit/blob/d0e06a99cc2afa0ba29abd99c2b1f7e228f75ab0/Makefile#L55 will re-use this directory and overwrite its content, because the directories oUnit and ounit are identic.
- dune will fail, if `oUnit` is referenced instead of `ounit` (the name of the library seems to be determined by the `dune-package` file, not the directory name)

**Comment by aantron** [comment]
That is disappointing about GitHub. I am still not sure of the explanation, though, because out of my projects, only Lambda Soup has ever been affected. I am ok with any way of resolving this, please let me know if you want me to do something.

**Comment by andersfugmann** [comment]
I've been trying to fix zmq.3.2-*, and I'm unable to get it to compile on my own machine. Limiting the ocaml compiler is not enough. 

The problems seems to be:
1. The c-stub relies on definition of type unt64 and uint64, which (for some reason) seems to have dissapeared from my gcc installation.
2. My debian distribution no longer ships a `libzmq` version compatible with the code. The last working version is `zmq-3.2`, and debian's stable version is `4.3.1-4+deb10u1`

To me it does not seem worth it to maintain these old versions, so I vote to remove `zmq.3.2-*`packages from the opam repository. Comments?

**Comment by mseri** [comment]
Instead of removing them I'd mark them as `available: false`, so they are still part of the history and recoverable by somebody that needs the old version

**Comment by andersfugmann** [comment]
Perfect. Ill create a PR to do exactly that.

**Comment by gildor478** [comment]
> Your workaround for renaming oUnit doesn't work on windows and probably with other filesystems that are case insensitive. (Sorry to report it here, but you've closed the issues page, although it is mentioned inside the opam file)
> 
> * https://github.com/gildor478/ounit/blob/d0e06a99cc2afa0ba29abd99c2b1f7e228f75ab0/Makefile#L54 will install a directory called oUnit
> * https://github.com/gildor478/ounit/blob/d0e06a99cc2afa0ba29abd99c2b1f7e228f75ab0/Makefile#L55 will re-use this directory and overwrite its content, because the directories oUnit and ounit are identic.
> * dune will fail, if `oUnit` is referenced instead of `ounit` (the name of the library seems to be determined by the `dune-package` file, not the directory name)

Thanks for the report. Maybe you can open a bug and we'll discuss it here:
https://github.com/gildor478/ounit/issues

Have you actually tested this problem?
My AppVeyor tests seems to install OUnit fine on Windows:
https://ci.appveyor.com/project/gildor478/ounit#L336

**Comment by fdopen** [comment]
There is no 'issue page' at this repo. Did you disable it?
And the installation step is not the problem. The error happens, when you try to use oUnit from dune after the installation.

**Comment by gildor478** [comment]
@fdopen I was sure I have enabled it -- and I was wrong. I have re-enabled the issue page on https://github.com/gildor478/ounit/issues.

I propose we continue the discussion on the issue.

**Comment by gildor478** [comment]
FYI, the bug on Windows is tracked here gildor478/ounit#8. @fdopen provided me with a way to reproduce and I need to fix the bug.

**Pull request merged**
