### PR TITLE
Package ocsigenserver.3.0.0

### PR DESCRIPTION
**Pull request by jrochel**
See also the previous incarnation of this PR : https://github.com/ocaml/opam-repository/pull/18577

### CODE REVIEW

**Comment by jrochel** [comment]
@kit-ty-kate Hi there. Is there something I should do about this PR, maybe reduce its footprint? I feel that I cannot do anything about the various compilation errors. There reasons are either problems in other packages, operating systems, etc.

**Comment by kit-ty-kate** [comment]
Hi, sorry, there was still some failures in ocsigenserver itself:
```
# File "ocsigen_cohttp.ml", line 299, characters 5-16:
# 299 |     ~tls_own_key () >>= fun conduit_ctx ->
#            ^^^^^^^^^^^
# Error: The function applied to this argument has type
#          ?tls_server_key:Conduit_lwt_unix.tls_server_key ->
#          Conduit_lwt_unix.ctx Lwt.t
# This argument cannot be applied with label ~tls_own_key
# make[2]: *** [Makefile:61: ocsigen_cohttp.cmo] Error 2
# make[2]: Leaving directory '/home/opam/.opam/4.11/.opam-switch/build/ocsigenserver.3.0.0/src/server'
# make[1]: *** [Makefile:6: all] Error 2
# make[1]: Leaving directory '/home/opam/.opam/4.11/.opam-switch/build/ocsigenserver.3.0.0/src'
# make: *** [Makefile:8: all] Error 2
```
I'll try my best to fix everything, if there are more, by tonight.

**Comment by kit-ty-kate** [comment]
Thanks! I'm really sorry for the very long delay. That a combination of forgetting about it, getting discouraged at reading logs I'm not familiar with, getting distracted and being busy with other things.

Could you return the fix in the opam file upstream?

**Comment by jrochel** [comment]
Thanks a lot! I completely understand the long delay. I have applied the fix upstream.

**Pull request merged**
