### PR TITLE
touist.3.1.0 - via opam-publish

### PR DESCRIPTION
**Pull request by maelvalais**
The solver for the Touist language

The Touist language is a friendly language for writing propositional
logic and logic on real and integers (SMT). This language aims to
formalize real-life problems (e.g., the sudoku can be solved in a few
lines). Touist embeds the minisat solver (for propositional logic) and
the yices2 solver (optional, for SMT logic). It can also generate the
DIMACS, SMT2 and latex formats from you touist file. To use the SMT
solver, install yices2 with

   opam install yices2

---
* Homepage: http://touist.github.io
* Source repo: https://github.com/touist/touist.git
* Bug tracker: https://github.com/touist/touist/issues

---

Pull-request generated by opam-publish v0.3.4

### CODE REVIEW

**Comment by avsm** [comment]
Seeing a checksum error:

```
[ERROR] Bad checksum for
        /home/opam/.opam/packages.dev/touist.3.1.0/v3.1.0.tar.gz:
          - 8519d0e79d3b8c9a8d908d70c82678ba [expected result]
          - 5855815d9ad279ab057038e5835a52e5 [actual result]
        This may be fixed by running `opam update`.

```

**Comment by maelvalais** [comment]
Thanks! I'll fix it asap
Le mar. 9 mai 2017 à 13:00, Anil Madhavapeddy <notifications@github.com> a
écrit :

**Comment by maelvalais** [comment]
Hi @avsm,
Just wondering, the CI process does not check the depopts?

This PR is ready to be published! 😀

**Comment by avsm** [comment]
> Just wondering, the CI process does not check the depopts?

It doesn't yet, but the DataKit version will soon... just waiting to upgrade some hardware first :-)  Thanks for the PR!

**Pull request merged**
