### PR TITLE
fixed compatibility with camlp4.4.02+7

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
The two Travis failures are due to the fact that clang-3.6 doesn't exist on Ubuntu 12.04 LTS.
They are not important.

**Comment by UnixJunkie** [comment]
I think this PR should be accepted.

**Comment by yallop** [comment]
I tried this locally, with the following result:

```
#=== ERROR while installing clangml.3.6.0.3 ===================================#
# opam-version 1.2.2 (391297300524717e1475deaea37bca287c7f5e36)
# os           linux
# command      make
# path         /home/jeremy/.opam/4.02.3/build/clangml.3.6.0.3
# compiler     4.02.3
# exit-code    2
# env-file     /home/jeremy/.opam/4.02.3/build/clangml.3.6.0.3/clangml-25638-e0ba4f.env
# stdout-file  /home/jeremy/.opam/4.02.3/build/clangml.3.6.0.3/clangml-25638-e0ba4f.out
# stderr-file  /home/jeremy/.opam/4.02.3/build/clangml.3.6.0.3/clangml-25638-e0ba4f.err
### stdout ###
# [...]
# plugin/c++/OCamlVisitor/Decl.o: In function `OCamlVisitor::translate_declaration_name(clang::DeclarationName const&)':
# /home/jeremy/.opam/4.02.3/build/clangml.3.6.0.3/_build/plugin/c++/OCamlVisitor/Decl.cpp:10: undefined reference to `clang::DeclarationName::getAsString() const'
# /home/jeremy/.opam/4.02.3/build/clangml.3.6.0.3/_build/plugin/c++/OCamlVisitor/Decl.cpp:12: undefined reference to `clang::DeclarationName::getAsString() const'
# /home/jeremy/.opam/4.02.3/build/clangml.3.6.0.3/_build/plugin/c++/OCamlVisitor/Decl.cpp:15: undefined reference to `clang::DeclarationName::getAsString() const'
# /home/jeremy/.opam/4.02.3/build/clangml.3.6.0.3/_build/plugin/c++/OCamlVisitor/Decl.cpp:18: undefined reference to `clang::DeclarationName::getAsString() const'
# /home/jeremy/.opam/4.02.3/build/clangml.3.6.0.3/_build/plugin/c++/OCamlVisitor/Decl.cpp:30: undefined reference to `clang::DeclarationName::getAsString() const'
# plugin/c++/OCamlVisitor/Decl.o:/home/jeremy/.opam/4.02.3/build/clangml.3.6.0.3/_build/plugin/c++/OCamlVisitor/Decl.cpp:33: more undefined references to `clang::DeclarationName::getAsString() const' follow
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# Command exited with code 1.
# Makefile:15: recipe for target 'mainClang.native' failed
### stderr ###
# make: *** [mainClang.native] Error 10
```

**Comment by UnixJunkie** [comment]
This is due to the dual ABI thing of recent gcc.
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
I have to investigate if I can fix this.

**Comment by UnixJunkie** [comment]
I found a way out.
Thanks Jeremy for testing this.
I will submit another pull request soon.

**Pull request closed without merging**
