### PR TITLE
Package qcstm.0.1

### PR DESCRIPTION
**Pull request by jmid**
### `qcstm.0.1`
A simple state-machine framework for OCaml based on QCheck

---
* Homepage: https://github.com/jmid/qcstm
* Source repo: git+https://github.com/jmid/qcstm.git
* Bug tracker: https://github.com/jmid/qcstm/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by mseri** [comment]
The url field, pointing at the sources to build, is missing

**Comment by jmid** [comment]
> The url field, pointing at the sources to build, is missing

Thanks, that certainly helped!
A meta-comment: I was simply trying to mimic the example given at the top of https://opam.ocaml.org/doc/Packaging.html 
I think adding a `url`-field to this first opam-file example could be beneficial for a lot newcomers like me (I've noticed I'm not the only one making this mistake). I've thus created an issue to this effect.
Thanks again 🙂

**Comment by kit-ty-kate** [comment]
ocamlfind and ocamlbuild don't seem to be used at runtime so I tagged them as build dependencies.
Could you return this fix upstream?

Seems good otherwise.

**Comment by jmid** [comment]
> ocamlfind and ocamlbuild don't seem to be used at runtime so I tagged them as build dependencies.

OK to the build dependencies. If users want to play with this, e.g., in utop, they'll need to load the module. utop uses ocamlfind underneath as far as I understand, but then users will probably already have ocamlfind installed anyway.

> Could you return this fix upstream?

Sure, just to clarify as I'm not much of a git user: Do you want me to merge this in my opam-repository branch, make the change in the package's git repo qcstm.opam file (so it is addressed for future releases), or the former + retag as 0.1 release and recalculate md5-sum?

**Comment by kit-ty-kate** [comment]
> make the change in the package's git repo qcstm.opam file (so it is addressed for future releases)

just that if that's ok. Your opam-repository branch is already updated and there is no need for retagging as the opam file inside the archive doesn't matter.

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by jmid** [comment]
Thanks for merging - yes, I'll make the change in repo's qcstm.opam file shortly 🙂

**Pull request merged**
