### PR TITLE
Package iri.0.5.0

### PR DESCRIPTION
**Pull request by zoggy**
### `iri.0.5.0`
Implementation of Internationalized Resource Identifiers (IRIs)

---
* Homepage: https://framagit.org/zoggy/ocaml-iri
* Source repo: git+https://framagit.org/zoggy/ocaml-iri.git
* Bug tracker: https://framagit.org/zoggy/ocaml-iri/-/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks! Could you return the fixes to the opam file upstream?

**Comment by zoggy** [comment]
Ok, I modified the iri.opam file in ocaml-iri repo. By the way, how is opam supposed to known how to uninstall a package now that the ``remote:`` field is removed ?

**Comment by kit-ty-kate** [comment]
Since opam 2.0, every installed files are tracked down during installation and removed appropriately when uninstalling.

**Comment by zoggy** [comment]
Ah, nice :-) Thanks !

**Pull request merged**
