### PR TITLE
[new release] ppx_factory (0.0.0)

### PR DESCRIPTION
**Pull request by NathanReb**
PPX to derive factories and default values

- Project page: <a href="https://github.com/cryptosense/ppx_factory">https://github.com/cryptosense/ppx_factory</a>
- Documentation: <a href="https://cryptosense.github.io/ppx_factory/doc">https://cryptosense.github.io/ppx_factory/doc</a>

##### CHANGES:

*2019-03-07*

### Added

- Initial release

### CODE REVIEW

**Comment by mseri** [comment]
Is the version `0.0.0` on purpose?

**Comment by NathanReb** [comment]
I guess, is there anything wrong with version 0.0.0 ?

**Comment by mseri** [comment]
Nothing, just unusual, so I was double checking

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
