### PR TITLE
[new release] irmin et al. (2.6.1)

### PR DESCRIPTION
**Pull request by CraigFe**
##### CHANGES:

This release contains 2.6.0 plus the changes described in 2.5.4.

### CODE REVIEW

**Comment by CraigFe** [comment]
I'm not sure why Camelus reached this conclusion, but it doesn't look good :stuck_out_tongue: Are there logs that I can inspect?

**Comment by kit-ty-kate** [comment]
@CraigFe camelus is very opaque. But Camelus is testing your branch vs master so if yours is slightly out-of-date with master it makes it a bit unhappy sometimes. I don't know, feel free to ignore it, we do ignore it ourselves anyway

**Comment by kit-ty-kate** [comment]
However do you know why the `Test commits and graphs.` test is failing only on opam 2.1, not 2.0? Does it take some kind of environment variable?

**Comment by CraigFe** [comment]
Thanks @kit-ty-kate. I've rebased to see if that makes Camelus happy. I'm not sure why `Test commits and graphs` was failing on 2.1; AFAIK we should have no difference in behaviour due to Opam versions in our test suite. It's possible it was just a spurious failure... will see if it crops up again this time.

**Comment by kit-ty-kate** [comment]
> It's possible it was just a spurious failure... will see if it crops up again this time.

Indeed it disappeared. I'll remove the tests if it pops-up again. Would you be able to track this?

The rebase seem to have removed the constraint against 32bit systems on irmin-git though. Could you put it back?:
```
# test.exe: internal error, uncaught exception:
#           (Invalid_argument Bytes.create)
#           Raised by primitive operation at Astring_string.concat in file "src/astring_string.ml", line 68, characters 12-32
#           Called from Alcotest_engine__Core.Make.read_tail in file "src/alcotest-engine/core.ml", line 157, characters 6-43
#           Called from Fmt.append in file "src/fmt.ml" (inlined), line 69, characters 31-42
#           Called from Alcotest_engine__Core.Make.pp_error in file "src/alcotest-engine/core.ml", line 210, characters 6-188
#           Called from Fmt.append in file "src/fmt.ml" (inlined), line 69, characters 31-42
#           Called from Alcotest_engine__Core.Make.pp_error in file "src/alcotest-engine/core.ml", line 209, characters 4-225
#           Called from Stdlib__list.iter in file "list.ml", line 110, characters 12-15
#           Called from Alcotest_engine__Pp.Make.suite_results in file "src/alcotest-engine/pp.ml", line 232, characters 8-94
#           Called from Alcotest_engine__Core.Make.run_tests.(fun) in file "src/alcotest-engine/core.ml", line 413, characters 4-42
#           Called from Alcotest_engine__Monad.Extend.Infix.(>|=).(fun) in file "src/alcotest-engine/monad.ml", line 32, characters 46-51
#           Called from Alcotest_engine__Core.Make.run_with_args in file "src/alcotest-engine/core.ml", line 438, characters 4-357
#           Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 25, characters 19-24
#           Called from Cmdliner.Term.run in file "cmdliner.ml", line 117, characters 32-39
#   [OK]          misc                         5   git blobs of generic.
# 
# ┌──────────────────────────────────────────────────────────────────────────────┐
# │ [FAIL]        SLOW_GIT                     0   Commit wide node.             │
# └──────────────────────────────────────────────────────────────────────────────┘
```

**Comment by CraigFe** [comment]
> Indeed it disappeared. I'll remove the tests if it pops-up again. Would you be able to track this?

Will do :+1:

> The rebase seem to have removed the constraint against 32bit systems on irmin-git though. Could you put it back?:

Done.

**Comment by kit-ty-kate** [comment]
Here is another spurious failure: https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/c7e9e2d1096d91315f9c091aa4a9fb0d4d592664/variant/opam-2.0,compilers,4.12,irmin-fs.2.6.1,revdeps,irmin-unix.2.6.1

I disabled the tests for `irmin-pack` and `irmin-unix` is that ok for you? If so I'll merge this tomorrow.

**Comment by samoht** [comment]
> I disabled the tests for irmin-pack and irmin-unix is that ok for you? If so I'll merge this tomorrow.

yea that's ok - we are still investigating to understand where these spurious issues come from.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
