### PR TITLE
added mbox and maildir archive samples, removed bz2 dependency

### PR DESCRIPTION
**Pull request by gregtatcam**

### CODE REVIEW

**Comment by whitequark** [comment]
4.01.0 build fails:
```
# File "imap_crypto.mli", line 18, characters 32-37:
# Error: Unbound type constructor bytes
# Command exited with code 2.
```

**Comment by gregtatcam** [comment]
fixed the bytes issue

**Comment by avsm** [comment]
@gregatcam : you might want to setup a Travis on imaplet-lwt directly to make these easier to find. See https://github.com/ocaml/ocaml-travisci-skeleton for instructions

**Comment by gregtatcam** [comment]
It’s on my to-do list for this week…

**Pull request closed without merging**
