### PR TITLE
Release Alt-Ergo 2.4.0 (all packages)

### PR DESCRIPTION
**Pull request by ACoquereau**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There seems to be a missing dependency:
```
#=== ERROR while compiling alt-ergo-lib.2.4.0 =================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.11.1 | pinned(https://github.com/OCamlPro/alt-ergo/archive/2.4.0.tar.gz)
# path                 ~/.opam/4.11/.opam-switch/build/alt-ergo-lib.2.4.0
# command              ~/.opam/4.11/bin/ocaml unix.cma configure.ml alt-ergo-lib --libdir /home/opam/.opam/4.11/lib --mandir /home/opam/.opam/4.11/man
# exit-code            2
# env-file             ~/.opam/log/alt-ergo-lib-15-6a5a1c.env
# output-file          ~/.opam/log/alt-ergo-lib-15-6a5a1c.out
### output ###
# Found opam in path.
# Using default value for 'prefix' : /home/opam/.opam/4.11
# Using provided value for 'libdir' : /home/opam/.opam/4.11/lib
# Using provided value for 'mandir' : /home/opam/.opam/4.11/man
# Generating file src/lib/util/config.ml...done.
# Generating file src/bin/text/flags.dune...done.
# Generating file Makefile.config...done.
# Found dune in path.
# Error: The following libraries are missing in the default context:
# - cmdliner
# Hint: try:
#   opam install cmdliner
```

**Comment by ACoquereau** [comment]
Thanks, https://github.com/OCamlPro/alt-ergo/pull/425 should resolve that. I'll update this PR when the build will be fixed

**Comment by mseri** [comment]
There is still a mysterious fail on all builds:
```
Processing 61/62: [altgr-ergo: dune subst]
+ /home/opam/.opam/4.04/bin/dune "subst" (CWD=/home/opam/.opam/4.04/.opam-switch/build/altgr-ergo.2.4.0)
Processing 61/62: [altgr-ergo: dune build]
+ /home/opam/.opam/4.04/bin/dune "build" "-p" "altgr-ergo" "-j" "47" (CWD=/home/opam/.opam/4.04/.opam-switch/build/altgr-ergo.2.4.0)
-   altgr-ergo src/bin/gui/altgr-ergo.1 (exit 2)
- (cd _build/default/src/bin/gui && ../../../../install/default/bin/altgr-ergo --help=groff &> _build/default/src/bin/gui/altgr-ergo.1
[ERROR] The compilation of altgr-ergo failed at "/home/opam/.opam/4.04/bin/dune build -p altgr-ergo -j 47".

#=== ERROR while compiling altgr-ergo.2.4.0 ===================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.04.2 | pinned(https://github.com/OCamlPro/alt-ergo/archive/2.4.0.tar.gz)
# path                 ~/.opam/4.04/.opam-switch/build/altgr-ergo.2.4.0
# command              ~/.opam/4.04/bin/dune build -p altgr-ergo -j 47
# exit-code            1
# env-file             ~/.opam/log/altgr-ergo-15-24a5fe.env
# output-file          ~/.opam/log/altgr-ergo-15-24a5fe.out
### output ###
#   altgr-ergo src/bin/gui/altgr-ergo.1 (exit 2)
# (cd _build/default/src/bin/gui && ../../../../install/default/bin/altgr-ergo --help=groff &> _build/default/src/bin/gui/altgr-ergo.1
```

**Comment by ACoquereau** [comment]
I was able to reproduce this error on a fresh linux system, WLS (`git clone`, `opam install .`, error). But after i tried to locally build the project with `dune` (without error), the error disappear, the build is successful and i am unable to reproduce it anymore. I tried different fresh switches, even remove my `.opam` in my home, and the build is still successful.

**Comment by kit-ty-kate** [comment]
I was able to reproduce the issue locally. It all comes down to a config file loaded too early:
```
$ _build/install/default/bin/altgr-ergo --help=groff
Fatal error: exception Sys_error("/home/opam/.config/altgr-ergo.conf: No such file or directory")
```

**Comment by ACoquereau** [comment]
Thanks we also were able to reproduce this issue, https://github.com/OCamlPro/alt-ergo/pull/429 should resolve this

**Comment by ACoquereau** [comment]
Since libgtksourceview2 has been removed from `debian-testing` some month ago we are aware that `Altgr-Ergo` can't be available on this distribution.

**Comment by kit-ty-kate** [comment]
@mseri the accept failures feature won't work here because of issues similar to https://github.com/ocaml/opam/issues/4493

**Comment by kit-ty-kate** [comment]
Also it should have been attached in the `conf-gtksourceview` package if it didn't have this issue, since this was the package that failed.
I reverted the commit and we'll ignore the issue for now. It's fine.

Thanks a lot!

**Comment by ACoquereau** [comment]
Thanks !

**Pull request merged**
