### PR TITLE
[new release] pb-plugin and pb (1.0.0)

### PR DESCRIPTION
**Pull request by rgrinberg**
Plugin for generating pb protobuf message descriptions

- Project page: <a href="https://github.com/yallop/ocaml-pb">https://github.com/yallop/ocaml-pb</a>

### CODE REVIEW

**Comment by mseri** [comment]
It needs a lower bound on ocaml starting from 4.08 or needs stlib-shims: 
```
#=== ERROR while compiling pb-plugin.1.0.0 ====================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/yallop/ocaml-pb/releases/download/1.0.0/pb-plugin-1.0.0.tbz)
# path                 ~/.opam/4.03/.opam-switch/build/pb-plugin.1.0.0
# command              ~/.opam/4.03/bin/dune build -p pb-plugin -j 2 @install
# exit-code            1
# env-file             ~/.opam/log/pb-plugin-23-c5eb05.env
# output-file          ~/.opam/log/pb-plugin-23-c5eb05.out
### output ###
#       ocamlc pb-plugin/src/.pb_plugin.eobjs/byte/pb_plugin.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlc.opt -w -40 -g -bin-annot -I pb-plugin/src/.pb_plugin.eobjs/byte -I /home/opam/.opam/4.03/lib/angstrom -I /home/opam/.opam/4.03/lib/batteries -I /home/opam/.opam/4.03/lib/faraday -I /home/opam/.opam/4.03/lib/integers -I /home/opam/.opam/4.03/lib/pb -no-alias-deps -o pb-plugin/src/.pb_plugin.eobjs/byte/pb_plugin.cmo -c -impl pb-plugin/src/pb_plugin.ml)
# File "pb-plugin/src/pb_plugin.ml", line 280, characters 4-16:
# Error: Unbound module Result
```

**Comment by rgrinberg** [comment]
I would prefer the constraint in this case. I will create a minor release that relaxes this constraint whenever I have time if you don't mind.

**Comment by mseri** [comment]
Fine with me. I am on mobile at the moment. Can you add the bound?

**Comment by mseri** [comment]
I’m merging with the lower bound on 4.08

**Pull request merged**
