### PR TITLE
3 packages from gitlab.inria.fr/fpottier/menhir/-/archive/20211215/archive.tar.gz

### PR DESCRIPTION
**Pull request by fpottier**
This pull-request concerns:
-`menhir.20211215`: An LR(1) parser generator
-`menhirLib.20211215`: Runtime support library for parsers generated by Menhir
-`menhirSdk.20211215`: Compile-time library for auxiliary tools related to
 Menhir

---
* Homepage: http://gitlab.inria.fr/fpottier/menhir
* Source repo: git+https://gitlab.inria.fr/fpottier/menhir.git
* Bug tracker: https://gitlab.inria.fr/fpottier/menhir/-/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by fpottier** [comment]
Hello! This is a major release of Menhir; the code back-end has been re-implemented from scratch. I am expecting some packages that depend on Menhir to break. (See [CHANGES](https://gitlab.inria.fr/fpottier/menhir/-/blob/master/CHANGES.md) for suggested repairs.) Please let me know if I can help suggest fixes for some of these packages. Thanks!

**Comment by kit-ty-kate** [comment]
I added the constraint to js_of_ocaml at least (https://github.com/ocaml/opam-repository/pull/20260). Let’s see if we can see a clearer revdeps check result

**Comment by fpottier** [comment]
Indeed, `js_of_ocaml-compiler.3.11.0` needs `menhir < 20211215`, but the fix is already in the `js_of_ocaml` repository, so their next release will work without a constraint.

**Comment by fpottier** [comment]
I have looked at some of the problems, and here is what I have found for now.

Packages that need menhir < 20211215, which I don't know how to fix:
```
pds
psmt2-frontend
```

Packages that need menhir < 20211215, for which I have made a PR upstream:
```
coin
smtlib-utils
tip-parser
toml
uuuu
zipperposition
```

Packages that need menhir < 20211215, already fixed upstream:
```
atd
```

**Comment by mseri** [comment]
Thanks a lot. Let me make it a Pr with the bounds and then we try again. I will do it asap

**Comment by fpottier** [comment]
Hello, just a ping to ask if this PR is looking good?

**Comment by mseri** [comment]
There is still a massive amount of failures. I hope I will be able to send another upper bounds PR before Christmas but can make no promise

**Comment by fpottier** [comment]
OK, thanks. I have tried to look at the packages that fail but saw nothing definitely related to Menhir 20211215 beyond the packages that I listed above. If you would like me to investigate some of the failures, please do let me know which packages I should look at.

**Comment by mseri** [comment]
In the latest run there are many new packages, like alt-ergo, failing as
```
alt-ergo.2.1.0 (failed: the code back-end requires the type of every nonterminal symbol to be)

#=== ERROR while compiling alt-ergo.2.1.0 =====================================#
# context              2.0.10 | linux/x86_64 | ocaml-base-compiler.4.13.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.13/.opam-switch/build/alt-ergo.2.1.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code            2
# env-file             ~/.opam/log/alt-ergo-1358-d0f245.env
# output-file          ~/.opam/log/alt-ergo-1358-d0f245.out
### output ###
# menhir -v parsers/why/why_parser.mly 
# Error: the code back-end requires the type of every nonterminal symbol to be
# known. Please specify the type of every symbol via %type declarations, or
# enable type inference (look up --infer in the manual).
# Type inference is automatically enabled when Menhir is used via Dune.
# The types of the following nonterminal symbols are unknown:
# ac_modifier
# array_assignement
# array_assignements
# bound
# decl
# filters
# ident
# label_with_type
# lexpr
# lexpr_or_dom
# list0_lexpr_sep_comma
# list0_logic_binder_sep_comma
# list0_primitive_type_sep_comma
# list1_constructors_sep_bar
# list1_decl
# list1_label_expr_sep_PV
# list1_label_sep_PV
# list1_lexpr_or_dom_sep_comma
# list1_lexpr_sep_comma
# list1_lexpr_sep_pv
# list1_logic_binder_sep_comma
# list1_multi_logic_binder
# list1_named_ident_sep_comma
# list1_primitive_type_sep_comma
# list1_trigger_sep_bar
# list1_type_var_sep_comma
# list2_lexpr_sep_comma
# logic_binder
# logic_type
# multi_logic_binder
# named_ident
# primitive_type
# record_type
# simple_expr
# sq
# theory_elt
# theory_elts
# trigger
# triggers
# type_var
# type_vars
# Makefile.users:323: .depend: No such file or directory
# make: *** [Makefile.users:298: parsers/why/why_parser.ml] Error 1
```

i think these have to do with menhir changes, otherwise I cannot explain why I never saw that failure before

**Comment by mseri** [comment]
I think it is just about adding upper bounds and notifying the maintainers, but it takes quite some time to prepare such PRs

**Comment by fpottier** [comment]
Yes, this one is definitely related to the new release of Menhir.

**Comment by fpottier** [comment]
I have created a PR for alt-ergo.

**Comment by mseri** [comment]
Thanks. I will check the other packages with the same failure and update the pr asap

**Comment by kit-ty-kate** [comment]
This failure looks weird. @fpottier could you have a look at it and tell us if it’s expected? (to me, looking at the source code it seems like a bug in menhir)
```
#=== ERROR while compiling openQASM.0.3.0 =====================================#
# context              2.0.10 | linux/x86_64 | ocaml-base-compiler.4.13.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.13/.opam-switch/build/openQASM.0.3.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p openQASM -j 31 @install
# exit-code            1
# env-file             ~/.opam/log/openQASM-105-8a5d98.env
# output-file          ~/.opam/log/openQASM-105-8a5d98.out
### output ###
#       ocamlc lib/.openQASM.objs/byte/openQASM__Parser.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.13/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.openQASM.objs/byte -intf-suffix .ml -no-alias-deps -open OpenQASM__ -o lib/.openQASM.objs/byte/openQASM__Parser.cmo -c -impl lib/parser.ml)
# File "lib/parser.ml", line 1862, characters 8-9:
# 1862 |       | U ->
#                ^
# Error: The constructor U expects 2 argument(s),
#        but is applied here to 0 argument(s)
#     ocamlopt lib/.openQASM.objs/native/openQASM__Parser.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.13/bin/ocamlopt.opt -w -40 -g -I lib/.openQASM.objs/byte -I lib/.openQASM.objs/native -intf-suffix .ml -no-alias-deps -open OpenQASM__ -o lib/.openQASM.objs/native/openQASM__Parser.cmx -c -impl lib/parser.ml)
# File "lib/parser.ml", line 1862, characters 8-9:
# 1862 |       | U ->
#                ^
# Error: The constructor U expects 2 argument(s),
#        but is applied here to 0 argument(s)
```

**Comment by fpottier** [comment]
> This failure looks weird. @fpottier could you have a look at it and tell us if it’s expected? (to me, looking at the source code it seems like a bug in menhir)

Indeed, there is a shadowing problem (there are two data constructors named `U`) which was correctly avoided by earlier versions of Menhir, and which 20211215 does not avoid. I will close this PR and prepare a new one with a fix.

**Comment by mseri** [comment]
Voqc was failing with a similar error, we may try to relax the upper bounds when you make the new release

**Comment by fpottier** [comment]
I have submitted [a new PR](https://github.com/ocaml/opam-repository/pull/20308).

**Pull request closed without merging**
