### PR TITLE
fix an incorrect package name in ocamldbi (postgres -> postgresql)

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by dsheets** [comment]
I believe there is still a conflict and this renaming is incorrect. The `postgres` package was removed by @mmottl in f91083e36028712f673f0cb3c614674f1793c1f9. This is a great reason to not allow removal of packages or at least automate it.

**Comment by avsm** [comment]
seems to compile for me fine with postgresql installed... @mmottl ?

**Comment by mmottl** [comment]
@avsm I think the old Postgres package was already obsolete by the time it was introduced into OPAM.  Packages that refer to it probably did so by mistake.  Not sure, but I think there shouldn't be any issues just renaming these dependencies.  For most part the API should be backward compatible.

@dsheets I agree that packages generally should not be removed, and maybe it was a mistake even in this particular case where an already obsolete package was uploaded to OPAM.

**Comment by avsm** [comment]
Thanks @mmottl! A manual build test reveals no failures with `docker run ocaml/opam sh -c "opam depext -ui postgresql && opam depext -ui ocamldbi"` so I'll go ahead and merge and fix up build failures if they arise later.

**Comment by dsheets** [comment]
It seems unlikely that `postgresql` is actually a depopt of `ocamldbi` as the original declared them incompatible. I think all mentions of `postgres` or `postgresql` should probably be removed here.

**Comment by avsm** [comment]
@dsheets it is a depopt; from the sources:

```
ifeq ($(HAVE_POSTGRES),1)
OCAMLCINCS += -I $(shell ocamlfind query postgres)
OCAMLOPTINCS += -I $(shell ocamlfind query postgres)
OCAMLCLIBS += postgres.cma
DBI_DRIVERS += dbi_postgres.ml
endif

ifeq ($(HAVE_POSTGRESQL),1)
OCAMLCINCS += -I $(shell ocamlfind query postgresql)
OCAMLOPTINCS += -I $(shell ocamlfind query postgresql)
OCAMLCLIBS += postgresql.cma
DBI_DRIVERS += dbi_postgresql.ml
endif
```

**Comment by dsheets** [comment]
So is `freetds` but it is listed as a `conflict`:

```
ifeq ($(HAVE_FREETDS),1)
OCAMLCINCS += -I $(shell ocamlfind query freetds)
OCAMLOPTINCS += -I $(shell ocamlfind query freetds)
OCAMLCLIBS += freetds.cma
DBI_DRIVERS += dbi_freetds.ml
endif
```

Perhaps the author of the original metadata knew that these features of `ocamldbi` were broken?

**Comment by mmottl** [comment]
`ocamldbi` is apparently somewhat special, because it supports various backends.  I'm not sure why it would want to support both, because `postgres` has not been actively maintained for many years and is superseded by `postgresql`.  Maybe `ocamldbi` was developed before that happened and never bothered to throw out support for `postgres`, which it should have by now.

**Comment by Chris00** [comment]
On 2016-05-31, Markus Mottl wrote:
> 
> ocamldbi is apparently somewhat special, because it supports various backends.  I'm not sure why it would want to support both, because postgres has not been actively maintained for many years and is superseded by postgresql. Maybe ocamldbi was developed before that happened and never bothered to throw out support for postgres, which it should have by now.

ocamldbi was indeed developed a long time ago.  It should be rewritten using modern features of OCaml (one day maybe...).

**Pull request merged**
