### PR TITLE
mirage-net: older versions depend on cstruct

### PR DESCRIPTION
**Pull request by planar**

### CODE REVIEW

**Comment by avsm** [comment]
could you merge this with #3915?

**Comment by yallop** [comment]
I think restarting the build should pick up the changes from #3915, since Travis tests by merging against master.

I've restarted the [failed job](https://travis-ci.org/ocaml/opam-repository/jobs/57350932).

**Comment by yallop** [comment]
It's now [failing](https://travis-ci.org/ocaml/opam-repository/jobs/57350932) because it's picking up [shared-memory-ring.0.3.1](https://github.com/ocaml/opam-repository/blob/master/packages/shared-memory-ring/shared-memory-ring.0.3.1/opam), which doesn't have the camlp4 dependency.

**Comment by avsm** [comment]
Added the fix for camlp4 in #3918 and restarted Travis again

**Pull request merged**
