### PR TITLE
Package dbf.0.1.1

### PR DESCRIPTION
**Pull request by pveber**
### `dbf.0.1.1`
DBF format parsing
This is a small library meant to parse dBase database files. Many
cases/variants are not handled, but it might already be useful.

---
* Homepage: https://github.com/pveber/dbf
* Source repo: git+https://github.com/pveber/dbf.git
* Bug tracker: https://github.com/pveber/dbf/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The `ppx_cstruct` package was missing from the dependency list as well as dune, which according to your `dune-project` file requires at least dune 1.9. Could you return the fix to the source repository?

**Comment by mseri** [comment]
Also rresult seemed to be missing. Please add that as well to the source repository opam file

**Comment by pveber** [comment]
Thanks you two, it should be fixed now.

**Comment by mseri** [comment]
Now it fails with:
```
#=== ERROR while compiling dbf.0.1.1 ==========================================#
5198# context     2.0.6 | linux/x86_64 | ocaml-system.4.09.1 | file:///home/travis/build/ocaml/opam-repository
5199# path        ~/.opam/ocaml-system/.opam-switch/build/dbf.0.1.1
5200# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p dbf -j 1
5201# exit-code   1
5202# env-file    ~/.opam/log/dbf-7636-0a5907.env
5203# output-file ~/.opam/log/dbf-7636-0a5907.out
5204### output ###
5205# [...]
5206# Error: Unbound value Unix.openfile
5207#     ocamlopt lib/.dbf.objs/native/dbf.{cmx,o} (exit 2)
5208# (cd _build/default && /usr/local/bin/ocamlopt.opt -w -40 -g -I lib/.dbf.objs/byte -I lib/.dbf.objs/native -I /home/travis/.opam/ocaml-system/lib/base -I /home/travis/.opam/ocaml-system/lib/base/base_internalhash_types -I /home/travis/.opam/ocaml-system/lib/base/caml -I /home/travis/.opam/ocaml-system/lib/base/md5 -I /home/travis/.opam/ocaml-system/lib/base/shadow_stdlib -I /home/travis/.opam/[...]
5209# File "lib/dbf.ml", line 253, characters 11-24:
5210# 253 |   let fd = Unix.openfile fn [O_RDONLY] 0 in
5211#                  ^^^^^^^^^^^^^
5212# Alert deprecated: module Core_kernel.Unix
5213# [since 2020-03] Core_kernel shadows Unix. Use Core.Unix, which overrides some of Unix's behavior. If necessary, Unix is available and unshadowed as Caml_unix.
5214# File "lib/dbf.ml", line 253, characters 11-24:
5215# 253 |   let fd = Unix.openfile fn [O_RDONLY] 0 in
5216#                  ^^^^^^^^^^^^^
5217# Error: Unbound value Unix.openfile
5218
5219
5220
5221
```

**Comment by pveber** [comment]
sorry, I messed up with my git history. New attempt is on its way.

**Comment by mseri** [comment]
Travis is happy now, the CI is being fuzzy.

**Pull request merged**
