### PR TITLE
apron: the version needs a v

### PR DESCRIPTION
**Pull request by mseri**
See https://github.com/ocaml/opam-repository/pull/24491

### CODE REVIEW

**Comment by mseri** [comment]
Ping @antoinemine

**Comment by antoinemine** [comment]
Hi. I'm not sure what I should do at this point. I see that a `v0.9.14` has been merged. I can't see it after `git update`, though, not sure why. But doing a new `opam publish -v v0.9.14` fail with ` [ERROR] Uncaught exception: "/usr/bin/git commit -m Package apron.v0.9.14"`.

**Comment by mseri** [comment]
You don't need to republish or do anything. The package should appear in the index soon with the correct version. The ping was just to inform you that I did re-release it with the v

**Comment by antoinemine** [comment]
OK, thanks!

**Pull request merged**
