### PR TITLE
Add plugin flag to opam-0install

### PR DESCRIPTION
**Pull request by dra27**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @talex5. Does it really make sense to have a command `opam 0install`? I’m not sure opam-0install is meant to be that user facing

**Comment by dra27** [comment]
I only hit this from the repro case in https://github.com/ocaml/opam/issues/4554#issue-811269537 and got bitten because opam 2.1 is more fastidious about plugins being tagged than 2.0 is (I think).

**Comment by dra27** [comment]
(I therefore have no strong opinion either way!)

**Comment by dra27** [comment]
xref https://github.com/ocaml-opam/opam-0install-solver/pull/34

**Comment by kit-ty-kate** [comment]
The issue is that `opam-0install` does not do any installation so it’s a bit weird to have such a command that only calls a solver.

Maybe if it was called `opam-solve`?

**Comment by dra27** [comment]
This appears to have been a typo in the original issue leading my slightly down the wrong garden path! Sorry for the noise...

**Pull request closed without merging**
