### PR TITLE
Genprint v0.3

### PR DESCRIPTION
**Pull request by progman1**
library for printing of values vis a vis the ocaml interpreter, but from within compilation units.

### CODE REVIEW

**Comment by progman1** [comment]
I generated the checksum and added it only to the repo opam file
and with it passing checks here I opam updated then tried an install. - checksum failure!
what am I doing wrong?!
thanks

**Comment by kit-ty-kate** [comment]
> what am I doing wrong?!

According to Github https://github.com/progman1/genprintlib/releases/tag/v0.3a you force-pushed the tag 2 hours ago.

**Comment by kit-ty-kate** [comment]
Anyway, here is the diff between the two archive:
```
diff -ru genprintlib-0.3a/genprint.opam new/genprintlib-0.3a/genprint.opam
--- genprintlib-0.3a/genprint.opam	2020-04-08 13:36:01.000000000 +0100
+++ new/genprintlib-0.3a/genprint.opam	2020-04-08 17:57:32.000000000 +0100
@@ -19,14 +19,13 @@
 
 depends: [
   "ocaml" {>= "4.04.1" & < "4.11"}
-  "dune"
-#{="1.9.0"}
+  "dune" {>="1.9.0"}
   "ppxlib"
   "cppo" {build}
   "stdlib-shims"
 ]
 
-url {
-  src: "https://github.com/progman1/genprintlib/archive/v0.3a.tar.gz"
-  checksum: "md5=337ab52d6db6c291eefbbdd773fc82d9"
-}
+#url {
+#  src: "https://github.com/progman1/genprintlib/archive/v0.3a.tar.gz"
+#  checksum: "md5=af5ac50329278ffc51f77ecbecfb99a8"
+#}
diff -ru genprintlib-0.3a/README.md new/genprintlib-0.3a/README.md
--- genprintlib-0.3a/README.md	2020-04-08 13:36:01.000000000 +0100
+++ new/genprintlib-0.3a/README.md	2020-04-08 17:57:32.000000000 +0100
@@ -98,7 +98,7 @@
 under [lib]) are treated as if they may have such sub-modules. 
 This may not always be appropriate as it imposes a performance cost.
 If this is annoying the environment variable [GENPRINT_ALL_LIBS=1] can be used to prevent the 
-search, which is appropriate if the values one is interested in are not displayed as __<abstr>__
+search, which is appropriate if the values one is interested in are not displayed as ```<abstr>```
 as a result.
 Local project code is always scanned for sub-modules.
```
In the future please do not force-push after a package has been released as it breaks packages here.

**Comment by progman1** [comment]
I pushed the dune dependency change yesterday and there were several changes after that.
this must be somehing to do with github not taking the current state as input to a release archive.
in any case the change I made today was to only add the checksum to my opam repo clone and push it up and submit the PR. the checksum is calculated from the downloaded v03a archive. 
what is left to go wrong?
the only thing I add a -f (force ) to is the /usr/bin/hub command for submitting the PR
as otherwise a meaningless error message is returned. 
is there a way of staying on a version number without bumping  it every mis-step on the way to
release?

**Pull request merged**
