### PR TITLE
Release caqti.1.0.0

### PR DESCRIPTION
**Pull request by paurkedal**
It's time for a stable release!

Changes since 0.11.0 include bug fixes, sub-second time precision for MariaDB, and adjustments of the driver API.

### CODE REVIEW

**Comment by paurkedal** [comment]
CI fails due to depext issues for the MariaDB client library (cf #12260). It would have been good to see the revdeps result, though I think that's blocked for now unless I split up the PR.

**Comment by kit-ty-kate** [comment]
Ok, could you at least add the `{build}` attribute to `dune` and remove the few unused references to `ocamlfind`?

I don't really understand why the `mariadb` package fails. There seems to be a missing dependency over `conf-mariadb` but I don't know how it got accepted if that's the case. cc @andrenth

**Comment by paurkedal** [comment]
Fixed opam files, thanks.  One ocamlfind dependency remains due to caqti-dynload using findlib.

There was a dependency on conf-mariadb at some point, but as far as I understand it did not work well due differences between distributions and limited functionality of depext.  I don't know the details, I just hope opam2 will solve it.

**Comment by paurkedal** [comment]
I have updated this PR to opam 2. (Using `opam-package-upgrade`, manual integration of descr, and `opam-publish --dry-run` to generate the final files.  I'll probably start using `opam-publish` for the whole PR process later as it worked well despite the complexity of the package.)

The failures now under travis are four cases of MariaDB client library incompatibilities and case (the first) of not finding the source for caqti, which I don't understand, since I can manually fetch the `urs.src` and verify the checksums.

**Comment by mseri** [comment]
The OSX failure seems to be hitting most of the packages. Maybe it has to do with the lack of `sha512` in some versions of osx? Ping @rjbou @AltGr

**Comment by rjbou** [comment]
@mseri yes, `sha512` is an option unavailable on some macOS openssl. Related discussion: https://github.com/ocaml/opam-repository/pull/12647#issuecomment-422727985

**Comment by paurkedal** [comment]
Thanks for the cross-reference. I switched the checksum to sha256.

**Comment by paurkedal** [comment]
Changing to `sha256` did not fix the issue on Xcode for me, but note also that the error message is different from the other PR:
```
ERROR] The sources of the following couldn't be obtained, aborting:
          - caqti.1.0.0

The command "bash -e .travis-ci.sh" exited with 40.

Done. Your build exited with 1.
/Users/travis/.travis/job_stages: line 339: shell_session_update: command not found
```
This was also the error when using `sha512`.

**Comment by mseri** [comment]
Thanks. The issue affects most packages and is not related to this pr. I am going to merge

**Pull request merged**
