### PR TITLE
ocaml-lua: add bound on OCaml version

### PR DESCRIPTION
**Pull request by damiendoligez**
Issue reported upstream: https://github.com/pdonadeo/ocaml-lua/issues/8

/cc @pdonadeo

### CODE REVIEW

**Comment by pdonadeo** [comment]
I think this one can be closed.

**Comment by damiendoligez** [comment]
@pdonadeo I've seen your PR #7241, but we still need to restrict the old versions to < 4.04, don't we?

**Comment by pdonadeo** [comment]
Formally you are totally right, but there are no reason in the this world for which one should want to install an older version of the package. There are no compatibility issues, and no API changes, only bug fixes.

From your point of view is it advisable to delete releases of ocaml-lua < 1.3 altogether?

**Comment by damiendoligez** [comment]
>Formally you are totally right, but there are no reason in the this world for which one should want to install an older version of the package. There are no compatibility issues, and no API changes, only bug fixes.

Here's one reason: I just say `opam install ocaml-lua` and the SMT solver decides to install an old version. I don't know why and I don't really care, unless it fails. If it's not going to work with OCaml 4.04, we need to record this fact in the package.

Or what if someone does an `opam switch export` of their package list under 4.03 and then tries to import it in 4.04? I'd rather have a nice error message from OPAM than a random compilation failure.

>From your point of view is it advisable to delete releases of ocaml-lua < 1.3 altogether?

This is another solution. Which one is preferred, that's a question for the @ocaml/opam-repository team in general.

**Comment by dsheets** [comment]
We generally prefer to keep older versions of packages in order to support users that have not upgraded the package or who cannot move to a new package version due to incompatible new dependencies (new compiler version requirements). The current goal is to make opam the best place to find all current and historical ocaml software.

**Comment by pdonadeo** [comment]
@dsheets @damiendoligez These are all valid reasons to keep old versions up to date. I'm going to submit a new patch.

**Comment by samoht** [comment]
Fixed by #7260

**Pull request closed without merging**
