### PR TITLE
Package easy_logging.0.1

### PR DESCRIPTION
**Pull request by sapristi**
### `easy_logging.0.1`
Module to easily log messages
Logging infrastructure inspired by the Python logging module.
The aim of this module is to provide a quick and easy to use logging
infrastructure.

It has the following features :
   * one line logger creation
   * log messages are either [string] or [string lazy_t]
   * log level adaptable at runtime from anywhere in the program
   * handlers associated to each logger will format and treat the message independantly

---
* Homepage: https://sapristi.github.io/easy_logging/easy_logging/
* Source repo: git+https://github.com/sapristi/easy_logging.git
* Bug tracker: https://github.com/sapristi/easy_logging/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by mseri** [comment]
It inferred the wrong name (`prepare` instead of `easy_logging`)

**Comment by sapristi** [comment]
As mseri saw,  I was lost in opam-publish varying documentations, and misused opam-publish command.
The package should be named easy_logging.

**Comment by sapristi** [comment]
Ok so I changed the PR messages, but I have no idea if that is enough. Should I wait for actions in this PR or should I make a new one ?

**Comment by mseri** [comment]
You can force push on this PR adding the necessary fixes, but do as you find more convenient

**Comment by sapristi** [comment]
Ok so it seems putting in the right name pushes to the other PR, si I guess this one should be closed. Thank you mseri !

**Pull request closed without merging**
