### PR TITLE
Constrain dog to Irmin <= "0.9.9".

### PR DESCRIPTION
**Pull request by yallop**
With Irmin 0.9.10:

```
# File "lib/dog_misc.mli", line 26, characters 14-34:
# Error: Unbound type constructor Irmin.basic
# Command exited with code 2.
# Makefile:8: recipe for target 'build' failed
```

/cc @samoht

### CODE REVIEW

**Comment by yallop** [comment]
Restarting the build after #4986 is merged might do something useful.

**Comment by samoht** [comment]
I've just restarted the build

**Comment by samoht** [comment]
@yallop can you update the PR to require `irmin-unix`?

**Comment by yallop** [comment]
Done (6fecf8b)

**Pull request merged**
