### PR TITLE
Fix interactions between num and ocamlfind

### PR DESCRIPTION
**Pull request by jpdeplaix**
This should fix the build failures seen here:
* http://gallium.inria.fr/~scherer/tmp/opam-builder/opam-builder.html?q=ocamlfind

which are related to the fact that older versions of ```ocamlfind``` did require the ```num``` package but it wasn't set explicitly in the ```ocamlfind``` package.
I also wanted to add a ```build``` attribute to the num package to avoid unnecessary rebuilds. However this has a consequence: the num's META file is replaced by the one from ```ocamlfind``` if we reinstall it. My solution is to add a patch to ocamlfind so that it always ignores the ```num``` package.

cc @gasche @xavierleroy @gerdstolpmann

### CODE REVIEW

**Comment by jpdeplaix** [comment]
ci.ocaml.io fails with ```Target ocaml/opam-repository/heads/master does not exist```.
Anybody knows why ? @avsm

**Comment by xavierleroy** [comment]
I like the explicit dependency on `num=0` for older versions of ocamlfind.  I'll let Gerd comment on the patch for 1.7.3, because I don't really understand what it does and  what problem it fixes.

**Comment by gasche** [comment]
I believe that the ocamlfind patch is correct but not very elegant (at least you could just disable the conditional test and add a comment to note that this is special-cased for 4.06). The patch should also come with a comment that explains the problem it solves.

I think that a better long-term approach (and a nicer patch) would be the following:

```diff
From 04a4e29db7d86e56ba7cb3b1ea6a26cdf9e597b2 Mon Sep 17 00:00:00 2001
From: Gabriel Scherer <gabriel.scherer@gmail.com>
Date: Fri, 20 Oct 2017 16:13:59 +0200
Subject: [PATCH] don't install an empty 'num' package if a third-party package
 exists

When reinstalling/updating ocamlfind in an existing OCaml environment,
ocamlfind is installed in a context where ocamlfind packages may
already exist. In particular, the `num` package (separated from the
compiler distribution in 4.06) may exist and own the file
${ocaml_core_stdlib}/num.cmi. In this case ocamlfind should not
overwrite it by installing its own num package -- the behaviour
observed by Jacques-Pascal Deplaix before this patch.

This approach may be generalizable to the other builtin base packages.
---
 configure | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/configure b/configure
index 6a4a558..2627f1f 100755
--- a/configure
+++ b/configure
@@ -524,7 +524,11 @@ fi
 
 # num?
 
-if [ -f "${ocaml_core_stdlib}/num.cmi" ]; then
+if [ -f "${ocaml_sitelib}/num/META" ]; then
+    echo "num: package already present"
+    lnum=""
+    numtop=""
+elif [ -f "${ocaml_core_stdlib}/num.cmi" ]; then
     echo "num: found"
     lnum="num num-top"
     numtop="num-top"
-- 
2.9.5
```

**Comment by jpdeplaix** [comment]
@gasche sorry for that. I should have indeed tried to spend more time in making the patch. Your solution looks nice, I committed it instead of mine.

**Comment by gasche** [comment]
@jpdeplaix does it mean that you tested it to work correctly for your use-case? (I must admit that I haven't tested it on my side.)

(The CI seems confused (maybe the lack of entropy issue we saw before?) but I don't know how to un-stuck it. @avsm?)

**Comment by jpdeplaix** [comment]
> @jpdeplaix does it mean that you tested it to work correctly for your use-case? (I must admit that I haven't tested it on my side.)

Yes, it works well as far as I tried.

**Comment by gerdstolpmann** [comment]
Sorry for being quiet - was a busy week for me. I'll integrate the patch into ocamlfind.

**Pull request merged**
