### PR TITLE
Update merlin.4.14-502~preview

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Alternative to https://github.com/ocaml/opam-repository/pull/25685

### CODE REVIEW

**Comment by mseri** [comment]
Does dot_merlin_reader need an upper bound?
```

#=== ERROR while compiling dot-merlin-reader.4.9 ==============================#
# context              2.2.0~beta3~dev | linux/x86_64 | ocaml-base-compiler.5.2.0~beta2 | file:///home/opam/opam-repository
# path                 ~/.opam/5.2~beta2/.opam-switch/build/dot-merlin-reader.4.9
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p dot-merlin-reader -j 255
# exit-code            1
# env-file             ~/.opam/log/dot-merlin-reader-8-c567d5.env
# output-file          ~/.opam/log/dot-merlin-reader-8-c567d5.out
### output ###
# (cd _build/default && /home/opam/.opam/5.2~beta2/bin/ocamlc.opt -w -40 -g -bin-annot -I src/dot-merlin/.dot_merlin_reader.eobjs/byte -I /home/opam/.opam/5.2~beta2/lib/findlib -I /home/opam/.opam/5.2~beta2/lib/merlin-lib/dot_protocol -I /home/opam/.opam/5.2~beta2/lib/merlin-lib/utils -I /home/opam/.opam/5.2~beta2/lib/ocaml/str -I /home/opam/.opam/5.2~beta2/lib/ocaml/unix -no-alias-deps -o src/dot-merlin/.dot_merlin_reader.eobjs/byte/dune__exe__Dot_merlin_reader.cmo -c -impl src/dot-merlin/dot_merlin_reader.ml)
# File "src/dot-merlin/dot_merlin_reader.ml", lines 326-359, characters 4-47:
# 326 | ....match d with
# 327 |     | `B _ | `S _ | `CMI _ | `CMT _  as directive ->
# 328 |       { cfg with to_canonicalize = (cwd, directive) :: cfg.to_canonicalize }
# 329 |     | `EXT _ | `SUFFIX _ | `FLG _ | `READER _
# 330 |     | (`EXCLUDE_QUERY_DIR | `USE_PPX_CACHE | `UNKNOWN_TAG _) as directive ->
# ...
# 356 |       | Some p ->
# 357 |         log ~title:"conflicting paths for findlib toolchain" "%s\n%s" p path
# 358 |       end;
# 359 |       { cfg with findlib_toolchain = Some path}
# Warning 8 [partial-match]: this pattern-matching is not exhaustive.
# Here is an example of a case that is not matched:
# `H _
# 
# File "src/dot-merlin/dot_merlin_reader.ml", line 451, characters 22-41:
# 451 |     [ List.concat_map cfg.to_canonicalize ~f:(fun (dir, directive) ->
#                             ^^^^^^^^^^^^^^^^^^^
# Error: This expression has type
#          "(string * Merlin_dot_protocol.Directive.include_path) list"
#        but an expression was expected of type
#          "(string *
#           [< `B of string | `CMI of string | `CMT of string | `S of string ])
#          list"
#        Type
#          "Merlin_dot_protocol.Directive.include_path" =
#            "[ `B of string
#            | `CMI of string
#            | `CMT of string
#            | `H of string
#            | `S of string ]"
#        is not compatible with type
#          "[< `B of string | `CMI of string | `CMT of string | `S of string ]"
#        The second variant type does not allow tag(s) "`H"
```

**Comment by kit-ty-kate** [comment]
ah yes, my bad

**Comment by mseri** [comment]
it was still trying to use 4.9, I forced it to pick the same version. Feel free to revert if it is not the correct fix

**Comment by avsm** [comment]
Tests still failing, but in an annoyingly trivial way :-) Any changes needed?

**Comment by mseri** [comment]
This is fine to merge for me, please fix the test error before the stable release lands:
```
#=== ERROR while compiling merlin.4.14-502~preview ============================#
# context              2.2.0~beta3~dev | linux/x86_64 | ocaml-base-compiler.5.2.0~beta2 | pinned(https://github.com/ocaml/merlin/archive/884c07820b144e88018e23b468aeaf24f43ea8da.tar.gz)
# path                 ~/.opam/5.2~beta2/.opam-switch/build/merlin.4.14-502~preview
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p merlin -j 255
# exit-code            1
# env-file             ~/.opam/log/merlin-7-f6e52f.env
# output-file          ~/.opam/log/merlin-7-f6e52f.out
### output ###
# File "tests/test-dirs/inconsistent-assumptions.t", line 1, characters 0-0:
# /usr/bin/git --no-pager diff --no-index --color=always -u _build/.sandbox/beb5cc2d48e9a4445f5a9385ebdce9d4/default/tests/test-dirs/inconsistent-assumptions.t _build/.sandbox/beb5cc2d48e9a4445f5a9385ebdce9d4/default/tests/test-dirs/inconsistent-assumptions.t.corrected
# diff --git a/_build/.sandbox/beb5cc2d48e9a4445f5a9385ebdce9d4/default/tests/test-dirs/inconsistent-assumptions.t b/_build/.sandbox/beb5cc2d48e9a4445f5a9385ebdce9d4/default/tests/test-dirs/inconsistent-assumptions.t.corrected
# index dd7546f..2f06299 100644
# --- a/_build/.sandbox/beb5cc2d48e9a4445f5a9385ebdce9d4/default/tests/test-dirs/inconsistent-assumptions.t
# +++ b/_build/.sandbox/beb5cc2d48e9a4445f5a9385ebdce9d4/default/tests/test-dirs/inconsistent-assumptions.t.corrected
# @@ -70,8 +70,8 @@ Do an update that breaks the build:
#    File "foo.ml", line 4, characters 11-12:
#    4 | let x, _ = x + 1, Bar.b
#                   ^
# -  Error: This expression has type char but an expression was expected of type
# -           int
# +  Error: This expression has type "char" but an expression was expected of type
# +           "int"
#    [2]
#    $ cd ..
#  
```

**Comment by mseri** [comment]
ping @voodoos

**Comment by voodoos** [comment]
@mseri was the failure happening in every environment ? 
I am not able to reproduce it on my machine with e 5.2.0-beta2

**Pull request merged**
