### PR TITLE
[new release] kafka_async, kafka_lwt and kafka (0.5)

### PR DESCRIPTION
**Pull request by didier-wenzek**
OCaml bindings for Kafka, Async bindings

- Project page: <a href="https://github.com/didier-wenzek/ocaml-kafka">https://github.com/didier-wenzek/ocaml-kafka</a>
- Documentation: <a href="https://didier-wenzek.github.io/ocaml-kafka">https://didier-wenzek.github.io/ocaml-kafka</a>

##### CHANGES:

* Add Async bindings
* Split sync and Lwt variants into separate OPAM packages
* Fix compatibility with OCaml 4.09
* Register callbacks as GC roots
* Port to `dune`
* Port to OPAM 2 format
* Make `dune` generate `opam` files automatically
* Add Changelog to facilitate releases with `dune-release`
* Depend ob `zlib` depext instead of explicit package names

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
The failure on FreeBSD is due to a required C library missing, possibly fixable by this PR: https://github.com/didier-wenzek/ocaml-kafka/pull/24

**Comment by Leonidas-from-XIV** [comment]
I think the issue is that FreeBSD does not install ports to a location from where

```c
#include <librdkafka/rdkafka.h>
```

can read it. I guess this is a bigger can of worms (figuring out what the right `-L` and `-I` incantations are) that we should tackle upstream and we should just consider it uninstallable on FreeBSD for now.

**Comment by didier-wenzek** [comment]
Agree.

The issue on Ubuntu is not easy to tackle either. The latter is due to Ubuntu Xenial coming with an old version of librdkafka (0.8.6).

**Comment by mseri** [comment]
Thanks for the explanations

**Comment by didier-wenzek** [comment]
Thank you.

**Pull request merged**
