### PR TITLE
simpler conf-rdkit package

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I think this requires python2 not python3
```
#=== ERROR while compiling conf-rdkit.1.0.0 ===================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.09.0 | pinned
# path                 ~/.opam/4.09/.opam-switch/build/conf-rdkit.1.0.0
# command              /usr/bin/python3 test.py
# exit-code            1
# env-file             ~/.opam/log/conf-rdkit-23-6d07ae.env
# output-file          ~/.opam/log/conf-rdkit-23-6d07ae.out
### output ###
# Traceback (most recent call last):
#   File "test.py", line 2, in <module>
#     import rdkit
# ModuleNotFoundError: No module named 'rdkit'

- Traceback (most recent call last):
-   File "test.py", line 2, in <module>
-     import rdkit
- ModuleNotFoundError: No module named 'rdkit'
```

**Comment by UnixJunkie** [comment]
Note that this will never work on the Mac, since brew needs to use a special tap.
Also, the version of rdkit on Mac supports only Python3.
The rdkit packages on Debian and Centos are so old...

**Comment by UnixJunkie** [comment]
Interesting. Still not working.
I think I should rename it conf-rdkit-python-2, maybe.
Because one day, there should be conf-rdkit-python-3.

**Comment by UnixJunkie** [comment]
The problem is that many distros don't have yet the Python-3 ready version of rdkit.

**Comment by UnixJunkie** [comment]
I think I could make this work only if the latest Ubuntu or Debian was in the test matrix.

**Comment by UnixJunkie** [comment]
I will submit something better soon.

**Pull request closed without merging**
