### PR TITLE
jsoo.3.3.0

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
It seems that the OSX build timed out. Is there anyway to re-trigger this one only

**Comment by mseri** [comment]
Done. Not sure where is the rest of the CI gone

**Comment by mseri** [comment]
@hhugo The osx build has too much to do, it keeps timing out

**Comment by hhugo** [comment]
What's the process for getting this merged ? How do I know it doesn't break existing package ?
Is there anything to do to fix osx build ?

**Comment by avsm** [comment]
Datakit CI was down -- now bringing back up

**Comment by hhugo** [comment]
Can this be merged now ?

**Comment by hhugo** [comment]
Ping

**Comment by xclerc** [comment]
(We will need this PR to be merged for the upcoming JS stable release.)

**Comment by mseri** [comment]
Sorry for disappearing. I am confused about the camlp4 issues on Travis, but I agree that all the revdeps failures are independent. I'll submit a PR to fix some of them separately

**Pull request merged**
