### PR TITLE
Updated Lacaml

### PR DESCRIPTION
**Pull request by mmottl**

### CODE REVIEW

**Comment by fdopen** [comment]
ocamlbuild is missing again ...

**Comment by mmottl** [comment]
@fdopen Thanks, it's not yet generated by `oasis2opam`.  I have just fixed this manually.  @Chris00 Is there going to be a fix for this issue in the near future, or should I just add `ocamlbuild` to the Lacaml `_opam` file?

**Comment by Chris00** [comment]
@mmottl The development version of `oasis2opam` does generate the `ocamlbuild` dependency.  I'll make a release ASAP.

**Comment by Chris00** [comment]
On Mon, 4 Apr 2016 11:42:15 -0700, Markus Mottl wrote:
> 
> @Chris00 Is there going to be a fix for this issue in the near future, or should I just add ocamlbuild to the Lacaml _opam file?

@mmottl The development version of `oasis2opam` does generate the `ocamlbuild` dependency.  I'll make a release ASAP.

**Comment by mmottl** [comment]
@Chris00 Thanks a lot for your work on this!

**Pull request merged**
