### PR TITLE
kinetic.0.0.3

### PR DESCRIPTION
**Pull request by toolslive**

### CODE REVIEW

**Comment by dsheets** [comment]
This used to be called `kinetic-client`? Should that package be renamed as well?

**Comment by toolslive** [comment]
the library is called kinetic-client.
the opam canonical name is "kinetic-client.0.0.3". 
(name, layout, dependencies, etc are identical to the 0.0.1 version)
"kinetic.0.0.3" was just a name for the branch/pull request. 
I didn't know you expect them to be identical

**Comment by dsheets** [comment]
Oops, nope sorry. /me is just blind. Did you want to include <https://github.com/CloudFounders/kinetic-ocaml-client/issues> as the bug report venue?

**Comment by toolslive** [comment]
yes.

**Pull request merged**
