### PR TITLE
brotli.1.2.2 - via opam-publish

### PR DESCRIPTION
**Pull request by fxfactorial**
Bindings to Google's Brotli compresion algorithm

OCaml Bindings to brotli, Google's compression algorithm for the web
Source: https://github.com/google/brotli/ RFC:
http://www.ietf.org/id/draft-alakuijala-brotli

---
* Homepage: http://hyegar.com
* Source repo: https://github.com/fxfactorial/ocaml-brotli.git
* Bug tracker: https://github.com/fxfactorial/ocaml-brotli/issues

---

Pull-request generated by opam-publish v0.3.2

### CODE REVIEW

**Comment by yallop** [comment]
The build is failing with the following:

```
# gcc: error: unrecognized command line option ‘-fsanitize-undefined-trap-on-error’
# gcc: error: unrecognized command line option ‘-std=c++14’
```

**Comment by fxfactorial** [comment]
I have explained this already on the previous PR brotli and if you read two lines further then you'll see the error message says that you need to use gcc 5, not gcc 4. Do OCaml packages  now need to be held hostage by outdated Travis machines?

**Comment by yallop** [comment]
When you're expecting the PR to fail CI it would be helpful to add a note when submitting.  If you can link to the previous PR, all the better.

**Comment by fxfactorial** [comment]
Thanks you’re right, I’ll put notes next time when the build is expected to fail

**Pull request merged**
