### PR TITLE
Lwt: dune exec: use --no-config

### PR DESCRIPTION
**Pull request by aantron**
See https://github.com/ocaml/dune/issues/3296.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Would it not be even more simple with `"-p" name` instead?

**Comment by kit-ty-kate** [comment]
> Would it not be even more simple with `"-p" name` instead?

(replacing the whole `"--no-config" "--root" "."`)

**Comment by aantron** [comment]
Changed to `"-p" name`.

**Comment by aantron** [comment]
The revdeps failures look unrelated to this PR. I'll submit separate PRs to fix some of them, though.

**Comment by mseri** [comment]
Looks good. Thanks

**Pull request merged**
