### PR TITLE
Add ffmpeg.0.2.0

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The opam file needs to be changed accordingly to the opam file in the source repository: https://github.com/savonet/ocaml-ffmpeg/blob/master/ffmpeg.opam

**Comment by kit-ty-kate** [comment]
ok done.

**Comment by toots** [comment]
Thanks!

**Comment by kit-ty-kate** [comment]
looks good now. Thanks!

**Pull request merged**
