### PR TITLE
[new release] otr (1.0.0)

### PR DESCRIPTION
**Pull request by bikallem**
A typed router for OCaml web applications

- Project page: <a href="https://github.com/lemaetech/otr">https://github.com/lemaetech/otr</a>

##### CHANGES:

- First release.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by anuragsoni** [comment]
@bikallem  @kit-ty-kate I believe there is clash with the package name for this library with an existing package https://github.com/ocaml/opam-repository/blob/d26bd31f0f3c0ef4b94b68cd929e45e0a584c8dc/packages/otr/otr.0.3.8/opam

If i'm not mistaken, as of now with this PR being merged, this routing library will look like a new version of the unrelated "otr" package

**Comment by avsm** [comment]
Good catch thanks, reverted this PR as a special case.

**Comment by kit-ty-kate** [comment]
Sorry for that. I'll try to find a proper check for that in CI so that it doesn't happen in the future.

**Comment by bikallem** [comment]
Hmm .. so do I have to re-submit the PR with a new name?

**Comment by kit-ty-kate** [comment]
yes, and probably change the name of the library too to avoid conflicts (`otr` installs a library with the same name)

**Comment by bikallem** [comment]
Sure. will do.

**Pull request merged**
