### PR TITLE
[release ppx_deriving_protobuf.2.7

### PR DESCRIPTION
**Pull request by gasche**
This is a draft PR for revdeps testing.

### CODE REVIEW

**Comment by XVilka** [comment]
Strange, seems a failure at 4.02:
```
#=== ERROR while compiling ppx_deriving_protobuf.2.7 ==========================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.02.3 | pinned(https://github.com/gasche/ppx_deriving_protobuf/archive/prepare-release-2.7.tar.gz)
# path                 ~/.opam/4.02/.opam-switch/build/ppx_deriving_protobuf.2.7
# command              ~/.opam/4.02/bin/dune build -p ppx_deriving_protobuf -j 2
# exit-code            1
# env-file             ~/.opam/log/ppx_deriving_protobuf-15-d6de66.env
# output-file          ~/.opam/log/ppx_deriving_protobuf-15-d6de66.out
### output ###
#       ocamlc src/.ppx_deriving_protobuf.objs/byte/ppx_deriving_protobuf.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.02/bin/ocamlc.opt -w -9 -g -bin-annot -I src/.ppx_deriving_protobuf.objs/byte -I /home/opam/.opam/4.02/lib/ocaml-migrate-parsetree -I /home/opam/.opam/4.02/lib/ocaml/compiler-libs -I /home/opam/.opam/4.02/lib/ppx_derivers -I /home/opam/.opam/4.02/lib/ppx_deriving/api -I /home/opam/.opam/4.02/lib/ppx_tools -I /home/opam/.opam/4.02/lib/result -no-alias-deps -o src/.ppx_deriving_protobuf.objs/byte/ppx_deriving_protobuf.cmo -c -impl src/ppx_deriving_protobuf.pp.ml)
# File "ppx_deriving_protobuf.cppo.ml", line 1173, characters 40-53:
# Error: This record pattern is expected to have type Parsetree.expression
#        The constructor Pconst_string does not belong to type Asttypes.constant
# Hint: Did you mean Const_string?
```
ocaml-protoc failure is very weird:
```
### output ###
# ocamlbuild -use-ocamlfind -pkgs compiler-libs.common,ppx_deriving_protobuf.runtime  -I src/compilerlib -I src/compilerlib/ocaml -I src/runtime -I src/ocaml-protoc pbrt.cma
# make: ocamlbuild: Command not found
# make: *** [Makefile:50: lib.byte] Error 127

- ocamlbuild -use-ocamlfind -pkgs compiler-libs.common,ppx_deriving_protobuf.runtime  -I src/compilerlib -I src/compilerlib/ocaml -I src/runtime -I src/ocaml-protoc pbrt.cma
- make: ocamlbuild: Command not found
- make: *** [Makefile:50: lib.byte] Error 127
```

**Comment by gasche** [comment]
The ocaml-protoc failure @XVilka is typical of a missing `ocamlbuild` dependency on a user package (it used to work thanks to the transitive dependency ->ppx_deriving_protobuf->ocamlbuild). We should fix those two failures (the first I haven't looked yet, I guess more cppo required, the second by editing the opam metadata for protoc).

**Comment by gasche** [comment]
The failure on 4.02.3 might be due to an AST difference between 4.02.2 and 4.02.3 (4.02.3 was a pretty big release that should have been a 4.0X), I'll investigate.

**Comment by gasche** [comment]
Note: The protoc failure given above (missing ocamlbuild dependency) only holds for the first release of protoc, not the older one which do have an ocamlbuild dependency but fail for another reason. I have a fix for the missing-ocamlbuild-dependency, but I will wait to investigate the other issue before updating this PR.

**Comment by XVilka** [comment]
Maybe just raise the minimum version and save time? 4.02 is pretty old version, a lot of packages require 4.03+ anyway.

**Comment by gasche** [comment]
Yes, our CI only tests 4.04 and up. I'll add 4.03, check that it builds, and raise the minimum version.

**Comment by gasche** [comment]
(4.02.3 used to matter because it was the Debian-stable version, but now the new stable uses 4.05 I think.)

**Comment by gasche** [comment]
The other ocaml-protoc failures came from a bug in the new dune build-system of the package, which I fixed. The revdeps are now looking good, so I will turn this into a definitive PR.

**Comment by gasche** [comment]
(I'll wait for CI to finish before clicking "Ready of review")

**Pull request merged**
