### PR TITLE
[new release] memtrace (0.2.1.2)

### PR DESCRIPTION
**Pull request by lukemaurer**
Streaming client for Memprof

- Project page: <a href="https://github.com/janestreet/memtrace">https://github.com/janestreet/memtrace</a>

##### CHANGES:

More fixes for 32-bit platforms.

### CODE REVIEW

**Comment by mseri** [comment]
Versions `v0.14.{0,1}` of the viewer are failing to build with
```
#=== ERROR while compiling memtrace_viewer.v0.14.0 ============================#
# context              2.0.8 | linux/x86_64 | ocaml-base-compiler.4.11.2 | file:///src
# path                 ~/.opam/4.11/.opam-switch/build/memtrace_viewer.v0.14.0
# command              ~/.opam/4.11/bin/dune build --profile release --default-target @install . --root . --cache-transport=direct
# exit-code            1
# env-file             ~/.opam/log/memtrace_viewer-15-3bd182.env
# output-file          ~/.opam/log/memtrace_viewer-15-3bd182.out
### output ###
#          gcc vendor/cstruct/lib/cstruct_stubs.o
# cstruct_stubs.c: In function 'caml_blit_bigstring_to_string':
# cstruct_stubs.c:29:31: warning: passing argument 1 of 'memcpy' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
#    memcpy(String_val(val_buf2) + Long_val(val_ofs2),
# In file included from cstruct_stubs.c:18:
# /usr/include/string.h:42:14: note: expected 'void * restrict' but argument is of type 'const char *'
#  extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
#               ^~~~~~
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 583, characters 32-47:
# 583 | let var x = Exp.ident (mknoloc (Longident.parse x))
#                                       ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 604, characters 35-50:
# 604 | let ojs_typ = Typ.constr (mknoloc (Longident.parse "Ojs.t")) []
#                                          ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 613, characters 33-48:
# 613 |   Exp.apply (Exp.ident (mknoloc (Longident.parse "List.iter"))) (nolabel [f; x])
#                                        ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 650, characters 26-41:
# 650 |   Pat.construct (mknoloc (Longident.parse "Some")) (Some arg)
#                                 ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 653, characters 26-41:
# 653 |   Pat.construct (mknoloc (Longident.parse "None")) None
#                                 ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 735, characters 56-71:
# 735 | let assert_false = Exp.assert_ (Exp.construct (mknoloc (Longident.parse "false")) None)
#                                                               ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 959, characters 43-58:
# 959 |         | Opt _ -> Exp.construct (mknoloc (Longident.parse "Some")) (Some extra_arg)
#                                                  ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1171, characters 27-42:
# 1171 |       Typ.constr (mknoloc (Longident.parse s)) (List.map gen_typ tyl)
#                                   ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1273, characters 61-76:
# 1273 |                     (Typ.arrow Nolabel (Typ.constr (mknoloc (Longident.parse name)) [Typ.constr (mknoloc (Longident.parse v)) []]) ojs_typ)))
#                                                                     ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1273, characters 106-121:
# 1273 |                     (Typ.arrow Nolabel (Typ.constr (mknoloc (Longident.parse name)) [Typ.constr (mknoloc (Longident.parse v)) []]) ojs_typ)))
#                                                                                                                  ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1341, characters 44-59:
# 1341 |       let e = Cl.apply (Cl.constr (mknoloc (Longident.parse super_class)) []) [Nolabel, obj] in
#                                                    ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1368, characters 43-58:
# 1368 |       let class_typ = Typ.constr (mknoloc (Longident.parse class_name)) [] in
#                                                   ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 583, characters 32-47:
# 583 | let var x = Exp.ident (mknoloc (Longident.parse x))
#                                       ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 604, characters 35-50:
# 604 | let ojs_typ = Typ.constr (mknoloc (Longident.parse "Ojs.t")) []
#                                          ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 613, characters 33-48:
# 613 |   Exp.apply (Exp.ident (mknoloc (Longident.parse "List.iter"))) (nolabel [f; x])
#                                        ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 650, characters 26-41:
# 650 |   Pat.construct (mknoloc (Longident.parse "Some")) (Some arg)
#                                 ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 653, characters 26-41:
# 653 |   Pat.construct (mknoloc (Longident.parse "None")) None
#                                 ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 735, characters 56-71:
# 735 | let assert_false = Exp.assert_ (Exp.construct (mknoloc (Longident.parse "false")) None)
#                                                               ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 959, characters 43-58:
# 959 |         | Opt _ -> Exp.construct (mknoloc (Longident.parse "Some")) (Some extra_arg)
#                                                  ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1171, characters 27-42:
# 1171 |       Typ.constr (mknoloc (Longident.parse s)) (List.map gen_typ tyl)
#                                   ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1273, characters 61-76:
# 1273 |                     (Typ.arrow Nolabel (Typ.constr (mknoloc (Longident.parse name)) [Typ.constr (mknoloc (Longident.parse v)) []]) ojs_typ)))
#                                                                     ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1273, characters 106-121:
# 1273 |                     (Typ.arrow Nolabel (Typ.constr (mknoloc (Longident.parse name)) [Typ.constr (mknoloc (Longident.parse v)) []]) ojs_typ)))
#                                                                                                                  ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1341, characters 44-59:
# 1341 |       let e = Cl.apply (Cl.constr (mknoloc (Longident.parse super_class)) []) [Nolabel, obj] in
#                                                    ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1368, characters 43-58:
# 1368 |       let class_typ = Typ.constr (mknoloc (Longident.parse class_name)) [] in
#                                                   ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "_none_", line 1:
# Warning 58: no cmx file was found in path for module Toploop, and its interface was not compiled with -opaque
# File "_none_", line 1:
# Warning 58: no cmx file was found in path for module Toploop, and its interface was not compiled with -opaque
# File "vendor/base/src/float.ml", line 512, characters 10-52:
# 512 |   let t = (round_nearest [@ocaml.inlined always]) t0 in
#                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Warning 55: Cannot inline: Function information unavailable
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 26, characters 40-49:
# 26 |           query: (string * string list) sexp_list;
#                                              ^^^^^^^^^
# Alert deprecated: Sexplib0.Sexp_conv.sexp_list
# [since 2019-03] use [@sexp.list] instead
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 27, characters 20-33:
# 27 |           fragment: string option [@default None] [@sexp_drop_default]
#                          ^^^^^^^^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 25, characters 16-22:
# 25 |           path: string [@default ""] [@sexp_drop_default];
#                      ^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 24, characters 16-26:
# 24 |           port: int option [@default None] [@sexp_drop_default];
#                      ^^^^^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 23, characters 16-29:
# 23 |           host: string option [@default None] [@sexp_drop_default];
#                      ^^^^^^^^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 22, characters 20-33:
# 22 |           userinfo: string option [@default None] [@sexp_drop_default];
#                          ^^^^^^^^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 21, characters 18-31:
# 21 |           scheme: string option [@default None] [@sexp_drop_default];
#                        ^^^^^^^^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 26, characters 40-49:
# 26 |           query: (string * string list) sexp_list;
#                                              ^^^^^^^^^
# Alert deprecated: Sexplib0.Sexp_conv.sexp_list
# [since 2019-03] use [@sexp.list] instead
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 27, characters 20-33:
# 27 |           fragment: string option [@default None] [@sexp_drop_default]
#                          ^^^^^^^^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 25, characters 16-22:
# 25 |           path: string [@default ""] [@sexp_drop_default];
#                      ^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 24, characters 16-26:
# 24 |           port: int option [@default None] [@sexp_drop_default];
#                      ^^^^^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 23, characters 16-29:
# 23 |           host: string option [@default None] [@sexp_drop_default];
#                      ^^^^^^^^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 22, characters 20-33:
# 22 |           userinfo: string option [@default None] [@sexp_drop_default];
#                          ^^^^^^^^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "vendor/uri-sexp/lib_sexp/uri_sexp.ml", line 21, characters 18-31:
# 21 |           scheme: string option [@default None] [@sexp_drop_default];
#                        ^^^^^^^^^^^^^
# Warning 22: [@sexp_drop_default] is deprecated: please use one of:
# - [@sexp_drop_default f] and give an explicit equality function ([f = Poly.(=)] corresponds to the old behavior)
# - [@sexp_drop_default.compare] if the type supports [%compare]
# - [@sexp_drop_default.equal] if the type supports [%equal]
# - [@sexp_drop_default.sexp] if you want to compare the sexp representations
# 
# File "_none_", line 1:
# Warning 58: no cmx file was found in path for module Toploop, and its interface was not compiled with -opaque
#          gcc vendor/core_kernel/src/md5_stubs.o
# md5_stubs.c:11:32: warning: '-pedantic' is not an option that controls warnings [-Wpragmas]
#  #pragma GCC diagnostic ignored "-pedantic"
#                                 ^~~~~~~~~~~
#          gcc vendor/async_ssl/bindings/openssl_helpers.o
# openssl_helpers.c: In function 'async_ssl__subject_alt_names':
# openssl_helpers.c:66:9: warning: 'ASN1_STRING_data' is deprecated [-Wdeprecated-declarations]
#          cstr = ASN1_STRING_data(gen->d.dNSName);
#          ^~~~
# In file included from /usr/include/openssl/e_os2.h:13,
#                  from /usr/include/openssl/bio.h:13,
#                  from /usr/include/openssl/x509v3.h:13,
#                  from openssl_helpers.c:2:
# /usr/include/openssl/asn1.h:554:1: note: declared here
#  DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
#  ^~~~~~~~~~~~~~~~~~
# File "vendor/async_ssl/bindings/ctypes_foreign_threaded_flat.ml", line 1, characters 39-68:
# 1 | module Ctypes_foreign_threaded_stubs = Ctypes_foreign_threaded_stubs
#                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Warning 49: no cmi file was found in path for module Ctypes_foreign_threaded_stubs
# File "vendor/async_ssl/bindings/ctypes_foreign_threaded_flat.ml", line 1, characters 39-68:
# 1 | module Ctypes_foreign_threaded_stubs = Ctypes_foreign_threaded_stubs
#                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Warning 49: no cmi file was found in path for module Ctypes_foreign_threaded_stubs
# File "vendor/async_websocket/src/crypto.ml", line 2, characters 25-40:
# 2 | module CryptokitBignum = CryptokitBignum
#                              ^^^^^^^^^^^^^^^
# Warning 49: no cmi file was found in path for module CryptokitBignum
# File "vendor/conduit-async/async/private_ssl_real.ml", line 61, characters 39-50:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/conduit-async/async/private_ssl_real.ml", line 127, characters 33-44:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/conduit-async/async/private_ssl_real.ml", line 129, characters 39-50:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/conduit-async/async/private_ssl_real.ml", line 150, characters 39-50:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/conduit-async/async/private_ssl_real.ml", line 151, characters 35-46:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/conduit-async/async/private_ssl_real.ml", line 242, characters 33-44:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/async_websocket/src/crypto.ml", line 2, characters 25-40:
# 2 | module CryptokitBignum = CryptokitBignum
#                              ^^^^^^^^^^^^^^^
# Warning 49: no cmi file was found in path for module CryptokitBignum
# File "vendor/conduit-async/async/private_ssl_real.ml", line 61, characters 39-50:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/conduit-async/async/private_ssl_real.ml", line 127, characters 33-44:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/conduit-async/async/private_ssl_real.ml", line 129, characters 39-50:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/conduit-async/async/private_ssl_real.ml", line 150, characters 39-50:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/conduit-async/async/private_ssl_real.ml", line 151, characters 35-46:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "vendor/conduit-async/async/private_ssl_real.ml", line 242, characters 33-44:
# Alert deprecated: Core.sexp_opaque
# [since 2019-03] use [@sexp.opaque] instead
# File "server/src/filtered_trace.ml", line 41, characters 22-30:
# 41 |     | Alloc { obj_id; is_major = true; _ } ->
#                            ^^^^^^^^
# Error: The field is_major is not part of the record argument for the Memtrace.Trace.Event.t.Alloc constructor
# File "server/src/location_trie.ml", line 92, characters 10-18:
# 92 |         ; is_major = _
#                ^^^^^^^^
# Error: The field is_major is not part of the record argument for the Memtrace.Trace.Event.t.Alloc constructor
```
Is that expected?

**Comment by mseri** [comment]
Does this supersede https://github.com/ocaml/opam-repository/pull/18081 ?

**Comment by lukemaurer** [comment]
> Does this supersede #18081 ?

It does. Closed #18081.

**Comment by lukemaurer** [comment]
> Versions `v0.14.{0,1}` of the viewer are failing to build with
> 
> ```
> #=== ERROR while compiling memtrace_viewer.v0.14.0 ============================#
> # context              2.0.8 | linux/x86_64 | ocaml-base-compiler.4.11.2 | file:///src
> # path                 ~/.opam/4.11/.opam-switch/build/memtrace_viewer.v0.14.0
> # command              ~/.opam/4.11/bin/dune build --profile release --default-target @install . --root . --cache-transport=direct
> # exit-code            1
> # env-file             ~/.opam/log/memtrace_viewer-15-3bd182.env
> # output-file          ~/.opam/log/memtrace_viewer-15-3bd182.out
> ### output ###
> #          gcc vendor/cstruct/lib/cstruct_stubs.o
> # cstruct_stubs.c: In function 'caml_blit_bigstring_to_string':
> # cstruct_stubs.c:29:31: warning: passing argument 1 of 'memcpy' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
> #    memcpy(String_val(val_buf2) + Long_val(val_ofs2),
> # In file included from cstruct_stubs.c:18:
> # /usr/include/string.h:42:14: note: expected 'void * restrict' but argument is of type 'const char *'
> #  extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
> #               ^~~~~~
> 
> [ omit: long list of deprecation warnings ]
> 
> # File "server/src/filtered_trace.ml", line 41, characters 22-30:
> # 41 |     | Alloc { obj_id; is_major = true; _ } ->
> #                            ^^^^^^^^
> # Error: The field is_major is not part of the record argument for the Memtrace.Trace.Event.t.Alloc constructor
> # File "server/src/location_trie.ml", line 92, characters 10-18:
> # 92 |         ; is_major = _
> #                ^^^^^^^^
> # Error: The field is_major is not part of the record argument for the Memtrace.Trace.Event.t.Alloc constructor
> ```
> 
> Is that expected?

Ah, updated with patched opams.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
