### PR TITLE
Add ctypes 0.22.0

### PR DESCRIPTION
**Pull request by yallop**

### CODE REVIEW

**Comment by mseri** [comment]
There are lots of failures of the form

[(failed: Library "ctypes.foreign" not found.)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/19fc8025de07f1f1ada9788fb61412362f8a15ad/variant/compilers,4.14,ctypes.0.22.0,revdeps,argon2.1.0.1)

is there a change that made these appeari with this release?

**Comment by raphael-proust** [comment]
The CI looks better although I don't understand some of the issues and so I can't tell for sure if they are from ctypes or from the revdeps being broken. I can tell that:

- `ppx_rapper` seems broken (some expect test is failing) (ping @roddyyaga )
- `srt` seems broken (missing dependency to `ocamlfind`?) (ping @toots )

**Comment by mseri** [comment]
I think they are both unrelated. For the first I don't think we can do anything (and seems to have to do more with ppx/ppxlib) and the latter is indeed likely a missing dependency (I'll send a PR to fix it)

**Comment by mseri** [comment]
I am more worried about macos failures:
```
# File "tests/test-callback_lifetime/dune", line 2, characters 7-29:
# 2 |  (name test_callback_lifetime)
#            ^^^^^^^^^^^^^^^^^^^^^^
# (cd _build/default/tests/test-callback_lifetime && ./test_callback_lifetime.exe)
# ..EE..
# ==============================================================================
# Error: Callback lifetime tests:3:calling expired closures (stubs).
# 
# File "/Users/mac1000/.opam/5.1.1/.opam-switch/build/ctypes-foreign.0.22.0/_build/default/tests/test-callback_lifetime/oUnit-Callback lifetime tests-m1-worker-01#00.log", line 55, characters 1-1:
# Error: Callback lifetime tests:3:calling expired closures (stubs) (in the log).
# 
# Worker stops running: Killed by signal -10
# ------------------------------------------------------------------------------
# ==============================================================================
# Error: Callback lifetime tests:2:calling expired closures (foreign).
# 
# File "/Users/mac1000/.opam/5.1.1/.opam-switch/build/ctypes-foreign.0.22.0/_build/default/tests/test-callback_lifetime/oUnit-Callback lifetime tests-m1-worker-01#00.log", line 51, characters 1-1:
# Error: Callback lifetime tests:2:calling expired closures (foreign) (in the log).
# 
# Worker stops running: Killed by signal -10
# ------------------------------------------------------------------------------
# Ran: 6 tests in: 1.36 seconds.
# FAILED: Cases: 6 Tried: 6 Errors: 2 Failures: 0 Skip:  0 Todo: 0 Timeouts: 0.
```
Are those known/expected?

**Comment by yallop** [comment]
The `test_callback_lifetime` failure on macOS  is (unfortunately) a known issue: https://github.com/yallop/ocaml-ctypes/issues/730

**Comment by toots** [comment]
Glad to see that `ctypes` is being migrated to `dune`! I believe `srt` should be fine with a dependency on `ocamlfind` indeed. I have added it to the upstream repository so it'll be there for the next release.

**Pull request merged**
