### PR TITLE
release pa_ppx 0.15 w/Camlp5 8.03.00, ocaml 5.2 compatibility

### PR DESCRIPTION
**Pull request by chetmurthy**
very little changes except for adding AST support for OCaml 5.2

### CODE REVIEW

**Comment by chetmurthy** [comment]
It looks like some OPAM packages aren't getting downloaded (e.g. "astring").  No idea what to do about it.

**Comment by mseri** [comment]
I am rerunning them, let's see if the network is back up

**Comment by chetmurthy** [comment]
looks like not?  no idea what to do about this.

**Comment by chetmurthy** [comment]
Looks like this is good-to-go ?

**Comment by mseri** [comment]
Sorry I was away. Looks fine, thanks

**Pull request merged**
