### PR TITLE
mirage-net-lwt.1.0.0: Avoid inconsistance with mirage-net.1.1.0

### PR DESCRIPTION
**Pull request by jpdeplaix**
Noticed in #11426
This seems fair to remove broken packages.

### CODE REVIEW

**Comment by hannesm** [comment]
FYI, I played a bit with mirage-net*, the resulting matrix

- [x] mirage-net.1.0.0 mirage-net-lwt.1.0.0
- [x] mirage-net.1.0.0 mirage-net-lwt.1.1.1
- [ ] mirage-net.1.1.0 mirage-net-lwt.1.0.0
- [x] mirage-net.1.1.0 mirage-net-lwt.1.1.1

we maybe just need to adjust some constraints (i.e. mirage-net-lwt.1.1.1 should depend on >= mirage-net.1.1.0)? I suspect we will run again into this issue with various other mirage (mirage-block/-channel/-clock/-console/-flow/-fs/-kv/-protocols/-stack/-time) interfaces... or we remove the non-jbuilder releases of all of them... //cc @samoht

**Comment by jpdeplaix** [comment]
@hannesm what would you prefer ? Do you think it's fine for now to remove mirage-net-lwt.1.0.0 or do you prefer to add a constrain ?
Both are fine by me.

**Comment by avsm** [comment]
I'd prefer a constraint if at all possible, since these were all valid releases at one point. But I recognise that finding the right constraint can be a pain :)

**Comment by jpdeplaix** [comment]
Ok, no problem. I've just updated the PR

**Comment by jpdeplaix** [comment]
Ok, let's merge this one and the two others.

**Pull request merged**
