### PR TITLE
Add conf-brotli

### PR DESCRIPTION
**Pull request by fxfactorial**

### CODE REVIEW

**Comment by dbuenzli** [comment]
Seems perfect,  thanks ! 

We'll wait for the CI and someone to merge this.

**Comment by dbuenzli** [comment]
This fails on `linux` because as Edgar [said](https://github.com/ocaml/opam-repository/pull/10118#issuecomment-323585730) the brotli package is in debian experimental. Travis succeeds on `osx` this is good to go and https://github.com/ocaml/opam-repository/pull/10118 should be restarted once this gets merged.

**Comment by dbuenzli** [comment]
ping

**Comment by avsm** [comment]
thanks!

**Pull request merged**
