### PR TITLE
8 packages from savonet/ocaml-ffmpeg at 1.1.0

### PR DESCRIPTION
**Pull request by toots**
This pull-request concerns:
-`ffmpeg.1.1.0`: Bindings for the ffmpeg libraries
-`ffmpeg-av.1.1.0`: Bindings for the ffmpeg libraries -- top-level helpers
-`ffmpeg-avcodec.1.1.0`: Bindings for the ffmpeg avcodec library
-`ffmpeg-avdevice.1.1.0`: Bindings for the ffmpeg avdevice library
-`ffmpeg-avfilter.1.1.0`: Bindings for the ffmpeg avfilter library
-`ffmpeg-avutil.1.1.0`: Bindings for the ffmpeg avutil libraries
-`ffmpeg-swresample.1.1.0`: Bindings for the ffmpeg swresample library
-`ffmpeg-swscale.1.1.0`: Bindings for the ffmpeg swscale library

---
* Homepage: https://github.com/savonet/ocaml-ffmpeg
* Source repo: git+https://github.com/savonet/ocaml-ffmpeg.git
* Bug tracker: https://github.com/savonet/ocaml-ffmpeg/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by mseri** [comment]
Are these
```
# File "tools/ffmpeg_utils.ml", line 93, characters 23-37:
# 93 |     input : [ `Video ] Avfilter.input;
#                             ^^^^^^^^^^^^^^
# Error: Unbound module Avfilter
# make[2]: *** [../Makefile.rules:122: tools/ffmpeg_utils.cmx] Error 2
# make[2]: Leaving directory '/home/opam/.opam/4.13/.opam-switch/build/liquidsoap.2.0.0/src'
# make[1]: *** [../Makefile.rules:69: all-auto-ocaml-prog] Error 2
# make[1]: Leaving directory '/home/opam/.opam/4.13/.opam-switch/build/liquidsoap.2.0.0/src'
# make: *** [Makefile.rules:29: all-subdirs] Error 2
```
and similarly missing `Avcodec` due to something missing on the hardware/distributed version of ffmpg, or they are hiding some other issue?

**Comment by mseri** [comment]
The only other failure is related to [liquidsoap.2.0.0~rc1](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/e436f5832a2bd34c7ca14ad296acc3bd085ad8a1/variant/opam-2.0,compilers,4.10,liquidsoap.2.0.0~rc1):
```
# File "lang/parser.ml", lines 400-620, characters 2-23:
# 400 | ..fun _menhir_env _menhir_stack _menhir_s _v ->
# 401 |     let _menhir_stack = (_menhir_stack, _menhir_s, _v) in
# 402 |     match _menhir_s with
# 403 |     | MenhirState100 ->
# 404 |         let (_menhir_env : _menhir_env) = _menhir_env in
# ...
# 617 |             let (_menhir_stack, _menhir_s, _) = _menhir_stack in
# 618 |             (_menhir_errorcase _menhir_env (Obj.magic _menhir_stack) _menhir_s : 'freshtv1808)) : 'freshtv1810)
# 619 |     | _ ->
# 620 |         _menhir_fail ()
# Error: This definition has type
#          'ttv_tail.
#            _menhir_env ->
#            'ttv_tail ->
#            _menhir_state -> 'tv_ty_content_arg list -> 'freshtv1790
#        which is less general than
#          'ttv_tail 'ttv_return.
#            _menhir_env ->
#            'ttv_tail ->
#            _menhir_state -> 'tv_ty_content_arg list -> 'ttv_return
```

**Comment by toots** [comment]
> The only other failure is related to [liquidsoap.2.0.0~rc1](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/e436f5832a2bd34c7ca14ad296acc3bd085ad8a1/variant/opam-2.0,compilers,4.10,liquidsoap.2.0.0~rc1):
> 
> ```
> # File "lang/parser.ml", lines 400-620, characters 2-23:
> # 400 | ..fun _menhir_env _menhir_stack _menhir_s _v ->
> # 401 |     let _menhir_stack = (_menhir_stack, _menhir_s, _v) in
> # 402 |     match _menhir_s with
> # 403 |     | MenhirState100 ->
> # 404 |         let (_menhir_env : _menhir_env) = _menhir_env in
> # ...
> # 617 |             let (_menhir_stack, _menhir_s, _) = _menhir_stack in
> # 618 |             (_menhir_errorcase _menhir_env (Obj.magic _menhir_stack) _menhir_s : 'freshtv1808)) : 'freshtv1810)
> # 619 |     | _ ->
> # 620 |         _menhir_fail ()
> # Error: This definition has type
> #          'ttv_tail.
> #            _menhir_env ->
> #            'ttv_tail ->
> #            _menhir_state -> 'tv_ty_content_arg list -> 'freshtv1790
> #        which is less general than
> #          'ttv_tail 'ttv_return.
> #            _menhir_env ->
> #            'ttv_tail ->
> #            _menhir_state -> 'tv_ty_content_arg list -> 'ttv_return
> ```
> 
> I think it may be related to https://gitlab.inria.fr/fpottier/menhir/-/issues/57, in the future it is recommended to call menhir with --infer (if the issue linked above is really what is going on here). For the moment we added a conflict between ocaml < 4.12 and that version of menhir

Noted and applied upstream!

**Comment by toots** [comment]
> Are these
> 
> ```
> # File "tools/ffmpeg_utils.ml", line 93, characters 23-37:
> # 93 |     input : [ `Video ] Avfilter.input;
> #                             ^^^^^^^^^^^^^^
> # Error: Unbound module Avfilter
> # make[2]: *** [../Makefile.rules:122: tools/ffmpeg_utils.cmx] Error 2
> # make[2]: Leaving directory '/home/opam/.opam/4.13/.opam-switch/build/liquidsoap.2.0.0/src'
> # make[1]: *** [../Makefile.rules:69: all-auto-ocaml-prog] Error 2
> # make[1]: Leaving directory '/home/opam/.opam/4.13/.opam-switch/build/liquidsoap.2.0.0/src'
> # make: *** [Makefile.rules:29: all-subdirs] Error 2
> ```
> 
> and similarly missing `Avcodec` due to something missing on the hardware/distributed version of ffmpg, or they are hiding some other issue?

Yeah, it's the same. I decided to make `liquidsoap.2.0.0` depends on the top-level `ffmpeg` so that all packages are available at once, avoiding the issues with partial packages. Not sure why the CI is still picking it up for partial dependencies.

**Comment by mseri** [comment]
Ok thanks for the clarification. If you want to test what the CI does, the first few lines of the CI output give you the reproduction steps, e.g.:
```
git clone --recursive "https://github.com/ocaml/opam-repository.git" && cd "opam-repository" && git fetch origin "refs/pull/20119/head" && git reset --hard e436f583
git fetch origin master
git merge e3825c34dc7243090d6a911821b9681418e601b0
cat > ../Dockerfile <<'END-OF-DOCKERFILE'
FROM ocaml/opam:debian-11-ocaml-4.13@sha256:e5d382899729a136009a16bf1fbb33dae27b95bb09aa092080190692350cbdbb
USER 1000:1000
RUN opam repository remove -a multicore || true
RUN sudo ln -f /usr/bin/opam-2.0 /usr/bin/opam
RUN opam init --reinit -ni
ENV OPAMDOWNLOADJOBS 1
ENV OPAMERRLOGLEN 0
ENV OPAMSOLVERTIMEOUT 500
ENV OPAMPRECISETRACKING 1
WORKDIR /home/opam
RUN rm -rf opam-repository/
COPY --chown=1000:1000 . opam-repository/
RUN opam repository set-url --strict default "file://$HOME/opam-repository"
RUN opam pin add -k version -yn ffmpeg-av.1.1.0 1.1.0
RUN opam depext -u
RUN opam remove ffmpeg-av.1.1.0 && opam depext ffmpeg-av.1.1.0 && opam install --deps-only ffmpeg-av.1.1.0 && opam install -v ffmpeg-av.1.1.0; \
    res=$?; \
    test "$res" != 31 && exit "$res"; \
    export OPAMCLI=2.0; \
    build_dir=$(opam var prefix)/.opam-switch/build; \
    failed=$(ls "$build_dir"); \
    for pkg in $failed; do \
    if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"debian-11\""; then \
    echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field."; \
    fi; \
    done; \
    exit 1
RUN opam depext -u
RUN opam remove liquidsoap-daemon.0.3.0 && opam depext liquidsoap-daemon.0.3.0 && opam install --deps-only liquidsoap-daemon.0.3.0 && opam install -v liquidsoap-daemon.0.3.0; \
    res=$?; \
    test "$res" != 31 && exit "$res"; \
    export OPAMCLI=2.0; \
    build_dir=$(opam var prefix)/.opam-switch/build; \
    failed=$(ls "$build_dir"); \
    for pkg in $failed; do \
    if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"debian-11\""; then \
    echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field."; \
    fi; \
    done; \
    exit 1
RUN opam depext -u
RUN opam remove liquidsoap-daemon.0.3.0 && opam depext --with-test liquidsoap-daemon.0.3.0 && opam install --deps-only --with-test liquidsoap-daemon.0.3.0 && opam install -v --with-test liquidsoap-daemon.0.3.0; \
    res=$?; \
    test "$res" != 31 && exit "$res"; \
    export OPAMCLI=2.0; \
    build_dir=$(opam var prefix)/.opam-switch/build; \
    failed=$(ls "$build_dir"); \
    for pkg in $failed; do \
    if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"debian-11\""; then \
    echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field."; \
    fi; \
    done; \
    exit 1

END-OF-DOCKERFILE
docker build -f ../Dockerfile .
```

**Pull request merged**
