### PR TITLE
Package ocamlformat.0.5

### PR DESCRIPTION
**Pull request by jberdine**
### `ocamlformat.0.5`

Auto-formatter for OCaml code

OCamlFormat is a tool to automatically format OCaml code in a uniform style.

---
* Homepage: https://github.com/ocaml-ppx/ocamlformat
* Source repo: https://github.com/ocaml-ppx/ocamlformat.git
* Bug tracker: https://github.com/ocaml-ppx/ocamlformat/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by jberdine** [comment]
[CHANGES](https://github.com/ocaml-ppx/ocamlformat/blob/v0.5/CHANGES.md) for reference

**Comment by hcarty** [comment]
@jberdine It looks like this needs `ocamlformat_support` 0.4 packaged as well.

**Comment by jberdine** [comment]
Indeed, incoming, and I'll rebase this on top.

**Comment by hcarty** [comment]
@jberdine Do you want to handle the two PRs separately or merge both packages in this one?

**Comment by jberdine** [comment]
I don't know, whatever is best from the opam repo point of view. This one isn't installable without the other, and the other isn't useful other than for this, so I don't think that there is a benefit to splitting them up. But I don't know how to get `opam publish` to send them both at once, so just send each one separately and then manually rebase and force push. Would love to learn a better way.

**Comment by hcarty** [comment]
That's a good question - maybe @AltGr knows?

For now I think focusing on one PR (this one) is sufficient.  Thanks!

**Comment by hcarty** [comment]
CI failures are unrelated.  Travis is waiting on compilers which aren't supported by these packages.  Merging!

Thanks!

**Pull request merged**
