### PR TITLE
[camlp5] Support for 4.07.1.

### PR DESCRIPTION
**Pull request by ejgallego**
Interim commit until a release is done. If that happens soon enough will update this PR.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I have no idea why the package keeps failing to install on MacOS :/
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - camlp5.7.06.10-g84ce6cc4:
            https://github.com/camlp5/camlp5/archive/84ce6cc4d7738b3c43dfeadd5e9717bb9b50c786.tar.gz
            (download failed)
```
cc @rjbou ?

**Comment by ejgallego** [comment]
Umm, let's try a rerun.

**Comment by kit-ty-kate** [comment]
Still broken. @rjbou @AltGr any idea ?

**Comment by rjbou** [comment]
@mseri @kit-ty-kate the openssl / macos problem ~~I know about is the `sha512` openssl option that is not available on MacOS~~. After looking further, it seems that on MacOS, the only `sha` openssl option available are `sha` and `sha1`, from the CI install.

**Pull request merged**
