### PR TITLE
Package asak.0.2

### PR DESCRIPTION
**Pull request by nobrakal**
### `asak.0.2`
Partitioning OCaml codes
Asak provides functions to parse, type-check and identify similar OCaml codes.
These functions are then used to partition codes implementing the same function and help to detect code duplication.

---
* Homepage: https://github.com/nobrakal/asak
* Source repo: git+https://github.com/nobrakal/asak.git
* Bug tracker: https://github.com/nobrakal/asak/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This PR should not have been merged. It contains various issues that need to be resolved

**Comment by nobrakal** [comment]
Ah oops. How do you want to proceed ?

**Comment by kit-ty-kate** [comment]
Fixed in https://github.com/ocaml/opam-repository/pull/15692

**Comment by samoht** [comment]
@kit-ty-kate apologies, ocaml-ci was green and I haven't spotted any mistake :-) Maybe should we use a linter to encode your knowledge into a tool?

**Pull request merged**
