### PR TITLE
Package oseq.0.2

### PR DESCRIPTION
**Pull request by c-cube**
### `oseq.0.2`

---
* Homepage: https://github.com/c-cube/oseq/
* Source repo: git+https://github.com/c-cube/oseq.git
* Bug tracker: https://github.com/c-cube/oseq/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There seem to be a missing test dependency:
```
#=== ERROR while compiling oseq.0.2 ===========================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.0 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/4.07.0/.opam-switch/build/oseq.0.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p oseq
# exit-code   1
# env-file    ~/.opam/log/oseq-14508-e4db2f.env
# output-file ~/.opam/log/oseq-14508-e4db2f.out
### output ###
# File "qtest/dune", line 21, characters 18-21:
# 21 |   (libraries oseq gen qcheck containers)
#                        ^^^
# Error: Library "gen" not found.
# Hint: try: dune external-lib-deps --missing -p oseq @runtest
```

**Comment by c-cube** [comment]
But it's in the opam file, there's a line `"gen" {test}`, right? I don't understand why it fails :confused: (and had the same issue with travis…)

**Comment by kit-ty-kate** [comment]
With opam2 it's `{with-test}` not `{test}` :/

**Comment by c-cube** [comment]
How comes `opam lint` doesn't complain then? :disappointed:

**Comment by kit-ty-kate** [comment]
cc @AltGr @rjbou

**Comment by kit-ty-kate** [comment]
The remaining failure comes from Travis' MacOS not being able to check sha512. This will be fixed in opam 2.0.1 if I'm right.

Thanks!

**Comment by c-cube** [comment]
Thanks @kit-ty-kate !

**Comment by rjbou** [comment]
For the `test` filter, cf. #12729.
For sha512, yes it'll be included in 2.0.1.

**Pull request merged**
