### PR TITLE
imagelib.20160413: add missing upper bound

### PR DESCRIPTION
**Pull request by mseri**
Reported in https://github.com/ocaml/opam-repository/issues/15867

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>

### CODE REVIEW

**Comment by mseri** [comment]
Looks like this is no longer downloadable. Should I point it to the opam cache?

**Comment by kit-ty-kate** [comment]
> Looks like this is no longer downloadable. Should I point it to the opam cache?

I think it might be the only thing to do. @craff is there any archive available elsewhere? The Patoline website died.

**Comment by kit-ty-kate** [comment]
Fixed in bulk PR https://github.com/ocaml/opam-repository/pull/16534

**Comment by mseri** [comment]
Thanks

**Pull request closed without merging**
