### PR TITLE
[new release] dscheck (0.4.0)

### PR DESCRIPTION
**Pull request by polytypic**
Traced Atomics

- Project page: <a href="https://github.com/ocaml-multicore/dscheck">https://github.com/ocaml-multicore/dscheck</a>

##### CHANGES:

- Made (empty) package available on OCaml 4 (@polytypic, review: @lyrm)

### CODE REVIEW

**Comment by polytypic** [comment]
The revdeps failures listed below are unrelated to the changes in this `dscheck` release:
- 4.14
  - [oplsr.8.0.1 (failed: The installation of oplsr failed at "R CMD BATCH install_pls.r".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f59e28b1673176bcc08057d1a391610fda62f55f/variant/compilers,4.14,dscheck.0.4.0,revdeps,oplsr.8.0.1)
  - [orrandomForest.3.0.0 (failed: The installation of orrandomForest failed at "R CMD BATCH install_randomForest.r".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f59e28b1673176bcc08057d1a391610fda62f55f/variant/compilers,4.14,dscheck.0.4.0,revdeps,orrandomForest.3.0.0)
- 5.1
  - [lbvs_consent.2.2.0 (failed: The compilation of lbvs_consent.2.2.0 failed at "make obmaccs".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f59e28b1673176bcc08057d1a391610fda62f55f/variant/compilers,5.1,dscheck.0.4.0,revdeps,lbvs_consent.2.2.0)
  - [oplsr.8.0.1 (failed: The installation of oplsr failed at "R CMD BATCH install_pls.r".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f59e28b1673176bcc08057d1a391610fda62f55f/variant/compilers,5.1,dscheck.0.4.0,revdeps,oplsr.8.0.1)
  - [orrandomForest.3.0.0 (failed: The installation of orrandomForest failed at "R CMD BATCH install_randomForest.r".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f59e28b1673176bcc08057d1a391610fda62f55f/variant/compilers,5.1,dscheck.0.4.0,revdeps,orrandomForest.3.0.0)

The builds of those packages just fail on their own.  Those same packages seem to be causing revdeps failures constantly.  I've already wasted time looking at them several times.  It would be great if something could be done to avoid having people waste time on them.

**Comment by polytypic** [comment]
The revdeps failure:

- 5.1
  - [saturn_lockfree.0.4.1 (failed: Library "saturn" not found.)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f59e28b1673176bcc08057d1a391610fda62f55f/variant/compilers,5.1,dscheck.0.4.0,revdeps,saturn_lockfree.0.4.1)

is unrelated to the changes in this `dscheck` release.  It seems to be the same as the issue [runtest failures on saturn_lockfree.0.4.1 release](https://github.com/ocaml-multicore/saturn/issues/109) that has been fixed (by me) in the Saturn repository.

**Comment by polytypic** [comment]
The revdeps failures:

- 4.14
  - [saturn_lockfree.0.4.1 (failed: Library "saturn" not found.)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f59e28b1673176bcc08057d1a391610fda62f55f/variant/compilers,4.14,dscheck.0.4.0,revdeps,saturn_lockfree.0.4.1)

are caused by the changes in this release.  Previously the `dscheck` package was not available on OCaml 4 so testing of Saturn was skipped on OCaml 4.

What could be done to avoid this revdeps failure to appear in the future?

We will be updating Saturn such that future releases will build and test properly on OCaml 4.

**Comment by haochenx** [comment]
re: saturn_lockfree.0.4.1 (failed: Library "saturn" not found.)
> Could something be done to avoid this appear as (known/unnecessary) revdeps failure in the future?
> What could be done to avoid this revdeps failure to appear in the future?

listing dscheck >= 0.4.0 as a conflict in saturn_lockfree.0.4.1's opam file might be a solution

**Comment by polytypic** [comment]
> @polytypic So I think we just need to mark `saturn` or `saturn_lockfree` incompatible with ocaml4. I am right to assume that we need to add the bound to saturn?

`saturn` and `saturn_lockfree` actually work on OCaml 4 (IIRC, 4.13+ works).  The problem is that tests in Saturn have previously required OCaml 5 (i.e. `dscheck` only available on OCaml 5).  This has meant that the libraries have not been tested by OCaml-CI nor Opam-CI on OCaml 4.  The primary motivation for the change to make the `dscheck` package available on OCaml 4 is to allow libraries like Saturn (and several others) to be tested on OCaml 4 (as much as possible).

**Comment by mseri** [comment]
I'll open a separate PR for that

**Pull request merged**
