### PR TITLE
Package simlog.0.0.4

### PR DESCRIPTION
**Pull request by muqiuhan**
### `simlog.0.0.4`
A simple OCaml logging library
A simple OCaml logging library

---
* Homepage: https://github.com/muqiuhan/simlog
* Source repo: git+https://github.com/muqiuhan/simlog.git
* Bug tracker: https://github.com/muqiuhan/simlog/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by muqiuhan** [comment]
For package name conflict in #24625

**Comment by mseri** [comment]
It is failing sith
```
#=== ERROR while compiling simlog.0.0.4 =======================================#
# context              2.2.0~alpha3~dev | linux/x86_64 | ocaml-base-compiler.4.11.2 | pinned(https://github.com/muqiuhan/dog/archive/refs/tags/0.0.4.tar.gz)
# path                 ~/.opam/4.11/.opam-switch/build/simlog.0.0.4
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p simlog -j 71 @install
# exit-code            1
# env-file             ~/.opam/log/simlog-7-985b36.env
# output-file          ~/.opam/log/simlog-7-985b36.out
### output ###
# Error: I don't know about package simlog (passed through --only-packages)
```

**Comment by muqiuhan** [comment]
image
```


<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Processing  1/4: [simlog.0.0.4: http]
[ERROR] Failed to get sources of simlog.0.0.4: Curl failed

#=== ERROR while fetching sources for simlog.0.0.4 ============================#
OpamSolution.Fetch_fail("https://github.com/muqiuhan/dog/archive/refs/tags/0.0.4.tar.gz (Curl failed: \"/usr/bin/curl --write-out %{http_code}\\\\n --retry 3 --retry-delay 2 --user-agent opam/2.2.0~alpha3~dev -L -o /home/opam/.opam/4.14/.opam-switch/sources/simlog/0.0.4.tar.gz.part -- https://github.com/muqiuhan/dog/archive/refs/tags/0.0.4.tar.gz\" exited with code 6)")


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - fetch simlog 0.0.4
+- 
- No changes have been performed
# Run eval $(opam env) to update the current shell environment
'opam reinstall --with-test --verbose simlog.0.0.4' failed.
"/usr/bin/env" "bash" "-c" "opam reinstall --with-test --verbose simlog.0.0.4;
        res=$?;
        test "$res" != 31 && exit "$res";
        export OPAMCLI=2.0;
        build_dir=$(opam var prefix)/.opam-switch/build;
        failed=$(ls "$build_dir");
        partial_fails="";
        for pkg in $failed; do
          if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"fedora-37\""; then
            echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field.";
          fi;
          test "$pkg" != 'simlog.0.0.4' && partial_fails="$partial_fails $pkg";
        done;
        test "${partial_fails}" != "" && echo "opam-repo-ci detected dependencies failing: ${partial_fails}";
        exit 1" failed with exit status 40
2023-10-14 08:57.45: Job failed: Failed: Build failed
2023-10-14 08:57.45: Log analysis:
2023-10-14 08:57.45: >>> 
[ERROR] Failed to get sources of simlog.0.0.4: Curl failed
 (score = 25)
2023-10-14 08:57.45: >>> 
[ERROR] Failed to get sources of simlog.0.0.4: Curl failed
 (score = 25)
2023-10-14 08:57.45: Failed to get sources of simlog.0.0.4: Curl failed
````

sorry, `Curl failed` whats that mean?

**Comment by mseri** [comment]
Tjose are CI issues, nothing to do with your pr. I have restarted the jobs but I expect them to pass

**Comment by muqiuhan** [comment]
> I have restarted the jobs

I have tried this a few times before, but this is always the result

**Comment by mseri** [comment]
Something is off with the specific machine then. Thanks for checking as well

**Pull request merged**
