### PR TITLE
Package ocsigen-toolkit.3.3.4

### PR DESCRIPTION
**Pull request by balat**
### `ocsigen-toolkit.3.3.4`
Reusable UI components for Eliom applications (client only, or client-server)
The Ocsigen Toolkit is a set of user interface widgets that facilitate the development of Eliom applications.

---
* Homepage: http://www.ocsigen.org
* Source repo: git+https://github.com/ocsigen/ocsigen-toolkit.git
* Bug tracker: https://github.com/ocsigen/ocsigen-toolkit/issues/

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
This PR needs https://github.com/ocaml/opam-repository/pull/24605 available before it can be tested by opam-repo-ci.
From the build logs:
```
ocsigen-toolkit.3.3.4 is not installed. Install it? [y/n] y
  * Missing dependency:
    - eliom >= 10.1.2
    no matching version
```

Options are to package this up with the PR 24605 or wait for that PR to merge and re-run the build for this one. @balat

**Comment by balat** [comment]
Thank you. The other one is now merged.

**Comment by balat** [comment]
The ci seems to be stuck ...

**Comment by mseri** [comment]
I tried to kill the jobs and restart it, let's see if it works

**Comment by mtelvers** [comment]
@mseri One of the workers was stuck, and since the scheduler groups like jobs together, it was queuing up the other jobs for that worker to finish.

**Comment by mseri** [comment]
Looks good now, thanks

**Pull request merged**
