### PR TITLE
Package llama-cpp-ocaml.0.0.1

### PR DESCRIPTION
**Pull request by igarnier**
### `llama-cpp-ocaml.0.0.1`
Ctypes bindings to llama.cpp
llama-cpp-ocaml is a MIT-licensed set of ctypes bindings to llama.cpp, a performant and lightweight library to perform inference on various kinds of large language models.

---
* Homepage: http://github.com/atacama-dev/llama-cpp-ocaml
* Source repo: git+https://github.com/atacama-dev/llama-cpp-ocaml
* Bug tracker: http://github.com/atacama-dev/llama-cpp-ocaml

---
# 0.0.1
- First release of `llama-cpp-ocaml`, ctypes bindings for https://github.com/ggerganov/llama.cpp/

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by igarnier** [comment]
Looks like `opam publish` didn't snapshot the git subtree of the vendored library. I'll fallback to copying the vendored library.

**Comment by raphael-proust** [comment]
There is a build error on freebsd (see below). Is it known? Is it something that "just needs some devs to setup some system libraries from source or something"? Or is it that the package should be marked as `available : { os != freebsd }`?

```
#=== ERROR while compiling llama-cpp-ocaml.0.0.1 ==============================#
# context              2.1.5 | freebsd/x86_64 | ocaml-base-compiler.4.14.1 | pinned(https://github.com/atacama-dev/llama-cpp-ocaml/archive/refs/tags/0.0.1.tar.gz)
# path                 /usr/home/opam/.opam/4.14.1/.opam-switch/build/llama-cpp-ocaml.0.0.1
# command              /usr/home/opam/.opam/4.14.1/bin/dune build -p llama-cpp-ocaml -j 31 @install
# exit-code            1
# env-file             /usr/home/opam/.opam/log/llama-cpp-ocaml-6263-5df773.env
# output-file          /usr/home/opam/.opam/log/llama-cpp-ocaml-6263-5df773.out
### output ###
# File "src/dune", line 3, characters 0-446:
#  3 | (rule
#  4 |   (deps (source_tree llama.cpp) produce-static-archive.patch)
#  5 |   (targets libllama_bindings.a dllllama_bindings.so)
# ....
# 12 |         (chdir llama.cpp (run make libllama.so libllama.a))
# 13 |         (copy llama.cpp/libllama.a libllama_bindings.a)
# 14 |         (copy llama.cpp/libllama.so dllllama_bindings.so)))))
# (cd _build/default/src && /usr/bin/patch -d llama.cpp --binary -p1) < _build/default/src/produce-static-archive.patch
# patch: unrecognized option `--binary'
# usage: patch [-bCcEeflNnRstuv] [-B backup-prefix] [-D symbol] [-d directory]
#              [-F max-fuzz] [-i patchfile] [-o out-file] [-p strip-count]
#              [-r rej-name] [-V t | nil | never | none] [-x number]
#              [-z backup-ext] [--posix] [origfile [patchfile]]
#        patch <patchfile
# (cd _build/default/src && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -g -I /usr/home/opam/.opam/4.14.1/lib/ocaml -I /usr/home/opam/.opam/4.14.1/lib/bigarray-compat -I /usr/home/opam/.opam/4.14.1/lib/ctypes -I /usr/home/opam/.opam/4.14.1/lib/ctypes-foreign -I /usr/home/opam/.opam/4.14.1/lib/integers -I functions -I types -I llama.cpp -o extra_stubs.o -c extra_stubs.c)
# In file included from extra_stubs.c:2:
# In file included from llama.cpp/llama.h:4:
# llama.cpp/ggml.h:1816:31: warning: "callback" is deprecated: use "caml_callback" instead [-W#pragma-messages]
#             ggml_opt_callback callback,
#                               ^
# /usr/home/opam/.opam/4.14.1/lib/ocaml/caml/compatibility.h:71:18: note: expanded from macro 'callback'
# #define callback CAML_DEPRECATED("callback", "caml_callback") caml_callback
#                  ^
# /usr/home/opam/.opam/4.14.1/lib/ocaml/caml/misc.h:58:3: note: expanded from macro 'CAML_DEPRECATED'
#   CAML_PREPROWARNING(name1 is deprecated: use name2 instead)
#   ^
# /usr/home/opam/.opam/4.14.1/lib/ocaml/caml/misc.h:56:31: note: expanded from macro 'CAML_PREPROWARNING'
# #define CAML_PREPROWARNING(x) _Pragma(CAML_MAKEWARNING2(x))
#                               ^
# <scratch space>:112:6: note: expanded from here
#  GCC warning "\"callback\" is deprecated: use \"caml_callback\" instead"
#      ^
# In file included from extra_stubs.c:2:
# llama.cpp/llama.h:515:98: warning: "callback" is deprecated: use "caml_callback" instead [-W#pragma-messages]
#     LLAMA_API void llama_beam_search(struct llama_context * ctx, llama_beam_search_callback_fn_t callback, void * callback_data, size_t n_beams, int n_past, int n_predict, int n_threads);
#                                                                                                  ^
# /usr/home/opam/.opam/4.14.1/lib/ocaml/caml/compatibility.h:71:18: note: expanded from macro 'callback'
# #define callback CAML_DEPRECATED("callback", "caml_callback") caml_callback
#                  ^
# /usr/home/opam/.opam/4.14.1/lib/ocaml/caml/misc.h:58:3: note: expanded from macro 'CAML_DEPRECATED'
#   CAML_PREPROWARNING(name1 is deprecated: use name2 instead)
#   ^
# /usr/home/opam/.opam/4.14.1/lib/ocaml/caml/misc.h:56:31: note: expanded from macro 'CAML_PREPROWARNING'
# #define CAML_PREPROWARNING(x) _Pragma(CAML_MAKEWARNING2(x))
#                               ^
# <scratch space>:116:6: note: expanded from here
#  GCC warning "\"callback\" is deprecated: use \"caml_callback\" instead"
#      ^
# 2 warnings generated.
# (cd _build/default/src && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -g -I /usr/home/opam/.opam/4.14.1/lib/ocaml -I /usr/home/opam/.opam/4.14.1/lib/bigarray-compat -I /usr/home/opam/.opam/4.14.1/lib/ctypes -I /usr/home/opam/.opam/4.14.1/lib/ctypes-foreign -I /usr/home/opam/.opam/4.14.1/lib/integers -I functions -I types -I llama.cpp -o c_generated_functions.o -c c_generated_functions.c)
# c_generated_functions.c:268:10: warning: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
#    char* x198 = llama_token_get_text(x194, x195);
#          ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# c_generated_functions.c:351:52: warning: passing 'llama_grammar_element **' (aka 'struct llama_grammar_element **') to parameter of type 'const llama_grammar_element **' (aka 'const struct llama_grammar_element **') discards qualifiers in nested pointer types [-Wincompatible-pointer-types-discards-qualifiers]
#    struct llama_grammar* x288 = llama_grammar_init(x281, x282, x285);
#                                                    ^~~~
# llama.cpp/llama.h:409:44: note: passing argument to parameter 'rules' here
#             const llama_grammar_element ** rules,
#                                            ^
# c_generated_functions.c:599:10: warning: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
#    char* x518 = llama_print_system_info();
#          ^      ~~~~~~~~~~~~~~~~~~~~~~~~~
# c_generated_functions.c:607:18: warning: incompatible function pointer types passing 'void (*)(enum llama_log_level, char *, void *)' to parameter of type 'llama_log_callback' (aka 'void (*)(enum llama_log_level, const char *, void *)') [-Wincompatible-function-pointer-types]
#    llama_log_set(x521, x522);
#                  ^~~~
# llama.cpp/llama.h:527:53: note: passing argument to parameter 'log_callback' here
#     LLAMA_API void llama_log_set(llama_log_callback log_callback, void * user_data);
#                                                     ^
# 4 warnings generated.
```

**Comment by igarnier** [comment]
I think I fixed the BSD builds but there's more to do for macos.

**Comment by igarnier** [comment]
I think I fixed the builds. The remaining errors are probably CI flakiness. Over to you guys! cc @raphael-proust

**Pull request merged**
