### PR TITLE
[new release] mimic (v0.0.1)

### PR DESCRIPTION
**Pull request by dinosaure**
A simple protocol dispatcher

- Project page: <a href="https://github.com/mirage/ocaml-git">https://github.com/mirage/ocaml-git</a>
- Documentation: <a href="https://mirage.github.io/ocaml-git/">https://mirage.github.io/ocaml-git/</a>

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by kit-ty-kate** [comment]
Oh wait no, hm, the version number has the `v` prefix. Is that expected? Could you remove it?

**Comment by dinosaure** [comment]
Yes, I can redo the release without `v` if you want.

**Comment by dinosaure** [comment]
Replaced by #17944

**Pull request closed without merging**
