### PR TITLE
cohttp.0.11.0: fix depopts (needs both async and async_ssl)

### PR DESCRIPTION
**Pull request by planar**

### CODE REVIEW

**Comment by samoht** [comment]
@AltGr we should we do in opam 1.2 with this kind of constraints? 

@planar to give some context: in opam 1.2 the depopts must be a disjonction of packages, without constraints, as we hit some solver issues otherwise (can't remember exactly what was the problem ...). So npw we have to move the constraints into conflicts, but not sure about conjonctions as in that case.

**Comment by planar** [comment]
Can't it be a disjunction of conjunctions? My intuition tells me you can quickly get into trouble with negation (hence also with version constraints) but disjunction of conjunctions is another class of formulas, so I'd be interested in a detailed explanation.

In this case, I tried it and it worked...

Otherwise you'd have to say it's incompatible with (async and not async_ssl) but we don't have negation in the constraint language, right?

**Comment by AltGr** [comment]
OPAM 1.1 accepted it, but it didn't really work ; not as you would expect anyway (the constraint wouldn't be given to the solver, it would only be checked _before_ the solver was called, so it wouldn't prevent installing at once async and cohttp without async_ssl) ; the semantics you want is indeed a conflict. For backwards-compatibility, this awkward semantics is still accepted because your package is defined with `opam-version: "1"` rather than `opam-version: "1.2"`.

Indeed, I don't think Cudf supports arbitrary formulas as conflicts (this would easily add too much complexity to the NP-complete problem, defeating the solver's strategy) ; from previous discussions on the `features` field and depopts, our conclusion was that this general issue should be solved through better handling of packages' configure scripts rather than more complex dependencies.

In your case, that would mean depopts on both `async` and `async_ssl`, and passing `--enable/disable-async` to `./configure` depending on the presence of both (this can already be encoded with `"--%{async+async_ssl:enable}-async%", but the `features` field is planned to give more flexibility there). The only downside is that if async is changed, and you don't have `async_ssl`, an unneeded recompilation of `cohttp` will take place.

Of course, in your case, since `async_ssl` depends on `async`, you actually only need a depopt on `async_ssl`, and to adjust `./configure` accordingly.

**Comment by planar** [comment]
OK, thanks for the explanation. In this case we'd have to patch the package's `Makefile` because it auto-detects `async` but fails to test for `async_ssl`. As this is an old version of `cohttp`, I don't think it's worth the trouble.

**Pull request closed without merging**
