### PR TITLE
result 1.1

### LINKED ISSUE #4837: package "result" 1.0 fails to build
I get the following error when trying to install "result" (1.0) on both OS X and Linux:

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] File "$HOME/.opam/4.02.3/build/result.1.0/result.install", line 1, character 0-1: '-' is not a valid token.

#=== ERROR while installing result.1.0 ========================================#
OpamTypesBase.Lexer_error("'-' is not a valid token")

### PR DESCRIPTION
**Pull request by diml**
Fixes #4837

### CODE REVIEW

**Comment by avsm** [comment]
thanks, could you add a `os: linux` constraint to the old version too?

**Comment by diml** [comment]
sure, done

**Comment by diml** [comment]
Fixed the use of `|>` in gen_result_install.ml

**Comment by samoht** [comment]
why do you have gasoline in that patch?

**Pull request merged**
