### PR TITLE
Add gapi-ocaml 0.3.8

### PR DESCRIPTION
**Pull request by astrada**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
the `light-uninstall` flag was useless. Could you return the fix upstream?

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by astrada** [comment]
@kit-ty-kate sorry to bother you, but why I'm still not seeing version 0.3.8 when I do `opam update && opam upgrade`? I'm asking because in version 0.3.8 I fixed a severe bug that broke my application with http/2, so I would like to make it available as soon a possible. Thanks
screenshot from 2018-11-25 10-51-39

**Comment by mseri** [comment]
@astrada Should be fixed now

**Comment by astrada** [comment]
Thanks!

**Pull request merged**
