### PR TITLE
[new release] oidc (0.1.0)

### PR DESCRIPTION
**Pull request by ulrikstrid**
Base package for working with OIDC

- Project page: <a href="https://ulrikstrid.github.io/ocaml-oidc">https://ulrikstrid.github.io/ocaml-oidc</a>
- Documentation: <a href="https://ulrikstrid.github.io/ocaml-oidc">https://ulrikstrid.github.io/ocaml-oidc</a>

##### CHANGES:

- Initial release includes things needed to create a OpenID Connect Relayin Party (client)

### CODE REVIEW

**Comment by ulrikstrid** [comment]
I don't understand why it can't find `uunf.string`, does anyone know?

**Comment by kit-ty-kate** [comment]
According to its sources `uunf.string` is an optional dependency triggered by `uutf`: https://github.com/dbuenzli/uunf/blob/master/pkg/pkg.ml#L27

I've added the missing dependency. Could you return the fix upstream?

**Comment by ulrikstrid** [comment]
Yes, thank you @kit-ty-kate

**Comment by kit-ty-kate** [comment]
In e3f783c it seems you inadvertently used the opam file from your repository as is. However this removed the required `url` section added a few unrequired fields and the next commit removed the version constraint for some of your test dependencies. The syntax was indeed not correct but I'm assuming here that the constraints weren't there for nothing so I added them back with the right syntax along with everything else missing.

Could you return the fix in the opam file upstream while the CI re-checks everything?

**Comment by ulrikstrid** [comment]
The constraint is there from `jose` anyway so it's not a big issue, but I fixed it in the repo as well now. I can't access https://ci.ocaml.org for some reason so can't see what's wrong now.

I feel like I'm hitting a bunch of issues because I'm mainly using `esy` when developing so I don't hit some of these issues, sorry about the noise.

**Comment by kit-ty-kate** [comment]
Our CI is now back. Sorry for that.
It seems that a bunch more test dependencies are required `junit` `junit_alcotest` and `oidc-client` (which does not exist yet):
```
#=== ERROR while compiling oidc.0.1.0 =========================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(https://github.com/ulrikstrid/ocaml-oidc/releases/download/v0.1.0/oidc-v0.1.0.tbz)
# path                 ~/.opam/4.08/.opam-switch/build/oidc.0.1.0
# command              ~/.opam/4.08/bin/dune build -p oidc -j 72 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/oidc-29-d8be27.env
# output-file          ~/.opam/log/oidc-29-d8be27.out
### output ###
# File "test/dune", line 4, characters 29-40:
# 4 |    junit junit_alcotest oidc oidc-client containers))
#                                  ^^^^^^^^^^^
# Error: Library "oidc-client" not found.
# Hint: try: dune external-lib-deps --missing -p oidc -j 72 @install @runtest
```

**Comment by ulrikstrid** [comment]
I'll split out the tests. I can't release oidc-client because it depends on some forks and unreleased libraries by @anmonteiro

**Comment by ulrikstrid** [comment]
@kit-ty-kate I think everything should be good now. Again, sorry about the noise in this PR.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
