### PR TITLE
xtmpl is compatible with js_of_ocaml >= 3

### PR DESCRIPTION
**Pull request by zoggy**

### CODE REVIEW

**Comment by zoggy** [comment]
Installation fails with a missing js_of_ocaml-camlp4 package. That is strange, since it is not required by xtmpl (and I compile it on my machine with no such a package installed).

**Comment by jpdeplaix** [comment]
If so, something is clearly wrong somewhere in the build system.
Here ocamlfind is complaining about ```js_of_ocaml.syntax``` being required (in ```-package js_of_ocaml.syntax```) but not found.

```
 ocamlfind ocamlc -c -package sedlex,uutf,re.str,js_of_ocaml -annot -rectypes -safe-string -g xtmpl_js.mli
# ocamlfind ocamlc -c -package sedlex,uutf,re.str,js_of_ocaml \
# -package js_of_ocaml.syntax -syntax camlp4o \
# -annot -rectypes -safe-string -g xtmpl_js.ml
# Makefile:96: recipe for target 'xtmpl_js.cmo' failed
### stderr ###
# ocamlfind: Package `js_of_ocaml-camlp4' not found - required by `js_of_ocaml.syntax'
```

Could you also add the ```{build}``` attribute to ```ocamlfind``` ? I doubt this package is using the ```Findlib``` library.

**Comment by jpdeplaix** [comment]
Ping @zoggy

**Comment by kit-ty-kate** [comment]
Ping @zoggy

**Comment by avsm** [comment]
Going to close this PR as it has lingered for a long time. @zoggy, please do reopen with the latest master branch if you still need it.

**Pull request closed without merging**
