### PR TITLE
Yojson 2 constraints

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
This PR is (collecting) the Yojson 2.0.0 maximum constraints that are being revealed by the revdeps of #21460. I'll try to open PRs to the upstream projects which are affected so future releases will support newer Yojson versions again.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
@c-cube I know it is archived but it looks like the tarball of `cconv.0.2` is messed up. Wonder whether to replace it with the one from the OPAM cache?

**Comment by mseri** [comment]
I think this may be full of lower-bound issues. I suggest not to bother with them now unless there is something trivial to fix. I will try to solve them separately in subsequent PRs

**Comment by c-cube** [comment]
@Leonidas-from-XIV I think the opam-repo should be updated to use https://github.com/c-cube/cconv/archive/refs/tags/0.2.tar.gz if it's not in sync.

**Comment by Leonidas-from-XIV** [comment]
@mseri Ok, I fixed the whole rat-tail of minimum version failures, but there's some leftover failures like `obus.1.1.8` which is failing on… unclear what. Maybe ocamlfind? Maybe oasis? Do you have an idea?

**Comment by mseri** [comment]
Thanks a lot. I will have a look at this PR tomorrow and most likely merge it. After that we can try the yojson PR again

**Comment by Leonidas-from-XIV** [comment]
Great, let me know when to rebase and squash all the fixup commits. I let it like this for now so the links to the CI would work.

**Review by mseri — APPROVED** [review]
Looks great. Thanks a lot

**Comment by Leonidas-from-XIV** [comment]
Ok, I rebased and squashed the constraint-adding commits into one as well as the respective `fixup` commits, to the list of commits should be reasonably clean. No further changes.

**Pull request merged**
