### PR TITLE
elpi 1.2

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
Looks good now.

**Comment by kit-ty-kate** [comment]
I see you're using `ocamlfind` in your build system and it wasn't explicitly present in your dependencies.
Could you return my fix upstream?

**Comment by kit-ty-kate** [comment]
It seems good otherwise

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by gares** [comment]
Thanks

**Pull request merged**
