### PR TITLE
Revert #14294 and restore package-specific .gitattributes

### PR DESCRIPTION
**Pull request by dra27**
**DO NOT MERGE YET!**

This PR can merged when https://github.com/esy/esy/issues/936 is resolved.

Also note https://github.com/ocaml/opam/pull/3873, though this change wouldn't affect `esy` since it doesn't use `index.tar.gz`

cc @jordwalke, @andreypopp

### CODE REVIEW

**Comment by dra27** [comment]
This issue has been fixed in esy 0.5.8, so this PR just needs a thumbs up from the esy team that they're confident that enough users have migrated.

**Comment by mseri** [comment]
@dra27 this is now conflicting with gitattributes

@jordwalke, @andreypopp can we merge this?

**Comment by dra27** [comment]
The conflict was just from #14348 - rebased to avoid it.

**Comment by kit-ty-kate** [comment]
I'm not sure this PR should stay open indefinitely as it is just a superficial fix and things seems fine as they are. Please reopen if needed.

**Pull request closed without merging**
