### PR TITLE
oasis 0.4.6

### PR DESCRIPTION
**Pull request by gildor478**

### CODE REVIEW

**Comment by avsm** [comment]
thanks!

**Comment by gildor478** [comment]
@avsm @dsheets first time I submit something to OPAM. What is the ETA of the update? The PR was merged 3h ago and I cannot (yet) install OASIS 0.4.6.

I am fine waiting, just want to know when the update should happen.

**Comment by dsheets** [comment]
For users who have the repository checked out and have pointed an opam remote at it, the update has already happened. For users who use `https://opam.ocaml.org/`, there appears to be a delay but there shouldn't be one. I think there may be something wrong with the repo update scripts, @AltGr ?

**Comment by samoht** [comment]
I think there were an issue in the cron job, I've tweaked it a bit, should be updating the website every hour now.

**Pull request merged**
