### PR TITLE
make camlp4 compatible with bytecode-only switches

### PR DESCRIPTION
**Pull request by fdopen**
cc @diml

### CODE REVIEW

**Comment by diml** [comment]
Thanks, BTW are there opam switches that we can use to test byte code only builds?

**Comment by fdopen** [comment]
You can use `4.04.0+bytecode-only`, i've just added it: https://github.com/ocaml/opam-repository/pull/8603
However, there are many buildsystem that can't deal with it properly (e.g. oasis). So it's only useful for packages without much dependencies.

**Comment by dbuenzli** [comment]
> Thanks, BTW are there opam switches that we can use to test byte code only builds?

I [prayed](http://lists.ocaml.org/pipermail/opam-devel/2016-February/001339.html) more than once to our CI gods that we should at least have one byte code only testing target. It may never have materalized because travis was already too saturated. Has maybe now the situation changed ? 

Also there is [this problem](https://gitlab.camlcity.org/gerd/lib-findlib/issues/5) I'm not sure the fix made it to a release.

**Comment by avsm** [comment]
See this https://github.com/ocaml/opam-repository/pull/8603#issuecomment-283946861 about concern with a bytecode only switch. We could build containers that are x86_64/bytecode only, but I worry that users will continue to have problems with shadowed ocamlopt binaries in their PATH.

**Comment by avsm** [comment]
this is safe to merge without all the revdeps. thanks!

**Comment by diml** [comment]
@avsm, in Jbuilder I first look for `ocamlc` in the `PATH` and then I look for the other binaries from the compiler distribution only in the same directory as `ocamlc`. So projects using Jbuilder will gracefully support bytecode only switches even if there is a previous `ocamlopt` available

**Pull request merged**
