### PR TITLE
Add base-raw_spacetime

### PR DESCRIPTION
**Pull request by lpw25**
Add a "base" package to represent `raw_spacetime_lib` which was added to the compiler distribution in version 4.04. Since the corresponding findlib library was added in version 1.7.1, I added a dependency on that as well.

### CODE REVIEW

**Comment by dbuenzli** [comment]
Please don't add the `base` prefix.

**Comment by lpw25** [comment]
I thought all the otherlibs had a `base` prefix

**Comment by dbuenzli** [comment]
> I thought all the otherlibs had a base prefix

Yes but it's a bad idea. If we align the OPAM package names with those of the ocamlfind package name with those of the library archive names, it makes things a bit easier for everyone.

**Comment by lpw25** [comment]
I don't mind either way. However, the repository maintainers want to name things is fine by me.
> If we align the OPAM package names with those of the ocamlfind package name with those of the library archive names
Unfortunately, ocamlfind already uses a name that differs from the archive name. The archive has a gratutitous `_lib` on the end.

**Comment by dbuenzli** [comment]
> The archive has a gratutitous _lib on the end.

Good +1.

**Comment by lpw25** [comment]
I should probably point out that this is blocking any release of the spacetime tools, and I'm not sure how to proceed. I can see two lint warnings from "camelus", but those seem to apply to the existing `base-` packages as well. I can also see a failure of the installability check -- but there is no additional information so I don't know what is actually wrong.

**Comment by samoht** [comment]
Would it be possible to align all the names as suggested by @dbuenzli?

**Comment by lpw25** [comment]
Do you mean changing all the `base-` packages, or just renaming this one to `raw_spacetime`?

It's probably too late to change the name of the archive. It would require another release of both the compiler and ocamlfind.

**Comment by dbuenzli** [comment]
> or just renaming this one to raw_spacetime?

Renaming the others will need some migration steps. Just this package name would be good.

**Comment by mshinwell** [comment]
I don't understand why we should be changing other package names at the same time as introducing this new one.  That seems like mixing up concerns, which is generally a mistake.  The right thing to do would seem to be to follow the existing naming convention so we can get this out---it is blocking a significant advance in profiling tools---and then, after that if so desired, rename everything together.  It seems better for everything to be consistent at all times, even if that consistency is not yet the desired result.

**Comment by dbuenzli** [comment]
By the way I don't know `ocamlfind` had to be changed for that it would have been sufficient to add a `META` file to this virtual package.

**Comment by avsm** [comment]
There's no need to change the other base packages at the moment. Just renaming this one to `raw_spacetime` would be fine. We can tackle the other ones at a later date and unblock the spacetime merge now.

**Comment by lpw25** [comment]
Ok, I've renamed it.

**Comment by samoht** [comment]
Thanks. TravisCI says:

```
The following dependencies couldn't be met:
  - raw_spacetime -> ocamlfind >= 1.7.1
Your request can't be satisfied:
  - No package matches ocamlfind>=1.7.1.
```

Is this expected? If that requires a new version of ocamlfind can we check that the names are consistent there too? btw. I am also not sure why this needs  new version of ocamlfind, as Daniel pointed out if you just need a META file, put it it unders `files/` with the appropriate install file.

**Comment by lpw25** [comment]
> Is this expected?

It is now that I see the latest version of ocamlfind isn't on opam. Who is responsible for maintaining the ocamlfind package on opam?

> I am also not sure why this needs a new version of ocamlfind

Builtin libraries have there META files provided by ocamlfind

**Comment by avsm** [comment]
ocamlfind 1.7.1: https://github.com/ocaml/opam-repository/pull/7921

could you merge that branch to this PR please?

**Comment by lpw25** [comment]
Done

**Comment by samoht** [comment]
All green, thanks!

**Pull request merged**
