### PR TITLE
[new release] phylogenetics (0.0.0)

### PR DESCRIPTION
**Pull request by pveber**
Algorithms and datastructures for phylogenetics

- Project page: <a href="https://github.com/biocaml/phylogenetics/">https://github.com/biocaml/phylogenetics/</a>

##### CHANGES:

First release on OPAM

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The tests fail with:
```
#=== ERROR while compiling phylogenetics.0.0.0 ================================#
# context              2.0.10 | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(https://github.com/biocaml/phylogenetics/releases/download/v0.0.0/phylogenetics-0.0.0.tbz)
# path                 ~/.opam/4.08/.opam-switch/build/phylogenetics.0.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p phylogenetics -j 31 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/phylogenetics-1365-5f1023.env
# output-file          ~/.opam/log/phylogenetics-1365-5f1023.out
### output ###
#       menhir lib/newick_parser_errors.ml
# Read 3 sample input sentences and 2 error messages.
#     test_app alias app/runtest (exit 1)
# (cd _build/default/app && ./test_app.exe)
# Testing `All tests'.
# This run has ID `RIVTWXR8'.
# 
#   [OK]          Sequence                    0   of_string.
#   [OK]          Alignment                   0   of_string_list.
#   [OK]          Alignment                   1   of_fasta.
#   [OK]          Alignment                   2   get_base.
#   [OK]          Phylogenetic_tree           0   of_preorder.
#   [OK]          Zipper                      0   of_tree (check subtrees).
#   [OK]          Zipper                      1   of_tree (check lengths).
#   [OK]          Zipper                      2   of_tree and back to_tree.
#   [OK]          Zipper                      3   of_tree_dir, move_left and ba...
#   [OK]          Zipper                      4   goto vs several moves.
#   [OK]          Models                      0   JC69 exponential.
#   [OK]          Models                      1   K80 exponential.
# > [FAIL]        Felsenstein                 0   Biocaml vs bppml	JC69	treesiz...
#   [FAIL]        Felsenstein                 1   Biocaml vs bppml	JC69	treesiz...
#   [FAIL]        Felsenstein                 2   Biocaml vs bppml	JC69	treesiz...
#   [FAIL]        Felsenstein                 3   Biocaml vs bppml	JC69	treesiz...
#   [FAIL]        Felsenstein                 4   Biocaml vs bppml	K80(kappa=2....
#   [FAIL]        Felsenstein                 5   Biocaml vs bppml	K80(kappa=2....
#   [FAIL]        Felsenstein                 6   Biocaml vs bppml	K80(kappa=2....
#   [FAIL]        Felsenstein                 7   Biocaml vs bppml	K80(kappa=2....
#   [FAIL]        Felsenstein                 8   Biocaml vs bppml	K80(kappa=0....
#   [FAIL]        Felsenstein                 9   Biocaml vs bppml	K80(kappa=0....
#   [FAIL]        Felsenstein                10   Biocaml vs bppml	K80(kappa=0....
#   [FAIL]        Felsenstein                11   Biocaml vs bppml	K80(kappa=0....
#   [FAIL]        Felsenstein                12   Biocaml vs bppml	JC69	treesiz...
#   [FAIL]        Felsenstein                13   Biocaml vs bppml	JC69	treesiz...
#   [FAIL]        Felsenstein                14   Biocaml vs bppml	JC69	treesiz...
#   [FAIL]        Felsenstein                15   Biocaml vs bppml	JC69	treesiz...
#   [FAIL]        Felsenstein                16   Biocaml vs bppml	K80(kappa=4....
#   [FAIL]        Felsenstein                17   Biocaml vs bppml	K80(kappa=4....
#   [FAIL]        Felsenstein                18   Biocaml vs bppml	K80(kappa=4....
#   [FAIL]        Felsenstein                19   Biocaml vs bppml	K80(kappa=4....
#   [OK]          Rejection_sampling          0   Specific branch length on tin...
#   [OK]          MCMC                        0   Specific branch length on tin...
#   [OK]          Newick                      0   just_parse_test1.
#   [OK]          Newick                      1   just_parse_test2.
#   [OK]          PhyloCTMC                   0   Felsenstein vs Phylo_ctmc.
# 
# ┌──────────────────────────────────────────────────────────────────────────────┐
# │ [FAIL]        Felsenstein                 0   Biocaml vs bppml	JC69	tree...  │
# └──────────────────────────────────────────────────────────────────────────────┘
# ERROR (bpp_interface): bppml failed:
# sh: 1: bppml: not found
# 
# ERROR(felsenstein_bpp): bppml failed
# ASSERT identical log likelihoods!
# FAIL identical log likelihoods!
# 
#    Expected: `-10.1039'
#    Received: `0'
# 
# Raised at file "src/alcotest-engine/test.ml", line 196, characters 4-261
# Called from file "src/alcotest-engine/core.ml", line 180, characters 17-23
# Called from file "src/alcotest-engine/monad.ml", line 24, characters 31-35
# 
# Logs saved to `~/.opam/4.08/.opam-switch/build/phylogenetics.0.0.0/_build/default/app/_build/_tests/All tests/Felsenstein.000.output'.
#  ──────────────────────────────────────────────────────────────────────────────
# 
# Full test results in `~/.opam/4.08/.opam-switch/build/phylogenetics.0.0.0/_build/default/app/_build/_tests/All tests'.
# 20 failures! in 12.079s. 37 tests run.
```
Could you have a look?

**Comment by kit-ty-kate** [comment]
The bppphyview package is only available on Debian-based systems as well. Could this test be optional?

**Comment by pveber** [comment]
Sorry I overlooked that aspect! Would it be possible to disable tests completely for this release? And for the next I'll just include `bppml`'s output in the test once and for all, instead of requiring it at run time.

**Comment by mseri** [comment]
I'll open a separate PR for the biocaml failure

**Comment by pveber** [comment]
Alright, as per biocaml/phylogenetics@a107e96, the tests requiring bppml (as well as slow tests) are skipped by default. That will be for next release though. Thanks again for the reviews!

**Pull request merged**
