### PR TITLE
8 packages from savonet/ocaml-ffmpeg at 1.0.2

### PR DESCRIPTION
**Pull request by toots**
This pull-request concerns:
-`ffmpeg.1.0.2`: Bindings for the ffmpeg libraries
-`ffmpeg-av.1.0.2`: Bindings for the ffmpeg libraries -- top-level helpers
-`ffmpeg-avcodec.1.0.2`: Bindings for the ffmpeg avcodec library
-`ffmpeg-avdevice.1.0.2`: Bindings for the ffmpeg avdevice library
-`ffmpeg-avfilter.1.0.2`: Bindings for the ffmpeg avfilter library
-`ffmpeg-avutil.1.0.2`: Bindings for the ffmpeg avutil libraries
-`ffmpeg-swresample.1.0.2`: Bindings for the ffmpeg swresample library
-`ffmpeg-swscale.1.0.2`: Bindings for the ffmpeg swscale library

---
* Homepage: https://github.com/savonet/ocaml-ffmpeg
* Source repo: git+https://github.com/savonet/ocaml-ffmpeg.git
* Bug tracker: https://github.com/savonet/ocaml-ffmpeg/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by toots** [comment]
This is a bugfix release, fixing a deadlock in read/write callbacks in `Av` streams.

**Comment by toots** [comment]
Summary of CI failures:
* Absence of ffmpeg upstream packages or outdated ffmpeg packages (alpine, archlinux, centos, fedora, oraclelinux, ubuntu-18.04)
* Missing runtime codec (suse)
* Issue with CI runner hardware acceleration (ffmpeg-avutil on ubuntu 18.04, ubuntu 21.04)
* Incorrect dependencies logic (liquidsoap 2.0.x). Should be addressed in a separate PR, most likely with the forthcoming 2.0.1 bugfix release.

**Comment by mseri** [comment]
Thanks for the report! Does it mean that liquidsoap and liquidsoap-daemon need upper bounds/conflicts on ffmpeg? In this case I'd like to have the upper bounds/conflicts added before we merge this

**Comment by toots** [comment]
It's a little more complex. Liquidsoap can use different combinations of the various sub-packages for the different optional ffmpeg-related features. I'd like to take a moment to decide if we want to use specific `conf-*` like we did for sdl or else just depends on the top-level `ffmpeg` package and enable all of them at once.

**Comment by toots** [comment]
Also, there's a bug in way liquidsoap picks up optional features based on available ffmpeg packages, which causes the build failure listed in the CI. This, too, will be fixed with the upcoming bugfix.

**Comment by toots** [comment]
Hi,

Apology, I rushed this release because it contains a fix for a pretty bad ocaml runtime deadlock when using caml read/write callbacks. However, we will need to do a full `1.1.0` release in the coming days with the upcoming `2.0.1` bugfix release of liquidsoap.

Shall I close this PR?

**Comment by toots** [comment]
Closed in favor of: https://github.com/ocaml/opam-repository/pull/20119

**Pull request closed without merging**
