### PR TITLE
Js_of_ocaml.3.1.0

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
ready to be merged.

**Comment by hcarty** [comment]
The Travis build looks ok but I can't view any of the datakit failures - the connection times out.  One of the datakit messages here in the github interface says `js_of_ocaml-toplevel 3.1.0 failed`.  Do you know if that's an expected failure or a CI error @hhugo?

**Comment by hhugo** [comment]
@hcarty, This is the CI not managing to download the archive. I have to manually press the retry button every time this happens. It's actually quite painful.

```
 [ERROR] The sources of the following couldn't be obtained, aborting:
          - js_of_ocaml.3.1.0
          - js_of_ocaml-compiler.3.1.0
          - js_of_ocaml-ppx_deriving_json.3.1.0
```

**Comment by hcarty** [comment]
@hhugo The failures all seem unrelated.  I'm ok with merging this now if you are!

**Comment by hhugo** [comment]
You can merge.
Thanks

**Comment by hcarty** [comment]
Thank you!

**Pull request merged**
