### PR TITLE
[new release] js_of_ocaml-ocamlbuild, js_of_ocaml-compiler, js_of_ocaml-ppx, js_of_ocaml-lwt, js_of_ocaml-toplevel, js_of_ocaml-tyxml, js_of_ocaml and js_of_ocaml-ppx_deriving_json (3.7.1)

### PR DESCRIPTION
**Pull request by hhugo**
Compiler from OCaml bytecode to Javascript

- Project page: <a href="http://ocsigen.github.io/js_of_ocaml">http://ocsigen.github.io/js_of_ocaml</a>

## Features/Changes
* lib: Add Navigator.{vendor,maxTouchPoints} (ocsigen/js_of_ocaml#1062)
* lib: adds the intersection observer API (ocsigen/js_of_ocaml#1063)

## Bug fixes
* compiler: revert of "Eliminate allocation of dummy function ocsigen/js_of_ocaml#1013"
* compiler: fix for ocsigen/js_of_ocaml#1051 (ocsigen/js_of_ocaml#1052), Ensure the overflow warning is always displayed
* runtime: add missing primitives for 4.11
* lib: Fix resize-observer (ocsigen/js_of_ocaml#1058)

### CODE REVIEW

**Comment by hhugo** [comment]
`js_of_ocaml-compiler.3.7.0` is broken, is there anyway to reflect that in its opam file ?

**Comment by hannesm** [comment]
@hhugo 
> js_of_ocaml-compiler.3.7.0 is broken, is there anyway to reflect that in its opam file ?

a `available: false` line in the opam file leads to opam never selecting that particular package.

**Comment by hhugo** [comment]
> @hhugo
> 
> > js_of_ocaml-compiler.3.7.0 is broken, is there anyway to reflect that in its opam file ?
> 
> a `available: false` line in the opam file leads to opam never selecting that particular package.

I've just done that, thanks

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
