### PR TITLE
[WIP] pre-release of ppx_deriving.4.3

### PR DESCRIPTION
**Pull request by gasche**
This is a pre-release commit to test the ppx_deriving revdeps in the
opam-repository CI. Don't merge yet!

First attempt: https://github.com/ocaml/opam-repository/pull/13652

This second attempt incorporates minor changes to the opam file (no
other change to the ppx_deriving pre-release), and occurs after the
revdeps failures of the first attempt have been reviewed and fixed.

### CODE REVIEW

**Comment by XVilka** [comment]
Are there any updates regarding this?

**Comment by gasche** [comment]
There are more reverse-dependency failures than I anticipated, and I would like to have a look to understand what is failing -- the first pass I did on revdep failures was fairly instructive. I haven't had the time to do a full sweep yet.

If anyone is willing to assist in this work, here is the workflow:

- go to the [revdeps CI results](https://ci.ocamllabs.io/ocaml/opam-repository/pr/14018?test=2%20Revdeps), - go to the log of any of the packages that fails to build
- figure out why the package fails to build (it could be ppx_deriving related, or it could be an unrelated failure; usually the log is telling)
- devise a fix for the opam-repository (typically: adding missing dependencies or adding missing upper-bounds on some dependencies)
- if the last version of the software is also affected (and not just older releases), notify the upstream maintainer; typically I do this by sending a pull request against the in-package `.opam` file(s).

**Comment by kit-ty-kate** [comment]
Ok I took a look and the only related failures are:
* ppx_deriving_argparse 0.0.{4,5}
```
#=== ERROR while compiling ppx_deriving_argparse.0.0.4 ========================#
# context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.07/.opam-switch/build/ppx_deriving_argparse.0.0.4
# command              ~/.opam/4.07/bin/ocamlbuild -classic-display -use-ocamlfind src_test/test.byte --
# exit-code            10
# env-file             ~/.opam/log/ppx_deriving_argparse-17-58a313.env
# output-file          ~/.opam/log/ppx_deriving_argparse-17-58a313.out
### output ###
# ocamlfind ocamldep -package result -package oUnit -modules src_test/test.ml > src_test/test.ml.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -ppx 'ocamlfind ppx_deriving/ppx_deriving src/ppx_deriving_argparse.cma /home/opam/.opam/4.07/lib/ppx_deriving/ppx_deriving_show.cma' -I /home/opam/.opam/4.07/lib/ppx_deriving/ -package result -package oUnit -w @5@8@10@11@12@14@23@24@26@29@40 -I src_test -I src -o src_test/test.cmo src_test/test.ml
# + ocamlfind ocamlc -c -g -bin-annot -safe-string -ppx 'ocamlfind ppx_deriving/ppx_deriving src/ppx_deriving_argparse.cma /home/opam/.opam/4.07/lib/ppx_deriving/ppx_deriving_show.cma' -I /home/opam/.opam/4.07/lib/ppx_deriving/ -package result -package oUnit -w @5@8@10@11@12@14@23@24@26@29@40 -I src_test -I src -o src_test/test.cmo src_test/test.ml
# File "_none_", line 1:
# Error: Cannot load /home/opam/.opam/4.07/lib/ppx_deriving/ppx_deriving_show.cmxs: cannot find file /home/opam/.opam/4.07/lib/ppx_deriving/ppx_deriving_show.cmxs in search path
# Command exited with code 2.
```
* every version of uwt < 0.3.2:
```
#=== ERROR while compiling uwt.0.0.2 ==========================================#
# context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.07/.opam-switch/build/uwt.0.0.2
# command              ~/.opam/4.07/bin/omake test
# exit-code            2
# env-file             ~/.opam/log/uwt-17-dbd123.env
# output-file          ~/.opam/log/uwt-17-dbd123.out
### output ###
# *** omake: reading OMakefiles
# *** omake: finished reading OMakefiles (0.02 sec)
# - build examples show_uwt.o
# + ocamlfind ocamlc -package ppx_import,unix,ppx_deriving.show -g -bin-annot -safe-string -g -I . -I ../src -c show_uwt.ml
# File "_none_", line 1:
# Error: Unbound value Stdlib.Bytes.pp
# *** omake: 257/355 targets are up to date
# *** omake: failed (1.03 sec, 26/54 scans, 11/100 rules, 51/112 digests)
# *** omake: targets were not rebuilt because of errors:
#    examples/show_uwt.cmi
#       depends on: examples/show_uwt.ml
#    examples/show_uwt.cmo
#       depends on: examples/show_uwt.ml
#    examples/show_uwt.cmx
#       depends on: examples/show_uwt.ml
#    examples/show_uwt.o
#       depends on: examples/show_uwt.ml
```

**Comment by kit-ty-kate** [comment]
ok so I looked it up and for `uwt < 0.3.2` it was already there before but I can't find the reason behind it.
For `ppx_deriving_argparse.0.0.{4,5}` I think that needs an upper-bound constraint. I'll do it then merge this PR

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Comment by kit-ty-kate** [comment]
oh nevermind, it was really just a test release. @gasche could you do a release? I think it's ready.

**Comment by gasche** [comment]
Ack, will do this shortly. Thanks for your work.

**Pull request closed without merging**
