### PR TITLE
Deleting oma.20240106 because three functions contain serious bugs.

### PR DESCRIPTION
**Pull request by fpottier**
These bugs are fixed in the next release (submitted today).

### CODE REVIEW

**Comment by raphael-proust** [comment]
We generally prefer the packages to be marked with

```
flags: [ avoid-version ]
```

rather than deleted. And this applies to buggy packages too. Is there any reason to delete rather than mark to be avoided?

**Comment by fpottier** [comment]
No, no reason. I didn't know about `avoid-version`. I can use that.

**Comment by fpottier** [comment]
Done.

**Comment by fpottier** [comment]
The checks have passed.

**Pull request merged**
