### PR TITLE
[opam-publish] OcLaunch.0.2.1

### PR DESCRIPTION
**Pull request by leowzukw**
Pull-request generated by opam-publish v.0.1-beta

### CODE REVIEW

**Comment by dsheets** [comment]
```
# File "src/const.ml", line 39, characters 5-13:
# Error: Unbound module Core
```

**Comment by leowzukw** [comment]
Same problem as #4011

Try analog solution

**Comment by dsheets** [comment]
```
# Fatal error: exception Sys_error("src/*.atd: No such file or directory")
```

Globs aren't allowed as the commands are exec'd rather than run inside a shell.

**Comment by leowzukw** [comment]
So I should give complete name i.e. ```settings.atd```?

With my local opam pin, it doesn't work.

**Comment by dsheets** [comment]
What doesn't work? Does the current version work?

**Comment by leowzukw** [comment]
The archive http://download.tuxfamily.org/oclaunch/sources/oclaunch-v0.1.3.tar.gz compiles with proper preparation. (oasis setup and atdgen -t/-j/-b/-v src/settings.atd). This is not working with opam, but I give this archive up.

I patched it and it create http://download.tuxfamily.org/oclaunch/sources/oclaunch-v0.1.3_patched.tar.gz. On my computer, when I get the archive, extract and do
``` bash
ocaml setup.ml -configure
ocaml setup.ml -build
```
It produces binaries.

But when I do
```bash
oasis2opam http://download.tuxfamily.org/oclaunch/sources/oclaunch-v0.1.3_patched.tar.gz
opam pin add oclaunch-test ./OcLaunch.0.1.3
```

It can't install.
The error is 
```
Cannot find file setup.ml.
```

**Comment by dsheets** [comment]
This error is because `oasis2opam` creates a metadata directory and `opam pin` expects a source directory. If you look inside `OcLaunch.0.1.3`, you'll find there is only opam metadata in there and not any source (and therefore not `setup.ml`). If you move `OcLaunch.0.1.3` to `opam/` inside of the corresponding source directory, you should then be able to pin the package modulo whatever fixups to the `oasis2opam` file are necessary.

**Comment by leowzukw** [comment]
Ok thanks

**Comment by Chris00** [comment]
>  modulo whatever fixups to the oasis2opam file are necessary.

Ideally, there should not be any.  If you need some, please [report an issue](https://github.com/ocaml/oasis2opam) and we'll see what we can do.

**Comment by leowzukw** [comment]
Travis can't find ocamlbuild

```
# E: Failure("Command ''/home/lwzukw/.opam/4.01.0/bin/ocamlbuild' src/oclaunch.native -tag debug' terminated with error code 127")
```

**Comment by yallop** [comment]
It looks like you're including the configuration data in the tarball.  Removing `setup.data` should fix it.

**Comment by leowzukw** [comment]
It works... sometimes

**Comment by dsheets** [comment]
`|>` is OCaml 4.01 or later. You need to use `available: [ ocaml-version >= "4.01.0"]` or similar.

**Comment by leowzukw** [comment]
It works!

**Pull request merged**
