### PR TITLE
Fix kaputt.1.2 for 4.06.0

### PR DESCRIPTION
**Pull request by chambart**
This is some simple safe-string fix

### CODE REVIEW

**Comment by rgrinberg** [comment]
Is it possible to just submit this patch upstream and let the maintainer (cc @xclerc) take care of it?. IMHO we should avoid accepting patches in opam-repository as much as possible.

**Comment by chambart** [comment]
This was submitted upstream. But I still intend to use this version before a release occur.

**Comment by rgrinberg** [comment]
Can't you just use the patch locally and wait until a release? What's the urgency in using a patched version of kaputt?

Sorry but I think that we should be applying patches like this in opam-repository only as an absolute last resort. filing patches to opam-repository is not really conducive to do proper review/testing. Especially when it's done without the upstream author's consent. If the issue is that the package's release cycle is slow, can you consider helping out with that instead?

**Comment by chambart** [comment]
This is not for personal usage, but for a project that is currently moving to 4.06 and needs this for its release. I'm not considering taking over the maintenance of kaputt.

By the way this was suggested by the author @xclerc, hence I suppose that I have his consent.

**Comment by avsm** [comment]
Very small fixes like this that are constrained to a particular ocaml version and do not change interfaces are just about ok in opam, particularly if upstream isn't actively maintained any more and there are users that need it.  Just bear in mind that it adds some complexity in the long-term (for instance, if you try to `pin --dev` for kaputt)

**Comment by rgrinberg** [comment]
OK, then it's fine if we have @xclerc 's approval. But if he already read and approved the patch, making the point release doesn't seem like a more time consuming than making a PR here. I don't think that should require stepping up as a maintainer for a package.

**Comment by hcarty** [comment]
This PR has been sitting here for a long time.  We should either accept it or reject it rather than letting it continue to sit - @avsm @rgrinberg what are your current opinions?

**Comment by rgrinberg** [comment]
I would have preferred to hear xclerc here. My stance is still to discourage this kind of stuff as much as possible and encourage removing the barriers upstream in making routine patch release work not to be bottlenecked by a single maintainer.

But we can trust @chambart's word here, so I'm merging.

**Pull request merged**
