### PR TITLE
[Lambdoc] Do not attempt installation of 'css' and 'examples'

### PR DESCRIPTION
**Pull request by darioteixeira**

### CODE REVIEW

**Comment by darioteixeira** [comment]
Well, OPAM does not recreate the directory structure, and therefore its useless to install these files.

**Comment by dbuenzli** [comment]
It does, but you need to specify the destination, i.e: 

```
"css/boxout-warning.png" { "css/boxout-warning.png" }
...
```

**Comment by darioteixeira** [comment]
> It does, but you need to specify the destination, i.e:

Ah, thanks, I had missed that. Fixed now.

**Comment by darioteixeira** [comment]
Well, it seems OPAM does not like to install symbolic links.  Is this a known limitation?

**Comment by dbuenzli** [comment]
> Well, it seems OPAM does not like to install symbolic links.

Well I guess it has the semantics of `install` or `cp`. I don't know if that really qualifies as a "limitation", I can see all sorts of problems if symlinks are treated as such (e.g. they are relative to your build dir which will be destroyed, etc.).

**Comment by darioteixeira** [comment]
> Well I guess it has the semantics of install or cp. I don't know if that really qualifies as a "limitation",
> I can see all sorts of problems if symlinks are treated as such (e.g. they are relative to your build dir
> which will be destroyed, etc.).

In the general case symlinks can be problematic, yes.  In this particular case they are safe, though, as the targets are also part of the install manifest.

Anyway, I've amended the PR so that the manuals are not installed (for now).

**Comment by darioteixeira** [comment]
This can be merged.  One of tests may have failed, but extraneous reasons.

**Pull request merged**
