### PR TITLE
Update to gasoline 0.3.0

### PR DESCRIPTION
**Pull request by michipili**

### CODE REVIEW

**Comment by michipili** [comment]
For one thing, we have the usual *bmake*-related false positive.  One build failed for wrong reasons, it looks like it stalled.  Maybe someone with appropriate credentials can retry it?

**Comment by samoht** [comment]
job restarted.

**Comment by samoht** [comment]
Travis is now green. Could you fix the other warning/errors in the opam file so that only error 39 remains? Thanks!

**Comment by michipili** [comment]
Sure, thanks!

**Comment by michipili** [comment]
There is two failed builds in Travis because of network issues, apparently.

**Comment by amirmc** [comment]
Restarted those builds.

**Comment by michipili** [comment]
Thanks, everything looks green now.

**Comment by samoht** [comment]
Error 32 can still be fixed later, thanks!

**Pull request merged**
