### PR TITLE
Re-add Camomile.0.8.6

### PR DESCRIPTION
**Pull request by jpdeplaix**
@toots This time I finally located the cause of your problem: the default directory as far as camomile was concerned was in ```%{share}%```. But this variable is not equal to ```~/.opam/<switch>/share/camomile``` but rather ```~/.opam/<switch>/share```.

I've tested it and liquidsoap works (at least ```./liquidsoap``` doesn't raise an error related to camomile anymore). I also tested using this small test-case which previously failed:
```ocaml
module C = CamomileLibraryDyn.Camomile.CharEncoding
```

cc @gasche

### CODE REVIEW

**Comment by gasche** [comment]
Well at least I'm glad to see that there was, in the end, a reason for being really prudent on this one.

@toots, would you review the current proposal (and maybe the corresponding part of the `configure.ml`, so that we have at least two people who agree they understand the issue)?

If you both agree and the CI passes, I'll merge the PR.

**Comment by toots** [comment]
Seems like it's indeed installing the files where they should be, thanks!

On a side note, maybe `opam` could be more verbose when using `install` and `remove` files? There is literally nothing in the logs, even in `--verbose` mode and nothing in the `opam` file. Makes it difficult to spot and debug install issues..

Thanks y'all tho!

**Comment by jpdeplaix** [comment]
> On a side note, maybe opam could be more verbose when using install and remove files? There is literally nothing in the logs, even in --verbose mode and nothing in the opam file. Makes it difficult to spot and debug install issues..

What do you mean by ```install``` and ```remove``` files ? ```--verbose``` indeed showed the fully expended command ```ocaml "configure.ml" "--share" "/home/jpdeplaix/.opam/4.05.0/share/"``` but the consequences where hidden inside the script (configure.ml) so it was not really easy to see what was happening just by reading the logs.

**Comment by toots** [comment]
@jpdeplaix I would love to see logs of which files are installed and where. Something like:
```
install file foo at /path/to/installed/foo
```

**Comment by jpdeplaix** [comment]
@toots the install files in ```~/.opam/<switch>/install/``` give you just that although it is only available for packages that have an .install file (but this package has one).
I may be wrong but I believe opam 2.0 has something like this for packages which use ```install``` and ```remove``` rules instead of an .install file (if this is what you meant).

**Comment by toots** [comment]
Ok gotcha. I usually observe the logs when doing `opam install --verbose <package>` to monitor if everything is going the right way. I'll check this location as well.

**Pull request merged**
