### PR TITLE
[new release] merlin, merlin-lib and dot-merlin-reader (4.9-414/500)

### PR DESCRIPTION
**Pull request by voodoos**
CHANGES:

merlin 4.9
==========
Fri May 26 15:23:42 CEST 2023

  + merlin binary
    - Allow monadic IO in dot protocol (#1581)
    - Add a `scope` option to the `occurrences` command in preparation for
      the upcoming `project-wide-occurrences` feature (#1596)
    - Construct bool-typed holes as `false` instead of `true` in the
      `construct` command, for consistency (#1599).
    - Add a hook to configure system command for spawning ppxes when Merlin is
      used as a library. (#1585)
    - Implement an all-or-nothing cache for the PPX phase (#1584)
    - Cleanup functors caches when backtracking, to avoid memory leaks
      (#1609, fixes #1529 and ocaml-lsp#1032)
    - Fix `construct` results ordering for sum types sand poly variants (#1603)
    - Fix object method completion not working (#1606, fixes #1575)
    - Improve context detection for package types (#1608, fixes #1607)
    - Fix incorrect locations for string literals (#1574)
    - Fixed an issue that caused `errors` to erroneously alert about missing
      `cmi` files (#1577)
    - Prevent destruct from crashing on closed variant types (#1602,
      fixes #1601)
    - Improve longident parsing (#1612, fixes #945)
  + editor modes
    - emacs: call the user's configured completion UI in
      `merlin-construct` (#1598)
  + test suite
    - Add missing dependency to a test using ppxlib (#1583)
    - Add tests for the new PPX phase cache (#1584)
    - Add and update tests for `construct` ordering (#1603)

### CODE REVIEW

**Comment by anmonteiro** [comment]
Is there a corresponding 5.1 preview for this release?

**Comment by voodoos** [comment]
> Is there a corresponding 5.1 preview for this release?

Not yet.

**Comment by avsm** [comment]
Looks like there's one revdeps failure:

```
[dot-merlin-reader.4.6 (failed: Unbound module Merlin_dot_protocol.Commands)](https://toxis.caelum.ci.dev/github/ocaml/opam-repository/commit/bc1219b7fbc76677a342186a200b9c13eb1c8e08/variant/compilers,4.14,merlin-lib.4.9-414,revdeps,dot-merlin-reader.4.6)
```

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
