### PR TITLE
Package submit.0.9

### PR DESCRIPTION
**Pull request by Niols**
### `submit.0.9`

---
* Homepage: https://github.com/colis-anr/morbig
* Source repo: git://github.com/colis-anr/morbig.git
* Bug tracker: https://github.com/colis-anr/morbig/issues

---
:camel: Pull-request generated by opam-publish v2.0.0~beta

### CODE REVIEW

**Comment by Niols** [comment]
Hello there,

The only test that does not pass is the one on OS X. This is not surprising as we don't pass our continuous integration on OS X either. I'm not so sure about the error we get though:

    [ERROR] The sources of the following couldn't be obtained, aborting:
          - submit.0.9:
            Failure("openssl error")

In any case, we are planning to add OS X's support for the next 1.0 version; we will see then. In the meantime, should I add in the OPAM file that OS X is not supported? And remove that flag for the next release?

**Comment by mseri** [comment]
I think it's good to mark the unavailability of osx support in the opam file. Please add the relevant available stanza in the opam file.

Usually we have the content of `url` in a separate file named `url` and a `descr` file with the description of the package, see e.g. https://github.com/ocaml/opam-repository/pull/12576/files
Can you please also do that change?

**Comment by Niols** [comment]
Alright. Just to confirm, I should add a `available: [ os != "osx" ]` field to my OPAM file?

I know about the separate url and descr files. I generated them, but then I used `opam publish` that merged that in one file. I was a bit surprised but I thought it had just changed. I'll fix that.

Thank you for your help!

**Comment by Niols** [comment]
OK, it's not "osx" but "macos". Also, `opam publish` changed a lot since last time I used it. I found the `--split` option that does what you want. However, here is its description:

    --split
       Split the URL and description of packages into separate files
       (`url` and `descr`). This can be useful on legacy repositories, but
       is deprecated.

Should I really use-it?

**Comment by mseri** [comment]
Yes please, until we switch to opam2, let's stick with the standard structure

**Comment by Niols** [comment]
Thank you for your time and comments! I also realise I used `opam publish submit` which created a package named… "submit". I file a PR that, I hope, is much better, here: #12577.

**Comment by mseri** [comment]
I thought it was the actual name of the package 😆

**Comment by Niols** [comment]
Haha, yup. Sorry again about that :-o

**Pull request closed without merging**
