### PR TITLE
Add dependencies on the "num" package

### PR DESCRIPTION
**Pull request by xavierleroy**
This pull request adds a dependency on the "num" package to a number of packages that appear to use the Num library for arbitrary-precision integer and rational arithmetic that is currently part of the core OCaml installation.  This explicit dependency will be necessary when this library becomes an independent package.

The packages in question were found by grepping for patterns in META files, Makefiles and OCaml source files.  Some uses of the Num library may have been missed; a few others (e.g. in sample code but not in the main source files) were ignored.  Also, no dependency was added for packages that are not available for OCaml 4.04, e.g. many versions of Jane Street's Core libraries.

### CODE REVIEW

**Comment by xavierleroy** [comment]
A lot of CI failures here.  One was my fault (typo in fstar.0.9.1.1/opam) and is fixed by the latest commit.  The following packages failed to build but that's not my fault:
* kaputt-1.1         fatal warning triggered
* coq-8.4.6~camlp4   fatal warning triggered
* ocamlyices-*       yices not installed
* orm-*              Camlp4 type error
* pfff.0.29          fatal warning triggered
* rml.1.09.*         error in configure

**Comment by xavierleroy** [comment]
There is also obigstore that fails to build, and the reason isn't completely clear from the CI log, but note that this package doesn't build at all according to OPAM Builder at OCamlPro.

**Comment by avsm** [comment]
Apologies for the delayed response -- it's a long weekend here in the UK, so I will look at this tomorrow and help triage the failures

**Comment by avsm** [comment]
I've fixed a few of the build failures as separate PRs and linked to this issue

**Comment by avsm** [comment]
@xavierleroy if you could merge with git://github.com/avsm/opam-repository in the xavierleroy-master branch, that will resolve the merge conflicts and hopefully fix the breakages above.  I coudn't figure out how to send you a PR to your fork directly...

**Comment by xavierleroy** [comment]
I just did a merge and push, hope it was the right one...  Let's see what CI says about it.

**Comment by avsm** [comment]
GitHub webhooks are struggling today, so I am temporarily closing this to help prod the CI. I'll reopen it shortly.

**Comment by xavierleroy** [comment]
The suspense is killing me.  Reopening!

**Comment by xavierleroy** [comment]
Doesn't work.  Closing!

**Comment by avsm** [comment]
Trying again! It may pick it up on a rescan. The hooks aren't being delivered by GitHub

**Comment by avsm** [comment]
Only yices failed as we do not have depexts for it -- merging!

**Pull request merged**
