### PR TITLE
Speex updates

### PR DESCRIPTION
**Pull request by toots**
* New speex `0.3.0`
* Bugfix `0.2.2` for brach `0.2.x`
* Split out depext to a conf package

### CODE REVIEW

**Comment by mseri** [comment]
There are a number of conflicts, I think you need to rebase over opam-repository#master

**Comment by toots** [comment]
Done now!

**Comment by kit-ty-kate** [comment]
There seems to be a constraint missing somewhere for `speex.0.2.2`
```
# File "speex.ml", line 1:
# Error: The implementation speex.ml does not match the interface speex.cmi:
#        ...
#        In module Wrapper.Decoder:
#        Values do not match:
#          val open_feed :
#            Ogg.Sync.read ->
#            (Decoder/2.t * Ogg.Stream.stream * Ogg.Sync.t * nativeint * 
#             int * (string * (string * string) list) * Header.t)
#            ref
#        is not included in
#          val open_feed : (int -> string * int) -> t
#        File "speex.mli", line 238, characters 4-44: Expected declaration
#        File "speex.ml", line 390, characters 8-17: Actual declaration
#        File "speex.ml", lines 334-461, characters 2-5:
#          Definition of module Decoder/1
#        File "speex.ml", lines 259-329, characters 0-3:
#          Definition of module Decoder/2
# make[2]: *** [OCamlMakefile:952: speex.cmo] Error 2
# make[2]: Leaving directory '/home/opam/.opam/4.11/.opam-switch/build/speex.0.2.2/src'
# make[1]: *** [OCamlMakefile:717: byte-code-library] Error 2
# make[1]: Leaving directory '/home/opam/.opam/4.11/.opam-switch/build/speex.0.2.2/src'
# make: *** [Makefile:13: all] Error 2
```

**Comment by mseri** [comment]
Now fails only on freebsd, do you plan to add the depext for it or it is considered unsupported?

**Comment by toots** [comment]
> Now fails only on freebsd, do you plan to add the depext for it or it is considered unsupported?

Added!

**Comment by mseri** [comment]
Thanks

**Pull request merged**
