### PR TITLE
+cstruct.1.6.0

### PR DESCRIPTION
**Pull request by avsm**
Recommend not merging this without a reverse dependency check. @samoht, got a moment to try that?

### CODE REVIEW

**Comment by yallop** [comment]
[Odd](https://travis-ci.org/ocaml/opam-repository/jobs/57071996):

```
=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] Bad checksum for
/home/travis/.opam/packages.dev/cppo.1.1.2/cppo-1.1.2.tar.gz:
- f1a551639c0c667ee8840d95ea5b2ab7 [expected result]
- 46779ea3d20070bb8118b2a1f3c88056 [actual result]
This may be fixed by running `opam update`.
```

This looks like a blip, so I'm going to restart the job.

**Comment by samoht** [comment]
Not easy to test the reverse deps for me currently, but if no one else can, I'll do it tonight.

**Comment by avsm** [comment]
I've left a revdep check running via this script and an `opam pin`.  Really need to clean it up to run standalone more easily in its own OPAM root.

```
#!/bin/sh 

export OPAMYES=1
export OPAMJOBS=4
export OPAMVERBOSE=true

revdeps=`opam list --depends-on cstruct --rec -s`

rm -rf logs ok err
mkdir -p logs ok err

for i in $revdeps; do
  echo $i
  opam install $i > logs/$i.txt 2>&1 | tee -a build.txt
  if [ $? != 0 ]; then
    mv logs/$i.txt err/
  else
    mv logs/$i.txt ok/
  fi
done
```

**Comment by avsm** [comment]
Most revdeps seem safe; merging.

**Pull request merged**
