### PR TITLE
Release rpclib and ppx_deriving_rpc 6.0.0 

### PR DESCRIPTION
**Pull request by anton-trunov**
I just hope @jonludlam and @mseri wouldn't mind.

### CODE REVIEW

**Comment by avsm** [comment]
This still uses jbuilder - any reason not to release something with dune instead?

**Comment by anton-trunov** [comment]
@avsm I would also like that. `ocaml-rpc`'s authors already did port it to dune, but there is no official release with that support at the moment.

**Comment by anton-trunov** [comment]
6.0.0 is out for about a year and I'd like this to be released because the project I'm working on needs to move on with its deps

**Comment by mseri** [comment]
I've been wanting to do that for over a year, thanks. The reason it was not published is that we had not benchmarked the new version and the new monadic interface was a beta: there is lots of room for imprivement there but it will require some further breaking changes to be right. Also we needed to port the derivers to ppxlib.

By releasing I  hope we will get more users and feedback for that.

**Comment by mseri** [comment]
You need to release the rpclibs with it, there were a number of breaking changes with it

**Comment by mseri** [comment]
I can draft a release with the dune port later tomorrow if you want. And then we can release the one supprting newer compilers once all the PRs are merged

**Comment by anton-trunov** [comment]
> I can draft a release with the dune port later tomorrow if you want. And then we can release the one supprting newer compilers once all the PRs are merged

That would be extremely helpful! thanks a lot in advance

> You need to release the rpclibs with it, there were a number of breaking changes with them
You are right, thanks, I'm going to add this.

**Comment by mseri** [comment]
> Btw, it worked on my machine with OCaml 4.08.1. Can we please try it with `"ocaml" {>= "4.03.0" & < "4.09.0"}`? (after I add rpclib 6.0.0 -- I forgot that I installed it from my local copy of ocaml-rpc).

Done. Let's wait, maybe it is not needed afetr all

**Comment by anton-trunov** [comment]
> Done. Let's wait, maybe it is not needed afetr all

Indeed, ppx_deriving_rpc 6.0.0 needs rpclib 6.0.0, I could also reproduce it locally.

**Comment by mseri** [comment]
Then it probably also needs the async and lwt ones. We should probably do a full release

**Comment by mseri** [comment]
If it's green, we will need to remove `{build}` from all jbuilders before merge

**Comment by jonludlam** [comment]
:+1:

**Comment by anton-trunov** [comment]
Everything was green, except the build on macOS timed out:

>The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by anton-trunov** [comment]
I also managed to build locally with OCaml 4.09, it turned out that `ppxlib` should have been constrained to at most v0.8.
I'd try adding `< 4.10` constraint on OCaml to see if I could also use 4.09 in the project I'm working on.

**Comment by anton-trunov** [comment]
@mseri macOS build timed out once again (but my local macOS builds succeed).

**Comment by mseri** [comment]
Thanks!

**Comment by anton-trunov** [comment]
Awesome, thank you!

**Pull request merged**
