### PR TITLE
Package eliom.10.1.2

### PR DESCRIPTION
**Pull request by balat**
### `eliom.10.1.2`
Client/server Web and mobile framework
Eliom is a framework for implementing Web sites and client/server Web and mobile applications.
It uses advanced concepts to simplify the implementation of common behaviors (e.g. scoped sessions, continuation based Web programming ...).
It uses advanced static typing features of OCaml to check many properties of the Web application at compile-time (html, page parameters ...).
Eliom allows implementing the whole application as a single program that includes both the client and the server code. For example, you can implement event handlers (onclick ...) directly in OCaml, and you can call a server-side OCaml function from the client. Pages are generated either on the server or the client.
These client-side features remain compatible with traditional Web programming (links, forms, URLs, bookmarks, sessions ...).
It is possible to generate mobile applications for Android and iOS with the exact same code as your Web application.
The client-side code is compiled to JS using Ocsigen Js_of_ocaml or to Wasm using Wasm_of_ocaml.

---
* Homepage: https://ocsigen.org/eliom/
* Source repo: git+https://github.com/ocsigen/eliom.git
* Bug tracker: https://github.com/ocsigen/eliom/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
@balat there is an error on macOS in the test suite, but not for any other platform.

```
[ERROR] The compilation of eliom.10.1.2 failed at "dune build -p eliom -j 11 @install".

#=== ERROR while compiling eliom.10.1.2 =======================================#
# context              2.2.0~alpha2 | macos/x86_64 | ocaml-base-compiler.4.14.1 | pinned(https://github.com/ocsigen/eliom/archive/refs/tags/10.1.2.tar.gz)
# path                 ~/.opam/4.14.1/.opam-switch/build/eliom.10.1.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p eliom -j 11 @install
# exit-code            1
# env-file             ~/.opam/log/eliom-3170-ddf6bc.env
# output-file          ~/.opam/log/eliom-3170-ddf6bc.out
### output ###
# File "_build/default/src/lib/server/type_includes", line 1, characters 3-56:
# 1 | -n (
# 2 | -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml
# 3 | -n )
# Error: too many s-expressions found in input
# (cd _build/default && /Users/mac1000/.opam/4.14.1/bin/ocamlc.opt -w -40 -w -9 -warn-error -3-6 -g -bin-annot -I src/ppx/.ppx_client.objs/byte -I /Users/mac1000/.opam/4.14.1/lib/ocaml-compiler-libs/common -I /Users/mac1000/.opam/4.14.1/lib/ocaml-compiler-libs/shadow -I /Users/mac1000/.opam/4.14.1/lib/ocaml/compiler-libs -I /Users/mac1000/.opam/4.14.1/lib/ppx_derivers -I /Users/mac1000/.opam/4.14.1/lib/ppxlib -I /Users/mac1000/.opam/4.14.1/lib/ppxlib/ast -I /Users/mac1000/.opam/4.14.1/lib/ppxlib/astlib -I /Users/mac1000/.opam/4.14.1/lib/ppxlib/print_diff -I /Users/mac1000/.opam/4.14.1/lib/ppxlib/stdppx -I /Users/mac1000/.opam/4.14.1/lib/ppxlib/traverse_builtins -I /Users/mac1000/.opam/4.14.1/lib/sexplib0 -I /Users/mac1000/.opam/4.14.1/lib/stdlib-shims -I src/ppx/.ppx_utils.objs/byte -intf-suffix .ml -no-alias-deps -o src/ppx/.ppx_client.objs/byte/ppx_eliom_client.cmo -c -impl src/ppx/ppx_eliom_client.pp.ml)
# File "src/ppx/ppx_eliom_client.ml", line 169, characters 6-29:
# 169 |     @ define_client_functions loc client_expr_data
#             ^^^^^^^^^^^^^^^^^^^^^^^
# Warning 6 [labels-omitted]: label loc was omitted in the application of this function.
# (cd _build/default && /Users/mac1000/.opam/4.14.1/bin/ocamlc.opt -w -40 -w -9 -warn-error -6-16-22-27-32-37-39-67-69 -g -bin-annot -I src/lib/client/.eliom_client.objs/byte -I /Users/mac1000/.opam/4.14.1/lib/angstrom -I /Users/mac1000/.opam/4.14.1/lib/base64 -I /Users/mac1000/.opam/4.14.1/lib/bigstringaf -I /Users/mac1000/.opam/4.14.1/lib/bytes -I /Users/mac1000/.opam/4.14.1/lib/cohttp -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-compiler/runtime -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt/logger -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-tyxml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml/deriving -I /Users/mac1000/.opam/4.14.1/lib/lwt -I /Users/mac1000/.opam/4.14.1/lib/lwt_log/core -I /Users/mac1000/.opam/4.14.1/lib/lwt_react -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/baselib/base -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/cookies -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/polytables -I /Users/mac1000/.opam/4.14.1/lib/ppx_sexp_conv/runtime-lib -I /Users/mac1000/.opam/4.14.1/lib/re -I /Users/mac1000/.opam/4.14.1/lib/react -I /Users/mac1000/.opam/4.14.1/lib/reactiveData -I /Users/mac1000/.opam/4.14.1/lib/seq -I /Users/mac1000/.opam/4.14.1/lib/sexplib0 -I /Users/mac1000/.opam/4.14.1/lib/stringext -I /Users/mac1000/.opam/4.14.1/lib/tyxml -I /Users/mac1000/.opam/4.14.1/lib/tyxml/functor -I /Users/mac1000/.opam/4.14.1/lib/uri -I /Users/mac1000/.opam/4.14.1/lib/uri-sexp -I /Users/mac1000/.opam/4.14.1/lib/uutf -no-alias-deps -o src/lib/client/.eliom_client.objs/byte/eliommod_cookies.cmo -c -impl src/lib/client/eliommod_cookies.pp.ml)
# File "src/lib/client/eliommod_cookies.ml", line 107, characters 19-49:
# 107 |                   (Ocsigen_cookie_map.Poly.remove cpath name
#                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Warning 6 [labels-omitted]: label path was omitted in the application of this function.
# (cd _build/default && /Users/mac1000/.opam/4.14.1/bin/ocamlopt.opt -w -40 -w -9 -warn-error -3-6 -g -I src/ppx/.ppx_client.objs/byte -I src/ppx/.ppx_client.objs/native -I /Users/mac1000/.opam/4.14.1/lib/ocaml-compiler-libs/common -I /Users/mac1000/.opam/4.14.1/lib/ocaml-compiler-libs/shadow -I /Users/mac1000/.opam/4.14.1/lib/ocaml/compiler-libs -I /Users/mac1000/.opam/4.14.1/lib/ppx_derivers -I /Users/mac1000/.opam/4.14.1/lib/ppxlib -I /Users/mac1000/.opam/4.14.1/lib/ppxlib/ast -I /Users/mac1000/.opam/4.14.1/lib/ppxlib/astlib -I /Users/mac1000/.opam/4.14.1/lib/ppxlib/print_diff -I /Users/mac1000/.opam/4.14.1/lib/ppxlib/stdppx -I /Users/mac1000/.opam/4.14.1/lib/ppxlib/traverse_builtins -I /Users/mac1000/.opam/4.14.1/lib/sexplib0 -I /Users/mac1000/.opam/4.14.1/lib/stdlib-shims -I src/ppx/.ppx_utils.objs/byte -I src/ppx/.ppx_utils.objs/native -intf-suffix .ml -no-alias-deps -o src/ppx/.ppx_client.objs/native/ppx_eliom_client.cmx -c -impl src/ppx/ppx_eliom_client.pp.ml)
# File "src/ppx/ppx_eliom_client.ml", line 169, characters 6-29:
# 169 |     @ define_client_functions loc client_expr_data
#             ^^^^^^^^^^^^^^^^^^^^^^^
# Warning 6 [labels-omitted]: label loc was omitted in the application of this function.
# (cd _build/default && /Users/mac1000/.opam/4.14.1/bin/ocamlc.opt -w -40 -w -9 -warn-error -6-16-22-27-32-37-39-67-69 -g -bin-annot -I src/lib/client/.eliom_client.objs/byte -I /Users/mac1000/.opam/4.14.1/lib/angstrom -I /Users/mac1000/.opam/4.14.1/lib/base64 -I /Users/mac1000/.opam/4.14.1/lib/bigstringaf -I /Users/mac1000/.opam/4.14.1/lib/bytes -I /Users/mac1000/.opam/4.14.1/lib/cohttp -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-compiler/runtime -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt/logger -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-tyxml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml/deriving -I /Users/mac1000/.opam/4.14.1/lib/lwt -I /Users/mac1000/.opam/4.14.1/lib/lwt_log/core -I /Users/mac1000/.opam/4.14.1/lib/lwt_react -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/baselib/base -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/cookies -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/polytables -I /Users/mac1000/.opam/4.14.1/lib/ppx_sexp_conv/runtime-lib -I /Users/mac1000/.opam/4.14.1/lib/re -I /Users/mac1000/.opam/4.14.1/lib/react -I /Users/mac1000/.opam/4.14.1/lib/reactiveData -I /Users/mac1000/.opam/4.14.1/lib/seq -I /Users/mac1000/.opam/4.14.1/lib/sexplib0 -I /Users/mac1000/.opam/4.14.1/lib/stringext -I /Users/mac1000/.opam/4.14.1/lib/tyxml -I /Users/mac1000/.opam/4.14.1/lib/tyxml/functor -I /Users/mac1000/.opam/4.14.1/lib/uri -I /Users/mac1000/.opam/4.14.1/lib/uri-sexp -I /Users/mac1000/.opam/4.14.1/lib/uutf -intf-suffix .ml -no-alias-deps -o src/lib/client/.eliom_client.objs/byte/eliom_runtime.cmo -c -impl src/lib/client/eliom_runtime.pp.ml)
# File "src/lib/eliom_runtime.shared.ml", line 32, characters 14-17:
# Warning 16 [unerasable-optional-argument]: this optional argument cannot be erased.
# (cd _build/default && /Users/mac1000/.opam/4.14.1/bin/ocamlopt.opt -w -40 -w -9 -warn-error -6-16-22-27-32-37-39-67-69 -g -I src/lib/client/.eliom_client.objs/byte -I src/lib/client/.eliom_client.objs/native -I /Users/mac1000/.opam/4.14.1/lib/angstrom -I /Users/mac1000/.opam/4.14.1/lib/base64 -I /Users/mac1000/.opam/4.14.1/lib/bigstringaf -I /Users/mac1000/.opam/4.14.1/lib/bytes -I /Users/mac1000/.opam/4.14.1/lib/cohttp -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-compiler/runtime -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt/logger -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-tyxml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml/deriving -I /Users/mac1000/.opam/4.14.1/lib/lwt -I /Users/mac1000/.opam/4.14.1/lib/lwt_log/core -I /Users/mac1000/.opam/4.14.1/lib/lwt_react -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/baselib/base -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/cookies -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/polytables -I /Users/mac1000/.opam/4.14.1/lib/ppx_sexp_conv/runtime-lib -I /Users/mac1000/.opam/4.14.1/lib/re -I /Users/mac1000/.opam/4.14.1/lib/react -I /Users/mac1000/.opam/4.14.1/lib/reactiveData -I /Users/mac1000/.opam/4.14.1/lib/seq -I /Users/mac1000/.opam/4.14.1/lib/sexplib0 -I /Users/mac1000/.opam/4.14.1/lib/stringext -I /Users/mac1000/.opam/4.14.1/lib/tyxml -I /Users/mac1000/.opam/4.14.1/lib/tyxml/functor -I /Users/mac1000/.opam/4.14.1/lib/uri -I /Users/mac1000/.opam/4.14.1/lib/uri-sexp -I /Users/mac1000/.opam/4.14.1/lib/uutf -intf-suffix .ml -no-alias-deps -o src/lib/client/.eliom_client.objs/native/eliommod_cookies.cmx -c -impl src/lib/client/eliommod_cookies.pp.ml)
# File "src/lib/client/eliommod_cookies.ml", line 107, characters 19-49:
# 107 |                   (Ocsigen_cookie_map.Poly.remove cpath name
#                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Warning 6 [labels-omitted]: label path was omitted in the application of this function.
# (cd _build/default && /Users/mac1000/.opam/4.14.1/bin/ocamlopt.opt -w -40 -w -9 -warn-error -6-16-22-27-32-37-39-67-69 -g -I src/lib/client/.eliom_client.objs/byte -I src/lib/client/.eliom_client.objs/native -I /Users/mac1000/.opam/4.14.1/lib/angstrom -I /Users/mac1000/.opam/4.14.1/lib/base64 -I /Users/mac1000/.opam/4.14.1/lib/bigstringaf -I /Users/mac1000/.opam/4.14.1/lib/bytes -I /Users/mac1000/.opam/4.14.1/lib/cohttp -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-compiler/runtime -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt/logger -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-tyxml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml/deriving -I /Users/mac1000/.opam/4.14.1/lib/lwt -I /Users/mac1000/.opam/4.14.1/lib/lwt_log/core -I /Users/mac1000/.opam/4.14.1/lib/lwt_react -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/baselib/base -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/cookies -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/polytables -I /Users/mac1000/.opam/4.14.1/lib/ppx_sexp_conv/runtime-lib -I /Users/mac1000/.opam/4.14.1/lib/re -I /Users/mac1000/.opam/4.14.1/lib/react -I /Users/mac1000/.opam/4.14.1/lib/reactiveData -I /Users/mac1000/.opam/4.14.1/lib/seq -I /Users/mac1000/.opam/4.14.1/lib/sexplib0 -I /Users/mac1000/.opam/4.14.1/lib/stringext -I /Users/mac1000/.opam/4.14.1/lib/tyxml -I /Users/mac1000/.opam/4.14.1/lib/tyxml/functor -I /Users/mac1000/.opam/4.14.1/lib/uri -I /Users/mac1000/.opam/4.14.1/lib/uri-sexp -I /Users/mac1000/.opam/4.14.1/lib/uutf -intf-suffix .ml -no-alias-deps -o src/lib/client/.eliom_client.objs/native/eliom_runtime.cmx -c -impl src/lib/client/eliom_runtime.pp.ml)
# File "src/lib/eliom_runtime.shared.ml", line 32, characters 14-17:
# Warning 16 [unerasable-optional-argument]: this optional argument cannot be erased.
# (cd _build/default && /Users/mac1000/.opam/4.14.1/bin/ocamlc.opt -w -40 -w -9 -warn-error -6-16-22-27-32-37-39-67-69 -g -bin-annot -I src/lib/client/.eliom_client.objs/byte -I /Users/mac1000/.opam/4.14.1/lib/angstrom -I /Users/mac1000/.opam/4.14.1/lib/base64 -I /Users/mac1000/.opam/4.14.1/lib/bigstringaf -I /Users/mac1000/.opam/4.14.1/lib/bytes -I /Users/mac1000/.opam/4.14.1/lib/cohttp -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-compiler/runtime -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt/logger -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-tyxml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml/deriving -I /Users/mac1000/.opam/4.14.1/lib/lwt -I /Users/mac1000/.opam/4.14.1/lib/lwt_log/core -I /Users/mac1000/.opam/4.14.1/lib/lwt_react -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/baselib/base -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/cookies -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/polytables -I /Users/mac1000/.opam/4.14.1/lib/ppx_sexp_conv/runtime-lib -I /Users/mac1000/.opam/4.14.1/lib/re -I /Users/mac1000/.opam/4.14.1/lib/react -I /Users/mac1000/.opam/4.14.1/lib/reactiveData -I /Users/mac1000/.opam/4.14.1/lib/seq -I /Users/mac1000/.opam/4.14.1/lib/sexplib0 -I /Users/mac1000/.opam/4.14.1/lib/stringext -I /Users/mac1000/.opam/4.14.1/lib/tyxml -I /Users/mac1000/.opam/4.14.1/lib/tyxml/functor -I /Users/mac1000/.opam/4.14.1/lib/uri -I /Users/mac1000/.opam/4.14.1/lib/uri-sexp -I /Users/mac1000/.opam/4.14.1/lib/uutf -intf-suffix .ml -no-alias-deps -o src/lib/client/.eliom_client.objs/byte/eliom_uri.cmo -c -impl src/lib/client/eliom_uri.pp.ml)
# File "src/lib/eliom_uri.shared.ml", line 99, characters 2-33:
# Warning 6 [labels-omitted]: labels https, host, port were omitted in the application of this function.
# File "src/lib/eliom_uri.shared.ml", line 319, characters 4-31:
# Warning 6 [labels-omitted]: label sep was omitted in the application of this function.
# (cd _build/default && /Users/mac1000/.opam/4.14.1/bin/ocamlc.opt -w -40 -w -9 -warn-error -6-16-22-27-32-37-39-67-69 -g -bin-annot -I src/lib/client/.eliom_client.objs/byte -I /Users/mac1000/.opam/4.14.1/lib/angstrom -I /Users/mac1000/.opam/4.14.1/lib/base64 -I /Users/mac1000/.opam/4.14.1/lib/bigstringaf -I /Users/mac1000/.opam/4.14.1/lib/bytes -I /Users/mac1000/.opam/4.14.1/lib/cohttp -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-compiler/runtime -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-lwt/logger -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml-tyxml -I /Users/mac1000/.opam/4.14.1/lib/js_of_ocaml/deriving -I /Users/mac1000/.opam/4.14.1/lib/lwt -I /Users/mac1000/.opam/4.14.1/lib/lwt_log/core -I /Users/mac1000/.opam/4.14.1/lib/lwt_react -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/baselib/base -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/cookies -I /Users/mac1000/.opam/4.14.1/lib/ocsigenserver/polytables -I /Users/mac1000/.opam/4.14.1/lib/ppx_sexp_conv/runtime-lib -I /Users/mac1000/.opam/4.14.1/lib/re -I /Users/mac1000/.opam/4.14.1/lib/react -I /Users/mac1000/.opam/4.14.1/lib/reactiveData -I /Users/mac1000/.opam/4.14.1/lib/seq -I /Users/mac1000/.opam/4.14.1/lib/sexplib0 -I /Users/mac1000/.opam/4.14.1/lib/stringext -I /Users/mac1000/.opam/4.14.1/lib/tyxml -I /Users/mac1000/.opam/4.14.1/lib/tyxml/functor -I /Users/mac1000/.opam/4.14.1/lib/uri -I /Users/mac1000/.opam/4.14.1/lib/uri-sexp -I /Users/mac1000/.opam/4.14.1/lib/uutf -intf-suffix .ml -no-alias-deps -o src/lib/client/.eliom_client.objs/byte/eliom_comet.cmo -c -impl src/lib/client/eliom_comet.pp.ml)
# File "src/lib/eliom_comet.client.ml", line 378, characters 10-35:
# Warning 6 [labels-omitted]: label service was omitted in the application of this function.
# File "src/lib/eliom_comet.client.ml", line 383, characters 8-33:
# Warning 6 [labels-omitted]: label service was omitted in the application of this function.



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build eliom 10.1.2
+- 
```

**Comment by tmcgilchrist** [comment]
I also noticed that test is failing in the GitHub Actions run here https://github.com/ocsigen/eliom/actions/runs/6447682391/job/17504192227

**Comment by balat** [comment]
Thanks @tmcgilchrist I think it is fixed now. Let's wait for the opam-ci to check

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Comment by balat** [comment]
Yes we will announce it. Thanks!

**Pull request merged**
