### PR TITLE
adjust constraints of earlier tls releases

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by avsm** [comment]
Also, nocrypto probably needs a ctypes <0.4.0 as well.

**Comment by hannesm** [comment]
it seems to me that opam-1.1 is still unhappy somehow (the built using ocaml 4.00 cannot find tls-0.1.0 (which requires ocaml 4.01 anyways))...

**Comment by hannesm** [comment]
(and opam-1.1 is generally not nicely working here... opam list tls-0.1.0 failed... all over.. maybe the travis script is slightly broken there?)

**Comment by AltGr** [comment]
the "!=" operator in version constraints is not allowed in OPAM 1.1.
Please change `opam-version:` to `1.2` so that it can be rewritten properly

**Comment by hannesm** [comment]
I changed `!=` to `< & >`, but this was only in the 0.3.0 opam, which already has `opam-version: "1.2"`...

**Comment by avsm** [comment]
Can you rebase/merge with #3698?

**Comment by hannesm** [comment]
rebased

**Comment by hannesm** [comment]
and it's green... :dancers:

**Pull request merged**
