### PR TITLE
+ devkit 0.7

### PR DESCRIPTION
**Pull request by cyberhuman**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Fails on 4.04 with:
```
- File "httpev.ml", line 566, characters 11-17:
- Error: This function has type
-          Unix.socket_domain -> Unix.socket_type -> int -> Unix.file_descr
-        It is applied to too many arguments; maybe you forgot a `;'.
- Command exited with code 2.
- Makefile:36: recipe for target 'lib' failed
- make: *** [lib] Error 10
```

**Comment by cyberhuman** [comment]
@ygrek do you know what extunix failures are about?

**Comment by ygrek** [comment]
I suspect it picks up system camlp4, witness : 
```
+OCAML_VERSION=4.07
+SYS_OCAML_VERSION=4.02
[...]
Get:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu trusty-updates/main amd64 camlp4 amd64 4.01.0-3ubuntu3.1 [10.1 MB]
Get:6 http://us-east-1.ec2.archive.ubuntu.com/ubuntu trusty-updates/universe amd64 camlp4-extra amd64 4.01.0-3ubuntu3.1 [9,987 kB]
```

**Comment by ygrek** [comment]
ie I claim it is CI host misconfiguration issue

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
