### PR TITLE
[new release] Docfd 3.0.0

### PR DESCRIPTION
**Pull request by darrenldl**
TUI multiline fuzzy document finder

https://github.com/darrenldl/docfd

Think interactive grep for text files, PDFs, DOCXs, etc,
but word/token based instead of regex and line based,
so you can search across lines easily.

Docfd aims to provide good UX via integration with common text editors
and PDF viewers,
so you can jump directly to a search result with a single key press.

Features:

- Multithreaded indexing and searching

- Multiline fuzzy search of multiple files or a single file

- Swap between multi-file view and single file view on the fly

- Content view pane that shows the snippet surrounding the search result selected

- Text editor and PDF viewer integration

### CODE REVIEW

**Comment by darrenldl** [comment]
Following the dune's guide on cram tests is not bullet proof I guess. I'm removing the runtest line from the opam file.

**Comment by mseri** [comment]
cram tests don't always play nice with the sandbox

**Comment by mseri** [comment]
Thanks

**Comment by darrenldl** [comment]
Yeah I couldn't get it to find `docfd` command without doing `dune build @all` etc first on my end either. It's weird that the cram test dep clause also doesn't seem to trigger a rebuild of the exe? Anyhow.

**Pull request merged**
