### PR TITLE
Add obytelib and fix compatibility with ocaml 4.03 for ocapic, ocamlclean and ocamlpp.

### PR DESCRIPTION
**Pull request by bvaugon**
- OByteLib is a generic library to mangage different formats of the OCaml bytecode. For testing purpose (and for the fun), it also contains an OCaml VM written in OCaml.
- The other changes are for the new versions of ocapic (OCaml on PIC microcontrollers), ocamlclean (an OCaml bytecode cleaner) and ocamlpp (a pretty-printer for .byte and .cmo files) which are compatible with ocaml-4.03.

### CODE REVIEW

**Comment by yallop** [comment]
The build is [failing on 4.01.0](https://travis-ci.org/ocaml/opam-repository/jobs/165090652):

```
# Options are:
# [...]
#   -dparsetree  (undocumented)
#   -dtypedtree  (undocumented)
#   -drawlambda  (undocumented)
#   -dlambda  (undocumented)
#   -dinstr  (undocumented)
#   - <file>  Treat <file> as a file name (even if it starts with `-')
#   -help  Display this list of options
#   --help  Display this list of options
# Command exited with code 2.
```

**Comment by avsm** [comment]
Great to see ocamlclean updated for 4.03, am keen to try it for MirageOS!  Any plans for a native code version?

**Comment by yallop** [comment]
There's a char signedness issue [showing up on OS X](https://travis-ci.org/ocaml/opam-repository/jobs/165166174):

```
# ceeprom.c:73:35: warning: comparison of constant -1 with expression of type 'unsigned char' is always false [-Wtautological-constant-out-of-range-compare]
#       if((h = fgetc(eeprom_file)) == EOF || (l = fgetc(eeprom_file)) == EOF){
```

**Comment by bvaugon** [comment]
Travis now failed on mac osx since the graphics library is not installed in the given VM.
--- log ---
The following actions were aborted
  ∗  install ocapic 3.3
The following actions failed
  ∗  install graphics 1.0
--- log ---
I hope it does not block the merge...

@avsm: indeed, porting dead code cleaner techniques from ocamlclean on native code would be interesting, but to do that generically, it might be done inside the compiler, maybe on FLambda...

**Comment by avsm** [comment]
thanks!

**Pull request merged**
