### PR TITLE
Jsoo 3.4.0

### PR DESCRIPTION
**Pull request by hhugo**
- adds support for OCaml 4.08

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
```
[ERROR] undefined filter variable in dependencies of js_of_ocaml-compiler.3.4.0: test
```

**Comment by kit-ty-kate** [comment]
Fixed. Could you return the fix upstream?

**Comment by hhugo** [comment]
@kit-ty-kate, thanks, the opam file is already fixed upstream.

**Comment by hhugo** [comment]
The remaining error seems to be unrelated.

**Comment by kit-ty-kate** [comment]
thanks!

**Pull request merged**
