### PR TITLE
Add dns{,-lwt,-lwt-unix,-async}.1.0.1 mirage-dns.3.0.1

### PR DESCRIPTION
**Pull request by djs55**

### CODE REVIEW

**Comment by djs55** [comment]
The travis failures are build failures of `bin_prot` (a dependency)

**Comment by avsm** [comment]
I've opened a PR that constraints older bin_prot

**Comment by djs55** [comment]
```
#=== ERROR while installing core.v0.9.0 =======================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p core -j 4
# path         /home/travis/.opam/4.05.0/build/core.v0.9.0
# compiler     4.05.0
# exit-code    1
# env-file     /home/travis/.opam/4.05.0/build/core.v0.9.0/core-20735-1ad015.env
# stdout-file  /home/travis/.opam/4.05.0/build/core.v0.9.0/core-20735-1ad015.out
# stderr-file  /home/travis/.opam/4.05.0/build/core.v0.9.0/core-20735-1ad015.err
### stderr ###
# [...]
#     ocamlopt src/core__Weak_hashtbl.{cmx,o}
#     ocamlopt src/core__Unix_error.{cmx,o}
#       ocamlc src/core__Syscall_result.{cmo,cmt}
#     ocamlopt src/core__Syscall_result_intf.{cmx,o}
#       ocamlc src/core__Core_unix.{cmi,cmti} (exit 2)
# (cd _build/default && /home/travis/.opam/4.05.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/travis/.opam/4.05.0/lib/base -I /home/travis/.opam/4.05.0/lib/base/caml -I /home/travis/.opam/4.05.0/lib/base/shadow_stdlib -I /home/travis/.opam/4.05.0/lib/bin_prot -I /home/travis/.opam/4.05.0/lib/bin_prot/shape -I /home/travis/.opam/4.05.0/lib/core_kernel -I /home/travis/.opam/4.05.0/lib/core_kernel/base_for_tests -I /home/travis/.opam/4.05.0/lib/fieldslib -I /home/travis/.opam/4.05.0/lib/jane-street-headers -I /home/travis/.opam/4.05.0/lib/num -I /home/travis/.opam/4.05.0/lib/ocaml -I /home/travis/.opam/4.05.0/lib/ocaml/threads -I /home/travis/.opam/4.05.0/lib/ppx_assert/runtime-lib -I /home/travis/.opam/4.05.0/lib/ppx_bench/runtime-lib -I /home/travis/.opam/4.05.0/lib/ppx_compare/runtime-lib -I /home/travis/.opam/4.05.0/lib/ppx_expect/collector -I /home/travis/.opam/4.05.0/lib/ppx_expect/common -I /home/travis/.opam/4.05.0/lib/ppx_expect/config -I /home/travis/.opam/4.05.0/lib/ppx_hash/runtime-lib -I /home/travis/.opam/4.05.0/lib/ppx_inline_test/config -I /home/travis/.opam/4.05.0/lib/ppx_inline_test/runtime-lib -I /home/travis/.opam/4.05.0/lib/sexplib -I /home/travis/.opam/4.05.0/lib/sexplib/0 -I /home/travis/.opam/4.05.0/lib/sexplib/unix -I /home/travis/.opam/4.05.0/lib/spawn -I /home/travis/.opam/4.05.0/lib/stdio -I /home/travis/.opam/4.05.0/lib/typerep -I /home/travis/.opam/4.05.0/lib/variantslib -no-alias-deps -I src -open Core__ -o src/core__Core_unix.cmi -c -intf src/core_unix.pp.mli)
# File "src/core_unix.mli", line 398, characters 0-858:
# Error: This variant or record definition does not match that of type
#          Unix.open_flag
#        The field O_KEEPEXEC is only present in the original definition.
```

**Comment by djs55** [comment]
thanks!

**Pull request merged**
