### PR TITLE
Relinquish Caravan maintainership

### PR DESCRIPTION
**Pull request by xandkar**
I'm unlikely to ever work on this again. Hopefully the thematic name can be put to better use.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Should it be marked as deprecated?

**Comment by xandkar** [comment]
> Should it be marked as deprecated?

Yes.

**Comment by xandkar** [comment]
No worries. Thank you.

**Comment by avsm** [comment]
Thanks for the contributions to date, @xandkar, and hope to see you back in the future :-)

**Comment by xandkar** [comment]
> Thanks for the contributions to date, @xandkar, and hope to see you back in the future :-)

The pleasure was entirely mine, @avsm - I'll be around :)

**Pull request merged**
