### PR TITLE
Tyxml 4.0.0

### PR DESCRIPTION
**Pull request by Drup**
Lot's of changes, breaking compat. The changelog is [here](https://github.com/ocsigen/tyxml/releases/tag/4.0.0).

The virtual package thing was advised by @rgrinberg and copied from mirage-conduit.

All @darioteixeira's packages already have a constraint, it seems. cc @fxfactorial @smondet

### CODE REVIEW

**Comment by Drup** [comment]
It looks like the constraints for ketrew are wrong. @smondet ?

**Comment by smondet** [comment]
@Drup it seems that the `MakeWrapped` module disapeared in 3.5.0 and we didn't catch it (all users of Ketrew I know run on `master` ☺).
the constraint should be “≤ 3.5.0” (?)

**Comment by Drup** [comment]
So, Some builds timeout because of https://github.com/ocaml/opam-repository/issues/6582 and some build had a network failure ...

**Comment by vasilisp** [comment]
This conflicts with all released versions of Eliom, and the conflict is implicit (via Ocsigen Server and Js_of_ocaml). I would slightly prefer to have an explicit conflict. This is more future-proof (we will probably release the Eliom reverse-dependencies first), and also prevents "cheating" the solver by pinning JSOO + Ocsigen Server.

**Comment by Drup** [comment]
@vasilisp I think it's better to add it in a following PR. If I ask CI to check even more packages, it's going to explode.

**Comment by samoht** [comment]
I've pushed a quick fix for #6582 and I've restarted the failing builds for that PR.

**Comment by Drup** [comment]
thanks @samoht !

@fxfactorial podge uninstall is buggy. Do I need to fix this ?

**Comment by Drup** [comment]
There is still one timeout and two unrelated failures (not sure where the cppo one comes from, it was working fine before, the other one is just depext for sqlite not present for OSX). 

Most of it works now, can we merge ? :/

**Comment by samoht** [comment]
Can you add some brackets around `ocaml-version >= 4.02`. Seems that it breaks 1.2.0:

```
[ERROR] available is not a valid variable.
[WARNING] Invalid variable available in filter
```

**Comment by Drup** [comment]
@samoht Done (but github doesn't show it)

**Comment by Drup** [comment]
@samoht only 2 time out now....

**Comment by samoht** [comment]
There's is still that weird error message:

```
[ERROR] available is not a valid variable.
[WARNING] Invalid variable available in filter
```

I have no idea where it comes from :-/

**Comment by Drup** [comment]
@samoht Isn't that an opam-depext error message ?

**Comment by Drup** [comment]
Thanks @samoht !

**Comment by samoht** [comment]
I don't think so, it seems to be somewhat related to js_of_ocaml 2.6 but I don't see why. Merging anyway...

**Comment by dbuenzli** [comment]
> [ERROR] available is not a valid variable.
> [WARNING] Invalid variable available in filter

FWIW I also saw this in my PR yesterday evening.

**Comment by samoht** [comment]
ok after a quick bisect, I think the error lies in https://github.com/ocaml/opam-repository/pull/6518/files#r64274467

**Pull request merged**
