### PR TITLE
[new release] yaml (1.0.0)

### PR DESCRIPTION
**Pull request by avsm**
Parse and generate YAML 1.1 files

- Project page: <a href="https://github.com/avsm/ocaml-yaml">https://github.com/avsm/ocaml-yaml</a>
- Documentation: <a href="https://avsm.github.io/ocaml-yaml/">https://avsm.github.io/ocaml-yaml/</a>

##### CHANGES:

* Support parsing of canonical Yaml null, float and bool
  values (@avsm, fixes avsm/ocaml-yaml#15 avsm/ocaml-yaml#16).
* Port from jbuilder to dune (avsm/ocaml-yaml#2 @rgrinberg)
* Use dune.configurator for config probing (avsm/ocaml-yaml#18 @emillon)
* Upgrade opam metadata to 2.0 format (@avsm)
* Suppress some C warnings on build due to ctypes autogen
  until ctypes gains support for unsigned char types (@avsm)
* Add Windows build support (@avsm avsm/ocaml-yaml#11)
* Refresh libyaml to upstream changeset 85d1f168ef39f4 (@avsm)
* Switch CI to Azure Pipelines and test Windows, Linux and
  macOS (@avsm)
* Add Junit output to the Alcotest (@avsm)

### CODE REVIEW

**Comment by mseri** [comment]
Thanks

**Comment by mseri** [comment]
Please announce this on the discourse forum if you have not already done it :)

**Comment by kit-ty-kate** [comment]
@avsm did you check all the reverse dependencies? I'm wondering whether those actually work correctly due to the change in behaviour of the yaml parser (e.g. `23` is not parsed as `String "23"` anymore but as `Float 23.`)

**Comment by kit-ty-kate** [comment]
if there weren't I think it might be more cautious to restrict all the reverse dependencies

**Comment by avsm** [comment]
i only did build testing -- if you could add the revdep constraints where appropriate i'd appreciate it (been travelling)

**Comment by kit-ty-kate** [comment]
I had a look at the code for both and they don't use the yaml parser (the one bit that changed behaviour after 1.0.0). I think it's fine to let them as is for now.

**Comment by avsm** [comment]
great, thanks!

**Pull request merged**
