### PR TITLE
Package taglib.0.3.10

### PR DESCRIPTION
**Pull request by toots**
### `taglib.0.3.10`
Bindings for the taglib library
Bindings for the taglib library which provides functions for reading tags in headers of audio files

---
* Homepage: https://github.com/savonet/ocaml-taglib
* Source repo: git+https://github.com/savonet/ocaml-taglib.git
* Bug tracker: https://github.com/savonet/ocaml-taglib/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mseri** [comment]
Fails to build on ocaml 5:
```
#=== ERROR while compiling taglib.0.3.10 ======================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-variants.5.0.0+trunk | pinned(https://github.com/savonet/ocaml-taglib/archive/v0.3.10.tar.gz)
# path                 ~/.opam/5.0/.opam-switch/build/taglib.0.3.10
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p taglib -j 31 @install
# exit-code            1
# env-file             ~/.opam/log/taglib-7-061de9.env
# output-file          ~/.opam/log/taglib-7-061de9.out
### output ###
# File "src/dune", line 8, characters 9-21:
# 8 |   (names taglib_stubs)
#              ^^^^^^^^^^^^
# (cd _build/default/src && /usr/bin/gcc -fPIC -I/usr/include/taglib -g -I /home/opam/.opam/5.0/lib/ocaml -I /home/opam/.opam/5.0/lib/ocaml/unix -o taglib_stubs.o -c taglib_stubs.cc)
# In file included from /home/opam/.opam/5.0/lib/ocaml/caml/alloc.h:20,
#                  from taglib_stubs.cc:98:
# /home/opam/.opam/5.0/lib/ocaml/caml/misc.h:206:18: error: variable or field 'call_timing_hook' declared void
#   206 | Caml_inline void call_timing_hook(_Atomic caml_timing_hook * a)
#       |                  ^~~~~~~~~~~~~~~~
# /home/opam/.opam/5.0/lib/ocaml/caml/misc.h:206:35: error: '_Atomic' was not declared in this scope; did you mean 'Atom'?
#   206 | Caml_inline void call_timing_hook(_Atomic caml_timing_hook * a)
#       |                                   ^~~~~~~
#       |                                   Atom
# In file included from /home/opam/.opam/5.0/lib/ocaml/caml/domain.h:30,
#                  from /home/opam/.opam/5.0/lib/ocaml/caml/memory.h:27,
#                  from /home/opam/.opam/5.0/lib/ocaml/caml/callback.h:22,
#                  from taglib_stubs.cc:99:
# /home/opam/.opam/5.0/lib/ocaml/caml/platform.h: In function 'void caml_plat_lock(caml_plat_mutex*)':
# /home/opam/.opam/5.0/lib/ocaml/caml/platform.h:156:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
#   156 |   check_err("lock", pthread_mutex_lock(m));
#       |             ^~~~~~
# /home/opam/.opam/5.0/lib/ocaml/caml/platform.h: In function 'int caml_plat_try_lock(caml_plat_mutex*)':
# /home/opam/.opam/5.0/lib/ocaml/caml/platform.h:166:15: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
#   166 |     check_err("try_lock", r);
#       |               ^~~~~~~~~~
# /home/opam/.opam/5.0/lib/ocaml/caml/platform.h: In function 'void caml_plat_unlock(caml_plat_mutex*)':
# /home/opam/.opam/5.0/lib/ocaml/caml/platform.h:175:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
#   175 |   check_err("unlock", pthread_mutex_unlock(m));
#       |             ^~~~~~~~

```

**Comment by toots** [comment]
> Fails to build on ocaml 5:
> 
> ```
> #=== ERROR while compiling taglib.0.3.10 ======================================#
> # context              2.2.0~alpha~dev | linux/x86_64 | ocaml-variants.5.0.0+trunk | pinned(https://github.com/savonet/ocaml-taglib/archive/v0.3.10.tar.gz)
> # path                 ~/.opam/5.0/.opam-switch/build/taglib.0.3.10
> # command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p taglib -j 31 @install
> # exit-code            1
> # env-file             ~/.opam/log/taglib-7-061de9.env
> # output-file          ~/.opam/log/taglib-7-061de9.out
> ### output ###
> # File "src/dune", line 8, characters 9-21:
> # 8 |   (names taglib_stubs)
> #              ^^^^^^^^^^^^
> # (cd _build/default/src && /usr/bin/gcc -fPIC -I/usr/include/taglib -g -I /home/opam/.opam/5.0/lib/ocaml -I /home/opam/.opam/5.0/lib/ocaml/unix -o taglib_stubs.o -c taglib_stubs.cc)
> # In file included from /home/opam/.opam/5.0/lib/ocaml/caml/alloc.h:20,
> #                  from taglib_stubs.cc:98:
> # /home/opam/.opam/5.0/lib/ocaml/caml/misc.h:206:18: error: variable or field 'call_timing_hook' declared void
> #   206 | Caml_inline void call_timing_hook(_Atomic caml_timing_hook * a)
> #       |                  ^~~~~~~~~~~~~~~~
> # /home/opam/.opam/5.0/lib/ocaml/caml/misc.h:206:35: error: '_Atomic' was not declared in this scope; did you mean 'Atom'?
> #   206 | Caml_inline void call_timing_hook(_Atomic caml_timing_hook * a)
> #       |                                   ^~~~~~~
> #       |                                   Atom
> # In file included from /home/opam/.opam/5.0/lib/ocaml/caml/domain.h:30,
> #                  from /home/opam/.opam/5.0/lib/ocaml/caml/memory.h:27,
> #                  from /home/opam/.opam/5.0/lib/ocaml/caml/callback.h:22,
> #                  from taglib_stubs.cc:99:
> # /home/opam/.opam/5.0/lib/ocaml/caml/platform.h: In function 'void caml_plat_lock(caml_plat_mutex*)':
> # /home/opam/.opam/5.0/lib/ocaml/caml/platform.h:156:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
> #   156 |   check_err("lock", pthread_mutex_lock(m));
> #       |             ^~~~~~
> # /home/opam/.opam/5.0/lib/ocaml/caml/platform.h: In function 'int caml_plat_try_lock(caml_plat_mutex*)':
> # /home/opam/.opam/5.0/lib/ocaml/caml/platform.h:166:15: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
> #   166 |     check_err("try_lock", r);
> #       |               ^~~~~~~~~~
> # /home/opam/.opam/5.0/lib/ocaml/caml/platform.h: In function 'void caml_plat_unlock(caml_plat_mutex*)':
> # /home/opam/.opam/5.0/lib/ocaml/caml/platform.h:175:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
> #   175 |   check_err("unlock", pthread_mutex_unlock(m));
> #       |             ^~~~~~~~
> ```

Yeah this looks like an issue with the compiler here. And `#include` directive is failing.

**Comment by kit-ty-kate** [comment]
> Yeah this looks like an issue with the compiler here. And `#include` directive is failing.

Mmh indeed. https://github.com/ocaml/ocaml/pull/11557 should fix it.

**Comment by kit-ty-kate** [comment]
In the meantime this looks fine. Thanks!

**Comment by toots** [comment]
> > Yeah this looks like an issue with the compiler here. And `#include` directive is failing.
> 
> Mmh indeed. [ocaml/ocaml#11557](https://github.com/ocaml/ocaml/pull/11557) should fix it.

Thanks for doing that!

**Pull request merged**
