### PR TITLE
QOcamlBrowser 0.2.11 for OCaml >= 4.08

### PR DESCRIPTION
**Pull request by Kakadu**
it was lagging behind.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The `remove` field is unnecessary since opam 2.0

**Comment by kit-ty-kate** [comment]
Could you return the fix to the upstream opam file?

**Comment by Kakadu** [comment]
> Could you return the fix to the upstream opam file?

Is it so important (changing opam file in project's repo)?

**Comment by kit-ty-kate** [comment]
> Is it so important (changing opam file in project's repo)?

yes, otherwise you'll have to do the same fixes next time (also you don't have to change the tag/archive or anything, it's just for the next release)

**Comment by mseri** [comment]
Thanks

**Pull request merged**
