### PR TITLE
+ sexplib and parsexp v0.11

### PR DESCRIPTION
**Pull request by trefis**
This also includes parsexp_io and ppx_js_style on which it depends.

### CODE REVIEW

**Comment by trefis** [comment]
As for #11608 , this depends on #11606 . My bad.

**Comment by trefis** [comment]
Rebased now that the prerequisite has been merged.

**Comment by jpdeplaix** [comment]
Could you have a look at the revdeps failures ?

**Comment by trefis** [comment]
- bap-frontend, bap-primus, bare: that's a conflict between sexplib0 and sexplib < v0.11 (sexplib v0.9 and v0.10 both define sexplib.0 which brings `Sexplib0__...` units. I just pushed a fix.
- planck: "could not obtain the sources of omake.0.9.8.6-0.rc1"
- mirage-http: "conf-pkg-config: pkg-config command not found"

**Comment by trefis** [comment]
There is a bunch of new failures, they all seem to be "could not obtain sources".
(Also, the set of revdeps grew since I added a constraint on a few packages earlier... this doesn't feel like a very sustainable workflow)

**Comment by trefis** [comment]
Also, the failure new bap-frontend failure seems unrelated to this PR:
```
#       ocamlc Camomile/.camomile.objs/camomileLibrary.{cmi,cmti} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlc.opt -I Camomile -w -40 -g -bin-annot -I Camomile/.camomile.objs -no-alias-deps -o Camomile/.camomile.objs/camomileLibrary.cmi -c -intf Camomile/camomileLibrary.mli)
# File "camomileLibrary.mlip", line 207, characters 21-35:
# Error: Unbound module type UCharInfo.Type
```

**Comment by trefis** [comment]
As for the conduit failure, it concerns a bunch of v0.9 packages:
```
#=== ERROR while compiling ipaddr.2.7.2 =======================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.05.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.05.0/.opam-switch/build/ipaddr.2.7.2
# command              ~/.opam/4.05.0/bin/ocaml pkg/pkg.ml build --pinned false --with-base-unix true
# exit-code            1
# env-file             ~/.opam/log/ipaddr-18-b53916.env
# output-file          ~/.opam/log/ipaddr-18-b53916.out
### output ###
# ocamlfind ocamldep -package 'bytes sexplib ppx_sexp_conv' -modules lib/ipaddr.ml > lib/ipaddr.ml.depends
# + ocamlfind ocamldep -package 'bytes sexplib ppx_sexp_conv' -modules lib/ipaddr.ml > lib/ipaddr.ml.depends
# File "lib/ipaddr.ml", line 30, characters 12-16:
# Error: Cannot locate deriver sexp
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'lib/ipaddr.a' 'lib/ipaddr.cmxs' 'lib/ipaddr.cmxa'
#      'lib/ipaddr.cma' 'lib/macaddr.cmx' 'lib/macaddr.cmi' 'lib/macaddr.mli'
#      'lib/ipaddr.cmx' 'lib/ipaddr.cmi' 'lib/ipaddr.mli' 'lib/ipaddr_unix.a'
#      'lib/ipaddr_unix.cmxs' 'lib/ipaddr_unix.cmxa' 'lib/ipaddr_unix.cma'
#      'lib/ipaddr_unix.cmx' 'lib/ipaddr_unix.cmi' 'lib/ipaddr_unix.mli'
#      'top/ipaddr_top.a' 'top/ipaddr_top.cmxs' 'top/ipaddr_top.cmxa'
#      'top/ipaddr_top.cma' 'top/ipaddr_top.cmx' 'top/ipaddr_top.cmi'
#      'top/ipaddr_top.mli']: exited with 10



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
+- The following actions were aborted
| - install conduit 1.0.3
+- 
+- The following actions failed
| - build ipaddr 2.7.2
+- 
+- The following changes have been performed
| - remove    sexplib0                v0.11.0
| - downgrade parsexp                 v0.11.0 to v0.9.0
| - downgrade sexplib                 v0.11.0 to v0.9.3
```

**Comment by jpdeplaix** [comment]
Ok, I thought I fixed the ipaddr failure in #11543 but it doesn't seem to be the case. I'll try something else.
In the meantime this seems good enough.

**Pull request merged**
