### PR TITLE
Octez 18.1 packages

### PR DESCRIPTION
**Pull request by killian-delarue**
Packages for Octez v18.1

### CODE REVIEW

**Comment by mseri** [comment]
octez-lib failure on macos is due to
```
Errors
# [15:56:14.251] ASSERT expects 5 requests
# [15:56:14.252] [error] Alcotest assertion failure
# [15:56:14.252] [error] File "src/lib_requester/test/test_requester.ml", line 211, character 2:
# [15:56:14.252] [error] FAIL expects 5 requests
# [15:56:14.252] [error] 
# [15:56:14.252] [error]    Expected: `5'
# [15:56:14.252] [error]    Received: `4'
# [15:56:14.252] [error] 
# [15:56:14.252] [error] 
# [15:56:14.252] [FAILURE] (7/37, 1 failed) tezos-requester: all (test fetch: full requester issues request)
[...]
# [10:23:24.217] [SUCCESS] (3/4) Syslog: check formatting function
# [10:23:24.217] Starting test: Syslog: send message through socket
# [10:23:24.217] [error] Protocol not supported
# [10:23:24.218] [FAILURE] (4/4, 1 failed) Syslog: send message through socket
```
Should we make it unavailable on mac or it is not a problem?

**Comment by mseri** [comment]
hacl_star_raw fails to link on freebsd:
```
# [ 60%] Linking C shared library libhacl.so
# ld: error: relocation R_X86_64_PC32 cannot be used against symbol 'Hacl_Impl_Chacha20_Vec_chacha20_constants'; recompile with -fPIC
# >>> defined in CMakeFiles/hacl.dir/src/Hacl_Chacha20.c.o
# >>> referenced by Hacl_Chacha20_Vec128.c
# >>>               CMakeFiles/hacl_vec128.dir/src/Hacl_Chacha20_Vec128.c.o:(Hacl_Chacha20_Vec128_chacha20_encrypt_128)
# 
# ld: error: relocation R_X86_64_PC32 cannot be used against symbol 'Hacl_Impl_Chacha20_Vec_chacha20_constants'; recompile with -fPIC
# >>> defined in CMakeFiles/hacl.dir/src/Hacl_Chacha20.c.o
# >>> referenced by Hacl_Chacha20_Vec128.c
# >>>               CMakeFiles/hacl_vec128.dir/src/Hacl_Chacha20_Vec128.c.o:(Hacl_Chacha20_Vec128_chacha20_decrypt_128)
# 
# ld: error: relocation R_X86_64_PC32 cannot be used against symbol 'Hacl_Impl_Chacha20_Vec_chacha20_constants'; recompile with -fPIC
# >>> defined in CMakeFiles/hacl.dir/src/Hacl_Chacha20.c.o
# >>> referenced by Hacl_Chacha20_Vec256.c
# >>>               CMakeFiles/hacl_vec256.dir/src/Hacl_Chacha20_Vec256.c.o:(Hacl_Chacha20_Vec256_chacha20_encrypt_256)
# 
# ld: error: relocation R_X86_64_PC32 cannot be used against symbol 'Hacl_Impl_Chacha20_Vec_chacha20_constants'; recompile with -fPIC
# >>> defined in CMakeFiles/hacl.dir/src/Hacl_Chacha20.c.o
# >>> referenced by Hacl_Chacha20_Vec256.c
# >>>               CMakeFiles/hacl_vec256.dir/src/Hacl_Chacha20_Vec256.c.o:(Hacl_Chacha20_Vec256_chacha20_encrypt_256)
# 
# ld: error: relocation R_X86_64_PC32 cannot be used against symbol 'Hacl_Impl_Chacha20_Vec_chacha20_constants'; recompile with -fPIC
# >>> defined in CMakeFiles/hacl.dir/src/Hacl_Chacha20.c.o
# >>> referenced by Hacl_Chacha20_Vec256.c
# >>>               CMakeFiles/hacl_vec256.dir/src/Hacl_Chacha20_Vec256.c.o:(Hacl_Chacha20_Vec256_chacha20_encrypt_256)
# 
# ld: error: relocation R_X86_64_PC32 cannot be used against symbol 'Hacl_Impl_Chacha20_Vec_chacha20_constants'; recompile with -fPIC
# >>> defined in CMakeFiles/hacl.dir/src/Hacl_Chacha20.c.o
# >>> referenced by Hacl_Chacha20_Vec256.c
# >>>               CMakeFiles/hacl_vec256.dir/src/Hacl_Chacha20_Vec256.c.o:(Hacl_Chacha20_Vec256_chacha20_encrypt_256)
# 
# ld: error: relocation R_X86_64_PC32 cannot be used against symbol 'Hacl_Impl_Chacha20_Vec_chacha20_constants'; recompile with -fPIC
# >>> defined in CMakeFiles/hacl.dir/src/Hacl_Chacha20.c.o
# >>> referenced by Hacl_Chacha20_Vec256.c
# >>>               CMakeFiles/hacl_vec256.dir/src/Hacl_Chacha20_Vec256.c.o:(Hacl_Chacha20_Vec256_chacha20_decrypt_256)
# 
# ld: error: relocation R_X86_64_PC32 cannot be used against symbol 'Hacl_Impl_Chacha20_Vec_chacha20_constants'; recompile with -fPIC
# >>> defined in CMakeFiles/hacl.dir/src/Hacl_Chacha20.c.o
# >>> referenced by Hacl_Chacha20_Vec256.c
# >>>               CMakeFiles/hacl_vec256.dir/src/Hacl_Chacha20_Vec256.c.o:(Hacl_Chacha20_Vec256_chacha20_decrypt_256)
# 
# ld: error: relocation R_X86_64_PC32 cannot be used against symbol 'Hacl_Impl_Chacha20_Vec_chacha20_constants'; recompile with -fPIC
# >>> defined in CMakeFiles/hacl.dir/src/Hacl_Chacha20.c.o
# >>> referenced by Hacl_Chacha20_Vec256.c
# >>>               CMakeFiles/hacl_vec256.dir/src/Hacl_Chacha20_Vec256.c.o:(Hacl_Chacha20_Vec256_chacha20_decrypt_256)
# 
# ld: error: relocation R_X86_64_PC32 cannot be used against symbol 'Hacl_Impl_Chacha20_Vec_chacha20_constants'; recompile with -fPIC
# >>> defined in CMakeFiles/hacl.dir/src/Hacl_Chacha20.c.o
# >>> referenced by Hacl_Chacha20_Vec256.c
# >>>               CMakeFiles/hacl_vec256.dir/src/Hacl_Chacha20_Vec256.c.o:(Hacl_Chacha20_Vec256_chacha20_decrypt_256)
# cc: error: linker command failed with exit code 1 (use -v to see invocation)
# gmake[3]: *** [CMakeFiles/hacl.dir/build.make:1067: libhacl.so] Error 1
# gmake[3]: Leaving directory '/usr/home/opam/.opam/4.14.1/.opam-switch/build/hacl-star-raw.0.7.1/hacl-star-raw/build'
# gmake[2]: *** [CMakeFiles/Makefile2:142: CMakeFiles/hacl.dir/all] Error 2
# gmake[2]: Leaving directory '/usr/home/opam/.opam/4.14.1/.opam-switch/build/hacl-star-raw.0.7.1/hacl-star-raw/build'
# gmake[1]: *** [Makefile:136: all] Error 2
# gmake[1]: Leaving directory '/usr/home/opam/.opam/4.14.1/.opam-switch/build/hacl-star-raw.0.7.1/hacl-star-raw/build'
# gmake: *** [Makefile:52: build-c] Error 2
# gmake: Leaving directory '/usr/home/opam/.opam/4.14.1/.opam-switch/build/hacl-star-raw.0.7.1/hacl-star-raw'
```
probably we should mark it unavailable? (ping @franziscuskiefer)

**Comment by franziskuskiefer** [comment]
I'm not sure what the freebsd support is in hacl ... Passing this on to @victor-dumitrescu . Is this supposed to work?

**Comment by killian-delarue** [comment]
> octez-lib failure on macos is due to
> 
> ```
> Errors
> # [15:56:14.251] ASSERT expects 5 requests
> # [15:56:14.252] [error] Alcotest assertion failure
> # [15:56:14.252] [error] File "src/lib_requester/test/test_requester.ml", line 211, character 2:
> # [15:56:14.252] [error] FAIL expects 5 requests
> # [15:56:14.252] [error] 
> # [15:56:14.252] [error]    Expected: `5'
> # [15:56:14.252] [error]    Received: `4'
> # [15:56:14.252] [error] 
> # [15:56:14.252] [error] 
> # [15:56:14.252] [FAILURE] (7/37, 1 failed) tezos-requester: all (test fetch: full requester issues request)
> [...]
> # [10:23:24.217] [SUCCESS] (3/4) Syslog: check formatting function
> # [10:23:24.217] Starting test: Syslog: send message through socket
> # [10:23:24.217] [error] Protocol not supported
> # [10:23:24.218] [FAILURE] (4/4, 1 failed) Syslog: send message through socket
> ```
> 
> Should we make it unavailable on mac or it is not a problem?

I think we want it available on Mac

**Comment by avsm** [comment]
@killian-delarue what's the status of this? Are you revising the release?

**Comment by killian-delarue** [comment]
> @killian-delarue what's the status of this? Are you revising the release?

I think it should be merge. What is missing ?

**Comment by mseri** [comment]
Nothing, we were waiting to hear from you if anything needed to change due to the failure on macos

**Comment by killian-delarue** [comment]
> Nothing, we were waiting to hear from you if anything needed to change due to the failure on macos

Ok, sorry for my lack of reactivity. I think it can be merged, the macos issue is reported and shouldn't be a probem here.

**Comment by mseri** [comment]
thanks!

**Pull request merged**
