### PR TITLE
Clangml 3.8.0.3

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Is it possible to retrieve the logfiles of the failing build:
https://travis-ci.org/ocaml/opam-repository/jobs/171043767
env-file     /Users/travis/.opam/system/build/clangml.3.8.0.3/clangml-6837-44ea43.env
stdout-file  /Users/travis/.opam/system/build/clangml.3.8.0.3/clangml-6837-44ea43.out
stderr-file  /Users/travis/.opam/system/build/clangml.3.8.0.3/clangml-6837-44ea43.err

**Comment by UnixJunkie** [comment]
probably outdated boost version installed by brew on the mac.

**Comment by avsm** [comment]
These are a little odd on the mac build:

```
# File "myocamlbuild.ml", line 192, characters 54-56:
# Warning 14: illegal backslash escape in string.
# File "myocamlbuild.ml", line 192, characters 59-61:
# Warning 14: illegal backslash escape in string.
# File "myocamlbuild.ml", line 87, characters 15-31:
# Warning 3: deprecated: Ocamlbuild_plugin.String.lowercase
# Use String.lowercase_ascii instead.
# File "myocamlbuild.ml", line 97, characters 4-16:
# Warning 3: deprecated: Scanf.fscanf
# Use Scanning.from_channel then Scanf.bscanf.
```

**Comment by UnixJunkie** [comment]
I am thinking about cancelling this package version: the install on mac is a hack (this clang version is not and will not be supported by brew).
I'll correct the warnings you report at least on the master branch of clangml if they still apply.

**Pull request closed without merging**
