### PR TITLE
[new release] irmin et al. (2.4.0)

### PR DESCRIPTION
**Pull request by CraigFe**
- Project page: <a href="https://github.com/mirage/irmin">https://github.com/mirage/irmin</a>
- Documentation: <a href="https://mirage.github.io/irmin/">https://mirage.github.io/irmin/</a>

### Fixed
- **irmin-pack**
  - Fix a bug in `inode` where the `remove` function could cause hashing
    instabilities. No user-facing change since this function is not being used
    yet. (mirage/irmin#1247, @Ngoguey42, @icristescu)

- **irmin**
  - Ensure that `Tree.add_tree t k v` complexity does not depend on `v` size.
    (mirage/irmin#1267, @samoht @Ngoguey42 and @CraigFe)

### Added

- **irmin**
  - Added a `Perms` module containing helper types for using phantom-typed
    capabilities as used by the store backends. (mirage/irmin#1262, @CraigFe)

  - Added an `Exported_for_stores` module containing miscellaneous helper types
    for building backends. (mirage/irmin#1262, @CraigFe)

  - Added new operations `Tree.update` and `Tree.update_tree` for efficient
    read-and-set on trees. (mirage/irmin#1274, @CraigFe)
    
- **irmin-pack**:
  - Added `integrity-check-inodes` command to `irmin-fsck` for checking the
    integrity of inodes. (mirage/irmin#1253, @icristescu, @Ngoguey42)

- **irmin-bench**
  - Added benchmarks for tree operations. (mirage/irmin#1237, @icristescu, @Ngoguey42,
    @Craigfe)

#### Changed

- The `irmin-mem` package is now included with the `irmin` package under the
  library name `irmin.mem`. It keeps the same top-level module name of
  `Irmin_mem`. (mirage/irmin#1276, @CraigFe)

#### Removed

- `Irmin_mem` no longer provides the layered in-memory store `Make_layered`.
  This can be constructed manually via `Irmin_layers.Make`. (mirage/irmin#1276, @CraigFe)

### CODE REVIEW

**Comment by CraigFe** [comment]
CI is failing for a couple of different reasons. Will need to re-cut this release upstream to fix.

**Comment by kit-ty-kate** [comment]
Some tests on the arm32 platform failed:
```
#=== ERROR while compiling irmin-unix.2.4.0 ===================================#
# context              2.1.0~beta4 | linux/arm32 | ocaml-base-compiler.4.11.1 | pinned(https://github.com/mirage/irmin/releases/download/2.4.0/irmin-2.4.0.tbz)
# path                 ~/.opam/4.11/.opam-switch/build/irmin-unix.2.4.0
# command              ~/.opam/4.11/bin/dune runtest -p irmin-unix -j 31
# exit-code            1
# env-file             ~/.opam/log/irmin-unix-24-2d1f9f.env
# output-file          ~/.opam/log/irmin-unix-24-2d1f9f.out
### output ###
#         test alias test/irmin-unix/runtest (exit 2)
# (cd _build/default && test/irmin-unix/test.exe -q --color=always)
# +85865us irw-polling     [INFO] Polling mode
# Testing `irmin-unix'.
# This run has ID `5F48E344-F114-486C-A79D-A58829D14A72'.
# 
#   [OK]          FS                        0   Basic operations on contents.
#   [OK]          FS                        1   Basic operations on nodes.
#   [OK]          FS                        2   Basic operations on commits.
#   [OK]          FS                        3   Basic operations on branches.
#   [OK]          FS                        4   Hash operations on trees.
#   [OK]          FS                        5   Basic merge operations.
#   [OK]          FS                        6   Basic operations on slices.
#   [OK]          FS                        7   Test merges on tree updates.
#   [OK]          FS                        8   Tree caches and hashconsing.
#   [OK]          FS                        9   Complex histories.
#   [OK]          FS                       10   Empty stores.
#   [OK]          FS                       11   Private node manipulation.
#   [OK]          FS                       12   High-level store operations.
#   [OK]          FS                       13   High-level operations on trees.
#   [OK]          FS                       14   High-level store synchronisation.
#   [OK]          FS                       15   High-level store merges.
#   [OK]          FS                       16   Unrelated merges.
#   [OK]          FS                       17   Low-level concurrency.
#   [OK]          FS                       18   Concurrent updates.
#   [OK]          FS                       19   with_tree strategies.
#   [OK]          FS                       20   Concurrent head updates.
#   [OK]          FS                       21   Concurrent merges.
#   [OK]          FS                       22   Shallow objects.
#   [OK]          FS                       23   Closure with disconnected commits.
#   [OK]          FS                       24   Clear.
#   [SKIP]        FS                       25   Wide nodes.
#   [OK]          FS                       26   Graph.Iter.
#   [OK]          FS                       27   Watch.Callbacks and exceptions.
#   [OK]          FS                       28   Watch.Basic operations.
#   [OK]          GIT                       0   Basic operations on contents.
#   [OK]          GIT                       1   Basic operations on nodes.
#   [OK]          GIT                       2   Basic operations on commits.
#   [OK]          GIT                       3   Basic operations on branches.
#   [OK]          GIT                       4   Hash operations on trees.
#   [OK]          GIT                       5   Basic merge operations.
#   [OK]          GIT                       6   Basic operations on slices.
#   [OK]          GIT                       7   Test merges on tree updates.
#   [OK]          GIT                       8   Tree caches and hashconsing.
#   [OK]          GIT                       9   Complex histories.
#   [OK]          GIT                      10   Empty stores.
#   [OK]          GIT                      11   Private node manipulation.
#   [OK]          GIT                      12   High-level store operations.
#   [OK]          GIT                      13   High-level operations on trees.
# > [FAIL]        GIT                      14   High-level store synchronisation.
#   [OK]          GIT                      15   High-level store merges.
#   [OK]          GIT                      16   Unrelated merges.
#   [OK]          GIT                      17   Low-level concurrency.
#   [OK]          GIT                      18   Concurrent updates.
#   [OK]          GIT                      19   with_tree strategies.
#   [OK]          GIT                      20   Concurrent head updates.
#   [OK]          GIT                      21   Concurrent merges.
#   [OK]          GIT                      22   Shallow objects.
#   [OK]          GIT                      23   Closure with disconnected commits.
#   [OK]          GIT                      24   Clear.
#   [SKIP]        GIT                      25   Wide nodes.
#   [OK]          GIT                      26   Graph.Iter.
#   [OK]          GIT                      27   Watch.Callbacks and exceptions.
#   [OK]          GIT                      28   Watch.Basic operations.
#   [OK]          HTTP.FS                   0   Basic operations on contents.
#   [OK]          HTTP.FS                   1   Basic operations on nodes.
#   [OK]          HTTP.FS                   2   Basic operations on commits.
#   [OK]          HTTP.FS                   3   Basic operations on branches.
#   [OK]          HTTP.FS                   4   Hash operations on trees.
#   [OK]          HTTP.FS                   5   Basic merge operations.
#   [OK]          HTTP.FS                   6   Basic operations on slices.
#   [OK]          HTTP.FS                   7   Test merges on tree updates.
#   [OK]          HTTP.FS                   8   Tree caches and hashconsing.
#   [OK]          HTTP.FS                   9   Complex histories.
#   [OK]          HTTP.FS                  10   Empty stores.
#   [OK]          HTTP.FS                  11   Private node manipulation.
#   [FAIL]        HTTP.FS                  12   High-level store operations.
#   [OK]          HTTP.FS                  13   High-level operations on trees.
#   [OK]          HTTP.FS                  14   High-level store synchronisation.
#   [OK]          HTTP.FS                  15   High-level store merges.
#   [OK]          HTTP.FS                  16   Unrelated merges.
#   [OK]          HTTP.FS                  17   Low-level concurrency.
#   [FAIL]        HTTP.FS                  18   Concurrent updates.
#   [OK]          HTTP.FS                  19   with_tree strategies.
#   [OK]          HTTP.FS                  20   Concurrent head updates.
#   [OK]          HTTP.FS                  21   Concurrent merges.
#   [OK]          HTTP.FS                  22   Shallow objects.
#   [FAIL]        HTTP.FS                  23   Closure with disconnected commits.
#   [FAIL]        HTTP.FS                  24   Clear.
#   [SKIP]        HTTP.FS                  25   Wide nodes.
#   [FAIL]        HTTP.FS                  26   Graph.Iter.
#   [FAIL]        HTTP.FS                  27   Watch.Callbacks and exceptions.
```

**Comment by CraigFe** [comment]
Thanks. Without a trace it's not easy to debug that one, so I've just added a conflict for now. Will try to get 32-bit CI again upstream and fix that on a subsequent release.

**Comment by CraigFe** [comment]
There are quite a few CI failures still, but they look unrelated. Perhaps because they timed out while waiting for resource from the cluster?

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
