### PR TITLE
llvm: add conf-wget since the source install script requires it at th…

### PR DESCRIPTION
**Pull request by avsm**
…e moment

This could also be patched to use `curl` which is guaranteed to be
available in the CI environments

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Fine by me. There is just one or two things. Could you do it for each version ? And you made a little copy-paste mistake for the the new llvm.3.8 script (you installed llvm 3.9 instead of 3.8).

**Comment by jpdeplaix** [comment]
Up

**Comment by avsm** [comment]
@jpdeplaix this should fix that, but I don't have time to maintain and debug the depext -- if you would like to edit your gist to reflect some of my changes, that would be most appreciated.

**Comment by jpdeplaix** [comment]
I just did that but unfortunately apt.llvm.org doesn't provide older versions (< 3.8) anymore :/

**Pull request closed without merging**
