### PR TITLE
Package universal-portal.0.1

### PR DESCRIPTION
**Pull request by pedrobslisboa**
### `universal-portal.0.1`
Universal Portal for ssr natively ReasonReact apps

---
* Homepage: https://github.com/pedrobslisboa/universal-portal
* Source repo: git+https://github.com/pedrobslisboa/universal-portal.git
* Bug tracker: https://github.com/pedrobslisboa/universal-portal/issues

---
:camel: Pull-request generated by opam-publish v2.3.0

### CODE REVIEW

**Comment by mseri** [comment]
Is this missing a dependency?
```
#=== ERROR while compiling universal-portal.0.1 ===============================#
# context              2.2.0~beta1 | linux/x86_64 | ocaml-base-compiler.5.1.1 | pinned(https://github.com/pedrobslisboa/universal-reason-portal/archive/refs/tags/0.1.tar.gz)
# path                 ~/.opam/5.1/.opam-switch/build/universal-portal.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p universal-portal -j 255 @install
# exit-code            1
# env-file             ~/.opam/log/universal-portal-7-d09ee3.env
# output-file          ~/.opam/log/universal-portal-7-d09ee3.out
### output ###
# File "packages/server/src/dune", line 8, characters 2-30:
# 8 |   server-reason-react.reactDom
#       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Library "server-reason-react.reactDom" not found.
# -> required by library "universal-portal.server" in
#    _build/default/packages/server/src
# -> required by _build/default/META.universal-portal
# -> required by _build/install/default/lib/universal-portal/META
# -> required by _build/default/universal-portal.install
# -> required by alias install
# File "packages/shared/js/dune", line 6, characters 25-39:
# 6 |  (libraries reason-react melange-webapi)
#                              ^^^^^^^^^^^^^^
# Error: Library "melange-webapi" not found.
# -> required by library "universal-portal.shared_js" in
#    _build/default/packages/shared/js
# -> required by _build/default/META.universal-portal
# -> required by _build/install/default/lib/universal-portal/META
# -> required by _build/default/universal-portal.install
# -> required by alias install
# File "packages/shared/native/dune", line 5, characters 38-66:
# 5 |  (libraries server-reason-react.react server-reason-react.reactDom)
#                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Library "server-reason-react.reactDom" not found.
# -> required by library "universal-portal.shared_native" in
#    _build/default/packages/shared/native
# -> required by _build/default/META.universal-portal
# -> required by _build/install/default/lib/universal-portal/META
# -> required by _build/default/universal-portal.install
# -> required by alias install
# File "packages/server/src/dune", line 13, characters 7-30:
# 13 |   (pps server-reason-react.ppx server-reason-react.browser_ppx)))
#             ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Library "server-reason-react.ppx" not found.
# -> required by
#    _build/default/packages/server/src/.merlin-conf/lib-universal-portal.server
# -> required by _build/default/packages/server/src/server.a
# -> required by _build/install/default/lib/universal-portal/server/server.a
# -> required by _build/default/universal-portal.install
# -> required by alias install
# File "packages/shared/native/dune", line 9, characters 3-26:
# 9 |    server-reason-react.ppx
#        ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Library "server-reason-react.ppx" not found.
# -> required by
#    _build/default/packages/shared/native/.merlin-conf/lib-universal-portal.shared_native
# -> required by _build/default/packages/shared/native/shared_native.a
# -> required by
#    _build/install/default/lib/universal-portal/shared_native/shared_native.a
# -> required by _build/default/universal-portal.install
# -> required by alias install
# File "packages/shared/js/dune", line 8, characters 36-67:
# 8 |   (pps melange.ppx reason-react-ppx server-reason-react.browser_ppx -js)))
#                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Library "server-reason-react.browser_ppx" not found.
# -> required by
#    _build/default/packages/shared/js/UniversalPortal_Shared.re.pp.ml
# -> required by
#    _build/default/packages/shared/js/.shared_js.objs/melange/universalPortal_Shared.cmi
# -> required by
#    _build/install/default/lib/universal-portal/shared_js/melange/universalPortal_Shared.cmi
# -> required by _build/default/universal-portal.install
# -> required by alias install
```

**Comment by davesnx** [comment]
server-reason-react isn't published to opam, yet (I pushed the PR after seeing this PR)

https://github.com/ocaml/opam-repository/pull/25226

**Comment by davesnx** [comment]
server-reason-react got published to opam after: https://github.com/ocaml/opam-repository/pull/25226

**Comment by samoht** [comment]
@davesnx do you mind adding `melange-server-react` to the list of dependencies to please the CI? Thanks!

**Comment by pedrobslisboa** [comment]
Long time no see of this PR, just updated it with correct dependencies. 🤞🏻

**Comment by samoht** [comment]
Thanks! The remaining failures are on unstable distributions:

- opensuse-15.5-ocaml-5.1 [universal-portal.0.1 (failed: quickjs.0.1.1 failed to build)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/12bb8f00d4200644524572c2be37ecde3319bcfe/variant/distributions,opensuse-15.5-ocaml-5.1,universal-portal.0.1)
- oraclelinux-9-ocaml-5.1 [universal-portal.0.1 (failed: System package install failed with exit code 1 at command:)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/12bb8f00d4200644524572c2be37ecde3319bcfe/variant/distributions,oraclelinux-9-ocaml-5.1,universal-portal.0.1)

So for me this is good to merge!

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
