### PR TITLE
Add google-drive-ocamlfuse 0.5.17

### PR DESCRIPTION
**Pull request by astrada**

### CODE REVIEW

**Comment by AltGr** [comment]
hmm, there are still some quirks with @opam-ci: seems what it tested wasn't exactly what is in this PR...

**Comment by AltGr** [comment]
Got it, GitHub is actually giving us the current sha, not the common ancestor; so this includes a reverse diff of what was done on master since. We can either diff to the common ancestor instead, or diff the merge commit with the current master commit.

**Comment by AltGr** [comment]
yay, much better now :)

**Comment by AltGr** [comment]
(Sorry for the spam @astrada, just debugging the brand new beta opam-ci tool, this is quite unrelated to your PR)

**Comment by astrada** [comment]
OK, thanks. Anyway I updated my opam file to pass the linter, but I forgot to push it. I'm doing it now so I can test my new file.

**Comment by avsm** [comment]
Diffing to the current master commit seems most useful given that'll be where it'll get merged

**Comment by samoht** [comment]
I've restarted the failed job

**Comment by AltGr** [comment]
@avsm you mean diffing current master and merge commit ? That would indeed avoid errors such as [this one](https://github.com/ocaml/opam-repository/pull/4259#issuecomment-113092529), at least once the dependency has been merged. The reasons I prefered to diff with the ancestor are these (maybe none of them is a blocker):
- it's easier to track (reports refer only to existing, visible SHAs)
- the results don't get outdated when master changes
- ocaml-git doesn't provide a way to fetch a commit which doesn't belong to a branch, which is the case of the "virtual merge commit" referred to in the PR information, AFAIK. Of course it's no reason not to improve its API :)

**Comment by AltGr** [comment]
- it forces authors to rebase their PRs to avoid such errors. I don't think it's a bad thing, as it makes the history tree a bit thinner

**Pull request merged**
