### PR TITLE
Add: brr.0.0.6, note.0.0.3

### PR DESCRIPTION
**Pull request by dbuenzli**
* Add: `brr.0.0.6` [home](https://erratique.ch/software/brr), [doc](https://erratique.ch/software/brr/doc/), [issues](https://github.com/dbuenzli/brr/issues)  
  *Browser programming toolkit for OCaml*
* Add: `note.0.0.3` [home](https://erratique.ch/software/note), [doc](https://erratique.ch/software/note/doc/), [issues](https://github.com/dbuenzli/note/issues)  
  *Declarative events and signals for OCaml*

---

#### `brr` v0.0.6 2023-07-29 Zagreb

- The experimental library `brr.note` has been migrated to the `note.brr`
  library available via the `note` package. The toplevel modules 
  were renamed from `Brr_note*` to `Note_brr*`.
  
- Fix encoding mess in `Brr.Uri` which tried to expose a model that is
  not workable in practice due to the way the URI standard is defined.
  
  * Accessors and `Uri.with_uri` no longer perform percent decoding and 
    encoding for you.
  * Added helper functions `Uri.[with_]{query,fragment}_params`.
  * Added helper functions `Uri.[with_]{path_segments}`.
  
  Thanks to Max Lang for the report and making sure the new API makes
  sense ([#50](https://github.com/dbuenzli/brr/issues/50)).

- Add canvas color space support (note: unsupported on Firefox for now).

  * `C2d.attrs`, add `color_space` and `will_read_frequently` attributes.
  * Add `C2d.Image_data.color_space` and a `?color_space` optional argument
    to `C2d.{create,get}_image_data` and `C2d.Image_data.create`.

- `Brr.Blob.{array_buffer,text,data_uri}`: add an optional argument
  `?progress`. If provided the load happens via a `FileReader` object
  and load progress is reported ([#39](https://github.com/dbuenzli/brr/issues/39)).

- Updated developer tool console to Manifest V3 ([#44](https://github.com/dbuenzli/brr/issues/44)).

---

#### `note` v0.0.3 2023-07-39 Zagreb

- Add the `note.brr` experimental library. This used to be `brr.note`
  in `brr`. The toplevel modules have been renamed from `Brr_note*` to
  `Note_brr*`. `brr` becomes an optional dependency of `note`.

---

Use `b0 -- .opam.publish brr.0.0.6 note.0.0.3` to update the pull request.

### CODE REVIEW

**Comment by dbuenzli** [comment]
The failures seems to be due to a change in checksum in the leaflet revdep /cc @zapashcanon

**Comment by zapashcanon** [comment]
cc @Swrup who is the maintainer of this leaflet package ;)

**Comment by dinosaure** [comment]
I made an issue about `leaflet`, thanks!

**Comment by dbuenzli** [comment]
Thanks!

**Pull request merged**
