### PR TITLE
conduit-async: fix bounds for async

### PR DESCRIPTION
**Pull request by samoht**
Should fix the issue found in #12552

### CODE REVIEW

**Comment by samoht** [comment]
I'm moved some of the revdeps fixes to https://github.com/ocaml/opam-repository/pull/12556 to avoid saturating the CI..

**Comment by mseri** [comment]
Let’s re run the tests with the sedlex fix

**Comment by samoht** [comment]
Rebased

**Comment by samoht** [comment]
> so I think we can merge

sounds good to me :-)

**Pull request merged**
