### PR TITLE
checksum changes

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
```
[91m[ERROR] Bad checksum for
        /home/opam/.opam/packages.dev/ppx_meta_conv.2.5.0/2.5.0.tar.gz:
          - 6fc5428ec4d8d9a12128f9a3f0d254dc [expected result]
          - 2cd5055d7267c0e762c7220568d3b5e6 [actual result]
        This may be fixed by running `opam update`.
```

**Comment by camlspotter** [comment]
omake.0.10.1 glitch

**Comment by camlspotter** [comment]
Timed out :-(

**Comment by camlspotter** [comment]
https://github.com/ocaml/opam-repository/pull/8342, which is a subset of this has passed. Let's wait its merge.

**Comment by avsm** [comment]
This could use a merge against master now that #8342 has passed. Thanks for all the fixes @camlspotter!

**Comment by camlspotter** [comment]
So now the diff is enough small to test things in time! (I hope)

**Comment by avsm** [comment]
Hurrah! Also, there is no time limit on the DataKit builds @camlspotter, so larger PRs are ok

**Pull request merged**
