### PR TITLE
Package malfunction.0.5

### PR DESCRIPTION
**Pull request by stedolan**
### `malfunction.0.5`
Compiler back-end for functional languages, based on OCaml
Malfunction is a high-performance, low-level untyped program
representation, designed as a target for compilers of functional
programming languages.

---
* Homepage: https://github.com/stedolan/malfunction
* Source repo: git+https://github.com/stedolan/malfunction.git
* Bug tracker: https://github.com/stedolan/malfunction/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by stedolan** [comment]
I don't know what's going on in the macos-homebrew test. Is there any way to reproduce this locally? (The build logs give a dockerfile, but I don't think that base image is public)

**Comment by mseri** [comment]
I tried locally. It works with bash 5 but `/bin/bash` on mac points to bash 3.2, and that fails because `|&` is not supported

**Comment by stedolan** [comment]
Ah, thanks! I'll switch it to `2>&1 |`

**Comment by mseri** [comment]
Good point

**Comment by stedolan** [comment]
The only reason it's a bash script is for `|&`, which I hadn't realised was a recent addition. I'll change it to pure `sh`.

**Comment by dinosaure** [comment]
I'm not sure why but it seems that the `test.sh` returns a bad code on MacOS:
```shell-session
- File "test_cli/dune", line 1, characters 0-118:
- 1 | (rule
- 2 |  (targets test.log test.expect)
- 3 |  (deps test.sh (source_tree .) (package malfunction))
- 4 |  (action (run ./test.sh)))
- (cd _build/default/test_cli && ./test.sh)
- Command exited with code 2.
- (cd _build/default/examples && ./primrec.exe)
-  interpreted: 1.13 secs
-     compiled: 0.14 secs
- (cd _build/default/test && ./test.exe ../docs/spec.md ../test)
- ../docs/spec.md: 
../docs/spec.md:          [13/13] tests passed
- ../test/basic.test: 
../test/basic.test:       [6/6] tests passed
- ../test/lazy.test: 
../test/lazy.test:        [5/5] tests passed
- ../test/vector.test: 
../test/vector.test:      [3/3] tests passed
- ../test/conversions.test: 
../test/conversions.test: [6/6] tests passed
- ../test/factorial.test: 
../test/factorial.test:   [1/1] tests passed
- ../test/float.test: 
../test/float.test:       [8/8] tests passed
- ../test/evalorder.test: 
../test/evalorder.test:   [3/3] tests passed
- ../test/shifts.test: 
../test/shifts.test:      [18/18] tests passed
- ../test/prim.test: 
../test/prim.test:        [1/1] tests passed
- All tests passed
```

**Comment by stedolan** [comment]
As far as I can tell, the remaining CI failures are due to:
  - build failures of uunf on 4.14+flambda
  - lack of native code support on ocaml5 on various archs

So I think this is ready to merge?

**Comment by avsm** [comment]
Looks good. Ideally we would have a dependency to indicate it shouldn't attempt compilation on a bytecode-only compiler, but that can be refined later.

**Pull request merged**
