### PR TITLE
added packages/conf-openbabel/conf-openbabel.0.1

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by avsm** [comment]
would alpine and centos packages be easily available for this? if not i'll merge as-is

**Comment by UnixJunkie** [comment]
For centos, I'm sure there are, I will list them if it is not already done.
For Alpine, I looked for them and apparently they don't have openbabel (while it is a super famous
package for chemists).

**Comment by UnixJunkie** [comment]
I corrected the depext package name for centos.

**Comment by UnixJunkie** [comment]
This site is quite nice to find package names across distros:
https://pkgs.org/

**Comment by UnixJunkie** [comment]
This package is as good as I can make it.
I think it is OK to merge.
If not, what should I make better?

**Comment by avsm** [comment]
This looks as good as we can get right now indeed, thank you!

**Pull request merged**
