### PR TITLE
[new release] ppxlib (0.24.0)

### PR DESCRIPTION
**Pull request by pitag-ha**
Standard library for ppx rewriters

- Project page: <a href="https://github.com/ocaml-ppx/ppxlib">https://github.com/ocaml-ppx/ppxlib</a>
- Documentation: <a href="https://ocaml-ppx.github.io/ppxlib/">https://ocaml-ppx.github.io/ppxlib/</a>

##### CHANGES:

- Add support for OCaml 4.14 (ocaml-ppx/ppxlib#304, @kit-ty-kate)

- Expand nodes before applying derivers or other inline attributes based
  transformation, allowing better interactions between extensions and
  derivers (ocaml-ppx/ppxlib#279, ocaml-ppx/ppxlib#297, @NathanReb)

- Add support for registering ppx_import as a pseudo context-free rule (ocaml-ppx/ppxlib#271, @NathanReb)

- Add `input_name` to the `Expansion_context.Extension` and `Expansion_context.Deriver` modules (ocaml-ppx/ppxlib#284, @tatchi)

- Improve `gen_symbol` to strip previous unique suffix before adding a new one (ocaml-ppx/ppxlib#285, @ceastlund)

- Improve `name_type_params_in_td` to use prefixes `a`, `b`, ... instead of `v_x`. (ocaml-ppx/ppxlib#285, @ceastlund)

- Fix a bug in `type_is_recursive` and `really_recursive` where they would
  consider a type declaration recursive if the type appeared inside an attribute
  payload (ocaml-ppx/ppxlib#299, @NathanReb)

### CODE REVIEW

**Comment by pitag-ha** [comment]
This release is ready for review. I've just made it a draft release to double-check due to a couple of impactful commits in it and because I've reverted one commit for this release. But as soon as it passes all your checks, let's undraft it.

**Comment by kit-ty-kate** [comment]
For posterity:
```
#=== ERROR while compiling ppx_repr.0.5.0 =====================================#
# context              2.0.10 | linux/x86_64 | ocaml-base-compiler.4.13.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.13/.opam-switch/build/ppx_repr.0.5.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ppx_repr -j 31 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/ppx_repr-2647-e7966f.env
# output-file          ~/.opam/log/ppx_repr-2647-e7966f.out
### output ###
# File "test/ppx_repr/deriver/passing/type_params.expected", line 1, characters 0-0:
#          git (internal) (exit 1)
# (cd _build/default && /usr/bin/git --no-pager diff --no-index --color=always -u test/ppx_repr/deriver/passing/type_params.expected test/ppx_repr/deriver/passing/type_params.actual)
# diff --git a/test/ppx_repr/deriver/passing/type_params.expected b/test/ppx_repr/deriver/passing/type_params.actual
# index 9dfae04..5e92841 100644
# --- a/test/ppx_repr/deriver/passing/type_params.expected
# +++ b/test/ppx_repr/deriver/passing/type_params.actual
# @@ -13,8 +13,8 @@ let __ : type a. a typ -> a Id.t typ = Id.t
#  module Phantom :
#    sig
#      type _ t = int[@@deriving repr]
# -    include sig val t : 'v_x__001_ Repr.t -> 'v_x__001_ t Repr.t end[@@ocaml.doc
# -                                                                    "@inline"]
# +    include sig val t : 'a__001_ Repr.t -> 'a__001_ t Repr.t end[@@ocaml.doc
# +                                                                  "@inline"]
#      [@@merlin.hide ]
#    end =
#    struct
```

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Comment by pitag-ha** [comment]
Thanks @kit-ty-kate for your patience! On one hand it's helpful to try out experimental `dune-release` features like `--draft`, but on the other hand I know that I've generated both of us more work with that.

**Pull request merged**
