### PR TITLE
the basic make program naming issue

### PR DESCRIPTION
**Pull request by azarens**
doesn't work on bsd otherwise

### CODE REVIEW

**Comment by dsheets** [comment]
Could you be a little more specific about the problem you are trying to solve?

The present opam file does not work for me on FreeBSD 10 but this *is not* due to the opam file but rather the use of `make -C src all` in `configure.ml`. I don't believe your fix actually changes anything. Have you tested it?

**Comment by azarens** [comment]
The system is NetBSD, but that should be beside the point.  This particular configure command when executed on pristine source tree did not have the same issue.

For some reason, when I run "gmake configure" in the source directory created by "opam source" and the "build/patoline.0.1" directory created by opam, I'm getting different results.  Namely, in one case, I get an executable configure script produced, whereas in another case it becomes a shell script.  Is opam introducing additional files into the build process?

**Comment by dsheets** [comment]
Do you have `patoline` pinned to their development repo? Which version of opam are you using?

The version of patoline in opam generates a non-portable makefile. The version of patoline in the upstream repo produces an executable.

**Comment by samoht** [comment]
should be "make" (with quotes), see https://github.com/ocaml/opam-repository/pull/4833

**Comment by dsheets** [comment]
I don't believe that (`"make"`) actually solves the problem (which I don't believe is as reported)... have you tested the proposed change?

**Comment by dsheets** [comment]
This issue is due to a portability problem in the upstream package and is not fixable with only opam metadata. I am closing this issue as it's not an opam packaging problem.

**Pull request closed without merging**
