### PR TITLE
jbuilder 1.0+beta8, ppx_{driver,here,inline_test,bench} v0.9.1, base v0.9.2

### PR DESCRIPTION
**Pull request by diml**
This release removes a few hard-coded parameters in jbuilder and
updates the packages relying on these parameters

### CODE REVIEW

**Comment by diml** [comment]
I removed the alpha versions of Base and Stdio since they were broken and are no longer needed. 

Looking at the other revdeps failures, there seem to be a missing constraint on jbuilder for pumping. /cc @drup, `(executable ...)` is only available since 1.0+beta6. BTW since beta7 you can also [simplify the build: field](https://github.com/janestreet/jbuilder/blob/master/doc/manual.org#invocation-from-opam).

ppx_fun is also broken but it looks unrelated to this PR as well, it is missing a dependency to ppx_tools. /cc @little-arhat

**Comment by hcarty** [comment]
We should be careful/cautious in general when removing packages - if a user has a package installed that's since been removed, opam won't know how to properly uninstall/update it.

**Comment by diml** [comment]
Not sure why opam can't upgrade it, but anyway base v0.9.0 has been out for a few weeks so hopefully it shouldn't be too disruptive.

The revdeps looks good now, except for pumping and ppx_fun but they are unrelated to this PR. The travis failure is due to the bug in ocaml 4.05.0+beta3

**Pull request merged**
