### PR TITLE
[new release] goblint-cil (2.0.4)

### PR DESCRIPTION
**Pull request by sim642**
A front-end for the C programming language that facilitates program analysis and transformation

- Project page: <a href="https://github.com/goblint/cil">https://github.com/goblint/cil</a>

##### CHANGES:

* Add `Return` statement expression location (goblint/cil#167).
* Add `availability` attribute support (goblint/cil#168, goblint/cil#171).
* Remove unused `Libmaincil` module (goblint/cil#165).
* Fix some synthetic locations (goblint/cil#166, goblint/cil#167).

### CODE REVIEW

**Comment by sim642** [comment]
The freebsd (experimental) failures seem to be the same as last time: https://github.com/ocaml/opam-repository/pull/24812#issuecomment-1819231335.

**Review by shonfeder — APPROVED** [review]

**Comment by shonfeder** [comment]
Thanks for the error, analysis and the update, @sim642 :)

Assuming that these are not fundamental incompatibilities with the platforms failing on CI, do you think we should either the package to accept those CI failures in the future, and/or add a post-failure message on them indicating how a user could adjust their system to let the installation go thru?

**Comment by sim642** [comment]
I added some `x-ci-accept-failures` and `availability` changes that should be appropriate for these packages.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
