### PR TITLE
[coq] New opam package version.

### LINKED ISSUE #11316: `coq` build is broken in OSX.
It seems that https://github.com/ocaml/opam-repository/commit/bedf28512d289a4db677dba8b0afe70fd17164b2 broke the build of Coq in OSX.

See for example: https://travis-ci.org/ocaml/opam-repository/jobs/334441912

This will likely require action in backporting upstream https://github.com/coq/coq/pull/6518

An extremely annoying aspect of OPAM is these "updates" to already existing packages without increasing the version numbering. This indeed looks to me like a critical design flaw. Now, it turns out that some users will have `num.1.1` in their system however there is no way to know if the have a `1.1` after or before bedf28512d289a4db677dba8b0afe70fd17164b2 was committed.

So it seems to me that it is impossible to debug problems like these reliably.

### PR DESCRIPTION
**Pull request by ejgallego**
Backports https://github.com/coq/coq/commit/fc76dd1 to 8.7.1 to fix #11316.

This will also fix https://github.com/coq/coq/issues/6681

### CODE REVIEW

**Comment by ejgallego** [comment]
Let's see if this works cc: @RalfJung

**Comment by RalfJung** [comment]
LGTM. I assume coqide in https://github.com/coq/opam-coq-archive/ will also need a patch?

**Comment by ejgallego** [comment]
Umm, it is not working, I dunno... launching a debug build.

**Comment by ejgallego** [comment]
Wow, it took a while but this finally seems ready. Upstream patch at https://github.com/coq/coq/pull/6669

**Comment by ejgallego** [comment]
> I assume coqide in https://github.com/coq/opam-coq-archive/ will also need a patch?

Umm, I'm not sure, does `coqide` rebuild Coq?

It should not rebuild Coq so in principle, as it doesn't link to num it should work.

**Comment by ejgallego** [comment]
Anyways we should port CoqIDE to Dune and let it be built against the standard Coq META, but that's a bit of work.

**Comment by RalfJung** [comment]
> Umm, I'm not sure, does coqide rebuild Coq?

AFAIK it does. What else should it do?

**Comment by ejgallego** [comment]
> AFAIK it does. What else should it do?

It could perfectly build using Coq as a library, `coq-serapi` does that for example. Some time ago I proposed to split coqide from Coq and indeed that's what happened. But now we have different plans, hopefully using `dune` we can avoid rebuildling Coq.

**Comment by mattam82** [comment]
Ping?

**Comment by jpdeplaix** [comment]
All green now. Merging, thanks.

**Pull request merged**
