### PR TITLE
[new release] httpaf_caged (1.0.1)

### PR DESCRIPTION
**Pull request by thedufer**
A higher-level httpaf-async server interface

- Project page: <a href="https://github.com/thedufer/httpaf_caged">https://github.com/thedufer/httpaf_caged</a>

##### CHANGES:

fix a couple of release issues (such as the duplicate dune requirement)

### CODE REVIEW

**Comment by mseri** [comment]
Looks like you are missing a dependency on ppx_jane:

```
#=== ERROR while compiling httpaf_caged.1.0.1 =================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://github.com/thedufer/httpaf_caged/releases/download/1.0.1/httpaf_caged-1.0.1.tbz)
# path                 ~/.opam/4.10/.opam-switch/build/httpaf_caged.1.0.1
# command              ~/.opam/4.10/bin/dune build -p httpaf_caged -j 72 @install
# exit-code            1
# env-file             ~/.opam/log/httpaf_caged-23-9c272d.env
# output-file          ~/.opam/log/httpaf_caged-23-9c272d.out
### output ###
# File "dune", line 5, characters 18-26:
# 5 |  (preprocess (pps ppx_jane)))
#                       ^^^^^^^^
# Error: Library "ppx_jane" not found.
# Hint: try: dune external-lib-deps --missing -p httpaf_caged -j 72 @install
```

**Comment by thedufer** [comment]
Thanks for the pointer!  I wrote down my opam roots incorrectly (httpaf instead of httpaf-async) and lost a bunch of transitive dependencies.

I updated the opam file in this PR but didn't change the bundle it points to at all.  Is that just going to work?  I mean the checks passed but it felt weird.

**Comment by mseri** [comment]
If there are transitive dependencies that you are linking explicitly in your project, e.g. `ppx_jane`, it is better to list them explicitly in the opam file. In this way you reduce risk of metadata breakage when new version of your dependencies are released or if dune becomes stricter on transitive dependencies. Can you check that all the packages you are explicitly using are listed, and add the missing ones (if any)?

**Comment by thedufer** [comment]
I believe those cover it.

**Comment by mseri** [comment]
Thank you very much! There is a missing "v" in janestreet dependencies. I have fixed it here, can you please upstream the changes. I'll let the CI have another go, but this is now good to merge

**Comment by thedufer** [comment]
Yep I've upstreamed that fix.  Thanks!

**Comment by thedufer** [comment]
Thanks for your help and patience!

**Pull request merged**
