### PR TITLE
Add reason-parser.1.12.0

### PR DESCRIPTION
**Pull request by tekknolagi**
This adds the reason sub-package, reason-parser.

### CODE REVIEW

**Comment by tekknolagi** [comment]
This is a pretty neat CI setup you have here.

**Comment by avsm** [comment]
glad its useful! https://github.com/avsm/mirage-ci

**Comment by tekknolagi** [comment]
@avsm Approximately when will this package go live? Trying to figure out when our package CI will pass.

**Comment by avsm** [comment]
sorry I missed this question when you asked it @tekknolagi -- the opam.ocaml.org site is rebuilt hourly, so that's the approximate lag to a merged package going live.

**Comment by tekknolagi** [comment]
Oh, neat. Thanks!

**Pull request merged**
