### PR TITLE
Add monomorphic 1.2

### PR DESCRIPTION
**Pull request by jpdeplaix**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
mmmh there was a system failure on one travis node, can you either relaunch it or merge this PR ?

**Comment by yallop** [comment]
I've restarted the job.

**Comment by samoht** [comment]
```
[ERROR] At ~/.opam/repo/default/packages/monomorphic/monomorphic.1.2/opam:8:57:
  Not a recognised version-control URL
```

Can you please change `archive` to `http` in the `url` file?

**Comment by jpdeplaix** [comment]
Oh, I didn't see you change you comment :/ Are you sure it's the problem now ?

**Comment by samoht** [comment]
yea sorry I read the error message after doing my first comment (call it a reflex...). The error is really in the `dev-repo` contents. opam doesn't know that an `https` url is a `git` repo. You need to help it by adding `.git` at the end of the repo.

**Pull request merged**
