### PR TITLE
mirage-net-lwt: restrict to ipaddr <3.0.0 (requires Macaddr.t which i…

### PR DESCRIPTION
**Pull request by hannesm**
…s now longer part of ipaddr 3.0.0 API)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by kit-ty-kate** [comment]
oops mmh, there is a problem. Several packages become not installable after this :/ Could you have a look?

**Comment by hannesm** [comment]
@avsm https://github.com/ocaml/opam-repository/pull/13244 and upstream https://github.com/mirage/ocaml-ipaddr/pull/82

**Comment by hannesm** [comment]
NB: this PR is fine to merge as well, and I'll follow up tonight with a release of mirage-net{-lwt} to get the packages above installable again (and then hopefully really soon now a mirage release so people can actually use these packages ;)

**Comment by hannesm** [comment]
see #13246 for a new mirage-net release to avoid uninstallable packages

**Pull request merged**
