### PR TITLE
Fix accessor*, higher_kinded, and ppx_accessor packages.

### PR DESCRIPTION
**Pull request by xclerc**
This pull requests fixes the following packages by adding a `public_name` stanza (See [1]):

- `accessor`;
- `accessor_async`;
- `accessor_base`;
- `accessor_core`;
- `higher_kinded`;
- `ppx_accessor`.

[1] https://discuss.ocaml.org/t/ann-v0-14-release-of-jane-street-packages/5893/9

### CODE REVIEW

**Comment by xclerc** [comment]
(Do not merge, this pull request needs additional commits.)

**Comment by xclerc** [comment]
https://github.com/ocaml/opam-repository/pull/16562/commits/ba464086519e6fdc8d01b1d6apend557ea8b8fc06c67 is expected to fix the pending issues by:

- adding the missing `applicative_without_return` library (in `accessor`);
- updating the dependencies of the various packages.

**Comment by xclerc** [comment]
(The Travis error is a timeout.)

**Comment by kit-ty-kate** [comment]
thanks a lot! Sorry for the time this took, we had lots of issues in our CI

**Pull request merged**
