### PR TITLE
Fix drom.0.1.0 checksum

### PR DESCRIPTION
**Pull request by lefessan**
There was a modification of the release commit, so it changed the checksum.

### CODE REVIEW

**Comment by avsm** [comment]
Could you please rename this package to drom.0.1.0-1 then, and remove the previous? We're trying hard to make the released packages immutable from an archive perspective.

**Comment by lefessan** [comment]
I directly switched to 0.2.0, and removed the former (incorrect) package.

**Comment by lefessan** [comment]
The CI failed because of download problems ?

**Comment by avsm** [comment]
Thanks @lefessan; it looks like it was a transient GitHub problem (they returned a 404 on the archive), so I've restarted the affected jobs.

**Comment by lefessan** [comment]
Thanks ! All the lights are green now :-)

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
