### PR TITLE
added packages/bitv/bitv.1.3

### PR DESCRIPTION
**Pull request by UnixJunkie**
should be compatible with ocaml 4.06.0

### CODE REVIEW

**Comment by gasche** [comment]
Travis CI fails on 4.00 and 4.01, because you didn't use a Bytes compatibility module:

```
# File "bitv.ml", line 526, characters 12-22:
# Error: Unbound module Bytes
# make: *** [bitv.cmo] Error 2
```

You need to use a compatibility module or update your ocaml lower bound.

**Comment by UnixJunkie** [comment]
@backtracking I think this means a change upstream.
What is a Bytes compatiblity module? Are there examples somewhere?
Should we depend on some library providing that?
Sorry for the dumb question.
As a packager, I am OK to add a lower bound ocaml version constraint to this package, but Jean-Christophe might want that bitv installs on many ocaml versions.

**Comment by jpdeplaix** [comment]
@UnixJunkie You just have to add ```base-byte``` to your dependencies and everything should be fine :)
Could you also add the ```build``` attribute to ```ocamlfind``` if this package doesn't use the ```Findlib``` library ?

**Comment by UnixJunkie** [comment]
done

**Comment by UnixJunkie** [comment]
thanks for the info

**Comment by gasche** [comment]
You need `base-bytes` as a dependency *and* you need every `ocamlfind` invocation to also use the `bytes` package. This requires a change in the package build system, so it's not a metadata-only information. I propose that you *remove* base-bytes as a dependency of this version, you add the upper bound, and then you discuss with Jean-Christophe to know whether you want to do a 1.3.1 that properly supports older versions.

**Comment by UnixJunkie** [comment]
I incremented the lower bound

**Pull request merged**
