### PR TITLE
camlzip version 1.08

### PR DESCRIPTION
**Pull request by xavierleroy**
Version 1.08 of Camlzip was just released.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I improved the opam file by:
* Removing the `remove` field which is unnecessary with opam 2
* Using `conf-zlib` instead of custom depexts
* Tagging `ocamlfind` as a build dependency since you seem to use it only during compilation

**Comment by xavierleroy** [comment]
Thanks a lot for the review and improvements.  However I'm not sure what you mean by "Tagging ocamlfind as a build dependency since you seem to use it only during compilation" ?  Users of this package are supposed to use ocamlfind... (In order to link with the library.)

**Comment by kit-ty-kate** [comment]
@xavierleroy Tagging `ocamlfind` as a build dependency means camlzip won't get rebuilt if ocamlfind is updated. It stays an hard dependency, it's just about rebuilding.
But other than that, `ocamlfind` is not used by `dune` for example, so users won't necessary need it to use `camlzip`.

**Comment by kit-ty-kate** [comment]
Sounds like `alt-ergo < 2.3.0` and `alt-ergo-free` are incompatible with this version of camlzip. Could you add the appropriate constraints to those packages in this PR if you have some time? Otherwise I'll do it later.

**Comment by xavierleroy** [comment]
I'm not comfortable with editing a bunch of packages to add version constraints: I'm sure there are tools to help with this but I don't know them.  It would be very appreciated if someone more familiar with these tools could edit the alt-ergo packages.

**Comment by mseri** [comment]
Thanks and sorry for the delay. I can deal with alt-ergo later

**Pull request merged**
