### PR TITLE
github: restrict deps to < 3.0 for findlib package name changes

### PR DESCRIPTION
**Pull request by dsheets**
Due to mirage/ocaml-github#192, the findlib package names will be changing.

/cc @AltGr @avsm @samoht

### CODE REVIEW

**Comment by avsm** [comment]
see https://github.com/moby/datakit/issues/554 for datakit-github-bridge failure on mtime.os

**Comment by dsheets** [comment]
I've rebased this PR and restarted the CI and the same datakit-bridge-github `mtime.os` failures keep happening. I'm not sure what else to do or why the CI is still failing.

**Comment by samoht** [comment]
Seems that there is a missing `"mtime" {< "1.0.0"}` constraint in datakit-github-birdge 0.10.1

**Comment by samoht** [comment]
The revdep is fixed by #9221

**Pull request merged**
