### PR TITLE
[new release] docker-api (0.2)

### PR DESCRIPTION
**Pull request by Chris00**
Binding to the Docker Remote API

- Project page: <a href="https://github.com/Chris00/ocaml-docker">https://github.com/Chris00/ocaml-docker</a>
- Documentation: <a href="https://Chris00.github.io/ocaml-docker/doc">https://Chris00.github.io/ocaml-docker/doc</a>

##### CHANGES:

- Upgrade to API v1.29.
- New signature of `Container.create`.
- Add functions `Container.wait` and `Container.changes`.
- Handle errors `409 Conflict`.
- New exceptions `Docker.Failure` and `Docker.No_such_container`.
- New tests `ls` and `ps`.
- Use [Dune](https://github.com/ocaml/dune) and
  [dune-release](https://github.com/samoht/dune-release).

### CODE REVIEW

**Comment by Chris00** [comment]
To run the tests, some images must be installed — they are not by default on Travis.

**Comment by kit-ty-kate** [comment]
Could you disable the tests then ? Or part of them maybe. I don't know what's the best way of doing this.

**Comment by Chris00** [comment]
> Could you disable the tests then ? Or part of them maybe. I don't know what's the best way of doing this.

That will have to wait.

**Comment by kit-ty-kate** [comment]
Closing this. Please feel free to reopen it.

**Comment by Chris00** [comment]
See https://github.com/ocaml/opam-repository/pull/12786

**Pull request closed without merging**
