### PR TITLE
mlcuddidl.3.0.6

### PR DESCRIPTION
**Pull request by nberth**
Supports OCaml 4.10

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by kit-ty-kate** [comment]
Mh actually I just tried it and it fails on OCaml 4.10:
```
#=== ERROR while compiling mlcuddidl.3.0.6 ====================================#
# context     2.0.6 | linux/x86_64 | ocaml-variants.4.10.0+trunk | git://github.com/ocaml/opam-repository.git
# path        ~/.opam/4.10/.opam-switch/build/mlcuddidl.3.0.6
# command     /usr/bin/make -j4
# exit-code   2
# env-file    ~/.opam/log/mlcuddidl-3044-58a9f1.env
# output-file ~/.opam/log/mlcuddidl-3044-58a9f1.out
### output ###
# [...]
# --------------------------------------------------
# /home/kit_ty_kate/.opam/4.10/bin/ocamlopt.opt -I cudd-3.0.0 -I cudd-3.0.0/st -I cudd-3.0.0/mtr -I cudd-3.0.0/epd -I cudd-3.0.0/util -I cudd-3.0.0/cudd -I cuddsrc-dbug -I /home/kit_ty_kate/.opam/4.10/lib/ocaml -I /home/kit_ty_kate/.opam/4.10/lib/camlidl -g -ccopt "-fPIC -O0 -g -DDD_CACHE_PROFILE -DDD_UNIQUE_PROFILE -DDD_VERBOSE -DDD_DEBUG -DDD_STATS -DDD_COUNT -DMTR_DEBUG -w -o cuddauxAddCamlT[...]
# /home/kit_ty_kate/.opam/4.10/bin/ocamlopt.opt -I cudd-3.0.0 -I cudd-3.0.0/st -I cudd-3.0.0/mtr -I cudd-3.0.0/epd -I cudd-3.0.0/util -I cudd-3.0.0/cudd -I cuddsrc-dbug -I /home/kit_ty_kate/.opam/4.10/lib/ocaml -I /home/kit_ty_kate/.opam/4.10/lib/camlidl -g -ccopt "-fPIC -O0 -g -DDD_CACHE_PROFILE -DDD_UNIQUE_PROFILE -DDD_VERBOSE -DDD_DEBUG -DDD_STATS -DDD_COUNT -DMTR_DEBUG -w -o cuddauxUtil.d.o[...]
# /home/kit_ty_kate/.opam/4.10/bin/ocamlopt.opt -I cudd-3.0.0 -I cudd-3.0.0/st -I cudd-3.0.0/mtr -I cudd-3.0.0/epd -I cudd-3.0.0/util -I cudd-3.0.0/cudd -I cuddsrc-dbug -I /home/kit_ty_kate/.opam/4.10/lib/ocaml -I /home/kit_ty_kate/.opam/4.10/lib/camlidl -g -ccopt "-fPIC -O0 -g -DDD_CACHE_PROFILE -DDD_UNIQUE_PROFILE -DDD_VERBOSE -DDD_DEBUG -DDD_STATS -DDD_COUNT -DMTR_DEBUG -w -o cuddauxAddIte.d[...]
# /home/kit_ty_kate/.opam/4.10/bin/ocamlopt.opt -I cudd-3.0.0 -I cudd-3.0.0/st -I cudd-3.0.0/mtr -I cudd-3.0.0/epd -I cudd-3.0.0/util -I cudd-3.0.0/cudd -I cuddsrc-dbug -I /home/kit_ty_kate/.opam/4.10/lib/ocaml -I /home/kit_ty_kate/.opam/4.10/lib/camlidl -g -ccopt "-fPIC -O0 -g -DDD_CACHE_PROFILE -DDD_UNIQUE_PROFILE -DDD_VERBOSE -DDD_DEBUG -DDD_STATS -DDD_COUNT -DMTR_DEBUG -w -o cuddauxAddApply[...]
# cuddauxAddCamlTable.c: In function ‘Cuddaux_addCamlConst’:
# cuddauxAddCamlTable.c:102:25: error: ‘caml_stat_compactions’ undeclared (first use in this function)
#   102 |       old_compactions = caml_stat_compactions;
#       |                         ^~~~~~~~~~~~~~~~~~~~~
# cuddauxAddCamlTable.c:102:25: note: each undeclared identifier is reported only once for each function it appears in
# make: *** [Makefile:298: cuddauxAddCamlTable.d.o] Error 2
# make: *** Waiting for unfinished jobs....
```
It might have something to do with the changes between beta1 and beta2

**Comment by kit-ty-kate** [comment]
I reverted your PR, could you fix this and submit another one? Sorry for not catching it earlier

**Comment by nberth** [comment]
@kit-ty-kate Yes indeed trunk has changed again since then, so I'll hold on that until things stabilise in 4.10. Thanks for catching that.

**Pull request merged**
