### PR TITLE
[new release] hpack, h2-mirage, h2-lwt, h2 and h2-lwt-unix (0.1.0)

### PR DESCRIPTION
**Pull request by anmonteiro**
### hpack

An HPACK (Header Compression for HTTP/2) implementation in OCaml

### h2

An HTTP/2 implementation in OCaml

- Project page: <a href="https://github.com/anmonteiro/ocaml-h2">https://github.com/anmonteiro/ocaml-h2</a>

##### CHANGES:

- Initial public release

### CODE REVIEW

**Comment by mseri** [comment]
Before moving on with the merge, can you please clarify `hpack` situation with https://discuss.ocaml.org/t/ann-h2-an-http-2-implementation-for-ocaml/3578/3 ?

**Comment by anmonteiro** [comment]
@mseri That was an oversight on my part. I'm fixing the situation now.

**Comment by avsm** [comment]
Have there been substantial changes to @314eter's hpack code?  If not, it would be good to ensure that it is acceptable for that to be bundled as part of h2, or if he prefers to develop it independently.  Also, the 'author' field in the hpack should reflect the source code author. 

 (From opam's perspective, we'd love to see collaboration of course!)

**Comment by anmonteiro** [comment]
I adapted @314eter's original work and made substantial changes to it. I'd be happy to find a way to collaborate and give credit where credit is due.

**Comment by anmonteiro** [comment]
Pushed a new commit rectifying the situation. Apologies again for the trouble.

**Comment by 314eter** [comment]
I'm happy with anything that respects the license, and that's fixed now.

The substantial changes are extra comments and documentation and rewrites of some parts of the code, which are great enhancements, but don't really change the functionality or the interface. So there's no use keeping them both maintained. I think a separate hpack library could be useful in other http2 implementations in the future, which is a possible reason to keep it in its own repository, but if you prefer to keep everything together that's fine with me too, and then I'll archive mine.

**Comment by avsm** [comment]
If it's helpful, we can move h2 to the mirage/ organisation and give you both write access to the repo, as a shared collaboration area.

**Comment by mseri** [comment]
@anmonteiro and @314eter thanks both for your works, and for the help and reponsiveness in dealing with this matter. I think a move to `mirage` can be planned and made in the future if you want it, without the need to stop this PR to be merged at this point.

Let me know if you prefer to discuss it before I merge, otherwise I think we can go on and merge this PR

**Comment by anmonteiro** [comment]
I think this is good to merge on my end. We can discuss future plans later.

**Comment by 314eter** [comment]
I have thought about it some more, and I would prefer to keep hpack separate from h2. It's of course no problem if you want to keep using your own fork in h2, but that's still possible if there's another version on opam.

I had some unpublished bugfixes and a partial fuzzer that I didn't push to github yet. My initial plan was to do a PR for h2, but after reviewing the code I decided that I don't agree with all the changes, and I'm not sure they don't introduce new bugs.

I finished the things I was still working on and fixed some bugs, and I think [ocaml-hpack](https://github.com/314eter/ocaml-hpack) is stable enough for release now.

**Comment by anmonteiro** [comment]
@314eter that's fine for me, but if you're going to publish a version that's different from mine there's a name conflict in OPAM. 

Would you like to talk about this somewhere else? How would you like me to reach you?

**Pull request merged**
