### PR TITLE
[new release] sihl-email, sihl-queue, sihl-storage and sihl (0.1.5)

### PR DESCRIPTION
**Pull request by jerben**
A Sihl service for sending emails using Lwt

- Project page: <a href="https://github.com/oxidizing/sihl">https://github.com/oxidizing/sihl</a>
- Documentation: <a href="https://oxidizing.github.io/sihl/">https://oxidizing.github.io/sihl/</a>

### Fixed
- Remove seed service since the same functionality
- Simplify app abstraction, instead of `with_` use service APIs directly
- Extract storage service as `sihl-storage` opam package
- Extract email service as `sihl-email` opam package
- Extract queue service as `sihl-queue` opam package
- Move configuration and logging into core, neither of the are implemented as services
- Replace `pcre` with `re` as regex library to get rid of a system dependency on pcre
- Split up `Sihl.Data` into `Sihl.Migration`, `Sihl.Repository` and `Sihl.Database`
- Move module signatures from `Foo.Service.Sig` to `Foo.Sig`, the services might live in a third party opam package, but the signatures are staying in `sihl`
- Move `Sihl.App` to `Sihl.Core.App` and simplify app API
- Move log service, config service and cmd service into core (they don't have to be provided to other services through functors)
- Simplify Sihl app creation and service configuration

### Fixed
- Remove `reason` and `tyxml-jsx` as dependency as they are not used anymore

### Added
- Various combinators for `Sihl.Seed.t` including constructor and field accessors

### Added
- Seed Service with commands `seedlist` and `seedrun <name>`

### Fixed
- Lifecycle API: A service now has two additional functions `start` and `stop`, which are used in the lifecycle definition
- Database service query functions `query`, `atomic` and `with_connection` can now be nested

### Fixed
- Re-export `Sihl.Queue.Job.t`
- Export content types under `Sihl.Web`

### Fixed
- Don't raise exception when user login fails if it is a user error
- Remove dev tools as dev dependencies

### Added
- Storage service can remove files
- Move README.md documentation to ocamldoc based documentation

### Fixed
- DB connection leaks caused deadlocks
- Provide all service dependencies using functors
- Move Opium & Cohttp specific stuff into the web server service implementation to allow for swappable implementation based on something like httpaf
- Inject log service to all other services by default

### Added
- Support letters 0.2.0 for SMTP emailing
- Switch to exception based service API
- HTTP Response API to respond with file `Sihl.Web.Res.file`

### Fixed
- Stop running integration tests during OPAM release

### Added
- Initial release of Sihl

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I believe you need to add `(package sihl)` to the `(test ..)` stanzas to make it only run for the `sihl` package and not for the subpackages.
```
#=== ERROR while compiling sihl-email.0.1.5 ===================================#
# context     2.0.6 | freebsd/x86_64 | ocaml-base-compiler.4.09.1 | file:///usr/home/travis/build/ocaml/opam-repository
# path        /usr/home/travis/.opam/ocaml-base-compiler.4.09.1/.opam-switch/build/sihl-email.0.1.5
# command     /usr/home/travis/.opam/ocaml-base-compiler.4.09.1/bin/dune build -p sihl-email -j 1 @install @runtest
# exit-code   1
# env-file    /usr/home/travis/.opam/log/sihl-email-37803-05296d.env
# output-file /usr/home/travis/.opam/log/sihl-email-37803-05296d.out
### output ###
# File "test/sihl/dune", line 3, characters 26-38:
# 3 |  (libraries sihl alcotest alcotest-lwt))
#                               ^^^^^^^^^^^^
# Error: Library "alcotest-lwt" not found.
# Hint: try:
#   dune external-lib-deps --missing -p sihl-email -j 1 @install @runtest
```

**Comment by jerben** [comment]
@kit-ty-kate Thanks for the feedback. I added `(package sihl)` to the test stanzas.

**Comment by mseri** [comment]
Failures were all due to network issues. I have rerun a few and they all succeeded. Thanks!

**Comment by jerben** [comment]
Thanks!

**Pull request merged**
