### PR TITLE
added packages/camltc/camltc.0.9.7.0

### PR DESCRIPTION
**Pull request by UnixJunkie**
this one tries to get rid of the git submodule so that the build of the package is more reproducible

### CODE REVIEW

**Comment by UnixJunkie** [comment]
probably it is for tests only, I made the change

**Comment by kit-ty-kate** [comment]
It apparently is not :/

Also, please can you make the requested change https://github.com/ocaml/opam-repository/pull/12365#issuecomment-407030724 ?! Not that I'm getting a bit pissed but I am... 🙃

**Comment by UnixJunkie** [comment]
I removed the test flag for ounit.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
