### PR TITLE
Fixed LIRARY_PATH and C_INCLUDE_PATH handling and path ordering.

### PR DESCRIPTION
**Pull request by Ninjapouet**
Allows to support cross-compilation a bit more.

The previous version messed up include directories by using an internal hash table to ensure uniqueness. Uniqueness on include paths is smart but unnecessary while keeping paths order is _mandatory_. Furthermore, the doc tells to set C_INTERNAL_PATH with something like /opt/include but it doesn't work with the previous search algorithm for it adds automatically the include directory, leading to always wrong custom C_INCLUDE_PATH or LIBRARY_PATH and forcing the use of system library. This prevents using custom paths and thus cross-compiling correctly.

### CODE REVIEW

**Comment by hcarty** [comment]
@aantron If you have time, could you please take a look at this? I'm not familiar enough with libev to tell if this will cause regressions for currently supported platforms.

**Comment by aantron** [comment]
Not reordering the paths seems right.

The other issue seems misdiagnosed, but I'm not fully sure. The old code first cuts off the last component of the path before appending `/include`, so it should still get the right paths. In other words, the old code is working with installation prefixes as long as possible. This is likely why it has "`uniq`" to begin with. 

It seems like the easiest way to fix this while preventing doubts about obscure platforms would be to either just not call `uniq` (which might result in more fs access, I have no idea if that's really a problem), or change `uniq` to preserve the order by filtering the list using the hash table instead of building a fresh one from the hash table. 

This is all by reading code instead of trying it, so could be really wrong.

**Comment by Ninjapouet** [comment]
Retested and yes, the include management isn't a issue. I previously had a trace like showing a result with /opt/include/include but I can't reproduce it manually so it was probably a build artifact.

**Comment by kit-ty-kate** [comment]
The target branch (`2.0.0`) has diverged from this PR. Could you rebase your change over it ?
Is there a reason why this PR was only made over this branch and not `master` ?

I don't understand anything about this package so I'm willing to trust anybody who would tell me this is good to merge (once the conflicts are resolved and/or switched on master).

**Comment by aantron** [comment]
@kit-by-kate From my incomplete point of view, the status of this PR is that it makes two changes, of which one is needed (1) and the other is unnecessary and based on a misconception (2), and it is best to rework it to make only (1), and to make (1) in a simpler way.

**Comment by kit-ty-kate** [comment]
@aantron thanks :)

**Comment by kit-ty-kate** [comment]
I'm going to close this PR. Feel free to open another one against the master branch

**Pull request closed without merging**
