### PR TITLE
new release: ocaml-freestanding 0.6.7 (support for OCaml 4.14, floating point fix for xen/qubes)

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
the lower bounds issues of solo5-bindings-hvt are due to incompatibility with gcc>10, and should be ignored (are unrelated to this release).

**Comment by hannesm** [comment]
An issue may be (won't fix in this PR):
```
#=== ERROR while compiling hacl_x25519.0.2.2 ==================================#
# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.14.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/hacl_x25519.0.2.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p hacl_x25519 -j 31 @install
# exit-code            1
# env-file             ~/.opam/log/hacl_x25519-19-d594bd.env
# output-file          ~/.opam/log/hacl_x25519-19-d594bd.out
### output ###
# (cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.hacl_x25519.objs/byte -I /home/opam/.opam/4.14/lib/bigarray-compat -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/eqaf -intf-suffix .ml -no-alias-deps -o src/.hacl_x25519.objs/byte/hacl_ed25519.cmo -c -impl src/hacl_ed25519.ml)
# File "src/hacl_ed25519.ml", line 8, characters 5-16:
# 8 |   if Cstruct.len cs = key_length_bytes then `Checked cs
#          ^^^^^^^^^^^
# Alert deprecated: Cstruct.len
# len is deprecated, you should use length instead.
# File "src/hacl_ed25519.ml", line 37, characters 53-64:
# 37 |     (checked_buffer priv) (Cstruct.to_bigarray msg) (Cstruct.len msg);
#                                                           ^^^^^^^^^^^
# Alert deprecated: Cstruct.len
# len is deprecated, you should use length instead.
# File "src/hacl_ed25519.ml", line 42, characters 5-16:
# 42 |     (Cstruct.len msg)
#           ^^^^^^^^^^^
# Alert deprecated: Cstruct.len
# len is deprecated, you should use length instead.
# File "freestanding/dune", line 3, characters 0-193:
#  3 | (rule
#  4 |  (deps Makefile hacl_x25519_stubs.c Hacl_Hash.c Hacl_Curve25519_51.c
#  5 |    Hacl_Ed25519.c)
#  6 |  (targets libhacl_x25519_freestanding_stubs.a)
#  7 |  (action
#  8 |   (no-infer
#  9 |    (progn
# 10 |     (run %{make})))))
# (cd _build/default/freestanding && /usr/bin/gmake)
# cc -O3 -I../src/kremlin/include -I../src/kremlin/kremlib/dist/minimal -I../src -DKRML_HOST_TIME -include _freestanding/overrides.h -ffreestanding -fstack-protector-strong -nostdinc -mstack-protector-guard=global -I/home/opam/.opam/4.14/lib/pkgconfig/../../include/ocaml-freestanding -isystem /home/opam/.opam/4.14/lib/pkgconfig/../../include/solo5-bindings-xen/crt -I/home/opam/.opam/4.14/lib/pkgconfig/../../include/solo5-bindings-xen/solo5   -c -o hacl_x25519_stubs.o hacl_x25519_stubs.c
# In file included from src/hacl_x25519_stubs.c:4:
# ../src/Hacl_Curve25519_51.h:26:10: fatal error: kremlin/internal/types.h: No such file or directory
#    26 | #include "kremlin/internal/types.h"
#       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
# compilation terminated.
```

But this is again unrelated to this release (also, hacl_x25519 is not maintained anymore),only used by arcane releases, and the issue may be related to "dune 3.x".

**Comment by hannesm** [comment]
the mirage-block-solo5 issue is fixed by #21105

**Comment by hannesm** [comment]
looks fine to be merged.

**Comment by dinosaure** [comment]
Thanks! Something seems wrong with `checkseum` but I will try to see where is the error.

**Pull request merged**
