### PR TITLE
ocaml-planet.0.1.1 - via opam-publish

### PR DESCRIPTION
**Pull request by kayceesrk**
A planet (feed aggregator) in OCaml.

A library for aggregating RSS2 and Atom feeds in OCaml.

Features:

* Performs deduplication.
* Supports pagination and generating well-formed html prefix snippets.
* Support for generating aggregate feeds.
* Sorts the posts from most recent to oldest.
* Depends on ocamlnet for html parsing.

---
* Homepage: https://github.com/kayceesrk/ocaml-planet
* Source repo: https://github.com/kayceesrk/ocaml-planet.git
* Bug tracker: https://github.com/kayceesrk/ocaml-planet/issues

---
Pull-request generated by opam-publish v0.2.1

### CODE REVIEW

**Comment by samoht** [comment]
> `packages/ocaml-planet/ocaml-planet.0.1.1/descr`

The current policy is to remove any `ocaml-` prefix from package names as the repository only contains `ocaml` project.

**Comment by kayceesrk** [comment]
What's the best way to go about it? Should I delete ocaml-planet and submit a new one? Apart from ocaml.io, we don't have any external users at this moment.

**Comment by samoht** [comment]
yup, creating a new PR to rename the package would be good. Thanks!

**Comment by avsm** [comment]
yep, fixing up ocaml.io isnt an issue.

**Comment by amirmc** [comment]
Isn't there a package called planets already? I wonder about user error here. 

Best wishes,
Amir

--
sent via mobile

**Comment by amirmc** [comment]
https://opam.ocaml.org/packages/planets/planets.0.1.14/

**Comment by kayceesrk** [comment]
How about "river" from "river-of-news". opam doesn't have a package with that name.

**Comment by avsm** [comment]
I like River!

**Comment by samoht** [comment]
good name :-)

**Comment by dbuenzli** [comment]
Le vendredi, 20 mars 2015 à 17:08, Anil Madhavapeddy a écrit :
> I like River!

This makes it a possibility that there is life on your planet.  

Daniel

**Comment by amirmc** [comment]
Great idea!  Rename it!

**Comment by kayceesrk** [comment]
Thanks all. :-) I'll make the changes over this weekend.

**Pull request merged**
