### PR TITLE
Add mlmpfr 4.1.1 release

### PR DESCRIPTION
**Pull request by thvnx**

### CODE REVIEW

**Comment by mseri** [comment]
Tests seem to be failing everywhere with a rather useless output:
```

#=== ERROR while compiling mlmpfr.4.1.1 =======================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.0 | pinned(https://github.com/thvnx/mlmpfr/archive/refs/tags/mlmpfr.4.1.1.tar.gz)
# path                 ~/.opam/4.14/.opam-switch/build/mlmpfr.4.1.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build ./mlmpfr_compatibility_test
# exit-code            1
# env-file             ~/.opam/log/mlmpfr-7-9187d8.env
# output-file          ~/.opam/log/mlmpfr-7-9187d8.out
```

**Comment by mseri** [comment]
We faced the same situation with all previous versions. I don't think this is worse off so I suggest merging, I have started a PR to try and improve compatibility with other distributions

**Comment by thvnx** [comment]
Hi @mseri , agree, and yes, this is the same story, again. This version of mlmpfr should be only used with the new  4.1.1 release of the C mpfr library, which is not packaged by default on the various environment the CI is run. It shouldn't break anything, they were no fundamental changes since 4.1.0.

Note that it can wait, I don't have much time at the moment to improve things further (I didn't have time to check you PR yet by the way, but thank you for that !).

**Comment by kit-ty-kate** [comment]
Thanks. Sorry for the wait

**Pull request merged**
