### PR TITLE
Add Ubuntu depext to orocksdb

### PR DESCRIPTION
**Pull request by aantron**
cc @domsj

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Could you also add the debian depext ? (https://packages.debian.org/stretch/librocksdb-dev)

I think it is worth putting it into a separate ```conf-rocksdb``` package as well if you have time to do it.

**Comment by aantron** [comment]
@jpdeplaix I added the Debian depext.

I do have time to create a `conf-rocksdb` package in principle, but I prefer to defer to @domsj or someone else with expertise with RocksDB and an interest in maintaining the package. I was only going down a big list of packages to install for bulk processing purposes, and adding missing depexts for the sake of thoroughness.

I can still do it if others really have no time, however :)

**Comment by domsj** [comment]
I'm not really into packaging, so whatever you think is best is fine for me...
All patches/PRs are welcome :stuck_out_tongue_winking_eye:.

**Comment by aantron** [comment]
Alright, I'll replace the commit in this PR with one that adds a `conf-rocksdb`.

**Comment by aantron** [comment]
Ok, hopefully that's right.

RocksDB doesn't seem to make itself known to `pkg-config`, so I didn't include a script inside `conf-rocksdb` to check for the actual presence of RocksDB. I don't know if that's acceptable for a `conf-*` package. If not, I can restore the previous commits to this PR.

**Comment by jpdeplaix** [comment]
Mmh I think that's ok but one thing that could be done instead in to have an "empty" C file:
```c
int main() {}
```
and to try to compile it like this: ```cc -lrocksdb test.c```. If it fails, it is unlikely to be installed on the system.
Poke @engil

**Comment by aantron** [comment]
I added the check (I think, because I don't have an opam repository set up locally to test the whole package from). However, the test itself works (it succeeds iff RocksDB is installed).

**Comment by jpdeplaix** [comment]
It seems good enough for now at least. Thanks again !

**Pull request merged**
