### PR TITLE
minilight.1.6 - via opam-publish

### PR DESCRIPTION
**Pull request by AltGr**
Minimal global illumination renderer.

MiniLight is a minimal global illumination renderer. It is primarily an exercise
in simplicity. But that makes it a good base and benchmark (in some sense) for
development and experimentation. And it just might be the neatest renderer
around (on average, about 650 lines). There are translations into several
programming languages.

---
* Homepage: http://www.hxa.name/minilight
* Source repo: 
* Bug tracker: 

---
### opam-lint failures
- **WARNING** 37 Missing field 'dev-repo'
- **WARNING** 36 Missing field 'bug-reports'

---

Pull-request generated by opam-publish v0.3.0

### CODE REVIEW

**Comment by avsm** [comment]
```
===== ERROR while installing minilight.1.6 =====
# opam-version 1.1.2-rc3
# os           linux
# command      ocamlopt.opt -verbose -unsafe -nodynlink -inline 100 -ffast-math -I ocaml/src -o minilight-ocaml unix.cmxa ocaml/src/random2.ml ocaml/src/vector3f.ml ocaml/src/triangle.ml ocaml/src/spatialIndex.mli ocaml/src/spatialIndex.ml ocaml/src/scene.ml ocaml/src/surfacePoint.ml ocaml/src/rayTracer.ml ocaml/src/image.ml ocaml/src/camera.ml ocaml/src/minilight.ml
# path         /home/travis/.opam/4.02.3/build/minilight.1.6
# compiler     4.02.3
# exit-code    2
# env-file     /home/travis/.opam/4.02.3/build/minilight.1.6/minilight-14860-d2d111.env
# stdout-file  /home/travis/.opam/4.02.3/build/minilight.1.6/minilight-14860-d2d111.out
# stderr-file  /home/travis/.opam/4.02.3/build/minilight.1.6/minilight-14860-d2d111.err
### stderr ###
# ...[truncated]
#   -dprefer  (undocumented)
#   -dalloc  (undocumented)
#   -dreload  (undocumented)
#   -dscheduling  (undocumented)
#   -dlinear  (undocumented)
#   -dstartup  (undocumented)
#   -opaque  Does not generate cross-module optimization information
#      (reduces necessary recompilation on module change)
#   -help  Display this list of options
#   --help  Display this list of options
'opam install minilight.1.6' failed.
```

https://travis-ci.org/ocaml/opam-repository/jobs/79797873

**Comment by AltGr** [comment]
hm, it seems that's due to the `{arch = "i386"}` filter being unsupported in 1.1.
the rewriting script assumes the condition is true in that case, which is wrong -- but there is no perfect answer, as it could also break the other way around (ie not compile on i386 without the switch).

Anyway, it's easy to fix in this case, but this re-raises the "deprecating 1.1" debate :)

**Comment by AltGr** [comment]
This should be fixed by https://github.com/ocaml/opam/pull/2303, once the fixed rewrite script gets live.

**Comment by avsm** [comment]
@AltGr do you have any mechanism to check the number of hits on opam.ocamlpro.com (the old site) and opam.ocaml.org/1.1 and see if they are significant beyond Travis?

**Comment by samoht** [comment]
I've restarted Travis on 1.1 to see if the rewrite now works better.

**Comment by samoht** [comment]
@AltGr Not sure that your fix is the right one, see:

```
===== ERROR while installing minilight.1.6 =====
# opam-version 1.1.2-rc3
# os           linux
# command      ocamlopt.opt -verbose -unsafe -nodynlink -inline 100 -ffast-math -I ocaml/src -o minilight-ocaml unix.cmxa ocaml/src/random2.ml ocaml/src/vector3f.ml ocaml/src/triangle.ml ocaml/src/spatialIndex.mli ocaml/src/spatialIndex.ml ocaml/src/scene.ml ocaml/src/surfacePoint.ml ocaml/src/rayTracer.ml ocaml/src/image.ml ocaml/src/camera.ml ocaml/src/minilight.ml
# path         /home/travis/.opam/4.02.3/build/minilight.1.6
# compiler     4.02.3
# exit-code    2
# env-file     /home/travis/.opam/4.02.3/build/minilight.1.6/minilight-14860-d2d111.env
# stdout-file  /home/travis/.opam/4.02.3/build/minilight.1.6/minilight-14860-d2d111.out
# stderr-file  /home/travis/.opam/4.02.3/build/minilight.1.6/minilight-14860-d2d111.err
### stderr ###
# ...[truncated]
#   -dprefer  (undocumented)
#   -dalloc  (undocumented)
#   -dreload  (undocumented)
#   -dscheduling  (undocumented)
#   -dlinear  (undocumented)
#   -dstartup  (undocumented)
#   -opaque  Does not generate cross-module optimization information
#      (reduces necessary recompilation on module change)
#   -help  Display this list of options
#   --help  Display this list of options
'opam install minilight.1.6' failed.
```

**Comment by AltGr** [comment]
Yes, https://github.com/ocaml/opam/pull/2303 wasn't merged yet.

**Comment by AltGr** [comment]
@avsm: from quick grepping through the server logs for hits to `urls.txt`:

* overall: `/1.1/urls.txt` 19261 against `/urls.txt` 411384
* last 6 months: `/1.1/urls.txt` 5336 against `/urls.txt` 168036
* last month: `/1.1/urls.txt`  368 against `/urls.txt` 29708

So it's down from 3% to 1% of hits between the last two.

**Comment by AltGr** [comment]
Relevant commit merged (but the updated rewrite script will only get live tomorrow)

**Comment by avsm** [comment]
It does seem to be quite low now.  How about turning off the URL experimentally for a few days and see if anyone complains?

**Pull request merged**
