### PR TITLE
make parmap depend on conf-autoconf

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
all green in travis and camelus now

**Comment by dbuenzli** [comment]
> all green in travis and camelus now

@UnixJunkie AFAIK opam's maintainers are not color blind. Please avoid generating useless notifications.

**Comment by UnixJunkie** [comment]
I was trying to help triaging the pull requests. If my help doesn't help, then I can stop doing it.

**Comment by UnixJunkie** [comment]
And when I say it's all green, I actually went to look at some of the travis logs. Because sometimes it's green in travis but the package never installed (for example because it has too many constraints/dependencies).

**Comment by dbuenzli** [comment]
> I was trying to help triaging the pull requests. If my help doesn't help, then I can stop doing it.

I don't know but as a repository watcher I find it annoying as it generate on more notification. The maintainers do have the PR dashboard to glance over greenness so I don't think it's worth adding more notifications here.

**Comment by avsm** [comment]
> I was trying to help triaging the pull requests. If my help doesn't help, then I can stop doing it.

I find these notifications quite useful, since Travis doesnt send a message when it successfully finishes.  There's absolutely no harm in a note from a package submitter saying that they believe that a PR is ready to merge since it passes CI, especially since it sometimes takes multiple pushes to get it right.

**Comment by dbuenzli** [comment]
> I find these notifications quite useful, since Travis doesnt send a message when it successfully finishes. There's absolutely no harm in a note from a package submitter saying that they believe that a PR is ready to merge since it passes CI, especially since it sometimes takes multiple pushes to get it right.

I find this very noisy, and I'm considering removing myself from watching this repository. If we follow this pattern we get at minimum of 4 notification per package addition:

1. The initial PR
2. Camelus
3. The PR person says it's all green
4. The merge notification

wouldn't it be possible to change this so that Camelus reports directly only if it fails and otherwise once travis succeded or failed ?

**Comment by dsheets** [comment]
Opened AltGr/Camelus#9.

**Pull request merged**
