### PR TITLE
Support ndbm, bugfix for omake

### PR DESCRIPTION
**Pull request by madroach**
These are two small changes I carried for some time in my local repository.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
mmh can you explain your patch for omake? Also I wonder why it works without stating the patch in the `extra-files` field

The ndbm support seems fine indeed tho

**Comment by mseri** [comment]
I think the osx failure is related to an issue with the version of openssl shipped with it and the supported hashes. We have seen it in many different packages. Can you try replacing the url checksum with md5 and see if it resolves the issue?

**Comment by madroach** [comment]
I added the _optional_ ``extra-files:`` field.

As to why the patch is needed:
```
*** omake error:
   File lib/build/OCaml.om: line 184, characters 4-31
   Array value where string expected:
      Use the $(string ...) function if you really want to do this
      The array has length 3:
         [0] = <data "cc"> : String
         [1] = <data "-O2"> : String
         [2] = <data "-pipe"> : String
```

**Comment by madroach** [comment]
I added another commit adding a ``with-doc`` build-dep to sequence. Or is this supposed to be filtered ``{build with-doc}`` ?
Please feel free to cherry-pick any of the commits I added to this branch.

**Comment by UnixJunkie** [comment]
@madroach just FYI, you might be interested by the dokeysto package in opam

**Comment by kit-ty-kate** [comment]
Sorry I neglected this PR. Merging

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by MdeLv** [comment]
Hi, 
can you have a look at [ conf-dbm triggers false "upstream changes" #16308 ](https://github.com/ocaml/opam-repository/issues/16308#issue-608433728)?
The issue seems related to this merge: [https://github.com/ocaml/opam-repository/commit/9ecbe4e1cb23338275ab0b394ce278c63ba4d1c7](https://github.com/ocaml/opam-repository/commit/9ecbe4e1cb23338275ab0b394ce278c63ba4d1c7).

Thanks.

**Pull request merged**
