### PR TITLE
conf-ncurses: Do not depend on `conf-pkg-config` when not required

### PR DESCRIPTION
**Pull request by OCamlPro-Henry**
This is a fix for:

  https://github.com/ocaml/opam-repository/issues/5880#issuecomment-193480687

### CODE REVIEW

**Comment by dsheets** [comment]
Fails on opam 1.2.0 (and only 1.2.0) with:

```
[ERROR] At ~/.opam/repo/default/packages/conf-ncurses/conf-ncurses.1/opam:11:25:
  Expected a list of constraints
```

which we discussed at <https://github.com/ocaml/opam-repository/pull/5837#discussion_r54594712>.

**Comment by dsheets** [comment]
Oh, perhaps it causes issues for other versions and they just fail to fail per <https://github.com/ocaml/opam-repository/issues/5880#issuecomment-193497399>.

**Comment by OCamlPro-Henry** [comment]
Ouch! I made the same mistake twice in less than a week... 

I updated the patch for a better fix (I hope) : it introduce two versions of `conf-ncurses`. One available only on `BSD` (without dependency over `pkg-config`) and one only available on non-BSD.

**Comment by OCamlPro-Henry** [comment]
BTW, if this fix os OK, we should probably merge `ocamlfind-1.6.2` at the same time in order to avoid too many recompilation.

**Comment by hannesm** [comment]
before you merge, please verify that it works on the systems where you try to fix it... not only on MacOSX.. kthxbye

**Comment by avsm** [comment]
Would prefer if this wasnt called `-bsd` -- how about `-system` as we do with camlp4?

**Comment by avsm** [comment]
agreed re: combining with ocamlfind 1.6.2 merge

**Comment by OCamlPro-Henry** [comment]
@hannesm do you mean it needs further testing on various BSD ?

**Comment by OCamlPro-Henry** [comment]
@avsm Indeed, `+system` is more consistent. I will update the package.

**Comment by hannesm** [comment]
@OCamlPro-Henry what exactly do you mean by "further"? did you test it on any [Free|Net|Open]BSD?

**Comment by avsm** [comment]
i can test it on openbsd and freebsd, but not until tomorrow -- giving talks today

**Comment by OCamlPro-Henry** [comment]
@hannesm Ok 'further' was innapropriate in my sentence. I did not run test on any BSD. I only take care of preserving the existing constraints. I will wait for @avsm to test before merging.

**Comment by hannesm** [comment]
@OCamlPro-Henry good.  @avsm thanks.  Travis is not able to test on BSD, and since this modifies a central package for opam, I'd appreciate if it doesn't break on BSD.  Actually, opam on BSD without this PR is working fine.  (Keep in mind that while MacOSX is some sort of BSD, they imported a huge amount of the GNU toolchain which is not available on BSD.)  I don't have much time to test this this week due to travelling.

**Comment by OCamlPro-Henry** [comment]
@samoht I added `ocamlfind-1.6.2` in this PR. I only updated the `dev-repo` and `issues` fields to `gitlab.camlcity.org`.

**Comment by pirbo** [comment]
Can I insist on the fact that while you're waiting for someone checking that going from doing ```pkg-config --help``` to do nothing works on *BSD ... MacOS users cannot install ocamlfind?

**Comment by fdopen** [comment]
Your new solution is fine. It won't break any of the mentioned BSDs. `opam install ocamlfind` will install `conf-m4.1` and `conf-ncurses.1+system` , not `conf-pkg-config` (I've tested it and I've looked at the output of `ldd $(which ocamlrun)` and `find /lib* /usr -iname '*curse*'`)

Ncurses (or curses) are pre-installed (under usual configurations for developers) and pkg-config files are only provided for legacy or older versions in the ports tree (if at all), not the system versions that are used by default (If it is currently not broken for some bsd users, it's just good luck that they have an alternative version installed, so pkg-config won't complain).

**Comment by OCamlPro-Henry** [comment]
@fdopen thanks for the review ! That was my understanding, by I haven't got the chance to investigate and to confirm this idea.

@avsm any chance you test this today ? Or are you busy with the preparation of the Mirage hackathon ?

Anyway, with the review, I feel pretty confident and I would like to merge quickly. It is confirm that this fix the currently broken OS X port. And I see I don't see any reason for this patch not to fix the BSD port too.

**Comment by OCamlPro-Henry** [comment]
> I've tested it

Oh, I missread that part. So merging. Thanks again.

**Pull request merged**
