### PR TITLE
Fix various older iocaml version constraints.

### PR DESCRIPTION
**Pull request by andrewray**
* 0.4.7+ is >= 4.02 unless websocket has a change of heart.

* 0.4.6 is compatible with all ocaml versions >= 4.00.1.

* 0.3.1 has been removed.  it cannot install anymore because there is no working zmq3 package.

* version >= 0.4.2 <= 0.4.5 are compatible with ocaml 4.01 only

### CODE REVIEW

**Comment by andrewray** [comment]
I've made a mistake here.  iocaml-kernel.0.4.0 and iocaml.0.4.2 (which pair together) have a nonsensical constraint ```>= "4.01.0" & < "4.01.0"```.  However, this version wont compile for the same reason as I removed 0.3.1 - the zmq.3.2.-x series doesn't work, so enabling them will lead to a failure with all compiler versions anyway.  Not sure if we want to try and get this fixed, or just remove the packages.

The other error in the report is related to websocket.0.8.1.  It seems to require optcomp to compile, but it doesn't seem to be given as a dependency.

```
#=== ERROR while installing websocket.0.8.1 ===================================#
# opam-version 1.2.0
# os           linux
# command      make
# path         /home/andyman/.opam/4.01.0/build/websocket.0.8.1
# compiler     4.01.0
# exit-code    2
# env-file     /home/andyman/.opam/4.01.0/build/websocket.0.8.1/websocket-14128-6d07ae.env
# stdout-file  /home/andyman/.opam/4.01.0/build/websocket.0.8.1/websocket-14128-6d07ae.out
# stderr-file  /home/andyman/.opam/4.01.0/build/websocket.0.8.1/websocket-14128-6d07ae.err
### stdout ###
# ocaml setup.ml -configure 
### stderr ###
# ocamlfind: Package `optcomp' not found
# W: Field 'pkg_optcomp' is not set: Command ''/home/andyman/.opam/4.01.0/bin/ocamlfind' query -format %d optcomp > '/tmp/oasis-2968c0.txt'' terminated with error code 2
# E: Cannot find findlib package optcomp
# E: Failure("1 configuration error")
# make: *** [setup.data] Error 1
```

**Comment by andrewray** [comment]
After casting unfair aspersions on zmq.3.2-x, I now realise that it wont build because I have zmq4, not zmq3 on my system.  Looking the zmq opam files I think there's a reasonable chance travis will install zmq3, so this might well work.  I'll try relaxing the bad constraint on iocaml 0.4.2 once the websocket fix #3773 is live.

**Comment by avsm** [comment]
#3773 is now merged, so this can be rebased to try again.

**Comment by andrewray** [comment]
I think I've fought this hard enough to try and clean up obsolete stuff!  At some point everything seems to have worked (mostly - 4.01 tests tend to time out, though it passed once).  The only issue remaining is conduit doesn't compile and breaks v0.4.7 though I thought it had been fixed earlier and expected the last run to pick it up.  

It would be reassuring to see 0.4.7 pass, though I honestly think this is all working now (he says over confidently....).

**Comment by avsm** [comment]
That was rather a heroic fixing session -- I've fixed conduit and tested manually.

**Pull request merged**
