### PR TITLE
ucorelib: add v0.1.0 & v0.2.0, fix v0.0.1 & v0.0.2

### PR DESCRIPTION
**Pull request by nekketsuuu**
* add v0.1.0 and v0.2.0
* fix the opam file of v0.0.1 and v0.0.2
    * add some information
    * add the upper bound of available ocaml-version due to safe string

### CODE REVIEW

**Comment by nekketsuuu** [comment]
CI tests looks OK to me.
Travis failed due to a connection error, and datakit/4 failed due to another package.

**Comment by yomimono** [comment]
Is `ocamlfind` needed besides at build-time?  If you only need it for compilation, please tag it with `{build}` (as you've done for `ocamlbuild`).

Also, it looks like the `ounit` requirement is just for tests - you can tag the dependency with `{test}` to avoid users needing to install `ounit` if they just want to depend on `ucorelib` and are not interested in running its tests.

Other than those suggestions, this looks good :) Thanks for the updates to the old versions of `ucorelib`!

**Comment by nekketsuuu** [comment]
@yomimono Thanks for your advice. But it seems that adding `{build}`, `{test}`, or `{build & test}` breaks the build. I don't know why, so I leave the dependency flags unspecified.

Also, according to your advice, I add `build-test`, and it seems good. Thank you :+1:

**Comment by yomimono** [comment]
Thanks, @nekketsuuu ! Congratulations on the release. :)

**Pull request merged**
