### PR TITLE
igvxml.0.0.2 - via opam-publish

### PR DESCRIPTION
**Pull request by ihodes**
Create IGV session files from the command-line

---
* Homepage: https://github.com/hammerlab/igvxml
* Source repo: 
* Bug tracker: https://github.com/hammerlab/igvxml/issues

---
### opam-lint failures
- **WARNING** 37 Missing field 'dev-repo'
- **WARNING** 97 long description unspecified

---

Pull-request generated by opam-publish v0.3.2

### CODE REVIEW

**Comment by ihodes** [comment]
I'm curious about the deb-repo failure; I have a dev-repo specified in my opam file; should it be something else?

**Comment by dbuenzli** [comment]
> I have a dev-repo specified in my opam file

Where ?

**Comment by ihodes** [comment]
https://github.com/hammerlab/igvxml/commit/100df0f312f0c4e01e087f386e05203c94ee3665 

in this tag: https://github.com/hammerlab/igvxml/releases/tag/0.0.2 which is the one I believe I published (looking at my bash history and the archive URL seems to confirm this). I see in this PR the opam file does *not* have the dev-repo field; do you have any idea why this might be?

Regardless, I'm happy to get this into the opam repo and publish a new version later, if that works for you/whomever would approve this PR. 

Thanks!

**Comment by dbuenzli** [comment]
> do you have any idea why this might be?

Depends a bit on how you use opam-publish I think it may take the opam file that was previously in the repo I'm not sure as I'm not using the full workflow of opam-publish I only use `submit`. 

That said you should put a public url in your `dev-repo` so that other people can do `opam pin ivgxml --dev-repo`.

**Comment by yallop** [comment]
The build's [failing](https://travis-ci.org/ocaml/opam-repository/jobs/146693175):

```
### stdout ###
# ocamlfind install igvxml META\
# [...]
# 	    _build/igvxml.o\
# 	    _build/igvxml.cma\
# 	    _build/igvxml.cmi\
# 	    _build/igvxml.cmo\
# 	    _build/igvxml.cmx\
# 	    _build/igvxml.cmxa\
#             _build/igvxml.cmx\
# 	    _build/igvxml.cmxs\
# 	    _build/igvxml.cmt
### stderr ###
# ocamlfind: _build/igvxml.cmt: No such file or directory
# make: *** [install] Error 2
```

(And yes, please do add the `dev-repo` information to the `opam` file.)

**Comment by ihodes** [comment]
Super, I've opened a new PR here https://github.com/ocaml/opam-repository/pull/7049

Thank you for the review! 

Turns out opam-publish prepare generates its own opam file instead of using the one found in opam/, hence my earlier problems.

**Pull request closed without merging**
