### PR TITLE
Sawja 1.5.2 release

### PR DESCRIPTION
**Pull request by davidpichardie**

### CODE REVIEW

**Comment by davidpichardie** [comment]
Opam seems unable to find camlzip.1.05
I don't understand

**Comment by samoht** [comment]
It's a network connectivity issue, I'm restarting your builds.

**Comment by samoht** [comment]
ping @gildor478: the forge is down

**Comment by gildor478** [comment]
@samoht rebooted

**Comment by samoht** [comment]
Thanks, I've restarted the TravisCI jobs.

**Comment by davidpichardie** [comment]
Thanks for your help. Everything looks good now.

**Comment by davidpichardie** [comment]
Thanks !

**Pull request merged**
