### PR TITLE
Various fixes (lower-bound constraint checking edition)

### PR DESCRIPTION
**Pull request by kit-ty-kate**
cc @hannesm for `mirage-crypto`, `mirage-xen`
cc @pqwy for `nocrypto`
cc @pitag-ha for `ppxlib`

### CODE REVIEW

**Comment by mseri** [comment]
Fwiw, the lint can be ignored in this case, we could probably just make a mega commit fixing them all some times in the future. I think this can be merged

**Comment by avsm** [comment]
lgtm, and looks like @hannesm has pushed the mirage-crypto fixes back upstream

**Comment by pitag-ha** [comment]
Thanks for catching this, @kit-ty-kate! I've just opened a [PR](https://github.com/ocaml-ppx/ppxlib/pull/240) to upstream it to ppxlib.

**Comment by hannesm** [comment]
Thanks @kit-ty-kate, I upstreamed your fix to https://github.com/mirage/mirage-crypto/commit/fbb8eec8901a3c75ef24e4837b11d912c6a99a57 (and also commented on https://github.com/mirage/eqaf/pull/27#issuecomment-818987504).

**Pull request merged**
