### PR TITLE
[new release] owl-zoo, owl-top, owl-base, owl and owl-plplot (1.0.0)

### PR DESCRIPTION
**Pull request by jzstark**
OCaml Scientific and Engineering Computing - Zoo

- Project page: <a href="https://github.com/owlbarn/owl">https://github.com/owlbarn/owl</a>
- Documentation: <a href="https://owlbarn.github.io/">https://owlbarn.github.io/</a>

##### CHANGES:

* Update project governance 
* Fix bug in convolution operation 
* Fix bug in AEOS module
* Enable differentiation through the Jacobian in Algodiff
* Fix windows compatibility issue (@kkirstein owlbarn/owl#549)
* Fix bitwidth issue in mingw by replacing long type with int64_t (thanks @kkirstein)
* Fix Dockerfile for master branch

### CODE REVIEW

**Comment by mseri** [comment]
The failures seem to be the usual ones. @jzstark do you want to include the two bugfixes merged today on the release or I should merge?

**Comment by jzstark** [comment]
@mseri I think it is OK to merge now, and the new bugfixes can wait for the next minor release. Thanks a lot!

**Comment by kkirstein** [comment]
There are still some fixes for the windows build in my backlog, but those are only minor issues, like silencing compilation warnings and improve installation docs, so please don't wait for that with the release.

**Comment by jzstark** [comment]
@kkirstein Thanks! Please do help to PR the fixes at your convenience.

**Pull request merged**
