### PR TITLE
constrains the upper bounds of old bap packages

### PR DESCRIPTION
**Pull request by gitoleg**
Since the old versions of bap weren't properly constrained (they didn't have the upper bounds), the https://github.com/ocaml/opam-repository/pull/13010 PR added the upper bounds, and https://github.com/ocaml/opam-repository/pull/13716/ relaxed them a litte bit. However, neither upper bounds were actually right (nor were the absence of them, therefore the introduced upper bounds were still a closer approximation of truth). This PR adds proper constraints to those old versions of bap.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by kit-ty-kate** [comment]
oh wait, `these releases are not installable anymore (3): bap-fsi-benchmark.1.4.0 bap-fsi-benchmark.1.5.0 bap-ida.1.5.0`

Could you take care of that first?

**Comment by ivg** [comment]
> oh wait, `these releases are not installable anymore (3): bap-fsi-benchmark.1.4.0 bap-fsi-benchmark.1.5.0 bap-ida.1.5.0`
> 
> Could you take care of that first?

@kit-ty-kate, done!

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
