### PR TITLE
constrain x509 and key-parsers to asn1-combinators < 0.2.0

### PR DESCRIPTION
**Pull request by hannesm**
due to API changes, fixes the issues mentioned in #10837

### CODE REVIEW

**Comment by hannesm** [comment]
CI issues:
```
OCaml 4.04 and key-parsers.0.8.1
# File "src/kp_cvc.ml", line 107, characters 25-33:
# Error: Attribute `tailcall' was not used
# Command exited with code 2.
```

```
OCaml 4.02 and key-parsers.0.3.0
# File "src/ppx_deriving.ml", line 210, characters 11-17: Assertion failed
```

I've no clue how to fix these issues. //cc @emillon

**Comment by emillon** [comment]
The first one is due to an incompatibility between `@tailcall` annotations (that we removed in `key-parsers.0.9.1`) and `ppx_deriving.4.2`. Tightening the constraint on 0.8.1 to `ppx_deriving < 4.2` should work.

Not sure about the 0.3.0 one, where can the full log be found? If necessary 0.1.0, 0.2.0 and 0.3.0 can also be removed.

**Comment by hannesm** [comment]
@emillon full log is at https://travis-ci.org/ocaml/opam-repository/jobs/306708997

**Comment by emillon** [comment]
For the 0.3.0 build it's probably because the ppx_deriving bounds are pretty wide. I digged [an old log](https://travis-ci.org/cryptosense/key-parsers/jobs/115117320) for that version and it used ppx_deriving 3.2 (the build you linked to uses 2.1). Constraining to `>= 3.0, < 4.0` might work.

**Comment by hannesm** [comment]
thanks to @emillon travis is now happy with this PR!

**Comment by emillon** [comment]
If travis is happy, I'm happy as well! Thanks for taking care of this.

**Comment by yomimono** [comment]
Thanks @emillon and @hannesm !

**Pull request merged**
