### PR TITLE
[new release] dns (13 packages) (9.1.0)

### PR DESCRIPTION
**Pull request by hannesm**
An opinionated Domain Name System (DNS) library

- Project page: <a href="https://github.com/mirage/ocaml-dns">https://github.com/mirage/ocaml-dns</a>
- Documentation: <a href="https://mirage.github.io/ocaml-dns/">https://mirage.github.io/ocaml-dns/</a>

##### CHANGES:

* Dns.Dnskey: provide to_string and name_key_to_string (@hannesm, @dinosaure,
  mirage/ocaml-dns#356 - fixes mirage/ocaml-dns#355)
* BREAKING: Dns.Dnskey remove pp_name_key (unused, irritating, mirage/ocaml-dns#356)
* BREAKING Dns_certify_mirage.retrieve_certificate use separate dns_key_name
  and dns_key arguments, avoid string decoding in that function (mirage/ocaml-dns#356)

### CODE REVIEW

**Comment by hannesm** [comment]
your linting and our spam protection aren't on line. but I won't change that.

**Comment by hannesm** [comment]
The CI failures are unrelated. Something I don't quite understand (and this can't be a regression in dns 9.1.0 -- it must've been around for 9.0.0 as well):

```
#=== ERROR while compiling irmin-client.3.9.0 =================================#
# context              2.4.0~alpha1~dev | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/irmin-client.3.9.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p irmin-client
# exit-code            1
# env-file             ~/.opam/log/irmin-client-7-be04b3.env
# output-file          ~/.opam/log/irmin-client-7-be04b3.out
### output ###
# File "test/irmin-client/dune", line 2, characters 7-11:
# 2 |  (name test)
#            ^^^^
# (cd _build/default/test/irmin-client && ./test.exe)
# Fatal error: exception The default generator is not yet initialized. 
# To initialize the RNG with a default generator, and set up entropy collection and periodic reseeding as a background task, do the following:
#   If you are using MirageOS, use the random device in config.ml: `let main = Mirage.main "Unikernel.Main" (random @-> job)`, and `let () = register "my_unikernel" [main $ default_random]`. 
#   If you are using Lwt, execute `Mirage_crypto_rng_lwt.initialize (module Mirage_crypto_rng.Fortuna)` at startup. 
#   If you are using Async, execute `Mirage_crypto_rng_async.initialize (module Mirage_crypto_rng.Fortuna)` at startup. 
#   If you are using Eio, execute in one of the fibers `Mirage_crypto_rng_eio.run (module Fortuna) env` (`env` from `Eio_main.run`).
#    
#   Otherwise, there is no periodic reseeding. For an initial seed from getrandom(), execute `Mirage_crypto_rng_unix.initialize (module Mirage_crypto_rng.Fortuna)`. You can use `Mirage_crypto_rng.accumulate` and `Mirage_crypto_rng.reseed` to reseed the RNG manually.

```

/cc @zshipko @samoht @art-w -- I'm not sure where in the irmin-client the rng is used, and library should be responsible to initialize it? any hints are welcome. I also wouldn't know what conflict / upper bound should be put into irmin-client -- any hints or ideas of people who care about irmin-client are welcome.

**Comment by hannesm** [comment]
added a constraint for irmin-client as indicated by @clecat in https://github.com/mirage/irmin/issues/2348

**Comment by hannesm** [comment]
CI looks fine to merge -- the irmin-client failures, I'm sorry about them, but this is not the PR to fix them.

**Comment by mseri** [comment]
Thanks. 


I am curious to understand in what sense you mean about irmin? It seesm that tests are failing to run or run forever, do you think it is related to this release in some way?

**Comment by hannesm** [comment]
Thanks for merging @mseri. Sorry that my comment was not understandable.

What I meant: dns 9.1.0 didn't change (in perspective to 9.0.0) anything related to the RNG - that's why I was surprised by the error. Furthermore, dns requires mirage-crypto >= 1.0.0, whereas irmin-client now requires <= 0.11.3. So, any irmin-client failures have to be unrelated to this release.

The changes in dns from 9.0.0 to 9.1.0 are very small, and nothing that is used by irmin-client as far as I can tell - it is mostly in dns-certify (and some functions in Dns.Dnskey).

So, the irmin-client failures must have been there before (either when irmin-client was released - or due to a release of another dependency).

**Pull request merged**
