### PR TITLE
Update js_of_ocaml upper bounds in preparation to release 6.0.0

### PR DESCRIPTION
**Pull request by vouillon**

### CODE REVIEW

**Comment by mseri** [comment]
Thanks

**Comment by mseri** [comment]
Would it be possible to paste here the errors in some representative cases?

**Comment by vouillon** [comment]
JavaScript numbers are not longer mapped to OCaml floats but are given type `Js.number Js.t`. This causes most of the errors.

A few JavaScript properties (and method parameters) were wrongly given type `int`.  This has been fixed by https://github.com/ocsigen/js_of_ocaml/pull/1747. This incompatible changes breaks the latest release of `eliom` and `eliom-toolkit`.

[incr_dom.v0.15.1](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/786b392ff23317513c09a92944451877820a5a4b/variant/compilers,4.14,js_of_ocaml-ppx.6.0.0,revdeps,incr_dom.v0.15.1):
```
# File "src/js_misc.ml", line 40, characters 15-25:
# 40 |   Float.( >= ) rect##.top 0.
#                     ^^^^^^^^^^
# Error: This expression has type
#          Js_of_ocaml__.Js.number_t = Js_of_ocaml__.Js.number Js_of_ocaml.Js.t
#        but an expression was expected of type Core.Float.t = float
```

eliom.11.1.0:
```
File "src/lib/client/eliommod_dom.ml", line 697, characters 15-62:
697 |   { html_top = Dom_html.document##.documentElement##.scrollTop
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type Js_of_ocaml__.Js.number_t = Js.number Js.t
       but an expression was expected of type int
```

ocsigen-toolkit.4.1.0:
```
File "src/widgets/ot_picture_uploader.eliom", line 329, characters 38-50:
329 |               (fun ev -> float_of_int ev##.clientX)
                                            ^^^^^^^^^^^^
Error: This expression has type
         Js_of_ocaml__.Js.number_t = Js_of_ocaml__.Js.number Js_of_ocaml.Js.t
       but an expression was expected of type int
```

**Comment by mseri** [comment]
Thanks a lot

**Pull request merged**
