### PR TITLE
+ mesh 0.8.7

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by samoht** [comment]
fails on OSX:
```
#=== ERROR while installing mesh.0.8.7 ========================================#
# opam-version 1.2.2
# os           darwin
# command      ocaml setup.ml -build
# path         /Users/travis/.opam/system/build/mesh.0.8.7
# compiler     system (4.02.3)
# exit-code    1
# env-file     /Users/travis/.opam/system/build/mesh.0.8.7/mesh-2728-ad6566.env
# stdout-file  /Users/travis/.opam/system/build/mesh.0.8.7/mesh-2728-ad6566.out
# stderr-file  /Users/travis/.opam/system/build/mesh.0.8.7/mesh-2728-ad6566.err
### stdout ###
# [...]
# /Users/travis/.opam/system/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -safe-string -I src -ccopt -DTRILIBRARY -ccopt -DEXTERNAL_TEST -package bigarray -package bytes -package graphics -I src -o src/easymeshF.cmx src/easymeshF.ml
# /Users/travis/.opam/system/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -safe-string -I src -ccopt -DTRILIBRARY -ccopt -DEXTERNAL_TEST -package bigarray -package bytes -package graphics -I src -o src/easymesh.cmx src/easymesh.ml
# /Users/travis/.opam/system/bin/ocamlfind ocamlopt -a src/mesh_utils.cmx src/mesh_common.cmx src/meshC.cmx src/meshF.cmx src/mesh.cmx src/easymeshC.cmx src/easymeshF.cmx src/easymesh.cmx -o src/mesh.cmxa
# /Users/travis/.opam/system/bin/ocamlfind ocamlopt -shared src/mesh.cmxa src/mesh_utils.cmx src/mesh_common.cmx src/meshC.cmx src/meshF.cmx src/mesh.cmx src/easymeshC.cmx src/easymeshF.cmx src/easymesh.cmx -o src/mesh.cmxs
# /Users/travis/.opam/system/bin/ocamlfind ocamldep -package bigarray -package bytes -package graphics -modules src/mesh_display.mli > src/mesh_display.mli.depends
# /Users/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -ccopt -DTRILIBRARY -ccopt -DEXTERNAL_TEST -package bigarray -package bytes -package graphics -I src -o src/mesh_display.cmi src/mesh_display.mli
# + /Users/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -ccopt -DTRILIBRARY -ccopt -DEXTERNAL_TEST -package bigarray -package bytes -package graphics -I src -o src/mesh_display.cmi src/mesh_display.mli
# File "src/mesh_display.mli", line 60, characters 20-34:
# Error: Unbound module Graphics
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/usr/local/bin/ocamlbuild' src/mesh.cma src/mesh.cmxa src/mesh.a src/mesh.cmxs src/mesh_display.cma src/mesh_display.cmxa src/mesh_display.a src/mesh_display.cmxs src/libmesh_triangle_stubs.a src/dllmesh_triangle_stubs.so src/mesh_triangle.cma src/mesh_triangle.cmxa src/mesh_triangle.a src/mesh_triangle.cmxs -tag debug' terminated with error code 10")
```

**Comment by Chris00** [comment]
On Tue, 23 Feb 2016 01:14:38 -0800, Thomas Gazagnaire wrote:
> 
> fails on OSX:
> 
> #=== ERROR while installing mesh.0.8.7 ========================================#
> # Error: Unbound module Graphics

Doesn't Graphics exist on OSX?

**Comment by Chris00** [comment]
To have the `Graphics` module on OSX, one must install OCaml with `brew [re]install ocaml --with-x11` it seems.  I will try to see what I can do to disable the compilation of that module if `Graphics` is not available.  (Suggestions welcome!)

**Comment by samoht** [comment]
ha good catch! It might be possible to modify the runes in https://github.com/ocaml/ocaml-ci-scripts/blob/master/.travis-ocaml.sh#L94-L99 as well

**Comment by dsheets** [comment]
How is this now passing?

**Comment by samoht** [comment]
>  I will try to see what I can do to disable the compilation of that module if Graphics is not available. 

I guess it was possible to do this :-)

**Pull request merged**
