### PR TITLE
[urgent] Package opam-state.2.0.0~rc and 7 others

### PR DESCRIPTION
**Pull request by AltGr**
This pull-request concerns:
-`opam-state.2.0.0~rc`: opam 2.0 development libraries
-`opam-solver.2.0.0~rc`: opam 2.0 development libraries
-`opam-repository.2.0.0~rc`: opam 2.0 development libraries
-`opam-installer.2.0.0~rc`: Installation of files to a prefix, following opam conventions
-`opam-format.2.0.0~rc`: opam 2.0 development libraries
-`opam-devel.2.0.0~rc`: opam 2.0.0 development version
-`opam-core.2.0.0~rc`: opam 2.0 development libraries
-`opam-client.2.0.0~rc`: opam 2.0 development libraries

---
* Homepage: 
  `opam-state.2.0.0~rc`: https://opam.ocaml.org/
  `opam-solver.2.0.0~rc`: https://opam.ocaml.org/
  `opam-repository.2.0.0~rc`: https://opam.ocaml.org/
  `opam-installer.2.0.0~rc`: https://opam.ocaml.org/
  `opam-format.2.0.0~rc`: https://opam.ocaml.org/
  `opam-devel.2.0.0~rc`: https://opam.ocaml.org
  `opam-core.2.0.0~rc`: https://opam.ocaml.org/
  `opam-client.2.0.0~rc`: https://opam.ocaml.org/
* Source repo: https://github.com/ocaml/opam.git
* Bug tracker: https://github.com/ocaml/opam/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by AltGr** [comment]
Ref. https://github.com/ocaml/opam/issues/3210 — This has been announced as part of the opam2 RC install instructions, but (oops) the package here was'nt present yet. So it would be nice if it could be merged ASAP...

**Comment by jpdeplaix** [comment]
```dose3``` needs patching first:
```
- File "_none_", line 1:
- Error: No implementations provided for the following modules:
-          Unix referenced from /home/opam/.opam/4.05.0/lib/dose3/common.cmxa(Common)
```
Could you add a patch to ```dose3``` that adds the appropriate ```unix``` dependency in the META file ?

**Comment by AltGr** [comment]
Yes, I'll fix this quickly

**Comment by AltGr** [comment]
Failures seem due to failed dls with codes 429 on GH: too many requests.

**Comment by jpdeplaix** [comment]
Everything seems good. Merging, thanks.

**Comment by AltGr** [comment]
Thanks

**Pull request merged**
