### PR TITLE
Release i3ipc 0.1.3

### PR DESCRIPTION
**Pull request by Armael**

### CODE REVIEW

**Comment by Armael** [comment]
I'm not sure how to interpret the CI failures?

**Comment by hcarty** [comment]
@Armael I kicked off a rebuild for the failure - it's not caused by your PR.

**Comment by mseri** [comment]
It seems an infrastructure problem, it doesnot work even if you rebuild. I think this can be merged anyways

**Comment by hcarty** [comment]
Thanks @mseri for the clarification and @Armael for the PR!

Merging.

**Comment by Armael** [comment]
Thanks everyone!

**Pull request merged**
