### PR TITLE
added conf-tk and conf-tcl

### PR DESCRIPTION
**Pull request by timbertson**
They're only used in a couple of packages, so I've replaced all uses (although I don't know what ivy is, I'm just after a working labltk).

### CODE REVIEW

**Comment by timbertson** [comment]
Hmm, I don't understand the travis failure - `pkg-config tcl` works fine on fedora and nix, is ubuntu special or am I misreading the reason for failure?

**Comment by samoht** [comment]
Maybe you need the `-dev` versions of these packages?

**Comment by timbertson** [comment]
@samoht `conf-tcl` does depend on ubuntu's `tcl-dev` package. (I could have called it `conf-tcl-dev`, but leaving the `-dev` suffix out of the opam name seemed consistent with other similar packages)

**Comment by samoht** [comment]
Hum yes sorry. So not sure what's happening then...

**Comment by avsm** [comment]
I did a multidistro bulk build; looks like a pkg-config depext is missing:

https://github.com/avsm/opam-pr-build-results/blob/6068/README.md

**Comment by timbertson** [comment]
@avsm do you mean pkg-config is not getting installed? Looking at e.g. the ubuntu 15.10 output, pkg-config, tcl-dev and tk-dev are all being installed by apt (https://github.com/avsm/opam-pr-build-results/blob/6068/build/log.ubuntu-15.10_ocaml-4.02.3#L137)

It doesn't install pkg-config, but that's probably because it's already installed - you can see `pkg-config --help` works: https://github.com/avsm/opam-pr-build-results/blob/6068/build/log.ubuntu-15.10_ocaml-4.02.3#L491

I think the issue is that `tcl-dev` and `tk-dev` don't consistently ship with any pkg-config file - I have one on fedora, and the arch package lists one too (https://www.archlinux.org/packages/extra/x86_64/tcl/files/), but trying it out in an ubuntu VM, installing tcl-dev doesn't install any `*.pc` files. The fedora build would probably succeed if we added `tcl-devel` as a fedora depext, but it would then be the only distro that does succeed.

So, is there any cross-platform way to test for these dev packages without using `pkg-config`?

Suggestion: If we left the conf-* packages without any actual check they would always succeed, but `labltk` would still fail to compile. If opam was smart enough to instruct users to try `opam depext labltk.8.06.0` on build failure (because it has _transitive_ depexts), perhaps that would be sufficient? Running that depext command does cause the right system packages to be installed, it's just not suggested to the user when `labltk` fails to build.

It could also simplify other conf-* packages, e. off the top of my head it would remove the need for #5898 and #5847, and I'm sure plenty more where the verification command itself causes further issues.

**Comment by lefessan** [comment]
I think a consistent way would be to test their use, as in the packages that depends on them. For example, `labltk` has a file `config/auto-aux/tclversion.c` that can be summarized to:
```
#include <stdio.h>
#include <tcl/tcl.h>
main (){ puts(TCL_VERSION);}
```
Your `conf-tcl` package could try to compile and run that file.

Something similar could be done for TK.

**Comment by timbertson** [comment]
Hmm, it's a fair approach @lefessan. Unfortunately I just tried it, and even that simple file requires a bunch of hackery to try and guess a valid include location:

https://github.com/michipili/labltk/blob/8d114cc406f33edbb8268524743acd8f2cf6e673/configure#L168

Hardcoding like this will mean that anyone with a non-standard `tcl` install location will be unable to install these packages without modifying this package's recipe. But maybe this is an OK fallback - I'm now trying `pkg-config` for the most flexibility, and if that fails then give the compilation a go with a couple of well-known include locations to cover those distros that don't ship a pkg-config file.

It feels quite messy, but I can see the value in having the `conf-` package not install unless the relevant depexts are actually present.

**Comment by timbertson** [comment]
OK, I've rebased and now the only travis failures are:

 - labltk failing to build on ocaml 4.03 for what looks like an API change
 - ivy failing to build on darwin

Both of these are unrelated to tcl/tk, so can this be merged now?

@avsm, is is worth running another multidistro build with the latest changes? Due to the hardcoded include paths, errors are likely to be quite distro-specific. And is there anyone who can test on BSD?

**Comment by lefessan** [comment]
@timbertson I have asked @damiendoligez about the removal of Zenon 0.8. For tcl, maybe a solution to handle weird configurations would be to use env variables to specify the locations of tcl.h and tk.h. However, it would only work if the packages that also depend on conf-tcl and conf-tk use the same variables.

I am inclined to accept the PR as it is (after understand what to do with Zenon), and let the users with unusual configurations fix the packages themselves.

**Comment by timbertson** [comment]
@lefessan oh yes, sorry I forgot to discuss Zenon (it's been a while since I made this PR). Would you prefer me to move it into a separate PR to move this one along?

As for environment variables, I don't think that would be useful (as you say, the important thing is whether labltk and other users of tcl/tk can find the installed libraries). So it might just be a case of adding other fallback paths which users of tcl/tk look in but the conf-* packages don't. Or else getting weird distros to provide pkg-config files, which are a perfect fit for all these hardcoded-path shenanigans in the first place ;)

**Comment by lefessan** [comment]
Actually, it reminded me of something: I think that, if `conf-tcl` creates a file `conf-tcl.config` in its root, the variables that are defined there can be accessed from `opam` files of dependant packages.

So, if you define `conf-tcl.config` as:
```
include: "/usr/include"
```
it should be possible for labltk to use a variable `%{conf-tcl:include}%` to locate the same files....

**Comment by timbertson** [comment]
Ahh, good to know @lefessan. Are you suggesting this for use right now, though? I think at the moment adding this wouldn't be worth the extra complexity, as it would make the `conf-*` packages quite a bit more complex (includedir isn't the only piece of information needed for full compilation) and would require changes to already-working labltk and ivy packages.

If we want conf-* to provide anything, it's probably better for them to synthesize a .pc file when none is provided by the distro, since that doesn't require OPAM specific code to make use of.

**Comment by damiendoligez** [comment]
@timbertson @lefessan http://zenon-prover.org is back online, so you can drop that part of the PR. Thanks for bringing the problem to my attention.

**Comment by timbertson** [comment]
Thanks @damiendoligez , I've removed that commit, so I think this is ready to merge now :)

**Pull request merged**
