### PR TITLE
Jane Street packages v0.15.0

### PR DESCRIPTION
**Pull request by aalekseyev**
This PR adds Jane Street packages v0.15.0, and adds upper-bound constrains to any reverse dependencies that are not compatible with v0.15.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Closing this temporarily while I figure out how to make CI not crash on this massive PR

**Comment by olafhering** [comment]
Unless I miss something: `ocaml_intrinsics` needs the equivalent of `ExclusiveArch: x86_64 %ix86`.

**Comment by aalekseyev** [comment]
@kit-ty-kate, any luck with the CI?

**Comment by kit-ty-kate** [comment]
> @kit-ty-kate, any luck with the CI?

Sadly no, this is simply too many jobs (~ half a milion). I’ve split split the commit adding the jst packages from the rest in https://github.com/ocaml/opam-repository/pull/20863 and will do the rest in several steps later.

**Comment by kit-ty-kate** [comment]
https://github.com/ocaml/opam-repository/pull/20876 seems to be holding up so far

**Comment by aalekseyev** [comment]
@olafhering, I don't know. Why do you think so?
My understanding is that it's supposed to work on any architecture falling back to "software" implementations as necessary, but I may be wrong.

**Comment by kit-ty-kate** [comment]
The CI results in https://github.com/ocaml/opam-repository/pull/20876 says otherwise though

**Comment by olafhering** [comment]
it has some arm64 conditionals, they fail to compile in Leap and Tumbleweed. That still leaves other archs.

Sorry, I had no time to make all pending upgrades public in [devel:languages:ocaml](https://build.opensuse.org/project/show/devel:languages:ocaml). Maybe later this month.

**Pull request closed without merging**
