### PR TITLE
repository cleanups: remove 'findlib' files, rename desc and desr to descr

### PR DESCRIPTION
**Pull request by hannesm**
this PR does multiple changes
- removes leftover `findlib` files (see #9328 for earlier discussion)
- moves `desc` and `desr` files to `descr`
- removes `.chamo.sourceview.buffers` which seems to be accidentally commited

### CODE REVIEW

**Comment by hcarty** [comment]
This looks good to me. The Travis failure is unrelated.

**Comment by pmetzger** [comment]
Just a side note: a request name that is just "cleanups" is a bad idea. It means people don't know whether to pay attention to the particular request or not because they don't know what it is about.

**Comment by hannesm** [comment]
@pmetzger good point, renamed.  sorry.

**Comment by kit-ty-kate** [comment]
Looks good. Thanks a lot!!

**Pull request merged**
