### PR TITLE
Use `plugin` flag for OPAM plugins

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by avsm** [comment]
Dammit, there's a huge warning on the `plugin` flag if used in OPAM 1.2.0 :-/

I hate these unnecessary warnings -- they should be in OPAM lint and not the main tool, as they really hamper us adding new features.

**Comment by avsm** [comment]
This is one reason to use a tag rather than the more structured `flags` field.

**Comment by AltGr** [comment]
Ack, indeed. These were the only available feedback before `opam lint`, but yes, mixing this kind of packager-directed feedback with the users' isn't nice. 1.2.1 is affected too.

A tag could be used instead as a flag as a workaround until 1.3 -- I doubt too many users will be hit by the change if we fix it in 1.3, and a rewrite + lint warning will be there to avoid the confusion.

**Comment by AltGr** [comment]
There might be another workaround, but it's only slightly better: by specifying `opam-version: "1.2.2"`, it'll make opam (>= 1.2.1) be more tolerant and print:
```
[NOTE] File /home/lg/.opam/packages/depext/depext.0.4/opam is written for OPAM 1.2.2, and this is 1.2.1.
       It may depend on new features, consider upgrading.
```
at least this will be printed only once per run and is less scary.
Maybe that mode should be the default when no debug options are set...

**Comment by avsm** [comment]
I think depending more on opam lint and less on these per package warnings might be better. we could reduce them for 1.2.2 to help with 1.3 migration...

**Comment by avsm** [comment]
> A tag could be used instead as a flag as a workaround until 1.3 -- I doubt too many users will be hit by the change if we fix it in 1.3, and a rewrite + lint warning will be there to avoid the confusion.

Agreed -- this seems like a good solution. Using the `opam:plugin` (or `flags:plugin`) prefix and then rewriting it into a more typed version is better than introducing new syntax into a point release.

**Comment by AltGr** [comment]
yup, got that, I'm on it -- no sense in printing these warnings for repo packages on 'opam update' indeed.

**Comment by avsm** [comment]
Have pushed the use of `flags:plugin` to this pull req

**Pull request merged**
