### PR TITLE
Added < spotlib.4.0.0 for the existing opamfind

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by avsm** [comment]
This seems to fail on OCaml 4.04.0 -- an upper bound on compiler version required?

**Comment by camlspotter** [comment]
Thanks, I forgot to register the upgraded version of ppx_meta_conv.  The older opamfind packages now require some additional version constraints...

**Comment by avsm** [comment]
Thanks! This now conflicts with the master branch, so either a conflict fix or closing it is needed.

**Comment by camlspotter** [comment]
Ok, abandoning this PR.

**Pull request closed without merging**
