### PR TITLE
[ppx-import] Release supporting OCaml 4.07.0

### PR DESCRIPTION
**Pull request by ejgallego**
I've updated the repository field, but not the maintainer one;
cc: @gasche @whitequark as to what should be done here.

### CODE REVIEW

**Comment by mseri** [comment]
Is the `~pre00` on purpose? Is `1.5~pre0` recognised as smaller than `1.5`?

**Comment by mseri** [comment]
I am inclied to merge if that is on purpose, and postpone an eventual change of maintainership

**Comment by gasche** [comment]
Note: I would be willing to help make a proper release for ppx_import, but I've been super-busy and didn't find the time to push it yet. If @ejgallego is willing to wait over the weekend, I could do one tomorrow and use it instead of a commit-specific tarball. (On the other hand, I see nothing deeply wrong with using a commit-specific tarball; it merely highlights that maintainers, in that case myself, have not been available enough, which is true.)

**Comment by ejgallego** [comment]
> Note: I would be willing to help make a proper release for ppx_import, but I've been super-busy and didn't find the time to push it yet. If @ejgallego is willing to wait over the weekend, I could do one tomorrow and use it instead of a commit-specific tarball. (On the other hand, I see nothing deeply wrong with using a commit-specific tarball; it merely highlights that maintainers, in that case myself, have not been available enough, which is true.)

Thanks @gasche and @mseri , indeed if you prefer no problem in waiting for a release, I will update this PR accordingly then.

**Comment by gasche** [comment]
Great! Let's do this. (If it doesn't happen this week-end, go for the PR.) Thanks for your patience.

**Comment by gasche** [comment]
The archive URL of the new release is

  https://github.com/ocaml-ppx/ppx_import/archive/v1.5.tar.gz

**Comment by ejgallego** [comment]
Updated

**Comment by mseri** [comment]
Thanks! Let's wait for Travis and the CI, and I'll merge!

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
