### PR TITLE
faad.0.4.0

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by toots** [comment]
CentOS distribution doesn't have `faad2-devel` but it's available in secondary repositories:https://pkgs.org/download/faad

**Comment by kit-ty-kate** [comment]
Seems like this library requires either OCaml >= 4.02 or to depend on the `base-bytes` package, but it's probably the former considering the error message:
```
- File "faad.mli", line 46, characters 16-23:
- Error: Unbound module Bytes
```

**Comment by kit-ty-kate** [comment]
mmh that fix was indeed unlikely to work. Could you add a lower-bound instead or fix your release?

**Comment by toots** [comment]
@kit-ty-kate I don't get it. Isn't `base-bytes` supposed to provide the `Bytes` module?

**Comment by kit-ty-kate** [comment]
It only provides a `Bytes` module in a `bytes` package. If you didn't use the `bytes` package in the first place, the compiler doesn't see it.

**Comment by toots** [comment]
Ya makes sense, I don't know what confused me.. Just uploaded a fixed release.

**Pull request merged**
