### PR TITLE
oasis tests are broken, disable them

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by yomimono** [comment]
2016-03-12T20:33:03+00:00 mirageos#01 E: Test OASIS:15:TestStdFiles:1:remove-section has failed.

A failed Travis build log depending on oasis is at https://travis-ci.org/mirage/mirage-tcpip/jobs/115511468 .

**Comment by gildor478** [comment]
# W: Test 'main' fails: Command '/home/travis/.opam/system/build/oasis.0.4.5/_build/test/test.byte -oasis /home/travis/.opam/system/build/oasis.0.4.5/_build/src/cli/Main.byte -is-native true -native-dynlink true -ocamlmod /home/travis/.opam/system/bin/ocamlmod -fake-ocamlfind /home/travis/.opam/system/build/oasis.0.4.5/_build/test/utils/fake_ocamlfind.byte' terminated with error code 1
# E: Failure("Tests had a 33.33% failure rate")

I use Travis for the OASIS project, with OCaml 4.02.2 and it seems OK. Can anyone point me to a more precise error report ? Something that will contain more precise logs with the error in fake_ocamlfind.byte ?

**Comment by gildor478** [comment]
Cannot reproduce this error. Please ping me if you have a way to reproduce it.

**Pull request merged**
