### PR TITLE
gsl is gsl on FreeBSD

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
worthless since gsl also fails... and I won't bother to remove its GNUisms and fix their build system

**Comment by dsheets** [comment]
Just to clarify: FreeBSD's `gsl` port doesn't build? Or the OCaml `gsl` package fails?

If the latter, could we please still add the FreeBSD `gsl` depext here? It is correct and may be useful for others.

**Comment by hannesm** [comment]
FreeBSD's `math/gsl` port is fine.  The gsl from opam (ocaml-gsl) does not work on posix systems.  I don't see much value in having a conf-gsl with no working reverse dependencies.  But cherry-pick and PR yourself.

**Comment by yallop** [comment]
I've merged this into master: https://github.com/ocaml/opam-repository/commit/7a9d9a73e918c580f1ce8c4b180237439bd8d86e

**Pull request closed without merging**
