### PR TITLE
Add a conf package for capnproto

### PR DESCRIPTION
**Pull request by jpdeplaix**
I was trying to install ```capnp-rpc-lwt``` and the following error appeared:
```
Error: Program capnpc not found in the tree or in PATH (context: default)
```
It seems that ```capnp-rpc-lwt``` is the only capnp-* packages that requires this command but maybe I missed something.
This conf package allows the user to know which external package to install is this case. It could also be useful for other opam packages which use this command.

cc @talex5

### CODE REVIEW

**Comment by talex5** [comment]
It should be a dependency of `capnp`, which `capnp-rpc-lwt` depends on.

**Comment by gasche** [comment]
Besides what @taelx5 said, it seems to me that the depexts could be improved by looking at what capnp currently has:

- it has a "centos" depext that you should reuse
- for debian/ubuntu it seems to add "libcapnp-dev", which you could reuse

**Comment by jpdeplaix** [comment]
Sorry for the delay. It is fixed.
Should I also add ```conf-capnproto``` as a dependency of ```capnp-rpc``` ?

**Comment by gasche** [comment]
So I looked at the CI failures of this (new version of the change) and they are a bit odd. An old version of capnp (2.1.0) fails under OCaml 4.04 and 4.05 with an error message that seems to come from a much older time:

```
# - build src/compiler includes.ml
# + ocaml -I /home/travis/.opam/4.04.2/lib/toplevel make_includes.ml
# *** omake: 52/232 targets are up to date
# *** omake: failed (0.99 sec, 5/5 scans, 4/10 rules, 32/101 digests)
### stderr ###
# File "./make_includes.ml", line 17, characters 9-20:
# Error: Unbound value String.trim
# *** omake: targets were not rebuilt because of errors:
#    src/compiler/includes.ml
#       depends on: src/runtime/common-inc.ml
#       depends on: src/runtime/reader-inc.ml
#       depends on: src/compiler/make_includes.ml
#       depends on: src/runtime/builder-inc.ml
```

`String.trim` was added to the standard library for 4.00, so it is not missing from 4.0{4,5}. It looks like the `make_includes.ml` file works in a peculiar environment where, I suppose, the `String` module is bound to something else.

This seems clearly independent to @jpdeplaix's change, so I'm willing to merge the PR despite the failures, but I wonder if we shouldn't try to silence them for good by marking old capnp release incompatible with new OCaml versions. I wouldn't want to do this blindly though (if they are *meant* to be compatible, then keeping them gives us more regression-finding power), so I'm not satisfied that I have no idea of where the error comes from, and why it fails only at those OCaml versions (4.03 works fine for example). @talex5, would you, by chance, have some idea of what's going on with these failures?

**Comment by gasche** [comment]
Ok, so looking more at the issue, it looks like the reason for this odd failure pattern is that the way the capnp.2.1.{0,1} versions handle OCaml version availability constraints is by giving an explicit list of unsupported versions, instead of an upper bound:

```
available: [ ocaml-version >= "4.01.0" & ocaml-version != "4.03.0" & ocaml-version != "4.04.0" ]
```

I suppose that this was first put for 4.03, and then updated for 4.04, and then people forgot. The version is probably broken on all recent OCaml releases. (It explains why the CI passed on 4.03: it did not try to build this version.) This should be `< 4.03`. @jpdeplaix, would you also make this change?

**Comment by talex5** [comment]
> Should I also add conf-capnproto as a dependency of capnp-rpc ?

No, that's just the abstract logic - it doesn't depend on the serialisation at all.

**Comment by jpdeplaix** [comment]
@gasche I just looked at the code and it seems that the problem comes from ```core_kernel``` that includes its own ```String``` module since ```v0.9.0```.
Before, it was named ```Core_string``` and so the ```String``` module is the one from the stdlib.

**Comment by gasche** [comment]
I notice that you didn't only add the core_kernel constraint, you also removed the `ocaml-version != 4.0{3,4}` constraints. Are you sure that those are subsumed by the new condition?

**Comment by jpdeplaix** [comment]
> I notice that you didn't only add the core_kernel constraint, you also removed the ocaml-version != 4.0{3,4} constraints. Are you sure that those are subsumed by the new condition?

Ok, I assumed badly that it was somehow related. Turns out it's not:
https://github.com/ocaml/opam-repository/commit/53c290b85ae9a2834fa46d92ee9d3822d5baef8c

It's fixed. Thanks for noticing, sorry for that.

**Comment by jpdeplaix** [comment]
Ok, I don't understand this error message that appears on 4.02.3 via ci.ocaml.io but not via travis:
```
File "fragmentBuffer.ml", line 1:
Error: I/O error: /tmp/ocamlppc06341957a364f9315c698491d8e0587: File exists
File "message.ml", line 1:
Error: I/O error: /tmp/ocamlpp93d2572a6c5f462bc9f030fc39a3f7d7: File exists
*** omake: 142/232 targets are up to date
*** omake: failed (5.45 sec, 38/38 scans, 22/37 rules, 95/128 digests)
*** omake: targets were not rebuilt because of errors:
   src/runtime/fragmentBuffer.cmo
      depends on: src/runtime/fragmentBuffer.ml
   src/runtime/message.cmo
      depends on: src/runtime/message.ml
[ERROR] The compilation of capnp failed at "env PREFIX=/home/opam/.opam/system
        omake".
```

**Comment by gasche** [comment]
This looks like another instance of the "entropy error" that plagued other PRs -- the CI machines don't have enough entropy to seed their random-number generator properly, so different runs conflict in their choice of temporary directory. I think this PR is now good enough and can be merged.

**Comment by gasche** [comment]
I noticed an issue with `uint` on 4.06 in the CI report, see https://github.com/ocaml/opam-repository/pull/10565.

**Pull request merged**
