### PR TITLE
Package prr.0.1.1

### PR DESCRIPTION
**Pull request by haochenx**
### `prr.0.1.1`
A fork of brr, sans browser-only APIs
A fork of brr, sans browser-only APIs; see https://github.com/kxcdev/prr and https://github.com/dbuenzli/brr for details

---
* Homepage: https://github.com/kxcdev/prr
* Source repo: git+https://github.com/kxcdev/prr.git
* Bug tracker: https://github.com/kxcdev/prr/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by haochenx** [comment]
opam-ci seems failing but I think it's a temporary problem with the ci instead of the package?

<details>
  <summary>log from opam-ci</summary>

url: https://opam-ci.ci3.ocamllabs.io/github/ocaml/opam-repository/commit/944e288890777a98e2c7812b6aaa782386507d5d/variant/compilers,4.08,prr.0.1.1,lower-bounds

```
2023-02-11 22:18.47: New job: build prr.0.1.1, lower-bounds, using opam dev
                              from https://github.com/ocaml/opam-repository.git#refs/pull/23294/head (944e288890777a98e2c7812b6aaa782386507d5d)
                              on debian-11-ocaml-4.08/amd64

To reproduce locally:

cd $(mktemp -d)
git clone --recursive "https://github.com/ocaml/opam-repository.git" && cd "opam-repository" && git fetch origin "refs/pull/23294/head" && git reset --hard 944e2888
git fetch origin master
git merge --no-edit c779ad0dff3b595b4a557c4c9bb27282c6555207
cat > ../Dockerfile <<'END-OF-DOCKERFILE'
FROM ocaml/opam:debian-11-ocaml-4.08@sha256:5e82dc9238357e07d4e6c9eb0605953cd9b5168ca69da251d0ffbc04c3f9d384
USER 1000:1000
WORKDIR /home/opam
RUN sudo ln -f /usr/bin/opam-dev /usr/bin/opam
RUN opam init --reinit -ni
ENV OPAMDOWNLOADJOBS="1"
ENV OPAMERRLOGLEN="0"
ENV OPAMSOLVERTIMEOUT="500"
ENV OPAMPRECISETRACKING="1"
RUN rm -rf opam-repository/
COPY --chown=1000:1000 . opam-repository/
RUN opam repository set-url --strict default opam-repository/
ENV OPAMCRITERIA="-removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed"
ENV OPAMFIXUPCRITERIA="-removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed"
ENV OPAMUPGRADECRITERIA="-removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed"
RUN opam pin add -k version -yn prr.0.1.1 0.1.1
RUN opam update --depexts || true
RUN opam reinstall prr.0.1.1; \
    res=$?; \
    test "$res" != 31 && exit "$res"; \
    export OPAMCLI=2.0; \
    build_dir=$(opam var prefix)/.opam-switch/build; \
    failed=$(ls "$build_dir"); \
    partial_fails=""; \
    for pkg in $failed; do \
    if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"debian-11\""; then \
    echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field."; \
    fi; \
    test "$pkg" != 'prr.0.1.1' && partial_fails="$partial_fails $pkg"; \
    done; \
    test "${partial_fails}" != "" && echo "opam-repo-ci detected dependencies failing: ${partial_fails}"; \
    exit 1
ENV OPAMCRITERIA="+removed,+count[version-lag,solution]"
ENV OPAMFIXUPCRITERIA="+removed,+count[version-lag,solution]"
ENV OPAMUPGRADECRITERIA="+removed,+count[version-lag,solution]"
ENV OPAMEXTERNALSOLVER="builtin-0install"
RUN opam update --depexts || true
RUN opam reinstall prr.0.1.1; \
    res=$?; \
    test "$res" != 31 && exit "$res"; \
    export OPAMCLI=2.0; \
    build_dir=$(opam var prefix)/.opam-switch/build; \
    failed=$(ls "$build_dir"); \
    partial_fails=""; \
    for pkg in $failed; do \
    if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"debian-11\""; then \
    echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field."; \
    fi; \
    test "$pkg" != 'prr.0.1.1' && partial_fails="$partial_fails $pkg"; \
    done; \
    test "${partial_fails}" != "" && echo "opam-repo-ci detected dependencies failing: ${partial_fails}"; \
    exit 1

END-OF-DOCKERFILE
docker build -f ../Dockerfile .

2023-02-11 22:18.47: Using cache hint "ocaml/opam:debian-11-ocaml-4.08@sha256:5e82dc9238357e07d4e6c9eb0605953cd9b5168ca69da251d0ffbc04c3f9d384-prr.0.1.1-944e288890777a98e2c7812b6aaa782386507d5d"
2023-02-11 22:18.47: Using OBuilder spec:
((from ocaml/opam:debian-11-ocaml-4.08@sha256:5e82dc9238357e07d4e6c9eb0605953cd9b5168ca69da251d0ffbc04c3f9d384)
 (user (uid 1000) (gid 1000))
 (workdir /home/opam)
 (run (shell "sudo ln -f /usr/bin/opam-dev /usr/bin/opam"))
 (run (network host)
      (shell "opam init --reinit --config .opamrc-sandbox -ni"))
 (env OPAMDOWNLOADJOBS 1)
 (env OPAMERRLOGLEN 0)
 (env OPAMSOLVERTIMEOUT 500)
 (env OPAMPRECISETRACKING 1)
 (run (shell "rm -rf opam-repository/"))
 (copy (src .) (dst opam-repository/))
 (run (shell "opam repository set-url --strict default opam-repository/"))
 (env OPAMCRITERIA -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed)
 (env OPAMFIXUPCRITERIA -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed)
 (env OPAMUPGRADECRITERIA -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed)
 (run (shell "opam pin add -k version -yn prr.0.1.1 0.1.1"))
 (run (network host)
      (shell "opam update --depexts || true"))
 (run (cache (opam-archives (target /home/opam/.opam/download-cache)))
      (network host)
      (shell  "opam reinstall prr.0.1.1;\
             \n        res=$?;\
             \n        test \"$res\" != 31 && exit \"$res\";\
             \n        export OPAMCLI=2.0;\
             \n        build_dir=$(opam var prefix)/.opam-switch/build;\
             \n        failed=$(ls \"$build_dir\");\
             \n        partial_fails=\"\";\
             \n        for pkg in $failed; do\
             \n          if opam show -f x-ci-accept-failures: \"$pkg\" | grep -qF \"\\\"debian-11\\\"\"; then\
             \n            echo \"A package failed and has been disabled for CI using the 'x-ci-accept-failures' field.\";\
             \n          fi;\
             \n          test \"$pkg\" != 'prr.0.1.1' && partial_fails=\"$partial_fails $pkg\";\
             \n        done;\
             \n        test \"${partial_fails}\" != \"\" && echo \"opam-repo-ci detected dependencies failing: ${partial_fails}\";\
             \n        exit 1"))
 (env OPAMCRITERIA +removed,+count[version-lag,solution])
 (env OPAMFIXUPCRITERIA +removed,+count[version-lag,solution])
 (env OPAMUPGRADECRITERIA +removed,+count[version-lag,solution])
 (env OPAMEXTERNALSOLVER builtin-0install)
 (run (network host)
      (shell "opam update --depexts || true"))
 (run (cache (opam-archives (target /home/opam/.opam/download-cache)))
      (network host)
      (shell  "opam reinstall prr.0.1.1;\
             \n        res=$?;\
             \n        test \"$res\" != 31 && exit \"$res\";\
             \n        export OPAMCLI=2.0;\
             \n        build_dir=$(opam var prefix)/.opam-switch/build;\
             \n        failed=$(ls \"$build_dir\");\
             \n        partial_fails=\"\";\
             \n        for pkg in $failed; do\
             \n          if opam show -f x-ci-accept-failures: \"$pkg\" | grep -qF \"\\\"debian-11\\\"\"; then\
             \n            echo \"A package failed and has been disabled for CI using the 'x-ci-accept-failures' field.\";\
             \n          fi;\
             \n          test \"$pkg\" != 'prr.0.1.1' && partial_fails=\"$partial_fails $pkg\";\
             \n        done;\
             \n        test \"${partial_fails}\" != \"\" && echo \"opam-repo-ci detected dependencies failing: ${partial_fails}\";\
             \n        exit 1"))
)

2023-02-11 22:18.47: Waiting for resource in pool OCluster
2023-02-11 22:18.47: Waiting for worker…
2023-02-11 22:20.00: Got resource from pool OCluster
Building on c2-3.ocamllabs.io
fatal: Unable to create '/var/cache/obuilder/ocluster/git/opam-repository.git-b322f7b18d276db68487afc3dfc5a5befdd45818/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git-reset failed with exit-code 128
2023-02-11 22:20.00: Job failed: Failed: Build failed
```
</details>

**Comment by haochenx** [comment]
Looks like that after a few reruns, all CI tests has now passed 🚀

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by haochenx** [comment]
Thank you for reviewing and acceptance! @kit-ty-kate

**Pull request merged**
