### PR TITLE
Package checked_oint.0.1.1

### PR DESCRIPTION
**Pull request by Hirrolot**
### `checked_oint.0.1.1`
An OCaml library for checked integer arithmetic

---
* Homepage: https://github.com/Hirrolot/checked_oint
* Source repo: git+https://github.com/Hirrolot/checked_oint.git
* Bug tracker: https://github.com/Hirrolot/checked_oint/issues

---
:camel: Pull-request generated by opam-publish v2.3.0

### CODE REVIEW

**Comment by raphael-proust** [comment]
All looks good. Waiting for the last couple of architectures to finish running in the CI.

**Comment by Hirrolot** [comment]
Can somebody merge this?

**Comment by Hirrolot** [comment]
Anybody is here? @raphael-proust @avsm

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
