### PR TITLE
the checksum was wrong

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I don't know how the package could be accepted if the tarball checksum was wrong ?!

**Comment by dsheets** [comment]
Sometimes the tarballs are re-generated by GitHub, I believe.

**Comment by avsm** [comment]
They can be re-tagged by upstream maintainers, at which point GitHub will regenerate the tarball with a different checksum.

**Comment by UnixJunkie** [comment]
Travis is OK with all the linux environments.
I checked a few: the package was really installed then removed when the ocaml version
is a supported one.

**Pull request merged**
