### PR TITLE
[new release] merlin (3.3.4-4.10preview1)

### PR DESCRIPTION
**Pull request by let-def**
Editor helper, provides completion, typing and source browsing in Vim and Emacs

- Project page: <a href="https://github.com/ocaml/merlin">https://github.com/ocaml/merlin</a>

##### CHANGES:

Mon Mar  2 14:26:32 CET 2020

This is a preview release that adds support for OCaml 4.10.
Short-path is disabled.  Other versions of OCaml are not supported.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks a lot!!

**Comment by let-def** [comment]
Thank you :)

**Comment by Octachron** [comment]
@let-def , should I announce that there is a version of merlin available for 4.10.0 ? Or do you think it is better to wait?

**Comment by let-def** [comment]
It is fine to announce the release, as long as it is clear that it is a preview and not a definitive version. (And maybe that short-path does not work?)

**Comment by Octachron** [comment]
Ok, let's announce the preview then.

**Pull request merged**
