### PR TITLE
Package bls12-381.6.1.0

### PR DESCRIPTION
**Pull request by dannywillems**
### `bls12-381.6.1.0`
Implementation of BLS12-381 and some cryptographic primitives built
on top of it

---
* Homepage: https://nomadic-labs.gitlab.io/cryptography/ocaml-bls12-381/bls12-381/
* Source repo: git+https://gitlab.com/nomadic-labs/cryptography/ocaml-bls12-381.git
* Bug tracker: https://gitlab.com/nomadic-labs/cryptography/ocaml-bls12-381/-/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by dannywillems** [comment]
Failed builds do not seem to be related to any constraint on versions like before.

**Comment by dannywillems** [comment]
I don't know if any action is required on my side. @kit-ty-kate let me know if any

**Comment by kit-ty-kate** [comment]
The tests fail on s390x, is that expected?
```
#=== ERROR while compiling bls12-381-hash.0.0.5 ===============================#
# context              2.2.0~alpha~dev | linux/s390x | ocaml-base-compiler.5.0.0 | pinned(https://gitlab.com/nomadic-labs/cryptography/ocaml-bls12-381-hash/-/archive/0.0.5/ocaml-bls12-381-hash-0.0.5.tar.gz)
# path                 ~/.opam/5.0/.opam-switch/build/bls12-381-hash.0.0.5
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p bls12-381-hash -j 3
# exit-code            1
# env-file             ~/.opam/log/bls12-381-hash-8-7ae588.env
# output-file          ~/.opam/log/bls12-381-hash-8-7ae588.out
### output ###
# Error: No rule found for test/test_poseidon.exe
# -> required by alias test/runtest in test/dune:2
# Error: No rule found for test/test_rescue.exe
# -> required by alias test/runtest in test/dune:2
# Error: No rule found for test/test_anemoi.exe
# -> required by alias test/runtest in test/dune:2
# Error: No rule found for test/test_griffin.exe
# -> required by alias test/runtest in test/dune:2
```

**Comment by kit-ty-kate** [comment]
ah it’s an old package, nevermind

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
