### PR TITLE
LablGtk3 3.1.2 extra packages

### PR DESCRIPTION
**Pull request by garrigue**
These are packages associated with LablGtk3 (using the same tarball).
They were not included in #20311

### CODE REVIEW

**Comment by garrigue** [comment]
Note: lablgtk3-sourceview3 is needed to update CoqIde.

**Comment by mseri** [comment]
Before merging, do you know why coqide is not recognizing the version of lablgtk?
```
+ /home/opam/.opam/opam-init/hooks/sandbox.sh "build" "./configure" "-configdir" "/home/opam/.opam/4.13/lib/coq/config" "-prefix" "/home/opam/.opam/4.13" "-mandir" "/home/opam/.opam/4.13/man" "-docdir" "/home/opam/.opam/4.13/doc" "-libdir" "/home/opam/.opam/4.13/lib/coq" "-datadir" "/home/opam/.opam/4.13/share/coq" "-native-compiler" "no" (CWD=/home/opam/.opam/4.13/.opam-switch/build/coqide.8.13.2)
- You have OCaml 4.13.1. Good!
- You have OCamlfind 1.9.1. Good!
- You have native-code compilation. Good!
- You have the Zarith library 1.12 installed. Good!
- LablGtk3 and LablGtkSourceView3 found ([unspecified]), but too old (required >= 3.1.0, found [unspecified]):
- => no CoqIde will be built.
- 
-   Architecture                : Linux
-   Sys.os_type                 : Unix
-   Coq VM bytecode link flags  : -dllib -lcoqrun -dllpath /home/opam/.opam/4.13/lib/coq/kernel/byterun
-   Other bytecode link flags   : 
-   OCaml version               : 4.13.1
-   OCaml binaries in           : /home/opam/.opam/4.13/bin/
-   OCaml library in            : /home/opam/.opam/4.13/lib/ocaml
-   OCaml flambda flags         : 
-   Native dynamic link support : true
-   CoqIde                      : no
-   Documentation               : None
-   Web browser                 : firefox -remote "OpenURL(%s,new-tab)" || firefox %s &
-   Coq web site                : http://coq.inria.fr/
-   Bytecode VM enabled         : true
-   Native Compiler enabled     : no
```
Happens in all three of:
```
coqide.8.13.0 (failed: Error: The installation of coqide failed at "make COQ_USE_DUNE= install-ide-bin install-ide-files install-ide-info install-ide-devfiles".)
coqide.8.13.1 (failed: Error: The installation of coqide failed at "make COQ_USE_DUNE= install-ide-bin install-ide-files install-ide-info install-ide-devfiles".)
coqide.8.13.2 (failed: Error: The installation of coqide failed at "make COQ_USE_DUNE= install-ide-bin install-ide-files install-ide-info install-ide-devfiles".)```

**Comment by SkySkimmer** [comment]
That means `ocamlfind query -format %v lablgtk3` is printing `[unspecified]`.

**Comment by garrigue** [comment]
@kit-ty-kate Does it mean I need to do a new release of lablgtk3 with your patch ?

**Comment by kit-ty-kate** [comment]
of both lablgtk3 and the extra packages, I believe yes. Otherwise this will break coqide < 8.14.0 (in >= 8.14.0 the configure script still fails but somehow is ignored and dune builds just fine, but maybe something will be missing in the install)

**Comment by garrigue** [comment]
Rather than redoing all the work, I have added a patch to lablgtk3 in this PR.
Is this sufficient to fix things?

The basic problem might be that this time I did the release by hand, rather than using the semi-automated steps with dune-release, that in my experience resulted always in taking more time to fix things.

**Comment by kit-ty-kate** [comment]
> Is this sufficient to fix things?

The same patch is also required on the "extra" packages added by this release I believe

> The basic problem might be that this time I did the release by hand, rather than using the semi-automated steps with dune-release, that in my experience resulted always in taking more time to fix things.

Yes, this is the difference. `dune-release` automatically overwrites (using `dune subst`) the `(version ...)` field in the archive it creates then uploads.

**Comment by garrigue** [comment]
Well, at least it seems sufficient for Coq 8.13 and 8.14.
Do I redo a release, or is it OK for now?
Redoing a release with the same version number is not hard, but does opam properly update in that case?

**Comment by kit-ty-kate** [comment]
if it is sufficient then it's fine for now

**Comment by mseri** [comment]
Looks good now. Thanks for the help and the patience

**Pull request merged**
