### PR TITLE
delete ocsigen-start.0.99

### PR DESCRIPTION
**Pull request by pwbs**
because its dependencies are broken

	deleted:    packages/ocsigen-start/ocsigen-start.0.99/descr
	deleted:    packages/ocsigen-start/ocsigen-start.0.99/opam
	deleted:    packages/ocsigen-start/ocsigen-start.0.99/url

### CODE REVIEW

**Comment by avsm** [comment]
cc @vasilisp -- is this ok or can they be fixed with constraints?

**Comment by vasilisp** [comment]
@avsm 0.99 was a preview version,. Installing that one instead of 1.0.0 will cause more harm than good, so I am OK with deletion.

If you think it is better to keep it, maybe strengthening the OCaml version to `>= 4.02.2` would fix the issue (I would need to test). @pwbs do you have a link to a compilation failure?

**Comment by pw374** [comment]
I saw the problem yesterday on someone else's computer.
I'm counting on https://github.com/ocaml/opam-repository/pull/9190 to show evidence of the problem, as I don't wanna do `opam switch` on my own machine just to show this problem...

**Comment by pwbs** [comment]
Well, now we have evidence that it's quite broken:
https://travis-ci.org/ocaml/opam-repository/builds/232751374?utm_source=github_status&utm_medium=notification

**Comment by vasilisp** [comment]
That issue can be fixed with an `eliom <= 6.2.0` constraint.

**Comment by pwbs** [comment]
Anyways, it's probably not worth maintaining `ocsigen-start.0.99` since it's deprecated (and the `eliom <= 6.2.0` constraint might be insufficient?)

**Comment by vasilisp** [comment]
I endorse removal :).

**Pull request merged**
