### PR TITLE
nebula does not compile with latest tsdl

### PR DESCRIPTION
**Pull request by damiendoligez**

### CODE REVIEW

**Comment by hakuch** [comment]
Thanks for the notification, @yallop, and thanks for addressing this @damiendoligez. :-)

The change looks correct. Is there anything I can do to help here?

**Comment by damiendoligez** [comment]
The tests fail because two of the test machines are failing to install the external dependency `libsdl2-dev` for some reason...

**Comment by dbuenzli** [comment]
> are failing to install the external dependency libsdl2-dev for some reason...

The reason is that these packages do not exist in ubuntu 12.04. libsdl2 seems only supported from 15.10 on.

**Comment by dsheets** [comment]
Merging because our Travis instance is too old. Thanks for your help, everyone!

**Pull request merged**
