### PR TITLE
+webmachine.0.6.0

### PR DESCRIPTION
**Pull request by seliopou**

### CODE REVIEW

**Comment by samoht** [comment]
Thanks! Would you be able to add constraints to fix the revdeps failures? This is needed for datakit-ci and irmin-http.

**Comment by seliopou** [comment]
Done.

**Comment by seliopou** [comment]
Looks like it's failing now because `git-unix` is missing constraints on `cohttp` or some related module; and `irmin-unix` is failing because of a safe-string issue? The last one I'm not too sure about.

**Comment by samoht** [comment]
Thanks! I will fix the remaining issues in an other PR.

**Pull request merged**
