### PR TITLE
Added new fancy ppx_deriving_argparse.0.0.4

### PR DESCRIPTION
**Pull request by masashi-y**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There is a failure during the test phase:
```
#=== ERROR while installing ppx_deriving_argparse.0.0.1 =======================#
# opam-version 1.2.2
# os           linux
# command      ocamlbuild -classic-display -use-ocamlfind src_test/example.byte --
# path         /home/travis/.opam/4.06.1/build/ppx_deriving_argparse.0.0.1
# compiler     4.06.1
# exit-code    10
# env-file     /home/travis/.opam/4.06.1/build/ppx_deriving_argparse.0.0.1/ppx_deriving_argparse-16499-a71bb4.env
# stdout-file  /home/travis/.opam/4.06.1/build/ppx_deriving_argparse.0.0.1/ppx_deriving_argparse-16499-a71bb4.out
# stderr-file  /home/travis/.opam/4.06.1/build/ppx_deriving_argparse.0.0.1/ppx_deriving_argparse-16499-a71bb4.err
### stdout ###
# ocamlfind ocamldep -package result -package oUnit -modules src_test/example.ml > src_test/example.ml.depends
# + ocamlfind ocamldep -package result -package oUnit -modules src_test/example.ml > src_test/example.ml.depends
# ocamlfind: Package `oUnit' not found
# Command exited with code 2.
```

**Comment by masashi-y** [comment]
Hi, I have fixed the build issue.

**Comment by kit-ty-kate** [comment]
I think you forgot to update the checksum:
```
[ERROR] Bad checksum for
        /home/opam/.opam/packages.dev/ppx_deriving_argparse.0.0.1/0.0.1.tar.gz:
          - f4b8fb73268d6f5286fccd53587a5932 [expected result]
          - f840457a3f12c3bc5b3fd0c01227f3a8 [actual result]
        This may be fixed by running `opam update`.
```

**Comment by masashi-y** [comment]
Sorry for causing you troubles. Is it OK now?

**Comment by kit-ty-kate** [comment]
Unfortunately not, I still get the first problem:
```
#=== ERROR while installing ppx_deriving_argparse.0.0.1 =======================#
# opam-version 1.2.2
# os           linux
# command      ocamlbuild -classic-display -use-ocamlfind src_test/example.byte --
# path         /home/travis/.opam/4.05.0/build/ppx_deriving_argparse.0.0.1
# compiler     4.05.0
# exit-code    10
# env-file     /home/travis/.opam/4.05.0/build/ppx_deriving_argparse.0.0.1/ppx_deriving_argparse-16379-a71bb4.env
# stdout-file  /home/travis/.opam/4.05.0/build/ppx_deriving_argparse.0.0.1/ppx_deriving_argparse-16379-a71bb4.out
# stderr-file  /home/travis/.opam/4.05.0/build/ppx_deriving_argparse.0.0.1/ppx_deriving_argparse-16379-a71bb4.err
### stdout ###
# ocamlfind ocamldep -package result -package oUnit -modules src_test/example.ml > src_test/example.ml.depends
# + ocamlfind ocamldep -package result -package oUnit -modules src_test/example.ml > src_test/example.ml.depends
# ocamlfind: Package `oUnit' not found
# Command exited with code 2.
```

**Comment by masashi-y** [comment]
Now I believe it's ok.

**Comment by masashi-y** [comment]
Apologies... I fixed both of the issues. Please check again!

**Comment by kit-ty-kate** [comment]
Looks ok. Sorry for the delay. Thanks !

**Pull request merged**
