### PR TITLE
Add ocaml-glpk 0.1.7.

### PR DESCRIPTION
**Pull request by smimram**

### CODE REVIEW

**Comment by yallop** [comment]
The [4.04.0 build](https://travis-ci.org/ocaml/opam-repository/jobs/173295409) is failing:

```
# /home/travis/.opam/4.04.0+beta2/lib/ocaml/caml/alloc.h:65:21: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘caml_field_unboxed’
# [...]
# /home/travis/.opam/4.04.0+beta2/lib/ocaml/caml/alloc.h:66:1: error: unknown type name ‘inline’
#  static inline value caml_field_boxed (value arg) { return Field (arg, 0); }
#  ^
```

apparently because `gcc` is being invoked with `-ansi`

```
# ocamlc -c -cc "gcc" -ccopt "-fPIC -Wall -ansi -DCAML_NAME_SPACE -g \
# 				-DPIC   \
# 				 -Ioldapi/   -o oldapi/lpx.o " oldapi/lpx.c 
```

since `-ansi` means C89 mode, which doesn't support the `inline` keyword.  OCaml 4.04.0 requires a C99 compiler, as do extensions built for it.

**Comment by smimram** [comment]
I have disabled OCaml 4.04 for now. I'll try to do a new release soon.

**Comment by dsheets** [comment]
The homebrew depext is `homebrew/science/glpk` and it builds on OS X (locally) but with a number of warnings like:

```
oldapi/lpx.c:634:10: warning: variable 'status' is used uninitialized whenever
      switch default is taken [-Wsometimes-uninitialized]
         default:         xassert(lp != lp);
```

**Comment by smimram** [comment]
Thanks, I just added the homebrew dependency.

**Comment by yallop** [comment]
Thanks!

**Pull request merged**
