### PR TITLE
upper bounds for mirage-random

### PR DESCRIPTION
**Pull request by hannesm**
next release will break API, so nothing old will work anymore \o/

### CODE REVIEW

**Comment by hannesm** [comment]
I'm closing this, since it is not yet clear whether we actually need mirage-random.

**Comment by hannesm** [comment]
re-opening, the discussion about mirage-random needs more time -- so let's keep it and move ahead

**Comment by mseri** [comment]
So, should I merge this once the lint tells me it is ok?

**Comment by hannesm** [comment]
@mseri: yes please

**Pull request merged**
