### PR TITLE
Add minivpt lower bounds

### PR DESCRIPTION
**Pull request by jmid**
In #24677 there are lower bound failures in lower bound dependency... :sweat_smile: 
This causes:
```
#=== ERROR while compiling minivpt.2.0.0 ======================================#
# context              2.2.0~alpha3~dev | linux/x86_64 | ocaml-base-compiler.4.03.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.03/.opam-switch/build/minivpt.2.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build obuild build lib-minivpt
# exit-code            2
# env-file             ~/.opam/log/minivpt-7-cd9550.env
# output-file          ~/.opam/log/minivpt-7-cd9550.out
### output ###
# uncaught exception
# Fatal error: exception Failure("unknown option: lib-minivpt")
```

After having checked locally, this PR therefore adds a lower bound requirement of `obuild.0.0.3`

### CODE REVIEW

**Comment by jmid** [comment]
CI showed
- lbvs_consent failures (expected - and to be fixed by #24677)
- s390x failures with `No space left of device`

I've therefore restarted the failing jobs,

**Comment by jmid** [comment]
Still seeing
`s390x-ocaml-4.14 minivpt.1.0.0 (failed: Failed: Build failed)`
with the message
`fatal: cannot create directory at 'packages/camyll/camyll.0.3.0': No space left on device`

**Comment by mseri** [comment]
That’s a ci issue, don’t worry about it. Thanks for the fix

**Comment by mseri** [comment]
Minivpt now builds fine, thanks

**Pull request merged**
