### PR TITLE
Blacklist lablgtk3 3.0.beta7 also from Coq 8.10.{0,1}

### PR DESCRIPTION
**Pull request by Blaisorblade**
Workaround for coq/coq#11217; I've confirmed it affects those versions as well.

### CODE REVIEW

**Comment by mseri** [comment]
Does the issue affect only osx? In that casw should we use something linke
```
conflicts: ["lablgtk3-sourceview3" {= "3.0.beta7" & os-family = "macos"}
```
or it is not supported by opam?

CC @garrigue (fyi)

**Comment by Blaisorblade** [comment]
AFAIK the bug shouldn't be mac-specific, but I haven't confirmed yet. Should I split the PR so that testing can pass on Travis?

**Comment by ejgallego** [comment]
Indeed this bug is not mac-specific; note that 8.11 won't have this problem.

**Comment by mseri** [comment]
Thanks for the clarification

**Pull request merged**
