### PR TITLE
[new release] encore (0.3)

### PR DESCRIPTION
**Pull request by dinosaure**
Library to generate encoder/decoder which ensure isomorphism

- Project page: <a href="https://github.com/dinosaure/encore">https://github.com/dinosaure/encore</a>
- Documentation: <a href="https://dinosaure.github.io/encore/">https://dinosaure.github.io/encore/</a>

##### CHANGES:

- Fix OPAM file about how to ask to `dune` to build `encore` (@kit-ty-kate)
- Use `ke` as common implementation of ring-buffer
- Support of 4.07.0 in Travis CI
- Provide a C stubs to know if a bigarray overlaps an other
 * Compilation fixed with MirageOS (@hannesm)
- Tests about printer, parsers and combinators
- Add `from` function to let user to allocate internal buffer
- Use rev_iter instead fold and rev on internal queue
- Delete tag argument on bijection objects to be more usable
- Delete dependency of ocplib-endian and use bigstringaf instead
- Use angstrom.0.10.0 (@andreas)

### CODE REVIEW

**Comment by dinosaure** [comment]
Sorry for the inconvenience but CI should be fixed now, if someone can restart them :+1:

**Comment by kit-ty-kate** [comment]
`git.2.0.0` is not compatible:
```
#=== ERROR while compiling git.2.0.0 ==========================================#
# context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.07/.opam-switch/build/git.2.0.0
# command              ~/.opam/4.07/bin/dune build -p git -j 71
# exit-code            1
# env-file             ~/.opam/log/git-17-ac4cbb.env
# output-file          ~/.opam/log/git-17-ac4cbb.out
### output ###
#       ocamlc src/git/.git.objs/byte/git__Helper.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git/.git.objs/byte -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/checkseum -I /home/opam/.opam/4.07/lib/cstruct -I /home/opam/.opam/4.07/lib/decompress -I /home/opam/.opam/4.07/lib/decompress/impl -I /home/opam/.opam/4.07/lib/digestif -I /home/opam/.opam/4.07/lib/duff -I /home/opam/.opam/4.07/lib/encore -I /home/opam/.opam/4.07/lib/encore/butils -I /home/opam/.opam/4.07/lib/eqaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/fpath -I /home/opam/.opam/4.07/lib/hex -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/logs -I /home/opam/.opam/4.07/lib/lru -I /home/opam/.opam/4.07/lib/lwt -I /home/opam/.opam/4.07/lib/ocamlgraph -I /home/opam/.opam/4.07/lib/ocplib-endian -I /home/opam/.opam/4.07/lib/optint -I /home/opam/.opam/4.07/lib/psq -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/uri -intf-suffix .ml -no-alias-deps -open Git__ -o src/git/.git.objs/byte/git__Helper.cmo -c -impl src/git/helper.ml)
# File "src/git/helper.ml", line 44, characters 4-12:
# Error: This function has type
#          fwd:('a -> 'b) -> bwd:('b -> 'a) -> ('a, 'b) Encore.Bijection.texn
#        It is applied to too many arguments; maybe you forgot a `;'.
#       ocamlc src/git/.git.objs/byte/git__Blob.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git/.git.objs/byte -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/checkseum -I /home/opam/.opam/4.07/lib/cstruct -I /home/opam/.opam/4.07/lib/decompress -I /home/opam/.opam/4.07/lib/decompress/impl -I /home/opam/.opam/4.07/lib/digestif -I /home/opam/.opam/4.07/lib/duff -I /home/opam/.opam/4.07/lib/encore -I /home/opam/.opam/4.07/lib/encore/butils -I /home/opam/.opam/4.07/lib/eqaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/fpath -I /home/opam/.opam/4.07/lib/hex -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/logs -I /home/opam/.opam/4.07/lib/lru -I /home/opam/.opam/4.07/lib/lwt -I /home/opam/.opam/4.07/lib/ocamlgraph -I /home/opam/.opam/4.07/lib/ocplib-endian -I /home/opam/.opam/4.07/lib/optint -I /home/opam/.opam/4.07/lib/psq -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/uri -intf-suffix .ml -no-alias-deps -open Git__ -o src/git/.git.objs/byte/git__Blob.cmo -c -impl src/git/blob.ml)
# File "src/git/blob.ml", line 76, characters 10-18:
# Error: This expression has type
#          (< reta : ('a * 'a list, 'a * 'a list, Encore.Bijection.exn)
#                    Encore.Bijection.kind;
#             retb : ('a list, 'a list, Encore.Bijection.exn)
#                    Encore.Bijection.kind >,
#           'a * 'a list, 'a list)
#          Encore.Bijection.t
#        This is not a function; it cannot be applied.
#       ocamlc src/git/.git.objs/byte/git__User.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git/.git.objs/byte -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/checkseum -I /home/opam/.opam/4.07/lib/cstruct -I /home/opam/.opam/4.07/lib/decompress -I /home/opam/.opam/4.07/lib/decompress/impl -I /home/opam/.opam/4.07/lib/digestif -I /home/opam/.opam/4.07/lib/duff -I /home/opam/.opam/4.07/lib/encore -I /home/opam/.opam/4.07/lib/encore/butils -I /home/opam/.opam/4.07/lib/eqaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/fpath -I /home/opam/.opam/4.07/lib/hex -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/logs -I /home/opam/.opam/4.07/lib/lru -I /home/opam/.opam/4.07/lib/lwt -I /home/opam/.opam/4.07/lib/ocamlgraph -I /home/opam/.opam/4.07/lib/ocplib-endian -I /home/opam/.opam/4.07/lib/optint -I /home/opam/.opam/4.07/lib/psq -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/uri -intf-suffix .ml -no-alias-deps -open Git__ -o src/git/.git.objs/byte/git__User.cmo -c -impl src/git/user.ml)
# File "src/git/user.ml", line 43, characters 6-14:
# Error: This function has type
#          fwd:('a -> 'b) -> bwd:('b -> 'a) -> ('a, 'b) Encore.Bijection.texn
#        It is applied to too many arguments; maybe you forgot a `;'.
#     ocamlopt src/git/.git.objs/native/git__Helper.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlopt.opt -w -40 -g -I src/git/.git.objs/byte -I src/git/.git.objs/native -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/checkseum -I /home/opam/.opam/4.07/lib/cstruct -I /home/opam/.opam/4.07/lib/decompress -I /home/opam/.opam/4.07/lib/decompress/impl -I /home/opam/.opam/4.07/lib/digestif -I /home/opam/.opam/4.07/lib/duff -I /home/opam/.opam/4.07/lib/encore -I /home/opam/.opam/4.07/lib/encore/butils -I /home/opam/.opam/4.07/lib/eqaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/fpath -I /home/opam/.opam/4.07/lib/hex -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/logs -I /home/opam/.opam/4.07/lib/lru -I /home/opam/.opam/4.07/lib/lwt -I /home/opam/.opam/4.07/lib/ocamlgraph -I /home/opam/.opam/4.07/lib/ocplib-endian -I /home/opam/.opam/4.07/lib/optint -I /home/opam/.opam/4.07/lib/psq -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/uri -intf-suffix .ml -no-alias-deps -open Git__ -o src/git/.git.objs/native/git__Helper.cmx -c -impl src/git/helper.ml)
# File "src/git/helper.ml", line 44, characters 4-12:
# Error: This function has type
#          fwd:('a -> 'b) -> bwd:('b -> 'a) -> ('a, 'b) Encore.Bijection.texn
#        It is applied to too many arguments; maybe you forgot a `;'.
#       ocamlc src/git/.git.objs/byte/git__Reference.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git/.git.objs/byte -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/checkseum -I /home/opam/.opam/4.07/lib/cstruct -I /home/opam/.opam/4.07/lib/decompress -I /home/opam/.opam/4.07/lib/decompress/impl -I /home/opam/.opam/4.07/lib/digestif -I /home/opam/.opam/4.07/lib/duff -I /home/opam/.opam/4.07/lib/encore -I /home/opam/.opam/4.07/lib/encore/butils -I /home/opam/.opam/4.07/lib/eqaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/fpath -I /home/opam/.opam/4.07/lib/hex -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/logs -I /home/opam/.opam/4.07/lib/lru -I /home/opam/.opam/4.07/lib/lwt -I /home/opam/.opam/4.07/lib/ocamlgraph -I /home/opam/.opam/4.07/lib/ocplib-endian -I /home/opam/.opam/4.07/lib/optint -I /home/opam/.opam/4.07/lib/psq -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/uri -intf-suffix .ml -no-alias-deps -open Git__ -o src/git/.git.objs/byte/git__Reference.cmo -c -impl src/git/reference.ml)
# File "src/git/reference.ml", line 211, characters 8-16:
# Error: This function has type
#          fwd:('a -> 'b) -> bwd:('b -> 'a) -> ('a, 'b) Encore.Bijection.texn
#        It is applied to too many arguments; maybe you forgot a `;'.
#       ocamlc src/git/.git.objs/byte/git__Tree.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git/.git.objs/byte -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/checkseum -I /home/opam/.opam/4.07/lib/cstruct -I /home/opam/.opam/4.07/lib/decompress -I /home/opam/.opam/4.07/lib/decompress/impl -I /home/opam/.opam/4.07/lib/digestif -I /home/opam/.opam/4.07/lib/duff -I /home/opam/.opam/4.07/lib/encore -I /home/opam/.opam/4.07/lib/encore/butils -I /home/opam/.opam/4.07/lib/eqaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/fpath -I /home/opam/.opam/4.07/lib/hex -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/logs -I /home/opam/.opam/4.07/lib/lru -I /home/opam/.opam/4.07/lib/lwt -I /home/opam/.opam/4.07/lib/ocamlgraph -I /home/opam/.opam/4.07/lib/ocplib-endian -I /home/opam/.opam/4.07/lib/optint -I /home/opam/.opam/4.07/lib/psq -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/uri -intf-suffix .ml -no-alias-deps -open Git__ -o src/git/.git.objs/byte/git__Tree.cmo -c -impl src/git/tree.ml)
# File "src/git/tree.ml", line 231, characters 8-16:
# Error: This function has type
#          fwd:('a -> 'b) -> bwd:('b -> 'a) -> ('a, 'b) Encore.Bijection.texn
#        It is applied to too many arguments; maybe you forgot a `;'.
#       ocamlc src/git/.git.objs/byte/git__Commit.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git/.git.objs/byte -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/checkseum -I /home/opam/.opam/4.07/lib/cstruct -I /home/opam/.opam/4.07/lib/decompress -I /home/opam/.opam/4.07/lib/decompress/impl -I /home/opam/.opam/4.07/lib/digestif -I /home/opam/.opam/4.07/lib/duff -I /home/opam/.opam/4.07/lib/encore -I /home/opam/.opam/4.07/lib/encore/butils -I /home/opam/.opam/4.07/lib/eqaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/fpath -I /home/opam/.opam/4.07/lib/hex -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/logs -I /home/opam/.opam/4.07/lib/lru -I /home/opam/.opam/4.07/lib/lwt -I /home/opam/.opam/4.07/lib/ocamlgraph -I /home/opam/.opam/4.07/lib/ocplib-endian -I /home/opam/.opam/4.07/lib/optint -I /home/opam/.opam/4.07/lib/psq -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/uri -intf-suffix .ml -no-alias-deps -open Git__ -o src/git/.git.objs/byte/git__Commit.cmo -c -impl src/git/commit.ml)
# File "src/git/commit.ml", line 92, characters 8-16:
# Error: This function has type
#          fwd:('a -> 'b) -> bwd:('b -> 'a) -> ('a, 'b) Encore.Bijection.texn
#        It is applied to too many arguments; maybe you forgot a `;'.
#       ocamlc src/git/.git.objs/byte/git__Tag.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git/.git.objs/byte -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/checkseum -I /home/opam/.opam/4.07/lib/cstruct -I /home/opam/.opam/4.07/lib/decompress -I /home/opam/.opam/4.07/lib/decompress/impl -I /home/opam/.opam/4.07/lib/digestif -I /home/opam/.opam/4.07/lib/duff -I /home/opam/.opam/4.07/lib/encore -I /home/opam/.opam/4.07/lib/encore/butils -I /home/opam/.opam/4.07/lib/eqaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/fpath -I /home/opam/.opam/4.07/lib/hex -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/logs -I /home/opam/.opam/4.07/lib/lru -I /home/opam/.opam/4.07/lib/lwt -I /home/opam/.opam/4.07/lib/ocamlgraph -I /home/opam/.opam/4.07/lib/ocplib-endian -I /home/opam/.opam/4.07/lib/optint -I /home/opam/.opam/4.07/lib/psq -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/uri -intf-suffix .ml -no-alias-deps -open Git__ -o src/git/.git.objs/byte/git__Tag.cmo -c -impl src/git/tag.ml)
# File "src/git/tag.ml", line 99, characters 8-16:
# Error: This function has type
#          fwd:('a -> 'b) -> bwd:('b -> 'a) -> ('a, 'b) Encore.Bijection.texn
#        It is applied to too many arguments; maybe you forgot a `;'.
#       ocamlc src/git/.git.objs/byte/git__Value.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git/.git.objs/byte -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/checkseum -I /home/opam/.opam/4.07/lib/cstruct -I /home/opam/.opam/4.07/lib/decompress -I /home/opam/.opam/4.07/lib/decompress/impl -I /home/opam/.opam/4.07/lib/digestif -I /home/opam/.opam/4.07/lib/duff -I /home/opam/.opam/4.07/lib/encore -I /home/opam/.opam/4.07/lib/encore/butils -I /home/opam/.opam/4.07/lib/eqaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/fpath -I /home/opam/.opam/4.07/lib/hex -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/logs -I /home/opam/.opam/4.07/lib/lru -I /home/opam/.opam/4.07/lib/lwt -I /home/opam/.opam/4.07/lib/ocamlgraph -I /home/opam/.opam/4.07/lib/ocplib-endian -I /home/opam/.opam/4.07/lib/optint -I /home/opam/.opam/4.07/lib/psq -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/uri -intf-suffix .ml -no-alias-deps -open Git__ -o src/git/.git.objs/byte/git__Value.cmo -c -impl src/git/value.ml)
# File "src/git/value.ml", line 186, characters 8-16:
# Error: This function has type
#          fwd:('a -> 'b) -> bwd:('b -> 'a) -> ('a, 'b) Encore.Bijection.texn
#        It is applied to too many arguments; maybe you forgot a `;'.
#       ocamlc src/git/.git.objs/byte/git__Sync.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git/.git.objs/byte -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/astring -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/checkseum -I /home/opam/.opam/4.07/lib/cstruct -I /home/opam/.opam/4.07/lib/decompress -I /home/opam/.opam/4.07/lib/decompress/impl -I /home/opam/.opam/4.07/lib/digestif -I /home/opam/.opam/4.07/lib/duff -I /home/opam/.opam/4.07/lib/encore -I /home/opam/.opam/4.07/lib/encore/butils -I /home/opam/.opam/4.07/lib/eqaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/fpath -I /home/opam/.opam/4.07/lib/hex -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/logs -I /home/opam/.opam/4.07/lib/lru -I /home/opam/.opam/4.07/lib/lwt -I /home/opam/.opam/4.07/lib/ocamlgraph -I /home/opam/.opam/4.07/lib/ocplib-endian -I /home/opam/.opam/4.07/lib/optint -I /home/opam/.opam/4.07/lib/psq -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/uri -intf-suffix .ml -no-alias-deps -open Git__ -o src/git/.git.objs/byte/git__Sync.cmo -c -impl src/git/sync.ml)
# File "src/git/sync.ml", line 181, characters 13-26:
# Error: Unbound module Encore.FQueue
```

**Comment by mseri** [comment]
It was timing out in multiple tests. Rerunning them fixed a few. I have just restareted the one 5(@5 failed again (ocaml 4.04)  to double check if that also is transient

**Comment by dinosaure** [comment]
Close to prepare an other release :+1: sorry for the noise. Then, about the time-out of the solver, how I should fix it?

**Pull request closed without merging**
