### PR TITLE
[new release] ocamlformat (0.12)

### PR DESCRIPTION
**Pull request by Julow**
Auto-formatter for OCaml code

- Project page: <a href="https://github.com/ocaml-ppx/ocamlformat">https://github.com/ocaml-ppx/ocamlformat</a>

CHANGES:

#### Changes

  + Set "conventional" as the default profile (ocaml-ppx/ocamlformat#1060) (Guillaume Petiot)
    This new profile is made to better match the most used style and is encouraged.
    To continue using the previous default, use `profile = ocamlformat` in your `.ocamlformat`.
  + CLI: Allow both values of boolean options (ocaml-ppx/ocamlformat#1062) (Jules Aguillon)
    Now, both `--opt` and --no-opt` are available on the CLI for any boolean option "opt".
    Previously, only one of them were available depending on the default value.
  + Auto mode for `break-string-literals` (ocaml-ppx/ocamlformat#1057) (Guillaume Petiot)
    `wrap`, `newlines` and `newlines-and-wrap` values of `break-string-literals` are removed.
    `auto` replaces them, it is equivalent to `newlines-and-wrap`.
  + Dock collection brackets (ocaml-ppx/ocamlformat#1014) (Guillaume Petiot)
    `after-and-docked` value of `break-separators` is removed and is replaced by a new `dock-collection-brackets` option.
  + Preserve `begin` and `end` keywords in if-then-else (ocaml-ppx/ocamlformat#978) (Jules Aguillon)
    Previously, `begin`/`end` keywords around if-then-else branches were turned into parentheses.

#### New features

  + Give a hint when warning 50 is raised (ocaml-ppx/ocamlformat#1111) (Guillaume Petiot)
  + Add a message when a config value is removed (ocaml-ppx/ocamlformat#1089) (Etienne Millon)
    Explain what replaces removed options and avoid printing a parsing error.
  + Implement `sequence-blank-line=preserve-one` for let bindings (ocaml-ppx/ocamlformat#1077) (Jules Aguillon)
    Preserve a blank line after `let .. in` when `sequence-blank-line` set to `preserve-one`.
    Previously, only blank lines after `;` could be preserved.
  + Parse toplevel directives (ocaml-ppx/ocamlformat#1020) (Jules Aguillon)
    Allow `#directives` in `.ml` files.
    Previously, files containing a directive needed to be parsed as "use file".
    The "use file" mode is removed and `--use-file` is now the same as `--impl`.
  + Don't require `--name`, require kind, forbid `--inplace`, allow `--check`, make `--enable-outside-detected-project` implicit when reading from stdin (ocaml-ppx/ocamlformat#1018) (Guillaume Petiot)
  + Parse code in docstrings (ocaml-ppx/ocamlformat#941) (Guillaume Petiot)
    Format OCaml code in cinaps-style comments `(*$ code *)` and code blocks in documentation comments `(** {[ code ]} *)`.
  + Parse documentation comments with Odoc (ocaml-ppx/ocamlformat#721) (Jules Aguillon)
    Formatting of documentation comments is more robust and support newer Odoc syntaxes.
    Internally, Odoc replaces Octavius as the documentation parser.

#### Bug fixes

  + Fix unstabilizing comments on assignments (ocaml-ppx/ocamlformat#1093) (Guillaume Petiot)
  + Fix the default value documentation for `max-indent` (ocaml-ppx/ocamlformat#1105) (Guillaume Petiot)
  + Fix closing parenthesis exceeding the margin in function application (ocaml-ppx/ocamlformat#1098) (Jules Aguillon)
  + Missing break before attributes of `Pmty_with` (ocaml-ppx/ocamlformat#1103) (Josh Berdine)
  + Fix closing quote exceeding the margin (ocaml-ppx/ocamlformat#1096) (Jules Aguillon)
  + Fix break before the closing bracket of collections (exceeding the margin) (ocaml-ppx/ocamlformat#1073) (Guillaume Petiot)
  + Fix precedence of Dot wrt Hash (ocaml-ppx/ocamlformat#1058) (Guillaume Petiot)
  + Fix break in variant type definition to not exceed the margin (ocaml-ppx/ocamlformat#1064) (Guillaume Petiot)
  + Fix newlines and indentation in toplevel extension points (ocaml-ppx/ocamlformat#1054) (Guillaume Petiot)
  + Fix placement of doc comments around extensions (ocaml-ppx/ocamlformat#1052) (Jules Aguillon)
  + Inline extensions that do not break (ocaml-ppx/ocamlformat#1050) (Guillaume Petiot)
  + Add missing cut before attributes in type declarations (ocaml-ppx/ocamlformat#1051) (Guillaume Petiot)
  + Fix alignment of cases (ocaml-ppx/ocamlformat#1046) (Guillaume Petiot)
  + Fix blank line after comments at the end of lists (ocaml-ppx/ocamlformat#1045) (Guillaume Petiot)
  + Fix indexing operators precedence (ocaml-ppx/ocamlformat#1039) (Jules Aguillon)
  + Fix dropped comment after infix op (ocaml-ppx/ocamlformat#1030) (Guillaume Petiot)
  + No newline if the input is empty (ocaml-ppx/ocamlformat#1031) (Guillaume Petiot)
  + Fix unstable comments around attributes (ocaml-ppx/ocamlformat#1029) (Guillaume Petiot)
  + Fix extra blank line in sequence (ocaml-ppx/ocamlformat#1021) (Jules Aguillon)
  + Check functor arguments when computing placement of doc comments (ocaml-ppx/ocamlformat#1013) (Jules Aguillon)
  + Fix indentation of labelled args (ocaml-ppx/ocamlformat#1006) (Guillaume Petiot)
  + Fix linebreak between or-cases with comments when `break-cases=all` (ocaml-ppx/ocamlformat#1002) (Guillaume Petiot)
  + Fix unstable unattached doc comment in records (ocaml-ppx/ocamlformat#998) (Jules Aguillon)
  + Fix string literal changed (ocaml-ppx/ocamlformat#995) (Jules Aguillon)
  + Fix type variable (ocaml-ppx/ocamlformat#996) (Jules Aguillon)
  + Fix crash on extension sequence (ocaml-ppx/ocamlformat#992) (Guillaume Petiot)
  + Fix position of expressions regarding of comments in infix-op expressions (ocaml-ppx/ocamlformat#986) (Guillaume Petiot)
  + Escape special characters in external declaration (ocaml-ppx/ocamlformat#988) (Jules Aguillon)
  + Fix parens around constrained expr with attrs (ocaml-ppx/ocamlformat#987) (Guillaume Petiot)
  + Fix the margin, and correctly breaks comments (ocaml-ppx/ocamlformat#957) (Guillaume Petiot)
  + Fix formatting of custom indexing operators (ocaml-ppx/ocamlformat#975) (Guillaume Petiot)
  + Fix position of comments of labelled arrow types (ocaml-ppx/ocamlformat#976) (Guillaume Petiot)
  + No box around inline odoc styles (ocaml-ppx/ocamlformat#971) (Guillaume Petiot)
  + Fix boxing of collection expressions/patterns (ocaml-ppx/ocamlformat#960) (Guillaume Petiot)
  + Fix crash on record expr with pack fields (ocaml-ppx/ocamlformat#963) (Jules Aguillon)
  + Fix letop in subexpr (ocaml-ppx/ocamlformat#956) (hhugo)

#### Internal

  + Take file kind from --name when formatting stdin (ocaml-ppx/ocamlformat#1119) (Jules Aguillon)
  + Make Fmt.t abstract (ocaml-ppx/ocamlformat#1109) (Jules Aguillon)
  + Future-proof Fmt API in case Fmt.t goes abstract (ocaml-ppx/ocamlformat#1106) (Etienne Millon)
  + Future-proof `Fmt` API in case `Fmt.t` goes abstract (ocaml-ppx/ocamlformat#1106) (Etienne Millon)
  + Optional names for formatting boxes in debug output (ocaml-ppx/ocamlformat#1083) (Guillaume Petiot)
  + Check ocamlformat error codes in the testsuite (ocaml-ppx/ocamlformat#1084) (Etienne Millon)
  + Clean `Translation_unit` (ocaml-ppx/ocamlformat#1078) (Guillaume Petiot)
  + Use dune file generation in test/passing/dune (ocaml-ppx/ocamlformat#1082) (Etienne Millon)
  + CI: factorize tests and check reason build (ocaml-ppx/ocamlformat#1079) (Guillaume Petiot)
  + Use short form for action in src/dune (ocaml-ppx/ocamlformat#1076) (Etienne Millon)
  + Cleanup `sequence_blank_line` (ocaml-ppx/ocamlformat#1075) (Jules Aguillon)
  + CI: use a script travis-ci.sh to simplify .travis.yml (ocaml-ppx/ocamlformat#1063) (Guillaume Petiot)
  + Remove utility functions from `Fmt_ast` (ocaml-ppx/ocamlformat#1059) (Guillaume Petiot)
  + CI: use opam-2.0.5 in Travis (ocaml-ppx/ocamlformat#1044) (Anton Kochkov)
  + CI: check the build with OCaml 4.07.1 and 4.08.0 (ocaml-ppx/ocamlformat#1036) (Jules Aguillon)
  + Use the same sets of options for both branches by default in `test_branch.sh` (ocaml-ppx/ocamlformat#1033) (Guillaume Petiot)
  + Fix `test_branch.sh` and CI checking of CHANGES.md (ocaml-ppx/ocamlformat#1032, ocaml-ppx/ocamlformat#1034) (Jules Aguillon)
  + Fix flag of git-worktree in `test_branch.sh` and `bisect.sh` (ocaml-ppx/ocamlformat#1027) (Guillaume Petiot)
  + Remove the `bisect_ppx` dependency and clean the `Makefile` (ocaml-ppx/ocamlformat#1005) (Jules Aguillon)
  + Use a `CHANGES.md` log file again (ocaml-ppx/ocamlformat#1023) (Guillaume Petiot)
  + Support OCaml 4.09.0 (add the odoc.1.4.2 dependency) (ocaml-ppx/ocamlformat#1024) (Guillaume Petiot)
  + Update labels of issue templates (ocaml-ppx/ocamlformat#1017) (Guillaume Petiot)
  + Update labels in `CONTRIBUTING.md` (ocaml-ppx/ocamlformat#1007) (Guillaume Petiot)
  + Allow to ignore invalid options (ocaml-ppx/ocamlformat#984) (hhugo)
    The `--ignore-invalid-option` flag is added to ignore invalid options in `.ocamlformat` files.
  + Improve the documentation of `--doc-comments` (ocaml-ppx/ocamlformat#982) (Jules Aguillon)
  + Remove symbolic links and change naming convention of tests (ocaml-ppx/ocamlformat#980) (Guillaume Petiot)
  + Change the type of `fmt_code` (ocaml-ppx/ocamlformat#974) (Guillaume Petiot)
  + Simplify `Makefile` (ocaml-ppx/ocamlformat#973) (hhugo)
  + Dune should not be flagged as a build dep anymore (ocaml-ppx/ocamlformat#954) (Guillaume Petiot)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There is a revdeps failure on ppx_mysql. Could you have a look?
```
#=== ERROR while compiling ppx_mysql.1.1 ======================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.09.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.09/.opam-switch/build/ppx_mysql.1.1
# command              ~/.opam/4.09/bin/dune runtest -p ppx_mysql -j 2
# exit-code            1
# env-file             ~/.opam/log/ppx_mysql-25-83ed9b.env
# output-file          ~/.opam/log/ppx_mysql-25-83ed9b.out
### output ###
#  ocamlformat tests/test_ppx/test_ppx.expected.reformatted.ml (exit 2)
# (cd _build/default/tests/test_ppx && /home/opam/.opam/4.09/bin/ocamlformat test_ppx.expected.ml -o test_ppx.expected.reformatted.ml)
# Fatal error: exception ("User Error: malformed .ocamlformat file"
#   ("bad value for"
#     (break-string-literals
#       "value `wrap` has been removed in version 0.12. It has been replaced by the new default `auto` value, which breaks lines at newlines and wraps string literals at the margin."))
#   ("bad value for"
#     (break-separators
#       "value `after-and-docked` has been removed in version 0.12. One can get a similar behaviour by setting `break-separators=after`, `space-around-lists=false`, and `dock-dollection-brackets=false`.")))
# Raised at file "src/error.ml" (inlined), line 9, characters 14-30
# Called from file "src/error.ml", line 11, characters 19-40
# Called from file "src/exn.ml", line 66, characters 8-11
# Re-raised at file "src/exn.ml", line 69, characters 6-15
# Called from file "src/Conf.ml", line 1919, characters 6-1023
# Called from file "list.ml", line 121, characters 24-34
# Called from file "src/list0.ml" (inlined), line 22, characters 40-81
# Called from file "src/Conf.ml", line 2069, characters 4-45
# Called from file "src/Conf.ml", line 99, characters 14-18
# Called from file "src/Conf.ml", line 2106, characters 4-61
# Called from file "src/Conf.ml", line 2149, characters 20-69
#  ocamlformat tests/test_ppx/test_ppx.result.reformatted.ml (exit 2)
# (cd _build/default/tests/test_ppx && /home/opam/.opam/4.09/bin/ocamlformat test_ppx.result.ml -o test_ppx.result.reformatted.ml)
# Fatal error: exception ("User Error: malformed .ocamlformat file"
#   ("bad value for"
#     (break-string-literals
#       "value `wrap` has been removed in version 0.12. It has been replaced by the new default `auto` value, which breaks lines at newlines and wraps string literals at the margin."))
#   ("bad value for"
#     (break-separators
#       "value `after-and-docked` has been removed in version 0.12. One can get a similar behaviour by setting `break-separators=after`, `space-around-lists=false`, and `dock-dollection-brackets=false`.")))
# Raised at file "src/error.ml" (inlined), line 9, characters 14-30
# Called from file "src/error.ml", line 11, characters 19-40
# Called from file "src/exn.ml", line 66, characters 8-11
# Re-raised at file "src/exn.ml", line 69, characters 6-15
# Called from file "src/Conf.ml", line 1919, characters 6-1023
# Called from file "list.ml", line 121, characters 24-34
# Called from file "src/list0.ml" (inlined), line 22, characters 40-81
# Called from file "src/Conf.ml", line 2069, characters 4-45
# Called from file "src/Conf.ml", line 99, characters 14-18
# Called from file "src/Conf.ml", line 2106, characters 4-61
# Called from file "src/Conf.ml", line 2149, characters 20-69
#   test_query alias tests/test_query/runtest
# tput: No value for $TERM and no -T specified
# stty: 'standard input': Inappropriate ioctl for device
# Testing Query module.
# This run has ID `BC8389AF-B3E1-4936-8AB3-912B37605E95`.
#  ...                Query          0   parse_query.
[OK]                Query          0   parse_query.
#  ...                Query          1   remove_duplicates.
[OK]                Query          1   remove_duplicates.
# The full test results are available in `/home/opam/.opam/4.09/.opam-switch/build/ppx_mysql.1.1/_build/default/tests/test_query/_build/_tests/BC8389AF-B3E1-4936-8AB3-912B37605E95`.
# Test Successful in 0.000s. 2 tests run.
```

**Comment by Julow** [comment]
That error is expected, an option has been removed.
I didn't expect ocamlformat to be a test dependency, especially unbounded.
Should I add version constraint in that package description ?

**Comment by kit-ty-kate** [comment]
> That error is expected, an option has been removed.
> I didn't expect ocamlformat to be a test dependency, especially unbounded.
> Should I add version constraint in that package description ?

If you can that'd be perfect. Otherwise I'll do it later

**Comment by Julow** [comment]
Just did.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
