### PR TITLE
Cpdf unsafe string fix

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
looks OK to merge

**Comment by mseri** [comment]
If this was to release an ocaml binary only, I would have no trouble merging it straight away, however this package also provides (from the git repo README)

> b) cpdf as an OCaml library.

I know of many instances in which mixing libraries using `-unsafe-string` and `-safe-string` produces cmi conflicts and makes the library unusable with `ocaml >= 4.06.0`, we had to port a great deals of libraries for `xapi` to make sure that we could avoid mixing the flags and have everything building. From my past experience I believe the CI is green mostly because there is no other package in opam that depends on this.

I'd like to have the other maintainers opinion on this matter, and understand if we have any kind of default policy on this. Ping @kit-ty-kate

**Comment by UnixJunkie** [comment]
@johnwhitington

**Comment by kit-ty-kate** [comment]
Your patch doesn't seem to have worked
```
#=== ERROR while compiling cpdf.2.2.1 =========================================#
# context              2.0.0~rc3 | linux/x86_64 | ocaml-base-compiler.4.06.1 | pinned(https://github.com/johnwhitington/cpdf-source/archive/v2.2.1.zip)
# path                 ~/.opam/4.06/.opam-switch/build/cpdf.2.2.1
# command              /usr/bin/make
# exit-code            2
# env-file             ~/.opam/log/cpdf-19-777834.env
# output-file          ~/.opam/log/cpdf-19-777834.out
### output ###
# make[1]: Entering directory '/home/opam/.opam/4.06/.opam-switch/build/cpdf.2.2.1'
# ocamlfind ocamldep -native cpdfcommand.mli > ._ncdi/cpdfcommand.di
# ocamlfind ocamldep -native cpdf.mli > ._ncdi/cpdf.di
# ocamlfind ocamldep -native cpdfstrftime.mli > ._ncdi/cpdfstrftime.di
# ocamlfind ocamldep -native xmlm.mli > ._ncdi/xmlm.di
# ocamlfind ocamldep cpdfcommandrun.ml > ._d/cpdfcommandrun.d
# ocamlfind ocamldep cpdfcommand.ml > ._d/cpdfcommand.d
# ocamlfind ocamldep cpdf.ml > ._d/cpdf.d
# ocamlfind ocamldep cpdfstrftime.ml > ._d/cpdfstrftime.d
# ocamlfind ocamldep xmlm.ml > ._d/xmlm.d
# ocamlfind ocamlc -package camlpdf -c -annot xmlm.mli
# ocamlfind ocamlopt -package camlpdf -c -annot -g -w -3 -annot xmlm.ml
# File "xmlm.ml", line 965, characters 19-47:
# Error: This expression has type string -> int -> int -> unit
#        but an expression was expected of type bytes -> int -> int -> unit
#        Type string is not compatible with type bytes 
# OCamlMakefile:1076: recipe for target 'xmlm.cmx' failed
# make[1]: *** [xmlm.cmx] Error 2
# make[1]: Leaving directory '/home/opam/.opam/4.06/.opam-switch/build/cpdf.2.2.1'
# OCamlMakefile:777: recipe for target 'native-code' failed
# make: *** [native-code] Error 2
```

**Comment by kit-ty-kate** [comment]
IMHO the best way of doing that if you really want to use unsafe-strings is to do `["env" "OCAMLPARAM=safe-string=0,_" make]` instead of `make`. That has the advantage to not require any patches and to be portable across different versions of the compiler

**Comment by pmetzger** [comment]
There is already discussion of eliminating the unsafe strings option from the compiler in an upcoming release. I'd suggest that the right thing to do is to patch the program to use bytes in appropriate places. I've done it a couple of times and it was pretty straightforward each time — the compiler tells you where you need to fix things after all.

**Comment by UnixJunkie** [comment]
@pmetzger upstream already knows about the problem, we just try to unbreak a previously working package here

**Comment by kit-ty-kate** [comment]
@UnixJunkie can you remove my deadname from your commit message please? My name is Kate.

**Comment by pmetzger** [comment]
> upstream already knows about the problem, we just try to unbreak a previously working package here

My fear is that the library will cause trouble, as @mseri has also explained. Could you try just creating appropriate patches for the program? It might only take a few minutes. Then they can be incorporated into the opam package with the patch facility until upstream creates a new release based on your patches.

**Comment by johnwhitington** [comment]
@pmetzeger I have a patch from @alainfrisch for `camlpdf`.

The actual changes to `cpdf` to use the alain's new camlpdf patches are, as you suspect, trivial.

However, it breaks `cpdf` for me (produces invalid PDF files for some of the test suite). Until I untangle that, which will take time, we can't fix `cpdf` directly.

**Comment by pmetzger** [comment]
> However, it breaks cpdf for me (produces invalid PDF files for some of the test suite). Until I untangle that, which will take time, we can't fix cpdf directly.

How odd. That does make things more complicated, though.

**Comment by mseri** [comment]
Are the patches available to see somewhere?

**Comment by johnwhitington** [comment]
Here's the camlpdf patch:

https://github.com/johnwhitington/camlpdf/pull/23

For `cpdf`, it looks like all you have to do is bring in a new `xmlm.ml` and alter the makefile to change `-unsafe-string` to `-safe-string`. No changes to the `cpdf` code itself.

**Comment by UnixJunkie** [comment]
@kit-ty-kate I tried but it does not work.
Can you give me the exact sequence of git commands to do that?
Or, should I just delete the branch and close this PR?

**Comment by kit-ty-kate** [comment]
@UnixJunkie 
```
$ git rebase -i HEAD^^
(* use reword, save, amend the commit *)
(* fix the conflicts if any *)
$ git rebase --continue
```
You could also squash everything in one commit or redo a PR if you prefer.

**Comment by UnixJunkie** [comment]
OK, superseded by
https://github.com/ocaml/opam-repository/pull/12411

**Comment by kit-ty-kate** [comment]
Sorry to be picky but could you also `get reset --hard` this branch so the commit doesn't appear anymore?

**Comment by kit-ty-kate** [comment]
Ok whatever it's done.

**Pull request closed without merging**
