### PR TITLE
3 packages from gitlab.inria.fr/fpottier/menhir/repository/20210419/archive.tar.gz

### PR DESCRIPTION
**Pull request by fpottier**
This pull-request concerns:
-`menhir.20210419`: An LR(1) parser generator
-`menhirLib.20210419`: Runtime support library for parsers generated by Menhir
-`menhirSdk.20210419`: Compile-time library for auxiliary tools related to
 Menhir

---
* Homepage: http://gitlab.inria.fr/fpottier/menhir
* Source repo: git+https://gitlab.inria.fr/fpottier/menhir.git
* Bug tracker: https://gitlab.inria.fr/fpottier/menhir/-/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by gasche** [comment]
I just got a CI failure due to a bad-checksum error.

The `opam` file for Menhir says:

```
url {
  src:
    "https://gitlab.inria.fr/fpottier/menhir/repository/20210419/archive.tar.gz"
  checksum: [
    "md5=1af2d137eb20811c74ca516500164fd4"
    "sha512=37a88b3ea0bde6089e5fbf0c1f10c1867c4edcd033ed3d5b75e7ed93e14ddd4f4c4db96baf638a054f65e294b83411497615c7fc14c6ff3a2a007e70f9d12c98"
  ]
}
```

My terminal says:

```
$ wget https://gitlab.inria.fr/fpottier/menhir/repository/20210419/archive.tar.gz
$ md5sum archive.tar.gz 
b91030d62e5a6f438e75834b23d03689  archive.tar.gz
$ sha512sum archive.tar.gz 
51484ff86b806912674946d1e9f2978e32ee3ee6d2b31f911a2ebf295c04afe7c4f67d6a4bd68fcda7f16ac65a4c9cef31b3da0115dbf261ee98270aef0f3aab  archive.tar.gz
```

It looks like something is wrong. It could be that @fpottier changed the archives after the fact, or that his git host (gitlab.inria.fr) changed its archive-generation algorithm after the release. (The latter option is worrying as it could invalidate more packages from François and others.)

**Comment by gasche** [comment]
Ah, @fpottier just replied on the project-with-failing-CI:

> No. There is a problem with gitlab.inria.fr: all archives are now behind an authentication barrier. I have reported the problem.

**Comment by gasche** [comment]
@fpottier: my suspicion is that gitlab.inria.fr changed its archive-distribution format, now instead of 

```
https://gitlab.inria.fr/fpottier/menhir/-/archive/20210419/archive.tar.gz
```

you are supposed to access

```
https://gitlab.inria.fr/fpottier/menhir/-/archive/20210419/menhir-20210419.tar.gz
```

There is an HTML redirection (or something) from the former URL to the new one (or actually a different scheme `<project name>-<tag>-<commit hash>.tar.gz`), and we get the HTML of the redirection page or something.

**Comment by fpottier** [comment]
The HTML text that I get with `wget` looks like an authentication page to me, not a redirection. Anyway, we will see.

**Comment by gasche** [comment]
Actually I confused above the URL

```
https://gitlab.inria.fr/fpottier/menhir/-/archive/20210419/archive.tar.gz
```

which is still working, and the URL you actually used in the opam file

```
https://gitlab.inria.fr/fpottier/menhir/repository/20210419/archive.tar.gz
```

which is now a 404 or something.

"We will see": well yes, but right now anyone using Menhir in their codebase (or all other software you optimistically host on gitlab.inria.fr) and using standard CI practices to test their code is seeing CI failures until we do see...

```
$ opam search --depends-on menhir,pprint,fix,visitors | wc -l
138
```

**Comment by fpottier** [comment]
Thanks for pointing this out. I could update my `opam` packages to use the link format that you suggest. However, in the long run, I'm not sure which of the two formats is supposed to be stable and supported.

**Comment by fpottier** [comment]
I have sent a PR to `opam` with updated URLs.

**Comment by mimoo** [comment]
CI is still failing on my side with this error :o

**Comment by gasche** [comment]
Does your CI run an `opam update` often enough?

**Pull request merged**
