### PR TITLE
Make spotify_ml.push unavailable, the version should have been 0.0.1

### PR DESCRIPTION
**Pull request by mseri**
@raphael-proust I think we should revert the original PR or remove the package altogether.

in the meantime merging this as a fix

### CODE REVIEW

**Comment by mseri** [comment]
Ping @maxRN (I saw the discussion on discort)

**Comment by maxRN** [comment]
Thank you! @mseri

**Comment by maxRN** [comment]
Is there anything else I need to do? I'm fine with deleting the version.

**Comment by maxRN** [comment]
@mseri Sorry to bother you again about this, but the wrong (old) version is still showing as latest on ocaml.org and opam.ocaml.org. Do you know if this is a bug with those sites not respecting the `available` property?

**Pull request merged**
