### PR TITLE
xentropyd needs cstruct.syntax

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
I intended to fix 0.9.1 as well, but that seems to be completely broken...

**Comment by hannesm** [comment]
...and travis reports a spurious build failure..

**Comment by dsheets** [comment]
kicked

**Comment by hannesm** [comment]
@dsheets thx!  any suggestions what to do with 0.9.1? travis says [here](https://travis-ci.org/ocaml/opam-repository/jobs/128246697):
```
# File "xenctrl/domains.ml", line 34, characters 45-85:
# Error: This expression has type Io_page.t
#        but an expression was expected of type
#          Cstruct.buffer =
#            (char, Bigarray.int8_unsigned_elt, Bigarray.c_layout)
#            Bigarray.Array1.t
# Command exited with code 2.
```

maybe simply remove it from opam?

**Pull request closed without merging**
