### PR TITLE
Allow coq to build with trunk

### PR DESCRIPTION
**Pull request by chambart**
There are 2 parts to this change:
  * allow the coq package to build with camlp4
  * Fix the things in coq that are not valid with trunk:
    * C stubs using uint32 int32 uint64 int64 -> now use uint32_t ...
    * an exception name declare 2 times in the same file (this is now forbidden)

Unfortunately, the patch to the opam file is opam 1.2.1 specific: the syntax
    "%{camlp5:installed?--usecamlp5:--usecamlp4}%"
 is not accepted with opam 1.2.0 (at least the debian package version)

### CODE REVIEW

**Comment by samoht** [comment]
You can use something like `--camlp4 { camlp4:installed } --camlp5 { camlp5:installed }` for a filter which should work with opam 1.1 and 1.2

**Comment by chambart** [comment]
I'm not certain of what syntax you are suggesting. That's kind of part of opam that lacks some documentation (I found that syntax by reading opam sources...).
The expected behavior here is: if camlp5 is installed then use it and add:
``` --usecaml5 --camlp5dir %{lib}%/camlp5 ```
otherwise (then camlp4 is installed) just use
``` --usecamlp4 ```

**Comment by samoht** [comment]
Then write:
```
--usecaml5 { camlp5:installed } --camlp5dir %{lib}%/camlp5 { camlp5:installed } --usecamlp4 { camlp4:installed}
```

See `<command>` at https://opam.ocaml.org/doc/manual/dev-manual.html#sec9

**Comment by chambart** [comment]
Thank you. this should be fixed now.

**Comment by avsm** [comment]
We really cannot patch upstream Coq with a local patch unless the `patches` field is restricted by `ocaml-version` to be only applied for that version of the compiler. Could you add the constraint to `patches`? Also, has the patch been submitted upstream?

**Comment by chambart** [comment]
I just sent the patch to coq-dev.

**Comment by chambart** [comment]
Is there anything else that would be needed on that one ?

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
