### PR TITLE
[new release] elpi (1.16.5)

### PR DESCRIPTION
**Pull request by gares**
ELPI - Embeddable λProlog Interpreter

- Project page: <a href="https://github.com/LPCIC/elpi">https://github.com/LPCIC/elpi</a>
- Documentation: <a href="https://LPCIC.github.io/elpi/">https://LPCIC.github.io/elpi/</a>

##### CHANGES:

Requires Menhir 20211230 and OCaml 4.08 or above.
Camlp5 8.0 or above is optional.

- Apis in the Builtin module:
  - New `string_set`, `int_set` and `loc_set` conversions
  - New `ocaml_set_conv` giving both the declarations and the conversion for the
    provided OCaml `Set` module

### CODE REVIEW

**Comment by gares** [comment]
Should I do anything for `macos-homebrew (experimental)` which fails (to install findlib...)

**Comment by gares** [comment]
@cohencyril FYI this release of Elpi will be the *required* (lower bound) for Coq-Elpi 1.15 (which will support Coq 8.16, univpoly, reversible coercions, ...). You may want to start pushing this in nix.

**Comment by CohenCyril** [comment]
> for Coq-Elpi 1.15 (which will support Coq 8.16, univpoly, reversible coercions, ...)

this is amazing!

**Comment by kit-ty-kate** [comment]
Really sorry for the wait. Thanks

**Comment by gares** [comment]
thanks!

**Pull request merged**
