### PR TITLE
Add `nixpkgs` depexts and some missing dependencies

### PR DESCRIPTION
**Pull request by timbertson**
Working on [opam2nix](https://github.com/timbertson/opam2nix), I've encountered a number of packages which don't compile due to missing dependencies. I've added a `nixpkgs` depext to track external dependency names in [nixpkgs](https://github.com/NixOS/nixpkgs/).

I also encountered a number of dependencies which needed to be added to get certain packages to compile - my assumption is that these dependencies are implicitly provided by transitive dependencies. In `opam2nix` only explicit direct dependencies are visible to the package being compiled, which explains why they would fail under this mode (whereas in normal opam operation, I believe a package can use any package which happens to be installed, even if it doesn't declare a dependency on it).

### CODE REVIEW

**Comment by timbertson** [comment]
Also, if possible it'd be great for future packages to include these added dependencies - do I need to do anything to notify the maintainers of these packages, or are they likely to check the latest package definition before publishing a new version?

**Comment by dbuenzli** [comment]
> or are they likely to check the latest package definition before publishing a new version?

This is unlikely to happen. It would be nice to notify them (Simply collecting the addresses from the maintainer field and sending a message pointing to this  PR should be enough).

**Comment by gasche** [comment]
I used the following script to get the email of all maintainers:

```shell
$ wget https://github.com/ocaml/opam-repository/pull/5338.patch
$ cat 5338.patch \
   | grep -E -o "packages/\\S*/opam" | sort -u \
   | xargs grep maintainer \
   | grep -o -E "\"[^\"]*\"" | sort -u
```

Output:

```
"anil@recoil.org"
"contact@ocamlpro.com"
"mirageos-devel@lists.openmirage.org"
"opam-devel@lists.ocaml.org"
"roberto@dicosmo.org"
"thomas.braibant@gmail.com"
"Thomas Gazagnaire <thomas@gazagnaire.org>"
"ygrek@autistici.org"
```

**Comment by timbertson** [comment]
Thanks. I'm not quite sure of the workflow - should I try to merge this and then ping them, or get them to pitch in on this PR? I assume waiting for all 9 maintainers to give the green light might be a bit slow for something which shouldn't affect anyone not using nixpkgs...

**Comment by gasche** [comment]
I would push for the PR to be merged, and notify them afterwards. They don't need to agree on the change (it won't affect them in any way), it's just that it is helpful for them to have the information for later packaging.

Note that if you could write a script to add those dependencies to programmatically-defined packages (for example you could maintain a textual mapping from package names (version notwithstanding) to nixpg depexts), it could be easy for your to generate further pull requests for past or future packaging versions, so you would rely less on packagers to heed your advice. For an example of scripted processing of OPAM files, see [admin/scripts-add-build-deps](https://github.com/ocaml/opam/blob/master/admin-scripts/add-build-deps.ml) for example.

**Comment by dsheets** [comment]
Another option is to create `conf-*` configuration packages with the depexts for various platforms so that packages can simply depend on e.g. `conf-perl` for present and future versions. It would be best to get these modifications upstreamed to the maintainers so that they will put the `depext` or `conf-*` dependency in their future releases. In my experience, most maintainers are very happy to get pull requests updating their opam metadata.

**Comment by dsheets** [comment]
#4897 tracks the auto-mention feature of [AltGr/opam-bot](https://github.com/AltGr/opam-bot) aka @camelus.

**Comment by lefessan** [comment]
Hi, Any news ? The PR is now conflicting with the current files, could you either update your PR, or upstream your changes ?

**Comment by timbertson** [comment]
Yeah, this sort of languished. I'm going to do it in two steps now - add conf-* for the additional dependencies needed here and then ping upstream authors to just use those packages instead of manual `depexts`. Which seems to be a much better idea anyway, e.g. it turns out there was already conf-openssl and conf-libcurl which have more extensive depexts than ocurl knows about.

**Comment by gasche** [comment]
Note that the ownership model of opam-repository is very loose: you can send a PR that modifies the metadata of existing packages (typically to reflect improvements, or changes in packaging policies). It is nice of you to send an email to the maintainers to notify them (so that they can, for example, update their upstream copy of the `opam` file), but you can change the packages directly if you wish.

**Comment by lefessan** [comment]
That's not a good policy. Either the maintainers maintain their packages, in which case they should accept patches and publish new versions, or, if they don't, we should have another maintainer take their packages in charge (the maintainer does not need to be the author). But modifying somebody else's package is not a good idea, it creates regressions when the original author creates a new version that does not contain the patches submitted by other people. I would clearly recommend to avoid that path, if possible.

**Comment by samoht** [comment]
@lefessan can we discuss that on opam-devel? The current policy is indeed "loose", as @gasche said, and this is done on purpose.

**Comment by dbuenzli** [comment]
Does it really need to be discussed ? Signing is going to change that anyways no ?

**Comment by samoht** [comment]
Repo maintainers can still fix package metadata, even with signing, if they have a quota. 

But until we have signing and things becoming more strict, improving the quality of all the packages in the repo is still greatly encouraged... With sending patch upstream when needed, of course.

**Comment by gasche** [comment]
When I make a change that implement cross-cutting concerns that concern several packages, it is much easier for me, and much better in term of history quality, to have the changes in a single pull request; I don't want to have to send a PR to each maintainer separately (assuming they have github forks, which already looks like a hassle to make sure of), but sending an email to notify them of a common PR and get approval is easy (see the scripts above).

Downstream packages should plan for the possibility that upstream packages could be updated on changes of packaging policies, and check the repository `opam` from time to time, for example just before making a new release.

**Comment by dbuenzli** [comment]
> I don't want to have to send a PR to each maintainer separately (assuming they have github forks, which already looks like a hassle to make sure of), but sending an email to notify them of a common PR and get approval is easy (see the scripts above).
> Downstream packages should plan for the possibility that upstream packages could be updated on changes of packaging policies, and check the repository opam from time to time, for example just before making a new release.

What you describe here doesn't really reflect the reality of the opam-repository. In most cases there's no distinction between package maintainers and developers and the `opam` file for the package is not in an opam-repository fork but in the dev repository of the package itself. So it should really be reported upstream since it is this file that will be used for subsequent releases. Asking for upstream to look downstream is not going to work and you'll be bound to make the same corrections again and again; it would be the equivalent of fixing a bug but not reporting it.

**Comment by avsm** [comment]
Yes, Gabriel has described the current policy correctly. We can change it if there's consensus and tooling to support a stricter model, but on opam-devel...

**Pull request closed without merging**
