### PR TITLE
gpr: upper bound on core

### PR DESCRIPTION
**Pull request by avsm**
Seeing a linking exception
```
gcc: error: src/liblacaml_stubs.a: No such file or directory
File "caml_startup", line 1:
Error: Error during linking
```

helps with revdeps on #9132

### CODE REVIEW

**Comment by avsm** [comment]
@mmottl I'm unable to find the right combination of lacaml and gpr to make old versions compile -- any chance of your help with this?

**Comment by mmottl** [comment]
@avsm Sure, I can try to help.  The linking error points to an Oasis-related issue.  It may generate incorrect build code (in `myocamlbuild.ml`).  This only affects `Lacaml` to my knowledge.  The `Lacaml` build itself would succeed, but projects trying to link `Lacaml` would fail.  Some older versions of `Lacaml` may suffer from this.

Would it be possible to just remove the affected versions of `Lacaml` and their dependencies (`gpr`)?  I doubt it would affect many people, if any.  This would seem like the easiest and fastest solution.

**Comment by avsm** [comment]
> Would it be possible to just remove the affected versions of Lacaml and their dependencies (gpr)? I doubt it would affect many people, if any. This would seem like the easiest and fastest solution.

Sure -- if you think there are no active users then a PR for that would be welcome. The preference is for 1) working packages; 2) constraints; 3) removal, in that order :-)

**Comment by mmottl** [comment]
Thanks, I'm pretty sure that most of the older packages can be safely removed as long as a working version exists for all compilers.  I've cleaned out some of my older packages that I'm reasonably sure nobody depends on.  I'll submit a pull request soon.

**Pull request closed without merging**
