### PR TITLE
[new release] curve-sampling (0.2.1)

### PR DESCRIPTION
**Pull request by Chris00**
Sampling of parametric and implicit curves

- Project page: <a href="https://github.com/Chris00/ocaml-curve-sampling">https://github.com/Chris00/ocaml-curve-sampling</a>
- Documentation: <a href="https://Chris00.github.io/ocaml-curve-sampling/doc">https://Chris00.github.io/ocaml-curve-sampling/doc</a>

##### CHANGES:

- New functions `is_empty` and `bounding_box`.
- Do not fail on empty samplings.

### CODE REVIEW

**Comment by Chris00** [comment]
Depend on https://github.com/ocaml/opam-repository/pull/19999

**Comment by kit-ty-kate** [comment]
arm32 seems to be unsupported:
```
#=== ERROR while compiling gsl.1.24.3 =========================================#
# context              2.1.1 | linux/arm32 | ocaml-base-compiler.4.13.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.13/.opam-switch/build/gsl.1.24.3
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p gsl -j 1
# exit-code            1
# env-file             ~/.opam/log/gsl-23-f1ee31.env
# output-file          ~/.opam/log/gsl-23-f1ee31.out
### output ###
#          gcc src/mlgsl_blas.o (exit 1)
# (cd _build/default/src && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -fPIC -DPIC -Wno-unused-parameter -g -I /home/opam/.opam/4.13/lib/ocaml -o mlgsl_blas.o -c mlgsl_blas.c)
# In file included from mlgsl_vector.h:9,
#                  from mlgsl_vector_double.h:9,
#                  from mlgsl_blas.c:8:
# wrappers.h:13:2: error: #error "Architectures with double-word alignment for doubles are not supported"
#    13 | #error "Architectures with double-word alignment for doubles are not supported"
#       |  ^~~~~
#          gcc src/mlgsl_blas_complex.o (exit 1)
```
Could you add `available: arch != "arm32"` if this is expected?

**Comment by kit-ty-kate** [comment]
Ah sorry I misread this as a curve-sampling failure instead of a failure in gsl. I’ll constrain it

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
