### PR TITLE
Add xenstore.1.3.0

### PR DESCRIPTION
**Pull request by djs55**
Related to [mirage/ocaml-cstruct#95]

### CODE REVIEW

**Comment by samoht** [comment]
Thanks! I'm wondering if we also need to put upper bound constraints in previous version (and same question for previous camp4-related packages)

**Comment by djs55** [comment]
Do you mean adding a `cstruct <= 1.9.0` constraint for older versions and
then releasing and merging `cstruct.2.0.0`?

On Mon, Mar 14, 2016 at 10:27 PM, Thomas Gazagnaire <
notifications@github.com> wrote:

> Thanks! I'm wondering if we also need to put upper bound constraints in
> previous version (and same question for previous camp4-related packages)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocaml/opam-repository/pull/5992#issuecomment-196548081>
> .
>



-- 
Dave Scott

**Comment by samoht** [comment]
I think we can already add `cstruct <= 1.9.0` to the packages which needs it (without releasing 2.0 yet)

**Comment by djs55** [comment]
Yup -- I guess that's best done in separate individual PRs? Last time I
updated lots of (xapi) packages in one PR the travis jobs hit the time
limit. Does that sound sensible?

On Mon, Mar 14, 2016 at 11:22 PM, Thomas Gazagnaire <
notifications@github.com> wrote:

> I think we can already add cstruct <= 1.9.0 to the packages which needs
> it (without releasing 2.0 yet)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocaml/opam-repository/pull/5992#issuecomment-196562549>
> .
>



-- 
Dave Scott

**Comment by samoht** [comment]
Yes separate PRs is fine. It'll be painful but we need to make sure the REVDEPS are fine..

**Pull request merged**
