### PR TITLE
[new release] websocket, websocket-lwt-unix and websocket-async (2.16)

### PR DESCRIPTION
**Pull request by vbmithr**
Websocket library

- Project page: <a href="https://github.com/vbmithr/ocaml-websocket">https://github.com/vbmithr/ocaml-websocket</a>
- Documentation: <a href="https://vbmithr.github.io/ocaml-websocket/doc">https://vbmithr.github.io/ocaml-websocket/doc</a>

##### CHANGES:

- async: Adapt to Core/Async v0.15

### CODE REVIEW

**Comment by mseri** [comment]
The ojs failure seems independent of this
```
#=== ERROR while compiling ojs-base.0.6.0 =====================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/ojs-base.0.6.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build ./configure --prefix /home/opam/.opam/5.0
# exit-code            1
# env-file             ~/.opam/log/ojs-base-8-692933.env
# output-file          ~/.opam/log/ojs-base-8-692933.out
### output ###
[...]
# ### checking required tools and libraries ###
# checking for js_of_ocaml... ok
# checking for cohttp... ok
# checking for websocket... Package websocket found with version 2.15-3-g631a3f0, but wanted >= 2.14
# 
# You way have a look at config_check.log for details.
```

**Comment by kit-ty-kate** [comment]
It’s not really independent. `ojs-base` is buggy (cc @zoggy) so if this release stays like this it should have `< 2.16` but if not it would be nice if the version number given by websocket was correct. Any chance you could fix that @vbmithr?

**Comment by vbmithr** [comment]
And how come the version is `2.15-3-g631a3f0`? I don't even know how to specify this.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
