### PR TITLE
[new release] trace (2 packages) (0.5)

### PR DESCRIPTION
**Pull request by c-cube**
A stub for tracing/observability, agnostic in how data is collected

- Project page: <a href="https://github.com/c-cube/ocaml-trace">https://github.com/c-cube/ocaml-trace</a>

##### CHANGES:

- perf: reduce overhead in trace-tef
- perf: add Mpsc_queue, adapted from picos, to trace-tef

### CODE REVIEW

**Comment by c-cube** [comment]
There might be a deadlock, I'm investigating.

**Comment by mseri** [comment]
Tests are timing out still

**Comment by c-cube** [comment]
Thank you. That's very weird.

**Comment by c-cube** [comment]
This is looking a lot better!

**Comment by c-cube** [comment]
seems to be an unrelated failure.

**Comment by mseri** [comment]
Thanks

**Comment by c-cube** [comment]
Thank you! :)

**Pull request merged**
