### PR TITLE
Remove depexts from tsdl packages use conf-sdl2 instead.

### PR DESCRIPTION
**Pull request by dbuenzli**
And make opam lint happy.

### CODE REVIEW

**Comment by dbuenzli** [comment]
There seem to be mostly rev-deps failure and one `ocamlbuild` error that I'm too tired to figure out. Since this generally improves the repo quality. I'd argue for merge.

**Comment by samoht** [comment]
The revdeps issues are:

```
#=== ERROR while compiling tsdl-ttf.0.2 =======================================#
# command              ocaml setup.ml -build
# path                 /home/opam/.opam/ocaml-base-compiler.4.03.0/.opam-switch/build/tsdl-ttf.0.2
# exit-code            1
# env-file             /home/opam/.opam/log/tsdl-ttf-157-a7c577.env
# output-file          /home/opam/.opam/log/tsdl-ttf-157-a7c577.out
### output ###
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlopt.opt unix.cmxa -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocamlbuild /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamldep -package ctypes -package result -package tsdl -modules src/tsdl_ttf.mli > src/tsdl_ttf.mli.depends
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ctypes -package result -package tsdl -I src -o src/tsdl_ttf.cmi src/tsdl_ttf.mli
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamldep -package ctypes -package result -package tsdl -modules src/tsdl_ttf.ml > src/tsdl_ttf.ml.depends
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ctypes -package result -package tsdl -I src -o src/tsdl_ttf.cmo src/tsdl_ttf.ml
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlc -a -cclib -lSDL2_ttf -I src src/tsdl_ttf.cmo -o src/tsdl_ttf.cma
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -package ctypes -package result -package tsdl -I src -o src/tsdl_ttf.cmx src/tsdl_ttf.ml
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlopt -a -cclib -lSDL2_ttf -I src src/tsdl_ttf.cmx -o src/tsdl_ttf.cmxa
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlopt -shared -I src src/tsdl_ttf.cmxa src/tsdl_ttf.cmx -o src/tsdl_ttf.cmxs
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamldep -package ctypes -package result -package threads -package tsdl -modules test/show_string.ml > test/show_string.ml.depends
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package ctypes -package result -package threads -package tsdl -thread -I test -I src -o test/show_string.cmo test/show_string.ml
# + /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package ctypes -package result -package threads -package tsdl -thread -I test -I src -o test/show_string.cmo test/show_string.ml
# File "test/show_string.ml", line 30, characters 40-48:
# Error: This expression has type 'a option
#        but an expression was expected of type Tsdl.Sdl.rect
# Command exited with code 2.
# E: Failure("Command ''/home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlbuild' src/tsdl_ttf.cma src/tsdl_ttf.cmxa src/tsdl_ttf.a src/tsdl_ttf.cmxs test/show_string.byte -tag debug' terminated with error code 10")
```

and

```
#=== ERROR while compiling tsdl-mixer.0.2 =====================================#
# command              ocaml setup.ml -build
# path                 /home/opam/.opam/ocaml-base-compiler.4.03.0/.opam-switch/build/tsdl-mixer.0.2
# exit-code            1
# env-file             /home/opam/.opam/log/tsdl-mixer-249-a7c577.env
# output-file          /home/opam/.opam/log/tsdl-mixer-249-a7c577.out
### output ###
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlopt.opt unix.cmxa -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocamlbuild /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamldep -package ctypes -package tsdl -modules src/tsdl_mixer.mli > src/tsdl_mixer.mli.depends
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ctypes -package tsdl -I src -o src/tsdl_mixer.cmi src/tsdl_mixer.mli
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamldep -package ctypes -package tsdl -modules src/tsdl_mixer.ml > src/tsdl_mixer.ml.depends
# /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ctypes -package tsdl -I src -o src/tsdl_mixer.cmo src/tsdl_mixer.ml
# + /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ctypes -package tsdl -I src -o src/tsdl_mixer.cmo src/tsdl_mixer.ml
# File "src/tsdl_mixer.ml", line 4, characters 5-11:
# Error: Unbound module Result
# Command exited with code 2.
# E: Failure("Command ''/home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlbuild' src/tsdl_mixer.cma src/tsdl_mixer.cmxa src/tsdl_mixer.a src/tsdl_mixer.cmxs -tag debug' terminated with error code 10")
```

I think these would be worth to try to fix it if you can find some courage :-)

**Comment by dbuenzli** [comment]
I have a better idea. Let's call in @tokenrove the maintainer of these packages and ask him if he can fix the issues.

**Comment by tokenrove** [comment]
Indeed.  I'll take a look.  (It will probably take me a couple of days to have the time, however.)

**Comment by samoht** [comment]
Thanks @tokenrove! Meanwhile I am merging this PR.

**Pull request merged**
