### PR TITLE
[new release] tyxml-ppx and tyxml (4.3.0)

### PR DESCRIPTION
**Pull request by Drup**
CHANGES:

* Dunify
  This also removes all the deprecated libraries (`tyxml.syntax`, `tyxml.parser`)
  and removes the ocamlfind library `tyxml.ppx` in favor of `tyxml-ppx`.
  (ocsigen/tyxml#197 by Drup, Rudi Grinberg and Anton Bachin)
* Add simplistic indentation for the Format-based printer (ocsigen/tyxml#187 by Drup)
* Allow the ppx to be used for more exotic tyxml instances, such
  as reactive elements (ocsigen/tyxml#200 by Drup)
* Add `Html.of_seq` and `Svg.of_seq`, which allow to easily import
  HTML parsed with markup in TyXML (ocsigen/tyxml#221 by Drup)

## Elements and attributes
* Add Html.txt and Svg.txt as an alias for `pcdata` (ocsigen/tyxml#222 by Drup)
* Add noopener link types (ocsigen/tyxml#198 by Jérôme Vouillon)
* Slightly relax dt content type (ocsigen/tyxml#193 by Anton Bachin)
* Add touch events (ocsigen/tyxml#211 by Malthe Borch)
* Fix handling of figcaption in the PPX (ocsigen/tyxml#219 by Drup)

### CODE REVIEW

**Comment by Drup** [comment]
I'm not sure what's up with last ocsigenserver, but the log is with tyxml 4.2 anyway (since it's not compatible with the new one).

**Comment by Drup** [comment]
Nevermind, it's just broken on 4.07 ...

**Comment by Drup** [comment]
All green except some revdep on opensuse (lack some depexts) and travis (camlp4 on system compilers is still borked). It's ready for me.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
