### PR TITLE
[new release] combinat (3.0)

### PR DESCRIPTION
**Pull request by jfeser**
Fast combinatorics for OCaml

- Project page: <a href="https://github.com/jfeser/combinat">https://github.com/jfeser/combinat</a>
- Documentation: <a href="https://jfeser.github.io/combinat/combinat/index.html">https://jfeser.github.io/combinat/combinat/index.html</a>

##### CHANGES:

 - Complete API redesign.
 - Removed dependency on Base stdlib.
 - Added iterators for sequences.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
You seem to have used dune-release here but the whole `url` section is missing. Do you have any idea how that happened?

**Comment by kit-ty-kate** [comment]
I just realized you removed it in https://github.com/ocaml/opam-repository/pull/21113/commits/5f909f1e2a91f12a1ad9a3c9ef6eef467b02f56b. What was your reasoning behind that?

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by jfeser** [comment]
Tried to edit the opam file to address lints from CI and messed up the url. Thanks for fixing!

**Pull request merged**
