### PR TITLE
add upper bounds of dns, dns-lwt, mirage-dns reverse dependencies

### PR DESCRIPTION
**Pull request by hannesm**
this is for preparation of a new dns release which is a rewrite, i.e. the API is different (see https://discuss.ocaml.org/t/psa-dns-2-0-a-new-udns-era-dawns/ for announcement)

since this touches various (very) old package releases, I won't have time and resources to fix CI.

### CODE REVIEW

**Comment by hannesm** [comment]
CI failures (not mentioning solver timeouts and network issues) are as follows (as mentioned, I won't fix them in this PR):

https://ci.ocaml.org/log/saved/docker-build-32f88d50164b1f2d42f184168e523d52/c9feffb2cf6122b04b4f19106d92d8381cd5c6ae (maybe of interest for looking into the CI system itself)
```
Error removing intermediate container 208af0c72981: No such container: 208af0c7298191ca14c242d6890b206ba7f5366fbd6d403d23b3a01062e71977
container is marked for removal and cannot be started
```

https://ci.ocaml.org/log/saved/docker-build-db978d07e156c616583f4f0412aed62f/ec4218deb57eac3e6930ce8c2ca620fee3f84637
```
#=== ERROR while compiling pcap-format.0.5.2 ==================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.04.2 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.04/.opam-switch/build/pcap-format.0.5.2
# command              ~/.opam/4.04/bin/dune build -p pcap-format -j 2
# exit-code            1
# env-file             ~/.opam/log/pcap-format-15-eeb999.env
# output-file          ~/.opam/log/pcap-format-15-eeb999.out
### output ###
# File "lib/dune", line 6, characters 7-18:
# 6 |   (pps ppx_cstruct)))
#            ^^^^^^^^^^^
# Error: Library "ppx_cstruct" not found.
# Hint: try: dune external-lib-deps --missing -p pcap-format -j 2 @@default
```

https://ci.ocaml.org/log/saved/docker-build-d9a5d092ddc008acecd4922afc4ad0bc/351e4787a86303d907ed1b1b06924daa788f68a6
```
#=== ERROR while compiling dns-lwt-unix.1.1.0 =================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/mirage/ocaml-dns/releases/download/v1.1.0/dns-v1.1.0.tbz)
# path                 ~/.opam/4.03/.opam-switch/build/dns-lwt-unix.1.1.0
# command              ~/.opam/4.03/bin/dune runtest -p dns-lwt-unix -j 2
# exit-code            1
# env-file             ~/.opam/log/dns-lwt-unix-15-6cbabc.env
# output-file          ~/.opam/log/dns-lwt-unix-15-6cbabc.out
### output ###
#     ocamlopt examples/server.exe (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlopt.opt -w -40 -g -o examples/server.exe -I /home/opam/.opam/4.03/lib/base64 -I /home/opam/.opam/4.03/lib/bytes -I /home/opam/.opam/4.03/lib/cstruct -I /home/opam/.opam/4.03/lib/dns -I /home/opam/.opam/4.03/lib/dns-lwt -I /home/opam/.opam/4.03/lib/hashcons -I /home/opam/.opam/4.03/lib/ipaddr -I /home/opam/.opam/4.03/lib/lwt -I /home/opam/.opam/4.03/lib/mirage-profile -I /home/opam/.opam/4.03/lib/ocplib-endian -I /home/opam/.opam/4.03/lib/re -I /home/opam/.opam/4.03/lib/re/posix -I /home/opam/.opam/4.03/lib/re/str -I /home/opam/.opam/4.03/lib/result -I /home/opam/.opam/4.03/lib/seq -I /home/opam/.opam/4.03/lib/sexplib -I /home/opam/.opam/4.03/lib/stringext -I /home/opam/.opam/4.03/lib/uri -I lwt-unix /home/opam/.opam/4.03/lib/ocaml/unix.cmxa /home/opam/.opam/4.03/lib/ocaml/bigarray.cmxa /home/opam/.opam/4.03/lib/sexplib/sexplib.cmxa /home/opam/.opam/4.03/lib/cstruct/cstruct.cmxa /home/opam/.opam/4.03/lib/seq/seq.cmxa /home/opam/.opam/4.03/lib/re/re.cmxa /home/opam/.opam/4.03/lib/re/str/re_str.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr.cmxa /home/opam/.opam/4.03/lib/re/posix/re_posix.cmxa /home/opam/.opam/4.03/lib/stringext/stringext.cmxa /home/opam/.opam/4.03/lib/uri/uri.cmxa /home/opam/.opam/4.03/lib/base64/base64.cmxa /home/opam/.opam/4.03/lib/uri/services.cmxa /home/opam/.opam/4.03/lib/hashcons/hashcons.cmx /home/opam/.opam/4.03/lib/result/result.cmxa /home/opam/.opam/4.03/lib/dns/dns.cmxa /home/opam/.opam/4.03/lib/lwt/lwt.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/ocplib_endian.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/bigstring.cmxa /home/opam/.opam/4.03/lib/mirage-profile/mirage_profile.cmxa /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr_unix.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-log.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-unix.cmxa lwt-unix/dns_lwt_unix.cmxa examples/.forward.eobjs/native/server.cmx)
# File "_none_", line 1:
# Error: Files lwt-unix/dns_lwt_unix.cmxa
#        and /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa
#        make inconsistent assumptions over implementation Dns_server
#     ocamlopt lib_test/unix/time_server.exe (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlopt.opt -w -40 -g -o lib_test/unix/time_server.exe -I /home/opam/.opam/4.03/lib/base64 -I /home/opam/.opam/4.03/lib/bytes -I /home/opam/.opam/4.03/lib/cstruct -I /home/opam/.opam/4.03/lib/dns -I /home/opam/.opam/4.03/lib/dns-lwt -I /home/opam/.opam/4.03/lib/hashcons -I /home/opam/.opam/4.03/lib/ipaddr -I /home/opam/.opam/4.03/lib/lwt -I /home/opam/.opam/4.03/lib/mirage-profile -I /home/opam/.opam/4.03/lib/ocplib-endian -I /home/opam/.opam/4.03/lib/re -I /home/opam/.opam/4.03/lib/re/posix -I /home/opam/.opam/4.03/lib/re/str -I /home/opam/.opam/4.03/lib/result -I /home/opam/.opam/4.03/lib/seq -I /home/opam/.opam/4.03/lib/sexplib -I /home/opam/.opam/4.03/lib/stringext -I /home/opam/.opam/4.03/lib/uri -I lwt-unix /home/opam/.opam/4.03/lib/ocaml/unix.cmxa /home/opam/.opam/4.03/lib/ocaml/bigarray.cmxa /home/opam/.opam/4.03/lib/sexplib/sexplib.cmxa /home/opam/.opam/4.03/lib/cstruct/cstruct.cmxa /home/opam/.opam/4.03/lib/seq/seq.cmxa /home/opam/.opam/4.03/lib/re/re.cmxa /home/opam/.opam/4.03/lib/re/str/re_str.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr.cmxa /home/opam/.opam/4.03/lib/re/posix/re_posix.cmxa /home/opam/.opam/4.03/lib/stringext/stringext.cmxa /home/opam/.opam/4.03/lib/uri/uri.cmxa /home/opam/.opam/4.03/lib/base64/base64.cmxa /home/opam/.opam/4.03/lib/uri/services.cmxa /home/opam/.opam/4.03/lib/hashcons/hashcons.cmx /home/opam/.opam/4.03/lib/result/result.cmxa /home/opam/.opam/4.03/lib/dns/dns.cmxa /home/opam/.opam/4.03/lib/lwt/lwt.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/ocplib_endian.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/bigstring.cmxa /home/opam/.opam/4.03/lib/mirage-profile/mirage_profile.cmxa /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr_unix.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-log.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-unix.cmxa lwt-unix/dns_lwt_unix.cmxa lib_test/unix/.time_server.eobjs/native/time_server.cmx)
# File "_none_", line 1:
# Error: Files lwt-unix/dns_lwt_unix.cmxa
#        and /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa
#        make inconsistent assumptions over implementation Dns_server
#     ocamlopt examples/forward.exe (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlopt.opt -w -40 -g -o examples/forward.exe -I /home/opam/.opam/4.03/lib/base64 -I /home/opam/.opam/4.03/lib/bytes -I /home/opam/.opam/4.03/lib/cstruct -I /home/opam/.opam/4.03/lib/dns -I /home/opam/.opam/4.03/lib/dns-lwt -I /home/opam/.opam/4.03/lib/hashcons -I /home/opam/.opam/4.03/lib/ipaddr -I /home/opam/.opam/4.03/lib/lwt -I /home/opam/.opam/4.03/lib/mirage-profile -I /home/opam/.opam/4.03/lib/ocplib-endian -I /home/opam/.opam/4.03/lib/re -I /home/opam/.opam/4.03/lib/re/posix -I /home/opam/.opam/4.03/lib/re/str -I /home/opam/.opam/4.03/lib/result -I /home/opam/.opam/4.03/lib/seq -I /home/opam/.opam/4.03/lib/sexplib -I /home/opam/.opam/4.03/lib/stringext -I /home/opam/.opam/4.03/lib/uri -I lwt-unix /home/opam/.opam/4.03/lib/ocaml/unix.cmxa /home/opam/.opam/4.03/lib/ocaml/bigarray.cmxa /home/opam/.opam/4.03/lib/sexplib/sexplib.cmxa /home/opam/.opam/4.03/lib/cstruct/cstruct.cmxa /home/opam/.opam/4.03/lib/seq/seq.cmxa /home/opam/.opam/4.03/lib/re/re.cmxa /home/opam/.opam/4.03/lib/re/str/re_str.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr.cmxa /home/opam/.opam/4.03/lib/re/posix/re_posix.cmxa /home/opam/.opam/4.03/lib/stringext/stringext.cmxa /home/opam/.opam/4.03/lib/uri/uri.cmxa /home/opam/.opam/4.03/lib/base64/base64.cmxa /home/opam/.opam/4.03/lib/uri/services.cmxa /home/opam/.opam/4.03/lib/hashcons/hashcons.cmx /home/opam/.opam/4.03/lib/result/result.cmxa /home/opam/.opam/4.03/lib/dns/dns.cmxa /home/opam/.opam/4.03/lib/lwt/lwt.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/ocplib_endian.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/bigstring.cmxa /home/opam/.opam/4.03/lib/mirage-profile/mirage_profile.cmxa /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr_unix.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-log.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-unix.cmxa lwt-unix/dns_lwt_unix.cmxa examples/.forward.eobjs/native/forward.cmx)
# File "_none_", line 1:
# Error: Files lwt-unix/dns_lwt_unix.cmxa
#        and /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa
#        make inconsistent assumptions over implementation Dns_server
```

https://ci.ocaml.org/log/saved/docker-build-c1578505f2e55db7b0e223fa1f38efe7/1a3d72799750dc2268a5817ed911479394c49201
```

#=== ERROR while compiling dns-lwt-unix.1.1.1 =================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/mirage/ocaml-dns/releases/download/v1.1.1/dns-v1.1.1.tbz)
# path                 ~/.opam/4.03/.opam-switch/build/dns-lwt-unix.1.1.1
# command              ~/.opam/4.03/bin/dune runtest -p dns-lwt-unix -j 2
# exit-code            1
# env-file             ~/.opam/log/dns-lwt-unix-15-4eae94.env
# output-file          ~/.opam/log/dns-lwt-unix-15-4eae94.out
### output ###
#     ocamlopt lib_test/unix/time_server.exe (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlopt.opt -w -40 -g -o lib_test/unix/time_server.exe -I /home/opam/.opam/4.03/lib/base64 -I /home/opam/.opam/4.03/lib/bytes -I /home/opam/.opam/4.03/lib/cstruct -I /home/opam/.opam/4.03/lib/dns -I /home/opam/.opam/4.03/lib/dns-lwt -I /home/opam/.opam/4.03/lib/hashcons -I /home/opam/.opam/4.03/lib/ipaddr -I /home/opam/.opam/4.03/lib/lwt -I /home/opam/.opam/4.03/lib/mirage-profile -I /home/opam/.opam/4.03/lib/ocplib-endian -I /home/opam/.opam/4.03/lib/re -I /home/opam/.opam/4.03/lib/re/posix -I /home/opam/.opam/4.03/lib/re/str -I /home/opam/.opam/4.03/lib/result -I /home/opam/.opam/4.03/lib/seq -I /home/opam/.opam/4.03/lib/sexplib -I /home/opam/.opam/4.03/lib/stringext -I /home/opam/.opam/4.03/lib/uri -I lwt-unix /home/opam/.opam/4.03/lib/ocaml/unix.cmxa /home/opam/.opam/4.03/lib/ocaml/bigarray.cmxa /home/opam/.opam/4.03/lib/sexplib/sexplib.cmxa /home/opam/.opam/4.03/lib/cstruct/cstruct.cmxa /home/opam/.opam/4.03/lib/seq/seq.cmxa /home/opam/.opam/4.03/lib/re/re.cmxa /home/opam/.opam/4.03/lib/re/str/re_str.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr.cmxa /home/opam/.opam/4.03/lib/re/posix/re_posix.cmxa /home/opam/.opam/4.03/lib/stringext/stringext.cmxa /home/opam/.opam/4.03/lib/uri/uri.cmxa /home/opam/.opam/4.03/lib/base64/base64.cmxa /home/opam/.opam/4.03/lib/uri/services.cmxa /home/opam/.opam/4.03/lib/hashcons/hashcons.cmx /home/opam/.opam/4.03/lib/result/result.cmxa /home/opam/.opam/4.03/lib/dns/dns.cmxa /home/opam/.opam/4.03/lib/lwt/lwt.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/ocplib_endian.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/bigstring.cmxa /home/opam/.opam/4.03/lib/mirage-profile/mirage_profile.cmxa /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr_unix.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-log.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-unix.cmxa lwt-unix/dns_lwt_unix.cmxa lib_test/unix/.time_server.eobjs/native/time_server.cmx)
# File "_none_", line 1:
# Error: Files lwt-unix/dns_lwt_unix.cmxa
#        and /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa
#        make inconsistent assumptions over implementation Dns_server
#     ocamlopt examples/server.exe (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlopt.opt -w -40 -g -o examples/server.exe -I /home/opam/.opam/4.03/lib/base64 -I /home/opam/.opam/4.03/lib/bytes -I /home/opam/.opam/4.03/lib/cstruct -I /home/opam/.opam/4.03/lib/dns -I /home/opam/.opam/4.03/lib/dns-lwt -I /home/opam/.opam/4.03/lib/hashcons -I /home/opam/.opam/4.03/lib/ipaddr -I /home/opam/.opam/4.03/lib/lwt -I /home/opam/.opam/4.03/lib/mirage-profile -I /home/opam/.opam/4.03/lib/ocplib-endian -I /home/opam/.opam/4.03/lib/re -I /home/opam/.opam/4.03/lib/re/posix -I /home/opam/.opam/4.03/lib/re/str -I /home/opam/.opam/4.03/lib/result -I /home/opam/.opam/4.03/lib/seq -I /home/opam/.opam/4.03/lib/sexplib -I /home/opam/.opam/4.03/lib/stringext -I /home/opam/.opam/4.03/lib/uri -I lwt-unix /home/opam/.opam/4.03/lib/ocaml/unix.cmxa /home/opam/.opam/4.03/lib/ocaml/bigarray.cmxa /home/opam/.opam/4.03/lib/sexplib/sexplib.cmxa /home/opam/.opam/4.03/lib/cstruct/cstruct.cmxa /home/opam/.opam/4.03/lib/seq/seq.cmxa /home/opam/.opam/4.03/lib/re/re.cmxa /home/opam/.opam/4.03/lib/re/str/re_str.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr.cmxa /home/opam/.opam/4.03/lib/re/posix/re_posix.cmxa /home/opam/.opam/4.03/lib/stringext/stringext.cmxa /home/opam/.opam/4.03/lib/uri/uri.cmxa /home/opam/.opam/4.03/lib/base64/base64.cmxa /home/opam/.opam/4.03/lib/uri/services.cmxa /home/opam/.opam/4.03/lib/hashcons/hashcons.cmx /home/opam/.opam/4.03/lib/result/result.cmxa /home/opam/.opam/4.03/lib/dns/dns.cmxa /home/opam/.opam/4.03/lib/lwt/lwt.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/ocplib_endian.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/bigstring.cmxa /home/opam/.opam/4.03/lib/mirage-profile/mirage_profile.cmxa /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr_unix.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-log.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-unix.cmxa lwt-unix/dns_lwt_unix.cmxa examples/.forward.eobjs/native/server.cmx)
# File "_none_", line 1:
# Error: Files lwt-unix/dns_lwt_unix.cmxa
#        and /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa
#        make inconsistent assumptions over implementation Dns_server
#     ocamlopt examples/forward.exe (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlopt.opt -w -40 -g -o examples/forward.exe -I /home/opam/.opam/4.03/lib/base64 -I /home/opam/.opam/4.03/lib/bytes -I /home/opam/.opam/4.03/lib/cstruct -I /home/opam/.opam/4.03/lib/dns -I /home/opam/.opam/4.03/lib/dns-lwt -I /home/opam/.opam/4.03/lib/hashcons -I /home/opam/.opam/4.03/lib/ipaddr -I /home/opam/.opam/4.03/lib/lwt -I /home/opam/.opam/4.03/lib/mirage-profile -I /home/opam/.opam/4.03/lib/ocplib-endian -I /home/opam/.opam/4.03/lib/re -I /home/opam/.opam/4.03/lib/re/posix -I /home/opam/.opam/4.03/lib/re/str -I /home/opam/.opam/4.03/lib/result -I /home/opam/.opam/4.03/lib/seq -I /home/opam/.opam/4.03/lib/sexplib -I /home/opam/.opam/4.03/lib/stringext -I /home/opam/.opam/4.03/lib/uri -I lwt-unix /home/opam/.opam/4.03/lib/ocaml/unix.cmxa /home/opam/.opam/4.03/lib/ocaml/bigarray.cmxa /home/opam/.opam/4.03/lib/sexplib/sexplib.cmxa /home/opam/.opam/4.03/lib/cstruct/cstruct.cmxa /home/opam/.opam/4.03/lib/seq/seq.cmxa /home/opam/.opam/4.03/lib/re/re.cmxa /home/opam/.opam/4.03/lib/re/str/re_str.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr.cmxa /home/opam/.opam/4.03/lib/re/posix/re_posix.cmxa /home/opam/.opam/4.03/lib/stringext/stringext.cmxa /home/opam/.opam/4.03/lib/uri/uri.cmxa /home/opam/.opam/4.03/lib/base64/base64.cmxa /home/opam/.opam/4.03/lib/uri/services.cmxa /home/opam/.opam/4.03/lib/hashcons/hashcons.cmx /home/opam/.opam/4.03/lib/result/result.cmxa /home/opam/.opam/4.03/lib/dns/dns.cmxa /home/opam/.opam/4.03/lib/lwt/lwt.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/ocplib_endian.cmxa /home/opam/.opam/4.03/lib/ocplib-endian/bigstring.cmxa /home/opam/.opam/4.03/lib/mirage-profile/mirage_profile.cmxa /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa /home/opam/.opam/4.03/lib/ipaddr/ipaddr_unix.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-log.cmxa /home/opam/.opam/4.03/lib/lwt/lwt-unix.cmxa lwt-unix/dns_lwt_unix.cmxa examples/.forward.eobjs/native/forward.cmx)
# File "_none_", line 1:
# Error: Files lwt-unix/dns_lwt_unix.cmxa
#        and /home/opam/.opam/4.03/lib/dns-lwt/dns_lwt.cmxa
#        make inconsistent assumptions over implementation Dns_server
```

https://ci.ocaml.org/log/saved/docker-build-a303273dadcf562f60a193161848f801/43373634851c7e93639137657a337837256d864f
```
#=== ERROR while compiling dns-forward.0.10.0 =================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/mirage/ocaml-dns-forward/releases/download/v0.10.0/dns-forward-0.10.0.tbz)
# path                 ~/.opam/4.03/.opam-switch/build/dns-forward.0.10.0
# command              ~/.opam/4.03/bin/jbuilder build -p dns-forward -j 2
# exit-code            1
# env-file             ~/.opam/log/dns-forward-16-1bf61b.env
# output-file          ~/.opam/log/dns-forward-16-1bf61b.out
### output ###
# The jbuilder binary is deprecated and will cease to be maintained in July 2019.
# Please switch to dune instead.
# File "lib/jbuild", line 1, characters 0-0:
# Warning: jbuild files are deprecated, please convert this file to a dune file
# instead.
# Note: You can use "dune upgrade" to convert your project to dune.
# File "lib_test/jbuild", line 1, characters 0-0:
# Warning: jbuild files are deprecated, please convert this file to a dune file
# instead.
# Note: You can use "dune upgrade" to convert your project to dune.
# File "lwt/jbuild", line 1, characters 0-0:
# Warning: jbuild files are deprecated, please convert this file to a dune file
# instead.
# Note: You can use "dune upgrade" to convert your project to dune.
#       ocamlc lib/.dns_forward.objs/byte/dns_forward__Dns_forward_config.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.dns_forward.objs/byte -I /home/opam/.opam/4.03/lib/astring -I /home/opam/.opam/4.03/lib/base64 -I /home/opam/.opam/4.03/lib/bigarray-compat -I /home/opam/.opam/4.03/lib/bytes -I /home/opam/.opam/4.03/lib/cstruct -I /home/opam/.opam/4.03/lib/dns -I /home/opam/.opam/4.03/lib/duration -I /home/opam/.opam/4.03/lib/fmt -I /home/opam/.opam/4.03/lib/hashcons -I /home/opam/.opam/4.03/lib/io-page -I /home/opam/.opam/4.03/lib/ipaddr -I /home/opam/.opam/4.03/lib/logs -I /home/opam/.opam/4.03/lib/lwt -I /home/opam/.opam/4.03/lib/mirage-channel -I /home/opam/.opam/4.03/lib/mirage-channel-lwt -I /home/opam/.opam/4.03/lib/mirage-clock -I /home/opam/.opam/4.03/lib/mirage-clock-lwt -I /home/opam/.opam/4.03/lib/mirage-device -I /home/opam/.opam/4.03/lib/mirage-flow -I /home/opam/.opam/4.03/lib/mirage-flow-lwt -I /home/opam/.opam/4.03/lib/mirage-time -I /home/opam/.opam/4.03/lib/mirage-time-lwt -I /home/opam/.opam/4.03/lib/re -I /home/opam/.opam/4.03/lib/re/posix -I /home/opam/.opam/4.03/lib/re/str -I /home/opam/.opam/4.03/lib/result -I /home/opam/.opam/4.03/lib/rresult -I /home/opam/.opam/4.03/lib/seq -I /home/opam/.opam/4.03/lib/sexplib -I /home/opam/.opam/4.03/lib/stdlib-shims -I /home/opam/.opam/4.03/lib/stringext -I /home/opam/.opam/4.03/lib/uri -intf-suffix .ml -no-alias-deps -open Dns_forward__ -o lib/.dns_forward.objs/byte/dns_forward__Dns_forward_config.cmo -c -impl lib/dns_forward_config.pp.ml)
# File "lib/dns_forward_config.ml", line 47, characters 15-25:
# Error: Unbound value _t_of_sexp
# Hint: Did you mean int_of_sexp?
#     ocamlopt lib/.dns_forward.objs/native/dns_forward__Dns_forward_config.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlopt.opt -w -40 -g -I lib/.dns_forward.objs/byte -I lib/.dns_forward.objs/native -I /home/opam/.opam/4.03/lib/astring -I /home/opam/.opam/4.03/lib/base64 -I /home/opam/.opam/4.03/lib/bigarray-compat -I /home/opam/.opam/4.03/lib/bytes -I /home/opam/.opam/4.03/lib/cstruct -I /home/opam/.opam/4.03/lib/dns -I /home/opam/.opam/4.03/lib/duration -I /home/opam/.opam/4.03/lib/fmt -I /home/opam/.opam/4.03/lib/hashcons -I /home/opam/.opam/4.03/lib/io-page -I /home/opam/.opam/4.03/lib/ipaddr -I /home/opam/.opam/4.03/lib/logs -I /home/opam/.opam/4.03/lib/lwt -I /home/opam/.opam/4.03/lib/mirage-channel -I /home/opam/.opam/4.03/lib/mirage-channel-lwt -I /home/opam/.opam/4.03/lib/mirage-clock -I /home/opam/.opam/4.03/lib/mirage-clock-lwt -I /home/opam/.opam/4.03/lib/mirage-device -I /home/opam/.opam/4.03/lib/mirage-flow -I /home/opam/.opam/4.03/lib/mirage-flow-lwt -I /home/opam/.opam/4.03/lib/mirage-time -I /home/opam/.opam/4.03/lib/mirage-time-lwt -I /home/opam/.opam/4.03/lib/re -I /home/opam/.opam/4.03/lib/re/posix -I /home/opam/.opam/4.03/lib/re/str -I /home/opam/.opam/4.03/lib/result -I /home/opam/.opam/4.03/lib/rresult -I /home/opam/.opam/4.03/lib/seq -I /home/opam/.opam/4.03/lib/sexplib -I /home/opam/.opam/4.03/lib/stdlib-shims -I /home/opam/.opam/4.03/lib/stringext -I /home/opam/.opam/4.03/lib/uri -intf-suffix .ml -no-alias-deps -open Dns_forward__ -o lib/.dns_forward.objs/native/dns_forward__Dns_forward_config.cmx -c -impl lib/dns_forward_config.pp.ml)
# File "lib/dns_forward_config.ml", line 47, characters 15-25:
# Error: Unbound value _t_of_sexp
# Hint: Did you mean int_of_sexp?
```

**Comment by kit-ty-kate** [comment]
```
these releases are not installable anymore (3): dns-forward.0.9.0 dns-forward-lwt-unix.0.9.0 vpnkit.0.1.1
```
Could you take care of that?

**Comment by hannesm** [comment]
@kit-ty-kate I found my typo for dns-forward*, but I've no clue what is wrong with vpnkit 0.1.1 :/ I don't think the constraints added in this PR have an effect on the installability (since only the upper bound is limited to versions that are not yet released to opam-repository).

**Comment by hannesm** [comment]
ah, vpnkit depends on dns-forward <0.10.0 -- thus the commit I pushed should solve this as well... let's see what camelus says

**Comment by kit-ty-kate** [comment]
Sounds fine now. Thanks a lot!

**Pull request merged**
