### PR TITLE
[new release] tyxml-lwd, nottui, nottui-pretty, nottui-lwt, lwd and brr-lwd (0.3)

### PR DESCRIPTION
**Pull request by let-def**
Make reactive webpages in Js_of_ocaml using Tyxml and Lwd

- Project page: <a href="https://github.com/let-def/lwd">https://github.com/let-def/lwd</a>
- Documentation: <a href="https://let-def.github.io/lwd/doc">https://let-def.github.io/lwd/doc</a>

##### CHANGES:

Mon Sep  5 10:57:53 JST 2022

- Add [Lwd_seq.sort_uniq] function
- Make [Lwd_seq.t] injective
- Fix a bug breaking invariants in Lwd_table.remove
- Documentation update contributed by @shubhamkumar13
- Option to disable the default Quit behavior of Nottui contributed by @OhadRau

### CODE REVIEW

**Comment by let-def** [comment]
(Working on a fix :gear: ...)

**Comment by let-def** [comment]
The errors do not seem related to this package:
- build failure of Notty 0.2 with lwt on older OCaml versions
- no space left on device

**Comment by mseri** [comment]
I’d like to fix notty 0.2 metadata, probably it needs an upper bound on lwt, which could affect still the build here. Let me try to address that separately before merging this

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
