### PR TITLE
[release of alt-ergo 1.01] with its GUI and plugins

### PR DESCRIPTION
**Pull request by OCamlPro-Iguernlala**

### CODE REVIEW

**Comment by OCamlPro-Iguernlala** [comment]
Should I put "dev-repo" field in opam files (with an empty value/string) ? I guess it's not required since its absence only triggers a warning.

**Comment by AltGr** [comment]
An empty field is the worst thing (and I think in that case you would get an error).
If there is no dev-repo, keeping the warning is fine. (It's still useful for the vast majority of packages which do, but may not provide the info yet)

**Comment by OCamlPro-Iguernlala** [comment]
I should fix files/alt-ergo.install for plugins ...

**Comment by lefessan** [comment]
Could you:
1/ break this PR in two PRs:
  * one for alt-ergo and its plugins
  * one for altgr-ergo (since it does depend on alt-ergo)
  Otherwise, Travis is just checking that it can install `alt-ergo`, not `altgr-ergo`
2/ fix some opam files that are still not correctly written:
  * `alt-ergo` and `altgr-ergo` both have a `make install` in their `build` section (not detected because of the `.install` file), and no `remove` section (opam will only uninstall what was install using the `.install` file)

Thanks !

**Comment by OCamlPro-Iguernlala** [comment]
I made two different PRs for alt-ergo (https://github.com/ocaml/opam-repository/pull/5626) and for altgr-ergo (https://github.com/ocaml/opam-repository/pull/5627).

I'll wait their merge to open PRs for the plugins.

**Pull request closed without merging**
