### PR TITLE
Add libsvm.0.9.4

### PR DESCRIPTION
**Pull request by olgu**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Does it compile on OS X?

**Comment by UnixJunkie** [comment]
you need to add conf-libsvm in the depends section

**Comment by olgu** [comment]
I think this no longer needed since it was decided to vendor the libsvm library:
https://bitbucket.org/ogu/libsvm-ocaml/pull-requests/1/port-to-jbuilder/diff

**Comment by UnixJunkie** [comment]
Should we delete the conf-libsvm package then?

**Comment by olgu** [comment]
I suggest that we first wait until this release satisfies all checks and is stable before removing `conf-libsvm` in case the `libsvm` C++ library will be excluded again from the package. 

One issue is caused by `ocamlfind` under `OCaml 4.05.0`:

\#=== ERROR while compiling ocamlfind.1.7.3 ====================================#
\# command              make opt
\# path                 /home/opam/.opam/ocaml-variants.4.05.0+trunk/.opam-switch/build/ocamlfind.1.7.3
\# exit-code            2
\# env-file             /home/opam/.opam/log/ocamlfind-426-af57d6.env
\# output-file          /home/opam/.opam/log/ocamlfind-426-af57d6.out

The other issue seems to be related to a missing C++ compiler:

\#=== ERROR while installing libsvm.0.9.4 ======================================#
\# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
\# os                   linux
\# command              jbuilder build -p libsvm -j 2
\# path                 /home/opam/.opam/4.04.2/build/libsvm.0.9.4
\# compiler             4.04.2
\# exit-code            1
\# env-file             /home/opam/.opam/4.04.2/build/libsvm.0.9.4/libsvm-29-b11210.env
\# stdout-file          /home/opam/.opam/4.04.2/build/libsvm.0.9.4/libsvm-29-b11210.out
\# stderr-file          /home/opam/.opam/4.04.2/build/libsvm.0.9.4/libsvm-29-b11210.err
\### stderr ###
\#          gcc lib/libsvm_stubs.o (exit 1)
\# (cd _build/default/lib && /usr/bin/gcc -I /home/opam/.opam/4.04.2/lib/ocaml -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC -I /home/opam/.opam/4.04.2/lib/base -I /home/opam/.opam/4.04.2/lib/base/caml -I /home/opam/.opam/4.04.2/lib/base/shadow_stdlib -I /home/opam/.opam/4.04.2/lib/bytes -I /home/opam/.opam/4.04.2/lib/lacaml -I /home/opam/.opam/4.04.2/lib/ocaml -I /home/opam/.opam/4.04.2/lib/ocaml/threads -I /home/opam/.opam/4.04.2/lib/sexplib/0 -I /home/opam/.opam/4.04.2/lib/stdio -g -o libsvm_stubs.o -c libsvm_stubs.cpp)
\# gcc: error trying to exec 'cc1plus': execvp: No such file or directory
\#          gcc lib/svm.o (exit 1)
\# (cd _build/default/lib && /usr/bin/gcc -I /home/opam/.opam/4.04.2/lib/ocaml -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC -I /home/opam/.opam/4.04.2/lib/base -I /home/opam/.opam/4.04.2/lib/base/caml -I /home/opam/.opam/4.04.2/lib/base/shadow_stdlib -I /home/opam/.opam/4.04.2/lib/bytes -I /home/opam/.opam/4.04.2/lib/lacaml -I /home/opam/.opam/4.04.2/lib/ocaml -I /home/opam/.opam/4.04.2/lib/ocaml/threads -I /home/opam/.opam/4.04.2/lib/sexplib/0 -I /home/opam/.opam/4.04.2/lib/stdio -g -o svm.o -c svm.cpp)
\# gcc: error trying to exec 'cc1plus': execvp: No such file or directory

To fix those I need some help.

**Comment by samoht** [comment]
There seems to be an issue with 4.05+trunk:
```
ocamlopt -I +compiler-libs -o ocamlfind_opt findlib.cmxa unix.cmxa \
# 	   ocaml_args.cmx frontend.cmx
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(startup_aux.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(fail.o): relocation R_X86_64_32 against symbol `caml_exn_Failure' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(roots.o): relocation R_X86_64_32 against symbol `caml_frametable' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(signals.o): relocation R_X86_64_32S against undefined symbol `caml_pending_signals' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(signals_asm.o): relocation R_X86_64_32S against symbol `caml_system__code_begin' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(misc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(freelist.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(major_gc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(minor_gc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(memory.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(alloc.o): relocation R_X86_64_32S against undefined symbol `caml_atom_table' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(compare.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(ints.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(floats.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(str.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(array.o): relocation R_X86_64_32 against undefined symbol `caml_atom_table' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(io.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(extern.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(intern.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(hash.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(sys.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(parsing.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(gc_ctrl.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(obj.o): relocation R_X86_64_32S against undefined symbol `caml_atom_table' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(lexing.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(unix.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(printexc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(callback.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(weak.o): relocation R_X86_64_32 against symbol `caml_ephe_ref_table' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(compact.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(finalise.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(custom.o): relocation R_X86_64_32 against symbol `caml_custom_table' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(globroots.o): relocation R_X86_64_32 against symbol `caml_global_roots' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(backtrace.o): relocation R_X86_64_32 against symbol `caml_backtrace_last_exn' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: /home/opam/.opam/ocaml-variants.4.05.0+trunk/lib/ocaml/libasmrun.a(startup.o): relocation R_X86_64_32S against symbol `caml_data_segments' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: final link failed: Nonrepresentable section on output
# collect2: error: ld returned 1 exit status
# File "caml_startup", line 1:
```

This is probably an error with the image, so happy to merge.

**Comment by samoht** [comment]
For `cc1plus`, maybe this needs to be installed as an external dependency? I'll make some tests

**Comment by samoht** [comment]
@olgu can you add:

```
depexts: [
  [["debian"] ["g++"]]
]
```

to make the compilation on debian happy? (just tested this in a debian container and it seems to work well)

**Comment by olgu** [comment]
Thanks for your help and sorry for the delay!

**Comment by samoht** [comment]
The remaining error is due to some issue with our infra, so merging. Sorry for the delay!

**Pull request merged**
