### PR TITLE
added ppx_orakuda.3.0.0

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
Could you tell me why it is "broken" ?

**Comment by samoht** [comment]
Not sure ... but happy to merge if Travis is green and no weird conflicts appears in the run logs.

**Comment by avsm** [comment]
@altgr is camelus hooked up with ocaml 4.03.0 yet? this particular PR also doesnt include spotlib 3.1.0, so unless camelus merges against master it would not be installable.  Can you merge this PR against ocaml/ocaml-repository master and push the result?

**Comment by yallop** [comment]
I've tested this locally with 4.03.0.

**Comment by camlspotter** [comment]
Thanks guys!

**Pull request merged**
