### PR TITLE
[camlp5] New release 7.03, compatible with OCaml 4.06.0.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
CI Failure with 4.06 looks due to the use of an old 4.06 image, but can't tell for sure.

**Comment by gasche** [comment]
@avsm the magic numbers used by the OCaml implementation were bumped *after* beta2 (not a great idea), and @ejgallego's intuition that the CI is using the older magic number sounds reasonable. Do you know when the images used for 4.06 testing were built? Are they fixed on beta2?

**Comment by ejgallego** [comment]
> @avsm the magic numbers used by the OCaml implementation were bumped after beta2 (not a great idea),

Indeed @gasche , maybe a reasonable policy is that parsertree/magic interfaces are expected to stable once the first beta appears?

**Comment by gasche** [comment]
Well we sure made a mistake by not updating the magic numbers before the betas, but not updating them at all would have been even worse so that's how it is. I will do an extra beta or rc this week.

**Comment by ejgallego** [comment]
The CI says it is using the `4.06.0+trunk` switch, but indeed I couldn't locate a git hash of the exact version used. I think that would be a useful data to have in the logs, where can I submit a feature request? On this repository?

**Comment by gasche** [comment]
Let's merge the release now to unblock Coq testing. If it turns out @ejgallego did a mistake we can always merge a new release and mark this one incompatible with 4.06.0.

**Comment by ejgallego** [comment]
Thanks @gasche , working fine in my opam setup.

**Comment by avsm** [comment]
I'm rebuilding the opam2 images again... hopefully this'll be the last magic number change :-)

**Pull request merged**
