### PR TITLE
extlib: add bound on OCaml version

### PR DESCRIPTION
**Pull request by damiendoligez**

### CODE REVIEW

**Comment by damiendoligez** [comment]
I sent a pull request upstream: https://github.com/ygrek/ocaml-extlib/pull/37

**Comment by gasche** [comment]
I think this change could be reverted, given that the string primitive names were changed back in 4.04+beta2.

**Comment by damiendoligez** [comment]
@gasche Agreed. I've tested with beta2 and it compiles. I wouldn't even set the bound to 4.05.

Same for `extlib-compat` (#7173).

**Pull request merged**
