### PR TITLE
ocamlfind.1.9.0: Fix BSD support

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Comment by dra27** [comment]
Slightly simpler fix: add `["sed" "-ib" "-e" "s/</?/" "tools/extract_args/Makefile"]`

**Comment by dra27** [comment]
(my bad - I neither realised that `$<` in that meaning is a GNUism, nor remembered that while the build requires GNU make, configuration doesn't!)

**Comment by kit-ty-kate** [comment]
Tested successfully on FreeBSD and macOS. Merging.

**Comment by hannesm** [comment]
Thanks for your quick patch and merge!

**Pull request merged**
