### PR TITLE
do not use shell path hardcoded in ./configure

### PR DESCRIPTION
**Pull request by ygrek**
This will allow many packages build out-of-the box in [Termux](http://termux.com)

Generated with `for i in $(ag -l  -Q '"./configure"' packages compilers) ; do sed -i -e 's|"./configure"|"sh" "./configure"|' $i; done`

Related https://github.com/ocaml/ocaml/pull/935

### CODE REVIEW

**Comment by avsm** [comment]
@ygrek: is there a Docker image of Termux (or some other automatable build environment) that we could use to hook into CI?

**Comment by ygrek** [comment]
I believe there are docker images of android, then need to check how to install termux apk.. will try to look into it

**Comment by avsm** [comment]
@ygrek any chance of a fresh version of this with the `"sh" "sh" "configure"` duplication removed? I"m closing this for now to avoid DOSing our CI (which attempts to builds all the affected packages in a PR, which is obviously quite large here).  But am keen to merge a version of this patch sooner rather than later also.

**Comment by bluelightning32** [comment]
I'm interested in picking up the work on this PR.

Avsm, how should i proceed? Should I start a new PR?

What was unfinished in this PR? I don't understand what you mean by "sh" "sh" "configure" duplication.

**Pull request closed without merging**
