### PR TITLE
+ mysql 1.2.1

### PR DESCRIPTION
**Pull request by ygrek**

### CODE REVIEW

**Comment by yallop** [comment]
```
[ERROR] curl: code 404 while downloading
        http://ygrek.org.ua/release/ocaml-mysql/ocaml-mysql-1.2.1.tar.gz
```

**Comment by ygrek** [comment]
my bad

**Comment by yallop** [comment]
The build is [failing on OS X](https://travis-ci.org/ocaml/opam-repository/jobs/147258004):

```
### stderr ###
# ./configure: line 3435: mysql_config: command not found
# ./configure: line 3444: mysql_config: command not found
# configure: error: MySQL client library not found
```

Could you please add either an `available` constraint (`[ os != "darwin" ]`) or extend the `depexts` as needed, perhaps like this:

```
 [["osx" "homebrew"] ["mysql"]]
```

?

**Comment by hcarty** [comment]
I think you can get away with the `mysql-connector-c` brew package since only the client library is required.

**Comment by ygrek** [comment]
Thanks for the OSX hints

**Comment by samoht** [comment]
All green!

**Pull request merged**
