### PR TITLE
Luv 0.5.3: libuv binding

### PR DESCRIPTION
**Pull request by aantron**
- Interpret port numbers correctly as unsigned short integers (aantron/luv@23d2ac6).

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The bash script seems to fail somewhere in the middle when OCaml is also installed system wide but the current one is the one built by opam:
```
-         bash src/c/dlluv.so,src/c/libuv.a (exit 2)
```
Could you have a look at it? https://travis-ci.org/github/ocaml/opam-repository/jobs/685765509

**Comment by aantron** [comment]
libuv has had a release in the meantime (yesterday), so I'll retag in addition to looking at the Travis issue.

**Comment by aantron** [comment]
I wasn't able to reproduce the problem in Travis locally, by installing a system OCaml (from APT). I suggest that I'll debug the Travis problem in a separate dummy PR with a "release" that has all the libuv build verbosity options enabled.

**Comment by aantron** [comment]
I updated the release.

**Comment by avsm** [comment]
Thanks!

**Pull request merged**
