### PR TITLE
Packages reason.3.4.0, rtop.3.4.0

### PR DESCRIPTION
**Pull request by anmonteiro**

### CODE REVIEW

**Comment by anmonteiro** [comment]
Revdeps is failing because of a mismatching checksum in `ppx_fast_pipe`, should I fix that in this PR?

**Comment by anmonteiro** [comment]
Done in https://github.com/ocaml/opam-repository/pull/13275, this PR now depends on it.

**Comment by anmonteiro** [comment]
Just rebased this on top of #13275

**Comment by kit-ty-kate** [comment]
All good. Thanks!

**Pull request merged**
