### PR TITLE
Package mccs.1.1+1

### PR DESCRIPTION
**Pull request by AltGr**
### `mccs.1.1+1`

Multi Criteria CUDF Solver with OCaml bindings

This is a stripped-down version of the mccs solver (written in C++), including
OCaml bindings based on the cudf library.

---
* Homepage: http://www.i3s.unice.fr/~cpjm/misc/
* Source repo: https://github.com/AltGr/ocaml-mccs.git
* Bug tracker: https://github.com/AltGr/ocaml-mccs/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by AltGr** [comment]
It seems Travis didn't recognise the C++ `auto` keyword, that is C++11 and that I used. Is it due to an old version of gcc, or bad options ? Do I need to explicit all those annoying iterator types for compat ?

**Comment by AltGr** [comment]
Removed all the `auto` (meh...)

But Travis still fails with:
```
# mccs_stubs.cpp:64:15: error: expected type-specifier before ‘unordered_map’
#      tbl = new unordered_map<string, CUDFVirtualPackage*>;
#                ^
# mccs_stubs.cpp:64:15: error: expected ‘;’ before ‘unordered_map’
# mccs_stubs.cpp: In destructor ‘Virtual_packages::~Virtual_packages()’:
# mccs_stubs.cpp:68:12: error: ‘tbl’ was not declared in this scope
#      delete tbl;
#             ^
```

Any advice, or hint on how to reproduce ?

**Comment by dra27** [comment]
Yes - on my old Ubuntu VM I have to add `-std=c++11`

**Comment by dra27** [comment]
It's a typical example of why C(++) compilers displaying lots of error messages is pointless - way up the log should be a GCC warning telling you that it's detected C++11, but not activated it!

**Comment by AltGr** [comment]
It's the inline `unordered_map<string, CUDFVirtualPackage*>` that's C++11 ? I need to declare it first ? :confused:

**Comment by dra27** [comment]
I just did this in the jbuild file:
```diff
-  (cxx_flags         (:standard -I .))
+  (cxx_flags         (:standard -I . -std=c++11))
```

**Comment by dra27** [comment]
(Ubuntu 14.04)

**Comment by AltGr** [comment]
Ok. Apparently it's the `unordered_map` template itself that is only in the stdlib since c++11.
I can safely put back the `auto` then ?

**Comment by AltGr** [comment]
Thanks @dra27 :)

**Comment by avsm** [comment]
Hm, looks like an unrelated camlp4 compilation failure on 4.05

**Comment by AltGr** [comment]
Superseded by #10075

**Pull request closed without merging**
