### PR TITLE
Package cryptoverif.2.05

### PR DESCRIPTION
**Pull request by bruno-blanchet**
### `cryptoverif.2.05`
CryptoVerif: Cryptographic protocol verifier in the computational model
CryptoVerif is an automatic protocol prover sound in the computational model. It can prove

  - secrecy;
  - correspondences, which include in particular authentication;
  - indistinguishability between two games.

It provides a generic mechanism for specifying the security assumptions on cryptographic primitives, which can handle in particular symmetric encryption, message authentication codes, public-key encryption, signatures, hash functions.

The generated proofs are proofs by sequences of games, as used by cryptographers. These proofs are valid for a number of sessions polynomial in the security parameter, in the presence of an active adversary. CryptoVerif can also evaluate the probability of success of an attack against the protocol as a function of the probability of breaking each cryptographic primitive and of the number of sessions (exact security).

This software is under development; please use it at your own risk. Comments and bug reports welcome.

---
* Homepage: https://cryptoverif.inria.fr
* Bug tracker: Bruno.Blanchet@inria.fr

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by mseri** [comment]
Do you know what may have caused this failure in the lower bounds check?
```
# + /home/opam/.opam/4.03/bin/ocamlfind ocamlmklib -o src/cryptokit_stubs -lz src/arcfour.o src/stubs-arcfour.o src/blowfish.o src/stubs-blowfish.o src/d3des.o src/stubs-des.o src/rijndael-alg-fst.o src/ripemd160.o src/stubs-ripemd160.o src/sha1.o src/stubs-sha1.o src/sha256.o src/stubs-sha256.o src/sha512.o src/stubs-sha512.o src/stubs-aes.o src/stubs-md5.o src/stubs-misc.o src/stubs-rng.o src/stubs-zlib.o src/keccak.o src/stubs-sha3.o
# gcc: error: src/arcfour.o: No such file or directory
# gcc: error: src/stubs-arcfour.o: No such file or directory
# gcc: error: src/blowfish.o: No such file or directory
# gcc: error: src/stubs-blowfish.o: No such file or directory
# gcc: error: src/d3des.o: No such file or directory
# gcc: error: src/stubs-des.o: No such file or directory
# gcc: error: src/rijndael-alg-fst.o: No such file or directory
# gcc: error: src/ripemd160.o: No such file or directory
# gcc: error: src/stubs-ripemd160.o: No such file or directory
# gcc: error: src/sha1.o: No such file or directory
# gcc: error: src/stubs-sha1.o: No such file or directory
# gcc: error: src/sha256.o: No such file or directory
# gcc: error: src/stubs-sha256.o: No such file or directory
# gcc: error: src/sha512.o: No such file or directory
# gcc: error: src/stubs-sha512.o: No such file or directory
# gcc: error: src/stubs-aes.o: No such file or directory
# gcc: error: src/stubs-md5.o: No such file or directory
# gcc: error: src/stubs-misc.o: No such file or directory
# gcc: error: src/stubs-rng.o: No such file or directory
# gcc: error: src/stubs-zlib.o: No such file or directory
# gcc: error: src/keccak.o: No such file or directory
# gcc: error: src/stubs-sha3.o: No such file or directory
# Command exited with code 2.
```

Actions:
```
The following actions will be performed:
  - remove    dune-configurator        2.9.1          [uses dune]
  - install   ocamlbuild               0.9.0          [required by cryptokit]
  - downgrade conf-pkg-config          2 to 1.0
  - install   base-num                 base           [required by num]
  - remove    opam-depext              1.1.5
  - remove    zarith                   1.11           [conflicts with ocamlfind]
  - remove    conf-gmp-powm-sec        3
  - remove    result                   1.5            [uses dune]
  - remove    csexp                    1.5.1          [uses dune]
  - install   num                      0              [required by ocamlfind]
  - remove    conf-perl                1
  - remove    conf-gmp                 3
  - remove    dune                     2.9.1          [uses ocamlfind-secondary]
  - remove    ocamlfind-secondary      1.9.1          [conflicts with ocamlfind]
  - downgrade ocamlfind                1.9.1 to 1.6.2
  - remove    ocaml-secondary-compiler 4.08.1-1
  - downgrade cryptokit                1.16.1 to 1.10 [uses ocamlfind]
  ```

Details on https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/8d90eb0edb56ad6f07aa01239f409062d7c00208/variant/opam-2.1,compilers,4.03,cryptoverif.2.05,lower-bounds


Do we just neeed a lower bound on cryptokit?

**Comment by bruno-blanchet** [comment]
I am sorry but I do not understand this error. From the log, it seems that the c files were just compiled without error, and still it does not find the object files. That's really strange.Moreover, cryptokit 1.16.1 works with ocaml 4.03 and cryptokit 1.10 works with ocaml 4.04. it is just cryptokit 1.10 that does not seem to work with ocaml 4.03...Le 9 sept. 2021 21:15, Marcello Seri ***@***.***> a écrit :
Do you know what may have caused this failure in the lower bounds check?
# + /home/opam/.opam/4.03/bin/ocamlfind ocamlmklib -o src/cryptokit_stubs -lz src/arcfour.o src/stubs-arcfour.o src/blowfish.o src/stubs-blowfish.o src/d3des.o src/stubs-des.o src/rijndael-alg-fst.o src/ripemd160.o src/stubs-ripemd160.o src/sha1.o src/stubs-sha1.o src/sha256.o src/stubs-sha256.o src/sha512.o src/stubs-sha512.o src/stubs-aes.o src/stubs-md5.o src/stubs-misc.o src/stubs-rng.o src/stubs-zlib.o src/keccak.o src/stubs-sha3.o
# gcc: error: src/arcfour.o: No such file or directory
# gcc: error: src/stubs-arcfour.o: No such file or directory
# gcc: error: src/blowfish.o: No such file or directory
# gcc: error: src/stubs-blowfish.o: No such file or directory
# gcc: error: src/d3des.o: No such file or directory
# gcc: error: src/stubs-des.o: No such file or directory
# gcc: error: src/rijndael-alg-fst.o: No such file or directory
# gcc: error: src/ripemd160.o: No such file or directory
# gcc: error: src/stubs-ripemd160.o: No such file or directory
# gcc: error: src/sha1.o: No such file or directory
# gcc: error: src/stubs-sha1.o: No such file or directory
# gcc: error: src/sha256.o: No such file or directory
# gcc: error: src/stubs-sha256.o: No such file or directory
# gcc: error: src/sha512.o: No such file or directory
# gcc: error: src/stubs-sha512.o: No such file or directory
# gcc: error: src/stubs-aes.o: No such file or directory
# gcc: error: src/stubs-md5.o: No such file or directory
# gcc: error: src/stubs-misc.o: No such file or directory
# gcc: error: src/stubs-rng.o: No such file or directory
# gcc: error: src/stubs-zlib.o: No such file or directory
# gcc: error: src/keccak.o: No such file or directory
# gcc: error: src/stubs-sha3.o: No such file or directory
# Command exited with code 2.

Actions:
The following actions will be performed:
  - remove    dune-configurator        2.9.1          [uses dune]
  - install   ocamlbuild               0.9.0          [required by cryptokit]
  - downgrade conf-pkg-config          2 to 1.0
  - install   base-num                 base           [required by num]
  - remove    opam-depext              1.1.5
  - remove    zarith                   1.11           [conflicts with ocamlfind]
  - remove    conf-gmp-powm-sec        3
  - remove    result                   1.5            [uses dune]
  - remove    csexp                    1.5.1          [uses dune]
  - install   num                      0              [required by ocamlfind]
  - remove    conf-perl                1
  - remove    conf-gmp                 3
  - remove    dune                     2.9.1          [uses ocamlfind-secondary]
  - remove    ocamlfind-secondary      1.9.1          [conflicts with ocamlfind]
  - downgrade ocamlfind                1.9.1 to 1.6.2
  - remove    ocaml-secondary-compiler 4.08.1-1
  - downgrade cryptokit                1.16.1 to 1.10 [uses ocamlfind]

Details on https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/8d90eb0edb56ad6f07aa01239f409062d7c00208/variant/opam-2.1,compilers,4.03,cryptoverif.2.05,lower-bounds
Do we just neeed a lower bound on cryptokit?

**Comment by mseri** [comment]
@kit-ty-kate do you have experience with this kind of errors in the CI?

**Comment by kit-ty-kate** [comment]
> @kit-ty-kate do you have experience with this kind of errors in the CI?

yes. That's the usual failure with ocamlbuild.0.9.0. I've created a PR for it in https://github.com/ocaml/opam-repository/pull/19477. It'll be fixed soon.

**Comment by mseri** [comment]
Thanks a lot. Then this seems good to merge

**Pull request merged**
