### PR TITLE
fdkaac.0.3.2: Add conflict on liquidsoap < 1.4.0

### PR DESCRIPTION
**Pull request by toots**
This was forgotten during the last release and fixes: #16174

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I'd rather keep the constraints in the related packages (here `liquidsoap`), would it be ok to do it there instead? It allows a much clearer description of packages and easier to modify later without having to remember where to modify the constraints.

If you don't have time I'll do it at some point.

**Comment by toots** [comment]
> I'd rather keep the constraints in the related packages (here `liquidsoap`), would it be ok to do it there instead? It allows a much clearer description of packages and easier to modify later without having to remember where to modify the constraints.
> 
> If you don't have time I'll do it at some point.

Sure no problem, I'll do it right now.

**Comment by toots** [comment]
Should be good now @kit-ty-kate

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
