### PR TITLE
added packages/clangml-transforms/clangml-transforms.0.21

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Does someone know what is the Linux distro used in this job:
https://travis-ci.org/ocaml/opam-repository/jobs/90138083

    E: Unable to locate package clang-3.6
    E: Couldn't find any package by regex 'clang-3.6'
    E: Unable to locate package libclang-3.6-dev
    E: Couldn't find any package by regex 'libclang-3.6-dev'
    E: Unable to locate package llvm-3.6-dev
    E: Couldn't find any package by regex 'llvm-3.6-dev'

I'd like to find out the package names I need to git it so that it works.

**Comment by samoht** [comment]
That's an old ubuntu. We should switch to a more recent version one by using the container support in Travis CI. Can appreciate some help there.

Anyway, I'm happy to merge the PR if you've tested it on recent distros and you think that's fine.

**Comment by dbuenzli** [comment]
> Does someone know what is the Linux distro used in this job:

This seems to be a recurring theme. Is it possible to have a clear indication in the build bots of what distribution and version is being used ?

**Comment by samoht** [comment]
patches to https://github.com/ocaml/opam-repository/blob/master/.travis-ci.sh are welcome to print the OS version in the logs.

Travis CI says on https://docs.travis-ci.com/user/ci-environment/ that it uses Ubuntu 12.04 LTS Server Edition 64 bit (we are using the standard build for that repo)

**Comment by dbuenzli** [comment]
> Travis CI says on https://docs.travis-ci.com/user/ci-environment/ that it uses Ubuntu 12.04 LTS Server Edition 64 bit (we are using the standard build for that repo)

Ok. But that bit of documentation seems to be a little bit too far away from the average opam contributor so I'd be nice if that info could be found in the build logs, the natural place you look for when something fails. So I'd say it's not patches welcome, it's patches required; time lost will be minimized for everybody involved.

**Comment by UnixJunkie** [comment]
superseded by https://github.com/ocaml/opam-repository/pull/5217

**Pull request closed without merging**
