### PR TITLE
Add protocol-9p.0.7.3

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by avsm** [comment]
this needs an `opam-version: 1.2.2` i think

```
#=== ERROR while installing protocol-9p.0.7.3 =================================#
# opam-version 1.2.0
# os           linux
# command      ocaml pkg/pkg.ml build --pinned --with-lambda-term
# path         /home/travis/.opam/4.02.3/build/protocol-9p.0.7.3
# compiler     4.02.3
# exit-code    1
# env-file     /home/travis/.opam/4.02.3/build/protocol-9p.0.7.3/protocol-9p-18722-4345db.env
# stdout-file  /home/travis/.opam/4.02.3/build/protocol-9p.0.7.3/protocol-9p-18722-4345db.out
# stderr-file  /home/travis/.opam/4.02.3/build/protocol-9p.0.7.3/protocol-9p-18722-4345db.err
### stderr ###
# pkg.ml: [ERROR] key --pinned: "--with-lambda-term": Can't parse boolean value.
```

**Comment by yallop** [comment]
@samoht: doesn't this need an `opam-version` constraint?

**Comment by samoht** [comment]
Unfortunately the `opam-version` field is not clever enough to filter unknown packages. See https://github.com/ocaml/opam-repository/pull/6979

**Comment by yallop** [comment]
I mean something like [this](https://github.com/ocaml/opam-repository/blob/d3250da0cda8e32869bcd9580963a26dcb64ad0d/packages/ppx_deriving/ppx_deriving.4.0/opam#L30).  I don't know whether it'd help in this case, though.

**Comment by samoht** [comment]
Ha that's a good idea. I'll see if I can add without too much pain.

**Pull request merged**
