### PR TITLE
brotli.1.0 - via opam-publish

### PR DESCRIPTION
**Pull request by fxfactorial**
Bindings to Google's Brotli compresion algorithm

High level and easy to use OCaml bindings to brotli, a compression
algorithm from Google.

Brotli source: https://github.com/google/brotli/ 

RFC: http://www.ietf.org/id/draft-alakuijala-brotli

---
* Homepage: http://hyegar.com
* Source repo: https://github.com/fxfactorial/ocaml-brotli.git
* Bug tracker: https://github.com/fxfactorial/ocaml-brotli/issues

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by fxfactorial** [comment]
@avsm Expected: `cc1plus: error: unrecognized command line option ‘-std=c++11’ ` yes I need it.

**Comment by fxfactorial** [comment]
Please wait to merge this.

**Comment by samoht** [comment]
do you need a system package to be present to run `cc1plus`? If you it could be worth to add it to the `depexts` field.

**Comment by fxfactorial** [comment]
All I'm asking for is g++, would have thought that'd be present

**Comment by samoht** [comment]
I guess it needs a more recent ubuntu that the one installed in Travis (precise). Merging anyway as it blocking your other releases.

**Pull request merged**
