### PR TITLE
[new release] eqaf (v0.1)

### PR DESCRIPTION
**Pull request by dinosaure**
Constant time equal function on `string`

- Project page: <a href="https://github.com/dinosaure/eqaf">https://github.com/dinosaure/eqaf</a>
- Documentation: <a href="https://dinosaure.github.io/eqaf/">https://dinosaure.github.io/eqaf/</a>

##### CHANGES:

* First release

### CODE REVIEW

**Comment by dinosaure** [comment]
Did you know a way to constraint tests to be available only on `ocaml > "4.03.0"` ?

**Comment by mseri** [comment]
I think (but I've never tried) that you can add `{ ocaml-version > "4.03.0" }` as a filter to the `build-test` section

**Comment by dinosaure** [comment]
Ok, so `ppx_expect` does not compile on `4.03.0` and we continue to have a bug on Mac OSX about expected results - the situation could be better if we provide only the C implementation of the equal function, @hannesm and @cfcs, do you have any opinion about that?

NOTE: I can not test the code, I did not have any access on a Mac.

**Comment by cfcs** [comment]
@dinosaure I think that seems sensible, it's not much code, and if the whole reason for having this is that the OCaml implementation is not in fact constant-time, I don't see a good way around this.

**Comment by dinosaure** [comment]
CI fails because benchmark/test runs on `4.03.0` but I explicitly put a constraint like what @mseri said on `build-test`. Any other idea?

**Comment by mseri** [comment]
the problem is that it tries to install the test dependencies even if the tests are not really running. I'll keep your last commit because it shows that the tests are expected to fail for 4.03.0. I'll merge and if we find a better solution will send a separate PR. Thanks

**Comment by dinosaure** [comment]
Thanks a lot 👍 !

**Pull request merged**
