### PR TITLE
+pa_qualified

### PR DESCRIPTION
**Pull request by cakeplus**
Pa_qualified adds support for fully qualified module references to OCaml. If a module reference (in any possible context) starts with "Q.", then the rest of the reference denotes a context-independent globally unique path (as if the reference was located at the very beginning of the file). Qualified references can never be shadowed by other definitions (warranty void if "Q" is defined explicitly somewhere).

### CODE REVIEW

**Comment by cakeplus** [comment]
Hooray! Camlp4 compatibility bugs. So exciting! :-)

Why did OPAM use Camlp4 4.01.0 with OCaml 4.00.1? This seems to be the root of the problem.

**Comment by cakeplus** [comment]
I know why: because there was no Camlp4 package before 4.01.0.
Perhaps I should just add a version constraint? (>= 4.01.0)

**Comment by yallop** [comment]
The [Camlp4 4.01.0 package](https://github.com/ocaml/opam-repository/blob/master/packages/camlp4/camlp4.4.01.0/opam) is just a dummy that doesn't install anything, so I don't think that's the problem,. although the version numbers are a bit confusing

It does look like you have some minor incompatibilities with 4.00.1, though (e.g. using `|>`), so adding a version constraint is probably the easiest fix.

**Comment by cakeplus** [comment]
Indeed, the problem turned out to be with the constructor name disambiguation feature that appeared in OCaml 4.01.0. I've added a version constraint.

**Comment by yallop** [comment]
Thanks!

**Pull request merged**
