### PR TITLE
[new release] odate (0.6)

### PR DESCRIPTION
**Pull request by hhugo**
Date & Duration Library

- Project page: <a href="https://github.com/hhugo/odate">https://github.com/hhugo/odate</a>

## Changes
* Compatibility with ocaml > 4.06
* Enable ocamlformat
* Switch to dune lang 2
* Switch to expect tests

### CODE REVIEW

**Comment by hhugo** [comment]
I'm having issues with dune-release. I think the tarball is not available

**Comment by dmbaturin** [comment]
> I'm having issues with dune-release. I think the tarball is not available

I usually use opam-publish, it works quite well. I explicitly point it to a tarball though, like `opam-publish https://.../1.0.0/package-1.0.0.tar.gz`.

**Comment by hhugo** [comment]
> > I'm having issues with dune-release. I think the tarball is not available
> 
> I usually use opam-publish, it works quite well. I explicitly point it to a tarball though, like `opam-publish https://.../1.0.0/package-1.0.0.tar.gz`.

Dune-release usually work just fine

**Comment by kit-ty-kate** [comment]
Thanks! Could you return the fixes upstream?

**Pull request merged**
