### PR TITLE
7 packages from oxidizing/sihl at 0.3.0-rc2

### PR DESCRIPTION
**Pull request by aronerben**
This pull-request concerns:
-`sihl.0.3.0-rc2`: The Sihl web framework
-`sihl-cache.0.3.0-rc2`: A module that provides services to store and retrieve data with
 key-value semantics
-`sihl-email.0.3.0-rc2`: Sihl service to deal with sending emails
-`sihl-queue.0.3.0-rc2`: Sihl service to deal with queuing jobs
-`sihl-storage.0.3.0-rc2`: Sihl service to deal with storage of large files
-`sihl-token.0.3.0-rc2`: Sihl service to deal with tokens
-`sihl-user.0.3.0-rc2`: Sihl services to deal with users

---
* Homepage: https://github.com/oxidizing/sihl
* Source repo: git+https://github.com/oxidizing/sihl.git
* Bug tracker: https://github.com/oxidizing/sihl/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

--
EDIT: Correct versions:
-`sihl.0.3.0~rc2`: The Sihl web framework
-`sihl-cache.0.3.0~rc2`: A module that provides services to store and retrieve data with
 key-value semantics
-`sihl-email.0.3.0~rc2`: Sihl service to deal with sending emails
-`sihl-queue.0.3.0~rc2`: Sihl service to deal with queuing jobs
-`sihl-storage.0.3.0~rc2`: Sihl service to deal with storage of large files
-`sihl-token.0.3.0~rc2`: Sihl service to deal with tokens
-`sihl-user.0.3.0~rc2`: Sihl services to deal with users

### CODE REVIEW

**Comment by mseri** [comment]
Are you sure the version is correct? I think you should release 0.3.0~rc2

**Comment by aronerben** [comment]
> Are you sure the version is correct? I think you should release 0.3.0~rc2 otherwise this will be considered newer than 0.3.0

Ah dangit, I hoped my first attempt would go smoother :P 
Thanks for your hint, I've made the (hopefully correct) adjustments.

**Comment by mseri** [comment]
Looks good now, thanks

**Comment by aronerben** [comment]
> Looks good now, thanks

Thank you!

**Pull request merged**
