### PR TITLE
avoid mirage-* packages that require solo5-bindings-* which are deprecated

### PR DESCRIPTION
**Pull request by hannesm**
I'm still on the fence, we could as well mark these as unavailable. They are bitrot, and requires solo5-bindings-* packages which are deprecated (and modern C compilers error compiling them due to usage of `-Wall -Werror`.

The list in here is taken from https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/327d6ea9ffe66fe2ac64d4ee6373cc6db7845a01

### CODE REVIEW

**Comment by hannesm** [comment]
related to #23697

**Comment by mseri** [comment]
I know that they are equivalent, but why not "deprecated" instead? This way it will be easier to spot it for cleanup. (Sorry for not mentioning it in the other PR)

The inconvenience with `avoid-version` is that it is being used for beta packages or preview packages and sometimes the stable version is missing, or a beta version is still being used in the wild and should not be removed. With `deprecated` we give a clear message that it is meant to no longer be used

**Comment by hannesm** [comment]
as you wish :)

**Comment by mseri** [comment]
Thanks

**Pull request merged**
