### PR TITLE
new file:   packages/line_oriented/line_oriented.1.0.0/opam

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This package does not seem to contain anything (nothing is built)

**Comment by UnixJunkie** [comment]
How come? If I do this in a fresh git checkout:
```
opam pin add line_oriented $PWD
```
The package is correctly built and installed.

**Comment by UnixJunkie** [comment]
Maybe a problem with "line-oriented" instead of "line_oriented" somewhere?

**Comment by kit-ty-kate** [comment]
There is simply no `build` or `install` field in this opam file so nothing is executed

**Comment by UnixJunkie** [comment]
ok, corrected

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
