### PR TITLE
plplot 5.11.0

### PR DESCRIPTION
**Pull request by hcarty**

### CODE REVIEW

**Comment by hcarty** [comment]
I'll fix the name and the other builds then force-push an update

**Comment by hcarty** [comment]
I fixed the name inside the opam file.

The Ubuntu failures are because the system packages are for an older version of PLplot (5.9.9).  On newer versions of Ubuntu or with a suitable version of PLplot built from source it Works For Me under Ubuntu.

**Comment by yallop** [comment]
```
=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] Bad checksum for
        /Users/travis/.opam/packages.dev/plplot.5.11.0/v5.11.0.tar.gz:
          - 5fee9b49dd1a45b025a3f506843a2bcb [expected result]
          - b73c6801b42187695d9d3aae96696143 [actual result]
        This may be fixed by running `opam update`.
```

**Comment by hcarty** [comment]
@yallop Thanks!

**Comment by hcarty** [comment]
Download checksum should be fixed now

**Pull request merged**
