### PR TITLE
[conf-timeout] package to detect if timeout is available

### PR DESCRIPTION
**Pull request by maroneze**

### CODE REVIEW

**Comment by mseri** [comment]
Cfr https://github.com/ocaml/opam-repository/issues/16689

**Comment by mseri** [comment]
Not sure about the centos fail. I'll wait for @kit-ty-kate to have a look before doing anything

**Comment by maroneze** [comment]
I just tried a centos Docker and got the same error. But what's worse, is that `which` is not available by default. I'll change the package to not require `conf-which`, using instead `command -v`, as recommended by [SO](https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script).

**Comment by maroneze** [comment]
It seems CentOS is a bit finnicky: it has both packages `coreutils` and `coreutils-single`, which conflict with each other. I don't think opam has a way to say "check if either of these is installed, otherwise try installing one", so I'm tempted to simply not check at all whether coreutils is available in CentOS (which should be the case most of the time), deferring the check to `command` itself. For instance, I just tried uninstalling `coreutils-single`, and I got an error saying that this would remove `systemd`, a protected package. So there's very little chance of that happening.

**Comment by mseri** [comment]
Thanks, this has waited far too long

**Pull request merged**
