### PR TITLE
Package biocaml.0.8.0

### PR DESCRIPTION
**Pull request by pveber**
### `biocaml.0.8.0`

The OCaml Bioinformatics Library
Biocaml aims to be a high-performance user-friendly library for
Bioinformatics. See the [website](http://biocaml.org) for detailed API
documentation. We welcome contributors and feedback from users. Please
contact us with any comments and suggestions for features you would
like added.

---
* Homepage: http://biocaml.org
* Source repo: https://github.com/biocaml/biocaml.git
* Bug tracker: https://github.com/biocaml/biocaml/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by gasche** [comment]
Merged, thanks. Note that the CI didn't test whether it builds under 4.06 (sexplib and solvuu-build were missing; at least sexplib is now fixed), so you will have to do your own testing.

**Comment by pveber** [comment]
Rats, I forgot to remove `solvuu-build` from the list of dependencies... May I send a new PR through `opam-publish` to fix that? In any case, thanks for using your sharp eyes on this!

**Comment by gasche** [comment]
If you don't mind the low-level way, sending a PR using normal git tools from an opam-repository clone would probably be the easiest way. Otherwise I'll just do it. (I remove it just from this last version, right?)

**Comment by pveber** [comment]
Low-level is great, let me do it right now. Thanks!

**Comment by pveber** [comment]
Errr... actually this package does not depend on `solvuu-build` directly (its `cfstream` and this should be fixed in a very near future). So nothing to change here, we're good. Thanks again!!

**Pull request merged**
