### PR TITLE
[new release] Timedesc and related libs 0.9.1

### PR DESCRIPTION
**Pull request by darrenldl**
OCaml date time handling library

Homepage: https://github.com/daypack-dev/timere

### CODE REVIEW

**Comment by mseri** [comment]
There used to be a rather comprehensive description, is the empty description expected?

**Comment by darrenldl** [comment]
Ah, only timedesc.opam carries the detailed description, as other libs are smaller subcomponents.

I'll add some relevant descriptions to the ones with empty descriptions atm.

**Comment by mseri** [comment]
There is a couple of surprising lower bound failures:
```
#=== ERROR while compiling timedesc-tzlocal.0.9.1 =============================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.13.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.13/.opam-switch/build/timedesc-tzlocal.0.9.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune install -p timedesc-tzlocal --create-install-files timedesc-tzlocal
# exit-code            1
# env-file             ~/.opam/log/timedesc-tzlocal-9-97ded8.env
# output-file          ~/.opam/log/timedesc-tzlocal-9-97ded8.out
### output ###
#    ocamlfind (internal) (exit 127)
# /home/opam/.opam/4.13/bin/ocamlfind printconf destdir > /opam-tmp/dunee5eae3.output


#=== ERROR while compiling timedesc-tzdb.0.9.1 ================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.13.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.13/.opam-switch/build/timedesc-tzdb.0.9.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune install -p timedesc-tzdb --create-install-files timedesc-tzdb
# exit-code            1
# env-file             ~/.opam/log/timedesc-tzdb-9-f7126a.env
# output-file          ~/.opam/log/timedesc-tzdb-9-f7126a.out
### output ###
#    ocamlfind (internal) (exit 127)
# /home/opam/.opam/4.13/bin/ocamlfind printconf destdir > /opam-tmp/dune9a2a82.output
```

**Comment by mseri** [comment]
I am rerunning the failing builds, I believe it may be a transient failure

**Comment by mseri** [comment]
Thanks

**Pull request merged**
