### PR TITLE
Add opam 2.0.0~rc2 libraries and opam-devel package

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by AltGr** [comment]
(seems to pass indeed when re-running them at a slower pace)

**Comment by kit-ty-kate** [comment]
Seems like `opam-bundle.0.1` needs to be constrained.
```
#=== ERROR while compiling opam-bundle.0.1 ====================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.06.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.06/.opam-switch/build/opam-bundle.0.1
# command              /usr/bin/make
# exit-code            2
# env-file             ~/.opam/log/opam-bundle-18-a00279.env
# output-file          ~/.opam/log/opam-bundle-18-a00279.out
### output ###
# ocaml crunch.ml shell/common.sh shell/bootstrap.sh shell/configure.sh shell/compile.sh shell/self_extract.sh > src/opamBundleScripts.ml
# ocamlfind ocamlopt -package cmdliner,opam-repository,opam-client -linkpkg -w A-44 -I src src/opamBundleScripts.ml src/opamBundleMain.ml -o opam-bundle
# File "src/opamBundleMain.ml", line 106, characters 24-40:
# Error: Unbound value OpamStd.Sys.arch
# Makefile:4: recipe for target 'opam-bundle' failed
# make: *** [opam-bundle] Error 2

- ocaml crunch.ml shell/common.sh shell/bootstrap.sh shell/configure.sh shell/compile.sh shell/self_extract.sh > src/opamBundleScripts.ml
- ocamlfind ocamlopt -package cmdliner,opam-repository,opam-client -linkpkg -w A-44 -I src src/opamBundleScripts.ml src/opamBundleMain.ml -o opam-bundle
- File "src/opamBundleMain.ml", line 106, characters 24-40:
- Error: Unbound value OpamStd.Sys.arch
- Makefile:4: recipe for target 'opam-bundle' failed
- make: *** [opam-bundle] Error 2
```

**Comment by kit-ty-kate** [comment]
Could you also add a constrain on jbuilder >= beta19.1 ? :/
```
#=== ERROR while compiling mccs.1.1+6 =========================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.06.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.06/.opam-switch/build/mccs.1.1+6
# command              ~/.opam/4.06/bin/jbuilder build -p mccs
# exit-code            1
# env-file             ~/.opam/log/mccs-19-f96d0c.env
# output-file          ~/.opam/log/mccs-19-f96d0c.out
### output ###
# File "src/jbuild", line 31, characters 26-36:
# Error: Unknown constructor universe
```

**Comment by kit-ty-kate** [comment]
Everything look fine now but the tests fail :/
```
make "tests" (CWD=/home/travis/.opam/system/build/opam-devel.2.0.0~rc2)
- jbuilder build opam.install src/tools/opam_check.exe
- jbuilder runtest --force --no-buffer  src/ tests/
- make[1]: Entering directory `/home/travis/.opam/system/build/opam-devel.2.0.0~rc2/_build/default/tests'
- /usr/bin/make --no-print-directory REPOKIND=local run
-   00 init                 ..................................... [FAIL]
-   01 upload               ..................................... [FAIL]
-   02 install-remove       ..................................... [FAIL]
-   03 list                 ..................................... [ OK ]
-   04 install-opt          ..................................... [FAIL]
-   05 list                 ..................................... [ OK ]
-   06 install              ..................................... [FAIL]
-   07 list                 ..................................... [ OK ]
-   08 reinstall            ..................................... [FAIL]
-   09 list                 ..................................... [ OK ]
-   10 upload-new           ..................................... [ OK ]
-   11 list                 ..................................... [ OK ]
-   12 upgrade              ..................................... [FAIL]
-   13 list                 ..................................... [ OK ]
-   14 downgrade            ..................................... 
- [FAIL]
-   15 list                 ..................................... [ OK ]
-   16 switch-alias         ..................................... [FAIL]
-   17 list                 ..................................... [ OK ]
-   18 switch-env-packages  ..................................... [FAIL]
-   19 repo                 ..................................... [FAIL]
-   20 list                 ..................................... [ OK ]
- FAILED! Logs in /home/travis/.opam/system/build/opam-devel.2.0.0~rc2/_build/default/tests/failed-local.log
- make[1]: Leaving directory `/home/travis/.opam/system/build/opam-devel.2.0.0~rc2/_build/default/tests'
- make[2]: *** [run] Error 1
- make[1]: *** [local] Error 2
-         make alias tests/runtest (exit 2)
- (cd _build/default/tests && /usr/bin/make all)
- make: *** [tests] Error 1
[ERROR] The compilation of opam-devel failed at "make tests".
```

**Comment by AltGr** [comment]
I believe it is an issue with the testing (actually forgot that the opam file had a test entry) ; the testing was recently changed to go through jbuilder, and is probably confused by the context of running within opam.

I think this is safe to merge while I look at the issue (esp. since the package has already been [announced](https://opam.ocaml.org/blog/opam-2-0-0-rc2) — sorry to have been overlooking this). Thanks a lot @kit-ty-kate for all the effort to have it work!

**Comment by AltGr** [comment]
Ok, it seems what happens is that opam is killing the tests from its package with its own sandboxing !
It's only due to the fact that, to speedup further repository format upgrades from 1.2 to 2.0, it keeps a cache of archives hashes which were missing from the 1.2 repo in `~/.cache/opam-compilers-to-packages/url-hashes` — which it doesn't have write-access to with sandboxing enabled.

**Comment by kit-ty-kate** [comment]
should we remove the `build-test` field then or merge as is ?

**Comment by AltGr** [comment]
Indeed, removing it for now is a good idea, better than keeping it broken. Thanks!

**Comment by AltGr** [comment]
Tested and the hash cache isn't the only reason: we don't allow recursive sandboxing, so running opam's test within opam (and without explicitely disabling sandboxing for them) wouldn't work.

**Comment by AltGr** [comment]
We'll be good with https://github.com/ocaml/opam/pull/3367 for the next release

**Comment by kit-ty-kate** [comment]
Mmh there is an error when using the system switch on 4.06:
```
- (cd _build/default && /usr/local/bin/ocamlopt.opt -w -40 -w +a-4-44-48 -warn-error A -safe-string -g -I /home/travis/.opam/system/lib/ocamlgraph -I /home/travis/.opam/system/lib/re -I /usr/local/lib/ocaml -no-alias-deps -I src/core -o src/core/opamSHA.cmx -c -impl src/core/opamSHA.ml)
- File "src/core/opamSHA.ml", line 114, characters 17-32:
- Error (warning 3): deprecated: B.Array1.map_file
- Use [array1_of_genarray (Unix.map_file ...)] instead.
- Note that Bigarray.Array1.map_file raises Sys_error while
- Unix.map_file raises Unix_error.
- make: *** [opam-core.install] Error 1
```
Did you really want to put `-warn-error A` ?

**Comment by AltGr** [comment]
Gaaah, __I__ don't, and it's only enabled when running from Travis! What I don't understand is that I still disabled warn 3 for this exact purpose:
https://github.com/ocaml/opam/blob/master/configure.ac#L128-L130

**Pull request merged**
