### PR TITLE
Constrain async_ssl 113.00.00 o ctypes versions below 0.6.0

### PR DESCRIPTION
**Pull request by yallop**
See https://github.com/janestreet/async_ssl/pull/11

/cc @diml

### CODE REVIEW

**Comment by dsheets** [comment]
#6680 #6681 #6682 have been opened to address issues found during testing of this PR. Please split this PR into changes on smaller package sets and rebase on top of `master` when those PRs merge.

**Comment by yallop** [comment]
This fails on OS X, but I think that's expected.

**Comment by dsheets** [comment]
`async_ssl.113.00.00` fails but the others should be fine. Please, add the restriction on 113.00.00 for OS X.

**Comment by yallop** [comment]
See ce6641f.

**Comment by yallop** [comment]
The job [timed out](https://travis-ci.org/ocaml/opam-repository/jobs/135603786):
> The job exceeded the maxmimum time limit for jobs, and has been terminated.

**Comment by dsheets** [comment]
Yes, it likely tries to build all of core several times for each version of the package. I recommend putting each version in its own PR. :-(

**Comment by yallop** [comment]
Split:
* #6664 fixes `async_ssl.113.00.00`
* #6707 fixes `async_ssl.113.00.01`
* #6708 fixes `async_ssl.113.24.00`

**Pull request merged**
