### PR TITLE
[new release] js_of_ocaml-webidl and js_of_ocaml-webgpu (0.2)

### PR DESCRIPTION
**Pull request by tari3x**
Generate js_of_ocaml bindings from webidl definitions

- Project page: <a href="https://github.com/tari3x/webgpu">https://github.com/tari3x/webgpu</a>
- Documentation: <a href="https://tari3x.github.io/webgpu">https://tari3x.github.io/webgpu</a>

##### CHANGES:

Init

### CODE REVIEW

**Comment by tari3x** [comment]
Hmm, what do I click to see the error?

**Comment by kit-ty-kate** [comment]
The error was that `{= "version"}` is not equivalent to `{= version}` so opam was looking to get `js_of_ocaml-webidl.version` instead of `js_of_ocaml-webidl.0.2` and our CI detected that the required package didn't exist and that the package couldn't be installed.

I fixed the issue here, I'll simply wait for the CI to finish and merge this. In the meantime could you fix your `dune-project`? The following patch should do the job:
```
@@ -40,6 +38,6 @@
    js_of_ocaml-ppx
    ppx_jane
    ocamlformat
-   (js_of_ocaml-webidl (= version))
+   (js_of_ocaml-webidl (= :version))
   )
  )
```

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by tari3x** [comment]
Made the change on my side, thanks!

Fwiw, I still don't know how I could have figured it myself - I couldn't see the error from CI.

**Comment by tari3x** [comment]
Interesting, why does this still show that it's version 0.1?
https://opam.ocaml.org/packages/js_of_ocaml-webgpu/

**Comment by tari3x** [comment]
Is 0.2 now. Guess it takes a while to propagate.

**Comment by kit-ty-kate** [comment]
It usually only takes a couple of hours but we got a problem with the server used to do this task (fixed now as you've seen). Sorry for that

**Comment by tari3x** [comment]
No problem, thanks for looking into it!

**Pull request merged**
