### PR TITLE
bibtex2html 1.99

### PR DESCRIPTION
**Pull request by backtracking**
fixed compilation with OCaml 4.06
now requires OCaml >= 4.03.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Could you fix the errors and warnings above ? Seems good otherwise.

**Comment by kit-ty-kate** [comment]
(if the first error is not clear enough: you have to put ```"1.2"``` instead of ```"1"``` there)

**Comment by backtracking** [comment]
thanks for the clarification regarding the opam version number
I've fixed everything except "remove" (will be fixed in the next release)

**Comment by backtracking** [comment]
I'm still getting "Errors for `bibtex2html.1.99`" from camelus, with no Details. 
I thought I would been left with the "remove" warning only. Any clue?

**Comment by kit-ty-kate** [comment]
So for the second warning you have either to add the ```.git``` suffix to your url.
For the first one I don't understand why this cannot be fixed now ? Could you extract your patch and patch it manually here or just call directly the ```rm``` command for each files installed ?
I would **really** prefer to not have a package that is basically "uninstallable".

**Comment by backtracking** [comment]
Thanks.
Regarding "remove", I've added a "make uninstall" to bibtex2html sources already. I'm just lacking time to make a new release. So let's keep it like this for the moment if you don't mind.

**Comment by kit-ty-kate** [comment]
Ok. I'll merge this as soon as the CI is green and I'll open a PR to fix the previous versions as well (I'll go with a local patch).

**Comment by kit-ty-kate** [comment]
Thanks !

**Pull request merged**
