### PR TITLE
[camlp5] Updade to 7.01

### PR DESCRIPTION
**Pull request by ejgallego**
Needed for Coq + OCaml 4.05 among others.

### CODE REVIEW

**Comment by avsm** [comment]
restarted some failed jobs

**Comment by avsm** [comment]
4.05 is failing because of a bad upstream container update that led to 4.05.1dev being made available. I've pushed a fix now and will restart the job.

**Comment by ejgallego** [comment]
@avsm I was wondering about this, thanks! I did strengthen the upper constraint to `<= 4.05.0` thou, as it seems that Camlp5 chokes on `4.05.1`, but I am wondering why the old package had a `<= 4.06` constraint.

**Comment by avsm** [comment]
Bah, it's unclear how often Travis refreshes its container cache. I'll go ahead and merge this since it passes manual testing. Thanks for the contribution!

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
