### PR TITLE
Add package for OCaml-safepass 2.0

### PR DESCRIPTION
**Pull request by darioteixeira**

### CODE REVIEW

**Comment by yallop** [comment]
The `remove` step is [leaving something behind](https://travis-ci.org/ocaml/opam-repository/jobs/139230301):

```
Directory /home/travis/.opam/4.03.0/doc/safepass is not empty, not
          removing
```

**Comment by darioteixeira** [comment]
@yallop: that would be documentation, and was already the case with previous versions of the package.  Shouldn't OPAM automatically take care of removing the docs?

**Comment by avsm** [comment]
@darioteixeira unfortunately not -- the `remove` field should take it out (although this is improved in OPAM2). 

```
+remove: [["ocamlfind" "remove" "safepass"]]
```

whereas you call `make install` that also builds and installs the docs.

**Comment by darioteixeira** [comment]
@avsm: Okay, I can see two ways of doing this: `["rm" "-rf" "%{share}%/doc/safepass"]` and `["rm" "-rf" safepass:doc]`.  The latter seems preferable; but is it future-proof?

**Comment by yallop** [comment]
Another option is to use a [`*.install` file](https://opam.ocaml.org/doc/manual/dev-manual.html#sec25) for the documentation files, to delegate removal of those files to opam.

**Pull request merged**
