### PR TITLE
atd 2.0.0

### PR DESCRIPTION
**Pull request by mjambon**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Looks like you opam files are in the 2.0 format. Could you go back to the 1.2 format so that I can merge it ?

(for the record the CI is down right now so I won't be able to merge anything in the meantime, sorry for the inconvenience)

**Comment by kit-ty-kate** [comment]
Some old version of `atdgen` & `atdj` seems to require some extra constraints:
```
#=== ERROR while compiling atdgen.1.13.0 ======================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.06.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.06/.opam-switch/build/atdgen.1.13.0
# command              ~/.opam/4.06/bin/jbuilder build -p atdgen -j 47
# exit-code            1
# env-file             ~/.opam/log/atdgen-18-12ca7e.env
# output-file          ~/.opam/log/atdgen-18-12ca7e.out
### output ###
#       ocamlc atdgen/src/.atdgen_emit.objs/atdgen_emit__Indent.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I atdgen/src/.atdgen_emit.objs -I /home/opam/.opam/4.06/lib/atd -I /home/opam/.opam/4.06/lib/biniou -I /home/opam/.opam/4.06/lib/easy-format -I /home/opam/.opam/4.06/lib/yojson -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/atdgen_emit__Indent.cmo -c -impl atdgen/src/indent.ml)
# File "atdgen/src/indent.ml", line 14, characters 21-33:
# Error: Unbound module Atd.Indent
#     ocamlopt atdgen/src/.atdgen_emit.objs/atdgen_emit__Biniou.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -safe-string -g -I atdgen/src/.atdgen_emit.objs -I /home/opam/.opam/4.06/lib/atd -I /home/opam/.opam/4.06/lib/biniou -I /home/opam/.opam/4.06/lib/easy-format -I /home/opam/.opam/4.06/lib/yojson -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/atdgen_emit__Biniou.cmx -c -impl atdgen/src/biniou.ml)
# File "atdgen/src/biniou.ml", line 60, characters 22-42:
# Error: This expression has type string -> biniou_int option
#        but an expression was expected of type
#          Atd.Annot.t = Atd.Ast.annot_section list
#     ocamlopt atdgen/src/.atdgen_emit.objs/atdgen_emit__Json.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -safe-string -g -I atdgen/src/.atdgen_emit.objs -I /home/opam/.opam/4.06/lib/atd -I /home/opam/.opam/4.06/lib/biniou -I /home/opam/.opam/4.06/lib/easy-format -I /home/opam/.opam/4.06/lib/yojson -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/atdgen_emit__Json.cmx -c -impl atdgen/src/json.ml)
# File "atdgen/src/json.ml", line 57, characters 4-28:
# Error: This expression has type string -> int option option
#        but an expression was expected of type
#          Atd.Annot.t = Atd.Ast.annot_section list
#     ocamlopt atdgen/src/.atdgen_emit.objs/atdgen_emit__Validate.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -safe-string -g -I atdgen/src/.atdgen_emit.objs -I /home/opam/.opam/4.06/lib/atd -I /home/opam/.opam/4.06/lib/biniou -I /home/opam/.opam/4.06/lib/easy-format -I /home/opam/.opam/4.06/lib/yojson -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/atdgen_emit__Validate.cmx -c -impl atdgen/src/validate.ml)
# File "atdgen/src/validate.ml", line 34, characters 24-48:
# Error: This expression should not be a function, the expected type is
# Atd.Annot.t
#     ocamlopt atdgen/src/.atdgen_emit.objs/atdgen_emit__Doc.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -safe-string -g -I atdgen/src/.atdgen_emit.objs -I /home/opam/.opam/4.06/lib/atd -I /home/opam/.opam/4.06/lib/biniou -I /home/opam/.opam/4.06/lib/easy-format -I /home/opam/.opam/4.06/lib/yojson -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/atdgen_emit__Doc.cmx -c -impl atdgen/src/doc.ml)
# File "atdgen/src/doc.ml", line 15, characters 22-38:
# Error: This expression has type
#          string -> [> `Text of block list ] option option
#        but an expression was expected of type
#          Atd.Annot.t = Atd.Ast.annot_section list
```
```
#=== ERROR while compiling atdj.1.13.0 ========================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.06.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.06/.opam-switch/build/atdj.1.13.0
# command              ~/.opam/4.06/bin/jbuilder build -p atdj -j 47
# exit-code            1
# env-file             ~/.opam/log/atdj-18-1b522a.env
# output-file          ~/.opam/log/atdj-18-1b522a.out
### output ###
#       ocamlc atdgen/src/.atdgen_emit.objs/atdgen_emit__Indent.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I atdgen/src/.atdgen_emit.objs -I /home/opam/.opam/4.06/lib/atd -I /home/opam/.opam/4.06/lib/biniou -I /home/opam/.opam/4.06/lib/easy-format -I /home/opam/.opam/4.06/lib/yojson -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/atdgen_emit__Indent.cmo -c -impl atdgen/src/indent.ml)
# File "atdgen/src/indent.ml", line 14, characters 21-33:
# Error: Unbound module Atd.Indent
#     ocamlopt atdgen/src/.atdgen_emit.objs/atdgen_emit__Biniou.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -safe-string -g -I atdgen/src/.atdgen_emit.objs -I /home/opam/.opam/4.06/lib/atd -I /home/opam/.opam/4.06/lib/biniou -I /home/opam/.opam/4.06/lib/easy-format -I /home/opam/.opam/4.06/lib/yojson -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/atdgen_emit__Biniou.cmx -c -impl atdgen/src/biniou.ml)
# File "atdgen/src/biniou.ml", line 60, characters 22-42:
# Error: This expression has type string -> biniou_int option
#        but an expression was expected of type
#          Atd.Annot.t = Atd.Ast.annot_section list
#     ocamlopt atdgen/src/.atdgen_emit.objs/atdgen_emit__Validate.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -safe-string -g -I atdgen/src/.atdgen_emit.objs -I /home/opam/.opam/4.06/lib/atd -I /home/opam/.opam/4.06/lib/biniou -I /home/opam/.opam/4.06/lib/easy-format -I /home/opam/.opam/4.06/lib/yojson -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/atdgen_emit__Validate.cmx -c -impl atdgen/src/validate.ml)
# File "atdgen/src/validate.ml", line 34, characters 24-48:
# Error: This expression should not be a function, the expected type is
# Atd.Annot.t
#     ocamlopt atdgen/src/.atdgen_emit.objs/atdgen_emit__Json.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -safe-string -g -I atdgen/src/.atdgen_emit.objs -I /home/opam/.opam/4.06/lib/atd -I /home/opam/.opam/4.06/lib/biniou -I /home/opam/.opam/4.06/lib/easy-format -I /home/opam/.opam/4.06/lib/yojson -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/atdgen_emit__Json.cmx -c -impl atdgen/src/json.ml)
# File "atdgen/src/json.ml", line 57, characters 4-28:
# Error: This expression has type string -> int option option
#        but an expression was expected of type
#          Atd.Annot.t = Atd.Ast.annot_section list
#     ocamlopt atdgen/src/.atdgen_emit.objs/atdgen_emit__Doc.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -safe-string -g -I atdgen/src/.atdgen_emit.objs -I /home/opam/.opam/4.06/lib/atd -I /home/opam/.opam/4.06/lib/biniou -I /home/opam/.opam/4.06/lib/easy-format -I /home/opam/.opam/4.06/lib/yojson -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/atdgen_emit__Doc.cmx -c -impl atdgen/src/doc.ml)
# File "atdgen/src/doc.ml", line 15, characters 22-38:
# Error: This expression has type
#          string -> [> `Text of block list ] option option
#        but an expression was expected of type
#          Atd.Annot.t = Atd.Ast.annot_section list
```
Also some packages seem to have been broken:
```
#=== ERROR while compiling hardcaml-yosys.0.1.0 ===============================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.06.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.06/.opam-switch/build/hardcaml-yosys.0.1.0
# command              ~/.opam/4.06/bin/ocaml pkg/pkg.ml build
# exit-code            1
# env-file             ~/.opam/log/hardcaml-yosys-18-75ac8d.env
# output-file          ~/.opam/log/hardcaml-yosys-18-75ac8d.out
### output ###
# ocamlfind ocamlopt unix.cmxa -I /home/opam/.opam/4.06/lib/ocamlbuild /home/opam/.opam/4.06/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /home/opam/.opam/4.06/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# atdgen -t -o src/yosys_atd src/yosys_atd.atd
# ocamlfind ocamldep -syntax camlp4o -package hardcaml -package hardcaml.syntax -package atdgen -package yojson -modules src/yosys_atd_t.mli > src/yosys_atd_t.mli.depends
# + ocamlfind ocamldep -syntax camlp4o -package hardcaml -package hardcaml.syntax -package atdgen -package yojson -modules src/yosys_atd_t.mli > src/yosys_atd_t.mli.depends
# File "src/yosys_atd_t.mli", line 2, characters 14-18:
# Parse error: illegal begin of interf
# File "src/yosys_atd_t.mli", line 1:
# Error: Error while running external preprocessor
# Command line: camlp4 '-I' '/home/opam/.opam/4.06/lib/ocaml/camlp4' '-I' '/home/opam/.opam/4.06/lib/hardcaml' '-parser' 'o' '-parser' 'op' '-printer' 'p' 'pa_hardcaml.cmo'  'src/yosys_atd_t.mli' > /tmp/ocamlpp8ee3bd
# 
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'src/HardCamlYosys.cmxs' 'src/HardCamlYosys.cmxa'
#      'src/HardCamlYosys.cmx' 'src/HardCamlYosys.cma' 'src/HardCamlYosys.cmi'
#      'src/HardCamlYosys.a' 'src/import.mli' 'src/cell.mli' 'src/techlib.mli'
#      'src/lvt.mli' 'src/io.mli' 'src/yosys_atd_j.mli' 'src/yosys_atd_t.mli']: exited with 10
```
```
#=== ERROR while compiling raygun4ocaml.0.1.0 =================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.06.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.06/.opam-switch/build/raygun4ocaml.0.1.0
# command              ~/.opam/4.06/bin/ocaml setup.ml -build
# exit-code            1
# env-file             ~/.opam/log/raygun4ocaml-18-6aa130.env
# output-file          ~/.opam/log/raygun4ocaml-18-6aa130.out
### output ###
# File "./setup.ml", line 318, characters 20-36:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "./setup.ml", line 318, characters 42-58:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "./setup.ml", line 327, characters 14-30:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "./setup.ml", line 327, characters 38-54:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "./setup.ml", line 330, characters 25-41:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "./setup.ml", line 368, characters 10-26:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "./setup.ml", line 474, characters 13-29:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "./setup.ml", line 1825, characters 16-33:
# Warning 3: deprecated: String.capitalize
# Use String.capitalize_ascii instead.
# File "./setup.ml", line 1831, characters 16-35:
# Warning 3: deprecated: String.uncapitalize
# Use String.uncapitalize_ascii instead.
# File "setup.ml", line 5847, characters 11-28:
# Warning 3: deprecated: String.capitalize
# Use String.capitalize_ascii instead.
# File "setup.ml", line 5848, characters 11-30:
# Warning 3: deprecated: String.uncapitalize
# Use String.uncapitalize_ascii instead.
# W: Cannot find source file matching module 'raygun' in library raygun
# /home/opam/.opam/4.06/bin/ocamlopt.opt unix.cmxa -I /home/opam/.opam/4.06/lib/ocamlbuild /home/opam/.opam/4.06/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/opam/.opam/4.06/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# File "_tags", line 31, characters 18-32:
# Warning: the tag "pkg_cohttp.lwt" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
# File "_tags", line 32, characters 18-25:
# Warning: the tag "pkg_lwt" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
# /home/opam/.opam/4.06/bin/ocamlfind ocamldep -package ISO8601 -package atdgen -package unix -modules lib/time.mli > lib/time.mli.depends
# /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/time.cmi lib/time.mli
# /home/opam/.opam/4.06/bin/ocamlfind ocamldep -package ISO8601 -package atdgen -package unix -modules lib/time.ml > lib/time.ml.depends
# /home/opam/.opam/4.06/bin/ocamlfind ocamldep -package ISO8601 -package atdgen -package unix -modules lib/raygun_t.mli > lib/raygun_t.mli.depends
# /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/raygun_t.cmi lib/raygun_t.mli
# /home/opam/.opam/4.06/bin/ocamlfind ocamldep -package ISO8601 -package atdgen -package unix -modules lib/raygun_t.ml > lib/raygun_t.ml.depends
# /home/opam/.opam/4.06/bin/ocamlfind ocamldep -package ISO8601 -package atdgen -package unix -modules lib/stacktrace.mli > lib/stacktrace.mli.depends
# /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/stacktrace.cmi lib/stacktrace.mli
# /home/opam/.opam/4.06/bin/ocamlfind ocamldep -package ISO8601 -package atdgen -package unix -modules lib/stacktrace.ml > lib/stacktrace.ml.depends
# /home/opam/.opam/4.06/bin/ocamlfind ocamldep -package ISO8601 -package atdgen -package unix -modules lib/api.mli > lib/api.mli.depends
# /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/api.cmi lib/api.mli
# /home/opam/.opam/4.06/bin/ocamlfind ocamldep -package ISO8601 -package atdgen -package unix -modules lib/api.ml > lib/api.ml.depends
# /home/opam/.opam/4.06/bin/ocamlfind ocamldep -package ISO8601 -package atdgen -package unix -modules lib/raygun_j.mli > lib/raygun_j.mli.depends
# /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/raygun_j.cmi lib/raygun_j.mli
# /home/opam/.opam/4.06/bin/ocamlfind ocamldep -package ISO8601 -package atdgen -package unix -modules lib/raygun_j.ml > lib/raygun_j.ml.depends
# /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/time.cmo lib/time.ml
# /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/raygun_t.cmo lib/raygun_t.ml
# /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/stacktrace.cmo lib/stacktrace.ml
# /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/api.cmo lib/api.ml
# /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/raygun_j.cmo lib/raygun_j.ml
# + /home/opam/.opam/4.06/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ISO8601 -package atdgen -package unix -I lib -o lib/raygun_j.cmo lib/raygun_j.ml
# File "lib/raygun_j.ml", line 96, characters 2-24:
# Error: Unbound module Ag_oj_run
# Command exited with code 2.
# + /home/opam/.opam/4.06/bin/ocamlopt.opt unix.cmxa -I /home/opam/.opam/4.06/lib/ocamlbuild /home/opam/.opam/4.06/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/opam/.opam/4.06/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# File "myocamlbuild.ml", line 518, characters 43-62:
# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
# Use String.uncapitalize_ascii instead.
# File "myocamlbuild.ml", line 531, characters 51-70:
# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
# Use String.uncapitalize_ascii instead.
# E: Failure("Command ''/home/opam/.opam/4.06/bin/ocamlbuild' lib/raygun.cma lib/raygun.cmxa lib/raygun.a lib/raygun.cmxs -tag debug' terminated with error code 10")
```

**Comment by mjambon** [comment]
Thanks for summarizing the problems. I think I fixed them, let's see how it goes.

**Comment by mjambon** [comment]
I'm wondering if there's a way to expedite the task of fixing problems with reverse dependencies. Say package B depends on package A, and B fails to build with the latest version of A. I'm thinking of:

1. Semi-automatically adding a version constraint preventing the use of the current version of the package A by all the existing versions of package B.
2. Semi-automatically emailing the package maintainer about this.

Are there tools that could help us do this? Is it in the works? Should I make a proper feature request?

**Comment by rgrinberg** [comment]
@mjambon have you considered adding `conflicts` to your submission rather than updating constraints for old packages that nobody is likely to use anyway. It might seem a bit harsh, since we are likely to rule out many valid build plans but the alternatives seems much worse. E.g something like:

```
conflicts: [
  "atd" {< "2.0.0"}
  "atdgen" {< "2.0.0"}
  "wcslib "..." 
]
```

You can generate a list of packages quickly with `$ opam list --depends-on atdgen` (and `atd`) and just slap a conflict with the current version.

I know this isn't ideal, but spending valuable time on this stuff is even more counter productive.

**Comment by mjambon** [comment]
Thanks @rgrinberg. I declared a list of conflicts. Let's see what happens now.

**Comment by kit-ty-kate** [comment]
mmh this is really really not ideal what was the problem when you tried to fix the packages one by one ?

**Comment by kit-ty-kate** [comment]
Otherwise everything seems good and I'm keen to merge this tomorrow but I would really really like to avoid this kind of fix if it's not temporary.

**Comment by mjambon** [comment]
@kit-ty-kate 

There are just too many packages that depend on atd and which are broken for various reasons. I don't have the resources to take care of them myself; their respective maintainers should do this job at their own pace.

I understand that this is not ideal, but at least it leaves a written acknowledgment of the problems and allows us to move on.

**Comment by rgrinberg** [comment]
Martin Jambon <notifications@github.com> writes:

> Thanks @rgrinberg. I declared a list of conflicts. Let's see what happens now.

Yeah, hopefully this will us move on in a simpler way.

It's unfortunate, but as maintainers we simply can't take the
responsibility for fixing constraints on random opam packages. You're
not "doing it wrong", many submitters have the exact same problems.

I prefer to spend my open source time fixing bugs or developing new
features rather than messing up with CI and package constraints. I
recommend this approach to other maintainers as well.

Kate, unfortunately the current opam submission process doesn't scale
for even moderately used opam packages. We need to think of something
here...

**Comment by kit-ty-kate** [comment]
@rgrinberg ok I'll try to come up with something.

Thanks!

**Pull request merged**
