### PR TITLE
Planck

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
Seems insufficient dep:

```
# Camlp4: Uncaught exception: DynLoader.Error ("../pa_bind_inline/pa_bind_inline.cmo", "file not found in path")
# 
# File "plpautoconv.ml", line 1:
# Error: Error while running external preprocessor
# Command line: camlp4 '-I' '/usr/local/lib/ocaml/camlp4' '-I' '/Users/travis/.opam/system/lib/type_conv' '-I' '/usr/local/lib/ocaml' '-I' '/usr/local/lib/ocaml' '-I' '/Users/travis/.opam/system/lib/sexplib' '-I' '/Users/travis/.opam/system/lib/sexplib' '-I' '/Users/travis/.opam/system/lib/monad-custom' '-parser' 'o' '-parser' 'op' '-printer' 'p' 'pa_type_conv.cma' 'unix.cma' 'bigarray.cma' 'sexplib.cma' 'pa_sexp_conv.cma' 'pa_monad.cmo' '../pa_bind_inline/pa_bind_inline.cmo' 'plpautoconv.ml' > /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/ocamlppfa8756
```

**Comment by camlspotter** [comment]
Confirmed:

```
$ omake ocaml/plpautoconv.cmi
*** omake: reading OMakefiles
*** omake: finished reading OMakefiles (0.11 sec)
- scan ocaml scan-ocaml-plpautoconv.ml
+ ocamlfind ocamldep -package spotlib,sexplib,ocamlgraph,compiler-libs.common -syntax camlp4o -package sexplib.syntax,monad-custom -ppopt ../pa_bind_inline/pa_bind_inline.cmo -modules plpautoconv.ml
     | Shell.ocamldep-postproc()
Camlp4: Uncaught exception: DynLoader.Error ("../pa_bind_inline/pa_bind_inline.cmo", "file not found in path")
```

**Comment by camlspotter** [comment]
Fixed and verified it builds with spotlib.2.2.0

**Comment by OCamlPro-Henry** [comment]
Thanks !

**Pull request merged**
