### PR TITLE
conf-openjdk: add Ubuntu-family support

### PR DESCRIPTION
**Pull request by jmid**

### CODE REVIEW

**Comment by jmid** [comment]
CI is failing on
- Alpine
- OpenSuse
- Oracle
- x86_32
- FreeBSD
- macOS

Note: none of these were changed (so far) in the PR.
- Oracle and FreeBSD are failing the system package install.
- 32-bit is failing with
  ```
  # Error: missing `server' JVM at `/usr/lib/jvm/java-17-openjdk-i386/lib/server/libjvm.so'.
  # Please install or use the JRE or JDK that contains these missing components.
  ```
- The rest are failing due to a missing PATH I suspect

**Comment by jmid** [comment]
Compared to the above status
- FreeBSD is failing package install (as Oracle has been removed)
- Alpine, OpenSuse, FreeBSD, and macOS are failing the `javac -version` check

The former fails with
```
- pkg: No packages available to install matching 'openjdk' have been found in the repositories
[ERROR] System package install failed with exit code 1 at command:
            sudo pkg install -y openjdk
[ERROR] These packages are still missing: openjdk
```
From https://www.freshports.org/search.php?query=openjdk it seems `openjdk` is no longer a valid package name.
Instead only specific version names, e.g., openjdk11/openjdk21 are listed.
I've thus gone for installing `openjdk19` which seems neither bleeding edge nor ancient, so that it installs on a FreeBSD box from within the past couple of years.

For the latter, I'm unsure whether conf-packages should manipulate PATH to find `javac`.
For now, I've therefore gone with adding a post-install failure message to the user.

**Comment by mseri** [comment]
I think we should not manipulate the path,  it is ok with the explicit failure message.

I would remove freebsd depext and add a failure message saying to install a version of openjdk if this fails to install.

**Comment by jmid** [comment]
OK, the latest 3 commit attempt to do so.

**Comment by shonfeder** [comment]
Would it make sense to add the failure messages to the other failing platforms? Or do we think we will get those passing eventually in this PR too?

Failing now on 

- alpine: `[conf-openjdk.1 (failed: The compilation of conf-openjdk.1 failed at "javac -version".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f723d510bcbf7c62b759d388b0fbd95b1689e4fe/variant/distributions,alpine-3.20-ocaml-5.2,conf-openjdk.1)`

- opensuse: `[conf-openjdk.1 (failed: The compilation of conf-openjdk.1 failed at "javac -version".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f723d510bcbf7c62b759d388b0fbd95b1689e4fe/variant/distributions,opensuse-15.6-ocaml-4.14,conf-openjdk.1)`

- x86_32-ocaml-4.14: `[conf-openjdk.1 (failed: missing `server' JVM at `/usr/lib/jvm/java-17-openjdk-i386/lib/server/libjvm.so'.)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f723d510bcbf7c62b759d388b0fbd95b1689e4fe/variant/extras,x86_32-ocaml-4.14,conf-openjdk.1)`

- macos: `[conf-openjdk.1 (failed: The compilation of conf-openjdk.1 failed at "javac -version".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f723d510bcbf7c62b759d388b0fbd95b1689e4fe/variant/macos,macos-homebrew-ocaml-4.14-amd64,conf-openjdk.1)`

**Comment by jmid** [comment]
The error message is actually being printed for all failing platforms, it is just a bit lost in the output.
For example, here's a quote from an Alpine log:
```
<><> conf-openjdk.1 troubleshooting <><><><><><><><><><><><><><><><><><><><><><>
=> Please ensure that the javac binary is installed and is available in PATH
....
```
I'm open to input as to how to highlight the message a bit more.


The x86_32 failure stands a bit out because the system package install is failing there with
```
Error: missing `server' JVM at `/usr/lib/jvm/java-17-openjdk-i386/lib/server/libjvm.so'.
```
which seems to be a known issue caused by either
- a missing `server` directory https://forums.raspberrypi.com/viewtopic.php?t=197824 or
- a large file system https://bugs.openjdk.org/browse/JDK-8280747

Overall, there's not much more to do opam-ci-wise, so 3e9c57b marks them as expected failures.

**Comment by jmid** [comment]
There's something strange going on with x86_32
- CI passed in 3e9c57b and we got a green light https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/3e9c57ba0e4b6738a9c324694b8deef36b2c7bd2/variant/extras,x86_32-ocaml-4.14,conf-openjdk.1
- CI then failed in aabaa4e with the missing `server` error https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/aabaa4e9103598d6faa972a978909cbae7e91c7a/variant/extras,x86_32-ocaml-4.14,conf-openjdk.1

I guess this could be explained by variations in "large file system" (as linked above) between CI machines? :thinking: 

Also fixed the x-ci-accept-failures platform name for it.

**Comment by jmid** [comment]
Modulo a lint failure this is now green and should thus be good to go.

**Comment by shonfeder** [comment]
Looks great. The linting failure is not relevant to these changes.

**Comment by dinosaure** [comment]
Thanks!

**Pull request merged**
