### PR TITLE
Package zarith.1.9.1

### PR DESCRIPTION
**Pull request by antoinemine**
### `zarith.1.9.1`
Implements arithmetic and logical operations over arbitrary-precision integers
The Zarith library implements arithmetic and logical operations over
arbitrary-precision integers. It uses GMP to efficiently implement
arithmetic over big integers. Small integers are represented as Caml
unboxed integers, for speed and space economy.

---
* Homepage: https://github.com/ocaml/Zarith
* Source repo: git+https://github.com/ocaml/Zarith.git
* Bug tracker: https://github.com/ocaml/Zarith/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
It seems like neither `bignum` (cc @xclerc) nor `zarith-ppx` (cc @Drup) are compatible with this release.
```
#=== ERROR while compiling bignum.v0.12.0 =====================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.08.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.08/.opam-switch/build/bignum.v0.12.0
# command              ~/.opam/4.08/bin/dune build -p bignum -j 2
# exit-code            1
# env-file             ~/.opam/log/bignum-17-dc59a3.env
# output-file          ~/.opam/log/bignum-17-dc59a3.out
### output ###
#       ocamlc src/.bignum.objs/byte/bignum__Bignum0.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.bignum.objs/byte -I /home/opam/.opam/4.08/lib/base -I /home/opam/.opam/4.08/lib/base/caml -I /home/opam/.opam/4.08/lib/base/md5 -I /home/opam/.opam/4.08/lib/base/shadow_stdlib -I /home/opam/.opam/4.08/lib/base_bigstring -I /home/opam/.opam/4.08/lib/base_quickcheck -I /home/opam/.opam/4.08/lib/bin_prot -I /home/opam/.opam/4.08/lib/bin_prot/shape -I /home/opam/.opam/4.08/lib/core_kernel -I /home/opam/.opam/4.08/lib/core_kernel/base_for_tests -I /home/opam/.opam/4.08/lib/fieldslib -I /home/opam/.opam/4.08/lib/jane-street-headers -I /home/opam/.opam/4.08/lib/num -I /home/opam/.opam/4.08/lib/parsexp -I /home/opam/.opam/4.08/lib/ppx_assert/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_bench/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_expect/collector -I /home/opam/.opam/4.08/lib/ppx_expect/common -I /home/opam/.opam/4.08/lib/ppx_expect/config -I /home/opam/.opam/4.08/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_inline_test/config -I /home/opam/.opam/4.08/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_module_timer/runtime -I /home/opam/.opam/4.08/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.08/lib/sexplib -I /home/opam/.opam/4.08/lib/sexplib0 -I /home/opam/.opam/4.08/lib/splittable_random -I /home/opam/.opam/4.08/lib/stdio -I /home/opam/.opam/4.08/lib/time_now -I /home/opam/.opam/4.08/lib/typerep -I /home/opam/.opam/4.08/lib/variantslib -I /home/opam/.opam/4.08/lib/zarith -I bigint/src/.bigint.objs/byte -I bigint/src/.bigint.objs/native -intf-suffix .ml -no-alias-deps -open Bignum__ -o src/.bignum.objs/byte/bignum__Bignum0.cmo -c -impl src/bignum0.pp.ml)
# File "src/bignum0.ml", line 24, characters 15-31:
# 24 |         if n > max_memoized_pow then begin
#                     ^^^^^^^^^^^^^^^^
# Error: This expression has type int but an expression was expected of type
#          t = Q.t
#     ocamlopt src/.bignum.objs/native/bignum__Bignum0.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlopt.opt -w -40 -g -I src/.bignum.objs/byte -I src/.bignum.objs/native -I /home/opam/.opam/4.08/lib/base -I /home/opam/.opam/4.08/lib/base/caml -I /home/opam/.opam/4.08/lib/base/md5 -I /home/opam/.opam/4.08/lib/base/shadow_stdlib -I /home/opam/.opam/4.08/lib/base_bigstring -I /home/opam/.opam/4.08/lib/base_quickcheck -I /home/opam/.opam/4.08/lib/bin_prot -I /home/opam/.opam/4.08/lib/bin_prot/shape -I /home/opam/.opam/4.08/lib/core_kernel -I /home/opam/.opam/4.08/lib/core_kernel/base_for_tests -I /home/opam/.opam/4.08/lib/fieldslib -I /home/opam/.opam/4.08/lib/jane-street-headers -I /home/opam/.opam/4.08/lib/num -I /home/opam/.opam/4.08/lib/parsexp -I /home/opam/.opam/4.08/lib/ppx_assert/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_bench/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_expect/collector -I /home/opam/.opam/4.08/lib/ppx_expect/common -I /home/opam/.opam/4.08/lib/ppx_expect/config -I /home/opam/.opam/4.08/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_inline_test/config -I /home/opam/.opam/4.08/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.08/lib/ppx_module_timer/runtime -I /home/opam/.opam/4.08/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.08/lib/sexplib -I /home/opam/.opam/4.08/lib/sexplib0 -I /home/opam/.opam/4.08/lib/splittable_random -I /home/opam/.opam/4.08/lib/stdio -I /home/opam/.opam/4.08/lib/time_now -I /home/opam/.opam/4.08/lib/typerep -I /home/opam/.opam/4.08/lib/variantslib -I /home/opam/.opam/4.08/lib/zarith -I bigint/src/.bigint.objs/byte -I bigint/src/.bigint.objs/native -intf-suffix .ml -no-alias-deps -open Bignum__ -o src/.bignum.objs/native/bignum__Bignum0.cmx -c -impl src/bignum0.pp.ml)
# File "src/bignum0.ml", line 24, characters 15-31:
# 24 |         if n > max_memoized_pow then begin
#                     ^^^^^^^^^^^^^^^^
# Error: This expression has type int but an expression was expected of type
#          t = Q.t
```
```
#=== ERROR while compiling zarith-ppx.0.1 =====================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.08.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.08/.opam-switch/build/zarith-ppx.0.1
# command              ~/.opam/4.08/bin/dune runtest -p zarith-ppx -j 2
# exit-code            1
# env-file             ~/.opam/log/zarith-ppx-17-95080a.env
# output-file          ~/.opam/log/zarith-ppx-17-95080a.out
### output ###
# File "README.md", line 1, characters 0-0:
#          git (internal) (exit 1)
# (cd _build/default && /usr/bin/git diff --no-index --color=always -u README.md README.md.corrected)
# diff --git a/README.md b/README.md.corrected
# index 7fda49f..dbcef87 100644
# --- a/README.md
# +++ b/README.md.corrected
# @@ -28,8 +28,9 @@ Here are some examples:
#  It also raises errors for incorrect literals:
#  ```ocaml
#  # 1.234e2z ;;
# -Characters 0-8:
# -Error: This literal does not fit in an integer. You should use a rational number.
# +Line 1, characters 1-9:
# +Error: This literal does not fit in an integer. You should use a rational
# +       number.
#  ```
#  
#  This package depends on vanilla Zarith, but the generated code is compatible with any cross-compiled version of Zarith such as `zarith-freestanding` and `zarith-xen`.
#         diff alias test/runtest (exit 1)
# (cd _build/default/test && /usr/bin/diff -dEbZBt testppx.result testppx.expected)
# 33,34c34,35
# < Line 3, characters 0-4:
# < 3 | 0b2z ;;
# ---
# > Characters 12-16:
# >   0b2z ;;
# 37,38c38,39
# < Line 1, characters 0-4:
# < 1 | 0O8z ;;
# ---
# > Characters 0-4:
# >   0O8z ;;
# 41,42c42,43
# < Line 1, characters 0-7:
# < 1 | 0x12g8z ;;
# ---
# > Characters 0-7:
# >   0x12g8z ;;
# 45,46c46,47
# < Line 1, characters 0-4:
# < 1 | 0b2q ;;
# ---
# > Characters 0-4:
# >   0b2q ;;
# 49,50c50,51
# < Line 1, characters 0-4:
# < 1 | 0O8q ;;
# ---
# > Characters 0-4:
# >   0O8q ;;
# 53,54c54,55
# < Line 1, characters 0-7:
# < 1 | 0x12g8q ;;
# ---
# > Characters 0-7:
# >   0x12g8q ;;
# 57,58c58,59
# < Line 3, characters 18-25:
# < 3 | let foo = [ Q.neg 0x12.4q ] ;;
# ---
# > Characters 46-53:
# >   let foo = [ Q.neg 0x12.4q ] ;;
# 60,63c61,63
# < Error: Hexadecimal floating point numbers are not accepted. Please use
# <        hexadecimal
# <        integers, or regular floating point
# <        numbers.
# ---
# > Error: Hexadecimal floating point numbers are not accepted. Please use hexadecimal
# > integers, or regular floating point
# > numbers.
# 74,75c74,75
# < Line 3, characters 0-4:
# < 3 | 1.2z;;
# ---
# > Characters 16-20:
# >   1.2z;;
# 77,80c77,79
# < Error: This literal does not fit in an integer. You should use a rational
# <        number.
# < Line 1, characters 0-6:
# < 1 | 1.e-4z;;
# ---
# > Error: This literal does not fit in an integer. You should use a rational number.
# > Characters 0-6:
# >   1.e-4z;;
# 82,83c81
# < Error: This literal does not fit in an integer. You should use a rational
# <        number.
# ---
# > Error: This literal does not fit in an integer. You should use a rational number.
```

**Comment by antoinemine** [comment]
For bignum: newer zariths redefine <, >, etc. in an effort to avoid bugs where OCaml's default polymorphic operators are used (they behave incorrectly on Q). bignum0.ml does a `include Zarith.Q` and use the overrided operators to compare integers. Note that the file has a similar problem with + and -, and solves it using Int.(+) and Int.(-). We could change bignum to use Int.(<), etc. Or revert zarith's choice to redefine <, >, etc. in Q... @xclerc, any though on the best solution?

For ppx-zarith, testing fails. The results in testppx.result actually seem correct. They do not match the provided testppx.expected, but only on minor aspects (how errors are printed, how lines are cut). I'm not sure how this is related to any change in Zarith. @Drup, any thought ?

**Comment by hhugo** [comment]
The work to adapt bignum is already done and is just waiting for zarith to be officially released.

**Comment by Drup** [comment]
> For ppx-zarith, testing fails. The results in testppx.result actually seem correct. They do not match the provided testppx.expected, but only on minor aspects (how errors are printed, how lines are cut). I'm not sure how this is related to any change in Zarith. @Drup, any thought ?

Sometimes, I really long for a porcelaine mode for ocaml error messages .... 
I'm pretty sure this is all fine, you can just disable the tests for recent ocaml versions.

**Comment by kit-ty-kate** [comment]
It's all fixed now. Thanks!

**Comment by antoinemine** [comment]
Thanks !

**Pull request merged**
