### PR TITLE
Add Topiary v0.3.0

### PR DESCRIPTION
**Pull request by Niols**
Website: https://topiary.tweag.io/
Repository: https://github.com/tweag/topiary
Release: https://github.com/tweag/topiary/releases/tag/v0.3.0
Change log: https://github.com/tweag/topiary/blob/v0.3.0/CHANGELOG.md

### CODE REVIEW

**Comment by Niols** [comment]
All the CI errors seem to be related to the Rust lower bound not being respected on the test machines. Topiary v0.3.0 requires Rust ≥ 1.70.0. This does make me wonder again whether we should introduce a package say `conf-rust-ge-1-70-0` to specify those requirements in a cleaner way.

There still remains an error with openSUSE and I have been aware of it for a while and sadly have no idea where it comes from. I think it's more an issue for Topiary rather than the packaging of Topiary in OPAM.

**Comment by mseri** [comment]
It is green wherever it can be built. Thanks

**Comment by mseri** [comment]
We can add a rust-2024 next year when it is release

**Comment by Niols** [comment]
Cargo support in OPAM souds interesting! (Although only for a few select projects.) Definitely not in the scope of this PR though.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
