### PR TITLE
[coq] Update META and install targets.

### PR DESCRIPTION
**Pull request by ejgallego**
This is a backport of a 8.7.2 patch that fixes packages that build
against Coq using ocamlfind. We also try to detect Alpine Linux md5
correctly.

No code change in Coq itself.

### CODE REVIEW

**Comment by ejgallego** [comment]
IMHO it is worth backporting this change as it will make life of packages using ocamlfind's `coq.*` possible in OPAM. cc @Zimmi48 @RalfJung

**Comment by RalfJung** [comment]
Alternatively, this could directly update the `coq.8.7.1`. What is usually done in opam land?

**Comment by RalfJung** [comment]
Also, maybe this should wait until the [patch lands upstream](https://github.com/coq/coq/pull/6447).

**Comment by ejgallego** [comment]
@RalfJung we will commit upstream tonight so no worries about that part :)

**Comment by ejgallego** [comment]
While I am at it, I will also fix Alpine's build.

**Comment by ejgallego** [comment]
Well Alpine seems to be missing a working diff, I am puzzled testing such distro is mandatory in OPAM now.

**Comment by Zimmi48** [comment]
I don't get why you want to backport the patch on the configure that we are not even clear that we are going to accept, and is not that important. What is the limit between patches you think should be backported in the package and patches that shouldn't?

**Comment by Zimmi48** [comment]
Oh sorry, you already replied to this here: https://github.com/coq/coq/pull/6458#issuecomment-352299296

**Comment by ejgallego** [comment]
> I don't get why you want to backport the patch on the configure that we are not even clear that we are going to accept, and is not that important.

Well, the point is very clear, without that patch OPAM's CI fails. See:
https://github.com/ocaml/opam-repository/pull/11044

https://github.com/ocaml/opam-repository/pull/11044#issuecomment-352261188

> I'm going to go ahead and merge this but there are two problems that needs to be addressed sooner or later:
>
> - md5sum --version is not valid on Alpine Linux. This needs to be fixed upstream in the next version.

**Comment by RalfJung** [comment]
FTR. the alpine linux patch is upstream at https://github.com/coq/coq/pull/6458

**Comment by ejgallego** [comment]
On the other hand @Zimmi48 , the goals of package maintainers and upstream maintainers are rarely aligned; it is very often the case that packages ship with hacks and customizations that would never be included upstream.

For example, upstream could well reject the Alpine patch, but it would still make sense for the OPAM package to ship it.

**Comment by RalfJung** [comment]
> it is very often the case that packages ship with hacks and customizations that would never be included upstream.

It is also very often the case that upstream curses downstream for doing that, and rightly so. This frequently introduces problem because downstream has no idea what they are doing. (Well, that part is obviously different here where the downstream patches come from upstream developers, but the general point stands.) Let's not go there, please. Backporting patches already accepted or close to acceptance upstream so users don't have to wait until the next release is okay IMHO, but "hacks and customizations that would never be included upstream" are not.

**Comment by ejgallego** [comment]
IMHO this should be ready to merge.

**Comment by ejgallego** [comment]
ping. What more needs to be done here?

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
