### PR TITLE
added packages/parany/parany.2.0.0

### PR DESCRIPTION
**Pull request by UnixJunkie**
added a chunk size parameter plus ocamldoc.
Playing with ~csize allows to accelerate computations with a too fine granularity.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
The errors I see are related to ocamlnet failing to build.

**Comment by yallop** [comment]
There's an flambda/ocamlnet issue causing the build to fail, fixed in #10041.

**Comment by yallop** [comment]
@UnixJunkie, could you rebase against `master` to pick up the flambda fix?

**Comment by UnixJunkie** [comment]
done

**Comment by avsm** [comment]
I think this needs a clean rebase, as the diff currently has all kinds of other packages in it.

**Comment by UnixJunkie** [comment]
I sent https://github.com/ocaml/opam-repository/pull/10066.
Once it is accepted, this one also can be closed (and don't need to be accepted).

**Comment by UnixJunkie** [comment]
the other pull request is passing all CI tests, so I am already closing this one

**Pull request closed without merging**
