### PR TITLE
Add nbd.2.1.0

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by djs55** [comment]
A strange failure:
```
[WARNING] install and dev-repo are unknown fields in /home/travis/.opam/repo/default/packages/liquidsoap/liquidsoap.1.1.1/opam: is your OPAM up-to-date ?
[WARNING] install is an unknown field in /home/travis/.opam/repo/default/packages/ocurl/ocurl.0.7.2/opam: is your OPAM up-to-date ?
Creating a cache of metadata in ~/.opam/state.cache ...
[ERROR] global-config does not define the variable available.
'opam init . --comp=4.02.3' failed.
The command "bash -e .travis-ci.sh" exited with 66.
```

**Comment by dsheets** [comment]
@djs55, see #6520.

**Comment by dsheets** [comment]
The only error is 1.1.2 infrastructure breakage ignored by #6530. Merging.

**Pull request merged**
