### PR TITLE
rml: Fix dependencies

### PR DESCRIPTION
**Pull request by jpdeplaix**
Related to #11270 
cc @mandel 

I saw you were not using ```ocamlbuild``` as well. Could you consider removing the check for it in the ```configure``` file ?

### CODE REVIEW

**Comment by mandel** [comment]
Thanks @jpdeplaix. I will remove `ocamlbuild` in the next release of ReactiveML. 

For the opam-lint errors, Do you want me to add the missing following lines?
```
homepage: "http://reactiveml.org"
author: "Louis Mandel louis@reactiveml.org"
bug-reports: "bugs@reactiveml.org"
```

**Comment by jpdeplaix** [comment]
That's ok, just did it for you. Thanks !

**Comment by jpdeplaix** [comment]
A weird error is appearing with rml.1.08.04:
```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed base-num.base
∗  installed num.0
∗  installed ocamlbuild.0
[ERROR] The compilation of rml failed at "./configure --prefix
        /home/travis/.opam/3.12.1".
Processing  4/4: [rml: make uninstall]
#=== ERROR while installing rml.1.08.04 =======================================#
# opam-version 1.2.2
# os           linux
# command      ./configure --prefix /home/travis/.opam/3.12.1
# path         /home/travis/.opam/3.12.1/build/rml.1.08.04
# compiler     3.12.1
# exit-code    1
# env-file     /home/travis/.opam/3.12.1/build/rml.1.08.04/rml-15289-d2c37b.env
# stdout-file  /home/travis/.opam/3.12.1/build/rml.1.08.04/rml-15289-d2c37b.out
# stderr-file  /home/travis/.opam/3.12.1/build/rml.1.08.04/rml-15289-d2c37b.err
### stdout ###
# [...]
# unable to create ../compiler/parsing/parse_printer.ml.
# unable to create ../compiler/parsing/parser.mly.
# unable to create ../compiler/reac/reac_ast.ml.
# unable to create ../compiler/parsing/syntaxerr.ml.
# unable to create ../compiler/global/warnings.ml.
# unable to create ../tools/rmlbuild/rmlbuild/Makefile.
# unable to create ../tools/rmlbuild/rmlbuild/main.ml.
# unable to create ../tools/rmlbuild/rmlbuild/ocamlbuild_pack.mlpack.
# unable to create ../tools/rmlbuild/rmlbuild/ocamlbuild_plugin.ml.
# unable to create ../tools/rmlbuild/rmlbuild/start.sh.
### stderr ###
# [...]
# patch: **** Can't create file ../compiler/parsing/parser.mly : Invalid cross-device link
# patch: **** Can't create file ../compiler/reac/reac_ast.ml : Invalid cross-device link
# patch: **** Can't create file ../compiler/parsing/syntaxerr.ml : Invalid cross-device link
# patch: **** Can't create file ../compiler/global/warnings.ml : Invalid cross-device link
# patch: **** Can't create file ../tools/rmlbuild/rmlbuild/Makefile : Invalid cross-device link
# patch: **** Can't create file ../tools/rmlbuild/rmlbuild/main.ml : Invalid cross-device link
# patch: **** Can't create file ../tools/rmlbuild/rmlbuild/ocamlbuild_pack.mlpack : Invalid cross-device link
# patch: **** Can't create file ../tools/rmlbuild/rmlbuild/ocamlbuild_plugin.ml : Invalid cross-device link
# patch: **** Can't create file ../tools/rmlbuild/rmlbuild/start.sh : Invalid cross-device link
# configure: error: Install "patch" or send an email to louis.mandel@reactiveML.org
```
Is that a known bug ?
I will just go ahead and merge this as it is a really old version and looks broken anyway.

**Comment by mandel** [comment]
This is a strange bug coming from the call to the patch command. Thank you for merging.

**Pull request merged**
