### PR TITLE
Add: mtime.2.0.0

### PR DESCRIPTION
**Pull request by dbuenzli**
* Add: `mtime.2.0.0` [home](https://erratique.ch/software/mtime), [doc](https://erratique.ch/software/mtime/doc/), [issues](https://github.com/dbuenzli/mtime/issues)  
  *Monotonic wall-clock time for OCaml*

---

#### `mtime` v2.0.0 2022-12-02 Zagreb

* Use the new `js_of_ocaml` ocamlfind `META` standard to link JavaScript
  stubs ([#28](https://github.com/dbuenzli/mtime/issues/28)).
* `Mtime_clock` use `CLOCK_BOOTTIME` rather than `CLOCK_MONOTONIC`
  on Linux and `mach_continuous_time` rather than `mach_absolute_time`
  on macOS. This means that on these platforms sleep time is taken 
  into account ([#10](https://github.com/dbuenzli/mtime/issues/10)). Thanks to Bikal Lem for the patch.
* Add `Mtime.{to,of}_float_ns`.
* Remove deprecated values `Mtime.s_to_*` and `Mtime.Span.to_*` floating
  points functions. Note that the implementation of `Mtime.Span.to_*`
  functions was broken if your span exceeded `Int64.max_int`. Thanks
  to Thomas Leonard for the report ([#46](https://github.com/dbuenzli/mtime/issues/46)).
* Change implementation of `Mtime.Span.pp` and remove
  `Mtime.Span.pp_float_s`. The implementation no longer uses floating
  point arithmetic and always over approximates the result, no
  duration is printed shorter than it is. The output is no longer
  US-ASCII but UTF-8 encoded since U+03BC is used for µs.
* Stop installing the clock interface in `mtime.clock`, this package
  is now empty ([#42](https://github.com/dbuenzli/mtime/issues/42)).

---

Use `b0 -- .opam.publish mtime.2.0.0` to update the pull request.

### CODE REVIEW

**Comment by dbuenzli** [comment]
> * Remove deprecated values `Mtime.s_to_*` and `Mtime.Span.to_*` floating points functions

Ugh. Now I feel really bad of having broken all these packages.

**Comment by dbuenzli** [comment]
Not sure I understand the remaining failures.

**Comment by dbuenzli** [comment]
Is there anything I should do to get this merged ?

**Comment by avsm** [comment]
This looks good to me on first reading through the CI. Just need to check some of the lower bounds failures (which I believe aren't to do with this PR, but missing lower bounds on dune for some of those packages). This should be good to merge.

**Comment by kit-ty-kate** [comment]
Thanks! Sorry for the wait

**Pull request merged**
