### PR TITLE
Package horned_worm.0.3.7

### PR DESCRIPTION
**Pull request by kkazuo**
### `horned_worm.0.3.7`
An easy functional Web app micro framework
An easy functional Web app micro framework.
You can create REST API server with composable functions.

---
* Homepage: https://github.com/kkazuo/horned_worm
* Source repo: git+https://github.com/kkazuo/horned_worm.git
* Bug tracker: https://github.com/kkazuo/horned_worm/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by mseri** [comment]
@kkazuo sorry to bother, can you rebase the PR on the current master so that we have a full CI run?

**Comment by mseri** [comment]
This way we can test the old compilers

**Comment by kkazuo** [comment]
Thank you @mseri . 
I renewed this PR and now CI had pass.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
