### PR TITLE
[new release] pp (2.0.0)

### PR DESCRIPTION
**Pull request by mbarbin**
Pretty-printing library

- Project page: <a href="https://github.com/ocaml-dune/pp">https://github.com/ocaml-dune/pp</a>
- Documentation: <a href="https://ocaml-dune.github.io/pp/">https://ocaml-dune.github.io/pp/</a>

##### CHANGES:

- Prepare release (ocaml-dune/pp#21, @mbarbin)
  - Upgrade to `ocamlformat.0.26.2`.
  - Fmt the code
  - Add CI badge to README
  - Upgrade GitHub workflow actions dependencies (checkout@v4, setup-ocaml@v3)
  - Add more validation steps in CI
  - Add `ocamlformat` as dev-setup dependency

- Add `Pp.verbatimf`. (ocaml-dune/pp#18, @mbarbin)

- Add `Pp.paragraph` and `Pp.paragraphf` (ocaml-dune/pp#19, @Alizter)

- Remove `of_fmt` constructor. (ocaml-dune/pp#17, @Alizter)

### CODE REVIEW

**Comment by mbarbin** [comment]
I just had a first look at the CI results. This release contains https://github.com/ocaml-dune/pp/pull/17 which has a breaking change to the public APi of pp. In particular `Pp.to_ast` no longer returns a result type. This is causing a good number of the build issues I see in the CI.

I think the normal way of fixing this is to introduce a new version constraints to these packages (& < 2.0.0 ). Is that right?

**Comment by mbarbin** [comment]
cc @rgrinberg

**Comment by mseri** [comment]
Thanks.

@mbarbin would it be possible to move [745b16a](https://github.com/ocaml/opam-repository/pull/26570/commits/745b16a7d006e1e5698a2bb813725c03c246bcc7) to a separate PR? This way I can directly merge and we can re-run the tests here. Otherwise the revdeps will hit heavily the CI

**Comment by mseri** [comment]
pp revdeps are all green, the builds are green. I am merging to avoid testing all revdeps of dune multiple times

**Comment by mbarbin** [comment]
Thank you!

**Pull request merged**
