### PR TITLE
auto-fix opam-lint warnings

### PR DESCRIPTION
**Pull request by lefessan**
`opam lint` displays a lot of warnings on old packages, and these warnings come back everytime a package metadata is modified (usually to modify compatibility ranges). This PR fixes many warnings by:
1) fixing `dev-repo` fields to use git+https://github.com instead of just https://github.com (warning 42)
2) propagating `maintainer`, `dev-repo`, `authors`, `homepage` and `bug-reports` between versions of the same package (warnings 23, 25, 35, 36 and 37)

It is done automatically.

As a comparison, here is the state before the PR:
http://opam.ocamlpro.com/builder/c7ac1fc-lint.html
and here is the state after the PR:
http://opam.ocamlpro.com/builder/c7ac1fc-autofix-lint.html

The PR is not intented to be merge immediatly, but instead, to start a discussion on the usefulness of such tooling (i.e. no need to develop such tools if nobody cares about old metadata triggering warnings...).

### CODE REVIEW

**Comment by samoht** [comment]
That looks pretty useful!

**Comment by dsheets** [comment]
This would be really useful. Some of the changes like `https://....git` -> `git+https://` may not be compatible with older opam versions, I seem to recall. It would probably be best to split the changeset into warning classes that are fixed and potentially then by project.

**Comment by lefessan** [comment]
If git+https is only available from some version, it is possible to check the OPAM file version and only do it from that version...or convert to a git:// url...

**Comment by djs55** [comment]
This looks very useful to me too. I've been updating some of my old packages manually and I've also noticed that:
- I quite often have a `build` step which is `make install` which I need to move to be an `install` step
- I have `ocaml-version:` rather than `available: [ocaml-version`

**Comment by UnixJunkie** [comment]
I feel anything that improves the quality of existing packages is useful.
I looked at several packages recently and there are ugly stuffs: packages with an install target but no uninstall target for example. Which means their installation is not reversible by a simple 'opam remove pkg'.

**Comment by samoht** [comment]
@lefessan would it be possible to re-submit this patch in chunks (it'll be easier to review)? e.g. a commit to fix all warning 42, a commit to fix all warning 23, etc..

**Comment by avsm** [comment]
Closing this one for now as it needs a rebase to apply.

**Pull request closed without merging**
