### PR TITLE
added unmagic.1.0.1

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
omake.0.10.1 and my macros cannot live together:

```
Warning 46: illegal environment variable OCAMLPARAM : missing '=' in 
# File "_none_", line 1:
# Warning 46: illegal environment variable OCAMLPARAM : missing '=' in 
# File "_none_", line 1:
# Error: Files unmagic.cmo and /home/opam/.opam/4.03.0/lib/spotlib/spotlib.cmo
#        make inconsistent assumptions over interface Spotlib
```

**Comment by camlspotter** [comment]
```
ocaml 4.03.0
  - install omake            0.10.1         
  - install spotlib          2.1.2 
```

Ah, this is very old spotlib w/o the OMyMakefile fix for omake.0.10.1.  No wonder it fails.

Tested locally:

```
$ opam install spotlib.2.1.2
$ cd $HOME/.opam/4.04.0-test/build/spotlib.2.1.2
$ ocamlobjinfo lib/*.cm* | grep 'Spotlib$'
Unit name: Spotlib
	1626f04f5082bbd56a6af955e547eae0	Spotlib
Unit name: Spotlib
	1626f04f5082bbd56a6af955e547eae0	Spotlib
Unit name: Spotlib
	1626f04f5082bbd56a6af955e547eae0	Spotlib
Unit name: Spotlib
	6b5939e9945064d0edd6350199658012	Spotlib
	1626f04f5082bbd56a6af955e547eae0	Spotlib
Cmt unit name: Spotlib
	1626f04f5082bbd56a6af955e547eae0	Spotlib
Name: Spotlib
	Spotlib
	6b5939e9945064d0edd6350199658012	Spotlib
Name: Spotlib
	Spotlib
	6b5939e9945064d0edd6350199658012	Spotlib
BFD library unavailable, cannot print info on .cmxs files
```

I must understand what is happening here.

**Comment by camlspotter** [comment]
It is a known issue of `omake.0.10.1`: https://github.com/ocaml-omake/omake/issues/73

**Comment by camlspotter** [comment]
I could simulate the inconsistency interfaces by running the two packaging commands (by ocamlc and by ocamlopt) in parallel:

```
cd lib

ocamlfind ocamlc -package unix,str -g -annot -w Ae -g -pack -annot -bin-annot -o spotlib.cmo monad_intf.cmo xlist.cmo monad.cmo option.cmo result.cmo base.cmo mtypes.cmo xlazy.cmo stream.cmo xhashtbl.cmo xset.cmo xstring.cmo xformat.cmo xfilename.cmo xunix.cmo xprintf.cmo file.cmo xsys.cmo xint64.cmo xprintexc.cmo phantom.cmo weaktbl.cmo hashset.cmo comopt.cmo overload.cmo at.cmo dllist.cmo spot.cmo &
ocamlfind ocamlopt -package unix,str -g -annot -w Ae -pack -annot -bin-annot -o spotlib.cmx monad_intf.cmx xlist.cmx monad.cmx option.cmx result.cmx base.cmx mtypes.cmx xlazy.cmx stream.cmx xhashtbl.cmx xset.cmx xstring.cmx xformat.cmx xfilename.cmx xunix.cmx xprintf.cmx file.cmx xsys.cmx xint64.cmx xprintexc.cmx phantom.cmx weaktbl.cmx hashset.cmx comopt.cmx overload.cmx at.cmx dllist.cmx spot.cmx &

sleep 1

ocamlobjinfo spotlib.cmo | grep 'Spotlib$'
ocamlobjinfo spotlib.cmx | grep 'Spotlib$'
```

I guess `omake.0.10.1` runs commands in parallel by default unlike `omake.0.9.x` I guess. The possible fixes are:

* run `omake` with `-j1`
* make the packaging commands run in sequence w/o parallelization

**Comment by camlspotter** [comment]
Should wait the fixes for spotlib.

**Comment by rgrinberg** [comment]
I agree with @camlspotter that changing the constraints is the least invasive for now but for future reasons, users of OCamlPackage should probably set `-j1` explicitly. The builds really rely on being sequentially so it should be specified.

**Comment by camlspotter** [comment]
Checksum failure of dependent libraries which are fixed at the same time in parallel.  Need to wait.

**Pull request merged**
