### PR TITLE
Package opam-publish.2.0.0

### PR DESCRIPTION
**Pull request by rjbou**
### `opam-publish.2.0.0`

---
* Homepage: https://github.com/ocaml/opam-publish
* Source repo: git+https://github.com/ocaml/opam-publish.git
* Bug tracker: https://github.com/ocaml/opam-publish/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by rjbou** [comment]
opam-publish 2.0.0 set master as default,  **do not merge** before opam repo switch default.

**Comment by rjbou** [comment]
switch done, merging

**Comment by hannesm** [comment]
both travis and opam-CI result in solver timeouts -- something worth looking into?
```
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
[ERROR] Sorry, resolution of the request timed out.
        Try to specify a simpler request, use a different solver, or increase the allowed time by setting OPAMSOLVERTIMEOUT to a bigger value (currently, it is set to 60.0 seconds).
Command failed: opam list --readonly --external  --resolve=opam-publish.2.0.0 returned 60
```

**Comment by rjbou** [comment]
Locally, constraining opam-* deps to 2.0.0 unblocks it.

**Comment by hannesm** [comment]
@rjbou thanks!  the travis CI on macOS hits https://github.com/ocaml/opam/pull/3543
```
<><>Gathering sources><><><><><><><><><><><><><><><><><><><><><><><><><><>🐫
[ERROR] The sources of the following couldn't be obtained, aborting:
          - opam-publish.2.0.0:
            Failure("openssl error")
```

**Comment by hannesm** [comment]
I can see multiple paths forward: instead of including a sha512 checksum, use sha256 instead (that should be supported by macOS openssl), or ignore the macOS error for now and wait for an opam release that fixes the issue.  what do you prefer?

**Comment by rjbou** [comment]
I'll let opam repo maintainers have the final word on that. It's ok for me to change this opam publish release until the fix is released, it is the solution that is the less ci breaker.
ftm, we plan to release an opam 2.0.1 very shortly, in few weeks, with this (and other) fixes.

**Comment by kit-ty-kate** [comment]
mmh let's merge this now and fix MacOS in a future PR

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
