### PR TITLE
mirage-block-solo5 < 0.7.0: restrict to cstruct < 6.1.0

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
looks fine to be merged - the #21103 introduced 4.14 support for this package. the errors are mainly that older solo5 releases do not support gcc >= 10.

**Comment by hannesm** [comment]
The issue observed in https://github.com/ocaml/opam-repository/pull/21103
```
#=== ERROR while compiling mirage-block-solo5.0.6.1 ===========================#
# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.14.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/mirage-block-solo5.0.6.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p mirage-block-solo5 -j 31
# exit-code            1
# env-file             ~/.opam/log/mirage-block-solo5-10617-c1401a.env
# output-file          ~/.opam/log/mirage-block-solo5-10617-c1401a.out
### output ###
# (cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.block.objs/byte -I /home/opam/.opam/4.14/lib/bheap -I /home/opam/.opam/4.14/lib/cmdliner -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/duration -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/functoria-runtime -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/metrics -I /home/opam/.opam/4.14/lib/mirage-block -I /home/opam/.opam/4.14/lib/mirage-runtime -I /home/opam/.opam/4.14/lib/mirage-solo5 -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/stdlib-shims -intf-suffix .ml -no-alias-deps -o src/.block.objs/byte/block.cmo -c -impl src/block.ml)
# File "src/block.ml", line 82, characters 21-29:
# 82 |       Lwt.fail_with (Fmt.strf "Block: connect(%s): Invalid argument" name)
#                           ^^^^^^^^
# Alert deprecated: Fmt.strf
# use Fmt.str instead.
# File "src/block.ml", line 84, characters 21-29:
# 84 |       Lwt.fail_with (Fmt.strf "Block: connect(%s): Unspecified error" name)
#                           ^^^^^^^^
# Alert deprecated: Fmt.strf
# use Fmt.str instead.
# File "src/block.ml", line 104, characters 49-60:
# 104 |      let new_offset = Int64.(add offset (of_int (Cstruct.len b))) in
#                                                        ^^^^^^^^^^^
# Error: Unbound value Cstruct.len
# Hint: Did you mean lenv?
# (cd _build/default && /home/opam/.opam/4.14/bin/ocamlopt.opt -w -40 -g -I src/.block.objs/byte -I src/.block.objs/native -I /home/opam/.opam/4.14/lib/bheap -I /home/opam/.opam/4.14/lib/cmdliner -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/duration -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/functoria-runtime -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/metrics -I /home/opam/.opam/4.14/lib/mirage-block -I /home/opam/.opam/4.14/lib/mirage-runtime -I /home/opam/.opam/4.14/lib/mirage-solo5 -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/stdlib-shims -intf-suffix .ml -no-alias-deps -o src/.block.objs/native/block.cmx -c -impl src/block.ml)
# File "src/block.ml", line 82, characters 21-29:
# 82 |       Lwt.fail_with (Fmt.strf "Block: connect(%s): Invalid argument" name)
#                           ^^^^^^^^
# Alert deprecated: Fmt.strf
# use Fmt.str instead.
# File "src/block.ml", line 84, characters 21-29:
# 84 |       Lwt.fail_with (Fmt.strf "Block: connect(%s): Unspecified error" name)
#                           ^^^^^^^^
# Alert deprecated: Fmt.strf
# use Fmt.str instead.
# File "src/block.ml", line 104, characters 49-60:
# 104 |      let new_offset = Int64.(add offset (of_int (Cstruct.len b))) in
#                                                        ^^^^^^^^^^^
# Error: Unbound value Cstruct.len
# Hint: Did you mean lenv?
```

**Comment by hannesm** [comment]
this looks good to be merged!

**Comment by samoht** [comment]
Something needs to be constrained in `mirage-block-lwt` too:

```
#=== ERROR while compiling mirage-block-lwt.1.0.0 =============================#
# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.02.3 | file:///home/opam/opam-repository
# path                 ~/.opam/4.02/.opam-switch/build/mirage-block-lwt.1.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build -n mirage-block-lwt --pinned false
# exit-code            1
# env-file             ~/.opam/log/mirage-block-lwt-23-635ce5.env
# output-file          ~/.opam/log/mirage-block-lwt-23-635ce5.out
### output ###
# ocamlfind ocamldep -package 'mirage-block lwt cstruct io-page logs result' -package bytes -modules lwt/mirage_block_lwt.ml > lwt/mirage_block_lwt.ml.depends
# ocamlfind ocamldep -package 'mirage-block lwt cstruct io-page logs result' -package bytes -modules lwt/mirage_block_lwt.mli > lwt/mirage_block_lwt.mli.depends
# ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_lwt.cmi lwt/mirage_block_lwt.mli
# + ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_lwt.cmi lwt/mirage_block_lwt.mli
# File "lwt/mirage_block_lwt.mli", line 175, characters 17-36:
# Warning 34: unused type error#row.
# File "lwt/mirage_block_lwt.mli", line 176, characters 17-48:
# Warning 34: unused type write_error#row.
# ocamlfind ocamldep -package 'mirage-block lwt cstruct io-page logs result' -package bytes -modules lwt/mirage_block_compare.ml > lwt/mirage_block_compare.ml.depends
# ocamlfind ocamldep -package 'mirage-block lwt cstruct io-page logs result' -package bytes -modules lwt/mirage_block_lwt_s.ml > lwt/mirage_block_lwt_s.ml.depends
# ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_lwt_s.cmo lwt/mirage_block_lwt_s.ml
# ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_compare.cmo lwt/mirage_block_compare.ml
# ocamlfind ocamlopt -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_lwt_s.cmx lwt/mirage_block_lwt_s.ml
# ocamlfind ocamldep -package 'mirage-block lwt cstruct io-page logs result' -package bytes -modules lwt/mirage_block_copy.ml > lwt/mirage_block_copy.ml.depends
# ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_copy.cmo lwt/mirage_block_copy.ml
# ocamlfind ocamldep -package 'mirage-block lwt cstruct io-page logs result' -package bytes -modules lwt/mirage_block_iter.ml > lwt/mirage_block_iter.ml.depends
# ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_iter.cmo lwt/mirage_block_iter.ml
# ocamlfind ocamldep -package 'mirage-block lwt cstruct io-page logs result' -package bytes -modules lwt/mirage_block_mem.ml > lwt/mirage_block_mem.ml.depends
# ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_mem.cmo lwt/mirage_block_mem.ml
# ocamlfind ocamldep -package 'mirage-block lwt cstruct io-page logs result' -package bytes -modules lwt/mirage_block_patterns.ml > lwt/mirage_block_patterns.ml.depends
# ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_patterns.cmo lwt/mirage_block_patterns.ml
# ocamlfind ocamldep -package 'mirage-block lwt cstruct io-page logs result' -package bytes -modules lwt/mirage_block_safe.ml > lwt/mirage_block_safe.ml.depends
# ocamlfind ocamldep -package 'mirage-block lwt cstruct io-page logs result' -package bytes -modules lwt/mirage_block_log.ml > lwt/mirage_block_log.ml.depends
# ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_log.cmo lwt/mirage_block_log.ml
# ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_safe.cmo lwt/mirage_block_safe.ml
# + ocamlfind ocamlc -c -bin-annot -safe-string -package 'mirage-block lwt cstruct io-page logs result' -warn-error +1..49-34 -w A-4-41-44 -package bytes -I lwt -o lwt/mirage_block_safe.cmo lwt/mirage_block_safe.ml
# File "lwt/mirage_block_safe.ml", line 69, characters 10-29:
# Error: This expression should not be a function, the expected type is
# ('a, Format.formatter, unit) format
```

**Comment by hannesm** [comment]
That's true @samoht, but unrelated to this PR.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
