### PR TITLE
UPDATE hll 3.16 and pds 5.38

### PR DESCRIPTION
**Pull request by orbitz**

### CODE REVIEW

**Comment by orbitz** [comment]
Looks like the OS X build is failing, but I can't tell if it's related to my packages.  Could I get some guidance?

**Comment by mseri** [comment]
No, that is an issue with homebrew and the macos Travis image. I am waiting for the big CI run, testing also the old compilers

**Comment by orbitz** [comment]
@mseri thanks!

**Comment by kit-ty-kate** [comment]
`pds` was not compatible with OCaml 4.02 so I restricted it:
```
- make[1]: Leaving directory '/home/opam/.opam/4.02/.opam-switch/build/pds.5.38/build/release/pds_template'
- File "../../../src/snabela/snabela_lexer.ml", line 148, characters 4-6:
- Error: Unbound constructor Ok
- make[1]: *** [../../../Ocamlrules.mk.in:113: snabela_lexer.cmx] Error 2
- make[1]: Leaving directory '/home/opam/.opam/4.02/.opam-switch/build/pds.5.38/build/release/snabela'
- make: *** [pds.mk:79: release_snabela] Error 2
```
I also removed the `remove` fields since those are not necessary with opam 2.0.
Could these two changes be returned upstream? (I also reformatted the files to be more standard with the rest of the opam file but that's optional for you)

Thanks!

**Pull request merged**
