### PR TITLE
duppy.0.7.4

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by toots** [comment]
Question: What is the proper way to push this to legacy `1.2` opam users? This release has an important bugfix..

**Comment by kit-ty-kate** [comment]
mmh not sure why `camlp4` fails here. cc @dra27 ?

**Comment by toots** [comment]
Ok. I was planning on removing the `camlp4` part, I'll do another release without it soon.

**Comment by dra27** [comment]
Something looks wrong with the builds for the specific compiler versions (especially given that macOS is passing). The local test would be expected to fail - that needs updating to build a "system" camlp4.

**Comment by toots** [comment]
Closing, see #12977

**Pull request closed without merging**
