### PR TITLE
fixed ocamltter.4.0.2

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
ppx_tiny_json_conv　is not found...

**Comment by camlspotter** [comment]
This time, locally checked!

**Comment by lefessan** [comment]
Log of failure: 
```#    This expression should use a => binding.
# ocamlfind: Package `ppx_tiny_json_conv' not found
# *** omake: targets were not rebuilt because of errors:
```
Maybe a missing dependency ?

**Comment by camlspotter** [comment]
Thanks, this time, I have checked things locally, but forgot to update local repo :-(

**Comment by camlspotter** [comment]
ppx_monadic...   Now I am in the OPAM hell.

**Pull request merged**
