### PR TITLE
plist.1.0.0 - via opam-publish

### PR DESCRIPTION
**Pull request by fxfactorial**
Native OCaml Plist manipulation

Plist

---
* Homepage: https://github.com/fxfactorial/ocaml-plist
* Source repo: https://github.com/fxfactorial/ocaml-plist.git
* Bug tracker: https://github.com/fxfactorial/ocaml-plist/issues

---

Pull-request generated by opam-publish v0.3.3

### CODE REVIEW

**Comment by fxfactorial** [comment]
Okay this is a bit odd. I need the unix package just for build, some stuff in `setup.ml` but adding `"unix"{build}` to depends doesn't work since `unix` is not an opam package.

**Comment by dbuenzli** [comment]
> "unix"{build} to depends doesn't work since unix is not an opam package.

Did you try with `base-unix` ?

**Comment by fxfactorial** [comment]
@dbuenzli Oh right, forgot it was prefixed with base. Anyway I am redoing it using oasis's own I/O wrappers, changing some hashes now for this PR.

**Comment by Chris00** [comment]
@fxfactorial Tip: for the `depexts` section, you can use an `_opam` file that will be automatically concatenated with the generated `opam`.

**Comment by Chris00** [comment]
@fxfactorial For the `base-unix` dependency to be generated, you need to add a `unix` dep. in `_oasis`.  Alternatively, add a `depends` section to `_opam`.

**Comment by fxfactorial** [comment]
@Chris00 thanks! What does the concatenation of the files? I only needed the `unix` dependency at build time, not for my actual lib.

**Comment by Chris00** [comment]
@fxfactorial I added an explanation at the end of the [Convention section](https://github.com/ocaml/oasis2opam#conventions).  Let me know if it is not clear enough.

**Pull request merged**
