### PR TITLE
[new release] containers (2 packages) (3.15)

### PR DESCRIPTION
**Pull request by c-cube**
A modular, clean and powerful extension of the OCaml standard library

- Project page: <a href="https://github.com/c-cube/ocaml-containers/">https://github.com/c-cube/ocaml-containers/</a>

### CODE REVIEW

**Comment by mseri** [comment]
Tests with ocaml 4.10 -- 4.12 are failing with
```
# File "tests/core/reg/t_reg454.expected", line 1, characters 0-0:
# /usr/bin/git --no-pager diff --no-index --color=always -u _build/default/tests/core/reg/t_reg454.expected _build/default/tests/core/reg/t_reg454.output
# diff --git a/_build/default/tests/core/reg/t_reg454.expected b/_build/default/tests/core/reg/t_reg454.output
# index ae66ec1..0ccaa88 100644
# --- a/_build/default/tests/core/reg/t_reg454.expected
# +++ b/_build/default/tests/core/reg/t_reg454.output
# @@ -1,2 +1,2 @@
#  123456
# -123456
# +1024
```
is that somethign to worry about?

**Comment by c-cube** [comment]
Indeed, my CI wasn't run in release profile so the bug wasn't fixed on 4.10..4.12. This should be better :crossed_fingers:

**Comment by c-cube** [comment]
fat finger, sorry :sweat_smile:

**Comment by mseri** [comment]
Thanks

**Comment by c-cube** [comment]
Thank you!

**Pull request merged**
