### PR TITLE
Add merlin-of-pds 1.1

### PR DESCRIPTION
**Pull request by orbitz**
A small program for turning `pds.conf` files into `.merlin` files.

### CODE REVIEW

**Comment by orbitz** [comment]
How do I tell what failed?

**Comment by samoht** [comment]
Check in the logs of one of the Travis run (when it is available). The solver should print a scary error message.

**Comment by orbitz** [comment]
The travis job has all green checkboxes next to it.  I'm not really sure how to debug this?

**Comment by samoht** [comment]
If you look at the logs of one the green run, you can see:

```
build one: merlin-of-pds.1.1
Checking for availability...
The following dependencies couldn't be met:
  - merlin-of-pds -> pds >= 5
Your request can't be satisfied:
  - No package matches pds>=5.
```

Which looks like expected as the most recent version of `pds` that I see in my opam universe is `4.13`. Did you forget to push a more recent version?

**Comment by samoht** [comment]
Ha actually it was merged in https://github.com/ocaml/opam-repository/pull/8084, so I have restarted the Travis builds.

**Comment by orbitz** [comment]
@samoht Hahah, so dumb of me.  I had that PR open and didn't even think of it.  I'm not on the ball these days.

@avsm Hrm, I'm not sure what to do about that.  The repo is public, I'm guessing you just don't have a bitbucket account?  Does `git clone https://bitbucket.org/acslab/merlin-of-pds.git` work for you?

**Comment by samoht** [comment]
> Does git clone https://bitbucket.org/acslab/merlin-of-pds.git work for you?

Yes it does for me. Could you update the `dev-repo` field? Thanks!

**Comment by orbitz** [comment]
Updated!  Looks like it's still failing on something, though.

**Comment by samoht** [comment]
You may need to rebase to make @camelus happy, but don't worry too much about it as I'm happy to merge the PR as it is.

**Comment by orbitz** [comment]
Thanks @samoht !

**Pull request merged**
