### PR TITLE
[jingoo] release version 1.3.0

### PR DESCRIPTION
**Pull request by tategakibunko**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I've tried rerunning the Camelus check manually but it gave me the same answer.. Does anybody know why it does that? @AltGr @rjbou ? It installs successfully on mirage-ci and Travis and I'm not sure why would Camelus says otherwise

**Comment by mseri** [comment]
No idea. Seems to install fine on my computer as well

**Comment by AltGr** [comment]
The PR should be rebased: I am guessing the repository revision it was made from doesn't contain all the dependencies of the package. Since Travis tests from a virtual merge with the current master, it gets them and runs OK, but Camelus really tests the submitted repository, not a merge.

One reason to do this is that the linting results remain stable against changes or merges to master while the PR is open.

**Comment by tategakibunko** [comment]
Thank you for your help!

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
