### PR TITLE
graphql 0.6.0, graphql-lwt 0.6.0 and ppx_graphql 0.2.0

### PR DESCRIPTION
**Pull request by andreas**

### CODE REVIEW

**Comment by andreas** [comment]
Initially this PR only included `graphql.0.6.0` and `graphql-lwt.0.6.0`. However, the revdeps job uncovered a dependency issue with `ppx_graphql 0.1.0` (it was missing `ppx_metaquot` as an opam dependency). As such, I included a new version of `ppx_graphql` (`0.2.0`), and fixed up the previous version (`0.1.0`).

Alpine still fails with an error regarding `m4`, but that seems unrelated to this PR.

**Comment by hannesm** [comment]
@andreas Travis CI (at e.g. https://travis-ci.org/ocaml/opam-repository/jobs/361771688) indicates that ppx_graphql 0.1.0 relies on an earlier alcotest release (`<0.8.0`, `0.8.0` is when alcotest's `float` combinator started requiring an `epsilon` parameter).  could you add that constraint in this PR?

**Comment by andreas** [comment]
@hannesm, ah thanks! Added that constraint now.

**Comment by hannesm** [comment]
I PRed some more constraints for angstrom in #11720, this is good to go.  thanks!

**Comment by andreas** [comment]
Thanks for the help, @hannesm!

**Pull request merged**
