### PR TITLE
Package ocaml-iri.0.5.0

### PR DESCRIPTION
**Pull request by zoggy**
### `ocaml-iri.0.5.0`
Implementation of Internationalized Resource Identifiers (IRIs)

---
* Homepage: https://framagit.org/zoggy/ocaml-iri
* Source repo: git+https://framagit.org/zoggy/ocaml-iri.git
* Bug tracker: https://framagit.org/zoggy/ocaml-iri/-/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Your package fails to build with the following error:
```
#=== ERROR while compiling ocaml-iri.0.5.0 ====================================#
# context              2.0.8 | linux/x86_64 | ocaml-base-compiler.4.12.0 | pinned
# path                 ~/.opam/4.12/.opam-switch/build/ocaml-iri.0.5.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build make all
# exit-code            2
# env-file             ~/.opam/log/ocaml-iri-15-56405a.env
# output-file          ~/.opam/log/ocaml-iri-15-56405a.out
### output ###
# make: *** No rule to make target 'all'.  Stop.
```

**Comment by zoggy** [comment]
I don't understand what's wrong.

**Comment by kit-ty-kate** [comment]
Oh, your opam file does not specify any archive somehow. Could specify the way you used opam-publish here https://github.com/ocaml-opam/opam-publish/issues/124 and add the required `url` section?

**Comment by zoggy** [comment]
Sure, but sorry, opam-published created a new pull request: https://github.com/ocaml/opam-repository/pull/18624/commits/8a794ecc19b11fde675fce5ddc53cf818ba5021c

**Comment by kit-ty-kate** [comment]
That's ok. I could reproduce your use-case and wrote a comment on the issue above. I'll close this one in favour of https://github.com/ocaml/opam-repository/pull/18624

**Pull request closed without merging**
