### PR TITLE
biniou 1.0.10

### PR DESCRIPTION
**Pull request by mjambon**

### CODE REVIEW

**Comment by samoht** [comment]
```
#=== ERROR while installing biniou.1.0.10 =====================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/system/build/biniou.1.0.10
# compiler     system (4.02.3)
# exit-code    2
# env-file     /home/travis/.opam/system/build/biniou.1.0.10/biniou-8647-0c525f.env
# stdout-file  /home/travis/.opam/system/build/biniou.1.0.10/biniou-8647-0c525f.out
# stderr-file  /home/travis/.opam/system/build/biniou.1.0.10/biniou-8647-0c525f.err
### stdout ###
# ocamlfind ocamlc -a -g -annot -bin-annot -o biniou.cma \
# 		-package "easy-format" bi_util.mli bi_util.ml bi_share.mli bi_share.ml bi_outbuf.mli bi_outbuf.ml bi_inbuf.mli bi_inbuf.ml bi_vint.mli bi_vint.ml bi_io.mli bi_io.ml bi_dump.ml bi_stream.mli bi_stream.ml
# ocamlfind ocamlc -o bdump.byte -g -annot -bin-annot \
# 		-package easy-format -linkpkg biniou.cma bdump.ml
# mkdir -p doc
# ocamlfind ocamldoc -d doc -html -package easy-format bi_util.mli bi_share.mli bi_outbuf.mli bi_inbuf.mli bi_vint.mli bi_io.mli bi_stream.mli
# sed -e 's:@@VERSION@@:1.0.10:' META.in > META
### stderr ###
# [...]
# Warning 3: deprecated: String.unsafe_set
# File "bi_io.ml", line 562, characters 12-25:
# Warning 3: deprecated: String.create
# Use Bytes.create instead.
# File "bi_stream.ml", line 56, characters 16-29:
# Warning 3: deprecated: String.create
# Use Bytes.create instead.
# make: Circular bdump.ml <- bdump.ml dependency dropped.
# make: Circular META.in <- META.in dependency dropped.
# make: *** No rule to make target `test_biniou', needed by `default'.  Stop.
```

**Comment by samoht** [comment]
@mjambon ping?

**Comment by whitequark** [comment]
@mjambon 
```
Some files in ~/.opam/system/install/biniou.install couldn't be installed:
  - /Users/travis/.opam/system/build/biniou.1.0.11/bdump to /Users/travis/.opam/system/bin
```

**Comment by mjambon** [comment]
Dropping this pull request. There's a new pull request with fixes for biniou 1.0.12. Sorry for the mess. https://github.com/ocaml/opam-repository/pull/6924

**Pull request closed without merging**
