### PR TITLE
Liquidsoap 1.3.0

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by yallop** [comment]
The [Travis 4.05.0 build](https://travis-ci.org/ocaml/opam-repository/jobs/226387120) is failing:

```
# Error: Signature mismatch:
# [...]
#            Unix.file_descr -> Unix.file_descr * Unix.sockaddr
#        is not included in
#          val accept : Unix.file_descr -> socket * Unix.sockaddr
#        File "harbor/harbor.ml", line 37, characters 4-60:
#          Expected declaration
#        File "harbor/harbor.ml", line 72, characters 8-14: Actual declaration
```

**Comment by toots** [comment]
@yallop: should be fixed now.

**Comment by yallop** [comment]
Yes, everything's passing except for the openSUSE build (regarding which see https://github.com/ocaml/opam-depext/pull/62).

**Comment by toots** [comment]
Thanks!

**Pull request merged**
