### PR TITLE
[new release] decompress and rfc1951 (0.8.1)

### PR DESCRIPTION
**Pull request by dinosaure**
CHANGES:

* _Dunify_ project (@dinosaure)
* *breaking-change* Unbox `Bytes.t` and `Bigstring.t` as I/O buffer (@dinosaure)
* Add foreign tests vectors (@cfcs, @dinosaure)
* Catch invalid distance (@XVilka, @dinosaure)
* Better check on dictionaries (@XVilka, @dinosaure)
* *breaking-change* Add [wbits] argument to check Window size on RFC1951 (@XVilka, @dinosaure)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Compilation and tests fail
```
#=== ERROR while compiling decompress.0.8.1 ===================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.0 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/4.07.0/.opam-switch/build/decompress.0.8.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune runtest --only-packages decompress --root . -j 1
# exit-code   1
# env-file    ~/.opam/log/decompress-16859-edbed0.env
# output-file ~/.opam/log/decompress-16859-edbed0.out
### output ###
#       ocamlc lib/.decompress_impl.objs/decompress_impl__Decompress_q.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/travis/.opam/4.07.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w +1..49 -w -4-41-44 -g -bin-annot -I lib/.decompress_impl.objs -I lib/.decompress_impl.objs/.private -I /home/travis/.opam/4.07.0/lib/checkseum -I /home/travis/.opam/4.07.0/lib/optint -no-alias-deps -opaque -open Decompress_impl__ -[...]
# File "lib/decompress_q.ml", line 1:
# Error: The files lib/.decompress_impl.objs/decompress_impl__Decompress_q.cmi
#        and lib/.decompress_impl.objs/decompress_impl.cmi
#        make inconsistent assumptions
#        over interface Decompress_impl__Decompress_q
```
```
#=== ERROR while compiling rfc1951.0.8.1 ======================================#
# context     2.0.0 | linux/x86_64 | ocaml-system.4.06.1 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-system/.opam-switch/build/rfc1951.0.8.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune runtest --only-packages rfc1951 --root . -j 1
# exit-code   1
# env-file    ~/.opam/log/rfc1951-21474-dd0857.env
# output-file ~/.opam/log/rfc1951-21474-dd0857.out
### output ###
# File "test/dune", line 9, characters 24-31:
# 9 |  (libraries checkseum.c rfc1951 alcotest))
#                             ^^^^^^^
# Error: Library "rfc1951" not found.
# Hint: try: dune external-lib-deps --missing --root . --only-packages rfc1951 @runtest
# File "test/dune", line 4, characters 24-34:
# 4 |  (libraries checkseum.c decompress re.str camlzip alcotest))
#                             ^^^^^^^^^^
# Error: Library "decompress" not found.
# Hint: try: dune external-lib-deps --missing --root . --only-packages rfc1951 @runtest
```
Also could you improve the runtest command by just `"dune" "runtest" "-p" name "-j" jobs`?

**Comment by cfcs** [comment]
Can we pull in the description you pushed for `0.7` https://github.com/ocaml/opam-repository/pull/12807/commits/b90b715ebb02e4fc01aae4cfee0285eda5d940da ?

**Comment by kit-ty-kate** [comment]
The tests fail
```
#=== ERROR while compiling rfc1951.0.8.1 ======================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.0 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/4.07.0/.opam-switch/build/rfc1951.0.8.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p rfc1951 -j 1
# exit-code   1
# env-file    ~/.opam/log/rfc1951-23788-9f1a9b.env
# output-file ~/.opam/log/rfc1951-23788-9f1a9b.out
### output ###
# File "test/dune", line 11, characters 24-42:
# 11 |  (libraries checkseum.c decompress.rfc1951 alcotest))
#                              ^^^^^^^^^^^^^^^^^^
# Error: Library "decompress.rfc1951" not found.
# Hint: try: dune external-lib-deps --missing -p rfc1951 @runtest
```

**Comment by dinosaure** [comment]
Oh god, it's done!

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
