### PR TITLE
+async,core_*,incremental,posixat,re2,record_builder,shexp,splay_tree…

### PR DESCRIPTION
**Pull request by trefis**
…,textutils: v0.10

### CODE REVIEW

**Comment by trefis** [comment]
(I had forgotten a package...)

**Comment by jpdeplaix** [comment]
A lot of reverse dependencies failed with ```Unbound module Async.Std```.
Do they need a constraint over ```< "v0.9"``` or ```< "v0.10"``` ?

**Comment by trefis** [comment]
`< "v0.10"`.

**Comment by jpdeplaix** [comment]
There is still a problem on ```amqp-client``` (the constraint is not set for the depopt, it should go to the ```constraints``` field) and the build on Alpine is still failing. Could you do a separate PR to fix those two issues after this one ?

**Comment by trefis** [comment]
- #11144
- I will submit another PR soon for the alpine build failures.

**Pull request merged**
