### PR TITLE
added scaml.1.2.0pre7

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Sorry for taking so much time. I've fixed a few issues, could you return them upstream? (notably the version field was not equal to the version you're pushing here and dune is not compatible with the `{build}` tag).

There is also an issue concerning the version number. The `pre7` prefix isn't right as `1.2.0` isn't superior to `1.2.0pre7`. Opam will take `1.2.0pre7` over `1.2.0` and I don't think that's what you want. See https://opam.ocaml.org/doc/Manual.html#Package-Formulas. If that's not what you want, could you rename the version to `1.2.0~pre7` instead? (you don't have to change the archive, just the directory added in this PR)

**Comment by camlspotter** [comment]
Thanks, I will fix issues.

**Comment by camlspotter** [comment]
@kit-ty-kate Could you check the fix?  Thanks!

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
