### PR TITLE
Fix vg constraint regarding jsoo

### PR DESCRIPTION
**Pull request by hhugo**
PR to fix this upstream https://github.com/dbuenzli/vg/pull/25
cc @dbuenzli 

required for #16295

### CODE REVIEW

**Comment by avsm** [comment]
Thanks!

**Comment by joelburget** [comment]
What was the problem here? I'm on jsoo 3.6.0 and am trying to use vg.

**Comment by hhugo** [comment]
See the change in https://github.com/dbuenzli/vg/pull/25

**Comment by joelburget** [comment]
Thanks @hhugo. Does that mean vg just needs to cut a new release including your patch?

**Comment by hhugo** [comment]
yes. I believe so. cc @dbuenzli

**Comment by dbuenzli** [comment]
Will do. Thanks @hhugo for you patch.

**Pull request merged**
