### PR TITLE
Place installation instructions under 'install' target

### PR DESCRIPTION
**Pull request by darioteixeira**

### CODE REVIEW

**Comment by samoht** [comment]
Not sure why, but eliom doesn't seem to compile anymore:
```
#=== ERROR while installing eliom.4.1.0 =======================================#
# opam-version 1.2.0
# os           linux
# command      make
# path         /home/travis/.opam/system/build/eliom.4.1.0
# compiler     system (4.02.1)
# exit-code    2
# env-file     /home/travis/.opam/system/build/eliom.4.1.0/eliom-13228-4519e5.env
# stdout-file  /home/travis/.opam/system/build/eliom.4.1.0/eliom-13228-4519e5.out
# stderr-file  /home/travis/.opam/system/build/eliom.4.1.0/eliom-13228-4519e5.err
### stdout ###
# ...[truncated]
# ocamlfind ocamlc -c -thread -ppopt src/syntax/pa_include.cmo -syntax camlp4o -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax' -ppopt -sig-inc -ppopt ../src/lib -package react,js_of_ocaml -package lwt,ocsigenserver,ocsigenserver.ext,tyxml.functor -w +A-4-6-7-9-27-32-33-34-37-44 -I src/lib -I src/lib/server -o src/lib/server/eliommod_services.cmi src/lib/server/eliommod_services.mli
# ocamlfind ocamldep -ppopt src/syntax/pa_include.cmo -syntax camlp4o -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax' -ppopt -sig-inc -ppopt ../src/lib -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax,lwt.syntax' -package js_of_ocaml.syntax -package react,js_of_ocaml -package lwt,ocsigenserver,ocsigenserver.ext,tyxml.functor -modules src/lib/server/eliommod_timeouts.ml > src/lib/server/eliommod_timeouts.ml.depends
# ocamlfind ocamldep -ppopt src/syntax/pa_include.cmo -syntax camlp4o -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax' -ppopt -sig-inc -ppopt ../src/lib -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax,lwt.syntax' -package js_of_ocaml.syntax -package react,js_of_ocaml -package lwt,ocsigenserver,ocsigenserver.ext,tyxml.functor -modules src/lib/server/eliommod_sessadmin.ml > src/lib/server/eliommod_sessadmin.ml.depends
# ocamlfind ocamldep -ppopt src/syntax/pa_include.cmo -syntax camlp4o -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax' -ppopt -sig-inc -ppopt ../src/lib -package react,js_of_ocaml -package lwt,ocsigenserver,ocsigenserver.ext,tyxml.functor -modules src/lib/server/eliommod_sessadmin.mli > src/lib/server/eliommod_sessadmin.mli.depends
# ocamlfind ocamlc -c -thread -ppopt src/syntax/pa_include.cmo -syntax camlp4o -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax' -ppopt -sig-inc -ppopt ../src/lib -package react,js_of_ocaml -package lwt,ocsigenserver,ocsigenserver.ext,tyxml.functor -w +A-4-6-7-9-27-32-33-34-37-44 -I src/lib -I src/lib/server -o src/lib/server/eliommod_sessadmin.cmi src/lib/server/eliommod_sessadmin.mli
# ocamlfind ocamlopt -c -thread -ppopt src/syntax/pa_include.cmo -syntax camlp4o -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax' -ppopt -sig-inc -ppopt ../src/lib -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax,lwt.syntax' -package js_of_ocaml.syntax -package react,js_of_ocaml -package lwt,ocsigenserver,ocsigenserver.ext,tyxml.functor -w +A-4-6-7-9-27-32-33-34-37-44 -I src/lib -I src/lib/server -o src/lib/server/eliommod_sessadmin.cmx src/lib/server/eliommod_sessadmin.ml
# + ocamlfind ocamlopt -c -thread -ppopt src/syntax/pa_include.cmo -syntax camlp4o -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax' -ppopt -sig-inc -ppopt ../src/lib -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax,lwt.syntax' -package js_of_ocaml.syntax -package react,js_of_ocaml -package lwt,ocsigenserver,ocsigenserver.ext,tyxml.functor -w +A-4-6-7-9-27-32-33-34-37-44 -I src/lib -I src/lib/server -o src/lib/server/eliommod_sessadmin.cmx src/lib/server/eliommod_sessadmin.ml
# File "src/lib/server/eliommod_sessadmin.ml", line 126, characters 2-25:
# Error: Unbound value Ocsigen_messages.debug2
# Command exited with code 2.
### stderr ###
# ocamlfind: Package `wikidoc' not found
# make: *** [all] Error 10

```

**Comment by darioteixeira** [comment]
Current Eliom seems incompatible with the new version of Ocsigenserver.  However, the Ocsigen folks are planning a new release of Eliom any moment now.  That should fix it...

**Comment by samoht** [comment]
Could you add a constraint to eliom/ocsigen to make this compile? @Drup any idea which constraint is missing?

**Comment by Drup** [comment]
https://github.com/ocaml/opam-repository/pull/4515 Should have fixed that.

**Comment by samoht** [comment]
ok, so I'm restarting manually the jobs.

**Comment by Drup** [comment]
The new failure doesn't seem eliom-related.

**Comment by samoht** [comment]
Indeed this looks like a missing depext:
```
===== ERROR while installing camlhighlight.3.0 =====
# opam-version 1.1.2-rc3
# os           linux
# command      make
# path         /home/travis/.opam/system/build/camlhighlight.3.0
# compiler     system (4.02.1)
# exit-code    2
# env-file     /home/travis/.opam/system/build/camlhighlight.3.0/camlhighlight-2410-ebe0e0.env
# stdout-file  /home/travis/.opam/system/build/camlhighlight.3.0/camlhighlight-2410-ebe0e0.out
# stderr-file  /home/travis/.opam/system/build/camlhighlight.3.0/camlhighlight-2410-ebe0e0.err
### stdout ###
# ...[truncated]
# pkg_tyxml: ........................................... /home/travis/.opam/system/lib/tyxml
# ocamldoc: ............................................ /usr/bin/ocamldoc
# 
# ocaml setup.ml -build 
# /usr/bin/ocamlopt.opt unix.cmxa -I /usr/lib/ocaml/ocamlbuild /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/travis/.opam/system/bin/ocamlfind ocamlc -ccopt -x -ccopt c++ -ccopt -Wall -ccopt -Wextra -ccopt -O2 -c src/source-highlight_stubs.c
# + /home/travis/.opam/system/bin/ocamlfind ocamlc -ccopt -x -ccopt c++ -ccopt -Wall -ccopt -Wextra -ccopt -O2 -c src/source-highlight_stubs.c
# src/source-highlight_stubs.c:11:39: fatal error: srchilite/sourcehighlight.h: No such file or directory
# compilation terminated.
# Command exited with code 2.
### stderr ###
# ...[truncated]
# Warning 3: deprecated: Lazy.lazy_from_fun
# Use Lazy.from_fun instead.
# File "setup.ml", line 247, characters 8-26:
# Warning 3: deprecated: String.set
# Use Bytes.set instead.
# File "setup.ml", line 2502, characters 6-24:
# Warning 3: deprecated: Lazy.lazy_from_fun
# Use Lazy.from_fun instead.
# E: Failure("Command ''/usr/bin/ocamlbuild' src/libcamlhighlight_stubs.a src/dllcamlhighlight_stubs.so src/camlhighlight.cma src/camlhighlight.cmxa src/camlhighlight.a src/camlhighlight.cmxs -tag debug' terminated with error code 10")
# make: *** [build] Error 1
```

**Comment by darioteixeira** [comment]
If you look at the details of the Travis build, you'll see that the only failure is on the job for OPAM 1.1.1.  Did this version of OPAM even know about depexts?

**Comment by samoht** [comment]
Hum actually it seems to be an issue with the latest release of `opam-depext` and opam 1.1.1:

```
=-=-= Installing depext.0.7 =-=-=
depext.0.7 Downloading https://github.com/ocaml/opam-depext/archive/v0.7.tar.gz
Building depext.0.7:
  ocamlopt -I /home/travis/.opam/system/lib/cmdliner unix.cmxa cmdliner.cmxa -o opam-depext depext.ml
  ocamlc -I /home/travis/.opam/system/lib/cmdliner unix.cma cmdliner.cma -o opam-depext depext.ml
Installing depext.0.7.
opam: unknown option `--safe'
Usage: opam list [OPTION]... [PATTERNS]...
Try `opam list --help' or `opam --help' for more information.
# Detecting depexts using flags: x86_64 linux ubuntu
opam: unknown option `--safe'
Usage: opam list [OPTION]... [PATTERNS]...
Try `opam list --help' or `opam --help' for more information.
opam: unknown option `--safe'
Usage: opam list [OPTION]... [PATTERNS]...
```

I'm not sure where this comes from, if someone has time to investigate that would be handy. @AltGr or @avsm maybe?

**Comment by AltGr** [comment]
I'll have a look, see if it can be fixed in either depext or the travis scripts.

**Comment by samoht** [comment]
I've relaunched the failing job, hopefully it should be better now (after @AltGr fixes)

**Pull request merged**
