### PR TITLE
Package yuujinchou.4.0.0

### PR DESCRIPTION
**Pull request by favonia**
### `yuujinchou.4.0.0`
A domain-specific language for manipulating hierarchical names
This package offers a domain-specific language for manipulating hierarchical names. It intends to facilitate the implementation of lexical scoping and import statements.

---
* Homepage: https://github.com/RedPRL/yuujinchou
* Source repo: git+https://github.com/RedPRL/yuujinchou.git
* Bug tracker: https://github.com/RedPRL/yuujinchou/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by favonia** [comment]
I'm not sure what happened in the failed jobs---it seems some build environments are using the pre-release versions of OCaml 5.0.0?

**Comment by favonia** [comment]
PS: one might want to squash the history as this PR contains several merge commits.

**Comment by favonia** [comment]
The `debian-10-ocaml-5.0` environment reports `Effect.Unhandled` is not a contsructor. This indicates that `debian-10-ocaml-5.0` is using pre-beta releases of OCaml 5.

PS: One might want to squash all the merge commits in this PR.

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
