### PR TITLE
Disable detection of num from ocamlfind

### LINKED ISSUE #10925: Confusing state of num in 4.05.0 and ocamlfind 1.7.3
I updated my `4.05.0` switch to ocamlfind 1.7.3 and now
```
$ ocamlfind query num
ocamlfind: Package `num' not found
```
but
```
$ opam info num

=-=- num: information on all versions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
name                   num
all-installed-versions 0 [4.05.0+trunk+flambda 4.05.0+flambda 4.05.0+spacetime 4.05.0+flambda+spacetime 4.04.0 4.05.0]  1.1 [4.06.0]
all-versions           0  1.0  1.1

=-=- Version-specific details -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
version      0
repository   default
homepage:    https://github.com/ocaml/ocaml
bug-reports: http://caml.inria.fr/mantis/
dev-repo:    git+https://github.com/ocaml/ocaml.git
authors:     "Valérie Ménissier-Morain" "Pierre Weis" "Xavier Leroy"
license:     LGPL-2 with OCaml linking exception
depends:     "ocaml" {< "4.06.0"} "base-num"
synopsis     The Num library for arbitrary-precision integer and rational arithmetic
```
and
```
$ opam list | grep num
base-num                base         Num library distributed with the OCaml compiler
num                     0            The Num library for arbitrary-precision integer and rational arithmetic
parany                  3.0.0        Parallelize any computation over independent items, even if there is an infinite number of them.
ppx_enumerate           v0.9.0       Generate a list containing all values of a finite type
```

### PR DESCRIPTION
**Pull request by AltGr**
as an attempt to fix #10925

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I think this might need to be a separate revision version. Could you copy it to `ocamlfind.1.8.1-1` instead?

**Comment by kit-ty-kate** [comment]
@thomasblanc Camelus seems to still fail. Could you have a look?

**Comment by mseri** [comment]
Is there a reason we cannot upstream this change?

**Comment by AltGr** [comment]
Hold on this, we discussed a better solution with @dra27

**Comment by thomasblanc** [comment]
@kit-ty-kate sorry for the lack of answers, it seems that Camelus is getting cranky. I'm trying to put some sense into him.

**Comment by thomasblanc** [comment]
@kit-ty-kate should be fixed.

**Comment by kit-ty-kate** [comment]
@AltGr @dra27 any news on the alternative solution?

**Comment by kit-ty-kate** [comment]
Closing this for the moment. Please reopen when the new solution is available

**Pull request closed without merging**
