### PR TITLE
[new release] xdg, stdune, ordering, ocamlc-loc, fiber, dyn, dune, dune-site, dune-rpc, dune-rpc-lwt, dune-private-libs, dune-glob, dune-configurator, dune-build-info and dune-action-plugin (3.1.0)

### PR DESCRIPTION
**Pull request by rgrinberg**
XDG Base Directory Specification

- Project page: <a href="https://github.com/ocaml/dune">https://github.com/ocaml/dune</a>
- Documentation: <a href="https://dune.readthedocs.io/">https://dune.readthedocs.io/</a>

##### CHANGES:

- Add `sourcehut` as an option for defining project sources in dune-project
  files. For example, `(source (sourcehut user/repo))`. (ocaml/dune#5564, @rgrinberg)

- Add `dune coq top` command for running a Coq toplevel (ocaml/dune#5457, @rlepigre)

- Fix dune exec dumping database in wrong directory (ocaml/dune#5544, @bobot)

- Always output absolute paths for locations in RPC reported diagnostics
  (ocaml/dune#5539, @rgrinberg)

- Add `(deps <deps>)` in ctype field (ocaml/dune#5346, @bobot)

- Add `(include <file>)` constructor to dependency specifications. This can be
  used to introduce dynamic dependencies (ocaml/dune#5442, @anmonteiro)

- Ensure that `dune describe` computes a transitively closed set of
  libraries (ocaml/dune#5395, @esope)

- Add direct dependencies to $ dune describe output (ocaml/dune#5412, @esope)

- Show auto-detected concurrency on Windows too (ocaml/dune#5502, @MisterDA)

- Fix operations that remove folders with absolute path. This happens when
  using esy (ocaml/dune#5507, @EduardoRFS)

- Dune will not fail if some directories are non-empty when uninstalling.
  (ocaml/dune#5543, fixes ocaml/dune#5542, @nojb)

- `coqdep` now depends only on the filesystem layout of the .v files,
  and not on their contents (ocaml/dune#5547, helps with ocaml/dune#5100, @ejgallego)

- The mdx stanza 0.2 can now be used with `(implicit_transitive_deps false)`
  (ocaml/dune#5558, fixes ocaml/dune#5499, @emillon)

- Fix missing parenthesis in printing of corresponding terminal command for
  `(with-outputs-to )` (ocaml/dune#5551, fixes ocaml/dune#5546, @Alizter)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
```
#=== ERROR while compiling ocamlc-loc.3.1.0 ===================================#
# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.13.1 | pinned(https://github.com/ocaml/dune/releases/download/3.1.0/fiber-3.1.0.tbz)
# path                 ~/.opam/4.13/.opam-switch/build/ocamlc-loc.3.1.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlc-loc -j 31 @install
# exit-code            1
# env-file             ~/.opam/log/ocamlc-loc-2104-2330bc.env
# output-file          ~/.opam/log/ocamlc-loc-2104-2330bc.out
### output ###
# File "src/ocamlc_loc/dune", line 4, characters 12-19:
# 4 |  (libraries dune_re dyn))
#                 ^^^^^^^
# Error: Library "dune_re" not found.
# -> required by library "ocamlc-loc" in _build/default/src/ocamlc_loc
# -> required by _build/default/META.ocamlc-loc
# -> required by _build/install/default/lib/ocamlc-loc/META
# -> required by _build/default/ocamlc-loc.install
# -> required by alias install

- File "src/ocamlc_loc/dune", line 4, characters 12-19:
- 4 |  (libraries dune_re dyn))
-                 ^^^^^^^
- Error: Library "dune_re" not found.
- -> required by library "ocamlc-loc" in _build/default/src/ocamlc_loc
- -> required by _build/default/META.ocamlc-loc
- -> required by _build/install/default/lib/ocamlc-loc/META
- -> required by _build/default/ocamlc-loc.install
- -> required by alias install
```

**Comment by rgrinberg** [comment]
That's a bit of a shame. How about we just remove ocamlc_loc from the submitted packages. I'll fix it upstream and resubmit eventually.

**Comment by Blaisorblade** [comment]
The new failure seems spurious, isn't it? E.g. https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/7807dd155520fc2079a1f377f34bd32bb7e54dbb/variant/opam-2.1,compilers,4.14,dune-configurator.3.1.0,revdeps,aacplus.0.2.1 is failing on `configure`...

**Comment by kit-ty-kate** [comment]
Thanks. Sorry for the wait

**Pull request merged**
