### PR TITLE
Package ppx_deriving_jsoo.0.2

### PR DESCRIPTION
**Pull request by ocpmax**
### `ppx_deriving_jsoo.0.2`
Ppx deriver for Js_of_ocaml

---
* Homepage: https://gitlab.com/o-labs/ppx_deriving_jsoo
* Source repo: git://gitlab.com/o-labs/ppx_deriving_jsoo
* Bug tracker: https://gitlab.com/o-labs/ppx_deriving_jsoo/-/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This package doesn't seem to be compatible with ppxlib 0.18 and newer:
```
#=== ERROR while compiling ppx_deriving_jsoo.0.2 ==============================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(https://gitlab.com/api/v4/projects/22645789/repository/archive?sha=2fa6de4c7361e71048c308180e2d47aa1ae255f5)
# path                 ~/.opam/4.08/.opam-switch/build/ppx_deriving_jsoo.0.2
# command              ~/.opam/4.08/bin/dune build -p ppx_deriving_jsoo -j 47 @install
# exit-code            1
# env-file             ~/.opam/log/ppx_deriving_jsoo-1-9a63fb.env
# output-file          ~/.opam/log/ppx_deriving_jsoo-1-9a63fb.out
### output ###
#       ocamlc src/.ppx_deriving_jsoo.objs/byte/ppx_deriving_jsoo__Common.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.ppx_deriving_jsoo.objs/byte -I /home/opam/.opam/4.08/lib/ocaml-compiler-libs/common -I /home/opam/.opam/4.08/lib/ocaml-compiler-libs/shadow -I /home/opam/.opam/4.08/lib/ocaml-migrate-parsetree -I /home/opam/.opam/4.08/lib/ocaml/compiler-libs -I /home/opam/.opam/4.08/lib/ppx_derivers -I /home/opam/.opam/4.08/lib/ppxlib -I /home/opam/.opam/4.08/lib/ppxlib/ast -I /home/opam/.opam/4.08/lib/ppxlib/print_diff -I /home/opam/.opam/4.08/lib/ppxlib/stdppx -I /home/opam/.opam/4.08/lib/ppxlib/traverse_builtins -I /home/opam/.opam/4.08/lib/sexplib0 -I /home/opam/.opam/4.08/lib/stdlib-shims -no-alias-deps -open Ppx_deriving_jsoo__ -o src/.ppx_deriving_jsoo.objs/byte/ppx_deriving_jsoo__Common.cmo -c -impl src/common.pp.ml)
# File "src/common.ml", line 42, characters 61-83:
# 42 |   | PStr [{pstr_desc = Pstr_eval ({pexp_desc = Pexp_constant (Pconst_string (s, _)); _}, _); _}] -> Some s
#                                                                   ^^^^^^^^^^^^^^^^^^^^^^
# Error: The constructor Pconst_string expects 3 argument(s),
#        but is applied here to 2 argument(s)
```
Do you want to restrict this version or fix the issue and retag the release?

**Comment by ocpmax** [comment]
sorry, I didn't push the correct commit hash, the release should be for ppxlib >= 0.16

**Comment by kit-ty-kate** [comment]
> sorry, I didn't push the correct commit hash, this release should be for ppxlib >= 0.16

Thanks a lot! However this is not entirely correct as this requires at least ppxlib 0.18 (the API changed in 0.18.0 as shown by the `Pconst_string` change in your latest commit). Could you return my latest commit to your opam file upstream so that this fix is also there next time around?

**Comment by ocpmax** [comment]
my bad, I thought they did this change when going to ocaml-migrate-parsetree >= 2.
I will also a push a corrective version of ppx_deriving_encoding that uses the same dependency

**Pull request merged**
