### PR TITLE
[new release] zmq, zmq-lwt and zmq-async (5.2.0)

### PR DESCRIPTION
**Pull request by andersfugmann**
OCaml bindings for ZeroMQ 4.x

- Project page: <a href="https://github.com/issuu/ocaml-zmq">https://github.com/issuu/ocaml-zmq</a>

##### CHANGES:

* Remove dependency on StdInt (issuu/ocaml-zmq#121, @andersfugmann)

* Silence warnings about `const char*` when writing to the inside of an
  allocated string value (issuu/ocaml-zmq#116, @Leonidas-from-XIV)

### CODE REVIEW

**Comment by andersfugmann** [comment]
The tests seems to be stuck.
The error reported on`frama-c.24.0` is caused by a faulty expect test (Difference is a newline inserted in some json test result) and not related to this PR.

**Comment by raphael-proust** [comment]
I have restarted the test that timeouted.

The other two errors seem to be due to frama-c (has been an issue on some other packages recently) and macos ci setup (that too has been an issue on some other packages).

**Comment by mseri** [comment]
Looks mostly good. However the async tests hang forever in s390x, seems to not be a CI issue

**Comment by andersfugmann** [comment]
The hanging test is indeed a bug. One a fix is merged upstream, I will update the PR.

**Comment by andersfugmann** [comment]
Once the fix for s390x has been merged upstream,  I'll create a new release. Closing this PR.

**Pull request closed without merging**
