### PR TITLE
mirage.1.0.0: fix remove instructions

### PR DESCRIPTION
**Pull request by planar**

### CODE REVIEW

**Comment by dsheets** [comment]
What is your method for sussing these issues?

**Comment by planar** [comment]
I'm basically trying to install all packages one after the other in alphabetical order. When something goes wrong, I investigate and from time to time something else goes wrong while I investigate, so I investigate recursively. Unfortunately, this is very time-consuming.

Some parts of this process could be more automated (e.g. detecting the remove problems).

**Comment by dsheets** [comment]
Do you know of <http://www.recoil.org/~avsm/opam-bulk/>?

**Comment by planar** [comment]
Yes, I'm doing something like that, but my goal is slightly different: I want to test modified versions of the compiler and compare the results to the normal one.

I also need to do that for a stable set of packages, rather than the live repository.

All the PR I submit here are just a side product of this process.

**Comment by avsm** [comment]
Yeah, both of those use cases should be satisfied by ocaml-docker-scripts, but I need to replace the Makefile with Jenga to speed things up first.  You can currently do a mass Docker build with multiple revisions of the compiler and a fixed opam-repository rev, as all of those are tracked in the container.  What's missing is a decent frontend -- I'm hoping to do some refactoring on it this week and write it up soon.

**Pull request merged**
