### PR TITLE
base v0.14.2

### PR DESCRIPTION
**Pull request by cwong-ocaml**
Includes [this fix](https://github.com/janestreet/base/pull/124)

### CODE REVIEW

**Comment by cwong-ocaml** [comment]
Looks like there's some incompatibility with ocaml-variants >= 0.14.0? I'm unsure how to proceed.

**Comment by kit-ty-kate** [comment]
I’m not sure to understand why the requirement was bumped to a compiler that is not released yet. My PR was compatible with previous versions of the compiler as well, as far as I know.

**Comment by cwong-ocaml** [comment]
looks like a miscommunication, let's try again

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
