### PR TITLE
Add coq.8.5.0~camlp4

### PR DESCRIPTION
**Pull request by jeehoonkang**

### CODE REVIEW

**Comment by dsheets** [comment]
Hi! I don't know much about coq's build system. Does it really work with camlp4 (and camlp5??) now?

I don't think we can merge this package with this name because it conflicts with the other coq package that uses camlp5. If there is a variant of coq that uses camlp4, we should probably publish it under a different package name (`coq-camlp4`?) and mark it as conflicted with the primary coq package (and vice versa). Alternately, the primary coq package could be modified to use *either* camlp4 *or* camlp5 and they could be put in a disjunction in the `depends` constraints.

Finally, from the CI, it doesn't look like this package is compatible with OCaml 4.00 or 4.01 so those constraints should be declared.

Thank you!

**Comment by jeehoonkang** [comment]
Hi!

- Coq 8.5 still supports `-usecamlp4` and `-usecamlp5` options.  Coqs complied with different `camlp?` options *behave differently*, so this PR just supports two versions of Coqs with different version tags.  This is consistent with the convention from a previous package (`coq.8.4.6~camlp4`).
- As you said, it seems OCaml 4.02 is required.  I will add the requirement.

**Comment by dsheets** [comment]
Great! Thanks! After you add the OCaml version constraint, this is ready for merge.

I am skeptical of the camlp4/camlp5 version modifier convention because, as you say, these packages behave differently and users will probably care. With a difference only in the version of the package, doing things like `opam install coq` and `opam upgrade coq` can have unexpected results. It also becomes unwieldy to depend on "coq+camlp4" in a version range as there is no way to select across versions with the `~camlp4` modifier.

If current users are fine with this behavior, then I'll stop worrying. :smile:

**Comment by jeehoonkang** [comment]
Hi!  I just updated this PR.  Please review :-)  Thank you!

**Pull request merged**
