### PR TITLE
Octez 17.1 packages

### PR DESCRIPTION
**Pull request by killian-delarue**
Packages for Octez 17.1

### CODE REVIEW

**Comment by avsm** [comment]
This package may be missing a constraint on the version of `ocaml`

```
#=== ERROR while compiling octez-distributed-internal.17.1 ====================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | pinned(https://gitlab.com/tezos/tezos/-/archive/v17.1/tezos-17.1.tar.gz)
# path                 ~/.opam/5.0/.opam-switch/build/octez-distributed-internal.17.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p octez-distributed-internal -j 255
# exit-code            1
# env-file             ~/.opam/log/octez-distributed-internal-7-8a5edd.env
# output-file          ~/.opam/log/octez-distributed-internal-7-8a5edd.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -O3 -I src/lib_distributed_internal/src/.distributed.objs/byte -I src/lib_distributed_internal/src/.distributed.objs/native -I /home/opam/.opam/5.0/lib/ocaml/unix -intf-suffix .ml -no-alias-deps -o src/lib_distributed_internal/src/.distributed.objs/native/distributed.cmx -c -impl src/lib_distributed_internal/src/distributed.ml)
# File "src/lib_distributed_internal/src/distributed.ml", line 73, characters 25-70:
# 73 | module Node_id_hashtbl = Hashtbl.MakeSeeded (Node_id_seeded_hash_type)
#                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Modules do not match:
#        sig
#          type t = Node_id.t
#          val equal : t -> t -> bool
#          val hash : int -> t -> int
#        end
#      is not included in Hashtbl.SeededHashedType
#      The value `seeded_hash' is required but not provided
#      File "hashtbl.mli", line 411, characters 4-36: Expected declaration
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/lib_distributed_internal/src/.distributed.objs/byte -I /home/opam/.opam/5.0/lib/ocaml/unix -intf-suffix .ml -no-alias-deps -o src/lib_distributed_internal/src/.distributed.objs/byte/distributed.cmo -c -impl src/lib_distributed_internal/src/distributed.ml)
# File "src/lib_distributed_internal/src/distributed.ml", line 73, characters 25-70:
# 73 | module Node_id_hashtbl = Hashtbl.MakeSeeded (Node_id_seeded_hash_type)
#                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Modules do not match:
#        sig
#          type t = Node_id.t
#          val equal : t -> t -> bool
#          val hash : int -> t -> int
#        end
#      is not included in Hashtbl.SeededHashedType
#      The value `seeded_hash' is required but not provided
#      File "hashtbl.mli", line 411, characters 4-36: Expected declaration

```

**Comment by killian-delarue** [comment]
> This package may be missing a constraint on the version of `ocaml`
> 
> ```
> #=== ERROR while compiling octez-distributed-internal.17.1 ====================#
> # context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | pinned(https://gitlab.com/tezos/tezos/-/archive/v17.1/tezos-17.1.tar.gz)
> # path                 ~/.opam/5.0/.opam-switch/build/octez-distributed-internal.17.1
> # command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p octez-distributed-internal -j 255
> # exit-code            1
> # env-file             ~/.opam/log/octez-distributed-internal-7-8a5edd.env
> # output-file          ~/.opam/log/octez-distributed-internal-7-8a5edd.out
> ### output ###
> # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -O3 -I src/lib_distributed_internal/src/.distributed.objs/byte -I src/lib_distributed_internal/src/.distributed.objs/native -I /home/opam/.opam/5.0/lib/ocaml/unix -intf-suffix .ml -no-alias-deps -o src/lib_distributed_internal/src/.distributed.objs/native/distributed.cmx -c -impl src/lib_distributed_internal/src/distributed.ml)
> # File "src/lib_distributed_internal/src/distributed.ml", line 73, characters 25-70:
> # 73 | module Node_id_hashtbl = Hashtbl.MakeSeeded (Node_id_seeded_hash_type)
> #                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> # Error: Modules do not match:
> #        sig
> #          type t = Node_id.t
> #          val equal : t -> t -> bool
> #          val hash : int -> t -> int
> #        end
> #      is not included in Hashtbl.SeededHashedType
> #      The value `seeded_hash' is required but not provided
> #      File "hashtbl.mli", line 411, characters 4-36: Expected declaration
> # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/lib_distributed_internal/src/.distributed.objs/byte -I /home/opam/.opam/5.0/lib/ocaml/unix -intf-suffix .ml -no-alias-deps -o src/lib_distributed_internal/src/.distributed.objs/byte/distributed.cmo -c -impl src/lib_distributed_internal/src/distributed.ml)
> # File "src/lib_distributed_internal/src/distributed.ml", line 73, characters 25-70:
> # 73 | module Node_id_hashtbl = Hashtbl.MakeSeeded (Node_id_seeded_hash_type)
> #                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> # Error: Modules do not match:
> #        sig
> #          type t = Node_id.t
> #          val equal : t -> t -> bool
> #          val hash : int -> t -> int
> #        end
> #      is not included in Hashtbl.SeededHashedType
> #      The value `seeded_hash' is required but not provided
> #      File "hashtbl.mli", line 411, characters 4-36: Expected declaration
> ```

Indeed, I added the constraints in 63428c6281c3b389d301e9bd7c43b430b3422a55

**Comment by raphael-proust** [comment]
In some parts of our codebase we do provide functor parameters which are compatible with both 4 and 5 ocamls. This use has crept up since then. I'll make sure to fix it upstream.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
