### PR TITLE
New zmq version fixing compilation on OSX and BSD

### PR DESCRIPTION
**Pull request by andersfugmann**

### CODE REVIEW

**Comment by andersfugmann** [comment]
The tests fails because travis uses an old outdated version of ZMQ 3.x.x.
The opam package zmq requires libzmq3-dev >= 4.0.0,
but Travis installs libzmq3-dev_3.2.2+dfsg-1~travis1_amd64.deb (libzmq version version 3.2.2).
Travis seems to be based on ubuntu version 12.04 (precise), which is more than four years old and thus installs libzmq3-dev 3.2.2+dfsg-1~travis1 which is not supported by the ocaml zmq bindings.

Is there a way to have Travis install a more up to date version of libzmq3? Updating ubuntu to 14.04 would solve the problem.

**Comment by avsm** [comment]
> Is there a way to have Travis install a more up to date version of libzmq3?

There is -- we'll have Docker-based container support for Travis shortly, and I'll update this PR when the container builds finish.

**Comment by andersfugmann** [comment]
Thanks. Looking forward to it.

**Pull request merged**
