### PR TITLE
Package azure-cosmos-db.0.2.1

### PR DESCRIPTION
**Pull request by mknaack**
### `azure-cosmos-db.0.2.1`
Azure cosmos db interface
Provides an interface to the Azure Cosmos db.

---
* Homepage: https://bitbucket.org/knaack/azure-cosmos-db
* Source repo: git+https://bitbucket.org/knaack/azure-cosmos-db.git
* Bug tracker: https://bitbucket.org/knaack/azure-cosmos-db/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The naked-pointer checker is detecting naked pointer in the code:
```
#=== ERROR while compiling azure-cosmos-db.0.2.1 ==============================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-options-only-nnpchecker.1 | pinned(https://bitbucket.org/knaack/azure-cosmos-db/get/a9f6cd4145b2f18c8248e54a28634367ab93c11c.tar.gz)
# path                 ~/.opam/4.14/.opam-switch/build/azure-cosmos-db.0.2.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p azure-cosmos-db -j 255
# exit-code            1
# env-file             ~/.opam/log/azure-cosmos-db-7-b9d924.env
# output-file          ~/.opam/log/azure-cosmos-db-7-b9d924.out
### output ###
# File "test/dune", line 2, characters 7-11:
# 2 |  (name test)
#            ^^^^
# (cd _build/default/test && ./test.exe)
# Testing `Main tests'.
# This run has ID `BDLPL846'.
# 
#   [OK]          utility test                0   x_ms_date.
#   [OK]          utility test                1   adjust_host_no_change.
#   [OK]          utility test                2   adjust_host_change.
#   [OK]          utility test                3   auth_key_test.
#   [OK]          utility test                4   auth_key_test_get_list.
#   [OK]          utility test                5   convert_list_databases_test.
#   [OK]          utility test                6   string_of_bool_true.
#   [OK]          utility test                7   string_of_bool_false.
# 
# Full test results in `~/.opam/4.14/.opam-switch/build/azure-cosmos-db.0.2.1/_build/default/test/_build/_tests/Main tests'.
# Test Successful in 0.001s. 8 tests run.
# Out-of-heap pointer at 0x562c4cc5ae80 of value 0x562c4cb11df0 has non-black head (tag=65)
# 
# Out-of-heap pointers were detected by the runtime.
# The process would otherwise have terminated normally.
```
Could you have a look and see where it is coming from?

**Comment by mknaack** [comment]
I believe the problem comes from cohttp. I could not get 'rr' to work but managed to make a small example with cohttp that give the same error.

**Comment by mseri** [comment]
Can you open an issue on the cohttp repo with the example?

**Comment by mknaack** [comment]
Sure - I have made an issue on cohttp with the example. [https://github.com/mirage/ocaml-cohttp/issues/964](https://github.com/mirage/ocaml-cohttp/issues/964)

**Comment by mseri** [comment]
Thanks!

**Comment by mseri** [comment]
I think we can merge this, since the issue is unrelated

**Pull request merged**
