### PR TITLE
Constrain acpc 1.0, 1.1, 1.2, 1.2.1, 1.2.2 to pre-4.06.0 compilers

### PR DESCRIPTION
**Pull request by minishrink**

### CODE REVIEW

**Comment by gasche** [comment]
It would be nice for these PRs if you could indicate a source explaining why you think that these packages should be constrained. My opam-builder bot only reports that those packages have a dependency that is unavailable under 4.06, not a build error -- but then maybe some other version combinations do?

**Comment by avsm** [comment]
Yes, it looks like dolog is the culprit

```
#=== ERROR while compiling dolog.0.6 ==========================================#
# context              2.0.0~beta5 | linux/x86_64 | ocaml-base-compiler.4.06.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.06.0/.opam-switch/build/dolog.0.6
# command              ~/.opam/4.06.0/bin/ocaml setup.ml -configure --prefix /home/opam/.opam/4.06.0
# exit-code            2
# env-file             ~/.opam/log/dolog-1-e80101.env
# output-file          ~/.opam/log/dolog-1-e80101.out
### output ###
# File "./setup.ml", line 234, characters 8-26:
# Warning 3: deprecated: String.set
# Use Bytes.set instead.
# File "./setup.ml", line 234, characters 8-11:
# Error: This expression has type string but an expression was expected of type
#          bytes
```

@minishrink the logs on http://obi.ocamllabs.io/triage.html are working again and not just container failures :)

**Comment by minishrink** [comment]
Ah, I see, I was using the other page to indicate build failures. I take it this and the acme PR can be closed?

**Comment by gasche** [comment]
Yes, but note that we may need this PR anyway after the build of the dependencies have been resolved: we don't know if they work with -safe-string yet, given that their dependencies fail. (In that case we can always reopen the PR or reuse bits in a new PR.)

Also: apologies for having bit a bit dry in my question above -- the question was natural to me but of course there is no reason it would be natural to a new contributor. Thanks for your contributions to the health of the opam repository.

**Pull request closed without merging**
