### PR TITLE
yojson 1.4.0

### PR DESCRIPTION
**Pull request by mjambon**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
The minimal version of ```biniou``` required does not match the new version number of ```biniou```.

**Comment by mjambon** [comment]
Thanks for the heads up. I have to fix the biniou package too (at https://github.com/ocaml/opam-repository/pull/9867)

**Comment by jpdeplaix** [comment]
Well, it's not what I had in mind in the first place. As written in https://github.com/mjambon/biniou/pull/23, I added some ```@since 1.2.0``` guessing that it will be the next version, but turns out it's not.
But since it's only 2-3 functions, I suppose it's not a big deal and it can be fixed later.

**Comment by mjambon** [comment]
My bad. I released 1.2.0.

**Comment by jpdeplaix** [comment]
No worries.

**Pull request merged**
