### PR TITLE
Fix older sha packages

### PR DESCRIPTION
**Pull request by djs55**
- the repo move has invalidated the checksum
- the metadata is now linted
- use my recent email address

Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by djs55** [comment]
@talex5 I think `0install` might be incompatible with the old `sha.1.8`

**Comment by talex5** [comment]
Yes, looks like it. Do you want to add a constraint in this PR, or should I make one?

**Comment by djs55** [comment]
Probably better in a separate PR (I might mess it up)

**Comment by djs55** [comment]
Apart from `0install` the other failures are dependencies unavailable on 4.06.0 which are being fixed separately.

**Pull request merged**
