### PR TITLE
Package ocaml-gist.0.0.1

### PR DESCRIPTION
**Pull request by SanderSpies**
### `ocaml-gist.0.0.1`

A tool to create online OCaml gist experiences for the web

---
* Homepage: https://github.com/SanderSpies/ocaml-gist
* Source repo: https://github.com/SanderSpies/ocaml-gist.git
* Bug tracker: https://github.com/SanderSpies/ocaml-gist/issues

---
### opam-lint failures
- **WARNING** 97 long description unspecified

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by avsm** [comment]
This PR is blocked on https://github.com/ocaml/opam-repository/pull/10898

**Comment by SanderSpies** [comment]
Can this be merged?

**Comment by jpdeplaix** [comment]
I'm curious, what is it that makes this package only available with OCaml 4.04.2 ?

**Comment by SanderSpies** [comment]
@jpdeplaix it depends on ocaml-webworker which only supports ocaml 4.04.2. The reason for this is that the webworker contains a modified part of merlin to run on the web. Doing this requires a bunch of work and I haven't gotten around at making this work for other OCaml versions. 4.02.3 might work, but I'm not 100% sure.

**Comment by hcarty** [comment]
Even if the version constraints are overly restrictive at first I think this should be merged now. The constraints can be relaxed in a separate PR if/as it is found possible to do so.

**Comment by jpdeplaix** [comment]
> Even if the version constraints are overly restrictive at first I think this should be merged now. The constraints can be relaxed in a separate PR if/as it is found possible to do so.

Fair enough.

**Comment by SanderSpies** [comment]
Thank you!

**Comment by jpdeplaix** [comment]
Ok I shouldn't have been that enthusiastic.
Could you do another PR to add a ```conf-npm``` package as yours needs npm to be built ?

**Comment by jpdeplaix** [comment]
poke @SanderSpies

**Pull request merged**
