### PR TITLE
+uri.2.0.0

### PR DESCRIPTION
**Pull request by avsm**
* Create a new subpackage `uri.sexp` for the sexpression converters, so
  that the base Uri package is more dependency free (based on #121 by @Julow).
  To convert old code, simply use `Uri_sexp.t` instead of `Uri.t` in a record
  type for which you are using `[@@deriving sexp]`.  This is a type alias to
  `Uri.t` but also has the right sexp-conversion functions in scope.
* Deprecate `Uri_re` in favour of `Uri.Re`.  The unwrapped `Uri_re` will
  be removed in a future release of this library.
* Switch to using sexplib0 instead of sexplib for easier dependencies
  (based on #123 by @mseri)
* Port build to Dune from jbuilder.
* Add benchmarks using `core_bench` (#125 via @drup)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I think those two packages need upper-bound constraint on uri:
```
#=== ERROR while compiling async_js.v0.11.0 ===================================#
# context              2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.07/.opam-switch/build/async_js.v0.11.0
# command              ~/.opam/4.07/bin/jbuilder build -p async_js -j 127
# exit-code            1
# env-file             ~/.opam/log/async_js-18-dea771.env
# output-file          ~/.opam/log/async_js-18-dea771.out
### output ###
#     ocamlopt src/.async_js.objs/async_js__Rpc.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlopt.opt -w -40 -safe-string -g -I src/.async_js.objs -I src/.async_js.objs/.private -I /home/opam/.opam/4.07/lib/async_kernel -I /home/opam/.opam/4.07/lib/async_rpc_kernel -I /home/opam/.opam/4.07/lib/base -I /home/opam/.opam/4.07/lib/base/caml -I /home/opam/.opam/4.07/lib/base/md5 -I /home/opam/.opam/4.07/lib/base/shadow_stdlib -I /home/opam/.opam/4.07/lib/bin_prot -I /home/opam/.opam/4.07/lib/bin_prot/shape -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/core_kernel -I /home/opam/.opam/4.07/lib/core_kernel/base_for_tests -I /home/opam/.opam/4.07/lib/fieldslib -I /home/opam/.opam/4.07/lib/jane-street-headers -I /home/opam/.opam/4.07/lib/js_of_ocaml -I /home/opam/.opam/4.07/lib/parsexp -I /home/opam/.opam/4.07/lib/ppx_assert/runtime-lib -I /home/opam/.opam/4.07/lib/ppx_bench/runtime-lib -I /home/opam/.opam/4.07/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.07/lib/ppx_expect/collector -I /home/opam/.opam/4.07/lib/ppx_expect/common -I /home/opam/.opam/4.07/lib/ppx_expect/config -I /home/opam/.opam/4.07/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.07/lib/ppx_inline_test/config -I /home/opam/.opam/4.07/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.07/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.07/lib/protocol_version_header -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/sexplib -I /home/opam/.opam/4.07/lib/sexplib0 -I /home/opam/.opam/4.07/lib/splittable_random -I /home/opam/.opam/4.07/lib/stdio -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/typerep -I /home/opam/.opam/4.07/lib/uchar -I /home/opam/.opam/4.07/lib/uri -I /home/opam/.opam/4.07/lib/variantslib -intf-suffix .ml -no-alias-deps -open Async_js__ -o src/.async_js.objs/async_js__Rpc.cmx -c -impl src/rpc.pp.ml)
# File "src/rpc.ml", line 151, characters 58-71:
# Error: Unbound value Uri.sexp_of_t
#       ocamlc src/.async_js.objs/async_js__Rpc.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I src/.async_js.objs -I src/.async_js.objs/.private -I /home/opam/.opam/4.07/lib/async_kernel -I /home/opam/.opam/4.07/lib/async_rpc_kernel -I /home/opam/.opam/4.07/lib/base -I /home/opam/.opam/4.07/lib/base/caml -I /home/opam/.opam/4.07/lib/base/md5 -I /home/opam/.opam/4.07/lib/base/shadow_stdlib -I /home/opam/.opam/4.07/lib/bin_prot -I /home/opam/.opam/4.07/lib/bin_prot/shape -I /home/opam/.opam/4.07/lib/bytes -I /home/opam/.opam/4.07/lib/core_kernel -I /home/opam/.opam/4.07/lib/core_kernel/base_for_tests -I /home/opam/.opam/4.07/lib/fieldslib -I /home/opam/.opam/4.07/lib/jane-street-headers -I /home/opam/.opam/4.07/lib/js_of_ocaml -I /home/opam/.opam/4.07/lib/parsexp -I /home/opam/.opam/4.07/lib/ppx_assert/runtime-lib -I /home/opam/.opam/4.07/lib/ppx_bench/runtime-lib -I /home/opam/.opam/4.07/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.07/lib/ppx_expect/collector -I /home/opam/.opam/4.07/lib/ppx_expect/common -I /home/opam/.opam/4.07/lib/ppx_expect/config -I /home/opam/.opam/4.07/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.07/lib/ppx_inline_test/config -I /home/opam/.opam/4.07/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.07/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.07/lib/protocol_version_header -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/posix -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/sexplib -I /home/opam/.opam/4.07/lib/sexplib0 -I /home/opam/.opam/4.07/lib/splittable_random -I /home/opam/.opam/4.07/lib/stdio -I /home/opam/.opam/4.07/lib/stringext -I /home/opam/.opam/4.07/lib/typerep -I /home/opam/.opam/4.07/lib/uchar -I /home/opam/.opam/4.07/lib/uri -I /home/opam/.opam/4.07/lib/variantslib -intf-suffix .ml -no-alias-deps -open Async_js__ -o src/.async_js.objs/async_js__Rpc.cmo -c -impl src/rpc.pp.ml)
# File "src/rpc.ml", line 151, characters 58-71:
# Error: Unbound value Uri.sexp_of_t
```
```
#=== ERROR while compiling wamp.1.0 ===========================================#
# context              2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.07/.opam-switch/build/wamp.1.0
# command              ~/.opam/4.07/bin/ocaml pkg/pkg.ml build --pinned false --with-yojson false --with-msgpck false
# exit-code            1
# env-file             ~/.opam/log/wamp-18-6e0df4.env
# output-file          ~/.opam/log/wamp-18-6e0df4.out
### output ###
# ocamlfind ocamldep -package bytes -package result -package uri -package ppx_deriving.std -package ppx_sexp_conv -modules src/wamp.ml > src/wamp.ml.depends
# ocamlfind ocamldep -package bytes -package result -package uri -package ppx_deriving.std -package ppx_sexp_conv -modules src/wamp.mli > src/wamp.mli.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -w -40 -package bytes -package result -package uri -package ppx_deriving.std -package ppx_sexp_conv -I src -I test -o src/wamp.cmi src/wamp.mli
# ocamlfind ocamlopt -c -g -bin-annot -safe-string -w -40 -package bytes -package result -package uri -package ppx_deriving.std -package ppx_sexp_conv -I src -I test -o src/wamp.cmx src/wamp.ml
# + ocamlfind ocamlopt -c -g -bin-annot -safe-string -w -40 -package bytes -package result -package uri -package ppx_deriving.std -package ppx_sexp_conv -I src -I test -o src/wamp.cmx src/wamp.ml
# File "src/wamp.ml", line 6, characters 5-16:
# Error: Unbound module Sexplib
# Hint: Did you mean Stdlib?
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'src/wamp.a' 'src/wamp.cmxs' 'src/wamp.cmxa' 'src/wamp.cma'
#      'src/wamp.cmx' 'src/wamp.cmi' 'src/wamp.mli']: exited with 10
```

**Comment by kit-ty-kate** [comment]
Only constraints on the listed versions were needed I think

**Comment by kit-ty-kate** [comment]
Looks good now. Thanks!

**Comment by avsm** [comment]
Thanks for the fixes and merge!

**Pull request merged**
