### PR TITLE
conf-r trial fix

### PR DESCRIPTION
**Pull request by UnixJunkie**
Don't merge this.
We might have to upgrade the bugfix version number of this package if the fix is correct.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
It's fixed after #13126. Thanks!

**Comment by kit-ty-kate** [comment]
oops I didn't see the `don't merge this` in the original message. Would you like me to revert it?

**Comment by kit-ty-kate** [comment]
Reverted. What was the original goal of this PR?

**Comment by UnixJunkie** [comment]
I will bump the version number of the incriminated package and include your fix.
Thanks!

**Comment by UnixJunkie** [comment]
original goal: apparently, the R command was not installed by the package.
While this package is supposed to install the R interpreter (command: R).

**Comment by kit-ty-kate** [comment]
@UnixJunkie it was, it's just that the opensuse image changed an broke the way the system was detected so no packages were actually installed. `conf-r` works as it is now.

**Pull request merged**
