### PR TITLE
added ocp-pack-split

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
It is OK in Travis, except that some download failed at some point, as often.

**Comment by yallop** [comment]
I've restarted the job.

**Comment by UnixJunkie** [comment]
It's all green now.

**Comment by UnixJunkie** [comment]
The package doesn't have a bug tracker and an open source code repository so I cannot correct
the camelus warnings.

**Comment by samoht** [comment]
Thanks! (I forgot I wrote that...)

**Pull request merged**
