### PR TITLE
Release of Esperanto (v0.0.5)

### PR DESCRIPTION
**Pull request by dinosaure**
- Support Cosmopolitan 3.1 (dinosaure/esperanto#43, @dinosaure)
- Fix the compilation of esperanto with setup-ocaml and GitHub CI (dinosaure/esperanto#44, @dinosaure)
- Extend the support of Esperanto to 4.13 (dinosaure/esperanto#45, @dinosaure)

### CODE REVIEW

**Comment by dinosaure** [comment]
- [ ] move the `dune-project` file to the root of the distribution
- [ ] see what happens between `opam.2.0` and `opam.2.1` about the sandboxing and how we tried to install `esperanto-cosmopolitan`

**Comment by dinosaure** [comment]
The error on MacOS seems unrelated. The linter is a bit restrictive: currently we have a `dune-project` file only for `esperanto-cosmopolitan`. `{x86_64,aarch64}-esperanto` don't use `dune` but due to the presence of the `dune-projet`, it seems that we should require `dune` according to the linter (which is not true).

**Comment by mseri** [comment]
So aarch64-esperanto can build on x86 linux but not on macos x86 or arm64, is that still correct?

**Comment by dinosaure** [comment]
Yes, we probably can build everything on any `x86_64` systems (like mac) but the distribution comes with several shell scripts which are used then to compile OCaml source code. I prefer to be restrictive/conservative on this topic (and trust only on a linux machine) instead of "accidentally" support something new and unexpected :+1:.

**Comment by mseri** [comment]
Thanks for the clarificAtion

**Pull request merged**
