### PR TITLE
2 packages from c-cube/ezcurl at 0.2

### PR DESCRIPTION
**Pull request by c-cube**
This pull-request concerns:
-`ezcurl.0.2`: Friendly wrapper around OCurl
-`ezcurl-lwt.0.2`: Friendly wrapper around OCurl, Lwt version

---
* Homepage: https://github.com/c-cube/ezcurl/
* Source repo: git+https://github.com/c-cube/ezcurl.git
* Bug tracker: https://github.com/c-cube/ezcurl/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by c-cube** [comment]
cc @zapashcanon

**Comment by zapashcanon** [comment]
Thanks for being so quick ! :)

**Comment by dinosaure** [comment]
The error seems unrelated to this package (it's about `cppo`).

**Comment by c-cube** [comment]
thank you!

**Pull request merged**
