### PR TITLE
Package ocamline.1.2

### PR DESCRIPTION
**Pull request by chrisnevers**
### `ocamline.1.2`
Command line interface for user input

---
* Homepage: https://github.com/chrisnevers/ocamline
* Source repo: git://github.com/chrisnevers/ocamline.git
* Bug tracker: https://github.com/chrisnevers/ocamline/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This version made all the packages depending on `ocamline` break:
```
# File "lib/repl.ml", line 11, characters 6-9:
# 11 |       ";" in
#            ^^^
# Error: This expression has type string but an expression was expected of type
#          unit
```
I just added a comment to fix their constraints to require `ocamline < 1.2`

**Comment by chrisnevers** [comment]
The `mincaml` thats breaking is no longer maintained or used. It now goes by `gobba`

**Comment by 0x0f0f0f** [comment]
#15765 should fix.

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
