### PR TITLE
+websocket.2.10

### PR DESCRIPTION
**Pull request by vbmithr**

### CODE REVIEW

**Comment by avsm** [comment]
@diml any luck with the async_ssl release? It's causing a lot of CI failures

**Comment by copy** [comment]
Supposedly this has been fixed in #10008, can the CI jobs be restarted?

**Comment by samoht** [comment]
@vbmithr could you rebase this PR please, now that the async_ssl package has been fixed? Thanks!

**Comment by vbmithr** [comment]
Done.

**Comment by samoht** [comment]
All green, thanks!

**Pull request merged**
