### PR TITLE
ocsigen-start.1.1.0: Update archive checksum

### PR DESCRIPTION
**Pull request by kit-ty-kate**
(just a test for the moment)
(alternative to #13424)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
@jrochel just changing the checksum seems to work ok

**Comment by kit-ty-kate** [comment]
ok, nevermind it only compiles on 4.07, sorry

**Comment by mseri** [comment]
Should we close this and remove ocsigen-start.1.1.0 as suggested in the other pr?

**Comment by jrochel** [comment]
https://github.com/ocaml/opam-repository/pull/13424

**Pull request closed without merging**
