### PR TITLE
LablGL 1.07

### PR DESCRIPTION
**Pull request by garrigue**
New version of LablGL for compatibility with OCaml 5.0.0.

### CODE REVIEW

**Comment by garrigue** [comment]
I see that compilation fails on architectures that do not have a native code compiler.
Is there a way in the opam file to make part of the compilation/installation dependent on its availability?

**Comment by raphael-proust** [comment]
@garrigue According to https://github.com/ocaml/opam-repository/pull/23376#issuecomment-1439950764 you can use

```
conflicts: ["ocaml-option-bytecode-only"]
```

to mark a whole package as needing ocamlopt

Or you can use `!ocaml:native` in your build rule filters.

**Comment by garrigue** [comment]
Ok, it is not exactly what I was asking for, but it was hidden in your answer.
By writing `[make "glutopt"] {ocaml:native}` , the package also install on bytecode-only architectures.
So the package itself looks fine.

There is still something strange: I see a huge number of spurious revdeps, i.e. packages that do not depend on lablgl but are tested by the CI. Any idea what this comes from ?

**Comment by mseri** [comment]
It is acutally due to lablgtk. If you run `opam list --depends-on lablgl --recursive --all --depopts` you will see the full list (thanks @kit-ty-kate)

**Comment by mseri** [comment]
Non of the failures depend on this. I have sent a PR to fix all the one that needed upper or lower bounds

**Pull request merged**
