### PR TITLE
fdkaac.0.3.2

### PR DESCRIPTION
**Pull request by toots**
This PR adds the recently-release `fdkaac.0.3.2`, with support for version `2.0.x` of the upstream library.

### CODE REVIEW

**Comment by toots** [comment]
CI failures are mostly due to missing depexts. `fdk-aac` is not usually shipped with main distribution but available through well-known 3rd party sources.

**Comment by kit-ty-kate** [comment]
It's ok I guess. Just in case, could you check that this warning doesn't cause any problem?
```
Processing  7/8: [fdkaac: dune build]
+ /home/opam/.opam/4.10/bin/dune "build" "-p" "fdkaac" "-j" "72" "@install" (CWD=/home/opam/.opam/4.10/.opam-switch/build/fdkaac.0.3.2)
-       ocamlc src/fdkaac_stubs.o
- In file included from /home/opam/.opam/4.10/lib/ocaml/caml/custom.h:23:0,
-                  from fdkaac_stubs.c:25:
- fdkaac_stubs.c: In function 'ocaml_fdkaac_encode':
- /home/opam/.opam/4.10/lib/ocaml/caml/mlvalues.h:265:23: warning: passing argument 1 of 'memcpy' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
-  #define String_val(x) ((const char *) Bp_val(x))
-                        ^
- fdkaac_stubs.c:234:10: note: in expansion of macro 'String_val'
-    memcpy(String_val(ret), outbuf, outArgs.numOutBytes);
-           ^~~~~~~~~~
- In file included from /usr/include/features.h:424:0,
-                  from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
-                  from /usr/include/stdint.h:26,
-                  from /usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h:9,
-                  from /home/opam/.opam/4.10/lib/ocaml/caml/config.h:59,
-                  from /home/opam/.opam/4.10/lib/ocaml/caml/mlvalues.h:22,
-                  from /home/opam/.opam/4.10/lib/ocaml/caml/custom.h:23,
-                  from fdkaac_stubs.c:25:
- /usr/include/x86_64-linux-gnu/bits/string_fortified.h:31:1: note: expected 'void * restrict' but argument is of type 'const char *'
-  __NTH (memcpy (void *__restrict __dest, const void *__restrict __src,
-  ^
- In file included from /home/opam/.opam/4.10/lib/ocaml/caml/custom.h:23:0,
-                  from fdkaac_stubs.c:25:
- fdkaac_stubs.c: In function 'ocaml_fdkaac_flush':
- /home/opam/.opam/4.10/lib/ocaml/caml/mlvalues.h:265:23: warning: passing argument 1 of 'memcpy' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
-  #define String_val(x) ((const char *) Bp_val(x))
-                        ^
- fdkaac_stubs.c:272:10: note: in expansion of macro 'String_val'
-    memcpy(String_val(ret), outbuf, outArgs.numOutBytes);
-           ^~~~~~~~~~
- In file included from /usr/include/features.h:424:0,
-                  from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
-                  from /usr/include/stdint.h:26,
-                  from /usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h:9,
-                  from /home/opam/.opam/4.10/lib/ocaml/caml/config.h:59,
-                  from /home/opam/.opam/4.10/lib/ocaml/caml/mlvalues.h:22,
-                  from /home/opam/.opam/4.10/lib/ocaml/caml/custom.h:23,
-                  from fdkaac_stubs.c:25:
- /usr/include/x86_64-linux-gnu/bits/string_fortified.h:31:1: note: expected 'void * restrict' but argument is of type 'const char *'
-  __NTH (memcpy (void *__restrict __dest, const void *__restrict __src,
-  ^
```
If it's properly tagged on the OCaml side as a `bytes` it should be fine but I'd rather be sure before merging this in case this hasn't been tested with OCaml 4.10

**Comment by toots** [comment]
Thanks for checking on that! In this case, the ML value is allocated in the C callback via `caml_alloc_string`, filled up via `memcpy` and returned as `string` so I believe this should be safe. I have fixed the warning upstream.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
