### PR TITLE
Package prbnmcn-gnuplot.0.0.1

### PR DESCRIPTION
**Pull request by igarnier**
### `prbnmcn-gnuplot.0.0.1`
Declarative generation of gnuplot scripts
Declarative generation of gnuplot scripts

---
* Homepage: http://github.com/igarnier/prbnmcn-gnuplot
* Source repo: git+https://github.com/igarnier/prbnmcn-gnuplot
* Bug tracker: http://github.com/igarnier/prbnmcn-gnuplot

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by igarnier** [comment]
I guess I need to have stricter version constraints on gnuplot.

**Comment by kit-ty-kate** [comment]
This is still failing on very old gnuplot (4.6.2):
```
#=== ERROR while compiling prbnmcn-gnuplot.0.0.1 ==============================#
# context              2.1.0 | linux/x86_64 | ocaml-base-compiler.4.12.0 | pinned(https://github.com/igarnier/prbnmcn-gnuplot/archive/0.0.1.tar.gz)
# path                 ~/.opam/4.12/.opam-switch/build/prbnmcn-gnuplot.0.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p prbnmcn-gnuplot -j 127 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/prbnmcn-gnuplot-17-f915c5.env
# output-file          ~/.opam/log/prbnmcn-gnuplot-17-f915c5.out
### output ###
#      example alias test/runtest (exit 1)
# (cd _build/default/test && ./example.exe)
# 
# $name_0 << EOD
# ^
# "/opam-tmp/build1a7e42.dune/gnuplote307ed.gp", line 5: invalid command
# 
# run_script: call to gnuplot failed, exiting
# gnuplot_test alias test/runtest (exit 1)
# (cd _build/default/test && ./gnuplot_test.exe)
# 
# $name_0 << EOD
# ^
# "/opam-tmp/build1a7e42.dune/gnuplot16f403.gp", line 6: invalid command
# 
# run_script: call to gnuplot failed, exiting
```
I'm guessing that's fine and they can be ignored?

**Comment by igarnier** [comment]
Yes, these errors can be ignored.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
