### PR TITLE
10 packages from savonet/liquidsoap

### PR DESCRIPTION
**Pull request by toots**
This pull-request concerns:
- `liquidsoap.2.2.0`: Swiss-army knife for multimedia streaming
- `liquidsoap-core.2.2.0`: Liquidsoap core library and binary
- `liquidsoap-js.2.2.0`: Liquidsoap language - javascript wrapper
- `liquidsoap-lang.2.2.0`: Liquidsoap language library
- `liquidsoap-libs.2.2.0~1`: Liquidosap standard library
- `liquidsoap-libs-extra.2.2.0~1`: Liquidosap standard library -- extra functionalities
- `liquidsoap-mode.2.2.0`: Liquidosap emacs mode
- `prometheus-liquidsoap.2`: Virtual package installing liquidsoap dependencies for prometheus optional features
- `sdl-liquidsoap.3`: Virtual package installing liquidsoap dependencies for SDL optional features
- `tls-liquidsoap.1`: Virtual package install liquidosap dependencies for TLS optional features

---
* Homepage: https://github.com/savonet/liquidsoap
* Source repo: git+https://github.com/savonet/liquidsoap.git
* Bug tracker: https://github.com/savonet/liquidsoap/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by avsm** [comment]
Looks like tsdl-ttf might need an upper bound on ctypes following #23357; /cc @yallop @emillion 

```
#=== ERROR while compiling tsdl-ttf.0.2 =======================================#
# context              2.2.0~alpha2~dev | linux/x86_64 | ocaml-base-compiler.4.08.1 | file:///home/opam/opam-repository
# path                 ~/.opam/4.08/.opam-switch/build/tsdl-ttf.0.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build ocaml setup.ml -build
# exit-code            1
# env-file             ~/.opam/log/tsdl-ttf-7-239f6d.env
# output-file          ~/.opam/log/tsdl-ttf-7-239f6d.out
### output ###
# File "./setup.ml", line 1779, characters 22-40:
# 1779 |         let compare = Pervasives.compare
#                              ^^^^^^^^^^^^^^^^^^
# Alert deprecated: module Stdlib.Pervasives
# Use Stdlib instead.
# 
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
# File "setup.ml", line 3471, characters 16-34:
# Alert deprecated: module Stdlib.Pervasives
# Use Stdlib instead.
# 
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
# /home/opam/.opam/4.08/bin/ocamlopt.opt unix.cmxa -I /home/opam/.opam/4.08/lib/ocamlbuild /home/opam/.opam/4.08/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/opam/.opam/4.08/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/opam/.opam/4.08/bin/ocamlfind ocamldep -package ctypes -package result -package tsdl -modules src/tsdl_ttf.mli > src/tsdl_ttf.mli.depends
# /home/opam/.opam/4.08/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ctypes -package result -package tsdl -I src -o src/tsdl_ttf.cmi src/tsdl_ttf.mli
# /home/opam/.opam/4.08/bin/ocamlfind ocamldep -package ctypes -package result -package tsdl -modules src/tsdl_ttf.ml > src/tsdl_ttf.ml.depends
# /home/opam/.opam/4.08/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ctypes -package result -package tsdl -I src -o src/tsdl_ttf.cmo src/tsdl_ttf.ml
# /home/opam/.opam/4.08/bin/ocamlfind ocamlc -a -cclib -lSDL2_ttf -I src src/tsdl_ttf.cmo -o src/tsdl_ttf.cma
# /home/opam/.opam/4.08/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -package ctypes -package result -package tsdl -I src -o src/tsdl_ttf.cmx src/tsdl_ttf.ml
# /home/opam/.opam/4.08/bin/ocamlfind ocamlopt -a -cclib -lSDL2_ttf -I src src/tsdl_ttf.cmx -o src/tsdl_ttf.cmxa
# /home/opam/.opam/4.08/bin/ocamlfind ocamlopt -shared -I src src/tsdl_ttf.cmxa src/tsdl_ttf.cmx -o src/tsdl_ttf.cmxs
# /home/opam/.opam/4.08/bin/ocamlfind ocamldep -package ctypes -package result -package threads -package tsdl -modules test/show_string.ml > test/show_string.ml.depends
# /home/opam/.opam/4.08/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package ctypes -package result -package threads -package tsdl -thread -I test -I src -o test/show_string.cmo test/show_string.ml
# /home/opam/.opam/4.08/bin/ocamlfind ocamlc -g -linkpkg -package ctypes -package result -package threads -package tsdl -thread -I src -I test src/tsdl_ttf.cma test/show_string.cmo -o test/show_string.byte
# + /home/opam/.opam/4.08/bin/ocamlfind ocamlc -g -linkpkg -package ctypes -package result -package threads -package tsdl -thread -I src -I test src/tsdl_ttf.cma test/show_string.cmo -o test/show_string.byte
# File "_none_", line 1:
# Error: Files /home/opam/.opam/4.08/lib/tsdl/tsdl.cma(Tsdl)
#        and /home/opam/.opam/4.08/lib/ctypes/ctypes-foreign-threaded.cma(Foreign)
#        make inconsistent assumptions over interface Foreign
# Command exited with code 2.
# E: Failure("Command ''/home/opam/.opam/4.08/bin/ocamlbuild' src/tsdl_ttf.cma src/tsdl_ttf.cmxa src/tsdl_ttf.a src/tsdl_ttf.cmxs test/show_string.byte -tag debug' terminated with error code 10")
```

**Comment by toots** [comment]
Thanks @avsm ! Is there anything we can do on our end?

**Comment by avsm** [comment]
Thanks for bearing with me; just had to triage the rest of the errors. All merged now and should be available soon on opam.ocaml.org!

**Comment by toots** [comment]
Awesome thank you!

**Comment by codeofdusk** [comment]
Thanks @avsm! I don't see the new packages either [online](https://opam.ocaml.org/packages/liquidsoap/) or when running `opam update` locally.

**Comment by kit-ty-kate** [comment]
@codeofdusk sadly the current infrastructure takes a few hours to regenerate the repository. It should be available in an hour unless something breaks.

**Pull request merged**
