### PR TITLE
lz4.1.1.1 - via opam-publish

### PR DESCRIPTION
**Pull request by yallop**
Bindings for LZ4, a very fast lossless compression algorithm

---
* Homepage: https://github.com/whitequark/ocaml-lz4
* Source repo: git://github.com/whitequark/ocaml-lz4.git
* Bug tracker: https://github.com/whitequark/ocaml-lz4/issues

---
### opam-lint failures
- **WARNING** 97 long description unspecified

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by whitequark** [comment]
This needs a version bump in the repo, too

**Comment by yallop** [comment]
Bumped (https://github.com/whitequark/ocaml-lz4/commit/eb542f3d)

**Comment by whitequark** [comment]
Yep--looks good to me

**Comment by yallop** [comment]
The build fails because `liblz4-dev` is not available on Ubuntu 12.04.

**Pull request merged**
