### PR TITLE
Constrain opasswd to ctypes versions below 0.6.0

### PR DESCRIPTION
**Pull request by yallop**
See https://github.com/xapi-project/ocaml-opasswd/pull/5

/cc @simonjbeaumont.  A new release of opasswd would be appreciated!

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
I'm sure we can tag a new version. Presumably the new one wouldn't need the upper bound on ctypes?

**Comment by yallop** [comment]
@simonjbeaumont: yes, the current `HEAD` of ocaml-opasswd should work with both ctypes 0.6.0 and with previous versions.

**Comment by simonjbeaumont** [comment]
I'll make a note to sort that out. Just took a look and it's creaking a bit. It's still using obuild so we might take the opportunity to wean ourselves off that.

**Comment by simonjbeaumont** [comment]
https://github.com/ocaml/opam-repository/pull/6673

**Comment by dsheets** [comment]
It would be nice to have the metadata for 0.9.3 made lint-clean but not necessary. This adds a constraint and passes Travis CI so merging.

**Pull request merged**
