### PR TITLE
arakoon 1.9.15

### PR DESCRIPTION
**Pull request by toolslive**

### CODE REVIEW

**Comment by toolslive** [comment]
This one currently depends on `core.114.35+03` which is not (yet) available.

**Comment by avsm** [comment]
This one needs to wait until #8792 is merged to get the latest core

**Comment by avsm** [comment]
@toolslive is the version of core now in opam-repository sufficient? (v0.9.0)

**Comment by toolslive** [comment]
dunno, can't verify as v0.9.0 doesn't install for me:

```
#=== ERROR while installing core.v0.9.0 =======================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p core -j 4
# path         /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/build/core.v0.9.0
# compiler     4.04.1
# exit-code    1
# env-file     /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/build/core.v0.9.0/core-3567-e7966f.env
# stdout-file  /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/build/core.v0.9.0/core-3567-e7966f.out
# stderr-file  /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/build/core.v0.9.0/core-3567-e7966f.err
### stderr ###
# Warning 55: Cannot inline: Function information unavailable
# [...]
#       ocamlc src/core__Lock_file.{cmi,cmti}
#       ocamlc src/core__Core_time.{cmi,cmti}
#       ocamlc src/core__Time_common.{cmi,cmo,cmt}
#       ocamlc src/core__Time_ns_intf.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/base -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/base/caml -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/base/shadow_stdlib -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/bin_prot -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/bin_prot/shape -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/core_kernel -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/core_kernel/base_for_tests -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/fieldslib -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/jane-street-headers -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/num -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ocaml -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ocaml/threads -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ppx_assert/runtime-lib -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ppx_bench/runtime-lib -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ppx_compare/runtime-lib -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ppx_expect/collector -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ppx_expect/common -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ppx_expect/config -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ppx_hash/runtime-lib -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ppx_inline_test/config -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/ppx_inline_test/runtime-lib -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/sexplib -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/sexplib/unix -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/spawn -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/stdio -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/typerep -I /home/romain/workspace/ROOT/OPAM_ROOT/4.04.1/lib/variantslib -no-alias-deps -I src -open Core__ -o src/core__Time_ns_intf.cmo -c -impl src/time_ns_intf.pp.ml)
# File "src/time_ns_intf.ml", line 5, characters 10-32:
# Error: Unbound module type Immediate_option.Int63
# 
# Waiting for 2 jobs to finish.

```

**Comment by avsm** [comment]
hm cannot repro the above failure with `docker run ocaml/opam:alpine_ocaml-4.04.1 sh -c "git -C /home/opam/opam-repository pull && opam update && opam depext -uivyj4 core"` -- any idea how your setup might be different? cc @diml

**Comment by toolslive** [comment]
Unfortunately, the opam installed package situation is not a state function, but also depends on how you got there.

Anyway, I tried from a clean slate in a docker container, and the combination of versions of packages doesn't really compile (anymore) (`Error: Unbound module Core.Time_internal`). 

I suggest we abandon this pull request and I'll prepare one for Arakoon 1.9.17 which uses more recent versions of the dependencies, like  Lwt.3.0.0, and has more chance of success.

**Comment by avsm** [comment]
closed in favour of #9261

**Comment by diml** [comment]
Possibly the build error was due to `base-native-int63`. I though I tested all packages with it, but maybe not.

**Pull request closed without merging**
