### PR TITLE
3 packages from c-cube/ocaml-containers at 3.4

### PR DESCRIPTION
**Pull request by c-cube**
This pull-request concerns:
-`containers.3.4`: A modular, clean and powerful extension of the OCaml standard library
-`containers-data.3.4`: A set of advanced datatypes for containers
-`containers-thread.3.4`: An extension of containers for threading

---
* Homepage: https://github.com/c-cube/ocaml-containers/
* Source repo: git+https://github.com/c-cube/ocaml-containers.git
* Bug tracker: https://github.com/c-cube/ocaml-containers/issues/

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by c-cube** [comment]
It feels like the CI is red 100% of the time…

**Comment by kit-ty-kate** [comment]
The `license` field is missing. Could you add it to those packages? The rest of the failures can be ignored.

**Comment by c-cube** [comment]
Ok I will. `opam lint` is still green, of course.

**Comment by kit-ty-kate** [comment]
The tests do not pass on 32bit architectures:
```
#=== ERROR while compiling containers.3.4 =====================================#
# context              2.1.0~beta4 | linux/arm32 | ocaml-base-compiler.4.12.0 | pinned(https://github.com/c-cube/ocaml-containers/archive/v3.4.tar.gz)
# path                 ~/.opam/4.12/.opam-switch/build/containers.3.4
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p containers -j 31
# exit-code            1
# env-file             ~/.opam/log/containers-23-8eb1b2.env
# output-file          ~/.opam/log/containers-23-8eb1b2.out
### output ###
# check_labelled_mods alias src/core/tests/runtest
# labelled modules are consistent ✔
# Error: exception Out of memory
# Raised by primitive operation at Stdune__digest.generic in file
#   "src/stdune/digest.ml", line 35, characters 23-59
# Called from Dune_util__report_error.report in file
#   "src/dune_util/report_error.ml", line 87, characters 15-33
# Called from Fiber.Execution_context.forward_exn_with_bt in file
#   "src/fiber/fiber.ml", line 136, characters 10-17
# Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
#   (inlined), line 36, characters 27-56
# Called from Stdune__exn_with_backtrace.reraise in file
#   "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
# Called from Fiber.Execution_context.forward_error in file
#   "src/fiber/fiber.ml", line 144, characters 4-29
# Called from Fiber.Ivar.fill in file "src/fiber/fiber.ml", line 469,
#   characters 6-24
# Called from Fiber.Execution_context.safe_run_k in file "src/fiber/fiber.ml",
#   line 129, characters 18-21
# Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
#   (inlined), line 36, characters 27-56
# Called from Stdune__exn_with_backtrace.reraise in file
#   "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
# Called from Fiber.Execution_context.forward_error in file
#   "src/fiber/fiber.ml", line 144, characters 4-29
# Called from Fiber.Ivar.fill in file "src/fiber/fiber.ml", line 469,
#   characters 6-24
# Called from Fiber.Execution_context.safe_run_k in file "src/fiber/fiber.ml",
#   line 129, characters 18-21
# Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
#   (inlined), line 36, characters 27-56
# Called from Stdune__exn_with_backtrace.reraise in file
#   "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
# Called from Fiber.Execution_context.forward_error in file
#   "src/fiber/fiber.ml", line 144, characters 4-29
# Called from Fiber.Ivar.fill in file "src/fiber/fiber.ml", line 469,
#   characters 6-24
# Called from Fiber.Execution_context.safe_run_k in file "src/fiber/fiber.ml",
#   line 129, characters 18-21
# Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
#   (inlined), line 36, characters 27-56
# Called from Stdune__exn_with_backtrace.reraise in file
#   "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
# Called from Fiber.Execution_context.forward_error in file
#   "src/fiber/fiber.ml", line 144, characters 4-29
# Called from Fiber.Ivar.fill in file "src/fiber/fiber.ml", line 469,
#   characters 6-24
# Called from Fiber.Execution_context.safe_run_k in file "src/fiber/fiber.ml",
#   line 129, characters 18-21
# Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
#   (inlined), line 36, characters 27-56
# Called from Stdune__exn_with_backtrace.reraise in file
#   "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
# Called from Fiber.Execution_context.forward_error in file
#   "src/fiber/fiber.ml", line 144, characters 4-29
# Called from Fiber.Execution_context.safe_run_k in file "src/fiber/fiber.ml",
#   line 129, characters 18-21
# Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
#   (inlined), line 36, characters 27-56
# Called from Stdune__exn_with_backtrace.reraise in file
#   "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
# Called from Fiber.Execution_context.forward_error in file
#   "src/fiber/fiber.ml", line 144, characters 4-29
# Called from Fiber.Execution_context.safe_run_k in file "src/fiber/fiber.ml",
#   line 129, characters 18-21
# Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
#   (inlined), line 36, characters 27-56
# Called from Stdune__exn_with_backtrace.reraise in file
#   "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
# Called from Fiber.Execution_context.forward_error in file
#   "src/fiber/fiber.ml", line 144, characters 4-29
# Called from Stdlib__queue.iter.iter in file "queue.ml", line 121, characters
#   6-15
# Called from Fiber.run.(fun).loop in file "src/fiber/fiber.ml", line 616,
#   characters 10-33
# Called from Stdune__exn.protectx in file "src/stdune/exn.ml", line 12,
#   characters 8-11
# Re-raised at Stdune__exn.protectx in file "src/stdune/exn.ml", line 18,
#   characters 4-11
# Called from Dune_engine__scheduler.Run_once.run in file
#   "src/dune_engine/scheduler.ml", line 751, characters 10-50
# Re-raised at Stdune__exn.raise_with_backtrace in file "src/stdune/exn.ml"
#   (inlined), line 36, characters 27-56
# Called from Stdune__exn_with_backtrace.reraise in file
#   "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
# Called from Main.run_build_command in file "bin/main.ml", line 17, characters
#   4-29
# Called from Cmdliner_term.app.(fun) in file
#   "vendor/cmdliner/src/cmdliner_term.ml", line 25, characters 19-24
# Called from Cmdliner.Term.run in file "vendor/cmdliner/src/cmdliner.ml", line
#   117, characters 32-39
# Called from Cmdliner.Term.term_eval in file
#   "vendor/cmdliner/src/cmdliner.ml", line 147, characters 18-36
# Called from Cmdliner.Term.eval_choice in file
#   "vendor/cmdliner/src/cmdliner.ml", line 265, characters 22-48
# Called from Main in file "bin/main.ml", line 262, characters 10-51
# 
# I must not crash.  Uncertainty is the mind-killer. Exceptions are the
# little-death that brings total obliteration.  I will fully express my cases. 
# Execution will pass over me and through me.  And when it has gone past, I
# will unwind the stack along its path.  Where the cases are handled there will
# be nothing.  Only I will remain.
```
I'll disable them for the time being, but could you have a look into it?

**Comment by kit-ty-kate** [comment]
There was another failure on 32bit in the tests of `containers-data` this time:
```
#=== ERROR while compiling containers-data.3.4 ================================#
# context              2.1.0~beta4 | linux/arm32 | ocaml-base-compiler.4.12.0 | pinned(https://github.com/c-cube/ocaml-containers/archive/v3.4.tar.gz)
# path                 ~/.opam/4.12/.opam-switch/build/containers-data.3.4
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p containers-data -j 31
# exit-code            1
# env-file             ~/.opam/log/containers-data-24-500fb1.env
# output-file          ~/.opam/log/containers-data-24-500fb1.out
### output ###
#   mdx_runner README.md.corrected
# sh: 1: ocaml-mdx: not found
# warning: ocaml-mdx exited with code 127
# run_qtest_data alias qtest/runtest (exit 1)
# (cd _build/default/qtest && ./run_qtest_data.exe)
#  seed: 365591617
# Running tests...l:15                                        l:15 *                                      l:16                                        l:16 *                                      l:28                                        l:28 *                                      l:71                                        l:71 *                                      l:86                                        l:86 *                                      l:99                                        l:99 *                                      l:100                                       l:100 *                                     l:101                                       l:101 *                                     l:41                                        l:41 *                                      l:293                                       l:293 *                                    l:296                                      l:296 *                                    l:299                                      l:299 *                                    l:345                                      l:345 *                                    l:349                                      l:349 *                                    l:377                                      l:377 *                                    l:393                                      l:393 *                                    l:498                                      l:498 *                                    l:535                                      l:535 *                                    l:547                                      l:547 *                                    l:131                                        l:131 *                                      l:132                                        l:132 *                                      l:133                                        l:133 *                                      l:134                                        l:134 *                                      l:135                                        l:135 *                                      l:137                                        l:137 *                                      l:138                                        l:138 *                                      l:139                                        l:139 *                                      l:140                                        l:140 *                                      l:311                                        l:311 *                                      l:312                                        l:312 *                                      l:313                                        l:313 *                                      l:314                                        l:314 *                                      l:315                                        l:315 *                                      l:364                                        l:364 *                                      l:365                                        l:365 *                                      l:366                                        l:366 *                                      l:367                                        l:367 *                                      l:371                                        l:371 *                                      l:400                                        l:400 *                                      l:421                                        l:421 *                                      l:438                                        l:438 *                                      l:516                                        l:516 *                                      l:536                                        l:536 *                                      l:673                                        l:673 *                                      l:675                                        l:675 *                                      l:677                                        l:677 *                                      l:679                                        l:679 *                                      l:685                                        l:685 *                                      l:699                                        l:699 *                                      l:714                                        l:714 *                                      l:719                                        l:719 *                                      l:724                                        l:724 *                                      l:729                                        l:729 *                                      ple_queue.ml:56                                 ple_queue.ml:56 *                               ple_queue.ml:72                                 ple_queue.ml:72 *                               ple_queue.ml:74                                 ple_queue.ml:74 *                               ple_queue.ml:82                                 ple_queue.ml:82 *                               ple_queue.ml:87                                 ple_queue.ml:87 *                               ple_queue.ml:119                                ple_queue.ml:119 *                              ple_queue.ml:123                                ple_queue.ml:123 *                              ple_queue.ml:168                                ple_queue.ml:168 *                              ple_queue.ml:178                                ple_queue.ml:178 *                              l:234                                  l:234 *                                l:245                                  l:245 *                                l:282                                  l:282 *                                l:291                                  l:291 *                                l:300                                  l:300 *                                l:310                                  l:310 *                                l:340                                  l:340 *                                l:351                                  l:351 *                                l:369                                  l:369 *                                l:389                                  l:389 *                                l:406                                  l:406 *                                l:422                                  l:422 *                                l:439                                  l:439 *                                l:454                                  l:454 *                                l:480                                  l:480 *                                l:508                                  l:508 *                                l:525                                  l:525 *                                l:544                                  l:544 *                                l:566                                  l:566 *                                l:584                                  l:584 *                                l:604                                  l:604 *                                l:625                                  l:625 *                                l:810                                  l:810 *                                l:819                                  l:819 *                                l:850                                  l:850 *                                l:851                                  l:851 *                                l:852                                  l:852 *                                l:853                                  l:853 *                                l:854                                  l:854 *                                l:855                                  l:855 *                                l:58                                          l:58 *                                        l:66                                          l:66 *                                        l:92                                          l:92 *                                        l:93                                          l:93 *                                        l:97                                          l:97 *                                        l:125                                         l:125 *                                       l:138                                         l:138 *                                       l:163                                         l:163 *                                      l:171                                        l:171 *                                      l:233                                        l:233 *                                      l:241                                        l:241 *                                      l:243                                        l:243 *                                      l:250                                        l:250 *                                      l:267                                        l:267 *                                      l:278                                        l:278 *                                      l:287                                        l:287 *                                      l:292                                        l:292 *                                      l:304                                        l:304 *                                      l:334                                        l:334 *                                      l:335                                        l:335 *                                      l:336                                        l:336 *                                      l:340                                        l:340 *                                      l:357                                        l:357 *                                      l:360                                        l:360 *                                      l:396                                        l:396 *                                      l:400                                        l:400 *                                      l:419                                        l:419 *                                      l:420                                        l:420 *                                      l:421                                        l:421 *                                      l:422                                        l:422 *                                      l:426                                        l:426 *                                      l:450                                        l:450 *                                      l:470                                        l:470 *                                      l:485                                        l:485 *                                      l:486                                        l:486 *                                      l:487                                        l:487 *                                      l:491                                        l:491 *                                      l:501                                        l:501 *                                      l:502                                        l:502 *                                      l:503                                        l:503 *                                      l:504                                        l:504 *                                      l:515                                        l:515 *                                      l:524                                        l:524 *                                      l:541                                        l:541 *                                      l:558                                        l:558 *                                      l:560                                        l:560 *                                      l:565                                        l:565 *                                      l:600                                        l:600 *                                      l:601                                        l:601 *                                      l:623                                        l:623 *                                      l:226                          l:226 *                        l:237                          l:237 *                        l:248                          l:248 *                        l:271                          l:271 *                        l:278                          l:278 *                        l:373                          l:373 *                        l:417                          l:417 *                        l:429                          l:429 *                        l:440                          l:440 *                        l:563                          l:563 *                        l:589                          l:589 *                        l:612                          l:612 *                        l:622                          l:622 *                        l:103                            l:103 *                          l:105                            l:105 *                          l:106                            l:106 *                          l:160                            l:160 *                          l:165                                    l:165 *                                  l:193                                    l:193 *                                  l:263                                   l:263 *                                 l:265                                   l:265 *                                 l:267                                   l:267 *                                 l:17                                      l:17 *                                    l:57                                      l:57 *                                    l:72                                      l:72 *                                    l:97                                      l:97 *                                    l:132                                     l:132 *                                   l:159                                     l:159 *                                   l:12                                      l:12 *                                    ap.ml:7                                       ap.ml:7 *                                     l:33                                   l:33 *                                 l:52                                   l:52 *                                 l:53                                   l:53 *                                 l:72                                   l:72 *                                 l:93                                   l:93 *                                 l:114                                  l:114 *                                l:131                                  l:131 *                                l:141                                  l:141 *                                l:70                                      l:70 *                                    l:92                                      l:92 *                                    l:101                                     l:101 *                                   l:104                                     l:104 *                                   l:105                                     l:105 *                                   l:106                                     l:106 *                                   l:110                                     l:110 *                                   l:111                                     l:111 *                                   l:112                                     l:112 *                                   l:113                                     l:113 *                                   l:150                                     l:150 *                                   l:180                                     l:180 *                                   l:191                                     l:191 *                                   l:234                                     l:234 *                                   l:252                                     l:252 *                                   l:270                                     l:270 *                                   l:291                                     l:291 *                                 l:356                                   l:356 *                                 l:368                                   l:368 *                                 l:370                                   l:370 *                                 l:376                                   l:376 *                                 l:383                                   l:383 *                                 l:390                                   l:390 *                                 l:397                                   l:397 *                                 l:412                                   l:412 *                                 l:418                                   l:418 *                                 l:452                                   l:452 *                                 l:459                                   l:459 *                                 l:465                                   l:465 *                                 l:498                                   l:498 *                                 l:516                                   l:516 *                                 l:569                                   l:569 *                                 l:575                                   l:575 *                                 l:581                                   l:581 *                                 l:589                                   l:589 *                                 l:608                                   l:608 *                                 l:616                                   l:616 *                                 l:618                                   l:618 *                                 l:623                                   l:623 *                                 l:661                                   l:661 *                                 l:666                                   l:666 *                                 l:687                                   l:687 *                                 l:694                                   l:694 *                                 l:704                                   l:704 *                                 l:730                                   l:730 *                                 l:880                                   l:880 *                                 l:884                                   l:884 *                                 l:889                                   l:889 *                                 l:896                                   l:896 *                                 l:903                                   l:903 *                                 l:910                                   l:910 *                                 l:918                                   l:918 *                                 mutArray.ml:33                             mutArray.ml:33 *                           mutArray.ml:34                             mutArray.ml:34 *                           mutArray.ml:49                          mutArray.ml:49 *                        mutArray.ml:50                          mutArray.ml:50 *                        mutArray.ml:51                          mutArray.ml:51 *                        mutArray.ml:52                          mutArray.ml:52 *                        mutArray.ml:71                           mutArray.ml:71 *                         mutArray.ml:83                         mutArray.ml:83 *                       mutArray.ml:84                         mutArray.ml:84 *                       mutArray.ml:85                         mutArray.ml:85 *                       mutArray.ml:86                         mutArray.ml:86 *                       mutArray.ml:96                          mutArray.ml:96 *                        mutArray.ml:97                          mutArray.ml:97 *                        mutArray.ml:98                          mutArray.ml:98 *                        mutArray.ml:99                          mutArray.ml:99 *                        mutArray.ml:100                         mutArray.ml:100 *                       mutArray.ml:104                               mutArray.ml:104 *                             mutArray.ml:105                               mutArray.ml:105 *                             mutArray.ml:109                               mutArray.ml:109 *                             mutArray.ml:110                               mutArray.ml:110 *                             mutArray.ml:132                               mutArray.ml:132 *                             mutArray.ml:155                               mutArray.ml:155 *                             l:7                                        l:7 *                                      l:186                                 l:186 *                               l:187                                 l:187 *                               l:188                                 l:188 *                               l:189                                 l:189 *                               l:190                                 l:190 *                               l:191                                 l:191 *                               l:192                                 l:192 *                               l:196                                 l:196 *                               l:368                                 l:368 *                               l:376                                 l:376 *                               l:377                                 l:377 *                               l:405                                 l:405 *                               l:489                                 l:489 *                               l:499                                 l:499 *                               l:573                                 l:573 *                               l:604                                 l:604 *                               l:643                                 l:643 *                               l:674                                 l:674 *                               l:718                                 l:718 *                               l:727                                 l:727 *                               l:728                                 l:728 *                               l:759                                 l:759 *                               l:127                                  l:127 *                                l:140                                  l:140 *                                l:141                                  l:141 *                                l:154                                  l:154 *                                l:170                                  l:170 *                                l:184                                  l:184 *                                l:295                                    l:295 *                                  l:347                                    l:347 *                                  l:354                                    l:354 *                                  l:496                                    l:496 *                                  l:144                                  l:144 *                                l:150                                  l:150 *                                l:151                                  l:151 *                                l:186                                  l:186 *                                l:246                                  l:246 *                                l:254                                  l:254 *                                l:310                                  l:310 *                                l:321                                  l:321 *                                l:333                                  l:333 *                                l:347                                  l:347 *                                l:378                                  l:378 *                                l:387                                  l:387 *                                l:388                                  l:388 *                                l:38                                    l:38 *                                  l:72                                    l:72 *                                  l:89                                    l:89 *                                  l:94                                    l:94 *                                  l:119                                   l:119 *                                 l:125                                   l:125 *                                 l:139                                   l:139 *                                 l:154                                   l:154 *                                 l:167                                   l:167 *                                 l:186                                   l:186 *                                 l:196                                   l:196 *                                 l:244                                   l:244 *                                 l:282                                   l:282 *                                 l:291                                   l:291 *                                 l:302                                   l:302 *                                 l:311                                   l:311 *                                 l:322                                   l:322 *                                 l:346                                   l:346 *                                 l:357                                   l:357 *                                 l:362                                   l:362 *                                 l:375                                   l:375 *                                 l:400                                   l:400 *                                 l:418                                   l:418 *                                 l:439                                   l:439 *                                 l:444                                   l:444 *                                 l:461                                   l:461 *                                 l:471                                   l:471 *                                 l:485                                   l:485 *                                 l:499                                   l:499 *                                 l:500                                   l:500 *                                 l:501                                   l:501 *                                 l:510                                   l:510 *                                 l:511                                   l:511 *                                 l:512                                   l:512 *                                 l:513                                   l:513 *                                 l:36                                     l:36 *                                   l:59                                     l:59 *                                   l:125                                    l:125 *                                  l:126                                    l:126 *                                  l:130                                    l:130 *                                  l:155                                    l:155 *                                  l:156                                    l:156 *                                  l:160                                    l:160 *                                  l:207                                    l:207 *                                  l:208                                    l:208 *                                  l:209                                    l:209 *                                  l:210                                    l:210 *                                  l:219                                    l:219 *                                  ove_back>../src/data/CCDeque.ml:251                         ove_back>../src/data/CCDeque.ml:251 *                       ove_front>../src/data/CCDeque.ml:257                        ove_front>../src/data/CCDeque.ml:257 *                      l:289                        l:289 *                      l:290                        l:290 *                      l:293                        l:293 *                      l:298                        l:298 *                      l:330                         l:330 *                       l:331                         l:331 *                       l:334                         l:334 *                       l:339                         l:339 *                       l:361                                    l:361 *                                  l:365                                    l:365 *                                  l:376                                    l:376 *                                  l:398                                    l:398 *                                  l:399                                    l:399 *                                  l:405                                    l:405 *                                  l:413                                    l:413 *                                  l:425                                    l:425 *                                  l:440                                    l:440 *                                  l:450                                    l:450 *                                  l:550                                    l:550 *                                  l:556                                    l:556 *                                  l:562                                    l:562 *                                  l:574                                    l:574 *                                  l:617                                    l:617 *                                  l:621                                    l:621 *                                  l:632                                    l:632 *                                  l:664                                    l:664 *                                  l:59                                     l:59 *                                   l:315                                    l:315 *                                  l:323                                    l:323 *                                  l:333                                    l:333 *                                  l:11                                  l:11 *                                l:24                                  l:24 *                                l:33                                  l:33 *                                l:98                                  l:98 *                                l:99                                  l:99 *                                l:100                                 l:100 *                               l:101                                 l:101 *                               l:128                                l:128 *                              l:129                                l:129 *                              l:130                                l:130 *                              l:131                                l:131 *                              l:132                                l:132 *                              l:59                                        l:59 *                                      l:63                                        l:63 *                                      l:64                                        l:64 *                                      l:65                                        l:65 *                                      l:66                                        l:66 *                                      l:67                                        l:67 *                                      l:73                                        l:73 *                                      l:90                                        l:90 *                                      l:124                                       l:124 *                                     l:129                                       l:129 *                                     l:150                                       l:150 *                                     l:175                                       l:175 *                                     l:176                                       l:176 *                                     l:189                                       l:189 *                                     l:202                                       l:202 *                                     l:220                                       l:220 *                                     l:224                                       l:224 *                                     l:250                                       l:250 *                                     l:265                                       l:265 *                                     l:266                                       l:266 *                                     l:271                                       l:271 *                                     l:282                                       l:282 *                                     l:294                                       l:294 *                                     l:307                                       l:307 *                                     l:327                                       l:327 *                                     l:328                                       l:328 *                                     l:329                                       l:329 *                                     l:346                                       l:346 *                                     l:354                                       l:354 *                                     l:369                                       l:369 *                                     l:383                                       l:383 *                                     l:416                                       l:416 *                                     l:425                                       l:425 *                                     l:457                                       l:457 *                                     l:461                                       l:461 *                                     l:483                                       l:483 *                                     l:484                                       l:484 *                                     l:485                                       l:485 *                                     l:486                                       l:486 *                                     l:487                                       l:487 *                                     l:503                                       l:503 *                                     l:522                                       l:522 *                                     l:529                                       l:529 *                                     l:538                                       l:538 *                                     l:552                                       l:552 *                                     
# Failure: >>../src/data/CCIntMap.ml:291
# 
# test `../src/data/CCIntMap.ml:291:  
# 
#   Q.(list (pair int bool)) ( fun l -> 
#     equal ~eq:(=) (of_list l) (of_list (List.rev l)))
# 
# `
# failed on ≥ 1 cases:
# [(-954928363, false); (-954928363, true)] (after 14 shrink steps)
# 
# ///////////////////////////////////////////////////////////////////////////////
# Ran: 437 tests in: 9.17 seconds.                                        
# FAILURE
```

**Comment by kit-ty-kate** [comment]
All good now. Thanks! Could you return the license and tests re-enabling (I believe this is not the first time these were disabled) to the opam files upstream? Could you also have a look at the failures on 32bit?

**Comment by c-cube** [comment]
The failure on 32 bits looks like a dune failure, doesn't it? I only see a dune stacktrace :slightly_smiling_face: . As for the other test it's… a test that lacks an assumption, and it randomly stumbled upon a failure in CI.

Sorry for the snark yesterday. Your work is appreciated.

**Pull request merged**
