### PR TITLE
[new release] llvm (12.0.1) 

### PR DESCRIPTION
**Pull request by arbipher**
Hi, I make the llvm-12.0.1 for the llvm binding package.

I copied the packages from 11.0.0 and update the version number.
I tested the building and loading it in utop locally for my change. I also read the files that the patches applied. They both look good to me.

It's my first PR to opam-repository. Please tell me if I miss some standard workflow.

### CODE REVIEW

**Comment by arbipher** [comment]
```shell
⋊> diff conf-llvm/conf-llvm.11.0.0 conf-llvm/conf-llvm.12.0.1/                                                                20:35:03
Common subdirectories: conf-llvm/conf-llvm.11.0.0/files and conf-llvm/conf-llvm.12.0.1/files
diff '--color=auto' conf-llvm/conf-llvm.11.0.0/opam conf-llvm/conf-llvm.12.0.1/opam
11,18c11,18
<   ["llvm@11"] {os-distribution = "homebrew" & os = "macos"}
<   ["llvm-11"] {os-distribution = "macports" & os = "macos"}
<   ["llvm-11-dev"] {os-family = "debian"}
<   ["llvm11-dev"] {os-distribution = "alpine"}
<   ["llvm11-devel"] {os-family = "suse"}
<   ["llvm11-devel"] {os-distribution = "fedora"}
<   ["llvm11-devel" "epel-release"] {os-distribution = "centos"}
<   ["devel/llvm11"] {os = "freebsd"}
---
>   ["llvm@12"] {os-distribution = "homebrew" & os = "macos"}
>   ["llvm-12"] {os-distribution = "macports" & os = "macos"}
>   ["llvm-12-dev"] {os-family = "debian"}
>   ["llvm12-dev"] {os-distribution = "alpine"}
>   ["llvm12-devel"] {os-family = "suse"}
>   ["llvm12-devel"] {os-distribution = "fedora"}
>   ["llvm12-devel" "epel-release"] {os-distribution = "centos"}
>   ["devel/llvm12"] {os = "freebsd"}
```

```shell
⋊> diff llvm/llvm.11.0.0 llvm/llvm.12.0.1/                                                                                    20:35:31
Common subdirectories: llvm/llvm.11.0.0/files and llvm/llvm.12.0.1/files
diff '--color=auto' llvm/llvm.11.0.0/opam llvm/llvm.12.0.1/opam
36,37c36,37
<   src: "https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/llvm-11.1.0.src.tar.xz"
<   checksum: "sha256=ce8508e318a01a63d4e8b3090ab2ded3c598a50258cc49e2625b9120d4c03ea5"
---
>   src: "https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/llvm-12.0.1.src.tar.xz"
>   checksum: "sha256=7d9a8405f557cefc5a21bf5672af73903b64749d9bc3a50322239f56f34ffddf"
```

**Comment by arbipher** [comment]
I read the working `opam-ci` and most reports _unavailable system package 'llvm-12-dev'_.

On my local site, I use `https://apt.llvm.org/` to install llvm-12. It may not be on the default system repo.

**Comment by mseri** [comment]
Thanks, in these cases we rely on the CI output for the distributions that have the package. You can see that it compiles and installs successfully on:
https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/232caed6555401469b3586aca97407990a444b8b/variant/opam-2.0,distributions,debian-unstable,llvm.12.0.1
https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/232caed6555401469b3586aca97407990a444b8b/variant/opam-2.0,distributions,ubuntu-20.04,conf-llvm.12.0.1
https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/232caed6555401469b3586aca97407990a444b8b/variant/opam-2.0,distributions,ubuntu-21.04,conf-llvm.12.0.1

**Comment by mseri** [comment]
Thanks

**Pull request merged**
