### PR TITLE
+lz4.1.0.1

### PR DESCRIPTION
**Pull request by whitequark**

### CODE REVIEW

**Comment by yallop** [comment]
The build's failing because It's still using the pre-0.4.0 include path for ctypes:

```
# + /home/travis/.opam/system/bin/ocamlfind ocamlc -ccopt -I -ccopt /home/travis/.opam/system/lib/ctypes/.. -c lib/LZ4_stubs.c
# lib/LZ4_stubs.c:4:37: fatal error: ctypes_cstubs_internals.h: No such file or directory
```

**Comment by avsm** [comment]
@whitequark -- looking at this one?

**Comment by whitequark** [comment]
Whoops, old `url`

**Comment by avsm** [comment]
Thanks!

**Pull request merged**
