### PR TITLE
[new release] multipart_form (0.1.0)

### PR DESCRIPTION
**Pull request by dinosaure**
Multipart-form: RFC2183, RFC2388 & RFC7578

- Project page: <a href="https://github.com/dinosaure/multipart_form">https://github.com/dinosaure/multipart_form</a>
- Documentation: <a href="https://dinosaure.github.io/multipart_form/">https://dinosaure.github.io/multipart_form/</a>

##### CHANGES:

- First release of `multipart_form`

### CODE REVIEW

**Comment by dinosaure** [comment]
@tmattio, @anmonteiro

**Comment by kit-ty-kate** [comment]
There is a failure on OCaml 4.07:
```
#=== ERROR while compiling multipart_form.0.1.0 ===============================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/dinosaure/multipart_form/releases/download/v0.1.0/multipart_form-v0.1.0.tbz)
# path                 ~/.opam/4.07/.opam-switch/build/multipart_form.0.1.0
# command              ~/.opam/4.07/bin/dune build -p multipart_form -j 72
# exit-code            1
# env-file             ~/.opam/log/multipart_form-23-6ce548.env
# output-file          ~/.opam/log/multipart_form-23-6ce548.out
### output ###
#       ocamlc lib/.multipart_form.objs/byte/multipart_form__Field.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.multipart_form.objs/byte -I /home/opam/.opam/4.07/lib/angstrom -I /home/opam/.opam/4.07/lib/base64 -I /home/opam/.opam/4.07/lib/base64/rfc2045 -I /home/opam/.opam/4.07/lib/bigarray-compat -I /home/opam/.opam/4.07/lib/bigstringaf -I /home/opam/.opam/4.07/lib/fmt -I /home/opam/.opam/4.07/lib/ke -I /home/opam/.opam/4.07/lib/pecu -I /home/opam/.opam/4.07/lib/result -I /home/opam/.opam/4.07/lib/rresult -I /home/opam/.opam/4.07/lib/stdlib-shims -I /home/opam/.opam/4.07/lib/unstrctrd -I /home/opam/.opam/4.07/lib/unstrctrd/parser -I /home/opam/.opam/4.07/lib/uutf -no-alias-deps -open Multipart_form__ -o lib/.multipart_form.objs/byte/multipart_form__Field.cmo -c -impl lib/field.ml)
# File "lib/field.ml", line 50, characters 12-23:
# Error: Unbound module Option
```
Do you want to restrict this package to OCaml >= 4.08 or fix this issue then republish?

**Comment by dinosaure** [comment]
> Do you want to restrict this package to OCaml >= 4.08 or fix this issue then republish?

I updated constraints :+1:.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
