### PR TITLE
Add ctypes 0.14.0

### PR DESCRIPTION
**Pull request by yallop**

### CODE REVIEW

**Comment by mseri** [comment]
Most failures seems unrelated. The only one that may look suspicious is:
```

#=== ERROR while compiling pkcs11.0.16.0 ======================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.05.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.05.0/.opam-switch/build/pkcs11.0.16.0
# command              ~/.opam/4.05.0/bin/ocaml pkg/pkg.ml build --pinned false --with-cmdliner false --with-driver true
# exit-code            1
# env-file             ~/.opam/log/pkcs11-18-c25f2c.env
# output-file          ~/.opam/log/pkcs11-18-c25f2c.out
### output ###
[...]
# + ocamlfind ocamlc -c -g -bin-annot -w @8 -open Result -package zarith -package ppx_deriving_yojson -package ppx_deriving.std -package integers -package hex -package str -I src -I src_rev -I src_driver -I src_cli -I include -o src/p11_attribute.cmo src/p11_attribute.ml
# File "src/p11_attribute.ml", line 111, characters 28-43:
# Warning 40: NOT_IMPLEMENTED was selected from type P11_attribute_type.not_implemented.
# It is not visible in the current scope, and will not 
# be selected if the type becomes unknown.
[...]
# ocamlfind ocamlc -a -package zarith -package ppx_deriving_yojson -package ppx_deriving.std -package integers -package hex -package str -I src src/p11_aes_cbc_encrypt_data_params.cmo src/p11_hex_data.cmo src/p11_ulong.cmo src/p11_aes_ctr_params.cmo src/p11_aes_key_wrap_params.cmo src/p11_bigint.cmo src/p11_helpers.cmo src/p11_mechanism_type.cmo src/p11_key_gen_mechanism.cmo src/p11_key_type.cmo src/p11_object_class.cmo src/p11_attribute_type.cmo src/p11_attribute.cmo src/p11_attribute_types.cmo src/p11_des_cbc_encrypt_data_params.cmo src/p11_ec_kdf.cmo src/p11_ecdh1_derive_params.cmo src/p11_flags.cmo src/p11_gcm_params.cmo src/p11_hw_feature_type.cmo src/p11_version.cmo src/p11_info.cmo src/p11_load_mode.cmo src/p11_object_handle.cmo src/p11_ecmqv_derive_params.cmo src/p11_pkcs5_pbkd2_pseudo_random_function_type.cmo src/p11_pkcs5_pbkdf2_salt_source_type.cmo src/p11_pkcs5_pbkd2_data_params.cmo src/p11_rsa_pkcs_mgf_type.cmo src/p11_rsa_pkcs_oaep_params.cmo src/p11_rsa_pkcs_pss_params.cmo src/p11_mechanism.cmo src/p11_mechanism_info.cmo src/p11_rv.cmo src/p11_session_handle.cmo src/p11_session_info.cmo src/p11_slot.cmo src/p11_slot_id.cmo src/p11_slot_info.cmo src/p11_template.cmo src/p11_token_info.cmo src/p11_user_type.cmo src/p11.cmo src/p11_key_attributes.cmo -o src/pkcs11.cma
# ocamlfind ocamldep -package ctypes.stubs -package ctypes.foreign -open Result -package zarith -package ppx_deriving_yojson -package ppx_deriving.std -package integers -package hex -package str -modules src_driver/pkcs11_generator.ml > src_driver/pkcs11_generator.ml.depends
# + ocamlfind ocamldep -package ctypes.stubs -package ctypes.foreign -open Result -package zarith -package ppx_deriving_yojson -package ppx_deriving.std -package integers -package hex -package str -modules src_driver/pkcs11_generator.ml > src_driver/pkcs11_generator.ml.depends
# ocamlfind: Package `ctypes.foreign.unthreaded' not found - required by `ctypes.foreign'
# Command exited with code 2.
```

If this is unrelated as well, I am happy to merge

**Comment by yallop** [comment]
@mseri: it looks to me like the [opam file for pkcs11](https://github.com/ocaml/opam-repository/blob/89e4ed12fdeda79ad072f3616ec3034a9c2d7aee/packages/pkcs11/pkcs11.0.16.0/opam#L13) optionally builds some components if `ctypes` is installed:

```yaml
build: [
  [ "ocaml" "pkg/pkg.ml" "build"
    "--pinned" "%{pinned}%"
    "--with-cmdliner" "%{cmdliner:installed}%"
    "--with-driver" "%{ctypes:installed}%"
  ]
]
```

but those components really depend on having both the `ctypes` and `ctypes-foreign` packages installed.  If so then there's an issue that needs to be fixed in the `pkcs11` package (/cc @emillon), but it's not related to changes in this `ctypes` release.

**Comment by emillon** [comment]
Yes, that's indeed what's happening: the driver component depends on `Foreign`, which is in turn available if `ctypes-foreign` (which is just `conf-libffi` in disguise) was installed when `ctypes` was built.

There are a couple solutions I can think of:
1. `ctypes-foreign` could install `Foreign` & friends automatically (in that case `pkcs11` would just depopt on it)
1. these depopts could be made nonoptional
1. `pkcs11` could be split into several opam packages

If (1) is an option or somewhere in your roadmap that's great, otherwise I think I'll try to make that nonoptional.

**Comment by yallop** [comment]
@emillon: I'm not planning to change the behaviour of `ctypes-foreign` installation in the near future.  I think it'd be tricky without making significant changes to the way the package is organized/built.

The other solutions sound good, though.  Another short-term option could be to make the `--with-driver` flag depend on both `ctypes` and `ctypes-foreign` being installed.  I'm not sure whether there's a less clunky way than this:

```yaml
    "--with-driver"
      "true"  { ctypes:installed &  ctypes-foreign:installed}
      "false" {!ctypes:installed | !ctypes-foreign:installed}
```

**Comment by emillon** [comment]
That seems to be a good idea, thanks! That doesn't completely match `depopts` but I think that works!

**Comment by mseri** [comment]
Thanks all for reacting so quickly. I'll merge this in the meanwhile

**Pull request merged**
