### PR TITLE
fix constraints of the form "with-test >= Y" to "with-test & >= Y"

### PR DESCRIPTION
**Pull request by hannesm**
fix constraints of the form "Y >= with-test" to ">= Y & with-test"

### CODE REVIEW

**Comment by hannesm** [comment]
CI looks fine, I don't plan to fix the build of these packages -- mainly a community service to have nice and clean dependency conjunctions ;)

**Comment by hannesm** [comment]
I will not further push this. There's #27112 and also the following error (related to bisect I suspect):

```

#=== ERROR while compiling gobba.0.4.2 ========================================#
# context              2.4.0~alpha1~dev | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(https://github.com/0x0f0f0f/gobba/archive/0.4.2.tar.gz)
# path                 ~/.opam/4.08/.opam-switch/build/gobba.0.4.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p gobba -j 31
# exit-code            1
# env-file             ~/.opam/log/gobba-7-d56a01.env
# output-file          ~/.opam/log/gobba-7-d56a01.out
### output ###
# File "/home/opam/.opam/4.08/lib/owl/owl.dune", line 1, characters 0-0:
# Warning: .dune files are ignored since 2.0. Reinstall the library with dune
# >= 2.0 to get rid of this warning and enable support for the subsystem this
# library provides.
# File "/home/opam/.opam/4.08/lib/owl-base/owl-base.dune", line 1, characters 0-0:
# Warning: .dune files are ignored since 2.0. Reinstall the library with dune
# >= 2.0 to get rid of this warning and enable support for the subsystem this
# library provides.
# File "/home/opam/.opam/4.08/lib/ppx_derivers/ppx_derivers.dune", line 1, characters 0-0:
# Warning: .dune files are ignored since 2.0. Reinstall the library with dune
# >= 2.0 to get rid of this warning and enable support for the subsystem this
# library provides.
#          ppx lib/complexp.pp.ml (exit 2)
# (cd _build/default && .ppx/85ae8413f5a2e8b09d063ead993906cf/ppx.exe --conditional --cookie 'library-name="gobba"' -o lib/complexp.pp.ml --impl lib/complexp.ml --dump-ast)
# .ppx/85ae8413f5a2e8b09d063ead993906cf/ppx.exe: unknown option '--conditional'.
# ppx.exe [options] [<files>]
#   --as-ppx                  Act as a -ppx rewriter
#   --as-pp                   Shorthand for: --dump-ast --embed-errors
#   --dump-ast                Output a binary AST instead of source code
#   --null                    Output nothing, just report errors
#   -o FILE                   Output to this file instead of the standard output
#   --intf FILE               Treat FILE as a .mli file
#   --impl FILE               Treat FILE as a .ml file
#   --embed-errors            Embed error reported by rewriters into the AST
#   --print-transformations   Print registered transformations in their order of executions
#   --cookie NAME=EXPR        Set the cookie NAME to EXPR
#   -exclude <pattern>        Exclude functions matching pattern
#   -exclude-file <filename>  Exclude functions listed in given file
#   -mode {safe|fast|faster}
#                             Ignored
#   -conditional              Do not instrument unless environment variable BISECT_ENABLE is YES
#   -no-comment-parsing       Do not parse source files for BISECT-* comments
#   -help                     Display this list of options
#   --help                    Display this list of options
#          ppx lib/dictp.pp.ml (exit 2)
```

But I've no clue what/who emits the `--conditional` (vs `-conditional`).

**Comment by hannesm** [comment]
I removed the gobba 0.4.2 changes -- and expect the CI runs to be fine now, apart from the error(s) in #27112

**Comment by mseri** [comment]
Lint has passed. Thanks!

**Comment by hannesm** [comment]
I'm sorry, but I think [c46b46b](https://github.com/ocaml/opam-repository/pull/27102/commits/c46b46b5e97c823451ba9f5d1cfab5e85a364c7a) should be reverted since it is likely an instance of https://github.com/ocurrent/opam-repo-ci/issues/405 I'll open a followup PR.

**Comment by mseri** [comment]
Oh man, there have been a few of those commits lately 😰

**Pull request merged**
