### PR TITLE
Release LLVM 17

### PR DESCRIPTION
**Pull request by alan-j-hu**
Note that conf-llvm's configure.sh script should be unchanged from LLVM 16.

### CODE REVIEW

**Comment by mseri** [comment]
Is the macos failure expected? I think I remember a discussion about this in the past but cannot remember the conclusion
```
File "src/llvm/static/dune", line 2, characters 0-559:
#  2 | (library
#  3 |  (name llvm_static)
#  4 |  (public_name llvm.static)
#  5 |  (implements llvm)
#  6 |  (foreign_stubs
#  7 |   (language c)
#  8 |   (names llvm_ocaml)
#  9 |   (extra_deps llvm_ocaml.h)
# 10 |   (flags (-I/opt/homebrew/Cellar/llvm@17/17.0.6/include  -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS)))
# 11 |  (c_library_flags (-L/opt/homebrew/Cellar/llvm@17/17.0.6/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -lstdc++ -lLLVMCore -lLLVMRemarks -lLLVMBitstreamReader -lLLVMBinaryFormat -lLLVMTargetParser -lLLVMSupport -lLLVMDemangle
# 12 | -lm -lz -lzstd -lcurses -lxml2)))
# (cd _build/default && /Users/mac1000/.opam/4.14.2/bin/ocamlmklib.opt -g -o src/llvm/static/llvm_static_stubs src/llvm/static/llvm_ocaml.o -ldopt -L/opt/homebrew/Cellar/llvm@17/17.0.6/lib -ldopt -Wl,-search_paths_first -ldopt -Wl,-headerpad_max_install_names -ldopt -lstdc++ -ldopt -lLLVMCore -ldopt -lLLVMRemarks -ldopt -lLLVMBitstreamReader -ldopt -lLLVMBinaryFormat -ldopt -lLLVMTargetParser -ldopt -lLLVMSupport -ldopt -lLLVMDemangle -ldopt -lm -ldopt -lz -ldopt -lzstd -ldopt -lcurses -ldopt -lxml2)
# ld: library 'zstd' not found
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by alan-j-hu** [comment]
I've marked this as unavailable for ARM Macs with Homebrew. I may publish a separate version, with the workaround with an additional dependency on pkg-config, for Homebrew on the ARM Macs separately.

**Comment by mseri** [comment]
> I opened a PR at #25002 some months ago. However, it's an annoying breaking Homebrew change due to Mac's switch from Intel to ARM. Homebrew installed Intel binaries in the standard location, `/usr/local`, so it installs ARM binaries in a non-standard location, `/opt/homebrew`. Furthermore, due to security issues, Mac doesn't let you change the default library search path with `LD_LIBRARY_PATH` due to "System Integrity Protection" (SIP), so the libraries installed by Homebrew for ARM can't be made to be found. The OCaml LLVM package is not the only breakage by the Homebrew change. For example, I saw error messages on the Internet from people trying to use zstd (the LLVM dependency involved) purely from C on the new Macs. The Homebrew change breaks many things, because naturally tools search for libraries under standard paths, not arbitrary non-standard paths like `/opt/homebrew`.

At that is my fault sorry, I need to find some time to review it properly and understand what is going on

**Comment by mseri** [comment]
> I've marked this as unavailable for ARM Macs with Homebrew. I may publish a separate version, with the workaround with an additional dependency on pkg-config, for Homebrew on the ARM Macs separately.

Sounds good

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
