### PR TITLE
use new package conf-gnuplot

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Once this is accepted, I'll look into using the new conf-autoconf package in the same fashion.

**Comment by UnixJunkie** [comment]
It seems like the gnuplot library needs a version constraint on core.
I'll see if I can pinpoint it.

**Comment by UnixJunkie** [comment]
all green in travis and for camelus

**Comment by dsheets** [comment]
Thanks for your work!

**Pull request merged**
