### PR TITLE
simplify cudf install/uninstall command

### PR DESCRIPTION
**Pull request by timbertson**
in [opam2nix](https://github.com/timbertson/opam2nix), the `lib` suffix is scoped per ocaml version to allow for multiple ocaml versions without conflict (e.g. `lib/ocaml/4.08.1/site-lib`). So the hardcoded `lib/` in cudf installs to the wrong location.

This PR leaves the install paths up to `ocamlfind` (which does the right thing in both contexts), but keeps `BINDIR` which is used by the Makefile itself.

I've verified this builds locally with opam and produces the same output (in lib/ and bin/)

/cc @rdicosmo

### CODE REVIEW

**Comment by mseri** [comment]
Could you move this change to a different patched version: `cudf-0.9-1`?

**Comment by kit-ty-kate** [comment]
> This PR leaves the install paths up to `ocamlfind` (which does the right thing in both contexts), but keeps `BINDIR` which is used by the Makefile itself.

If this is the case, a dependency on `ocamlfind` is missing. I'll add it.

**Comment by timbertson** [comment]
Thanks @kit-ty-kate. I'm happy with that change, but surprised that you were able to push it into my repository. Is that because you have push permissions on this upstream repo, or some other reason?

**Comment by kit-ty-kate** [comment]
@timbertson every PRs made through github give the push permission on the source branch to the maintainers of the repository the PR has been made to, by default. If you prefer not to, there is a checkbox to uncheck when you open a PR.

**Comment by timbertson** [comment]
Huh, never knew that, thanks

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
