### PR TITLE
add coqide.8.15.1

### PR DESCRIPTION
**Pull request by palmskog**
Followup to #21001 (CoqIDE release is in the same archive).

cc: @MSoegtropIMC @skyskimmer

### CODE REVIEW

**Comment by SkySkimmer** [comment]
https://github.com/ocaml/opam-repository/blob/master/packages/lablgtk3-sourceview3/lablgtk3-sourceview3.3.0.beta4/opam may have the wrong version constraint

see also https://github.com/ocaml/opam-repository/pull/20651

I guess it should have ocaml < 4.09 or maybe lablgtk = version

**Comment by palmskog** [comment]
Maintainers, please advise if I should submit a separate PR for the lablgtk3-sourceview3.3.0.beta4 package with the fix suggested by @SkySkimmer and then rebase this PR. The fix proposal was was prompted by [this failing build](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/4f36fc0c55d72602e7c92dbedd49364f4bec1ce9/variant/opam-2.1,compilers,4.09,coqide.8.15.1,lower-bounds).

**Comment by mseri** [comment]
Thanks for the submission and the fix. Let's see if the CI is happy now

**Comment by palmskog** [comment]
Unfortunately, it looks like the same error is still present in the single failing, but now for the "next" version of lablgtk3-sourceview3, namely, 3.0.beta5. Possibly a similar version OCaml 4.09 error?

**Comment by mseri** [comment]
Yeah, looking at the github history I think 3.3.1 is the first working (or maybe beta8)

**Comment by mseri** [comment]
Good now, thanks!

**Pull request merged**
