### PR TITLE
Package pprint.20220103

### PR DESCRIPTION
**Pull request by fpottier**
### `pprint.20220103`
A pretty-printing combinator library and rendering engine
This library offers a set of combinators for building so-called documents as
well as an efficient engine for converting documents to a textual, fixed-width
format. The engine takes care of indentation and line breaks, while respecting
the constraints imposed by the structure of the document and by the text width.

---
* Homepage: https://github.com/fpottier/pprint
* Source repo: git+ssh://git@github.com/fpottier/pprint.git
* Bug tracker: francois.pottier@inria.fr

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by fpottier** [comment]
I have looked at `ott` and `asli`; they both need `pprint < 20220103`. I have submitted two PRs upstream.

**Comment by fpottier** [comment]
I have extended this PR with a `conflicts` clause for `ott` and an upper bound for `asli`.

**Comment by kit-ty-kate** [comment]
`ott` does not depend on anything but the ocaml compiler. How did you get an error? I’m not seeing anything in the CI

**Comment by fpottier** [comment]
`ott` is a code generator. It does not depend on `pprint`, but it produces code that depends on `pprint`, and the generated code works only with PPrint < 20220103.

**Comment by kit-ty-kate** [comment]
Ah I see. I’m not using this part of `ott`. Only its `.ott --> .latex` pipeline and I wasn’t aware it used pprint. Too bad they didn’t provide the tests in the opam file. I’ll have a look to add them so we get noticed in the future

**Comment by kit-ty-kate** [comment]
Done in https://github.com/ott-lang/ott/pull/89

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
