### PR TITLE
[typerex] cleanup old versions and urls

### PR DESCRIPTION
**Pull request by lefessan**

### CODE REVIEW

**Comment by avsm** [comment]
Any reason to delete these?  It violates quite a few constraints in other packages. e.g.

```
packages/ocp-build/ocp-build.1.99-beta/opam:depends: ["typerex" {>= "1.99"}]
packages/ocp-build/ocp-build.1.99.1-beta/opam:depends: ["typerex" {= "1.99.1-beta"}]
packages/ocp-build/ocp-build.1.99.2-beta/opam:depends: ["typerex" {= "1.99.2-beta"}]
packages/ocp-build/ocp-build.1.99.3-beta/opam:depends: ["typerex" {= "1.99.3-beta"}]
packages/ocp-build/ocp-build.1.99.4-beta/opam:depends: ["typerex" {= "1.99.4-beta"}]
packages/ocp-build/ocp-build.1.99.5-beta/opam:depends: ["typerex" {= "1.99.5-beta"}]
packages/ocp-build/ocp-build.1.99.6-beta/opam:depends: ["typerex" {= "1.99.6-beta"}]
```

**Comment by avsm** [comment]
Ping.

**Comment by avsm** [comment]
The typerex distfiles have now disappeared upstream, but the constraints are still broken in OPAM.  /cc @AltGr

**Comment by avsm** [comment]
Will close this in a few days if it doesn't get a response.  Sadly the upstream distfiles have disappeared and so OPAM packages for typerex will be broken.  This is better than having dangling constraints in the repository though.

**Comment by lefessan** [comment]
Hi Anil,

  I uploaded a new version 1.99.9-beta of ocp-build. It uses a Makefile to compile, and there is no bootstrap anymore, so it should fix the issues with the trunk of OCaml. Package "typerex" as no reason to exist, we will probably replace it at some point by a meta package that will depend on a set of ocp- tools.

**Pull request merged**
