### PR TITLE
conf-openblas - add Fedora support

### PR DESCRIPTION
**Pull request by XVilka**
Fixing https://github.com/ocaml/opam-repository/issues/11293

### CODE REVIEW

**Comment by yomimono** [comment]
I don't think it's necessary to change the version number of `conf-openblas`, and doing so will result in any users who have `conf-openblas` installed already and upgrade having to reinstall the package and its dependencies for no reason.

The depext change looks OK (and seems to work in CI); can you submit a version which just changes the depexts of `conf-openblas` version 0.1?

**Comment by XVilka** [comment]
@yomimono done.

**Comment by XVilka** [comment]
Note, the package will require rewriting for OPAM-2.0 migration. by the way. OPAM 2.0 autoconverts it wrongly. Not sure if a bug in opam or just need to be fixed manually when 2.0 is released.

**Comment by jpdeplaix** [comment]
Fair enough. I'll merge that.

cc @AltGr for the opam2 related bug.
In the meantime could you give more information about the rewriting issue ?

**Comment by AltGr** [comment]
Err, what is ` depexts: [   [["centos"] [""]] ]` supposed to mean ? I don't know how it is expected to be rewritten ? Is that the issue you are referring to ?

**Comment by AltGr** [comment]
Actually, the general `depexts:` format is a bit suspicious: e.g. `["libopenblas-dev liblapacke-dev"]` should rather be written `["libopenblas-dev" "liblapacke-dev"]` (list of strings rather than singleton list containing a single string with a space).

**Pull request merged**
