### PR TITLE
opam2web 1.3.x believes opam is opam's findlib package name (<1.2.0)

### PR DESCRIPTION
**Pull request by dsheets**

### CODE REVIEW

**Comment by avsm** [comment]
travis missed the build... push a dummy commit

**Comment by dsheets** [comment]
Done. GitHub <-> Travis link seems to have some serious issues today, though.

**Comment by avsm** [comment]
Looks like a real error ;

```
[ERROR] Installation of dose.3.1.2 failed
∗  installed dyntype.0.9.0
∗  installed uri.1.3.11
∗  installed cow.0.6.1
∗  installed js_of_ocaml.2.5
#=== ERROR while installing dose.3.1.2 ========================================#
Some files in ~/.opam/system/install/dose.install couldn't be installed:
  - /home/travis/.opam/system/build/dose.3.1.2/_obuild/dose/algo.cmi to /home/travis/.opam/system/lib/dose
  - /home/travis/.opam/system/build/dose.3.1.2/_obuild/dose/common.cmi to /home/travis/.opam/system/lib/dose
  - /home/travis/.opam/system/build/dose.3.1.2/_obuild/dose/debian.cmi to /home/travis/.opam/system/lib/dose
```

**Comment by dsheets** [comment]
Odd. opam-lib.1.1.1 is the only satisfying dependency and it requires dose 3.1.2. Without patching, this will never be fixed. Do we have an acceptable method of disabling/marking bad packages?

**Comment by avsm** [comment]
Does available:false work?

**Comment by dsheets** [comment]
I'll also modify the test script to use -notuptodate,-removed,-changed or something.

**Comment by dsheets** [comment]
Neither was required. dose's install file was broken.

**Pull request merged**
