### PR TITLE
Ocamlbuild.0.10.1

### PR DESCRIPTION
**Pull request by gasche**
Followup on #8155... The joy of software development :-)

### CODE REVIEW

**Comment by samoht** [comment]
Does it fix?

```
#=== ERROR while installing mtime.0.8.3 =======================================#
# opam-version 1.2.2
# os           linux
# command      ocaml pkg/build.ml native=true native-dynlink=true jsoo=false
# path         /home/travis/.opam/4.03.0/build/mtime.0.8.3
# compiler     4.03.0
# exit-code    10
# env-file     /home/travis/.opam/4.03.0/build/mtime.0.8.3/mtime-24235-865888.env
# stdout-file  /home/travis/.opam/4.03.0/build/mtime.0.8.3/mtime-24235-865888.out
# stderr-file  /home/travis/.opam/4.03.0/build/mtime.0.8.3/mtime-24235-865888.err
### stdout ###
# [...]
# ocamlfind ocamlopt -a -cclib -lmtime_stubs -cclib -lrt src-os/mtime_base.cmx src-os/mtime.cmx -o src-os/mtime.cmxa
# ocamlfind ocamlc -c -g -bin-annot -safe-string -I src-os -o src-os/mtime.cmo src-os/mtime.ml
# ocamlfind ocamlc -a -dllib -lmtime_stubs -cclib -lrt src-os/mtime_base.cmo src-os/mtime.cmo -o src-os/mtime.cma
# ocamlfind ocamlopt -shared -linkall src-os/libmtime_stubs.a src-os/mtime.cmxa -o src-os/mtime.cmxs
# + ocamlfind ocamlopt -shared -linkall src-os/libmtime_stubs.a src-os/mtime.cmxa -o src-os/mtime.cmxs
# /usr/bin/ld: cannot find -lmtime_stubs
# collect2: ld returned 1 exit status
# File "caml_startup", line 1:
# Error: Error during linking
# Command exited with code 2.
```

**Comment by samoht** [comment]
I have reverted 0.10.0 as it seems to break some existing packages. Was it expected?

**Comment by gasche** [comment]
Nope, breaking builds is never expected. Although it is not completely surprising either as 0.10 indeed changes the way `.cmxs` are built.

Thanks for reverting. I'll investigate locally with the repro-case and see what we should do.

"Jamais deux sans trois"...

**Comment by gasche** [comment]
I'll close the PR for now while I don't understand the regression better.

**Comment by whitequark** [comment]
@gasche Can we please get a version with the -toolchain option? This holds up many downstream cross-compilation improvements.

**Comment by gasche** [comment]
I'll try to do this before the end of the month, yes. This release is painful because of the `.cmxs` regression (we have to revert the changes before going through), but in general, for future releases, I would warmly welcome help / be glad let someone else do the release.

**Comment by whitequark** [comment]
> This release is painful because of the .cmxs regression (we have to revert the changes before going through)

Actually, I don't think so. I believe the root cause of the regression is ocamlbuild not passing the necessary -I flags when building a cmxs, most likely caused by ocaml/ocamlbuild#89888f2c40.

**Comment by gasche** [comment]
This commit is part of the `.cmxs` changes I had in mind and plan to revert before doing a new release -- I should have released before merging them in the first place.

**Comment by whitequark** [comment]
@gasche Actually, it's weirder. I bisected the change to ocaml/ocamlbuild@f865497a8. It looks like -linkall wasn't passed before but it is passed now, which causes the immediate failure.

Also, you've added the tag "foo" in ocaml_specific.ml...

**Comment by whitequark** [comment]
@gasche I think I know what happens. Specifically, you're now linking a cmxa and a into a cmxs, instead of cmx and o. However, cmxa already has an autolink directive, so instead of the a, what's really needed is a -I flag.

**Comment by gasche** [comment]
I think that the discussion in https://github.com/ocaml/ocamlbuild/issues/131 would give more context.

**Comment by whitequark** [comment]
@gasche At a glance that was just a mixture of more confusion and everything I already knew. Anyway, I already implemented a fix, PR incoming.

**Comment by whitequark** [comment]
@gasche Please review https://github.com/ocaml/ocamlbuild/pull/159.

**Pull request closed without merging**
