### PR TITLE
Package sqlite3.4.3.0

### PR DESCRIPTION
**Pull request by mmottl**
### `sqlite3.4.3.0`

sqlite3-ocaml - SQLite3 bindings for OCaml

sqlite3-ocaml is an OCaml library with bindings to the SQLite3 client API.
Sqlite3 is a self-contained, serverless, zero-configuration, transactional SQL
database engine with outstanding performance for many use cases.

---
* Homepage: http://mmottl.github.io/sqlite3-ocaml
* Source repo: https://github.com/mmottl/sqlite3-ocaml.git
* Bug tracker: https://github.com/mmottl/sqlite3-ocaml/issues

---

---
### 4.3.0 (2017-10-10)

  * Improved compatibility with MSVC

  * Used untagging and unboxing attributes on external functions
:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by gasche** [comment]
The 4.06 failure is due to `sexplib` not being compatible with 4.06 for now. I don't know whether sqlite itself is compatible with `-safe-string` (this could be tested using the `4.06.0+beta2+default-unsafe-string` flag to get the dependencies to build, and then passing `-safe-string` to the build). @mmottl, do you know if this release works under 4.06? If not, is a 4.06-compatibility release planned?

**Comment by mmottl** [comment]
Indeed, it seems that `sexplib` will need to be fixed.  `sqlite3` should be compatible, as should be all my other packages.  I had updated them as soon as `-safe-string` was introduced (4.02 - three years ago!).

I've joined the related issue https://github.com/janestreet/sexplib/issues/31 and will wait for a reply from JS before deciding on what to do next.  It would create quite some churn if I had to eliminate all dependencies on `base`, which pulls in `sexplib`.

**Comment by gasche** [comment]
To be clear, I'm not suggesting that you remove the dependency; it's perfectly fine if some basic blocks of the ecosystem take a longer time to become 4.06-ready (often they are also the more tightly coupled to the compiler, and thus require more porting work), and it is also fine to keep improving OCaml software even if it is not available under the newest (or upcoming) version. I'll merge sqlite3 right now, but I wanted to get a sense of whether you had given a thought to 4.06 compatibility (otherwise, the gentle question may have encouraged you to revise the new release to include support, or to do another release for this, and the "make sure 4.06 goes well" side of my life is pleased).

**Comment by mmottl** [comment]
That's how I understood it.  I'd certainly rather wait for basic dependencies to get updated (which, I'm sure they will soon) than tear them out.

**Pull request merged**
