### PR TITLE
xenctrl.0.9.26 needs configure before make uninstall

### PR DESCRIPTION
**Pull request by dsheets**

### CODE REVIEW

**Comment by dsheets** [comment]
I've just seen <https://github.com/djs55/opam-repo-dev/commit/ae35c5e5f8f4a4d62e62bced61e458ff37b3dbd0>. Please wait to merge.

**Comment by avsm** [comment]
Yep the direct `ocamlfind` use is encouraged as that means source archives aren't unpacked for uninstallation.

**Comment by dsheets** [comment]
Unfortunately, it looks like the xenguest-4.4 subcomponent does `rm -f $(BINDIR)/xenguest` on uninstall. :-/ Dunno what the right answer is but maybe @djs55 can shed some light.

**Comment by djs55** [comment]
Interesting -- I didn't realise the direct `ocamlfind` was considered best practice.

Perhaps just extend this patch with an additional
```
"rm" "-f" "%{bin}%/xenguest"
```
(if I've got the syntax right?) I'm sure no-one else will be silly enough to name their binary "xenguest" and clash with this :)

**Comment by dbuenzli** [comment]
Le samedi, 25 avril 2015 à 20:19, Dave Scott a écrit :
> Interesting -- I didn't realise the direct ocamlfind was considered best practice.

In the days of opam I would rather say that a `.install` file is best practice.  

I never made much noise around topkg because I still consider it as a bloody hack, but in any case around 95% of the package that are using oasis at the moment would be as well served by using topkg with the machine benefit of a good and precise opam integration and the immensely *human* benefit of not not having the poor people following your repo to have to suffer the pain of looking at PRs of oasis generated code.  

D

**Comment by djs55** [comment]
Thanks @dbuenzli for pointing me at the .install files -- I'll switch over to that for my future releases.

My "plan" (perhaps too strong a word!) that I've been discussing with @euanh @jonludlam et al is to switch the remaining of our omake/obuild-using components to oasis+ocamlbuild (most are using oasis+ocamlbuild already, so this will simplify a little), and then perform a mass migration to something simpler and cleaner, once we figure out what that is :-)

**Comment by djs55** [comment]
Oh and thanks @dsheets for fixing my broken package ;-)

**Pull request merged**
