### PR TITLE
Ocaml src updates

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
If I understand it correctly, @avsm proposed such a change in #26947.

**Comment by hannesm** [comment]
from my point of view, this is good to merge

**Review by shym — APPROVED** [review]
This looks good to me.
(I’ve checked in particular that no `ocaml-src` package was forgotten in the first commit.)

**Comment by hannesm** [comment]
anything needed from my site to merge now that there's a consider-for-merge label?

**Comment by mseri** [comment]
I was waiting to see if somebody else from the previous discussion wanted to chip in. Let's merge then

**Pull request merged**
