### PR TITLE
Fix bap packages: fix their dependencies to use the same version as the package version

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Detected with [check.ocamllabs.io](http://check.ocamllabs.io)

cc @gitoleg could you check if there is no mistake from me here?
cc @ivg is there a reason why `bap-saluki` has a rather weird version number? (`bap-1.5` for instance)

### CODE REVIEW

**Comment by ivg** [comment]
I think it's accidental, it coincides with the tag version. It should be 1.5.0 of course. Thanks for the PR, it looks reasonable, but let us run it on our CI, just to double check.

**Comment by kit-ty-kate** [comment]
i think that should fix most of the breakage, though there is still the missing `bap-ida-python.1.4.0` package that messes things a bit. Does anyone know how to fix it properly?

**Comment by gitoleg** [comment]
@kit-ty-kate 
I'm currently working on it, so I'll let you know when everything will be ready

**Comment by ivg** [comment]
Yep, it looks like that `bap-ida-python.1.4.0`  wasn't ever released. Probably, it would be easier to release it retrospectively (basically to rerelease bap-ida-python.1.3.0 as bap-ida-python.1.4.o), just to make automated versioning easier and to remove this nasty whole in versioning.

**Comment by kit-ty-kate** [comment]
I suddenly remembered I could have used `{= version}` instead of `{= "<the same version as the package I'm modifying>"}`. It would have avoided some problems and be less of a hassle. Anyway, I'll remember for next time..

**Comment by gitoleg** [comment]
@kit-ty-kate 
hey, there is a PR in your `opam-repository` that is waiting for you)

**Comment by kit-ty-kate** [comment]
Ah sorry, apparently when you're forking a repository, by default github doesn't make you "watch" it so I didn't get notified

**Comment by kit-ty-kate** [comment]
Thanks a lot for your help

**Pull request merged**
