### PR TITLE
ppx_tools 5.0 and 5.0+4.02.0

### PR DESCRIPTION
**Pull request by alainfrisch**

### CODE REVIEW

**Comment by aantron** [comment]
🎉 :)

**Comment by yallop** [comment]
The ppx_tools build is [failing](https://travis-ci.org/ocaml/opam-repository/jobs/127541439) on 4.03:

```
# File "ast_mapper_class.ml", line 296, characters 6-23:
# Error: This variant pattern is expected to have type
#          Parsetree.expression_desc
#        The constructor Pexp_letexception does not belong to type Parsetree.expression_desc
# make: *** [ast_mapper_class.cmo] Error 2
```

**Comment by alainfrisch** [comment]
Argh, I adapted to trunk no 4.03 by mistake...

**Comment by alainfrisch** [comment]
Should be fixed now.  "5.0" is for trunk, and we have also "5.0+4.02.0" and "5.0+4.03.0".

**Pull request merged**
