### PR TITLE
Add capnp-rpc.0.1

### PR DESCRIPTION
**Pull request by talex5**

### CODE REVIEW

**Comment by talex5** [comment]
The distro checks are failing because many distros don't provide the schema compiler binary. I think I'll add the generated files to the release archive so it can be installed anywhere.

**Comment by avsm** [comment]
Do other language bindings do similarly? Not providing the schema compiler binary seems like an odd omission -- should we report this upstream to Fedora/Alpine/etc?

**Comment by talex5** [comment]
For example, Debian 8 doesn't have the package at all.

**Comment by talex5** [comment]
On the other hand, the capnp package doesn't install on Debian 8 anyway, but the CI detects that and skips it. Maybe I should just add the required packages for the other distros, so it skips them too if they're too old

**Comment by avsm** [comment]
It's ok to have some failing distros if it's because of version only. We're working on improving the integration between depext and the solver in opam2: https://github.com/ocaml/opam/issues/2919

**Comment by talex5** [comment]
OK. I've made a new PR at #10074 (GitHub won't let me reopen this one).

**Pull request closed without merging**
