### PR TITLE
Core suite v0.11

### PR DESCRIPTION
**Pull request by trefis**
Take 2.

### CODE REVIEW

**Comment by trefis** [comment]
Apparently camelus hasn't registered the last commit (which removes jane-street-tests) just yet.
I'm looking at the async_smtp failure.

**Comment by trefis** [comment]
(This is now fixed)

**Comment by kit-ty-kate** [comment]
```
#=== ERROR while compiling async_inotify.v0.11.0 ==============================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.05.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.05.0/.opam-switch/build/async_inotify.v0.11.0
# command              ~/.opam/4.05.0/bin/jbuilder build -p async_inotify -j 71
# exit-code            1
# env-file             ~/.opam/log/async_inotify-16-3a23c3.env
# output-file          ~/.opam/log/async_inotify-16-3a23c3.out
### output ###
#       ocamlc src/.async_inotify.objs/async_inotify.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I /home/opam/.opam/4.05.0/lib/async -I /home/opam/.opam/4.05.0/lib/async_extra -I /home/opam/.opam/4.05.0/lib/async_find -I /home/opam/.opam/4.05.0/lib/async_kernel -I /home/opam/.opam/4.05.0/lib/async_rpc_kernel -I /home/opam/.opam/4.05.0/lib/async_unix -I /home/opam/.opam/4.05.0/lib/base -I /home/opam/.opam/4.05.0/lib/base/caml -I /home/opam/.opam/4.05.0/lib/base/md5 -I /home/opam/.opam/4.05.0/lib/base/shadow_stdlib -I /home/opam/.opam/4.05.0/lib/bin_prot -I /home/opam/.opam/4.05.0/lib/bin_prot/shape -I /home/opam/.opam/4.05.0/lib/core -I /home/opam/.opam/4.05.0/lib/core_kernel -I /home/opam/.opam/4.05.0/lib/core_kernel/base_for_tests -I /home/opam/.opam/4.05.0/lib/fieldslib -I /home/opam/.opam/4.05.0/lib/inotify -I /home/opam/.opam/4.05.0/lib/jane-street-headers -I /home/opam/.opam/4.05.0/lib/ocaml/threads -I /home/opam/.opam/4.05.0/lib/parsexp -I /home/opam/.opam/4.05.0/lib/ppx_assert/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_bench/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_expect/collector -I /home/opam/.opam/4.05.0/lib/ppx_expect/common -I /home/opam/.opam/4.05.0/lib/ppx_expect/config -I /home/opam/.opam/4.05.0/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_inline_test/config -I /home/opam/.opam/4.05.0/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.05.0/lib/protocol_version_header -I /home/opam/.opam/4.05.0/lib/sexplib -I /home/opam/.opam/4.05.0/lib/sexplib/unix -I /home/opam/.opam/4.05.0/lib/sexplib0 -I /home/opam/.opam/4.05.0/lib/spawn -I /home/opam/.opam/4.05.0/lib/splittable_random -I /home/opam/.opam/4.05.0/lib/stdio -I /home/opam/.opam/4.05.0/lib/typerep -I /home/opam/.opam/4.05.0/lib/variantslib -no-alias-deps -I src/.async_inotify.objs -open Async_inotify__ -o src/.async_inotify.objs/async_inotify.cmo -c -impl src/async_inotify.pp.ml)
# File "src/async_inotify.ml", line 47, characters 16-29:
# Error: Unbound type constructor Inotify.watch
#     ocamlopt src/.async_inotify.objs/async_inotify.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlopt.opt -w -40 -safe-string -g -I /home/opam/.opam/4.05.0/lib/async -I /home/opam/.opam/4.05.0/lib/async_extra -I /home/opam/.opam/4.05.0/lib/async_find -I /home/opam/.opam/4.05.0/lib/async_kernel -I /home/opam/.opam/4.05.0/lib/async_rpc_kernel -I /home/opam/.opam/4.05.0/lib/async_unix -I /home/opam/.opam/4.05.0/lib/base -I /home/opam/.opam/4.05.0/lib/base/caml -I /home/opam/.opam/4.05.0/lib/base/md5 -I /home/opam/.opam/4.05.0/lib/base/shadow_stdlib -I /home/opam/.opam/4.05.0/lib/bin_prot -I /home/opam/.opam/4.05.0/lib/bin_prot/shape -I /home/opam/.opam/4.05.0/lib/core -I /home/opam/.opam/4.05.0/lib/core_kernel -I /home/opam/.opam/4.05.0/lib/core_kernel/base_for_tests -I /home/opam/.opam/4.05.0/lib/fieldslib -I /home/opam/.opam/4.05.0/lib/inotify -I /home/opam/.opam/4.05.0/lib/jane-street-headers -I /home/opam/.opam/4.05.0/lib/ocaml/threads -I /home/opam/.opam/4.05.0/lib/parsexp -I /home/opam/.opam/4.05.0/lib/ppx_assert/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_bench/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_expect/collector -I /home/opam/.opam/4.05.0/lib/ppx_expect/common -I /home/opam/.opam/4.05.0/lib/ppx_expect/config -I /home/opam/.opam/4.05.0/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_inline_test/config -I /home/opam/.opam/4.05.0/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.05.0/lib/protocol_version_header -I /home/opam/.opam/4.05.0/lib/sexplib -I /home/opam/.opam/4.05.0/lib/sexplib/unix -I /home/opam/.opam/4.05.0/lib/sexplib0 -I /home/opam/.opam/4.05.0/lib/spawn -I /home/opam/.opam/4.05.0/lib/splittable_random -I /home/opam/.opam/4.05.0/lib/stdio -I /home/opam/.opam/4.05.0/lib/typerep -I /home/opam/.opam/4.05.0/lib/variantslib -no-alias-deps -I src/.async_inotify.objs -open Async_inotify__ -o src/.async_inotify.objs/async_inotify.cmx -c -impl src/async_inotify.pp.ml)
# File "src/async_inotify.ml", line 47, characters 16-29:
# Error: Unbound type constructor Inotify.watch
```

**Comment by kit-ty-kate** [comment]
This should be fixed. Could you make an other PR to fix the previous versions of ```async_inotify``` after this one ?

**Comment by trefis** [comment]
> Could you make an other PR to fix the previous versions of async_inotify after this one ?

Will do.

**Pull request merged**
