### PR TITLE
+ esgg 20190319

### PR DESCRIPTION
**Pull request by ygrek**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The dependency constraint sounds wrong:
```
[ERROR] No solution for esgg.20190319: The following dependencies couldn't be met:
          - esgg -> devkit > 0.7
              no matching version
```

**Comment by ygrek** [comment]
Thanks, I don't know where camelus logs are :/

Will need to update devkit first, PR incoming

**Comment by cyberhuman** [comment]
PR #13713

**Comment by ygrek** [comment]
please restart build, devkit is now updated (but it may fail to build due to wrong camlp4 setup in travis, see PR linked above for details)

**Comment by ygrek** [comment]
nvm, there is another dep (atd > 2.0.0) that we need to address. Will open new PR when all is ready

**Pull request closed without merging**
