### PR TITLE
release charrua-client 0.0.1

### PR DESCRIPTION
**Pull request by yomimono**

### CODE REVIEW

**Comment by yomimono** [comment]
How can I see the details of the failed installability check?

**Comment by hannesm** [comment]
I suspect one issue might be that `mirage-stdlib-random` is not released yet.. sorry..

**Comment by yomimono** [comment]
Er, that would do it indeed.  I'll close this for now and release into mirage-dev instead.

**Comment by hannesm** [comment]
(which depends on mirage-types.dev version (due to changed RANDOM interface)... yes, releasing to mirage-dev sounds like a good plan)

**Pull request closed without merging**
