### PR TITLE
Make Why3 conflict with some versions of Coq.

### PR DESCRIPTION
**Pull request by silene**

### CODE REVIEW

**Comment by gasche** [comment]
If I understand correctly, you are planning to have a future release where you don't need the 8.7 bound on conflict, but would just have a configure-script that disables the Coq support if the coq version is not supported?

(Or, long term, what is the plan for a user that wants to use both Coq 8.7 and Why3? Is there a way at least to ask opam to use why3 without Coq support in that case?)

**Comment by silene** [comment]
> you would just have a configure-script that disables the Coq support if the coq version is not supported?

No, that is more complicated than that. Why3 0.87.1 works perfectly fine with Coq 8.7.0. But the `configure` script makes the assumption that, as long as Coq is installed, `coqc -byte` can actually be executed. This assumption had been true up to now, but starting with the opam package for Coq 8.7, this does not hold anymore. (The `-byte` option is seldom used nowadays, so I understand why the Coq developers would decide that the opam package should no longer provide it.) For example, if you compile and install Coq 8.7 by hand (so that the `-byte` option is provided), and if you then install Why3 using `opam`, then you get a version of Why3 that fully supports Coq 8.7. I just need to improve the build infrastructure of Why3 so that it detects whether the `-byte` option of `coqc` is broken.

**Comment by gasche** [comment]
Thanks, I understand better now.

This is unrelated, but the Continuous Integration testing is failing on 0.81 and 0.82 because of Gtk version mismatch. I suppose that you should add the bounds `{>= "2.14.2"}` as done in 0.84 (and maybe add them also in 0.83, which for some reason doesn't fail at CI time). Would you consider including the change in the PR, so that we see if the CI works for all changed Why3 versions?

**Comment by silene** [comment]
> I suppose that you should add the bounds `{>= "2.14.2"}` as done in 0.84 (and maybe add them also in 0.83, which for some reason doesn't fail at CI time).

Given than 0.83 does not fail and that it contains [14ee7f4](https://gitlab.inria.fr/why3/why3/commit/14ee7f4912d0e18bd5831d56070376d0a5f2330c) (which I don't understand, even though I am the author), my guess is that it is not the lower bound on Gtk that matters, but the upper bound. Let see if it goes through.

**Comment by silene** [comment]
Not sure if it is actually an improvement, but at least it is no longer a compilation error:

    The following dependencies couldn't be met:
      - why3 -> lablgtk < 2.18 -> ocaml < 4.04.0

**Comment by gasche** [comment]
Yes, I went [back](https://ci.ocaml.io/log/saved/docker-build-efd5689f664d08f97102d4ddaa73e2e5/c399bf423df5a4e2a525420f5e76868963821435) to check and the failing builds where using lablgtk 2.18.5, so I suppose your guess is right.

The only remaining failure on the Travis test is due to a bug in the CI itself.

**Comment by gasche** [comment]
(I sent a possible fix for the OSX Travis bug at https://github.com/ocaml/ocaml-ci-scripts/pull/190 )

**Comment by ejgallego** [comment]
IMHO this is a bug in Coq's OPAM package and it should be fixed, by either providing a package install the byte-build of Coq [which is needed by some other users] or by restoring the previous semantics.

**Comment by gasche** [comment]
@ejgallego I think that would be nice, but this is a discussion for coqdev to have, because all Coq devs need to be aware of the backward-compatibility implications of their choices -- no matter what they decide in the end. Could you start a discussion there?

**Comment by ejgallego** [comment]
So it looks to me like https://github.com/coq/opam-coq-archive/pull/188 should be propagated to the OPAM repos.

On a related note to Coq plugin / library authors [cc: @silene ] could we stop implementing workaround to Coq problems instead of trying to address the issue upstream?

It seems the culture whenever a Coq problem is found is to "workaround it", instead of tyring to fix the problem upstream. I guess this culture comes from a past when it was harder to get fixes pushed to Coq's main repository, however, it has not been the case for a few years with Coq main repos being hosted at github.

**Pull request merged**
