### PR TITLE
Package camlp5.8.00~alpha01

### PR DESCRIPTION
**Pull request by chetmurthy**
### `camlp5.8.00~alpha01`
Preprocessor-pretty-printer of OCaml
Camlp5 is a preprocessor and pretty-printer for OCaml programs. It also provides parsing and printing tools.

As a preprocessor, it allows to:

extend the syntax of OCaml,
redefine the whole syntax of the language.
As a pretty printer, it allows to:

display OCaml programs in an elegant way,
convert from one syntax to another,
check the results of syntax extensions.
Camlp5 also provides some parsing and pretty printing tools:

extensible grammars
extensible printers
stream parsers and lexers
pretty print module
It works as a shell command and can also be used in the OCaml toplevel.

---
* Homepage: https://camlp5.github.io
* Source repo: git+https://github.com/camlp5/camlp5.git
* Bug tracker: https://github.com/camlp5/camlp5/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by mseri** [comment]
Thanks for taking care of the revdeps! Let's see how this round of CI looks like

**Comment by mseri** [comment]
The elpi failures are due to the time command on alpine, you can safely ignore them

**Comment by chetmurthy** [comment]
It seems that the continuous integration build failed by running out of time?  The others seem like elpi failures, again running out of time.

**Comment by chetmurthy** [comment]
FYI, I have prepared fixes for all three packages (elpi, ulex-camlp5, and ledit) to bring them up to working with camlp5 8.00.  They're "breaking" (would cause them to no longer work with camlp5 <= 7.99) so it will certainly take time and maybe some further work (e.g. using cppo) to make them acceptable.  The changes were anodyne, of course.

**Comment by chetmurthy** [comment]
Hi, I'm unclear if there's anything else I need to fix?  Could you please advise?  Am I missing something from the test-failure logs?  Thanks.

**Comment by mseri** [comment]
Looks good to me. Thanks for the effort

**Pull request merged**
