### PR TITLE
Remove p3

### PR DESCRIPTION
**Pull request by tomjridge**
Future developments can be found at http://www.tom-ridge.com/parsing.html

### CODE REVIEW

**Comment by avsm** [comment]
Are you sure you don't want to leave these here for existing users? We typically do not delete older releases from OPAM stable once published.

**Comment by dbuenzli** [comment]
@avsm at least if @tomjridge feels he won't develop this further the package should be marked as deprecated. How exactly is however still unclear https://github.com/ocaml/opam/issues/2046

**Comment by tomjridge** [comment]
I guess I was worried about changes to ocaml causing maintenance work. For example, when the string lexer changed, p3 compilation broke because some comments contained {xxx| patterns. In addition, I doubt there are any users. And frankly I feel embarrassed about the quality of the implementation - I don't think I ever really got things right. So, all in all, just deleting it seemed cleanest.

**Comment by avsm** [comment]
Many thanks for the clarification @tomjridge! Deleting it now...

Regarding the ocaml version causing maintenance, you can restrict the set of compilers that the package installs to.  I just wanted to make sure you were aware of that, but the remainder of your reasons are also perfectly valid for deletion (and harder to fix using opam constraints :-)

**Pull request merged**
