### PR TITLE
atd, atdgen-runtime, atdgen, atdj version 1.13.0.

### PR DESCRIPTION
**Pull request by mjambon**
atdgen-runtime is a new package. All these packages are now derived from the same git repository and use the same version.

There will be issues with atdj since its version is going from 20151001.01.2 down to 1.13.0. Waiting for CI to see how bad it looks.

### CODE REVIEW

**Comment by avsm** [comment]
Looks like a few constraints are needed:


```
#=== ERROR while compiling atdj.20151001.01.2 =================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.05.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.05.0/.opam-switch/build/atdj.20151001.01.2
# command              /usr/bin/make
# exit-code            2
# env-file             ~/.opam/log/atdj-18-874a9e.env
# output-file          ~/.opam/log/atdj-18-874a9e.out
### output ###
# omake
# *** omake: reading OMakefiles
# --- Checking for ocamlfind... (found /home/opam/.opam/4.05.0/bin/ocamlfind)
# --- Checking for ocamlc.opt... (found /home/opam/.opam/4.05.0/bin/ocamlc.opt)
# --- Checking for ocamlopt.opt... (found /home/opam/.opam/4.05.0/bin/ocamlopt.opt)
# --- Checking for ocamldep.opt... (found /home/opam/.opam/4.05.0/bin/ocamldep.opt)
# --- Checking for ocamllex.opt... (found /home/opam/.opam/4.05.0/bin/ocamllex.opt)
# --- Checking whether ocamlc understands the "z" warnings... (yes)
# --- Checking whether ocamlopt can create cmxs plugins... (yes)
# --- Checking for latex... (FAILED - no latex found)
# *** omake: finished reading OMakefiles (0.14 sec)
# --- Checking if ocamldep understands -modules... (yes)
# - build . atdj_env.o
# + ocamlfind ocamlc -package str,unix,atd,atdgen -dtypes -g -g -I . -c atdj_env.ml
# File "atdj_env.ml", line 15, characters 27-44:
# Error: Unbound module Atd_ast
```

**Comment by kit-ty-kate** [comment]
ping @mjambon

**Comment by mjambon** [comment]
Still haven't had time to look into this.

**Comment by mjambon** [comment]
camelus is deeply unhappy because I added version constraints on a bunch of old opam files that don't pass opam lint. What's a good practice here? (delete old packages? ignore opam-lint errors?)

**Comment by mjambon** [comment]
@kit-ty-kate thanks! I removed the `build-test` from these old packages. I think we're getting close.

**Comment by kit-ty-kate** [comment]
Mmh there are some failures but most are unrelated or are failures related to old versions of atdgen that can be fixed later. Let's merge this in the meantime. Thanks!

**Pull request merged**
