### PR TITLE
old websockets needs an old version of ocplib-endian

### PR DESCRIPTION
**Pull request by samoht**
/cc @vbmithr

### CODE REVIEW

**Comment by mseri** [comment]
TheCI error now is because the old cohttp wasn’t safe-string compliant. I guess we cannot do much about that. Same for stog

**Comment by mseri** [comment]
Stog 0.14.0 fails in a weird way:
```
# ### checking required tools and libraries ###
# checking for xmlm... Package xmlm found with version v1.3.0, but wanted >= 1.1
# 
# You way have a look at config_check.log for details.
```

**Comment by hannesm** [comment]
@mseri I address this in #11960 -- xmlm upstream (git master, unreleased) uses since just after `v1.3.0` `%%VERSION_NUM%%` which will translate to `1.3.x` / `.1.4.x` (without leading `v`) in the future.

**Comment by hannesm** [comment]
though travis complains about build-test in cohttp 0.20.2 / 0.21.1 with 4.06.0

**Comment by samoht** [comment]
@hannesm I am looking at these now

**Comment by samoht** [comment]
The remaining issues should be fixed by https://github.com/ocaml/opam-repository/pull/11962 and https://github.com/ocaml/opam-repository/pull/11963

**Comment by mseri** [comment]
There may or may not be further failures in the stog revdeps. What we see currently is an infrastructure error: 
```
docker: Error: No such image: sha256:40a245857eea654981be4e612cc80dde9e0979615f394386af9b0859be6eb8b2.
```

I have tried rerunning all or part of the build multiple times without success, I keep getting the same error. I think it's good to merge

**Pull request merged**
