### PR TITLE
functoria-runtime: add upper bounds to prepare for the MirageOS 4

### PR DESCRIPTION
**Pull request by samoht**
Extracted from #20558

### CODE REVIEW

**Comment by samoht** [comment]
The revdeps tests are getting a bit crazy here (I am not sure to understand why the full universe is getting tested as revdeps of functoria-runtime.3.0.1...) so I'll merge this quickly.

**Comment by hannesm** [comment]
this looks good to me.

**Comment by kit-ty-kate** [comment]
> I am not sure to understand why the full universe is getting tested as revdeps of functoria-runtime.3.0.1...

functoria-runtime.3.0.1 --> mirage-runtime --> mirage-crypto-rng.0.7.0 --> {tls,x509,*} (explosion)

**Comment by kit-ty-kate** [comment]
@hannesm is there a reason why mirage-crypto-rng.0.7.0 is the only version of mirage-crypto-rng to depend on mirage-runtime?

**Comment by hannesm** [comment]
@kit-ty-kate yes, that one bundled the package that is nowadays separate as mirage-crypto-rng-mirage. since it is mostly of historic interest, we can also remove it (or mark it unavailable if that is sufficient).

**Pull request merged**
