### PR TITLE
Updated pcre, fixing callout bug

### PR DESCRIPTION
**Pull request by mmottl**

### CODE REVIEW

**Comment by yallop** [comment]
The commit/PR description ("Updated Lacaml") don't match the contents (updated pcre-ocaml).

**Comment by mmottl** [comment]
That's funny.  I've been making too many releases the last couple of days for both Lacaml and pcre-ocaml.  No wonder I got confused.  Is there anything I can or should do to fix the log entry?  I guess nobody really cares...

**Comment by yallop** [comment]
You should be able to edit the commit message like this

```
  git commit --amend -m 'Add pcre.7.2.3'
```

and then force-push the branch:

```
  git push -f
```

**Comment by mmottl** [comment]
Thanks, I wasn't sure whether it would still be safe to do so.  I've done as suggested.

**Comment by yallop** [comment]
Thanks!

**Pull request merged**
