### PR TITLE
ppx_orakuda, ppx_test: relaxing ocaml-version constraints

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by yallop** [comment]
Perhaps the `ppxx` constraint needs relaxing, too:

```
Package is unavailable on this configuration, skipping:
The following dependencies couldn't be met:
  - ppx_orakuda -> ppxx < 1.4.0
Your request can't be satisfied:
  - ppxx<1.4.0 is not available because your system doesn't comply with ocaml-version = "4.03.0".
```

```
Package is unavailable on this configuration, skipping:
The following dependencies couldn't be met:
  - ppx_test -> ppxx >= 1.3.0
Your request can't be satisfied:
  - ppxx>=1.3.0 is not available because your system doesn't comply with ocaml-version = "4.03.0".
```

**Comment by camlspotter** [comment]
ppxx.1.3.1 is now in the repo, so I guess the issue is now gone.

**Comment by camlspotter** [comment]
Wiered,  what's this?

```
# *** omake error:
#    File Omake_builtin: line 0, characters 0-0
#    include file Pervasives not found in OMAKEPATH
#       (OMAKEPATH[] = "." : Sequence /home/travis/.opam/4.04.0/lib/omake : Dir)
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=/home/travis/.opam/4.04.0\"' terminated with error code 123")
```

**Comment by camlspotter** [comment]
Does this relate with the recent update of omake?  Apparently it has some problem and not yet solved:  https://github.com/ocaml/opam-repository/pull/7876

**Comment by yallop** [comment]
I've restarted the build.

**Comment by yallop** [comment]
There's a [new failure](https://travis-ci.org/ocaml/opam-repository/jobs/177847739):

```
# File "_none_", line 1:
# Error: Files ppx_test.cmo and /home/travis/.opam/4.04.0/lib/ppxx/ppxx.cmo
#        make inconsistent assumptions over interface Ppxx
# *** omake: targets were not rebuilt because of errors:
#    ppx/ppx_test.run
#       depends on: ppx
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=/home/travis/.opam/4.04.0\"' terminated with error code 2")
```

**Comment by yallop** [comment]
The failure occurred after #7876 was merged.

**Comment by yallop** [comment]
I've restarted the failing jobs.

**Comment by yallop** [comment]
The jobs [failed again](https://travis-ci.org/ocaml/opam-repository/jobs/177847742):

```
# [...]
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/travis/.opam/4.03.0/lib/ocaml, /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/travis/.opam/4.03.0/lib/ocaml, /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/travis/.opam/4.03.0/lib/ocaml, /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs
# File "_none_", line 1:
# Error: Files ppx_test.cmo and /home/travis/.opam/4.03.0/lib/ppxx/ppxx.cmo
#        make inconsistent assumptions over interface Ppxx
# *** omake: targets were not rebuilt because of errors:
#    ppx/ppx_test.run
#       depends on: ppx
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=/home/travis/.opam/4.03.0\"' terminated with error code 2")
```

@camlspotter, could you investigate?

**Comment by camlspotter** [comment]
Thanks, let me check

**Comment by camlspotter** [comment]
Strange, it succeeds locally:

```
$ opam install ppx_test
$ eval `opam config env`
$ opam install ppx_test
The following actions will be performed:
  - install ppxx     1.3.0                              [required by ppx_test]
  - install ppx_test 1.4.0
===== 2 to install =====
Do you want to continue ? [Y/n] 
y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] https://opam.ocaml.org/archives/ppx_test.1.4.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ppxx.1.3.0+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-> installed ppxx.1.3.0
-> installed ppx_test.1.4.0
Done.
```

**Comment by camlspotter** [comment]
Sorry but let me send a fresh PR to see the problem still persists...

**Comment by camlspotter** [comment]
Turned out I am using `omake.0.9.8.6-0.rc1` and Travis uses `omake.0.10.1`.

**Comment by camlspotter** [comment]
Let me remove `omake.0.10.1` in this PR.  We need absolutely need this.

**Comment by yallop** [comment]
@rgrinberg: are you happy for `omake.0.10.1` to be removed?

**Comment by camlspotter** [comment]
If I could have some free time, I could help fixing `omake.0.10.1`, but sorry, I am extremely busy for now unfortunately...

**Comment by rgrinberg** [comment]
>@rgrinberg: are you happy for `omake.0.10.1` to be removed?
>

Give me a few hours to try and understand the issues here first. At least so
that I can make some bug reports for omake.

I just installed ppxx, ppx_test, ppx_orakuda on 4.03 and omake 0.10.1 locally
and it worked reasonably well. So it's not like things are completely broken.

**Comment by camlspotter** [comment]
Which version of opam do you use?

**Comment by rgrinberg** [comment]
@camlspotter I'm using 1.2.2

**Comment by camlspotter** [comment]
Uninstalling of omake does not remove files under `$HOME/.opam/<version>/lib/omake/`.  Could you make sure that your omake is not using old files installed by a previous installation?

In my OS X, with opam.1.2.2, switch 4.04.0:

```
# make sure omake uninstalled
$ opam remove omake 
[WARNING] Directory /Users/jun/.opam/4.04.0/lib/omake is not empty, not removing
⊘  removed   omake.0.10.1

# make sure the lib dir is empty
$ /bin/rm -rf $HOME/.opam/4.04.0/lib/omake

# reinstall omake
$ opam install omake.0.10.1
∗  installed omake.0.10.1
Done.

# see lib is not populated enough
$ ls $HOME/.opam/4.04.0/lib/omake
opam.config                                                       <==== Not enough files!!
```

**Comment by rgrinberg** [comment]
@camlspotter Thanks for the pointer. Let me investigate and see how easy is the fix.

**Comment by camlspotter** [comment]
Please check https://github.com/ocaml/opam-repository/pull/7964 .  I have installed `omake.0.10.1` with opam.1.2.2 and a *clean* switch 4.03.0.  It does not install its important library files.

**Comment by rgrinberg** [comment]
> Uninstalling omake does not remove files under $HOME/.opam/<version>/lib/omake/. Could you make sure that your omake is not using old files installed somehow by a previous installation?

That's a great point. Unfortunately, that's a problem with omake 0.9.8.6 as well:

```
opam remove omake
The following actions will be performed:
  ⊘  remove omake 0.9.8.6-0.rc1

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[WARNING] Directory /home/rgrinberg/.opam/omake2/lib/omake is not empty, not removing
⊘  removed   omake.0.9.8.6-0.rc1
Done.
```

I will look for a fix for this ASAP, but this doesn't seem critical given this.

**Comment by yallop** [comment]
This has been superseded by #7964.

**Pull request closed without merging**
