### PR TITLE
[new release] fftw3 (0.8.2)

### PR DESCRIPTION
**Pull request by Chris00**
Binding to the famous Fast Fourier Transform library FFTW

- Project page: <a href="https://github.com/Chris00/fftw-ocaml">https://github.com/Chris00/fftw-ocaml</a>
- Documentation: <a href="https://Chris00.github.io/fftw-ocaml/doc">https://Chris00.github.io/fftw-ocaml/doc</a>

##### CHANGES:

- Fix enabling the single precision module `Fftw3.S`.
- Enable robustness tests at compile time (thanks to Dune.configurator).
- Switch to Dune.
- Rely on a `conf-fftw3` package for the presence of the C FFTW3 library.

### CODE REVIEW

**Comment by Chris00** [comment]
@kit-ty-kate I respected [your wish](https://github.com/ocaml/opam-repository/pull/12037#discussion_r191082400).  `;-)`

**Comment by kit-ty-kate** [comment]
Thanks! :)

There was a missing dependency on the conf-* package which I taken care of. Error was:
```
#=== ERROR while compiling conf-fftw3.1 =======================================#
"pkg-config": command not found.
```
Let's wait for the CI

**Comment by kit-ty-kate** [comment]
Thanks a lot !!

**Comment by Chris00** [comment]
My pleasure! :-)

**Pull request merged**
