### PR TITLE
[new release] cstruct-async, ppx_cstruct, cstruct, cstruct-unix, cstruct-sexp and cstruct-lwt (4.0.0)

### PR DESCRIPTION
**Pull request by avsm**
Access C-like structures directly from OCaml

- Project page: <a href="https://github.com/mirage/ocaml-cstruct">https://github.com/mirage/ocaml-cstruct</a>
- Documentation: <a href="https://mirage.github.io/ocaml-cstruct/">https://mirage.github.io/ocaml-cstruct/</a>

##### CHANGES:

- Sexplib is now an optional library for the base `Cstruct` module.
  A new `Cstruct_sexp` module has been introduced with the serialiser
  functions, contained within the `cstruct-sexp` opam package.

  To convert old code, simply use `Cstruct_sexp.t` instead of
  `Cstruct.t` in a record type for which you are using `[@@deriving sexp]`.
  This is a type alias to `Cstruct.t` but also has the right
  sexp-conversion functions in scope.  There is an example of this
  in the `ppx_test/with-sexp` directory in the source repo.

  When you have converted and released your library, add an
  opam constraint of `cstruct {>="4.0.0"}` to your own opam
  packages to ensure that they pick up this version of the library.
  (fixes mirage/ocaml-cstruct#222, @avsm)

- JavaScript stubs are now installed using the jsoo mechanism
  rather than a manual specification (mirage/ocaml-cstruct#241 @jonludlam)

- Use computed versions in opam files to ensure that dependent
  opam packages such as cstruct-async get the same base version
  of cstruct to avoid mismatches. (@avsm)

- Add a ppx test suite to checks that all error paths in ppx
  handling are reachable and have meaningful location info (mirage/ocaml-cstruct#238 @emillon)

### CODE REVIEW

**Comment by mseri** [comment]
4.03-4.05 are failing with:
```
===== Installing package ======
The following dependencies couldn't be met:
  - ppx_cstruct → cstruct-unix >= 4.0.0 → ocaml >= 4.06.0
      base of this switch (use `--unlock-base' to force)
```

Do you want to lower bound ocaml in `ppx_cstruct` opam file?

**Comment by mseri** [comment]
I know you are ludicrously busy, but please have also a look at ther revdeps: lots of things are failing due to the sexp split. It may be important to add upper bounds before merging this PR.

**Comment by avsm** [comment]
Thanks for the triage @mseri! I'll look the revdeps and fixes now

**Comment by avsm** [comment]
The ppx failure is a bit frustrating, since only cstruct-unix depends on ocaml>=4.06, but the CI failing since its trying to install all packages...

**Comment by avsm** [comment]
This nocrypto failure is concerning

```
# File "src/nocrypto.cmx", line 1:
# Error: The implementation (obtained by packing)
#        does not match the interface src/nocrypto.mli:
#        ...
#        In module Hash:
#        Values do not match:
#          val hash_of_sexp : Ppx_sexp_conv_lib.Sexp.t -> hash
#        is not included in
#          val hash_of_sexp : Sexplib.Sexp.t -> hash
#        File "src/nocrypto.mli", line 217, characters 2-43:
#          Expected declaration
#        File "src/hash.ml", line 114, characters 0-86: Actual declaration
```

**Comment by emillon** [comment]
Related issue: https://github.com/mirleft/ocaml-nocrypto/issues/156

**Pull request merged**
