### PR TITLE
[compilers] Add 4.06.0+32bit compiler.

### PR DESCRIPTION
**Pull request by ejgallego**
A must for js_of_ocaml users.

### CODE REVIEW

**Comment by ejgallego** [comment]
Ahhh, unfortunately it failed at the last compilation step.... looking more into it. Should I file an upstream bug if the 32bits build is broken?

**Comment by avsm** [comment]
Yes please, to the upstream bug. It may be able to go into a point release.

**Comment by ejgallego** [comment]
https://caml.inria.fr/mantis/view.php?id=7679

**Comment by ejgallego** [comment]
So indeed it seems I had a problem with my OPAM metadata, I just tested this branch on Linux [by building jsCoq with 4.06.0+32bit which is far from a trivial operation] and it seems to work OK.

I'm afraid I am not able to test on OSX, but the recipe is the same than in `4.05.0+32bit`.

**Pull request merged**
