### PR TITLE
Add shared-block-ring.1.0.0

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave.scott@citrix.com>

### CODE REVIEW

**Comment by avsm** [comment]
```
# ocamlfind: Package `sexplib.syntax' not found
# W: Field 'pkg_sexplib_syntax' is not set: Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d sexplib.syntax > '/tmp/oasis-0d9244.txt'' terminated with error code 2
# E: Cannot find findlib package sexplib.syntax
# E: Failure("1 configuration error")
# make: *** [setup.data] Error 1
```

need to depend on `camlp4` as well.

**Comment by djs55** [comment]
Thanks! I really should have tested this in my own opam-repo-dev first...

On Fri, Mar 6, 2015 at 10:53 AM, Anil Madhavapeddy <notifications@github.com
> wrote:

> # ocamlfind: Package `sexplib.syntax' not found
> # W: Field 'pkg_sexplib_syntax' is not set: Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d sexplib.syntax > '/tmp/oasis-0d9244.txt'' terminated with error code 2
> # E: Cannot find findlib package sexplib.syntax
> # E: Failure("1 configuration error")
> # make: *** [setup.data] Error 1
>
> need to depend on camlp4 as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocaml/opam-repository/pull/3677#issuecomment-77541250>
> .
>



-- 
Dave Scott

**Comment by avsm** [comment]
mirage/mirage-dev is also useful for this if slightly extended to test incoming pulls.

**Comment by djs55** [comment]
On 4.00.1
```
# File "lib/ring.ml", line 192, characters 8-16:
# Error: The record field label C.producer belongs to the type
#          C.producer = Common(B).producer
#        but is mixed here with labels of type t
# Command exited with code 2.
### stderr ###
```
I think it needs 4.01.0+

**Comment by djs55** [comment]
OK, OCaml 4.00.1 failed even though there's an ocaml-version constraint for 4.01.0. Perhaps the travis script only copes with the output of opam 1.2?

**Pull request merged**
