### PR TITLE
new file:   packages/hts_shrink/hts_shrink.3.0.1/opam

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
According to the `molenc` repository, this package requires `molenc >= 11.1.1`. However no such version exist in opam-repository
```

#=== ERROR while compiling hts_shrink.3.0.1 ===================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://github.com/UnixJunkie/hts_shrink/archive/v3.0.1.tar.gz)
# path                 ~/.opam/4.10/.opam-switch/build/hts_shrink.3.0.1
# command              ~/.opam/4.10/bin/dune build -p hts_shrink -j 72
# exit-code            1
# env-file             ~/.opam/log/hts_shrink-23-2baaf0.env
# output-file          ~/.opam/log/hts_shrink-23-2baaf0.out
### output ###
#       ocamlc src/.dscan.eobjs/byte/dune__exe__Dscan.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.dscan.eobjs/byte -I /home/opam/.opam/4.10/lib/batteries -I /home/opam/.opam/4.10/lib/bst -I /home/opam/.opam/4.10/lib/bytes -I /home/opam/.opam/4.10/lib/cpm -I /home/opam/.opam/4.10/lib/cpu -I /home/opam/.opam/4.10/lib/dolog -I /home/opam/.opam/4.10/lib/minicli -I /home/opam/.opam/4.10/lib/molenc -I /home/opam/.opam/4.10/lib/num -I /home/opam/.opam/4.10/lib/ocaml/threads -I /home/opam/.opam/4.10/lib/parany -no-alias-deps -open Dune__exe -o src/.dscan.eobjs/byte/dune__exe__Dscan.cmo -c -impl src/dscan.ml)
# File "src/dscan.ml", line 85, characters 5-17:
# 85 |      FpMol.to_out output test_mol);
#           ^^^^^^^^^^^^
# Error: Unbound value FpMol.to_out
```

**Comment by UnixJunkie** [comment]
ok, I have to update the molenc in opam-repos first.

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml/opam-repository/pull/16963

**Comment by UnixJunkie** [comment]
I will resend this PR later on.

**Pull request closed without merging**
