### PR TITLE
BAP 1.4 Release

### PR DESCRIPTION
**Pull request by ivg**
In this attempt we addressed the 429 problem by mirroring most of our packages. The failures are still expected, since the base docker image that is  used in the OPAM CI system doesn't have the necessary LLVM version (we work with 3.4,3.8,4.0,5.0). We are testing internally using Vagrant and Docker with Ubuntu ([Trusty][1] and [Xenial][2] images are uploaded to the hub) using 4.03, 4.04, and 4.05 versions of the OCaml compiler.

[1]: https://hub.docker.com/r/binaryanalysisplatform/trusty-bap-1.4/
[2]: https://hub.docker.com/r/binaryanalysisplatform/xenial-bap-1.4/

Release Notes
=============

Features
--------

- PR#762 MIPS and MIPS64 lifters
- PR#739 PowerPC and PowerPC64 lifters
- PR#744 LLVM 5.0 compatibility
- PR#734 BARE Binary Analysis Rule Engine
- PR#734 New Taint Analysis Framework
- PR#734 Primus Lisp 2.0 with symbols and methods
- PR#734 Recipes
- PR#734 Primus Test Framework
- PR#734 Dataflow and Abstract Interpretation Framework
- PR#734 Progress Reports and Profilers
- PR#773 New primitives for BML

Bug fixes
---------

- PR#782 Incorrect error handling in x86 lifter
- PR#734 Failure to decode ICC binaries
- PR#772 Fixes equiv type in Graphlib
- PR#771 Unhardcodes llvm backed in the linear sweep disassembler
- PR#770 Fixes the memory printer
- PR#761 Fixes handling relocations in reconstructor
- PR#759 Fixes race condition in the source merge procedure
- PR#758 Restores the source-type command line option
- PR#755 Proper handling of tail calls in IR lifter
- PR#754 Fixes segment registers in mov instruction
- PR#746 Fixes xor in the BIL simplfication procedure
- PR#728 Fixes flag calculation in the x86 sub instruction
- PR#727 Fixes numerous missed sign extensions in x86 lifter
- PR#725 Adds modulo operation to x86 rot/rol instructions
- PR#724 Fixes operands order in the x86 xadd instruction
- PR#723 Fixes segment duplication

### CODE REVIEW

**Comment by ivg** [comment]
I'm digging through the build logs. Still have quite a few connectivity issues, mostly from Janestreet stuff (e.g., bin_prot). 

Though found a valid issue - a missing dependency for the `bare` package, it's oasis, we didn't notice it on our CI as we never installed it alone. Will push an update soon.

Also, I have an idea how to fix the llvm issue, we're depexting llvm-3.4 on debian by default, since this is the version that is available on most common debian distributions nowdays. But maybe it's time to switch to at least 3.8.

**Comment by ivg** [comment]
Also, a strange [failure][1]:
```
OCI runtime create failed: container_linux.go:295: starting container process caused "process_linux.go:399: container init caused \"process_linux.go:382: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2018-03-05T22:21:04Z\\\\\\\" level=fatal msg=\\\\\\\"failed to update store for object type *libnetwork.sbState: timeout\\\\\\\"\\\\n\\\"\"": unknown
```

[1]: https://ci.ocamllabs.io/log/saved/docker-build-79521d04a61d9abe323b01474956f3ae/aa4b5be782445a640fd33abc8505f8633addb7fe

**Comment by jpdeplaix** [comment]
I don't have the hand of the CI machine so I can't help but ping @avsm for the disk space problem.

The "unable to obtain sources" problem is fixed by using a local cache in the ARM64 CI which I have control over but for some reasons opam2 wants to install outdated jst packages due to this issue: https://github.com/ocaml/opam/issues/3229.

Otherwise I've spotted an issue on regular.1.4.0 and bap-frames.2.1.1:
```
#=== ERROR while installing regular.1.4.0 =====================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/4.06.1/build/regular.1.4.0
# compiler     4.06.1
# exit-code    2
# env-file     /home/travis/.opam/4.06.1/build/regular.1.4.0/regular-10843-c35af0.env
# stdout-file  /home/travis/.opam/4.06.1/build/regular.1.4.0/regular-10843-c35af0.out
# stderr-file  /home/travis/.opam/4.06.1/build/regular.1.4.0/regular-10843-c35af0.err
### stdout ###
# Error: Signature mismatch:
# [...]
#          val unsafe_blit :
#            src:t -> src_pos:int -> dst:t -> dst_pos:int -> len:int -> unit
#        is not included in
#          val unsafe_blit : (bytes, t) Blit.blit
#        File "src/blit_intf.ml", line 137, characters 9-42:
#          Expected declaration
#        File "lib/regular/regular_bytes.ml", line 37, characters 6-17:
#          Actual declaration
# Command exited with code 2.
### stderr ###
# make: *** [build] Error 1
```
```
#=== ERROR while installing bap-frames.2.1.1 ==================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/system/build/bap-frames.2.1.1
# compiler     system (4.02.3)
# exit-code    2
# env-file     /home/travis/.opam/system/build/bap-frames.2.1.1/bap-frames-12614-52d546.env
# stdout-file  /home/travis/.opam/system/build/bap-frames.2.1.1/bap-frames-12614-52d546.out
# stderr-file  /home/travis/.opam/system/build/bap-frames.2.1.1/bap-frames-12614-52d546.err
### stdout ###
# [...]
# /home/travis/.opam/system/bin/ocamlfind ocamldep -package bap -package bap-traces -package core_kernel -package piqirun.pb -package ppx_jane -modules lib/frame_events.ml > lib/frame_events.ml.depends
# /home/travis/.opam/system/bin/ocamlfind ocamldep -package bap -package bap-traces -package core_kernel -package piqirun.pb -package ppx_jane -modules lib/frame_mach.ml > lib/frame_mach.ml.depends
# /home/travis/.opam/system/bin/ocamlfind ocamldep -package bap -package bap-traces -package core_kernel -package piqirun.pb -package ppx_jane -modules lib/frame_reader.mli > lib/frame_reader.mli.depends
# /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package bap -package bap-traces -package core_kernel -package piqirun.pb -package ppx_jane -I lib -o lib/frame_reader.cmi lib/frame_reader.mli
# /home/travis/.opam/system/bin/ocamlfind ocamldep -package bap -package bap-traces -package core_kernel -package piqirun.pb -package ppx_jane -modules lib/frame_reader.ml > lib/frame_reader.ml.depends
# /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package bap -package bap-traces -package core_kernel -package piqirun.pb -package ppx_jane -I lib -o lib/frame_arch.cmo lib/frame_arch.ml
# + /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package bap -package bap-traces -package core_kernel -package piqirun.pb -package ppx_jane -I lib -o lib/frame_arch.cmo lib/frame_arch.ml
# File "lib/frame_arch.ml", line 105, characters 15-31:
# Error: Unbound value Variants.to_rank
# Command exited with code 2.
### stderr ###
# W: Cannot find source file matching module 'Frame_piqi' in library bap-frames.
# W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
# W: Cannot find source file matching module 'Frame_piqi' in library bap-frames.
# W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
# E: Failure("Command ''/usr/bin/ocamlbuild' lib/bap-frames.cma lib/bap-frames.cmxa lib/bap-frames.a lib/bap-frames.cmxs plugin/bap-plugin-frames.cma plugin/bap-plugin-frames.cmxa plugin/bap-plugin-frames.a plugin/bap-plugin-frames.cmxs -tag debug' terminated with error code 10")
# make: *** [build] Error 1
```

There is an other issue with Travis failing because it takes too much time but that's just because the PR is slightly too big. If you could cut in 2 or 3 PRs next time (as jst does) it would be perfect. But it would still work with mirage-ci though, so no worries if you can't do that for dependency reasons.

**Comment by ivg** [comment]
Also, apparently jbuilder may have [a leaking fd problem][1] or someone else have and `jbuilder` dies of starvation, looping in @rgrinberg.

```
# [...]
# Raised at file "src/with_required_by.ml", line 50, characters 2-113
# Called from file "src/fiber/fiber.ml", line 303, characters 6-18
# Fatal error: exception Sys_error("_build/.to-delete-in-source-tree: Too many open files")
# Raised by primitive operation at file "pervasives.ml", line 315, characters 29-55
# Called from file "src/io.ml", line 18, characters 11-32
# Called from file "src/build_system.ml", line 1121, characters 2-28
# Called from file "pervasives.ml", line 540, characters 30-33
# Called from file "pervasives.ml" (inlined), line 542, characters 20-39
# Called from file "pervasives.ml", line 545, characters 2-15
# Called from file "bin/main.ml", line 1409, characters 19-25
```

[1]: https://travis-ci.org/ocaml/opam-repository/jobs/350009250#L5930

**Comment by ivg** [comment]
> Otherwise I've spotted an issue on regular.1.4.0 and bap-frames.2.1.1:

The `bap-frames` issue is legit, as the package was under constraint so it was trying to compile with the older core-kernel. I've added some constraints on it. 

Also it looks like that we have an issue with `ocaml-version >= 4.06`, honestly we didn't test on it, as I said we test only on 4.03, 4.04, and 4.05. Apparently, bap doesn't work right now for 4.06 and greater for two reasons

1) the regular library (that also provides a compatibility layer for the Bytes module) somewhere relies on type equality between `bytes` and `string`. 
2) utop.1.19.3 is not available for 4.06 and above, and it is the last non-broken version of utop. 

So my next steps would be to upgrade _all_ our packages upper bound for the compiler version. It will require some perl, so I'll be back.

**Comment by rgrinberg** [comment]
The problem isn't leaking but rather acquiring too many FD's all at once. We think resolved this problem in master and we have a release with a fix incoming.

**Comment by ivg** [comment]
Ok, I've updated the upper bound of all our packages to 4.05 including.

**Comment by ivg** [comment]
I don't see anymore legit failures. Those that are on `ci/datakit/1` all due to the absence (expectable) of IDA Pro on the CI servers or a failure to download external packages (usually camomile). Concerning the `arm64` version it fails either from the `No space left` error, or for some weird compilation errors in dependencies. 

@jpdeplaix, can you please merge this PR.

**Comment by jpdeplaix** [comment]
Ok I cannot anything but trust you that it doesn't break any revdeps at this point. Next time could you make two PRs with one with the packages depending on ```bap-ida-python``` ? So that next time packages that can be built can be checked completely.

Thanks a lot.

**Comment by ivg** [comment]
> Next time could you make two PRs with one with the packages depending on bap-ida-python?

I think I can relax our checks and delay them until runtime. 

> Ok I cannot anything but trust you that it doesn't break any revdeps at this point. 

So far all the revdeps are part of bap, there are no packages in the official opam repository that depends on bap.

**Pull request merged**
