### PR TITLE
Debug OSX Travis builds

### PR DESCRIPTION
**Pull request by yallop**
Don't merge this, please.

### CODE REVIEW

**Comment by yallop** [comment]
See: https://github.com/ocaml/opam/issues/2164

**Comment by yallop** [comment]
Disabling the `OPAMFETCH` override [seems](https://travis-ci.org/ocaml/opam-repository/jobs/64328100) to fix the OSX build.

**Comment by yallop** [comment]
@avsm, do you remember what was causing curl to break on OSX (d64c277)?

**Comment by dsheets** [comment]
https://github.com/ocaml/opam/issues/2006

**Comment by samoht** [comment]
@AltGr or @yallop it is possible to refresh that PR to fix the OSX build?

**Comment by yallop** [comment]
@samoht: let's see whether c20894f helps.

**Comment by yallop** [comment]
Closing this.  See #4296 for the fix/workaround.

**Pull request closed without merging**
