### PR TITLE
Move away from git url for portia.

### PR DESCRIPTION
**Pull request by rixed**

### CODE REVIEW

**Comment by lefessan** [comment]
Thanks !

**Comment by dsheets** [comment]
On OS X:
```
### stdout ###
# sed -e 's|@PLUGINDIR@|/usr/lib/portia|g' main.fwi > main.fw
# Using Funnelweb to build portiaLog.ml :-(
### stderr ###
# Makefile:44: fwdepend: No such file or directory
# Makefile:61: depend: No such file or directory
# /bin/sh: fw: command not found
# make: *** [portiaLog.ml] Error 127
```

If you could either mark the package as not available on OS X (`"darwin"`) or correct the issue using the metadata (or a small patch), it would be appreciated. Otherwise, we will merge this as is.

**Comment by rixed** [comment]
The problem is, funnelweb a very old program and literate programming being not very popular this is not packaged for OSX, not even in brew.
So I could either:
1- mark it unavailable on OSX, but it should be marked as unavailable everywhere but on debian and ubuntu ;
2- package funnelweb in opam but we may not want to start packaging every dependencies in opam (although I did this in the past for a pet project and opam did  ery well) ;
3- ship the preprocessed source code ;
4- remove portia from opam because frankly I'm the only user :-)

Let me try option 3 which seems both correct and easy.

**Comment by dsheets** [comment]
The build is still looking for `fwdepend`, `depend`, and `fw`, it seems.

**Comment by rixed** [comment]
fwdepend and depend are OK because the Makefile know how to generate those.
the fact that it was still looking for fw (funnelweb) was because some of the documentation was updated by the makefile with some configuration, thus triggering the rebuild of the sources.
It's fixed: now the doc should not be touched at all by the makefile, therefore the pre-generated source files should be enough.

**Comment by rixed** [comment]
If I keep failing at bootstrapping another option is to remove portia, since I'm probably the only user :)

**Comment by dsheets** [comment]
LGTM. Thanks!

**Pull request merged**
