### PR TITLE
Add graphics dependency for async_graphics

### PR DESCRIPTION
**Pull request by lpw25**
This should hopefully address #5311

### CODE REVIEW

**Comment by dbuenzli** [comment]
The [V2.0 errors](https://ci.ocaml.io/log/saved/docker-build-54566076598f7ab202978cbf9b7eac84/0d6512f71daa33ad15dfb3bf234a8fc659e15424) seem to be due to core.109.47.00 not the package itself

**Comment by dbuenzli** [comment]
The only travis error is due to [async_unix.109.15.00](https://travis-ci.org/ocaml/opam-repository/jobs/250319897#L1051) on 4.00.1. I don't know if people want to fix these errors. But as far as I'm concerned @lpw25 job is over here and this can be merged.

**Comment by samoht** [comment]
Would it be possible to also fix the camelus errors?

**Comment by samoht** [comment]
Thanks! unfortunately the `dev-repo` field is now duplicated!

**Comment by lpw25** [comment]
Oops. Fixed.

**Pull request merged**
