### PR TITLE
Add other bindings to Cordova plugins.

### PR DESCRIPTION
**Pull request by dannywillems**
I added .git after the dev-repo name as asked for ocaml-cordova.

I also changed ocaml-cordova to cordova because ocaml- prefix is not useful.

### CODE REVIEW

**Comment by dsheets** [comment]
Could you please submit these packages in smaller batches? Right now, the CI build testing system times out trying to build them all. The limiting factor is build speed on OS X which gets to `cordova-plugin-email-composer` before exceeding 50 minutes of run-time. I recommend submitting the packages in batches of no more than 10.

**Comment by dannywillems** [comment]
@dsheets Done.

**Comment by dannywillems** [comment]
@dsheets I can't do a PR by commits: each commit is added automatically to the same PR. It must be merged before other commits.

**Comment by yallop** [comment]
@dannywillems: the GitHub model is PR-per-branch, not PR-per-commit.

**Comment by dannywillems** [comment]
@yallop thanks, I didn't know it.

**Pull request merged**
