### PR TITLE
Add Unison 2.51.2

### PR DESCRIPTION
**Pull request by msprotz**

### CODE REVIEW

**Comment by msprotz** [comment]
Linux build came green, but OSX said:
```
2020-02-06 16:23:45.783 xcodebuild[32623:49512] [MT] IDELogStore: Failed to open log store at /Users/travis/Library/Developer/Xcode/DerivedData/uimacnew-gwnbfagalxkykkdkghxodwjhrvgy/Logs/Build
```
along with more related errors. Not sure what's happening, help most welcome.

**Comment by msprotz** [comment]
@juergenhoetzel or @AltGr any clue what might be happening? (still trying to figure it out)

**Comment by kit-ty-kate** [comment]
The issue seems to come from an interaction between Xcode and opam's sandbox:
```
- 2020-02-06 16:23:45.783 xcodebuild[32623:49512] [MT] IDELogStore: Failed to open log store at /Users/travis/Library/Developer/Xcode/DerivedData/uimacnew-gwnbfagalxkykkdkghxodwjhrvgy/Logs/Build
```

**Comment by kit-ty-kate** [comment]
On alpine, this package also fails with:
```
# /home/opam/.opam/4.09/.opam-switch/build/unison.2.51.2/src/fsmonitor/linux/inotify_stubs.c:41:10: fatal error: inotify_compat.h: No such file or directory
#  #include "inotify_compat.h"
#           ^~~~~~~~~~~~~~~~~~
```
but I think it can be ignored for now.

**Comment by kit-ty-kate** [comment]
Judging by the difference between the latest available version of this package and this version, it seems like the package was already broken previously on macos. It should be safe to merge unless it was previously working on macos?

**Comment by msprotz** [comment]
So it seems like the native Gtk UI doesn't build with OPAM's sandbox feature on OSX, so I disable the graphical UI altogether in favor of the text-only UI, on the basis that it's better than nothing.

Now, the build triggers an OSX linker assertion failure:

```
0  0x103d150d8  __assert_rtn + 127
1  0x103d1e485  ld::passes::stubs::arm::StubHelperAtom::StubHelperAtom(ld::passes::stubs::Pass&, ld::Atom const&, ld::Atom const*, bool) (.cold.1) + 0
2  0x103cd1ec7  ld::passes::stubs::x86_64::classic::StubHelperAtom::StubHelperAtom(ld::passes::stubs::Pass&, ld::Atom const&, ld::Atom const&, bool) + 167
3  0x103cd1db3  ld::passes::stubs::x86_64::classic::LazyPointerAtom::LazyPointerAtom(ld::passes::stubs::Pass&, ld::Atom const&, bool, bool) + 135
4  0x103cd1ce8  ld::passes::stubs::x86_64::classic::StubAtom::StubAtom(ld::passes::stubs::Pass&, ld::Atom const&, bool, bool) + 92
5  0x103ccfed7  ld::passes::stubs::Pass::makeStub(ld::Atom const&, bool) + 1779
6  0x103cd063d  ld::passes::stubs::Pass::process(ld::Internal&) + 1233
7  0x103cd09e9  ld::passes::stubs::doPass(Options const&, ld::Internal&) + 105
8  0x103bf7e41  main + 887
9  0x7fff636567fd  start + 1
A linker snapshot was created at:
	/tmp/unison-2020-01-17-091601.ld-snapshot
ld: Assertion failed: (targetAtom != NULL), function Fixup, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-530/src/ld/ld.hpp, line 780.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
```

**Comment by msprotz** [comment]
Ah, well, the CI says yes, so I guess the linker failure is now my own problem and we can merge this. Maybe I have to update my system or something, who knows.

I'm in favor of merging, at this stage. Thanks!

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
