### PR TITLE
add ocaml-solo5 0.8.5

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by avsm** [comment]
A testcase is failure a -Werror check here


```
# __V=1 /home/opam/.opam/4.14/.opam-switch/build/solo5.0.7.0/toolchain/bin/x86_64-solo5-none-static-cc  -std=c11 -Wall -Wextra -Werror -O2 -g -c test_zeropage.c -o test_zeropage.o
# + exec cc -nostdinc -mstack-protector-guard=global -isystem /home/opam/.opam/4.14/.opam-switch/build/solo5.0.7.0/toolchain/bin/../include/x86_64-solo5-none-static -I /home/opam/.opam/4.14/.opam-switch/build/solo5.0.7.0/toolchain/bin/../include/solo5 -ffreestanding -fstack-protector-strong -std=c11 -Wall -Wextra -Werror -O2 -g -c test_zeropage.c -o test_zeropage.o
# test_zeropage.c: In function 'solo5_app_main':
# test_zeropage.c:39:5: error: array subscript 0 is outside array bounds of 'uint64_t[0]' {aka 'long unsigned int[]'} [-Werror=array-bounds]
#    39 |     *addr_invalid = 1;
#       |     ^~~~~~~~~~~~~
# cc1: all warnings being treated as errors
# make[2]: *** [../Makefile.tests:38: test_zeropage.o] Error 1

```

**Comment by hannesm** [comment]
Thanks for noticing. Should we add deprecated or avoid-version flags to older solo5 releases (which include -Werror)?

**Comment by hannesm** [comment]
Apologies if I was unclear. I think this PR is good to go. The remaining CI failures are unrelated and can be fixed in other PRs:

opensuse 15.6 (maybe a CI-accept-failure for solo5 0.9)
```
# CC stub/stubs.o
# __V=1 /home/opam/.opam/4.14/.opam-switch/build/solo5.0.9.0/toolchain/bin/x86_64-solo5-none-static-cc -MT stub/stubs.o -MMD -MP -MF stub/stubs.Td -std=c11 -Wall -Wextra  -O2 -g -mno-sse -mno-mmx -mno-aes -mno-avx -mno-red-zone -DSSP_GUARD_SYMBOL=__stack_chk_guard -DSSP_FAIL_SYMBOL=__stack_chk_fail  -D__SOLO5_BINDINGS__ -ffile-prefix-map=/home/opam/.opam/4.14/.opam-switch/build/solo5.0.9.0=. -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -c stub/stubs.c -o stub/stubs.o
# + exec cc -nostdinc -mstack-protector-guard=global -isystem /home/opam/.opam/4.14/.opam-switch/build/solo5.0.9.0/toolchain/bin/../include/x86_64-solo5-none-static -I /home/opam/.opam/4.14/.opam-switch/build/solo5.0.9.0/toolchain/bin/../include/solo5 -ffreestanding -fstack-protector-strong -MT stub/stubs.o -MMD -MP -MF stub/stubs.Td -std=c11 -Wall -Wextra -O2 -g -mno-sse -mno-mmx -mno-aes -mno-avx -mno-red-zone -DSSP_GUARD_SYMBOL=__stack_chk_guard -DSSP_FAIL_SYMBOL=__stack_chk_fail -D__SOLO5_BINDINGS__ -ffile-prefix-map=/home/opam/.opam/4.14/.opam-switch/build/solo5.0.9.0=. -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -c stub/stubs.c -o stub/stubs.o
# cc: error: unrecognized command line option '-ffile-prefix-map=/home/opam/.opam/4.14/.opam-switch/build/solo5.0.9.0=.'
# make[1]: *** [GNUmakefile:77: stub/stubs.o] Error 1
# make[1]: Leaving directory '/home/opam/.opam/4.14/.opam-switch/build/solo5.0.9.0/bindings'
# make: *** [GNUmakefile:82: bindings] Error 2
```

solo5 0.7 (and likely others) should be avoided -- since they come with -Werror, so prone to failure with new C compilers being developed.

**Comment by hannesm** [comment]
see https://github.com/ocaml/opam-repository/pull/27031 for the solo5 adjustments (crossing fingers that the "lower bound" check will respect the avoid-version).

**Comment by mseri** [comment]
Thanks

**Pull request merged**
