### PR TITLE
acgtk: Fixed compilation issues with new ocaml versions

### PR DESCRIPTION
**Pull request by Nyavlys**

### CODE REVIEW

**Comment by yallop** [comment]
The OS X build is failing:

```
#=== ERROR while installing bolt.1.4 ==========================================#
[...]
# sh: /Users/travis/.opam/system/bin/camlp4of: No such file or directory
```

Perhaps there's a missing dependency on `camlp4`.

**Comment by Nyavlys** [comment]
Yes, I noticed. But I don't currently have an access to an OS X system. I'll try to investigate this, but it will probably take more time.

But I can't really understand why Bolt (not acgtk) fails only on OS X. I would expect the same error to arise on Linux as well. Do you have an explanation?

**Comment by yallop** [comment]
I think that camlp4 is installed by default in the Linux VMs.

**Comment by yallop** [comment]
I'm going to merge this as it is, and the problem with bolt can be addressed separately.

**Pull request merged**
