### PR TITLE
Update mlmpfr package releases

### PR DESCRIPTION
**Pull request by thvnx**
This patch updates all mlmpfr releases with bugfixes.

### CODE REVIEW

**Comment by thvnx** [comment]
See https://github.com/thvnx/mlmpfr.

**Comment by thvnx** [comment]
All the failures are expected: mpfr C library isn't installed on the system, or, it is, but its not the right version (the package checks for it, then fails if not compatible).

**Comment by kit-ty-kate** [comment]
This error message doesn't seem expected though:
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - mlmpfr.4.0.1:
            https://github.com/thvnx/mlmpfr/archive/mlmpfr.4.0.1.tar.gz (Bad checksum, expected md5=5d61b9f932cb3b980c0ed9e081f447c0)
```

**Comment by thvnx** [comment]
I didn't see it, thanks!

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
