### PR TITLE
oscisgen-start 6.3.0: remove upper bound on eliom to force CI tests

### PR DESCRIPTION
**Pull request by mseri**
Due to the erroneous merge of https://github.com/ocaml/opam-repository/pull/25579
Ping @balat

### CODE REVIEW

**Comment by mseri** [comment]
@balat the CI looks mostly fine. The only failures are due to ocsigen-toolkit and are all of the type
```
# File "_none_", line 1:
# Error: Cannot load js_of_ocaml-ppx_deriving_json: this object file uses
#        unsafe features
```

**Comment by balat** [comment]
Yes we have this every time. We should try to drive this in toolkit.

**Comment by balat** [comment]
I opened an issur on Ocsigen Toolkit https://github.com/ocsigen/ocsigen-toolkit/issues/230

**Comment by mseri** [comment]
Can I merge the relaxed upper bound or should I close this PR?

**Comment by balat** [comment]
Oh yes this one was only for testing sorry, and the other one is already merged.
You can close. Thank you!

**Pull request closed without merging**
