### PR TITLE
z3: fixes the installation of dynamic libraries

### PR DESCRIPTION
**Pull request by ivg**
@c-cube accidentaly reverted (in #17558) the installation command back to what was used in 4.8.8 instead of using one from 4.8.8-1, so the dll files are again not installed, which prevents us from packing z3 into a plugin (cmxs) or loading it in a toplevel (ocaml or utop).

It also restored the installation of the z3 binary, which is also extremely useful.

### CODE REVIEW

**Comment by mseri** [comment]
Thanks!

**Comment by mseri** [comment]
Could you move this change to 0.4.9-1? I will keep an eye out for this in the next release

**Comment by ivg** [comment]
> Could you move this change to 0.4.9-1? I will keep an eye out for this in the next release

Then I will have a problem, as I need to specify that bap works with 4.8.8-1 and 4.8.9-1, it is doable, (I can use conflicts) but confusing. Also, the problem is very subtle, in fact, it is only triggered by toplevels as normal linking and dynamic linking works fine.

Basically, my point is that it is an error in the installation script that should be fixed. But I can imagine that this point could be debunked. There is no rush, right now, let's wait until Monday and have some discussion when @c-cube will come and all other interested parties.

**Comment by avsm** [comment]
Please bump the version and just mark this existing one as unavailable in the constraints so it won't get selected (so you don't need constraints).  The discipline of treating versions as immutable is important as it will be enforced eventually, so we need to get used to doing that.  Note that the amount of _time_ between an error entering the repository is immaterial, since downstream users of opam-repo use git commits -- and we don't want anyone observing the same version of a package materially changing its contents when they advance back and forth on the opam-repo commit history.

**Comment by ivg** [comment]
>  The discipline of treating versions as immutable is important as it will be enforced eventually, so we need to get used to doing that. 

Okay, let's stick to this rule then. I am all for it. 

> mark this existing one as unavailable in the constraints

Do you mean to mark it in the current 4.8.9 opam, right?

**Comment by mseri** [comment]
> Do you mean to mark it in the current 4.8.9 opam, right?

Yes, correct! Thanks

**Comment by c-cube** [comment]
Sorry for the unintensional regression. I have no particular opinion on the new patch :)

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
