### PR TITLE
Octez 14

### PR DESCRIPTION
**Pull request by pirbo**
This is a new major release of the octez software suite for the tezos blockchain

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
tezos-crypto seems to have some issues. For some reason sometimes it doesn’t find `Bls12_381_polynomial.Srs.M` even with 0.1.3
```
#=== ERROR while compiling tezos-crypto.14.0 ==================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/tezos-crypto.14.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p tezos-crypto -j 31
# exit-code            1
# env-file             ~/.opam/log/tezos-crypto-8-bfb6f2.env
# output-file          ~/.opam/log/tezos-crypto-8-bfb6f2.out
### output ###
# (cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -open Tezos_stdlib -open Tezos_error_monad -open Data_encoding -g -bin-annot -I src/lib_crypto/dal/.tezos_crypto_dal.objs/byte -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/base -I /home/opam/.opam/4.14/lib/base/base_internalhash_types -I /home/opam/.opam/4.14/lib/base/caml -I /home/opam/.opam/4.14/lib/base/shadow_stdlib -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/bls12-381 -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/data-encoding -I /home/opam/.opam/4.14/lib/either -I /home/opam/.opam/4.14/lib/ezjsonm -I /home/opam/.opam/4.14/lib/ff-sig -I /home/opam/.opam/4.14/lib/hex -I /home/opam/.opam/4.14/lib/integers -I /home/opam/.opam/4.14/lib/jane-street-headers -I /home/opam/.opam/4.14/lib/json-data-encoding -I /home/opam/.opam/4.14/lib/json-data-encoding-bson -I /home/opam/.opam/4.14/lib/jsonm -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/lwt-canceler -I /home/opam/.opam/4.14/lib/ocplib-endian -I /home/opam/.opam/4.14/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_expect/collector -I /home/opam/.opam/4.14/lib/ppx_expect/common -I /home/opam/.opam/4.14/lib/ppx_expect/config -I /home/opam/.opam/4.14/lib/ppx_expect/config_types -I /home/opam/.opam/4.14/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_here/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_inline_test/config -I /home/opam/.opam/4.14/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/ringo -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/stdlib-shims -I /home/opam/.opam/4.14/lib/stringext -I /home/opam/.opam/4.14/lib/tezos-bls12-381-polynomial -I /home/opam/.opam/4.14/lib/tezos-error-monad -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/bare/functor-outputs -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/bare/sigs -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/bare/structs -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/traced/functor-outputs -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/traced/sigs -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/traced/structs -I /home/opam/.opam/4.14/lib/tezos-stdlib -I /home/opam/.opam/4.14/lib/time_now -I /home/opam/.opam/4.14/lib/uchar -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/uutf -I /home/opam/.opam/4.14/lib/zarith -I /home/opam/.opam/4.14/lib/zarith_stubs_js -intf-suffix .ml -no-alias-deps -open Tezos_crypto_dal -o src/lib_crypto/dal/.tezos_crypto_dal.objs/byte/tezos_crypto_dal__Dal_cryptobox.cmo -c -impl src/lib_crypto/dal/dal_cryptobox.ml)
# File "src/lib_crypto/dal/dal_cryptobox.ml", line 356, characters 6-32:
# 356 |       Bls12_381_polynomial.Srs.M.(to_array (load_from_file srs_g1_file k))
#             ^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Bls12_381_polynomial.Srs.M
# (cd _build/default && /home/opam/.opam/4.14/bin/ocamlopt.opt -w -40 -open Tezos_stdlib -open Tezos_error_monad -open Data_encoding -g -O3 -I src/lib_crypto/dal/.tezos_crypto_dal.objs/byte -I src/lib_crypto/dal/.tezos_crypto_dal.objs/native -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/base -I /home/opam/.opam/4.14/lib/base/base_internalhash_types -I /home/opam/.opam/4.14/lib/base/caml -I /home/opam/.opam/4.14/lib/base/shadow_stdlib -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/bls12-381 -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/data-encoding -I /home/opam/.opam/4.14/lib/either -I /home/opam/.opam/4.14/lib/ezjsonm -I /home/opam/.opam/4.14/lib/ff-sig -I /home/opam/.opam/4.14/lib/hex -I /home/opam/.opam/4.14/lib/integers -I /home/opam/.opam/4.14/lib/jane-street-headers -I /home/opam/.opam/4.14/lib/json-data-encoding -I /home/opam/.opam/4.14/lib/json-data-encoding-bson -I /home/opam/.opam/4.14/lib/jsonm -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/lwt-canceler -I /home/opam/.opam/4.14/lib/ocplib-endian -I /home/opam/.opam/4.14/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_expect/collector -I /home/opam/.opam/4.14/lib/ppx_expect/common -I /home/opam/.opam/4.14/lib/ppx_expect/config -I /home/opam/.opam/4.14/lib/ppx_expect/config_types -I /home/opam/.opam/4.14/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_here/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_inline_test/config -I /home/opam/.opam/4.14/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/ringo -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/stdlib-shims -I /home/opam/.opam/4.14/lib/stringext -I /home/opam/.opam/4.14/lib/tezos-bls12-381-polynomial -I /home/opam/.opam/4.14/lib/tezos-error-monad -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/bare/functor-outputs -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/bare/sigs -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/bare/structs -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/traced/functor-outputs -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/traced/sigs -I /home/opam/.opam/4.14/lib/tezos-lwt-result-stdlib/traced/structs -I /home/opam/.opam/4.14/lib/tezos-stdlib -I /home/opam/.opam/4.14/lib/time_now -I /home/opam/.opam/4.14/lib/uchar -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/uutf -I /home/opam/.opam/4.14/lib/zarith -I /home/opam/.opam/4.14/lib/zarith_stubs_js -intf-suffix .ml -no-alias-deps -open Tezos_crypto_dal -o src/lib_crypto/dal/.tezos_crypto_dal.objs/native/tezos_crypto_dal__Dal_cryptobox.cmx -c -impl src/lib_crypto/dal/dal_cryptobox.ml)
# File "src/lib_crypto/dal/dal_cryptobox.ml", line 356, characters 6-32:
# 356 |       Bls12_381_polynomial.Srs.M.(to_array (load_from_file srs_g1_file k))
#             ^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Bls12_381_polynomial.Srs.M
```

**Comment by kit-ty-kate** [comment]
The `tezos` package seems to be missing a dependency:
```
tezos.14.0 is not installed. Install it? [y/n] y
  * Missing dependency:
    - tezos-client-001-PtCJ7pwo-commands >= 14.0
    no matching version
```

**Comment by pirbo** [comment]
So about `tezos-bls12-381-polynomial` the problem was actually that the release of 0.1.3 (incompatible with Octez 14) had been merge in between the opening of the PR and one of its rebase...

Well spotted about the tezos meta-package, fixed!

Thanks

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
