### PR TITLE
tentative fix for conf-gmp for BSDs

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by samoht** [comment]
Can you explain why a new version is needed? Why not patching the existing package?

**Comment by UnixJunkie** [comment]
It is possible but I don't like to do it because it kind of break the reproducibility of package installs.
package.version is not supposed to move over time; like for software tags.

**Comment by samoht** [comment]
> package.version is not supposed to move over time

your are fixing metadata (tracked by Git) so yes, metadata *is* supposed to change over time, to become more accurate. That's the whole point of separating package contents and package metadata.

**Comment by UnixJunkie** [comment]
ok, I will fix cong-gmp and conf-mpfr in this way then.

**Pull request merged**
