### PR TITLE
added conf-aclocal as a dep of parmap

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
maybe wait for @hcarty before merging. He says that breaks on alpine-3.3

**Comment by avsm** [comment]
if its just alpine-3.3 and not 3.4/5/6 then we are ok to merge i think...

**Comment by hcarty** [comment]
This may be fine - it is the `which` package that bit me on alpine-3.3.

I'd say merge and let's try to find a fix for 3.3 if possible, but as a separate task. Let's not hold up everything else. I'm working on porting some internal CI from 3.3 to 3.5 anyway.

**Comment by UnixJunkie** [comment]
According to this site:
https://pkgs.alpinelinux.org/packages?name=which&branch=&repo=&arch=&maintainer=
alpine >= 3.4 all have a which package

**Pull request merged**
