### PR TITLE
Ocaml-amqp.0.1.0

### PR DESCRIPTION
**Pull request by andersfugmann**
New version 0.1.0 of ocaml-amqp

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
I'm wondering, shouldn't this package be called just `amqp` in OPAM?

**Comment by andersfugmann** [comment]
Your right. The name ocaml would seem a bit redundant in this context. I just took blindly the name of my git repo. To follow existing naming scheme, it should maybe be called async-amqp, as it uses async. Thoughts?

**Comment by Leonidas-from-XIV** [comment]
If you're sure there is not going to be a different backend then `async`, you could do that. Currently the only person publishing under the `async-` prefix is @rgrinberg and `async_` is solely Jane Street and one package by @lpw25.

**Comment by andersfugmann** [comment]
As the library is not affiliated with Janestreet, I think it would be wrong to create a false association with Janestreet.  
I don't see the library to use a different backend than async in the near future 
(Maybe a backed based on algebraic effects when/if this goes mainstream), but I use features from Core and Async so it pretty coupled to Async currently.  

Alternative names could be amqplib or amqp-client. 
I could also just keep it as is, but I'm open to suggestions.

**Comment by rgrinberg** [comment]
IMO you shouldn't worry about the "false association". For one, I already abuse it, and the convention seems to work well for lwt packages. It's pretty clear to people that many of the `lwt-*` packages are 3rd party.

I think the fact your library is async only is a very important bit of information because it means that it has quite a narrow use case by the community's standard so it should be very clearly presented.

**Comment by Leonidas-from-XIV** [comment]
`async-amqp`, `async_amqp`, `amqp-client` all sound good to me. The current name is a bit inconvenient as it needs to be passed in `-package` to `ocamlbuild` at which point it feels redundant to have `ocaml` in the name.

**Comment by andersfugmann** [comment]
Thanks for the suggestions.
I will rename the package to amqp-client and include async in the opam package description.

**Pull request merged**
