### PR TITLE
Add LLVM 3.8

### PR DESCRIPTION
**Pull request by jpdeplaix**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
@sylvestre could you update the llvm.org/apt repositories to 3.8 ? :)

**Comment by sylvestre** [comment]
Already the case but built not on all archs/distro yet.

**Comment by jpdeplaix** [comment]
Ok. Do you have any ideas when it will be available ? For the moment none of the distros have the stable release.

**Comment by sylvestre** [comment]
I don't know, sorry.

**Comment by samoht** [comment]
@jpdeplaix we can merge this if you did some test and are confident that everything works (as we cannot really use the CI to test unreleased packages :p)

**Comment by jpdeplaix** [comment]
Yes please :) It works at least for me, on my machine.

**Pull request merged**
