### PR TITLE
add frama-c.20170501 and frama-c-base.20170501

### PR DESCRIPTION
**Pull request by maroneze**

### CODE REVIEW

**Comment by maroneze** [comment]
Ok, new issue with a derived library, I guess we'll try a more robust setting in our CI...

**Comment by avsm** [comment]
No problem, feel free to this PR to push changes to test until you are ready to merge.

**Comment by maroneze** [comment]
Well, we really wanted to avoid adding `conf-autoconf` as dependency, but due to packaged libraries we have not been able to do otherwise... still, we managed to avoid redoing `./configure` unnecessarily, so there's that.

Now, there's a known issue with flambda, which seems to cause some builds to fail. But that is not really Frama-C's fault.

**Comment by avsm** [comment]
> Now, there's a known issue with flambda, which seems to cause some builds to fail. But that is not really Frama-C's fault. Should we blacklist the flambda compilers in the available tag?

For the moment it might be better to leave this part broken. We have an upcoming solution in opam2 (https://github.com/ocaml/opam/issues/2810, cc @altgr) but there is no effective way of expressing this in opam 1.2.2.  It's also a rather serious bug in the compiler if flambda fails, so I'd encourage this to be filed upstream if it isn't already fixed in trunk.

**Comment by avsm** [comment]
Thanks for the major update! You way want to consider posting to https://discuss.ocaml.org about the new release and changelog, where we have a Community category and an `announce` tag for this sort of post.

**Comment by maroneze** [comment]
Thanks for the details. I'm almost sure the bug has been reported; for instance, even ocamlgraph (one of Frama-C's dependencies) with lablgtk cannot be built on `4.04.1+flambda`. However, on `4.06.0+trunk+flambda` I am able to compile Frama-C without issues, so the bug must have been fixed.

**Pull request merged**
