### PR TITLE
+cairo2 0.5

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
The errors:
```
Package expat was not found in the pkg-config search path.
Perhaps you should add the directory containing `expat.pc'
to the PKG_CONFIG_PATH environment variable
Package 'expat', required by 'Fontconfig', not found
```
seem to be completely unrelated to cairo — I forcibly asked `expat` to be installed to no avail.

**Comment by dbuenzli** [comment]
FWIW today on osx I had to install cairo as follows: 

```
PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig opam install cairo2
```

but that's because I had to install an earlier version of cairo. I hadn't to do this with the latest version of cairo on `brew` (but the latest version has a font rendering bug).

**Comment by Chris00** [comment]
Thanks @dbuenzli. However these are some of the Ubuntu tests that are failing...

**Comment by samoht** [comment]
That's a very weird error, I don't see any difference between the successful and failing jobs...

**Comment by yallop** [comment]
Perhaps the Ubuntu Expat depext should be `"libexpat1-dev"` rather than `"expat"`.

**Comment by Chris00** [comment]
@yallop Well, technically, I should not require `expat` — the package manager should install it by itself if it is required for `pkg-config`...  Let us see how it goes with you suggestion.

**Comment by Chris00** [comment]
I do not even understand why this Ubuntu VM complains about expat.  It is not installed on my (Debian) machine and cairo compiles fine...

**Comment by Chris00** [comment]
I enabled the Travis tests for the package (pin — install — and remove) and [it works fine](https://travis-ci.org/Chris00/ocaml-cairo/builds/75871379). I use the container infrastructure but it should not matter.

**Pull request merged**
