### PR TITLE
Oloop

### PR DESCRIPTION
**Pull request by agarwal**
Replaces #4342.

### CODE REVIEW

**Comment by agarwal** [comment]
Please don't merge this. We've managed to corrupt our repo. I don't actually see this commit in GitHub anymore, although you can click on it above!

**Comment by dsheets** [comment]
I believe that the `opam/files/oloop.install` file in the archive is sufficient to install the binaries and the inclusion of this file in the opam metadata repository is unnecessary.

In the past 3 days I have seen as many people do this same thing. I have never seen it before. If you would, could you advise us on why you've included the install file with the package metadata? @AltGr, is there a reason to include `.install` overlay files if any of:

1. It is identical to the archive `/[package].install`
2. It is similar to the archive `/[package].install` but contains renamings to the file base names
3. It is identical to the archive `/opam/files/[package].install`

Any information would be appreciated. There is a real (but quite minor) cost to putting more data in the repository than necessary (clones, history, download, latency, bandwidth all suffer slightly and forever).

**Comment by agarwal** [comment]
@dsheets I assumed the entire opam/ directory within the archive is ignored when the metadata source comes from an opam remote. I thought the opam/ directory within an archive is relevant only when you do a path or git pin. Am I wrong?

**Comment by dsheets** [comment]
I believe you are right, @agarwal. You will still need to place your `oloop.install` in `files/` rather than the root of the package metadata, however. `/[package].install` files are used but `/opam/files/[package].install` files are not.

**Comment by agarwal** [comment]
Right, so the two choices are:
- put `oloop.install` in the root of our archive
- put `oloop.install` under `files` since the whole files directory is overlaid on the archive

We chose the latter just to keep our archive root less cluttered.

**Comment by samoht** [comment]
The `files/` subdir is supposed to contains files and patches that are pushed upstream. Ideally these should not be there at all. Regarding the `.install` files: ideally again, the build system should generate them directly -- as we are not in an ideal world yet, I think it is better to put the static file at the root of the repository.

**Comment by dsheets** [comment]
One option is to have your build system copy `/opam/files/oloop.install` to `/oloop.install` which will then be picked up by opam. Also, `/oloop.install` could then be added to `/.gitignore` to keep the root uncluttered.

If you insist on putting the `.install` in the opam repository, you will need to change its location from `/packages/oloop/oloop.0.1.1/oloop.install` to `/packages/oloop/oloop.0.1.1/files/oloop.install` (i.e. it is currently not in `files`).

**Comment by dbuenzli** [comment]
You can also use a [simple and decent](https://github.com/dbuenzli/topkg) opam-friendly package builder. It will generate a precise .install file for you.

**Comment by agarwal** [comment]
> The files/ subdir is supposed to contains files and patches that are pushed upstream. Ideally these should not be there at all.

Okay, thanks for clarifying this. I didn't realize the goal is to really avoid this.

> Regarding the .install files: ideally again, the build system should generate them directly

Indeed that is what I do in most of my packages. I didn't here because I didn't implement the build of this package. I was just trying to get a working release out fast (which has completely failed, it is still surprisingly difficult to release a package).

**Comment by agarwal** [comment]
> One option is to have your build system copy /opam/files/oloop.install to /oloop.install which will then be picked up by opam.

Good idea. I'll update the build instructions to do this.

> If you insist on putting the .install in the opam repository, you will need to change its location

Oops, I just saw this too, but anyway moot now given your above suggestion.

**Comment by agarwal** [comment]
> You can also use a simple and decent opam-friendly package builder. It will generate a precise .install file for you.

Thanks. I'll take a look. But to be honest, my immediate reaction is "oh boy, yet another tool in the build process. I've already used so many. Why is this so hard!".

**Comment by agarwal** [comment]
Superseded by #4348.

**Comment by dbuenzli** [comment]
> Thanks. I'll take a look. But to be honest, my immediate reaction is "oh boy, yet another tool in the build process.

I wouldn't call that a tool in the build process. It's a way of declaring what your package can build according to the build environment (which is determined by opam). You actually don't use it when you develop your package it's only for distribution. It liberates you from the oasis auto generated crap and allows you to interact directly with your build system of choice.

**Comment by agarwal** [comment]
Got it. Thanks for the clarification.

**Pull request closed without merging**
