### PR TITLE
Update ocamlmod 0.0.7 — using oasis to uninstall

### PR DESCRIPTION
**Pull request by Chris00**
See https://github.com/ocaml/opam/issues/2253 for the motivation

### CODE REVIEW

**Comment by Chris00** [comment]
The error says that [the package is not available](https://travis-ci.org/ocaml/opam-repository/jobs/72006161#L447-L451) for a given switch...

**Comment by samoht** [comment]
It's because of that error few line above:
```
[ERROR] At ~/.opam/repo/default/packages/ocamlmod/ocamlmod.0.0.7/opam:5:70:
  Not a recognised version-control URL
[ERROR] At ~/.opam/repo/default/packages/ocamlmod/ocamlmod.0.0.7/opam:5:70:
  Not a recognised version-control URL
```

**Comment by Chris00** [comment]
It is a valid one (for darcs)!  What are we supposed to do in such case?  Comment out the field?  But then `opam lint` complains...

**Comment by samoht** [comment]
Yea, would be nice if can set-up the opam field to 1.2.2 and let the rewrite happen. @AltGr can you remind us how the rewrite logic is done and how such a case could be added?

**Comment by AltGr** [comment]
Unfortunately, older opam will pass hg:// or darcs:// urls to the tools, which won't work.
To have the url parse with 1.2.0, I recommend writing `hg://https://xxx`. I made sure it will work with trunk opam, and can be rewritten automatically to proper `hg+https://` for the next version.

**Comment by Chris00** [comment]
It won't work for `darcs` (resp. `git`) — `darcs+https` (resp. `git+https`) is not accepted.  How about a separate field telling the type of version control system?

**Comment by Chris00** [comment]
BTW, is there any documentation about the right URL format to use for `dev-repo` (e.g. for example, when do we have to prefix with `git://` and when can it be guessed)?

**Comment by AltGr** [comment]
We only have: http://opam.ocaml.org/doc/Manual.html#URLs

* suffixes `.hg` and `.git` enforce the kind of pinning
* a string without url prefix (`foo://`) is assumed to be a local path
* otherwise, `vcs://` is always needed

I have a patch pending that adds a note to use `hg://https://` and the like for now, for compatibility, to the manual.

**Pull request merged**
