### PR TITLE
Mirage entropy xen 0.3.0

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
pls restart job 1

**Comment by yallop** [comment]
Job 1 restarted.

**Comment by hannesm** [comment]
please once more.. some checksum mismatch for some debian package in there..

**Comment by hannesm** [comment]
The rationale behind the changes to `.travis-ci.sh`: Travis uses an arcane ubuntu release (for which not even packages of non-arcane binutils exist). It seems like they finally will upgrade their infrastructure next month to a more recent release. For the time being, the most practical and least wasteful solution is to hack the `.travis-ci.sh` script. This is not elegant, but works for now.

**Comment by samoht** [comment]
Job 1 restarted.

**Comment by samoht** [comment]
green!

**Pull request merged**
