### PR TITLE
Fix other packages affected by triple-quoting opam bug

### PR DESCRIPTION
**Pull request by dra27**
Following on from #14910, I checked for other packages.

The fix is to ensure the strings contain no newlines, which creates some hideously long lines (in some cases, these might better be moved to scripts?)

For now, `"""` should only be used in meta-data (so `messages`, `post-messages`, `synopsis` and `description` are OK, but commands are not)

### CODE REVIEW

**Comment by mseri** [comment]
It's a pity, it makes the command practically unreadable. I'll wait for the CI, then merge

**Comment by kit-ty-kate** [comment]
I think moving them to separate scripts is a better idea

**Comment by mseri** [comment]
`torch` failures are unrelated. Tbh I'd merge them as they are for now, the only real bad one is clang, we could move it to a separate script later if it's really needed

**Comment by kit-ty-kate** [comment]
ok fair enough

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
