### PR TITLE
tiny_json opam file fixes for OCaml 4.6.0

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
Many old source files are missing or with wrong checksums...

**Comment by camlspotter** [comment]
All fails are about 4.06.0, but these packages are constrained with `ocaml-version < "4.06.0"`.

**Comment by yomimono** [comment]
It surprises me that opam does the right thing with `4.6.0` -- my brain didn't :) Thanks @camlspotter !

**Comment by avsm** [comment]
@altgr is OCaml 4.06.0 = 4.6.0 in OpamVersionCompare?

**Pull request merged**
