### PR TITLE
Add mirage-protocols*.1.3.0 mirage-stack*.1.2.0 tcpip.3.4.0

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by hannesm** [comment]
I suspect we'll need to adjust several upper bounds before merging this, otherwise we'll end up in broken package universes.

**Comment by jpdeplaix** [comment]
```tcpip.3.4.0``` fails with:
```
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/opam/.opam/4.05.0/lib/bytes -I /home/opam/.opam/4.05.0/lib/cstruct -I /home/opam/.opam/4.05.0/lib/duration -I /home/opam/.opam/4.05.0/lib/fmt -I /home/opam/.opam/4.05.0/lib/io-page -I /home/opam/.opam/4.05.0/lib/ipaddr -I /home/opam/.opam/4.05.0/lib/logs -I /home/opam/.opam/4.05.0/lib/lwt -I /home/opam/.opam/4.05.0/lib/mirage-clock -I /home/opam/.opam/4.05.0/lib/mirage-device -I /home/opam/.opam/4.05.0/lib/mirage-flow -I /home/opam/.opam/4.05.0/lib/mirage-profile -I /home/opam/.opam/4.05.0/lib/mirage-protocols -I /home/opam/.opam/4.05.0/lib/mirage-protocols-lwt -I /home/opam/.opam/4.05.0/lib/mirage-random -I /home/opam/.opam/4.05.0/lib/mirage-time -I /home/opam/.opam/4.05.0/lib/mirage-time-lwt -I /home/opam/.opam/4.05.0/lib/ocaml -I /home/opam/.opam/4.05.0/lib/ocplib-endian -I /home/opam/.opam/4.05.0/lib/randomconv -I /home/opam/.opam/4.05.0/lib/result -I /home/opam/.opam/4.05.0/lib/rresult -I /home/opam/.opam/4.05.0/lib/sexplib -I /home/opam/.opam/4.05.0/lib/sexplib/0 -I /home/opam/.opam/4.05.0/lib/uchar -I src/tcpip_checksum -no-alias-deps -I src/tcp -open Tcp -o src/tcp/tcp__Options.cmo -c -impl src/tcp/options.pp.ml)
# File "src/tcp/options.ml", line 112, characters 19-27:
# Error: This expression has type 'a list -> 'a list
#        but an expression was expected of type ('b, 'c) Rresult.result
#     ocamlopt src/tcp/tcp__Options.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlopt.opt -w -40 -g -I /home/opam/.opam/4.05.0/lib/bytes -I /home/opam/.opam/4.05.0/lib/cstruct -I /home/opam/.opam/4.05.0/lib/duration -I /home/opam/.opam/4.05.0/lib/fmt -I /home/opam/.opam/4.05.0/lib/io-page -I /home/opam/.opam/4.05.0/lib/ipaddr -I /home/opam/.opam/4.05.0/lib/logs -I /home/opam/.opam/4.05.0/lib/lwt -I /home/opam/.opam/4.05.0/lib/mirage-clock -I /home/opam/.opam/4.05.0/lib/mirage-device -I /home/opam/.opam/4.05.0/lib/mirage-flow -I /home/opam/.opam/4.05.0/lib/mirage-profile -I /home/opam/.opam/4.05.0/lib/mirage-protocols -I /home/opam/.opam/4.05.0/lib/mirage-protocols-lwt -I /home/opam/.opam/4.05.0/lib/mirage-random -I /home/opam/.opam/4.05.0/lib/mirage-time -I /home/opam/.opam/4.05.0/lib/mirage-time-lwt -I /home/opam/.opam/4.05.0/lib/ocaml -I /home/opam/.opam/4.05.0/lib/ocplib-endian -I /home/opam/.opam/4.05.0/lib/randomconv -I /home/opam/.opam/4.05.0/lib/result -I /home/opam/.opam/4.05.0/lib/rresult -I /home/opam/.opam/4.05.0/lib/sexplib -I /home/opam/.opam/4.05.0/lib/sexplib/0 -I /home/opam/.opam/4.05.0/lib/uchar -I src/tcpip_checksum -no-alias-deps -I src/tcp -open Tcp -o src/tcp/tcp__Options.cmx -c -impl src/tcp/options.pp.ml)
# File "src/tcp/options.ml", line 112, characters 19-27:
# Error: This expression has type 'a list -> 'a list
#        but an expression was expected of type ('b, 'c) Rresult.result
#       ocamlc src/ethif/ethif_packet.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/opam/.opam/4.05.0/lib/bytes -I /home/opam/.opam/4.05.0/lib/cstruct -I /home/opam/.opam/4.05.0/lib/duration -I /home/opam/.opam/4.05.0/lib/fmt -I /home/opam/.opam/4.05.0/lib/io-page -I /home/opam/.opam/4.05.0/lib/ipaddr -I /home/opam/.opam/4.05.0/lib/logs -I /home/opam/.opam/4.05.0/lib/lwt -I /home/opam/.opam/4.05.0/lib/mirage-device -I /home/opam/.opam/4.05.0/lib/mirage-flow -I /home/opam/.opam/4.05.0/lib/mirage-net -I /home/opam/.opam/4.05.0/lib/mirage-net-lwt -I /home/opam/.opam/4.05.0/lib/mirage-profile -I /home/opam/.opam/4.05.0/lib/mirage-protocols -I /home/opam/.opam/4.05.0/lib/mirage-protocols-lwt -I /home/opam/.opam/4.05.0/lib/ocaml -I /home/opam/.opam/4.05.0/lib/ocplib-endian -I /home/opam/.opam/4.05.0/lib/result -I /home/opam/.opam/4.05.0/lib/rresult -I /home/opam/.opam/4.05.0/lib/sexplib -I /home/opam/.opam/4.05.0/lib/sexplib/0 -I /home/opam/.opam/4.05.0/lib/uchar -no-alias-deps -I src/ethif -o src/ethif/ethif_packet.cmo -c -impl src/ethif/ethif_packet.pp.ml)
# File "src/ethif/ethif_packet.ml", line 52, characters 18-21:
# Error: Unbound value >>=
# Hint: Did you mean >=?
#       ocamlc src/udp/udp_packet.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/opam/.opam/4.05.0/lib/bytes -I /home/opam/.opam/4.05.0/lib/cstruct -I /home/opam/.opam/4.05.0/lib/duration -I /home/opam/.opam/4.05.0/lib/fmt -I /home/opam/.opam/4.05.0/lib/ipaddr -I /home/opam/.opam/4.05.0/lib/logs -I /home/opam/.opam/4.05.0/lib/lwt -I /home/opam/.opam/4.05.0/lib/mirage-device -I /home/opam/.opam/4.05.0/lib/mirage-flow -I /home/opam/.opam/4.05.0/lib/mirage-protocols -I /home/opam/.opam/4.05.0/lib/mirage-protocols-lwt -I /home/opam/.opam/4.05.0/lib/mirage-random -I /home/opam/.opam/4.05.0/lib/ocaml -I /home/opam/.opam/4.05.0/lib/randomconv -I /home/opam/.opam/4.05.0/lib/result -I /home/opam/.opam/4.05.0/lib/rresult -I /home/opam/.opam/4.05.0/lib/sexplib -I /home/opam/.opam/4.05.0/lib/sexplib/0 -I /home/opam/.opam/4.05.0/lib/uchar -I src/tcpip_checksum -no-alias-deps -I src/udp -o src/udp/udp_packet.cmo -c -impl src/udp/udp_packet.pp.ml)
# File "src/udp/udp_packet.ml", line 35, characters 27-30:
# Error: Unbound value >>=
# Hint: Did you mean >=?
```
However this is a weird error as it appears only on the ARM64 CI and not on the x86_64 one.
* ARM64 CI log: https://arm64.ci.ocamllabs.io/log/saved/docker-build-4ab1f548e5227e100a26de2aa49617d3/6612cc9cb84978ca180838543a039ffd09142f2e
* x86_64 CI log: https://ci.ocamllabs.io/log/saved/docker-build-fa3746255c7aa5b9caf137d516b18701/d07ae8fa8ec67d9f4390e8257f0309bb69e818d1

**Comment by yomimono** [comment]
https://arm64.ci.ocamllabs.io/log/saved/docker-build-4ab1f548e5227e100a26de2aa49617d3/6612cc9cb84978ca180838543a039ffd09142f2e got a solution which installed `rresult 0.1.0` which put the infix operators somewhere different from current rresult.  We should put a lower bound on `rresult` in tcpip.

**Comment by hannesm** [comment]
travis CI (see https://api.travis-ci.org/v3/job/345901211/log.txt) fails with SIGFPE while running ppx_cstruct tests, any ideas?

I don't understand this issue provided by datakit-ci, but it is worrying. see https://ci.ocamllabs.io/log/saved/docker-run-7701c83d1148d8322ba27acf7c21d004/d24319f682ae4e30f5cc20b4b79810ea1835e9e2
```
File "src/stack-direct/tcpip_stack_direct.ml", line 1:
Error: The files /home/opam/.opam/4.05.0/lib/mirage-net-lwt/mirage_net_lwt.cmi
       and /home/opam/.opam/4.05.0/lib/mirage-net/mirage_net.cmi
       make inconsistent assumptions over interface Mirage_net
    ocamlopt src/stack-direct/tcpip_stack_direct.{cmx,o} (exit 2)
```

vpnkit needs additional upper bounds (see https://ci.ocamllabs.io/log/saved/docker-run-d3fc7fb5d771b12a8c133e4f476793c1/c3fd8c9eaf99350f189789a57b8e12e35213f7d2)

**Comment by jpdeplaix** [comment]
The issue in datakit-ci comes from something that changed in jbuilder if I remember correctly. Poke @rgrinberg @diml

**Comment by diml** [comment]
Looking quickly at the log, the issue in datakit-ci seems to be with the build of mirage-net-lwt 1.0.0, which doesn't use jbuilder:

```
+ /home/opam/.opam/4.05.0/bin/ocaml "pkg/pkg.ml" "build" "--pkg-name" "mirage-net-lwt" "--pinned" "false" (CWD=/home/opam/.opam/4.05.0/.opam-switch/build/mirage-net-lwt.1.0.0)
- ocamlfind ocamldep -package 'result mirage-net lwt io-page cstruct ipaddr' -package 'result mirage-device' -package bytes -modules src/mirage_net_lwt.mli > src/mirage_net_lwt.mli.depends
- ocamlfind ocamldep -package 'result mirage-device' -package bytes -modules src/mirage_net.mli > src/mirage_net.mli.depends
- ocamlfind ocamlc -c -g -bin-annot -safe-string -package 'result mirage-device' -warn-error +1..49 -w A-4-41-44 -package bytes -I src -o src/mirage_net.cmi src/mirage_net.mli
- ocamlfind ocamlc -c -g -bin-annot -safe-string -package 'result mirage-net lwt io-page cstruct ipaddr' -package 'result mirage-device' -warn-error +1..49 -w A-4-41-44 -package bytes -I src -o src/mirage_net_lwt.cmi src/mirage_net_lwt.mli
- + ocamlfind ocamlc -c -g -bin-annot -safe-string -package 'result mirage-net lwt io-page cstruct ipaddr' -package 'result mirage-device' -warn-error +1..49 -w A-4-41-44 -package bytes -I src -o src/mirage_net_lwt.cmi src/mirage_net_lwt.mli
- findlib: [WARNING] Interface mirage_net.cmi occurs in several directories: src, /home/opam/.opam/4.05.0/lib/mirage-net
- # No parallelism done
- ocamlfind ocamldep -package 'result mirage-net lwt io-page cstruct ipaddr' -package 'result mirage-device' -package bytes -modules src/mirage_net_lwt.mli > src/mirage_net_lwt.mli.depends
- ocamlfind ocamldep -package 'result mirage-device' -package bytes -modules src/mirage_net.mli > src/mirage_net.mli.depends
- ocamlfind ocamlc -c -g -bin-annot -safe-string -package 'result mirage-device' -warn-error +1..49 -w A-4-41-44 -package bytes -I src -o src/mirage_net.cmi src/mirage_net.mli
- ocamlfind ocamlc -c -g -bin-annot -safe-string -package 'result mirage-net lwt io-page cstruct ipaddr' -package 'result mirage-device' -warn-error +1..49 -w A-4-41-44 -package bytes -I src -o src/mirage_net_lwt.cmi src/mirage_net_lwt.mli
- + ocamlfind ocamlc -c -g -bin-annot -safe-string -package 'result mirage-net lwt io-page cstruct ipaddr' -package 'result mirage-device' -warn-error +1..49 -w A-4-41-44 -package bytes -I src -o src/mirage_net_lwt.cmi src/mirage_net_lwt.mli
- findlib: [WARNING] Interface mirage_net.cmi occurs in several directories: src, /home/opam/.opam/4.05.0/lib/mirage-net
- # No parallelism done
-> compiled  mirage-net-lwt.1.0.0
```

mirage-net-lwt 1.1.0 uses jbuilder, so I suggest to simply bump the version constraint.

**Comment by samoht** [comment]
> Looking quickly at the log, the issue in datakit-ci seems to be with the build of mirage-net-lwt 1.0.0

if that version seems broken (which seems to be the case!) it is probably best to just remove it.

**Comment by jpdeplaix** [comment]
I opened a PR to remove it.
So I think in order we can merge #11490 then this one, then finally #11457

**Comment by jpdeplaix** [comment]
Ok I'm going to merge this. Thanks for your patience.

**Comment by djs55** [comment]
@jpdeplaix thanks!

**Pull request merged**
