### PR TITLE
Osdp 1.0.0

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by proux01** [comment]
CI fails on Alpine and Centos for the conf-csdp package, this is expected due to unavailable depext:
* no csdp package for Alpine
* there seems to be some csdp package for Centos but not available on the repos: yum answers `No package csdp available.` 

CI goes through perfectly for all other distros (debian and ubuntu).

**Comment by proux01** [comment]
I don't know how to fix this linting error:
>     conf-csdp.1 has errors:
>         error 52: Package is needlessly flagged "light-uninstall", since it has no remove instructions
this is a conf package (`flag: conf`) so it has neither install nor remove instructions.

I had a look to other opam files of conf-* packages in the repo but couldn't see anything I made differently.

**Comment by mseri** [comment]
Don't worry about the linting error. It should disappear once the CI containers are moved to the latest opam

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
