### PR TITLE
containers: fix deps in with-test mode

### PR DESCRIPTION
**Pull request by damiendoligez**
The tests in these versions of `containers` need `qcheck` >= 0.7.

### CODE REVIEW

**Comment by mseri** [comment]
Seems like containers 2.2 is not compatible with ocaml 4.07. @c-cube can I add an upper bound?
```
#=== ERROR while compiling containers.2.2 =====================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.1 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-base-compiler.4.07.1/.opam-switch/build/containers.2.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build jbuilder runtest -p containers -j 1
# exit-code   1
# env-file    ~/.opam/log/containers-16552-dc54dc.env
# output-file ~/.opam/log/containers-16552-dc54dc.out
### output ###
# [...]
# Warning: jbuild files are deprecated, please convert this file to a dune file instead.
# Note: You can use "dune upgrade" to convert your project to dune.
#       ocamlc qtest/.run_qtest.eobjs/byte/run_qtest.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/travis/.opam/ocaml-base-compiler.4.07.1/bin/ocamlc.opt -w -40 -nolabels -g -bin-annot -I qtest/.run_qtest.eobjs/byte -I /home/travis/.opam/ocaml-base-compiler.4.07.1/lib/bytes -I /home/travis/.opam/ocaml-base-compiler.4.07.1/lib/gen -I /home/travis/.opam/ocaml-base-compiler.4.07.1/lib/oUnit -I /home/travis/.opam/ocaml-base-compiler.4.07.1/lib/ocaml/threads -I /home[...]
# File "../src/core/CCArrayLabels.ml", line 15, characters 17-30:
# Error: Signature mismatch:
#        ...
#        In module Floatarray:
#        Modules do not match:
#          (module CCArrayLabels.Floatarray)
#        is not included in
#          (module Array.Floatarray)
```

**Comment by c-cube** [comment]
sure, thanks! I do recall something like that indeed.

**Comment by mseri** [comment]
Merging. FYI, containers 2.3 shows a failure on osx tests!
```
- (cd _build/default/qtest && ./run_qtest.exe)
random seed: 144074685
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
- Failure: >>../src/threads/CCTimer.ml:157
- 
- estimate delay
- ///////////////////////////////////////////////////////////////////////////////
- Ran: 1145 tests in: 26.34 seconds.                                        
- FAILURE
[ERROR] The compilation of containers failed at
        "/Users/travis/.opam/opam-init/hooks/sandbox.sh build jbuilder runtest
        -p containers -j 1".
```

**Comment by c-cube** [comment]
Does this bug consistently show up? I have no macOS machine to test on, sadly :/

**Comment by mseri** [comment]
No idea. If I find some time I’ll create a switch and check

**Pull request merged**
