### PR TITLE
[new release] digestif (0.7.4)

### PR DESCRIPTION
**Pull request by dinosaure**
Hashes implementations (SHA*, RIPEMD160, BLAKE2* and MD5)

- Project page: <a href="https://github.com/mirage/digestif">https://github.com/mirage/digestif</a>
- Documentation: <a href="https://mirage.github.io/digestif/">https://mirage.github.io/digestif/</a>

##### CHANGES:

- Compatibility version with MirageOS 3

### CODE REVIEW

**Comment by mseri** [comment]
@dinosaure can you upstream b08adbe?

**Comment by dinosaure** [comment]
Yes, for sure!

**Comment by mseri** [comment]
@dinosaure can I merge or I should wait for @hannesm to have a look?

**Comment by kit-ty-kate** [comment]
It should be fine. Thanks!

**Comment by dinosaure** [comment]
Waiting @hannesm should be the best where this release is specially for him :+1:

**Pull request merged**
