### PR TITLE
Added new modular-arithmetic.0,1

### PR DESCRIPTION
**Pull request by sonologico**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
According to the error message you are using `jbuilder`:
```
#=== ERROR while compiling modular-arithmetic.0.1 =============================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.06.1 | pinned(https://github.com/sonologico/modular-arithmetic/archive/modular-arithmetic-0.1.tar.gz)
# path                 ~/.opam/4.06/.opam-switch/build/modular-arithmetic.0.1
# command              /usr/bin/make
# exit-code            2
# env-file             ~/.opam/log/modular-arithmetic-19-326a35.env
# output-file          ~/.opam/log/modular-arithmetic-19-326a35.out
### output ###
# jbuilder build
# make: jbuilder: Command not found
# Makefile:2: recipe for target 'build' failed
# make: *** [build] Error 127

- jbuilder build
- make: jbuilder: Command not found
- Makefile:2: recipe for target 'build' failed
- make: *** [build] Error 127
```
However the typical jbuilder command and dependency are not present. Do you really need a Makefile on top of jbuilder ?

**Comment by kit-ty-kate** [comment]
Also you do not need `ocamlfind` if you are using `jbuilder`

**Comment by sonologico** [comment]
Thanks for pointing that out. I was a bit lost on this.

Doing a grep through this repository for some examples, I see that I can remove 'install' and 'remove', update 'depends' to say jbuilder and update build/build-test to the following:

build:          [["jbuilder" "build" "-p" name "-j" jobs]]  
build-test:     [["jbuilder" "runtest" "-p" name "-j" jobs]]

Is that correct?

**Comment by kit-ty-kate** [comment]
Yes it is. You also need to add `"ounit" {test}` to the list of dependencies.

**Comment by sonologico** [comment]
Ah, yes - of course.

**Comment by sonologico** [comment]
Ah, my bad, forgot to include something in the commit.

**Comment by kit-ty-kate** [comment]
Seems like you require OCaml >= 4.05
```
#=== ERROR while installing modular-arithmetic.0.1 ============================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -p modular-arithmetic -j 2
# path                 /home/opam/.opam/4.03.0/build/modular-arithmetic.0.1
# compiler             4.03.0
# exit-code            1
# env-file             /home/opam/.opam/4.03.0/build/modular-arithmetic.0.1/modular-arithmetic-7-d2c37b.env
# stdout-file          /home/opam/.opam/4.03.0/build/modular-arithmetic.0.1/modular-arithmetic-7-d2c37b.out
# stderr-file          /home/opam/.opam/4.03.0/build/modular-arithmetic.0.1/modular-arithmetic-7-d2c37b.err
### stderr ###
#       ocamlc src/.mod_arith.objs/mod_arith.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.03.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.mod_arith.objs -no-alias-deps -o src/.mod_arith.objs/mod_arith.cmo -c -impl src/mod_arith.ml)
# File "src/mod_arith.ml", line 108, characters 10-27:
# Error: Unbound value int_of_string_opt
```

**Comment by sonologico** [comment]
I caught that and added the constraint. Seems like it is all good now.

**Comment by kit-ty-kate** [comment]
Looks good indeed. Thanks

**Comment by sonologico** [comment]
Thanks for all the help. Got a better picture of what to watch out for, so next time it should be smoother.

**Pull request merged**
