### PR TITLE
Disable merlin 4.14-502 preview

### PR DESCRIPTION
**Pull request by voodoos**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
merlin and merlin-lib should also be constrained

**Comment by voodoos** [comment]
Oups, of course.
Should I remove the `available: opam-version >= "2.1.0"` constraint ?

**Comment by kit-ty-kate** [comment]
> Should I remove the `available: opam-version >= "2.1.0"` constraint ?

yeah

**Comment by voodoos** [comment]
done

**Comment by mseri** [comment]
Thanks

**Comment by kit-ty-kate** [comment]
why was this merged before #25902 ?

**Pull request merged**
