### PR TITLE
Fix ocp-build.1.99.19-beta checksum and uninstall

### PR DESCRIPTION
**Pull request by lefessan**

### CODE REVIEW

**Comment by gabelevi** [comment]
@lefessan @avsm @fdopen - Currently the ocaml-ci-scripts don't work for me due to this checksum change not being sync'd to https://github.com/fdopen/opam-repository-mingw. Does anyone know how that sync works?

Looks like the ocaml-ci-scripts for appveyor uses that repo instead of this one. https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor-opam.sh#L70

**Comment by gabelevi** [comment]
Appveyor runs [like this one](https://ci.appveyor.com/project/Facebook/flow/build/1862) fail with the message

```
[ERROR] Bad checksum for
        C:/cygwin64/home/appveyor/.opam/packages.dev/ocp-build.1.99.19-beta/1.99.19-beta.tar.gz:
          - 83a32517f9e49119b200952f34e533d9 [expected result]
          - ac7000cfff5a0d94970050fa86f93667 [actual result]
        Metadata might be out of date, in this case run `opam update`.
```

I tried forking the script and adding an `opam update`, before noticing that it wasn't reading from opam-repository 😛

**Comment by fdopen** [comment]
Ok, I've fixed it. It's unavoidable, if lefassan changes the upstream tarball several times instead of releasing new versions.

If you target windows, consider to use a better maintained build system with proper windows support 😉

**Comment by gabelevi** [comment]
Thanks @fdopen!

**Comment by lefessan** [comment]
> If you target windows, consider to use a better maintained build system with proper windows support￼ 

Isn't it weird to complain about a lack of maintenance for `ocp-build` when the problem actually comes from too much maintenance ?

**Pull request merged**
