### PR TITLE
Package curses.1.0.11

### PR DESCRIPTION
**Pull request by Perdu**
### `curses.1.0.11`
Bindings to ncurses
Tools for building terminal-based user interfaces

---
* Homepage: https://github.com/mbacarella/curses
* Source repo: git+https://github.com/mbacarella/curses.git
* Bug tracker: https://github.com/mbacarella/curses/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by avsm** [comment]
What's the intention behind this PR? It seems to update just the source archive for an already-existing release.

**Comment by Perdu** [comment]
Maintainer asked me to run `opam publish` to be able to do the release. I don't know the details, but I need this release to exist for Arch Linux User Repository packaging. See https://github.com/mbacarella/curses/issues/11

**Comment by avsm** [comment]
This version is already released...https://ocaml.org/p/curses/1.0.11
/cc @mbacarella to find out more.

**Comment by mbacarella** [comment]
@Perdu, asked me to release curses 1.0.11.

I mindlessly tried running `opam publish` and it was blowing up mysteriously. I struggled and gave up.

I asked @Perdu to try and they submitted this.

Turns out 1.0.11 was released to opam already (and that's probably why `opam publish` was blowing up for me), but @Perdu thought 1.0.11 hadn't been released because they didn't see it as a release in the curses project github (a 1.0.11 *tag* exists, but not a *release*).

I don't know how the curses repo ended up in this state but I think we can close this PR while I figure out what to do.

**Comment by avsm** [comment]
Sounds good, thanks!

**Pull request closed without merging**
