### PR TITLE
ocamlbuild bulk deps: add some missing packages

### PR DESCRIPTION
**Pull request by gasche**
Guillaume Bury reported a typo in the ocamlbuild-detection logic: it
looked for a file name "_tag" instead of "_tags", and thus missed some
ocamlbuild users. The present patch is the result of re-running the
script after fixing this: 171 additional packages are detected to use
ocamlbuild (including a few maintained by Guillaume Bury).

The last commit on master at the time the script was re-run was

> commit a939e2dd452c9cd24a55a359cb09faa145f63b32
> Merge: 58e08f2 7016e0b
> Author: yallop <yallop@gmail.com>
> Date:   Tue Dec 1 23:08:32 2015 +0000
>
>     Merge pull request #5221 from gabelevi/flowtype
>
>     +flowtype.0.19.0

### CODE REVIEW

**Comment by yallop** [comment]
I've read through the patch; it looks good to me.

**Comment by samoht** [comment]
not sure if this is related, but there a syntax error on opam.1.2.0:

```
[ERROR] At ~/.opam/repo/default/packages/wxOCaml/wxOCaml.1.0.1/opam:7:53:
  Not a recognised version-control URL
```

**Comment by yallop** [comment]
Not related: that was introduced in 52053621 (#5180).  /cc @lefessan

**Comment by yallop** [comment]
Fixed in #5232.

**Comment by samoht** [comment]
@gasche any idea why we have:

```
[WARNING] Directory /home/travis/.opam/4.02.3/lib/ocamlbuild is not empty, not removing
```

**Comment by gasche** [comment]
I don't think it is related to this request, except that adding dependency on the `ocamlbuild` package means that OPAM will occasionally try to install it. I would guess that this is a bad interaction between my [dummy ocamlbuild OPAM package](https://github.com/ocaml/opam-repository/commit/a280b5ba) and the dummy *ocamlfind* package that ocamlfind generates at installation time. My guess comes from the fact that the repository you give contains ocamlfind's META file.

My dummy OPAM package gives no installation and uninstallation rules, so there is no package-specific reason for OPAM to go look into `$switch/lib/ocamlbuild`. Is there a global OPAM policy to try to do something with the `$switch/lib/$pkg` directory, regardless of the install/uninstall rules?

**Comment by gasche** [comment]
This may also be presented as an ocamlfind packaging problem: with its install-meta [Makefile](https://godirepo.camlcity.org/wwwsvn/trunk/Makefile?rev=222&root=lib-findlib&view=markup) rule, findlib installs an [ocamlbuild](https://godirepo.camlcity.org/wwwsvn/trunk/site-lib-src/ocamlbuild/?root=lib-findlib) directory in its `-sitelib` variable, which is set by OPAM to `opam config var lib`, but the OPAM package's [ocamlfind.install](https://github.com/ocaml/opam-repository/blob/master/packages/ocamlfind/ocamlfind.1.5.6/files/ocamlfind.install) file does not list those.

**Comment by samoht** [comment]
the policy is for whoever puts things somewhere, it is also it's job to remove it. so in that case I guess that's ocamlfind's job..

**Comment by gasche** [comment]
But I think that ocamlfind does remove this directory in its `uninstall` rule. The question is: at which time was this warning called by opam? Was it trying to remove `ocamlbuild` or `ocamlfind`?

**Comment by samoht** [comment]
when removing `ocamlbuild` I think

**Comment by gasche** [comment]
Then I would say it is opam's, not ocamlfind's, fault. Or at least there is an assumption in OPAM about who owns `$switch/lib/ocamlbuild` that should be explicited.

In any case, I think we may have to ask Gerd to stop installing a dummy `$sitelib/ocamlbuild` directory with a dummy META file once ocamlbuild exists as a separate project. We could even have the dummy ocamlbuild package install the current dummy-META file instead of ocamlfind.

**Comment by samoht** [comment]
> In any case, I think we may have to ask Gerd to stop installing a dummy $sitelib/ocamlbuild directory with a dummy META file once ocamlbuild exists as a separate project. We could even have the dummy ocamlbuild package install the current dummy-META file instead of ocamlfind.

that's a great plan!

**Comment by gasche** [comment]
So I coordinated with Gerd, but this will not affect the present issue: he is going to use the same strategy used for Camlp4, which is to test at findlib-install time whether the OCaml version is distributing ocamlbuild or not. This means there won't be any conflict between findlib-dummy-ocamlbuild and separated-ocamlbuild, but there remain an issue between findlib-dummy-ocamlbuild and opam-dummy-ocamlbuild. How can I tell OPAM, in the `opam` metadata of the dummy package, to *not* try to remove `$lib/ocamlbuild` when it uninstalls the `ocamlbuild` package?

**Pull request merged**
