### PR TITLE
[new release] mirage (2 packages) (4.8.0)

### PR DESCRIPTION
**Pull request by hannesm**
The MirageOS library operating system

- Project page: <a href="https://github.com/mirage/mirage">https://github.com/mirage/mirage</a>
- Documentation: <a href="https://mirage.github.io/mirage/">https://mirage.github.io/mirage/</a>

##### CHANGES:

- BREAKING avoid optional runtime arguments in devices (ip, git, happy-eyeballs,
  dns) (mirage/mirage#1552 mirage/mirage#1577 by @hannesm)
- update documentation (fixes mirage/mirage#1560, mirage/mirage#1571 mirage/mirage#1576 by @hannesm)
- code cleanups, removed unused code (mirage/mirage#1575 by @reynir)
- provide Mirage_runtime,register_arg, deprecate Mirage_runtime.register
  (mirage/mirage#1574 by @hannesm)
- improve Mirage_runtime argument error message (mirage/mirage#1573 by @hannesm)
- config.ml: make deprecation warnings non-errors (mirage/mirage#1568 by @reynir)
- Use copy# for config.ml (mirage/mirage#1570 by @reynir)
- generated opam file: avoid double slash (reported in mirage/mirage#1563 by @reynir, fixed
  in mirage/mirage#1564 by @reynir)
- BUGFIX: version check: log a warning if version is not parseable
  (reported in mirage/mirage#1565 by @reynir, fixed in mirage/mirage#1566 by @hannesm)

### CODE REVIEW

**Comment by hannesm** [comment]
fine to merge, CI errors are usual or unrelated.

**Comment by hannesm** [comment]
is there anything that is blocking a merge?

**Comment by mseri** [comment]
I think only me being away, sorry

**Comment by hannesm** [comment]
Thanks Marcello! :)

**Pull request merged**
