### PR TITLE
coccinelle: add deps on camlp4 and parmap and bound on menhir

### PR DESCRIPTION
**Pull request by damiendoligez**
@coccinelle: we also need an email address to set the maintainer field for this package.

### CODE REVIEW

**Comment by lefessan** [comment]
On 4.02.3 and 4.04, 3.12.1, 4.00.0, 3.01.0
# chemoelectric-pycaml-8614105/pycaml_stubs.c:33:20: fatal error: Python.h: No such file or directory
#  #include <Python.h>
depext for Python or python-dev missing ?

On 4.03.0, pcre 7.1.0 does not build, it seems incompatible with 0.9.0 (required by menhir.20140422):
# E: Failure("Command ''/home/travis/.opam/4.03.0/bin/ocamlbuild' lib/libpcre_stubs.a lib/dllpcre_stubs.so lib/pcre.cma lib/pcre.cmxa lib/pcre.a lib/pcre.cmxs examples/cloc/cloc.native examples/count_hash/count_hash.native examples/pcregrep/pcregrep.native examples/subst/subst.native -tag debug' terminated with error code 10")

**Comment by damiendoligez** [comment]
For pcre vs. ocamlbuild.0.9.0, see #7512 .

**Comment by samoht** [comment]
I've restarted the build

**Comment by samoht** [comment]
The build is still failing with:

```
# chemoelectric-pycaml-8614105/pycaml_stubs.c:33:20: fatal error: Python.h: No such file or directory
#  #include <Python.h>
```

But `opam-depext` tried to install python-2.7:

```
# Detecting depexts using flags: x86_64 linux ubuntu
# The following system packages are needed:
#  - libpcre3-dev
#  - m4
#  - pkg-config
#  - python2.7
#  - python2.7-dev
# All required OS packages found.
```

So I am not sure what's wrong, but it appears to be an issue with TravisCI env. In regard of this, I am merging this PR which fixes other (real) issue.

**Pull request merged**
