### PR TITLE
Package z3.4.11.0

### PR DESCRIPTION
**Pull request by smuenzel**
### `z3.4.11.0`
Z3 solver

---
* Homepage: https://github.com/Z3prover/z3
* Source repo: git+https://github.com/Z3prover/z3.git
* Bug tracker: https://github.com/Z3prover/z3/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by smuenzel** [comment]
I removed the message about static linking, since it's been the case for versions 4.9.X and 4.10.X, so everyone should have had time to adjust

**Comment by smuenzel** [comment]
The goblint failure seems unrelated to the z3 change, it fails without this change as well.

**Comment by smuenzel** [comment]
@sim642, it seems like that when z3 is installed, goblint detects it and the compilation fails. I believe this is a new issue in the current goblint version, but I'm not sure

```
#=== ERROR while compiling goblint.2.0.0 ======================================#
# context     2.1.2 | linux/x86_64 |  | git+file:///home/stefan/development/opam-repository
# path        ~/.opam/4.14.0/.opam-switch/build/goblint.2.0.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p goblint -j 15 --promote-install-files=false @install
# exit-code   1
# env-file    ~/.opam/log/goblint-128398-43c72b.env
# output-file ~/.opam/log/goblint-128398-43c72b.out
### output ###
# (cd _build/default/src && /usr/bin/bash -e -u -o pipefail -c 'git describe --all --long --dirty || echo "n/a"') > /tmp/build_0f8b3f_dune/dune-pipe-action-_26aca4_.stdout
# fatal: not a git repository (or any parent up to mount point /)
# Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
# (cd _build/default && /home/stefan/.opam/4.14.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.goblint_lib.objs/byte -I /home/stefan/.opam/4.14.0/lib/angstrom -I /home/stefan/.opam/4.14.0/lib/arg-complete -I /home/stefan/.opam/4.14.0/lib/astring -I /home/stefan/.opam/4.14.0/lib/batteries -I /home/stefan/.opam/4.14.0/lib/bigarray-compat -I /home/stefan/.opam/4.14.0/lib/bigstringaf -I /home/stefan[...]
# File "src/witness/z3/violationZ3.z3.ml", line 8, characters 7-10:
# Error: Unbound module Cil

```

**Comment by sim642** [comment]
Thanks for the mention! It would be better to add a conflicts with `z3` (any version) to goblint.2.0.0 instead of the other way around (as you've done right now), because any version of `z3` installed would trigger that error.

Looks like the CI does trigger revdeps via `depopts` but not in the "forward" direction: this incompatibility didn't show in #21998 because the CI doesn't try different `depopts` combinations.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
