### PR TITLE
ppx_orakuda.3.0.1 ppx_test.1.4.0 work OCaml >= 4.03.0

### PR DESCRIPTION
**Pull request by rgrinberg**
Let's see what happens with this one

### CODE REVIEW

**Comment by rgrinberg** [comment]
@camlspotter @yallop 

Looks like the situation isn't so bad. These packages indeed build on 4.04. That error on 4.03 is bizarre though:

```
# - build ppx ppx_test.o
# + ocamlfind ocamlc -annot -bin-annot -package compiler-libs.common,ppxx -g -w A-3-4-9-40-42-44-45-48 -warn-error a -g -I . -c ppx_test.ml
# - build ppx ppx_test.o
# + ocamlfind ocamlopt -annot -bin-annot -package compiler-libs.common,ppxx -g -w A-3-4-9-40-42-44-45-48 -warn-error a -I . -c ppx_test.ml
# - build ppx ppx_test.opt
# + ocamlfind ocamlopt -package compiler-libs.common,ppxx -g -I . -o ppx_test.opt ppx_test.cmx -linkpkg
# - build ppx ppx_test.run
# + ocamlfind ocamlc -package compiler-libs.common,ppxx -g -g -I . -o ppx_test.run ppx_test.cmo -linkpkg
# *** omake: 64/101 targets are up to date
# *** omake: failed (0.69 sec, 7/7 scans, 15/23 rules, 47/132 digests)
### stderr ###
# [...]
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/travis/.opam/4.03.0/lib/ocaml, /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/travis/.opam/4.03.0/lib/ocaml, /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/travis/.opam/4.03.0/lib/ocaml, /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs
# File "_none_", line 1:
# Error: Files ppx_test.cmo and /home/travis/.opam/4.03.0/lib/ppxx/ppxx.cmo
#        make inconsistent assumptions over interface Ppxx
# *** omake: targets were not rebuilt because of errors:
#    ppx/ppx_test.run
#       depends on: ppx
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=/home/travis/.opam/4.03.0\"' terminated with error code 2")
```

Could it be some sort of race condition?

**Comment by camlspotter** [comment]
We had the same failure in https://github.com/ocaml/opam-repository/pull/7857 .  Let me try reproducing the issue locally again.

**Comment by camlspotter** [comment]
Here is the entire log, starting from clean switch install of 4.03.0:

```
$ opam --version
1.2.2
$ opam switch 4.03.0

=-=- Installing compiler 4.03.0 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[default.comp] https://github.com/ocaml/ocaml/archive/4.03.0.tar.gz downloaded
Now compiling OCaml. This may take a while, please bear with us...
Done.

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
∗  installed base-bigarray.base
∗  installed base-threads.base
∗  installed base-unix.base
Done.
# To setup the new switch in the current shell, you need to run:
eval `opam config env`
$ opam switch 4.03.0
# To setup the new switch in the current shell, you need to run:

$ eval `opam config env`
$ opam install base-bytes.base conf-libpcre.1 conf-m4.1 conf-pkg-config.1.0 ocamlfind.1.7.1 omake.0.10.1 pcre.7.2.3 ppx_tools.5.0+4.03.0 ppxx.1.3.0 re.1.6.0
The following actions will be performed:
  ∗  install conf-pkg-config 1.0       
  ∗  install conf-m4         1         
  ∗  install ocamlbuild      0.9.3            [required by pcre, re]
  ∗  install conf-libpcre    1         
  ∗  install ocamlfind       1.7.1     
  ∗  install ppx_tools       5.0+4.03.0
  ∗  install omake           0.10.1    
  ∗  install base-bytes      base      
  ∗  install ppxx            1.3.0     
  ∗  install re              1.6.0     
  ∗  install pcre            7.2.3     
===== ∗  11 =====
Do you want to continue ? [Y/n] 
y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ocamlfind] Archive in cache
[omake] Archive in cache
[pcre] Archive in cache
[ppx_tools] Archive in cache
[default] https://opam.ocaml.org/archives/ppxx.1.3.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/re.1.6.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlbuild.0.9.3+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
∗  installed conf-pkg-config.1.0
∗  installed conf-m4.1
∗  installed conf-libpcre.1
∗  installed ocamlbuild.0.9.3
∗  installed ocamlfind.1.7.1
∗  installed base-bytes.base
∗  installed ppx_tools.5.0+4.03.0
∗  installed pcre.7.2.3
∗  installed re.1.6.0
∗  installed omake.0.10.1
[ERROR] The compilation of ppxx failed at "ocaml setup.ml -build".
Processing 11/11: [ppxx: ocaml setup.ml]
#=== ERROR while installing ppxx.1.3.0 ========================================#
# opam-version 1.2.2 (391297300524717e1475deaea37bca287c7f5e36)
# os           darwin
# command      ocaml setup.ml -build
# path         /Users/jun/.opam/4.03.0/build/ppxx.1.3.0
# compiler     4.03.0
# exit-code    1
# env-file     /Users/jun/.opam/4.03.0/build/ppxx.1.3.0/ppxx-31517-06fa5f.env
# stdout-file  /Users/jun/.opam/4.03.0/build/ppxx.1.3.0/ppxx-31517-06fa5f.out
# stderr-file  /Users/jun/.opam/4.03.0/build/ppxx.1.3.0/ppxx-31517-06fa5f.err
### stdout ###
# *** omake: reading OMakefiles
### stderr ###
# [...]
# Warning 3: deprecated: String.capitalize
# Use String.capitalize_ascii instead.
# File "setup.ml", line 5848, characters 11-30:
# Warning 3: deprecated: String.uncapitalize
# Use String.uncapitalize_ascii instead.
# *** omake error:
#    File Omake_builtin: line 0, characters 0-0
#    include file Pervasives not found in OMAKEPATH
#       (OMAKEPATH[] = "." : Sequence /Users/jun/.opam/4.03.0/lib/omake : Dir)
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=/Users/jun/.opam/4.03.0\"' terminated with error code 123")



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions failed
  ∗  install ppxx 1.3.0
The following changes have been performed
  ∗  install base-bytes      base      
  ∗  install conf-libpcre    1         
  ∗  install conf-m4         1         
  ∗  install conf-pkg-config 1.0       
  ∗  install ocamlbuild      0.9.3     
  ∗  install ocamlfind       1.7.1     
  ∗  install omake           0.10.1    
  ∗  install pcre            7.2.3     
  ∗  install ppx_tools       5.0+4.03.0
  ∗  install re              1.6.0     

The former state can be restored with:
    opam switch import "~/.opam/4.03.0/backup/state-20161101113448.export"
$ ls ~/.opam/4.03.0/lib/omake/
opam.config
$ 
```

So the problem still persists.  `omake.0.10.1` does not install necessary files under `$HOME/.opam/4.03.0/lib/omake/`, therefore it fails building `ppxx`.  

Why this is different from Travis is not clear to me at all.  It is as if Travis uses files from old installations somehow.

Anyway,  this confirms that the current `omake.0.10.1` has a big issue.

**Comment by rgrinberg** [comment]
Thanks for bearing with me. But I simply cannot reproduce this problem, locally or on travis. The issue you're pointing out has been fixed already. It works fine for me and on travis.

I just tested in on a clean 4.03 switch:

```
opam install ppx_test
The following actions will be performed:
  ∗  install conf-m4    1                     [required by ocamlfind]
  ∗  install ocamlbuild 0.9.3                 [required by re]
  ∗  install ocamlfind  1.7.1                 [required by ppx_test]
  ∗  install ppx_tools  5.0+4.03.0            [required by ppxx]
  ∗  install omake      0.10.1                [required by ppx_test]
  ∗  install base-bytes base                  [required by re]
  ∗  install ppxx       1.3.0                 [required by ppx_test]
  ∗  install re         1.7.1                 [required by ppx_test]
  ∗  install ppx_test   1.4.0
===== ∗  9 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ocamlbuild] Archive in cache
[omake] Archive in cache
[ppx_test] Archive in cache
[ppx_tools] Archive in cache
[ppxx] Archive in cache
[re] Archive in cache
[default] https://opam.ocaml.org/archives/ocamlfind.1.7.1+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed conf-m4.1
∗  installed ocamlbuild.0.9.3
∗  installed ocamlfind.1.7.1
∗  installed base-bytes.base
∗  installed ppx_tools.5.0+4.03.0
∗  installed re.1.7.1
∗  installed omake.0.10.1
∗  installed ppxx.1.3.0
∗  installed ppx_test.1.4.0
Done.
```

ppx_test installs just fine.

Here are all the files that omake installs:

```
ls -R ~/.opam/omake2/lib/omake
/home/rgrinberg/.opam/omake2/lib/omake:
build/  configure/  OMakefile.default  OMakeroot.default  OMakeroot.om  opam.config  parse/  Pervasives.om  Pervasives.omc  web/

/home/rgrinberg/.opam/omake2/lib/omake/build:
C.om  C.omc  Common.om  Common.omc  LaTeX.om  LaTeX.omc  OCaml.om  OCaml.omc  svn_realclean.om

/home/rgrinberg/.opam/omake2/lib/omake/configure:
Configure.om  Configure.omc  fam.om  fs_case_sensitive.om  moncontrol.om  ncurses.om  posix_spawn.om  readline.om  snprintf.om  X.om

/home/rgrinberg/.opam/omake2/lib/omake/parse:
C/  LaTeX/

/home/rgrinberg/.opam/omake2/lib/omake/parse/C:
Lex.om  Parse.om

/home/rgrinberg/.opam/omake2/lib/omake/parse/LaTeX:
Lex.om  Macros.om  Parse.om  Spell.om

/home/rgrinberg/.opam/omake2/lib/omake/web:
simple-xml.om
```

Please let me which ones are missing.

**Comment by rgrinberg** [comment]
And note that for this particular PR, ppxx, which uses omake just the same, installed on all versions just fine. @yallop Given the travis results + manual verification of the travis failure, I think this PR is safe to merge.

**Comment by yallop** [comment]
> Why this is different from Travis is not clear to me at all. It is as if Travis uses contaminated files from old installations somehow.

The [Travis script](https://github.com/ocaml/opam-repository/blob/185c3f074b6b3371b6995d094c07b5e5f2bde6be/.travis-ci.sh#L90-L128) uses the same OPAM switch to install multiple packages in the same PR, so there are potential problems if one of the packages isn't cleaned up properly.

**Comment by avsm** [comment]
restarted https://travis-ci.org/ocaml/opam-repository/jobs/180101454 now that #7969 is merged

**Comment by camlspotter** [comment]
`opam update` does not help my situation.  I did:

```
#!/bin/sh
opam update
opam switch 4.04.0
eval `opam config env`
opam remove omake
/bin/rm -rf ~/.opam/4.04.0/lib/omake
opam install omake
```

Here is the log:

```
$ sh omake.sh

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[default] synchronized from https://opam.ocaml.org
[NOTE] omake is not installed.

Nothing to do.
The following actions will be performed:
  ∗  install omake 0.10.1

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[omake] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
∗  installed omake.0.10.1
Done.
```

Files are missing:

```
$ ls ~/.opam/4.04.0/lib/omake/
opam.config
```

I removed the local cache of the source code but the same happens.

**Comment by rgrinberg** [comment]
>`opam update` does not help my situation.  I did:
> ...

OK but this issue is definitely local to you. I've verified this on various OSX
and Linux systems and everyone installs/uninstalls omake successfully (there are
some issues when hevea is present, but that's besides the point).

The original problem was caused by my careless omission of the `$ make install`
command when installing opam. With that being said, it should have been added
now. You can verify this on your local opam by the following command:

```
$ opam show omake.0.10.1 --raw
```

This is the output that I get:

```
opam-version: "1.2"
name: "omake"
version: "0.10.1"
maintainer: "Gerd Stolpmann <gerd@gerd-stolpmann.de>"
authors: ["Aleksey Nogin" "Jason Hickey" "Gerd Stolpmann"]
homepage: "http://projects.camlcity.org/projects/omake.html"
bug-reports: "https://github.com/ocaml-omake/issues"
license: "GPL2"
dev-repo: "https://github.com/ocaml-omake/omake.git"
build: [
  ["./configure" "-prefix" "%{prefix}%"]
  [make]
]
install: [make "install"]
remove: [
  ["rm" "-f" "%{prefix}%/bin/omake"]
  ["rm" "-f" "%{prefix}%/bin/osh"]
  ["rm" "-rf" "%{prefix}%/lib/omake"]
]
depends: "ocamlfind"
available: [ocaml-version >= "4.02.3" & ocaml-native]
```

Note that the install step above is present! (hopefully it's the same for you)

If you run something like:

```
$ opam reinstall omake.0.10.1 --verbose | perl -ne 'print if /^[\[+]/'
```

You will see all the commands that opam is executing. That install command
should be part of the pack.

If you verify you have the correct opam file, and the install command is being
ran, and you STILL don't have the all the artifacts installed then that will be
very surprising to me.

**Comment by rgrinberg** [comment]
@avsm @yallop I think this PR should be merged. The CI failures are unrelated to any of the issues raised by camlspotter here. The CI failure here seems to be some sort of race conditions that I've yet figured how to reproduce. The packages in question here seem to install reliably for me in all of the manual tests I've conducted (not just on my own machines). Also, since this PR only enables the packages to be installed on new systems where the CI passes anyway (4.04), I see no reason to delay this.

I will investigate the issues further on the omake bug tracker.

**Comment by yallop** [comment]
Ok, let's merge this and open a new issue to track the problem (https://github.com/ocaml/opam-repository/issues/7995).

**Pull request merged**
