### PR TITLE
Camlp4 4.08

### PR DESCRIPTION
**Pull request by diml**
This will be the last release of Camlp4 (https://discuss.ocaml.org/t/the-end-of-camlp4/4216).

### CODE REVIEW

**Comment by diml** [comment]
I went through most of the build failures. They don't seem related to camlp4. Most of them look like problem with OCaml 4.08 not related to preprocessing, such as using deprecated feautres.

**Comment by XVilka** [comment]
@diml one failure seems still related, see:
```
# Camlp4: Uncaught exception: DynLoader.Error ("./syntax/common/pa_deriving_common.cma", "no implementation available for Pa_deriving_common.Id")
# 
# File "syntax/std/pa_deriving_std.ml", line 1:
# Error: Error while running external preprocessor
# Command line: camlp4 '-I' '/home/opam/.opam/4.08/lib/ocaml/camlp4' '-I' '/home/opam/.opam/4.08/lib/ocaml/camlp4' '-I' '/home/opam/.opam/4.08/lib/ocaml/camlp4' '-parser' 'o' '-parser' 'op' '-printer' 'p' '-parser' 'Camlp4QuotationCommon' '-parser' 'Camlp4OCamlOriginalQuotationExpander' '-parser' 'Camlp4GrammarParser' 'syntax/common/pa_deriving_common.cma' 'syntax/std/pa_deriving_std.ml' > /tmp/ocamlppf62640
# 
# Command exited with code 2.
# E: Failure("Command ''/home/opam/.opam/4.08/bin/ocamlbuild' syntax/common/pa_deriving_common.cma syntax/common/pa_deriving_common.cmxa syntax/common/pa_deriving_common.a syntax/common/pa_deriving_common.cmxs syntax/std/pa_deriving_std.cma syntax/std/pa_deriving_std.cmxa syntax/std/pa_deriving_std.a syntax/std/pa_deriving_std.cmxs syntax/classes/pa_deriving_classes.cma syntax/classes/pa_deriving_classes.cmxa syntax/classes/pa_deriving_classes.a syntax/classes/pa_deriving_classes.cmxs lib/deriving.cma lib/deriving.cmxa lib/deriving.a lib/deriving.cmxs lib/deriving_num.cma lib/deriving_num.cmxa lib/deriving_num.a lib/deriving_num.cmxs -use-ocamlfind -tag debug' terminated with error code 10")
# make: *** [Makefile:7: build] Error 1
```
Also seems like a good opportunity to catch the building errors in the dark edges of OCaml ecosystem, since the builds are triggered by a very old specimen.

**Comment by diml** [comment]
Yh, I saw this but I don't see how it could be related to this change. I wouldn't be surprised if this was already a problem with older versions of Camlp4.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
