### PR TITLE
ounit-2.0.1

### PR DESCRIPTION
**Pull request by gildor478**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Errors come from the use of ```String.uppercase_ascii``` which is not available < 4.03.

**Comment by jpdeplaix** [comment]
```
File "src/oUnitConf.ml", line 75, characters 4-14:
Error: Unbound value String.map
```
using 3.12.1

**Comment by gildor478** [comment]
Going back in time!

2.0.4 should be compatible with 3.12.1.

Hopefully this will be releasable!

**Comment by gildor478** [comment]
@jpdeplaix Ready!

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
