### PR TITLE
[new release] http-mirage-client (0.0.7)

### PR DESCRIPTION
**Pull request by hannesm**
HTTP client for MirageOS

- Project page: <a href="https://github.com/robur-coop/http-mirage-client">https://github.com/robur-coop/http-mirage-client</a>

##### CHANGES:

- Adapt to TLS 1.0.0 API changes (robur-coop/http-mirage-client#1, @hannesm)

### CODE REVIEW

**Comment by hannesm** [comment]
I don't understand the test failures and can't reproduce them. Good to merge from my point of view.

**Comment by hannesm** [comment]
But I wonder whether there is an underlying CI issue:
```
Fatal error: exception Unix.Unix_error(Unix.ENOENT, "open", "/home/opam/.opam/4.14/.opam-switch/build/http-mirage-client.0.0.7/_build/default/test/_build/_tests/E0F10B07-9F72-465B-BBB5-C3023F2AA47E/http/1.1.000.output")
[ERROR] The compilation of http-mirage-client failed at "/home/opam/.opam/opam-init/hooks/sandbox.sh build dune build -p http-mirage-client -j 39 @install @runtest".
```

**Comment by hannesm** [comment]
I wonder whether it would be possible to get this merged? This would allow me to unlock some further releases. Thanks a lot.

**Comment by mseri** [comment]
Looks good, thanks!

**Pull request merged**
