### PR TITLE
fixes following core suite v0.11

### PR DESCRIPTION
**Pull request by trefis**
I left the following packages broken:
- camlhighlight (a failed build is logged [here](https://ci.ocamllabs.io/log/saved/docker-run-f1fd63e27f717ac46fc3d7494f21a5e4/b2acb1b5f773afe387129ea5fc7b5a5dba83d612))
- nocrypto (a failed build is logged [here](https://ci.ocamllabs.io/log/saved/docker-run-acdc48bd8962eca2ae7b1407977f308c/0b95ffea49bb08e149bff429110fec57fa5951ce))
- yaml

That last one doesn't have any constraint at the moment, looking at the code it opens Sexplib.Conv without depending on sexplib in the opam file: someone else will have to look at it.

For the other two, I'm not sure what's going on. The build fails because some cmi files are not available (because the right -I haven't been passed).
It might be an issue with the content of some of our META files (in which case it's a jbuilder issue I guess), or it might just be that their build system is confused: IDK.

### CODE REVIEW

**Comment by avsm** [comment]
i'll fix yaml, thanks :)

**Comment by avsm** [comment]
```
#=== ERROR while installing prettiest.0.0.1 ===================================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -p prettiest -j 2
# path                 /home/opam/.opam/4.05.0/build/prettiest.0.0.1
# compiler             4.05.0
# exit-code            1
# env-file             /home/opam/.opam/4.05.0/build/prettiest.0.0.1/prettiest-7-eecdc3.env
# stdout-file          /home/opam/.opam/4.05.0/build/prettiest.0.0.1/prettiest-7-eecdc3.out
# stderr-file          /home/opam/.opam/4.05.0/build/prettiest.0.0.1/prettiest-7-eecdc3.err
### stderr ###
#       ocamlc lib/.prettiest.objs/prettiest.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.prettiest.objs -I /home/opam/.opam/4.05.0/lib/base -I /home/opam/.opam/4.05.0/lib/base/caml -I /home/opam/.opam/4.05.0/lib/base/shadow_stdlib -I /home/opam/.opam/4.05.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.05.0/lib/sexplib/0 -no-alias-deps -o lib/.prettiest.objs/prettiest.cmo -c -impl lib/prettiest.pp.ml)
# File "lib/prettiest.ml", line 68, characters 43-48:
# Error: Unbound value force
#     ocamlopt lib/.prettiest.objs/prettiest.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlopt.opt -w -40 -g -I lib/.prettiest.objs -I /home/opam/.opam/4.05.0/lib/base -I /home/opam/.opam/4.05.0/lib/base/caml -I /home/opam/.opam/4.05.0/lib/base/shadow_stdlib -I /home/opam/.opam/4.05.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.05.0/lib/sexplib/0 -no-alias-deps -o lib/.prettiest.objs/prettiest.cmx -c -impl lib/prettiest.pp.ml)
# File "lib/prettiest.ml", line 68, characters 43-48:
# Error: Unbound value force


```

**Comment by trefis** [comment]
That failure is happening with base v0.9, indeed `force` was added in `v0.10`.
I guess this package needs a lower bound as well...

**Comment by kit-ty-kate** [comment]
Good enough. I'll add the lower-bound in a followup pr

**Comment by kit-ty-kate** [comment]
Ping @pqwy & @hannesm for nocrypto (see the first message)

**Comment by kit-ty-kate** [comment]
Also, mirage has the same problem: https://ci.ocamllabs.io/log/saved/docker-build-79ef4b292a79e33f7957d93853f5ec9f/39d26910164aeef6b82a96d0dc54cbba42d96169

**Comment by diml** [comment]
I don't think so, there have been no changes in generated META file for a while.

**Comment by diml** [comment]
I think it's a problem with the hand-written META file for ipaddr.2.7.2 that is the problem:

```
version = "2.7.2"
description =
"A library for manipulation of IP (and MAC) address representations"
requires = "bytes sexplib"
```

i.e. it doesn't mention `ppx_sexp_conv.runtime-lib`, as a result the compiler doesn't see `ppx_sexp_conv_lib.cmi` when compiling mirage. Ipaddr.2.8.0 is using jbuilder so its META file will be correct, I suggest to simply bump the version constraint on ipaddr.

**Comment by kit-ty-kate** [comment]
@diml according to this log this is not the issue: https://travis-ci.org/ocaml/opam-repository/jobs/355944133

**Comment by diml** [comment]
I definitely was for mirage, I reproduced the error on my machine, and upgrading ipaddr to 2.8.0 fixed the issue

**Comment by diml** [comment]
I found the issue for nocrypto: when creating the packed module (with `ocamlfind ocamlopt -pack`), the build system doesn't pass the `-package ..` options. If I run the same command with `-package ppx_sexp_conv,sexplib` the build succeeds.

@pqwy you should try jbuilder for nocrypto :)

**Pull request merged**
