### PR TITLE
[new release] textmate-language (0.3.2)

### PR DESCRIPTION
**Pull request by alan-j-hu**
Tokenizing code with TextMate grammars for syntax highlighting

- Project page: <a href="https://github.com/alan-j-hu/ocaml-textmate-language">https://github.com/alan-j-hu/ocaml-textmate-language</a>
- Documentation: <a href="https://alan-j-hu.github.io/ocaml-textmate-language/">https://alan-j-hu.github.io/ocaml-textmate-language/</a>

##### CHANGES:

- Fix bug of incorrect, non-increasing string indices being returned.

### CODE REVIEW

**Comment by alan-j-hu** [comment]
This is supposed to be a non-breaking patch release that fixes incorrect token positions being output, but it looks like a reverse dependency has a test checking for exactly the same tokens being emitted as before. \:(

**Comment by mseri** [comment]
That's ok. We can add an upper bound separately for that

**Comment by mseri** [comment]
Thanks

**Comment by mseri** [comment]
Ping @patricoferris

**Pull request merged**
