### PR TITLE
Update charrua-{core,unix} to version 0.3.

### PR DESCRIPTION
**Pull request by haesbaert**

### CODE REVIEW

**Comment by hannesm** [comment]
the unix name should be `charrua-unix.0.3` (`.`, not `-` before 0) to make opam happy

**Comment by samoht** [comment]
```
#=== ERROR while installing charrua-core.0.3 ==================================#
# opam-version 1.2.2
# os           linux
# command      sh build.sh
# path         /home/travis/.opam/system/build/charrua-core.0.3
# compiler     system (4.02.3)
# exit-code    10
# env-file     /home/travis/.opam/system/build/charrua-core.0.3/charrua-core-8605-805f32.env
# stdout-file  /home/travis/.opam/system/build/charrua-core.0.3/charrua-core-8605-805f32.out
# stderr-file  /home/travis/.opam/system/build/charrua-core.0.3/charrua-core-8605-805f32.err
### stdout ###
# ocamlfind ocamlopt unix.cmxa -I /usr/lib/ocaml/ocamlbuild /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# ocamlfind ocamldep -package tcpip -package sexplib -package sexplib.syntax -package cstruct.unix -package ipaddr -package cstruct -package cstruct.syntax -syntax camlp4o -syntax pa_cstruct -modules lib/dhcp_wire.mli > lib/dhcp_wire.mli.depends
# + ocamlfind ocamldep -package tcpip -package sexplib -package sexplib.syntax -package cstruct.unix -package ipaddr -package cstruct -package cstruct.syntax -syntax camlp4o -syntax pa_cstruct -modules lib/dhcp_wire.mli > lib/dhcp_wire.mli.depends
# ocamlfind: Package `sexplib.syntax' not found
# Command exited with code 2.
```

**Comment by samoht** [comment]
@haesbaert there's a dependency to `camlp4` which is missing.

**Comment by haesbaert** [comment]
Thanks, I was out this weekend, will have a look tonight.

**Comment by hannesm** [comment]
:wine_glass: :D

**Comment by samoht** [comment]
@haesbaert ping?

**Comment by haesbaert** [comment]
Sorry, though week, will sort it all tonight.

**Comment by hannesm** [comment]
travis is happy now with christianos recent commit... :+1:

**Comment by samoht** [comment]
Great, thanks!

**Pull request merged**
