### PR TITLE
Jane Street packages: v0.14

### PR DESCRIPTION
**Pull request by xclerc**
This pull requests contains the `v0.14.0` version for all Jane Street packages.

(An announce with a changelog will be published on https://discuss.ocaml.org/
when this pull request is merged.)

### CODE REVIEW

**Comment by xclerc** [comment]
For the record, the relaxations introduced by https://github.com/ocaml/opam-repository/pull/16526/commits/e39d335aab47c74753ac316fc88aa147ac2771cc / https://github.com/ocaml/opam-repository/pull/16526/commits/983ad95fcb6c70ec20054b35c56dadf6f107ed81
are necessary because of dependencies of some Jane Street packages
on packages not part of this release.

**Comment by kit-ty-kate** [comment]
Several packages are uninstallable and fail with:
```
[ERROR] No solution for async.v0.14.0: The following dependencies couldn't be met:
          - async -> ppx_jane >= v0.14 -> ppx_fixed_literal
              unknown package
```

**Comment by xclerc** [comment]
Sorry for that; https://github.com/ocaml/opam-repository/pull/16526/commits/3845668a61063184ef893c3fd5d8d21b8916dcc2 should provide a fix.

**Comment by xclerc** [comment]
(Do not merge, please, there are pending issues.)

**Comment by kit-ty-kate** [comment]
ok, I'm cancelling all the CI builds to make some space for the other PRs until your issues get fixed.

**Comment by xclerc** [comment]
The issues were actually related to documentation generation,
the rest should be fine. Could you relaunch the CI?

**Comment by kit-ty-kate** [comment]
There are still some issues which make some of the packages not installable. For instance:
```
[ERROR] No solution for async_js.v0.14.0: The following dependencies couldn't be met:
          - async_js -> ppx_jane >= v0.14 -> ppx_stable >= v0.14 -> base >= v0.14 -> sexplib0 >= v0.14
          - async_js -> uri-sexp -> sexplib0 < v0.14
        Your request can't be satisfied:
          - No available version of sexplib0 satisfies the constraints
```

**Comment by xclerc** [comment]
Indeed, that was me being an idiot; should be better with https://github.com/ocaml/opam-repository/pull/16526/commits/d00ea17ddf82be6b2d750689a38c3e81e058b3e1.

**Comment by xclerc** [comment]
@kit-ty-kate Thanks for https://github.com/ocaml/opam-repository/pull/16526/commits/73868f46e123da70cde120672b226b0db6e98a81; I have imported
the fix to be sure all future exports have it.

**Comment by xclerc** [comment]
https://github.com/ocaml/opam-repository/pull/16526/commits/d664d8eb0fd8296d3f17f36b4c62fa34806b4d64 should address all reported problems (so far):
- compatibility with OCaml 4.11 (`async_unix`);
- compatibility with *BSD (`core` and `hardcaml`).

**Comment by kit-ty-kate** [comment]
Our CI really have lots of trouble to finish the whole build. It succeed so far, I think this should be good enough. Thanks!

**Pull request merged**
