### PR TITLE
Updated Lacaml

### PR DESCRIPTION
**Pull request by mmottl**

### CODE REVIEW

**Comment by mmottl** [comment]
Does anybody know why Travis is failing on build 6809.2 for Lacaml?  My OPAM dependencies specify BLAS and LAPACK for Ubuntu, but it's apparently not installed.

**Comment by samoht** [comment]
@mmottl opam 1.1 is trying to install a very old version of lacaml:  

```
=-=-= Installing lacaml.7.0.11 =-=-=
```

You either need to fill the depexts for that version or specify a version constraint somewhere.

**Comment by mmottl** [comment]
@samoht Ah, indeed.  I was under the impression this was about the currently submitted package only.

**Comment by Chris00** [comment]
@mmottl Also, is there any reason for the “*Merge branch 'master' of https://github.com/OCamlPro/opam-repository*”?  This is not the authoritative repository since a long time ago.

**Comment by mmottl** [comment]
@Chris00 Well-spotted, thanks!  It must have been a very long time ago that I set up this fork.

**Pull request merged**
