### PR TITLE
Add Ocaml 4.08.1+rc1

### PR DESCRIPTION
**Pull request by Octachron**
This is the new release candidate for OCaml 4.08.1, which fixes some bugs with packed library and ARM64 .

cc @avsm

### CODE REVIEW

**Comment by avsm** [comment]
Thanks! The CI containers are rebuilding the `4.08` ones to reflect this, and then I'll rebuild them again as soon as this is merged to have the official rc1 release. https://gitlab.com/ocaml-platform/ocaml-containers/pipelines/71709298

**Comment by kit-ty-kate** [comment]
I'm currently running Camelus manually, I'm going to merge it as soon as it's green and I'll launch a opam-health-check run using 4.08.1+rc1 right away

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by Octachron** [comment]
The rc1 announcement is out, now thanks!

**Pull request merged**
