### PR TITLE
Add OCaml Jupyter 0.0.0

### PR DESCRIPTION
**Pull request by akabe**
I released an OCaml kernel for [Jupyter notebook](http://jupyter.org/): https://akabe.github.io/ocaml-jupyter/

There is another OCaml kernel "[IOCaml](https://github.com/andrewray/iocaml)". It seems no longer maintained, and has some bugs, e.g., unable to use ppx and unsupported session keys. Thus I re-implemented a new program without such bugs.

### CODE REVIEW

**Comment by akabe** [comment]
I don't know the reason of failed test cases.

**Comment by camlspotter** [comment]
It failed to install zeromq development package for CentOS 7.  It is a glitch of conf-zmq.0.1 which your package depends on: https://github.com/ocaml/opam-repository/blob/master/packages/conf-zmq/conf-zmq.0.1/opam
My understanding is that you can leave it.  Mighty OPAM team will take care of it.

**Comment by akabe** [comment]
@camlspotter Thanks. I guess conf-zmq is not broken because building on Debian and Alpine Linux is not failed. However, `epel-release` is required in CentOS7 because CentOS 7 has no `zeromq-devel` in the standard package repository. I tried on docker:

```console
$ docker run -it --rm centos:7 bash
# yum update
# yum search all zeromq zmq
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: ftp.tsukuba.wide.ad.jp
 * extras: mirror.vastspace.net
 * updates: download.nus.edu.sg
Warning: No matches found for: zeromq
Warning: No matches found for: zmq
No matches found
# yum install -y epel-release
# yum search all zeromq zmq
...
zeromq-devel.x86_64 : Development files for zeromq
zeromq3-devel.x86_64 : Development files for zeromq3
zeromq.x86_64 : Software library for fast, message-based applications
zeromq3.x86_64 : Software library for fast, message-based applications
...
```

**Comment by akabe** [comment]
I tried editing [conf-zmq.1.0/opam](https://github.com/ocaml/opam-repository/blob/master/packages/conf-zmq/conf-zmq.0.1/opam) as follows:

```
opam-version: "1"
maintainer: "francois.berenger@inria.fr"
homepage: "http://zeromq.org/"
license: "LGPL"
build: [
  ["cc" "test.c" "-I/usr/local/include" "-L/usr/local/lib" "-lzmq"]
]
depexts: [
  [["debian"] ["libzmq3-dev"]]
  [["ubuntu"] ["libzmq3-dev"]]
  [["osx" "homebrew"] ["zeromq"]]
  [["alpine"] ["zeromq-dev"]]
  [["centos"] ["epel-release" "zeromq-devel"]]       # added epel-release
]
```

but it was failed installing `zeromq-devel` due to the reason of the above comment.

**Comment by akabe** [comment]
@avsm @samoht I need to install epel-release *before* zeromq-devel. Do you have any good ideas?   

P.S. Some other packages require epel-release, but `opam depext` for them is failed (I tried it on CentOS7 in Docker).

- https://github.com/ocaml/opam-repository/blob/b7ad53cbfeabd30d5670b3305d226c76d079c809/packages/hdf5/hdf5.0.1.3/opam
- https://github.com/ocaml/opam-repository/blob/c45df85d983a5466153de6ede8c60d514cf3d521/packages/sundialsml/sundialsml.2.7.0p0/opam

**Comment by avsm** [comment]
an issue for this on https://github.com/ocaml/opam-depext/issues would be appreciated -- sounds like we need to support yet more metadata for centos

**Comment by avsm** [comment]
cc @andrewray as well so he can comment on IOCaml's support status

**Comment by akabe** [comment]
@avsm Thanks. I'll issue this case.

cc @andrewray Sorry, I should contact you before publishing this package. I use IOCaml at work because IOCaml is an awesome package. I need ppx and comm messages, etc. but related issues and PRs are not updated from a few years ago.

**Comment by akabe** [comment]
I posted https://github.com/ocaml/opam-depext/issues/70. I'll add `os != "centos"` for passing CI for now.

**Comment by andrewray** [comment]
This package certainly fixes a need that a number of users have requested - namely updated protocol support.

IOcaml has been stalled for some time due partly to a severe lack of time, but also due to the complexity of updating the entire suite of kernel, server and javascript components.

I reality iocaml has become unsupported for some time as any help that has been offered has been concentrated on the kernel only, without considering the other projects.  That's mainly my fault for splitting the projects in the first place.  @rgrinberg has offered help in fixing some of this that I should really make some time to support.

**Comment by akabe** [comment]
@andrewray Thanks. I plan to only support kernel (and already support ppx and Jupyter protocol v5). JS kernel and server of IOCaml are useful, but I mainly use numerical computing libraries including C bindings (difficult to migrate to JS).

I was impressive when I first used IOCaml! I wanted to improve it, but some bugs are hard for me. As a result, I re-implemented.

**Comment by akabe** [comment]
Hmm. `os = linux` on CentOS7 in Docker. It seems `opam config list` contains no information related to linux distribution.

**Comment by akabe** [comment]
@avsm cc @yallop 

I fixed `conf-zmq` for installation of zeromq-devel after epel-release on CentOS7 (see [this script](https://gist.githubusercontent.com/akabe/9352e05d2413ccbefb2b52ea6ae81599/raw/7ad60a2be120849341cd7c5bf14656773cb7d405/centos-zmq.sh)) and added the fedora case.

**Comment by yallop** [comment]
Thanks for fixing the `conf-zmq` package, @akabe.  Since the changes only affect metadata, could you please just apply them directly to `conf-zmq.0.1` rather than creating a new version (`conf-zmq.0.2`)?

**Comment by akabe** [comment]
@yallop OK. I fix it.

**Comment by yallop** [comment]
Thanks!

**Pull request merged**
