### PR TITLE
[new release] mirage-crypto, mirage-crypto-rng, mirage-crypto-rng-mirage, mirage-crypto-rng-lwt, mirage-crypto-rng-eio, mirage-crypto-rng-async, mirage-crypto-pk and mirage-crypto-ec (0.11.1)

### PR DESCRIPTION
**Pull request by hannesm**
Simple symmetric cryptography for the modern age

- Project page: <a href="https://github.com/mirage/mirage-crypto">https://github.com/mirage/mirage-crypto</a>
- Documentation: <a href="https://mirage.github.io/mirage-crypto/doc">https://mirage.github.io/mirage-crypto/doc</a>

##### CHANGES:

* BUGFIX Chacha20 decrypt and encrypt with empty data (previously lead to
  segmentation fault, reported by @smondet in mirage/mirage-crypto#172, fix in mirage/mirage-crypto#173 by @reynir
  @hannesm), added tests with empty data for all symmetric ciphers

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks for noticing this... it's seems to be caused by @MisterDA's change in the docker images in https://github.com/ocurrent/ocaml-dockerfile/pull/147
```
opam@32f7b123968f:~$ opam list -s --color=never --depends-on 'mirage-crypto-pk.0.11.1' --coinstallable-with 'mirage-crypto-pk.0.11.1' --installable --all-versions --recursive --depopts
opam@32f7b123968f:~$ opam install webmachine.0.5.0 mirage-crypto-pk.0.11.1
[ERROR] Package conflict!
  * Missing dependency:
    - conf-gmp
    depends on the unavailable system package 'libgmp-dev'. Use `--no-depexts' to attempt installation anyway, or it is possible that a depext package name in the opam file is incorrect.

No solution found, exiting
opam@32f7b123968f:~$ sudo apt-get install libgmp-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libgmp-dev
opam@32f7b123968f:~$ sudo apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main arm64 Packages [8072 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main arm64 Packages [230 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [12.0 kB]
Fetched 8522 kB in 2s (4629 kB/s)                         
Reading package lists... Done
opam@32f7b123968f:~$ opam install webmachine.0.5.0 mirage-crypto-pk.0.11.1
The following actions will be performed:
=== install 43 packages
  - install angstrom            0.15.0       [required by uri]
 [...]
```
I'll get that reverted and fixed right away.

**Comment by hannesm** [comment]
CI looks fine to me - failures are unrelated.

**Comment by hannesm** [comment]
Is there anything I can do to drive this PR to completion (and getting it merged)?

**Comment by kit-ty-kate** [comment]
Thanks. Sorry for the wait

**Pull request merged**
