### PR TITLE
bump dolog version constraint in oplsr.8.0.1

### PR DESCRIPTION
**Pull request by UnixJunkie**
so that it can co-install with other recent things

PS: I tested locally; it can still compile

### CODE REVIEW

**Comment by mseri** [comment]
Thanks! Can you move this change to `opslr.8.0.1-1` and make it less restrictive, like
```
"dolog" {(>= "4.0.0" & < "5.0.0") | (>= "6.0.0")}
```
?

**Comment by UnixJunkie** [comment]
I weakened the version constraint, after some local testing.

**Comment by mseri** [comment]
Thanks. The installation failure is the usual issue with R packages, right?

**Comment by UnixJunkie** [comment]
Probably:
```
[ERROR] The installation of oplsr failed at "R CMD BATCH install_pls.r".
```
I tested locally though, I could install the package and R dependencies.

**Pull request merged**
