### PR TITLE
rename containers alpha releases so that they come before 2.0

### PR DESCRIPTION
**Pull request by c-cube**
grmlb grmbl version ordering

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Thanks. Merging now as it is not going to make the CI any more happy.

**Comment by emillon** [comment]
I believe that you only removed the `+alpha` and did not add the `~alpha` ones, is that intended?

**Comment by jpdeplaix** [comment]
Yes that was intended, we talked over irc about this, sorry for not having reporting this here.
Renaming the packages would have serve no purpose as it counts as if the packages were removed.

**Comment by emillon** [comment]
I was confused because I didn't see that 2.0 was released in the meantime. That makes sense, thanks!

**Pull request merged**
