### PR TITLE
[new release] OSCADml (0.2.0)

### PR DESCRIPTION
**Pull request by geoffder**
OCaml DSL for 3D solid modelling in OpenSCAD

- Project page: <a href="https://github.com/OCADml/OSCADml">https://github.com/OCADml/OSCADml</a>
- Documentation: <a href="https://ocadml.github.io/OSCADml">https://ocadml.github.io/OSCADml</a>

##### CHANGES:

- add dimension type parameter to `Scad.t` (adjust to abstract Gg types in OCADml)

### CODE REVIEW

**Comment by geoffder** [comment]
Ah woops, didn't mean to hit submit on this one (assuming that I should let the new release of OCADml that this depends on through first). Should I close this and redo later, or should I just leave it for now?

**Comment by kit-ty-kate** [comment]
Either way is fine. I've converted it to a draft so we don't merge it by mistake. Feel free to click on "Ready for review" when it's ready or close it if you prefer.

**Comment by geoffder** [comment]
Undrafted now that OCADml v0.3.0 is merged.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
