### PR TITLE
[new release] irmin and all (2.9.0)

### PR DESCRIPTION
**Pull request by samoht**
PPX deriver for Irmin type representations

- Project page: <a href="https://github.com/mirage/irmin">https://github.com/mirage/irmin</a>

### Fixed

- **irmin-pack**
   - Improved the performance of Index encode and decode operations by
     eliminating intermediate allocations (up to 5% fewer minor words
     allocated) (mirage/irmin#1577, @CraigFe)
   - Reduce the number of backend nodes built during export
     (up to 20% fewer minor words allocated) (mirage/irmin#1553, @Ngoguey42)

### Added

- **irmin**
  - Add Merkle Proofs and expose function to convert a proof to and from a tree.
    Once converted, normal tree operations can be performed on the proof, as
    long at it access values contained in the proof.
    (mirage/irmin#1583, @samoht, @Ngoguey42, @icristescu)

### Changed

- **irmin-pack**
  - Limit inode depth (mirage/irmin#1596, #samoht)
  - Adapt to index 1.5.0 (mirage/irmin#1593, @icristescu)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The tests seem to segfault on s390x:
```
#=== ERROR while compiling irmin.2.9.0 ========================================#
# context              2.1.1 | linux/s390x | ocaml-base-compiler.4.13.1 | pinned(https://github.com/mirage/irmin/releases/download/2.9.0/irmin-2.9.0.tbz)
# path                 ~/.opam/4.13/.opam-switch/build/irmin.2.9.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p irmin -j 3
# exit-code            1
# env-file             ~/.opam/log/irmin-1833-af4727.env
# output-file          ~/.opam/log/irmin-1833-af4727.out
### output ###
#         test alias test/irmin/runtest (got signal SEGV)
# (cd _build/default/test/irmin && ./test.exe)
# Testing `irmin'.
# This run has ID `XSEPBKU1'.
# 
#   [OK]          tree          0   bindings.
#   [OK]          tree          1   paginated bindings.
#   [OK]          tree          2   diff.
#   [OK]          tree          3   add.
#   [OK]          tree          4   remove.
#   [OK]          tree          5   update.

-         test alias test/irmin/runtest (got signal SEGV)
- (cd _build/default/test/irmin && ./test.exe)
- Testing `irmin'.
- This run has ID `XSEPBKU1'.
- 
-   [OK]          tree          0   bindings.
-   [OK]          tree          1   paginated bindings.
-   [OK]          tree          2   diff.
-   [OK]          tree          3   add.
-   [OK]          tree          4   remove.
-   [OK]          tree          5   update.
```

**Comment by kit-ty-kate** [comment]
Something seems wrong with frame-pointer on as well:
```
#=== ERROR while compiling irmin-pack.2.9.0 ===================================#
# context              2.1.1 | linux/x86_64 | ocaml-options-only-fp.1 | pinned(https://github.com/mirage/irmin/releases/download/2.9.0/irmin-2.9.0.tbz)
# path                 ~/.opam/4.13/.opam-switch/build/irmin-pack.2.9.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p irmin-pack -j 31
# exit-code            1
# env-file             ~/.opam/log/irmin-pack-2431-a9ad5e.env
# output-file          ~/.opam/log/irmin-pack-2431-a9ad5e.out
### output ###
#         test alias test/irmin-pack/runtest (exit 2)
# (cd _build/default/test/irmin-pack && ./test.exe -q --color=always)
# Testing `irmin-pack'.
# This run has ID `MZ14TDFH'.
# 
#   [OK]          PACK                      0   Basic operations on contents.
#   [OK]          PACK                      1   Basic operations on nodes.
#   [OK]          PACK                      2   Basic operations on commits.
#   [OK]          PACK                      3   Basic operations on branches.
#   [OK]          PACK                      4   Hash operations on trees.
#   [OK]          PACK                      5   Basic merge operations.
#   [OK]          PACK                      6   Basic operations on slices.
#   [OK]          PACK                      7   Test merges on tree updates.
#   [OK]          PACK                      8   Tree caches and hashconsing.
#   [OK]          PACK                      9   Complex histories.
#   [OK]          PACK                     10   Empty stores.
#   [OK]          PACK                     11   Private node manipulation.
#   [OK]          PACK                     12   High-level store operations.
#   [OK]          PACK                     13   High-level operations on trees.
#   [OK]          PACK                     14   High-level store synchronisation.
#   [OK]          PACK                     15   High-level store merges.
#   [OK]          PACK                     16   Unrelated merges.
#   [OK]          PACK                     17   Low-level concurrency.
#   [OK]          PACK                     18   Concurrent updates.
#   [OK]          PACK                     19   with_tree strategies.
#   [OK]          PACK                     20   Concurrent head updates.
#   [OK]          PACK                     21   Concurrent merges.
#   [OK]          PACK                     22   Shallow objects.
#   [OK]          PACK                     23   Closure with disconnected commits.
#   [OK]          PACK                     24   Clear.
#   [OK]          PACK                     25   Graph.Iter.
#   [OK]          PACK                     26   Watch.Callbacks and exceptions.
#   [OK]          PACK MEM                  0   Basic operations on contents.
#   [OK]          PACK MEM                  1   Basic operations on nodes.
#   [OK]          PACK MEM                  2   Basic operations on commits.
#   [OK]          PACK MEM                  3   Basic operations on branches.
#   [OK]          PACK MEM                  4   Hash operations on trees.
#   [OK]          PACK MEM                  5   Basic merge operations.
#   [OK]          PACK MEM                  6   Basic operations on slices.
#   [OK]          PACK MEM                  7   Test merges on tree updates.
#   [OK]          PACK MEM                  8   Tree caches and hashconsing.
#   [OK]          PACK MEM                  9   Complex histories.
#   [OK]          PACK MEM                 10   Empty stores.
#   [OK]          PACK MEM                 11   Private node manipulation.
#   [OK]          PACK MEM                 12   High-level store operations.
#   [OK]          PACK MEM                 13   High-level operations on trees.
#   [OK]          PACK MEM                 14   High-level store synchronisation.
#   [OK]          PACK MEM                 15   High-level store merges.
#   [OK]          PACK MEM                 16   Unrelated merges.
#   [OK]          PACK MEM                 17   Low-level concurrency.
#   [OK]          PACK MEM                 18   Concurrent updates.
#   [OK]          PACK MEM                 19   with_tree strategies.
#   [OK]          PACK MEM                 20   Concurrent head updates.
#   [OK]          PACK MEM                 21   Concurrent merges.
#   [OK]          PACK MEM                 22   Shallow objects.
#   [OK]          PACK MEM                 23   Closure with disconnected commits.
#   [OK]          PACK MEM                 24   Clear.
#   [OK]          PACK MEM                 25   Graph.Iter.
#   [OK]          PACK MEM                 26   Watch.Callbacks and exceptions.
#   [OK]          LAYERED_PACK              0   Basic operations on branches.
#   [OK]          LAYERED_PACK              1   Basic merge operations.
#   [OK]          LAYERED_PACK              2   Complex histories.
#   [OK]          LAYERED_PACK              3   Empty stores.
#   [OK]          LAYERED_PACK              4   Basic operations on slices.
#   [OK]          LAYERED_PACK              5   Private node manipulation.
#   [OK]          LAYERED_PACK              6   High-level store merges.
#   [OK]          LAYERED_PACK              7   Unrelated merges.
# > [FAIL]        LAYERED_PACK              8   Test commits and graphs.
```

**Comment by samoht** [comment]
I've added a constraint for s390x ; The "Test commits and graphs." test is a bit flaky https://github.com/mirage/irmin/issues/1383, I don't think it's related to anything we released in 2.9 so I'd ignore that error.

**Comment by kit-ty-kate** [comment]
@samoht If tests are flaky could you disable them for all versions of irmin-pack?

**Comment by kit-ty-kate** [comment]
actually nevermind i’ve done it in #20038

**Pull request merged**
