### PR TITLE
[new release] iter (1.2)

### PR DESCRIPTION
**Pull request by Drup**
## 1.2

- Rename the library to Iter.
- Add `from_labeled_iter`.
- Use `raise_notrace` for internal exceptions.

### CODE REVIEW

**Comment by Drup** [comment]
cc @c-cube

**Comment by mseri** [comment]
OCaml 4.02 failure is not really a failure. Feel free to merge unless you want to do something about it:
```
- SUCCESS
- File "README.md", line 1, characters 0-0:
-         diff (internal) (exit 1)
- (cd _build/default && /usr/bin/diff -u README.md README.md.corrected)
- --- README.md	2019-03-08 21:11:39.655095999 +0000
- +++ README.md.corrected	2019-03-08 21:11:40.962441999 +0000
- @@ -73,7 +73,7 @@
-  
-  ```ocaml
-  # let h: (int, string) Hashtbl.t = Hashtbl.create 16;;
- -val h : (int, string) Hashtbl.t = <abstr>
- +val h : (int, bytes) Hashtbl.t = <abstr>
-  # for i = 0 to 10 do
-       Hashtbl.add h i (string_of_int i)
-    done;;
- @@ -84,7 +84,7 @@
-  
-  # (* now to get the values *)
-    Iter.of_hashtbl h |> Iter.map snd |> Iter.to_list;;
- -- : string list = ["6"; "2"; "8"; "7"; "3"; "5"; "4"; "9"; "0"; "10"; "1"]
- +- : bytes list = ["6"; "2"; "8"; "7"; "3"; "5"; "4"; "9"; "0"; "10"; "1"]
-  ```
-  
-  ### Replacing `for` loops
- @@ -119,7 +119,7 @@
-    | Var of string
-    | App of term * term
-    | Lambda of term ;;
- -type term = Var of string | App of term * term | Lambda of term
- +type term = Var of bytes | App of term * term | Lambda of term
-  
-  # let rec subterms : term -> term Iter.t =
-    fun t ->
- @@ -138,13 +138,13 @@
-      Iter.filter_map
-        (function Var s -> Some s | _ -> None)
-        (subterms t) ;;
- -val vars : term -> string Iter.t = <fun>
- +val vars : term -> bytes Iter.t = <fun>
-  
-  # let size t = Iter.length (subterms t) ;;
-  val size : term -> int = <fun>
-  
-  # let vars_list l = Iter.(of_list l |> flat_map vars);;
- -val vars_list : term list -> string Iter.t = <fun>
- +val vars_list : term list -> bytes Iter.t = <fun>
-  ```
-  
-  ### Permutations
[ERROR] The compilation of iter failed at
        "/home/travis/.opam/opam-init/hooks/sandbox.sh build dune runtest -p
        iter".
```

**Comment by c-cube** [comment]
Ah I've seen that in similar projects, and didn't find a way other than disabling tests on 4.02 :disappointed:

**Comment by mseri** [comment]
If it's just that, I think I know how to do it 🤞

**Comment by mseri** [comment]
It worked, merging

**Pull request merged**
