### PR TITLE
Octez 17.2 packages

### PR DESCRIPTION
**Pull request by killian-delarue**
Octez v17.2 packages.

### CODE REVIEW

**Comment by avsm** [comment]
macOS tests are failing:

```

#=== ERROR while compiling tezos-client-009-PsFLoren.17.2 =====================#
# context              2.1.5 | macos/x86_64 | ocaml-base-compiler.4.14.1 | pinned(https://gitlab.com/tezos/tezos/-/archive/v17.2/tezos-17.2.tar.gz)
# path                 ~/.opam/4.14.1/.opam-switch/build/tezos-client-009-PsFLoren.17.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p tezos-client-009-PsFLoren -j 11
# exit-code            1
# env-file             ~/.opam/log/tezos-client-009-PsFLoren-1784-8a74e3.env
# output-file          ~/.opam/log/tezos-client-009-PsFLoren-1784-8a74e3.out
### output ###
# File "src/proto_009_PsFLoren/lib_client/dune", line 4, characters 0-723:
#  4 | (library
#  5 |  (name tezos_client_009_PsFLoren)
#  6 |  (public_name tezos-client-009-PsFLoren)
# ....
# 27 |   -open Tezos_client_base
# 28 |   -open Tezos_protocol_009_PsFLoren
# 29 |   -open Tezos_protocol_plugin_009_PsFLoren))
# (cd _build/default && /Users/mac1000/.opam/4.14.1/bin/ocamlopt.opt -w -40 -w -24 -g -g -O3 -o src/proto_009_PsFLoren/lib_client/.tezos_client_009_PsFLoren.inline-tests/inline_test_runner_tezos_client_009_PsFLoren.exe /Users/mac1000/.opam/4.14.1/lib/cstruct/cstruct.cmxa -I /Users/mac1000/.opam/4.14.1/lib/cstruct /Users/mac1000/.opam/4.14.1/lib/hex/hex.cmxa /Users/mac1000/.opam/4.14.1/lib/zarith/zarith.cmxa -I /Users/mac1000/.opam/4.14.1/lib/zarith /Users/mac1000/.opam/4.14.1/lib/zarith_stubs_js/zarith_stubs_js.cmxa -I /Users/mac1000/.opam/4.14.1/lib/ocaml /Users/mac1000/.opam/4.14.1/lib/lwt/lwt.cmxa /Users/mac1000/.opam/4.14.1/lib/ringo/ringo.cmxa /Users/mac1000/.opam/4.14.1/lib/aches/vache/vache.cmxa /Users/mac1000/.opam/4.14.1/lib/aches/rache/rache.cmxa /Users/mac1000/.opam/4.14.1/lib/aches/aches.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_inline_test/config/inline_test_config.cmxa /Users/mac1000/.opam/4.14.1/lib/base/base_internalhash_types/base_internalhash_types.cmxa -I /Users/mac1000/.opam/4.14.1/lib/base/base_internalhash_types /Users/mac1000/.opam/4.14.1/lib/base/caml/caml.cmxa /Users/mac1000/.opam/4.14.1/lib/sexplib0/sexplib0.cmxa /Users/mac1000/.opam/4.14.1/lib/base/shadow_stdlib/shadow_stdlib.cmxa /Users/mac1000/.opam/4.14.1/lib/base/base.cmxa -I /Users/mac1000/.opam/4.14.1/lib/base /Users/mac1000/.opam/4.14.1/lib/jane-street-headers/jane_street_headers.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_sexp_conv/runtime-lib/ppx_sexp_conv_lib.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_compare/runtime-lib/ppx_compare_lib.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_enumerate/runtime-lib/ppx_enumerate_lib.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_hash/runtime-lib/ppx_hash_lib.cmxa /Users/mac1000/.opam/4.14.1/lib/time_now/time_now.cmxa -I /Users/mac1000/.opam/4.14.1/lib/time_now /Users/mac1000/.opam/4.14.1/lib/ppx_inline_test/runtime-lib/ppx_inline_test_lib.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_here/runtime-lib/ppx_here_lib.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_expect/common/expect_test_common.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_expect/config_types/expect_test_config_types.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_expect/collector/expect_test_collector.cmxa -I /Users/mac1000/.opam/4.14.1/lib/ppx_expect/collector /Users/mac1000/.opam/4.14.1/lib/ppx_expect/config/expect_test_config.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-stdlib/tezos_stdlib.cmxa -I /Users/mac1000/.opam/4.14.1/lib/tezos-stdlib /Users/mac1000/.opam/4.14.1/lib/stringext/stringext.cmxa /Users/mac1000/.opam/4.14.1/lib/bigstringaf/bigstringaf.cmxa -I /Users/mac1000/.opam/4.14.1/lib/bigstringaf /Users/mac1000/.opam/4.14.1/lib/angstrom/angstrom.cmxa /Users/mac1000/.opam/4.14.1/lib/uri/uri.cmxa /Users/mac1000/.opam/4.14.1/lib/json-data-encoding/json_data_encoding.cmxa /Users/mac1000/.opam/4.14.1/lib/ocplib-endian/ocplib_endian.cmxa /Users/mac1000/.opam/4.14.1/lib/json-data-encoding-bson/json_data_encoding_bson.cmxa /Users/mac1000/.opam/4.14.1/lib/uutf/uutf.cmxa /Users/mac1000/.opam/4.14.1/lib/jsonm/jsonm.cmxa /Users/mac1000/.opam/4.14.1/lib/ezjsonm/ezjsonm.cmxa /Users/mac1000/.opam/4.14.1/lib/either/either.cmxa /Users/mac1000/.opam/4.14.1/lib/data-encoding/data_encoding.cmxa /Users/mac1000/.opam/4.14.1/lib/seqes/seqes.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-lwt-result-stdlib/bare/functor-outputs/bare_functor_outputs.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-lwt-result-stdlib/bare/sigs/bare_sigs.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-lwt-result-stdlib/bare/structs/bare_structs.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-lwt-result-stdlib/traced/functor-outputs/traced_functor_outputs.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-lwt-result-stdlib/traced/sigs/traced_sigs.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-lwt-result-stdlib/traced/structs/traced_structs.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-lwt-result-stdlib/tezos_lwt_result_stdlib.cmxa /Users/mac1000/.opam/4.14.1/lib/bigarray-compat/bigarray_compat.cmxa /Users/mac1000/.opam/4.14.1/lib/stdlib-shims/stdlib_shims.cmxa /Users/mac1000/.opam/4.14.1/lib/integers/integers.cmxa -I /Users/mac1000/.opam/4.14.1/lib/integers /Users/mac1000/.opam/4.14.1/lib/ctypes/ctypes.cmxa -I /Users/mac1000/.opam/4.14.1/lib/ctypes /Users/mac1000/.opam/4.14.1/lib/hacl-star-raw/ocamlevercrypt.cmxa -I /Users/mac1000/.opam/4.14.1/lib/hacl-star-raw /Users/mac1000/.opam/4.14.1/lib/hacl-star/hacl_star.cmxa /Users/mac1000/.opam/4.14.1/lib/integers_stubs_js/integers_stubs_js.cmxa /Users/mac1000/.opam/4.14.1/lib/ctypes_stubs_js/ctypes_stubs_js.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-hacl/tezos_hacl.cmxa /Users/mac1000/.opam/4.14.1/lib/ocaml/unix.cmxa -I /Users/mac1000/.opam/4.14.1/lib/ocaml /Users/mac1000/.opam/4.14.1/lib/ocaml/bigarray.cmxa -I /Users/mac1000/.opam/4.14.1/lib/ocaml /Users/mac1000/.opam/4.14.1/lib/bigstring/bigstring.cmxa /Users/mac1000/.opam/4.14.1/lib/secp256k1-internal/libsecp256k1.cmxa -I /Users/mac1000/.opam/4.14.1/lib/secp256k1-internal /Users/mac1000/.opam/4.14.1/lib/lwt-canceler/lwt_canceler.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-error-monad/tezos_error_monad.cmxa /Users/mac1000/.opam/4.14.1/lib/resto/resto.cmxa /Users/mac1000/.opam/4.14.1/lib/resto-directory/resto_directory.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-rpc/tezos_rpc.cmxa /Users/mac1000/.opam/4.14.1/lib/bls12-381/bls12_381.cmxa -I /Users/mac1000/.opam/4.14.1/lib/bls12-381 /Users/mac1000/.opam/4.14.1/lib/octez-bls12-381-signature/bls12_381_signature.cmxa -I /Users/mac1000/.opam/4.14.1/lib/octez-bls12-381-signature /Users/mac1000/.opam/4.14.1/lib/tezos-crypto/tezos_crypto.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-micheline/tezos_micheline.cmxa /Users/mac1000/.opam/4.14.1/lib/lwt_log/core/lwt_log_core.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-event-logging/tezos_event_logging.cmxa /Users/mac1000/.opam/4.14.1/lib/ptime/ptime.cmxa /Users/mac1000/.opam/4.14.1/lib/ptime/clock/os/ptime_clock.cmxa -I /Users/mac1000/.opam/4.14.1/lib/ptime/clock/os /Users/mac1000/.opam/4.14.1/lib/macaddr/macaddr.cmxa /Users/mac1000/.opam/4.14.1/lib/domain-name/domain_name.cmxa /Users/mac1000/.opam/4.14.1/lib/ipaddr/ipaddr.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-base/tezos_base.cmxa /Users/mac1000/.opam/4.14.1/lib/re/re.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-clic/tezos_clic.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-p2p-services/tezos_p2p_services.cmxa /Users/mac1000/.opam/4.14.1/lib/result/result.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_deriving/runtime/ppx_deriving_runtime.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-version/parser/tezos_version_parser.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-version/tezos_version.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-context/sigs/tezos_context_sigs.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-context/merkle_proof_encoding/tezos_context_merkle_proof_encoding.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-shell-services/tezos_shell_services.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-sapling/tezos_sapling.cmxa -I /Users/mac1000/.opam/4.14.1/lib/tezos-sapling /Users/mac1000/.opam/4.14.1/lib/tezos-client-base/tezos_client_base.cmxa /Users/mac1000/.opam/4.14.1/lib/optint/optint.cmxa /Users/mac1000/.opam/4.14.1/lib/base64/base64.cmxa /Users/mac1000/.opam/4.14.1/lib/fmt/fmt.cmxa /Users/mac1000/.opam/4.14.1/lib/repr/repr.cmxa /Users/mac1000/.opam/4.14.1/lib/ocaml/compiler-libs/ocamlcommon.cmxa /Users/mac1000/.opam/4.14.1/lib/ocaml-compiler-libs/common/ocaml_common.cmxa /Users/mac1000/.opam/4.14.1/lib/ppxlib/astlib/astlib.cmxa /Users/mac1000/.opam/4.14.1/lib/ppxlib/ast/ppxlib_ast.cmxa /Users/mac1000/.opam/4.14.1/lib/ocaml-compiler-libs/shadow/ocaml_shadow.cmxa /Users/mac1000/.opam/4.14.1/lib/ppxlib/print_diff/ppxlib_print_diff.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_derivers/ppx_derivers.cmxa /Users/mac1000/.opam/4.14.1/lib/ppxlib/traverse_builtins/ppxlib_traverse_builtins.cmxa /Users/mac1000/.opam/4.14.1/lib/ppxlib/stdppx/stdppx.cmxa /Users/mac1000/.opam/4.14.1/lib/ppxlib/ppxlib.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_repr/lib/ppx_repr_lib.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_repr/ppx_repr.cmxa /Users/mac1000/.opam/4.14.1/lib/octez-bls12-381-polynomial/octez_bls12_381_polynomial.cmxa -I /Users/mac1000/.opam/4.14.1/lib/octez-bls12-381-polynomial /Users/mac1000/.opam/4.14.1/lib/stdint/stdint.cmxa -I /Users/mac1000/.opam/4.14.1/lib/stdint /Users/mac1000/.opam/4.14.1/lib/octez-bls12-381-hash/bls12_381_hash.cmxa -I /Users/mac1000/.opam/4.14.1/lib/octez-bls12-381-hash /Users/mac1000/.opam/4.14.1/lib/octez-polynomial/polynomial.cmxa /Users/mac1000/.opam/4.14.1/lib/astring/astring.cmxa /Users/mac1000/.opam/4.14.1/lib/cmdliner/cmdliner.cmxa /Users/mac1000/.opam/4.14.1/lib/alcotest/stdlib_ext/alcotest_stdlib_ext.cmxa /Users/mac1000/.opam/4.14.1/lib/fmt/fmt_cli.cmxa /Users/mac1000/.opam/4.14.1/lib/alcotest/engine/alcotest_engine.cmxa /Users/mac1000/.opam/4.14.1/lib/fmt/fmt_tty.cmxa /Users/mac1000/.opam/4.14.1/lib/alcotest/alcotest.cmxa -I /Users/mac1000/.opam/4.14.1/lib/alcotest /Users/mac1000/.opam/4.14.1/lib/eqaf/eqaf.cmxa /Users/mac1000/.opam/4.14.1/lib/octez-mec/mec.cmxa /Users/mac1000/.opam/4.14.1/lib/octez-plompiler/plompiler.cmxa /Users/mac1000/.opam/4.14.1/lib/octez-plonk/plonk.cmxa /Users/mac1000/.opam/4.14.1/lib/ocplib-endian/bigstring/ocplib_endian_bigstring.cmxa /Users/mac1000/.opam/4.14.1/lib/ocaml/threads/threads.cmxa -I /Users/mac1000/.opam/4.14.1/lib/ocaml /Users/mac1000/.opam/4.14.1/lib/lwt/unix/lwt_unix.cmxa -I /Users/mac1000/.opam/4.14.1/lib/lwt/unix /Users/mac1000/.opam/4.14.1/lib/tezos-crypto-dal/tezos_crypto_dal.cmxa /Users/mac1000/.opam/4.14.1/lib/class_group_vdf/class_group_vdf.cmxa -I /Users/mac1000/.opam/4.14.1/lib/class_group_vdf /Users/mac1000/.opam/4.14.1/lib/aches-lwt/lache/lache.cmxa /Users/mac1000/.opam/4.14.1/lib/aches-lwt/aches_lwt.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-protocol-environment/sigs-internals/tezos_protocol_environment_sigs_internals.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-protocol-environment/sigs/tezos_protocol_environment_sigs.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-tree-encoding/tezos_tree_encoding.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-lazy-containers/tezos_lazy_containers.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-webassembly-interpreter/tezos_webassembly_interpreter.cmxa /Users/mac1000/.opam/4.14.1/lib/irmin/data/irmin_data.cmxa /Users/mac1000/.opam/4.14.1/lib/bheap/binary_heap.cmxa /Users/mac1000/.opam/4.14.1/lib/digestif/c/digestif_c.cmxa -I /Users/mac1000/.opam/4.14.1/lib/digestif/c /Users/mac1000/.opam/4.14.1/lib/logs/logs.cmxa /Users/mac1000/.opam/4.14.1/lib/logs/logs_fmt.cmxa /Users/mac1000/.opam/4.14.1/lib/mtime/mtime.cmxa /Users/mac1000/.opam/4.14.1/lib/ocamlgraph/graph.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_irmin/internal-lib/ppx_irmin_internal_lib.cmxa /Users/mac1000/.opam/4.14.1/lib/irmin/irmin.cmxa /Users/mac1000/.opam/4.14.1/lib/irmin-pack/irmin_pack.cmxa /Users/mac1000/.opam/4.14.1/lib/irmin/mem/irmin_mem.cmxa /Users/mac1000/.opam/4.14.1/lib/irmin-pack/mem/irmin_pack_mem.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-context/encoding/tezos_context_encoding.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-context/helpers/tezos_context_helpers.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-context/memory/tezos_context_memory.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-scoru-wasm/tezos_scoru_wasm.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-protocol-environment/structs/tezos_protocol_environment_structs.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-protocol-environment/tezos_protocol_environment.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-protocol-009-PsFLoren/environment/tezos_protocol_environment_009_PsFLoren.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-protocol-009-PsFLoren/raw/tezos_raw_protocol_009_PsFLoren.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-protocol-009-PsFLoren/tezos_protocol_009_PsFLoren.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-protocol-009-PsFLoren/lifted/tezos_protocol_009_PsFLoren_lifted.cmxa /Users/mac1000/.opam/4.14.1/lib/uri-sexp/uri_sexp.cmxa /Users/mac1000/.opam/4.14.1/lib/cohttp/cohttp.cmxa /Users/mac1000/.opam/4.14.1/lib/logs/logs_lwt.cmxa /Users/mac1000/.opam/4.14.1/lib/cohttp-lwt/cohttp_lwt.cmxa /Users/mac1000/.opam/4.14.1/lib/resto-cohttp/resto_cohttp.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-rpc-http/tezos_rpc_http.cmxa /Users/mac1000/.opam/4.14.1/lib/resto-cohttp-client/resto_cohttp_client.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-rpc-http-client/tezos_rpc_http_client.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-signer-services/tezos_signer_services.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-signer-backends/tezos_signer_backends.cmxa /Users/mac1000/.opam/4.14.1/lib/tezos-protocol-plugin-009-PsFLoren/tezos_protocol_plugin_009_PsFLoren.cmxa src/proto_009_PsFLoren/lib_client/tezos_client_009_PsFLoren.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_inline_test/runner/lib/ppx_inline_test_runner_lib.cmxa -I /Users/mac1000/.opam/4.14.1/lib/ppx_inline_test/runner/lib /Users/mac1000/.opam/4.14.1/lib/stdio/stdio.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_expect/matcher/expect_test_matcher.cmxa /Users/mac1000/.opam/4.14.1/lib/ppx_expect/evaluator/ppx_expect_evaluator.cmxa src/proto_009_PsFLoren/lib_client/.tezos_client_009_PsFLoren.inline-tests/.tezos_client_009_PsFLoren.inline-tests.eobjs/native/dune__exe__Inline_test_runner_tezos_client_009_PsFLoren.cmx -linkall)
# ld: warning: directory not found for option '-L/opt/local/lib'
# Undefined symbols for architecture x86_64:
#   "_SecRandomCopyBytes", referenced from:
#       ring::rand::darwin::fill::h02c81474def21321 in librustzcash.a(ring-1145901954d225e5.ring.4cf902cd-cgu.11.rcgu.o)
#       ring::ec::suite_b::ecdsa::signing::EcdsaKeyPair::new::h5c691f2f70e1b587 in librustzcash.a(ring-1145901954d225e5.ring.4cf902cd-cgu.1.rcgu.o)
#   "_kSecRandomDefault", referenced from:
#       ring::rand::darwin::fill::h02c81474def21321 in librustzcash.a(ring-1145901954d225e5.ring.4cf902cd-cgu.11.rcgu.o)
#       ring::ec::suite_b::ecdsa::signing::EcdsaKeyPair::new::h5c691f2f70e1b587 in librustzcash.a(ring-1145901954d225e5.ring.4cf902cd-cgu.1.rcgu.o)
# ld: symbol(s) not found for architecture x86_64
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# File "caml_startup", line 1:
# Error: Error during linking (exit code 1)
```

**Comment by avsm** [comment]
```
#=== ERROR while compiling octez-distributed-internal.17.2 ====================#
# context              2.2.0~alpha | linux/x86_64 | ocaml-base-compiler.5.0.0 | pinned(https://gitlab.com/tezos/tezos/-/archive/v17.2/tezos-17.2.tar.gz)
# path                 ~/.opam/5.0/.opam-switch/build/octez-distributed-internal.17.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p octez-distributed-internal -j 255
# exit-code            1
# env-file             ~/.opam/log/octez-distributed-internal-7-6dc813.env
# output-file          ~/.opam/log/octez-distributed-internal-7-6dc813.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/lib_distributed_internal/src/.distributed.objs/byte -I /home/opam/.opam/5.0/lib/ocaml/unix -intf-suffix .ml -no-alias-deps -o src/lib_distributed_internal/src/.distributed.objs/byte/distributed.cmo -c -impl src/lib_distributed_internal/src/distributed.ml)
# File "src/lib_distributed_internal/src/distributed.ml", line 73, characters 25-70:
# 73 | module Node_id_hashtbl = Hashtbl.MakeSeeded (Node_id_seeded_hash_type)
#                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Modules do not match:
#        sig
#          type t = Node_id.t
#          val equal : t -> t -> bool
#          val hash : int -> t -> int
#        end
#      is not included in Hashtbl.SeededHashedType
#      The value `seeded_hash' is required but not provided
#      File "hashtbl.mli", line 411, characters 4-36: Expected declaration
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -O3 -I src/lib_distributed_internal/src/.distributed.objs/byte -I src/lib_distributed_internal/src/.distributed.objs/native -I /home/opam/.opam/5.0/lib/ocaml/unix -intf-suffix .ml -no-alias-deps -o src/lib_distributed_internal/src/.distributed.objs/native/distributed.cmx -c -impl src/lib_distributed_internal/src/distributed.ml)
# File "src/lib_distributed_internal/src/distributed.ml", line 73, characters 25-70:
# 73 | module Node_id_hashtbl = Hashtbl.MakeSeeded (Node_id_seeded_hash_type)
#                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Modules do not match:
#        sig
#          type t = Node_id.t
#          val equal : t -> t -> bool
#          val hash : int -> t -> int
#        end
#      is not included in Hashtbl.SeededHashedType
#      The value `seeded_hash' is required but not provided
#      File "hashtbl.mli", line 411, characters 4-36: Expected declaration
```

also needs a 5.0 constraint

**Comment by raphael-proust** [comment]
Rather than an ocaml5 constraint, normally we do

```
  (* See [src/lib_base/tzPervasives.ml] for an explanation *)
  [@@@ocaml.warning "-32"]

  let hash = …

  let seeded_hash = Hashtbl.seeded_hash

  [@@@ocaml.warning "+32"]
```

to be compatible with both versions.

**Comment by raphael-proust** [comment]
https://gitlab.com/tezos/tezos/-/merge_requests/9576 an MR to fix this

**Comment by avsm** [comment]
Why are older releases now being marked as unavailable in 073c68886ce0cf9519e828abd56bcbb6b1a0979b as part of this PR?  Until https://github.com/ocaml/opam-repository/pull/23649 is resolved, they shouldn't be just removed arbitrarily as that will break anyone else pinning those specific versions.

**Comment by killian-delarue** [comment]
> Why are older releases now being marked as unavailable in [073c688](https://github.com/ocaml/opam-repository/commit/073c68886ce0cf9519e828abd56bcbb6b1a0979b) as part of this PR? Until #23649 is resolved, they shouldn't be just removed arbitrarily as that will break anyone else pinning those specific versions.

The use of version 17.1 should be prevented. Octez v17.2 is a security fix. 

The packages for Otcerz v15.0 was marked as unavailable when Octez v15.1 security upgrade was released.

**Comment by avsm** [comment]
The opam repository is not intended to be a dumping ground for thousands of unavailable packages, which is what all these Octez packages are turning into.  @raphael-proust @killian-delarue might we have a discussion about merging the Octez packages into <10 for future releases?  As far as I can tell, there is no real interdependency from other packages on the Octez ones, so they might as well be submitted as a single package

**Comment by killian-delarue** [comment]
> The opam repository is not intended to be a dumping ground for thousands of unavailable packages, which is what all these Octez packages are turning into. @raphael-proust @killian-delarue might we have a discussion about merging the Octez packages into <10 for future releases? As far as I can tell, there is no real interdependency from other packages on the Octez ones, so they might as well be submitted as a single package

In this PR we are only marking a version that we want to prevent being used.

Yes, the next versions will contain less opam packages.

**Comment by killian-delarue** [comment]
> If this is a security fix, then this is presumably quite urgent. What's happening with the Mac build failure reported above? And @raphael-proust, don't we need to constrain this release to OCaml <5 while your upstream fix is applied?

The fix will be applied for the next release, I have added a constraint here for this version

**Comment by raphael-proust** [comment]
@avsm 

> Yes, the next versions will contain less opam packages.

Specifically, we have https://gitlab.com/tezos/tezos/-/merge_requests/8637 upstream which should land soon and reduce the number of packages in further releases. It should reduce the number of package by 38 if I counted correctly. Further reductions are planned afterwards too.

See also https://github.com/ocaml/opam-repository/pull/23649 https://github.com/ocaml/opam-repository/issues/23697

**Comment by kit-ty-kate** [comment]
There are quite a lot of failures due to the number of packages being tested and the size taken by the builds filling out the available disk space of the machines, but it looks good overall and does not affect any non-tezos packages so let's merge this and fix things later if there are actual issues.

Thanks.

**Pull request merged**
