### PR TITLE
Package mccs.1.1+2

### PR DESCRIPTION
**Pull request by AltGr**
### `mccs.1.1+2`

Multi Criteria CUDF Solver with OCaml bindings

This is a stripped-down version of the mccs solver (written in C++), including
OCaml bindings based on the cudf library. Note that it includes some correctness
fixes, and a few changes not present in the upstream yet.

---
* Homepage: http://www.i3s.unice.fr/~cpjm/misc/
* Source repo: https://github.com/AltGr/ocaml-mccs.git
* Bug tracker: https://github.com/AltGr/ocaml-mccs/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by AltGr** [comment]
Ah, thanks for looking that up. Actually the link flag isn't needed, we just need glpk, ltdl somehow got picked up automatically on my system but we don't need to specify it anyway. Fixed.

**Comment by AltGr** [comment]
Failures on Alpine and CentOS 7: it appears they don't have `glpk` packaged. CentOS has `lpsolve`, that we could use instead as backend for mccs (it's slower, on my limited experiments, though). Alpine doesn't appear to have anything we can use.
What is the policy in this case ? We don't have a `depext` flag to explicitely mark the dependency as missing. Making the package unavailable altogether would be also wrong, because the user could get the dependencies by hand.

**Comment by AltGr** [comment]
(anyway, the issues above concern the `conf-glpk` package, not this one: I think this is good for merge)
The failure on Alpine is very suspicious, though, since `conf-glpk` apparently installed successfully (and then mccs failed to link). Is `conf-glpk` broken ? Here is the conf line:
```
cc "-c" "-l:libglpk.a" (CWD=/home/opam/.opam/4.04.2/build/conf-glpk.1)
```

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
