### PR TITLE
5 packages from zoggy.frama.io/activitypub/releases/ocaml-activitypub-0.1.0.tar.bz2

### PR DESCRIPTION
**Pull request by zoggy**
This pull-request concerns:
- `activitypub.0.1.0`: ActivityPub in OCaml
- `activitypub_client.0.1.0`: ActivityPub client in OCaml
- `activitypub_gui.0.1.0`: Simple ActivityPub client gui in OCaml
- `activitypub_server.0.1.0`: ActivityPub server in OCaml
- `activitypub_server_gui.0.1.0`: ActivityPub server in OCaml, admin GUI

---
* Homepage: https://zoggy.frama.io/activitypub/
* Source repo: git+https://framagit.org/zoggy/activitypub.git
* Bug tracker: https://framagit.org/zoggy/activitypub/issues

---
:camel: Pull-request generated by opam-publish v2.4.0

### CODE REVIEW

**Comment by zoggy** [comment]
Please wait, i'm investigating on conditionnaly use the syscall causing the problems.

**Comment by mseri** [comment]
It seems to be the foreign_stubs that fails
```
#=== ERROR while compiling activitypub_server.0.1.0 ===========================#
# context              2.4.0~alpha1~dev | linux/x86_64 | ocaml-base-compiler.5.2.0 | pinned(https://zoggy.frama.io/activitypub/releases/ocaml-activitypub-0.1.0.tar.bz2)
# path                 ~/.opam/5.2/.opam-switch/build/activitypub_server.0.1.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p activitypub_server -j 255 @install
# exit-code            1
# env-file             ~/.opam/log/activitypub_server-7-c0dea2.env
# output-file          ~/.opam/log/activitypub_server-7-c0dea2.out
### output ###
# File "server/dune", lines 1-10, characters 0-442:
#  1 | (library
#  2 |  (name activitypub_server)
#  3 |  (public_name activitypub_server)
#  4 |  (wrapped true)
#  5 |  (flags -g :standard -bin-annot -w -6-7-9-27-32-33-34-35-36-50-52 -no-strict-sequence -linkall)
#  6 |  (libraries activitypub fmt.tty lru_cache webmachine xtmpl)
#  7 |  (preprocess (pps ppx_blob lwt_ppx ocf_ppx rdf_ppx xtmpl_ppx))
#  8 |  (foreign_stubs (language c) (names unix_getdents) (flags -D __USE_LARGEFILE64))
#  9 |  (preprocessor_deps (file page.tmpl) (file style.css))
# 10 | )
# (cd _build/default && /home/opam/.opam/5.2/bin/ocamlmklib -g -o server/activitypub_server_stubs server/unix_getdents.o)
# /usr/bin/ld: server/unix_getdents.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: failed to set dynamic section sizes: bad value
# collect2: error: ld returned 1 exit status
```
and on recent systems like fedora 40. I think this should deserve a better check. Do you know where this fPIC issue comes from? What if you add the flag to line 8?

Also, it should probably be marked as unavailable on macos:
```
#=== ERROR while compiling activitypub_server.0.1.0 ===========================#
# context              2.3.0~alpha1 | macos/x86_64 | ocaml-base-compiler.5.2.0 | pinned(https://zoggy.frama.io/activitypub/releases/ocaml-activitypub-0.1.0.tar.bz2)
# path                 ~/.opam/5.2.0/.opam-switch/build/activitypub_server.0.1.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p activitypub_server -j 11 @install
# exit-code            1
# env-file             ~/.opam/log/activitypub_server-26683-3b77d8.env
# output-file          ~/.opam/log/activitypub_server-26683-3b77d8.out
### output ###
# File "server/dune", line 8, characters 36-49:
# 8 |  (foreign_stubs (language c) (names unix_getdents) (flags -D __USE_LARGEFILE64))
#                                         ^^^^^^^^^^^^^
# (cd _build/default/server && /usr/bin/cc -D __USE_LARGEFILE64 -g -I /Users/mac1000/.opam/5.2.0/lib/ocaml -I /Users/mac1000/.opam/5.2.0/lib/activitypub -I /Users/mac1000/.opam/5.2.0/lib/angstrom -I /Users/mac1000/.opam/5.2.0/lib/asn1-combinators -I /Users/mac1000/.opam/5.2.0/lib/astring -I /Users/mac1000/.opam/5.2.0/lib/base64 -I /Users/mac1000/.opam/5.2.0/lib/bigstringaf -I /Users/mac1000/.opam/5.2.0/lib/bos -I /Users/mac1000/.opam/5.2.0/lib/bytes -I /Users/mac1000/.opam/5.2.0/lib/ca-certs -I /Users/mac1000/.opam/5.2.0/lib/cohttp -I /Users/mac1000/.opam/5.2.0/lib/cohttp-lwt -I /Users/mac1000/.opam/5.2.0/lib/cohttp-lwt-unix -I /Users/mac1000/.opam/5.2.0/lib/conduit -I /Users/mac1000/.opam/5.2.0/lib/conduit-lwt -I /Users/mac1000/.opam/5.2.0/lib/conduit-lwt-unix -I /Users/mac1000/.opam/5.2.0/lib/cryptokit -I /Users/mac1000/.opam/5.2.0/lib/digestif -I /Users/mac1000/.opam/5.2.0/lib/dispatch -I /Users/mac1000/.opam/5.2.0/lib/domain-name -I /Users/mac1000/.opam/5.2.0/lib/dune-build-info -I /Users/mac1000/.opam/5.2.0/lib/duration -I /Users/mac1000/.opam/5.2.0/lib/eqaf -I /Users/mac1000/.opam/5.2.0/lib/fmt -I /Users/mac1000/.opam/5.2.0/lib/fpath -I /Users/mac1000/.opam/5.2.0/lib/gen -I /Users/mac1000/.opam/5.2.0/lib/gmap -I /Users/mac1000/.opam/5.2.0/lib/ipaddr -I /Users/mac1000/.opam/5.2.0/lib/ipaddr-sexp -I /Users/mac1000/.opam/5.2.0/lib/ipaddr/unix -I /Users/mac1000/.opam/5.2.0/lib/iri -I /Users/mac1000/.opam/5.2.0/lib/jsonm -I /Users/mac1000/.opam/5.2.0/lib/kdf/hkdf -I /Users/mac1000/.opam/5.2.0/lib/kdf/pbkdf -I /Users/mac1000/.opam/5.2.0/lib/ldp -I /Users/mac1000/.opam/5.2.0/lib/ldp_tls -I /Users/mac1000/.opam/5.2.0/lib/logs -I /Users/mac1000/.opam/5.2.0/lib/lru_cache -I /Users/mac1000/.opam/5.2.0/lib/lwt -I /Users/mac1000/.opam/5.2.0/lib/lwt/unix -I /Users/mac1000/.opam/5.2.0/lib/macaddr -I /Users/mac1000/.opam/5.2.0/lib/magic-mime -I /Users/mac1000/.opam/5.2.0/lib/menhirLib -I /Users/mac1000/.opam/5.2.0/lib/mirage-crypto -I /Users/mac1000/.opam/5.2.0/lib/mirage-crypto-ec -I /Users/mac1000/.opam/5.2.0/lib/mirage-crypto-pk -I /Users/mac1000/.opam/5.2.0/lib/mirage-crypto-rng -I /Users/mac1000/.opam/5.2.0/lib/mirage-crypto-rng-lwt -I /Users/mac1000/.opam/5.2.0/lib/mirage-crypto-rng/unix -I /Users/mac1000/.opam/5.2.0/lib/mtime -I /Users/mac1000/.opam/5.2.0/lib/mtime/clock -I /Users/mac1000/.opam/5.2.0/lib/ocaml/threads -I /Users/mac1000/.opam/5.2.0/lib/ocaml/unix -I /Users/mac1000/.opam/5.2.0/lib/ocf -I /Users/mac1000/.opam/5.2.0/lib/ocplib-endian -I /Users/mac1000/.opam/5.2.0/lib/ocplib-endian/bigstring -I /Users/mac1000/.opam/5.2.0/lib/ohex -I /Users/mac1000/.opam/5.2.0/lib/pcre -I /Users/mac1000/.opam/5.2.0/lib/ppx_sexp_conv/runtime-lib -I /Users/mac1000/.opam/5.2.0/lib/ptime -I /Users/mac1000/.opam/5.2.0/lib/ptime/clock -I /Users/mac1000/.opam/5.2.0/lib/rdf -I /Users/mac1000/.opam/5.2.0/lib/rdf_json_ld -I /Users/mac1000/.opam/5.2.0/lib/re -I /Users/mac1000/.opam/5.2.0/lib/re/str -I /Users/mac1000/.opam/5.2.0/lib/result -I /Users/mac1000/.opam/5.2.0/lib/rresult -I /Users/mac1000/.opam/5.2.0/lib/sedlex -I /Users/mac1000/.opam/5.2.0/lib/seq -I /Users/mac1000/.opam/5.2.0/lib/sexplib0 -I /Users/mac1000/.opam/5.2.0/lib/stringext -I /Users/mac1000/.opam/5.2.0/lib/tls -I /Users/mac1000/.opam/5.2.0/lib/tls-lwt -I /Users/mac1000/.opam/5.2.0/lib/uri -I /Users/mac1000/.opam/5.2.0/lib/uri-sexp -I /Users/mac1000/.opam/5.2.0/lib/uri/services -I /Users/mac1000/.opam/5.2.0/lib/uucp -I /Users/mac1000/.opam/5.2.0/lib/uuidm -I /Users/mac1000/.opam/5.2.0/lib/uunf -I /Users/mac1000/.opam/5.2.0/lib/uutf -I /Users/mac1000/.opam/5.2.0/lib/webmachine -I /Users/mac1000/.opam/5.2.0/lib/x509 -I /Users/mac1000/.opam/5.2.0/lib/xmlm -I /Users/mac1000/.opam/5.2.0/lib/xtmpl -I /Users/mac1000/.opam/5.2.0/lib/yojson -I /Users/mac1000/.opam/5.2.0/lib/zarith -o unix_getdents.o -c unix_getdents.c)
# unix_getdents.c:130:3: error: call to undeclared function 'caml_failwith'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
#   caml_failwith("get_dents64 not available");
#   ^
# 1 error generated.
```

**Comment by zoggy** [comment]
I have no idea about -fPIC, I thought the compilation tools were aware of required flags. I added it to see if it changes something.
I added an `availability` filter for macos.

**Comment by zoggy** [comment]
It seems better, now.

**Comment by mseri** [comment]
Looks good now, thanks

**Pull request merged**
