### PR TITLE
[new release] mimic (2 packages) (0.0.9)

### PR DESCRIPTION
**Pull request by dinosaure**
A simple protocol dispatcher

- Project page: <a href="https://github.com/dinosaure/mimic">https://github.com/dinosaure/mimic</a>
- Documentation: <a href="https://dinosaure.github.io/mimic/">https://dinosaure.github.io/mimic/</a>

##### CHANGES:

* Re-introduce the DNS stack into mimic to be able to resolve domain-names
  (@dinosaure, @hannesm, dinosaure/mimic#24, dinosaure/mimic#26)

### CODE REVIEW

**Comment by hannesm** [comment]
it looks like the release is not published on github... :/

**Comment by dinosaure** [comment]
I just fixed the release. Let's see the CI.

**Comment by hannesm** [comment]
while this is nice, unfortunately we'll need another patch for mimic -- https://github.com/dinosaure/mimic/pull/28 -- otherwise it won't work.. so please do not merge this, but instead wait for @dinosaure re-cutting the release. sorry for all the trouble.

**Comment by dinosaure** [comment]
The package is re-released, good to review :+1:.

**Comment by hannesm** [comment]
This looks fine. There are CI failures I haven't seen earlier (unrelated to this PR, maybe to dune 3.16?):

```
#=== ERROR while compiling alcotest.1.7.0 =====================================#
# context              2.0.10 | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/alcotest.1.7.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p alcotest -j 39 @install
# exit-code            1
# env-file             ~/.opam/log/alcotest-44-548b09.env
# output-file          ~/.opam/log/alcotest-44-548b09.out
### output ###
# File "src/alcotest-engine/dune", line 26, characters 2-9:
# 26 |   fmt.cli
#        ^^^^^^^
# Error: Library "fmt.cli" in /home/opam/.opam/4.14/lib/fmt is hidden
# (unsatisfied 'exists_if').
# -> required by library "alcotest.engine" in
#    _build/default/src/alcotest-engine
# -> required by _build/default/META.alcotest
# -> required by _build/install/default/lib/alcotest/META
# -> required by _build/default/alcotest.install
# -> required by alias install
```

This is with opam 2.0 (and OCaml 4.14/5.2). Not sure in which lifecycle opam 2.0 is?


To me, this looks unrelated to this PR, and this is good to merge (and would unlock some other releases).

**Comment by hannesm** [comment]
@samoht this is needed for the next mirage release (to unblock example unikernels like git, http)

**Comment by avsm** [comment]
An odd opam 2.0 failure, but it works on newer opams so I think we can fix this async.

```
#=== ERROR while compiling conf-pkg-config.3 ==================================#
# context              2.0.10 | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/conf-pkg-config.3
# command              ~/.opam/opam-init/hooks/sandbox.sh build pkg-config --help
# exit-code            1
# env-file             ~/.opam/log/conf-pkg-config-44-8b8a2d.env
# output-file          ~/.opam/log/conf-pkg-config-44-8b8a2d.out
### output ###
# bwrap: execvp pkg-config: No such file or directory


#=== ERROR while compiling alcotest.1.7.0 =====================================#
# context              2.0.10 | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/alcotest.1.7.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p alcotest -j 39 @install
# exit-code            1
# env-file             ~/.opam/log/alcotest-44-548b09.env
# output-file          ~/.opam/log/alcotest-44-548b09.out
### output ###
# File "src/alcotest-engine/dune", line 26, characters 2-9:
# 26 |   fmt.cli
#        ^^^^^^^
# Error: Library "fmt.cli" in /home/opam/.opam/4.14/lib/fmt is hidden
# (unsatisfied 'exists_if').
# -> required by library "alcotest.engine" in
#    _build/default/src/alcotest-engine
# -> required by _build/default/META.alcotest
# -> required by _build/install/default/lib/alcotest/META
# -> required by _build/default/alcotest.install
# -> required by alias install

```

**Pull request merged**
