### PR TITLE
Dose for ocamlgraph >= 1.8.6.

### PR DESCRIPTION
**Pull request by Drup**
This fix compat between dose and ocamlgraph >= 1.8.6 for dose 3.2* and 3.3. Afaics, 3.1 is not concerned, since it contains its own implementation of dominators.

Instalation for dose 3.2-rc2 and 3.2.2 is broken. They build if I get the sources and compile manually, but not with the build instruction in the opam file. I would appreciate instructions from someone with some ocp-build knownledge on that.

@rdicosmo @abate : I didn't find a way to send a patch to [dose's bug tracker](https://gforge.inria.fr/tracker/?atid=13810&group_id=4395&func=browse), I think it's only for people registered in the project.

### CODE REVIEW

**Comment by dsheets** [comment]
There are some issues with module capitalization in the install file and the dose build system. Last I ran into this problem, I believe I had concluded it was an issue with backward incompatible behavior between ocp-build minor revisions. Could you look into this?

**Comment by Drup** [comment]
I replaced the build instructions from 3.2.2 and 3.2-rc2 by the one in 3.3 and it seems to work. I don't really understand why it was done that way to begin with ...

**Comment by samoht** [comment]
because of bootstrap: these are amongst the first packages which have been added to opam-repository and they were needed to compile opam itself. Time have changed and we know how to package (and bootstrap) now. Thanks for fixing this!

**Comment by Drup** [comment]
@samoht hum, Ok. Note that I didn't touched the oldest one (but the newest should work fine now).

**Comment by samoht** [comment]
Thanks! /cc @AltGr

**Comment by abate** [comment]
The dose bugtracker is now open for everybody . You just need to create a guest account on the inria site. For what is concern the patch, I'll apply upstream once the new version of ocamlgraph lands in debian unstable. It should not be long now that jessie is out of the way.

**Comment by abate** [comment]
This problem is now fixed in the dose master branch.

**Pull request merged**
