### PR TITLE
pilat.1 - via opam-publish

### PR DESCRIPTION
**Pull request by Stevendeo**
A Frama-C polynomial invariant generator 

This tool generates invariants of linear and polynomial loops, with 
deterministic and non deterministic assignments, as annotations in the initial 
source code.

---
* Homepage: https://github.com/Stevendeo/Pilat/
* Source repo: https://github.com/Stevendeo/Pilat.git
* Bug tracker: 

---
### opam-lint failures
- **WARNING** 36 Missing field 'bug-reports'

---

Pull-request generated by opam-publish v0.3.4

### CODE REVIEW

**Comment by samoht** [comment]
Infrastructure issue reported on https://github.com/avsm/mirage-ci/issues/6 not sure what is happening.

TravisCI is complaining on older version of OCaml:

```
#=== ERROR while installing pilat.1 ===========================================#
# opam-version 1.2.2
# os           linux
# command      sh make.sh
# path         /home/travis/.opam/system/build/pilat.1
# compiler     system (4.02.3)
# exit-code    2
# env-file     /home/travis/.opam/system/build/pilat.1/pilat-10279-6ef1df.env
# stdout-file  /home/travis/.opam/system/build/pilat.1/pilat-10279-6ef1df.out
# stderr-file  /home/travis/.opam/system/build/pilat.1/pilat-10279-6ef1df.err
### stdout ###
# [...]
# Ocamlc       float.cmo
# Ocamlc       qring.cmo
# Ocamlc       pilat_math.cmi
# Ocamlc       poly.cmi
# Ocamlc       poly.cmo
# Ocamlc       poly_utils.cmi
# Ocamlc       poly_utils.cmo
# Ocamlc       pilat_visitors.cmi
# Ocamlc       pilat_visitors.cmo
# Ocamlc       lacaml_matrix.cmi
### stderr ###
# configure.in:20: warning: prefer named diversions
# configure.in:26: warning: prefer named diversions
# configure.in:32: warning: prefer named diversions
# configure.in:38: warning: prefer named diversions
# configure.in:50: warning: prefer named diversions
# File "lacaml_matrix.mli", line 27, characters 16-29:
# Error: Unbound module Lacaml__D
# make: *** [lacaml_matrix.cmi] Error 2
```

**Comment by samoht** [comment]
And a different error on 4.01:
```
#=== ERROR while installing pilat.1 ===========================================#
# opam-version 1.2.2
# os           linux
# command      sh make.sh
# path         /home/travis/.opam/4.01.0/build/pilat.1
# compiler     4.01.0
# exit-code    2
# env-file     /home/travis/.opam/4.01.0/build/pilat.1/pilat-20207-3d0870.env
# stdout-file  /home/travis/.opam/4.01.0/build/pilat.1/pilat-20207-3d0870.out
# stderr-file  /home/travis/.opam/4.01.0/build/pilat.1/pilat-20207-3d0870.err
### stdout ###
# [...]
# checking for Makefile.in... yes
# pilat... yes
# checking for /home/travis/.opam/4.01.0/lib/frama-c/share/frama-c/Makefile.dynamic... yes
# checking for /home/travis/.opam/4.01.0/lib/lacaml/lacaml.cmxa... yes
# checking for /home/travis/.opam/4.01.0/lib/lacaml/lacaml_top.cmxa... yes
# checking for /home/travis/.opam/4.01.0/lib/zarith/zarith.cmxa... yes
# configure: pilat: yes
# configure: creating ./config.status
# config.status: creating ./Makefile
# Ocamldep     ./.depend
### stderr ###
# [...]
# Error: Syntax error: 'end' expected
# File "poly_assign.ml", line 35, characters 16-19:
# Error: This 'sig' might be unmatched
# File "poly.mli", line 27, characters 33-34:
# Error: Syntax error
# File "poly_assign.mli", line 43, characters 13-14:
# Error: Syntax error: 'end' expected
# File "poly_assign.mli", line 29, characters 16-19:
# Error: This 'sig' might be unmatched
# make: *** [Pilat_DEP] Error 2
```

Would be probably be enough to just add:
```
available: [ocaml-version > "4.02.3"]
```
to your opam file.

**Comment by Stevendeo** [comment]
I'm not so sure what the remaining fails means. Do you have any idea ?

**Comment by samoht** [comment]
Merging as TravisCI is green. I have no idea at all why our CI infra is so broken on your pacakge :-)

**Comment by Stevendeo** [comment]
Okay thanks !

**Pull request merged**
