### PR TITLE
Patch ocamlmod.0.0.8 to support safe-string

### PR DESCRIPTION
**Pull request by jpdeplaix**
cc @gildor478 
patch from @yallop (#10364)

### CODE REVIEW

**Comment by jpdeplaix** [comment]
I don't see any other solutions except making a new release but @gildor478 seems a bit busy.
Original issue: https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1759&group_id=244&atid=1098

**Comment by gasche** [comment]
When you say "a new release", do you mean a new Oasis release? Does the latest release of Oasis not generate -safe-string-compatible code? In that case, yes indeed we should do a new release -- we may be able to prepare it so that @gildor478 does not have to omuch work with it. We would still have to either patch or new-release all user packages to update the generated code, of course.

**Comment by jpdeplaix** [comment]
No, I meant a new ocamlmod release with safe-string-compatible code generated by OASIS. The latest OASIS release indeed generates safe-string-compatible code.

**Comment by gildor478** [comment]
New release #10376

**Pull request merged**
