### PR TITLE
Constrain some package in anticipation of dune 2.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**
I went through a custom run of opam-health-check (before and after https://github.com/ocaml/opam-repository/pull/15158) and added a few easy constraints where needed.

cc @rgrinberg (I also added a constraint in `jbuilder.transition` to be more complete even though the conflicts is already in `dune.2.0.0`)

* cc @raphael-proust for `blake2`, `hacl` and `uecc`
* cc @yomimono for `bun`
* cc @UnixJunkie for `bytearray`, `get_line`, `orsvm_e1071` and `setcore`
* cc @zshipko for `ezsqlite`
* cc @struktured for `gemini`
* cc @gildor478 for `gettext-stub`
* cc @mseri for `md2mld`
* cc @hannesm for `mirage-clock-unix`
* cc @smolkaj for `open`
* cc @smondet for `ppx_deriving_cmdliner`
* cc @charlesetc for `relit-reason`
* cc @dinosaure for `rosetta`
* cc @LaurentMazare for `tensorflow`
* cc @Leonidas-from-XIV for `zmq` 

The reason for each breakage is stated in each individual commit messages.

### CODE REVIEW

**Comment by mseri** [comment]
Thanks @kit-ty-kate that's an error only on the opam file for `md2mld`, they both use dune. Apologies for not noticing before. I'll send a PR to fix it

**Comment by Leonidas-from-XIV** [comment]
Thanks for the PR. As a co-maintainer of zmq, what `configurator` now? I haven't seen any note on the `draft1` changelog of dune about the change.

**Comment by gildor478** [comment]
LGTM for gettext-stub, I am adding it to ocaml-gettext as well.

**Comment by kit-ty-kate** [comment]
> Thanks for the PR. As a co-maintainer of zmq, what `configurator` now? I haven't seen any note on the `draft1` changelog of dune about the change.

Mmh, that's true, there is no mention of dune-configurator in the changelog. Here is a related PR for a little bit of context: https://github.com/ocaml/opam-repository/pull/14851

**Pull request merged**
