### PR TITLE
Added cloudi.2.0.2

### PR DESCRIPTION
**Pull request by okeuday**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This package fails on OCaml 4.13:
```

#=== ERROR while compiling cloudi.2.0.2 =======================================#
# context              2.1.0~beta4 | linux/x86_64 | ocaml-variants.4.13.0+trunk | pinned(https://github.com/CloudI/cloudi_api_ocaml/archive/v2.0.2.tar.gz)
# path                 ~/.opam/4.13/.opam-switch/build/cloudi.2.0.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code            2
# env-file             ~/.opam/log/cloudi-19-b3b423.env
# output-file          ~/.opam/log/cloudi-19-b3b423.out
### output ###
# test -f /home/opam/.opam/4.13/lib/ocaml/nums.cmxa || \
#     (cd external/num-1.1/src && \
#      make OCAMLC="ocamlc" \
#              OCAMLOPT="ocamlopt" \
#              OCAMLDEP="ocamldep" \
#              OCAMLMKLIB="ocamlmklib" \
#              nums.cmxa nums.cma libnums.a && \
#      cp arith_flags.cmi arith_flags.cmx arith_status.cmi arith_status.cmx big_int.cmi big_int.cmx int_misc.cmi int_misc.cmx nat.cmi nat.cmx num.cmi num.cmx ratio.cmi ratio.cmx libnums.a nums.a nums.cmxa nums.cma ../../..)
# touch dependency_num
# ocamlc -safe-string -w @A -o erlang.cmi -c erlang.mli
# ocamlc -safe-string -w @A -o cloudi.cmi -c cloudi.mli
# ocamlopt -safe-string -w @A -o erlang.cmx -c erlang.ml
# ocamlopt -safe-string -w @A -o cloudi.cmx -c cloudi.ml
# File "cloudi.ml", line 62, characters 6-25:
# 62 |       mutable state : 's;
#            ^^^^^^^^^^^^^^^^^^^
# Error (warning 69 [unused-field]): mutable record field state is never mutated.
# make: *** [makefile:78: cloudi.cmx] Error 2
```
Would it be possible to avoid the use of `-warn-error` (or in this case `@A`) in your release archive? This will ease the maintenance toll on your side as well as mine.

**Comment by okeuday** [comment]
@kit-ty-kate I would prefer to keep `-warn-error` to ensure I catch any problems as quickly as possible.  I need to assume that warnings can be significant, potentially impacting the native compilation's validity.  This also helps to ensure I am following the OCaml "standard" as it evolves.

**Comment by okeuday** [comment]
@kit-ty-kate I updated the release to fix the compilation with 4.13.0-trunk.  The failed build checks appear to be due to the build system.

**Comment by kit-ty-kate** [comment]
Thanks. Could you return the constraint fix to the opam file upstream so that it can be taken into account for the next release?

**Comment by okeuday** [comment]
@kit-ty-kate I added the num version constraint to the opam file for the next release.  Thanks!

**Pull request merged**
