### PR TITLE
packages not available on windows because they embed an oasis configu…

### PR DESCRIPTION
**Pull request by hhugo**
…re script broken on windows

### CODE REVIEW

**Comment by hhugo** [comment]
This one should be easy to merge.

**Comment by mseri** [comment]
Can you paste here a protypical error message?

**Comment by mseri** [comment]
Ping @jonahbeckford, is that ok dkml-wise?

**Comment by jonahbeckford** [comment]
This doesn't seem like a Windows problem. It is just failing because the lack of shell/configure support on whichever Windows machine was tested.

So, without me having to do parallel testing on every opam package, the exclude from all Windows  is too broad.

**Comment by hhugo** [comment]
This is definitely a windows issue, these packages have their setup file generated from an old oasis version. The issue come from the following code that give the wrong location to ocamlbuild library
```
let fix_args args extra_argv =
    List.flatten
      [
        if (os_type ()) = "Win32" then
          [
            "-classic-display";
            "-no-log";
            "-no-links";
            "-install-lib-dir";
            (Filename.concat (standard_library ()) "ocamlbuild")
          ]
        else
```

Ocamlbuild is no longer installed as a sub directory of the stdlib.

**Comment by jonahbeckford** [comment]
Ah, thanks for correcting me. Definitely applies to all Windows machines. Disable it!

**Comment by mseri** [comment]
Thanks for the clarifications and for checking

**Pull request merged**
