### PR TITLE
Upgrade to fileutils 0.5.0.

### PR DESCRIPTION
**Pull request by gildor478**

### CODE REVIEW

**Comment by yallop** [comment]
Could you please add the missing fields to the `opam` file, @gildor478?

**Comment by gildor478** [comment]
will do later today.

**Comment by gildor478** [comment]
@yallop Friendly ping

**Comment by yallop** [comment]
Thanks!

**Comment by ivg** [comment]
This version breaks BAP (#7717) (and probably any other code that relies on `FileUtil.cp` link copying).

**Comment by gildor478** [comment]
Will publish a 0.5.1 tonight (sorry for the breakage).

**Pull request merged**
