### PR TITLE
modernize extunix and mikmatch packages

### PR DESCRIPTION
**Pull request by ygrek**

### CODE REVIEW

**Comment by samoht** [comment]
Almost good:

```
Processing package mikmatch.1.0.7... [WARNING] At
          ~/build/ocaml/opam-repository/packages/mikmatch/mikmatch.1.0.7/opam:26:9:
          Version constraint ((= 7.0.4)) no longer allowed in optional
          dependency (ignored).
          Use the 'conflicts' field instead.
```

**Comment by ygrek** [comment]
It is there from the beginning,not present in the newer versions

**Comment by ygrek** [comment]
Hm, 1.0.7 is the only one with this problem. Fixed, thanks.

**Comment by ygrek** [comment]
ping?

**Comment by samoht** [comment]
You can check the result of the runs by clicking on the red cross near your last commit. Now you get:

```
===== ERROR while installing kafka.0.2 =====
# opam-version 1.1.2-rc3
# os           linux
# command      make
# path         /home/travis/.opam/system/build/kafka.0.2
# compiler     system (4.02.1)
# exit-code    2
# env-file     /home/travis/.opam/system/build/kafka.0.2/kafka-12879-a71bb4.env
# stdout-file  /home/travis/.opam/system/build/kafka.0.2/kafka-12879-a71bb4.out
# stderr-file  /home/travis/.opam/system/build/kafka.0.2/kafka-12879-a71bb4.err
### stdout ###
# ...[truncated]
# ocaml_kafka.c:874:6: warning: implicit declaration of function ‘rd_kafka_metadata_destroy’ [-Wimplicit-function-declaration]
# ocaml_kafka.c: In function ‘ocaml_kafka_get_topics_metadata’:
# ocaml_kafka.c:899:18: error: dereferencing pointer to incomplete type
# ocaml_kafka.c:899:18: error: request for member ‘topic_cnt’ in something not a structure or union
# ocaml_kafka.c:899:8: warning: assignment makes integer from pointer without a cast [enabled by default]
# ocaml_kafka.c:900:6: error: unknown type name ‘rd_kafka_metadata_topic_t’
# ocaml_kafka.c:900:49: error: dereferencing pointer to incomplete type
# ocaml_kafka.c:900:49: error: request for member ‘topics’ in something not a structure or union
# ocaml_kafka.c:900:41: warning: initialization discards ‘const’ qualifier from pointer target type [enabled by default]
# Command exited with code 2.
### stderr ###
# make: *** [all] Error 10
```

**Comment by ygrek** [comment]
librdkafka on build servers is too old,. see #4201

**Comment by ygrek** [comment]
anything I could do here?

**Comment by samoht** [comment]
Merging. It's a bit annoying to not be able to test that properly...

**Comment by ygrek** [comment]
debian has recent enough version, if travis had debian slaves that would pass I believe

**Comment by samoht** [comment]
yup...

**Pull request merged**
