### PR TITLE
Automatically add guessed 'dev-repo' field for github packages

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by samoht** [comment]
@AltGr can you update this PR to see if the new format introduces less diffs?

**Comment by samoht** [comment]
@dbuenzli Travis is now disabled!

**Comment by AltGr** [comment]
Sure; however, we'll still have the problem we had before:
- this rewriting switches the files to `opam-version: "1.2"`
- files declared this way don't allow constraints in depopts
- rewriting the depopts causes `!=` comparisons to appear, which makes opam 1.1 fail to init (it chokes on the files before the redirect is done). This is worse than the current situation where you have lots of ugly warnings on init, but everything is fixed after an `opam update`. Existing 1.1 opam-roots are unaffected.

There would be several ways to resolve this situation:

- do the depopts rewrite without using `!=` (i.e. use `a<b | b>a`). Not a good option because it's ugly, it will stick for long, and it will introduce logic combinators in conflicts which [is bound to](https://github.com/ocaml/opam/pull/2267) cause more confusion later on.

- break `1.1` init. My impression is that when seeing the long list of warnings on init, and then packages limited to the one still defined with `opam-version: "1.1"`, most will look for help or give up before fixing with `opam update`. So it wouldn't change much to ask to `opam init https://opam.ocaml.org/1.1` (as documentd in the [FAQ](http://opam.ocaml.org/doc/FAQ.html#Gaspopaminitgivesmescreensfullsoferrorsaboutupgrading), which fully solves the issues and warnings.

- move the 1.2 repo out of the way using a redirect, so that opam 1.1 doesn't choke on it (e.g. redirect to `https://opam.ocaml.org/1.2`)

**Comment by avsm** [comment]
I think we should seriously consider just deprecating 1.1 at this point.  Do we have any way of determining how many people still use that from the logs?

**Comment by samoht** [comment]
I'm in favour of deprecating 1.1

**Comment by samoht** [comment]
@AltGr I guess this is the next PR to rewrite :-)

**Comment by samoht** [comment]
Closing this one as we already have #4692 and #5190

**Pull request closed without merging**
