### PR TITLE
Add google-drive-ocamlfuse 0.7.25

### PR DESCRIPTION
**Pull request by astrada**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The tests fail on 4.12 with:
```
#=== ERROR while compiling google-drive-ocamlfuse.0.7.25 ======================#
# context              2.0.7 | linux/x86_64 | ocaml-variants.4.12.0+trunk | pinned(https://github.com/astrada/google-drive-ocamlfuse/archive/v0.7.25.tar.gz)
# path                 ~/.opam/4.12/.opam-switch/build/google-drive-ocamlfuse.0.7.25
# command              ~/.opam/4.12/bin/dune runtest -p google-drive-ocamlfuse -j 47
# exit-code            1
# env-file             ~/.opam/log/google-drive-ocamlfuse-20-b7bf70.env
# output-file          ~/.opam/log/google-drive-ocamlfuse-20-b7bf70.out
### output ###
#    testSuite alias test/runtest (exit 1)
# (cd _build/default/test && ./testSuite.exe)
# .......Thread 14 killed on uncaught exception Sys_error("Condition.wait: Operation not permitted")
# Raised by primitive operation at BufferPool.acquire_buffer in file "src/bufferPool.ml", line 57, characters 8-38
# Called from TestBufferPool.test_pending_requests.(fun) in file "test/testBufferPool.ml", line 35, characters 16-69
# Called from Thread.create.(fun) in file "thread.ml", line 41, characters 8-14
# F
# ==============================================================================
# Failure: google-drive-ocamlfuse test suite:2:Buffer pool test:3:test_pending_requests
# 
# expected: 0 but got: 1
# ------------------------------------------------------------------------------
# Ran: 8 tests in: 0.18 seconds.
# FAILED: Cases: 8 Tried: 8 Errors: 0 Failures: 1 Skip:  0 Todo: 0 Timeouts: 0.
```
Could you have a look at it?

**Comment by kit-ty-kate** [comment]
If you can't find anything wrong it might be a bug in the compiler, I'll report that if so.

**Comment by astrada** [comment]
I think it's because in 4.12.0, the Thread module was rewritten for multicore. I will try to reproduce the error on my machine.

**Comment by astrada** [comment]
Actually, it was a bug in the test itself. I think I fixed it now.

**Comment by kit-ty-kate** [comment]
I'm happy to hear that. Thanks a lot!!

**Pull request merged**
