### PR TITLE
3 packages from gitlab.inria.fr/fpottier/menhir/repository/20200525/archive.tar.gz

### PR DESCRIPTION
**Pull request by fpottier**
This pull-request concerns:
-`menhir.20200525`: An LR(1) parser generator
-`menhirLib.20200525`: Runtime support library for parsers generated by Menhir
-`menhirSdk.20200525`: Compile-time library for auxiliary tools related to
 Menhir

---
* Homepage: http://gitlab.inria.fr/fpottier/menhir
* Source repo: git+https://gitlab.inria.fr/fpottier/menhir.git
* Bug tracker: menhir@inria.fr

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This release seems to trigger several build failures in packages using menhir that I've never seen before. Could you check if these are intended?
* https://ci.ocaml.org/log/saved/docker-run-eb368f3be02ae331e5a1129522970c88/d3f0c0215136037dd1f436620eea1ebbda61ff5f
* https://ci.ocaml.org/log/saved/docker-run-dc118f71cae205e1763bff2fe01b6bdc/a68742d6478a394503151705727e234acf99723a
* https://ci.ocaml.org/log/saved/docker-run-5dcbc660464520a5f19c89a83e607272/f9cf62a03c5d826bf7503182e517c0b1e97c18bd
* https://ci.ocaml.org/log/saved/docker-run-ed1aae185a137375c0380773fc7ba158/de39fa1bbf6d4cc3c82542bb45e5b3d1935adcd5
* https://ci.ocaml.org/log/saved/docker-run-21ac013656ea70fc410f48739e9e4711/0fc9607f64f5ac51fd47b222efa8b97896cd96c2
* https://ci.ocaml.org/log/saved/docker-run-85cbef767be7a54ab27286c8e1a2d8b7/8fd4d35834d7ebac76c9a69c5af08d9a344f48d7
* https://ci.ocaml.org/log/saved/docker-run-e2f3d29cf1a4b5cd3d5dcd88688bb97b/4bc4635078d0d35f45d11b3423927555bebb8033
* https://ci.ocaml.org/log/saved/docker-run-d58e6f1a6bd2126ba9aed8ffbbd1c48b/35ca95b42996335f77711b8bce73a03f0772adcd

**Comment by fpottier** [comment]
Hi Kate, thanks for pointing out these problems. It's quite possible that this release broke some uses of Menhir; I will look into it.

**Comment by fpottier** [comment]
Hi @kit-ty-kate, I have had a look at the failures (with Joe's help) and have sent patches to the authors of electrod, coccinelle, and systemverilog. tip-parser and nice_parser seem to work with the new Menhir.

I think you can release Menhir 20200525.

**Comment by kit-ty-kate** [comment]
Ok, I'll constrain those packages and merge this PR asap. Sorry for the wait

**Comment by kit-ty-kate** [comment]
Thanks a lot for looking into it!

**Pull request merged**
