### PR TITLE
Add mkaudio.1.0.0

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by yallop** [comment]
This is failing on 4.04.0+flambda due to [PR7426](https://caml.inria.fr/mantis/view.php?id=7426):

```
# >> Fatal error: Assignment of a float to a specialised non-float array: (array.unsafe_set[addr]<{audio.ml:668,1-10}>
#                                                           self-4/3888
#                                                           vol/3886
#                                                           Parraysetu_arg/3892)
# Fatal error: exception Misc.Fatal_error
```

There's a fix in #8834.

**Comment by johnelse** [comment]
Nice, thanks for the quick fix.

**Comment by yallop** [comment]
@johnelse, could you please rebase on `master` now that #8834 is merged?

**Comment by yallop** [comment]
Thanks!

**Comment by johnelse** [comment]
Thanks @yallop !

**Pull request merged**
