### PR TITLE
[new release] ppx_deriving_jsonschema (0.0.1)

### PR DESCRIPTION
**Pull request by Khady**
Jsonschema generator for ppx_deriving

- Project page: <a href="https://github.com/ahrefs/ppx_deriving_jsonschema">https://github.com/ahrefs/ppx_deriving_jsonschema</a>
- Documentation: <a href="https://ahrefs.github.io/ppx_deriving_jsonschema/">https://ahrefs.github.io/ppx_deriving_jsonschema/</a>

##### CHANGES:

- Initial alpha with basic features + @name @key @ref

### CODE REVIEW

**Comment by m-laniakea** [comment]
dune-release's check of the maintainer field is incomplete. 
Something like `khady@ahrefs.com` would do.

Then the packages likely need more detailed constraints.

**Comment by Khady** [comment]
I've changed the constraint on ppxlib to `"ppxlib" {>= "0.30.0"}`. I think that I could put a limit lower than that, but I don't know of an easy way to check except by actually installing all the older versions one by one.

**Comment by Khady** [comment]
I got it back all the way down to 0.24.0. I think that's enough.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
