### PR TITLE
Jane Street release v0.9.0 part2

### PR DESCRIPTION
**Pull request by diml**
Core and its dependencies

### CODE REVIEW

**Comment by avsm** [comment]
biocaml revdep fixed in https://github.com/ocaml/opam-repository/pull/8934

**Comment by avsm** [comment]
some of the bap failures will be fixed by https://github.com/ocaml/opam-repository/pull/8935

**Comment by avsm** [comment]
https://github.com/ocaml/opam-repository/pull/8938

**Comment by avsm** [comment]
@diml : could you push a merge against current master, so that the revdeps can run with the latest fixes?

**Comment by diml** [comment]
done

**Comment by avsm** [comment]
looking healthier...

- fixed batsh in https://github.com/ocaml/opam-repository/pull/8955

**Comment by avsm** [comment]
fixed core-lwt in https://github.com/ocaml/opam-repository/pull/8958

**Comment by avsm** [comment]
closing this temporarily to clear a CI queue

**Pull request closed without merging**
