### PR TITLE
Split build and install steps

### PR DESCRIPTION
**Pull request by AltGr**
This is done automatically using https://github.com/ocaml/opam/blob/6244d0e8dd8901d098de5a0f20ed466ac3b64f03/admin-scripts/split_install.ml

My limited overview found no errors, but the script may not be perfect for complex cases (for one thing, it assumes installation commands come last).

NOTE: this also rewrites 'ocaml-version:' and 'os:' into 'available:' as a side effect (because that's now how opam interprets those fields and the format preserving printer isn't clever enough to restore them)

### CODE REVIEW

**Comment by lefessan** [comment]
If the goal is to have all the packages obey a strict discipline (no install during build), maybe the script should not use an heuristic, but instead, just move all `build` instructions to `install`. Then, manual PRs could be used to move back purely build instructions to `build`. 

Note that some packages, like `coq` or `omake` create a link in `bindir` during the build, that is replaced by the correct file during `install`.

**Comment by avsm** [comment]
Once again, I'd like to merge this at the same time as retiring the OPAM 1.1 repo (since that's where the likely bugs are going to come in)...

**Comment by AltGr** [comment]
This is crazy, I was _certain_ I had dropped the 1.1 rewriting script months ago; but it's actually still running. I'll be doing it now.

On this specific change, the rewriting script concats back build and install, so it should be harmless. Of course, there may be trouble with side-effects of the rewrites...

**Comment by AltGr** [comment]
@lefessan: indeed, in case we don't know, it would be as incorrect, but more convenient to use a single `install:` field rather than a single `build:` field — since our main constraint at the moment is that we want to delimit the section where the prefix may be written into, to track it and avoid concurrency issues.

So, in case this PR is deemed too dangerous and nobody wants to review all rewritten packages, we could simply rename `build:` to `install:`, as a first step, then move the proper part back by hand. The rewrite really _seems_ good though.

My plan was to constrain where the different sections can write (I have a prototype of this for Linux using namespaces through a simple script based on `unshare` and `mount`), in a Linux testing environment, by simply providing in opam a generic way to wrap the package commands¹. Then, we could run tests on all packages to validate that build doesn't write outside of the build dir, and install doesn't write outside of the prefix.

Note that, for the examples you give, [Coq](https://github.com/AltGr/opam-repository/blob/split-install/packages/coq/coq.8.5.0/opam) and [omake](https://github.com/AltGr/opam-repository/blob/split-install/packages/omake/omake.0.9.8.6-0.rc1/opam), the rewrite really seems sound, and I wouldn't have done better by hand: if it's incorrect, it means we really need the tests unless we want to check all Makefiles of all projects manually (and in these cases, it's the Makefiles which would need fixing imho).

¹ this could be useful in other contexts as well, e.g. `ocp-bin`

**Comment by avsm** [comment]
We do need to have the ability to mechanically rewrite the repository, so finding bugs at this stage is generally beneficial.  I'd go so far as to normalise new PRs during merge as well, or do so via a cron job.

**Comment by avsm** [comment]
@altgr: i'd like to push this one through: how about describing the rewrite policy in the opam-repository/CHANGES file and then pushing the big one through and then running it regularly (on cron)?

**Comment by AltGr** [comment]
Updated, as well as `CHANGES.md`; the script was also improved (testing the invariant using namespaces allowed me to find missed cases)

**Comment by AltGr** [comment]
@avsm any reason to stall this any longer ?

**Comment by AltGr** [comment]
Updated. Please merge, since without this it's impossible to test "hardened opam" without a rewritten repo. Also, I don't want to include this in the repository automatic format upgrade since it's based on a heuristic (and backwards compatible).

**Comment by avsm** [comment]
No reason to stall this, but it still has merge conflicts.

**Comment by gasche** [comment]
The script has changed the `ocamlbuild` opam files in a way that may be incorrect -- I'm posting this comment to gather more information and decide what to do.

Ocamlbuild's `opam-install` rule does not perform any installation action by itself, but it generates a `ocamlbuild.install` file. It was my understanding that, at the end of the `build` run, opam would check for such a file and if present use it for installation.

Now this `opam-install` rule is invoked as an `install:` rule, and `opam lint` complains that I also need a matching `remove` rule -- which should not be necessary when using an `ocamlbuild.install` file.

Does this change break the build of `ocamlbuild`, or will opam also look for a `.install` file after the `install` rule is fired? My testing seems to indicate that the new `opam` file still works, but it seems a bit strange to me. What is the current semantics of `.install` files, when does OPAM look for them? Does it mean that having a `install:` rule that generates a `.install` and no `remove:` rule is correct?

The [documentation of .install files](https://opam.ocaml.org/doc/Manual.html#packagenameinstall) is very un-informative and fairly unclear (it mentions `opam-installer` as if the packager should use it in their build script. Would it be possible to update/improve it? I may send a PR after this clarification is made.

I think this issue could have been avoided if it was possible for package authors to make explicit their intent to provide a `.install` file. For example I could use `install-file: "build"` to indicate that my install-file is produced by my `build` rule, or `install-file: "file"` if it's already in the package archive, or `install-file: "none"` (or no `install-file` field at all) if no install file should be used. Or a `tag`, or whatever. @AltGr, I think it would be a good idea to have such a feature available, to make future installation-related refactoring safer and more informed. It would probably make packager's and user's  life easier as well -- they would understand better what is happening when inspecting the metadata of a given package, for example if they run the build/install rules manually for debugging purposes.

**Comment by dbuenzli** [comment]
> For example I could use install-file: "build" to indicate that my install-file is produced by my build rule, or install-file: "file" if it's already in the package archive, or install-file: "none" (or no install-file field at all) if no install file should be used.

Personally I prefer the current implicit behaviour. 

* `install-file:"file"` just looks into `file/` if there's one.
* `install-file:"build"`, no  `install:` field.
* `install-file:"none"`, an `install:` field that didn't generate an `install` file. 

While this does not allow to determine things exactly statically, it avoid too much packaging bureaucracy. I note that this PR moved some of my `build:` to `install:` while they should not. I hope it doesn't break anything.

**Comment by AltGr** [comment]
Indeed, the heuristic was incorrect in your case, and generating a .install file should be part of the `build:`step -- you don't need a `install:` field at all. Basically, `build:` should only write to the build dir, and `install:` only to the prefix.

It's true that not being able to tell if a package includes a `.install` file is sometimes a problem for rewrites or some operations ; but then, the presence/absence of a `.config` file should be documented as well. I'll see if there can be a lighter-weight approach to this.

**Comment by gasche** [comment]
Thanks for the quick reaction.

> I note that this PR moved some of my build: to install: while they should not. I hope it doesn't break anything.

Indeed, but in the case of ocamlbuild at least it seems to keep working after the split, which I find (good but) surprising. @AltGr can you confirm that a `.install` file is currently sought after the `install:` file has run?

Ok, let me drop the idea of explicitly mentioning `install-file` in the metadata. Could we get a clarification of the semantics of `.install` and when it is checked, and an improvement to [the documentation](https://opam.ocaml.org/doc/Manual.html#packagenameinstall)?

**Pull request merged**
