### PR TITLE
Add patches files to opam 

### PR DESCRIPTION
**Pull request by Nyavlys**
I added patches files in files/ In order  to have acgtk.1.3.1 compile with easy-format:version >1.2.0 and yojson:version>1.3.3 as well.

### CODE REVIEW

**Comment by gasche** [comment]
Where are the patches coming from? Did you write them yourself? Have them been submitted in the package upstream? Merged? Is patching better than doing a new release?

**Comment by dbuenzli** [comment]
Also this https://github.com/ocaml/opam-repository/issues/10531 seems to be of interest in this case.

**Comment by Nyavlys** [comment]
Hi,

Yes, I wrote the patches by myself. I chose to patch rather than to make a new release because the code of the package itself is unchanged.

The patches only concern makefiles (and configuration files) to take into account the fact that some packages my package depends on have changed they way the have to be linked.

On the other hand, if it makes life easier, I can release a new version with that modifications only, I don't really care.

Regarding the check failures (in case it helps):

+ I noticed that patching fails with opam V2.0 and CentOS but succeeds with any other version/distribution combination (including 1.2/CentOS)

+ there is still the same old problem with MacOS and bolt, or more precisely some camlp4 file that is not installed in travis/MacOS checks (https://github.com/ocaml/opam-repository/issues/7436)

Let me know if you prefer a new release instead of patches.

**Comment by gasche** [comment]
This does make sense to me, thanks -- although I would recommend that you submit them upstream for inclusion, to avoid divergence of the opam-packaged and upstream codebase. @dbuenzli, what do you think?

**Comment by dbuenzli** [comment]
Yes. I think it's better not to have patches in the repo.

**Comment by Nyavlys** [comment]
Ok. I'll make a new release, then.

**Comment by dbuenzli** [comment]
Thanks @Nyavlys this is very much appreciated.

**Pull request closed without merging**
