### PR TITLE
snappy.0.1.0: fix url

### PR DESCRIPTION
**Pull request by ygrek**

### CODE REVIEW

**Comment by ygrek** [comment]
ftr build failure on OSX is some python shenanigans (wtf btw)

**Comment by ygrek** [comment]
ping?

**Comment by kit-ty-kate** [comment]
No idea about the build failure in OSX :/
Hm, there is no need to remove ```snappy.0.0.1``` as it is already marked as ```available: false``` (i.e. not installable) and I think some opam maintainers don't like to remove packages.
Could you remove this change and just leave the url update ?

**Comment by ygrek** [comment]
> I think some opam maintainers don't like to remove packages.

It is a little frustrating to discover new rules by trial and error.
Are the best practices / requirements specified anywhere?

**Comment by ygrek** [comment]
travis build failure due to apt network errors

**Comment by mseri** [comment]
Build failures are all due to infrastructure issues

**Pull request merged**
