### PR TITLE
disable tests b/c of new MDX upper-bound

### PR DESCRIPTION
**Pull request by chetmurthy**
want this to build on ocaml 5.1, and tests use mdx,  so gotta disable tests

### CODE REVIEW

**Comment by mseri** [comment]
This should install fine on ocaml 5.1, it is only the CI test build that fails (until a new mdx is released)

**Comment by chetmurthy** [comment]
Um, it didn't, and I backed-up to just installing `mdx`, which also failed (all of this on Ubuntu).  I don't think I did anything odd or special  (no pins, fresh switch, after `opam update`, `opam upgrade`):
```
$ opam switch create 5.1.0

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><><><>
Switch invariant: ["ocaml-base-compiler" {= "5.1.0"} | "ocaml-system" {= "5.1.0"}]

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed ocaml-options-vanilla.1
⬇ retrieved ocaml-base-compiler.5.1.0  (cached)
∗ installed ocaml-base-compiler.5.1.0
∗ installed ocaml-config.3
∗ installed ocaml.5.1.0
∗ installed base-domains.base
∗ installed base-nnp.base
Done.
(Python) chet@moskva:~/Hack/Camlp5/src/ALL$ opam install mdx
[ERROR] Package conflict!
  * No agreement on the version of ocaml:
    - (invariant) → ocaml-base-compiler >= 5.1.0 → ocaml = 5.1.0
    - mdx → ocaml < 4.07.0
    You can temporarily relax the switch invariant with `--update-invariant'
  * No agreement on the version of ocaml-base-compiler:
    - (invariant) → ocaml-base-compiler >= 5.1.0
    - mdx → ocaml < 4.09.0 → ocaml-base-compiler = 4.08.1
  * Missing dependency:
    - mdx → ocaml < 4.07.0 → ocaml-variants >= 3.09.2 → ocaml-beta
    unmet availability conditions: 'enable-ocaml-beta-repository'

No solution found, exiting
(Python) chet@moskva:~/Hack/Camlp5/src/ALL$ opam install mdx.2.3.0
[ERROR] Package conflict!
  * No agreement on the version of ocaml:
    - (invariant) → ocaml-base-compiler >= 5.1.0 → ocaml = 5.1.0
    - mdx >= 2.3.0 → ocaml < 5.1.0
    You can temporarily relax the switch invariant with `--update-invariant'
  * No agreement on the version of ocaml-base-compiler:
    - (invariant) → ocaml-base-compiler >= 5.1.0
    - mdx >= 2.3.0 → ocaml < 5.1.0 → ocaml-base-compiler = 4.08.1
  * Missing dependency:
    - mdx >= 2.3.0 → ocaml < 5.1.0 → ocaml-variants >= 3.09.2 → ocaml-beta
    unmet availability conditions: 'enable-ocaml-beta-repository'

No solution found, exiting
(Python) chet@moskva:~/Hack/Camlp5/src/ALL $ opam install mdx.2.2.1
[ERROR] Package conflict!
  * No agreement on the version of ocaml:
    - (invariant) → ocaml-base-compiler >= 5.1.0 → ocaml = 5.1.0
    - mdx = 2.2.1 → ocaml < 5.1.0
    You can temporarily relax the switch invariant with `--update-invariant'
  * No agreement on the version of ocaml-base-compiler:
    - (invariant) → ocaml-base-compiler >= 5.1.0
    - mdx = 2.2.1 → ocaml < 5.1.0 → ocaml-base-compiler = 4.08.1
  * Missing dependency:
    - mdx = 2.2.1 → ocaml < 5.1.0 → ocaml-variants >= 3.09.2 → ocaml-beta
    unmet availability conditions: 'enable-ocaml-beta-repository'

No solution found, exiting
(Python) chet@moskva:~/Hack/Camlp5/src/ALL$ 
```

**Comment by mseri** [comment]
Of course installing `mdx` fails, but it should not prevent your package to install: when you install a package without `--with-test` is not supposed to pick up test dependencies.

I tried it locally and it works fine:
```
❯ opam switch
#   switch   compiler                   description
->  5.1.0    ocaml-base-compiler.5.1.0  5.1.0
    default  ocaml.4.14.0               default

[WARNING] The environment is not in sync with the current switch.
          You should run: eval $(opam env)
❯ opam install camlp5-buildscripts
The following actions will be performed:
  - install dune                3.10.0 [required by re]
  - install conf-bash           1      [required by camlp5-buildscripts]
  - install conf-m4             1      [required by not-ocamlfind]
  - install ocamlfind           1.9.6  [required by bos, not-ocamlfind]
  - install seq                 base   [required by re]
  - install conf-which          1      [required by not-ocamlfind]
  - install ocamlbuild          0.14.2 [required by bos]
  - install stdlib-shims        0.3.0  [required by ocamlgraph]
  - install camlp-streams       5.0.1  [required by not-ocamlfind]
  - install re                  1.11.0 [required by camlp5-buildscripts]
  - install topkg               1.0.7  [required by bos]
  - install ocamlgraph          2.1.0  [required by not-ocamlfind]
  - install rresult             0.7.0  [required by bos, not-ocamlfind]
  - install fmt                 0.9.0  [required by camlp5-buildscripts]
  - install astring             0.8.5  [required by bos]
  - install not-ocamlfind       0.11   [required by camlp5-buildscripts]
  - install logs                0.7.0  [required by bos]
  - install fpath               0.7.3  [required by bos]
  - install bos                 0.2.1  [required by camlp5-buildscripts]
  - install camlp5-buildscripts 0.03
===== 20 to install =====
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> retrieved astring.0.8.5  (cached)
-> retrieved camlp-streams.5.0.1  (cached)
-> retrieved bos.0.2.1  (cached)
-> installed conf-which.1
-> installed conf-bash.1
-> retrieved camlp5-buildscripts.0.03  (https://github.com/camlp5/camlp5-buildscripts/archive/refs/tags/0.03.tar.gz)
-> retrieved fmt.0.9.0  (cached)
-> retrieved fpath.0.7.3  (cached)
-> retrieved logs.0.7.0  (cached)
-> retrieved ocamlbuild.0.14.2  (cached)
-> installed conf-m4.1
-> retrieved ocamlfind.1.9.6  (http://download.camlcity.org/download/findlib-1.9.6.tar.gz)
-> retrieved dune.3.10.0  (https://github.com/ocaml/dune/releases/download/3.10.0/dune-3.10.0.tbz)
-> retrieved re.1.11.0  (https://github.com/ocaml/ocaml-re/releases/download/1.11.0/re-1.11.0.tbz)
-> retrieved rresult.0.7.0  (cached)
-> installed seq.base
-> retrieved ocamlgraph.2.1.0  (https://github.com/backtracking/ocamlgraph/releases/download/2.1.0/ocamlgraph-2.1.0.tbz)
-> retrieved stdlib-shims.0.3.0  (cached)
-> retrieved not-ocamlfind.0.11  (https://github.com/chetmurthy/not-ocamlfind/archive/refs/tags/0.11.tar.gz)
-> retrieved topkg.1.0.7  (https://erratique.ch/software/topkg/releases/topkg-1.0.7.tbz)
-> installed ocamlbuild.0.14.2
-> installed ocamlfind.1.9.6
-> installed topkg.1.0.7
-> installed rresult.0.7.0
-> installed fmt.0.9.0
-> installed astring.0.8.5
-> installed logs.0.7.0
-> installed fpath.0.7.3
-> installed bos.0.2.1
-> installed dune.3.10.0
-> installed stdlib-shims.0.3.0
-> installed camlp-streams.5.0.1
-> installed re.1.11.0
-> installed ocamlgraph.2.1.0
-> installed not-ocamlfind.0.11
-> installed camlp5-buildscripts.0.03
Done.
```

**Comment by chetmurthy** [comment]
Ah, ok, fair.  You're saying the tests will all be skipped anyway.  Fair enough.  I'll close this PR.

**Pull request closed without merging**
