### PR TITLE
Refine the dependencies of mesh* packages

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
@avsm `Error: Internal Server Error`

**Comment by Chris00** [comment]
Changes prompted by https://github.com/Chris00/mesh/issues/1

**Comment by jpdeplaix** [comment]
There seems to be a missing dependency:
```
Error: External library "base" not found.
```

**Comment by Chris00** [comment]
I'm a bit surprised because the only file in `config` that `mesh` requires does not depend on `base` (only the one that is *not* being built is).  @diml Is jbuilder looking for dependencies on a `jbuild` file level, before building the dependency graph?

**Comment by Chris00** [comment]
I [released a new version](https://github.com/ocaml/opam-repository/pull/11397) with the updated deps — and the script moved in its own directory.

**Comment by diml** [comment]
> @diml @rgrinberg Is jbuilder looking for dependencies on a jbuild file level, before building the dependency graph?

Yes. How would you do it otherwise?

**Comment by Chris00** [comment]
@diml I was thinking that it was done at the target level.  If a program is needed to compute some `:include`d parameters—as it is the case here—only the dependencies of the rule(s) executed to build that program are added (if the `jbuild` file contains unrelated rules, they are not taken into account).  Is there a problem with that way of proceeding?

**Comment by diml** [comment]
Ah, I see. This is indeed  the case. The only pitfall is when you have several libraries/executables in the same directory, because the .merlin is the same for all of them

**Pull request closed without merging**
