### PR TITLE
Add ctypes 0.18.0.

### PR DESCRIPTION
**Pull request by yallop**
[CHANGES](https://github.com/ocamllabs/ocaml-ctypes/blob/0.18.0/CHANGES.md)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
While compiling `ctypes.0.18.0` with ctypes-foreign installed I'm seeing this error. Is this expected?
```
- make: Circular ctypes-foreign <- ctypes-foreign dependency dropped.
```
With the removal of `ctypes.foreign.(threaded | unthreaded)`, is this expected? (while testing `gdal.0.9.0`)
```
# + /home/opam/.opam/4.11/bin/ocamlfind ocamlopt -linkpkg -g -linkpkg -package ctypes.foreign -package bigarray -I src -I examples src/gdal.cmxa examples/sanity.cmx -o examples/sanity.native
# ocamlfind: [WARNING] Package `threads': Linking problems may arise because of the missing -thread or -vmthread switch
# File "_none_", line 1:
# Error: No implementations provided for the following modules:
#          Thread referenced from /home/opam/.opam/4.11/lib/ctypes/ctypes-foreign.cmxa(Foreign)
#          Mutex referenced from /home/opam/.opam/4.11/lib/ctypes/ctypes-foreign.cmxa(Foreign)
# Command exited with code 2.
```
This big change will require more packages to be constrained to `ctypes < 0.18` later. I've just pushed a few changes to make my job easier.

Was there a reason `ctypes-foreign` wasn't a post dependency? Doing this unlocks issues testing packages that depend optionally with ctypes with foreign support but if there was a reason I'll revert this change.

**Comment by mseri** [comment]
Ping @yallop

**Comment by yallop** [comment]
Thanks, @mseri.  I haven't forgotten about this, but it'll be a few more days before I can investigate properly.

**Comment by yallop** [comment]
Thank you for your careful review of this, @kit-ty-kate .

> While compiling `ctypes.0.18.0` with ctypes-foreign installed I'm seeing this error. Is this expected?
> 
> ```
> - make: Circular ctypes-foreign <- ctypes-foreign dependency dropped.
> ```

This is an error, but I think it's a harmless one.  It'll be fixed in the next release (https://github.com/ocamllabs/ocaml-ctypes/pull/662).

> With the removal of `ctypes.foreign.(threaded | unthreaded)`, is this expected? (while testing `gdal.0.9.0`)
> 
> ```
> # + /home/opam/.opam/4.11/bin/ocamlfind ocamlopt -linkpkg -g -linkpkg -package ctypes.foreign -package bigarray -I src -I examples src/gdal.cmxa examples/sanity.cmx -o examples/sanity.native
> # ocamlfind: [WARNING] Package `threads': Linking problems may arise because of the missing -thread or -vmthread switch
> # File "_none_", line 1:
> # Error: No implementations provided for the following modules:
> #          Thread referenced from /home/opam/.opam/4.11/lib/ctypes/ctypes-foreign.cmxa(Foreign)
> #          Mutex referenced from /home/opam/.opam/4.11/lib/ctypes/ctypes-foreign.cmxa(Foreign)
> # Command exited with code 2.
> ```

I think it is expected, unfortunately.  The `ctypes.foreign` subpackage [depends on `threads`](https://github.com/ocamllabs/ocaml-ctypes/blob/0.18.0/META), but that doesn't seem to be sufficient for `ocamlfind` to add `-thread` (or `-I +threads`) to the build line.

> This big change will require more packages to be constrained to `ctypes < 0.18` later. I've just pushed a few changes to make my job easier.
> 
> Was there a reason `ctypes-foreign` wasn't a post dependency? Doing this unlocks issues testing packages that depend optionally with ctypes with foreign support but if there was a reason I'll revert this change.

Some of the build rules are [enabled only if `ctypes-foreign:installed` is true](https://github.com/yallop/opam-repository/blob/ctypes-0.18.0/packages/ctypes/ctypes.0.18.0/opam#L13-L14).  Will those rules continue to be enabled if `ctypes-foreign` is a post dependency and the package installation order changes?  If so, then I don't see a problem with making it a post dependency.

**Comment by aantron** [comment]
The Ctypes 0.18 release will be helpful to users of Luv, as with 0.17 users are required to install system dependencies that are not actually needed for the base package `ctypes`. See, for example, https://github.com/aantron/luv/issues/88.

**Comment by kit-ty-kate** [comment]
Sorry for the time this took. It's likely I've missed some revdeps failures as we're only testing 4.11 but hopefully that should be enough for now. I'll fix the remaining few if needed in further PRs. Thanks!

**Comment by kit-ty-kate** [comment]
cc @bbc2 for `pkcs11`
cc @victor-dumitrescu for `hacl-star-raw`
cc @dsheets for `unix-errno`
cc @cwong-ocaml for `async_ssl`
cc @dbuenzli for `tsdl-image`
cc @ygrek for `zstd`
cc @jmid for `qcstm`
cc @simonjbeaumont for `flock`
cc @xclerc for `memtrace_viewer`
cc @mgree for `libdash`

**Comment by dbuenzli** [comment]
> cc @dbuenzli for `tsdl-image`

I'm not the author/maintainer cc @tokenrove

**Comment by yallop** [comment]
Thank you for taking care of this, @kit-ty-kate!

**Comment by mgree** [comment]
Easy fix in my builds (for posterity: just add `-thread` and `-pkg threads`). Thanks for the ping! 😁

**Pull request merged**
