### PR TITLE
Package pyml_bindgen.0.1.1

### PR DESCRIPTION
**Pull request by mooreryan**
### `pyml_bindgen.0.1.1`
Generate pyml bindings from OCaml value specifications

---
* Homepage: https://github.com/mooreryan/ocaml_python_bindgen
* Source repo: git+https://github.com/mooreryan/ocaml_python_bindgen.git
* Bug tracker: https://github.com/mooreryan/ocaml_python_bindgen/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mooreryan** [comment]
I looked at the errors from opam 2.1 and it seemed to be from the resolver downgrading or dropping certain packages, so I made some changes to the deps.

* Made specific deps for the ppxs rather than ppx_jane
* Added a dep for python dev conf 
* Put a lower bound on cmdliner

**Comment by mooreryan** [comment]
The opam-2.1, extras, x86_32 is failing.  Looks to be sort of low level problem...any suggestions on how to proceed?

**Comment by mseri** [comment]
We can make it unavailable if it is not compatible. You can try to reproduce and work on it, if you want, following the steps at the top of the CI logs:
```
git clone --recursive "https://github.com/ocaml/opam-repository.git" && cd "opam-repository" && git fetch origin "refs/pull/19949/head" && git reset --hard e870dfb7
git fetch origin master
git merge c66dd4590bd215c9f95b36ed1c4047453a95dbaf
cat > ../Dockerfile <<'END-OF-DOCKERFILE'
FROM ocaml/opam:debian-11-ocaml-4.13@sha256:a77fc80588f2b127fbc53ae04a4d5f1b80f50157597a9b5981b8107b5ff74ebc
SHELL [ "/usr/bin/linux32", "/bin/sh", "-c" ]
USER 1000:1000
RUN opam repository remove -a multicore || true
RUN sudo ln -f /usr/bin/opam-2.1 /usr/bin/opam
RUN opam init --reinit -ni
ENV OPAMDOWNLOADJOBS 1
ENV OPAMERRLOGLEN 0
ENV OPAMSOLVERTIMEOUT 500
ENV OPAMPRECISETRACKING 1
WORKDIR /home/opam
RUN rm -rf opam-repository/
COPY --chown=1000:1000 . opam-repository/
RUN opam repository set-url --strict default "file://$HOME/opam-repository"
RUN opam pin add -k version -yn pyml_bindgen.0.1.1 0.1.1
RUN opam update --depexts
RUN opam remove pyml_bindgen.0.1.1 && opam install --deps-only pyml_bindgen.0.1.1 && opam install -v pyml_bindgen.0.1.1; \
    res=$?; \
    test "$res" != 31 && exit "$res"; \
    export OPAMCLI=2.0; \
    build_dir=$(opam var prefix)/.opam-switch/build; \
    failed=$(ls "$build_dir"); \
    for pkg in $failed; do \
    if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"debian-11\""; then \
    echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field."; \
    fi; \
    done; \
    exit 1
RUN opam update --depexts
RUN opam remove pyml_bindgen.0.1.1 && opam install --deps-only --with-test pyml_bindgen.0.1.1 && opam install -v --with-test pyml_bindgen.0.1.1; \
    res=$?; \
    test "$res" != 31 && exit "$res"; \
    export OPAMCLI=2.0; \
    build_dir=$(opam var prefix)/.opam-switch/build; \
    failed=$(ls "$build_dir"); \
    for pkg in $failed; do \
    if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"debian-11\""; then \
    echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field."; \
    fi; \
    done; \
    exit 1

END-OF-DOCKERFILE
docker build -f ../Dockerfile .
```

**Comment by mseri** [comment]
Let me just check if there is a CI issue, I  am seeing similar failures on other packages as well

**Comment by mooreryan** [comment]
I'm not positive but I think it's running into a problem similar to this one: https://github.com/ocaml/ocaml/issues/9800.  Maybe it is best to mark it as unavailable on the 32 bit x86?

**Comment by mooreryan** [comment]
Hey @mseri, just wanted to see if you had seen any issues in the CI, or if we should just mark the package as unavailable on the x86_32.  Thanks!

**Comment by kit-ty-kate** [comment]
Sorry for the delay. We couldn’t find the cause of this issue and we can ignore it for now. We’ll ignore similar issues in the future. Sorry for that again.

Thanks!

**Comment by mooreryan** [comment]
No worries, I appreciate the help!!

**Pull request merged**
