### PR TITLE
Old versions of ocaml-git do not compile on 4.06

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
Yup, just pushed a fix

**Comment by samoht** [comment]
Hum, interesting error on 4.04.2 while compiling nocrypto:

```
 File "_none_", line 1:
# Error: broken invariant in parsetree: Let with no bindings.
# Command exited with code 2.
```

**Comment by samoht** [comment]
nocrypto error fixed in #11964

**Comment by samoht** [comment]
The remaining errors are travis checks failing to find a solution to install git 1.4.10 (which is ok I think -- not sure why this is considered an error). So I think this is good to merge.

**Comment by mseri** [comment]
I agree. Thanks!

**Pull request merged**
