### PR TITLE
[new release] testo (4 packages) (0.1.0)

### PR DESCRIPTION
**Pull request by mjambon**
This is a new package! 🎉

Test framework for OCaml

- Project page: <a href="https://github.com/semgrep/testo">https://github.com/semgrep/testo</a>

##### CHANGES:

First official release

### CODE REVIEW

**Comment by shonfeder** [comment]
Thank you for publishing this new testing framework :)

There are several unbound module errors due to missing lower bounds. Could you take a look at the CI errors when you have a moment and let us know if you need any help identifying the needed lower bounds? Thanks!

**Comment by mjambon** [comment]
I set a minimum version for `re`. Let's see if it works.

**Comment by mjambon** [comment]
I also added a constraint on `cmdliner`.

**Comment by mjambon** [comment]
```
# (cd _build/default && /home/opam/.opam/4.13/bin/ocamlc.opt -w -40 -g -bin-annot -I lwt/.testo_lwt.objs/byte -I /home/opam/.opam/4.13/lib/astring -I /home/opam/.opam/4.13/lib/cmdliner -I /home/opam/.opam/4.13/lib/fpath -I /home/opam/.opam/4.13/lib/lwt -I /home/opam/.opam/4.13/lib/re -I /home/opam/.opam/4.13/lib/result -I /home/opam/.opam/4.13/lib/seq -I /home/opam/.opam/4.13/lib/testo-diff -I /home/opam/.opam/4.13/lib/testo-util -no-alias-deps -open Testo_lwt__ -o lwt/.testo_lwt.objs/byte/testo_lwt__Types.cmo -c -impl lwt/Types.ml)
# File "lwt/Types.ml", line 51, characters 53-61:
# 51 |   expected_output : (expected_output, missing_files) Result.t;
```

yikes. I checked that the type `Result.t` exists in the stdlib since OCaml 4.08.0. I presume one of the libraries we depend on used to expose a `Result` module but I don't know which one.

**Comment by mjambon** [comment]
Lwt depends on `result` without specifying a version constraint which leads to opam-ci using the lowest version available (1.0) which provides a `Result` module but not `Result.t`. I see the following options:

* fix this properly and set a version constraint in the lwt packages. Version 1.5 [should work](https://github.com/janestreet/result/releases/tag/1.5).
* declare that testo-lwt is incompatible with result < 1.5. I don't know how to do that.
* declare that testo-lwt requires result >= 1.5 (not ideal since we don't need it directly).
* release a version testo that avoids referencing `Result.t`.

What do you suggest?

**Comment by shonfeder** [comment]
Sorry for the delayed reply. Your fix here sounds good to me! Thank you for getting the CI green, and for publishing this new testing framework! Please don't forget to announce on discuss.ocaml.org if you're inclined!

**Pull request merged**
