### PR TITLE
Consolidate redis and session PRs

### PR DESCRIPTION
**Pull request by avsm**
I also added in some conflicts and upper bounds to avoid older versions of datakit and session from coinstalling with the new redis that has renamed ocamlfind packages.

@aluuu @rgrinberg @seliopou could you confirm this is right?

### CODE REVIEW

**Comment by avsm** [comment]
closed until new session release

**Comment by aluuu** [comment]
I still don't get it. Why do we have this error?

```
# Error: Findlib package "session.redis-lwt" not found.
# -> required by "ci/src/jbuild (context default)"
# Hint: try: jbuilder external-lib-deps --missing -p datakit-ci -j 1
```
Even with updated version of `session` package, which actually [contains](https://github.com/inhabitedtype/ocaml-session/blob/0.3.2/_oasis#L56) `session.redis-lwt` findlib package definition.

Could anyone explain me the cause of this error?

**Comment by rgrinberg** [comment]
Isn't it a matter of session including the correct opam dependencies rather than whatever it has in findlib? Does it have `redis-lwt` as an opam dependency?

**Comment by aluuu** [comment]
@rgrinberg looks like it [does](https://github.com/mirage/opam-repository/blob/ede22b8c69d34e47812704cba63851f17fc02e22/packages/session/session.0.3.2/opam#L56).

**Comment by aluuu** [comment]
Hmm, could it be caused be the fact that `datakit-ci.0.10.0` does not depend on `redis-lwt` explicitly? And redis-lwt is not considered as a dependency (as long as it is specified in depopts section of opam file)

**Comment by aluuu** [comment]
Another insight: maybe it can be caused by [these lines](https://github.com/mirage/opam-repository/blob/redis/packages/datakit-ci/datakit-ci.0.10.0/opam#L30). 

What happened as far as I understood:
1. during `opam install datakit-ci.0.10.0` dependency tree resolves to redis and session deps into `redis.0.3.3` (because of version restriction) and `session.0.3.2` (because it is the latest version of session)
2. `redis.0.3.3` installed successfully and it does not provide `redis-lwt` package
3. during `session.0.3.2` installation, depopt `redis-lwt` is absent, so `session.redis-lwt` is not built
4. `datakit-ci` build fails

Correct me if I'm wrong.

**Comment by rgrinberg** [comment]
Perhaps. The reason why I started getting rid of depopts is precisely because of issues like this.

If @seliopou agrees, I can just split session with jbuilder so that we don't have reverse engineer this nonsense anymore.

**Comment by aluuu** [comment]
I've tried to reproduce it locally:

```
[aluuu@Aleksandrs-MacBook-Pro:~/workspace/github.com/opam-repository on 3c12678]
% opam update && opam remove redis && opam remove session && opam install datakit-ci.0.10.0
```

`install`'s output:

```
The following actions will be performed:
  ∗  install redis      0.3.3                 [required by datakit-ci]
  ∗  install session    0.3.2                 [required by datakit-ci]
  ∗  install datakit-ci 0.10.0
===== ∗  3 =====
Do you want to continue ? [Y/n] n
```

Obviously, `session.0.3.2` and `redis.0.3.3` are incompatible.

Changed `datakit.0.10.0/opam` with
```
diff --git a/packages/datakit-ci/datakit-ci.0.10.0/opam b/packages/datakit-ci/datakit-ci.0.10.0/opam
index 7d3797d..8cd7ae8 100644
--- a/packages/datakit-ci/datakit-ci.0.10.0/opam
+++ b/packages/datakit-ci/datakit-ci.0.10.0/opam
@@ -27,7 +27,7 @@ depends: [
   "io-page"
   "pbkdf"
   "webmachine" {>= "0.4.0"}
-  "session" {>= "0.3.0"}
+  "session" {< "0.3.2"}
   "redis" {<"0.3.4"}
   "asetmap"
   "github" {>= "2.2.0"}
```

Repeat

```
[aluuu@Aleksandrs-MacBook-Pro:~/workspace/github.com/opam-repository on 3c12678]
% opam update && opam remove redis && opam remove session && opam install datakit-ci.0.10.0
```

Got
```
The following actions will be performed:
  ∗  install redis      0.3.3                 [required by datakit-ci]
  ∗  install session    0.3.0                 [required by datakit-ci]
  ∗  install datakit-ci 0.10.0
===== ∗  3 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
Processing  3/3: [datakit-ci: http] [redis: http] [session: http]
[session.0.3.0] https://github.com/inhabitedtype/ocaml-session/archive/0.3.0.tar.gz downloaded
[redis.0.3.3] https://github.com/0xffea/ocaml-redis/archive/0.3.3.tar.gz downloaded
[datakit-ci.0.10.0] https://github.com/moby/datakit/releases/download/0.10.0/datakit-0.10.0.tbz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
∗  installed redis.0.3.3
∗  installed session.0.3.0
[ERROR] The compilation of datakit-ci failed at "jbuilder build -p datakit-ci -j 4".

#=== ERROR while installing datakit-ci.0.10.0 =================================#
# opam-version 1.2.2
# os           darwin
# command      jbuilder build -p datakit-ci -j 4
# path         /Users/aluuu/.opam/4.04.0/build/datakit-ci.0.10.0
# compiler     4.04.0
# exit-code    1
# env-file     /Users/aluuu/.opam/4.04.0/build/datakit-ci.0.10.0/datakit-ci-72125-2dea01.env
# stdout-file  /Users/aluuu/.opam/4.04.0/build/datakit-ci.0.10.0/datakit-ci-72125-2dea01.out
# stderr-file  /Users/aluuu/.opam/4.04.0/build/datakit-ci.0.10.0/datakit-ci-72125-2dea01.err
### stderr ###
# Error: I couldn't find 'ocaml-migrate-parsetree.driver-main'.
# I need this library in order to use ppx rewriters.
# See the manual for details.
# Hint: opam install ocaml-migrate-parsetree
```

Another build failure, but not related to redis/session packages, as far as I can see.

**Comment by aluuu** [comment]
Hi all,

FYI, I've made #9200 with proposed fix.

**Pull request merged**
