### PR TITLE
ketrew.0.0.0 is unbuildable due to ocp-build/typerex brokenness

### PR DESCRIPTION
**Pull request by dsheets**
@smondet

### CODE REVIEW

**Comment by smondet** [comment]
I don't understand; there is a version constrain on `ocp-build`, so what changed that make it break?

**Comment by dsheets** [comment]
```
$ opam install ocp-build.1.99.6-beta
The following actions will be performed:
  ∗  install   typerex   1.99.6-beta                 [required by ocp-build]
  ↘  downgrade ocp-build 1.99.9-beta to 1.99.6-beta
===== ∗  1   ↘  1 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] curl: code 406 while downloading
        https://github.com/OCamlPro/typerex/archive/typerex.1.99.6-beta.tar.gz
[ERROR] The sources of the following couldn't be obtained, aborting:
          - typerex.1.99.6-beta
        (This may be fixed by running 'opam update')
```

Probably from #3491.

**Comment by avsm** [comment]
I've mostly given up triaging any problems with ocp-build.  Highly recommend moving over to something else.

**Comment by smondet** [comment]
Ketrew as already moved to something else (not released). 

But Ok for removing `0.0.0` from the opam-repo, if it annoys you.

**Comment by dsheets** [comment]
It fails reverse dependency tests for other packages (e.g. `uri`). Is there a new release soon?

**Comment by smondet** [comment]
I don't know when I'm going to be able to pull all the experimental things together to make a release.
But all the users I know are pinning Ketrew to `master` so removing `0.0.0` shouldn't be a problem; let me know if somebody complains.

**Comment by avsm** [comment]
@smondet will remove this one for now then, since it probably can't ever build successfully with the ocp-build package disappearing.

**Pull request merged**
