### PR TITLE
Package raylib.0.1.0

### PR DESCRIPTION
**Pull request by tjammer**
### `raylib.0.1.0`
OCaml bindings for raylib

---
* Homepage: https://github.com/tjammer/raylib-ocaml
* Source repo: git+https://github.com/tjammer/raylib-ocaml.git
* Bug tracker: https://github.com/tjammer/raylib-ocaml/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by mseri** [comment]
It is failing with
```
#=== ERROR while compiling raylib.0.1.0 =======================================#
2361# context              2.0.7 | linux/arm64 | ocaml-base-compiler.4.11.0 | file:///home/travis/build/ocaml/opam-repository
2362# path                 ~/.opam/ocaml-base-compiler.4.11.0/.opam-switch/build/raylib.0.1.0
2363# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p raylib -j 31 @install @runtest
2364# exit-code            1
2365# env-file             ~/.opam/log/raylib-24677-0a5907.env
2366# output-file          ~/.opam/log/raylib-24677-0a5907.out
2367### output ###
2368# File "src/c/dune", line 9, characters 16-48:
2369# 9 |   (include_dirs %{project_root}/src/c/vendor/src))
2370#                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2371# Error: Include directory "vendor/src" does not exist.
```

**Comment by tjammer** [comment]
Yes, I wasn't aware that github releases don't include submodules. I pushed a fix

**Comment by mseri** [comment]
The checksums need to be updated as well:
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - raylib.0.1.0:
            https://github.com/tjammer/raylib-ocaml/releases/download/0.1/raylib-ocaml-0.1.tar.gz (Bad checksum, expected md5=215b2bcd6b9f0000e715da153170b24a)
```

**Comment by tjammer** [comment]
Now it fails b/c there are some missing C dependencies (RandR headers). Unfortunately, the list of dependencies is quite long, eg for debian: `libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev`.

Unfortunately, there are no conf-packages for all these libraries. Can I provide some depext rules on which libs to install somehow? And if so, for which package managers is this needed? This job uses apt at least.

**Comment by mseri** [comment]
you can have the depexts directly in the opam file if you want. You can take inspiration from the conf packages to see how to address various distributions. If not all can be supported it is not a problem, but if you have a few then users can contribute depexts for their distributions

**Comment by mseri** [comment]
Wow, thank you very much!

**Comment by mseri** [comment]
Feel free to announce the release on discuss.ocaml.org. We have a community category and an announcement tag for this purpose

**Pull request merged**
