### PR TITLE
added packages/cpm/cpm.4.0.0

### PR DESCRIPTION
**Pull request by UnixJunkie**
package went from obuild to jbuilder

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I think it's OK to merge.
I also thing there are too many CI tests diagnostics. Users are overflown with information.
Where is the summary and how to look at it?

**Comment by kit-ty-kate** [comment]
What would you want as a summary ?
Just for info one revdeps is failing:
```
#=== ERROR while compiling lbvs_consent.1.1.2 =================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.05.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.05.0/.opam-switch/build/lbvs_consent.1.1.2
# command              ~/.opam/4.05.0/bin/obuild configure
# exit-code            4
# env-file             ~/.opam/log/lbvs_consent-18-be7d52.env
# output-file          ~/.opam/log/lbvs_consent-18-be7d52.out
### output ###
# Configuring consent-0.1...
# error: unexpected parse error 'unknown token 'ID[warning]' in meta file
# ( - ID[mt] ) = "Linking problems may arise because of the missing -thread or -vmthread switch" ID[warning] ( - ID[mt_vm] , - ID[mt_posix] ) = "Linking problems may arise because of the missing -thread or -vmthread switch" ID[package] "vm" ( ID[requires] = "unix" ID[directory] = "+vmthreads" ID[exists_if] = "threads.cma" ID[archive] ( ID[byte] , ID[mt] , ID[mt_vm] ) = "threads.cma" ID[version] = "[internal]" ) ID[package] "posix" ( ID[requires] = "unix" ID[directory] = "+threads" ID[exists_if] = "threads.cma" ID[archive] ( ID[byte] , ID[mt] , ID[mt_posix] ) = "threads.cma" ID[archive] ( ID[native] , ID[mt] , ID[mt_posix] ) = "threads.cmxa" ID[version] = "[internal]" )' in meta file /home/opam/.opam/4.05.0/lib/threads/META
```
Thanks and sorry for the delay.

**Comment by UnixJunkie** [comment]
As a "summary", I'd like to see just the things which are failing and that need to be corrected in order for the PR to be accepted.

**Comment by kit-ty-kate** [comment]
Could you be more specific ? Currently the box below tells you what category is failing (Maybe have better names here ?). When you click on details it gives you what are failing in red with their logs. (maybe you want green lines to be removed ?) Apart from the long-standing issues with Alpine & OpenSUSE (I'm as annoyed as everyone else) and the small suggestions/questions in parenthesis above I don't see what could be improved here :/ If you have other suggestions I'll be happy to discuss them.

**Comment by kit-ty-kate** [comment]
Also I find having opam1 & opam2 tested is a real pain and I would prefer to only have opam2 but I can't do anything here and such discussion was closed month ago... :(

**Comment by UnixJunkie** [comment]
Hello,

Thanks for your work on opam-repository and sorry if I sound like a grumpy old man. I'm not that old, but I might be grumpy sometimes.

It would be nice to clearly/easily see which errors are grave and should be corrected so that the PR can be merged (blocking errors).

For example, what am I supposed to do with this error:
alpine doesn't have m4?! https://ci.ocamllabs.io/log/saved/docker-build-a2d99b36856a6375bc0a0636a310b1f0/a85f159f7e0b1ad19195662d493140aa52ed6747
or conf-m4 doesn't work on alpine-3.6_ocaml-4.05.0 ?

What can I do about this one:
https://ci.ocamllabs.io/log/saved/docker-build-6eab66885928f0d8c93a81a7b936da69/d116b43711cb529e99a7d5fc8d35b35afdbb027e

How about this one:
https://ci.ocamllabs.io/log/saved/docker-build-4f9a0875e17489ef18c0165bf9bed59e/080d3ab9c28dcc1aa87ccd566ab5e26a942f983f

And this one:
https://travis-ci.org/ocaml/opam-repository/jobs/369033333

As you already noticed, lbvs_consent is now broken. I think because of the recent ocamlfind update which broke obuild. I'll try to fix this soon.

**Comment by UnixJunkie** [comment]
Yes, less "noise" would be great.
opam-1.2 starts to be old. Once 2.0 is officially out, opam-1.2 tests should really be removed.

**Comment by kit-ty-kate** [comment]
Oops I meant to say CentOS not OpenSUSE. So yes, the two Alpine failures and the CentOS failure are really annoying. I can't really do anything about it right now but I'll harder to beg to have that fixed by the end of the week.

The problem with camlp4+system is quite recent and may be related to a "recent" change by @dra27 but I'm not sure. I'll try to have that fixed by the end of the week as well.

If you don't see any updates from me by the end of the week please ping me again that would give me more energy to find more solutions* and to not be depressed over long-standing issues that I have little to no power over.

*: seems like I work on anger to some extend. (not related to you, don't worry ^^")

**Comment by kit-ty-kate** [comment]
@UnixJunkie The problems with Alpine & CentOS are now fixed. I might try to improve the readability at some point but to change the interface I have to dive into datakit and patch it locally so it might take some time.

**Pull request merged**
