### PR TITLE
Package resource-pooling.0.1

### PR DESCRIPTION
**Pull request by jrochel**
### `resource-pooling.0.1`

library for pooling resources like connections, threads, or similar

This package is derived from the module Lwt_pool from the lwt package,
which implements resource pooling. With Resource_pool this package
provides a modified version with additional features. Also there is a
module called Server_pool that manages resource clusters, specifically
a cluster of servers each with its own connection pool.

---
* Homepage: https://github.com/ocsigen/resource-pooling
* Source repo: https://github.com/ocsigen/resource-pooling.git
* Bug tracker: https://github.com/ocsigen/resource-pooling/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
A constraint on `lwt` or something like that is probably required here
```
#=== ERROR while installing resource-pooling.0.1 ==============================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              ocaml setup.ml -build
# path                 /home/opam/.opam/4.05.0/build/resource-pooling.0.1
# compiler             4.05.0
# exit-code            1
# env-file             /home/opam/.opam/4.05.0/build/resource-pooling.0.1/resource-pooling-7-97bbf8.env
# stdout-file          /home/opam/.opam/4.05.0/build/resource-pooling.0.1/resource-pooling-7-97bbf8.out
# stderr-file          /home/opam/.opam/4.05.0/build/resource-pooling.0.1/resource-pooling-7-97bbf8.err
### stdout ###
# [...]
# /home/opam/.opam/4.05.0/bin/ocamlfind ocamldep -package lwt -package batteries -modules src/resource_pool.ml > src/resource_pool.ml.depends
# /home/opam/.opam/4.05.0/bin/ocamlfind ocamldep -package lwt -package batteries -modules src/server_pool.mli > src/server_pool.mli.depends
# /home/opam/.opam/4.05.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package lwt -package batteries -I src -o src/server_pool.cmi src/server_pool.mli
# /home/opam/.opam/4.05.0/bin/ocamlfind ocamldep -package lwt -package batteries -modules src/server_pool.ml > src/server_pool.ml.depends
# /home/opam/.opam/4.05.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package lwt -package batteries -I src -o src/resource_pool.cmo src/resource_pool.ml
# /home/opam/.opam/4.05.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package lwt -package batteries -I src -o src/server_pool.cmo src/server_pool.ml
# + /home/opam/.opam/4.05.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package lwt -package batteries -I src -o src/server_pool.cmo src/server_pool.ml
# File "src/server_pool.ml", line 17, characters 14-34:
# Error: Unbound module Lwt_log
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/home/opam/.opam/4.05.0/bin/ocamlbuild' src/resource-pooling.cma src/resource-pooling.cmxa src/resource-pooling.a src/resource-pooling.cmxs -use-ocamlfind -tag debug' terminated with error code 10")
```

**Comment by mseri** [comment]
Wasn’t Lwt_log deprecated in favour of Log?

**Comment by jrochel** [comment]
Indeed. I wasn't aware of that as I using an old version of lwt. I will soon update my library to use `Logs_lwt` from the `logs` package.

**Comment by jrochel** [comment]
For now I'll go with `lwt (< 4.0.0)`. Once we port the application for which this package was developed to `lwt 4` I will also port this package to use the package `logs`.

**Comment by mseri** [comment]
In the ocaml-4.01 to ocaml-4.04 tests, for some reasons it tries to use lwt-2.4.5 and fails miserably. I think a lower bound forcing at least lwt-2.7 may be enough

**Comment by jrochel** [comment]
Thanks for the feedback. Sorry for the bother. I feel like I should have been more meticulous in my attempts of creating this package. Then again, it is my first one...

**Comment by kit-ty-kate** [comment]
No worries. Also, for the record OASIS is not meant to be used like this. The OASIS files should be generated before doing the release using `oasis setup` which generates a lot of files and doesn't require any other dependencies than ocamlfind and ocamlbuild.
Also people tend to use `dune` or `topkg` nowadays but it's a matter of choice I guess.

Do you want to continue improving the package or should I merge it as is?

**Comment by jrochel** [comment]
I'm fine with the package's current state. So I'd be grateful if you would merge it.

**Comment by kit-ty-kate** [comment]
ok, thx.

**Pull request merged**
