### PR TITLE
first release of pa_ppx_migrate_ocaml_parsetree, 0.01

### PR DESCRIPTION
**Pull request by chetmurthy**
This is broken out of pa_ppx_migrate (to make that build much faster), provides migrations between ocaml 4.02.0 <-> 5.3.0 and all intermediate versions.

### CODE REVIEW

**Comment by chetmurthy** [comment]
There are two failures, both due to mangled object-files produced by compile-steps.  I took the docker script for the "4.12" build, and ran it myself locally.   I found that it would sometimes go thru and sometimes fail.  I'm going to "rebuild failed" and see if after a few tries, things go thru, but at this point, I don't think the problem is with the actual CI run.

**Comment by mseri** [comment]
Do you want to investigate this further?

**Comment by chetmurthy** [comment]
It's a little difficult to investigate, b/c it takes so long to run the test (even on my local Radeon server).  I -did- do some investigation.  I found that splitting the install into "deps-only" and then "the package" made the failure go away.  But as I noted above, even the original Docker script sometimes succeeds on my local machine (though never, so far, on the CI cluster).

```
--- DOIT	2024-12-16 14:19:28.133508927 -0800
+++ DOIT.2	2024-12-16 17:25:25.822002683 -0800
@@ -23,21 +23,8 @@
 RUN opam repository set-url --strict default opam-repository/
 RUN opam update --depexts || true
 RUN opam pin add -k version -yn pa_ppx_migrate_ocaml_parsetree.0.01 0.01
-RUN opam reinstall pa_ppx_migrate_ocaml_parsetree.0.01; \
-    res=$?; \
-    test "$res" != 31 && exit "$res"; \
-    export OPAMCLI=2.0; \
-    build_dir=$(opam var prefix)/.opam-switch/build; \
-    failed=$(ls "$build_dir"); \
-    partial_fails=""; \
-    for pkg in $failed; do \
-    if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"debian-12\""; then \
-    echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field."; \
-    fi; \
-    test "$pkg" != 'pa_ppx_migrate_ocaml_parsetree.0.01' && partial_fails="$partial_fails $pkg"; \
-    done; \
-    test "${partial_fails}" != "" && echo "opam-repo-ci detected dependencies failing: ${partial_fails}"; \
-    exit 1
+RUN opam install --deps-only -t pa_ppx_migrate_ocaml_parsetree.0.01
+RUN opam install pa_ppx_migrate_ocaml_parsetree.0.01
 
 END-OF-DOCKERFILE
 docker build --progress plain -f ../Dockerfile .
```

**Comment by chetmurthy** [comment]
OK, all the tests passed.  I'm glad you pushed me about what I thought was a build-system glitch.  It was in fact a bug in my Makefile that only showed up under a poorly-timed race condition.  But fixed now.

**Comment by mseri** [comment]
Thanks for the patience!

**Pull request merged**
