### PR TITLE
psq {<0.2.0} for lru versions <0.3.0

### PR DESCRIPTION
**Pull request by pqwy**
[Crossref](https://github.com/ocaml/opam-repository/pull/13863), [crossref](https://github.com/ocaml/opam-repository/pull/13864).

### CODE REVIEW

**Comment by avsm** [comment]
just waiting for ci to finish

**Comment by pqwy** [comment]
Third time lucky :eyes:

**Comment by pqwy** [comment]
I'm not sure what is going on with `anycache`. It's marked read-only on gitlab. @edwintorok

**Comment by mseri** [comment]
Ccan you add the correct bound to anycache opam file?

**Comment by pqwy** [comment]
No. @mseri

First, because it's not my responsibility to maintain third-party packages. And second, because the exact same situation exists in the opam repo without this change.

Amusingly, by merging #13863, but neither #13864 nor this, you broke installability of all versions of `lru` in opam, and of everything that depends on it.

**Comment by mseri** [comment]
I asked as a favour because you were already fixing this, and changing just an opam package would have helped us maintaining the repo. Many times people help us for such a small changes without the need to be upset. I wasn’t asking to maintain the upstream package. It would have probably taken less time than writing your response. 


I was planning on merging if I weren’t getting a response soon anyways

**Comment by pqwy** [comment]
I am not upset. I feel like the expectation has been shifting for submitters to maintain the opam repo, and publishing a package includes more and more of wrangling with the the entire opam universe. I personally feel that the bar is being pushed a little too high.

But thank you, in any case!

**Pull request merged**
