### PR TITLE
Package rss.3.0

### PR DESCRIPTION
**Pull request by zoggy**
### `rss.3.0`
Library to read and write RSS files

---
* Homepage: http://zoggy.frama.io/ocamlrss/
* Source repo: git+https://framagit.org/zoggy/ocamlrss.git
* Bug tracker: https://framagit.org/zoggy/ocamlrss/-/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks! Could you return the fixes to the opam file upstream?

**Comment by zoggy** [comment]
Sure, thanks. Can you tell me why "dev" should be used instead of "pinned" in the build target ?

**Comment by kit-ty-kate** [comment]
You can read about it in: https://github.com/ocaml/dune/pull/3647

**Comment by zoggy** [comment]
Ok, thanks a lot !

**Pull request merged**
