### PR TITLE
[new release] mirage-net (4.0.0)

### PR DESCRIPTION
**Pull request by hannesm**
Network signatures for MirageOS

- Project page: <a href="https://github.com/mirage/mirage-net">https://github.com/mirage/mirage-net</a>
- Documentation: <a href="https://mirage.github.io/mirage-net/">https://mirage.github.io/mirage-net/</a>

##### CHANGES:

- remove dependency on mirage-device (mirage/mirage-net#24 @hannesm)
- remove Mirage_net_lwt module (mirage/mirage-net#24 @hannesm)

### CODE REVIEW

**Comment by dinosaure** [comment]
We should add a constraint on `mirage-net-{unix,solo5,xen}`?

**Comment by hannesm** [comment]
@dinosaure I will work on fixing this later. I think it is not good to break all the reverse deps packages with no good reason --> we can re-add a type error and val pp_error to mirage-net and leave the API clients alone :)

**Comment by hannesm** [comment]
After further investigation, I added the `` `Disconnected `` to the error variant, and all reverse dependencies are nicely working again (locally, let's see what the CI says).

**Comment by hannesm** [comment]
fine to merge.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
