### PR TITLE
lbfgs: add missing dependency on camlp4

### PR DESCRIPTION
**Pull request by damiendoligez**

### CODE REVIEW

**Comment by samoht** [comment]
missing depexts on OSX:

```
#=== ERROR while installing lbfgs.0.8.6 =======================================#
# opam-version 1.2.2
# os           darwin
# command      ocaml setup.ml -configure --prefix /Users/travis/.opam/system
# path         /Users/travis/.opam/system/build/lbfgs.0.8.6
# compiler     system (4.03.0)
# exit-code    1
# env-file     /Users/travis/.opam/system/build/lbfgs.0.8.6/lbfgs-7589-f0f09f.env
# stdout-file  /Users/travis/.opam/system/build/lbfgs.0.8.6/lbfgs-7589-f0f09f.out
# stderr-file  /Users/travis/.opam/system/build/lbfgs.0.8.6/lbfgs-7589-f0f09f.err
### stdout ###
# Please install one of these fortran compilers: gfortran, g95, g77.
# If you use a different compiler, send its name to the author (see _oasis file).
```

**Comment by Chris00** [comment]
@samoht What depext has to be added on OSX to have one of these compilers?

**Comment by Chris00** [comment]
Would
```
  [["osx" "homebrew"] ["gfortran"]]
```
do?

**Comment by samoht** [comment]
```
$ brew search gfortran
GNU Fortran is now provided as part of GCC, and can be installed with:
  brew install gcc
$ brew search g95
No formula found for "g95".
==> Searching pull requests...
$ brew search g77
No formula found for "g77".
==> Searching pull requests...
```

So `[["osx" "homebrew"] ["gcc"]]` seems to do it.

**Comment by damiendoligez** [comment]
Superseded by #7258

**Pull request closed without merging**
