### PR TITLE
[new release] inotify (2 packages) (2.6)

### PR DESCRIPTION
**Pull request by clecat**
Inotify bindings for OCaml

- Project page: <a href="https://github.com/whitequark/ocaml-inotify">https://github.com/whitequark/ocaml-inotify</a>
- Documentation: <a href="https://whitequark.github.io/ocaml-inotify">https://whitequark.github.io/ocaml-inotify</a>

##### CHANGES:

add an Eio backend in a new inotify-eio package (@patricoferris, @akirak, @clecat)

### CODE REVIEW

**Comment by clecat** [comment]
I cannot seem to reproduce the issues with `libirmin` locally: The tests are properly running.
It is especially strange due to the fact that this release should not have any impact on libraries (it added a new package).

**Comment by akirak** [comment]
The job for `tezos-context.12.3` failed, and the others were just cancelled. 

> Processing  1/129: [alcotest.1.8.0, alcotest-lwt.1.8.0: http]
[ERROR] Failed to get sources of alcotest.1.8.0, alcotest-lwt.1.8.0 (https://github.com/mirage/alcotest/releases/download/1.8.0/alcotest-1.8.0.tbz): Curl failed

I have no idea why this happens. All the other packages seem to fail on the CI server, so maybe it's misconfiguration?

**Comment by mseri** [comment]
None of the failures depend on this release, they are all CI issues

**Comment by mseri** [comment]
Thanks

**Comment by clecat** [comment]
Thank you for your time

**Pull request merged**
