### PR TITLE
mirage-net-xen uses `with sexplib` camlp4

### PR DESCRIPTION
**Pull request by samoht**
So it needs an older version of sexplib.

### CODE REVIEW

**Comment by hannesm** [comment]
it is likely that older versions need that as well!?

**Comment by samoht** [comment]
nope, older versions do not use sexplib (I did a quick grep before submitting the patch)

**Comment by hannesm** [comment]
ah, cool. thx!

**Comment by thornleyk** [comment]
I think I am having the same issue with sexplib on macosx mirage-net-macosx. the opam does not specify the version

**Comment by hannesm** [comment]
@thornleyk thx for the report, you should be able to get a working one by doing `opam pin add mirage-net-macosx --dev-repo`, or wait until #7807 lands (within the next few hours), and do a `opam update && opam install mirage-net-macosx`

**Pull request merged**
