### PR TITLE
Remove obsolete versions of ppx_regexp.

### PR DESCRIPTION
**Pull request by paurkedal**
Version 0.3.1 is a full and better replacement.

### CODE REVIEW

**Comment by hcarty** [comment]
Be careful - with opam 1.x, if this older version is removed from the repository, a user can be stuck unable to remove the older version if they still have it installed.

**Comment by paurkedal** [comment]
I wasn't aware of that.  Version 0.3.1 was release 1 month ago, so that could be an issue.  I'll take your advice and close this.  Thanks!

This would solve [a depfail for 4.06.0](http://gallium.inria.fr/~scherer/tmp/opam-builder/opam-builder.html?p=20171019113529-28d58d1-4.06.0%2Bbeta2%2Bdefault-unsafe-string.files%2Fppx_regexp.0.3.0.json&view=1).  If that's something we worry about, I can send a PR for a compiler version constraint instead.

**Comment by hcarty** [comment]
A version constraint would be ideal!  Thanks

**Comment by paurkedal** [comment]
#10511

**Pull request closed without merging**
