### PR TITLE
3 packages from gitlab.inria.fr/fpottier/menhir/-/archive/20211223/archive.tar.gz

### PR DESCRIPTION
**Pull request by fpottier**
This pull-request concerns:
-`menhir.20211223`: An LR(1) parser generator
-`menhirLib.20211223`: Runtime support library for parsers generated by Menhir
-`menhirSdk.20211223`: Compile-time library for auxiliary tools related to
 Menhir

---
* Homepage: http://gitlab.inria.fr/fpottier/menhir
* Source repo: git+https://gitlab.inria.fr/fpottier/menhir.git
* Bug tracker: https://gitlab.inria.fr/fpottier/menhir/-/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mseri** [comment]
Added a bound on lambdapi, I think/hope it should be the last one

**Comment by mseri** [comment]
Is this superseded by https://github.com/ocaml/opam-repository/pull/20316 ?

**Comment by fpottier** [comment]
No, `menhir` and `feat` are different packages; no relationship.

**Comment by mseri** [comment]
Sorry, I had read menhir on both :) I guess I need the holiday 😛

**Comment by kit-ty-kate** [comment]
@fpottier I tried using this version of menhir and I found the error message rather unhelpful:
```
      the code back-end requires the type of every nonterminal symbol to be
      known. Please specify the type of every symbol via %%type declarations, or
      enable type inference (look up --infer in the manual).
      Type inference is automatically enabled when Menhir is used via Dune.
```
It says it’s not supposed to be a problem when menhir is used by dune, however this is not true. This is only true if the user used the `2.1` or later version of the menhir plugin.

The INRIA gitlab instance does not allow outsiders to create an account so I cannot open a PR but here is my proposal to improve the error message: https://github.com/kit-ty-kate/menhir/commit/7d808a7ba6a5fd82739b3dc4fb41e618538c2260

@fpottier what do you think?

**Comment by fpottier** [comment]
Hi Kate, I think `(using menhir 2.0)` is enough. I didn't want to pollute the error message with this information, but you are right, it may be helpful, so I will add it. Thanks!

**Comment by fpottier** [comment]
Hi, by reading the CI log, I see that labrys.0.1 needs `menhir < 20211223`. Otherwise, I see no problems related to the new versions of Menhir.

**Comment by mseri** [comment]
Do you want to improve the error message in this release or you want do to it on the next one?

**Comment by fpottier** [comment]
Maybe it can wait until the next release. Otherwise I would have to close this PR and open a new one. What do you think?

**Comment by mseri** [comment]
I am fine either way. I slightly prefer a more descriptive error message but in that case I need to remember to cherry pick the two commits that I added here.
@kit-ty-kate what do you think?

**Comment by fpottier** [comment]
OK, let me close this PR and open a new one (hoping that this not delay things too much).

**Pull request closed without merging**
