### PR TITLE
[new release] cmon (0.1)

### PR DESCRIPTION
**Pull request by let-def**
A library for printing OCaml values with sharing

- Project page: <a href="https://github.com/let-def/cmon">https://github.com/let-def/cmon</a>

##### CHANGES:

First release.

### CODE REVIEW

**Comment by mseri** [comment]
32 bits tests fail with
```
#=== ERROR while compiling cmon.0.1 ===========================================#
# context              2.1.1 | linux/arm32 | ocaml-base-compiler.4.13.1 | pinned(https://github.com/let-def/cmon/releases/download/v0.1/cmon-0.1.tbz)
# path                 ~/.opam/4.13/.opam-switch/build/cmon.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p cmon -j 159 --promote-install-files=false @install @runtest
# exit-code            1
# env-file             ~/.opam/log/cmon-36-3d46b2.env
# output-file          ~/.opam/log/cmon-36-3d46b2.out
### output ###
# File "tests/test.expected", line 1, characters 0-0:
#          git (internal) (exit 1)
# (cd _build/default && /usr/bin/git --no-pager diff --no-index --color=always -u tests/test.expected tests/test.exe.output)
# diff --git a/tests/test.expected b/tests/test.exe.output
# index be06034..94fdeb6 100644
# --- a/tests/test.expected
# +++ b/tests/test.exe.output
# @@ -23,10 +23,10 @@ true
#  -2
#  
#  max_int:
# -4611686018427387903
# +1073741823
#  
#  min_int:
# --4611686018427387904
# +-1073741824
#  
#  0.:
#  0.
```

is that fine? In that case we can disable them on those archs

**Comment by let-def** [comment]
I did not develop with 32 bits in mind, but that should be easy to fix.
Sorry for the annoyance, wait a bit and I will try to publish an updated package soon!

**Comment by mseri** [comment]
No worries. We can wait :)

**Comment by mseri** [comment]
I am going to close this for now, feel free to reopen it once it is updated

**Pull request closed without merging**
