### PR TITLE
[new release] combinat (1.0)

### PR DESCRIPTION
**Pull request by jfeser**
Fast combinatorics functions for OCaml.

- Project page: <a href="https://github.com/jfeser/combinat">https://github.com/jfeser/combinat</a>
- Documentation: <a href="https://jfeser.github.io/combinat/">https://jfeser.github.io/combinat/</a>

##### CHANGES:

Initial release.

### CODE REVIEW

**Comment by mseri** [comment]
There are missing dependencies:
```
#=== ERROR while compiling combinat.1.0 =======================================#
# context              2.0.3 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/jfeser/combinat/releases/download/1.0/combinat-1.0.tbz)
# path                 ~/.opam/4.07/.opam-switch/build/combinat.1.0
# command              ~/.opam/4.07/bin/dune build -p combinat -j 71
# exit-code            1
# env-file             ~/.opam/log/combinat-20-5f5641.env
# output-file          ~/.opam/log/combinat-20-5f5641.out
### output ###
# File "lib/dune", line 3, characters 17-22:
# 3 |  (libraries base stdio bigarray)
#                      ^^^^^
# Error: Library "stdio" not found.
# Hint: try: dune external-lib-deps --missing -j 71 -p combinat @@default
# File "lib/dune", line 6, characters 18-31:
# 6 |  (preprocess (pps ppx_sexp_conv ppx_expect))
#                       ^^^^^^^^^^^^^
# Error: Library "ppx_sexp_conv" not found.
# Hint: try: dune external-lib-deps --missing -j 71 -p combinat @@default
```

**Comment by kit-ty-kate** [comment]
Could you return the fix I just did upstream?

**Comment by jfeser** [comment]
Sure. Thanks!

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
