### PR TITLE
Package for "num" version 1.2

### PR DESCRIPTION
**Pull request by xavierleroy**
The legacy library for arbitrary-precision arithmetic.  Now with better findlib support, thanks to @dra27.

### CODE REVIEW

**Comment by xavierleroy** [comment]
CI complains:
```
Bad hash for /home/opam/.opam/repo/default/packages/num/num.1.2/files/installation-warning.patch
```
However, the file and the hash were taken verbatim from num.1.1, and the hash looks correct to me.

**Comment by kit-ty-kate** [comment]
I took a look at it and there is indeed no difference. @dra27 could you take a look at it?

**Comment by kit-ty-kate** [comment]
oh, it works on Travis.. Something to do with `.gitattributes` maybe

**Comment by dra27** [comment]
It shouldn’t be .gitattributes, but that’s not to say that it isn’t! However, I wasn’t expecting the new release to need patches / let me have a proper look (but probably tomorrow)

**Comment by xavierleroy** [comment]
The package for 1.1 had two patches, one that is now part of the 1.2 upstream distribution, the other that I kept in the package for 1.2.  It's the MD5 of the latter patch that is causing trouble, perhaps because of a LF/CRLF Windows issue.  I did look around for a `.gitignore` file in the 1.1 package but didn't see any.  Thanks for looking into this.

**Comment by yakobowski** [comment]
@kit-ty-kate can you comment on why you removed the `remove` part of the Opam file?

**Comment by dra27** [comment]
@yakobowski - opam 2 records the files installed by package commands and automatically removes them, so there’s no need for the uninstall steps (I can’t remember if I originally wrote that patch before opam 2 had that, or if I was just forgetting...)

**Comment by yakobowski** [comment]
Neat! Thanks for the explanation.

**Comment by kit-ty-kate** [comment]
I just remembered that I have now access to the server and I can take a deeper look at why it's failing.
And the reason is: .... the file is empty :/
```
-rw-r--r-- 1 opam opam 0 Jun 21 12:52 /home/opam/.opam/repo/default/packages/num/num.1.2/files/installation-warning.patch
```
I don't understand how this is the case but it is.. stay tune for more info~

**Comment by kit-ty-kate** [comment]
With some minor local twitching in the CI and some patches this is now fixed. I'll merge it as soon as possible

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Comment by liyishuai** [comment]
OPAM [complains](//travis-ci.com/coq-community/reduction-effects/jobs/210175100#L667) upon compiling `num.1.2` that:
> #=== ERROR while compiling num.1.2 ============================================#
Bad hash for /home/travis/.opam/repo/default/packages/num/num.1.2/files/installation-warning.patch

Should I refrain from upgrading `num` for now?

**Comment by kit-ty-kate** [comment]
@liyishuai I assume you have set the target for the opam-repository to be the git repository itself and not http://opam.ocaml.org ? In which case just do `opam repository remove default && opam repository add default http://opam.ocaml.org`

**Pull request merged**
