### PR TITLE
Clean-up Ketrew 1.x packages

### PR DESCRIPTION
**Pull request by smondet**

### CODE REVIEW

**Comment by smondet** [comment]
The build that failed is because the MacOSX script is not wired to handle Sqlite3:
https://github.com/smondet/trakeva#sqlite3-on-macosx

**Comment by samoht** [comment]
the last version of sqlite3 has the right configure hook to disable dynamic extensions, maybe we should set it as default on OSX? (I'm not sure what these extension bring, apart build problems) What do you think?

**Comment by smondet** [comment]
@samoht ah yes simplifying the build of Sqlite on OSX would make my life easier (every single user ends up hitting  that error!)

**Comment by samoht** [comment]
@smondet can you try adding adding some instructions to the opam files of sqlite 4.03 and 4.04 to see if that works better? (see https://github.com/mmottl/sqlite3-ocaml/blame/master/_oasis#L40)

**Comment by smondet** [comment]
@samoht I pushed this in this PR but separate commit. Can do another PR if needed.

**Comment by samoht** [comment]
Sweet, all green now. Thanks! /cc @mmottl

**Comment by mmottl** [comment]
Ok, I have reconsidered the build configuration of the `sqlite3` package.  Loadable extensions will now be off by default on Mac OS X only.  You will have to explicitly enable them on that platform if you need them.  This means that we shouldn't need to add platform-specific hacks to the OPAM file for future releases.  I hope nobody will complain about the new default.

**Pull request merged**
