### PR TITLE
Package ppx_minidebug.2.0.2

### PR DESCRIPTION
**Pull request by lukstafi**
### `ppx_minidebug.2.0.2`
Debug logs for selected functions and let-bindings
Formatted logs of let-bound values, function arguments and results; `if` and `match` branches taken. Optionally, as collapsible HTML trees with highlights.

---
* Homepage: https://github.com/lukstafi/ppx_minidebug
* Source repo: git+https://github.com/lukstafi/ppx_minidebug.git
* Bug tracker: https://github.com/lukstafi/ppx_minidebug/issues

---
:camel: Pull-request generated by opam-publish v2.3.1

### CODE REVIEW

**Comment by lukstafi** [comment]
This is a low urgency / low priority release -- it doesn't affect my other projects. Maybe it's worth taking the opportunity to make infra progress on the spurious CI failures? I'll collect what I can of the relevant information later.

**Comment by mseri** [comment]
Should I mark it as do-not-merge then?

**Comment by lukstafi** [comment]
Not `do-not-merge`, but rather `needs reporter action`.

**Comment by mseri** [comment]
It doesn't look like there is any failure due to this package honestly, besides maybe windows (but I am re-running it, the previous failure was from the CI)

**Comment by mseri** [comment]
I have merged since there seems to be nothing to do here

**Pull request merged**
