### PR TITLE
ptmap 2.0.2

### PR DESCRIPTION
**Pull request by andyli**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I think it is OK to merge; the only failure I understand is due to ocaml-4.06.0 which is not yet released.
Also, if qtest can be said to be a dependency only for tests, that would be nice.

**Comment by UnixJunkie** [comment]
in the opam file, change

     "qtest" {>= "2.2"}

to

     "qtest" {test & >= "2.2"}

**Comment by andyli** [comment]
I tried to make qtest a dependency only for testing, but there is an issue: https://travis-ci.org/ocaml/opam-repository/jobs/269052916

```
[ERROR] The compilation of ptmap failed at "obuild configure".
Processing  4/4: [ptmap: ocamlfind remove]
#=== ERROR while installing ptmap.2.0.2 =======================================#
# opam-version 1.2.2
# os           linux
# command      obuild configure
# path         /home/travis/.opam/4.05.0/build/ptmap.2.0.2
# compiler     4.05.0
# exit-code    9
# env-file     /home/travis/.opam/4.05.0/build/ptmap.2.0.2/ptmap-13376-48c407.env
# stdout-file  /home/travis/.opam/4.05.0/build/ptmap.2.0.2/ptmap-13376-48c407.out
# stderr-file  /home/travis/.opam/4.05.0/build/ptmap.2.0.2/ptmap-13376-48c407.err
### stdout ###
# Configuring ptmap-1.0...
### stderr ###
# error: missing dependency 'qcheck'
```

The cause is in the ptmap.obuild file: https://github.com/backtracking/ptmap/blob/v2.0.2/ptmap.obuild#L15-L24
...where the tests should be declared as `Test` instead of `Executable`.

**Comment by ilovezfs** [comment]
Yup, that's what I was seeing, and hacked around it by making `qcheck` a build time dep, but fixing ptmap.obuild sounds like the correct fix :)

**Comment by ilovezfs** [comment]
Also, is `qtest` even needed? I think it's only `qcheck` that it needs, no?

**Comment by andyli** [comment]
> Also, is qtest even needed?
It is used to generate unit_tests.ml, so I believe it's needed.

I submitted a PR to the upstream for the change: https://github.com/backtracking/ptmap/pull/5
I think it would be nice to release the current 2.0.2 to opam since the qtest dependency shouldn't hurt.

**Comment by ilovezfs** [comment]
:+1:

**Comment by UnixJunkie** [comment]
I sent a pull request to the opam file to @backtracking.
Concerning the test target in .obuild files, I don't know if it works (I tried and it doesn't work for me).
If you know how to update the ptmap.obuild file in this regard, please send a pull request to @backtracking (I don't maintain this software).

**Pull request merged**
