### PR TITLE
release ocplib-simplex 0.4

### PR DESCRIPTION
**Pull request by OCamlPro-Iguernlala**

### CODE REVIEW

**Comment by OCamlPro-Iguernlala** [comment]
Not sure to inderstand the failure with OCaml 4.02.3. I tried locally and did not got any issue ...

**Comment by samoht** [comment]
```
OCAMLFIND_DESTDIR=/usr/lib/ocaml/../ \
-   ocamlfind install ocplib-simplex src/ocplibSimplex.* src/*.mli META
- Makefile:115: recipe for target 'install' failed
- ocamlfind: Cannot mkdir /usr/lib/ocaml/../ocplib-simplex: Permission denied
```
that OCAMLFIND_DESTDIR variable looks a bit wrong to me.

**Comment by OCamlPro-Iguernlala** [comment]
Yes ! I just realized this. Installation fails because of system compiler

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
