### PR TITLE
Re-enable a few packages for OCaml 5.3

### PR DESCRIPTION
**Pull request by dra27**
OCaml 5.3.0~beta1 (merged in #26822) includes ocaml/ocaml#13471, which permits a few packages to be re-enabled for OCaml 5.3 (effectively reverting #26546 for coq-core, #26548 for yocaml, #26713 for prbnmcn-dagger, #26715 for mock, #26717 for MlFront_Cli, and #26719 for mopsa).

For MlFront_Cli and coq-core there are later versions which are already 5.3-compatible but note that for the others this actually enables the package for 5.3 (in yocaml's case, the later versions are unavailable on 5.3 for other reasons).

coq-core accidentally runs its configure script using the wrong profile, which is why the `build-env` for those also includes `warn-error=-a` - cf. coq/coq#19805 to ensure that wouldn't be necessary if this kind of change were made in future (or for anything else in Coq's configure program which may trigger warnings in a future version of OCaml).

Note that omake and why3 were marked as conflicting base-effects at release.

irmin and octez-internal-libs (#26709 and #26711) cannot be fixed this way as the `effect` keyword appears within a ppx (something which might want to be considered separately if more invasive keywords get added to future OCaml releases).

Overall, I think this is probably worth doing, as it increases the number of available packages. Note that these changes don't necessarily want to go upstream - the better fix upstream is to switch away from the `effect` keyword and cut a new release.

### CODE REVIEW

**Comment by dra27** [comment]
> Warning in mock.1.0.0: The package has a dune dependency without a lower bound.

Not sure that it's necessarily worth fixing, but this is a shame - the warning shouldn't trigger when the `dune-project` file actually has `lang dune 1.0` in it! (and the 4.07 lowerbounds check confirms that it does indeed work with the oldest version of Dune...)

**Comment by mseri** [comment]
These errors are there because we are building against the alpha1 still, but should we add a conflict to prevent this to happen?

- [MlFront_Cli.0.4.0~prerel7 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,MlFront_Cli.0.4.0~prerel7)
- [caisar.2.1 (failed: why3.1.7.2 failed to build)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,caisar.2.1)
- [coq-core.8.17.0 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,coq-core.8.17.0)
- [coq-core.8.17.1 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,coq-core.8.17.1)
- [coq-core.8.18.0 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,coq-core.8.18.0)
- [coq-core.8.19.0 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,coq-core.8.19.0)
- [coq-core.8.19.1 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,coq-core.8.19.1)
- [mock.1.0.0 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,mock.1.0.0)
- [mopsa.1.0 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,mopsa.1.0)
- [omake.0.10.6 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,omake.0.10.6)
- [prbnmcn-dagger.0.0.2 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,prbnmcn-dagger.0.0.2)
- [prbnmcn-dagger.0.0.3 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,prbnmcn-dagger.0.0.3)
- [prbnmcn-dagger.0.0.4 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,prbnmcn-dagger.0.0.4)
- [prbnmcn-dagger.0.0.5 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,prbnmcn-dagger.0.0.5)
- [why3.1.6.0 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,why3.1.6.0)
- [why3.1.7.0 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,why3.1.7.0)
- [why3.1.7.1 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,why3.1.7.1)
- [why3.1.7.2 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,why3.1.7.2)
- [yocaml.1.0.0 (failed: Syntax error)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/70df880ec74dfc3ffb86e25ebac3fc8b93076994/variant/compilers,5.3~alpha1,yocaml.1.0.0)

In the meantime I mark it as do not merge until we can test it on the beta1

**Comment by dra27** [comment]
Indeed - the beta1 base image has just pushed! Up to you about the conflict - I wasn't sure if that overly pedantic or not?

**Comment by mseri** [comment]
For the conflicts I did not have a strong opinion, but I think it is nice to prevent unnecessary failures when we can. Thanks a lot, it builds fine!

**Pull request merged**
