### PR TITLE
Add: uucd.15.0.0, uucp.15.0.0, uunf.15.0.0, uuseg.15.0.0

### PR DESCRIPTION
**Pull request by dbuenzli**
* Add: `uucd.15.0.0` [home](https://erratique.ch/software/uucd), [doc](https://erratique.ch/software/uucd/doc/Uucd), [issues](https://github.com/dbuenzli/uucd/issues)  
  *Unicode character database decoder for OCaml*
* Add: `uucp.15.0.0` [home](https://erratique.ch/software/uucp), [doc](https://erratique.ch/software/uucp/doc/), [issues](https://github.com/dbuenzli/uucp/issues)  
  *Unicode character properties for OCaml*
* Add: `uunf.15.0.0` [home](https://erratique.ch/software/uunf), [doc](https://erratique.ch/software/uunf/doc/Uunf), [issues](https://github.com/dbuenzli/uunf/issues)  
  *Unicode text normalization for OCaml*
* Add: `uuseg.15.0.0` [home](https://erratique.ch/software/uuseg), [doc](https://erratique.ch/software/uuseg/doc/), [issues](https://github.com/dbuenzli/uuseg/issues)  
  *Unicode text segmentation for OCaml*

---

#### `uucd` v15.0.0 2022-09-15 Zagreb

- Support for Unicode 15.0.0

---

#### `uucp` v15.0.0 2022-09-15 Zagreb

- Unicode 15.0.0 support.
- Tool `ucharinfo`: allow to query more than one character at a time.
- Tool `ucharinfo`: tool allow to search characters by name.

---

#### `uunf` v15.0.0 2022-09-15 Zagreb

- Unicode 15.0.0 support.

---

#### `uuseg` v15.0.0 2022-09-15 Zagreb

- Unicode 15.0.0 support.

---

Use `b0 cmd -- .opam.publish uucd.15.0.0 uucp.15.0.0 uunf.15.0.0 uuseg.15.0.0` to update the pull request.

### CODE REVIEW

**Comment by dbuenzli** [comment]
Except for the `extras` failures which are due to OOM. I don't think the failures are due to the new release.

**Comment by kit-ty-kate** [comment]
Thanks

**Comment by dbuenzli** [comment]
Thanks @kit-ty-kate !

**Comment by samoht** [comment]
I've got a strange error on ppc64 on the CI of [another project](https://ocaml.ci.dev/github/MagnusS/okra/commit/69d9224e7c0a3c706ae641fa512b118bcdb941bf/variant/debian-11-4.14_ppc64_opam-2.1#L507-507):

```
#=== ERROR while compiling uunf.15.0.0 ========================================#
# context     2.1.4 | linux/ppc64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-repository
# path        ~/.opam/4.14/.opam-switch/build/uunf.15.0.0
# command     ~/.opam/4.14/bin/ocaml pkg/pkg.ml build --dev-pkg false --with-uutf true --with-cmdliner true
# exit-code   1
# env-file    ~/.opam/log/uunf-1-3a54da.env
# output-file ~/.opam/log/uunf-1-3a54da.out
### output ###
# ocamlfind ocamldep -modules src/uunf_fmt.ml > src/uunf_fmt.ml.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -I src -I test -o src/uunf_fmt.cmo src/uunf_fmt.ml
# ocamlfind ocamldep -modules src/uunf_tmap.ml > src/uunf_tmap.ml.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -I src -I test -o src/uunf_tmap.cmo src/uunf_tmap.ml
# ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -o src/uunf_fmt.cmx src/uunf_fmt.ml
# ocamlfind ocamldep -modules src/uunf_tmapbool.ml > src/uunf_tmapbool.ml.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -I src -I test -o src/uunf_tmapbool.cmo src/uunf_tmapbool.ml
# ocamlfind ocamldep -modules src/uunf_tmapbyte.ml > src/uunf_tmapbyte.ml.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -I src -I test -o src/uunf_tmapbyte.cmo src/uunf_tmapbyte.ml
# ocamlfind ocamldep -modules src/uunf_data.ml > src/uunf_data.ml.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -I src -I test -o src/uunf_data.cmo src/uunf_data.ml
# ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -o src/uunf_tmap.cmx src/uunf_tmap.ml
# ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -o src/uunf_tmapbool.cmx src/uunf_tmapbool.ml
# ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -o src/uunf_tmapbyte.cmx src/uunf_tmapbyte.ml
# ocamlfind ocamldep -modules src/uunf.ml > src/uunf.ml.depends
# ocamlfind ocamldep -modules src/uunf.mli > src/uunf.mli.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -I src -I test -o src/uunf.cmi src/uunf.mli
# ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -o src/uunf_data.cmx src/uunf_data.ml
# + ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -o src/uunf_data.cmx src/uunf_data.ml
# ocamlopt.opt got signal and exited
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'src/uunf.a' 'src/uunf.cmxs' 'src/uunf.cmxa' 'src/uunf.cma'
#      'src/uunf.cmx' 'src/uunf.cmi' 'src/uunf.mli' 'src/uunf_data.cmx'
#      'src/uunf_tmapbyte.cmx' 'src/uunf_tmapbool.cmx' 'src/uunf_tmap.cmx'
#      'src/uunf_fmt.cmx' 'src/uunf_string.a' 'src/uunf_string.cmxs'
#      'src/uunf_string.cmxa' 'src/uunf_string.cma' 'src/uunf_string.cmx'
#      'src/uunf_string.cmi' 'src/uunf_string.mli' 'test/unftrip.native'
#      'doc/index.mld' 'DEVEL.md' 'test/examples.ml']: exited with 10
```

**Comment by anmonteiro** [comment]
@samoht could it be a stack problem? https://github.com/ocaml/ocaml/issues/9839

**Comment by dbuenzli** [comment]
> I've got a strange error on ppc64 on the CI of [another project](https://ocaml.ci.dev/github/MagnusS/okra/commit/69d9224e7c0a3c706ae641fa512b118bcdb941bf/variant/debian-11-4.14_ppc64_opam-2.1#L507-507):

What about following the advice given there ? 

```
<><> uunf.15.0.0 troubleshooting ><><><><><><><><><><><><><><><><><><><><><><><>
=> If the build fails with "ocamlopt.opt got signal and exited", issue 'ulimit -s unlimited' and retry.
```

**Pull request merged**
