### PR TITLE
Mirage os shim.3.0.1

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by mseri** [comment]
I am not sure what's wrong with camelus but the rest seems fine. Let's wait for Travis

**Comment by kit-ty-kate** [comment]
@mseri I don't know either. cc @AltGr. I'll run the 2.0 version locally in the meantime (it'll give some unrelated warnings but they can be ignored)

**Comment by hannesm** [comment]
uhm, @camelus are you now on opam-2.0? :/  I agree with the warnings/errors, but I thought `master` is still using opam-1.2

**Comment by kit-ty-kate** [comment]
@hannesm no it's not but the only way for me to redo camelus checks manually is to use the 2.0 tool (it's not simply possible with the 1.2 version)

Checks are fine and I (or @mseri) will merge it as soon as Travis builds finish.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
