### PR TITLE
odoc 1.1.1

### PR DESCRIPTION
**Pull request by trefis**

### CODE REVIEW

**Comment by dbuenzli** [comment]
It seems the errors are due to `menhir` not dowloading: 

```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - menhir.20170509
`` `

**Comment by dbuenzli** [comment]
The download error persists travis is fine.

**Comment by dbuenzli** [comment]
I think this can be merged.

**Comment by avsm** [comment]
i've restarted some of the failing jobs

**Comment by dbuenzli** [comment]
Remaining failures have no logs (?).

**Comment by avsm** [comment]
GitHub is having a major service outage, so webhooks are wonky.

**Pull request merged**
