### PR TITLE
[new release] trace (4 packages) (0.6)

### PR DESCRIPTION
**Pull request by c-cube**
A stub for tracing/observability, agnostic in how data is collected

- Project page: <a href="https://github.com/c-cube/ocaml-trace">https://github.com/c-cube/ocaml-trace</a>

##### CHANGES:

- add `ppx_trace` for easier instrumentation.
  * `let%trace span = "foo" in …` will enter a scope `span` named "foo"
  * `let%trace () = "foo" in …` will enter a scope named "foo" with a hidden name
- add `trace-fuchsia` backend, which produces traces in the binary format
    of [fuchsia](https://fuchsia.dev/fuchsia-src/reference/tracing/trace-format).
    These traces are reasonably efficient to produce (~60ns per span on my machines)
    and reasonably compact on disk, at least compared to the TEF backend.

### CODE REVIEW

**Comment by c-cube** [comment]
… do we have a `config-littleendian` package in opam? :joy:

**Comment by mseri** [comment]
Should we mark it unavailable on s390x?

**Comment by c-cube** [comment]
Sure, yeah. In general it assumes little endian arch.

**Comment by c-cube** [comment]
This should be ready now!

**Pull request merged**
