### PR TITLE
[new release] eqaf (0.3)

### PR DESCRIPTION
**Pull request by dinosaure**
Constant-time equal function on string

- Project page: <a href="https://github.com/mirage/eqaf">https://github.com/mirage/eqaf</a>
- Documentation: <a href="https://mirage.github.io/eqaf/">https://mirage.github.io/eqaf/</a>

##### CHANGES:

- Provide `Eqaf_bigstring`
- Provide `Eqaf_cstruct`
- New check tool and delete any dependencies on `eqaf` package (@dinosaure, @hannesm, @cfcs)

### CODE REVIEW

**Comment by dinosaure** [comment]
Ok, so errors occur because linear regression on time needed to compute `equal` function is too noisy in CI.

**Comment by cfcs** [comment]
@dinosaure would it help to increase the amount of samples, or do you need to turn off that regression test?

**Comment by dinosaure** [comment]
@cfcs I believe we need to turn off tests in some contexts

**Comment by avsm** [comment]
We'll work on improving the opam ci to support isolation for tests like this, but this is fine to merge now

**Pull request merged**
