### PR TITLE
cohttp-lwt{,-jsoo}: add missing sexplib dependency

### PR DESCRIPTION
**Pull request by mseri**
Discovered by https://github.com/ocaml/opam-repository/pull/12910

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>

### CODE REVIEW

**Comment by mseri** [comment]
The failure for `calculon-web.0.2` has nothing to do with this PR. Travis osx failure is the usual one

**Comment by kit-ty-kate** [comment]
Would there be a simpler fix to just constrain `ppx_sexp_conv` to `< "v0.11.0"` in `cohttp-lwt.1.1.1` as `v0.11.0` now depends over `sexplib0` and not `sexplib` anymore?

**Comment by mseri** [comment]
Yes but this other fix is forward and backward compatible

**Comment by kit-ty-kate** [comment]
well if it doesn't work in the current state it's not really forward compatibility

**Comment by mseri** [comment]
Why not? With this fix, the package works independently of the version of ppx_sexp_conv. Also I believe this fix is more correct, as both packages are explicitly calling Sexplib functions but not declaring it as a delendency

**Comment by kit-ty-kate** [comment]
Well, in the current state the package doesn't compile so it's not really forward compatibility.
Plus I'm not very fond of having more patches added to the repository. Even more if it's an old version we're fixing.

**Comment by mseri** [comment]
We are disagreeing on terminology. Anyways it's not such a big deal. I have tested it locally and the issue is that sexplib was linked transitively via uri that was coming transitively from cohttp. From the test I have done seems that the right fix is to add a bound to cohttp.

**Comment by mseri** [comment]
Looks like it wiorked

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
