### PR TITLE
Octez 20.1

### PR DESCRIPTION
**Pull request by killian-delarue**
Packages for Octez v20.1

### CODE REVIEW

**Comment by mseri** [comment]
There are some linking errors remaining in tests, mosst of the rest seems a ci issue. Is this ready for review?

**Comment by killian-delarue** [comment]
> There are some linking errors remaining in tests, mosst of the rest seems a ci issue. Is this ready for review?

It is ready for review

**Comment by raphael-proust** [comment]
@killian-delarue you might want to either fix the build on windows or mark the package as not available there. The windows CI fails with some basic file operation.

**Comment by raphael-proust** [comment]
made all the file `available: os != "win32"`

**Pull request merged**
