### PR TITLE
2 packages from INRIA/zelus at 2.2

### PR DESCRIPTION
**Pull request by gbdrt**
This pull-request concerns:
-`zelus.2.2`: A synchronous language with ODEs
-`zelus-gtk.2.2`: Zelus GTK library

---
* Homepage: http://zelus.di.ens.fr
* Source repo: git+https://github.com/INRIA/zelus.git
* Bug tracker: https://github.com/INRIA/zelus/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by mseri** [comment]
In both packages the 'license' field is not present. Can you add the licenses using an SPDX-compatible identifier: https://spdx.org/licenses/?

There is a lower-bound failure:
```
#       ocamlc compiler/.zlcompilerlibs.objs/byte/match2condition.{cmi,cmo,cmt}
# File "compiler/verif/match2condition.ml", line 137, characters 2-796:
# 137 | ..match desc with
# 138 |   | Elocal _ | Eglobal _ | Econst _ | Econstr0 _ | Elast _ -> e
# 139 |   | Eapp(app, e_arg, e_list) ->
# 140 |       { e with e_desc = Eapp(app, expression e_arg,
# 141 |                              List.map expression e_list) }
# ...
# 150 |   | Etuple(e_list) ->
# 151 |       { e with e_desc = Etuple(List.map expression e_list) }
# 152 |   | Econstr1 _ | Ematch _ | Eseq _ | Elet _ | Eperiod _ | Eblock _ | Epresent _
# 153 |     -> assert false
# Warning 8: this pattern-matching is not exhaustive.
# Here is an example of a case that is not matched:
# Erecord_with (_, _)
#       ocamlc compiler/.zlcompilerlibs.objs/byte/zlus2lmm.{cmi,cmo,cmt}
# File "compiler/verif/zlus2lmm.ml", line 189, characters 2-805:
# 189 | ..match desc with
# 190 |   | Elocal(id) -> Llocal(id)
# 191 |   | Eglobal { lname = lid } -> Lglobal(lid)
# 192 |   | Econst(im) -> Lconst(immediate im)
# 193 |   | Econstr0(lid) -> Lconstr0(lid)
# ...
# 206 |   | Etypeconstraint(e, _) -> expression ck e
# 207 |   | Etuple(e_list) -> Ltuple(List.map (expression ck) e_list)
# 208 |   | Ematch _ | Eseq _ | Elet _
# 209 |   | Eperiod _ | Eblock _ | Epresent _ -> assert false
# Warning 8: this pattern-matching is not exhaustive.
# Here is an example of a case that is not matched:
# Erecord_with (_, _)
# File "compiler/verif/zlus2lmm.ml", line 298, characters 11-71:
# 298 | let kind = function | S | AS | A | AD -> A | D -> D | C -> assert false
#                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Warning 8: this pattern-matching is not exhaustive.
# Here is an example of a case that is not matched:
# P
#     ocamlopt compiler/.zlcompilerlibs.objs/native/match2condition.{cmx,o}
# File "compiler/verif/match2condition.ml", line 137, characters 2-796:
# 137 | ..match desc with
# 138 |   | Elocal _ | Eglobal _ | Econst _ | Econstr0 _ | Elast _ -> e
# 139 |   | Eapp(app, e_arg, e_list) ->
# 140 |       { e with e_desc = Eapp(app, expression e_arg,
# 141 |                              List.map expression e_list) }
# ...
# 150 |   | Etuple(e_list) ->
# 151 |       { e with e_desc = Etuple(List.map expression e_list) }
# 152 |   | Econstr1 _ | Ematch _ | Eseq _ | Elet _ | Eperiod _ | Eblock _ | Epresent _
# 153 |     -> assert false
# Warning 8: this pattern-matching is not exhaustive.
# Here is an example of a case that is not matched:
# Erecord_with (_, _)
#     ocamlopt compiler/.zlcompilerlibs.objs/native/zlus2lmm.{cmx,o}
# File "compiler/verif/zlus2lmm.ml", line 189, characters 2-805:
# 189 | ..match desc with
# 190 |   | Elocal(id) -> Llocal(id)
# 191 |   | Eglobal { lname = lid } -> Lglobal(lid)
# 192 |   | Econst(im) -> Lconst(immediate im)
# 193 |   | Econstr0(lid) -> Lconstr0(lid)
# ...
# 206 |   | Etypeconstraint(e, _) -> expression ck e
# 207 |   | Etuple(e_list) -> Ltuple(List.map (expression ck) e_list)
# 208 |   | Ematch _ | Eseq _ | Elet _
# 209 |   | Eperiod _ | Eblock _ | Epresent _ -> assert false
# Warning 8: this pattern-matching is not exhaustive.
# Here is an example of a case that is not matched:
# Erecord_with (_, _)
# File "compiler/verif/zlus2lmm.ml", line 298, characters 11-71:
# 298 | let kind = function | S | AS | A | AD -> A | D -> D | C -> assert false
#                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Warning 8: this pattern-matching is not exhaustive.
# Here is an example of a case that is not matched:
# P
```
Do you know where it may come from?

**Comment by gbdrt** [comment]
Thanks for looking at this.

The Zélus compiler is distributed under the terms of the Inria Non-Commercial License Agreement.
I did not find this one in the https://spdx.org/licenses/.
Is it ok to use Inria-NCLA?

Apparently the lower-bound failure is due to `menhir: unknown option '--infer-write-query'` but I cannot reproduce it.
Do you have any suggestion to fix this?
Do we need to explicitly exclude some menhir versions?

**Comment by mseri** [comment]
I think it should be enough to figure out when that option was added to menhir and add that as a lower bound on the version

**Comment by mseri** [comment]
Looks good now. Thanks!
Feel free to announce the release on the discuss.ocaml.org forum. We have a community category and an annoucement tag for this purpose

**Comment by gbdrt** [comment]
Thanks a lot for your help @mseri!

**Pull request merged**
