### PR TITLE
Fix omake installation

### PR DESCRIPTION
**Pull request by rgrinberg**
Don't use the broken omake.install file

Sorry for the broken PR previously.

cc @avsm

### CODE REVIEW

**Comment by avsm** [comment]
odd failure....

```
#=== ERROR while installing omake.0.10.1 ======================================#
# opam-version 1.2.2
# os           linux
# command      make install
# path         /home/travis/.opam/system/build/omake.0.10.1
# compiler     system (4.02.3)
# exit-code    2
# env-file     /home/travis/.opam/system/build/omake.0.10.1/omake-7882-dc6e87.env
# stdout-file  /home/travis/.opam/system/build/omake.0.10.1/omake-7882-dc6e87.out
# stderr-file  /home/travis/.opam/system/build/omake.0.10.1/omake-7882-dc6e87.err
### stdout ###
# [...]
# *** omake: finished reading OMakefiles (0.03 sec)
# *** omake: done (0.19 sec, 0/245 scans, 0/470 rules, 0/170 digests)
# ocaml build.ml -install OCAML="ocaml"
# src/main/prelim_omake '--dotomake' '.omake' '--force-dotomake' 'install' 'OCAML=ocaml'
# *** omake: reading OMakefiles
# *** omake: finished reading OMakefiles (0.03 sec)
# - build src/main <install>
# + Shell.cp(-f -m 555 omake /usr/bin/)
# *** omake: 1184/1187 targets are up to date
# *** omake: failed (0.18 sec, 0/245 scans, 1/457 rules, 0/169 digests)
### stderr ###
# *** omake error:
#    File src/main/OMakefile: line 52, characters 2-33
#    open(/usr/bin/omake): Permission denied
# *** omake: targets were not rebuilt because of errors:
#    <phony <src/main/install>>
# Command exited with error: src/main/prelim_omake '--dotomake' '.omake' '--force-dotomake' 'install' 'OCAML=ocaml'
# make: *** [install] Error 1
```

**Comment by rgrinberg** [comment]
Yes, I'm very confused about this one as well. I've checked that omake installs
itself to the switch local directory like it should on 4.02.3 so this stumps me.

**Comment by camlspotter** [comment]
My packages using omake fail to build recently.  Apparently some files are missing.  Does this relate with failures?:

```
# *** omake error:
#    File Omake_builtin: line 0, characters 0-0
#    include file Pervasives not found in OMAKEPATH
#       (OMAKEPATH[] = "." : Sequence /home/travis/.opam/4.04.0/lib/omake : Dir)
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=/home/travis/.opam/4.04.0\"' terminated with error code 123")
```

**Comment by rgrinberg** [comment]
Yes @camlspotter this one was my bad. This PR should fix it but i'm unable to reproduce this travis issue on 4.02.3. Perhaps a restart of that travis build is in order?

**Comment by camlspotter** [comment]
Thanks @rgrinberg.  The install tries to copy `omake` binaries to `/usr/bin`.  Should we give `./configure` a proper `--prefix` ?

**Comment by rgrinberg** [comment]
It installed omake in the right place for me even without setting it. But I'll give it a try anyway here.

**Comment by yallop** [comment]
The build's succeeding now, but it seems that files are being left behind when `omake` is uninstalled:

```
[WARNING] Directory /home/travis/.opam/4.04.0/lib/omake is not empty, not
          removing
```

**Comment by avsm** [comment]
merging as this improves the state of the repo even with stray files

**Comment by camlspotter** [comment]
Sorry, the problem still persists and all the packages using `omake` fails to install themselves.  We should resign `omake.0.10.1`.

**Pull request merged**
