### PR TITLE
added conf-dbm

### PR DESCRIPTION
**Pull request by UnixJunkie**
inspired by the configure file from dbm

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Well now that we have https://github.com/ocaml/dbm/pull/5 merged I would avoid requesting for the compat version of gdbm. The difference is really messy and quite impossible to deal with correctly it seems.

**Comment by UnixJunkie** [comment]
What is the C header file you want to rely on then?
You might know better than me what this conf- package should be, please feel free to edit it.

**Comment by kit-ty-kate** [comment]
`libgdbm-dev` should be sufficient here as on debian <= 9 it is the equivalent of debian >= 10's `libgdbm-compat-dev`. `dbm.1.2` now support both however previous versions does not support debian >= 10's `libgdbm-dev` but I think that's ok

**Comment by UnixJunkie** [comment]
ok, thanks for the edits

**Comment by kit-ty-kate** [comment]
Ok, the failure here comes from the fact that `ndbm.h` is not installed in the debian package.
Instead there is `dbm.h` (not to be used here I think), `gdbm-ndbm.h` and `gdbm.h`
See: https://packages.debian.org/stretch/amd64/libgdbm-dev/filelist

**Comment by UnixJunkie** [comment]
I knew it:
````
$ locate ndbm.h
/usr/include/gdbm-ndbm.h
/usr/include/ndbm.h
$ dpkg -S /usr/include/ndbm.h
libgdbm-compat-dev: /usr/include/ndbm.h
````
(that's on a debian buster/sid)

**Comment by UnixJunkie** [comment]
So, how do we go from here? I add back the libgdbm-compat-dev that was in there for debian and Ubuntu?

**Comment by kit-ty-kate** [comment]
Well it depends. Do you want to test for \*a\* dbm library or specifically ndbm ?

**Comment by UnixJunkie** [comment]
I changed the test file to use gdbm, finally. I guess that's what most people might use.
Should we run the produced exe, by the way?
I think that most opam conf-* packages are happy if they can compile and link against the desired library.

**Comment by UnixJunkie** [comment]
All CI tests are OK, what a rare event!
Sorry for the rather piggy build section in the opam file.
If someone has a proposal to do this in a nicer way, please feel free to contribute it.

**Comment by kit-ty-kate** [comment]
Awesome ! Thanks a lot ! Sorry for the delay.

**Pull request merged**
