### PR TITLE
Octez 19.0 packages

### PR DESCRIPTION
**Pull request by killian-delarue**
Packages for Octez v19.0

### CODE REVIEW

**Comment by raphael-proust** [comment]
There are some CI failures that should be fixable:

- Add `x-ci-accept-failures: [ "alpine" "macos-homebrew" ]` to `tezos-rust-libs` package
- It seems like the `conf-libev` package is broken for oraclelinux? Maybe the package needs a fix or maybe it needs to be marked as broken there. Not sure.
- The package hacl-star-raw seems broken on freebsd. Although I'm not sure if it should be marked as "unavailable" or "x-ci-accept-failures" because it might build fine with a custom dev setup.

**Comment by raphael-proust** [comment]
There are some build failures in some revdeps that seem to suggest some other packages are broken. I don't think we should add changes to this PR, but we should probably fix or more likely remove those old packages: `tezos-sapling.{11.0,11.1,12.0,12.3}`

See:  
[tezos-sapling.11.0 (failed: too many arguments to function 'librustzcash_init_zksnark_params')](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/ee13496feab6ab547c0765277333a38a47b8b292/variant/compilers,4.14,tezos-rust-libs.1.6,revdeps,tezos-sapling.11.0)  
[tezos-sapling.11.1 (failed: too many arguments to function 'librustzcash_init_zksnark_params')](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/ee13496feab6ab547c0765277333a38a47b8b292/variant/compilers,4.14,tezos-rust-libs.1.6,revdeps,tezos-sapling.11.1)  
[tezos-sapling.12.0 (failed: too many arguments to function 'librustzcash_init_zksnark_params')](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/ee13496feab6ab547c0765277333a38a47b8b292/variant/compilers,4.14,tezos-rust-libs.1.6,revdeps,tezos-sapling.12.0)  
[tezos-sapling.12.3 (failed: too many arguments to function 'librustzcash_init_zksnark_params')](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/ee13496feab6ab547c0765277333a38a47b8b292/variant/compilers,4.14,tezos-rust-libs.1.6,revdeps,tezos-sapling.12.3)

Also, this CI run is much more noisy because of random system failures (no space left on device, cancelled, etc.) which we didn't have much on in the last run.

**Comment by raphael-proust** [comment]
@mseri I think this is ready to merge

**Comment by mseri** [comment]
Thanks all

**Pull request merged**
