### PR TITLE
[new release] macaddr and ipaddr (3.1.0)

### PR DESCRIPTION
**Pull request by avsm**
CHANGES:

* Do not leak a `Not_found` exception when parsing `[:`
  in IPv6 and instead raise `Parse_error` as other errors
  do (found by fuzz testing in mirage/ocaml-ipaddr#84 by @dinosaure)
* Install automatic toplevel printers for the Ipaddr
  types via `[@@ocaml.toplevel_printer]`. This enables
  utop to automatically install the printers (@avsm)

### CODE REVIEW

**Comment by mseri** [comment]
Are macaddr tests using ipaddr? If so maybe they should target ipaddr instead!
```
#=== ERROR while compiling macaddr.3.1.0 ======================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.1 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-base-compiler.4.07.1/.opam-switch/build/macaddr.3.1.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p macaddr -j 1
# exit-code   1
# env-file    ~/.opam/log/macaddr-25850-cd2a5c.env
# output-file ~/.opam/log/macaddr-25850-cd2a5c.out
### output ###
# File "lib_test/dune", line 4, characters 12-18:
# 4 |  (libraries ipaddr oUnit ipaddr.sexp macaddr.sexp))
#                 ^^^^^^
# Error: Library "ipaddr" not found.
# Hint: try: dune external-lib-deps --missing -j 1 -p macaddr @runtest
```

**Comment by kit-ty-kate** [comment]
wouldn't this be a circular dependency?

**Comment by mseri** [comment]
If it is just in the test library (as it currently seem), one could simply offload all testing to ipaddr, in that way I don’t think it is circular

**Comment by kit-ty-kate** [comment]
fair enough

**Comment by avsm** [comment]
I'll fix this upstream; have disabled the macaddr tests in this release in opam for now

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
