### PR TITLE
[new release] eqaf (0.5)

### PR DESCRIPTION
**Pull request by dinosaure**
Constant-time equal function on string

- Project page: <a href="https://github.com/mirage/eqaf">https://github.com/mirage/eqaf</a>
- Documentation: <a href="https://mirage.github.io/eqaf/">https://mirage.github.io/eqaf/</a>

##### CHANGES:

- Delete `min` and use `<>` operator to compare length on `equal` function
- Implementation of `compare_{be,le}{,with_len}` function (@cfcs, @hannesm, @dinosaure)
- Test on `compare` function (@dinosaure)
- Unit test on `compare` (@dinosaure)
- Fuzz test on `compare` (@dinosaure)
- Documentation (@dinosaure, @cfcs)

### CODE REVIEW

**Comment by mseri** [comment]
For some reasons it is failing on Travis for all recent versions of ocaml (4.06, 4.07, 4.08) with
```
[ERROR] No solution for eqaf.0.5: The following dependencies couldn't be met:
          - eqaf → crowbar → xmldiff → xmlm < 1.3.0 → ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
```

**Comment by dinosaure** [comment]
Hmmhmm, indeed `xmlm.1.2.0` requires `< ocaml.4.06.0` and these deps appear with `(with-test}` flag because we want to compile with `opam install -t eqaf`. I can not reproduce it on my side where `opam install -t eqaf` wants to install only `crowbar` - I don't understand OPAM looks into `crowbar`'s deps for testing ...

**Comment by mseri** [comment]
I have disabled the tests on ocaml `>= 4.06.0` for now. I thought opam was fixed to avoid recursive test-dependencies installation (ping @rjbou)

**Comment by mseri** [comment]
@kit-ty-kate do you understand why opam on Travis is trying to install the test dependencies of the test dependencies even now that the tests are disabled?

**Comment by kit-ty-kate** [comment]
@mseri yes, simply because the test dependencies are still listed and opam is trying to get them. There is no way of "disabling" tests in the sense. You can only disable actions (and you did)

**Comment by kit-ty-kate** [comment]
The recursive test problem is described in https://github.com/ocaml/opam-depext/issues/121

**Comment by kit-ty-kate** [comment]
It should be good now. The failures in Travis are somewhat irrelevant

**Comment by dinosaure** [comment]
Thanks!

**Pull request merged**
