### PR TITLE
+mirage-unix.3.0.7

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
The xen error thingy looks unrelated (but I might be wrong) but do you have any clues about this one by any chance ?
```
#=== ERROR while compiling mirage-fs-lwt.1.1.1 ================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.05.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.05.0/.opam-switch/build/mirage-fs-lwt.1.1.1
# command              ~/.opam/4.05.0/bin/jbuilder build -p mirage-fs-lwt -j 71
# exit-code            1
# env-file             ~/.opam/log/mirage-fs-lwt-18-ae6277.env
# output-file          ~/.opam/log/mirage-fs-lwt-18-ae6277.out
### output ###
#     ocamldep lwt/mirage_fs_lwt.dependsi.ocamldep-output
#     ocamldep lwt/mirage_fs_lwt.depends.ocamldep-output
#       ocamlc lwt/mirage_fs_lwt.{cmi,cmti}
#       ocamlc lwt/mirage_fs_lwt.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/opam/.opam/4.05.0/lib/bytes -I /home/opam/.opam/4.05.0/lib/cstruct -I /home/opam/.opam/4.05.0/lib/fmt -I /home/opam/.opam/4.05.0/lib/lwt -I /home/opam/.opam/4.05.0/lib/mirage-device -I /home/opam/.opam/4.05.0/lib/mirage-fs -I /home/opam/.opam/4.05.0/lib/mirage-kv -I /home/opam/.opam/4.05.0/lib/mirage-kv-lwt -I /home/opam/.opam/4.05.0/lib/ocaml -I /home/opam/.opam/4.05.0/lib/ocplib-endian -I /home/opam/.opam/4.05.0/lib/result -I /home/opam/.opam/4.05.0/lib/sexplib -I /home/opam/.opam/4.05.0/lib/sexplib/0 -I /home/opam/.opam/4.05.0/lib/uchar -no-alias-deps -I lwt -o lwt/mirage_fs_lwt.cmo -c -impl lwt/mirage_fs_lwt.ml)
# File "lwt/mirage_fs_lwt.ml", line 1:
# Error: The files /home/opam/.opam/4.05.0/lib/mirage-kv/mirage_kv.cmi
#        and lwt/mirage_fs_lwt.cmi make inconsistent assumptions
#        over interface Mirage_kv
#     ocamlopt lwt/mirage_fs_lwt.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlopt.opt -w -40 -g -I /home/opam/.opam/4.05.0/lib/bytes -I /home/opam/.opam/4.05.0/lib/cstruct -I /home/opam/.opam/4.05.0/lib/fmt -I /home/opam/.opam/4.05.0/lib/lwt -I /home/opam/.opam/4.05.0/lib/mirage-device -I /home/opam/.opam/4.05.0/lib/mirage-fs -I /home/opam/.opam/4.05.0/lib/mirage-kv -I /home/opam/.opam/4.05.0/lib/mirage-kv-lwt -I /home/opam/.opam/4.05.0/lib/ocaml -I /home/opam/.opam/4.05.0/lib/ocplib-endian -I /home/opam/.opam/4.05.0/lib/result -I /home/opam/.opam/4.05.0/lib/sexplib -I /home/opam/.opam/4.05.0/lib/sexplib/0 -I /home/opam/.opam/4.05.0/lib/uchar -no-alias-deps -I lwt -o lwt/mirage_fs_lwt.cmx -c -impl lwt/mirage_fs_lwt.ml)
# File "lwt/mirage_fs_lwt.ml", line 1:
# Error: The files /home/opam/.opam/4.05.0/lib/mirage-kv/mirage_kv.cmi
#        and lwt/mirage_fs_lwt.cmi make inconsistent assumptions
#        over interface Mirage_kv
```

**Comment by hannesm** [comment]
i suspect this is the same issue as in https://github.com/ocaml/opam-repository/pull/11490#issuecomment-368997696

**Comment by hannesm** [comment]
I added more constraints in #11584

**Comment by jpdeplaix** [comment]
All green after rebuilding the revdeps.
Thanks a lot !!

**Pull request merged**
