### PR TITLE
hardcaml v1.2.0 and friends

### PR DESCRIPTION
**Pull request by andrewray**
updated: hardcaml, hardcaml-waveterm, hardcaml-examples, hardcaml-reedsolomon, hardcaml-vpi, hardcaml-llvmsim

new packages: hardcaml-framework, hardcaml-bloop, hardcaml-affirm, hardcaml-yosys, sattools

### CODE REVIEW

**Comment by andrewray** [comment]
ci/datakit/1 fails when executing

```
"curl -L \"https://gist.githubusercontent.com/jpdeplaix/53a7f91155e9d98dcfb18afcd1d6c529/raw\" | sh -ex -" failed
```

in order to install llvm.  I note that

```
andyman@brumble:~/dev/github/opam $ curl -L \"https://gist.githubusercontent.com/jpdeplaix/53a7f91155e9d98dcfb18afcd1d6c529/raw\"
curl: (1) Protocol ""https" not supported or disabled in libcurl
```

However, without escaping the quotes

```
andyman@brumble:~/dev/github/opam $ curl -L "https://gist.githubusercontent.com/jpdeplaix/53a7f91155e9d98dcfb18afcd1d6c529/raw"
#!/bin/sh

sudo add-apt-repository 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.9 main'
wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

sudo apt-get update

sudo apt-get install llvm-3.9-dev
```

**Comment by andrewray** [comment]
On the travis test the linux versions are (mainly) failing because of llvm with

```
# CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
#   CMake 3.4.3 or higher is required.  You are running version 3.2.2
```

This is while building the ocaml llvm binding.  Apart from that, as far as I can tell the llvm-3.9 library has been installed and ocaml llvm.3.9 binding is being selected which is all OK here.

On OSX the failure is because it is selecting llvm-3.9 but that doesn't include a `depext` to build it (there doesn't seem to be a llvm39 brew package thingy - although the llvm brew package is actually llvm39 I think - not that I can actually install it here as I think it conflicts with the system version - ho-hum).

**Comment by avsm** [comment]
I'll fix the llvm failures separately -- we need to rip out the source-based depext and generalise it to cover more distros.  The rest of the CI is very green, so this goes in now!

**Comment by andrewray** [comment]
Awesome thanks!

**Pull request merged**
