### PR TITLE
add ncurses-dev to ocamlfind depext

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
The two allowed failures that failed: ocaml compiler failed to build then some xquartz download timed out.

**Comment by samoht** [comment]
Is this a new dependency? I don't remember seeing an error related to that before and I don't see where it is used in findlib source code.

**Comment by UnixJunkie** [comment]
I removed ncurses-dev on my machine:

    sudo apt-get remove libncurses5-dev
    opam remove ocamlfind
    opam install ocamlfind

results in https://gist.github.com/UnixJunkie/4f3cffde70817a2421bb

**Comment by UnixJunkie** [comment]
I observed this on a freshly installed machine at home with few packages.

**Comment by samoht** [comment]
Ha, this is an issue with `ocaml` then. Not sure where to put that depext, I guess ocamlfind is alright.

**Comment by samoht** [comment]
@gasche why do ocaml needs `-lcurses` to link?

**Comment by UnixJunkie** [comment]
I just sent a quick fix, I did not dig further, sorry.

**Comment by gasche** [comment]
The OCaml toplevel uses the Terminfo database, and the flag `HAS_TERMCAP` is set by `./configure` which seems to check for termcap-providing libraries on the system (including `-lcurses` and `-lncurses`). [See the configure code here](https://github.com/ocaml/ocaml/blob/c65e735e8c71e18d8ab6a622bc098dee69ba545e/configure#L1024-L1035).

**Comment by samoht** [comment]
ok thanks. I guess that ocamlfind needs `lcurses` to build its toplevel support.

**Pull request merged**
