### PR TITLE
Package ocaml-http.0.1.6

### PR DESCRIPTION
**Pull request by sacerdot**
### `ocaml-http.0.1.6`
Library freely inspired from Perl's HTTP::Daemon module

---
* Homepage: https://github.com/sacerdot/ocaml-http
* Source repo: git+https://github.com/sacerdot/ocaml-http.git
* Bug tracker: https://github.com/sacerdot/ocaml-http/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by sacerdot** [comment]
Hi,

I am the new upstream maintainer of ocaml-http. I moved the project repository from ocamlforge to github and I have made a new release that works with recent ocaml versions (the previous one failed because of immutable strings, see https://github.com/ocaml/opam-repository/pull/12679).

**Comment by sacerdot** [comment]
> Could you also return the fix I just made upstream?

sure, I am gonna apply both changes now

**Comment by kit-ty-kate** [comment]
Seems like camlp4 was necessary
```
#=== ERROR while compiling ocaml-http.0.1.6 ===================================#
# context              2.0.2 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/sacerdot/ocaml-http/archive/v0.1.6.tar.gz)
# path                 ~/.opam/4.07/.opam-switch/build/ocaml-http.0.1.6
# command              /usr/bin/make all
# exit-code            2
# env-file             ~/.opam/log/ocaml-http-20-fd93a7.env
# output-file          ~/.opam/log/ocaml-http-20-fd93a7.out
### output ###
# ocamlfind ocamlc  -pp camlp4o -package "unix str pcre netstring" -c http_types.mli
# sh: 1: camlp4o: not found
# File "http_types.mli", line 1:
# Error: Error while running external preprocessor
# Command line: camlp4o 'http_types.mli' > /tmp/ocamlpp9d39cf
# 
# Makefile:72: recipe for target 'http_types.cmi' failed
# make: *** [http_types.cmi] Error 2
```

**Comment by sacerdot** [comment]
It was not, but it was still invoked by the Makefile. I have run all the tests and now it works without. I pushed again, hopefully the last time :-)

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
