### PR TITLE
add coqide.8.17.0

### PR DESCRIPTION
**Pull request by palmskog**
Followup to #23584.

cc: @MSoegtropIMC @Zimmi48

### CODE REVIEW

**Comment by palmskog** [comment]
The error on OCaml 5.0 is seemingly due to the (transitive) dependency library Cairo:
```
# /home/opam/.opam/5.0/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_stubs.c:1821: undefined reference to `alloc_custom'
# /usr/bin/ld: /home/opam/.opam/5.0/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/opam/.opam/5.0/.opam-switch/build/cairo2.0.6/_build/default/src/cairo_stubs.c:1822: more undefined references to `alloc_custom' follow
# collect2: error: ld returned 1 exit status
# File "caml_startup", line 1:
# Error: Error during linking (exit code 1)
```
I don't think we can do much about this in the package here.

**Comment by MSoegtropIMC** [comment]
For Coq Platform this is not an issue since I am anyway using OCaml 4.14, so I would suggest to merge this with OCaml restricted to <5~. I expect that the overlap of OCaml 5 users and CoqIDE-only users is quite small.

**Comment by palmskog** [comment]
@MSoegtropIMC but the problem is here not with the CoqIDE package. I'd argue the `coqide` package here should be kept compatible with OCaml 5. I think the Cairo problem is restricted to only some platform (macOS?).

**Comment by MSoegtropIMC** [comment]
Just to make sure I get this correctly: the issue is that the OCaml wrapper for cairo is in general OCaml 5 compatible, but on some platforms not?

**Comment by MSoegtropIMC** [comment]
> I think we just specify "cairo2" { >= "0.6.4" } and be done with it?

Sounds reasonable to me. I would prefer this general restriction over having this restriction only for OCaml 5 so that we don't have unnecessary deviations which might lead to hard to find bugs.

I guess you report at the same time upstream that cairo < 0.6.4 is incompatible with OCaml 5?

**Comment by palmskog** [comment]
> I guess you report at the same time upstream that cairo < 0.6.4 is incompatible with OCaml 5?

I don't know whether this is specific to how Coq indirectly uses cairo2 or it's a general issue. So we could add the constraint into the Coq repo, but no cycles here to investigate the root cause.

**Comment by palmskog** [comment]
Now the only failures are a mysterious "Job failed: Disconnected: Switch turned off" message and a macOS failure for the gmp system package dependency. Not sure I can do much about those...

**Comment by MSoegtropIMC** [comment]
Why does coqide fail on GMP and coq not?

**Comment by palmskog** [comment]
@MSoegtropIMC if you look in the [last CI run for Coq 8.17.0](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/736478400d5ccaa20c573d19f86f06b3a448cafc), it **did** fail on macOS due to gmp.

**Comment by MSoegtropIMC** [comment]
It is more an issue in the Opam main repo - it would make more sense to report it there and put me on CC.

**Comment by mseri** [comment]
It seems to me that the remaining errors are due to infrastructure issue. I am checking them but I don't think I see anything that would prevent merging.

I am rerunning them just to check if they are transient failures

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
