### PR TITLE
4 packages from igarnier/prbnmcn-dagger at 0.0.2

### PR DESCRIPTION
**Pull request by igarnier**
This pull-request concerns:
-`prbnmcn-dagger.0.0.2`: Probabilistic programming library
-`prbnmcn-dagger-gsl.0.0.2`: Probabilistic programming library: GSL-based samplers
-`prbnmcn-dagger-stats.0.0.2`: Probabilistic programming library: prbnmcn-stats-based samplers
-`prbnmcn-dagger-test.0.0.2`: Probabilistic programming library: tests

---
* Homepage: http://github.com/igarnier/prbnmcn-dagger
* Source repo: git+https://github.com/igarnier/prbnmcn-dagger
* Bug tracker: http://github.com/igarnier/prbnmcn-dagger

---
## 0.0.2
- Dependency: `prbnmcn-stats.0.0.3` -> `prbnmcn-stats.0.0.4`
- Add beta distribution to Gsl samplers
- Refactor Cps monad
- Add SMC inference
- Simplify handler type, modularize effect definitions away from Cps_monad
- Fix typo: bernouilli -> bernoulli (report by @nilsbecker)

## 0.0.1
- First release of `prbnmcn-dagger`, a library for probabilistic programming

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by igarnier** [comment]
The only remaining errors are in the `domains-effects` branch (clash between an identifier and the new effect keyword) and on the s390x arch. Is that blocking?

**Comment by samoht** [comment]
If the s390x is expected you should add something like `available: arch != "s390x"` to your opam file.

**Comment by igarnier** [comment]
Thanks! The failure is unexpected but sadly the log is not very informative (building the `prbnmcn-dagger-test` package failed but I can't even tell which test failed). If only I had a mainframe to investigate :)
In any case I'll do what you suggest.

**Comment by samoht** [comment]
Thanks, all good! The `domain-effects` branch is using an old compiler version (and the extensible type has been renamed to `Effect.t` in OCaml 5.0)

**Pull request merged**
