### PR TITLE
Package libdash.0.1.1

### PR DESCRIPTION
**Pull request by mgree**
### `libdash.0.1.1`
Bindings to the dash shell's parser

---
* Homepage: https://github.com/mgree/libdash
* Source repo: git+https:///github.com/mgree/libdash
* Bug tracker: https://github.com/mgree/libdash/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by mgree** [comment]
Can anyone explain what the INSTALL_LOCAL flag is doing? I couldn't find documentation anywhere and the Travis CI seems different from the last time I looked at it...

**Comment by mgree** [comment]
I would appreciate any insight into why [my own tests](https://travis-ci.com/github/mgree/libdash/builds/165758236) succeed on FreeBSD but not the [opam-repository tests](https://travis-ci.com/github/mgree/opam-repository/builds/165762131)... I suspect it's a linking issue, but the error message is uninformative.

**Comment by avsm** [comment]
Your invocation of the test seems different in your version.

```
 LD_LIBRARY_PATH=$(opam var libdash:lib) opam exec -- make -C test test
```

**Comment by mgree** [comment]
Gah! I thought I had taken that out. Thank you.

**Comment by mgree** [comment]
Looks like `conf-aclocal` was the trick for Alpine. So: all the critical stuff is working.

My current best guess about the FreeBSD issue is the `#!/bin/bash` in my testing script---that would explain error 127 in `make` (program not found). Why that script would work in my CI but not yours is baffling, but... FreeBSD keeps `bash` in `/usr/local/bin/bash`, I believe. If the tests don't work this time, I'll call it for now... 🤷‍♀️

**Comment by mgree** [comment]
Well, some transient error broke the OCaml 4.11.0+trunk build and the OpenSUSE build, but it looks like that fixed FreeBSD.

If you want an all green build, I suspect that simply retriggering the builds should do it.

I'm hopeful this is the end of this already-too-long PR. Maybe the next version bump will be simpler? 🤞

**Comment by mgree** [comment]
Thank you, good catch!

I needed opam-installer when I had a different resting regime in place (which meant I had more actions in the install phase and couldn't use the default; see [ocaml/opam  #4099](https://github.com/ocaml/opam/issues/4099).

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
