### PR TITLE
fstreams.0.1.1 - via opam-publish

### PR DESCRIPTION
**Pull request by tel**
Functional, lazy, infinite streams.

A very standard infinite data structure is the stream which lazily
determines its current and next values and even whether they exist or
not! This data structure is useful for describing computations which
are generated and consumed step-by-step and is a powerful basic tool
for many lazy algorithms.

Included in this module are two submodules, Infinite and
Finite. Infinite streams are streams which are guaranteed to always
have a next value and Finite streams are streams which may terminate
but are not obliged to.

Mathematically, Infinite streams are the greatest fixed point of the
functor F X = A * X and Finite streams are the greatest fixed point of
the functor F X = 1 + A * X.

---
* Homepage: https://github.com/tel/ocaml-fstreams
* Source repo: https://github.com/tel/ocaml-fstreams.git
* Bug tracker: https://github.com/tel/ocaml-fstreams/issues

---
Pull-request generated by opam-publish v0.2.1

### CODE REVIEW

**Comment by tel** [comment]
I think the current error may be in my understanding of how Oasis builds work with packing. I'd like to have a module structure like

```ocaml
module Fstreams = struct
  module Finite = Finite
  module Infinite = Infinite
end
```

where Finite and Infinite do not clobber any global names. I thought this was achievable using the `Pack` option? How can I get hierarchical modules like so?

**Comment by avsm** [comment]
You can do that via `pack: true` in the `_oasis` file; see https://github.com/mirage/ocaml-cohttp/blob/master/_oasis#L27 for an example usage.

**Comment by tel** [comment]
So the error that Travis identifies is

```
# W: Cannot find source file matching module 'fstreams' in library fstreams
# E: Failure("Command ''/usr/bin/ocamlbuild' src/fstreams.cma src/fstreams.cmxa src/fstreams.a src/fstreams.cmxs -tag debug' terminated with error code 6")
# make: *** [build] Error 1
```

which I believe is arising because of some kind of `-Wall` style setting in OCaml. I see that warning in my local builds, but they pass, presumably, because I'm not sensitive to it.

What is the `-warn-error` flag set on builds for OPAM?

**Comment by tel** [comment]
Or, in a related question, what is the recommended `-w` setting for the community?

**Comment by tel** [comment]
Hah, and in a final question—how can I change the compiler flags in Oasis!

/ocaml-build-newb.

**Comment by avsm** [comment]
The error comes from setting the `findlibname` to `fstreams` in the `_oasis` file.  Remove that, regenerate OASIS, and it compiles fine.  The warning is harmless; it's due to you packing into the Fstreams module, so there's no actual `fstreams.ml` anywhere.

**Comment by tel** [comment]
Ah, so the warning is just to be ignored.

What is proper use of the `findlibname` field then? As far as I'm aware the situation with `fstreams` is similar to `cohttp` in the following regards

* the name of the package matches the findlib name and matches the `Library` name
* there is no `lib/cohttp.mli` or `lib/cohttp.ml` and there is no `src/fstreams.mli` or `src/fstreams.ml`
* `Pack: true`

I've eliminated the `findlibname` field for now and will try to resubmit, but I'd like to better understand the issue.

Thanks

**Comment by tel** [comment]
Closed again in deference to https://github.com/ocaml/opam-repository/pull/3596

**Pull request closed without merging**
