### PR TITLE
[frama-c] blacklist incompatible why3 version

### PR DESCRIPTION
**Pull request by maroneze**
why3 1.0.0 was released shortly before Frama-C-20180502, but both are incompatible. Compilation works, but some specific parts of Frama-C are not compatible with this version of why3, so it is blacklisted in the latest versions of Frama-C (to avoid opam from trying to downgrade Frama-C if this version of why3 is already installed).

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
```
[ERROR] why3-base (< 0.86 | >= 1.0.0) & coq < 8.4.6 & coq >= 8.7 & lablgtk <
        2.18.2 & frama-c-e-acsl & frama-c-base is not a valid conjunction
```
I believe the correct way should probably be:
```
"why3-base" {< "0.86"}
"why3-base" {>= "1.0.0" }
```

**Comment by maroneze** [comment]
Thanks, I tried using the syntax mentioned in https://github.com/ocaml/opam/issues/2958 this time.

**Comment by maroneze** [comment]
I also disabled the tests in the 20171101 version, as had been already done in the 2018* versions. 

It seems that the remaining errors in the Travis CI are related to `alt-ergo` and not to `frama-c` directly.

**Comment by kit-ty-kate** [comment]
Looks ok. Thanks!

**Pull request merged**
