### PR TITLE
Unify configure invocation

### PR DESCRIPTION
**Pull request by michipili**
This is to solve #6271.

It might not be the best solution to handle everything in conf-autoconf, maybe we need an extra conf-* package just to store the configuration values. As usual, feedback is welcome! :)

Also, it should  be useful to adapt the linter to incite package author to use these variables, but I do not know where to start.

### CODE REVIEW

**Comment by lefessan** [comment]
You are mixing two different ideas:
* some packages need "autoconf" to build
* some packages runs a "./configure", that has been generated by "autoconf", but they don't need "autoconf" itself

`conf-autoconf` is needed for the first category, not for the second one. So, most of the packages you modify do not need to depend on `conf-autoconf`. On another hand, these packages would benefit from a common configuration, that would have to be run only once (your `detect_autoconf_settings.sh` that should actually be called `detect_config_settings.sh`). 

So, my advices:
* create a package `opamconf` that runs `detect_config_settings.sh`. Add this package plus one example of use (`gmp` for example).
* once this one is accepted, add other PRs for other packages, individually.
The reasons to do that are that (1) Travis cannot test all packages when they are too many in one PR, and (2) it is possible for each maintainer to review the changes to his packages, which is harder if they are all in one PR.

**Comment by michipili** [comment]
> You are mixing two different ideas

Yes, this is what I realised while writing my first paragraph.

> So, my advices:

It sounds good, I will soon update my work according to your advices.

**Comment by michipili** [comment]
Bonsoir Fabrice @lefessan 

I did not finish reworking this PR but I prepared a small repository for **opamconfig.**  I will write soon a proper OPAM package, but maybe you already have some feedback.

https://github.com/michipili/opamconfig

**Comment by michipili** [comment]
@lefessan I prepared a new PR #6761 for the package I created. I therefore close this one.

**Pull request closed without merging**
