### PR TITLE
Add package for gappa - a proof engine for numeric (floating point) proofs

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
Gappa is a tool to automatically generate proofs for numerical goals, e.g. error bounds for floating point approximations of a real expression.

This PR might be a bit controversial - gappa is written in C++. It is used in Coq, so it is convenient to have an opam package for it. I don't know how agreeable it is to add an opam packages for C++ code to the opam main repo, but since there is also a package for Z3, I thought I at least ask.

In case you don't want it, I can also add it to the Coq opam repo, but maybe you want some of the prerequisite conf packages.

### CODE REVIEW

**Comment by mseri** [comment]
The old ubuntus are failing with

```
error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#  #error This file requires compiler and library support \
```

I am not sure how easy/worth is to address it.

**Comment by MSoegtropIMC** [comment]
@mseri : Since the user base for gappa is not that large, I would expect that the overlap between gappa users and Ubuntu 16 users is empty and won't increase in the future. So unless it is terribly difficult for you to give a waiver for this, I would indeed prefer to keep it like this.

What is a bit more disturbing is the failure on Fedora. To me this looks like the autoconf package on Fedora is broken - autoconf needs aclocal and this does not seem to be installed, although autoconf is. Should I add `aclocal` as depext to `conf-autoconf` and see what happens?

**Comment by mseri** [comment]
> @mseri : Since the user base for gappa is not that large, I would expect that the overlap between gappa users and Ubuntu 16 users is empty and won't increase in the future. So unless it is terribly difficult for you to give a waiver for this, I would indeed prefer to keep it like this.

This is not a problem. I wanted to hear your opinion before deciding on the merge

> What is a bit more disturbing is the failure on Fedora. To me this looks like the autoconf package on Fedora is broken - autoconf needs aclocal and this does not seem to be installed, although autoconf is. Should I add `aclocal` as depext to `conf-autoconf` and see what happens?

If you don't mind we could have a `conf-autoconf.2` which adds `aclocal` to the depexts for Fedora. Let's see if that will fix it

**Comment by MSoegtropIMC** [comment]
> If you don't mind to add it, we could have a conf-autoconf.2 which adds aclocal to the depexts for Fedora. Let's see if that will fix it. Thanks for the help.

Sure I will try that - I anyway wanted to setup a Fedora VM for my release tests.

I also though about Ubuntu 16 - actually the Coq platform project might make the installation base of gappa much larger - a Windows only predecessor project had more than 10.000 downloads a year. I will discuss with the Coq team how to handle this and either fix it or explicitly state that Ubuntu 16 or older is not supported.

I set this to work in progress until it is decided.

**Comment by MSoegtropIMC** [comment]
@mseri : I analyzed the situation on Ubuntu and Fedora and I would say I should add an opam package for automake. On Ubuntu automake seems to be installed - possibly via the binutils package - on Fedora not. The opam conf-autoconf package I require installs just autoconf also on Ubuntu. The autoconf package recommends but does not require automake on Ubuntu. See:
(https://packages.ubuntu.com/bionic/autoconf). So in summary it is just luck that it works on Ubuntu - the prerequisites I gave are incomplete.

**Comment by mseri** [comment]
Thanks for looking into it

**Comment by MSoegtropIMC** [comment]
@mseri : I am still working on the Ubuntu16 fix (currently installing a VM).

**Comment by mseri** [comment]
Wow, thank you very much for this!

**Comment by MSoegtropIMC** [comment]
@mseri : I am thinking about dropping Ubuntu 16 (Xenial) support for these reasons:

- installing opam requires adding a non standard single package PPA to install the sandbox (bubble) or to disable the sandbox - I took the extra PPA approach with sandbox

- OCaml 4.07.1 does not compile once I get opam installed (switch creation fails)

But possibly I messed something up - how does the opam CI get as far as it does? Are these hand crafted images grown and patched over years? I used a plain fresh Ubuntu 16.04.7 with just build-essentials and bubble installed and would say opam is not supported at all on this platform, unless someone can give instructions on how get at least opam and OCaml 4.07.1 running there.

Possibly disabling the sandbox is the way to go?

**Comment by mseri** [comment]
Not sure about the way the images are built, sorry. I will have to ping @kit-ty-kate for that. 
You are free to not support Xenial, any interested user can either install manually bubblewrap or use unsandboxed builds. This is not a problem

It is weird that ocaml 4.07.1 does not build though.

**Comment by MSoegtropIMC** [comment]
> It is weird that ocaml 4.07.1 does not build though.

I didn't look into why OCaml 4.07.1 fails - opam is not terribly informative - e.g. does not provide a link to the logs. It just says one could try --jobs=1, but this doesn't help.

But since OCaml 4.07.1 was common when Xenial was common, it is indeed weird that it fails. If this helps, I can give the exact commands I issues on a fresh installed Ubuntu 16.

I would like to support gappa if Xenial is supported at all - something which is unclear to me.

**Comment by mseri** [comment]
Xenial is supported, but you need to disable the sandbox or install bubblewrap. The error seems to be due to the old gcc version, see https://ci.ocaml.org/log/saved/docker-build-d15454418c83e6142f8d1d3ba9e4f84c/817d0b96f4d83b95c2dc1ce35f3e607e466bc2c6

Fwiw, I think this PR is ready to merge if you want

**Comment by MSoegtropIMC** [comment]
> Fwiw, I think this PR is ready to merge if you want

Let me look into it today evening once more and then I will decide.

**Comment by MSoegtropIMC** [comment]
I think I can fix it for Xenial until Monday. Please wait until then.

**Comment by MSoegtropIMC** [comment]
A quick status note: I got opam installed on Ubuntu 16.04. I tried to install bubblewrap - it is not included in the Ubuntu package repo for 16.04, but there is an addon repo - but the version of bubblewrap got this way is too old and results in strange errors. I think minimum required is 0.2.1.

The tests for this PR on Ubuntu 16.04 are ongoing ...

**Comment by MSoegtropIMC** [comment]
@mseri : this should work now - at least locally it does build now on Ubuntu 16.04.

**Comment by mseri** [comment]
Thank you very much for this! It is good to merge

**Comment by MSoegtropIMC** [comment]
> Thank you very much for this! It is good to merge

I say thank your for your openness to take this foreign language stuff in!

**Pull request merged**
