### PR TITLE
[new release] mwt (v0.1.0)

### PR DESCRIPTION
**Pull request by hcarty**
Mediumweight thread library for OCaml via Lwt

- Project page: <a href="https://github.com/hcarty/mwt">https://github.com/hcarty/mwt</a>

##### CHANGES:

* Initial release

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The archive is unavailable:
```
$ wget https://github.com/hcarty/mwt/releases/download/v0.1.0/mwt-0.1.0.tbz
[...]
HTTP request sent, awaiting response... 404 Not Found
```

**Comment by hcarty** [comment]
@kit-ty-kate Ack, I'm sorry!  Thank you for catching that.  I missed a `dune-release` step.

I pushed up the source archive and restarted the datakit CI builds.  Could you restart Travis?

**Comment by hcarty** [comment]
Thank you!

**Comment by kit-ty-kate** [comment]
There is a problem with OCaml 4.02:
```
#=== ERROR while installing mwt.0.1.0 =========================================#
# opam-version 1.2.2
# os           linux
# command      dune build -p mwt -j 4
# path         /home/travis/.opam/system/build/mwt.0.1.0
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/mwt.0.1.0/mwt-11107-e7966f.env
# stdout-file  /home/travis/.opam/system/build/mwt.0.1.0/mwt-11107-e7966f.out
# stderr-file  /home/travis/.opam/system/build/mwt.0.1.0/mwt-11107-e7966f.err
### stderr ###
#     ocamlopt src/.mwt.objs/mwt.{cmx,o} (exit 2)
# (cd _build/default && /usr/bin/ocamlopt.opt -w -40 -g -I src/.mwt.objs -I /home/travis/.opam/system/lib/bytes -I /home/travis/.opam/system/lib/lwt -I /home/travis/.opam/system/lib/lwt/unix -I /home/travis/.opam/system/lib/result -I /usr/lib/ocaml/threads -intf-suffix .ml -no-alias-deps -o src/.mwt.objs/mwt.cmx -c -impl src/mwt.pp.ml)
# File "src/mwt.ml", line 47, characters 21-23:
# Error: Unbound constructor Ok
#       ocamlc src/.mwt.objs/mwt.{cmo,cmt} (exit 2)
# (cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.mwt.objs -I /home/travis/.opam/system/lib/bytes -I /home/travis/.opam/system/lib/lwt -I /home/travis/.opam/system/lib/lwt/unix -I /home/travis/.opam/system/lib/result -I /usr/lib/ocaml/threads -intf-suffix .ml -no-alias-deps -o src/.mwt.objs/mwt.cmo -c -impl src/mwt.pp.ml)
# File "src/mwt.ml", line 47, characters 21-23:
# Error: Unbound constructor Ok
```

**Comment by hcarty** [comment]
Thanks - bumped the version constraint to >= 4.03.0

**Comment by hcarty** [comment]
Clean!

**Pull request merged**
