### PR TITLE
added packages/genspir/genspir.1.0.0

### PR DESCRIPTION
**Pull request by UnixJunkie**
switched from oasis to dune

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I will use a proper tag name once all tests pass.

**Comment by UnixJunkie** [comment]
This is the final tag.

**Comment by kit-ty-kate** [comment]
Just an off topic general advice, I've seen a lot of your packages using dune but without any `dune-project` file in the repository. It really helps to know which minimal version of dune you require for your packages. Plus it's going to be mandatory for dune 2.0. I'd suggest to add them to your projects for future releases

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by UnixJunkie** [comment]
I really don't like putting automatically generated files under VC...

**Comment by kit-ty-kate** [comment]
> I really don't like putting automatically generated files under VC...

it's not automatically generated. It's only generated once if it doesn't already exist. It's not going to change by itself.

**Comment by UnixJunkie** [comment]
Ok, I'll consider it.

**Pull request merged**
