### PR TITLE
sh, don't bash

### PR DESCRIPTION
**Pull request by dsheets**
Based on #5651, this patch uses `sh` in place of `bash` where use of `bash` is unnecessary. Not all distros ship `bash` by default, in particular distros based on `busybox` do not typically have `bash`.

@Kakadu, please review this.

### CODE REVIEW

**Comment by Kakadu** [comment]
I think that doesn't brake anything. 

Btw, is fixing this warnings really necessary?

**Comment by dsheets** [comment]
@Kakadu, it's not necessary to fix the warnings for the packages that you don't maintain. It would be nice (but is also not necessary) to fix the warnings for the packages that you *do* maintain. Thanks for the review!

**Comment by avsm** [comment]
`lablqt.0.2` needs an upper bound on sexplib to `<113.24.00` so that it picks up the camlp4 extension.

**Comment by dsheets** [comment]
That constraint exists in master. I will rebase.

**Comment by dsheets** [comment]
Fixed in #5784.

**Pull request closed without merging**
