### PR TITLE
[coq-serapi] New upstream version.

### PR DESCRIPTION
**Pull request by ejgallego**
- [serlib] Be more lenient when parsing back `Id.t` as to accommodate
  hacks in the Coq AST (#64) Thanks to @palmskog for the report.

### CODE REVIEW

**Comment by ejgallego** [comment]
This fails due to `m4` not being installed. I am unsure if action from me is required.

**Comment by mseri** [comment]
No, sorry, the containers are being rebuilt to fix that issue. You can safely ignore it

**Comment by mseri** [comment]
The osx failure is due to a known opam2 bug, this is good to merge

**Comment by ejgallego** [comment]
Thanks again !

**Pull request merged**
