### PR TITLE
Add portia.1.0

### PR DESCRIPTION
**Pull request by rixed**

### CODE REVIEW

**Comment by samoht** [comment]
Seems to require >=4.02?

```
#=== ERROR while installing portia.1.0 ========================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/4.01.0/build/portia.1.0
# compiler     4.01.0
# exit-code    2
# env-file     /home/travis/.opam/4.01.0/build/portia.1.0/portia-30763-48c407.env
# stdout-file  /home/travis/.opam/4.01.0/build/portia.1.0/portia-30763-48c407.out
# stderr-file  /home/travis/.opam/4.01.0/build/portia.1.0/portia-30763-48c407.err
### stdout ###
# ocamlfind ocamldep  -package "batteries dynlink" *.ml > depend
### stderr ###
# Makefile:45: fwdepend: No such file or directory
# Makefile:62: depend: No such file or directory
# File "output.fw", line 29, characters 10-19:
# Error: Syntax error: operator expected.
# make: *** [depend] Error 2
```

**Comment by rixed** [comment]
Yes indeed. Fixed.

**Comment by samoht** [comment]
Same issue for portia 1.0 apparently:

```
#=== ERROR while installing portia.1.0 ========================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/4.01.0/build/portia.1.0
# compiler     4.01.0
# exit-code    2
# env-file     /home/travis/.opam/4.01.0/build/portia.1.0/portia-30795-48c407.env
# stdout-file  /home/travis/.opam/4.01.0/build/portia.1.0/portia-30795-48c407.out
# stderr-file  /home/travis/.opam/4.01.0/build/portia.1.0/portia-30795-48c407.err
### stdout ###
# ocamlfind ocamldep  -package "batteries dynlink" *.ml > depend
### stderr ###
# Makefile:45: fwdepend: No such file or directory
# Makefile:62: depend: No such file or directory
# File "output.fw", line 29, characters 10-19:
# Error: Syntax error: operator expected.
# make: *** [depend] Error 2
```

**Comment by rixed** [comment]
Lol I fixed the wrong one (which was also broken BTW).

**Comment by samoht** [comment]
All green now, merging!

**Pull request merged**
