### PR TITLE
bap-veri: upper bound on textutils

### PR DESCRIPTION
**Pull request by avsm**
see #9187

### CODE REVIEW

**Comment by avsm** [comment]
@diml where does Regular.Std come from? Cant find it in textutils

**Comment by diml** [comment]
@avsm where did you see that? I can't find it our tree

**Comment by diml** [comment]
Just saw it in the log, that's odd. Trying to install it with the old version of textutils

**Comment by diml** [comment]
it comes from the `regular` opam package, which seems to be part of BAP as well

**Comment by avsm** [comment]
cc @ivg -- not sure what is wrong with bap-veri's build

```
# + /home/opam/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -pp 'ppx-jane -dump-ast' -package bap -package bap-traces -package core_kernel -package pcre -package ppx_jane -package textutils -package threads -thread -I lib -o lib/veri_rule.cmi lib/veri_rule.mli
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/opam/.opam/4.03.0/lib/ocaml/compiler-libs, /home/opam/.opam/4.03.0/lib/ocaml
# File "lib/veri_rule.mli", line 9, characters 8-15:
# Error: Unbound module type Regular
```

with Regular 1.2.0...
build log: https://ci.ocaml.io/log/saved/docker-build-08a77e8e6a96d6caaf77914aaae92924/f6a5e090a03e74290c51c644355eaffd756b6978

**Comment by avsm** [comment]
this is not the right fix at any rate, so closing

**Pull request closed without merging**
