### PR TITLE
Release camlkit v0.1.1-alpha

### PR DESCRIPTION
**Pull request by dboris**

### CODE REVIEW

**Comment by shonfeder** [comment]
Hello :)

Looks like the build is failing currently,

On linux due to a missing rule a target:

```
[ERROR] The compilation of camlkit-base.0.1.1 failed at "dune build -p camlkit-base -j 7 @install".

#=== ERROR while compiling camlkit-base.0.1.1 =================================#
# context              2.2.0~beta3~dev | freebsd/x86_64 | ocaml-base-compiler.4.14.2 | pinned(https://github.com/dboris/camlkit/archive/refs/tags/v0.1.1-alpha.tar.gz)
# path                 ~/.opam/4.14.2/.opam-switch/build/camlkit-base.0.1.1
# command              ~/.opam/4.14.2/bin/dune build -p camlkit-base -j 7 @install
# exit-code            1
# env-file             ~/.opam/log/camlkit-base-43191-3c50e5.env
# output-file          ~/.opam/log/camlkit-base-43191-3c50e5.out
### output ###
# File "runtime/dune", line 1, characters 0-671:
#  1 | (library
#  2 |  (name runtime)
#  3 |  (public_name camlkit-base.runtime)
# ....
# 20 | ;   (generated_types Types_generated)
# 21 | ;   (generated_entry_point C))
# 22 |   (flags -linkall))
# Error: No rule found for runtime/flags.txt
# (cd _build/default && /home/opam/.opam/4.14.2/bin/ocamlc.opt -linkall -g -bin-annot -I runtime/.runtime.objs/byte -I /home/opam/.opam/4.14.2/lib/bigarray-compat -I /home/opam/.opam/4.14.2/lib/ctypes -I /home/opam/.opam/4.14.2/lib/ctypes-foreign -I /home/opam/.opam/4.14.2/lib/integers -I /home/opam/.opam/4.14.2/lib/ocaml/threads -I /home/opam/.opam/4.14.2/lib/stdlib-shims -no-alias-deps -open Runtime__ -o runtime/.runtime.objs/byte/runtime__Inspect.cmo -c -impl runtime/inspect.ml)
# File "runtime/inspect.ml", line 11, characters 10-26:
# 11 |     match Platform.current with
#                ^^^^^^^^^^^^^^^^
# Error: Unbound module Platform
```

And on MacOS due to a missing test dependency

```
#=== ERROR while compiling camlkit.0.1.1 ======================================#
# context              2.2.0~beta2 | macos/x86_64 | ocaml-base-compiler.4.14.2 | pinned(https://github.com/dboris/camlkit/archive/refs/tags/v0.1.1-alpha.tar.gz)
# path                 ~/.opam/4.14.2/.opam-switch/build/camlkit.0.1.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p camlkit -j 11 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/camlkit-2837-5b0033.env
# output-file          ~/.opam/log/camlkit-2837-5b0033.out
### output ###
# File "test/dune", line 5, characters 23-31:
# 5 |  (libraries foundation alcotest))
#                            ^^^^^^^^
# Error: Library "alcotest" not found.
# -> required by _build/default/test/test_objc.exe
# -> required by alias test/runtest in test/dune:2
# File "test/dune", line 11, characters 38-46:
# 11 |  (libraries foundation appkit camlkit alcotest))
#                                            ^^^^^^^^
# Error: Library "alcotest" not found.
# -> required by _build/default/test/test_camlkit.exe
# -> required by alias test/runtest in test/dune:8
# File "test/dune", line 17, characters 30-38:
# 17 |  (libraries foundation appkit alcotest))
#                                    ^^^^^^^^
# Error: Library "alcotest" not found.
# -> required by _build/default/test/test_stret.exe
# -> required by alias test/runtest in test/dune:14
```

Please have a look at those when you have a chance!

**Comment by dboris** [comment]
The setup on Linux is a bit more involved. A requirement is to have an opam switch built with `clang`. I do it with `env CC=clang opam switch create ...`. I haven't found a way to express this requirement in the opam file. Do you have a suggestion how to handle that?

**Comment by mseri** [comment]
AFAIK we don't have a way to handle that. Ping @rjbou and @kit-ty-kate that know more about opam internals

**Comment by shonfeder** [comment]
> I do it with `env CC=clang opam switch create ...`. I haven't found a way to express this requirement in the opam file

Passed along from @kit-ty-kate, the build environment can be configured via

```
build-env: [
  [CC = "clang"]
]
```

See https://opam.ocaml.org/doc/Manual.html#opamfield-build-env

Thanks for your patience and persistence :)

**Comment by dboris** [comment]
@shonfeder @kit-ty-kate Looks like `build-env: [[CC = "clang"]]` is having no effect. The `CC` variable is also not listed as supported in the opam manual: https://opam.ocaml.org/doc/Manual.html#opamfield-build-env.
Not sure what is the best way to move forward.

**Comment by dboris** [comment]
After more investigation, it appears that in addition to the `clang` issue, there is a second issue with the Linux setup:
the libobjc library provided by the distros is a very old version missing some important API functions. To use this project, the user would have to build a newer version of libobjc from source. Given all this trouble, I'm inclined to just release the project for macOS and FreeBSD. The other option is to release it as is for Linux, and explain in the README the correct procedure to install it. Out-of-the-box it will not work under Linux.

**Comment by raphael-proust** [comment]
> I'm inclined to just release the project for macOS and FreeBSD

You can do so by adding `available: os = "macos" | os = "freebsd"`.

It's reasonable to have some package which are installable only on some platforms so that's fine. Although note that according to https://pkgs.org/search/?q=libobjc2 it seems that Fedora and openSUSE seem to also have a recent enough version.

A better way to deal with the issue in that case is to depend on a package called `conf-libobjc2` for which you only provide the system package names for macos, freebsd, fedora, and opensuse. This has multiple advantages:

- as other distros distribute this version of libobjc, we can simply add a line to the `conf-` package and gain immediate installability
- users who make an effort to install libojc2 in their environments can install your package

**Comment by shonfeder** [comment]
Glad to see you're able to move forward :)

There are three CI failures still.

- 1. Name collision linting which I think we ignore: this library seems sensibly named and the supposed collisions are specious.
- 2. An internal assertion error from opam we've been seeing on ARM (I'm working on filing an issue for this)
- 3. A failure on freebsd that seem legit.

Here is the relevant error for (3):

```
#=== ERROR while compiling camlkit-base.0.1.1 =================================#
# context              2.2.0~beta3~dev | freebsd/x86_64 | ocaml-base-compiler.5.2.0 | pinned(https://github.com/dboris/camlkit/archive/refs/tags/v0.1.1-alpha.6.tar.gz)
# path                 ~/.opam/5.2.0/.opam-switch/build/camlkit-base.0.1.1
# command              ~/.opam/5.2.0/bin/dune build -p camlkit-base -j 15 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/camlkit-base-32285-d34249.env
# output-file          ~/.opam/log/camlkit-base-32285-d34249.out
### output ###
# File "test/test-camlkit-base/dune", line 2, characters 8-17:
# 2 |  (names test_objc test_stret)
#             ^^^^^^^^^
# (cd _build/default/test/test-camlkit-base && ./test_objc.exe)
# Testing objc.
# This run has ID `4EC04B62-C843-40D2-A9EE-4D290B05400E`.
# test_objc.exe: internal error, uncaught exception:
#                Unix.Unix_error(Unix.EEXIST, "symlink", "/home/opam/.opam/5.2.0/.opam-switch/build/camlkit-base.0.1.1/_build/default/test/test-camlkit-base/_build/_tests/latest")
#                
# Fatal error: exception Alcotest__Core.Make(M).Test_error
# (cd _build/default/test/test-camlkit-base && ./test_stret.exe)
# Testing stret.
# This run has ID `B295F513-C954-4291-9432-E2C1C316B079`.
#  ...                Stret          0   return small struct.
[OK]                Stret          0   return small struct.
#  ...                Stret          1   return large struct.
[OK]                Stret          1   return large struct.
# The full test results are available in `/home/opam/.opam/5.2.0/.opam-switch/build/camlkit-base.0.1.1/_build/default/test/test-camlkit-base/_build/_tests/B295F513-C954-4291-9432-E2C1C316B079`.
# Test Successful in 0.000s. 2 tests run.
```

**Comment by dboris** [comment]
I'm not sure what to make of this error. It looks like an issue with the testing infrastructure or dune, rather than the test itself. The same test runs correctly on the other [FreeBSD instance (freebsd-ocaml-4.14/amd64)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2856971abe8cf8dab9b7fe6ea25c4a926f37e041/variant/freebsd,freebsd-ocaml-4.14-amd64,camlkit-base.0.1.1,tests).

**Comment by shonfeder** [comment]
> The same test runs correctly on the other [FreeBSD instance (freebsd-ocaml-4.14/amd64)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2856971abe8cf8dab9b7fe6ea25c4a926f37e041/variant/freebsd,freebsd-ocaml-4.14-amd64,camlkit-base.0.1.1,tests).

True, but that is testing a different ocaml version, and, unless I'm missing something, the failure seems directly related to your tests rather than any general testing infrastructure?

**Comment by dboris** [comment]
The tests are not creating any symlinks or accessing Unix APIs. My interpretation is that this symlink is created by dune and is present in the Docker image, while it should not be.
```
Unix.Unix_error(Unix.EEXIST, "symlink", "/home/opam/.opam/5.2.0/.opam-switch/build/camlkit-base.0.1.1/_build/default/test/test-camlkit-base/_build/_tests/latest")
```
I think that's the symlink that is causing the issue:
/home/opam/.opam/5.2.0/.opam-switch/build/camlkit-base.0.1.1/_build/default/test/test-camlkit-base/_build/_tests/latest

Could it be a corrupted Docker image?

**Comment by shonfeder** [comment]
The FreeBSD builds aren't in a docker image, but I think you are right that something funky is going on with the build environment, because rerunning that job let it go through. I'll open an issue to track that for future. Thanks for all your work here to get the packaging building well and narrowed to supported platforms!

**Comment by dboris** [comment]
The effort to make the package installable on Linux didn't pay off, unfortunately. The `libobjc2` dependency provided by Fedora is correct, but the other dependency, `gnustep-base-devel` depends on the outdated `libobjc` that is not compatible. As a result, the test executables crash. The only way that I see to use this package on Linux is by building the gnustep libraries from source. 

Unless you have other ideas, I think I should mark the package as not available on Linux until the situation improves.

**Comment by dboris** [comment]
The FreeBSD CI bug has resurfaced, so maybe you should restart the CI job again.

**Comment by shonfeder** [comment]
Only CI failure now is the name collision lint, which is not relevant here. LGTM. Thanks for all your work tuning this package config!

**Comment by mseri** [comment]
Thanks a lot!

**Pull request merged**
