### PR TITLE
BAP 0.9.9

### PR DESCRIPTION
**Pull request by ivg**

### CODE REVIEW

**Comment by ivg** [comment]
What concerning the warning. It looks like that it refers to the usage of variable `bap:doc`. I think that it is completely valid to refer to a variable of my own package.

**Comment by samoht** [comment]
I think it's defined only if the package is installed...

**Comment by ivg** [comment]
yeah, and I'm using it in `remove` script.

**Comment by samoht** [comment]
which can be called with `opam remove --force bap` :p 

but anyway, you have a valid point (ie. using a variable to speak about self variables) and the next version of opam will support that properly. So it might be better to use `%{doc}%/bap` so that it could work fine on older version of opam as well.

**Comment by ivg** [comment]
I'd better remove it at all, since we decided not to install documentation on a user side. It takes to much time to compile it, and no-one can find it :)

btw, can you restart this [job](https://travis-ci.org/ocaml/opam-repository/jobs/74488723)? (Yet another connectivity issue.)

**Comment by samoht** [comment]
job restarted.

**Comment by ivg** [comment]
would you mind to merge it?

**Pull request merged**
