### PR TITLE
Fix conf-openblas on macOS arm64 hardware, hopefully without breakages

### PR DESCRIPTION
**Pull request by dra27**
Re-attempt at #25076, following the needed revert of the second part in #25195.

First commit is the same as #25076 - it changes macOS only, introducing a missing dependency (the package already used pkg-config without depending on its conf- package) and amending the call to `pkg-config` for Homebrew only to match Homebrew's recommendation.

The second commit addresses the unintended breakage in #25194 (for which apologies again!). There are two issues at play: `setenv` doesn't support filters (ocaml/opam#5787) and empty updates to environment variables crash opam, which is fixed in 2.1.5, but not in earlier releases (ocaml/opam#5350).

The fix I propose is to put the `setenv` field in a package of its own, and have `conf-openblas` depend on that package only for macOS with Homebrew. Note that `conf-openblas-macOS-env` will only install if `conf-openblas` installed, which means that we know that the environment variable update will not be empty, hence there is no need to check for the opam-version itself.

### CODE REVIEW

**Comment by dra27** [comment]
(draft because I don't at present have access to my Mac to test it)

**Comment by mseri** [comment]
Oh this lint was not there the last time:
```
2024-02-07 14:39.15: Error in conf-openblas-macOS-env.1:            warning 56: It is discouraged for non-compiler packages to use 'setenv:'
```

**Comment by hannesm** [comment]
would you mind to increase the version of "conf-openblas" to 0.2.2?

**Comment by dra27** [comment]
The lint issue was there last time - although it's at present removed in opam 2.2, because the issue which caused it be a warning has itself disappeared (cf. https://github.com/ocaml/opam/blob/5fa0ac762f4c8e6e2a45272adc6ef1fa4c6dcf28/src/state/opamFileTools.ml#L655-L661)

**Comment by dra27** [comment]
For both changes, @hannesm, or just for the second env-related change?

If for both, presumably the 0.2.1 should be marked as unavailable on macOS arm64 with Homebrew?

**Comment by mseri** [comment]
I would just move `packages/conf-openblas/conf-openblas.0.2.1/opam -> packages/conf-openblas/conf-openblas.0.2.2/opam` and not touch the other. When you run `opam upgrade` you'll get the latest one anyway

**Comment by dra27** [comment]
OK, I don't mind doing it (and will push in a sec!), but it's that bit which feels strange for using a version number bump. It's a _packaging_ error (we're not trying to install an older version of the thing, we're preserving older incorrect packaging instructions for the same thing), but we end up leaving opam-repository where if for any reason a solver on macOS happens to try 0.2.1 (lowerbounds, etc.), then it'll fail.

**Comment by mseri** [comment]
You can make it unavailable for macos on arm64 with homebrew if that is completely uninstallable, I thought it was working but required manually setting the correct PKG_CONFIG_PATH all the time you wanted to install something

**Comment by dra27** [comment]
With `conf-openblas.0.2.1` with macOS Homebrew, `PKG_CONFIG_PATH` needs to be set _both_ when running `opam install` and also when installing/building/running anything which uses the openblas package. The first part - having to set `PKG_CONFIG_PATH` in order to _install_ `conf-openblas` - I think is a bug in the conf-openblas package (so I just pushed a disabling of conf-openblas.0.2.1 for macOS+Homebrew). The second part is more of a "smell" - the `conf-openblas` package is meant to configure the openblas package to be ready for use, but it hadn't (because the `PKG_CONFIG_PATH` is left unconfigured) forcing _dependent_ packages to need to a special case for Homebrew. The setenv part is then what deals with that.

**Comment by dra27** [comment]
I've now tested and verified this on both Intel and ARM Mac hardware

**Comment by mseri** [comment]
Thanks

**Pull request merged**
