### PR TITLE
[new release] dune (15 packages) (3.11.1)

### PR DESCRIPTION
**Pull request by emillon**
Fast, portable, and opinionated build system

- Project page: <a href="https://github.com/ocaml/dune">https://github.com/ocaml/dune</a>
- Documentation: <a href="https://dune.readthedocs.io/">https://dune.readthedocs.io/</a>

##### CHANGES:

- Fix `dune rpc` commands on Windows (ocaml/dune#8806, fixes ocaml/dune#8799, @nojb)

- Fix `inline_tests` when the partition list is empty (ocaml/dune#8849, fixes ocaml/dune#8848, @hhugo)

### CODE REVIEW

**Comment by emillon** [comment]
I was able to have a local failure with `opam install dune.3.10.0 codept.0.11.1 --with-test` so I think it's due to a flaky test.

**Comment by haochenx** [comment]
Thanks for confirming. I'm convinced that it could be a flaky test. Looks mergeable to me.

**Comment by hhugo** [comment]
Once merged, can one rebase and restart ci on https://github.com/ocaml/opam-repository/pull/24565

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
