### PR TITLE
Odnnr 202

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by mseri** [comment]
Only on ocaml 5.0 it fails with
```
#=== ERROR while compiling odnnr.2.0.2 ========================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | pinned(https://github.com/UnixJunkie/odnnr/archive/v2.0.2.tar.gz)
# path                 ~/.opam/5.0/.opam-switch/build/odnnr.2.0.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p odnnr -j 31
# exit-code            1
# env-file             ~/.opam/log/odnnr-7-86ec1e.env
# output-file          ~/.opam/log/odnnr-7-86ec1e.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.model.eobjs/byte -I /home/opam/.opam/5.0/lib/batteries -I /home/opam/.opam/5.0/lib/camlp-streams -I /home/opam/.opam/5.0/lib/cpm -I /home/opam/.opam/5.0/lib/dolog -I /home/opam/.opam/5.0/lib/domainslib -I /home/opam/.opam/5.0/lib/lockfree -I /home/opam/.opam/5.0/lib/minicli -I /home/opam/.opam/5.0/lib/num -I /home/opam/.opam/5.0/lib/ocaml/str -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/parany -I src/.odnnr.objs/byte -no-alias-deps -o src/.model.eobjs/byte/model.cmo -c -impl src/model.ml)
# File "src/model.ml", line 268, characters 29-37:
# 268 |               Parmap.parmap ~core_pin ncores (fun (train_fn, test_fn) ->
#                                    ^^^^^^^^
# Error: The function applied to this argument has type
#          ?preserve:bool -> ?csize:int -> 'a list
# This argument cannot be applied with label ~core_pin
```

**Comment by UnixJunkie** [comment]
ok, I need to update the code.

**Comment by kit-ty-kate** [comment]
ping @UnixJunkie

**Comment by UnixJunkie** [comment]
Ok, I will have a look at it today.

**Comment by UnixJunkie** [comment]
at least parany-11 is needed

**Comment by UnixJunkie** [comment]
an upper bound might be needed too; I am looking for it

**Comment by UnixJunkie** [comment]
superseded by https://github.com/ocaml/opam-repository/pull/23309

**Pull request closed without merging**
