### PR TITLE
[new release] nuscr (2.0.0)

### PR DESCRIPTION
**Pull request by fangyi-zhou**
CHANGES:

## Added

- A new pragma system for extensions:
  `(*# PRAGMA #*)` at the beginning of the input file can enable theory
  extensions.
- Nested Protocol extension, via `NestedProtocols` pragma (by Benito Echarren Serrano)
- Refinement Type extension, via `RefinementTypes` pragma (by Fangyi Zhou)

## Changed

- New, improved command line interface with cmdliner
- Reorganise code layout
- Recursions immediately after a choice is permitted under some circumstances

## Fixed

- Non-distinct choice prefixes now raise an error
- Degenerate recursions in protocols will be removed
- Catch an uncaught exception when user enters a non-existent protocol from CLI
- Merging [end] and [\mu t.t] after projection is now possible

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I believe https://github.com/nuscr/nuscr/pull/140 should fix all the issues encountered here.

**Comment by kit-ty-kate** [comment]
```
2021-09-05 14:16.18: Error in nuscr.2.0.0:              error 60: Upstream check failed: "The archive doesn't match checksums:
                - archive: sha256=d6e1ca69f977ecd05c04545b8db3314a454e74c73cd8584085f1f4a255315b75, in opam file: sha256=fbd17793416c225702a93f52e200e48faa37721cab4d16c3d997500407c6fede
                - archive: sha512=ea7ebf199849e38ed9b393fbd9c4d782ca3fb9c36ad1b463d3c8da336b5979e6eff4e1e42169350e4896500c4744f16fa6e6b1d425122d4d69e87f0bb45c538b, in opam file: sha512=da005593f3ae30c2566121452535c2405508f197f26962ac25d402e40245b3c8344d5a654cd3e3069f85458b232a845bc4a0371bacc59741dfb067e88cd3d6d0
```

**Comment by fangyi-zhou** [comment]
Could you re-run the CI? I updated the release file now.

**Comment by kit-ty-kate** [comment]
> Could you re-run the CI? I updated the release file now.

Sadly i cannot. I lack the interface for it (see https://github.com/ocaml/opam-repository/pull/19397#issuecomment-913163748)
Could you rebase the PR on top of master? I don't seem to have the rights to push into your repository. That would do the job.

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by fangyi-zhou** [comment]
Thanks a lot!

**Pull request merged**
