### PR TITLE
Fix revdeps from #17571

### PR DESCRIPTION
**Pull request by mseri**
See https://github.com/ocaml/opam-repository/pulls

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>

### CODE REVIEW

**Comment by mseri** [comment]
Ping, upcoming breakage from the cohttp 3.0.0 release:

- @kkazuo (azblob-async)
- @rgrinberg @tmattio (curly -- tests, opium)
- @talex5 (current_github, current_web, prmetheus-app)
- @dinosaure (git-http, git-unix)
- @Aaylor (github-jsoo)
- @pirbo (kappa-server)
- @mmaker (letsencrypt)
- @komamitsu (oraft)
- @lpw25 (prof_spacetime)
- @jerben  (sihl -- tests)

**Comment by hannesm** [comment]
Thanks @mseri for your headsup and release engineering. For letsencrypt (@mmaker), the most recent release is already compatible with cohttp 3 (this PR did _not_ add an upper bound for letsencrypt 0.2.2).

**Comment by mseri** [comment]
Oh, indeed @hannesm, thanks for pointing it out, and sorry @mmaker I thought I had checked them carefully

**Comment by tmattio** [comment]
Thanks for the ping @mseri! 🙌  Will add an upper bound to Opium.

**Comment by Aaylor** [comment]
Thanks for the ping, I'll add the upper bound for `github-jsoo` !

**Comment by dinosaure** [comment]
Just a note about the server side the update of the API. Due to `conduit.3.0.0`, the way to launch an HTTP server is a bit different and it was explained [here](https://github.com/mirage/ocaml-cohttp/blob/9f1745b17ef201b7341c1bd42fcd004c71e16f59/cohttp-lwt-unix-nossl/src/server.mli#L13-L55):

```ocaml
(** [create ?timeout ?backlog ?stop ?on_exn cfg protocol service t] is a new
   HTTP server.

    The user can decide to start a simple HTTP server (without encryption)
   or one with TLS encryption. It depends on what the user gives as [cfg],
   [protocol] and [service]. Using [conduit-lwt-tls], the end-user is able
   to make an encrypted HTTP server with:

    {[
      let run =
        create cfg Conduit_lwt_tls.TCP.protocol Conduit_lwt_tls.TCP.service
    ]}

    A simple HTTP server (with [conduit-lwt]) is:

    {[
      let run =
        create cfg Conduit_lwt.TCP.protocol Conduit_lwt.TCP.service
    ]}

    [cfg] depends on the given [service] - and let the user to define which
   port the server use, and, in the case of {!Conduit_lwt_tls.TCP.service},
   which TLS certificate it uses. See [Conduit] for more information about
   {i protocol} and {i service}.

    When provided, the [stop] thread will terminate the server if it
   ever becomes determined.

    When provided, [backlog] will limit the number of open
   connections.

    Every connection will be served in a new lightweight thread that
   is invoked via the callback defined in [t]. If the callback raises
   an exception, it is passed to [on_exn] (by default, to a function
   that logs the exception using the {!Logs} library). *)
val create :
  ?timeout:int ->
  ?backlog:int ->
  ?stop:unit Lwt.t ->
  ?on_exn:(exn -> unit) ->
  'cfg ->
  (_, 'flow) Conduit_lwt.protocol ->
  ('cfg, 't, 'flow) Conduit_lwt.Service.service -> t -> (unit -> unit Lwt.t)
```

`cfg` depends on what you give as a Conduit's service - if it's a TLS service, you must pass a certificate and TCP/IP configuration for example. This is the biggest **breaking change** of this release. In the case of `ocurrent` for example where the server is launch [here](https://github.com/ocurrent/ocurrent/blob/40e3bc65eae3517ee5c834f2cf9ed2264e1947c0/lib_web/current_web.ml#L77), the line should be updated with:

```ocaml
let default_mode =
  { Conduit_lwt.TCP.sockaddr= Unix.PF_INET (Unix.inet_addr_loopback, 8080)
  ; capacity= 40 }

let run ?(mode= default_mode):cfg site =
   let config = ... in
   create cfg Conduit_lwt.TCP.protocol Conduit_lwt.TCP.service config
```

If someone need any help about migration process, feel free to open an issue in the cohttp repository and I will happy to help you.

**Comment by mseri** [comment]
Also let me mention that `Cohttp_lwt_jsoo.Cohttp_lwt_Xhr` is now just `Cohttp_lwt_jsoo`

**Comment by jerben** [comment]
Thanks @mseri for the heads up, will add an upper bound to Sihl :slightly_smiling_face:

**Comment by komamitsu** [comment]
Thanks for the ping @mseri. I'll take care of it.

**Pull request merged**
