### PR TITLE
tcpip: add missing bounds to mirage-clock-unix on old versions

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
Fix issues seen in #9824

**Comment by avsm** [comment]
bah 4.02 is complaining now

https://travis-ci.org/ocaml/opam-repository/jobs/255588247

**Comment by samoht** [comment]
I've pushed a fix for the 4.02 failure.

**Comment by samoht** [comment]
The remaining issues are infrastructure timetout (probably because GH is a bit flaky these days). So merging.

**Pull request merged**
