### PR TITLE
[new release] refl.0.4.1

### PR DESCRIPTION
**Pull request by thierry-martinez**
Vincent Siles reported that the upperbound on `ppxli`b version for `refl` was superfluous: `refl` is reported to work with the last version of `ppxlib.0.28.0`. Moreover the constraint `metapp >= 0.4.0` implies `ppxlib >= 0.22.0`, so we better have to propagate this constraint.

### CODE REVIEW

**Comment by samoht** [comment]
Something else seems to be wrong:
```
#=== ERROR while compiling refl.0.4.0 =========================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(https://github.com/thierry-martinez/refl/archive/v0.4.0.tar.gz)
# path                 ~/.opam/4.08/.opam-switch/build/refl.0.4.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p refl -j 71 @install
# exit-code            1
# env-file             ~/.opam/log/refl-7-b609e1.env
# output-file          ~/.opam/log/refl-7-b609e1.out
### output ###
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -open Stdcompat -w +32+34-40 -g -bin-annot -I ppx/.ppx_refl.objs/byte -I /home/opam/.opam/4.08/lib/findlib -I /home/opam/.opam/4.08/lib/fix -I /home/opam/.opam/4.08/lib/metapp -I /home/opam/.opam/4.08/lib/metapp/preutils -I /home/opam/.opam/4.08/lib/metapp/version_info -I /home/opam/.opam/4.08/lib/ocaml-compiler-libs/common -I /home/opam/.opam/4.08/lib/ocaml-compiler-libs/shadow -I /home/opam/.opam/4.08/lib/ocaml/compiler-libs -I /home/opam/.opam/4.08/lib/ppx_derivers -I /home/opam/.opam/4.08/lib/ppxlib -I /home/opam/.opam/4.08/lib/ppxlib/ast -I /home/opam/.opam/4.08/lib/ppxlib/astlib -I /home/opam/.opam/4.08/lib/ppxlib/print_diff -I /home/opam/.opam/4.08/lib/ppxlib/stdppx -I /home/opam/.opam/4.08/lib/ppxlib/traverse_builtins -I /home/opam/.opam/4.08/lib/sexplib0 -I /home/opam/.opam/4.08/lib/stdcompat -I /home/opam/.opam/4.08/lib/stdlib-shims -intf-suffix .ml -no-alias-deps -open Ppx_refl__ -o ppx/.ppx_refl.objs/byte/ppx_refl.cmo -c -impl ppx/ppx_refl.pp.ml)
# File "ppx/ppx_refl.ml", line 1639, characters 14-161:
# 1639 | ..............(Pext_decl (Pcstr_tuple [], Some
# 1640 |                 [%type: ([%t parameter_tuple], [%t parameter_sequence])
# 1641 |                   Refl.gadt_constraints]))...........................
# Error: The constructor Pext_decl expects 3 argument(s),
#        but is applied here to 2 argument(s)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlopt.opt -open Stdcompat -w +32+34-40 -g -I ppx/.ppx_refl.objs/byte -I ppx/.ppx_refl.objs/native -I /home/opam/.opam/4.08/lib/findlib -I /home/opam/.opam/4.08/lib/fix -I /home/opam/.opam/4.08/lib/metapp -I /home/opam/.opam/4.08/lib/metapp/preutils -I /home/opam/.opam/4.08/lib/metapp/version_info -I /home/opam/.opam/4.08/lib/ocaml-compiler-libs/common -I /home/opam/.opam/4.08/lib/ocaml-compiler-libs/shadow -I /home/opam/.opam/4.08/lib/ocaml/compiler-libs -I /home/opam/.opam/4.08/lib/ppx_derivers -I /home/opam/.opam/4.08/lib/ppxlib -I /home/opam/.opam/4.08/lib/ppxlib/ast -I /home/opam/.opam/4.08/lib/ppxlib/astlib -I /home/opam/.opam/4.08/lib/ppxlib/print_diff -I /home/opam/.opam/4.08/lib/ppxlib/stdppx -I /home/opam/.opam/4.08/lib/ppxlib/traverse_builtins -I /home/opam/.opam/4.08/lib/sexplib0 -I /home/opam/.opam/4.08/lib/stdcompat -I /home/opam/.opam/4.08/lib/stdlib-shims -intf-suffix .ml -no-alias-deps -open Ppx_refl__ -o ppx/.ppx_refl.objs/native/ppx_refl.cmx -c -impl ppx/ppx_refl.pp.ml)
# File "ppx/ppx_refl.ml", line 1639, characters 14-161:
# 1639 | ..............(Pext_decl (Pcstr_tuple [], Some
# 1640 |                 [%type: ([%t parameter_tuple], [%t parameter_sequence])
# 1641 |                   Refl.gadt_constraints]))...........................
# Error: The constructor Pext_decl expects 3 argument(s),
#        but is applied here to 2 argument(s)
```

**Comment by thierry-martinez** [comment]
I was wrong: the release `refl.0.4.0` was not compatible with `ppxlib.0.28.0`, but the master version was. I am trying to make a new release then.

**Comment by thierry-martinez** [comment]
It's all green now!

**Comment by raphael-proust** [comment]
Why is the ulimit hack necessary?  
Is it possible to do it without `bash`? This is not very portable.

If the issue is that the CI had errors on strange architectures, it's possible to merge with those. (It's often less of an issue than introducing non-portable hacks.)

**Comment by thierry-martinez** [comment]
Sorry for the late answer: these architectures are not so strange (they are tested in CI: Mac OS/arm32/arm64,...) Moreover the hack is already used by default in `clangml.4.7.0` and `clangml.4.8.0`: this pull-requet only backports the hack for `clangml.4.6.0`. I would prefer if we can keep the hack for now, and see in another pull-request if we can find a more portable way to set a bigger stack (I think it is important to keep the compatibility with Mac OS).

**Pull request merged**
