### PR TITLE
Clangml 3.8.0.2

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
About what camelus says: 3.8.0 is the clang version we want to support.
3.8.0.2 is the clangml version that corresponds to it.

**Comment by dsheets** [comment]
https://github.com/ocaml/opam-repository/pull/7674/files#diff-877065c500a6fdad331ef771bee8d887R3 is incorrectly claiming the library is version 3.8.0.

Also, why are you removing the previous version?

**Comment by UnixJunkie** [comment]
I removed the previous versions for clang-3.8.0 because they were not compiling on mac.
This one does, at least on one mac I have access to.

**Comment by dsheets** [comment]
It would be great to restrict that version with something like `available: [ os != "darwin" ]`. Also, we recommend not including the `name` and `version` fields in `opam` files (at least until repo signing comes online) to avoid the duplication of metadata which can result in the current version mismatch problem.

**Comment by UnixJunkie** [comment]
OK, I will send another pull request: I am trying to get rid of the system compiler restriction now.
Also, I love if there is no duplcation of info, thanks for the hints.
I will restore the previous versions too.

**Comment by UnixJunkie** [comment]
By the way: removing the name and version fields could be made opam-repository wide in a single pull request.

**Pull request closed without merging**
