### PR TITLE
Package cps_toolbox.0.2

### PR DESCRIPTION
**Pull request by soren-n**
### `cps_toolbox.0.2`
A partial OCaml standard library replacement written with continuation passing style in mind

---
* Homepage: https://github.com/soren-n/cps-toolbox
* Source repo: git+https://github.com/soren-n/cps-toolbox.git
* Bug tracker: https://github.com/soren-n/cps-toolbox/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks! Could you return the fix upstream?

**Comment by soren-n** [comment]
Sure, will do thanks!

**Comment by kit-ty-kate** [comment]
The package stopped working:
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - cps_toolbox.0.2: Bad checksum
```
Any clues why?

**Comment by kit-ty-kate** [comment]
It looks like you force pushed a tag after release, could you please put the old one back?

**Comment by soren-n** [comment]
Should have been moved back now! Wasn't aware it would have an effect, thought opam would reference the specific commit. TIL, sorry for any inconvenience!

**Pull request merged**
