### PR TITLE
[new release] merlin (3 packages) (5.0-502)

### PR DESCRIPTION
**Pull request by voodoos**
CHANGES:

Fri May 17 19:59:42 CET 2024

+ merlin binary
  - Support for OCaml 5.2 (ocaml/merlin#1757)
  - destruct: Removal of residual patterns (ocaml/merlin#1737, fixes ocaml/merlin#1560) 
  - Do not erase fields' names when destructing punned record fields (ocaml/merlin#1734, fixes ocaml/merlin#1661) 
  - Ignore SIGPIPE in the Merlin server process (ocaml/merlin#1746) - Fix lexing of quoted strings in comments (ocaml/merlin#1754, fixes ocaml/merlin#1753) 
  - Improve cursor position detection in longidents (ocaml/merlin#1756) 
  - Addition of a `merlin-lib.commands` library which disassociates the execution of commands from the `new_protocol`, from the binary, allowing it to be invoked from other projects (ocaml/merlin#1758) 
  - New occurrences backend: Don't index occurrences when `merlin.hide` attribute is present. (ocaml/merlin#1768) 
  - Use the new `uid_to_decl` table in 5.2's cmt files to get documentation. (ocaml/merlin#1773)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Could someone also do a separate PR to disable the preview packages for OCaml 5.2?

**Comment by voodoos** [comment]
> Could someone also do a separate PR to disable the preview packages for OCaml 5.2?

https://github.com/ocaml/opam-repository/pull/25913

**Comment by OlivierNicole** [comment]
Not sure if this is the right place to signal this, but I was able to `opam install merlin` without issues on 5.2.0, but on a 5.2.0+fp switch (i.e., created with `opam switch create 5.2.0+fp ocaml-option-fp`) opam wants to downgrade my ocaml to 5.1.1.

**Comment by voodoos** [comment]
@mseri maybe we should work on having this release merged now that the preview is disabled 🙂

Is there anything holding it back ?

**Comment by kit-ty-kate** [comment]
Emergency merge.

**Pull request merged**
