### PR TITLE
Alsa 0.2.3

### PR DESCRIPTION
**Pull request by smimram**
Compatible with OCaml 4.04.0.

### CODE REVIEW

**Comment by smimram** [comment]
I don't have a mac at hand. Could someone help me correct the dependencies on OSX?

**Comment by dsheets** [comment]
Homebrew at least doesn't ship anything like `libasound`. Perhaps this package is Linux-specific?

**Comment by smimram** [comment]
I doubt this because ALSA is quite a popular library and it used to work... @toots ?

**Comment by toots** [comment]
ALSA is indeed linux-only. You might want to add `available: [os = "linux"]` at the bottom of the `opam` file..

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
