### PR TITLE
fstreams.0.1 - via opam-publish

### PR DESCRIPTION
**Pull request by tel**
Functional, lazy, infinite streams.

A very standard infinite data structure is the stream which lazily
determines its current and next values and even whether they exist or
not! This data structure is useful for describing computations which
are generated and consumed step-by-step and is a powerful basic tool
for many lazy algorithms.

Included in this module are two submodules, Infinite and
Finite. Infinite streams are streams which are guaranteed to always
have a next value and Finite streams are streams which may terminate
but are not obliged to.

Mathematically, Infinite streams are the greatest fixed point of the
functor F X = A * X and Finite streams are the greatest fixed point of
the functor F X = 1 + A * X.

---
* Homepage: https://github.com/tel/ocaml-fstreams
* Source repo: https://github.com/tel/ocaml-fstreams.git
* Bug tracker: https://github.com/tel/ocaml-fstreams/issues

---
Pull-request generated by opam-publish v0.2.1

### CODE REVIEW

**Comment by dsheets** [comment]
OASIS is still a dependency. Either add OASIS to the dependency list or include OASIS-generated files in the package (preferred).

**Comment by avsm** [comment]
If you want to avoid repackaging it, then just pushing `oasis` to the `depends` field of this pull request is fine.

**Comment by tel** [comment]
I'd like to avoid the Oasis dependency. To do so I need to include all of the appropriate Oasis-generated files which I presume is done by using `oasis setup -setup-update weak` and including files like `./configure`, `Makefile`, and `setup.ml`?

**Comment by dsheets** [comment]
That's correct. Usually people use `-setup-update none` (the default) but `weak` should work fine. Make sure to include the `META` file as well if there is one.

**Comment by tel** [comment]
Will do—what's the difference between `none` and `weak`?

**Comment by tel** [comment]
Still getting used to this process, so accidentally opened a new PR here: https://github.com/ocaml/opam-repository/pull/3579

**Comment by dsheets** [comment]
`none` doesn't do anything related to the `oasis` command. `weak` makes a build system which checks the `_oasis` metadata file for changes based on a hash baked into the build system. If the `_oasis` file has been changed, a build system made with `weak` will rebuild itself... as I understand it.

**Pull request closed without merging**
