### PR TITLE
add ocamleditor 1.15.0

### PR DESCRIPTION
**Pull request by ftovagliari**

### CODE REVIEW

**Comment by arbipher** [comment]
The failure cases on CI are on `ocamldiff.1.1`

```
# ocamlfind: odiff.cmxs: No such file or directory
```

However, the install script for `packages/ocamldiff.1.1/opam` with `ocamldiff.1.1/Makefile` should have that file via
 (in `Makefile` target) `install` -> `opt` -> `odiff.cmxs`.
 
 I can build both packages (`ocamldiff.1.1` `ocamleditor.1.15.9-ocaml414`) locally. No idea yet.

**Comment by ftovagliari** [comment]
The archive https://framagit.org/zoggy/ocamldiff/-/archive/1.1/ocamldiff-1.1.tar.gz defined in the ocamldiff opam package contains an incorrect Makefile. The maintainer of ocamldiff already knows about this.
On the other hand, the "pin-depends" field I added in the ocamleditor opam file (which points to the latest and correct version of ocamldiff) seems to only take effect locally.
I'm looking for an alternative solution.

**Comment by mseri** [comment]
You can ask @zoggy for a new release of ocamldiff or vendor its sources within your package (but that is easier to do with dune)

**Comment by zoggy** [comment]
Hello,
I was not aware of this Makefile problem (do you have some ref about it ?). I will dunify the build and make a new release in january.

**Comment by ftovagliari** [comment]
@zoggy Ok, thank you very much. Here is the ref. https://framagit.org/zoggy/ocamldiff/-/issues/7

**Comment by zoggy** [comment]
Thanks. I was looking in xmldiff. I really needed these holidays...

A new release (1.2) of ocamldiff should be available soon: https://github.com/ocaml/opam-repository/pull/25046

**Comment by mseri** [comment]
This is failing now with
```
# cp -v ocamleditor /home/opam/.opam/4.14/bin/ocamleditor
# cp: cannot stat 'ocamleditor': No such file or directory
```
Should I close this PR in favour of https://github.com/ocaml/opam-repository/pull/25053 ?

**Comment by mseri** [comment]
Looks like both PRs have the same issue. Opam has a sandbox, you cannot write outside the build folder.
You should generate a `ocamleditor.install` file in the sources folder with the following content
```
bin: [
  "ocamleditor"
  "ocamleditor_launch"
  ...
]
```
and the corresponding lib, doc, etc... if any.
The description of the `.install` files is here: https://opam.ocaml.org/doc/Manual.html#lt-pkgname-gt-install

**Comment by ftovagliari** [comment]
> This is failing now with
> 
> ```
> # cp -v ocamleditor /home/opam/.opam/4.14/bin/ocamleditor
> # cp: cannot stat 'ocamleditor': No such file or directory
> ```
> 
> Should I close this PR in favour of #25053 ?

Yes please

**Comment by ftovagliari** [comment]
> Looks like both PRs have the same issue. Opam has a sandbox, you cannot write outside the build folder. You should generate a `ocamleditor.install` file in the sources folder with the following content
> 
> ```
> bin: [
>   "ocamleditor"
>   "ocamleditor_launch"
>   ...
> ]
> ```
> 
> and the corresponding lib, doc, etc... if any. The description of the `.install` files is here: https://opam.ocaml.org/doc/Manual.html#lt-pkgname-gt-install

OK thank you. I will follow these guidelines.

**Comment by mseri** [comment]
Sorry @ftovagliari, I had misread the error and your opam file. Using `install` as you do is fine, the issue is that the `ocamleditor` file seems to not be present

**Pull request closed without merging**
