### PR TITLE
Release merlin and merlin-lib v4.8-{500,414}

### PR DESCRIPTION
**Pull request by voodoos**

### CODE REVIEW

**Comment by voodoos** [comment]
Look like a package (`gopcaml`) breaks with this new release of Merlin. I added a constraint on it, but I am not sure that this is the way to go ? Should I add a "conflict" instead ? Hopefully this will be fixed upstream at some point (cc @Gopiandcode)

**Comment by voodoos** [comment]
The error persists, so I guess the package was already broken ?

**Comment by voodoos** [comment]
@kit-ty-kate makes sense :-)

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
