### PR TITLE
jsoo_router.1.0 - via opam-publish

### PR DESCRIPTION
**Pull request by xvw**
Jsoo_router provide an extension point to manage route with the Hash

Jsoo_router is a an extension point to write easily "single-page-app".
The library provide a typesafe way to define variables in the routes.
You can read more informations here : https://github.com/xvw/jsoo_router

---
* Homepage: https://github.com/xvw/jsoo_router
* Source repo: https://github.com/xvw/jsoo_router.git
* Bug tracker: https://github.com/xvw/jsoo_router/issues

---

Pull-request generated by opam-publish v0.3.3

### CODE REVIEW

**Comment by samoht** [comment]
Some compilation errors:

```
#=== ERROR while installing jsoo_router.1.0 ===================================#
# opam-version 1.2.2
# os           linux
# command      ./configure --prefix=/home/travis/.opam/4.04.0
# path         /home/travis/.opam/4.04.0/build/jsoo_router.1.0
# compiler     4.04.0
# exit-code    1
# env-file     /home/travis/.opam/4.04.0/build/jsoo_router.1.0/jsoo_router-14399-89b24d.env
# stdout-file  /home/travis/.opam/4.04.0/build/jsoo_router.1.0/jsoo_router-14399-89b24d.out
# stderr-file  /home/travis/.opam/4.04.0/build/jsoo_router.1.0/jsoo_router-14399-89b24d.err
### stderr ###
# sh: 1: /Users/xvw/.opam/4.04.0/bin/ocamlc.opt: not found
# sh: 1: /Users/xvw/.opam/4.04.0/bin/ocamlfind: not found
# W: Failure("Command ''/Users/xvw/.opam/4.04.0/bin/ocamlfind' query -format %d compiler-libs.common > '/tmp/oasis-850360.txt'' terminated with error code 127")
# E: Cannot find findlib package compiler-libs.common
# E: Failure("1 configuration error")
```

**Comment by xvw** [comment]
Thanks for the point... I'm a really noob and I don't understand why I have this error.

**Comment by samoht** [comment]
@xvw You put `setup.data` in the distribution archive, so the paths to the binaries are hard-coded to your local ones:
 
```
/Users/xvw/.opam/4.04.0/bin/ocamlc.opt
```
Which should be:
```
/home/travis/.opam/4.04.0/<...>
```

Just remove `setup.data` and that should be ok.

**Comment by xvw** [comment]
It seems good ! 
Thanks a lot for your help @samoht !

**Comment by samoht** [comment]
All working now, merging!

**Pull request merged**
