### PR TITLE
Add JsOfOCairo.1.1.0

### PR DESCRIPTION
**Pull request by jacquev6**
New version

### CODE REVIEW

**Comment by hcarty** [comment]
Could you add the license to the opam file and fix the commit message typo? 'OCairo' vs 'OCaml'.

**Comment by jacquev6** [comment]
Thanks for spotting the typo, my bad!
Just for information, the license was removed by `opam-publish prepare`.
I fixed both. Thanks!

**Comment by jpdeplaix** [comment]
Looks like your tests are failing:
```
#=== ERROR while installing JsOfOCairo.1.1.0 ==================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder runtest -p JsOfOCairo
# path         /home/travis/.opam/system/build/JsOfOCairo.1.1.0
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/JsOfOCairo.1.1.0/JsOfOCairo-11752-c61e7b.env
# stdout-file  /home/travis/.opam/system/build/JsOfOCairo.1.1.0/JsOfOCairo-11752-c61e7b.out
# stderr-file  /home/travis/.opam/system/build/JsOfOCairo.1.1.0/JsOfOCairo-11752-c61e7b.err
### stderr ###
# [...]
# File "tst/jbuild", line 29, characters 12-174:
# Error: Library "General" not found.
# -> required by library "Tests" in _build/default/tst/Tests
# -> required by library "Tests" in _build/default/tst/Tests
# Hint: try: jbuilder external-lib-deps --missing -p JsOfOCairo @runtest
# File "tst/jbuild", line 53, characters 12-180:
# Error: Library "General" not found.
# -> required by library "Tests" in _build/default/tst/Tests
# -> required by library "Tests" in _build/default/tst/Tests
# Hint: try: jbuilder external-lib-deps --missing -p JsOfOCairo @runtest
```

**Comment by jacquev6** [comment]
@jpdeplaix Thanks... Let's not publish 1.1.0. I'll open a new PR with 1.1.1 when I have fixed that.

Sorry for the noise.

**Pull request closed without merging**
