### PR TITLE
[new release] obatcher (1.1)

### PR DESCRIPTION
**Pull request by koonwen**
A Framework for building Batched Concurrent Data Structures

- Project page: <a href="https://github.com/koonwen/obatcher">https://github.com/koonwen/obatcher</a>
- Documentation: <a href="https://koonwen.github.io/obatcher">https://koonwen.github.io/obatcher</a>

##### CHANGES:

	- Add multififo scheduler to tests
	- Add btree example
	- Add polymorphic batcher

### CODE REVIEW

**Comment by shonfeder** [comment]
Thanks for publishing the update :)

The only CI issues is

```
Error in obatcher.1.1: Maintainer email missing. Please add a maintainer email to the opam file. Maintainer: Lee Koon Wen
```

Which should be an easy fix, tho this lint is proving a bit controversial https://github.com/ocaml/infrastructure/issues/152

**Comment by koonwen** [comment]
Déjà vu moment. Sorry about that, made the changes!

**Comment by shonfeder** [comment]
> Déjà vu moment. Sorry about that, made the changes!

No worries at all! We are just rolling this out really :) Thanks again!

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
