### PR TITLE
added packages/parany/parany.7.0.2

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by mseri** [comment]
We could add a lower bound on ocaml unless you prefer to fix this for 4.02:
```
#=== ERROR while compiling parany.7.0.1 =======================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.02.3 | pinned(https://github.com/UnixJunkie/parany/archive/v7.0.1.tar.gz)
# path                 ~/.opam/4.02/.opam-switch/build/parany.7.0.1
# command              ~/.opam/4.02/bin/dune build -p parany -j 2
# exit-code            1
# env-file             ~/.opam/log/parany-23-bc5b41.env
# output-file          ~/.opam/log/parany-23-bc5b41.out
### output ###
#       ocamlc src/.parany.objs/byte/parany.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.02/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.parany.objs/byte -I /home/opam/.opam/4.02/lib/bytes -I /home/opam/.opam/4.02/lib/equeue -I /home/opam/.opam/4.02/lib/netcamlbox -I /home/opam/.opam/4.02/lib/netmulticore -I /home/opam/.opam/4.02/lib/netplex -I /home/opam/.opam/4.02/lib/netstring -I /home/opam/.opam/4.02/lib/netsys -I /home/opam/.opam/4.02/lib/ocaml/threads -I /home/opam/.opam/4.02/lib/rpc -I /home/opam/.opam/4.02/lib/setcore -intf-suffix .ml -no-alias-deps -o src/.parany.objs/byte/parany.cmo -c -impl src/parany.ml)
# File "src/parany.ml", line 54, characters 8-19:
# Error: Unbound value Unix.sleepf
# Hint: Did you mean sleep?
#     ocamlopt src/.parany.objs/native/parany.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.02/bin/ocamlopt.opt -w -40 -g -I src/.parany.objs/byte -I src/.parany.objs/native -I /home/opam/.opam/4.02/lib/bytes -I /home/opam/.opam/4.02/lib/equeue -I /home/opam/.opam/4.02/lib/netcamlbox -I /home/opam/.opam/4.02/lib/netmulticore -I /home/opam/.opam/4.02/lib/netplex -I /home/opam/.opam/4.02/lib/netstring -I /home/opam/.opam/4.02/lib/netsys -I /home/opam/.opam/4.02/lib/ocaml/threads -I /home/opam/.opam/4.02/lib/rpc -I /home/opam/.opam/4.02/lib/setcore -intf-suffix .ml -no-alias-deps -o src/.parany.objs/native/parany.cmx -c -impl src/parany.ml)
# File "src/parany.ml", line 54, characters 8-19:
# Error: Unbound value Unix.sleepf
# Hint: Did you mean sleep?
```

**Comment by UnixJunkie** [comment]
I will try to fix this.

**Comment by UnixJunkie** [comment]
Fixed, so new minor version.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
