### PR TITLE
[new release] x509 (0.12.0)

### PR DESCRIPTION
**Pull request by hannesm**
Public Key Infrastructure (RFC 5280, PKCS) purely in OCaml

- Project page: <a href="https://github.com/mirleft/ocaml-x509">https://github.com/mirleft/ocaml-x509</a>
- Documentation: <a href="https://mirleft.github.io/ocaml-x509/doc">https://mirleft.github.io/ocaml-x509/doc</a>

##### CHANGES:

* FEATURE PKCS12 support (mirleft/ocaml-x509#114 by @hannesm)
* FEATURE ECDSA and EDDSA support via mirage-crypto-ec (mirleft/ocaml-x509#145 by @hannesm)
  This breaks some clients since the Private_key.t and Public_key.t variants
  are extended (may result in partial pattern matches of users of this library).
* CRL.is_revoked has `crls` as last parameter to avoid warning 16
  (4.12 compatibility) (mirleft/ocaml-x509#144 by @hannesm)
* Signing_request.sign: add optional labelled argument `~subject` to allow
  changing the subject when signing a signing request (mirleft/ocaml-x509#139 by @reynir)
* BUGFIX Encoding of Distinguished_name components (adhere to specification)
  DomainComponent and EMail are now serialised using a IA5String; Serialnumber,
  CountryName and DnQualifier as PrintableString (reported in mirleft/ocaml-x509#69, fixed mirleft/ocaml-x509#140
  by @NightBlues)
* BREAKING Remove `~sloppy` from Private_key.decode_{pem,der}. The seemingly
  bad RSA keys were valid and should have been accepted by mirage-crypto.
  (mirleft/ocaml-x509#142 by @psafont)

### CODE REVIEW

**Comment by hannesm** [comment]
I'll take a look at the reverse dependencies, some may be broken (these which deconstruct Public_key.t / Private_key.t).

**Comment by hannesm** [comment]
I pushed upper bounds to reverse dependencies which either failed or I was able to spot "partial-match" in the log output. As commented above, the variant Public_key.t and Private_key.t are extended in this release of x509 (and now include next to RSA keys as well EC keys).
- albatross @hannesm 
- awa @hannesm 
- capnp-rpc-net @talex5 
- current_github @talex5 
- dkim @dinosaure 
- jose @ulrikstrid
- letsencrypt @hannesm 
- tls, tls-mirage @hannesm 

IMHO this PR is now good to be merged (feel free to search for further partial matches). When merged, I'll prepare subsequent releases for the packages I'm maintaining of the above list.

**Comment by hannesm** [comment]
from my point of view, this is good to be merged (and a merge will unblock other releases)

**Comment by avsm** [comment]
Looks good to me from scanning the CI logs.  A post on discuss.ocaml.org with the changelog would be appreciated, as it will give a headsup to any projects not publishing on opam-repository.

**Comment by hannesm** [comment]
Thanks @avsm. Indeed, I want to get a release of tls out (which entails some API changes as well) and post an update to discuss.

**Pull request merged**
