### PR TITLE
Remove old Mirage/Solo5 package releases

### PR DESCRIPTION
**Pull request by mato**
These packages are long out of date and (at least in the 0.1.x series releases) broken in today's Mirage/Solo5 package universe.

I'd like to remove them from the OPAM repository as there is no reason for someone to install them today and keeping them around complicates PRs such as #11373.

### CODE REVIEW

**Comment by hannesm** [comment]
LGTM (and CI passes)! related to #11194 -- /cc @yomimono @avsm who may have an opinion on removing releases

**Comment by avsm** [comment]
it's a real pity to lose our history. once the right upper bounds are in place, it should mostly never break again...

**Comment by mato** [comment]
@avsm These packages are known-broken (have incorrect dependencies, etc.) so they do not build even with the upper bounds set (see #11373). I could try and figure out the right upper bounds but TBH for historic packages that's just pointless busywork.

**Comment by avsm** [comment]
If you set upper bounds on them so that they dont affect the other PRs for recent packages (i.e. constrain things so that these old packages never get selected), I can look at this end of next week to get them building again.   Am very busy with some other work until then

**Comment by hannesm** [comment]
since this is not urgent, we can leave this PR open for now -- and merge before just before solo5-0.3.0 is released, or merge a different PR with upper bounds adjustments if someone finds the time to do them

**Comment by AltGr** [comment]
I don't understand the argument about losing history... This is git right ?

**Comment by AltGr** [comment]
We may want to setup an attic branch or repo that gathers all removed package definitions, for easier access.

**Comment by gasche** [comment]
What about just setting `available: [false]` to disable those packages while keeping them in-repo?

**Comment by yomimono** [comment]
`available: [false]` or removing them and depending on git's history are both fine with me.  For packages that people might really want to install for reproducibility reasons (validating published results, etc), I'd prefer the first since it seems to me to be easier to edit that line away locally than to go digging around in history, but I don't think these packages are those.

**Comment by samoht** [comment]
Would it be possible to add the right version constraints instead of disabling them completely? I am willing to help find what these constraints; expect a few PRs soon.

**Comment by samoht** [comment]
After pocking around a bit, I haven't found a combination of versions which were causing a compilation issue...

**Comment by mato** [comment]
@samoht There is more detail on the failing package combinations in https://github.com/ocaml/opam-repository/pull/11373#issuecomment-364128638 which is what motivated me to open this PR in the first place.

**Comment by samoht** [comment]
@mato 

> the old mirage-console-solo5.0.1.1 release is basically broken. 

Any more details/way to reproduce it? I'm happy to try/test/fix things but I haven't been able to find what is failing.

**Comment by mato** [comment]
@samoht:

> Any more details/way to reproduce it? I'm happy to try/test/fix things but I haven't been able to find what is failing.

It's pretty straightforward -- create a new, empty, opam switch from scratch (I tried just now with 4.04.2), and try and install some of the historic package versions into it, e.g.

    opam install mirage-console-solo5.0.1.1

You'll find that there are numerous errors during the package build -- I tried installing `cstruct-lwt` to fix the missing dependency, and then ran into a mismatch with the `mirage-types`, so someone would have to work backwards in history to figure out what the right constraints are to get this (ancient, still OASIS-based!) version of the package to install.

You'd then need to similarly check various other intermediate versions of those packages to check that they are also installable.

Personally I don't think its worth the work, but feel free.

**Comment by samoht** [comment]
The mirage-console-solo5 constraints are fixed in #12049

**Comment by mato** [comment]
@samoht Thanks. I think you've missed `mirage-bootvar-solo5.0.1.1` which presumably needs at least the constraint on `mirage-types`.

By the way, are you testing this with OPAM 1? The reason I ask is that since I submitted #11373 I've upgraded my OPAM install to 2.0-rc, which appears to give slightly different results with the unfixed packages (more of them work); presumably this is due to different solver results.

**Comment by samoht** [comment]
@mato bootvar seems to compile file with old versions of mirage, I guess these signatures haven't changed much since the beginning of the project.

I am testing with both opam 1.2 and opam 2 depending on the machine I am with; the solver has changed between these two versions so I am not very surprised, but if you see something unusual with opam2 it's worth reporting it I think.

**Comment by samoht** [comment]
I think I fixed all the issues that I could find so I think we can close that PR. If you please other constraints issues I'll be happy to debug and fix them (seriously, I like doing this kind of stuff in my spare time :p)

**Pull request closed without merging**
