### PR TITLE
objc.0.0.1 - via opam-publish

### PR DESCRIPTION
**Pull request by fxfactorial**
Introspect Objective-C objects from OCaml
Manipulate, introspect Objective-C Objects from OCaml!

---
- Homepage: http://hyegar.com
- Source repo: https://github.com/fxfactorial/ocaml-objc.git
- Bug tracker: https://github.com/fxfactorial/ocaml-objc/issues

---

Pull-request generated by opam-publish v0.3.2

### CODE REVIEW

**Comment by fxfactorial** [comment]
Oops, forgot to add OS constraint for just darwin.

**Comment by dsheets** [comment]
Could you add the OS constraint to this PR? Without these constraints, auto-builders have more noise and QA is unnecessarily harder.

**Comment by fxfactorial** [comment]
@dsheets ya, will do

**Comment by fxfactorial** [comment]
I'm super expanding this so will come back to it soonish, will force push later on.

**Comment by samoht** [comment]
@fxfactorial what's the status of this PR? Should we close it?

**Comment by fxfactorial** [comment]
@samoht sorry for delay, I had some new ideas that I was playing with and haven't finished.

**Comment by avsm** [comment]
@fxfactorial I'll close this one out for now since it's been pending for months, but feel free to reopen it when you get back to the project!

**Pull request closed without merging**
