### PR TITLE
bastet.2.0.0: Disable the tests (non-deterministic)

### PR DESCRIPTION
**Pull request by kit-ty-kate**
cc @Risto-Stevcev 
```
#=== ERROR while compiling bastet.2.0.0 =======================================#
# context              2.1.0 | linux/x86_64 | ocaml-base-compiler.4.12.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.12.0/.opam-switch/build/bastet.2.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p bastet -j 47 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/bastet-3424-9fb1fe.env
# output-file          ~/.opam/log/bastet-3424-9fb1fe.out
### output ###
#  test_bastet alias bastet/test/runtest (exit 1)
# (cd _build/default/bastet/test && ./test_bastet.exe)
# qcheck random seed: 418342745
# 
# Testing `Ocaml_abstract'.
# This run has ID `95D5D1C9-2859-4C5A-BF07-57202F4CD701'.
# 
#   [OK]          Array.zip_with                             0   should zip_wit...
#   [OK]          Array.zip                                  0   should zip two...
#   [OK]          Array.Foldable                             0   should do a le...
#   [OK]          Array.Foldable                             1   should do a ri...
#   [OK]          Array.Foldable                             2   should do a ma...
#   [OK]          Array.Foldable                             3   should do a ma...
#   [OK]          Array.Unfoldable                           0   should do an u...
#   [OK]          Array.Unfoldable                           1   should do an u...
#   [OK]          Array.Traversable                          0   should travers...
#   [OK]          Array.Traversable                          1   should sequenc...
#   [OK]          Array.Show                                 0   should show th...
#   [OK]          Array.Extend                               0   should satisfy...
#   [OK]          Array.Alt.alt                              0   should order t...
#   [OK]          Array.Functor                              0   should satisfy...
#   [OK]          Array.Functor                              1   should satisfy...
#   [OK]          Array.Apply                                0   should satisfy...
#   [OK]          Array.Applicative                          0   should satisfy...
#   [OK]          Array.Applicative                          1   should satisfy...
#   [OK]          Array.Applicative                          2   should satisfy...
#   [OK]          Array.Monad                                0   should satisfy...
#   [OK]          Array.Monad                                1   should satisfy...
#   [OK]          Array.Alt                                  0   should satisfy...
#   [OK]          Array.Alt                                  1   should satisfy...
#   [OK]          Array.Eq                                   0   should satisfy...
#   [OK]          Array.Eq                                   1   should satisfy...
#   [OK]          Array.Eq                                   2   should satisfy...
#   [OK]          Array.Ord                                  0   should satisfy...
#   [OK]          Array.Ord                                  1   should satisfy...
#   [OK]          Array.Ord                                  2   should satisfy...
#   [OK]          Array.Invariant                            0   should satisfy...
#   [OK]          Array.Invariant                            1   should satisfy...
#   [OK]          Bool.Conjunctive.Medial_Magma              0   should satisfy...
#   [OK]          Bool.Conjunctive.Semigroup                 0   should satisfy...
#   [OK]          Bool.Conjunctive.Monoid                    0   should satisfy...
#   [OK]          Bool.Disjunctive.Medial_Magma              0   should satisfy...
#   [OK]          Bool.Disjunctive.Semigroup                 0   should satisfy...
#   [OK]          Bool.Disjunctive.Monoid                    0   should satisfy...
#   [OK]          Bool.Eq                                    0   should satisfy...
#   [OK]          Bool.Eq                                    1   should satisfy...
#   [OK]          Bool.Eq                                    2   should satisfy...
#   [OK]          Bool.Ord                                   0   should satisfy...
#   [OK]          Bool.Ord                                   1   should satisfy...
#   [OK]          Bool.Ord                                   2   should satisfy...
#   [OK]          Bool.Join_Semilattice                      0   should satisfy...
#   [OK]          Bool.Join_Semilattice                      1   should satisfy...
#   [OK]          Bool.Join_Semilattice                      2   should satisfy...
#   [OK]          Bool.Meet_Semilattice                      0   should satisfy...
#   [OK]          Bool.Meet_Semilattice                      1   should satisfy...
#   [OK]          Bool.Meet_Semilattice                      2   should satisfy...
#   [OK]          Bool.Bounded_Join_Semilattice              0   should satisfy...
#   [OK]          Bool.Bounded_Meet_Semilattice              0   should satisfy...
#   [OK]          Bool.Lattice                               0   should satisfy...
#   [OK]          Bool.Bounded_Lattice                       0   should satisfy...
#   [OK]          Bool.Distributive_Lattice                  0   should satisfy...
#   [OK]          Bool.Bounded_Distributive_Lattice          0   should satisfy...
#   [OK]          Bool.Heyting_Algebra                       0   should satisfy...
#   [OK]          Bool.Heyting_Algebra                       1   should satisfy...
#   [OK]          Bool.Involutive_Heyting_Algebra            0   should satisfy...
#   [OK]          Bool.Boolean_Algebra                       0   should satisfy...
#   [OK]          Default.Foldable                           0   should do a le...
#   [OK]          Default.Traversable                        0   should travers...
#   [OK]          Float.Additive.Medial_Magma                0   should satisfy...
#   [OK]          Float.Additive.Semigroup                   0   should satisfy...
#   [OK]          Float.Additive.Monoid                      0   should satisfy...
#   [OK]          Float.Additive.Quasigroup                  0   should satisfy...
#   [OK]          Float.Additive.Loop                        0   should satisfy...
#   [OK]          Float.Additive.Group                       0   should satisfy...
#   [OK]          Float.Additive.Group                       1   should satisfy...
#   [OK]          Float.Additive.Abelian_Group               0   should satisfy...
#   [OK]          Float.Multiplicative.Medial_Magma          0   should satisfy...
#   [OK]          Float.Multiplicative.Semigroup             0   should satisfy...
#   [OK]          Float.Multiplicative.Monoid                0   should satisfy...
#   [OK]          Float.Multiplicative.Quasigroup            0   should satisfy...
#   [OK]          Float.Multiplicative.Loop                  0   should satisfy...
#   [OK]          Float.Subtractive.Medial_Magma             0   should satisfy...
#   [OK]          Float.Subtractive.Quasigroup               0   should satisfy...
#   [OK]          Float.Divisive.Medial_Magma                0   should satisfy...
# > [FAIL]        Float.Divisive.Quasigroup                  0   should satisfy...
#   [OK]          Float.Eq                                   0   should satisfy...
#   [OK]          Float.Eq                                   1   should satisfy...
#   [OK]          Float.Eq                                   2   should satisfy...
#   [OK]          Float.Ord                                  0   should satisfy...
#   [OK]          Float.Ord                                  1   should satisfy...
#   [OK]          Float.Ord                                  2   should satisfy...
#   [OK]          Float.Bounded                              0   should satisfy...
#   [OK]          Float.Semiring                             0   should satisfy...
#   [OK]          Float.Semiring                             1   should satisfy...
#   [OK]          Float.Semiring                             2   should satisfy...
#   [OK]          Float.Semiring                             3   should satisfy...
#   [OK]          Float.Semiring                             4   should satisfy...
#   [OK]          Float.Semiring                             5   should satisfy...
#   [OK]          Float.Ring                                 0   should satisfy...
#   [OK]          Float.Commutative_Ring                     0   should satisfy...
#   [OK]          Float.Division_Ring                        0   should be a no...
#   [OK]          Float.Division_Ring                        1   should satisfy...
#   [OK]          Float.Euclidean_Ring                       0   should be a no...
#   [OK]          Float.Euclidean_Ring                       1   should satisfy...
#   [OK]          Float.Euclidean_Ring                       2   should satisfy...
#   [OK]          Float.Euclidean_Ring                       3   should satisfy...
#   [OK]          Float.Euclidean_Ring                       4   should satisfy...
#   [OK]          Float.Field                                0   should satisfy...
#   [OK]          List.Foldable                              0   should do a le...
#   [OK]          List.Foldable                              1   should do a ri...
#   [OK]          List.Foldable                              2   should do a ma...
#   [OK]          List.Foldable                              3   should do a ma...
#   [OK]          List.Unfoldable                            0   should do an u...
#   [OK]          List.Unfoldable                            1   should do an u...
#   [OK]          List.Traversable                           0   should travers...
#   [OK]          List.Traversable                           1   should sequenc...
#   [OK]          List.Show                                  0   should show th...
#   [OK]          List.Alt.alt                               0   should order t...
#   [OK]          List.Functor                               0   should satisfy...
#   [OK]          List.Functor                               1   should satisfy...
#   [OK]          List.Apply                                 0   should satisfy...
#   [OK]          List.Applicative                           0   should satisfy...
#   [OK]          List.Applicative                           1   should satisfy...
#   [OK]          List.Applicative                           2   should satisfy...
#   [OK]          List.Monad                                 0   should satisfy...
#   [OK]          List.Monad                                 1   should satisfy...
#   [OK]          List.Alt                                   0   should satisfy...
#   [OK]          List.Alt                                   1   should satisfy...
#   [OK]          List.Eq                                    0   should satisfy...
#   [OK]          List.Eq                                    1   should satisfy...
#   [OK]          List.Eq                                    2   should satisfy...
#   [OK]          Option.Infix                               0   should apply a...
#   [OK]          Option.Foldable                            0   should do a le...
#   [OK]          Option.Foldable                            1   should do a ri...
#   [OK]          Option.Foldable                            2   should do a ma...
#   [OK]          Option.Foldable                            3   should do a ma...
#   [OK]          Option.Traversable                         0   should travers...
#   [OK]          Option.Traversable                         1   should sequenc...
#   [OK]          Option.Semigroup                           0   should satisfy...
#   [OK]          Option.Monoid                              0   should satisfy...
#   [OK]          Option.Functor                             0   should satisfy...
#   [OK]          Option.Functor                             1   should satisfy...
#   [OK]          Option.Apply                               0   should satisfy...
#   [OK]          Option.Applicative                         0   should satisfy...
#   [OK]          Option.Applicative                         1   should satisfy...
#   [OK]          Option.Applicative                         2   should satisfy...
#   [OK]          Option.Monad                               0   should satisfy...
#   [OK]          Option.Monad                               1   should satisfy...
#   [OK]          Option.Alt                                 0   should satisfy...
#   [OK]          Option.Alt                                 1   should satisfy...
#   [OK]          Option.Alternative                         0   should satisfy...
#   [OK]          Option.Alternative                         1   should satisfy...
#   [OK]          Option.Plus                                0   should satisfy...
#   [OK]          Option.Plus                                1   should satisfy...
#   [OK]          Option.Eq                                  0   should satisfy...
#   [OK]          Option.Eq                                  1   should satisfy...
#   [OK]          Option.Eq                                  2   should satisfy...
#   [OK]          Option.Ord                                 0   should satisfy...
#   [OK]          Option.Ord                                 1   should satisfy...
#   [OK]          Option.Ord                                 2   should satisfy...
#   [OK]          String.Semigroup                           0   should satisfy...
#   [OK]          String.Monoid                              0   should satisfy...
#   [OK]          String.Quasigroup                          0   should satisfy...
#   [OK]          String.Loop                                0   should satisfy...
#   [OK]          String.Eq                                  0   should satisfy...
#   [OK]          String.Eq                                  1   should satisfy...
#   [OK]          String.Eq                                  2   should satisfy...
#   [OK]          String.Ord                                 0   should satisfy...
#   [OK]          String.Ord                                 1   should satisfy...
#   [OK]          String.Ord                                 2   should satisfy...
# 
# ┌──────────────────────────────────────────────────────────────────────────────┐
# │ [FAIL]        Float.Divisive.Quasigroup                  0   should sati...  │
# └──────────────────────────────────────────────────────────────────────────────┘
# 
# test `should satisfy associativity` failed on ≥ 1 cases:
# (0.0335737842802, 75.2803803749, 80.3610792556)
# 
# [exception] test `should satisfy associativity` failed on ≥ 1 cases:
# (0.0335737842802, 75.2803803749, 80.3610792556)
# 
# Logs saved to `~/.opam/4.12.0/.opam-switch/build/bastet.2.0.0/_build/default/bastet/test/_build/_tests/Ocaml_abstract/Float.Divisive.Quasigroup.000.output'.
#  ──────────────────────────────────────────────────────────────────────────────
# 
# Full test results in `~/.opam/4.12.0/.opam-switch/build/bastet.2.0.0/_build/default/bastet/test/_build/_tests/Ocaml_abstract'.
# 1 failure! in 0.616s. 163 tests run.
```

### CODE REVIEW

**Comment by Risto-Stevcev** [comment]
Ah yeah, I think this is an issue with Ints and Floats, something with the range (bounds) I set up for them. I think it always passes if the range is low enough.
Is it possible to keep the tests?

**Comment by kit-ty-kate** [comment]
>  Is it possible to keep the tests?

Well no, the tests are non-deterministic so it's really annoying for users wondering what they broke. It makes our CI systems unreliable and source of confusion. They can be kept on the next release if the issue is fixed ofc though.

**Comment by Risto-Stevcev** [comment]
Ok, just to clarify though -- I can't keep write any library for opam with non-deterministic tests right? I saw you removed the dependencies like alcotest, qcheck, mdx as well as the `@run-test`. Or do I have to remove all of these tests? they won't run without the dependencies

**Comment by kit-ty-kate** [comment]
> I can't keep or write any library for opam with non-deterministic tests right?

I don't really get the question. I mean usually people tend to avoid non-deterministic tests, when they happen it's usually not on purpose. We usually detect them a few weeks after they're added, if one is detected the tests are simply disabled.

Tests in opam-repository are not ran by users so it shouldn't affect anyone but the various opam CI systems.

> I saw you removed the dependencies like alcotest, qcheck, mdx as well as the `@run-test`.

Yes, it's more because there aren't any tests to run so they're useless dependencies for this particular version. It'd be sad to make CI machine use time that's not used in any way.

>Or do I have to remove all of these tests? they won't run without the dependencies

Sorry if I was confusing. You don't have anything to do per-say. I'm simply alerting you that your tests are buggy and that you might want to fix them for next release. Your own opam file doesn't have to change at all, we welcome more tests of course (as long as they don't fail randomly)

**Comment by Risto-Stevcev** [comment]
> I don't really get the question. I mean usually people tend to avoid non-deterministic tests, when they happen it's usually not on purpose. We usually detect them a few weeks after they're added, if one is detected the tests are simply disabled.

I'm not sure why this comment was necessary, I'm just trying to understand what my options are to keep my library in Opam because you removed the dependencies as well. Do you think I want it to be non-deterministic on purpose? or is it possible that I might not have the time or I don't think it's worth the effort to refactor them and then convince someone that they're now deterministic in order to not get my library kicked out of a package manager?

They fail rarely enough that I don't really care, and there are notes in the library about some practical decisions that were made for these.

> Yes, it's more because there aren't any tests to run so they're useless dependencies for this particular version. It'd be sad to make CI machine use time that's not used in any way.

Are they useless dependencies? I'd like to be able to run the tests I wrote for the project, even if they sometimes fail. Same with anyone that tests out the project locally. Does Opam automatically try to run tests if those libraries exist?

> Sorry if I was confusing. You don't have anything to do per-say. I'm simply alerting you that your tests are buggy and that you might want to fix them for next release. Your own opam file doesn't have to change at all, we welcome more tests of course (as long as they don't fail randomly)

Well I kind of do now right because anyone that wants to run the tests on my project can't do it now because the test dependencies are missing...

My bandwidth for work on open source has been very little over the past few months and shrinking, I'd like to avoid having to jump through hoops if possible. It was a hobby and I really don't want it to feel like a job. Is disable `@run-test` enough? can I keep my test dependencies or do the dependencies have to go as well for the CI to work?

**Comment by kit-ty-kate** [comment]
Sorry again if I was confusing, I didn't mean to be harsh.
We seem to be both confused and talking about different things. It's probably easier if we can quickly talk on a synchronous chat somewhere (discord, irc, platform of your choice)

> in order to not get my library kicked out of a package manager?

Just to be clear, the package is still available, the package is not being kicked out (it would be against our own policy anyway).

I'll uncomment the test dependencies if you need but there seems to be come confusion about what opam-repository is. I'll gladly answer your questions on the synchronous chat platform of your choice.

**Comment by kit-ty-kate** [comment]
> I'll uncomment the test dependencies

Done in https://github.com/ocaml/opam-repository/pull/19300

**Pull request merged**
