### PR TITLE
Package pfff.0.40.3

### PR DESCRIPTION
**Pull request by aryx**
### `pfff.0.40.3`
Tools and APIs for program analysis, code visualization, refactoring
pfff is a set of tools and APIs to perform some static analysis,
dynamic analysis, code visualizations, code navigations, or
style-preserving source-to-source transformations such as refactorings
on source code. For now the effort is focused on Javascript and Python
but there is also good support for C, C++, Java, Go, Ruby, PHP, HTML, Css, and
preliminary support for Erlang, C#, Lisp, Scheme, Haskell, Skip, SQL, and
even TeX. There is also very good support for OCaml and noweb
(literate programming) so that pfff can be used on the code of pfff
itself.

For more information see https://github.com/facebook/pfff/wiki/Main

---
* Homepage: https://github.com/facebook/pfff/wiki/Main
* Source repo: git+https://github.com/returntocorp/pfff.git
* Bug tracker: https://github.com/returntocorp/pfff/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The two travis checks (Linux system + MacOS) failed. It feels like it might come from the fact that those two checks are done with OCaml compilers installed system-wide. Could you check what might be wrong here?
```
#=== ERROR while compiling pfff.0.40.3 ========================================#
# context     2.0.6 | macos/x86_64 | ocaml-system.4.09.0 | file:///Users/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-system/.opam-switch/build/pfff.0.40.3
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code   2
# env-file    ~/.opam/log/pfff-66488-0a5907.env
# output-file ~/.opam/log/pfff-66488-0a5907.out
### output ###
# [...]
# ocamlc.opt -g -dtypes   -I ../commons -I ../h_program-lang -I ../lang_php/parsing -thread -custom -o show_function_class_names2.byte str.cma unix.cma bigarray.cma ../commons/lib.cma ../commons_core/lib.cma ../h_program-lang/lib.cma ../lang_php/parsing/lib.cma show_function_class_names2.cmo
# ocamlc.opt -g -dtypes   -I ../commons -I ../h_program-lang -I ../lang_php/parsing -thread  -c simple_code_search.ml
# ocamlc.opt -g -dtypes   -I ../commons -I ../h_program-lang -I ../lang_php/parsing -thread -custom -o simple_code_search.byte str.cma unix.cma bigarray.cma ../commons/lib.cma ../commons_core/lib.cma ../h_program-lang/lib.cma ../lang_php/parsing/lib.cma simple_code_search.cmo
# ocamlc.opt -g -dtypes   -I ../commons -I ../h_program-lang -I ../lang_php/parsing -thread  -c analyze_chain.ml
# ocamlc.opt -g -dtypes   -I ../commons -I ../h_program-lang -I ../lang_php/parsing -thread -custom -o analyze_chain.byte str.cma unix.cma bigarray.cma ../commons/lib.cma ../commons_core/lib.cma ../h_program-lang/lib.cma ../lang_php/parsing/lib.cma analyze_chain.cmo
# /Applications/Xcode-10.1.app/Contents/Developer/usr/bin/make pfff stags codequery codeslicer pfff_db pfff_test
# ocamlc.opt -g -thread -w +a-4-6-29-41-44-45-48-52-67 -warn-error +a -bin-annot -absname  -pp "cpp -Wno-invalid-pp-token" -I commons -I commons_ocollection -I commons_core -I commons_wrappers/graph -I globals -I h_visualization -I h_files-format -I h_program-lang -I graph_code -I lang_ml/parsing -I lang_ml/analyze -I lang_skip/parsing -I lang_skip/analyze -I lang_nw/parsing -I lang_nw/analyze [...]
# ocamlc.opt -g -thread -w +a-4-6-29-41-44-45-48-52-67 -warn-error +a -bin-annot -absname  -pp "cpp -Wno-invalid-pp-token" -I commons -I commons_ocollection -I commons_core -I commons_wrappers/graph -I globals -I h_visualization -I h_files-format -I h_program-lang -I graph_code -I lang_ml/parsing -I lang_ml/analyze -I lang_skip/parsing -I lang_skip/analyze -I lang_nw/parsing -I lang_nw/analyze [...]
# File "/Users/travis/.opam/ocaml-system/.opam-switch/build/pfff.0.40.3/_none_", line 1:
# Error: Cannot find file /Users/travis/.opam/ocaml-system/.opam-switch/build/pfff.0.40.3/nums.cma
# make[1]: *** [pfff] Error 2
# make: *** [all] Error 2
```

**Comment by aryx** [comment]
No idea, I thought nums.cma was provided by the nums library mentioned in the pfff.opam file as a dependency.

**Comment by aryx** [comment]
Also a few hours ago all the tests were failing. It was an issue with opam CI?

**Comment by kit-ty-kate** [comment]
> Also a few hours ago all the tests were failing. It was an issue with opam CI?

Yes, probably a connexion issue to docker. A click on the `rebuild` button fixed it.

**Comment by aryx** [comment]
Is it possible nums.cma is not in the ocaml standard library directory?

/Users/pad/.opam/4.10.0/lib/num $ cat META 
# This META is the one provided by findlib when the "num" library was
# part of the core OCaml distribution.  For backward compatibility,
# it is installed into OCaml's standard library directory. If the
# directory line below is removed, then it's installed in a
# subdirectory, as normal for a findlib package.

requires = "num.core"
requires(toploop) = "num.core,num-top"
version = "1.3"
description = "Arbitrary-precision rational arithmetic"
package "core" (
  directory = "^"
  version = "1.3"
  browse_interfaces = ""
  archive(byte) = "nums.cma"
  archive(native) = "nums.cmxa"
  plugin(byte) = "nums.cma"
  plugin(native) = "nums.cmxs"
)
/Users/pad/.opam/4.10.0/lib/num $

**Comment by aryx** [comment]
I link nums.cma, bigarray.cma str.cma and unix.cma without any -I. I assume they
are in the standard ocaml library directory.

**Comment by kit-ty-kate** [comment]
> I link nums.cma, bigarray.cma str.cma and unix.cma without any -I. I assume they
> are in the standard ocaml library directory.

~Looking a bit deeper it seems to be an issue in the num package as the install behaviour seems to be different between system-wide installs and opam switches. In the first case num.cma is not installed in `<prefix>/lib/ocaml` whereas in the second case it is.~
EDIT: I just realized this behaviour is normal as opam cannot add anything into the `/usr/lib/ocaml` directory.

However, apart from this issue, guessing where libraries are installed should not be done in in packages and it is good practice to use `ocamlfind` (or build-systems handling META files) for this purpose instead. Would it be possible for you to use ocamlfind in future versions? I just tried to patch your Makefiles quickly and it does not seem to be too much of a hassle.

Should we tag this package as unavailable with a system switches >= 4.06 or do you prefer to fix that first?

**Comment by aryx** [comment]
I'll remove the use of nums.cma and submit another PR.

**Pull request closed without merging**
