### PR TITLE
Make verimag packages incompatible with 4.06

### PR DESCRIPTION
**Pull request by Drup**
All these packages are broken by safe-string.

### CODE REVIEW

**Comment by Drup** [comment]
Apparently, rdgb doesn't compile with 4.05 either. Everything works now, so it can be merged.

cc @jahierwan I suppose ?

**Comment by jahierwan** [comment]
I'm sorry, i am now maintaining my opam packages on another repo for a while (http://www-verimag.imag.fr/DIST-TOOLS/SYNCHRONE/opam-repository) . I should either update or delete this one I guess. meanwhile I am ok with this PR.

**Comment by jahierwan** [comment]
ok, I will do that, thanks for the suggestion

**Comment by kit-ty-kate** [comment]
Thanks !

**Pull request merged**
