### PR TITLE
Add extprot.1.4.0.

### PR DESCRIPTION
**Pull request by mfp**

### CODE REVIEW

**Comment by ygrek** [comment]
CI error is
```
# Error: I/O error: /tmp/ocamlpp4b98369d70b132455575da0219a38eb9: File exists
```

**Comment by ygrek** [comment]
ftr I cannot reproduce this error locally with 4.02.3

**Comment by mfp** [comment]
I couldn't either. 

The error is reproducible in CI though, I triggered  a new build and got the same error, including exactly the same filename (unfortunately there is no unique URL for different CI builds), see the [logs]( https://ci.ocaml.io/log/saved/docker-build-b9e19f3441602180e9733642a87c5112/d0491a4c288becf2ad182cdc21797371d691b4f6) for the build on 2017-10-07 10:13.53, with the same error as the previous one on  2017-10-05 21:28.14.

The error is interesting. The `ocamlpp....` prefix comes from `call_external_preprocessor` in `driver/pparse.ml`, but the filename is too long to have come directly from that `Filename.temp_file` (which only adds 6 digits, likely some in the `132455575` section). `Filename.temp_file` uses Random's PRNG, which should have been self-initialized with `/dev/urandom` data (if not available, it'd use the time and PID, which we know has changed in between). At any rate, we can conclude the CI environment is entropy-deprived, either by accident (no time to gather entropy) or deliberately (something in place to make builds more reproducible?).

**Comment by ygrek** [comment]
@avsm any idea how to debug this / what might be the cause?

**Comment by avsm** [comment]
But it only happens on 4.02.3. Hmm...need to dig in further.

**Comment by gasche** [comment]
Should we consider merging this despite the lack-of-entropy issue? If I understand correctly no other package depends on `extprot` currently, so we can wait a bit more if we want.

**Comment by ygrek** [comment]
I understand CI is here to prevent breakage when users install packages. No human user did observe breakage, so let's not block new version because of this?

**Comment by ygrek** [comment]
Thank you!

**Pull request merged**
