### PR TITLE
[new release] current_web, current_slack, current_rpc, current_gitlab, current_github, current_git, current_examples, current_docker and current (0.6.3)

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Test web UI for OCurrent

- Project page: <a href="https://github.com/ocurrent/ocurrent">https://github.com/ocurrent/ocurrent</a>

##### CHANGES:

Web UI:

- Make line numbers clickable in logs (@MisterDA, ocurrent/ocurrent#352, ocurrent/ocurrent#356)
- Make the background of rendered graphiz transparent (@MisterDA, ocurrent/ocurrent#362)
- Disable uneeded tooltips on diagrams nodes (@MisterDA, ocurrent/ocurrent#382)

API:

- Add collapse_list to control rendering of ocurrent pipeline (@TheLortex @tmcgilchrist, ocurrent/ocurrent#314)
- Added ref_title accessor for commits (@benmandrew, ocurrent/ocurrent#383)

Plugins:

- GitHub: Add support for rebuilding a commit. (@novemberkilo, ocurrent/ocurrent#361)
- GitHub: Refactor and add support for check-suite events to allow rebuild webooks from GitHub. (@novemberkilo, ocurrent/ocurrent#364)
- GitHub: Remove the role check for webhooks. (@novemberkilo, ocurrent/ocurrent#366)
- GitHub: More explicitly set details_url in CheckRunStatus. (@tmcgilchrist, ocurrent/ocurrent#369)

- GitLab: use set_status name (= context) in the web interface (@tmcgilchrist, ocurrent/ocurrent#350)

- Git: Make the output of git fetch quiet (@kit-ty-kate, ocurrent/ocurrent#371)

- Docker: Add pull argument to docker compose (@patrickoferris, ocurrent/ocurrent#358)
- Docker: Docker compose cli v2. Required to support AWS ECS. (@mtelvers @tmcgilchrist, ocurrent/ocurrent#373)
- Docker: Add build context parameter to docker build (@patricoferris, ocurrent/ocurrent#363)

Other:

- Dune 3 fixes (@MisterDA, ocurrent/ocurrent#367)
- Fix some overuse of memory and concurrent fd open when too many jobs are queued (@kit-ty-kate, ocurrent/ocurrent#372)
- Pull in crunch.3.3.0 for Windows fixes (@MisterDA, ocurrent/ocurrent#370)
- Allow users to provide a command printer (@patricoferris, ocurrent/ocurrent#359)
- Update to routes 2.0 (@anuragsoni, ocurrent/ocurrent#381)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
@tmcgilchrist do you have any idea why the tests on macOS fail?
```
#=== ERROR while compiling current_git.0.6.3 ==================================#
# context              2.1.3 | macos/x86_64 | ocaml-base-compiler.4.14.0 | pinned(https://github.com/ocurrent/ocurrent/releases/download/0.6.3/current-0.6.3.tbz)
# path                 ~/.opam/4.14.0/.opam-switch/build/current_git.0.6.3
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p current_git -j 11
# exit-code            1
# env-file             ~/.opam/log/current_git-11891-8f1555.env
# output-file          ~/.opam/log/current_git-11891-8f1555.out
### output ###
# File "plugins/git/test/dune", line 1, characters 0-52:
# 1 | (mdx
# 2 |  (packages current_git)
# 3 |  (package current_git))
# (cd _build/default/plugins/git/test && /Users/mac1000/.opam/4.14.0/bin/ocaml-mdx test -o .mdx/test_submodules.md.corrected test_submodules.md) > _build/default/plugins/git/test/.mdx/test_submodules.md.corrected
# ocaml-mdx-test: internal error, uncaught exception:
#                 Unix.Unix_error(Unix.EINTR, "waitpid", "")
#
```

**Comment by MisterDA** [comment]
We have just fixed this mdx problem upstream, it was due to git submodules using `file://` urls and poor interaction with mdx.
https://github.com/ocurrent/ocurrent/pull/386
I suggest we skip the release of 0.6.3 to opam repo and re-submit using the patch a 0.6.4.

**Comment by raphael-proust** [comment]
@MisterDA I'm labelling as do-not-merge based on your comment. Don't hesitate to mention if things change.

**Comment by raphael-proust** [comment]
@tmcgilchrist @MisterDA if you want to skip, just close this PR. Otherwise let us know what to do with it.

**Comment by tmcgilchrist** [comment]
I'll re-create the release with the mdx fix included.

**Comment by tmcgilchrist** [comment]
> @tmcgilchrist do you have any idea why the tests on macOS fail?
> 
> ```
> #=== ERROR while compiling current_git.0.6.3 ==================================#
> # context              2.1.3 | macos/x86_64 | ocaml-base-compiler.4.14.0 | pinned(https://github.com/ocurrent/ocurrent/releases/download/0.6.3/current-0.6.3.tbz)
> # path                 ~/.opam/4.14.0/.opam-switch/build/current_git.0.6.3
> # command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p current_git -j 11
> # exit-code            1
> # env-file             ~/.opam/log/current_git-11891-8f1555.env
> # output-file          ~/.opam/log/current_git-11891-8f1555.out
> ### output ###
> # File "plugins/git/test/dune", line 1, characters 0-52:
> # 1 | (mdx
> # 2 |  (packages current_git)
> # 3 |  (package current_git))
> # (cd _build/default/plugins/git/test && /Users/mac1000/.opam/4.14.0/bin/ocaml-mdx test -o .mdx/test_submodules.md.corrected test_submodules.md) > _build/default/plugins/git/test/.mdx/test_submodules.md.corrected
> # ocaml-mdx-test: internal error, uncaught exception:
> #                 Unix.Unix_error(Unix.EINTR, "waitpid", "")
> #
> ```

There was a bug in mdx's handling of signals https://github.com/realworldocaml/mdx/pull/409

**Pull request closed without merging**
