### PR TITLE
Markup.ml 0.7.7: standards-compliant HTML5 parser

### PR DESCRIPTION
**Pull request by aantron**
This release fixes one bug (aantron/markup.ml#33).

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Tests are failing:
```
#=== ERROR while installing markup.0.7.7 ======================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder runtest -p markup
# path         /home/travis/.opam/system/build/markup.0.7.7
# compiler     system (4.07.0)
# exit-code    1
# env-file     /home/travis/.opam/system/build/markup.0.7.7/markup-16201-865888.env
# stdout-file  /home/travis/.opam/system/build/markup.0.7.7/markup-16201-865888.out
# stderr-file  /home/travis/.opam/system/build/markup.0.7.7/markup-16201-865888.err
### stderr ###
# File "test/lwt_unix/jbuild", line 5, characters 14-22:
# Error: Library "lwt.unix" not found.
# Hint: try: dune external-lib-deps --missing --profile release -p markup @runtest
#         test alias test/runtest
# 
# Running tests in test.exe
# ................................................................................................................................................................................................................................................................................................................................................
# Ran: 336 tests in: 0.22 seconds.
# OK
```

**Comment by aantron** [comment]
I'm guessing the tests were failing because the opam CI no longer installs depopts before running the `build-test` script. I removed the `build-test` script.

**Comment by aantron** [comment]
Remaining failures look like package manager problems, and are unrelated to Markup.ml.

**Comment by mseri** [comment]
Thanks. I have restarted the two failing travis tests, just to clean up the logs. I agree that the rest is infrastructure. Once Travis is also green I think we can merge

**Comment by mseri** [comment]
Yep, all green. I am going to merge

**Comment by aantron** [comment]
Thanks!

**Pull request merged**
