### PR TITLE
[new release] syndic (1.6.1)

### PR DESCRIPTION
**Pull request by Chris00**
CHANGES:

* `Syndic.Date.of_rfc822` accepts dates such as “May 15th, 2019”.

### CODE REVIEW

**Comment by Chris00** [comment]
The failure for 4.03 is with the tests — and on the line `#use "topfind" ;;`.

**Comment by mseri** [comment]
I can add a filter to disable the tests on 4.03 if you want, otherwise I’ll remove the name variable and merge

**Comment by Chris00** [comment]
> disable the tests on 4.03

OK, let's do that.  Thanks.
CC @dinosaure in case he has another solution (the failure must have happened with the previous version as it is unrelated to the changes).

**Comment by dinosaure** [comment]
Related to: https://github.com/ocaml/ocaml/issues/7555 so we can just drop `4.03.0`.

**Comment by mseri** [comment]
@Chris00 I’ll let you decide, either way is fine for me

**Comment by Chris00** [comment]
I think one can only run the tests for OCaml >= 4.04

**Pull request merged**
