### PR TITLE
Package mm.0.8.1

### PR DESCRIPTION
**Pull request by toots**
### `mm.0.8.1`
The mm library contains high-level to create and manipulate multimedia streams (audio, video, MIDI)

---
* Homepage: https://github.com/savonet/ocaml-mm
* Source repo: git+https://github.com/savonet/ocaml-mm.git
* Bug tracker: https://github.com/savonet/ocaml-mm/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mseri** [comment]
Tests on 32 bit archs are failing with
```
# - scale... Fatal error: exception Out of memory
# Raised by primitive operation at Mm_image__ImageYUV420.to_BMP in file "src/imageYUV420.ml", line 159, characters 2-19
# Called from Dune__exe__Test.(fun) in file "examples/test.ml", line 281, characters 24-46
# Called from Dune__exe__Test.time in file "examples/test.ml", line 32, characters 4-8
# Called from Dune__exe__Test in file "examples/test.ml", line 276, characters 2-256
```

**Comment by toots** [comment]
> Tests on 32 bit archs are failing with
> 
> ```
> # - scale... Fatal error: exception Out of memory
> # Raised by primitive operation at Mm_image__ImageYUV420.to_BMP in file "src/imageYUV420.ml", line 159, characters 2-19
> # Called from Dune__exe__Test.(fun) in file "examples/test.ml", line 281, characters 24-46
> # Called from Dune__exe__Test.time in file "examples/test.ml", line 32, characters 4-8
> # Called from Dune__exe__Test in file "examples/test.ml", line 276, characters 2-256
> ```

I would ignore that. The generated file is `381M` so it's possible that the operation is actually consuming all the memory resources of the virtual environment though I wouldn't consider that a test failure per se. The test passes on all other cases.

**Comment by toots** [comment]
@mseri would it be possible to merge this one? It is holding the liquidsoap `2.1.x` release. Thanks!

**Comment by mseri** [comment]
Yes. I was planning to do it today

**Comment by toots** [comment]
Thank you!

**Pull request merged**
