### PR TITLE
More constraints for Lwt 4.0.0

### PR DESCRIPTION
**Pull request by aantron**
See #11708, #11716. cc @hannesm

### CODE REVIEW

**Comment by aantron** [comment]
```
[ERROR] async < 111.25.00 & async >= 113.00.00 & lwt (< 2.5.0 | >= 4.0.0) &
        js_of_ocaml >= 3.0 is not a valid conjunction
```

Does this mean I can't write conflicts using `|`, and must use two conflicts entries to get the same effect?

**Comment by kit-ty-kate** [comment]
Seems like this syntax works only with opam2 but yes I would say. Sorry :/
@AltGr can you confirm ?

**Comment by aantron** [comment]
I converted the constraints not to use `|`. The build failures are not related to the new constraints, so I would say this is ready for merge.

**Comment by kit-ty-kate** [comment]
Yep, thank you ! :)

**Pull request merged**
