### PR TITLE
conf-sfml2: Add support for most distributions

### PR DESCRIPTION
**Pull request by kit-ty-kate**
To help merge https://github.com/ocaml/opam-repository/pull/21878

### CODE REVIEW

**Comment by fccm** [comment]
On a ChromeBook, the command `uname -a` tells me that the Linux provided is called "penguin".
The command used to install something is an "apt-get" and the name of the package is the same than on Debian:
`"libsfml-dev"`
I don't know if it should be included with `os-family` of `os-distribution`.

**Comment by kit-ty-kate** [comment]
what does `opam config report` give you?

**Comment by fccm** [comment]
```
# opam config report
# opam-version      2.0.3 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=10
# solver            mccs
# install-criteria  -removed,-count[version-lag:,true],-changed,-count[version-lag:,false],-new
# upgrade-criteria  -removed,-count[version-lag:,false],-new
# jobs              1
# repositories      1 (http) (default repo at e3a26c21)
# pinned            0
# current-switch    4.14.0
```

**Comment by kit-ty-kate** [comment]
Then no, it will be correctly detected as a Debian-based distribution.

**Pull request merged**
