### PR TITLE
added compilers/4.02.3/4.02.3+PIC/

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by yallop** [comment]
Is a separate PIC switch still needed?  The PIC runtime is built by default now:

  http://caml.inria.fr/mantis/view.php?id=6693
  https://github.com/ocaml/ocaml/blob/ca7b3c19/Changes#L458-L459

**Comment by UnixJunkie** [comment]
maybe not, I will double check.

**Comment by UnixJunkie** [comment]
/usr/bin/ld: /home/berenger/.opam/4.02.3/lib/ocaml/libasmrun.a(startup.o): relocation R_X86_64_32 
    against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

**Comment by yallop** [comment]
Does passing `-runtime-variant _pic` to `ocamlopt` help?

**Comment by UnixJunkie** [comment]
OK, I need to link against libasmrun_pic.a, so you were right.

**Pull request closed without merging**
