### PR TITLE
sequence.0.5.5 - via opam-publish

### PR DESCRIPTION
**Pull request by c-cube**
Simple and lightweight sequence abstract data type.

Simple sequence abstract data type, intended to transfer a finite number of
elements from one data structure to another. Some transformations on sequences,
like `filter`, `map`, `take`, `drop` and `append` can be performed before the
sequence is iterated/folded on.

---
* Homepage: https://github.com/c-cube/sequence/
* Source repo: https://github.com/c-cube/sequence.git
* Bug tracker: https://github.com/c-cube/sequence/issues

---
Pull-request generated by opam-publish v0.2.1

### CODE REVIEW

**Comment by whitequark** [comment]
`[ERROR] curl: code 404 while downloading https://github.com/c-cube/sequence/archive/0.5.5.tar.gz`

**Comment by yallop** [comment]
It [looks like](https://travis-ci.org/ocaml/opam-repository/jobs/47113480#L660) you need to constrain the package to OCaml 4.02 onwards:

```
# File "bigarray/sequenceBigarray.ml", line 39, characters 40-53:
# Error: Unbound constructor Bigarray.Char
```

**Comment by c-cube** [comment]
Oh, that sucks. I should have used the pre-4.02 constructor, I guess.

**Comment by yallop** [comment]
Can ocamldoc comments be associated with individual constructors?  The exposed representation for [`Bigarray.kind`](https://github.com/ocaml/ocaml/blob/64ee2135ded944021f9e0bbf3e1dc65fcd60b6c9/otherlibs/bigarray/bigarray.mli#L73-L86) is new in 4.02, but the type itself is not.

**Comment by dsheets** [comment]
Yes. The ocamldoc comment for `Char` is one such example. It has been erroneously associated to the last constructor rather than the type as a whole because whoever wrote the doc comment didn't know all of the intricate comment association rules for ocamldoc.

**Pull request merged**
