### PR TITLE
Add mirage-profile 0.5

### PR DESCRIPTION
**Pull request by talex5**

### CODE REVIEW

**Comment by dsheets** [comment]
Should `bug-reports` point to the issues page? Also, I don't know what the policy is regarding `name` and `version` fields in the repo. @samoht ?

**Comment by samoht** [comment]
the current (not strictly enforced) policy is to not have `version` and `name` in the opam file indeed. And also to have `/issues` at the end of the `bug-reports` links for GiHub repo.

**Comment by dsheets** [comment]
`name` and `version` elision is now tracked by OCamlPro/opam-publish#28.

**Comment by talex5** [comment]
OK, updated as suggested.

**Comment by talex5** [comment]
Note: some of the Travis builds failed due to network problems; doesn't look like a problem with the PR.

**Pull request merged**
