### PR TITLE
Package brotli.2.0.3

### PR DESCRIPTION
**Pull request by fxfactorial**
### `brotli.2.0.3`

Bindings to Google's Brotli compresion algorithm

OCaml Bindings to brotli, Google's compression algorithm for the web
Source: https://github.com/google/brotli/ RFC:
http://www.ietf.org/id/draft-alakuijala-brotli

---
* Homepage: http://hyegar.com
* Source repo: https://github.com/fxfactorial/reasonml-brotli.git
* Bug tracker: https://github.com/fxfactorial/reasonml-brotli/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by mseri** [comment]
Can you add the  libbrotli dev/devel as depext for the main linux distributions?

**Comment by mseri** [comment]
This is failing due to the lack of libbrotli on the ci distributions. I don’t think there is much we can do about it. Merging

**Comment by fxfactorial** [comment]
I already made the conf-brotli package. 

What are you asking me to now add ? Something to the opam file ?

**Comment by mseri** [comment]
Sorry, my bad, I nad not noticed it

**Pull request merged**
