### PR TITLE
ocaml-lua.1.5

### PR DESCRIPTION
**Pull request by pdonadeo**
* Added OPAM files for release 1.5
* tarballs migrated from ocamlcore (deprecated) to GitHub

### CODE REVIEW

**Comment by pdonadeo** [comment]
But... should I provide depexts for Alpine Linux?

**Comment by avsm** [comment]
Depexts for the additional distros would be useful but not blocking a merge. I've pushed some for Alpine and OpenSUSE to your branch so that the CI can test it -- hope that's ok.

**Comment by pdonadeo** [comment]
@avsm it's perfectly OK, thanks! I'll complete and commit again.

**Comment by avsm** [comment]
thanks!

**Pull request merged**
