### PR TITLE
[new release] atdgen-codec-runtime, atd, atdgen-runtime, atds, atdj and atdgen (2.2.0)

### PR DESCRIPTION
**Pull request by rgrinberg**
Runtime for atdgen generated bucklescript converters

- Project page: <a href="https://github.com/ahrefs/atd">https://github.com/ahrefs/atd</a>

##### CHANGES:

* Add support for merging double annotations (`<ocaml from="ProtoA"><ocaml predef>`)

* Add tests for annotation merging and target-specific annotations

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The packages are failing to build:
```
#=== ERROR while compiling atd.2.2.0 ==========================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://github.com/ahrefs/atd/releases/download/2.2.0/atd-2.2.0.tbz)
# path                 ~/.opam/4.10/.opam-switch/build/atd.2.2.0
# command              ~/.opam/4.10/bin/dune build -p atd -j 72 @install
# exit-code            1
# env-file             ~/.opam/log/atd-23-9af213.env
# output-file          ~/.opam/log/atd-23-9af213.out
### output ###
# File "atdgen/test/dune", line 199, characters 40-51:
# 199 |  (deps    (:atd test_annot_error.atd) %{bin:atdgen})
#                                               ^^^^^^^^^^^
# Error: Program atdgen not found in the tree or in PATH
#  (context: default)

- File "atdgen/test/dune", line 199, characters 40-51:
- 199 |  (deps    (:atd test_annot_error.atd) %{bin:atdgen})
-                                               ^^^^^^^^^^^
- Error: Program atdgen not found in the tree or in PATH
-  (context: default)
```

**Comment by rgrinberg** [comment]
Hmm, I have no idea why dune is looking for the executable. It's only necessary for running the tests. In any case, I'm a bit short on time, so I cannot continue to investigate.

@pirbo do you want take over the releasee? Feel free to make whatever changes are necessary to make sure the tests aren't getting in the way. Please don't send patches to opam-repository however, just tag & release from upstream.

**Comment by kit-ty-kate** [comment]
from afar the error seems a bit like the one encountered here https://github.com/ocaml/opam-repository/pull/15879 for `rpc` but with tests rules instead of documentation rules.

**Comment by rgrinberg** [comment]
Indeed, but in that issue the documentation was part of the package. I don’t see how I’ve made my tests part of the package in atd.

**Comment by pirbo** [comment]
All my patches needed to fix 2.1.0 have been upstreamed @XVilka. 
By uptreaming them, I detected a new potential problem in 2.2.0 for which I gave my workaround in https://github.com/ahrefs/atd/pull/207#issuecomment-590588167 but as it was more hallucinating what the test was supposed to be that fixing something obvious (and as I never ever used ppx-deriving-sexp myself), I didn't turn that into an PR.

The problem here seems to be again simply a missing `(package ...)` restriction in a `runtest` rule. I can have a quick look at this particular issue but sorry my hands are too full (as everybody else I know) to be involve in the general maintainance of atd.

**Comment by avsm** [comment]
@rgrinberg indicated that the atd release would happen after dune 2.5.0 is out, as there's a bugfix in there that requires the dune fix.

**Comment by pirbo** [comment]
Good and I'm happy to de-involve myself :-)
I still put my conclusion as I spent the last hour on that: It looked to me that simply removing `%{bin:atdgen}` from the deps of `test_annot_error.stderr` fixes the problem (and `dune build @atdgen/runtest` still works perfectly in a cleaned env as dune knows it need to build  `%{bin:atdgen}` when it appears in the "rule").

**Comment by XVilka** [comment]
Just for the record - Dune 2.5.0 [had been merged](https://github.com/ocaml/opam-repository/pull/16170)

**Pull request closed without merging**
