### PR TITLE
Release Solo5 v0.7.1

### PR DESCRIPTION
**Pull request by dinosaure**
## v0.7.1 (2022-03-14)

* Fix syntax error in stubs ld file (solo5/solo5#509)
* Fix `opam-release.sh (solo5/solo5#511)
* elftool: generate manifests from stdin or to stdout (solo5/solo5#510)

### CODE REVIEW

**Comment by mseri** [comment]
`OpamSolution.Fetch_fail("https://github.com/Solo5/solo5/releases/download/v0.7.1/solo5-v0.7.1.tar.gz (curl: code 404 while downloading https://github.com/Solo5/solo5/releases/download/v0.7.1/solo5-v0.7.1.tar.gz)")`

**Comment by dinosaure** [comment]
Errors seems unrelated to this package, if someone else than me can merge this PR :+1:.

**Comment by mseri** [comment]
Should we add an availability flag for these architectures:

- arm32
        solo5-cross-aarch64.0.7.1 (failed: Error: Package solo5-cross-aarch64.0.7.1 depends on the unavailable system package 'gcc-aarch64-linux-gnu'. You can use `--no-depexts' to attempt installation anyway.)
-   ppc64
        [solo5-cross-aarch64.0.7.1 (failed: Error: The compilation of solo5.0.7.1 failed at "make V=1".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/0498d87e93da58b2b44ff0f38f52f3821f0b3e4b/variant/opam-2.1,extras,ppc64,solo5-cross-aarch64.0.7.1)
        [solo5.0.7.1 (failed: array subscript 3584 is outside array bounds of 'struct tcb[1]' [-Werror=array-bounds])](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/0498d87e93da58b2b44ff0f38f52f3821f0b3e4b/variant/opam-2.1,extras,ppc64,solo5.0.7.1)
-   s390x
        solo5-cross-aarch64.0.7.1 (failed: Error: Package solo5-cross-aarch64.0.7.1 depends on the unavailable system package 'gcc-aarch64-linux-gnu'. You can use `--no-depexts' to attempt installation anyway.)

?

**Comment by dinosaure** [comment]
Hmmhmm, yes I think it's right. I prefer to be conservative about the cross-compilation support. I will add it.

**Comment by hannesm** [comment]
IIRC solo5 should work fine on ppc, and the compilation issue [array subscript 3584 is outside array bounds of 'struct tcb[1]' [-Werror=array-bounds])](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/0498d87e93da58b2b44ff0f38f52f3821f0b3e4b/variant/opam-2.1,extras,ppc64,solo5.0.7.1) should be investigated.

but it is only an issue in the tests.

**Comment by mseri** [comment]
The ppc64 test failure is still there. I will let you decide if you want to merge or not. Besides that point, it looks fine to me

**Comment by dinosaure** [comment]
I proposed a patch to fix the compilation on `ppc64`, see here: https://github.com/Solo5/solo5/pull/514. I will redo the release so. Thanks.

**Pull request closed without merging**
