### PR TITLE
New Menhir release. This time, without warn_error.patch.

### PR DESCRIPTION
**Pull request by fpottier**

### CODE REVIEW

**Comment by fpottier** [comment]
What are all these opam-lint errors about missing fields?
Last week's version of my "opam" did not trigger these errors.
Where do I find up-to-date documentation about writing an opam package description?
Thanks,
F.

**Comment by dbuenzli** [comment]
It seems that camelus was on strike last week (?).

It's always a good idea to do an `opam lint` on your opam file before submitting your package since this will happen anyway along with the ci. Note that this will automatically be done if you integrate [`opam-publish`](https://github.com/OCamlPro/opam-publish) in your release workflow (it will also significantly reduce the number of steps for proposing a new package). 

Some documentation can be found [here](http://opam.ocaml.org/doc/Manual.html#opam). The file format reference is [here](http://opam.ocaml.org/doc/manual/dev-manual.html#sec9).

**Comment by fpottier** [comment]
@dbuenzli Thanks for your comments.
I added a dev-repo URL to please opam-lint, but this is a private repository.
I don't know if this package description will work properly -- I wasn't able to figure out from the documentation how to test it locally.

**Comment by dbuenzli** [comment]
> I added a dev-repo URL to please opam-lint, but this is a private repository.

Well at least it will work for you or anybody who has access to it. 

> I wasn't able to figure out from the documentation how to test it locally.

Best is to have the `opam` file in the vcs at the root of your repository. That way you can simply test it by pinning menhir to your dev-repo e.g. by doing a: 

```
opam pin add menhir --dev-repo
``` 

This will install's menhir's current `HEAD` and use the `opam` file found in your vcs repository to actually install the package (it will also update the package whenever HEAD changes, on `opam update`). This assumes though that menhir can be compiled and installed directly from a checkout of your vcs, if not there are various way of adding specific install instructions for pinned repos to prepare your checkout for install.

**Comment by avsm** [comment]
Thanks for all the fixes!

**Pull request merged**
