### PR TITLE
package Coq 8.8.2

### PR DESCRIPTION
**Pull request by HeikoBecker**

### CODE REVIEW

**Comment by mseri** [comment]
This is not the first time I see this `debian-unstable` failure. For some reasons `opam2` (not sure about `opam1`) on `debian-unstable` fails to download packages from `ocaml forge` (you see a similar issue often for packages using `ounit`). @avsm do you know more about it?

**Comment by Zimmi48** [comment]
ping: it would be good not to let this package update waiting for too long

**Comment by rjbou** [comment]
@mseri It's a curl error 35 (unsupported protocol) that is raised only on unstable (vs stretch).

**Comment by eponier** [comment]
This time, the CI is stuck on a Docker error.

**Comment by pmetzger** [comment]
I'd like us to merge this without waiting much longer on the CI. The differences from 8.8.1 aren't large enough to merit alarm, and Coq is an important package.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
