### PR TITLE
Package line-up-words.1.0.0

### PR DESCRIPTION
**Pull request by diml**
### `line-up-words.1.0.0`

Align words in an intelligent way

line-up-words is a small command line tool that tries to align words
in a sequence of lines in an intelligent way.

It comes as a binary and an emacs mode.

---
* Homepage: https://github.com/janestreet/line-up-words
* Source repo: git+https://github.com/janestreet/line-up-words.git
* Bug tracker: https://github.com/janestreet/line-up-words/issues

---

---
1.0.0 (2018-02-13)
------------------

* Initial release
:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by samoht** [comment]
For some reasons, the sources are not available:
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - line-up-words.1.0.0
        (This may be fixed by running 'opam update')
```

**Comment by samoht** [comment]
Maybe because the checksum is not the right one:
```
$ md5sum line-up-words-1.0.0.tbz
12a7d50372c2ed9f23cb0ef3dba2e854  line-up-words-1.0.0.tbz
```

**Comment by diml** [comment]
Oops, I thought I fixed that. It should be OK now.

**Comment by samoht** [comment]
```
#=== ERROR while installing line-up-words.1.0.0 ===============================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -p line-up-words -j 2
# path                 /home/opam/.opam/4.05.0/build/line-up-words.1.0.0
# compiler             4.05.0
# exit-code            1
# env-file             /home/opam/.opam/4.05.0/build/line-up-words.1.0.0/line-up-words-7-e04b32.env
# stdout-file          /home/opam/.opam/4.05.0/build/line-up-words.1.0.0/line-up-words-7-e04b32.out
# stderr-file          /home/opam/.opam/4.05.0/build/line-up-words.1.0.0/line-up-words-7-e04b32.err
### stderr ###
# [...]
#     ocamldep lib/line_up_words_lib.dependsi.ocamldep-output
#          ppx bin/line_up_words.pp.mli
#     ocamldep lib/line_up_words_lib.depends.ocamldep-output
#       ocamlc lib/line_up_words_lib__Common.{cmi,cmti}
#     ocamldep bin/line_up_words.dependsi.ocamldep-output
#       ocamlc bin/line_up_words.{cmi,cmti}
#     ocamlopt lib/line_up_words_lib__Common.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05.0/bin/ocamlopt.opt -w -40 -g -I /home/opam/.opam/4.05.0/lib/base -I /home/opam/.opam/4.05.0/lib/base/caml -I /home/opam/.opam/4.05.0/lib/base/md5 -I /home/opam/.opam/4.05.0/lib/base/shadow_stdlib -I /home/opam/.opam/4.05.0/lib/bin_prot -I /home/opam/.opam/4.05.0/lib/bin_prot/shape -I /home/opam/.opam/4.05.0/lib/core -I /home/opam/.opam/4.05.0/lib/core_extended -I /home/opam/.opam/4.05.0/lib/core_kernel -I /home/opam/.opam/4.05.0/lib/core_kernel/base_for_tests -I /home/opam/.opam/4.05.0/lib/fieldslib -I /home/opam/.opam/4.05.0/lib/jane-street-headers -I /home/opam/.opam/4.05.0/lib/num -I /home/opam/.opam/4.05.0/lib/ocaml -I /home/opam/.opam/4.05.0/lib/ocaml/threads -I /home/opam/.opam/4.05.0/lib/patience_diff -I /home/opam/.opam/4.05.0/lib/pcre -I /home/opam/.opam/4.05.0/lib/ppx_assert/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_bench/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_expect/collector -I /home/opam/.opam/4.05.0/lib/ppx_expect/common -I /home/opam/.opam/4.05.0/lib/ppx_expect/config -I /home/opam/.opam/4.05.0/lib/ppx_hash/runtime-lib -I /home/opam/.opam/4.05.0/lib/ppx_inline_test/config -I /home/opam/.opam/4.05.0/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/4.05.0/lib/re2 -I /home/opam/.opam/4.05.0/lib/re2/c -I /home/opam/.opam/4.05.0/lib/sexplib -I /home/opam/.opam/4.05.0/lib/sexplib/0 -I /home/opam/.opam/4.05.0/lib/sexplib/num -I /home/opam/.opam/4.05.0/lib/sexplib/unix -I /home/opam/.opam/4.05.0/lib/spawn -I /home/opam/.opam/4.05.0/lib/stdio -I /home/opam/.opam/4.05.0/lib/textutils -I /home/opam/.opam/4.05.0/lib/textutils_kernel -I /home/opam/.opam/4.05.0/lib/typerep -I /home/opam/.opam/4.05.0/lib/variantslib -no-alias-deps -I lib -open Line_up_words_lib -o lib/line_up_words_lib__Common.cmx -c -impl lib/common.pp.ml)
# File "lib/common.ml", line 93, characters 35-49:
# Error: Unbound value Re2.create_exn
```

**Comment by diml** [comment]
Ah wait, that's wrong, I updated the release to fix this problem. The new archive must  not have been uploaded correctly.

**Comment by yomimono** [comment]
Congratulations on the release, and thanks for your patience :)

**Comment by diml** [comment]
Thanks, no problem :)

**Pull request merged**
