### PR TITLE
Package bls12-381.6.0.0

### PR DESCRIPTION
**Pull request by dannywillems**
### `bls12-381.6.0.0`
Implementation of BLS12-381 and some cryptographic primitives built
on top of it

---
* Homepage: https://gitlab.com/nomadic-labs/cryptography/ocaml-bls12-381
* Source repo: git+https://gitlab.com/nomadic-labs/cryptography/ocaml-bls12-381.git
* Bug tracker: https://gitlab.com/nomadic-labs/cryptography/ocaml-bls12-381/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by dannywillems** [comment]
Closing. I will reopen with a new 6.0.0 version.

**Comment by dannywillems** [comment]
Reopening this MR as the changes we were thinking for 6.0.0 will be postponed to the next major release.

**Comment by mseri** [comment]
Do these packages require an upper bound?

- 
- [bls12-381-hash.0.0.1 (failed: 'blst_fr_ops' undeclared (first use in this function); did you mean 'blst_fr_pow'?)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/13e7205d1ca801d9363456a00ceddfcf9f0f0962/variant/compilers,4.14,bls12-381.6.0.0,revdeps,bls12-381-hash.0.0.1)
-     [bls12-381-hash.0.0.2 (failed: 'blst_fr_ops' undeclared (first use in this function); did you mean 'blst_fr_pow'?)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/13e7205d1ca801d9363456a00ceddfcf9f0f0962/variant/compilers,4.14,bls12-381.6.0.0,revdeps,bls12-381-hash.0.0.2)
-     [tezos-bls12-381-polynomial.0.1.1 (failed: Unbound value G.fft)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/13e7205d1ca801d9363456a00ceddfcf9f0f0962/variant/compilers,4.14,bls12-381.6.0.0,revdeps,tezos-bls12-381-polynomial.0.1.1)
-     [tezos-bls12-381-polynomial.0.1.2 (failed: Unbound value G.fft)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/13e7205d1ca801d9363456a00ceddfcf9f0f0962/variant/compilers,4.14,bls12-381.6.0.0,revdeps,tezos-bls12-381-polynomial.0.1.2)

**Comment by dannywillems** [comment]
> Do these packages require an upper bound?
> 
>     * [bls12-381-hash.0.0.1 (failed: 'blst_fr_ops' undeclared (first use in this function); did you mean 'blst_fr_pow'?)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/13e7205d1ca801d9363456a00ceddfcf9f0f0962/variant/compilers,4.14,bls12-381.6.0.0,revdeps,bls12-381-hash.0.0.1)
> 
>     * [bls12-381-hash.0.0.2 (failed: 'blst_fr_ops' undeclared (first use in this function); did you mean 'blst_fr_pow'?)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/13e7205d1ca801d9363456a00ceddfcf9f0f0962/variant/compilers,4.14,bls12-381.6.0.0,revdeps,bls12-381-hash.0.0.2)
> 
>     * [tezos-bls12-381-polynomial.0.1.1 (failed: Unbound value G.fft)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/13e7205d1ca801d9363456a00ceddfcf9f0f0962/variant/compilers,4.14,bls12-381.6.0.0,revdeps,tezos-bls12-381-polynomial.0.1.1)
> 
>     * [tezos-bls12-381-polynomial.0.1.2 (failed: Unbound value G.fft)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/13e7205d1ca801d9363456a00ceddfcf9f0f0962/variant/compilers,4.14,bls12-381.6.0.0,revdeps,tezos-bls12-381-polynomial.0.1.2)

Yes, fixed.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
