### PR TITLE
Package z3.4.10.2

### PR DESCRIPTION
**Pull request by smuenzel**
### `z3.4.10.2`
Z3 solver

---
* Homepage: https://github.com/Z3prover/z3
* Source repo: git+https://github.com/Z3prover/z3.git
* Bug tracker: https://github.com/Z3prover/z3/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by Kakadu** [comment]
Will this package compile only bindings if system-wide z3 is installed via apt? If no, any chance to make it work?

**Comment by smuenzel** [comment]
No, it compiles all of z3 (including the bindings), ignoring any versions that are installed.
The binding compilation is part of the z3 build, separating that out seems like it would take non-trivial amount of work.

**Comment by smuenzel** [comment]
I think something is broken with CI

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
