### PR TITLE
zipperposition: upper bound on containers

### PR DESCRIPTION
**Pull request by avsm**
due to
```
 File "src/core/Interfaces.ml", line 13, characters 22-34:
 Error: Unbound type constructor CCHash.state
```

### CODE REVIEW

**Comment by c-cube** [comment]
Indeed, release 1.1 was fixing this kind of issues.

**Comment by avsm** [comment]
@c-cube what's the right upper bound? still fails with

```
# File "src/core/Ind_ty.ml", line 65, characters 4-15:
# Warning 32: unused value type_hd_exn.
# + /home/opam/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -no-alias-deps -ccopt -Wextra -ccopt -Wno-unused-parameter -w +a-4-42-44-48-50 -color always -package zarith -package unix -package sequence -package oclock -package containers.data -package containers -package bytes -I src/core -I src/core/lib -o src/core/FeatureVector.cmo src/core/FeatureVector.ml
# File "src/core/FeatureVector.ml", line 92, characters 11-24:
# Error: Unbound value Sequence.fmap
```

**Comment by c-cube** [comment]
Ah, there also needs to be an upper bount `"sequence" {< "0.9"}`, I think

**Comment by c-cube** [comment]
Sorry for the inconvenience :-s

**Pull request merged**
