### PR TITLE
Capnp fixes

### PR DESCRIPTION
**Pull request by hannesm**
combines https://github.com/ocaml/opam-repository/pull/10768 with https://github.com/ocaml/opam-repository/pull/10760

### CODE REVIEW

**Comment by gasche** [comment]
Log of build failure on 4.0{3,4,5}:

```
#=== ERROR while installing capnp-rpc-lwt.0.2 =================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p capnp-rpc-lwt -j 4
# path         /home/travis/.opam/4.03.0/build/capnp-rpc-lwt.0.2
# compiler     4.03.0
# exit-code    1
# env-file     /home/travis/.opam/4.03.0/build/capnp-rpc-lwt.0.2/capnp-rpc-lwt-14360-6b77b5.env
# stdout-file  /home/travis/.opam/4.03.0/build/capnp-rpc-lwt.0.2/capnp-rpc-lwt-14360-6b77b5.out
# stderr-file  /home/travis/.opam/4.03.0/build/capnp-rpc-lwt.0.2/capnp-rpc-lwt-14360-6b77b5.err
### stderr ###
#       capnpc capnp-rpc-lwt/persistent.{ml,mli} (exit 1)
# (cd _build/default/capnp-rpc-lwt && /usr/bin/capnpc -o ocaml persistent.capnp)
# persistent.capnp:26:58: error: Parse error.
# persistent.capnp:111:79: error: Parse error.
```

**Comment by hannesm** [comment]
@gasche yes, but only with travis AFAICS - datakit compiles and installs capnp fine.  @talex5 is that expected / can these errors be ignored?

**Comment by gasche** [comment]
Given that the proposed changes only the situation, I went ahead and merged. Please feel free to open a new issue if you find more fixes.

**Comment by talex5** [comment]
I suspect those errors are from building on a distribution with an old version of capnp, in which case I think it's expected.

**Comment by gasche** [comment]
Thanks for looking! Ideally we would have a configure script somewhere that would embed assumptions on capnp versions instead of having a build failure down the chain.

**Pull request merged**
