### PR TITLE
[new release] odepack (0.7.1)

### PR DESCRIPTION
**Pull request by Chris00**
CHANGES:

- Compile the FORTRAN code in "legacy" mode.
- Upgrade to dune-configurator.

### CODE REVIEW

**Comment by Chris00** [comment]
Does [conf-gfortran](https://github.com/ocaml/opam-repository/blob/master/packages/conf-gfortran/conf-gfortran.0/opam) need to be modified for FreeBSD?

**Comment by mseri** [comment]
It shouldn’t. `Lang/gcc` is a metapackge including all of c, c+c and gfortran compilers. The conf package installs fine, I wonder if odepack need some extra includes at compile time to work — this I don’t know

**Comment by mseri** [comment]
@kit-ty-kate you have a test freebsd machine, right? Could you have a look?

**Comment by kit-ty-kate** [comment]
It seems you already fixed the issue. One other way of fixing this would have also been to use `gcc` directly instead of the default compiler (`cc`) as it already contains the path to the gcc library `libgfortran`. This way you would not even have to use `gfortran --print-file-name`. But it sounds good now anyway, thanks ^_^

**Comment by Chris00** [comment]
Thanks or looking at it @kit-ty-kate!

**Comment by Chris00** [comment]
BTW, if my memory serves, we should use `dune-configurator` now but I can't find a link to the information.  Can you confirm?

**Comment by Chris00** [comment]
Found [this commit](https://github.com/ocaml/opam-repository/commit/d7e7f626e6a8c6bd43d03115fe465e66cad3cc75), so I guess it is OK.

**Comment by mseri** [comment]
Sorry for the late replay. That is correct. Since dune 2.0 configurator is released separately with each dune release

**Comment by Chris00** [comment]
@mseri Thanks for the confirmation.  Do not know why the [manual](https://dune.readthedocs.io/en/stable/) was [not updated](https://github.com/ocaml/dune/pull/3822).

**Comment by kit-ty-kate** [comment]
Thanks a lot! I fixed your opam file here as your `dune-project` file indicates this package requires at least dune 1.1 and the `-p <name> -j <jobs>` was missing from the `dune build @doc` command.
Could you return those fixes upstream for next time?

**Comment by Chris00** [comment]
Thanks.  Your changes are [merged in the main repo](https://github.com/Chris00/ocaml-odepack/commit/29a554ffc713226f78c6b1d83e11a248ede58fcf).

**Pull request merged**
