### PR TITLE
Add package for Lambdoc 1.0-beta3

### PR DESCRIPTION
**Pull request by darioteixeira**

### CODE REVIEW

**Comment by darioteixeira** [comment]
Travis is misbehaving...

**Comment by samoht** [comment]
I've relaunched all the tests.

**Comment by darioteixeira** [comment]
Thanks @samoht.  Hmm, something has changed in the sexplib package, because Camlhighlight is no longer compiling.  I think I know what it is, but it will require a bugfix release of Camlhighlight.  Stay tuned.

**Comment by darioteixeira** [comment]
Okay, the problem must be somewhere else.  Camlhighlight compiles fine on my machine using the same package versions.  I'll have to investigate this further.

**Comment by darioteixeira** [comment]
Judging from other PR, there's probably something fishy going on with Sexplib...

**Comment by darioteixeira** [comment]
Okay, can someone relaunch this?  It seems the problem was elsewhere, and was fixed by PR #3841.

**Comment by yallop** [comment]
Can you rebase against master to pick up the changes from #3841?

**Comment by yallop** [comment]
Having said that, I don't think that the problem addressed by #3841 is the cause of the failure here.  It [appears](https://travis-ci.org/ocaml/opam-repository/jobs/56132987#L1021-L1030) that camlhighlight is missing a dependency on type_conv:

```
# /usr/bin/ocamlopt.opt unix.cmxa -I /usr/lib/ocaml/ocamlbuild /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# File "_tags", line 46, characters 29-47:
# Warning: the tag "pkg_sexplib.syntax" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
[...]
# ocamlfind: Using -syntax, but no package is selected specifying a preprocessor as required for -syntax
```

**Comment by darioteixeira** [comment]
The dependency on `type_conv `is indirect.  Camlhighlight depends on `sexplib`, which in turn does depend on `type_conv`.  If `sexplib` is properly packaged this should not be an issue at all.

**Comment by yallop** [comment]
type_conv is an optional dependency in recent versions of sexplib; without it the sexplib syntax extension is not enabled, causing the camlhighlight build to fail.  See #3844 for a fix.

**Comment by darioteixeira** [comment]
yallop: This still seems like the wrong way to solve this problem. The proper way is to specify that Camlhighlight depends on `sexplib.syntax` -- is this supported in OPAM?

**Comment by darioteixeira** [comment]
My clone of this repo got borked: it seems I shouldn't have pulled from upstream while this PR was still open.  Anyway, I'll close this PR and issue a new one.

**Pull request closed without merging**
