### PR TITLE
Updated pcre-ocaml

### PR DESCRIPTION
**Pull request by mmottl**

### CODE REVIEW

**Comment by yallop** [comment]
The build is [failing](https://travis-ci.org/ocaml/opam-repository/jobs/111029318), apparently due to a libpcre version mismatch:

```
# /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -strict-sequence -I lib -package bytes -w Aer-44 -I examples/cloc -I lib -o examples/cloc/cloc.cmo examples/cloc/cloc.ml
# /home/travis/.opam/system/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -safe-string -strict-sequence -I lib -package bytes -w Aer-44 -I examples/cloc -I lib -o examples/cloc/cloc.cmx examples/cloc/cloc.ml
# /home/travis/.opam/system/bin/ocamlfind ocamlopt -g -I lib -linkpkg -package bytes lib/pcre.cmxa examples/cloc/cloc.cmx -o examples/cloc/cloc.native
# + /home/travis/.opam/system/bin/ocamlfind ocamlopt -g -I lib -linkpkg -package bytes lib/pcre.cmxa examples/cloc/cloc.cmx -o examples/cloc/cloc.native
# lib/libpcre_stubs.a(pcre_stubs.o): In function `pcre_dealloc_regexp':
# /home/travis/.opam/system/build/pcre.7.2.0/_build/lib/pcre_stubs.c:190: undefined reference to `pcre_free_study'
# collect2: ld returned 1 exit status
# File "caml_startup", line 1:
# Error: Error during linking
# Command exited with code 2.
```

**Comment by mmottl** [comment]
@yallop Thanks, it seems the PCRE library installed on the Travis host is really old, but it should still be supported.  I've added a patch that will hopefully fix this.

**Comment by yallop** [comment]
Everything's now passing except for the 3.12 build, which is [failing](https://travis-ci.org/ocaml/opam-repository/jobs/111224626) with the following error:

```
# lib/libpcre_stubs.a(pcre_stubs.o): In function `pcre_exec_stub':
# /home/travis/.opam/system/build/pcre.7.2.1/_build/lib/pcre_stubs.c:530: undefined reference to `caml_array_length'
# collect2: ld returned 1 exit status
# File "caml_startup", line 1, characters 0-1:
# Error: Error during linking
# Command exited with code 2.
```

**Comment by mmottl** [comment]
@yallop Thanks, this backward compatibility issue should now be fixed, too.

**Pull request merged**
