### PR TITLE
Fix missing dependency on num in functoria-runtime.2.0.0

### PR DESCRIPTION
**Pull request by jpdeplaix**

### CODE REVIEW

**Comment by hannesm** [comment]
this is slightly surprising -- what of the functoria runtime requires which of num? //cc @Drup

**Comment by jpdeplaix** [comment]
The build log is here: http://obi.ocamllabs.io/logs/ecd90745df38cd85a05d3885d92d2f85.txt

**Comment by hannesm** [comment]
thanks... is this a tooling issue?
```
- + ocamlfind ocamlopt -a -keep-locs -package 'cmdliner fmt' -dontlink 'unix str num threads' -dontlink 'unix str num threads' -package bytes -I runtime runtime/functoria_runtime.cmx runtime/functoria_info.cmx -o runtime/functoria-runtime.cmxa
- ocamlfind: Package `num' not found
- Command exited with code 2.
```

it explicitly states `dontlink num`..

**Comment by jpdeplaix** [comment]
Oh yes.. Mmh I'm not sure what the behaviour of ```ocamlfind``` should be in that case.
I've changed the PR. It seems that ```num``` is not used anywhere anyway.

**Comment by dbuenzli** [comment]
Maybe related to https://github.com/ocaml/opam-repository/issues/10857 or https://github.com/ocaml/opam-repository/issues/10925

**Comment by Drup** [comment]
Well, that's awkward. I guess there is such a thing as being too safe.
It feels a bit like an ocamlfind bug, though ...

**Comment by jpdeplaix** [comment]
@dbuenzli the compilation of ```topkg.0.9.1``` failed on 4.02.3. It seems to be related to a missing dependency over ```result```

**Pull request merged**
