### PR TITLE
added packages/lbvs_consent/lbvs_consent.1.1.3

### PR DESCRIPTION
**Pull request by UnixJunkie**
fix so that it compiles with the current version of the cpm library

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The only failure is on OSX. Could you explain the reason behind having:
```
["sh" "-c" "brew tap rdkit/rdkit && brew install rdkit"] {os = "darwin"}
```
in the build phase ? It's a bit unrelated to this but I find it a bit dubious :/

**Comment by UnixJunkie** [comment]
The command you are mentioning comes from the conf-rdkit package.
This brew recipe is very often broken and users have trouble installing it.
However, last time I checked, it was the official way to install rdkit on mac os x.
You can complain here https://github.com/rdkit/homebrew-rdkit/issues if it repeatedly does not work.

**Comment by UnixJunkie** [comment]
I think you are asking for changes into conf-rdkit's opam file.
I don't think it is a good idea: if the brew formula for rdkit was working, then conf-rdkit would install automatically on a mac.
Of course, if in the depexts field there was a way to specify a brew tap, then it could go into the depexts
but I don't think there is such a mechanism currently.

**Comment by kit-ty-kate** [comment]
I think the problem is for users who want to use another version of rdkit than the one available through this method. They wouldn't use `opam depext` and thus wouldn't expect to have the build phase install something on itself (+ it doesn't seem to work on Travis anyway).

**Comment by UnixJunkie** [comment]
cf. https://github.com/ocaml/opam-repository/pull/11931

**Comment by kit-ty-kate** [comment]
Looks good, thanks !

**Pull request merged**
