### PR TITLE
fix for ocamltter.2.1.0

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
It fails before compiling the package. Restart please

**Comment by samoht** [comment]
Restarted

**Comment by lefessan** [comment]
Uninstallation issues in https://travis-ci.org/ocaml/opam-repository/jobs/135376435 ?
Is it reproducible ?

**Comment by camlspotter** [comment]
Still some files remain...  I will fix this slowly...

**Comment by camlspotter** [comment]
Cleanly cleaned!

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
