### PR TITLE
added Frama-C.20160501

### PR DESCRIPTION
**Pull request by maroneze**

### CODE REVIEW

**Comment by maroneze** [comment]
Should I take into account the results from Travis CI? The error log is truncated to 4MB and the error messages seem unrelated to the commit itself, unless I've misunderstood them.

**Comment by samoht** [comment]
I'm sure you don't really want to commit 9835 files into that repository :p seems that you put all frama-c in there!

**Comment by maroneze** [comment]
Indeed, sorry for that, now it's a more reasonable size...

**Comment by maroneze** [comment]
I think the warnings were already present in previous versions and I'm not sure if there's an easy and safe way to remove them. @bobot can you please confirm that?

About the ocamlfind dependency, I think that would be better indeed, unless @bobot corrects me.

**Comment by dsheets** [comment]
Thanks!

**Pull request merged**
