### PR TITLE
Package ocaml-protoc-plugin.2.0.0

### PR DESCRIPTION
**Pull request by andersfugmann**
### `ocaml-protoc-plugin.2.0.0`
Plugin for protoc protobuf compiler to generate ocaml definitions from a .proto file
The plugin generates ocaml type definitions,
serialization and deserialization functions from a protobuf file.
The types generated aims to create ocaml idiomatic types;
- messages are mapped into modules
- oneof constructs are mapped to polymorphic variants
- enums are mapped to adt's
- map types are mapped to assoc lists
- all integer types are mapped to int by default (exact mapping is also possible)
- all floating point types are mapped to float.
- packages are mapped to nested modules

---
* Homepage: https://github.com/issuu/ocaml-protoc-plugin
* Source repo: git+https://github.com/issuu/ocaml-protoc-plugin
* Bug tracker: https://github.com/issuu/ocaml-protoc-plugin/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by andersfugmann** [comment]
CentOS fails as its running centos7, which is not supported as the needed files are not distrubuted with this version. The solution would be to restrict centos to version >= 8, but I don't know how to do this. I've tried:

```
available: (os-distribution != "ubuntu" | os-version >= "18.04") & (os-distribution != "centos" | os-version >= "8")
```
but it does not seem to restrict centos to version >= 8. depext do not by default output the `os-version`, so its hard to see how the `os-version` variable is set, and what to match on.

**Comment by andersfugmann** [comment]
AFAICS, depext sets `os-release`to the value of the key `VERSION_ID` in `/etc/os-release` ([src/state/opamSysPoll.ml](https://github.com/ocaml/opam/blob/master/src/state/opamSysPoll.ml#L119)).

For centos7, the value is `"7"` and for centos8 its `"8"`, so I'm a but puzzled as to why the package can be installed on cenos7.

**Comment by andersfugmann** [comment]
```

**Comment by andersfugmann** [comment]
Ahh. I think I found the problem. `ocaml-protoc-plugin` did not have a version constraint on conf-protoc, so the previous version (1.0.0) was installed.

**Comment by andersfugmann** [comment]
All green and ready to merge.

**Comment by kit-ty-kate** [comment]
Is there a reason why `conf-protoc` needs to have a new version? `1.0.0` and `1.0.1` seems worryingly identical.

**Comment by andersfugmann** [comment]
Version 1.0.0 are supposed to have google's well know .proto files included along with the protoc compiler (its actually required by the spec that these are available). However, ocaml-protoc-plugin now relies on these protoc files, and I discovered that these were not available on centos7 and some depends were missing. 
To avoid revisionism, I elected to create a 1.0.1 (semantic versioning - fixing bugs). 

If you prefer, I can port the changes to conf-protoc 1.0.0.

**Comment by andersfugmann** [comment]
@kit-ty-kate If you need further information, or would like me to change something, just let me know.

**Comment by kit-ty-kate** [comment]
I'm really sorry for the time I took to reply. I ported the change to `conf-protoc.1.0.0`, that seems to be a really minimal change, I think it's safe to just port it. If it's really a problem in the future we can still split in two packages at some point in the future.

**Comment by andersfugmann** [comment]
Look good to me. Thanks a lot! - and no worries about the delay.
I've added `flags: conf` to conf-protoc.0.0.9 also. Once green it should be ready to go.

**Comment by kit-ty-kate** [comment]
Oh I missed that one. Thanks!

**Pull request merged**
