### PR TITLE
Revert "mark old releases of mpp and glical as unavailable."

### PR DESCRIPTION
**Pull request by pw374**
Reverts ocaml/opam-repository#26919

Stuff back online.

### CODE REVIEW

**Comment by hannesm** [comment]
Thanks. Would you mind to add sha256 checksums to the opam files?

**Comment by hannesm** [comment]
I added the sha256 checksums for the archives, this is ready to be merged now.

**Comment by shonfeder** [comment]
Thanks, @hannesm!

**Comment by shonfeder** [comment]
No worries! Thank you for making this fix with recovered sources!

**Pull request merged**
