### PR TITLE
conduit: remove upper bounds on 3.0.0

### PR DESCRIPTION
**Pull request by mseri**
Since https://github.com/ocaml/opam-repository/pull/18517 makes 3.0.0 unavailable and the new 4.0.0 is backward compatible

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>

### CODE REVIEW

**Comment by mseri** [comment]
There are many `datakit` failure with `unknown module Flow_lwt_unix_hvsock`, do you know which upper bound is needed?

**Comment by mseri** [comment]
This failure makes no sense: https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/50d922a31693b13aa28f36adc4967290bac1d2f4/variant/compilers,4.04,ketrew.3.1.0
The opam file requires a version of `js_of_ocaml` that includes `js_of_ocaml.tyxml`, how can it be failing? Is there a concurrency issue when building?

**Comment by mseri** [comment]
`conduit-lwt-unix.1.0.3` revdeps contain multiple failures of all recent `cohttp-lwt-unix` module:
```
conduit-lwt-unix.1.0.3
    revdeps
        cohttp-lwt-unix.2.2.0 (failed: Cohttp Server Test:9:client_close)
        cohttp-lwt-unix.2.4.0 (failed: Cohttp Server Test:9:client_close)
        cohttp-lwt-unix.2.5.0 (failed: Cohttp Server Test:9:client_close)
        cohttp-lwt-unix.2.5.1 (failed: Cohttp Server Test:9:client_close)
        cohttp-lwt-unix.4.0.0 (failed: Cohttp Server Test:6:client_close)
```
Logs are clogged by
```
- [WARNING][application]: Closing channel failed: Unix.Unix_error(Unix.EBADF, "check_descriptor", "")
- [WARNING][application]: Closing channel failed: Unix.Unix_error(Unix.EBADF, "check_descriptor", "")
- [WARNING][application]: Closing channel failed: Unix.Unix_error(Unix.EBADF, "check_descriptor", "")
- [WARNING][application]: Closing channel failed: Unix.Unix_error(Unix.EBADF, "check_descriptor", "")
```

I am going to add a lower bound later on. Was this a known issue?

**Comment by mseri** [comment]
Besides the `datakit` error for which somebody needs to tell me what needs to be done, and the `cohttp-lwt-unix` test failure (which I believe depends on the sandboxing). This should be good to merge

**Comment by kit-ty-kate** [comment]
> Besides the `datakit` error for which somebody needs to tell me what needs to be done, and the `cohttp-lwt-unix` test failure (which I believe depends on the sandboxing). This should be good to merge

yeah the failures you pointed out above are most likely due to sandboxing. For `datakit` the package already fails with the the same error so we can ignore that for now

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
