### PR TITLE
New release of Menhir.

### PR DESCRIPTION
**Pull request by fpottier**
Major additions to Menhir (still undocumented; documentation coming soon).
Plus a fix so that "opam remove menhir" properly removes standard.mly.

### CODE REVIEW

**Comment by yallop** [comment]
There's one [remaining issue](https://travis-ci.org/ocaml/opam-repository/jobs/87021312) when uninstalling: the contents of the `doc/menhir` directory are not removed:

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[WARNING] Directory /home/travis/.opam/system/doc/menhir is not empty, not
          removing
```

Adding the following to the [remove command](https://github.com/ocaml/opam-repository/pull/5034/files#diff-4fcc40863678e6754bc175241e3cf5e1R19) should fix it:


```
  ["rm" "-fr" "%{doc}%/menhir"]
```

**Comment by fpottier** [comment]
Hi Jeremy,
Thanks for pointing this out. I have tried to fix everything by just calling [make uninstall].

**Comment by yallop** [comment]
Good idea! Could you please do the same for the [`20151012` release](https://github.com/ocaml/opam-repository/pull/5034/files#diff-4fcc40863678e6754bc175241e3cf5e1R18)?

**Comment by fpottier** [comment]
On Fri, Oct 23, 2015 at 07:21:36AM -0700, yallop wrote:
> Good idea! Could you please do the same for the [`20151012` release](https://github.com/ocaml/opam-repository/pull/5034/files#diff-4fcc40863678e6754bc175241e3cf5e1R18)?

Hello Jeremy,

Is there a point in updating old package descriptions?
Anyway, I've done it.

-- 
François Pottier
Francois.Pottier@inria.fr
http://gallium.inria.fr/~fpottier/

**Comment by yallop** [comment]
> Is there a point in updating old package descriptions?

It's sometimes helpful if other packages depend on versions other than the latest.

**Pull request merged**
