### PR TITLE
[new release] rpclib-html, rpclib-async, rpclib, rpc, rpclib-lwt, ppx_deriving_rpc and rpclib-js (7.1.0)

### PR DESCRIPTION
**Pull request by mseri**
A library to deal with RPCs in OCaml - html documentation generator

- Project page: <a href="https://github.com/mirage/ocaml-rpc">https://github.com/mirage/ocaml-rpc</a>
- Documentation: <a href="https://mirage.github.io/ocaml-rpc/rpclib-html">https://mirage.github.io/ocaml-rpc/rpclib-html</a>

##### CHANGES:

* Test suite refactoring
* Port to latest ppxlib
* Add ~strict flag to xmlrpc generation
* Support encoding/decoding of base64
* port to dune 2
* Add the possibility of having null as params in a requests for JSON-RPC

### CODE REVIEW

**Comment by avsm** [comment]
I think this might need some upper bounds on previous users of the library.
e.g. for xapi-rrd.0.12.0:

```
#=== ERROR while compiling xapi-rrd.0.12.0 ====================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.10.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.10/.opam-switch/build/xapi-rrd.0.12.0
# command              /usr/bin/make
# exit-code            2
# env-file             ~/.opam/log/xapi-rrd-25-1338df.env
# output-file          ~/.opam/log/xapi-rrd-25-1338df.out
### output ###
# oasis setup
# W: No replace section found in file Makefile
# ocaml setup.ml -configure --enable-tests
# File "./setup.ml", line 1775, characters 22-40:
# 1775 |         let compare = Pervasives.compare
#                              ^^^^^^^^^^^^^^^^^^
# Alert deprecated: module Stdlib.Pervasives
# Use Stdlib instead.
# 
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
# File "setup.ml", line 3467, characters 16-34:
# Alert deprecated: module Stdlib.Pervasives
# Use Stdlib instead.
# 
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
# ocamlfind: Package `rpclib.syntax' not found
# W: Field 'pkg_rpclib_syntax' is not set: Command ''/home/opam/.opam/4.10/bin/ocamlfind' query -format %d rpclib.syntax > '/tmp/oasis-f1f934.txt'' terminated with error code 2
# E: Cannot find findlib package rpclib.syntax
# E: Failure("1 configuration error")
# make: *** [Makefile:36: setup.data] Error 1
```

**Comment by mseri** [comment]
Indeed! I am surprised that it was not already marked incompatible with recent ocaml versions.

**Comment by kit-ty-kate** [comment]
I had this error while checking for packages compatible with the janestreet packages v0.14. Is this normal and fixed by the recent commits in this PR?
```
# ocamlfind: Package `ppx_deriving' not found - required by `ppx_deriving_rpc'
```

**Comment by mseri** [comment]
I think it is an incompatibility between old ppx_deriving And ocamlbuild and new dune and ppxlib. It should not happen on recent libraries. Where did you get it?

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
