### PR TITLE
[elpi] [win] use Digest rather than shasum

### PR DESCRIPTION
**Pull request by gares**
This makes the package work on windows with no change, CC @fdopen @msoegtropIMC
The patch is already applied upstream (in master)

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
Hmm - this is lacking the temp file patch, so as is it wouldn't work on Windows. This version does work (in first tests) on macOS, Linux and Windows: (https://github.com/MSoegtropIMC/coq-platform/tree/v8.12/opam/packages/elpi/elpi.1.11.4)

**Comment by gares** [comment]
Oh right, I'm adding that

**Comment by gares** [comment]
The temp file patch is OK also on linux and OSX, I've tested it in CI and merged it upstream already

**Comment by MSoegtropIMC** [comment]
Perfect, thanks!

**Comment by kit-ty-kate** [comment]
```
- TIMEOUT  grundlagen (type checker for λδ)          elpi
```
Just so you know, I've seen this error quite a bit. Is there any way to get deterministic tests? It would be really good for us if it was possible.

Otherwise it's good to merge. Thanks

**Comment by gares** [comment]
I guess the best would be to separate simple test from benchmarks. I'll try something.

**Pull request merged**
