### PR TITLE
ocamlfind: Fix num's META file installation when reinstalled

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes https://github.com/ocaml/opam-repository/issues/10925

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Waiting a few days for review.

**Comment by avsm** [comment]
Great to see this fixed. I think it really needs an ok from @dra27, as he looked at the original problem report.

**Comment by dra27** [comment]
This is a very good catch! It feels as though there should be fixes in two places: it would be good if findlib's build system supported deferring the detection of the `META` files so that it could be run in `install`, but it would also be good if opam had a flag which indicated a package which doesn't support being built when it's already installed.

For this PR, the duplication of the full `configure` line is unfortunate (it always was) and it also reveals past inconsistency with use of flags like `-no-custom`. Looking both at 1.3.1 (the oldest packaged version of `ocamlfind`) and 1.8.1, I would propose this simplification of the `install` stage:

```
install: [
  # Redetect currently-installed META files, see ocaml/opam-repository#17891
  ["mv" "Makefile.config" "build-config"]
  ["./configure" "-sitelib" lib]
  ["mv" "build-config" "Makefile.config"]
  [make "install"]
]
```

The re-run of `configure` will generate a nonsense `Makefile.config`, but it will succeed and it will generate the correct set of `META` files. All of those missing flags only affect `Makefile.config`, they don't affect any tests in `configure`, beyond some unnecessary probing of `ocamlc -config`.

**Comment by kit-ty-kate** [comment]
While I agree this duplication is unfortunate, I'm really not convinced by the alternative proposal. This issue is going to be fixed upstream at some point anyway (via https://github.com/ocaml/ocamlfind/pull/12) so I'd rather make sure we keep those two duplicate equal rather than relying on knowing what every options to `./configure` does in every versions. (from my point of view)

It can still be improved in a future PR but for now I'd rather fix the original issue as I keep being busy with other things and don't really have time to look at that. It's not a huge deal if we have this intermediate solution in the meantime.

**Comment by dra27** [comment]
I completely agree! As we'd discussed offline, if/when the upstream patch is merged, there's a minimum set of backports possibly worth doing, but the problem will be permanently fixed with the latest version

**Pull request merged**
