### PR TITLE
Add dev-repo field for github packages

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by AltGr** [comment]
This supersedes #3140 and #4692, using the new format-preserving reprinter.

**Comment by AltGr** [comment]
Once this is merged I still have a few more up my sleeve:
- add a `{build}` flag to ocamlfind depends (although that would lose `depends:` field comments and formatting...)
- split `build:` and `install:` fields (same remark, on the `build:` field; the script isn't guaranteed to be correct, obviously, but in practice I didn't find a concrete example where it yielded a bad result)
- add the `light-uninstall` flag to packages that just call `ocamlfind remove` from their `remove:` field, so that the hack can be removed from opam (maybe that could wait for 1.3; also, maybe `light-uninstall` should be the default and a flag should be given to require the removal commands to be done from the unpacked source tree)

Splitting build and install, in particular, will be very useful for many things, including properly tracking installed files (and automatically providing clean removal).

**Comment by AltGr** [comment]
Any reason to hold this ?

**Comment by samoht** [comment]
On 1.2.2:
```
[31m[ERROR][m async & lwt (< 2.4.3 | >= 2.5.0) is not a valid conjunction
```

**Comment by AltGr** [comment]
ack, I changed the semantics of `conflicts:` to make more sense, so it should now be a disjunction; I thought no package actually expliciely used a conjunction but it seems there was at least `cohttp`.

I propose to rewrite:
```
conflicts: [
  "async" {< "109.15.00"}
  "async" {>= "113.00.00"}
  "lwt" {< "2.4.3" & >= "2.5.0"}
]
```

to 
```
conflicts: [
  "async" {< "109.15.00"}
  "async" {>= "113.00.00"}
  "lwt" {< "2.4.3"}
  "lwt" {>= "2.5.0"}
]
```
which is unambiguous. Would that be ok ?

**Comment by AltGr** [comment]
@gasche you might trip on this as well

**Comment by samoht** [comment]
@AltGr that changes seems good to me

**Comment by gasche** [comment]
Is your new proposal backward-compatible, in the sense that 1.2 opams understand what this mean? If so, then that would make trunk-opam-printers compatible with 1.2-readers again -- currently I had to disable `conflicts` field cleanup to avoid the current state `{ < X | >= Y }`.

**Comment by AltGr** [comment]
@gasche indeed, as there were actually two changes:
- the list is interpreted as a disjunction rather than a conjunction
- conflicts are required to be a disjunction rather than a conjunction

**Comment by AltGr** [comment]
cf. #5224 -- that one was easy!

**Comment by samoht** [comment]
ping?

**Comment by samoht** [comment]
ping?

**Comment by AltGr** [comment]
Interesting... force-pushing a commit that is already on master to the PR branch (by mistake) causes Github to mark the PR as closed. Makes sense I guess...

**Comment by AltGr** [comment]
Updated

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
