### PR TITLE
Package uint.1.2.1

### PR DESCRIPTION
**Pull request by andrenth**
### `uint.1.2.1`

Unsigned ints for OCaml

---
* Homepage: https://github.com/andrenth/ocaml-uint
* Source repo: https://github.com/andrenth/ocaml-uint.git
* Bug tracker: https://github.com/andrenth/ocaml-uint/issues

---
### opam-lint failures
- **WARNING** 97 long description unspecified

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by gasche** [comment]
The CI fails under pre-4.2 machines, which shows I think that you haven't done the bytes-compatibility dance properly. See the [4.01 logs](https://travis-ci.org/ocaml/opam-repository/jobs/296767262) for example.

If your intent in specifying `base-bytes` is to mark this package as incompatible with pre-Bytes OCaml version (before 4.02), then you should depend on `base-bytes.base` (or use `available: [ocaml-version > "4.02"]`, but I prefer the more semantic dependency).

If your intent is to make sure that the backward-compatibility `bytes` ocamlfind package is present on the system, then you should slightly change your build system to pass the `bytes` package to the ocamlfind invocation.

**Comment by andrenth** [comment]
The idea was to mark the package as incompatible with older stdlibs. Interestingly I just copied the opam file from the stdint library, because uint is really old and didn't have one, and on stdint there's a dependency on "base-bytes".

So is better to tag a new release replacing base-bytes with base-bytes.base, or is there a way to amend this PR?

**Comment by gasche** [comment]
You don't need a new release to update the `opam` string present in the repository, you can just amend your branch and rebase your PR. You should probably fix the `opam` file contained in your upstream development repository, if any, but that is a separate matter.

(Note: if you copied this from stdint, then I guess its opam file is also wrong, unless it properly links the `bytes` package at compilation-time.)

**Comment by andrenth** [comment]
Hopefully fixed now.

**Comment by gasche** [comment]
Now Travis fails on all OCaml versions. I think using `"base-bytes.base"` directly is wrong, you should use a version constraint: `"base-bytes" {= "base"}`.

**Comment by andrenth** [comment]
Done.

**Pull request merged**
