### PR TITLE
add conf-perl dependency to mirage-xen-minios

### PR DESCRIPTION
**Pull request by timbertson**

### CODE REVIEW

**Comment by hannesm** [comment]
where exactly is `perl` needed in mirage-xen-minios?

**Comment by timbertson** [comment]
Seems to be from the minios install script itself, based on this output:

```
+ make build
./install.sh
+ . ./vars.sh
++ '[' /nix/store/k9vm03w033jpb88hhc9zmzrrk0k30xrd-mirage-xen-minios-0.7.0 = '' ']'
++ MINIOS=minios-v0.6
++ MINIOS_ARCHIVE=minios-v0.6.tar.gz
++ MINIOS_URL=https://github.com/talex5/xen/archive/minios-v0.6.tar.gz
++ LIBM=openlibm-0.4.1-tal1
++ LIBM_ARCHIVE=v0.4.1-tal1.tar.gz
++ LIBM_URL=https://github.com/talex5/openlibm/archive/v0.4.1-tal1.tar.gz
+ rm -rf xen-minios-v0.6
+ tar -zxf minios-v0.6.tar.gz
+ cd xen-minios-v0.6/extras/mini-os
+ make debug=n
make[1]: Entering directory '/run/user/1000/nix-build-mirage-xen-minios-0.7.0.drv-0/mirage-xen-minios/xen-minios-v0.6/extras/mini-os'
perl /run/user/1000/nix-build-mirage-xen-minios-0.7.0.drv-0/mirage-xen-minios/xen-minios-v0.6/extras/mini-os/../../tools/include/xen-external/bsd-sys-queue-h-seddery /run/user/1000/nix-build-mirage-xen-minios-0.7.0.drv-0/mirage-xen-minios/xen-minios-v0.6/extras/mini-os/../../tools/include/xen-external/bsd-sys-queue.h --prefix=minios  >include/list.h.new
/bin/sh: perl: command not found
```

**Comment by hannesm** [comment]
thx. this should then be in `mirage-xen-minios <0.8.0` (since 0.8.0, `mirage-xen-minios` depends on `xen-minios` (which already depends on `conf-perl`))!?

**Comment by timbertson** [comment]
Ahh I see, thanks for pointing that out - I had only built 0.7 but assumed 0.8 since these things don't change often. I've (force) pushed a new version which only adds this to 0.7.

**Comment by samoht** [comment]
thanks!

**Pull request merged**
