### PR TITLE
Package letters.0.3.2

### PR DESCRIPTION
**Pull request by joseferben**
### `letters.0.3.2`
Client library for sending emails over SMTP
Simple to use SMTP client implementation for OCaml

---
* Homepage: https://github.com/oxidizing/letters/
* Source repo: git+https://github.com/oxidizing/letters.git
* Bug tracker: https://github.com/oxidizing/letters/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mseri** [comment]
All versions of `sihl-email` up to 3.0.5 (included) are failing with
```
# File "sihl-email/sihl_email.ml", line 118, characters 6-70:
# 118 |       Letters.Config.make ~username ~password ~hostname ~with_starttls
#             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: This expression has type
#          ?mechanism:Sendmail.mechanism -> Letters.Config.t
#        but an expression was expected of type Letters.Config.t
```
Should I add an upper bound?

**Comment by mseri** [comment]
Are you sure about the signature of `make`? With your current signature it is pointless to have mechanism optional:
```
  val make
    :  ?mechanism:Sendmail.mechanism
    -> username:string
    -> password:string
    -> hostname:string
    -> with_starttls:bool
    -> t
```
has no positional argument, so afaik, the optional one will not be erasable. Something like
```
> let f ?a ~b ~c = ();;
Line 1, characters 7-8:
Warning 16 [unerasable-optional-argument]: this optional argument cannot be erased.
val f : ?a:'a -> b:'b -> c:'c -> unit = <fun>
```

**Comment by joseferben** [comment]
@mseri We changed the release to be backwards compatible, thanks for the input.

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
