### PR TITLE
compression/encryption for headers/body/attachments

### PR DESCRIPTION
**Pull request by gregtatcam**

### CODE REVIEW

**Comment by avsm** [comment]
This failure should be fixed when ocaml/opam-repository#3483 is merged

**Comment by avsm** [comment]
can you merge this against the master branch of opam-repository?

**Comment by gregtatcam** [comment]
done

**Comment by avsm** [comment]
Real failure this time: missing dependency on `bz2`

```
### stderr ###
# ocamlfind: Package `bz2' not found
# W: Field 'pkg_bz2' is not set: Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d bz2 > '/tmp/oasis-5bf8f0.txt'' terminated with error code 2
# ocamlfind: Package `bz2' not found
# W: Failure("Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d bz2 > '/tmp/oasis-96f7d3.txt'' terminated with error code 2")
# ocamlfind: Package `bz2' not found
# W: Failure("Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d bz2 > '/tmp/oasis-c6c28d.txt'' terminated with error code 2")
# E: Cannot find findlib package bz2
# E: Failure("1 configuration error")
```

**Comment by gregtatcam** [comment]
fixed

**Comment by avsm** [comment]
Test still failing -- looks like 0.15 doesnt have it (the buildbot will try all the versions in the pull req)

**Comment by gregtatcam** [comment]
added camlbz2 to 0.1.5

**Pull request closed without merging**
