### PR TITLE
[new release] ppx_distr_guards (0.2)

### PR DESCRIPTION
**Pull request by vogler**
Extension to distribute guards over or-patterns

- Project page: <a href="https://github.com/vogler/ppx_distr_guards">https://github.com/vogler/ppx_distr_guards</a>
- Documentation: <a href="https://vogler.github.io/ppx_distr_guards">https://vogler.github.io/ppx_distr_guards</a>

##### CHANGES:

- Initial version.

### CODE REVIEW

**Comment by vogler** [comment]
For OCaml 4.02-4.05 the test fails because of missing whitespace in tuples.
Any best practice to deal with such things? If not, I'll try to normalize it with sed.

**Comment by vogler** [comment]
Do I need to do something or is CI currently not working right?

For any OCaml <4.10:
~~~
[ERROR] No switch 4.09 is currently installed. Did you mean 'opam switch create 4.09'?
        Installed switches are:
          - 4.10
~~~
For OCaml 4.10:
~~~
Step 2/8 : RUN echo 'archive-mirrors: [ "file:///home/opam/opam-repository/cache" ]' >> /home/opam/.opam/config &&   opam switch 4.10 &&   git pull origin master &&   opam update &&   opam install -yv opam-depext &&   opam pin add -y opam-ci-scripts https://github.com/kit-ty-kate/opam-ci-scripts.git
 ---> Running in 4597dcc38dab
# Run eval $(opam env) to update the current shell environment
fatal: not a git repository (or any of the parent directories): .git
~~~

**Comment by kit-ty-kate** [comment]
Sorry for the cryptic error messages, they were unrelated. Thanks!

**Comment by kit-ty-kate** [comment]
Could you also return the fixes upstream?

**Comment by vogler** [comment]
Thanks! The test failed because of trailing whitespaces in different places across OCaml versions. I fixed it here: https://github.com/vogler/ppx_distr_guards/commit/2c940519e6c638be2d291a6cc2fab7d9ab79a854
Can I `dune-release` it again here with the same version by changing the tag or should I make a new version/PR?

**Pull request merged**
