### PR TITLE
Added new lens.1.0.0

### PR DESCRIPTION
**Pull request by pdonadeo**

### CODE REVIEW

**Comment by avsm** [comment]
Needs to be `ocaml-version >= 4.01.0`

**Comment by pdonadeo** [comment]
I'll fix it ASAP. In this moment I'm out of office.

**Comment by pdonadeo** [comment]
But... what now? Why Travis is trying to integrate for OCaml 4.00.1?

**Comment by yallop** [comment]
It's fine; the build failed for unrelated reasons, perhaps a result of temporary connectivity problems.  I've restarted the failed job.

**Comment by pdonadeo** [comment]
@yallop ok, sorry for the noise, I'm not used to Travis.

**Pull request merged**
