### PR TITLE
io-page: add bounds to io-page-unix and io-page-xen to prepare the re…

### PR DESCRIPTION
**Pull request by samoht**
…lease

### CODE REVIEW

**Comment by samoht** [comment]
I'd like to fix all rev-deps before merging this PR.

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by samoht** [comment]
@kit-ty-kate did you check if all the revdeps were green?

**Comment by kit-ty-kate** [comment]
oops sorry, I'm not too sure, from the partial logs they were all green but some were still running. Sorry about that

**Pull request merged**
