### PR TITLE
vchan: add missing upper bounds on xen-gnt

### PR DESCRIPTION
**Pull request by djs55**
There were already bounds on xen-evtchn, but xen-gnt were missed.

Related to https://github.com/mirage/ocaml-vchan/issues/102

Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by avsm** [comment]
```
#=== ERROR while installing vchan.0.9.5 =======================================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              make
# path                 /home/opam/.opam/4.03.0/build/vchan.0.9.5
# compiler             4.03.0
# exit-code            2
# env-file             /home/opam/.opam/4.03.0/build/vchan.0.9.5/vchan-29-89dc30.env
# stdout-file          /home/opam/.opam/4.03.0/build/vchan.0.9.5/vchan-29-89dc30.out
# stderr-file          /home/opam/.opam/4.03.0/build/vchan.0.9.5/vchan-29-89dc30.err
### stdout ###
# Makefile:15: recipe for target 'setup.data' failed
### stderr ###
# [...]
# W: Field 'pkg_cstruct_syntax' is not set: Command ''/home/opam/.opam/4.03.0/bin/ocamlfind' query -format %d cstruct.syntax > '/tmp/oasis-40ba37.txt'' terminated with error code 2
# ocamlfind: Package `xen-evtchn.unix' not found
# W: Field 'pkg_xen_evtchn_unix' is not set: Command ''/home/opam/.opam/4.03.0/bin/ocamlfind' query -format %d xen-evtchn.unix > '/tmp/oasis-da4a5e.txt'' terminated with error code 2
# ocamlfind: Package `xen-evtchn.unix.activations' not found
# W: Field 'pkg_xen_evtchn_unix_activations' is not set: Command ''/home/opam/.opam/4.03.0/bin/ocamlfind' query -format %d xen-evtchn.unix.activations > '/tmp/oasis-cb91b3.txt'' terminated with error code 2
# E: Cannot find findlib package cstruct.syntax
# E: Cannot find findlib package xen-evtchn.unix
# E: Cannot find findlib package xen-evtchn.unix.activations
# E: Failure("3 configuration errors")
# make: *** [setup.data] Error 1
```

**Comment by djs55** [comment]
@avsm it looks like the oldest version `vchan.0.9.5` is broken for other reasons too -- I'll try to fix it.

**Comment by djs55** [comment]
The missing `cstruct.syntax` has been fixed. There are failures of other packages: `irmin` and `mirage-conduit` which seem unrelated.

The `xen-evtchn.unix.activations` failure is still there because the sub package is conditionally built depending on whether the system has the C headers are not. I could add `depexts` to the old `xen-evtchn` to cover this case but this is only needed for Unix and might be a problem if targeting Xen. The new split-out `xen-evtchn{,-unix}.2.0.0` handles this properly: only the `unix` package has the `depext`s.

I think this change is still necessary, it's just not sufficient to reliably build old versions of `vchan`.

**Comment by djs55** [comment]
Actually I've changed my mind -- I think adding the `depext`s won't actually be harmful for the Unikernel cases -- if they're installed, the unnecessary sub package will be built; and if they're not installed, it's no problem. So I'll err on the side of making everything build by adding the depexts too.

**Comment by samoht** [comment]
Can you copy/paste the irmin pb if you them again. I'd like to fix those :-)

**Comment by avsm** [comment]
The mirage-conduit build failures are hopefully addressed in #9475

**Pull request merged**
