### PR TITLE
[new release] conduit (5 packages) (7.1.0)

### PR DESCRIPTION
**Pull request by samoht**
A network connection establishment library

- Project page: <a href="https://github.com/mirage/ocaml-conduit">https://github.com/mirage/ocaml-conduit</a>
- Documentation: <a href="https://mirage.github.io/ocaml-conduit/">https://mirage.github.io/ocaml-conduit/</a>

##### CHANGES:

* Support TLS tunnel over Lwt_io.channel (mirage/ocaml-conduit#428, @art-w)

### CODE REVIEW

**Comment by mseri** [comment]
Websockets, ocsigenserver and maybe a few more are failing with:
```
#=== ERROR while compiling ocsigenserver.5.0.1 ================================#
# context              2.3.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/ocsigenserver.5.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ocsigenserver -j 255
# exit-code            1
# env-file             ~/.opam/log/ocsigenserver-7-3f6ec4.env
# output-file          ~/.opam/log/ocsigenserver-7-3f6ec4.out
### output ###
# (cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -g -bin-annot -I src/server/.ocsigenserver.objs/byte -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/astring -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/bytes -I /home/opam/.opam/4.14/lib/cohttp -I /home/opam/.opam/4.14/lib/cohttp-lwt -I /home/opam/.opam/4.14/lib/cohttp-lwt-unix -I /home/opam/.opam/4.14/lib/conduit -I /home/opam/.opam/4.14/lib/conduit-lwt -I /home/opam/.opam/4.14/lib/conduit-lwt-unix -I /home/opam/.opam/4.14/lib/cryptokit -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/findlib -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/hmap -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/ipaddr-sexp -I /home/opam/.opam/4.14/lib/ipaddr/unix -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/lwt/unix -I /home/opam/.opam/4.14/lib/lwt_log -I /home/opam/.opam/4.14/lib/lwt_log/core -I /home/opam/.opam/4.14/lib/lwt_ssl -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/magic-mime -I /home/opam/.opam/4.14/lib/ocaml/threads -I /home/opam/.opam/4.14/lib/ocplib-endian -I /home/opam/.opam/4.14/lib/ocplib-endian/bigstring -I /home/opam/.opam/4.14/lib/pcre -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/re -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/ssl -I /home/opam/.opam/4.14/lib/stringext -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/uri-sexp -I /home/opam/.opam/4.14/lib/uri/services -I /home/opam/.opam/4.14/lib/xml-light -I /home/opam/.opam/4.14/lib/zarith -I src/baselib/.baselib.objs/byte -I src/baselib/.ocsigen_lib_base.objs/byte -I src/baselib/polytables/.polytables.objs/byte -I src/http/.http.objs/byte -I src/http/.ocsigen_cookie_map.objs/byte -intf-suffix .ml -no-alias-deps -o src/server/.ocsigenserver.objs/byte/ocsigen_cohttp.cmo -c -impl src/server/ocsigen_cohttp.ml)
# File "src/server/ocsigen_cohttp.ml", line 147, characters 29-32:
# 147 |   let sockaddr = getsockname edn in
#                                    ^^^
# Error: This expression has type Conduit_lwt_unix.endp
#        but an expression was expected of type
#          [< `TCP of Ipaddr.t * int
#           | `TLS of 'b * 'a
#           | `Unix_domain_socket of string
#           | `Unknown of string
#           | `Vchan_direct of 'c
#           | `Vchan_domain_socket of 'd ]
#          as 'a
#        The second variant type does not allow tag(s) `TLS_tunnel
# (cd _build/default && /home/opam/.opam/4.14/bin/ocamlopt.opt -w -40 -g -I src/server/.ocsigenserver.objs/byte -I src/server/.ocsigenserver.objs/native -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/astring -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/bytes -I /home/opam/.opam/4.14/lib/cohttp -I /home/opam/.opam/4.14/lib/cohttp-lwt -I /home/opam/.opam/4.14/lib/cohttp-lwt-unix -I /home/opam/.opam/4.14/lib/conduit -I /home/opam/.opam/4.14/lib/conduit-lwt -I /home/opam/.opam/4.14/lib/conduit-lwt-unix -I /home/opam/.opam/4.14/lib/cryptokit -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/findlib -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/hmap -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/ipaddr-sexp -I /home/opam/.opam/4.14/lib/ipaddr/unix -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/lwt/unix -I /home/opam/.opam/4.14/lib/lwt_log -I /home/opam/.opam/4.14/lib/lwt_log/core -I /home/opam/.opam/4.14/lib/lwt_ssl -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/magic-mime -I /home/opam/.opam/4.14/lib/ocaml/threads -I /home/opam/.opam/4.14/lib/ocplib-endian -I /home/opam/.opam/4.14/lib/ocplib-endian/bigstring -I /home/opam/.opam/4.14/lib/pcre -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/re -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/ssl -I /home/opam/.opam/4.14/lib/stringext -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/uri-sexp -I /home/opam/.opam/4.14/lib/uri/services -I /home/opam/.opam/4.14/lib/xml-light -I /home/opam/.opam/4.14/lib/zarith -I src/baselib/.baselib.objs/byte -I src/baselib/.baselib.objs/native -I src/baselib/.ocsigen_lib_base.objs/byte -I src/baselib/.ocsigen_lib_base.objs/native -I src/baselib/polytables/.polytables.objs/byte -I src/baselib/polytables/.polytables.objs/native -I src/http/.http.objs/byte -I src/http/.http.objs/native -I src/http/.ocsigen_cookie_map.objs/byte -I src/http/.ocsigen_cookie_map.objs/native -intf-suffix .ml -no-alias-deps -o src/server/.ocsigenserver.objs/native/ocsigen_cohttp.cmx -c -impl src/server/ocsigen_cohttp.ml)
# File "src/server/ocsigen_cohttp.ml", line 147, characters 29-32:
# 147 |   let sockaddr = getsockname edn in
#                                    ^^^
# Error: This expression has type Conduit_lwt_unix.endp
#        but an expression was expected of type
#          [< `TCP of Ipaddr.t * int
#           | `TLS of 'b * 'a
#           | `Unix_domain_socket of string
#           | `Unknown of string
#           | `Vchan_direct of 'c
#           | `Vchan_domain_socket of 'd ]
#          as 'a
#        The second variant type does not allow tag(s) `TLS_tunnel
```

is this a recent breaking change?

**Comment by samoht** [comment]
> is this a recent breaking change?

yes, `conduit_lwt_unix.7.1.0` introduce this new `TLS_tunnel` field. I'll add upper bounds. Thanks!

**Comment by avsm** [comment]
Just missing one upper bound on ocsigenserver 5.0.0 i think

**Comment by avsm** [comment]
Fixed and merged, thanks!

**Pull request merged**
