### PR TITLE
Updating urls of various packages: github -> framagit

### PR DESCRIPTION
**Pull request by zoggy**
I spent some time updating urls for packages which I moved from github to framagit. I dit not add missing fields to opam files, just updated urls and checksums. There may be errors in dependencies constraints but this PR does not aim at fixing this.

After this I will remove the corresponding repositories from github.

### CODE REVIEW

**Comment by mseri** [comment]
Thanks a lot!

**Comment by zoggy** [comment]
Can this be merged ? I have another PR ready to fix urls, but some include urls fixed in this PR.

**Comment by mseri** [comment]
I wanted to fix some lower bounds but remained in the backlog, sorry

**Comment by mseri** [comment]
I had compared the tarballs that I could find, there was no sensible change as far as I could tell

**Comment by zoggy** [comment]
Great, thanks !

**Comment by zoggy** [comment]
This is the next PR I referred to : https://github.com/ocaml/opam-repository/pull/20216

**Pull request merged**
