### PR TITLE
Fix no-shared-libs error in ocaml package

### PR DESCRIPTION
**Pull request by dra27**
This PR:

 - Refactors the ocaml package to eliminate the duplicated script
 - Eliminates the need for the Unix library, allowing installation on systems which can't dynamically load `unix.cma`

Should this be replicated in `opam admin upgrade`?

cc @avsm, @nojb, @AltGr, @rjbou

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Mmh now that `ocaml` is a simple package the CI wants to build every single of its revdeps (i.e. virtually all opam packages). That's annoying. I'll see if I can do something about it.

**Comment by mseri** [comment]
@dra27 does this need the feedback you asked for before being merged?

**Comment by vog** [comment]
I'm the author of the original problem description. (See issue https://github.com/ocaml/opam-repository/issues/12769, which led to issue https://github.com/ocaml/opam/issues/3608, which finally led to this pull request.)

Is there anything I can to do to assist here?

**Comment by avsm** [comment]
This looks good to merge and free us from CI spam :)

**Comment by rjbou** [comment]
> Should this be replicated in `opam admin upgrade`?

For consistency, yes, it will then be available from 2.0.2.

**Comment by mseri** [comment]
Done!

**Comment by dra27** [comment]
I've done a [Discuss post](https://discuss.ocaml.org/t/dont-panic-that-your-opam-switches-recompile-from-today/2816) explaining about the switch recompilation, in order to try to keep the issue tracker here quiet!

**Comment by mseri** [comment]
Thank you

**Comment by vog** [comment]
Thanks a lot for fixing this. The switch is finally usable for me, and works well for most packages.

However, installing `sqlite3` in that switch fails, which is very strange, as `sqlite3` is indeed supposed to work with static linking. I opened a separate issue for that: #12923

**Pull request merged**
