### PR TITLE
new file:   packages/nlopt/nlopt.0.0.6.1/opam

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I am testing some changes I made in a special branch; so that the git repository for nlopt can be opam pinned again; and the opam package becomes installable again

**Comment by UnixJunkie** [comment]
The fact that this package cannot install automatically currently blocks some of my software from being installed.
Developers can install nlopt by hand; but this is not acceptable for normal (end) users.

**Comment by UnixJunkie** [comment]
If those tests are OK; I'll send a PR upstream.

**Comment by UnixJunkie** [comment]
I guess Alpine Linux does not have libnlopt-dev.

**Comment by UnixJunkie** [comment]
I think the CI tests are OK for a few other Linux distros and even on a Mac with homebrew.
@mkur

**Comment by UnixJunkie** [comment]
I have sent the corresponding PR upstream.
https://github.com/mkur/nlopt-ocaml/pull/12

**Comment by dinosaure** [comment]
> I guess Alpine Linux does not have libnlopt-dev.

Can you add some constraints with `available` and say that this package is not available on `alpine` and so on (or `libnlopt-dev` has probably an other name on these distribution)?

**Comment by UnixJunkie** [comment]
Alpine has an nlopt package indeed.
https://pkgs.alpinelinux.org/package/edge/testing/x86_64/nlopt

**Comment by UnixJunkie** [comment]
I just added the missing Alpine depext for nlopt

**Comment by UnixJunkie** [comment]
should compile and install on archlinux and alpine now

**Comment by mseri** [comment]
On Archlinux it seems to install the package but still fails, maybe some flag is missing? FWIW I think this can be merged

**Comment by kit-ty-kate** [comment]
Thanks! Sorry for the delay

**Comment by kit-ty-kate** [comment]
@UnixJunkie mmh, maybe i made a mistake in merging this. Has @mkur agreed on the release or whatever change of maintainership? Is the release number `0.0.6.1` normal given the latest version was `0.6`?

If the package renaming is expected then a new `nlopt-ocaml.transition` package is probably expected to be added to simplify the change.

**Comment by mseri** [comment]
Oh well spotted, I had not noticed the change of maintainership. From the repo it is not clear that this was prearranged

**Comment by mkur** [comment]
> 



> I have sent the corresponding PR upstream. [mkur/nlopt-ocaml#12](https://github.com/mkur/nlopt-ocaml/pull/12)

Merged

**Comment by mkur** [comment]
No, it was not prearranged. While I am more than happy to have @UnixJunkie handle the build infra and let him maintain the opam package (not an opam expert myself) I would rather prefer if the opam package definition could point to the original repo. Or at least the release tags should be synchronized between repos. The most recent release in the original repo is 0.6.1 and includes UnixJunkies PR.

**Comment by UnixJunkie** [comment]
@mkur is lagging so much that it is difficult for me to follow.
This PR was sent more than a month ago.
There is no change of ownership, @mkur is still the maintainer of nlopt-ocaml.
I'll send another PR to update nlopt's package.
It will probably delete this one.

**Pull request merged**
