### PR TITLE
Release x509 0.7.0

### PR DESCRIPTION
**Pull request by hannesm**
CHANGES:

* major restructuring, it is unlikely any pre-0.7.0 users will work with 0.7.0+
* remove sexp de&encoders
* provide pretty-printers for validation errors (and types) instead of to_string functions
* use result type and Rresult instead of custom result types and control monad
* use a GADT map for certificate & csr extensions, distinguished names, general names (avoiding multiple extensions with the same OID, uses the gmap library)
* use domain-name library for hostname validation (instead of custom string matching)
* use ipaddr library for IPs in SubjectAlternativeName extension
* remove Encoding module, provide {en,de}code_{der,pem} in the respective modules (which decoders return (_, [> `Msg of string ]) result, no exceptions raised)
* fix DistributionPoint extension: the CRLissuer is a GeneralName, not a DistinguishedName
* remove Extension.reason_code (Extension.reason was there before, and is now used)
* remove bindings from toplevel, t is now Certificate.t, public_key is now Public_key.t
* use alcotest instead of oUnit

### CODE REVIEW

**Comment by hannesm** [comment]
I looked through CI failures, and they are unrelated (but due to fixing the upper bounds in reverse dependencies) -- and can be fixed in separate PRs.

**Comment by hannesm** [comment]
in a subsequent commit, I removed tls 0.9.0 -- which is broken (and has been fixed in 0.9.1), since the lwt sublibrary uses an internal module (named `Config`), thus exposing all internal modules (tls uses packing to avoid this).

**Comment by hannesm** [comment]
In more detail, CI failures (cc'ing the respective maintainers from the opam files)

calculon //cc @c-cube
```
#=== ERROR while compiling calculon.0.4 =======================================#
# context              2.0.4 | linux/x86_64 | ocaml-variants.4.08.1+trunk | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.08/.opam-switch/build/calculon.0.4
# command              ~/.opam/4.08/bin/dune runtest -p calculon -j 2
# exit-code            1
# env-file             ~/.opam/log/calculon-17-fc3ae8.env
# output-file          ~/.opam/log/calculon-17-fc3ae8.out
### output ###
#          mdx alias runtest (exit 125)
# (cd _build/default && /home/opam/.opam/4.08/bin/mdx test README.md)
# ocaml-mdx-test: internal error, uncaught exception:
#                 Failure("incomplete OCaml version")
```

git 2.0.0 //cc @dinosaure I suspect some missing upper bounds:
```
- File "src/git/deflate.ml", line 21, characters 10-23:
- 21 | type t = (B.Bigstring.t, B.Bigstring.t) Deflate.t
-                ^^^^^^^^^^^^^
- Error: Unbound module B
```

git-unix 2.0.0 //cc @dinosaure (suspect similar missing upper bounds)
```
# File "test/common/test_store.ml", line 317, characters 8-15:
# 317 |       | Error e -> Alcotest.failf "%a" ValueIO.EncoderRaw.pp_error e
#               ^^^^^^^
# Error: This pattern matches values of type ('a, 'b) result
#        but a pattern was expected which matches values of type
#          raw:Cstruct.t ->
#          etmp:Cstruct.t -> (string, ValueIO.EncoderRaw.error) result
#       ocamlc test/common/.test_git.objs/byte/test_store.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -w -40 -g -bin-annot -I test/common/.test_git.objs/byte -I /home/opam/.opam/4.08/lib/alcotest -I /home/opam/.opam/4.08/lib/angstrom -I /home/opam/.opam/4.08/lib/astring -I /home/opam/.opam/4.08/lib/base/caml -I /home/opam/.opam/4.08/lib/bigarray-compat -I /home/opam/.opam/4.08/lib/bigstringaf -I /home/opam/.opam/4.08/lib/bytes -I /home/opam/.opam/4.08/lib/checkseum -I /home/opam/.opam/4.08/lib/cmdliner -I /home/opam/.opam/4.08/lib/cstruct -I /home/opam/.opam/4.08/lib/decompress -I /home/opam/.opam/4.08/lib/decompress/impl -I /home/opam/.opam/4.08/lib/digestif -I /home/opam/.opam/4.08/lib/duff -I /home/opam/.opam/4.08/lib/encore -I /home/opam/.opam/4.08/lib/encore/butils -I /home/opam/.opam/4.08/lib/eqaf -I /home/opam/.opam/4.08/lib/fmt -I /home/opam/.opam/4.08/lib/fpath -I /home/opam/.opam/4.08/lib/git -I /home/opam/.opam/4.08/lib/hex -I /home/opam/.opam/4.08/lib/ke -I /home/opam/.opam/4.08/lib/logs -I /home/opam/.opam/4.08/lib/lru -I /home/opam/.opam/4.08/lib/lwt -I /home/opam/.opam/4.08/lib/lwt/unix -I /home/opam/.opam/4.08/lib/mmap -I /home/opam/.opam/4.08/lib/mtime -I /home/opam/.opam/4.08/lib/mtime/os -I /home/opam/.opam/4.08/lib/nocrypto -I /home/opam/.opam/4.08/lib/ocaml/threads -I /home/opam/.opam/4.08/lib/ocamlgraph -I /home/opam/.opam/4.08/lib/ocplib-endian -I /home/opam/.opam/4.08/lib/optint -I /home/opam/.opam/4.08/lib/parsexp -I /home/opam/.opam/4.08/lib/ppx_deriving/runtime -I /home/opam/.opam/4.08/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.08/lib/psq -I /home/opam/.opam/4.08/lib/re -I /home/opam/.opam/4.08/lib/re/posix -I /home/opam/.opam/4.08/lib/result -I /home/opam/.opam/4.08/lib/rresult -I /home/opam/.opam/4.08/lib/seq -I /home/opam/.opam/4.08/lib/sexplib -I /home/opam/.opam/4.08/lib/sexplib0 -I /home/opam/.opam/4.08/lib/stdlib-shims -I /home/opam/.opam/4.08/lib/stringext -I /home/opam/.opam/4.08/lib/uri -I /home/opam/.opam/4.08/lib/uuidm -I /home/opam/.opam/4.08/lib/zarith -no-alias-deps -o test/common/.test_git.objs/byte/test_store.cmo -c -impl test/common/test_store.ml)
# File "test/smart/test_smart.ml", line 460, characters 41-42:
# 460 |               (fun v -> `Advertised_refs v)
#                                                ^
# Error: This expression has type
#          (Smart.Common.advertised_refs, [ `Msg of string ]) result
#        but an expression was expected of type
#          Smart.Common.advertised_refs =
#            Git.Smart.Common(S.Hash)(S.Reference).advertised_refs
#       ocamlc test/smart/.test_smart.objs/byte/test_smart.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -w -40 -g -bin-annot -I test/smart/.test_smart.objs/byte -I /home/opam/.opam/4.08/lib/alcotest -I /home/opam/.opam/4.08/lib/angstrom -I /home/opam/.opam/4.08/lib/astring -I /home/opam/.opam/4.08/lib/base/caml -I /home/opam/.opam/4.08/lib/bigarray-compat -I /home/opam/.opam/4.08/lib/bigstringaf -I /home/opam/.opam/4.08/lib/bytes -I /home/opam/.opam/4.08/lib/checkseum -I /home/opam/.opam/4.08/lib/cmdliner -I /home/opam/.opam/4.08/lib/cstruct -I /home/opam/.opam/4.08/lib/decompress -I /home/opam/.opam/4.08/lib/decompress/impl -I /home/opam/.opam/4.08/lib/digestif -I /home/opam/.opam/4.08/lib/duff -I /home/opam/.opam/4.08/lib/encore -I /home/opam/.opam/4.08/lib/encore/butils -I /home/opam/.opam/4.08/lib/eqaf -I /home/opam/.opam/4.08/lib/fmt -I /home/opam/.opam/4.08/lib/fpath -I /home/opam/.opam/4.08/lib/git -I /home/opam/.opam/4.08/lib/hex -I /home/opam/.opam/4.08/lib/ke -I /home/opam/.opam/4.08/lib/logs -I /home/opam/.opam/4.08/lib/lru -I /home/opam/.opam/4.08/lib/lwt -I /home/opam/.opam/4.08/lib/lwt/unix -I /home/opam/.opam/4.08/lib/mmap -I /home/opam/.opam/4.08/lib/mtime -I /home/opam/.opam/4.08/lib/mtime/os -I /home/opam/.opam/4.08/lib/nocrypto -I /home/opam/.opam/4.08/lib/ocaml/threads -I /home/opam/.opam/4.08/lib/ocamlgraph -I /home/opam/.opam/4.08/lib/ocplib-endian -I /home/opam/.opam/4.08/lib/optint -I /home/opam/.opam/4.08/lib/parsexp -I /home/opam/.opam/4.08/lib/ppx_deriving/runtime -I /home/opam/.opam/4.08/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.08/lib/psq -I /home/opam/.opam/4.08/lib/re -I /home/opam/.opam/4.08/lib/re/posix -I /home/opam/.opam/4.08/lib/result -I /home/opam/.opam/4.08/lib/rresult -I /home/opam/.opam/4.08/lib/seq -I /home/opam/.opam/4.08/lib/sexplib -I /home/opam/.opam/4.08/lib/sexplib0 -I /home/opam/.opam/4.08/lib/stdlib-shims -I /home/opam/.opam/4.08/lib/stringext -I /home/opam/.opam/4.08/lib/uri -I /home/opam/.opam/4.08/lib/uuidm -I /home/opam/.opam/4.08/lib/zarith -no-alias-deps -o test/smart/.test_smart.objs/byte/test_smart.cmo -c -impl test/smart/test_smart.ml)
```

mirage-conduit 3.1.0 /cc @avsm (missing upper bound?)
```
#=== ERROR while compiling mirage-conduit.3.1.0 ===============================#
# context              2.0.4 | linux/x86_64 | ocaml-variants.4.08.1+trunk | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.08/.opam-switch/build/mirage-conduit.3.1.0
# command              ~/.opam/4.08/bin/dune build -p mirage-conduit -j 2
# exit-code            1
# env-file             ~/.opam/log/mirage-conduit-17-0f898d.env
# output-file          ~/.opam/log/mirage-conduit-17-0f898d.out
### output ###
#        ocaml (internal)
# ocamlfind: Package `launchd.lwt' not found
# ocamlfind: Package `lwt_ssl' not found
# /home/opam/.opam/4.08/lib/tls
# Configuration
#   launchd: false
#   ssl    : false
#   tls    : true
# File "mirage/dune", line 8, characters 42-53:
# 8 |                mirage-flow-lwt mirage-dns ipaddr.sexp
#                                               ^^^^^^^^^^^
# Error: Library "ipaddr.sexp" not found.
# Hint: try: dune external-lib-deps --missing -p mirage-conduit -j 2 @@default
```

certify 0.2.0 test script failure //cc @yomimono -- reported at https://github.com/yomimono/ocaml-certify/issues/18

**Comment by kit-ty-kate** [comment]
Can't we just tag `tls.0.9.0` with `available: false` ? I'm not against removing packages but this is not really a consensus.

**Comment by hannesm** [comment]
@kit-ty-kate as you wish, I force-pushed such a change here.

**Comment by kit-ty-kate** [comment]
thanks a lot!

**Pull request merged**
