### PR TITLE
Add mpris.0.1.1

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by johnelse** [comment]
Looks like this is failing on 4.06 because obus isn't available - I can limit this to OCaml < 4.06 if that's easiest?

**Comment by gasche** [comment]
@johnelse if you can confirm that your package does work with `-safe-string` (which you may test under 4.05 by just adding the `-safe-string` flag as a compiler option), then I think it's fine to ignore the 4.06 failure of your dependency. I would still wait for other CI results to have a complete picture before merging.

**Comment by johnelse** [comment]
Thanks, this does indeed build on 4.05 with `-safe-string` enabled.

**Comment by gasche** [comment]
Thanks!

**Pull request merged**
