### PR TITLE
Add Reason / Rtop 3.6.2

### PR DESCRIPTION
**Pull request by anmonteiro**
https://github.com/facebook/reason/issues/2630

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The tests fail with:
```
#=== ERROR while compiling reason.3.6.2 =======================================#
# context     2.0.7 | macos/x86_64 | ocaml-system.4.10.0 | file:///Users/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-system/.opam-switch/build/reason.3.6.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p reason -j 1
# exit-code   1
# env-file    ~/.opam/log/reason-97231-6cc03f.env
# output-file ~/.opam/log/reason-97231-6cc03f.out
### output ###
# [...]
# File "src/vendored-ocaml-migrate-parsetree-v1.7.3/test/driver/ppx1/dune", line 4, characters 12-35:
# 4 |  (libraries ocaml-migrate-parsetree))
#                 ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Library "ocaml-migrate-parsetree" not found.
# Hint: try:
#   dune external-lib-deps --missing -p reason -j 1 @runtest
# File "src/vendored-ocaml-migrate-parsetree-v1.7.3/test/driver/manual/dune", line 3, characters 12-35:
# 3 |  (libraries ocaml-migrate-parsetree)
#                 ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Library "ocaml-migrate-parsetree" not found.
# Hint: try:
#   dune external-lib-deps --missing -p reason -j 1 @runtest
```
I encountered the same issue when updating Reason to OCaml 4.12 in https://github.com/facebook/reason/pull/2635 and fixed it there.
I tried and `reason` does not have any tests ran using dune so I'll just disable them here in your PR to not bother you too much.

**Comment by anmonteiro** [comment]
Makes sense, appreciate it!

**Comment by anmonteiro** [comment]
Looks like the revdep failures are not reason's fault, but rather bugs in those libraries or missing dependencies.

**Comment by kit-ty-kate** [comment]
Fixed in https://github.com/ocaml/opam-repository/pull/17593, restarting CI.

**Comment by kit-ty-kate** [comment]
Looks good now. Thanks a lot!

**Pull request merged**
