### PR TITLE
Add BAP 0.9.6

### PR DESCRIPTION
**Pull request by ivg**

### CODE REVIEW

**Comment by ivg** [comment]
on 1.2.1 for some reason the checksum for easy format is bad:
```
[ERROR] Bad checksum for
        /home/travis/.opam/packages.dev/easy-format.1.0.2/easy-format-1.0.2.tar.gz:
          - 82f6db85477831cab11e4cfe80321225 [expected result]
          - 92e0128f0a869e9cbb519f232b5a1e5d [actual result]
```

will try to restart the build, maybe some temporary error.

**Comment by ivg** [comment]
Ha, I don't have rights to restart task =(

**Comment by yallop** [comment]
Yes, it looks like a transient problem.  I've restarted the [failed job](https://travis-ci.org/ocaml/opam-repository/jobs/59564551).

**Comment by ivg** [comment]
thanks, now it passes.

Btw, the error on darwin look opam-specific to me:
```
[ERROR] The compilation of uri failed at "ocaml setup.ml -install".
[ERROR] Actions cancelled because of
        Sys_error("/Users/travis/.opam/system/build/uri.1.8.0/uri-7175-3c16e6.env:
        Too many open files")
```
The `uri` library is very small, so I doubt that this is the cause of error. I suspect, that `opam` can leak descriptors

**Comment by avsm** [comment]
I just saw this too with a large upgrade on OS X. Fd leak somewhere...

**Comment by ivg** [comment]
anyway, would you like to merge the PR?

And would like me to file an issue about fds? I can try to reproduce it on mine machine, just to try to figure out who is leaking, opam or ci script. And if opam, then on which version. 

Since, on Mavericks with macports and opam 1.2.0 there is no issues.

**Pull request merged**
