### PR TITLE
[new release] lsp and ocaml-lsp-server (1.0.0)

### PR DESCRIPTION
**Pull request by rgrinberg**
LSP protocol implementation in OCaml

- Project page: <a href="https://github.com/ocaml/ocaml-lsp">https://github.com/ocaml/ocaml-lsp</a>

##### CHANGES:

- Initial Release

### CODE REVIEW

**Comment by mseri** [comment]
All failures are the same
```
#=== ERROR while compiling lsp.1.0.0 ==========================================#
2726# context              2.0.7 | linux/arm64 | ocaml-base-compiler.4.11.0 | file:///home/travis/build/ocaml/opam-repository
2727# path                 ~/.opam/ocaml-base-compiler.4.11.0/.opam-switch/build/lsp.1.0.0
2728# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p lsp -j 31 @install @runtest
2729# exit-code            1
2730# env-file             ~/.opam/log/lsp-18296-8a051f.env
2731# output-file          ~/.opam/log/lsp-18296-8a051f.out
2732### output ###
2733# [...]
2734# 11 |  (libraries stdlib-shims unix csexp)
2735#                                    ^^^^^
2736# Error: Library "csexp" not found.
2737# Hint: try:
2738#   dune external-lib-deps --missing -p lsp -j 31 @install @runtest
2739# File "lsp/src/dune", line 11, characters 0-57:
2740# 11 | (cinaps
2741# 12 |  (files types.mli types.ml)
2742# 13 |  (libraries lsp_gen))
2743# Error: Program cinaps not found in the tree or in PATH
2744#  (context: default)
2745# Hint: opam install cinaps
```

**Comment by mseri** [comment]
@rgrinberg thanks. Now it fails with a gigantic diff. Can you check if we just need to disable tests on the CI or if there some other issue behind it?

**Comment by rgrinberg** [comment]
Yeah, that’s annoying. I suppose I should just disable the tests for now.

**Comment by mseri** [comment]
Now lsp-server fails due to lack of octavius. I have added it myself, let’s see if it is enough.

FYI: I have noticed that the server does not build on 4.11 because it cannot find a compatible version of reason.

**Comment by rgrinberg** [comment]
Octavius is vendored. No idea why it’s missing.

Reason is just required for the tests.

**Comment by rgrinberg** [comment]
Perhaps it’s failing because it’s in a submodule? Let me check

**Comment by rgrinberg** [comment]
That seems to be the reason. I'll redo the release another time.

**Pull request closed without merging**
