### PR TITLE
3 packages from c-cube/ocaml-containers at 3.8

### PR DESCRIPTION
**Pull request by c-cube**
This pull-request concerns:
-`containers.3.8`: A modular, clean and powerful extension of the OCaml standard library
-`containers-data.3.8`: A set of advanced datatypes for containers
-`containers-thread.3.8`: An extension of containers for threading

---
* Homepage: https://github.com/c-cube/ocaml-containers/
* Source repo: git+https://github.com/c-cube/ocaml-containers.git
* Bug tracker: https://github.com/c-cube/ocaml-containers/issues/

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by c-cube** [comment]
oseq error is unrelated, I'm publishing a patch release.

**Comment by mseri** [comment]
Thanks

**Comment by mseri** [comment]
Does oseq.0.4.0 need an upper bound on ocaml 4.14?

**Comment by c-cube** [comment]
Thank you!

**Comment by c-cube** [comment]
> Does oseq.0.4.0 need an upper bound on ocaml 4.14?

maybe, because of the test part…

**Pull request merged**
