### PR TITLE
New package version why 2.41

### PR DESCRIPTION
**Pull request by claudemarche**

### CODE REVIEW

**Comment by claudemarche** [comment]
Any reason why not accepting this pull request?

**Comment by hcarty** [comment]
@claudemarche Can you look at the Travis failures?  It looks like why3 is failing to build there.

Beyond that I think this is ok to merge.

**Comment by claudemarche** [comment]
Indeed, all the errors I see come from other packages than the why package, so I don't see how to do better.

**Comment by hcarty** [comment]
Thanks!

**Pull request merged**
