### PR TITLE
tezos-p2p: Relax constraints on Lwt

### PR DESCRIPTION
**Pull request by kit-ty-kate**
@pirbo the package compiles. Is there a particular reason why the constraint is there?

### CODE REVIEW

**Comment by pirbo** [comment]
Tests are not compatible with Lwt 5 (because of the deprecation of Lwt_unix.set_default_async_method).

I'm OK with deactivating the tests from the opam package and remove that constraint. Tezos binaries works indeed well when compiled with lwt 5.

**Comment by kit-ty-kate** [comment]
@pirbo ok, does the current patch look ok for you? I changed it so it will effectively only use lwt < 4.3 when testing, and any version >= 4.0 otherwise (in most cases)

**Comment by kit-ty-kate** [comment]
if this looks good, could it be ported upstream? (if compatibility with Lwt >= 4.3 is not already fixed)

**Comment by pirbo** [comment]
Seems good to me, yes.
Uptream and version 8.0 (to be released next week the latest) are fully compatible with lwt >= 4.3

**Comment by kit-ty-kate** [comment]
> Uptream and version 8.0 (to be released next week the latest) are fully compatible with lwt >= 4.3

Oh, in that case I'll just wait for the next release and keep my patches local for testing purpose. Thanks!

**Pull request closed without merging**
