### PR TITLE
[BAP] brew support

### LINKED ISSUE #7575: bap 1.0.0 on osx failures
Here are a few things that are failing /cc @ivg

# bap-byteweight

The install procedure is trying to `wget` data:
```
wget -O /Users/dbuenzli/.opam/4.03.0/share/bap/sigs.zip https://github.com/BinaryAnalysisPlatform/bap/releases/download/v1.0.0/sigs.zip
```
 `wget` doesn't exist on osx and an install procedure should not try to download things. I think you should either provide the data in the distribution or provide the through another package. In particular this will prevent to install the package in offline opams which is an important use case for air gap settings.

# bap-objdump

There seem to be an error in the way `configure` is invoked:

```
> opam install bap-objdump -v -v 
The following actions will be performed:
  ∗  install bap-objdump 1.0.0

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[bap-objdump] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
+ tar "xfz" "/Users/dbuenzli/.opam/archives/bap-objdump.1.0.0+opam.tar.gz" "-C" "/var/folders/g4/nl6g_ytj63bbn9d45_jhggxc0000gn/T/opam-24769-7afd23"
+ mv "/var/folders/g4/nl6g_ytj63bbn9d45_jhggxc0000gn/T/opam-24769-7afd23/bap-objdump.1.0.0" "/Users/dbuenzli/.opam/4.03.0/build/bap-objdump.1.0.0"
[bap-objdump: ./configure] Command started
+ ./configure "--prefix=/Users/dbuenzli/.opam/4.03.0" "--enable-objdump" "--objdump-targets=[]" "--objdump-path=" (CWD=/Users/dbuenzli/.opam/4.03.0/build/bap-objdump.1.0.0)
- none: option '--objdump-path' needs an argument.
- configure options:
[...]
```

# bap-llvm.1.0.0 

It seems configure fails to find `llvm`: 

```
- E:   Failed to find llvm library, consider using --with-llvm-version
-      or --with-llvm-config command line options, to point me on a
-      correct version of LLVM. 
```

Even though `opam depext` says:

```
> opam depext bap-llvm.1.0.0
# Detecting depexts using flags: x86_64 osx homebrew
# The following system packages are needed:
#  - gmp
# All required OS packages found.
```

### PR DESCRIPTION
**Pull request by ivg**
This PR will bring support for Homebrew.  It also makes the installation procedure more robust on other platforms. 

# Details

A new meta package is added, called `conf-bap-llvm`, that will try to find on a system a version of llvm, that is supported by BAP. This is instead of `con-llvm.system` package, that was actually too BAP specific, and didn't make sense in some settings, i.e., on systems that do not have a default version of LLVM, e.g., `macports`. That's why we decided to factor out BAP specific behavior in a separate package prefixed with `bap`. We used the `OR` clause to depend on both `conf-bap-llvm` and `conf-llvm` packages. Thus, if a specific `conf-llvm` is not chosen or not installed, then by default a `conf-bap-llvm` is installed that will try to find any suitable version. Otherwise, whatever user has specified is used. As a final fallback, we added an ability to explicitly specify a particular `llvm-config` file with the `LLVM_CONFIG` environmental variable. 

## Travis
With the new approach we no longer need any Travis specific tricks, however, we are still unable to run tests on mac, as we are always killed by timeout during `brew install /homebrew/versions/llvm34`. Those who want, are encouraged to test the installation using the following Vagrantfile:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "AndrewDryga/vagrant-box-osx"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
  end
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
brew install opam
opam init --auto-setup --yes
eval `opam config env`
opam repo add bap-on-brew git://github.com/BinaryAnalysisPlatform/opam-repository#bap-on-brew
opam depext --install bap
SHELL
end
```

Of course, you will need mac labeled hardware to run this VM. 

## Github 
- resolve BinaryAnalysisPlatform/bap#568
- resolve #7575

### CODE REVIEW

**Comment by ivg** [comment]
Can someone provide a justification for "error 34"?
Also, is it possible to run Camelus on our own fork of the repository, so that we can reveal the problems before we submit the PR (alternatively can we run Camelus locally).

**Comment by ivg** [comment]
> Can someone provide a justification for "error 34"? 

Actually, it doesn't matter, I've just checked that it works without this extra constrained. I will update PR with fixes.

**Comment by avsm** [comment]
Camelus' source is at https://github.com/AltGr/Camelus

**Comment by avsm** [comment]
Hm, Travis doesn't seem to have picked up this commit. Any chance of a dummy commit to trigger it again?

**Comment by ivg** [comment]
Hmm... I'm trying, but it doesn't want to start. However, on our fork it works fine:
https://travis-ci.org/BinaryAnalysisPlatform/opam-repository/builds

This is the same branch, so the results should be identical.

**Comment by ivg** [comment]
Ha, actually, it did started several days ago, but for some reason Travis didn't report it back:
https://travis-ci.org/ocaml/opam-repository/builds/166824744

**Comment by avsm** [comment]
Looks like it timed out on the LLVM builds, restarting

**Comment by ivg** [comment]
It will always timeout :) As you may see in the [history][1] of builds, it never had enough time to even install llvm-3.4. I'm not sure why it takes so long, as on mine local VM it takes only a dozen minutes (probably 10 to 15 minutes in a fresh VM, where on Travis, it is killed with the timeout after 20 minutes of building LLVM, and another 30 were spent before it by the machine bootup). I myself, tested using the Vagrant file that is in the top posting. 

[1]: https://travis-ci.org/BinaryAnalysisPlatform/opam-repository/builds

**Pull request merged**
