### PR TITLE
tsdl-image: add archlinux depext

### PR DESCRIPTION
**Pull request by thizanne**

### CODE REVIEW

**Comment by hcarty** [comment]
tsdl is failing to install on Arch.  I'm not familiar enough with it or SDL2 to know if this is due to an issue with tsdl or the SDL2 version being too old.

**Comment by dbuenzli** [comment]
`tsdl` should install correctly only on `macos` see [this comment](https://github.com/ocaml/opam-repository/pull/9914#issuecomment-317581361).

**Comment by hcarty** [comment]
@dbuenzli Ah thank you!

@thizanne It looks like there is a test failure on macOS - https://travis-ci.org/ocaml/opam-repository/jobs/334794166

**Comment by jpdeplaix** [comment]
Merging this as it is an improvement over the current state but the errors on debian are a little worrying.
Looks like the binding is not up-to-date or too up-to-date. cc @tokenrove

**Comment by tokenrove** [comment]
I haven't had the chance to look at some reported Travis failures for tsdl-image dating back some time, but no one has reported any actual build failures to me.  Please do let me know (or better yet, submit a PR) if tsdl-image needs updating.  Thanks.

**Pull request merged**
