### PR TITLE
base, sexplib, ppx_*_conv: v0.10.0

### PR DESCRIPTION
**Pull request by trefis**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
There seem to be still a circular dependency between ```base``` and ```sexplib```.

**Comment by trefis** [comment]
Indeed, my bad.
This should be fixed now.

**Comment by trefis** [comment]
OK, so, there are a few revdeps failure, most of which are spurious.
Here are the proper failures:
- ocamlformat: needs an upper bound on a base
- conduit: needs an upper bound on ppx_driver

Here are some failures I don't understand:
- ocaml-topexpect: cf. [this ci-log](https://ci.ocaml.io/log/saved/docker-run-ebb58b6e210ee2ca077f40c58f8cd7e6/4a8f737047840551a560bc246543132c3a886fa9)
- boomerang: (might need an upper bound on ppx_hash, but I doubt that explains the failure) cf. [this ci-log](https://ci.ocaml.io/log/saved/docker-run-7542b05f468e7da7872a940fb6ab7b3b/f3ccbac4010f3740ef12f1f5ecf97a1a644adce1)
- xapi-backtrace: cf. [this ci-log](https://ci.ocaml.io/log/saved/docker-run-3641cb68e6c4df2a7cd0dca23877f95b/d4573daee489cc810e9eca0ad30c79961ed0fcbf) 

And the following packages failed randomly (container didn't start before timeout, opam failing to retrieve the sources for some of its deps), only once or twice while it looks like every package is build something like 40 times (hopefully the PR jpdeplaix linked above will fix that too): datakit-ci, command_rpc, async_kernel, ppx_js_style, async_parallel, protocol-9p, async_smtp, mirage-next-xen, async_zmq, nbd, x509.

**Comment by gasche** [comment]
The `boomerang` failure looks like a change to weak type variable scoping in 4.05 or 4.06. I would make the guess that it was already failing before.

`ocaml-topexpect` also broke on the OCaml version that introduced `-args{,0}` in the compiler command-line, as it seems to have a non-monotonous dependency on the compiler command-line stuff. (or maybe on the interface of the `Args` module.)

The `xapi-backtrace` failure is mysterious.

I *think* that it is ok to ignore these three failures.

Could you either rebase you PR to fix the "proper" failures, or open separate PRs for them? (When there are too much of them, or when it's too wide-ranging, it's better to open separate PRs to get separate testing.)

**Pull request merged**
