### PR TITLE
hardcaml-llvmsim: fix deps

### PR DESCRIPTION
**Pull request by damiendoligez**
Add a missing dep on `ctypes-foreign` and a bound on `llvm` version.

### CODE REVIEW

**Comment by damiendoligez** [comment]
Note: relaunch the OSX travis job after #7425 is merged.

**Comment by yallop** [comment]
#7425 is merged, and I've relaunched the OS X job (which may well time out; we'll see).

**Comment by samoht** [comment]
I've restarted the jobs again.

**Comment by avsm** [comment]
ping @andrewray on this one.

**Comment by andrewray** [comment]
I suspect a number of older hardcaml packages will also break because of the new version.  Is there an explanation somewhere of the various CI tests performed?

**Comment by andrewray** [comment]
First up the linux version - some strange things going on here.

1. [pre-install check - select llvm3.4](https://travis-ci.org/ocaml/opam-repository/jobs/152687243#L618)
2. [depext install - for llvm3.9(!)](https://travis-ci.org/ocaml/opam-repository/jobs/152687243#L672)
3. [actual install - select llvm3.5](https://travis-ci.org/ocaml/opam-repository/jobs/152687243#L887)

**Comment by andrewray** [comment]
OSX seems to suffer a similar issue - installing the depext for llvm3.9 rather that the version selected for compilation.

**Comment by avsm** [comment]
We need to sort out llvm depexts systematically -- merging this PR as it improves the basic bounds.

**Pull request merged**
