### PR TITLE
Extend Travis to push back opam-lint reports as PR comments

### PR DESCRIPTION
**Pull request by AltGr**
this can later be extended with e.g. dose-distchecks reports :)

### CODE REVIEW

**Comment by samoht** [comment]
yay! would be nice to merge some of the scripts with https://github.com/ocaml/ocaml-travisci-skeleton/blob/master/.travis-ocaml.sh at some point

**Comment by AltGr** [comment]
gaah, do travis "secret" tokens only work when you push from another branch in the same repo, but not from a fork ?
commit-back worked there: https://github.com/ocaml/opam-repository/pull/4206 (https://travis-ci.org/ocaml/opam-repository/jobs/66192715#L86)
but not here (https://travis-ci.org/ocaml/opam-repository/jobs/66191876#L86)

**Comment by dsheets** [comment]
GitHub personal tokens should work against any endpoint that the token's scopes allow (and for which the user is authorized).

**Comment by AltGr** [comment]
the problem is not the token: it's the travis encryption. You encrypt for a specific owner/repo (e.g. travis encrypt  "OPAM_CI_TOKEN=xxx" -r ocaml/opam-repository`), then put that in the .travis.yml file (https://github.com/ocaml/opam-repository/pull/4205/files#diff-354f30a63fb0907d4ad57269548329e3R19), and it gets decrypted by travis and set in the build script env (https://travis-ci.org/ocaml/opam-repository/jobs/66192715#L87)

But when PRing from a different repo, it seems it's not decrypted properly...

**Comment by amirmc** [comment]
I think this is by design.

from: http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests

> 
> ##### Security Restrictions when testing Pull Requests #
>
> The most important restriction for pull requests is about secure environment variables, or rather, any data that’s encrypted with our encryption feature.
> 
> A pull request sent from a fork of the upstream repository could be manipulated to expose any environment variables. The upstream repository’s maintainer would have no protection against this attack, as pull requests can be sent by anyone with a fork.
>
> For the protection of secure data, Travis CI makes it available only on pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.

**Comment by AltGr** [comment]
Ah. Makes sense indeed. But doesn't serve us well...

**Comment by AltGr** [comment]
Thanks @amirmc for the pointer.

Maybe Travis is not the fit in this case: the problem would be solved by simply having the tests registered somewhere static, rather than in the code (and the PR) itself. When we use these tests for security validations (http://opam.ocaml.org/blog/Signing-the-opam-repository/#Travis) directing the decision to merge by the repository managers, that could be an issue too, as one could attempt to trick them if they overlook the list of modified files (with limited consequences, as the repository bot should refuse unsigned changes to the travis scripts, but that still could be annoying).

Writing this in OCaml as a standalone service will actually just be a bit of glue between cohttp, opam-lib, ocaml-git and ocaml-github. Sounds fairly easy, we're not short on hosting options and a simple github webhook should do. It will be easier to extend with the security checks when we get to the signed repo, too.

Of course, we could just put the token in plain text to have this PR work. opam-ci is just a fresh github user without any authorisations, and the token further restricts what can be done. Still, it could be used for spam or faking reports, and that should be enough to not consider this an option.

**Comment by AltGr** [comment]
And now the PR shows green because the same commit was green when PRed from the same repo ?

**Comment by AltGr** [comment]
Now have it running as a small cohttp+ocaml-git service :)

**Pull request closed without merging**
