### PR TITLE
Package wall.0.1

### PR DESCRIPTION
**Pull request by let-def**
### `wall.0.1`

Realtime Vector Graphics with OpenGL

Lightweight, fast and declarative vector graphics rasterization using OpenGL.

---
* Homepage: https://github.com/let-def/wall
* Source repo: git+https://github.com/let-def/wall.git
* Bug tracker: https://github.com/let-def/wall

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There is a missing C header:
```
#=== ERROR while installing wall.0.1 ==========================================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -p wall -j 2
# path                 /home/opam/.opam/4.05.0/build/wall.0.1
# compiler             4.05.0
# exit-code            1
# env-file             /home/opam/.opam/4.05.0/build/wall.0.1/wall-7-70a526.env
# stdout-file          /home/opam/.opam/4.05.0/build/wall.0.1/wall-7-70a526.out
# stderr-file          /home/opam/.opam/4.05.0/build/wall.0.1/wall-7-70a526.err
### stderr ###
#       ocamlc lib/wall__backend_stubs.o (exit 2)
# (cd _build/default/lib && /home/opam/.opam/4.05.0/bin/ocamlc.opt -g -I /home/opam/.opam/4.05.0/lib/gg -I /home/opam/.opam/4.05.0/lib/grenier -I /home/opam/.opam/4.05.0/lib/result -I /home/opam/.opam/4.05.0/lib/stb_image -I /home/opam/.opam/4.05.0/lib/stb_truetype -ccopt -g -o wall__backend_stubs.o wall__backend_stubs.c)
# wall__backend_stubs.c:8:23: fatal error: GLES2/gl2.h: No such file or directory
#  #include <GLES2/gl2.h>
#                        ^
# compilation terminated.
```
Could you add the appropriate `conf-*` package that would pull `libgles2-mesa-dev` ? (I guess it's this one)

**Comment by let-def** [comment]
I don't intend to submit a patch to Centos to fix their dependency :P.

**Comment by kit-ty-kate** [comment]
Seems like you need to require OCaml >= 4.03:
```
/usr/bin/ocamlopt.opt: unknown option '-O3'.
```
Could you also fix the constraints of `gg.0.9.1` to be able to see the result on Mac and Travis 4.06 ? (for some reason it uses this version)

**Comment by kit-ty-kate** [comment]
Looks good now. Thanks a lot !!

**Pull request merged**
