### PR TITLE
Add owl.0.3.0

### PR DESCRIPTION
**Pull request by ryanrhymes**
The new release 0.3.0 of Owl. 

The detailed information about this release is here: [CHANGES.md](https://github.com/ryanrhymes/owl/blob/2a6cb4f385de08b49cf83dd4f9d6da3c206fd1ad/CHANGES.md)

### CODE REVIEW

**Comment by mseri** [comment]
I think you no longer need `owl.install` now that you are using `jbuilder`.
Also, you will need to release `owl_zoo` and `owl_top` as separate packages as far as I know

**Comment by ryanrhymes** [comment]
@mseri Many thanks, I will fix it and publish the other two separately ... probably a lot of glitches in this release, thanks for the patience.

**Comment by mseri** [comment]
Can you please add
```
available: [ ocaml-version >= "4.04.0" ]
```
to the `opam` file?

**Comment by mseri** [comment]
It is failing on osx because of a missing openblas

```
#=== ERROR while installing owl.0.3.0 =========================================#

# opam-version 1.2.2

# os           darwin

# command      jbuilder build -p owl -j 4

# path         /Users/travis/.opam/system/build/owl.0.3.0

# compiler     system (4.06.0)

# exit-code    1

# env-file     /Users/travis/.opam/system/build/owl.0.3.0/owl-10332-6205f5.env

# stdout-file  /Users/travis/.opam/system/build/owl.0.3.0/owl-10332-6205f5.out

# stderr-file  /Users/travis/.opam/system/build/owl.0.3.0/owl-10332-6205f5.err

### stderr ###

# Unix.map_file raises Unix_error.

# [...]

#       ocamlc src/owl/owl_neural_parallel.{cmi,cmo,cmt}

#       ocamlc src/owl/owl_ext.{cmi,cmo,cmt}

#       ocamlc src/owl/owl_sparse.{cmi,cmo,cmt}

#       ocamlc src/owl/owl_dense_common_c.o

#       ocamlc src/owl/owl_neural.{cmi,cmo,cmt}

#   ocamlmklib src/owl/dllowl_stubs.so,src/owl/libowl_stubs.a (exit 2)

# (cd _build/default && /usr/local/bin/ocamlmklib.opt -g -o src/owl/owl_stubs src/owl/owl_dense_common_c.o src/owl/owl_dense_common_vec_cmp.o src/owl/owl_dense_common_vec_map.o src/owl/owl_dense_common_vec_fold.o src/owl/owl_cblas_generated_stub.o src/owl/owl_lapacke_generated_stub.o -L/usr/local/lib/gcc/7 -lopenblas -lgfortran -lm)

# ld: library not found for -lopenblas

# clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
is this expected? Do depexts need update?

**Comment by mseri** [comment]
I am going to merge this, `conf-openblas` can be fixed as a separate PR. Please feel free to announce it on discuss.ocaml.org.

**Comment by ryanrhymes** [comment]
I think the main issue is how to link to OpenBLAS and Fortran. I don't have a good solution for OpenBLAS, the `conf-openblas` I made before seems still having problems. I will find some time in looking into Fortran issue.

**Comment by mseri** [comment]
I think we can merge this in the meanwhile. Aside openblas and gfortran, everything else seems to be fine

**Pull request merged**
