### PR TITLE
ocamltter: constraint to <ppx_meta_conv.2.6.0

### PR DESCRIPTION
**Pull request by avsm**
otherwise fails with "Package `ppx_meta_conv_ocaml' not found"

cc @camlspotter

### CODE REVIEW

**Comment by camlspotter** [comment]
Thanks @avsm, yes, ocamltter cannot compile with ppx_meta_conv.2.6.0.

**Comment by camlspotter** [comment]
cmi file corruption... I guess it is disk-full.

**Comment by avsm** [comment]
I dont think that cmi corruption is a full disk -- it seems to be a race condition during parallel builds.

**Comment by avsm** [comment]
Hm no, it happens only on ocamltter.4.1.0 and on both 4.04.0[+flambda]

**Pull request merged**
