### PR TITLE
Mark existing Lwt versions as incompatible with ocaml.5.1

### PR DESCRIPTION
**Pull request by raphael-proust**
Because: https://github.com/ocsigen/lwt/pull/995

Also see: https://github.com/ocaml/opam-repository/pull/24213#issuecomment-1669306812

### CODE REVIEW

**Comment by mseri** [comment]
Thanks

**Comment by kit-ty-kate** [comment]
We should've waited for the new release to be merged before merging that because that breaks people's setup if they use OCaml 5.1

**Comment by raphael-proust** [comment]
@kit-ty-kate because then there is no installable version available at all under 5.1?

**Comment by kit-ty-kate** [comment]
yeah exactly

**Pull request merged**
