### PR TITLE
[new release] dune (1.5.0)

### PR DESCRIPTION
**Pull request by rgrinberg**
CHANGES:

- Filter out empty paths from `OCAMLPATH` and `PATH` (ocaml/dune#1436, @rgrinberg)

- Do not add the `lib.cma.js` target in lib's directory. Put this target in a
  sub directory instead. (ocaml/dune#1435, fix ocaml/dune#1302, @rgrinberg)

- Install generated OCaml files with a `.ml` rather than a `.ml-gen` extension
  (ocaml/dune#1425, fix ocaml/dune#1414, @rgrinberg)

- Allow to use the `bigarray` library in >= 4.07 without ocamlfind and without
  installing the corresponding `otherlib`. (ocaml/dune#1455, @nojb)

- Add `@all` alias to build all targets defined in a directory (ocaml/dune#1409, fix
  ocaml/dune#1220, @rgrinberg)

- Add `@check` alias to build all targets required for type checking and tooling
  support. (ocaml/dune#1447, fix ocaml/dune#1220, @rgrinberg)

- Produce the odoc index page with the content wrapper to make it consistent
  with odoc's theming (ocaml/dune#1469, @rizo)

- Unblock signals in processes started by dune (ocaml/dune#1461, fixes ocaml/dune#1451,
  @diml)

- Respect `OCAMLFIND_TOOLCHAIN` and add a `toolchain` option to contexts in the
  workspace file. (ocaml/dune#1449, fix ocaml/dune#1413, @rgrinberg)

- Fix error message when using `copy_files` stanza to copy files from
  a non sub directory with lang set to dune < 1.3 (ocaml/dune#1486, fixes ocaml/dune#1485,
  @NathanReb)

- Install man pages in the correct subdirectory (ocaml/dune#1483, fixes ocaml/dune#1441, @emillon)

- Fix version syntax check for `test` stanza's `action` field. Only
  emits a warning for retro-compatibility (ocaml/dune#1474, fixes ocaml/dune#1471,
  @NathanReb)

- Fix interpretation of paths in `env` stanzas (ocaml/dune#1509, fixes ocaml/dune#1508, @diml)

- Add `context_name` expansion variable (ocaml/dune#1507, @rgrinberg)

- Use shorter paths for generated on-demand ppx drivers. This is to
  help Windows builds where paths are limited in length (ocaml/dune#1511, fixes
  ocaml/dune#1497, @diml)

- Fix interpretation of environment variables under `setenv`. Also forbid
  dynamic environment names or values (ocaml/dune#1503, @rgrinberg).

### CODE REVIEW

**Comment by rgrinberg** [comment]
Okay. Results look good. I haven't seen the owl failure before:

```
# /home/opam/.opam/4.07/lib/eigen/eigen.a(eigen_utils.o): In function `camlEigen_utils__3':
# :(.data+0xa0): undefined reference to `caml_owl_change_layout'
# collect2: error: ld returned 1 exit status
# File "caml_startup", line 1:
# Error: Error during linking
```

cc @ryanrhymes

**Comment by mseri** [comment]
I leave this as reminder for myself: add sexplib as missing dependency in cohttp-Lwt and cohttp-lwt-jsoo

**Comment by hcarty** [comment]
Is there any issue with merging this?  The revdep failures all look unrelated to this change.

**Comment by rgrinberg** [comment]
There are no issues from my end. I don't plan to investigate the owl related failures further.

**Comment by hcarty** [comment]
Thanks!

**Pull request merged**
