### PR TITLE
3 packages from gitlab.inria.fr/fpottier/menhir/repository/20210310/archive.tar.gz

### PR DESCRIPTION
**Pull request by fpottier**
This pull-request concerns:
-`menhir.20210310`: An LR(1) parser generator
-`menhirLib.20210310`: Runtime support library for parsers generated by Menhir
-`menhirSdk.20210310`: Compile-time library for auxiliary tools related to
 Menhir

---
* Homepage: http://gitlab.inria.fr/fpottier/menhir
* Source repo: git+https://gitlab.inria.fr/fpottier/menhir.git
* Bug tracker: menhir@inria.fr

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
```
#=== ERROR while compiling wikitext.3.0.0 =====================================#
# context              2.0.8 | linux/x86_64 | ocaml-base-compiler.4.11.2 | file:///src
# path                 ~/.opam/4.11/.opam-switch/build/wikitext.3.0.0
# command              ~/.opam/4.11/bin/dune build -p wikitext -j 47
# exit-code            1
# env-file             ~/.opam/log/wikitext-16-e7966f.env
# output-file          ~/.opam/log/wikitext-16-e7966f.out
### output ###
#       menhir src/wktxt_parser.{ml,mli} (exit 1)
# (cd _build/default && /home/opam/.opam/4.11/bin/menhir --explain src/wktxt_parser.mly --base src/wktxt_parser --infer-read-reply src/wktxt_parser__mock.mli.inferred)
# File "src/wktxt_parser.mly", line 29, characters 0-5:
# Error: the grammar is cyclic:
# the nonterminal symbol block expands to itself.
# A cyclic grammar is ambiguous.
```
This seems to be a new error. Is that expected?

**Comment by fpottier** [comment]
Hi Kate, interesting, thanks for reporting this. It is indeed a problem with their grammar: the new version of Menhir has been made a little stricter and now rejects certain grammars that are definitely bad. In this case, I believe that the fix is to replace line 30 in the grammar:
```
| EMPTYLINE* b = block { b }
```
with the following:
```
| EMPTYLINE b = block { b }
```

**Comment by kit-ty-kate** [comment]
Thanks a lot for looking into this. I've constrained `wikitext` as a result. cc @sagotch 
It is good to go now. Thanks again!

**Comment by sagotch** [comment]
Thank you both. And yes indeed, this is definitely bad, I'll fix this.

**Pull request merged**
