### PR TITLE
`ppx_deriving_yojson` Yojson 2.0 conflicts

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
This fixes the failures of #21523.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
@mseri Looks like `mparser.1.2` has broken checksums, can you replace the tarball by the archived one?

**Comment by mseri** [comment]
It is uploaded here: https://github.com/ocaml/opam-source-archives/raw/main/mparser-1.2.tar.gz
Can you update the URL, I cannot make the PR right now?

**Comment by mseri** [comment]
Do we really want to fix it further? Ping @kit-ty-kate for an extra opinion, imho it is a strict improvement and it is good to be merged, we can keep fixing thing incrementally separately

**Comment by Leonidas-from-XIV** [comment]
No, I think I'm good for now. The remaining minimum-version failures are a rather complicated field of ppx-rewriters like omp, ppxlib, ppx_tools_versioned and their transitive dependencies which is probably a substantial amount of work to get right and I think this PR already represents a decent improvement over the status quo.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
