### PR TITLE
Add Petrol 1.2.3

### PR DESCRIPTION
**Pull request by oemmerson**
This release has already been on Opam as the wrong src for 1.2.0 (see https://github.com/ocaml/opam-repository/pull/23908) so am adding it here under the correct version for anyone who has been using it thinking it was 1.2.0.

### CODE REVIEW

**Comment by haochenx** [comment]
CI fails on macOS. The reason seems to be stemming from 
https://github.com/ocaml/opam-repository/blob/f016dc51d87d9323b994ea1d40c09a70187d0b12/packages/conf-postgresql/conf-postgresql.1/opam#L27

Currently to install postgres using homebrew, you have to specify the major version. I.e. instead of `brew install postgresql`, `brew install postgresql@14` etc. must be used.

I'd like to suggest updating conf-postgresql but not sure about the following and some other maintainer needs to take a look.
1. whether it is the correct thing to do within this PR
2. if conf-postgresql is to be updated, whether a new version should be added or the existing version should be modified
3. whether this is a blocker to merge this PR (I guess not?)

### OPAM CI error excerpt (from [here](https://toxis.caelum.ci.dev/github/ocaml/opam-repository/commit/b80e57a42a74c3a40a462867c9b700676729c086/variant/macos,macos-homebrew-ocaml-4.14-amd64,petrol.1.2.3,tests))
```
<><> Handling external dependencies <><><><><><><><><><><><><><><><><><><><><><>
Let opam run your package manager to install the required system packages?
(answer 'n' for other options) [Y/n] y
+ /usr/local/bin/brew "install" "pkg-config" "postgresql" "sqlite"
- Warning: No available formula with the name "homebrew/core/postgresql".
- Please tap it and then try again: brew tap homebrew/core
[ERROR] System package install failed with exit code 1 at command:
            brew install pkg-config postgresql sqlite
```

**Comment by mseri** [comment]
Ping @Gopiandcode (so that you are aware)

**Comment by mseri** [comment]
@haochenx can you open an issue concerning conf-postgres? We will discuss it later on, this is becoming a problem with a number of homebrew packages. It should not block this package

**Comment by mseri** [comment]
CLosing in agreement to the discussion on the other PR

**Pull request closed without merging**
