### PR TITLE
Sync OCaml compiler PRs

### PR DESCRIPTION
**Pull request by bactrian**
The latest compiler pull requests for OCaml 4.03.0 as of Thu 05 Mar 2015 00:00:01 GMT

### CODE REVIEW

**Comment by yallop** [comment]
I wonder why it's deleting 4.03.0+pr100 when [pull request #100](https://github.com/ocaml/ocaml/pull/100) is still open.

**Comment by whitequark** [comment]
Merge conflicts.

**Comment by yallop** [comment]
It's not deleting other PRs that have merge conflicts (e.g [#103](https://github.com/ocaml/ocaml/pull/103), and many others).

**Comment by whitequark** [comment]
Oh. That's ... really weird.

**Comment by yallop** [comment]
I think it's only keeping the 30 most recent PRs.

**Comment by yallop** [comment]
Coincidentally, 30 is the [default pagination size](https://developer.github.com/v3/#pagination) for GitHub API requests.

**Comment by yallop** [comment]
See https://github.com/avsm/opam-sync-github-prs/issues/7

**Pull request merged**
