### PR TITLE
add tcpip 3.4.1

### PR DESCRIPTION
**Pull request by yomimono**

### CODE REVIEW

**Comment by jpdeplaix** [comment]
I'm trying to fix the deps in #11543.

**Comment by yomimono** [comment]
It seems that the revdeps tests can end up testing against a version of `tcpip` that isn't the one submitted.  From [this arm64 revdep failure](https://arm64.ci.ocamllabs.io/log/saved/docker-run-5a771b87eca172f4147be8ee67c8202e/a31bf174c801b6964c176a6896688c00e8b74ac1) (note tcpip 3.1.4, not 3.4.1):

```
-> compiled  tcpip.3.1.4
Processing 50/52: [tcpip: make install]
+ /usr/bin/make "install" (CWD=/home/opam/.opam/4.05.0/.opam-switch/build/tcpip.3.1.4)
- ocaml setup.ml -install 
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_checksum.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/libtcpip_stubs.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_checksum.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_checksum.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_checksum.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_checksum.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_checksum.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv6_socket.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv6-socket.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv6-socket.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv6-socket.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv6-socket.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv6_socket.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv6_socket.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv6_socket.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv6_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv4_socket.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv4-socket.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv4-socket.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv4-socket.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv4-socket.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv4_socket.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv4_socket.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv4_socket.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udpv4_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_wire.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_packet.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_packet.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_packet.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_packet.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_packet.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_wire.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_wire.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_wire.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_packet.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp_wire.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/udp.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv6_socket.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv6-socket.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv6-socket.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv6-socket.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv6-socket.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv6_socket.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv6_socket.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv6_socket.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv6_socket.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv6_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv4_socket.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv4-socket.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv4-socket.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv4-socket.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv4-socket.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv4_socket.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv4_socket.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv4_socket.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv4_socket.annot
- ocamlfind: [WARNING] Overwriting file /home/opam/.opam/4.05.0/lib/tcpip/tcp_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpv4_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/options.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/state.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcptimer.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/sequence.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ack.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/window.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/segment.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/user_buffer.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/pcb.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/flow.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/stats.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/wire.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp_wire.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp_packet.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp_packet.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp_packet.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp_packet.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp_wire.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp_wire.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/wire.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/wire.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/wire.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/stats.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/stats.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/stats.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/flow.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/flow.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/flow.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/pcb.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/pcb.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/pcb.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/user_buffer.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/user_buffer.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/user_buffer.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/segment.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/segment.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/segment.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/window.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/window.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/window.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ack.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ack.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ack.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/sequence.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/sequence.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/sequence.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcptimer.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcptimer.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcptimer.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/state.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/state.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/state.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/options.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/options.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/options.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcp.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_socket.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_socket.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6_socket.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip-stack-socket.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip-stack-socket.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip-stack-socket.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip-stack-socket.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6_socket.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6_socket.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6_socket.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_socket.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_socket.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_socket.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_socket.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_socket.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_socket.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_socket.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_direct.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip-stack-direct.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip-stack-direct.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip-stack-direct.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip-stack-direct.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_direct.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_direct.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_direct.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_direct.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/tcpip_stack_direct.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ndpv6.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6_wire.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6_wire.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6_wire.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6_wire.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ndpv6.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ndpv6.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ndpv6.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ndpv6.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6_wire.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ndpv6.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv6.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/static_ipv4.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_wire.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_packet.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_packet.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_packet.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_packet.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_packet.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_wire.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_wire.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_wire.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/static_ipv4.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/static_ipv4.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/static_ipv4.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/static_ipv4.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/routing.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_common.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_packet.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ipv4_wire.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/static_ipv4.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_socket.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4-socket.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4-socket.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4-socket.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4-socket.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_socket.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_socket.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_socket.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_socket.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_socket.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_packet.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_wire.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_wire.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_wire.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_wire.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_packet.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_packet.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_packet.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_packet.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_wire.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4_packet.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/icmpv4.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_wire.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_packet.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_packet.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_packet.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_packet.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_packet.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_wire.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_wire.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_wire.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_packet.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif_wire.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/ethif.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_wire.ml
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_packet.mli
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4.cma
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4.cmxa
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4.a
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4.cmxs
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_packet.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_packet.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_packet.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_packet.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_wire.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_wire.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_wire.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4.cmi
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4.cmti
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4.cmt
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4.annot
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_packet.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4_wire.cmx
- Installed /home/opam/.opam/4.05.0/lib/tcpip/arpv4.cmx
- Installed /home/opam/.opam/4.05.0/lib/stublibs/dlltcpip_stubs.so
- Installed /home/opam/.opam/4.05.0/lib/stublibs/dlltcpip_stubs.so.owner
- ocamlfind: [WARNING] You have installed DLLs but the directory /home/opam/.opam/4.05.0/lib/stublibs is not mentioned in ld.conf
- Installed /home/opam/.opam/4.05.0/lib/tcpip/META
-> installed tcpip.3.1.4
Processing 51/52: [charrua-core: ocaml build]
+ /home/opam/.opam/4.05.0/bin/ocaml "pkg/pkg.ml" "build" "--pinned" "false" "--tests" "false" (CWD=/home/opam/.opam/4.05.0/.opam-switch/build/charrua-core.0.6)
- ocamlfind ocamldep -package 'cstruct.ppx tcpip.ethif tcpip.udp' -package 'rresult cstruct ipaddr sexplib ppx_sexp_conv tcpip.ipv4' -modules lib/dhcp_wire.ml > lib/dhcp_wire.ml.depends
- + ocamlfind ocamldep -package 'cstruct.ppx tcpip.ethif tcpip.udp' -package 'rresult cstruct ipaddr sexplib ppx_sexp_conv tcpip.ipv4' -modules lib/dhcp_wire.ml > lib/dhcp_wire.ml.depends
- ocamlfind: Package `ppx_deriving' not found - required by `ppx_sexp_conv'
- Command exited with code 2.
- pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
-      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
-      'README.md' 'lib/dhcp_wire.a' 'lib/dhcp_wire.cmxs' 'lib/dhcp_wire.cmxa'
-      'lib/dhcp_wire.cma' 'lib/util.cmx' 'lib/dhcp_wire.cmx'
-      'lib/dhcp_wire.cmi' 'lib/dhcp_wire.mli' 'lib/dhcp_server.a'
-      'lib/dhcp_server.cmxs' 'lib/dhcp_server.cmxa' 'lib/dhcp_server.cma'
-      'lib/dhcp_lexer.cmx' 'lib/dhcp_parser.cmx' 'lib/dhcp_server.cmx'
-      'lib/dhcp_server.cmi' 'lib/dhcp_server.mli']: exited with 10
[ERROR] The compilation of charrua-core failed at "/home/opam/.opam/4.05.0/bin/ocaml pkg/pkg.ml build --pinned false --tests false".

#=== ERROR while compiling charrua-core.0.6 ===================================#
# context              2.0.0~rc | linux/arm64 | ocaml-base-compiler.4.05.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.05.0/.opam-switch/build/charrua-core.0.6
# command              ~/.opam/4.05.0/bin/ocaml pkg/pkg.ml build --pinned false --tests false
# exit-code            1
# env-file             ~/.opam/log/charrua-core-18-c2115b.env
# output-file          ~/.opam/log/charrua-core-18-c2115b.out
### output ###
# ocamlfind ocamldep -package 'cstruct.ppx tcpip.ethif tcpip.udp' -package 'rresult cstruct ipaddr sexplib ppx_sexp_conv tcpip.ipv4' -modules lib/dhcp_wire.ml > lib/dhcp_wire.ml.depends
# + ocamlfind ocamldep -package 'cstruct.ppx tcpip.ethif tcpip.udp' -package 'rresult cstruct ipaddr sexplib ppx_sexp_conv tcpip.ipv4' -modules lib/dhcp_wire.ml > lib/dhcp_wire.ml.depends
# ocamlfind: Package `ppx_deriving' not found - required by `ppx_sexp_conv'
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'lib/dhcp_wire.a' 'lib/dhcp_wire.cmxs' 'lib/dhcp_wire.cmxa'
#      'lib/dhcp_wire.cma' 'lib/util.cmx' 'lib/dhcp_wire.cmx'
#      'lib/dhcp_wire.cmi' 'lib/dhcp_wire.mli' 'lib/dhcp_server.a'
#      'lib/dhcp_server.cmxs' 'lib/dhcp_server.cmxa' 'lib/dhcp_server.cma'
#      'lib/dhcp_lexer.cmx' 'lib/dhcp_parser.cmx' 'lib/dhcp_server.cmx'
#      'lib/dhcp_server.cmi' 'lib/dhcp_server.mli']: exited with 10



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
+- The following actions failed
| - build charrua-core 0.6
+- 
+- The following changes have been performed
| - downgrade cstruct              3.1.1 to 2.4.1
| - downgrade mirage-profile       0.8.2 to 0.7.0
| - downgrade mirage-protocols     1.3.0 to 1.2.0
| - downgrade mirage-protocols-lwt 1.3.0 to 1.2.0
| - downgrade mirage-stack         1.2.0 to 1.1.0
| - downgrade mirage-stack-lwt     1.2.0 to 1.1.0
| - downgrade tcpip                3.4.1 to 3.1.4
| - recompile cstruct-lwt          3.2.1
| - recompile io-page              2.0.1
| - recompile io-page-unix         2.0.1
| - recompile mirage-net-lwt       1.1.0
| - recompile mirage-random        1.1.0
| - recompile ppx_cstruct          3.2.1
| - recompile randomconv           0.1.0
| - install   conf-time            1
| - install   conf-which           1
| - install   menhir               20171222
| - install   ppx_tools            5.0+4.05.0
+- 

The former state can be restored with:
    opam switch import "/home/opam/.opam/4.05.0/.opam-switch/backup/state-20180309130156.export"
'opam install --verbose --yes --jobs=2 charrua-core.0.6' failed.
# Run eval $(opam env) to update the current shell environment
[2018-03-09 13:08.27] Failed: Command "docker" "run" "--rm" "--memory-swap" "-1" "-v" "/home/opam/opam-repository/cache:/home/opam/opam-repository/cache" "sha256:3d907c6fd068729245ae4575c6005da4b4a84bf1fc8ae3031bfccdf15cd39c37" "opam" "config" "exec" "--" "opam-ci-install" "charrua-core.0.6" exited with status 31
```

**Comment by jpdeplaix** [comment]
Revdeps finally worked on the x86_64. Sorry for the delay.
I'm going to report the bug you mentioned to the opam issues-tracker right away. I managed to get some test-cases.

**Comment by jpdeplaix** [comment]
Reported here: https://github.com/ocaml/opam/issues/3250

**Pull request merged**
