### PR TITLE
Package for ocamlfind/findlib version 1.7.3

### PR DESCRIPTION
**Pull request by xavierleroy**
Package obtained by minimal modifications from ocamlfind.1.7.2.

### CODE REVIEW

**Comment by avsm** [comment]
the changelog suggests that the only significant change from 1.7.2 is a Num library change, so this should be fairly safe. cc @samoht

**Comment by xavierleroy** [comment]
CI looks pretty good.  The failure for "Common Distros" is due to Alpine not providing the "m4" command, which ocamlfind needs.

**Comment by avsm** [comment]
the lack of m4 is a bug in the CI scripts, which don't call depext when upgrading in some cases.  should be fixed eventually when https://github.com/ocaml/opam/issues/2919 lands in opam2 and we have more integrated depext handling, but can ignore it for now.

**Comment by avsm** [comment]
I've taken the opportunity to fix a few of the reds in the reverse dependencies, linked to this issue. None of them need to block the merge as there are no obvious regressions in the list.  Fingers crossed, in goes the new ocamlfind!

**Pull request merged**
