### PR TITLE
[new release] qinap (1.0)

### PR DESCRIPTION
**Pull request by guillecosta**
A (very small) monadic parsing library

- Project page: <a href="https://github.com/guillecosta/qinap">https://github.com/guillecosta/qinap</a>

##### CHANGES:

First public release

### CODE REVIEW

**Comment by mseri** [comment]
You require dune 2.6 or newer, also dune cannot be tagged as build dependency fir forward compatibility reasons. I made the change in this PR, can you please upstream it?

**Comment by guillecosta** [comment]
@mseri Thanks for the fixes! Sorry for the stupid question, but what do you mean by upstreaming? Making the same changes at the project repo?

**Comment by mseri** [comment]
Yes, sorry, that’s exactly what I mean. Please make the same changes on the main repository

**Comment by mseri** [comment]
Feel free to announce the release on the discuss.ocaml.org forum. We have a community category and an announcement tag for this purpose

**Pull request merged**
