### PR TITLE
Fix wrong uunf depopt constraint.

### PR DESCRIPTION
**Pull request by dbuenzli**
Discovered while testing 4.05.0+rc1 (#9650).

### CODE REVIEW

**Comment by dbuenzli** [comment]
As usual flambda 4.04.0 failure due to https://caml.inria.fr/mantis/view.php?id=7501 which was fixed in 4.04.1. Once travis is fine I guess this can be merged.

**Comment by dbuenzli** [comment]
So travis failed on 4.05 but it doesn't seem to be my fault.

**Comment by dbuenzli** [comment]
Ping.

**Comment by samoht** [comment]
Pong.

**Pull request merged**
