### PR TITLE
+ mldonkey 3.1.6

### PR DESCRIPTION
**Pull request by ygrek**

### CODE REVIEW

**Comment by ygrek** [comment]
ftr build failed because of : 

> ERROR] The sources of the following couldn't be obtained, aborting:
>
>          - depext.1.0.2

**Comment by yallop** [comment]
I've restarted the job.

**Comment by yallop** [comment]
The alpine build is failing:
```
# checking for inflate in -lz... no
# Zlib missing, did you install zlib and zlib-developer packages?
```

An extra `depext` entry should fix it:
```
  [["alpine"] ["zlib-dev"]]
```
or you could replace the whole `depext` section with a dependency on [`conf-zlib`](https://github.com/ocaml/opam-repository/blob/master/packages/conf-zlib/conf-zlib.1/opam).

**Comment by avsm** [comment]
replacing the dependencies with `conf-zlib` would be preferable.

**Comment by ygrek** [comment]
Fixed, thanks.

Now:
> - Fatal error: exception Sys_error("No space left on device")

**Comment by ygrek** [comment]
it failed to download github url which is working fine (also it is not clear if it actually tried to download from mirror)..

**Pull request merged**
