### PR TITLE
added packages/conf-python-3-6

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
there is no `python3.6` package in debian. Do you specifically need 3.6 or just 3?

**Comment by UnixJunkie** [comment]
Ok, I pushed some more changes.
However, note that some operating systems/packagers don't have a python3 package.
In which case I ask for python3.6.
Maybe this conf package could be renamed to conf-python-3, since it does not enforce python3.6 in all environments.

**Comment by UnixJunkie** [comment]
I just fixed the python script also.

**Comment by kit-ty-kate** [comment]
> Maybe this conf package could be renamed to conf-python-3, since it does not enforce python3.6 in all environments.

I think it would be best

**Comment by UnixJunkie** [comment]
I renamed it.

**Comment by UnixJunkie** [comment]
Still not OK?

**Comment by kit-ty-kate** [comment]
The name of the package doesn't match the directory it is in:
`conf-python-3-1.0.0` vs. `conf-python-3.1.0.0`. The minor and micro versions might be a bit overkill for conf packages too but it's not big deal.

**Comment by UnixJunkie** [comment]
I renamed the directory.

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by UnixJunkie** [comment]
Thanks for the fixes!

**Pull request merged**
