### PR TITLE
openflow.0.9.0 and frenetic.3.3.0

### PR DESCRIPTION
**Pull request by arjunguha**

### CODE REVIEW

**Comment by dsheets** [comment]
Frenetic is trying to install executables into `/usr/local/bin`. Please use opam's binary installation mechanism for binary installation either via a command-line argument to your build system or a `frenetic.install` file.

**Comment by arjunguha** [comment]
Stupid mistake by me. Thanks.

**Comment by arjunguha** [comment]
One of the jobs in the matrix failed earlier. Could you try to restart it?

**Comment by arjunguha** [comment]
Thanks!

**Pull request merged**
