### PR TITLE
crunch.1.0.0: conflicts with system compiler and safe-string

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I'm curious why it's not compatible with the system compiler

**Comment by kit-ty-kate** [comment]
This package seems really broken anyway:
```
#=== ERROR while installing crunch.1.0.0 ======================================#
# context              2.0.3 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/mirage/ocaml-crunch/tarball/ocaml-crunch-1.0.0)
# path                 ~/.opam/4.03/.opam-switch/build/crunch.1.0.0
# command              /usr/bin/make PREFIX=/home/opam/.opam/4.03 install
# exit-code            2
# env-file             ~/.opam/log/crunch-20-0ac68e.env
# output-file          ~/.opam/log/crunch-20-0ac68e.out
### output ###
# ./setup.bin -reinstall
# Installed /home/opam/.opam/4.03/lib/crunch/crunch.ml
# Installed /home/opam/.opam/4.03/lib/crunch/crunch.cma
# Installed /home/opam/.opam/4.03/lib/crunch/crunch.cmxa
# Installed /home/opam/.opam/4.03/lib/crunch/crunch.a
# Installed /home/opam/.opam/4.03/lib/crunch/crunch.cmxs
# Installed /home/opam/.opam/4.03/lib/crunch/crunch.cmi
# Installed /home/opam/.opam/4.03/lib/crunch/crunch.cmx
# Installed /home/opam/.opam/4.03/lib/crunch/META
# cp: cannot create regular file '/usr/local/bin/crunch': Permission denied
# E: Failure("Command ''cp' '/home/opam/.opam/4.03/.opam-switch/build/crunch.1.0.0/_build/crunch/crunch.native' '/usr/local/bin/crunch'' terminated with error code 1")
# Makefile:21: recipe for target 'install' failed
# make: *** [install] Error 1
```
I'm not sure what to do for this one

**Comment by mseri** [comment]
ping @avsm

**Comment by avsm** [comment]
ive deleted the package, as it does seem pretty broken with opam2

**Pull request merged**
