### PR TITLE
2 packages from c-cube/calculon at 0.4

### PR DESCRIPTION
**Pull request by c-cube**
This pull-request concerns:
-`calculon.0.4`: Library for writing IRC bots in OCaml and a collection of plugins
-`calculon-web.0.4`: A collection of web plugins for Calculon

---
* Homepage: https://github.com/c-cube/calculon
* Source repo: git+https://github.com/c-cube/calculon.git
* Bug tracker: https://github.com/c-cube/calculon/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by c-cube** [comment]
hu, it tries to install calculon-web.0.2 for some reason, which fails :/

**Comment by mseri** [comment]
It's the revdeps, I think calculon-web < 0.4 requires an upper bound on calcuon

**Comment by kit-ty-kate** [comment]
`calculon-web.0.2` fails anyway: http://check.ocamllabs.io/4.03.0/bad/calculon-web.0.2

@c-cube could you fix it and add the necessary upper-bound if needed?

**Comment by c-cube** [comment]
it's another failure in 0.2. Also, ci.ocamllabs.io 's certificate is expired.

**Comment by mseri** [comment]
irc-client-lwt does not seem to use the `.lwt` any longer, I added an upper bound for irc-client to it. Let's see if that is enough

**Comment by mseri** [comment]
Yep, that did the trick

**Pull request merged**
