### PR TITLE
Initial release of Jane Street ppx rewriters

### PR DESCRIPTION
**Pull request by diml**

### CODE REVIEW

**Comment by whitequark** [comment]
```
===== ERROR while installing ppx_type_conv.113.09.00 =====
# opam-version 1.1.2-rc3
# os           linux
# command      make
# path         /home/travis/.opam/4.02.3/build/ppx_type_conv.113.09.00
# compiler     4.02.3
# exit-code    2
# env-file     /home/travis/.opam/4.02.3/build/ppx_type_conv.113.09.00/ppx_type_conv-16251-e4db2f.env
# stdout-file  /home/travis/.opam/4.02.3/build/ppx_type_conv.113.09.00/ppx_type_conv-16251-e4db2f.out
# stderr-file  /home/travis/.opam/4.02.3/build/ppx_type_conv.113.09.00/ppx_type_conv-16251-e4db2f.err
### stdout ###
# ...[truncated]
# /home/travis/.opam/4.02.3/bin/ocamlfind ocamlopt -shared -linkall src/ppx_type_conv.cmxa -o src/ppx_type_conv.cmxs
# /home/travis/.opam/4.02.3/bin/ocamlfind ocamldep -package ppx_tools.metaquot -package ppx_driver -package ppx_deriving.api -package ppx_core -package compiler-libs -modules ppx_deriving_exporter/ppx_type_conv_deriving.ml > ppx_deriving_exporter/ppx_type_conv_deriving.ml.depends
# /home/travis/.opam/4.02.3/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package ppx_tools.metaquot -package ppx_driver -package ppx_deriving.api -package ppx_core -package compiler-libs -w -40 -I ppx_deriving_exporter -I src -o ppx_deriving_exporter/ppx_type_conv_deriving.cmo ppx_deriving_exporter/ppx_type_conv_deriving.ml
# + /home/travis/.opam/4.02.3/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package ppx_tools.metaquot -package ppx_driver -package ppx_deriving.api -package ppx_core -package compiler-libs -w -40 -I ppx_deriving_exporter -I src -o ppx_deriving_exporter/ppx_type_conv_deriving.cmo ppx_deriving_exporter/ppx_type_conv_deriving.ml
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/travis/.opam/4.02.3/lib/ocaml, /home/travis/.opam/4.02.3/lib/ocaml/compiler-libs
# File "ppx_deriving_exporter/ppx_type_conv_deriving.ml", line 1, characters 62-74:
# Error: Signature mismatch:
#        ...
#        The value `create' is required but not provided
# Command exited with code 2.
### stderr ###
# W: Cannot find source file matching module 'ppx_type_conv' in library ppx_type_conv
# E: Failure("Command ''/home/travis/.opam/4.02.3/bin/ocamlbuild' src/ppx_type_conv.cma src/ppx_type_conv.cmxa src/ppx_type_conv.a src/ppx_type_conv.cmxs ppx_deriving_exporter/ppx_type_conv_deriving.cma ppx_deriving_exporter/ppx_type_conv_deriving.cmxa ppx_deriving_exporter/ppx_type_conv_deriving.a ppx_deriving_exporter/ppx_type_conv_deriving.cmxs -use-ocamlfind -tag debug' terminated with error cod...[truncated]
# make: *** [build] Error 1
```

**Comment by whitequark** [comment]
Oh; this only happened because new ppx_deriving requires opam >=1.2.

The build on 4.02/1.2.0 timed out, but I'm assuming it went OK.

**Comment by avsm** [comment]
And we've passed 1000 packages :-)

**Comment by Chris00** [comment]
:+1:

**Pull request merged**
