### PR TITLE
[new release] mirage-flow, mirage-flow-unix and mirage-flow-combinators (4.0.0)

### PR DESCRIPTION
**Pull request by hannesm**
Flow implementations and combinators for MirageOS

- Project page: <a href="https://github.com/mirage/mirage-flow">https://github.com/mirage/mirage-flow</a>
- Documentation: <a href="https://mirage.github.io/mirage-flow/">https://mirage.github.io/mirage-flow/</a>

##### CHANGES:

- Redefine `close` semantics, which no longer is a `` shutdown `read_write ``
  (mirage/mirage-flow#49 @hannesm)
- Add ``shutdown : flow -> [ `read | `write | `read_write ] -> unit Lwt.t``
  (@djs55 @hannesm mirage/mirage-flow#16 mirage/mirage-flow#18 mirage/mirage-flow#48)
- Remove SHUTDOWNABLE signature (@djs55 mirage/mirage-flow#17, rebased into mirage/mirage-flow#48)

### CODE REVIEW

**Comment by hannesm** [comment]
this is a re-iteration of #24951 and since #24952 is merged, the revdeps failures should be minimal. I'll go through them once CI has advanced.

**Comment by hannesm** [comment]
see #24960 for fixing more revdeps

**Comment by hannesm** [comment]
re-iterating here from #24960 #24952:
- hvsock //cc @djs55
- protocol-9p-unix //cc @djs55
- spoke //cc @dinosaure
- mimic //cc @dinosaure
- tcpip (here, the with-test was clearly wrong) //cc @avsm
- tls-mirage //cc @hannesm
- awa-mirage //cc @hannesm @haesbaert
- vchan //cc @jonludlam
- mirage-console //cc @avsm

Please keep in mind, that (a) there's now shutdown and (b) close semantics changed (see https://github.com/ocaml/opam-repository/pull/24959 for the release and the details at https://mirage.github.io/mirage-flow/mirage-flow/Mirage_flow/module-type-S/index.html

(if you wonder why you appear in the list above -> take a look into the "maintainers" metadata of your opam package)

**Comment by hannesm** [comment]
remaining CI error (timeout of solver, ...) are unrelated. This is fine to merge from my point of view.

**Comment by mseri** [comment]
Thanks

**Pull request merged**
