### PR TITLE
+ sqlgg 20200521

### PR DESCRIPTION
**Pull request by ygrek**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Your `dune-project` file, says this package requires at least dune 2.0. Could you return the fix in the opam file upstream?

**Comment by kit-ty-kate** [comment]
Also, the directory layout is not the one used by opam-repository and our CI does not realize this is a new package. Could you move the `sqlgg.20200521` directory to the `sqlgg` directory?

**Comment by ygrek** [comment]
Done. Thanks for spotting, not sure how it happened :/

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
