### PR TITLE
Update OPAM of archimedes 0.4.17

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by dsheets** [comment]
It does not uninstall cleanly:

```
[WARNING] Directory /home/travis/.opam/system/share/archimedes is not empty,

          not removing
```

**Comment by Chris00** [comment]
@dsheets Strange.  Isn't the `.install` file (left unchanged) supposed to take care of that?

**Comment by dsheets** [comment]
Is this library using a `.install` file? I can't find it.

The leftover file is `share/archimedes/archimedes_graphics.dep`.

**Comment by Chris00** [comment]
The install file was on my disk but never commited, hence my confusion.

**Comment by dsheets** [comment]
Ok. Could you make sure the `.install` is upstreamed for the next release?

**Comment by Chris00** [comment]
@dsheets I am going to update `oasis2opam` to also suggest to put the `.install` file in the tarball.

**Pull request merged**
