### PR TITLE
Add coq 8.5.3

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by yallop** [comment]
It [appears](https://travis-ci.org/ocaml/opam-repository/jobs/172641790) that the `uninstall` step is leaving some files behind:

```
[WARNING] Directory /home/travis/.opam/4.03.0/share/coq is not empty, not
          removing
```

**Comment by maximedenes** [comment]
The remaining files are:
``
share/coq/coq.lang
share/coq/coq.png
share/coq/coq-ssreflect.lang
share/coq/coq_style.xml
``

They are all mentioned in the coq-coqide.install file. Why are they not removed by OPAM?

**Comment by dbuenzli** [comment]
> They are all mentioned in the coq-coqide.install file. Why are they not removed by OPAM?

It is actually odd the file is used at all. The basename of this file should be the same as the name of the package (i.e. `coqide.install`).

**Comment by maximedenes** [comment]
Oh, I see. No idea why it was done like that, I copied previous versions of the package. I'll check if it fixes the problem and update the PR, thanks!

**Comment by maximedenes** [comment]
OK, this time everything went fine, apart from the timeout which is too low. Can this get merged?

**Pull request merged**
