### PR TITLE
added packages/conf-r/conf-r.1.0.0

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
@pveber you might be interested

I'll probably release soon some other packages that will rely on this one.

**Comment by UnixJunkie** [comment]
@lehy maybe you are interested too

**Comment by UnixJunkie** [comment]
CI tests look goo to me

**Comment by pveber** [comment]
BTW, how about checking that R mathlib is also installed? It would be useful for ocaml-r (I'm finally not too far from a proper release)

**Comment by UnixJunkie** [comment]
@pveber you should create another conf-package.
This one is just about checking and being able to install the R interpreter.

**Comment by hannesm** [comment]
thanks for your contribution, merging.

please look into the CentOS7 failure (https://ci.ocamllabs.io/log/saved/docker-build-bf304f83560debca97c845228728ff0e/848da6f574c372d3302e6ad4456784141dcde47a)
```
The following command needs to be run through "sudo":
    yum install -y R
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.sov.uk.goscomb.net
 * extras: www.mirrorservice.org
 * updates: anorien.csc.warwick.ac.uk
No package R available.
```

**Comment by UnixJunkie** [comment]
Maybe they need the EPEL repository to be enabled.
I will look how this is done in other packages.

**Comment by UnixJunkie** [comment]
I sent a correction there: https://github.com/ocaml/opam-repository/pull/11478

**Pull request merged**
