### PR TITLE
camlidl.1.06 & mlgmpidl.1.2.5

### PR DESCRIPTION
**Pull request by nberth**

### CODE REVIEW

**Comment by gasche** [comment]
Do I understand correctly that you are the new upstream for camlidl? Also, if you are the new upstream, why do you need to add so many patches on top of existing releases, instead of making a new release that includes them?

**Comment by nberth** [comment]
@gasche Indeed I maintain and develop a few packages that rely on camlidl. I got some reports about new issues with OCaml 4.06 that require a new release of camlidl. Release 1.06 was originally designed as a patch-only release using the archive of 1.05, but then I decided to construct a new repository for it.
I'll integrate the patches and fix release 1.06 as soon as possible next week.

**Comment by gasche** [comment]
Thanks! I think it is a very good initiative, and it is good to do a new release.

**Comment by gasche** [comment]
(I don't know if you have already, but you should send an email to the previous maintainer to tell them about your new repo and your patches.)

**Pull request closed without merging**
