### PR TITLE
Add eigen.0.0.1

### PR DESCRIPTION
**Pull request by ryanrhymes**
Eigen is a thin OCaml interface to the well-known Eigen3 C++ template library. [Owl](https://github.com/ryanrhymes/owl) uses Eigen3 library to support efficient sparse matrix operations. To simplify the compilation of Owl, I split Owl and its interface to Eigen3 and make it into a separate library.

Original [Eigen3](http://eigen.tuxfamily.org/) is developed in C++, so the submitted library needs `g++` to compile the interfaced function into a separate library before compiling OCaml code. The details can be found [here](https://github.com/ryanrhymes/eigen).

### CODE REVIEW

**Comment by ryanrhymes** [comment]
The failed checks seem due to Eigen's OCaml version constraint, i.e.,`OCamlVersion: >= 4.04`

**Comment by yallop** [comment]
A version constraint in the `opam` file should fix that:

```
available: [ ocaml-version >= "4.04" ]
```

**Comment by ryanrhymes** [comment]
please can you have a look at this? it has passed the travis test.

**Comment by avsm** [comment]
fails a static link on alpine linux (with musllibc), not a blocker to merge

```
# ocamlfind ocamlopt unix.cmxa -I /home/opam/.opam/4.03.0/lib/ocamlbuild /home/opam/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /home/opam/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /home/opam/.opam/4.03.0/bin/ocamlfind ocamlc -g -ccopt -I/home/opam/.opam/4.03.0/lib/ctypes -package ctypes.stubs -package ctypes -c lib/ffi_eigen_generated_stub.c
# mv ffi_eigen_generated_stub.o lib/ffi_eigen_generated_stub.o
# /home/opam/.opam/4.03.0/bin/ocamlfind ocamlmklib -o lib/eigen_stubs -L/home/opam/.opam/4.03.0/lib -leigen -lstdc++ lib/ffi_eigen_generated_stub.o
# + /home/opam/.opam/4.03.0/bin/ocamlfind ocamlmklib -o lib/eigen_stubs -L/home/opam/.opam/4.03.0/lib -leigen -lstdc++ lib/ffi_eigen_generated_stub.o
# /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -leigen
# collect2: error: ld returned 1 exit status
```

**Pull request merged**
