### PR TITLE
first release of `future`

### PR DESCRIPTION
**Pull request by agarwal**

### CODE REVIEW

**Comment by agarwal** [comment]
The error seems related to #5617.

**Comment by agarwal** [comment]
The travis tests have now passed, so can this be merged?

Is there an explanation somewhere about camelus? What is it? That check still shows an error, but there is no link.

**Comment by samoht** [comment]
I'm not sure which version of the compiler and which OS `camelus` is using. /cc @AltGr 
Might be that the package is not installable on that particular configuration.

**Comment by OCamlPro-Henry** [comment]
@AltGr will give better details about Camelus, but it do not really try to install the package. It only try to call the solver. For that particular case, my guess is: `future` depends on `solvuu_build` which was not yet merged when camelus ran the test.

**Comment by dsheets** [comment]
That is what happened. I restarted the CI builds after `solvuu_build` was merged and camelus doesn't see that so it doesn't re-run the solver.

**Comment by agarwal** [comment]
Great, thanks for the merge.

**Comment by AltGr** [comment]
@camelus lives at https://github.com/AltGr/opam-bot
It doesn't suppose any OS or OCaml version -- it just assumes any is correct.
In this case, the package was indeed not installable due to a missing dependency. 

@camelus checks the patches strictly in the PR, not regarding the current state of master (this is different from travis); so in this case, rebasing the PR after having merged the dependency would have made the error go away.

**Comment by AltGr** [comment]
(note: travis assumes a non-installable package is OK, since it works for a given OS/ocaml-version configuration)

**Comment by agarwal** [comment]
@AltGr Thanks for linking to the opam-bot repo.

**Pull request merged**
