### PR TITLE
3 packages from framagit.org/zoggy/xtmpl/-/archive/0.19.0/xtmpl-0.19.0.tar.gz

### PR DESCRIPTION
**Pull request by zoggy**
This pull-request concerns:
-`xtmpl.0.19.0`: Xml templating library
-`xtmpl_js.0.19.0`: Xml templating library, javascript library
-`xtmpl_ppx.0.19.0`: Xml templating library, ppx extension

---
* Homepage: https://www.good-eris.net/xtmpl/
* Source repo: git+https://framagit.org/zoggy/xtmpl.git
* Bug tracker: https://framagit.org/zoggy/xtmpl/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mseri** [comment]
Looks like we need to add an upper bound to
```
    higlo.0.5 (failed: Unbound module Xtmpl_xml)
    higlo.0.6 (failed: Unbound module Xtmpl_xml)
    ojs-base.0.6.0 (failed: Error: The compilation of ojs-base failed at "/home/opam/.opam/opam-init/hooks/sandbox.sh build make all".) <- fails with xtmpl.ppx not found
    stog-writing.0.16.0 (failed: Unbound module Xtmpl_xml)
    stog-writing.0.17.0 (failed: Unbound module Xtmpl_xml)
    stog.0.16.0 (failed: Unbound module Xtmpl_xml)
    stog.0.17.0 (failed: Unbound module Xtmpl_xml)
    stog.0.17.1 (failed: Unbound module Xtmpl_xml)
    stog.0.18.0 (failed: Unbound module Xtmpl_xml)
    stog.0.18.0-1 (failed: Unbound module Xtmpl_xml)
```

**Comment by mseri** [comment]
I was planning to send a PR later for that, thanks a lot!

**Comment by mseri** [comment]
I am sending a separate PR for the two remaining issues

**Comment by zoggy** [comment]
Thanks. Regarding stog-writing, it should be ok now, since it depends on stog which depends on the correct version ok xtmpl now.

**Pull request merged**
