### PR TITLE
Why3 1.2.1

### PR DESCRIPTION
**Pull request by silene**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The failure on Fedora is unrelated (coq needs `find` to compile but is not installed on fedora by default). This might need to be fixed on our side

**Comment by silene** [comment]
The `opam` package for Coq 8.9.1 does not depend on `conf-findutils`, unfortunately. (The one for Coq 8.10.1 properly does.)

**Comment by kit-ty-kate** [comment]
Yes it should be fixed in https://github.com/ocaml/opam-repository/pull/15123

**Comment by silene** [comment]
The Travis Xcode failure is due to a timeout. And the only other failure is the one about Coq 8.9.1 not building on Fedora.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
