### PR TITLE
zed 1.5, lambda-term 1.11, utop 1.20

### PR DESCRIPTION
**Pull request by diml**

### CODE REVIEW

**Comment by avsm** [comment]
Travis failed with a jbuilder race; restarted. Is this a known jbuilder issue @diml ?

```
#=== ERROR while installing jbuilder.1.0+beta6 ================================#
# opam-version 1.2.2
# os           linux
# command      ./boot.exe -j 4
# path         /home/travis/.opam/system/build/jbuilder.1.0+beta6
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/jbuilder.1.0+beta6/jbuilder-21258-f33fa5.env
# stdout-file  /home/travis/.opam/system/build/jbuilder.1.0+beta6/jbuilder-21258-f33fa5.out
# stderr-file  /home/travis/.opam/system/build/jbuilder.1.0+beta6/jbuilder-21258-f33fa5.err
### stderr ###
# [...]
# Running[42]: (cd _build/default && /usr/bin/ocamlopt.opt -w -3-6-27-32-33-35-50 -g -no-alias-deps -I vendor/cmdliner/src -open Jbuilder_cmdliner -o vendor/cmdliner/src/jbuilder_cmdliner__Cmdliner_base.cmx -c -impl vendor/cmdliner/src/cmdliner_base.ml)
# Running[43]: (cd _build/default && /usr/bin/ocamlc.opt -w -3-6-27-32-33-35-50 -g -bin-annot -no-alias-deps -I vendor/cmdliner/src -open Jbuilder_cmdliner -o vendor/cmdliner/src/jbuilder_cmdliner__Cmdliner_term.cmi -c -intf vendor/cmdliner/src/cmdliner_term.mli)
# 
# Command [41] exited with code 2:
# $ (cd _build/default && /usr/bin/ocamlopt.opt -w -40 -w -49 -g -intf-suffix .ml-gen -no-alias-deps -I src -o src/jbuilder.cmx -c -impl src/jbuilder.ml-gen)
# File "src/jbuilder.ml-gen", line 1:
# Error: Corrupted compiled interface
# src/jbuilder__Log.cmi
```

**Comment by diml** [comment]
Yh, it's fixed in the development version. I'll do another release soon

**Comment by avsm** [comment]
revdeps; nebula fails to compile:
https://ci.ocaml.io/log/saved/docker-run-6dcd953f306976e98f294a85a88c9e7c/6ad9db4c3b09b0591997ebebcc94a8b8c7a43773
(might be unrelated to your PR)

and reason now fails as well https://ci.ocaml.io/log/saved/docker-run-0aff4309a8cbfbcbbf80a2c7d7d7a83d/04c5e6a392ccee81025d9b1d65963dcd3e85667d

```
- findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml/compiler-libs, /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml
- ocamlfind: Error from package `threads': Missing -thread or -vmthread switch
- Command exited with code 2.
- build.native: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-cflags' '-I,+ocamldoc' '-I'
-      'vendor/cmdliner' 'opam' 'pkg/META' 'pkg/META' 'src/reason.a'
-      'src/reason.cmxs' 'src/reason.cmxa' 'src/reason.cma'
-      'src/redoc_html.cmxs' 'src/redoc_html.cmi' 'src/redoc_html.cmx'
-      'src/redoc_html.cmo' 'vendor/cmdliner/cmdliner.cmi'
-      'vendor/cmdliner/cmdliner.cmx' 'vendor/cmdliner/cmdliner.cmo'
-      'src/reason_toploop.cmo' 'src/reason_utop.cmo' 'src/refmt_impl.native'
-      'src/ocamlmerlin_reason.native' 'src/refmt_merlin_impl.sh' 'src/rtop.sh'
-      'src/redoc.sh' 'src/reup.sh' 'src/rtop_init.ml'
-      '_reasonbuild/_build/myocamlbuild' 'src/reason_format_type.native'
-      'src/reactjs_jsx_ppx.native' 'src/ppx_react.native'
-      'editorSupport/emacs/refmt.el' 'editorSupport/emacs/reason-mode.el'
-      'editorSupport/VimReason/after/syntax/reason.vim'
-      'editorSupport/VimReason/autoload/reason.vim'
-      'editorSupport/VimReason/autoload/refmt.vim'
-      'editorSupport/VimReason/doc/reason.txt'
-      'editorSupport/VimReason/ftdetect/reason.vim'
-      'editorSupport/VimReason/ftplugin/reason.vim'
-      'editorSupport/VimReason/indent/reason.vim'
-      'editorSupport/VimReason/LICENSE'
-      'editorSupport/VimReason/plugin/reason.vim'
-      'editorSupport/VimReason/README.md'
-      'editorSupport/VimReason/syntax/reason.vim'
-      'editorSupport/VimReason/syntax_checkers/reason/reasonc.vim']: exited with 10
```

**Comment by diml** [comment]
Ah, it's the findlib_top thing. I did this as a quick hack for toplevel_expect_test but it's not good enough. There should be a cleaner way to do this, I'll submit a PR to findlib

**Comment by diml** [comment]
I submitted a PR to findlib: https://gitlab.camlcity.org/gerd/lib-findlib/merge_requests/5.

I also found a bug in the build of utop. I'm closing this PR for now, I'll open a new one once a new version of findlib has been released.

**Pull request closed without merging**
