### PR TITLE
Package typeid.0.1

### PR DESCRIPTION
**Pull request by titouancreach**
### `typeid.0.1`
Typeid and UUIDv7 implementation in OCaml
TypeId and UUIDv7 implementation in OCaml

---
* Homepage: https://github.com/titouancreach/typeid-ocaml
* Source repo: git+https://github.com/titouancreach/typeid-ocaml.git
* Bug tracker: https://github.com/titouancreach/typeid-ocaml/issues

---
:camel: Pull-request generated by opam-publish v2.3.0

### CODE REVIEW

**Comment by titouancreach** [comment]
I followed the doc here: https://opam.ocaml.org/doc/Packaging.html#Creating-a-package-definition-file

**Comment by mseri** [comment]
The lint error comes because you have all the dune sources inside the `typeid` folder, including the `dune-project` file. Usually all those files would be in the root of the repository, alongside the readme

**Comment by titouancreach** [comment]
Thanks very much @mseri

**Comment by titouancreach** [comment]
I close in favor of https://github.com/ocaml/opam-repository/pull/25419

**Pull request closed without merging**
