### PR TITLE
ocaml-src: restrict 4.03 to =4.03, add 4.04.1 and 4.04.2 (with tight bounds)

### PR DESCRIPTION
**Pull request by hannesm**
IIUC: `ocaml-src.X` should be the source of the ocaml compiler of the current switch.  add a 4.04.1 and 4.04.2 to the mix, and have tight bounds for 4.04.0 and 4.03.0.

### CODE REVIEW

**Comment by avsm** [comment]
thanks!

**Comment by avsm** [comment]
woops, revdeps for this were only tested on 4.03, so this broke mirage-xen-ocaml

```
# Detected OCaml version 4.04.2
# Applying OCaml 4.04 config
# patching file ocaml-src/asmrun/clambda_checks.c
# Hunk #1 FAILED at 59.
# Hunk #2 FAILED at 77.
# 2 out of 2 hunks FAILED -- saving rejects to file ocaml-src/asmrun/clambda_checks.c.rej
# Makefile:4: recipe for target 'build' failed
# make[1]: Leaving directory '/home/opam/.opam/4.04.2/build/mirage-xen-ocaml.3.0.0/xen-ocaml'
# Makefile:45: recipe for target 'xen-ocaml-build' failed
### stderr ###
```

fixing now

**Comment by hannesm** [comment]
ups - sorry, I tested only with ocaml-freestanding... wasn't aware that mirage-xen-ocaml had custom patches..

**Comment by avsm** [comment]
no worries -- am preparing a PR with the fix now; meanwhile compilation failure fixed in https://github.com/ocaml/opam-repository/pull/9809

**Pull request merged**
