### PR TITLE
[new release] ppxlib (0.3.1)

### PR DESCRIPTION
**Pull request by diml**
A comprehensive toolbox for ppx development. It features:

- Project page: <a href="https://github.com/ocaml-ppx/ppxlib">https://github.com/ocaml-ppx/ppxlib</a>
- Documentation: <a href="https://ocaml-ppx.github.io/ppxlib/">https://ocaml-ppx.github.io/ppxlib/</a>

##### CHANGES:

- Add `Attribute.declare_with_name_loc` (ocaml-ppx/ppxlib#33, @diml)

- Let the tool name pass throught when used as a -ppx (ocaml-ppx/ppxlib#41, @diml)

- Update the AST to 4.06 (ocaml-ppx/ppxlib#8, @xclerc)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There is a weird error with local OCaml compiler:
```
#===ERRORwhile installing ppxlib.0.3.1======================================#
#opam-version 1.2.2
#os           linux
#command      jbuilder runtest -p ppxlib -j 4
#path         /home/travis/.opam/system/build/ppxlib.0.3.1
#compiler     system (4.07.0)
#exit-code    1
#env-file     /home/travis/.opam/system/build/ppxlib.0.3.1/ppxlib-18402-c61e7b.env
#stdout-file  /home/travis/.opam/system/build/ppxlib.0.3.1/ppxlib-18402-c61e7b.out
#stderr-file  /home/travis/.opam/system/build/ppxlib.0.3.1/ppxlib-18402-c61e7b.err
### stderr ###
#[...]
#+Line _, characters 8-27:
#+Error: Unbound module Caml
# |}]
#
# let _ = Caml.Printf.sprintf "%s\n" [%plop.Truc.Bidule]
# [%%expect{|
#-- : string = "Truc.Bidule\n"
#+Line _, characters 8-27:
#+Error: Unbound module Caml
# |}]
```

**Comment by diml** [comment]
That's odd indeed. We'll look into it. /cc @xclerc

**Comment by diml** [comment]
dune

**Comment by mseri** [comment]
The CI used to be ok if I remember correctly. Should we wait to the revdeps to come back or we can merge?

**Comment by diml** [comment]
I'd say yes :)

**Pull request merged**
