### PR TITLE
13 packages from oxidizing/sihl at 0.0.32

### PR DESCRIPTION
**Pull request by jerben**
This pull-request concerns:
-`sihl.0.0.32`: A web framework for Reason and OCaml
-`sihl_admin.0.0.32`: A Sihl app to build backoffice web applications for administrators
-`sihl_email.0.0.32`: A Sihl app for email management
-`sihl_email_mariadb.0.0.32`: A storage for emails, templates and email queues using MariaDB
-`sihl_email_postgresql.0.0.32`: A storage for emails, templates and email queues using PostgreSQL
-`sihl_mariadb.0.0.32`: Provides support for migrations using MariaDB
-`sihl_postgresql.0.0.32`: Provides support for migrations using PostgreSQL
-`sihl_session.0.0.32`: A Sihl app for anonymous sessions
-`sihl_session_mariadb.0.0.32`: An implementation of the session store using MariaDB
-`sihl_session_postgresql.0.0.32`: An implementation of the session store using PostgreSQL
-`sihl_user.0.0.32`: A user management app for Sihl
-`sihl_user_mariadb.0.0.32`: A storage for users using MariaDB
-`sihl_user_postgresql.0.0.32`: A storage for users using PostgreSQL

---
* Homepage: https://github.com/oxidizing/sihl
* Source repo: git+https://github.com/oxidizing/sihl.git
* Bug tracker: https://github.com/oxidizing/sihl/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by avsm** [comment]
Thanks for this very impressive looking new package set! Just a few changes needed to fix the various CI failures:

- could you push a changeset to add dev-repo fields to the opam packages? This will allow `opam pin <pkg> --dev` to work correctly on them.
- there are various `{with-test}` dependencies missing -- if you click on the 'revdeps' part of the CI you will see red crosses and build logs showing the errors.

**Comment by jerben** [comment]
@avsm Thanks for the feedback! I will do those changes.

**Comment by jerben** [comment]
```
Reading package lists...
The following command needs to be run through "sudo":
    apt-get install -qq -yy libffi-dev libgmp-dev libmariadb-dev libpcre3-dev libssl-dev m4 perl pkg-config
# OS package update successful
E: Unable to locate package libmariadb-dev
OS package installation failed
```
Looks like `opam depext` fails for some distributions. One of our dependencies has following depexts: 

```
depexts: [
  ["libmariadb-dev"] {os-distribution = "debian"}
  ["libmariadb-dev"] {os-distribution = "ubuntu"}
]
```
Is there a way to define different depexts depending on the ubuntu version?

**Comment by jerben** [comment]
Closing this in favor of: https://github.com/ocaml/opam-repository/pull/16645

**Pull request closed without merging**
