### PR TITLE
new file:   packages/cpm/cpm.12.2.0/opam

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by mseri** [comment]
Which library provides `A.create`? Probably if I fix the following error we fix most revdeps on 5.0.0:

```
#=== ERROR while compiling molenc.16.13.0 =====================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-variants.5.0.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/molenc.16.13.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p molenc -j 71
# exit-code            1
# env-file             ~/.opam/log/molenc-7-dc9ce4.env
# output-file          ~/.opam/log/molenc-7-dc9ce4.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.molenc.objs/byte -I /home/opam/.opam/5.0/lib/batteries -I /home/opam/.opam/5.0/lib/bst -I /home/opam/.opam/5.0/lib/camlp-streams -I /home/opam/.opam/5.0/lib/dolog -I /home/opam/.opam/5.0/lib/domainslib -I /home/opam/.opam/5.0/lib/lockfree -I /home/opam/.opam/5.0/lib/num -I /home/opam/.opam/5.0/lib/ocaml/str -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/parany -I /home/opam/.opam/5.0/lib/pyml -I /home/opam/.opam/5.0/lib/stdcompat -I /home/opam/.opam/5.0/lib/vector3 -no-alias-deps -open Molenc -o src/.molenc.objs/byte/molenc__Sdf_3D.cmo -c -impl src/sdf_3D.ml)
# File "src/sdf_3D.ml", line 276, characters 14-22:
# 276 |   let bonds = A.create num_atoms [] in
#                     ^^^^^^^^
# Error: Unbound value A.create
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.molenc.objs/byte -I /home/opam/.opam/5.0/lib/batteries -I /home/opam/.opam/5.0/lib/bst -I /home/opam/.opam/5.0/lib/camlp-streams -I /home/opam/.opam/5.0/lib/dolog -I /home/opam/.opam/5.0/lib/domainslib -I /home/opam/.opam/5.0/lib/lockfree -I /home/opam/.opam/5.0/lib/num -I /home/opam/.opam/5.0/lib/ocaml/str -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/parany -I /home/opam/.opam/5.0/lib/pyml -I /home/opam/.opam/5.0/lib/stdcompat -I /home/opam/.opam/5.0/lib/vector3 -no-alias-deps -open Molenc -o src/.molenc.objs/byte/molenc__WMH.cmo -c -impl src/WMH.ml)
# File "src/WMH.ml", line 73, characters 12-20:
# 73 |   let res = A.create total 0 in
#                  ^^^^^^^^
# Error: Unbound value A.create
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.molenc.objs/byte -I /home/opam/.opam/5.0/lib/batteries -I /home/opam/.opam/5.0/lib/bst -I /home/opam/.opam/5.0/lib/camlp-streams -I /home/opam/.opam/5.0/lib/dolog -I /home/opam/.opam/5.0/lib/domainslib -I /home/opam/.opam/5.0/lib/lockfree -I /home/opam/.opam/5.0/lib/num -I /home/opam/.opam/5.0/lib/ocaml/str -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/parany -I /home/opam/.opam/5.0/lib/pyml -I /home/opam/.opam/5.0/lib/stdcompat -I /home/opam/.opam/5.0/lib/vector3 -no-alias-deps -open Molenc -o src/.molenc.objs/byte/molenc__Bloom.cmo -c -impl src/bloom.ml)
# File "src/bloom.ml", line 53, characters 12-20:
# 53 |   let res = A.create m 0 in (* dense output vector *)
#                  ^^^^^^^^
# Error: Unbound value A.create
```

**Comment by UnixJunkie** [comment]
A is an alias for BatArray, so batteries should provide this.

**Comment by mseri** [comment]
Fixed by @kit-ty-kate in https://github.com/ocaml/opam-repository/pull/22751

**Comment by UnixJunkie** [comment]
Okay, I will check what's needed for ocaml>=5.0.0 to fix at least this package.

**Comment by UnixJunkie** [comment]
cpm works fine with ocaml-5.
In some future PR(s) I will take care about making all my published opam packages compatible with ocaml-5.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
