### PR TITLE
[new release] reason-react (2 packages) (0.14.0)

### PR DESCRIPTION
**Pull request by davesnx**
Reason bindings for React.js

- Project page: <a href="https://reasonml.github.io/reason-react">https://reasonml.github.io/reason-react</a>
- Documentation: <a href="https://reasonml.github.io/reason-react">https://reasonml.github.io/reason-react</a>

##### CHANGES:

* Wrap the `React` library, exposing just a single top-level module
  (@anmonteiro in [reasonml/reason-react#783](https://github.com/reasonml/reason-react/pull/783))
* Re-organise toplevel modules (@davesnx in [reasonml/reason-react#794](https://github.com/reasonml/reason-react/pull/794))
* Require and adapt to Melange v3 (@anmonteiro in [reasonml/reason-react#821](https://github.com/reasonml/reason-react/pull/821))

### CODE REVIEW

**Comment by anmonteiro** [comment]
took care of the revdeps issues here: https://github.com/ocaml/opam-repository/pull/25230

**Comment by avsm** [comment]
Looks like a few test dependencies are missing here.

```
#=== ERROR while compiling reason-react-ppx.0.14.0 ============================#
# context              2.2.0~beta2~dev | linux/x86_64 | ocaml-base-compiler.5.1.1 | pinned(https://github.com/reasonml/reason-react/releases/download/0.14.0/reason-react-0.14.0.tbz)
# path                 ~/.opam/5.1/.opam-switch/build/reason-react-ppx.0.14.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p reason-react-ppx -j 255 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/reason-react-ppx-7-490676.env
# output-file          ~/.opam/log/reason-react-ppx-7-490676.out
### output ###
# File "ppx/test/dune", line 4, characters 11-23:
# 4 |   (package reason-react)
#                ^^^^^^^^^^^^
# Error: Package reason-react does not exist
# File "ppx/test/dune", line 8, characters 2-11:
# 8 |   %{bin:jq}
#       ^^^^^^^^^
# Error: Program jq not found in the tree or in PATH
#  (context: default)
# File "test/dune", line 6, characters 48-60:
# 6 |  (libraries reason-react reason-react.node jest melange.belt)
#                                                     ^^^^^^^^^^^^
# Error: Library "melange.belt" not found.
# -> required by alias test/runtest

```

**Comment by davesnx** [comment]
Sure, tests aren't meant to run on the opam-repository since https://github.com/ocaml/opam-repository/pull/24422#discussion_r1325170412

**Comment by davesnx** [comment]
This is ready to review @mseri

**Comment by mseri** [comment]
lgtm

**Comment by mseri** [comment]
thanks

**Pull request merged**
