### PR TITLE
Publish the first version of nosetup

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
These files were helpfully generated by topkg

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Looks like there is some issue with the version of `cstruct` that `angstrom` pics.

**Comment by avsm** [comment]
Cstruct.of_string was added in `cstruct {>="0.7.0"}`, will fix angstrom...

**Comment by avsm** [comment]
fixed pushed to your branch in c7e03509d7f3e31eb3d02cf53123cb88b84a53a5 /cc @seliopou

**Comment by Leonidas-from-XIV** [comment]
@avsm Thanks! I closed the other PR. Also added a constraint on 4.02 since it uses 4.02 syntax.

(Manually. Maybe `topkg` can generate this constraint as well, will look into it)

**Pull request merged**
