### PR TITLE
Restrict mysql_protocol to bitstring < 3

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
bitstring 3.0.0 removed the camlp4 bitstring.syntax so it can't compile anymore.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
The builds are all green except the build on Travis in macOS which is waiting for a macOS machine since a long time and might never terminate. I think it should be safe to merge.

cc @mseri maybe?

**Comment by avsm** [comment]
Thanks; this should have been caught by the revdeps tests when the new bitstring was merged...

**Comment by Leonidas-from-XIV** [comment]
Thanks @avsm! I have submitted this patch to upstream as well, which gives some time to port it to the PPX bitstring version.

**Comment by avsm** [comment]
Splendid, thanks! The more camlp4 retirement, the better :-) cc @jpdeplaix who was looking into the set of existing camlp4 users...

**Comment by jpdeplaix** [comment]
> Thanks; this should have been caught by the revdeps tests when the new bitstring was merged...

It has been caught but since errors on revdeps are discarded they did not appear on the results.
* PR: https://github.com/ocaml/opam-repository/pull/11208
* CI: https://ci.ocamllabs.io/ocaml/opam-repository/pr/11208

Related to https://github.com/avsm/mirage-ci/pull/12

Thanks for the ping :)

**Pull request merged**
