### PR TITLE
2 packages from project-everest/hacl-star at 0.2.2

### PR DESCRIPTION
**Pull request by victor-dumitrescu**
This pull-request concerns:
-`hacl-star.0.2.2`: OCaml API for EverCrypt/HACL*
-`hacl-star-raw.0.2.2`: Auto-generated low-level OCaml bindings for EverCrypt/HACL*

---
* Homepage: https://hacl-star.github.io/
* Source repo: git+https://github.com/project-everest/hacl-star.git
* Bug tracker: https://github.com/project-everest/hacl-star/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by victor-dumitrescu** [comment]
Hi, is it no longer the case that the FreeBSD build is allowed to fail?

**Comment by kit-ty-kate** [comment]
> Hi, is it no longer the case that the FreeBSD build is allowed to fail?

It makes very little sense for us to mark it as "allowed to fail" as it would just hide the failure if it's a genuine one. CI failures are always a case-by-case analysis anyway. In this case if you know it fails for a good reason it's fine to merge anyway. There is no hard blocks on CI failures (CIs are quite unstable beasts anyway)

Thanks!

**Comment by victor-dumitrescu** [comment]
Thanks for merging! Indeed, the FreeBSD failure was expected.

**Comment by kit-ty-kate** [comment]
When it is a structural issue with the package (e.g. use of linux-only syscalls, something that's not fixable by the user in any way, …) you can add `available: os = "linux" & os = "macos"` to your opam file to make it more explicit for instance.

**Pull request merged**
