### PR TITLE
elpi 1.0

### PR DESCRIPTION
**Pull request by gares**
This PR packages ELPI, an OCaml library providing an extension language to a host OCaml application.

### CODE REVIEW

**Comment by gares** [comment]
The `build-test` stanza requires `lua5.1` to be installed in order to run.

Which is the recommended way express that? There is already a `lua-config` but it pulls in only the header files, not the command line interpreter (and it pulls in lua5.2, while elpi uses 5.1)

**Comment by gares** [comment]
The package builds fine here on OSX but I had to `brew install gnu-time`

**Comment by kit-ty-kate** [comment]
Seems like you also depend on lua. Could you not invoke such command in your Makefile please ? (if I understand correctly what you said). There are meta package that are just here for that.
`conf-time` and `conf-lua` are what you want, though you might want to update them with the homebrew packages.

**Comment by gares** [comment]
I've added `conf-time {test}` but I don't see it being installed.
Am I missing something?

**Comment by kit-ty-kate** [comment]
the correct syntax was `{test}`. Also you missed `conf-lua` I guess ?
Also these won't work on OSX until you add the correct depext to `conf-lua` and `conf-time`.

**Comment by gares** [comment]
Sorry I did not understand I had to patch conf-time. But looking at its description
```
    new conf-time package for the time command
    
    This package does *not* enforce availability of "GNU time", it may be
    BSD time (BSD, OSX) or Busybox's (Alpine). The only common
    functionality is "time <command>".
```
Do you want me to add a new conf-gnu-time package?

**Comment by gares** [comment]
> Also you missed conf-lua I guess ?

I double checked and (despite an error being printed) `lua5.1` is not necessary (it is only to generate a performance graph, not to run the tests).

On the contrary (a decent version of) `time` is needed.

**Comment by kit-ty-kate** [comment]
mmh I see. So if you are willing to do that you can remove the `build-test` field and no tests will be build.
If you prefer to keep it but really need a GNU time, maybe you can create a new `conf-gnu-time` but I don't know if it's worth it.

**Comment by gares** [comment]
I've disabled tests, but maybe I should have asked first what is the policy for merging a PR here.
If it needs all green lights, then I'm fine with what I did.
If it does not require all CI to get green, I prefer to have the tests be run on most of the cases and have some platform fail for silly reasons.

**Comment by gares** [comment]
Can you help me understand the other failures? I quite don't get what's wrong from the logs

**Comment by kit-ty-kate** [comment]
Don't worry with that. Internal long-standing issues. Thanks !!

**Pull request merged**
