### PR TITLE
herelib: add missing dep on camlp4

### PR DESCRIPTION
**Pull request by damiendoligez**

### CODE REVIEW

**Comment by samoht** [comment]
Doesn't compile on `3.12` (/cc @diml)

```
#=== ERROR while installing herelib.109.12.00 =================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/3.12.1/build/herelib.109.12.00
# compiler     3.12.1
# exit-code    2
# env-file     /home/travis/.opam/3.12.1/build/herelib.109.12.00/herelib-15836-2c871f.env
# stdout-file  /home/travis/.opam/3.12.1/build/herelib.109.12.00/herelib-15836-2c871f.out
# stderr-file  /home/travis/.opam/3.12.1/build/herelib.109.12.00/herelib-15836-2c871f.err
### stdout ###
# ocamlopt.opt -o setup.exe setup.ml || ocamlopt -o setup.exe setup.ml || ocamlc -o setup.exe setup.ml
# rm -f setup.cmx setup.cmi setup.o setup.obj setup.cmo
# ./setup.exe -configure 
### stderr ###
# W: Field 'ocaml_version_ge_4_00_0' is not set: Cannot satisfy version constraint on ocaml: >= 4.00.0 (version: 3.12.1)
# E: OCaml version 3.12.1 doesn't match version constraint >= 4.00.0
# E: Failure("1 configuration error")
# make: *** [setup.data] Error 1
```

**Comment by diml** [comment]
You can add a constraint in the opam file

**Comment by yallop** [comment]
I'll merge this and open a new PR for the 3.12 constraint.

**Comment by yallop** [comment]
See #7392.

**Pull request merged**
