### PR TITLE
[new release] let-if (v0.1.0)

### PR DESCRIPTION
**Pull request by reynir**
This ppx brings a `let%if` construct similar Rust's `if let`.

- Project page: <a href="https://github.com/reynir/let-if/">https://github.com/reynir/let-if/</a>

##### CHANGES:

* Initial release!

### CODE REVIEW

**Comment by hcarty** [comment]
I haven't had a chance to check out the PR in detail, but could you add a license?

**Comment by reynir** [comment]
BSD-2-clause license added. Thanks!

**Comment by hcarty** [comment]
@reynir The CI failures are due to a combination of unrelated internal failures and the source code not being available at the location specified in `url`.  Could you take a look at the missing source issue?

**Comment by hcarty** [comment]
Thank you for the fix @reynir and the merge @samoht

**Pull request merged**
