### PR TITLE
restrict tls revdeps to < 0.9.0

### PR DESCRIPTION
**Pull request by hannesm**
discovered in #11104 //cc @djs55 @talex5 @samoht

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Some OPAM 2.0 related failures (cc @AltGr):
```
$ opam depext -uivyj 2 datakit-ci.0.9.0
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
[ERROR] Sorry, resolution of the request timed out.
        Try to specify a simpler request, use a different solver, or increase the allowed time by setting OPAMSOLVERTIMEOUT to a bigger value (currently, it is set to 60.0 seconds).
```

**Comment by hannesm** [comment]
FTR good to merge, CI is failing, but the constraints are an improvement (esp. once #11104 is merged).

**Comment by jpdeplaix** [comment]
Yes yes, I was going to ping for more unrelated failures. One sec

**Comment by jpdeplaix** [comment]
I'm not sure why ```capnp-rpc-lwt.0.2.0``` fails with this error message:
```
# (cd _build/default/capnp-rpc-lwt && /usr/bin/capnpc -o ocaml persistent.capnp)
# persistent.capnp:26:58: error: Parse error.
# persistent.capnp:111:79: error: Parse error.
```
cc @talex5 

Also, I believe ```datakit-ci.0.10.0``` needs some versions constraints over ```datakit-github``` or ```github-unix```: https://ci.ocamllabs.io/log/saved/docker-build-5facbd85e5ca5ef6c06b9e1a781876a4/4b08d822a24fcd9b174c643d7726aa3a42b70e4d

**Comment by talex5** [comment]
@jpdeplaix that capnp error probably means it was being compiled on a distribution with an old version of the capnproto C++ tool (the next release will support these versions too: https://github.com/mirage/capnp-rpc/pull/141).

(and the datakit link doesn't work - maybe the CI database got wiped?)

**Pull request merged**
