### PR TITLE
acgtk: fix compilation issues with new ocaml versions

### PR DESCRIPTION
**Pull request by Nyavlys**
Updated package to take into account ocamlc compiler modifications and dependencies (ocf only compiles with ocaml >= 4.03.0)

modified:   acgtk.1.0b/opam
	modified:   acgtk.1.0b/url
	modified:   acgtk.1.2/opam
	modified:   acgtk.1.2/url
	modified:   acgtk.1.3.0/opam
	modified:   acgtk.1.3.0/url

### CODE REVIEW

**Comment by yallop** [comment]
This wasn't mergeable, so I edited the [commit](https://github.com/Nyavlys/opam-repository/commit/de7383ca30689d6406fe8a60e3e9ff088ef1fcbc) using GitHub's new [maintainer super-powers](https://github.com/blog/2247-improving-collaboration-with-forks).

**Comment by yallop** [comment]
This isn't mergeable.  @Nyavlys, can you fix the conflicts?

**Comment by Nyavlys** [comment]
I fixed the compilation issues.

Sorry, but I don't understand why there still are "conflicts that must be resolved"

($ git status
On branch master
Your branch is up-to-date with 'origin/master'.)

**Comment by yallop** [comment]
The conflicts are with the [upstream master branch](https://github.com/ocaml/opam-repository/commits/master), not with your [own master branch](https://github.com/Nyavlys/opam-repository/commits/master).  One way to fix the conflict is to add the upstream repository as a remote, and then rebase against its master branch, like this:

```
git remote add upstream https://github.com/ocaml/opam-repository
git fetch upstream
git rebase upstream/master
```

**Comment by Nyavlys** [comment]
I rebased against upstream/master, but I'm afraid I first pushed some changes before it was completely rebased. Hence this new "conflict". 
So I rebased again, this time until completion, and pushed the modifications. As far as I understand, this should now be ok (no conflict left after rebase). Bbut probably because of the previous conflicts, this last git push is not automatically taken into account.

**Comment by Nyavlys** [comment]
If you prefer, I can close this pull request and start a new one that should not have all these conflicts.

**Comment by yallop** [comment]
Thanks.  I think that's probably going to be easiest.

**Pull request closed without merging**
