### PR TITLE
Package ocamlfind.1.9.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**
### `ocamlfind.1.9.0`
A library manager for OCaml
Findlib is a library manager for OCaml. It provides a convention how
to store libraries, and a file format ("META") to describe the
properties of libraries. There is also a tool (ocamlfind) for
interpreting the META files, so that it is very easy to use libraries
in programs and scripts.

---
* Homepage: http://projects.camlcity.org/projects/findlib.html
* Source repo: git+https://gitlab.camlcity.org/gerd/lib-findlib.git
* Bug tracker: https://gitlab.camlcity.org/gerd/lib-findlib/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @Kakadu @chetmurthy

**Comment by hannesm** [comment]
FWIW from a [FreeBSD CI run (using Cirrus CI)](https://cirrus-ci.com/task/4944846650605568?command=dependencies#L269) - this seems to fail on FreeBSD:
```
#=== ERROR while compiling ocamlfind.1.9.0 ====================================#
# context              2.0.6 | freebsd/x86_64 | ocaml-base-compiler.4.10.1 | https://opam.ocaml.org#7cf9a5cb
# path                 ~.opam/4.10.1/.opam-switch/build/ocamlfind.1.9.0
# command              ~.opam/4.10.1/.opam-switch/build/ocamlfind.1.9.0/./configure -bindir /.opam/4.10.1/bin -sitelib /.opam/4.10.1/lib -mandir /.opam/4.10.1/man -config /.opam/4.10.1/lib/findlib.conf -no-custom -no-camlp4
# exit-code            1
# env-file             ~.opam/log/ocamlfind-36730-07c2f6.env
# output-file          ~.opam/log/ocamlfind-36730-07c2f6.out
### output ###
# [...]
# bytes: found, installing fake library
# Configuration for dynlink written to site-lib-src/dynlink/META
# Configuration for stdlib written to site-lib-src/stdlib/META
# Configuration for unix written to site-lib-src/unix/META
# Configuration for bigarray written to site-lib-src/bigarray/META
# Configuration for compiler-libs written to site-lib-src/compiler-libs/META
# Configuration for ocamldoc written to site-lib-src/ocamldoc/META
# Configuration for raw_spacetime written to site-lib-src/raw_spacetime/META
# Configuration for threads written to site-lib-src/threads/META
# Configuration for str written to site-lib-src/str/META
# Configuration for bytes written to site-lib-src/bytes/META
# Detecting compiler arguments: FAILED (see the file ocargs.log for details)
```

**Comment by kit-ty-kate** [comment]
cc @dra27

**Comment by kit-ty-kate** [comment]
I'm on it. Sorry, I should've double checked on the platforms we don't test. I'll have a fix in a bit

**Comment by avsm** [comment]
Given this release is already merged, could someone please add a `os != freebsd` in the availability field so that it unblocks the CI breakage on Cirrus.

**Comment by kit-ty-kate** [comment]
fixed in https://github.com/ocaml/opam-repository/pull/18345. Turns out the archive from the website doesn't contain what is in the repository and installation failed also with ocaml-system. This is also fixed.

**Comment by gerdstolpmann** [comment]
The release tarball is packed from the patterns in `findlib.files`. I guess that wasn't clear, and I also didn't double-check.

As also a few others things broke, I'm going to make another release anyway, 1.9.1.

**Pull request merged**
