### PR TITLE
[new release] dream-html (0.0.3)

### PR DESCRIPTION
**Pull request by yawaramin**
HTML generator eDSL for Dream

- Project page: <a href="https://github.com/yawaramin/dream-html">https://github.com/yawaramin/dream-html</a>
- Documentation: <a href="https://yawaramin.github.io/dream-html/">https://yawaramin.github.io/dream-html/</a>

##### CHANGES:

Please refer to release notes in tags.

### CODE REVIEW

**Comment by yawaramin** [comment]
Note: possible nnpchecker error is caused by https://github.com/savonet/ocaml-ssl/issues/143

**Comment by raphael-proust** [comment]
I can't see the CI for this PR. And I don't have any UI to start it… @mseri do you know what's up?

**Comment by mseri** [comment]
There were some problems overnight. We are working on it

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
