### PR TITLE
Lower version constraints for OCaml 4.03 installation

### PR DESCRIPTION
**Pull request by olgu**

### CODE REVIEW

**Comment by yallop** [comment]
Could you please rebase this against the `master` branch?

**Comment by olgu** [comment]
Hi, I tried `git rebase master` in the `ibx` branch but it seems that I am doing something wrong here.
Shall I close the pull request and start from scratch?

**Comment by yallop** [comment]
Yes, closing and starting a new PR might be easiest.  (You might find it easier to keep the commit log clean by avoiding merges altogether, and rebasing instead whenever you need to combine changes from different branches.)

**Comment by samoht** [comment]
Assuming that the Git remote for that repository is called `origin` (you can check that by doing `git remote -v`), to rebase you can do:

```
git fetch origin
git rebase origin/master
```

**Comment by samoht** [comment]
but yes, closing and making a new PR on a fresh repo is good as well!

**Comment by olgu** [comment]
Thanks, I close now and start from scratch!

**Pull request closed without merging**
