### PR TITLE
http_router.0.1.2 - via opam-publish

### PR DESCRIPTION
**Pull request by bhoflack**
Simple http router for cohttp and async.

This is a simple http router for cohttp and async.  It allows you to route http requests to handlers.  Routes can be specified with a DSL that allows you to route constants and regex parts.

---
* Homepage: http://github.com/bhoflack/http_router
* Source repo: http://github.com/bhoflack/http_router.git
* Bug tracker: http://github.com/bhoflack/http_router/issues

---
Pull-request generated by opam-publish v0.2.1

### CODE REVIEW

**Comment by samoht** [comment]
The error is cryptic but it usually means that you didn't commit the `configure` file to your repo:

```
#=== ERROR while installing http_router.0.1.2 =================================#
# opam-version 1.2.2
# os           linux
# command      ./configure --prefix=/home/travis/.opam/system
# path         /home/travis/.opam/system/build/http_router.0.1.2
# compiler     system (4.02.3)
# exit-code    127
# env-file     /home/travis/.opam/system/build/http_router.0.1.2/http_router-8638-85453e.env
# stdout-file  /home/travis/.opam/system/build/http_router.0.1.2/http_router-8638-85453e.out
# stderr-file  /home/travis/.opam/system/build/http_router.0.1.2/http_router-8638-85453e.err
```

**Comment by samoht** [comment]
@AltGr any plan to make the error messages better in that case for opam 2.0?

**Comment by bhoflack** [comment]
Any idea why it's failing on some versions now?

**Comment by samoht** [comment]
I think it doesn't find an other file, probably `<something>.mllib`?

**Comment by samoht** [comment]
I think you need to add `async_ssl` to the list of dependencies.

**Comment by bhoflack** [comment]
I think this is the best i can do,  as async_ssl only supports 4.02.3 and higher.

**Comment by samoht** [comment]
@rgrinberg any idea what's wrong with cohttp 0.10.1 + async?

**Comment by rgrinberg** [comment]
You mean cohttp.0.9.5? Because that's the version I see being installed in travis. I think it's just too old, `Cohttp_async.Body` wasn't available back then. I'd go `>= 0.15.0` at the minimum

**Comment by samoht** [comment]
Ha I see. @bhoflack can you add the right mininum version for `cohttp`? I think that should solve the issue with `async_ssl` so you can remove that dependency.

**Comment by bhoflack** [comment]
Thanks @rgrinberg and @samoht.

I tried depending on cohttp > 0.15.0,  but that doesn't seem to work.  I checked and i think cohttp 0.9.5 is probably used because 0.9.6 and higher depend on 109.12.00,  which requires ocaml > 4.0.

So it looks like opam is ignoring my version range and is still installing an older version.  I didn't check,  but i guess the builds for 4.01 and 4.00 are also failing for a similar reason.

What do you suggest me to do?

Thanks

**Comment by rgrinberg** [comment]
@bhoflack I don't see your cohttp constraint in the PR. Are you sure you added it?

**Comment by bhoflack** [comment]
Thanks!  

I thought the opam file in the zip file was used.  I wasn't aware the one in the repo is being used.

**Comment by rgrinberg** [comment]
@bhoflack if you're using opam publish you just need to do prepare/submit again and it will override this submission as you'd expect

**Comment by bhoflack** [comment]
Finally!  Thanks for your help.

**Comment by samoht** [comment]
Thanks for your patience!

**Pull request merged**
