### PR TITLE
[new release] decimal (0.2.0)

### PR DESCRIPTION
**Pull request by yawaramin**
Arbitrary-precision floating-point decimal library

- Project page: <a href="https://github.com/yawaramin/ocaml-decimal">https://github.com/yawaramin/ocaml-decimal</a>
- Documentation: <a href="https://yawaramin.github.io/ocaml-decimal/api">https://yawaramin.github.io/ocaml-decimal/api</a>

### CODE REVIEW

**Comment by mseri** [comment]
Tests for long integers are failing on 32 bits systems. Is that expected?

**Comment by mseri** [comment]
```
# FAIL: 1E-958594760
# context: { prec = 9; round = half_up; e_max = 999999999; e_min = -999999999; capitals = true; clamp = false; traps = { clamped = false; invalid_operation = false; conversion_syntax = false; div_by_zero = false; div_impossible = false; div_undefined = false; inexact = false; rounded = false; subnormal = false; overflow = false; underflow = false }; flags = { clamped = false; invalid_operation = false; conversion_syntax = false; div_by_zero = false; div_impossible = false; div_undefined = false; inexact = false; rounded = false; subnormal = false; overflow = false; underflow = false } }
# 
# Fatal error: exception Assert_failure("test/decimal_test.ml", 58, 6)
```

**Comment by yawaramin** [comment]
Oh–looks like an overflow. I'll look into it–thanks!

**Comment by yawaramin** [comment]
Hi @mseri --it is indeed an integer overflow issue. Unfortunately I don't have the resources to test/develop/support 32-bit systems. I'll add a note that makes it clear that only 64-bit is supported in the opam file.

**Comment by mseri** [comment]
You could also disable it there if you think it is better: like in https://github.com/ocaml/opam-repository/blob/a78d7fa13785cc738a8dab82014f49ec6040608c/packages/mirage-entropy/mirage-entropy.0.4.1/opam#L36 but with `!=`
(using https://opam.ocaml.org/doc/Manual.html#opamvar-arch )

**Comment by yawaramin** [comment]
Thanks, that's a good suggestion. However I'm not sure how it would get generated from the `dune-project` file. There's no documentation about that.

**Pull request closed without merging**
