### PR TITLE
Parmap 1.0 rc1

### PR DESCRIPTION
**Pull request by rdicosmo**
Update metadata

### CODE REVIEW

**Comment by rdicosmo** [comment]
Only for the matrix entries with opam 1.1.2 and opam 1.2.0, we get an error about a "missing camlp4", and in the corresponding travis log one sees that in the configure phase the version of camlp4 is seen as different from the version of ocamlc.

Any ideas of what is wrong here, and how to fix it?

**Comment by rdicosmo** [comment]
Ok, found it...

**Comment by rdicosmo** [comment]
No, still not working, I'm giving up on updating metadata for rc1,rc2, rc3

**Comment by samoht** [comment]
```
#=== ERROR while installing parmap.1.0-rc1 ====================================#
# opam-version 1.2.0
# os           linux
# command      ./configure
# path         /home/travis/.opam/4.02.3/build/parmap.1.0-rc1
# compiler     4.02.3
# exit-code    1
# env-file     /home/travis/.opam/4.02.3/build/parmap.1.0-rc1/parmap-13857-ad8886.env
# stdout-file  /home/travis/.opam/4.02.3/build/parmap.1.0-rc1/parmap-13857-ad8886.out
# stderr-file  /home/travis/.opam/4.02.3/build/parmap.1.0-rc1/parmap-13857-ad8886.err
### stdout ###
# ...[truncated]
# checking for camlp4... camlp4
# versions differs from ocamlc
# checking for camlp4boot... camlp4boot
# checking for camlp4o... camlp4o
# checking for camlp4of... camlp4of
# checking for camlp4oof... camlp4oof
# checking for camlp4orf... camlp4orf
# checking for camlp4prof... camlp4prof
# checking for camlp4r... camlp4r
# checking for camlp4rf... camlp4rf
### stderr ###
# configure: error: You must install the Camlp4 pre-processor
```

You need to depend explicitly on camlp4. It is installed by default on system switches only.

**Comment by rdicosmo** [comment]
Ok, let's try this. But if this is the reason, why is parmap 1.0 rc1
building properly with all version of OCaml in opam 1.2.2 instead of
erroring out like what happens with opam 1.2.0 and opam 1.1.2?

**Pull request merged**
