### PR TITLE
4 packages from dx3mod/rpmfile at 0.4.0

### PR DESCRIPTION
**Pull request by dx3mod**
This pull-request concerns:
- `rpmfile.0.4.0`: RPM package metadata reader
- `rpmfile-cli.0.4.0`: CLI utility for reading RPM package information (like
  rpm -qi)
- `rpmfile-eio.0.4.0`: RPM package metadata reader (powered by Eio)
- `rpmfile-unix.0.4.0`: RPM package metadata reader (powered by Angstrom)

---
* Homepage: https://github.com/dx3mod/rpmfile
* Source repo: git+https://github.com/dx3mod/rpmfile.git
* Bug tracker: https://github.com/dx3mod/rpmfile/issues

---
:camel: Pull-request generated by opam-publish v2.4.0

### CODE REVIEW

**Comment by avsm** [comment]
This look good, but rpmfile.0.3.x are now failing due to their versions being incompatible. Pushing upper bounds to those packages would be appreciated. `opam admin add-constraint` will automate the job here if you'd prefer to do that from the CLI.

**Comment by dx3mod** [comment]
Thanks for the answer! That was indeed my big mistake. I just forgot about the version bounds.

**Comment by dx3mod** [comment]
> [rpmfile-eio.0.4.0 (failed: conf-pkg-config.3 failed to build)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/16889481d8ad909c61d74b3f074db54902e17010/variant/extras,opam-2.0-ocaml-5.2,rpmfile-eio.0.4.0)

There is this error again, like the last time.

**Comment by avsm** [comment]
That's a separate thing we can fix. Thanks for the upper bounds, now merging!

**Pull request merged**
