### PR TITLE
+ mldonkey 3.1.7-2

### PR DESCRIPTION
**Pull request by ygrek**
quickfix release, now includes configure in tarball

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks! However something (m4) is still missing:
```
#=== ERROR while compiling mldonkey.3.1.7-2 ===================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.02.3 | pinned(https://ygrek.org/p/release/mldonkey/mldonkey-3.1.7-2.tar.bz2)
# path                 ~/.opam/4.02/.opam-switch/build/mldonkey.3.1.7-2
# command              ~/.opam/4.02/.opam-switch/build/mldonkey.3.1.7-2/./configure --enable-debug --prefix /home/opam/.opam/4.02
# exit-code            127
# env-file             ~/.opam/log/mldonkey-23-b36dbe.env
# output-file          ~/.opam/log/mldonkey-23-b36dbe.out
### output ###
# Running m4 to generate Makefile...
# /home/opam/.opam/4.02/.opam-switch/build/mldonkey.3.1.7-2/./configure: 44: /home/opam/.opam/4.02/.opam-switch/build/mldonkey.3.1.7-2/./configure: m4: not found
```
You could either require `conf-m4` or regenerate the tarball with a Makefile. As you wish.

**Comment by ygrek** [comment]
(I pushed +conf-m4 fix first) but then I realized that you are right indeed and better have generated Makefile in release. The build system there is quite archaic, hopefuly I can simplify it for next release. Sorry for the troubles.

**Comment by mseri** [comment]
Looks good now imo.
I am a bit puzzled by the osx failure and the local switch one in Travis, I'll wait to merge for @kit-ty-kate to also have a look

**Comment by kit-ty-kate** [comment]
The remaining failures come from the fact that there is no debian or homebrew packages for camlp4 and a system compiler is used in both cases. It's ok to ignore. Thanks a lot!

**Pull request merged**
