### PR TITLE
fix conf-rdkit for recent rdkit on Linux

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks!

**Comment by kit-ty-kate** [comment]
There seem to be still a problem with this package:
```
#=== ERROR while compiling conf-rdkit.0.1 =====================================#
# context              2.0.3 | linux/x86_64 | ocaml-base-compiler.4.05.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.05.0/.opam-switch/build/conf-rdkit.0.1
# command              /bin/sh -c c++ test.cpp -o test -I/usr/local/include -I/usr/include/rdkit -L/usr/local/lib -lRDGeneral || \
              c++ test.cpp -o test -I/usr/local/include -I/usr/include/rdkit -L/usr/local/lib -lRDKitRDGeneral
# exit-code            1
# env-file             ~/.opam/log/conf-rdkit-1-982793.env
# output-file          ~/.opam/log/conf-rdkit-1-982793.out
### output ###
# [...]
# In file included from /usr/include/rdkit/RDGeneral/versions.h:13,
#                  from test.cpp:2:
# /usr/include/rdkit/RDGeneral/export.h:9:10: fatal error: boost/config.hpp: No such file or directory
#  #include <boost/config.hpp>
#           ^~~~~~~~~~~~~~~~~~
# compilation terminated.
# In file included from /usr/include/rdkit/RDGeneral/versions.h:13,
#                  from test.cpp:2:
# /usr/include/rdkit/RDGeneral/export.h:9:10: fatal error: boost/config.hpp: No such file or directory
#  #include <boost/config.hpp>
#           ^~~~~~~~~~~~~~~~~~
# compilation terminated.
```

**Comment by kit-ty-kate** [comment]
this appears on debian sid. Maybe it's a problem on debian's side?

**Comment by UnixJunkie** [comment]
Probably a problem with the boost version they provide.
Maybe too old to provide this file?
Or, we need a conf-boost and I should add it to the deps?

**Pull request merged**
