### PR TITLE
core.v0.11.1 and shexp.v0.11.1

### PR DESCRIPTION
**Pull request by diml**
Following a breaking change in spawn v0.12

### CODE REVIEW

**Comment by hcarty** [comment]
For anyone reviewing later - the Travis failure is an unrelated failure in the 4.02 test.

**Comment by kit-ty-kate** [comment]
@hcarty restarted it. It's green now.

@diml there are revdep failures. Could you add the good constraints for them ? (I think most failures are not related to this release but if it can be done it would be super :) )

**Comment by diml** [comment]
Ok, I added constraints to hll, opass and biocaml. I didn't understand the failure for get_line so I didn't touch it.

**Comment by diml** [comment]
The last two failures are for dlist and get_line. For dlist, it seems to be related to oasis. For get_line, I don't understand the error, it's complaining about `sexplib.unix` being not found, however it is definitely part of sexplib v0.11.0.

**Comment by kit-ty-kate** [comment]
Everything seem fine. However `core` doesn't compile under Alpine (I'm not sure if this is new or not):
Full log here: https://ci.ocamllabs.io/log/saved/docker-build-b86df542b39546662fd1be72eef79006/e4f19b72418d59e65e2b3d26ce3d4f5e1a1e5724

And `ppx_expect.113.33.00+4.03` doesn't build anymore on 4.03 and 4.04 (at least). For more details see Travis logs:
* https://travis-ci.org/ocaml/opam-repository/jobs/373043071
* https://travis-ci.org/ocaml/opam-repository/jobs/373043072

The `ppx_expect` failure is unrelated and can be fixed later (and it's better that way) but I'm not sure what to do with the Alpine failure. Could you have a quick look at it ?

**Comment by diml** [comment]
The alpine failure is not caused by this PR either, the diff between core v0.11.0 and v0.11.1 is very small and doesn't touch the C code. Maybe the version of Alpine or some C library has changed since core v0.11.0 was releaased?

**Comment by kit-ty-kate** [comment]
The Alpine CI part of the CI just got fixed today so the `core.v0.11.0` hasn't been tested on Alpine.
I'll merge it anyway. Do I have to create an issue somewhere or it's not worth it ?

Thanks.

**Comment by hcarty** [comment]
@diml @kit-ty-kate I added a bug to the Core github issue tracker a few weeks ago (https://github.com/janestreet/core/issues/109) so it's at least recorded.

**Comment by diml** [comment]
Thanks. I guess we'll need to fix this issue for future releases

**Pull request merged**
