### PR TITLE
goblint-cil build patch to detect more recent gcc

### PR DESCRIPTION
**Pull request by raphael-proust**
addressing https://github.com/ocaml/opam-repository/pull/24423#issuecomment-1727804077

### CODE REVIEW

**Comment by raphael-proust** [comment]
@sim642 The patch seems to work: gcc is correctly found on macos. There are now different errors.

- Is it ok to merge with these errors? (Do you want to mark the package a unavailable on some platforms because the errors indicate that the software is not correct there? Do you think those errors are ok?)
- If you want to copy the error logs you should do so before the PR is merged.

**Comment by sim642** [comment]
I've copied the logs into upstream issues to look into. I think oraclelinux-9 and freebsd are both new for opam CI, so there might be something up with that because all the tests fail.

**Comment by mseri** [comment]
`oraclelinux` should disappear soon while `freebsd` is here to stay :)

**Comment by mseri** [comment]
Thanks

**Pull request merged**
