### PR TITLE
release vchan, vchan-unix, vchan-xen v4.0.2

### PR DESCRIPTION
**Pull request by yomimono**

### CODE REVIEW

**Comment by yomimono** [comment]
The CentOS failure seems to be related to how CentOS is distributing Xen development packages these days and needs an update to the relevant upstream depexts for `xen-devel` - I'm not sure what it should be updated to, unfortunately.

**Comment by avsm** [comment]
thank you!

**Comment by avsm** [comment]
incidentally, if you want a quicker release workflow, then `dune-release tag && dune-release` will generate a PR here with the changelog and upload docs etc for you.

**Comment by yomimono** [comment]
`dune-release` doesn't like the `doc` fields in these opam files.

**Comment by mseri** [comment]
What about opam-publish?

**Comment by yomimono** [comment]
I've never once had success using `opam-publish` and found its error messages incomprehensible enough that I made my own solutions using the `github` library back when I was doing a lot of releases and before the days of `dune-release`.

`dune-release` is great; I love `dune-release`; my desire to hold up a release for another make-a-PR-and-wait-for-someone-to-merge-it cycle when I'm just trying to make a release is extremely low.

**Comment by hannesm** [comment]
> dune-release doesn't like the doc fields in these opam files.

then change the doc fields? ;) or run dune-release publish distrib (instead of dune-release publish)

**Comment by anmonteiro** [comment]
> then change the doc fields? ;) you can also run dune-release publish distrib which won't attempt to publish the docs :)

This needs to be front and center in the `dune-release` docs :D

**Comment by yomimono** [comment]
> then change the doc fields? ;) 

>> my desire to hold up a release for another make-a-PR-and-wait-for-someone-to-merge-it cycle when I'm just trying to make a release is extremely low.

Also, this is a bug in dune-release reported at https://github.com/samoht/dune-release/issues/59 .  I'm interested in scriptable solutions that solve this problem across the universe of repositories I might touch or fixes for the tool (especially if I'm going to get at-ed about how I'm not using it).

> you can also run dune-release publish distrib which won't attempt to publish the docs

This is useful information; thank you.

**Comment by mseri** [comment]
@yomimono I didn’t mean to eat you, sorry, it was just a curiosity :)

**Pull request merged**
