### PR TITLE
Package phonetic.0.1.0

### PR DESCRIPTION
**Pull request by sagotch**

### CODE REVIEW

**Comment by pmetzger** [comment]
Just a note: the description is so vague that if one doesn't already know one is interested in this package, the description will not help one learn that one wants to examine it.

**Comment by sagotch** [comment]
Noted. Documentation in general is not ready for v1.0.0

**Comment by mseri** [comment]
@sagotch do you plan to expand the description on the opam file before merge?

**Comment by sagotch** [comment]
It would be improved on a next release, but no need to wait for it for 0.1.0 version

**Comment by mseri** [comment]
Ok, thanks

**Pull request merged**
