### PR TITLE
[new release] topojsone and topojson (0.1.0)

### PR DESCRIPTION
**Pull request by patricoferris**
Streaming TopoJSON library

- Project page: <a href="https://github.com/geocaml/ocaml-topojson">https://github.com/geocaml/ocaml-topojson</a>

##### CHANGES:

Initial release

### CODE REVIEW

**Comment by patricoferris** [comment]
*sigh* I did the same thing as I did in https://github.com/ocaml/opam-repository/pull/22281 sorry, I wonder if ocaml-ci can catch these kinds of things. I'll have to re-release the package. Sorry for the noise!

**Comment by avsm** [comment]
What's the error you're referring to? A missing `(package)` to a tests stanza?

**Comment by patricoferris** [comment]
Sorry, I should have been more informative! Yes that's right, I suppose it's less about that specific failure case and more related to the fact that OCaml CI does an unconventional installation in order to support the features that it does:

 - Only runs tests on the intersection of the supported platforms for _all_ of the packages in a given repo hence https://github.com/geocaml/ocaml-topojson only gets tested on OCaml 5 and I never catch the fact that it doesn't work on `< 4.08`. I think this is being tracked: https://github.com/ocurrent/ocaml-ci/issues/470
 - And yes, the problem you specify, which I think is related to ocaml-ci not treating a multi-package repository as a multi-single-package repo if that makes sense.

**Comment by avsm** [comment]
Second problem is probably tracked by https://github.com/ocurrent/ocaml-ci/issues/257

**Pull request closed without merging**
