### PR TITLE
+lwt.2.7.0, lwt_ssl.1.0.0, lwt_glib.1.0.0, lwt_react.1.0.0

### PR DESCRIPTION
**Pull request by aantron**
Packages being factored out of Lwt, to be removed from the base `lwt` package in Lwt 3.0.0. See https://github.com/ocsigen/lwt/pull/301.

I submitted these in a separate PR because I suspect they won't build in CI (due to constraints) until Lwt 2.7.0 is accepted.

EDIT: #8195.

### CODE REVIEW

**Comment by avsm** [comment]
Any chance you could also merge in the lwt 2.7.0 PR into this branch please? It'll unblock CI.

**Comment by aantron** [comment]
Yes, I can do that. Do you mean after that PR is merged, or immediately?

**Comment by avsm** [comment]
Immediately would be good, as then the additional packages can be tested.  There is also a new set of CI tests that can test reverse dependencies that will run.

**Comment by aantron** [comment]
I rebased over the Lwt base package branch, not including new upper bounds as waiting for the revdeps build to complete. Let me know what subsequent other squashes/rebases/merges/whatever you want, and also feel free to merge any way that is appropriate.

**Comment by avsm** [comment]
Thank you for all the  upper bounds! One missing in the CI is `release.1.1.1`

```
# File "lib_test/master.ml", line 1:
# Error: Some fatal warnings were triggered (1 occurrences)
# Command exited with code 2.
```

All the others pass, yay!

**Comment by aantron** [comment]
Anil, I did add [an upper bound](https://github.com/ocaml/opam-repository/pull/8196/commits/d366949278b66cc0a80f515d2dd3cd7d7799cbc9#diff-a8ccf1118fcc4e1485d4a3242af2e752R9) on `release.1.1.1`. Indeed, from [that log](https://ci.ocaml.io/log/saved/docker-build-242fc5bff4c3c2a2537ace0890002765/116a1cf4c9d0225a0df73d298028b33e1b5e5167):

```
  - install lwt        2.6.0  
```

It is failing because of deprecation warnings unrelated to Lwt.

**Comment by aantron** [comment]
Do you want me to constrain it anyway? I guess it requires OCaml < 4.03, but I can look in more detail.

**Comment by aantron** [comment]
Also, since the CI is working out fine, I suppose we should rename this PR and abandon the other one. Reasonable?

**Comment by avsm** [comment]
Constraining it to build would be great.

**Comment by aantron** [comment]
Yep already looking to be sure of the constraint, will add a commit shortly.

**Comment by aantron** [comment]
Ok, all releases of `release` have an offending combination of lines:

- [All warnings as errors](https://github.com/andrenth/release/blob/master/myocamlbuild.ml#L797)
- [Usage of `String.uppercase`](https://github.com/andrenth/release/blob/02712226e9191a24fd362b8e2b614e3d9ea85432/lib_test/lwt/master.ml#L24)
- [`String.uppercase` is deprecated since 4.03](http://caml.inria.fr/pub/docs/manual-ocaml/libref/String.html#VALuppercase)

So I constrained them all to require < 4.03, except for release `1.0.2`, which is already constrained to `broken`.

cc @andrenth

**Comment by samoht** [comment]
@avsm are you ok to merge this one? It seems that the remaining errors were already there.

**Comment by avsm** [comment]
Good to go! Thanks for all the hard work with the release, @aantron!

**Pull request merged**
