### PR TITLE
core 112.35.01

### PR DESCRIPTION
**Pull request by bmillwood**
Fixing build of Core on 32-bit.

Core_profiler is still broken on 32-bit, but I'm actually not completely sure it was ever supposed to work there.

Don't merge this -- if it's good, let me know and I'll update it to the final URL.

### CODE REVIEW

**Comment by bmillwood** [comment]
@avsm ping

**Comment by avsm** [comment]
Aside from the lint errors, looks good to merge (the lint errors can be fixed en masse later on all the versions). Final please.

**Comment by bmillwood** [comment]
Oops, missed this. Will get to it on Monday.

**Comment by avsm** [comment]
Thanks! At some point, a mega PR that updates the various core packages to OPAM 1.2 would be useful (e.g. dev-repo fields so that `opam pin x --dev` works, and separate `build` and `install` fields).

**Pull request merged**
