### PR TITLE
conf-qt: don't run a script that calls 'sudo add-apt-repository'

### PR DESCRIPTION
**Pull request by yallop**
The `source linux` `depext` [script](https://gist.githubusercontent.com/Kakadu/7dc6f7c9f8760f7fbace/raw/295dd3528cf9cf2be7a67a9752e530353bb6211b/get_qt.sh) for `conf-qt` is Ubuntu-specific:

```
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
```

and has surprising and enduring effects on other systems (e.g. Debian).  Removing this will probably make the CI fail, but is better for users.

/cc @Kakadu

### CODE REVIEW

**Comment by Kakadu** [comment]
@yallop 
If Ubuntu version on CI server is rather new (12.04 didn't have right packages in 2013) we can remove the script at all.

**Comment by yallop** [comment]
Yes, Travis is running Trusty nowadays, so the packages that were once missing may be directly installable now.

**Comment by Kakadu** [comment]
It could even pass CI after your change ....

**Comment by Kakadu** [comment]
It seems that `qt5-qmake` package is needed....

**Comment by Kakadu** [comment]
From logs I can see that we don't have Qt5 installed on the GNU/Linux that uses `apk` package manager.

There are also some issues with QOCamlBrowser but I will deal with them in #9924

**Comment by yallop** [comment]
> From logs I can see that we don't have Qt5 installed on the GNU/Linux that uses apk package manager.

Yes; neither alpine nor Centos have Qt5 available, as far I can see.

**Comment by Kakadu** [comment]
Well, there is something https://pkgs.alpinelinux.org/package/edge/community/x86/qt5-qtbase

But for me it will be easier to disable CIing of Qt related packages on these distro's (my heart belongs to .debs)

**Comment by Kakadu** [comment]
Well, qmake for qt5 is not found because it has different name in Alpine. https://pkgs.alpinelinux.org/contents?branch=edge&name=qt5-qtbase-dev&arch=ppc64le&repo=community

I will try to get something useful from the Alpine Linux IRC.....

**Comment by Kakadu** [comment]
@yallop It seems that on alpine we need to adjust PATH to successfully use Qt5 on alpine, like `set PATH= /usr/lib/qt5/bin/:$PATH`. There is a small issue: I don't know how to make this command runnable only on alpine and manual entry doesn't help so much http://opam.ocaml.org/doc/Manual.html#Filters

Of course, we can run this path adjustment for every platform and hope that it will work OK.... What do you think?

**Comment by yallop** [comment]
@Kakadu: I think something like this might work:

```
build: [
    ["sh" "-exc" "PATH=/usr/lib/qt5/bin:$PATH echo \"Your Qt version is `qmake -query QT_VERSION`\"" ] 
       {os = "alpine"}
   …
```

**Comment by dbuenzli** [comment]
> {os = "alpine"}

I think os is the result of `uname -s` so I don't think that this will work.

**Comment by yallop** [comment]
I expect you're right, @dbuenzli, but in that case we have a few errors elsewhere in the repository, e.g. [in `sodium`](https://github.com/ocaml/opam-repository/blob/837741b6ac7dd627f28ec92334968ab601b15ce5/packages/sodium/sodium.0.6.0/opam#L36) (cc @dsheets).

**Comment by Kakadu** [comment]
it seems that @dbuenzli is right

**Comment by Kakadu** [comment]
@avsm Our minds have been diverged. Can you help us to constraint some opam commands to the linux version? The "os" variable corresponds to the output of `uname` command but we need output of `lsb_release -i`.

**Comment by avsm** [comment]
I'm afraid it's hard to fix this without opam changes -- see https://github.com/ocaml/opam/issues/2919 for the issue tracking the opam2 improvements in this regard.

**Pull request merged**
