### PR TITLE
gpx 1.1.1 (fixed 1.1.0 build).

### PR DESCRIPTION
**Pull request by sagotch**

### CODE REVIEW

**Comment by sagotch** [comment]
Could you relaunch ? https://travis-ci.org/ocaml/opam-repository/jobs/53011329
```
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

This one fail for a reason I do not understand:
https://travis-ci.org/ocaml/opam-repository/jobs/53011328

```
Checking for availability
[ERROR] No packages found.
'opam list gpx.1.1.1' failed.
Package unavailable.
```

NB: `gpx` is not supposed to be compatible with `4.00.1`: `available: [ ocaml-version >= "4.01" ]`

**Comment by yallop** [comment]
I've restarted the build.

**Comment by sagotch** [comment]
```
W: Failed to fetch http://www.rabbitmq.com/debian/dists/testing/Release.gpg  Could not connect to www.rabbitmq.com:80 (192.240.153.117). - connect (113: No route to host)
```

http://rabbitmq.com is down.

**Comment by dsheets** [comment]
This fails due to bug introduced in #3647. Merging.

**Pull request merged**
