### PR TITLE
Frama-C 17 Chlorine 20180501

### PR DESCRIPTION
**Pull request by maroneze**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Revdep failure looks unrelated but I don't actually know:
```
#=== ERROR while compiling pilat.1.1 ==========================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.06.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.06/.opam-switch/build/pilat.1.1
# command              /bin/sh make.sh
# exit-code            2
# env-file             ~/.opam/log/pilat-18-2bb9f1.env
# output-file          ~/.opam/log/pilat-18-2bb9f1.out
### output ###
# configure.in:18: warning: prefer named diversions
# configure.in:24: warning: prefer named diversions
# configure.in:30: warning: prefer named diversions
# configure.in:40: warning: prefer named diversions
# checking for frama-c-gui... yes
# checking for Makefile.in... yes
# pilat... yes
# checking for /home/opam/.opam/4.06/lib/lacaml/lacaml.cmxa... yes
# checking for /home/opam/.opam/4.06/lib/lacaml/lacaml_top.cmxa... no
# checking for /home/opam/.opam/4.06/lib/zarith/zarith.cmxa... yes
# configure: WARNING: lacaml_top not installed
# configure: WARNING: pilat disabled because /home/opam/.opam/4.06/lib/lacaml/lacaml_top.cmxa missing.
# configure: pilat: no
# configure: creating ./config.status
# config.status: creating ./Makefile
# Generating   .Makefile.plugin.generated
# Cleaning     Pilat
# Generating   .Makefile.plugin.generated
# Generating   top/Pilat.mli
# Ocamldep     ./.depend
# Ocamldep     ./.depend
# Generating   META.frama-c-pilat
# Ocamlc       mat_option.cmi
# Ocamlc       mat_option.cmo
# Ocamlc       float.cmo
# Ocamlc       qring.cmo
# Ocamlc       pilat_math.cmi
# Ocamlc       poly.cmi
# Ocamlc       poly.cmo
# Ocamlc       poly_utils.cmi
# Ocamlc       poly_utils.cmo
# Ocamlc       pilat_visitors.cmi
# Ocamlc       pilat_visitors.cmo
# File "pilat_visitors.ml", line 170, characters 6-112:
# Error: Some record fields are undefined: bstatics
# /home/opam/.opam/4.06/share/frama-c/Makefile.generic:77: recipe for target 'pilat_visitors.cmo' failed
# make: *** [pilat_visitors.cmo] Error 2
```
Otherwise could you flag the ocamlfind dependency with the `{build}` attribute if `Findlib` is not used in Frama-C ? `conf-autoconf` might also need this flag even if we mostly don't care in this case.

**Comment by maroneze** [comment]
The error message is because frama-c added a field `bstatics` in its latest release, and `pilat` was developed with the previous version of Frama-C.

In any way, `pilat` (developed and maintained by one of our former PhDs) should not block the release of Frama-C, since it is a derived plug-in. In this case, what is the standard procedure? Ignore since it's downstream, so kind of "the dependent package's fault"? Or must I go in that package and add "conflicts: frama-c.20180501"? He couldn't know in advance we had just released it anyway, so it's not really his fault that we have an API-incompatible change.

**Comment by kit-ty-kate** [comment]
@maroneze oops I didn't see you comment. Hm, yes, if it's related (a package breaking a revdep that were not broken before) then the broken package should be constrained.

**Comment by maroneze** [comment]
For `pilat`, I blacklisted this version.

For `ocamlfind`, we actually need it during runtime: frama-c has an option which uses Findlib to dynamically load modules and plug-ins.

For `autoconf`, I'm not sure, I'll contact the other developers, but it's possible we also need it after build.

**Comment by maroneze** [comment]
Well, it seems `pilat` is still failing, this time because the constraint I added somehow made opam choose a very old (2014) release of Frama-C, and obviously `pilat` is incompatible with that release, so compilation fails. But it is completely unrelated to this pull request.

I'd gladly try and fix the dependencies on pilat, however it would require that I install several packages to be able to install `pilat`, to check which versions of Frama-C are compatible with it, to then blacklist all of them. In the end, I'd be doing the downstream packager's job, but unfortunately I do not have time for this right now.

I'll notify the developer who will eventually fix it for his package, but I'd like that the Frama-C release not be delayed due to this.

The other errors seem related to `gnomecanvas` not compiling in some platforms, which was already the case 6 months ago with the previous release of Frama-C.

Can you please confirm if there is still something pending on my side?

**Comment by kit-ty-kate** [comment]
That would be fine. Thanks a lot.

Pinging `pilat`'s maintainer: @Stevendeo

**Comment by maroneze** [comment]
Thanks a lot!

**Comment by Stevendeo** [comment]
Updating pilat as we speak!

**Pull request merged**
