### PR TITLE
added ProVerif version 2.01

### PR DESCRIPTION
**Pull request by bruno-blanchet**

### CODE REVIEW

**Comment by bruno-blanchet** [comment]
I do not really understand why camelus says "new broken packages (1): proverif.2.01". The message is not very explicit, and the other tests work, so is the package really broken? If you can help me, that would be great. Thanks a lot.

**Comment by kit-ty-kate** [comment]
"broken packages" for Camelus means "package that cannot be installed (anymore)"

**Comment by kit-ty-kate** [comment]
however in this case the CI could check that it indeed works and Camelus just took this branch alone without merging our master in to do the check. Your branch is very old (the last commit before this one was from 2017) so some packages might have been missing then.

It looks fine otherwise. I'll open an issue on Camelus to also take into account master not just the branch

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
