### PR TITLE
New package traverse.0.1.0

### PR DESCRIPTION
**Pull request by thierry-martinez**
This library provides:
- a module signature `Traverse.Applicative.S` for applicative functors [[McBride and Patterson, 2008]],
- two functions `Traverse.list` and `Traverse.seq` to traverse lists and sequences by a given applicative functor and with a given arity,
- many instances of applicative functors: `Traverse.Applicative.{iter, map, reduce, env, fold, pair, forall, exists, option, result, list}`.

[McBride and Patterson, 2008]: http://www.staff.city.ac.uk/~ross/papers/Applicative.html

The purpose of this library is to provide a common dictionary of "visitors", which is orthogonal to the visited data structure. For instance, `Traverse.list Traverse.Applicative.iter (S O)` is equivalent to `List.iter`, `Traverse.list Traverse.Applicative.map (S (S O))` is equivalent to `List.map2`, etc.  Moreover, one can get a visitor which combine, for instance, both `List.map` and `List.fold_left` by invoking `Traverse.list Traverse.Applicative.(pair map fold)`. To get the same visitors for a sequence (`'a Seq.t`), one just have to replace `Traverse.list` by `Traverse.seq`, and it is easy to define a traversal for any algebraic data structures.

### CODE REVIEW

**Comment by thierry-martinez** [comment]
Thank you, @kit-ty-kate ! Should be fixed now.

**Comment by kit-ty-kate** [comment]
The opam file was missing its `build` field and would previously install nothing. Now that something is compiling the build fails with:
```
#=== ERROR while compiling traverse.0.1.0 =====================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(https://github.com/thierry-martinez/traverse/archive/v0.1.0.tar.gz)
# path                 ~/.opam/4.10/.opam-switch/build/traverse.0.1.0
# command              ~/.opam/4.10/bin/dune build -p traverse -j 72
# exit-code            1
# env-file             ~/.opam/log/traverse-23-de8fad.env
# output-file          ~/.opam/log/traverse-23-de8fad.out
### output ###
# File "src/dune", line 8, characters 23-29:
# 8 |   (libraries stdcompat metapp))
#                            ^^^^^^
# Error: Library "metapp" not found.
# Hint: try: dune external-lib-deps --missing -p traverse -j 72 @install
# File "meta/dune", line 9, characters 19-29:
# 9 |   (preprocess (pps metapp.ppx))
#                        ^^^^^^^^^^
# Error: Library "metapp.ppx" not found.
# Hint: try: dune external-lib-deps --missing -p traverse -j 72 @install
# File "src/dune", line 7, characters 33-43:
# 7 |   (preprocess (pps traverse.meta metapp.ppx))
#                                      ^^^^^^^^^^
# Error: Library "metapp.ppx" not found.
# Hint: try: dune external-lib-deps --missing -p traverse -j 72 @install
```

**Comment by thierry-martinez** [comment]
Oops, I don't know why I thought that build rules were implicit for dune packages, so I made the same mistake for metapp and metaquot. Sorry for this. Thank you very much, @kit-ty-kate !

**Comment by thierry-martinez** [comment]
Finally Travis CI is passing, but I don't know what to do about @camulus "Could not complete" status...

**Comment by kit-ty-kate** [comment]
Is this PR superseeded by https://github.com/ocaml/opam-repository/pull/15958 ?

**Comment by kit-ty-kate** [comment]
oh it also fixes other packages, right. Thanks!

**Pull request merged**
