### PR TITLE
Renamed camlp4.4.02.X+Y to camlp4.4.02+Z and relaxed constraints

### PR DESCRIPTION
**Pull request by diml**
- renamed the various camlp4.4.02.X+Y versions to camlp4.02+Z
- changed the constraints to simply `ocaml-version >= 4.02 & < 4.03`
- removed `camlp4.4.02.0` as it was just a rc1
- added new `camlp4.4.02+6` release

### CODE REVIEW

**Comment by samoht** [comment]
Errors in opam 1.1:

```
[WARNING] Errors while parsing camlp4.4.02+1 OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+2 OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+3 OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+4 OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+6 OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+system OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+1 OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+2 OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+3 OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+4 OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+6 OPAM file, skipping.
[WARNING] Errors while parsing camlp4.4.02+system OPAM file, skipping.
```

Please use "1.2" for `opam-version to fix this (and also would be great to make our lint bot happy)

**Comment by diml** [comment]
I fixed the opam-version and some of the opam-lint complaints.

**Comment by samoht** [comment]
I've restarted the failed job.

**Comment by avsm** [comment]
green 'n merged!

**Pull request merged**
