### PR TITLE
camlp4 for 4.06

### PR DESCRIPTION
**Pull request by gasche**

### CODE REVIEW

**Comment by gasche** [comment]
(cc @jpdeplaix)

**Comment by aantron** [comment]
@gasche, is there to be a `available: preinstalled` (`+system`) package as well?

**Comment by gasche** [comment]
@aantron I don't know, and I'm not familiar with system-specific packaging. Would you like to investigate and propose a PR to fix whatever needs to be fixed?

**Comment by aantron** [comment]
I would guess that a package like [`4.05+system`](https://github.com/ocaml/opam-repository/blob/3bcfe6c8d3ca0e77170ef7a93def21e1b7505546/packages/camlp4/camlp4.4.05%2Bsystem/opam) is enough. Compare [`4.05+1`](https://github.com/ocaml/opam-repository/blob/3bcfe6c8d3ca0e77170ef7a93def21e1b7505546/packages/camlp4/camlp4.4.05%2B1/opam). There shouldn't be anything else. Perhaps @diml knows more, having submitted those packages. I won't have time to submit a PR for this in the near term.

**Pull request merged**
