### PR TITLE
added travis script, lazy email access, efficient mbox import 

### PR DESCRIPTION
**Pull request by gregtatcam**

### CODE REVIEW

**Comment by avsm** [comment]
Does this have to be =0.9.3 for irmin? Makes pinning harder.

**Comment by gregtatcam** [comment]
Doesn’t have to. My concern was about changing Irmin API.

**Comment by avsm** [comment]
Put the minimal bound as required to work within the opam-repository as it stands.  When new packages come in, they adjust the upper bounds.  This lets you pin a working version of Irmin 0.9.4+ and have it compile against this. Same for the git constraints.

**Comment by gregtatcam** [comment]
ok

**Pull request merged**
