### PR TITLE
+oasis2debian.0.1.3

### PR DESCRIPTION
**Pull request by gildor478**

### CODE REVIEW

**Comment by avsm** [comment]
@gildor any chance you could merge this against opam-repository master branch? Looks like camelus needs some newer packages for installability checks.

**Comment by gildor478** [comment]
@avsm updated opam-repository master Unfortunately I did a rebase rather than a merge and make it hard to push to this branch, so I created a new PR  #9230.

Where can I see the error of camelus? I see no link here.

**Comment by avsm** [comment]
> Unfortunately I did a rebase rather than a merge and make it hard to push to this branch

You can force push a rebase to the existing PR via

```
git push origin +feature-oasis2debian-0.1.3
```

> Where can I see the error of camelus? I see no link here

The bot commented [above](https://github.com/ocaml/opam-repository/pull/9226#issuecomment-302643707) that the package is not installable.

**Comment by avsm** [comment]
closed in favour of #9230

**Pull request closed without merging**
