### PR TITLE
old-osbx: Add compiler constraints to osbx

### PR DESCRIPTION
**Pull request by seliopou**
See #10286 for further discussion.

### CODE REVIEW

**Comment by seliopou** [comment]
Travis failure due to nocrypto.0.5.4:

```
#=== ERROR while installing nocrypto.0.5.4 ====================================#
# opam-version 1.2.2
# os darwin
# command ocaml pkg/pkg.ml build --pinned false --tests false --with-lwt true --xen false --freestanding false
# path /Users/travis/.opam/system/build/nocrypto.0.5.4
# compiler system (4.05.0)
# exit-code 1
# env-file /Users/travis/.opam/system/build/nocrypto.0.5.4/nocrypto-9794-a92e23.env
# stdout-file /Users/travis/.opam/system/build/nocrypto.0.5.4/nocrypto-9794-a92e23.out
# stderr-file /Users/travis/.opam/system/build/nocrypto.0.5.4/nocrypto-9794-a92e23.err
### stdout ###
# [...]
# ocamlfind ocamlc -g -ccopt '--std=c99 -Wall -Wextra -O3' -package bytes -package cstruct -c src/native/aes/aesni.c
# mv aesni.o src/native/aes/aesni.o
# ocamlfind ocamlc -g -ccopt '--std=c99 -Wall -Wextra -O3' -package bytes -package cstruct -c src/native/des/generic.c
# mv sha512.o src/native/hash/sha512.o
# mv sha1.o src/native/hash/sha1.o
# mv generic.o src/native/des/generic.o
# mv generic.o src/native/aes/generic.o
# + mv generic.o src/native/aes/generic.o
# mv: rename generic.o to src/native/aes/generic.o: No such file or directory
# Command exited with code 1.
### stderr ###
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
# [...]
# 'src/nocrypto.cmxs' 'src/nocrypto.cmxa' 'src/nocrypto.cma'
# 'src/nocrypto.cmx' 'src/nocrypto.cmi' 'src/nocrypto.mli'
# 'unix/nocrypto_unix.a' 'unix/nocrypto_unix.cmxs'
# 'unix/nocrypto_unix.cmxa' 'unix/nocrypto_unix.cma'
# 'unix/nocrypto_entropy_unix.cmx' 'unix/nocrypto_entropy_unix.cmi'
# 'unix/nocrypto_entropy_unix.mli' 'lwt/nocrypto_lwt.a'
# 'lwt/nocrypto_lwt.cmxs' 'lwt/nocrypto_lwt.cmxa' 'lwt/nocrypto_lwt.cma'
# 'lwt/nocrypto_entropy_lwt.cmx' 'lwt/nocrypto_entropy_lwt.cmi'
# 'lwt/nocrypto_entropy_lwt.mli']: exited with 10
```

/cc @pqwy

**Comment by seliopou** [comment]
To further clarify, this Travis failure was limited to the OS X build.

**Comment by dbuenzli** [comment]
I restarted the job. It's a bit odd I just tried to install `nocrypto.0.5.4` locally here on macos and it works.

**Comment by seliopou** [comment]
Looks good!

**Comment by seliopou** [comment]
Failures due to ocamlfind failing to download. Restarted affected jobs.

**Comment by seliopou** [comment]
The build is finally green!

**Comment by seliopou** [comment]
This is good to go.

**Comment by gasche** [comment]
Sorry for the delay. I forgot to subscribe to this issue and am not subscribed-by-default for opam-repository. Please don't have everyone ping me whenever they want something in, but I deserve it at least for the PRs I asked you to split :-p

**Comment by seliopou** [comment]
@gache thanks :smiley:

**Pull request merged**
