### PR TITLE
add ocf 0.4.0 and make stog 0.15.0 depend on it

### PR DESCRIPTION
**Pull request by zoggy**

### CODE REVIEW

**Comment by avsm** [comment]
this conflicts against the OPAM repository master branch

**Comment by zoggy** [comment]
My repo is up to date with opam repo/master with no conflict. Could the conflict be due to the commit f444962 from @AltGr which appears in my pull request ?

**Comment by yallop** [comment]
Yes, it looks that way.   The md5 change in f444962 conflicts with 38681067, which deleted the file `packages/opam-publish/opam-publish.0.1~beta/url`.

The best thing to do is:
  1. run `git rebase -i` and delete the line with the f444962 commit, then
  2. force push (`git push -f`) to your master branch, at which point the change will show up here.

**Comment by zoggy** [comment]
That should be ok, now. Thanks!

**Pull request merged**
