### PR TITLE
Package inotify.2.4

### PR DESCRIPTION
**Pull request by c-cube**
### `inotify.2.4`
Inotify bindings for OCaml
Inotify bindings for OCaml

---
* Homepage: https://github.com/whitequark/ocaml-inotify
* Source repo: git+https://github.com/whitequark/ocaml-inotify.git
* Bug tracker: https://github.com/whitequark/ocaml-inotify/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mseri** [comment]
Thanks

**Comment by c-cube** [comment]
Thank you @mseri ! :grin:

**Comment by samoht** [comment]
There's a missing: `available: os = "linux"` for this package I think - when trying to install it on macOS I get:

```
#=== ERROR while compiling inotify.2.4 =======================================#
# context     2.1.2 | macos/arm64 | ocaml.4.14.0 | https://opam.ocaml.org#473aa392
# path        ~/git/irmin/_opam/.opam-switch/build/inotify.2.4
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p inotify -j 9 --promote-install-files=false @install
# exit-code   1
# env-file    ~/.opam/log/inotify-10028-d4bc88.env
# output-file ~/.opam/log/inotify-10028-d4bc88.out
### output ###
# File "lib/dune", line 4, characters 37-50:
# 4 |   (foreign_stubs (language c) (names inotify_stubs))
#                                          ^^^^^^^^^^^^^
# (cd _build/default/lib && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -pthread -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -g -I /Users/thomas/git/irmin/_opam/lib/ocaml -o inotify_stubs.o -c inotify_stubs.c)
# inotify_stubs.c:31:10: fatal error: 'features.h' file not found
# #include <features.h>
#          ^~~~~~~~~~~~
# 1 error generated.
```

**Pull request merged**
