### PR TITLE
+0install.2.11

### PR DESCRIPTION
**Pull request by talex5**

### CODE REVIEW

**Comment by avsm** [comment]
Bulk build: https://github.com/avsm/opam-pr-build-results/blob/6138/README.md

**Comment by talex5** [comment]
It fails on Fedora because curl fails to install its depext (indeed, Fedora isn't listed in https://github.com/ocaml/opam-repository/blob/master/packages/conf-libcurl/conf-libcurl.1/opam). I assume the bulk build for curl also fails?

I don't know why OCaml 4.03 complains. It says:

    # Error: Type [ `for_each ] Element.t is not a subtype of
    #          arg_parent = [ `command | `for_each | `runner ] Element.t 
    #        The first variant type does not allow tag(s) `command, `runner

where `Element.t` is defined as:

    type +'a t

https://github.com/0install/0install/blob/844b2349e2b090dba191ef7c578ab3fe88935502/ocaml/zeroinstall/element.mli#L20

**Comment by avsm** [comment]
Is the latter issue something to report on mantis against 4.03?

**Comment by talex5** [comment]
I've reported it here, with a simpler test-case: http://caml.inria.fr/mantis/view.php?id=7199

**Pull request merged**
