### PR TITLE
Package curses.1.0.11

### PR DESCRIPTION
**Pull request by mbacarella**
### `curses.1.0.11`
Bindings to ncurses
Tools for building terminal-based user interfaces

---
* Homepage: https://github.com/mbacarella/curses
* Source repo: git+https://github.com/mbacarella/curses.git
* Bug tracker: https://github.com/mbacarella/curses/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This happens on Ubuntu 18.04. I don't remember seeing that before, is that expected?
```
#=== ERROR while compiling curses.1.0.11 ======================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.1 | pinned(https://github.com/mbacarella/curses/archive/refs/tags/1.0.11.tar.gz)
# path                 ~/.opam/4.14/.opam-switch/build/curses.1.0.11
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p curses -j 71 @install
# exit-code            1
# env-file             ~/.opam/log/curses-7-ae9233.env
# output-file          ~/.opam/log/curses-7-ae9233.out
### output ###
# File "dune", line 1, characters 0-283:
#  1 | (library
#  2 |  (name curses)
#  3 |  (public_name curses)
# ....
# 12 |  (libraries unix)
# 13 |  (c_library_flags
# 14 |   (:include c_library_flags.sexp)))
# (cd _build/default && /home/opam/.opam/4.14/bin/ocamlmklib.opt -g -o curses_stubs ml_curses.o -ldopt -lncursesw)
# /usr/bin/ld: cannot find -lncursesw
# collect2: error: ld returned 1 exit status
```

**Comment by kit-ty-kate** [comment]
Also looking at the changelog it seems like we need to constraint all older versions to OCaml < 5.0. Would you be able to open a separate PR for that? If you don't have the time we'll do it

**Comment by mbacarella** [comment]
> This happens on Ubuntu 18.04. I don't remember seeing that before, is that expected?

We [did discuss this previously](https://github.com/ocaml/opam-repository/pull/20074#issuecomment-974856518). I'm still content to wait until someone complains :)

**Comment by mbacarella** [comment]
> Also looking at the changelog it seems like we need to constraint all older versions to OCaml < 5.0. Would you be able to open a separate PR for that? If you don't have the time we'll do it

Oh, right-o. I'll bust out a PR for this.

**Comment by kit-ty-kate** [comment]
> > This happens on Ubuntu 18.04. I don't remember seeing that before, is that expected?
> 
> We [did discuss this previously](https://github.com/ocaml/opam-repository/pull/20074#issuecomment-974856518). I'm still content to wait until someone complains :)

Alright then. Thanks!

**Pull request merged**
