### PR TITLE
[new release] reason-react (2 packages) (0.15.0)

### PR DESCRIPTION
**Pull request by jchavarri**
Reason bindings for React.js

- Project page: <a href="https://reasonml.github.io/reason-react">https://reasonml.github.io/reason-react</a>
- Documentation: <a href="https://reasonml.github.io/reason-react">https://reasonml.github.io/reason-react</a>

##### CHANGES:

* Add `isValidElement` (@r17x in
  https://github.com/reasonml/reason-react/pull/837)
* Add `startTransition` (@r17x in
  https://github.com/reasonml/reason-react/pull/838)
* Convert `ReasonReactErrorBoundary` to Reason instead of `%raw` JS. This has
  the benefit of skipping a hardcoded `require('react')` call (@anmonteiro in
  [reasonml/reason-react#839](https://github.com/reasonml/reason-react/pull/839))
* Add CSS Box Alignment Module Level 3 (@davesnx in
  https://github.com/reasonml/reason-react/pull/847)
* Fix: Remove "unique `key` prop" warnings from multi-child fragment elements
  (@jchavarri in https://github.com/reasonml/reason-react/pull/852)

### CODE REVIEW

**Comment by dinosaure** [comment]
To clarify, this package seems fine to merge but a specific revdep (`melange-fest`) fails because `curl` can not download a package. However, we can not say that it's really good to merge because we don't know if your package has a (subtle) breaking change which will break `melange-fest`). So, a double-look is needed.

**Comment by hannesm** [comment]
@jchavarri the issue you mentioned was reported (and allegedly fixed) https://github.com/ocurrent/ocaml-ci/issues/962

I restarted the failed builds, let's see whether this time curl has more luck (earlier it was exiting with code 6, which is "could not resolve host" -- for a github.com download that sounds like a temporary issue.

**Comment by jchavarri** [comment]
Thanks for the help. In the last build, some things were fixed but there is still this networking error:

```
[ERROR] Failed to get sources of jsonrpc.1.19.0, lsp.1.19.0 (https://github.com/ocaml/ocaml-lsp/releases/download/1.19.0/lsp-1.19.0.tbz): Curl failed
```

Any clues? Thanks again for your time.

**Comment by dinosaure** [comment]
`lambda-soup` was merged (see #26388) was merged and has the same kind of error. Some ready-to-merge PRs has the same issue. We can consider this PR as ready to merge. Thanks for your patience.

**Pull request merged**
