### PR TITLE
[new release] electrod (0.2.1)

### PR DESCRIPTION
**Pull request by grayswandyr**
Formal analysis for the Electrod formal pivot language

- Project page: <a href="https://grayswandyr.github.io/electrod">https://grayswandyr.github.io/electrod</a>
- Documentation: <a href="https://grayswandyr.github.io/electrod/api">https://grayswandyr.github.io/electrod/api</a>

##### CHANGES:

- fix bug between Dune, Menhir and 4.07.1
- make compilable until 4.04
- add compilation testing for various versions of the compiler

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Your source archive does not exist and thus return a 404 error.

**Comment by grayswandyr** [comment]
Source archive uploaded.

**Comment by mseri** [comment]
That is fine. The failure is a known one and does not depend on the package

**Comment by grayswandyr** [comment]
@mseri  So everything is OK, right? ('Cause there's this hanging "needs reporter action" label.)

**Comment by mseri** [comment]
Yes, looks good now. Sorry for the slow response

**Pull request merged**
