### PR TITLE
Added liquidsoap 1.3.5 and gd.1.0a5

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by toots** [comment]
Looking good here from what I can see. The `gd` build on `CentOS` will always fail b/c the distribution does not provide the `depext` package. This isn't the first time. For `RPM`-based distributions CI testing, I'd recommend switch to e.g. `Fedora`.

**Comment by kit-ty-kate** [comment]
Have you considered creating a new conf- package for the external dependencies of gd?

**Comment by toots** [comment]
@kit-ty-kate I'm not familiar with the ins and outs of having a separate `conf-` package for external dependencies. What are the pros and cons?

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
