### PR TITLE
[new release] merlin (3.3.4)

### PR DESCRIPTION
**Pull request by let-def**
Editor helper, provides completion, typing and source browsing in Vim and Emacs

- Project page: <a href="https://github.com/ocaml/merlin">https://github.com/ocaml/merlin</a>

##### CHANGES:

Tue Apr 14 15:25:05 CEST 2020

  + ocaml support
    - full support from OCaml 4.02 to OCaml 4.10 (ocaml/merlin#1117, ocaml/merlin#1127)
    - fix desynchronized cache (ocaml/merlin#1120)
    - short path for OCaml 4.09 and OCaml 4.10 (ocaml/merlin#1082, ocaml/merlin#1117)
    - catch and test environment initialization errors (ocaml/merlin#1083, ocaml/merlin#1130)
    - restore type levels after recovery (ocaml/merlin#1092)
  + merlin binary
    - fix syntax errors in 4.08 and 4.09 (ocaml/merlin#1081)
    - complete-prefix command accepts -kind option to filter results (ocaml/merlin#1071)
    - code cleanup (ocaml/merlin#1093, ocaml/merlin#1079, ocaml/merlin#1112)
    - better handling of expression and pattern extra nodes during browse tree
      traversal (ocaml/merlin#1091, ocaml/merlin#1121)
    - improve context detection (e.g. appropriate namespace for lookup) for
      various queries (ocaml/merlin#1104, ocaml/merlin#1110)
    - add stdlib to locate source path (ocaml/merlin#1085)
  + editor modes
    - vim: tweak heuristic to select python version (ocaml/merlin#1111)
    - emacs: marlin/call
    - lsp: move server to its own repository (ocaml/merlin#1069),
      https://github.com/ocaml/ocaml-lsp
  + test suite
    - dune rules for the test suite are now generated, deterministic and
      can be run individually (ocaml/merlin#1068, ocaml/merlin#1070, ocaml/merlin#1072)
    - fix incorrect command-line arguments in tests (ocaml/merlin#1073)
    - better coverage of frontend features (ocaml/merlin#1075, ocaml/merlin#1078, ocaml/merlin#1088, ocaml/merlin#1089, ocaml/merlin#1126)

Build no longer relies on implicit transitive_deps (ocaml/merlin#1065).

### CODE REVIEW

**Comment by trefis** [comment]
@kit-ty-kate: the test failure on 4.02 is expected: they are due to formatting changes, and the tests are disabled on 4.02 on [travis](https://github.com/ocaml/merlin/blob/master/.travis.yml#L11) and in our [dune-workspace](https://github.com/ocaml/merlin/blob/master/dune-workspace.test).
I don't know how to turn them off for datakit, but everything else looks fine, so I think this could be merged.

**Comment by kit-ty-kate** [comment]
A few more of the tests failed for some unknown reasons:
```

#=== ERROR while compiling merlin.3.3.4 =======================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.05.0 | pinned(https://github.com/ocaml/merlin/releases/download/v3.3.4/merlin-v3.3.4.tbz)
# path                 ~/.opam/4.05/.opam-switch/build/merlin.3.3.4
# command              ~/.opam/4.05/bin/dune runtest -p merlin -j 72
# exit-code            1
# env-file             ~/.opam/log/merlin-31-0d5f56.env
# output-file          ~/.opam/log/merlin-31-0d5f56.out
### output ###
# File "tests/test-dirs/warnings/backtrack.t", line 1, characters 0-0:
#          git (internal) (exit 1)
# (cd _build/default && /usr/bin/git diff --no-index --color=always -u tests/test-dirs/warnings/backtrack.t tests/test-dirs/warnings/backtrack.t.corrected)
# diff --git a/tests/test-dirs/warnings/backtrack.t b/tests/test-dirs/warnings/backtrack.t.corrected
# index 7b4b0b7..1942789 100644
# --- a/tests/test-dirs/warnings/backtrack.t
# +++ b/tests/test-dirs/warnings/backtrack.t.corrected
# @@ -2,6 +2,14 @@ If warnings are not backtracked properly, when reusing the same type checking
#  environment in different queries, some warnings will be reported only once.
#  
#    $ $MERLIN server stop-server
# +  abnormal termination
# +  merlin path: /home/opam/.opam/4.05/.opam-switch/build/merlin.3.3.4/_build/default/src/frontend/ocamlmerlin/ocamlmerlin_server.exe
# +  socket path: /tmp/ocamlmerlin_1000_244_90332232.socket
# +  {
# +    "class": "failure",
# +    "value": "abnormal termination",
# +    "notifications": []
# +  }
#  
#    $ $MERLIN server errors -filename backtrack.ml -w +A <<EOF \
#    > let f x = () \
```
Is that expected?

**Comment by kit-ty-kate** [comment]
There is also a test failure with the system compiler:
```
#=== ERROR while compiling merlin.3.3.4 =======================================#
# context     2.0.6 | linux/x86_64 | ocaml-system.4.09.1 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-system/.opam-switch/build/merlin.3.3.4
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p merlin -j 1
# exit-code   1
# env-file    ~/.opam/log/merlin-16258-949df2.env
# output-file ~/.opam/log/merlin-16258-949df2.out
### output ###
# [...]
# index e47c119..51f6301 100644
# --- a/tests/test-dirs/locate/context-detection/mod_constr.t
# +++ b/tests/test-dirs/locate/context-detection/mod_constr.t.corrected
# @@ -3,7 +3,7 @@
#    {
#      "class": "return",
#      "value": {
# -      "file": "~opam/lib/ocaml/string.ml",
# +      "file": "/usr/local/lib/ocaml/string.ml",
#        "pos": {
#          "line": 1,
#          "col": 0
```
Both errors are not preventing this PR from being merged but they are probably worth fixing for next time. If you say it's fine I'll go ahead and merge it.

**Comment by trefis** [comment]
The second one is unfortunate but unimportant indeed.

The first one is more annoying, we're aware of it and are going to investigate before the next release.

**Comment by kit-ty-kate** [comment]
Ok, thanks a lot!

**Pull request merged**
