### PR TITLE
[new release] hexstring (0.1.2)

### PR DESCRIPTION
**Pull request by mimoo**
A library to encode to and decode from hexadecimal strings

- Project page: <a href="https://github.com/mimoo/hexstring">https://github.com/mimoo/hexstring</a>

##### CHANGES:

Let's see if this works.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Thanks! Could you return the fixes to the opam file upstream so that they are taken into account for the next releases?

**Comment by mimoo** [comment]
why the dune version change btw?

**Comment by kit-ty-kate** [comment]
That's what your `dune-project` file says this package requires: https://github.com/mimoo/hexstring/commit/02262d09770dfb7277eafcd1839a9b46dda8c6e9#diff-1fb9d92d4f0b89e8c93cdefc87d39436b213422961c40453cf2fef5f4a195c57

**Comment by mimoo** [comment]
ah, interesting, looks like `dune-opam-lint` missed that.

**Comment by kit-ty-kate** [comment]
Indeed opam-dune-lint does not currently check that: https://github.com/ocurrent/opam-dune-lint/issues/28

**Pull request merged**
