### PR TITLE
[new release] mdx (2.4.0)

### PR DESCRIPTION
**Pull request by gpetiot**
CHANGES:

#### Added

- Handle the error-blocks syntax (realworldocaml/mdx#439, @jonludlam, @gpetiot)
- Allow execution of included OCaml code blocks (realworldocaml/mdx#446, @panglesd)
- Make MDX compatible with OCaml 5.2 (realworldocaml/mdx#448, @gpetiot)

#### Fixed

- Reduce false-positives while detecting warnings (realworldocaml/mdx#440, @Julow)

### CODE REVIEW

**Comment by gpetiot** [comment]
#25312 has been automatically closed because of a cleanup-gone-wrong on my fork.

**Comment by haochenx** [comment]
all errors are revdeps but the following of them are likely introduced by this release:

[capnp-rpc-unix.1.2.3 (failed: The compilation of capnp-rpc-unix.1.2.3 failed at "dune runtest -p capnp-rpc-unix -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,capnp-rpc-unix.1.2.3)
[current_examples.0.6 (failed: The compilation of current_examples.0.6 failed at "dune runtest -p current_examples -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,current_examples.0.6)
[current_examples.0.6.1 (failed: The compilation of current_examples.0.6.1 failed at "dune runtest -p current_examples -j 31".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,current_examples.0.6.1)
[current_examples.0.6.2 (failed: The compilation of current_examples.0.6.2 failed at "dune runtest -p current_examples -j 31".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,current_examples.0.6.2)
[current_examples.0.6.4 (failed: The compilation of current_examples.0.6.4 failed at "dune build -p current_examples -j 39 @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,current_examples.0.6.4)
[current_examples.0.6.6 (failed: The compilation of current_examples.0.6.6 failed at "dune build -p current_examples -j 31 @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,current_examples.0.6.6)
[dkml-c-probe.3.0.0 (failed: The compilation of dkml-c-probe.3.0.0 failed at "dune build -p dkml-c-probe -j 31 @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,dkml-c-probe.3.0.0)
[irmin-cli.3.4.0 (failed: The compilation of irmin-cli.3.4.0 failed at "dune runtest -p irmin-cli -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.4.0)
[irmin-cli.3.4.1 (failed: The compilation of irmin-cli.3.4.1 failed at "dune runtest -p irmin-cli -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.4.1)
[irmin-cli.3.4.2 (failed: The compilation of irmin-cli.3.4.2 failed at "dune runtest -p irmin-cli -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.4.2)
[irmin-cli.3.4.3 (failed: The compilation of irmin-cli.3.4.3 failed at "dune runtest -p irmin-cli -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.4.3)
[irmin-cli.3.5.0 (failed: The compilation of irmin-cli.3.5.0 failed at "dune runtest -p irmin-cli -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.5.0)
[irmin-cli.3.5.1 (failed: The compilation of irmin-cli.3.5.1 failed at "dune runtest -p irmin-cli -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.5.1)
[irmin-cli.3.5.2 (failed: The compilation of irmin-cli.3.5.2 failed at "dune runtest -p irmin-cli -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.5.2)
[irmin-cli.3.6.0 (failed: The compilation of irmin-cli.3.6.0 failed at "dune runtest -p irmin-cli -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.6.0)
[irmin-cli.3.6.1 (failed: The compilation of irmin-cli.3.6.1 failed at "dune runtest -p irmin-cli -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.6.1)
[irmin-cli.3.7.0 (failed: The compilation of irmin-cli.3.7.0 failed at "dune runtest -p irmin-cli -j 31".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.7.0)
[irmin-cli.3.7.1 (failed: The compilation of irmin-cli.3.7.1 failed at "dune runtest -p irmin-cli -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.7.1)
[irmin-cli.3.7.2 (failed: The compilation of irmin-cli.3.7.2 failed at "dune runtest -p irmin-cli -j 31".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-cli.3.7.2)
[irmin-unix.3.2.1 (failed: The compilation of irmin-unix.3.2.1 failed at "dune runtest -p irmin-unix -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-unix.3.2.1)
[irmin-unix.3.2.2 (failed: The compilation of irmin-unix.3.2.2 failed at "dune runtest -p irmin-unix -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-unix.3.2.2)
[irmin-unix.3.3.1 (failed: The compilation of irmin-unix.3.3.1 failed at "dune runtest -p irmin-unix -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-unix.3.3.1)
[irmin-unix.3.3.2 (failed: The compilation of irmin-unix.3.3.2 failed at "dune runtest -p irmin-unix -j 39".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,4.14,mdx.2.4.0,revdeps,irmin-unix.3.3.2)

[capnp-rpc-unix.1.2.3 (failed: The compilation of capnp-rpc-unix.1.2.3 failed at "dune runtest -p capnp-rpc-unix -j 31".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,5.1,mdx.2.4.0,revdeps,capnp-rpc-unix.1.2.3)
[current_examples.0.6.4 (failed: The compilation of current_examples.0.6.4 failed at "dune build -p current_examples -j 39 @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,5.1,mdx.2.4.0,revdeps,current_examples.0.6.4)
[current_examples.0.6.6 (failed: The compilation of current_examples.0.6.6 failed at "dune build -p current_examples -j 39 @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,5.1,mdx.2.4.0,revdeps,current_examples.0.6.6)
[dkml-c-probe.3.0.0 (failed: The compilation of dkml-c-probe.3.0.0 failed at "dune build -p dkml-c-probe -j 31 @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,5.1,mdx.2.4.0,revdeps,dkml-c-probe.3.0.0)
[eio_linux.0.11 (failed: The compilation of eio_linux.0.11 failed at "dune build -p eio_linux -j 39 @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,5.1,mdx.2.4.0,revdeps,eio_linux.0.11)
[eio_luv.0.6 (failed: The compilation of eio_luv.0.6 failed at "dune build -p eio_luv -j 39 --promote-install-files=false @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,5.1,mdx.2.4.0,revdeps,eio_luv.0.6)
[eio_luv.0.7 (failed: The compilation of eio_luv.0.7 failed at "dune build -p eio_luv -j 39 --promote-install-files=false @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,5.1,mdx.2.4.0,revdeps,eio_luv.0.7)
[eio_luv.0.8.1 (failed: The compilation of eio_luv.0.8.1 failed at "dune build -p eio_luv -j 39 @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,5.1,mdx.2.4.0,revdeps,eio_luv.0.8.1)
[eio_luv.0.9 (failed: The compilation of eio_luv.0.9 failed at "dune build -p eio_luv -j 31 @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2bd9565c5fb3656a1513d21fb342575493d392e1/variant/compilers,5.1,mdx.2.4.0,revdeps,eio_luv.0.9)

**Comment by gpetiot** [comment]
There is a breaking change in the way included blocks are processed (now executed by default). People should probably add an upper bound to their mdx version until they update their files.

**Comment by haochenx** [comment]
>There is a breaking change in the way included blocks are processed (now executed by default). People should probably add an upper bound to their mdx version until they update their files.

Thank you for the information. In that case, we'd like to see this PR including the upper bounds in affected packages, since otherwise merging this PR will break those packages.

@gpetiot do you mind to add the upper bounds? it won't be that difficult with [`opam admin add-constraints`](https://opam.ocaml.org/doc/man/opam-admin.html)

**Comment by haochenx** [comment]
oh, after a closer examination, it seems that only tests of the revdeps are broken for most of the cases.

in this case, merging this PR without adding upper bounds will mostly just generate noises for the opam-repo CI.
that is much better than making existing packages uninstallable (as I incorrectly claimed above) but still not ideal.

therefore, not having the upper bounds in the affected packages is not a clear blocker as far as I concern,
but it will be much better if we can have the upper bounds here.

**Comment by haochenx** [comment]
(an example of `opam admin add-constraint` is: `opam admin add-constraint --packages='irmin-cli,current_examples' 'mdx<2.4'`)

**Comment by gpetiot** [comment]
Thank you, I didn't know this command. However the `--packages` argument was only added since 2.2.0~alpha (I'm running 2.1.5), so I added this constraint on all packages, it might prevent future breakings anyway.

**Comment by raphael-proust** [comment]
Hiya,

I removed the last commit. A few comments about that.

First, it's better to make the MRs adding such constraint separate from your MR adding a package. That's for CI reasons mostly (it avoids your CI picking up all the issues that all those packages have). It's not so big a deal if you add one or two constraints, but the hundreds here where definitely too many.

Second, I'll happily apply the smaller set of constraints if you don't have access to a recent-enough opam. The amount of added constraints in the previous commit was unreasonable.

Third, I'd recommend you mention the breaking change in some public space like discuss or the mailing list. That might save some headaches for some developers.


Anyway, I've opened PR https://github.com/ocaml/opam-repository/pull/25369
FWIW I've run the command w/o `--packages` and then I selectively pulled changes into the git commit and discarded the rest

**Comment by mseri** [comment]
I have fixed eio's failures separately: https://github.com/ocaml/opam-repository/pull/25378
The rest seems to be independent of this PR

**Pull request merged**
