### PR TITLE
Update ppxlib.0.32.1~5.2preview

### PR DESCRIPTION
**Pull request by NathanReb**
Preview release with OCaml 5.2 compatibility

### CODE REVIEW

**Comment by NathanReb** [comment]
CC @kit-ty-kate 

Should I mark the previous preview release as `available: false`?

**Review by kit-ty-kate — CHANGES_REQUESTED** [review]
Adding a new version should not be necessary, the point of a preview release is also to avoid having to add more packages than necessary in opam-repository. Could you instead simply upgrade the url and checksum of 0.32.1~5.2preview with that of the new commit?

**Comment by kit-ty-kate** [comment]
An example of that can be found in https://github.com/ocaml/opam-repository/pull/25322

**Comment by NathanReb** [comment]
Ah yes sure, my bad!

**Review by kit-ty-kate — APPROVED** [review]

**Comment by NathanReb** [comment]
Nothing on my side. I haven't gone through all the failures but from a quick look I agree they do seem familiar!

We would really need for opam-ci to be able to detect when a failure is actually triggered by the new release and when it's not. Having so many false positive really makes it hard and time consuming to actually find and fix real errors.

**Pull request merged**
