### PR TITLE
8 packages from savonet/ocaml-ffmpeg at 1.0.0~rc1

### PR DESCRIPTION
**Pull request by toots**
This pull-request concerns:
-`ffmpeg.1.0.0~rc1`: Bindings for the ffmpeg libraries
-`ffmpeg-av.1.0.0~rc1`: Bindings for the ffmpeg libraries -- top-level helpers
-`ffmpeg-avcodec.1.0.0~rc1`: Bindings for the ffmpeg avcodec library
-`ffmpeg-avdevice.1.0.0~rc1`: Bindings for the ffmpeg avdevice library
-`ffmpeg-avfilter.1.0.0~rc1`: Bindings for the ffmpeg avfilter library
-`ffmpeg-avutil.1.0.0~rc1`: Bindings for the ffmpeg avutil libraries
-`ffmpeg-swresample.1.0.0~rc1`: Bindings for the ffmpeg swresample library
-`ffmpeg-swscale.1.0.0~rc1`: Bindings for the ffmpeg swscale library

---
* Homepage: https://github.com/savonet/ocaml-ffmpeg
* Source repo: git+https://github.com/savonet/ocaml-ffmpeg.git
* Bug tracker: https://github.com/savonet/ocaml-ffmpeg/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by toots** [comment]
Well, looks like we had tests failures we didn't see sorry about that will update here shortly.

**Comment by mseri** [comment]
Are these failures something to worry about?
```
# Available subtitle decoder: ssa - ASS (Advanced SubStation Alpha) subtitle
#    hw_encode alias test/runtest (exit 2)
# (cd _build/default/test && ../examples/hw_encode.exe nvenc.mp4 h264_nvenc device)
# hw_config for h264_nvenc:
# {
#   pixel_format: none,
#   methods: hw_device_ctx,
#   device_type: cuda
# },
# {
#   pixel_format: cuda,
#   methods: hw_frames_ctx,
#   device_type: cuda
# }
# Trying device context method..
# failed with error: Error number 1313558101 occurred
# Fatal error: exception FFmpeg.Avutils.Error(Unknown error occurred)
# Raised by primitive operation at Avutil.HwContext.create_device_context in file "avutil/avutil.ml", line 705, characters 6-67
# Called from Dune__exe__Hw_encode in file "examples/hw_encode.ml", line 162, characters 12-62
```

and

```
# encode_video alias test/runtest
# Pixel format:
# name: yuva420p
# nb_components: 4
# log2_chroma_w: 1
# log2_chroma_h: 1
# flags: alpha, planar
# comp: [
#   plane: 0, step: 0, shift: 0, offset: 0, depth: 4,
#   plane: 0, step: 0, shift: 0, offset: 0, depth: 4,
#   plane: 1, step: 0, shift: 0, offset: 0, depth: 4,
#   plane: 1, step: 0, shift: 0, offset: 0, depth: 4
# ]
# alias: N/A
# bits: 20
#     encoding alias test/runtest (exit 2)
# (cd _build/default/test && ../examples/encoding.exe out.mkv aac mpeg4 ass)
# Fatal error: exception FFmpeg.Avutils.Error(Encoder not found)
```

**Comment by toots** [comment]
> Are these failures something to worry about?
> 
> ```
> # Available subtitle decoder: ssa - ASS (Advanced SubStation Alpha) subtitle
> #    hw_encode alias test/runtest (exit 2)
> # (cd _build/default/test && ../examples/hw_encode.exe nvenc.mp4 h264_nvenc device)
> # hw_config for h264_nvenc:
> # {
> #   pixel_format: none,
> #   methods: hw_device_ctx,
> #   device_type: cuda
> # },
> # {
> #   pixel_format: cuda,
> #   methods: hw_frames_ctx,
> #   device_type: cuda
> # }
> # Trying device context method..
> # failed with error: Error number 1313558101 occurred
> # Fatal error: exception FFmpeg.Avutils.Error(Unknown error occurred)
> # Raised by primitive operation at Avutil.HwContext.create_device_context in file "avutil/avutil.ml", line 705, characters 6-67
> # Called from Dune__exe__Hw_encode in file "examples/hw_encode.ml", line 162, characters 12-62
> ```
> 
> and
> 
> ```
> # encode_video alias test/runtest
> # Pixel format:
> # name: yuva420p
> # nb_components: 4
> # log2_chroma_w: 1
> # log2_chroma_h: 1
> # flags: alpha, planar
> # comp: [
> #   plane: 0, step: 0, shift: 0, offset: 0, depth: 4,
> #   plane: 0, step: 0, shift: 0, offset: 0, depth: 4,
> #   plane: 1, step: 0, shift: 0, offset: 0, depth: 4,
> #   plane: 1, step: 0, shift: 0, offset: 0, depth: 4
> # ]
> # alias: N/A
> # bits: 20
> #     encoding alias test/runtest (exit 2)
> # (cd _build/default/test && ../examples/encoding.exe out.mkv aac mpeg4 ass)
> # Fatal error: exception FFmpeg.Avutils.Error(Encoder not found)
> ```

Hi @mseri.

Yes these two failures appear to be related to some run-time availabilities of either hardware decoding or encoder, which may depend on the hardware the CI is run on or the build-time configuration for ffmpeg.

**Comment by mseri** [comment]
Ok, but this is somehow "hardware"-related, not a bug in the software

**Comment by toots** [comment]
Yes

**Pull request merged**
