### PR TITLE
Let `cairo` depends on `conf-cairo`

### PR DESCRIPTION
**Pull request by OCamlPro-Henry**
/cc @Chris00

### CODE REVIEW

**Comment by dsheets** [comment]
This fails on OS X for missing `Graphics` so it should either be constrained to non-`darwin` or fixed, please.

**Comment by OCamlPro-Henry** [comment]
I was more thinking of just merging this. The breakage on OS X is not
introduced by this PR, so this PR is still an improvement.

And it is not OS X specifics. It should fail on any installation where
graphics was not build, so adding `os != darwin` seems a bit too much
for me. Even if OCaml without Graphics is a more common situation on
OS X than on usual Linux distro.

That said, the error appears only when building an example, which is
not installed. The library itself does not depend on Graphics. The
latest version of `cairo2` (0.5) fixed this by not building the
examples. Here, the error is trigered because I updated old versions.

I might try to add a patch that disable the compilation of
example. But I am not sure it is worth.

**Comment by dsheets** [comment]
Hmm I suppose that's ok. The defaults for Linux and OS X are flipped wrt `Graphics`, though. I don't really think a patch is worth it. If, in the default state, `opam install` fails to install the package even because the examples fail to compile, the package is broken for that configuration. A recent release fixes the issue for the default configuration so I see little point to not constraining the package to exclude OS X. Feel free to merge.

**Comment by OCamlPro-Henry** [comment]
Ok. I think I got your point. Since a recent version builds on OS X,
we won't lose much by restricting old versions and we gain a working
CI. I will add the constraint and merge.

I also quickly checked that packages that depends on cairo2 build with
the latest version, in order not to add regression.

**Comment by dsheets** [comment]
Thanks for checking the reverse dependencies.

**Pull request merged**
