### PR TITLE
Add gapi-ocaml 0.4.1

### PR DESCRIPTION
**Pull request by astrada**

### CODE REVIEW

**Comment by shonfeder** [comment]
The CI failures look to be issues with the CI pipeline rather than the packages themselve:

For  `AMD64, C, OCAML_VERSION=4.09` and version 4.11

> The job exceeded the maximum log length, and has been terminated.

For  `Xcode: xcode11.3, OCAML_VERSION=4.09` and 

> The job exceeded the maximum time limit for jobs, and has been terminated.

I see that on https://github.com/ocaml/opam-repository/pull/16548#issuecomment-637052891 the package was just merged any how. Not sure what's the best course of action here.

**Comment by shonfeder** [comment]
These new, additional CI failings also look to be pipeline related:

```
=== Building opam install google-drive-ocamlfuse.0.7.8 (d161d6)
[2020-06-22 16:47.12] Starting...
Sending build context to Docker daemon  2.048kB

Step 1/6 : FROM sha256:6597ac3fc0369176b30bc64eb656ccdf2e19c1e40bd10329b078935a94581d6c
pull access denied for sha256, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[2020-06-22 17:06.25] Failed: Command "sh" "-c" "docker build --label com.docker.datakit.digest=d161d6cd0d6951a4bbaec0f3c405d68c --label com.docker.datakit.builton=1592844432.76 --rm --force-rm - < /tmp/tmp-1b6d50fe/Dockerfile" exited with status 1
```

Sorry to bother @kit-ty-kate, but might you be able to help guide on how we can push this update through?

**Comment by avsm** [comment]
This is fine to merge, apologies for the CI hiccups.  Just one point with ocamlfuse for the future -- it seems to be directly invoking `make` somewhere, and so wont compile on FreeBSD:


```
#=== ERROR while compiling ocamlfuse.2.7.1-cvs5 ===============================#
13373# context     2.0.6 | freebsd/x86_64 | ocaml-base-compiler.4.09.1 | file:///usr/home/travis/build/ocaml/opam-repository
13374# path        /usr/home/travis/.opam/ocaml-base-compiler.4.09.1/.opam-switch/build/ocamlfuse.2.7.1-cvs5
13375# command     /usr/home/travis/.opam/ocaml-base-compiler.4.09.1/bin/ocaml setup.ml -build
13376# exit-code   1
13377# env-file    /usr/home/travis/.opam/log/ocamlfuse-21156-9e9a54.env
13378# output-file /usr/home/travis/.opam/log/ocamlfuse-21156-9e9a54.out
13379### output ###
13380# [...]
13381# make: "../../OCamlMakefile" line 1009: warning: duplicate script for target "%.mli" ignored
13382# make: "../../OCamlMakefile" line 987: warning: using previous script for "%.mli" defined here
13383# make: "../../OCamlMakefile" line 1010: warning: duplicate script for target "%.ml" ignored
13384# make: "../../OCamlMakefile" line 972: warning: using previous script for "%.ml" defined here
13385# make: "../../OCamlMakefile" line 1010: warning: duplicate script for target "%.mli" ignored
13386# make: "../../OCamlMakefile" line 987: warning: using previous script for "%.mli" defined here
13387# make: "../../OCamlMakefile" line 1084: Need an operator
13388# make: "../../OCamlMakefile" line 1091: Need an operator
13389# make: "../../OCamlMakefile" line 1093: Need an operator
13390# make: Fatal errors encountered -- cannot continue
13391# make: stopped in /usr/home/travis/.opam/ocaml-base-compiler.4.09.1/.opam-switch/build/ocamlfuse.2.7.1-cvs5/lib
13392# E: Failure("Command 'make -C lib INCDIRS=/usr/home/travis/.opam/ocaml-base-compiler.4.09.1/lib/camlidl' terminated with error code 1")
13393
13394
13395
13396
```

(The `make` macro in opam is replaced with `gmake` on the BSDs so they call GNU make reliably)

**Comment by shonfeder** [comment]
No worries at all! Thanks for the help here and for the tips :)

**Comment by astrada** [comment]
@avsm Thanks! About ocamlfuse for FreeBSD: it's selecting package `ocamlfuse.2.7.1-cvs5` and not the latest version `ocamlfuse.2.7.1-cvs6` that uses `dune` instead of `make`.

**Comment by avsm** [comment]
Aha, thats not an optimal solution, probably because of the `dune-configurator < 2.6` in the ocamlfuse.2.7.1-cvs6 opam file. If you release a new version compatible with dune 2.6, it'll probably get selected. Could also put in an `os != freebsd && != openbsd` in the earlier versions too.

**Comment by astrada** [comment]
OK, thanks, I'll look into updating the code to use dune-configurator 2.6.

**Pull request merged**
