### PR TITLE
Update yurt to 0.5

### PR DESCRIPTION
**Pull request by zshipko**

### CODE REVIEW

**Comment by zshipko** [comment]
What is the instability check done by @camelus? What do I need to do to fix it?

Thanks!

**Comment by yomimono** [comment]
^ @AltGr for the Camelus failure.  As far as I can tell, Camelus just counts the number of installable packages on trunk before your PR and after, and alerts if the number doesn't increase as expected (which in this case, it didn't).

I don't see anything wrong with this package, and [yurt 0.5 looks pretty installable to Travis](https://travis-ci.org/ocaml/opam-repository/jobs/335236463#L1189), so I'm not sure why the number is the same.

**Comment by zshipko** [comment]
@yomimono Thanks for the explanation! I am happy to do whatever is needed to resolve the issue, otherwise it should be ready to merge.

**Comment by yomimono** [comment]
@zshipko Congratulations on the release :) I've merged this since it looks fine to me.

**Comment by zshipko** [comment]
@yomimono Much appreciated!

**Comment by AltGr** [comment]
In CI, the [same error](https://ci.ocamllabs.io/log/saved/docker-build-0f287691ce901ce1ddcd8d0ce022a396/5acbe4039cd0f724536704d2a8de565fbd45f933) boils down to:
```
[ERROR] No solution for yurt.0.5: The following dependencies couldn't be met:
          - yurt -> lwt_log
            unknown package
```
but that's not a failure for CI, which tests arches/OSes separately. Maybe `lwt_log` has been merged in the meantime ?

**Pull request merged**
