### PR TITLE
added packages/batteries/batteries.2.6.0

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by yallop** [comment]
The build's [failing on 4.00.0](https://travis-ci.org/ocaml/opam-repository/jobs/221157351):

```
ocamlfind: _build/src/*.cmt: No such file or directory
```

**Comment by UnixJunkie** [comment]
It's the install that is failing, thanks for the heads up.

**Comment by UnixJunkie** [comment]
batteries v2.6.0 was retagged

**Comment by UnixJunkie** [comment]
It's all green now.

**Comment by UnixJunkie** [comment]
This is still not visible with opam repo https://opam.ocaml.org.
Is there a problem with the update of this repository?

**Pull request merged**
