### PR TITLE
explicitly depend on camlp4 - https://github.com/mirleft/ocaml-tls/pull/253

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
hmm, opam-1.1 is not happy with this (it installs cstruct without camlp4 extensions) -- does the order of dependencies matter?

**Comment by hannesm** [comment]
doesn't seem to help... how do I specify in a way opam-1.1 is happy to depend on cstruct which uses camlp4 extensions?

**Comment by avsm** [comment]
could you rebase this against master? I think @altgr has now fixed the 1.1 rewriting scripts.

**Comment by hannesm** [comment]
cool, all green now!

**Pull request merged**
