### PR TITLE
Add alpine support to conf-mysql

### PR DESCRIPTION
**Pull request by hcarty**
For a happier depext experience when building in Docker.

### CODE REVIEW

**Comment by hcarty** [comment]
The CentOS 7 problem is unrelated to this PR.

**Comment by avsm** [comment]
The other depexts are for mysql -- should this be `mysql-client` for alpine as well?

**Comment by hcarty** [comment]
Alpine has switched from mysql to mariadb - the only mysql packages seem to be transition packages so it seemed safer to point to the mariadb dev package. The mariadb C API is compatible with mysql's.

**Comment by avsm** [comment]
thanks!

**Comment by hcarty** [comment]
Thank you too!  Sorry for the mysql/mariadb confusion.

**Pull request merged**
