### PR TITLE
added packages/batteries/batteries.2.10.0

### PR DESCRIPTION
**Pull request by UnixJunkie**
I will issue a new tag if tests look good.

### CODE REVIEW

**Comment by gasche** [comment]
Here are some revdeps I have looked at from [the current RevDeps logs](https://ci.ocaml.org/ocaml/opam-repository/pr/14695?test=2%20Revdeps), starting from the end of the list:

- [profound](https://ci.ocaml.org/log/saved/docker-run-d235ee5141b533897f8f213e4ae5693a/22434a928b000d5aa1079046c46328f5d5e8a297): fails because of deprecated Pervasives, not our fault
- [orxgboost](https://ci.ocaml.org/log/saved/docker-run-205bc49d8331340d2db9e4357bac3460/3ed558ebbec38b580ce141f04bbded0b71d2db6b) fails for unknown reasons related to the R language, almost sure it's not our fault
- obandit from [1.38](https://ci.ocaml.org/log/saved/docker-run-909ae97b7a3f9e57582c74d264810557/a35753b2bf25d7999f7f27d362caccc8bae94998) to [0.2.1](https://ci.ocaml.org/log/saved/docker-run-d4b800764cd00a7ed29ca53eb4c870c8/6c67843122c62ae699bb047c6d98d1456e1eaa86): fails because the download URL changed; not our fault, but someone should fix this in the opam-repository
- molenc from [1.0.0](https://ci.ocaml.org/log/saved/docker-run-c984d42b37b95763067a363a985341eb/31b020e674f5e098b208deabc94b4ad06bac664d) to [2.0.0](https://ci.ocaml.org/log/saved/docker-run-c4c04b563ee34b9130afe01ee6aeac3a/4c02cff8928cbb75ce1281545fdfe10b2b73319e): fails in conf-rdkit (the depext is not installed in the CI, I guess), not our fault
- [lilis.0.1.3](https://ci.ocaml.org/log/saved/docker-run-5f3ee189c787fbf2cda747777f2701e0/53e7f0f9b170c4143d2711cc500fea2452582568): fails because of immutable string; someone should add a `base-unsafe-string` dependency in the opam-repository

**Comment by UnixJunkie** [comment]
Thanks for the detailed analysis.

**Comment by mseri** [comment]
Thanks for the triage. I’ll merge and deal with the independent fixes later

**Comment by gasche** [comment]
Thanks! I apologize for not saying this more clearly, but I wasn't finished triaging -- I only did about a quarter of the revdeps before breakfast. I think that this is fine -- I don't really expect failures due to revdeps but it would be nice to finish revdepping and improve the opam-repository state.

@UnixJunkie: next time, feel free to use the "draft pull request" feature to make it clear that the PR should not be merged right away.

**Comment by mseri** [comment]
@gasche sorry about that. Please let me know if ai need to revert it, of if there are other fixes I can add to the PR to fix some of the packages above

**Comment by gasche** [comment]
I think this is mostly a happy accident, and there is no need for reverting.

**Comment by mseri** [comment]
@freuk are the old release tarballs of obandit available somewhere? 0.2.1 has two tags on github  (0.2.1 and 0.2.1-zenodo) while the others none

**Comment by gasche** [comment]
More revdeps:

- [grip](https://ci.ocaml.org/log/saved/docker-run-5c165a48a190c07199b627a10f6036f2/e45e7367289a6e877e94d86a640aa65b60678825) fails because some depexts cannot be installed; (the depexts may have gotten out of date?)
- [get-line.2.1.0](https://ci.ocaml.org/log/saved/docker-run-655a58f8dd5aea710efe59b76c17b4c2/d62c586ee5bd4df7cdb0642137df3a3f35819b97) has a configure-time error, which I guess is fixed in 2.1.1; I think 2.1.0 could be disabled from the repository (`available: [false]`).

**Pull request merged**
