### PR TITLE
rankers.2.0.7: try weakening dolog version constraint

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by mseri** [comment]
I think we need to fix molenc 5.0.0 bounds:
```
#=== ERROR while compiling molenc.5.0.0 =======================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.04.2 | file:///home/opam/opam-repository
# path                 ~/.opam/4.04/.opam-switch/build/molenc.5.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p molenc -j 31
# exit-code            1
# env-file             ~/.opam/log/molenc-7-e48e36.env
# output-file          ~/.opam/log/molenc-7-e48e36.out
### output ###
#       ocamlc src/.molenc.objs/byte/molenc__Norm.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.04/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.molenc.objs/byte -I /home/opam/.opam/4.04/lib/batteries -I /home/opam/.opam/4.04/lib/bst -I /home/opam/.opam/4.04/lib/bytes -I /home/opam/.opam/4.04/lib/dolog -I /home/opam/.opam/4.04/lib/num -I /home/opam/.opam/4.04/lib/ocaml/threads -no-alias-deps -open Molenc -o src/.molenc.objs/byte/molenc__Norm.cmo -c -impl src/norm.ml)
# File "src/norm.ml", line 4, characters 16-26:
# Error: Unbound module BatMap.Int
#       ocamlc src/.molenc.objs/byte/molenc__Node.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.04/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.molenc.objs/byte -I /home/opam/.opam/4.04/lib/batteries -I /home/opam/.opam/4.04/lib/bst -I /home/opam/.opam/4.04/lib/bytes -I /home/opam/.opam/4.04/lib/dolog -I /home/opam/.opam/4.04/lib/num -I /home/opam/.opam/4.04/lib/ocaml/threads -no-alias-deps -open Molenc -o src/.molenc.objs/byte/molenc__Node.cmo -c -impl src/node.ml)
# File "src/node.ml", line 9, characters 16-26:
# Error: Unbound module BatSet.Int
#       ocamlc src/.molenc.objs/byte/molenc__Utls.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.04/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.molenc.objs/byte -I /home/opam/.opam/4.04/lib/batteries -I /home/opam/.opam/4.04/lib/bst -I /home/opam/.opam/4.04/lib/bytes -I /home/opam/.opam/4.04/lib/dolog -I /home/opam/.opam/4.04/lib/num -I /home/opam/.opam/4.04/lib/ocaml/threads -no-alias-deps -open Molenc -o src/.molenc.objs/byte/molenc__Utls.cmo -c -impl src/utls.ml)
# File "src/utls.ml", line 259, characters 16-30:
# Error: Unbound value BatString.chop
# Hint: Did you mean lchop or rchop?
```
Can be done separately

**Comment by UnixJunkie** [comment]
I have to release in opam a new version of molenc by the way, so I'll have a look.

**Comment by mseri** [comment]
Do you by chance know which lower bound needs fixing for
```

#=== ERROR while compiling molenc.5.0.0 =======================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.04.2 | file:///home/opam/opam-repository
# path                 ~/.opam/4.04/.opam-switch/build/molenc.5.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p molenc -j 31
# exit-code            1
# env-file             ~/.opam/log/molenc-7-82ad3e.env
# output-file          ~/.opam/log/molenc-7-82ad3e.out
### output ###
#       ocamlc src/.encoder.eobjs/byte/butina.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.04/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.encoder.eobjs/byte -I /home/opam/.opam/4.04/lib/batteries -I /home/opam/.opam/4.04/lib/bst -I /home/opam/.opam/4.04/lib/bytes -I /home/opam/.opam/4.04/lib/dolog -I /home/opam/.opam/4.04/lib/minicli -I /home/opam/.opam/4.04/lib/num -I /home/opam/.opam/4.04/lib/ocaml/threads -I /home/opam/.opam/4.04/lib/parmap -I src/.molenc.objs/byte -I src/.molenc.objs/native -no-alias-deps -o src/.encoder.eobjs/byte/butina.cmo -c -impl src/butina.ml)
# File "src/butina.ml", line 70, characters 4-17:
# Error: This function has type ('a -> 'b) -> 'a list -> ?ncores:int -> 'b list
#        It is applied to too many arguments; maybe you forgot a `;'.
```

**Comment by mseri** [comment]
I'll merge this, we can fix molenc 5 separately

**Comment by UnixJunkie** [comment]
I'll have a look. Apparently, molenc 5 needs a version constraint for parany.

**Pull request merged**
