### PR TITLE
add missing conf flag for ocaml

### PR DESCRIPTION
**Pull request by zapashcanon**
:)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
For this particular package, this is debatable given this is basically a meta-package here to abstract over `ocaml-base-compiler` and `ocaml-variants`. It has no `url` and thus `opam pin ocaml --dev` would give the wrong result.

**Comment by zapashcanon** [comment]
Shouldn't we add a flag like `compiler` or something to the package then ? I'd like to be able to filter out this kind of package easily and without hard-coding them.

**Comment by kit-ty-kate** [comment]
> Shouldn't we add a flag like `compiler` or something to the package then ?

no, `compiler` isn't the right flag for this. `conf` could be ok though. @rjbou @dra27  ?

**Comment by zapashcanon** [comment]
Yes, conf would be OK for me (I already filter them out :-)).

**Comment by rjbou** [comment]
Yes indeed, it fits `conf` requirements.

**Comment by dra27** [comment]
Ideally no dev-repo for this package and _definitely_ not pointing to ocaml/ocaml, please 🙂

**Comment by dra27** [comment]
In case you have one in the pipeline, please don't open a PR for ocaml-base-compiler or ocaml-variants - there's work in progress on the pinning workflow for the compiler which upstream changes as well (discussed back in March, I just haven't got to it yet)

**Comment by zapashcanon** [comment]
@kit-ty-kate I usef `flag: conf` everywhere, OK for you ?

**Comment by dra27** [comment]
This just needs similar updates to ocaml.4.12.2, ocaml.4.13.1, ocaml.4.13.2, ocaml.5.00.0 and I think it's good to go, thanks!

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
