### PR TITLE
Package foxes.1.0.0

### PR DESCRIPTION
**Pull request by AMTitan**
### `foxes.1.0.0`
An API for all your fox image needs
An API for all your fox image needs

---
* Homepage: https://github.com/Foxes-cool/Foxes-Ocaml
* Source repo: git+https://github.com/Foxes-cool/Foxes-Ocaml.git
* Bug tracker: https://github.com/Foxes-cool/Foxes-Ocaml/issues

---
:camel: Pull-request generated by opam-publish v2.2.0

### CODE REVIEW

**Comment by yawaramin** [comment]
Sorry to be a downer, but do we really want a library in opam to get URLs of fox images from a specific website? Seems like this could be a GitHub Gist...

**Comment by AMTitan** [comment]
I mean, technically, no, but the main advantage of Opam is the version control. It would also be nice for users to be able to know if the version of the installed API is out of date.

**Comment by raphael-proust** [comment]
An alternative is to host your own opam repository. Essentially a repository like this one which has a `packages/` directory with the structure that opam expect from it.

Then the package becomes available to users after they add your own repository as sources that opam can pick from:
```
opam repository set-url <name> <git-url>
```

It's not as good for discoverability (without the repository-adding command, `opam search` won't show the result), but it's nice for the other aspects of package management (e.g., for users to be able to ensure that a specific version is installed).

**Comment by AMTitan** [comment]
@kit-ty-kate When I do the `opam repository add ...` and `opam install foxes`, is there anything else I have to do? Opam says the library is installed but dune does not believe so.

**Comment by kit-ty-kate** [comment]
Your package does not install anything: https://github.com/Foxes-cool/Foxes-Ocaml/blob/main/lib/dune

You need to use `(public_name foxes)` instead of `(name foxes)` if you want it to be available outside your project directory/installed

**Pull request closed without merging**
