### PR TITLE
Package smbc.0.5

### PR DESCRIPTION
**Pull request by c-cube**
### `smbc.0.5`
Experimental model finder/SMT solver for functional programming

---
* Homepage: https://github.com/c-cube/smbc
* Source repo: git+https://github.com/c-cube/smbc.git
* Bug tracker: https://github.com/c-cube/smbc/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by mseri** [comment]
Thanks. It’s the usual suspect

**Comment by mseri** [comment]
Arg. I merged sithout a description. I’ll send a PR asap

**Comment by mseri** [comment]
Oh no it’s fine. There is the synopsis!

**Comment by c-cube** [comment]
Thank you! :)

**Pull request merged**
