### PR TITLE
[new release] dune (15 packages) (3.14.1)

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
Fast, portable, and opinionated build system

- Project page: <a href="https://github.com/ocaml/dune">https://github.com/ocaml/dune</a>
- Documentation: <a href="https://dune.readthedocs.io/">https://dune.readthedocs.io/</a>

### Fixed

- When a directory is changed to a file, correctly remove it in subsequent
  `dune build` runs. (ocaml/dune#9327, fix ocaml/dune#6575, @emillon)

- Fix a problem with the doc-new target where transitive dependencies were
  missed during compile. This leads to missing expansions in the output docs.
  (ocaml/dune#9955, @jonludlam)

- coq: fix performance regression in coqdep unescaping (ocaml/dune#10115, fixes ocaml/dune#10088,
  @ejgallego, thanks to Dan Christensen for the report)

- coq: memoize coqdep parsing, this will reduce build times for Coq users, in
  particular for those with many .v files (ocaml/dune#10116, @ejgallego, see also ocaml/dune#10088)

- on Windows, use an unicode-aware version of `CreateProcess` to avoid crashes
  when paths contains non-ascii characters. (ocaml/dune#10212, fixes ocaml/dune#10180, @emillon)

### CODE REVIEW

**Comment by emillon** [comment]
this release doesn't work on alpine, we'll push a fix in 3.14.2. we can leave CI run on this one, but I'm not sure what's best for 3.14.1 after. We can either not merge it, make it available: false or unavailable on alpine. I'll let the opam-repository maintainers decide.

**Comment by Leonidas-from-XIV** [comment]
Switching it to draft in the meantime to signal it shouldn't be merged as-is.

**Comment by Leonidas-from-XIV** [comment]
To add to @emillon's comment: I am pretty sure it doesn't work on any musl-based systems nor does it work on FreeBSD according to CI (for the same reason), so it is more dependent on the libc than the OS which makes it hard to exclude specific OSes.

**Comment by emillon** [comment]
One regression here, the musl one. It's being fixed in an upcoming 3.14.2.
Opam-repository maintainers, what do you want to do with 3.14.1? Should we merge it as `available: false` or close this PR?

**Comment by Leonidas-from-XIV** [comment]
#25474 created which comes with a fix for this regression.

**Comment by mseri** [comment]
I think it is easier to just close this PR since 3.14.2 is already released and this would be unavailable anyway

**Pull request closed without merging**
