### PR TITLE
liquidsoap.1.3.3, cry.0.6.0 and a couple depext for freebsd.

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by toots** [comment]
Okay guys, I've updated all the packages that I have control over upstream to build with `4.06` but there isn't much more that I can. Same with the `flambda` build bug with `mm` and `4.02`. Hope y'all can merge soon! :-)

**Comment by gasche** [comment]
Merged. There is one think you can do regarding 4.06 compatibility, which is to gently pressure your dependencies into fixing their own stuff. The sexplib already know, so I went to look at the Camomile situation, and it appears that [a release has been made](https://github.com/yoriyuki/Camomile/pull/36) but apparently it hasn't reached opam yet.

**Comment by gasche** [comment]
@toots, I think that `[compiler != "4.04.2_flambda"]` is a typo and that you should have used `4.04.2+flambda` instead -- I didn't notice at the time that the CI should not have a build failure if you explicitly marked the package incompatible. Do I remember correctly that the CI did in fact try to build the package using 4.04.2+flambda, and failed? If so, would you send another PR to fix the typo (we could check that the CI behaves in a better way then?). Sorry for the noise.

**Comment by toots** [comment]
I think it did fail with it too. Let me push a PR.

**Comment by toots** [comment]
#10496

**Comment by toots** [comment]
@gasche Looks like it worked!

**Pull request merged**
