### PR TITLE
Add z3 fix by removing the requirement for `python3-distutils`.

### PR DESCRIPTION
**Pull request by arbipher**
The PR is for #25807.
Let me see whether CI is happy about this.

### CODE REVIEW

**Comment by arbipher** [comment]
I checked the CI and archlinux [installs](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/e05964b65435483360215ad74811d32b963d7447/variant/distributions,archlinux-ocaml-5.2,z3.4.13.0-1) on Python 3.12 and it's satisfied. The current Debian or Ubuntu or others all runs from 3.9 to 3.11 according to `conf-python-3.9.0.0`.

p.s. I am also working on porting building ocaml-z3 from the python script to CMake. however, it may takes a few days and may be unstable in the beginning. The change for this PR is very small.

**Comment by Kakadu** [comment]
This changes look like they are not related to the topic of the PR. I actually expected something more straightforward, for example 

```diff
--- a/packages/z3/z3.4.13.0/opam
+++ b/packages/z3/z3.4.13.0/opam
@@ -6,7 +6,7 @@ bug-reports: "https://github.com/Z3prover/z3/issues"
license: "MIT"
dev-repo: "git+https://github.com/Z3prover/z3.git"
depexts: [
-  ["python3-distutils"] {os-family = "debian"}
+  ["python3-distutils"] {os-family = "debian" & !(os-distribution="ubuntu" & os-version>="24.04")}
]
patches: [
"libatomic.patch"
```

**Comment by arbipher** [comment]
The change on github is not showing my change comparing to the previous version of z3.4.13.0.

I just delete the requirement for `python3-distutils`.

```diff
Common subdirectories: packages/z3/z3.4.13.0-1/files and packages/z3/z3.4.13.0/files
diff '--color=auto' packages/z3/z3.4.13.0-1/opam packages/z3/z3.4.13.0/opam
7a8,10
> depexts: [
>   ["python3-distutils"] {os-family = "debian"}
> ]
```

I also asked on https://github.com/Z3Prover/z3/issues/7228 because the file path `z3/src/api/python/setup.py` (where `distutils` appears) is for Python API. It should be harmless to delete it for us.

**Comment by mseri** [comment]
Looks all right, thanks and sorry for the delay

**Pull request merged**
