### PR TITLE
vhd-format-*: release 0.9.2

### PR DESCRIPTION
**Pull request by mseri**
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

### CODE REVIEW

**Comment by jpdeplaix** [comment]
There is an issue with OCaml 4.06.1:
```
#=== ERROR while installing vhd-format-lwt.0.9.2 ==============================#
# opam-version 1.2.2
# os           linux
# command      jbuilder runtest -p vhd-format-lwt -j 4
# path         /home/travis/.opam/4.06.1/build/vhd-format-lwt.0.9.2
# compiler     4.06.1
# exit-code    1
# env-file     /home/travis/.opam/4.06.1/build/vhd-format-lwt.0.9.2/vhd-format-lwt-21000-477f54.env
# stdout-file  /home/travis/.opam/4.06.1/build/vhd-format-lwt.0.9.2/vhd-format-lwt-21000-477f54.out
# stderr-file  /home/travis/.opam/4.06.1/build/vhd-format-lwt.0.9.2/vhd-format-lwt-21000-477f54.err
### stderr ###
# Warning: This field is useless without a (public_name ...) field.
# [...]
#          ppx vhd_format_lwt_test/parse_test.pp.ml
#     ocamldep vhd_format_lwt_test/parse_test.depends.ocamldep-output
#          ppx disk/disk.pp.ml
#     ocamldep disk/disk.depends.ocamldep-output
#       ocamlc disk/disk.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/travis/.opam/4.06.1/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/travis/.opam/4.06.1/lib/bytes -I /home/travis/.opam/4.06.1/lib/cstruct -I /home/travis/.opam/4.06.1/lib/lwt -I /home/travis/.opam/4.06.1/lib/ocaml -I /home/travis/.opam/4.06.1/lib/ocaml/threads -I /home/travis/.opam/4.06.1/lib/result -I /home/travis/.opam/4.06.1/lib/sexplib -I /home/travis/.opam/4.06.1/lib/sexplib/0 -no-alias-deps -I disk -o disk/disk.cmo -c -impl disk/disk.pp.ml)
# File "disk/disk.ml", line 41, characters 35-38:
# Error: This expression has type string but an expression was expected of type
#          bytes
```

**Comment by mseri** [comment]
Mmh, I think I'll have to add a constraint on that. I don't think this has been `safe-string`ed yet.

**Comment by mseri** [comment]
Apologies for the time it took. This should fix it for the moment. The next version will be using safe-string.

**Comment by jpdeplaix** [comment]
No worries. Thanks a lot !

**Pull request merged**
