### PR TITLE
[new release] mirage-crypto-pk, mirage-crypto, mirage-crypto-rng and mirage-crypto-rng-mirage (0.8.0)

### PR DESCRIPTION
**Pull request by hannesm**
CHANGES:

* New package mirage-crypto-rng-mirage which contains the entropy collection
  code for MirageOS (mirage/mirage-crypto#69 requested by @samoht, implemented by @hannesm)
* Mirage_crypto_rng_lwt.initialize is not inside the Lwt monad anymore, and
  thus can be called by libraries at top level (mirage/mirage-crypto#69, requested by @avsm @xguerin
  @talex5 in mirage/ocaml-conduit#318, implemented by @hannesm)
* Both Mirage_crypto_rng_lwt.initialize and Mirage_crypto_rng_unix.initialize
  don't do anything if called a second time (mirage/mirage-crypto#69, implemented by @hannesm)
* Entropy source registration is now open and done via
  `Entropy.register_source : string -> source`, instead of a closed variant
  (mirage/mirage-crypto#69, fixes mirage/mirage-crypto#68, implemented by @hannesm)

### CODE REVIEW

**Comment by hannesm** [comment]
I don't quite understand Camelus assessment: "broken package mirage-crypto-rng-mirage". Anyone has any hints how Camelus came to that statement?

**Comment by hannesm** [comment]
ah, I figured that out -- it depends on mirage-crypto-rng =version and mirage-runtime >= 3.7.0 -- but all released mirage-runtime conflict with mirage-crypto-rng <= 0.8.0. This will be fixed with a subsequent release of mirage-runtime. the conflict is intentional since mirage <= 3.7.7 emits a dependency on (the no longer existing) mirage-crypto-rng.mirage.

**Comment by hannesm** [comment]
NB: please do not merge yet, I plan to revise / reorganize the conflicts and dependencies.

**Comment by hannesm** [comment]
I did the changes I intended, this is ready from my side.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
