### PR TITLE
New package version why3 0.86, for the corresponding new why3 release

### PR DESCRIPTION
**Pull request by claudemarche**
These commits also make a few minor changes in the descriptions of the packages for previous version why3-base and why3

### CODE REVIEW

**Comment by claudemarche** [comment]
First build failed because there is a new mandatory dependency on menhir. Retrying...

**Comment by claudemarche** [comment]
The error in the last Travis build is not related to why3. Please could you pull the commits in the master branch anyway?

**Comment by dsheets** [comment]
All green now but it looks like there is an issue on OS X <https://travis-ci.org/ocaml/opam-repository/jobs/62185347>.

**Comment by samoht** [comment]
@dsheets yes, homebrew doesn't install `gtksourceview`'s `pkg` configuration file at the right place. There is a note in the post-message on that package about that, though, so that's more or less fine.

**Pull request merged**
