### PR TITLE
2 packages from cryptosense/ocaml-mock at 0.1.1

### PR DESCRIPTION
**Pull request by bbc2**
This pull-request concerns:
-`mock.0.1.1`: Configurable functions to test impure code
-`mock-ounit.0.1.1`: OUnit wrapper for OCaml mock

---
* Homepage: https://github.com/cryptosense/ocaml-mock
* Source repo: git+https://github.com/cryptosense/ocaml-mock.git
* Bug tracker: https://github.com/cryptosense/ocaml-mock/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The tests for `mock-ounit` fails with OCaml < 4.04:
```
#=== ERROR while compiling mock-ounit.0.1.1 ===================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/cryptosense/ocaml-mock/archive/0.1.1.tar.gz)
# path                 ~/.opam/4.03/.opam-switch/build/mock-ounit.0.1.1
# command              ~/.opam/4.03/bin/dune runtest -p mock-ounit -j 2
# exit-code            1
# env-file             ~/.opam/log/mock-ounit-29-e05db4.env
# output-file          ~/.opam/log/mock-ounit-29-e05db4.out
### output ###
#          ppx tests/test_suite.pp.ml (exit 1)
# (cd _build/default && .ppx/30a18adec0a1407675322d723bf1b0ae/ppx.exe -o tests/test_suite.pp.ml --impl tests/test_suite.ml --dump-ast)
# File "tests/test_suite.ml", line 68, characters 37-39:
# Error: Syntax error
```

**Comment by kit-ty-kate** [comment]
In general it is also a good idea to explicitly list `"ocaml"` in the dependencies.

**Comment by bbc2** [comment]
I think I've fixed the issues you found.  The package should be ready now.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
