### PR TITLE
ocaml-lua.1.3

### PR DESCRIPTION
**Pull request by pdonadeo**

### CODE REVIEW

**Comment by dsheets** [comment]
```
[WARNING] Directory /home/travis/.opam/system/doc/ocaml-lua is not empty, not
          removing
```

Is it possible to make a clean uninstall?

**Comment by pdonadeo** [comment]
@dsheets yes, of course.

**Comment by dsheets** [comment]
Thanks!

I was wondering why the package is Linux-only for 1.3 as the `post_conf.ml` file seems to have some pieces for OS X so I made <https://github.com/pdonadeo/ocaml-lua/pull/9> which seems to at least build with homebrew `lua51`. I hope it can support OS X, soon! :-)

**Comment by pdonadeo** [comment]
The problem is that, at that time, I had a Mac, so I was able to compile and test the library on OSX. Now I don't have anymore an OSX, so I restricted 1.3 to Linux only but... only because I can't test it.

Did you tried to compile for OSX? The patch you just submitted is working?

**Comment by pdonadeo** [comment]
I mean: is the patch working, at least On Your Computer? © ® :-D

**Comment by dsheets** [comment]
Yes, I have successfully compiled on OS X 10.11.6 with pdonadeo/ocaml-lua#9 and homebrew's `lua51` package.

**Pull request merged**
