### PR TITLE
opass: add upper bound on core; fix opam-lint problems

### PR DESCRIPTION
**Pull request by damiendoligez**
cc @orbitz @mmatalka : please check the information I added in the `authors`, `homepage`, and `bug-reports` fields.

### CODE REVIEW

**Comment by orbitz** [comment]
@damiendoligez The information looks good.  This still seems to be failing, is there more things missing?

**Comment by samoht** [comment]
@orbitz seems to be a missing dependency to sexplib and camlp4:

```
#=== ERROR while installing opass.1.0.0 =======================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/system/build/opass.1.0.0
# compiler     system (4.02.3)
# exit-code    2
# env-file     /home/travis/.opam/system/build/opass.1.0.0/opass-495-df3644.env
# stdout-file  /home/travis/.opam/system/build/opass.1.0.0/opass-495-df3644.out
# stderr-file  /home/travis/.opam/system/build/opass.1.0.0/opass-495-df3644.err
### stdout ###
# ocamlfind ocamlc -thread -I +camlp4 -package core  -c \
# [...]
# ocamlfind ocamlc -pack -o editable.cmo entry.cmo form.cmo engine.cmo
# ocamlfind ocamlc -package core -custom -a -thread -I +camlp4 -o editable.cma editable.cmo
# make[3]: Leaving directory `/home/travis/.opam/system/build/opass.1.0.0/lib/editable'
# make -C db .d
# make[3]: Entering directory `/home/travis/.opam/system/build/opass.1.0.0/lib/db'
# ocamlfind ocamldep -package core,sexplib,sexplib.syntax -syntax camlp4o  db.ml  db.mli > .d
# make[3]: Leaving directory `/home/travis/.opam/system/build/opass.1.0.0/lib/db'
# make[2]: Leaving directory `/home/travis/.opam/system/build/opass.1.0.0/lib'
# make[1]: Leaving directory `/home/travis/.opam/system/build/opass.1.0.0'
### stderr ###
# ocamlfind: Package `sexplib.syntax' not found
# make[3]: *** No rule to make target `.d'.  Stop.
# make[2]: *** [db] Error 2
# make[1]: *** [all_trampoline] Error 2
# make: *** [all] Error 2
```

**Comment by avsm** [comment]
ive added some fixes to this in #6069, currently running a bulk build to test

**Comment by damiendoligez** [comment]
I just gave up on `opass.1.0.0` because of this problem:
```
# ocamlfind ocamlopt -thread -I +camlp4 -for-pack ueditable -package core  -c \
# 	entry.ml
[...]
# ocamlfind ocamlopt -pack -o editable.cmx entry.cmx form.cmx engine.cmx
### stderr ###
# File "editable.cmx", line 1:
# Error: File entry.cmx
# was not compiled with the `-for-pack Editable' option
```
I don't see how it could have ever worked (compiling with `-for-pack` with some module name, then packing with another name) and I don't have the time to investigate older versions of OCaml.

**Comment by orbitz** [comment]
@damiendoligez thanks for trying, but it's probably not worth having any of these older versions around anyways.  I've just opened a PR for the latest version with a nice lint-passing opam package.

https://github.com/ocaml/opam-repository/pull/6078

**Pull request closed without merging**
