### PR TITLE
+ snappy 0.1.1

### PR DESCRIPTION
**Pull request by ygrek**

### CODE REVIEW

**Comment by gasche** [comment]
The Travis build failures look as follows:

```
[snappy: ocaml setup.ml] Command started
+ ocaml "setup.ml" "-test" (CWD=/home/travis/.opam/system/build/snappy.0.1.1)
- E: Field 'test' is not set: Field 'test' is not set: Executable 'test' not yet built.
[ERROR] The compilation of snappy failed at "ocaml setup.ml -test".
```

I wonder if https://github.com/ygrek/ocaml-snappy/commit/5e347dfa062769460d1bc3dcb74739efd8b41a1b is the cause.

**Comment by ygrek** [comment]
Thanks, fixed hopefully

**Comment by ygrek** [comment]
OSX build fails because OSX
```
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found
```

**Comment by ygrek** [comment]
ping?

**Comment by gasche** [comment]
Thanks for the ping, merged.

**Pull request merged**
