### PR TITLE
containers.1.2 - via opam-publish

### PR DESCRIPTION
**Pull request by c-cube**
A modular, clean and powerful extension of the OCaml standard library.

Containers is an extension of OCaml's standard library (under BSD license)
focused on data structures, combinators and iterators, without dependencies on
unix, str or num. Every module is independent and is prefixed with 'CC' in the
global namespace. Some modules extend the stdlib (e.g. CCList provides safe
map/fold_right/append, and additional functions on lists).
Alternatively, `open Containers` will bring enhanced versions of the standard
modules into scope.

It also features sub-libraries for dealing with threads, S-expressions,
and the intricacies of unix.

---
* Homepage: https://github.com/c-cube/ocaml-containers/
* Source repo: https://github.com/c-cube/ocaml-containers.git
* Bug tracker: https://github.com/c-cube/ocaml-containers/issues/

---

Pull-request generated by opam-publish v0.3.3

### CODE REVIEW

**Comment by avsm** [comment]
zipperpositions.1.2. may need an upper bound;

```
# + /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -no-alias-deps -I src/core -I src/core/lib -I src/parsers -w +a-4-42-44-48-50-58-32-60@8 -color always -package zarith -package unix -package tip_parser -package sequence -package oclock -package containers.data -package containers -package bytes -package msat -I src/prover -I src/core -I src/core/lib -I src/parsers -I src/prover/calculi -I src/prover/lib -o src/prover/selection.cmo src/prover/selection.ml
# File "src/prover/selection.ml", line 58, characters 16-17:
# Error: This expression has type int option
#        but an expression was expected of type int
# Command exited with code 2.
```

**Comment by c-cube** [comment]
Yes indeed. I've changed a few signatures in the bitvectors library. Can you do it? :-)

**Comment by avsm** [comment]
It would be easier if you could add the upper bounds to zipperposition as an additional push to this PR, and then the whole thing will go green and be tested in one go.

**Comment by c-cube** [comment]
it is done.

**Comment by c-cube** [comment]
The error for zipperposition1.0 can be ignored, I think

**Comment by c-cube** [comment]
Been fixed, actually.

**Comment by avsm** [comment]
thanks!

**Pull request merged**
