### PR TITLE
[new release] gpt (1.0.0)

### PR DESCRIPTION
**Pull request by reynir**
A library to manipulate GUID Partition tables

- Project page: <a href="https://github.com/mirage/ocaml-gpt">https://github.com/mirage/ocaml-gpt</a>
- Documentation: <a href="https://mirage.github.io/ocaml-gpt/">https://mirage.github.io/ocaml-gpt/</a>

##### CHANGES:

* Initial release of `gpt.

### CODE REVIEW

**Comment by reynir** [comment]
CI seems to be having a bad day: https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/ce9b6f04d7ea6dcef762cfbe6ed26a8471091b1a
```
2024-02-16 14:30.48: New job: Analyse
2024-02-16 14:30.48: Checking out commit ce9b6f04. To reproduce:
                       git clone --recursive "https://github.com/ocaml/opam-repository.git" && cd "opam-repository" && git fetch origin "refs/pull/25270/head" && git reset --hard ce9b6f04
2024-02-16 14:30.48: Exec: "cp" "-a" "--" "/var/lib/ocurrent/var/git/opam-repository.git-a0bc4b41ddb868605dc1500002c27cfa79faf4389fe53b6754817ea16b48d458/.git" 
                           "/tmp/git-checkout229cefb5"
2024-02-16 14:30.51: Exec: "git" "-C" "/tmp/git-checkout229cefb5" "submodule" 
                           "deinit" "--force" "--all"
2024-02-16 14:30.54: Exec: "git" "-C" "/tmp/git-checkout229cefb5" "reset" 
                           "--hard" "-q" "ce9b6f04d7ea6dcef762cfbe6ed26a8471091b1a"
2024-02-16 14:30.58: Exec: "git" "-c" "protocol.file.allow=always" "-C" 
                           "/tmp/git-checkout229cefb5" "submodule" "update" 
                           "--recursive" "--init" "--no-fetch"
2024-02-16 14:30.58: Exec: "git" "merge" "-q" "--" "1bb24f52ef5c395ad7f49bb07ea82397a93389b6"
2024-02-16 14:30.59: Exec: "git" "diff" "--name-only" "1bb24f52ef5c395ad7f49bb07ea82397a93389b6"
2024-02-16 14:31.00: Exec: "git" "show" "1bb24f52ef5c395ad7f49bb07ea82397a93389b6:packages/gpt/gpt.1.0.0/opam"
fatal: path 'packages/gpt/gpt.1.0.0/opam' exists on disk, but not in '1bb24f52ef5c395ad7f49bb07ea82397a93389b6'
2024-02-16 14:31.12: Job failed: OpamPp.Bad_format(_) -- Raised by primitive operation at Lwt_unix.read_bigarray.(fun) in file "src/unix/lwt_unix.cppo.ml", line 688, characters 8-59
Called from Lwt_unix.wrap_syscall.(fun) in file "src/unix/lwt_unix.cppo.ml", line 571, characters 17-28
```

**Comment by avsm** [comment]
Looks like a lower bound on ocplib-endian is also needed here.

**Comment by dinosaure** [comment]
Seems related to the `cppo` issue which does not recognize the `~` on OCaml 5.2~alpha1 (also found on `ppx_minidebug`). A PR is available here to fix it: https://github.com/ocaml/opam-repository/pull/25287.

**Comment by reynir** [comment]
The dependency on ocplib-endian seems to be through lwt which was a dependency of mbr-format until I removed the erroneous lwt dependency in mbr-format>=1.0.0 https://github.com/ocaml/opam-repository/pull/25285

**Pull request merged**
