### PR TITLE
new file:   packages/dolog/dolog.6.0.0/opam

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
If it breaks some packages, I will add a version constraint to them later.
I hope the CI tests will let me know.

**Comment by kit-ty-kate** [comment]
The only incompatible package that the CI could test is `lbvs_consent.2.1.1`

**Comment by UnixJunkie** [comment]
I just sent a separate PR to update the version constraint on dolog for packages that may be impacted by the API change.

**Comment by UnixJunkie** [comment]
maybe this one can be merged now

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml/opam-repository/pull/17870/files

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
