### PR TITLE
new release ocamlgraph 1.8.7

### PR DESCRIPTION
**Pull request by backtracking**
This is a new release of OCamlGraph.
--
Jean-Christophe

### CODE REVIEW

**Comment by avsm** [comment]
The `dose` package currently has a constraint `ocamlgraph = 1.8.6` -- should this be relaxed to `ocamlgraph >= 1.8.6` with this release?

**Comment by avsm** [comment]
1.8.7 is also incompatible with opam-lib due to the dose transitive dependency, cc @AltGr @rdicosmo @abate

**Comment by abate** [comment]
I guess we can relax the dependency for dose, I'm going to wait the debian package to come out and let you know.

**Comment by lefessan** [comment]
@backtracking : you have both an install rule (make install-findlib) that install graph.* files, and an ocamlgraph.install files that does the same. What's the reason for having both ?

**Comment by backtracking** [comment]
I don't remember. Now that you mention it, I see no reason for that.
Is it OK if I simply remove the ocamlgraph.install file?
--
Jean-Christophe

**Comment by lefessan** [comment]
Yes, you can choose the method you prefer. Could you update the PR ?

**Comment by backtracking** [comment]
I removed ocamlgraph.install and I'm making a pull request right now.

**Pull request closed without merging**
