### PR TITLE
new release of hashcons

### PR DESCRIPTION
**Pull request by backtracking**
thanks for merging this new release (which fixes a bug)

### CODE REVIEW

**Comment by samoht** [comment]
Did you add a `configure` file in the release archive?

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed conf-m4.1
∗  installed conf-pkg-config.1.0
∗  installed conf-which.1
∗  installed conf-ncurses.1
∗  installed ocamlfind.1.6.2
[ERROR] The compilation of hashcons failed at "./configure".
Processing  6/6: [hashcons: ocamlfind remove]
#=== ERROR while installing hashcons.1.2 ======================================#
# opam-version 1.2.2
# os           linux
# command      ./configure
# path         /home/travis/.opam/system/build/hashcons.1.2
# compiler     system (4.02.3)
# exit-code    127
# env-file     /home/travis/.opam/system/build/hashcons.1.2/hashcons-8638-d474c2.env
# stdout-file  /home/travis/.opam/system/build/hashcons.1.2/hashcons-8638-d474c2.out
# stderr-file  /home/travis/.opam/system/build/hashcons.1.2/hashcons-8638-d474c2.err
```

**Comment by backtracking** [comment]
No, I forgot, because I prepared the tarball on github this time and
configure is not under version control. Sorry for that.

I don't know what is best practice: Should I add "autoconf" to the list
of installation instructions, or should I add "configure" to the tarball?

--
Jean-Christophe

**Comment by samoht** [comment]
@backtracking both options work I think. If you want to depend on `autoconf`, you can add `conf-autoconf` to your `depends`, this will ensure that the right external dependencies are installed on most platforms.

**Comment by lefessan** [comment]
I think the good practice in general is to not depend on autoconf, i.e. autoconf should not be a build dependency, but a "dev" dependency (although OPAM does not have such a kind of dependency, so you should just not put autoconf as a dependency).

**Pull request merged**
