### PR TITLE
[package update] Strenghten dependencies constraints in Ortac packages

### PR DESCRIPTION
**Pull request by n-osborne**
This PR updates some dependencies constraints for some Ortac packages.

When an Ortac package depends on another Ortac package, make the constraints ask for the exact same version.
The reason why is that version 0.4.0 brings some breaking changes (see #26691) and we can't guarantee that it will be an isolate case.

Constraints on the Gospel package are also added, as the next release is expected to bring breaking changes.

### CODE REVIEW

**Review by jmid — COMMENTED** [review]
Overall, with the Ortac packages we are trying to make things work together within versions, while avoiding issues arising from cross-version combinations, like ortac-core.0.4 and ortac-qcheck-stm.0.4.

The changes LGTM for doing so!

I think there is also an occurrence in packages/ortac-core/ortac-core.0.3.0/opam that needs `= version` but then everything should be version-aligned AFAICS!
```
  "ortac-runtime" {with-test}
```

**Comment by n-osborne** [comment]
Good catch, I missed this one!

**Comment by jmid** [comment]
The `ppx_deriving.5.2.1` failure on `ocaml.5.3.0~alpha1` is unrelated.

I've just filed #26702 to add missing upper bounds to address it.

**Comment by jmid** [comment]
This is all green modulo the `ppx_deriving` issue fixed in #26702.
It should therefore be good to merge, so that #26691 can be rebased and rerun its CI tests :slightly_smiling_face:

**Comment by mseri** [comment]
Thanks

**Pull request merged**
