### PR TITLE
aws-elasticache.0.1.0 - via opam-publish

### PR DESCRIPTION
**Pull request by seliopou**
Amazon ElastiCache

---
* Homepage: https://github.com/inhabitedtype/ocaml-aws
* Source repo: https://github.com/inhabitedtype/ocaml-aws.git
* Bug tracker: https://github.com/inhabitedtype/ocaml-aws/issues

---
### opam-lint failures
- **WARNING** 97 long description unspecified

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by yallop** [comment]
Here's the error message from the [Travis build](https://travis-ci.org/ocaml/opam-repository/jobs/118877339):
```
# File "lib/errors.ml", line 1, characters 0-1905:
# Error: Two constructors are named InvalidParameterCombination
# Command exited with code 2.
```

**Comment by samoht** [comment]
ping @seliopou

**Comment by samoht** [comment]
ping ping @seliopou

**Comment by seliopou** [comment]
May be a while before I get to this, so closing for now.

**Pull request closed without merging**
