### PR TITLE
datakit-ci needs uri>=2.0

### PR DESCRIPTION
**Pull request by samoht**
See http://check.ocamllabs.io/4.03.0/bad/datakit-ci.0.12.2

### CODE REVIEW

**Comment by mseri** [comment]
I think it also needs an upper bound on yojson

```

#=== ERROR while compiling datakit-ci.0.12.2 ==================================#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.04.2 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-base-compiler.4.04.2/.opam-switch/build/datakit-ci.0.12.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune runtest ci/tests
# exit-code   1
# env-file    ~/.opam/log/datakit-ci-16962-1e4c87.env
# output-file ~/.opam/log/datakit-ci-16962-1e4c87.out
### output ###
#       ocamlc ci/src/.datakit_ci.objs/byte/cI_result.{cmi,cmti} (exit 2)
# (cd _build/default && /home/travis/.opam/ocaml-base-compiler.4.04.2/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I ci/src/.datakit_ci.objs/byte -I /home/travis/.opam/ocaml-base-compiler.4.04.2/lib/asetmap -I /home/travis/.opam/ocaml-base-compiler.4.04.2/lib/asn1-combinators -I /home/travis/.opam/ocaml-base-comp[...]
# File "ci/src/cI_result.mli", line 13, characters 26-43:
# Warning 3: deprecated: Yojson.Basic.json
# json types are being renamed and will be removed in the next Yojson major version. Use type t instead
# File "ci/src/cI_result.mli", line 14, characters 14-31:
# Warning 3: deprecated: Yojson.Basic.json
# json types are being renamed and will be removed in the next Yojson major version. Use type t instead
# File "ci/src/cI_result.mli", line 1:
# Error: Some fatal warnings were triggered (2 occurrences)
```

**Comment by avsm** [comment]
Woah, why are warnings fatal in a release build here?

**Comment by samoht** [comment]
Not sure why `dune runtest` have these warning enabled.

**Comment by samoht** [comment]
> I think it also needs an upper bound on yojson

I am not sure how to fix this as it's already using yojson 1.7.0 which is the last released version in opam :-/

**Comment by samoht** [comment]
Fixed the `dune runtest` command to not run in dev mode (thx to @rgrinberg for the tip)

**Comment by kit-ty-kate** [comment]
There is a missing dependency during testing:
```
- File "bridge/github/dune", line 5, characters 20-37:
- 5 |  (libraries rresult github-hooks-unix github-unix datakit-github
-                         ^^^^^^^^^^^^^^^^^
- Error: Library "github-hooks-unix" not found.
- Hint: try: dune external-lib-deps --missing -p datakit-ci @runtest
-       ocamlc ci/tests/.test_ci.eobjs/byte/test_utils.{cmi,cmo,cmt}
```

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
