### PR TITLE
libsvm.0.9.3: remove ocaml version upper bound

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
the files generated by oasis need to be refreshed for recent versions of ocaml: cf. https://bitbucket.org/ogu/libsvm-ocaml/issues/3/update-files-generated-from-_oasis

**Comment by UnixJunkie** [comment]
the maintainer of libsvm needs to do a new release

**Comment by UnixJunkie** [comment]
the maintainer of libsvm has to do that, not me.

**Comment by akabe** [comment]
@UnixJunkie OK. I will contact the maintainer.

**Comment by UnixJunkie** [comment]
@akabe I pushed a tentative fix. You are right, we can invoke oasis at build time via the opam file.
It adds a dependency to the libsvm opam package, but I see that many packages do that, so why not.

**Comment by akabe** [comment]
@UnixJunkie I agree. [This issue](https://bitbucket.org/ogu/libsvm-ocaml/issues/3/update-files-generated-from-_oasis) was opened a month ago, but I have no response from the author of libsvm.

**Comment by UnixJunkie** [comment]
I added a version constraint to oasis (linearily scanned by hand on my system). We should be good to go now, let's see what the CI tests will say.

**Comment by akabe** [comment]
`oasis setup` fails because `oasis` is not installed. `"oasis" {build & >= "0.4.7"}` line should be added to `depends`, not `depopts`.

However CI tests will not be passed due to lack of `depexts` packages for alpine, centos, and fedora. fedora repository has `libsvm-devel`, but alpine and centos repositories don't. For passing CI tests, we need to install libsvm.so via `opam depext`. I will create `conf-libsvm` package to fix this problem.

**Comment by UnixJunkie** [comment]
good catch, I updated the opam file. You are right about a conf-libsvm, such a package would be useful.

**Comment by UnixJunkie** [comment]
Some errors are due to the missing svm.h file.
This will be solved by the upcoming conf-libsvm package which is in another pull request.

One error is strange: /usr/bin/ld: final link failed: Nonrepresentable section on output
I have never seen that

**Comment by UnixJunkie** [comment]
superseded by https://github.com/ocaml/opam-repository/pull/10217

**Pull request closed without merging**
