### PR TITLE
Package based64.1.0

### PR DESCRIPTION
**Pull request by lucas-deangelis**
### `based64.1.0`
Bindings to https://github.com/aklomp/base64

---
* Homepage: https://github.com/tewonobasu/based64
* Source repo: git+https://github.com/tewonobasu/based64.git
* Bug tracker: https://github.com/tewonobasu/based64/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by lucas-deangelis** [comment]
I think I've fixed the problems on Fedora, Alpine and for lower bounds. Should I make a new pull request with a new version?

**Comment by dinosaure** [comment]
> Should I make a new pull request with a new version?

You can force-push on this PR with the new version to avoid a duplicate of PRs :+1:.

**Comment by kit-ty-kate** [comment]
ping @lucas-deangelis

**Comment by mseri** [comment]
This unfortunately still fails to link in many distributions:
```
#=== ERROR while compiling based64.1.0 ========================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.0 | pinned(https://github.com/tewonobasu/based64/archive/1.0.tar.gz)
# path                 ~/.opam/4.14/.opam-switch/build/based64.1.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p based64 -j 31 @install
# exit-code            1
# env-file             ~/.opam/log/based64-7-41493b.env
# output-file          ~/.opam/log/based64-7-41493b.out
### output ###
# File "lib/dune", line 33, characters 0-330:
# 33 | (rule
# 34 |  (deps
# 35 |   (source_tree libbase64))
# ....
# 44 |     (copy libbase64/lib/libbase64.a libbase64.a)
# 45 |     (copy libbase64/lib/libbase64.so dllbase64.so)
# 46 |     (copy libbase64/include/libbase64.h base64.h)))))
# (cd _build/default/lib/libbase64 && /usr/bin/make all)
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib  -o lib/arch/avx2/codec.o -c lib/arch/avx2/codec.c
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib -o lib/arch/generic/codec.o -c lib/arch/generic/codec.c
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib  -o lib/arch/neon32/codec.o -c lib/arch/neon32/codec.c
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib  -o lib/arch/neon64/codec.o -c lib/arch/neon64/codec.c
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib  -o lib/arch/ssse3/codec.o -c lib/arch/ssse3/codec.c
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib  -o lib/arch/sse41/codec.o -c lib/arch/sse41/codec.c
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib  -o lib/arch/sse42/codec.o -c lib/arch/sse42/codec.c
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib  -o lib/arch/avx/codec.o -c lib/arch/avx/codec.c
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib -o lib/lib.o -c lib/lib.c
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib -o lib/codec_choose.o -c lib/codec_choose.c
# cc -no-pie -std=c99 -O3 -pedantic -Wall -Wextra -Ilib -o lib/tables/tables.o -c lib/tables/tables.c
# ld -r -o lib/libbase64.o lib/arch/avx2/codec.o lib/arch/generic/codec.o lib/arch/neon32/codec.o lib/arch/neon64/codec.o lib/arch/ssse3/codec.o lib/arch/sse41/codec.o lib/arch/sse42/codec.o lib/arch/avx/codec.o lib/lib.o lib/codec_choose.o lib/tables/tables.o
# objcopy --keep-global-symbols=lib/exports.txt lib/libbase64.o
# ar crs lib/libbase64.a lib/libbase64.o
# gcc -no-pie -o lib/libbase64.so lib/libbase64.o -shared
# /usr/bin/ld: lib/libbase64.o: relocation R_X86_64_32S against `base64_table_enc_6bit' can not be used when making a shared object; recompile with -fPIC
# collect2: error: ld returned 1 exit status
# make: *** [Makefile:68: lib/libbase64.so] Error 1
```

**Comment by kit-ty-kate** [comment]
Closing due to inactivity. Feel free to reopen whenever it is ready

**Pull request closed without merging**
