### PR TITLE
using old omake

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
The failure of unmagic is fixed in the PR for omake.0.9.8.7.  The others fail at the prepartions of OS environments.

**Comment by samoht** [comment]
Can you rebase now that #10250 is merged? Thanks!

**Comment by camlspotter** [comment]
Pierre has renamed functions in Format. ;-(

**Comment by samoht** [comment]
All green, thanks for your efforts :-)

**Pull request merged**
