### PR TITLE
package CoqIDE 8.7.2

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by RalfJung** [comment]
CI fails to install `conf-m4`, seems unrelated to what this PR does:
https://ci.ocamllabs.io/log/saved/docker-build-1a648252061e36a144348a3d054f0997/118b913318ec62fd57133952a504e5930a332ba1

**Comment by maximedenes** [comment]
Any update?

**Comment by mseri** [comment]
I have seen the m4 failure in other packages, it's unrelated and I am not sure why it happens. The other failure is due to the lack of epel when trying to install gtksurceview2 in centos, also unrelated to this package.

The failure on OSX was unexpected, I have restarted the test to double check.

**Comment by RalfJung** [comment]
Seems like it worked now? https://travis-ci.org/ocaml/opam-repository/jobs/342982768

**Comment by hannesm** [comment]
thanks for your contribution!

**Pull request merged**
