### PR TITLE
Added ISO8601 package.

### PR DESCRIPTION
**Pull request by sagotch**

### CODE REVIEW

**Comment by avsm** [comment]
Very useful library! Any chance you could make this pass `opam lint`?  You need to add a few fields like `dev-repo` and so on.

**Comment by sagotch** [comment]
Never heard about opam lint before, but sure. Give me few minutes :+1:

**Comment by dsheets** [comment]
```
# File "src/ISO8601_lexer.mll", line 20, characters 4-6:
# Error: Unbound value |>
```

**Comment by sagotch** [comment]
Waiting for travis-ci, but `opam` file should be ok, and 3.12.1 compatibilty restored.

**Comment by sagotch** [comment]
I did not renammed the directory to fit new version... BRB

**Pull request merged**
