### PR TITLE
ocaml-sat-solvers.0.4

### PR DESCRIPTION
**Pull request by oliverfriedmann**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Could you return the improvement upstream if that's fine by you? If you have any questions about it don't hesitate to ask

**Comment by oliverfriedmann** [comment]
> Could you return the improvement upstream if that's fine by you? If you have any questions about it don't hesitate to ask

Your changes look good to me. Not sure what I need to do now exactly though.

**Comment by kit-ty-kate** [comment]
I assumed you had the same file in the source repository. My bad.
Thanks!

**Comment by kit-ty-kate** [comment]
crap... I assumed this package already existed before.. What about removing the `ocaml-` prefix?

**Comment by oliverfriedmann** [comment]
It did - before this was version 0.3

**Comment by oliverfriedmann** [comment]
It seems that I cannot install 0.4 via opam - any idea why?

**Comment by oliverfriedmann** [comment]
This is what I get (0.4 is missing):

~$ opam update

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org/1.2.2

~$ opam info ocaml-sat-solvers
             package: ocaml-sat-solvers
             version: 0.3
          repository: default
        upstream-url: https://github.com/tcsprojects/ocaml-sat-solvers/archive/v0.3.tar.gz
       upstream-kind: http
   upstream-checksum: 3f91093e42464c9ed1b7ef333808f2a7
            homepage: https://github.com/tcsprojects/ocaml-sat-solvers
         bug-reports: https://github.com/tcsprojects/ocaml-sat-solvers/issues
            dev-repo: git://github.com/tcsprojects/ocaml-sat-solvers.git
              author: Oliver Friedmann, Martin Lange
             license: BSD-3-clause
             depends: minisat & ocamlbuild & ocamlfind
   installed-version: 
   available-version: 0.3
         description: An abstraction layer for integrating SAT Solvers into OCaml.
An abstraction layer for integrating SAT Solvers into OCaml.

**Comment by kit-ty-kate** [comment]
The opam repository switched to opam2 two months ago. It seems you are still opam1.2, please upgrade and it should work.

See the release page (https://github.com/ocaml/opam/releases) to get the latest released binary or upgrade via your system package manager. See https://opam.ocaml.org/blog/opam-2-0-1/ for more informations

**Pull request merged**
