### PR TITLE
+flowtype.0.43.0

### PR DESCRIPTION
**Pull request by gabelevi**

### CODE REVIEW

**Comment by gabelevi** [comment]
This contains the updated inotify stubs, so hopefully musl-libc will work!

**Comment by samoht** [comment]
Still failing on alpine, although I am not totally sure why

**Comment by gabelevi** [comment]
> hh_shared.c:166:26: fatal error: asm/unistd.h: No such file or directory

It's possible we might need to add some preprocessor magic to make alpine work 😞

**Comment by samoht** [comment]
I am merging this anyway as it passes on most of the distros --  try to do your best for the next release :-)

**Pull request merged**
