### PR TITLE
Sundials v3.1.1p0 release

### PR DESCRIPTION
**Pull request by tbrk**
New release of Sundials. Update to install package.

### CODE REVIEW

**Comment by tbrk** [comment]
The Ubuntu LTS and Alpine builds fail because the CI does not seem to be able to install the `depexts`.
I have to adapt the Sundials/ML configure script for CentOS.
Debian testing and unstable fail because the `depexts` are different than those for stable; is it possible to give different depexts for different versions of debian in the `opam` files (I read some of the issue reports for opam but without really understanding what I should do).

**Comment by tbrk** [comment]
OK. *CentOS* is fixed.

Without some kind of versioning for `depexts`, it's not possible to simultaneously support *Debian* *stable*, *testing*, and *unstable* because the required package names change.

I don't think I can fix the *Alpine* and *Ubuntu LTS* CI dependency problems.

**Comment by kit-ty-kate** [comment]
Yeah, that's a bit annoying but oh well. Hopefully it'll get better once opam2 will be released.
Could you add the `{build}` attribute to `ocamlfind` though? I'll merge it afterwards.

**Comment by tbrk** [comment]
*{build}* added. Thanks for spotting that.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
