### PR TITLE
minisat2.0.4 - via opam-publish

### PR DESCRIPTION
**Pull request by fgaray**
Bindings for minisat 2 SAT solver

These are bindings for ocaml for the minisat http://minisat.se/MiniSat.html
SAT solver.

---
- Homepage: https://github.com/abate/minisat-ocaml
- Source repo: https://github.com/abate/minisat-ocaml.git
- Bug tracker: 

---
### opam-lint failures
- **WARNING** 36 Missing field 'bug-reports'

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by yallop** [comment]
The build's [failing](https://travis-ci.org/ocaml/opam-repository/jobs/126487590):

```
### stdout ###
# [...]
# libminisat_stubs.c:(.text._ZN7Minisat6Solver12solveLimitedERKNS_3vecINS_3LitEEE[Minisat::Solver::solveLimited(Minisat::vec<Minisat::Lit> const&)]+0x32): undefined reference to `Minisat::Solver::solve_()'
# libminisat_stubs.a(libminisat_stubs.o): In function `Minisat::vec<Minisat::Lit>::capacity(int)':
# libminisat_stubs.c:(.text._ZN7Minisat3vecINS_3LitEE8capacityEi[Minisat::vec<Minisat::Lit>::capacity(int)]+0xd5): undefined reference to `__cxa_allocate_exception'
# libminisat_stubs.c:(.text._ZN7Minisat3vecINS_3LitEE8capacityEi[Minisat::vec<Minisat::Lit>::capacity(int)]+0xec): undefined reference to `__cxa_throw'
# libminisat_stubs.a(libminisat_stubs.o):(.data.rel.ro._ZTIN7Minisat20OutOfMemoryExceptionE[typeinfo for Minisat::OutOfMemoryException]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
# libminisat_stubs.a(libminisat_stubs.o):(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
# collect2: ld returned 1 exit status
# File "_none_", line 1:
# Error: Error while building custom runtime system
# Command exited with code 2.
``

**Comment by samoht** [comment]
ping @fgaray

**Comment by dsheets** [comment]
ping @fgaray

**Comment by yallop** [comment]
ping @fgaray

**Comment by samoht** [comment]
Closing the issue as no activity since last Apr.

**Pull request closed without merging**
