### PR TITLE
Package randii.1.0.0

### PR DESCRIPTION
**Pull request by wyn**
### `randii.1.0.0`
A pure OCaml port of the Random123 counter based random number generator from DEShaw Research
Currently implements the Threefry 2&4 digit 32&64 bit random number generators

---
* Homepage: https://github.com/KaroshiBee/randii
* Source repo: git+https://github.com/KaroshiBee/randii.git
* Bug tracker: https://github.com/KaroshiBee/randii/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by wyn** [comment]
hmm, uunf failing to build is maybe a known problem? https://github.com/ocaml/ocaml/issues/9839

on the ppc64 log it says: 
  > <><> uunf.15.0.0 troubleshooting ><><><><><><><><><><><><><><><<><><><><>
  > => If the build fails with "ocamlopt.opt got signal and exited", issue 'ulimit -s unlimited' and retry.
  
is that something i should be controlling from my build command?

(I presume the flambda uunf problem is related)

**Comment by mseri** [comment]
You don’t need to do anything about those failure, thanks.

Just a question. Currently the package also installs the smallcrush.exe test binary. If you rename `u01/main.ml` to `u01/smallcrush.ml`, remove the corresponding `public_name` entry from the dune file and replace `(name main)` with `(name smallcrush)`, you can avoid installing it altogether but you will still be able to run `dune exec —- u01/smallcrush.exe`

**Comment by wyn** [comment]
> You don’t need to do anything about those failures, thanks.
> 
> Just a question. Currently the package also installs the smallcrush.exe test binary. If you rename `u01/main.ml` to `u01/smallcrush.ml`, remove the corresponding `public_name` entry from the dune file and replace `(name main)` with `(name smallcrush)`, you can avoid installing it altogether but you will still be able to run `dune exec —- u01/smallcrush.exe`

Sure thing, I can do that

**Comment by mseri** [comment]
Thanks

**Comment by wyn** [comment]
Thanks, I appreciate the help. I'm still figuring out how all this ecosystem stuff fits together, cheers.

**Pull request merged**
