### PR TITLE
3 packages from ocaml-multicore/multicoretests at 0.1.1

### PR DESCRIPTION
**Pull request by jmid**
This pull-request concerns:
-`qcheck-lin.0.1.1`: A multicore testing library for OCaml
-`qcheck-multicoretests-util.0.1.1`: Various utility functions for property-based testing of multicore programs
-`qcheck-stm.0.1.1`: State-machine testing library for sequential and parallel model-based tests

---
* Homepage: https://github.com/ocaml-multicore/multicoretests
* Source repo: git+https://github.com/ocaml-multicore/multicoretests.git
* Bug tracker: https://github.com/ocaml-multicore/multicoretests/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by jmid** [comment]
The candidate release moved a couple of tests to the `qcheck-lin` and `qcheck-stm` packages, but failed to update the opam test requirements accordingly...

**Comment by jmid** [comment]
The moved expect test failed on 32-bit, so this is now adapted to diff based on wordsize :crossed_fingers:

**Comment by jmid** [comment]
Besides an internal opam build error this is now all green and should thus be good to go! :smiley:

**Comment by jmid** [comment]
The only failure seems to be an internal obuilder one: https://github.com/ocurrent/obuilder/issues/71
Let me know if I can do anything further to get this merged :pray:

**Comment by raphael-proust** [comment]
LGTM! I restarted the failed job just for completeness' sake, but it's good to go AFAIAC.

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
