### PR TITLE
[new release] mirage-console-lwt, mirage-console-xen-backend, mirage-console-xen, mirage-console, mirage-console-xen-proto and mirage-console-unix (v2.4.2)

### PR DESCRIPTION
**Pull request by yomimono**
Implementation of Mirage consoles using Lwt

- Project page: <a href="https://github.com/mirage/mirage-console">https://github.com/mirage/mirage-console</a>
- Documentation: <a href="https://mirage.github.io/mirage-console/">https://mirage.github.io/mirage-console/</a>

##### CHANGES:

* Use new grant API from mirage-xen instead of xen-gnt (mirage/mirage-console#75 @yomimono)

### CODE REVIEW

**Comment by paurkedal** [comment]
Was the addition of a "v"-prefix in the version number intentional?

**Comment by avsm** [comment]
oops, good catch. Which tool caused the v to sneak in @yomimono? I can take a look at fixing

**Comment by yomimono** [comment]
Probably user error (as the user, I apologize) - it looks like the result of `--keep-v` in `dune-release`.

**Comment by avsm** [comment]
no apologies needed, and an easy fix in https://github.com/ocaml/opam-repository/pull/13802!

**Pull request merged**
