### PR TITLE
[new release] fit (1.1.0)

### PR DESCRIPTION
**Pull request by lindig**
A parser for Garmin FIT data files

- Project page: <a href="https://github.com/lindig/fit">https://github.com/lindig/fit</a>

##### CHANGES:

* Remove Int32 of int32 representation for integer values, always use
  Int of int.
* Fix parsing of unsinged numerical values
* Provide parsing of strings (not just files)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
https://github.com/lindig/fit/blob/1e92366653921cfbf050eb3f7dbb11d37f3419fe/bin/build.sh#L1 makes this package fail on FreeBSD
```
#=== ERROR while compiling fit.1.1.0 ==========================================#
# context              2.1.5 | freebsd/x86_64 | ocaml-base-compiler.4.14.1 | pinned(https://github.com/lindig/fit/releases/download/1.1.0/fit-1.1.0.tbz)
# path                 /usr/home/opam/.opam/4.14.1/.opam-switch/build/fit.1.1.0
# command              /usr/home/opam/.opam/4.14.1/bin/dune build -p fit -j 7
# exit-code            1
# env-file             /usr/home/opam/.opam/log/fit-97681-722bb5.env
# output-file          /usr/home/opam/.opam/log/fit-97681-722bb5.out
### output ###
# File "bin/dune", line 6, characters 0-118:
#  6 | (rule
#  7 |  (target build.ml)
#  8 |  (deps (universe) build.sh)
#  9 |  (action
# 10 |   (with-stdout-to
# 11 |    %{target}
# 12 |    (bash "./build.sh"))))
# (cd _build/default/bin && /usr/local/bin/bash -e -u -o pipefail -c ./build.sh) > _build/default/bin/build.ml
# /usr/local/bin/bash: line 1: ./build.sh: cannot execute: required file not found
```
Could you switch it to use `#!/bin/sh` instead? It seems like no bash feature is used in this script.

**Comment by lindig** [comment]
Sure. But this will require a new release

**Comment by lindig** [comment]
Alternatively I could exclude FreeBSD for this one and address it for the next release.

**Comment by kit-ty-kate** [comment]
As you wish. Either one is fine for us

**Comment by lindig** [comment]
Thanks for you help. This will be gone at the next release. I always believed /bin/sh only has backtick substitution but it has `$( )` as you said.

**Comment by kit-ty-kate** [comment]
All green. Thanks!

**Pull request merged**
