### PR TITLE
17 packages from inhabitedtype/ocaml-aws at 1.2

### PR DESCRIPTION
**Pull request by tmcgilchrist**
This pull-request concerns:
-`aws.1.2`: Amazon Web Services SDK
-`aws-async.1.2`: Amazon Web Services SDK bindings for async
-`aws-autoscaling.1.2`: Amazon Web Services SDK bindings to Auto Scaling
-`aws-cloudformation.1.2`: Amazon Web Services SDK bindings to AWS CloudFormation
-`aws-cloudtrail.1.2`: Amazon Web Services SDK bindings to AWS CloudTrail
-`aws-cloudwatch.1.2`: Amazon Web Services SDK bindings to Amazon CloudWatch
-`aws-ec2.1.2`: Amazon Web Services SDK bindings to Amazon Elastic Compute Cloud
-`aws-elasticache.1.2`: Amazon Web Services SDK bindings to Amazon ElastiCache
-`aws-elasticloadbalancing.1.2`: Amazon Web Services SDK bindings to Elastic Load Balancing
-`aws-lwt.1.2`: Amazon Web Services SDK bindings for lwt
-`aws-rds.1.2`: Amazon Web Services SDK bindings to Amazon Relational Database Service
-`aws-route53.1.2`: Amazon Web Services SDK bindings to Amazon Route 53
-`aws-sdb.1.2`: Amazon Web Services SDK bindings to Amazon SimpleDB
-`aws-sqs.1.2`: Amazon Web Services SDK bindings to Amazon Simple Queue Service
-`aws-ssm.1.2`: Amazon Web Services SDK bindings to Amazon Simple Systems Management Service
-`aws-sts.1.2`: Amazon Web Services SDK bindings to AWS Security Token Service

---
* Homepage: https://github.com/inhabitedtype/ocaml-aws
* Source repo: git+https://github.com/inhabitedtype/ocaml-aws.git
* Bug tracker: https://github.com/inhabitedtype/ocaml-aws/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

### CODE REVIEW

**Comment by mseri** [comment]
Looks like the tarball has changed: 
```
https://github.com/inhabitedtype/ocaml-aws/archive/v1.2.tar.gz (Bad checksum, expected md5=f01fbb141e5a6e07dda8ce04ce7a089e)
```

**Comment by kit-ty-kate** [comment]
The segfault in ocamlopt on arm64 is there because it's trying to compile a 3.37MB generated file.

**Comment by kit-ty-kate** [comment]
Thanks! Could you return the fixes to the opam files upstream?

**Comment by tmcgilchrist** [comment]
Thank you so much @kit-ty-kate for the fixes. 

Curious about the arm64 build failure, the 3.37MB file is the types.ml from ec2, 
`ocamlopt libraries/ec2/lib/.aws_ec2.objs/native/aws_ec2__Types.{cmx,o} (got signal SEGV)`
Is that a known issue or am I pushing the max size of a file?

**Pull request merged**
