### PR TITLE
Ocamlweb new release : 1.40

### PR DESCRIPTION
**Pull request by jcourant**
This release replaces the deprecated \tt LaTeX command by \texttt in ocamlweb.sty.
Code is now utf8 (ocamlweb --version prints the names of the authors in utf8).

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Could you take care of the warnings from @camelus ? If there is no ```bug-reports``` and ```dev-repo``` it's fine but at least I think a remove field is indeed needed.

**Comment by yomimono** [comment]
@jcourant Could you please address the comments from @jpdeplaix above?  The most important part is "I think a remove field is indeed needed."  If you can't do that at this time, we'll likely close this pull request soon (but you're welcome to resubmit it with changes whenever is convenient for you).

**Comment by kit-ty-kate** [comment]
Ping @jcourant

**Comment by kit-ty-kate** [comment]
Closing this. Feel free to reopen it whenever you want.

**Pull request closed without merging**
