### PR TITLE
[new release] mdx (1.5.0)

### PR DESCRIPTION
**Pull request by NathanReb**
Executable code blocks inside markdown files

- Project page: <a href="https://github.com/realworldocaml/mdx">https://github.com/realworldocaml/mdx</a>
- Documentation: <a href="https://realworldocaml.github.io/mdx/">https://realworldocaml.github.io/mdx/</a>

#### Added

- Add `--syntax` option to `rule` subcommand to allow generating rules for cram
  tests (realworldocaml/mdx#177, @craigfe)
- Add a `require-package` label to explicitly declare dune `package` dependencies of a code block
  (realworldocaml/mdx#149, @Julow)
- Add an `unset-` label to unset env variables in shell blocks (realworldocaml/mdx#132, @clecat)

#### Changed

- Run promotion of markdown files before `.ml` files in generated dune rules (realworldocaml/mdx#140, @clecat)

#### Fixed

- Remove trailing whitespaces at the end of toplevel or bash evaluation lines
  (realworldocaml/mdx#166, @clecat)
- Improve error reporting of ocaml-mdx test (realworldocaml/mdx#172, @Julow)
- Rule: Pass the --section option to `test` (realworldocaml/mdx#176, @Julow)
- Remove trailing whitespaces from shell outputs and toplevel evals (realworldocaml/mdx#166, @clecat)
- Remove inappropriate empty lines in generated dune rules (realworldocaml/mdx#163, @Julow)
- Fix ignored `skip` label in `ocaml-mdx pp` (realworldocaml/mdx#1561, @CraigFe)
- Fix synchronization of new parts from markdown to `.ml` (realworldocaml/mdx#156, @Julow)
- Fix ignored `[@@@parts ...]` markers within module definitions (realworldocaml/mdx#155, @Julow)
- Fix a bug in internal OCaml version comparison that lead to crashes in some cases (realworldocaml/mdx#145, @gpetiot)
- Promote to empty `.ml` file when using `to-ml` direction (realworldocaml/mdx#139, @clecat)
- Apply `--force-output` to `.ml` file as well (realworldocaml/mdx#137, @clecat)
- Fix a bug preventing `.corrected` files to be written in some cases (realworldocaml/mdx#136, @clecat)
- Add compatibility with `4.09.0` (realworldocaml/mdx#133, @xclerc)

#### Removed

- Remove the `infer-timestamp` direction (realworldocaml/mdx#171 @Julow)

### CODE REVIEW

**Comment by mseri** [comment]
Can you check the revdeps, it seems that some error may be related to this release

**Comment by kit-ty-kate** [comment]
The tests fail with this error message:
```
#=== ERROR while compiling mdx.1.5.0 ==========================================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.02.3 | pinned(https://github.com/realworldocaml/mdx/releases/download/1.5.0/mdx-1.5.0.tbz)
# path                 ~/.opam/4.02/.opam-switch/build/mdx.1.5.0
# command              ~/.opam/4.02/bin/dune runtest -p mdx
# exit-code            1
# env-file             ~/.opam/log/mdx-29-216cfb.env
# output-file          ~/.opam/log/mdx-29-216cfb.out
### output ###
# File "test/dune.inc", line 146, characters 0-210:
# 146 | (alias
# 147 |  (name   runtest)
# 148 |  (deps   (:x require/require-package.md)
# 149 |          (package example_lib))
# 150 |  (action (progn
# 151 |            (run ocaml-mdx test --direction=to-md %{x})
# 152 |            (diff? %{x} %{x}.corrected))))
# Error: No rule found for alias .example_lib-files
#    ocaml-mdx alias test/runtest
# Generating output.html...
# File "test/cram.t", line 1, characters 0-0:
#          git (internal) (exit 1)
# (cd _build/default && /usr/bin/git diff --no-index --color=always -u test/cram.t test/cram.t.corrected)
# diff --git a/test/cram.t b/test/cram.t.corrected
# index 3568fd4..d3e390c 100644
# --- a/test/cram.t
# +++ b/test/cram.t.corrected
# @@ -58,8 +58,6 @@ And
#    > world\
#    > EOF
#    $ cat foo
# -  hello
# -  world
#    $ echo foo
#    foo
#  
```

**Comment by kit-ty-kate** [comment]
This error has been there for a while (see https://github.com/ocaml/opam-repository/pull/14791#issuecomment-529103707)
```
+ /home/opam/.opam/4.09/bin/dune "runtest" "-p" "datalog" (CWD=/home/opam/.opam/4.09/.opam-switch/build/datalog.0.6)
-    ocaml-mdx alias runtest (exit 125)
- (cd _build/default && /home/opam/.opam/4.09/bin/ocaml-mdx test README.md)
- >> Fatal error: CI/87 unbound at toplevel
- ocaml-mdx-test: internal error, uncaught exception:
-                 Misc.Fatal_error
```
Does anybody still have any idea where does it come from?

**Comment by NathanReb** [comment]
I'll take a look at the revdeps but it is indeed expected that some bug fixes will change the output of `ocaml-mdx test` and therefore "break" some MDX-based tests.

I'll try to make it clearer that for now, people using `mdx` for their tests should use hard constraints on a single version to prevent that kind of breakage in the future.

I'm a bit puzzled about the tests but I'll take a look as well.

Thanks to both of you!

**Comment by kit-ty-kate** [comment]
but should mdx fail with `internal error, uncaught exception` if it's only a matter of divergence of the output?

**Comment by NathanReb** [comment]
I wasn't referring to this failure which, if I understood it correctly, was already around for a while and is unrelated to this release, isn't it?

 To answer your question I have no idea where it comes from, I'll try to take a look before the next release!

**Comment by NathanReb** [comment]
Okay this seems broken beyond repair and I'd like to avoid dirty fixes in the opam file so we'll postpone the release a bit, that will also give us an occasion to squeeze in a couple more features that we're about to merge.

Thanks for the feedback and sorry for the noise!

**Pull request closed without merging**
