### PR TITLE
[new release] dune-build-info, dune, dune-configurator, dune-action-plugin, dune-private-libs and dune-glob (2.1.2)

### PR DESCRIPTION
**Pull request by rgrinberg**
Embed build informations inside executable

- Project page: <a href="https://github.com/ocaml/dune">https://github.com/ocaml/dune</a>
- Documentation: <a href="https://dune.readthedocs.io/">https://dune.readthedocs.io/</a>

##### CHANGES:

- Fix a bug in the `Fiber.finalize` function of the concurrency monad of Dune,
  causing a race condition at the user level (ocaml/dune#3009, fix ocaml/dune#2958, @diml)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The archive does not seem to exist yet:
```
Processing  1/1: [dune.2.1.2: http]
[ERROR] The sources of the following couldn't be obtained, aborting:
          - dune.2.1.2:
            https://github.com/ocaml/dune/releases/download/2.1.2/dune-2.1.2.tbz (curl: code 404 while downloading https://github.com/ocaml/dune/releases/download/2.1.2/dune-2.1.2.tbz)
```

**Comment by diml** [comment]
I just uploaded it.

**Comment by kit-ty-kate** [comment]
CI restarted

**Comment by kit-ty-kate** [comment]
Looks good. Thanks!

**Pull request merged**
