### PR TITLE
bulk addition of 'ocamlbuild {build}' dependencies

### PR DESCRIPTION
**Pull request by gasche**
I am experimenting with a script to edit opam-repository in bulk to add an [ocamlbuild](https://github.com/ocaml/opam-repository/tree/master/packages/ocamlbuild/) dependency to all packages that seem to depend on ocamlbuild, in the following sense:

- they have a `_tags` file somewhere in the package archive; or,
- they have a `myocamlbuild.ml` file somewhere in the package archive; or,
- they have an `_oasis` file in the archive with the `BuildTools: ocamlbuild` line present; or,
- they call `ocamlbuild` directly from the `build` command of their `opam` file

(The context is that, as announced at the last OCaml Workshop in Vancouver, ocamlbuild should be eventually split from the standard definition. This means that adding the ocamlbuild dependency today will be a no-op, but it prevents scripts from breaking on an ocamlbuild-deprived compiler, or all ocamlbuild-using project packagers from having to edit their past and present `opam` package metadata manually.)

The script I wrote can be found at [gasche/opam:admin-scripts/add_ocamlbuild_dependency.ml](https://github.com/gasche/opam/blob/ocamlbuild-migration-script/admin-scripts/add_ocamlbuild_dependency.ml). It is heavily commented so that you can check it does what is described in this PR.

Running the script adds an `ocamlbuild` dependency to 2869 of the 4185 packages in the current opam-repository master.

Programmatically modifying `opam` files has the unfortunate side-effect that fields are re-ordered and some bracketing conventions changed, so the diff generated do not only contain the new dependency. In order to make the diff as easy to review as possible (that is: not very much, given its size), I have been careful to split changes in two commits, one just that just reformats the `opam` file without changing its semantics (but updates the version to 1.2, as I don't know whether older version support the output of the script's opam-serialization), and one that does add the dependency.

In the future, I think it could be useful to write an `opam fmt` script that would reformat `opam` files (by just reading and writing them again), with an `opam fmt --check` mode to verify that `opam fmt` would be a no-op, and run this `--check` on opam-repository pull requests to make sure that commiters have properly normalized their opam file before submission. This would make it easier to mix and review both human-written and bulk-generated changes.

### Request for comment

Would you be ready to merge such a pull-request?

Are there any further change that we can make to the generating script to improve the proposed patch quality?

The current approach is to try to add as few `ocamlbuild` dependencies as necessary. Another would be to add it preemptively to all packages, and let packagers manually *remove* it when they deem it useful. This is guaranteed not to break programs, but it would result in some programs having stronger dependencies than necessary.

Another question is: what will happen for `./opam` files that are not in this public repository? Other repos are free to use my script to do their bulk-editing if it makes sense, but there are tons of `opam` files stored in upstream packages version control, and those would have to be modified manually. Maybe we should also provide a script to do this automatically, at the level of a single package (this would not be too hard by sharing code with the present script).

### CODE REVIEW

**Comment by gasche** [comment]
I suspect the Travis check fails because the scripting libraries I used come from opam trunk, and the way they print back opam files may not be always compatible with the older opam version run by travis. My next step (but not today) is to downgrade the libraries used to the opam-1.2.x API, to be sure to generate compatible `opam` files.

In the meantime, I have uploaded [there](http://gallium.inria.fr/~scherer/tmp/ocamlbuild-opam.txt) the log of the tool detection: for each package (and each version) in opam-repository, `ocamlbuild usage:` is `true` if ocamlbuild usage was detected by the script (and a dependency is added by this PR). Grepping this log is an easy way for tool authors to check that the bulk processing is as they expect.

**Comment by samoht** [comment]
The post-message field of `containers.0.7` looks suspicious:
```
post-messages: """
containers is now split into finer-grained sub-libraries, including
     `containers.io`, `containers.iter`, `containers.sexp`, `containers.data`.
     CCGen and CCSequence have been removed, consider using the libraries
    `gen` and `sequence` on opam."""
```

@AltGr seems that the pretty-printing put too much quotes.

**Comment by Chris00** [comment]
On Fri, 13 Nov 2015 17:53:54 -0800, Gabriel Scherer wrote:
> 
> Programmatically modifying opam files has the unfortunate side-effect that fields are re-ordered and some bracketing conventions changed, so the diff generated do not only contain the new dependency. In order to make the diff as easy to review as possible (that is: not very much, given its size), I have been careful to split changes in two commits, one just that just reformats the opam file without changing its semantics (but updates the version to 1.2, as I don't know whether older version support the output of the script's opam-serialization), and one that does add the dependency.

I had the same problem for https://github.com/ocaml/opam-repository/pull/4692
What I ended up doing was, after using opam to parse and decide whether the original file should be modified, use regular expressions to locate the correct spots in the original file to modify.

> [...]
> Another question is: what will happen for ./opam files that are not in this
> public repository? Other repos are free to use my script to do their
> bulk-editing if it makes sense, but there are tons of opam files stored in
> upstream packages version control, and those would have to be modified
> manually. Maybe we should also provide a script to do this automatically, at
> the level of a single package (this would not be too hard by sharing code with
> the present script).

Maybe one should already add a compiler where ocamlbuild is not included so that, when new packages do not declare such dependency, the tests fail.

Also, one may want to send an email to the maintainer of each package that you modify.

**Comment by gasche** [comment]
A note on the "notifying maintainers" idea: I understand Christophe is suggesting some form of automatic notification of maintainers of affected package, to take place when a final version of this proposed patch is merged. I'm fine with this idea, but would like to point out that I plan to wait for this discussion to stabilize before sending any kind of notifaction: there is an interlock between "notifying people" and preparing this patch.

I am preparing an announce to caml-list, telling people about the change, and I would like the announce to happen *before* we start notifying people that they have to check or fix or update things. On the other hand, I would like to send the announce *after* I am reasonably sure of whether such a bulk update will take place or not, to be able to give clear instructions to users (either: "just check your updated package and add the dependency to upstream opam", or on the contrary "you need to edit the packages you maintain by hand").

Regarding instructions to user: another option would be to just add "ocamlbuild" as a required package for the 4.02.3 switch distributed through OPAM. This means that ocamlbuild would be automatically installed, and there would be no need to update metadata at all. Of course, this is only delaying the problem, and I would rather fix it now. But we should keep it as an option if it turns out that a bulk transition won't be ready before the 4.02.3 release -- I don't know when that will be.

> Maybe one should already add a compiler where ocamlbuild is not included so that, when new packages do not declare such dependency, the tests fail.

This is indeed the best way to check, but I don't have the machinery at hand to build all packages, so I would rather let this be done automatically as part of the pre-4.02-3-release Q/A and build builds. (I am assuming that the proposed change approach is globally correct, and that this test will detect some missed cases, but in small enough numbers that we can handle them manually before the release.)

**Comment by gasche** [comment]
@Chris00 

> What I ended up doing was, after using opam to parse and decide whether the original file should be modified, use regular expressions to locate the correct spots in the original file to modify.

Do you happen to have the script for this regex-surgery part lying around?

**Comment by gasche** [comment]
I just push-forced a version of the patch that has been generated from the 1.2 libraries (and not the trunk libraries), hoping it may fix some of the unexpected-formatting issues.

**Comment by gasche** [comment]
There are some Travis build failures that look related to the fact that some of the updated metadata somewhere was wrong for some independent reason, but it looks like OPAM is now happy with what the post-patch `opam` files look like -- and the `containers` messages expertly spotted by @samoht use a single quote now.

Travis seems willing to re-build all packages whose `opam` file was changed. Is it a property of the travis script, or will users also have to rebuild their whole package universe? If the latter, does someone know whether conditioning the new `ocamlbuild` dependency on a `ocaml-version >= 4.02.3` would be possible, and prevent recompilations?

**Comment by Chris00** [comment]
On Sat, 14 Nov 2015 05:10:02 -0800, Gabriel Scherer wrote:
> 
> Do you happen to have the script for this regex-surgery part lying around?

Here it is:
https://github.com/ocamllabs/cosmetrics/blob/master/src/Cosmetrics_opam.ml#L79

**Comment by samoht** [comment]
> Travis seems willing to re-build all packages whose opam file was changed. Is it a property of the travis script, or will users also have to rebuild their whole package universe? If the latter, does someone know whether conditioning the new ocamlbuild dependency on a ocaml-version >= 4.02.3 would be possible, and prevent recompilations?

This is a property of the CI of opam-repository. Users won't have any recompilation if you modify an `opam` file but only if you modify `url`.

**Comment by samoht** [comment]
Personally I'm fine with such a bulk change. Would be great to run a normalisation on opam files regularly to avoid such big patches in the future (and ideally `opam-publish` will do that automatically). The normalisation have to happen anyway for the repository signing to be in place....

**Comment by gasche** [comment]
I removed the scary `[RFC]` part in the Pull Request title. What else can I do on my end to get this PR merged?

**Comment by avsm** [comment]
Is there an existing command for normalisation that doesn't change the 1.1 files?  I thought the problem was that it rewrote them to 1.2 format, @altgr?

**Comment by gasche** [comment]
My understanding is that normalization would happen whatever the opam version is, because OPAM printing will use a fixed order for the fields, so you'll see a normalization change whenever users didn't follow that order. (In my experience the OPAM fixed order is reasonable and can be argued to be an improvement.)

I think there is no normalization tool that exists today, but I started working on one on the side (I'm at the level or reading Cmdliner documentation again because it's not that easy to bootstrap a project using it). You may be interested in my [design notes](https://annuel.framapad.org/p/opam-fmt) for the tool.

**Comment by samoht** [comment]
Any opinion from someone else? I'm happy to merge it none. @AltGr / @hannesm maybe some comments related to the upcoming signing repository?

**Comment by gasche** [comment]
Re. normalization tool: currently it is possible to install `opam-lib` via OPAM, but the version of this library is indexed over the OPAM version, and that means that one may only have one fixed version of `opam-lib` in a given switch. This means that someone willing to install my hypothetic `opam-fmt` tool would have to choose exactly one version of OPAM config files to support (the tool upgrades earlier-version files to the current-version format, but refuses to work on later-version files).

Another approach would be to package `opam-lib` as separate packages `opam-lib-1.0`, `opam-lib-1.1`, etc. This would allow to install a tool (or family of tools) to work on packages for any OPAM version in parallel (for example, doing the re-formatting at exactly the opam version that the input `opam` file is in). This is a choice for the packages of `opam-lib` to make.

(The design of `opam-fmt` posted above was written before I understood this conflict issue and thus proposes a family of tools `opam-fmt-$OPAMLIBVER`. The better design is to propose exactly the approach that is easy to do given `opam-lib`'s packaging choices. Today that means having only one version installed at a time.)

**Comment by gasche** [comment]
I pushed a first prototype of `opam-fmt` script to https://github.com/gasche/opam-fmt

```
$ cd ~/Prog/opam-repository/packages
$ opam fmt --check batteries/batteries.2.3.1/opam
"batteries/batteries.2.3.1/opam" is not correctly formatted.
$ opam fmt --inplace batteries/batteries.2.3.1/opam
"batteries/batteries.2.3.1/opam" has been rewritten in place.
$ opam fmt --check batteries/batteries.2.3.1/opam
$ time opam fmt --check **/**/opam | wc -l
4187

real	0m11.829s
user	0m4.525s
sys	0m7.194s
```

(The reason why the error output should be silenced when running on all files is that reading opam files may print warnings on stderr.)

**Comment by hannesm** [comment]
regarding signing, @AltGr implemented normalisation ([here](https://github.com/ocaml/opam/blob/feebf648c711fb293cccd876483ea1e0f0042309/src/format/opamFormat.ml#L172)), and the plan is to use `sign (hash (normalise opam))`, where the normalised form does not need to be on disk at any point (since verification again can read opam, normalise and hash, and then check the signature)... thus, I don't mind having this merged.

**Comment by gasche** [comment]
@hannesm If I understand correctly, you are pointing out that the renormalization part of the PR would not affect the signatures (which is a very good property to have indeed). But the bulk *change* itself, which is to add a new dependency to the metadata, *would* change the signature. Is there a process in place in this case? For example is the plan to bulk-email the respective package maintainers to sign the post-bulk-update packages, or can such a change be validated by a repository-level maintainer with authority to update signatures in bulk? (He or she would only need to inspect the second, post-normalization patch, which is a good property.)

(In any case the split between normalization-only and real-update is going to change soon as I rework the present PR on top of Louis' recent more-faithful-reprinting work, as discussed on opam-devel.)

**Comment by hannesm** [comment]
@gasche once signing is in place, you are right that the actual changes (not the normalisation) need to be signed.  This is similar to when a new package `a` is released, and packages depending on `a` need to have their version constraints updated.

To solve these, either the developer of each package can submit and sign their opam files OR a quorum of repository maintainers (think of it as the set of people with write access to opam-repository) can sign the new opam file(s).  If we'd require a signature of only a single repository maintainer, an attacker would only need to compromise a single repository maintainer to implant arbitrary code in any package (thus we require a quorum).  There'll be updates (on opam-devel) and running code soon (the proposal from June is slightly too complex).

**Comment by gasche** [comment]
So I re-did a run of my script (you may be curious to see the [updated source code](https://github.com/gasche/opam/blob/ocamlbuild-migration-script/admin-scripts/add_ocamlbuild_dependency.ml)) to benefit from @AltGr 's work on formatting-preserving printing. I did it using the opam-lib version of the master branch; the incompatibility in text quoting behavior is not an issue anymore, given that I never change text-only fields. 

@AltGr : there was a minor hiccup with the fact that the `author:` field was not re-printed correctly due to the fact that it was translated into `authors:` on the fly, and thus the format-preserving logic could not locate the original field correctly. I fixed it quick&dirty with a `sed` call before reprinting.

The new patch is much cleaner; my understanding of the opam-devel discussion is that there is a consensus to apply the patch on top of the repository. I would be very much in favor of this, as it would allow me to move to the next ocamlbuild-plan item. Note that:

- some packages couldn't be downloaded or had wrong checksums, those were ignored
- there are still some comments lost during the reformatting (the ones inside the `depends` field)
- the `opam` file version is still bumped from `"1"` to `"1.2"` on all affected files, which we may want to change

Regarding the last item, given how minimal the change now is, I wonder whether it wouldn't also work with 1.1.

**Comment by hannesm** [comment]
from the diff, there are several occurences of changing conjuncts to disjuncts in `conflicts`:
```
-conflicts: [ "async_extra" {<= "111.25.00" & >= "112.01.00"} ]
+conflicts: [
+  "async_extra" {<= "111.25.00" | >= "112.01.00"}
+]
```

is this intentional and semantics preserving (after thinking about it, a disjunct makes more sense, wonder how a conjunct worked in the first place)?

**Comment by gasche** [comment]
@hannesm thanks looking! I don't know, but I assume this is indeed a style change. @AltGr, will 1.2 opam understand the move from `&` to `|` in conflicts?

Given the low number of packages with a removed comment (15), I manually crafted a new patch re-adding the comments back.

**Comment by gasche** [comment]
The travis test reports:

```
"async (< 109.15.00 | > 109.53.02) & lwt (< 2.4.3 | >= 2.4.7) & mirage-net < 0.5.0" is not a valid conjunction
```

so it looks like indeed this way of printing conflicts is not supported by opam-1.2.

**Comment by gasche** [comment]
I just updated the PR with a re-run of the script with field cleanup functions disabled. I want to see how the Travis react to this change, but I also need to update the package database with recent additions.

**Comment by gasche** [comment]
Now the script's output is up-to-date with respect to the master branch, with last commit 45a1b29c742abb2bb537501f80f28c61234b3a23 .

```
commit 45a1b29c742abb2bb537501f80f28c61234b3a23
Merge: c2a9c0d 3d08352
Author: David Sheets <sheets@alum.mit.edu>
Date:   Mon Nov 30 17:00:03 2015 +0000

    Merge pull request #5204 from Gbury/opam-publish/msat.0.1
    
    msat.0.1 - via opam-publish
```

**Comment by gasche** [comment]
Updating the script output is easy and an incremental operation: I run the script anew on top of the partially updated repository. Of course, there will still be occasions for automated rewriting *after* this first large PR is added, I don't expect people to auto-magically start to never forget about the ocamlbuild dependency, so I will run it again the future and submit smaller PRs.

But right now it would be fairly useful for me if the current batch change was merged reasonably quickly (I'm waiting for this to send the caml-list announce mail), once we have some Travis results again and are sure that the current patch creates valid 1.2 opam files.

**Comment by avsm** [comment]
Reviewed by @samoht and me and merged. Thanks!

**Comment by gasche** [comment]
Thanks a lot! I'll send the ocamlbuild announce real soon.

**Comment by Drup** [comment]
@gasche Idea to autodetect usage of ocamlbuild plugins : just grep for `Ocamlbuild_plugin` in files other than `myocamlbuild.ml`.

**Comment by hannesm** [comment]
@gasche was the following change intentional? (and @AltGr what is the semantics in opam for having a list of packages here?):
```
-  ("mirage-no-xen" | ("mirage-xen" & "mirage-entropy-xen" & "zarith-xen"))
+  ("mirage-no-xen" | ("mirage-xen" "mirage-entropy-xen" "zarith-xen"))
```

(this is the nocrypto package in the dependency list)

**Comment by gasche** [comment]
No, it wasn't intentional on my part.

**Comment by AltGr** [comment]
A list of packages in inner expressions is the same that at top-level, i.e. it depends on the field (yes, it's kind of weird). So, assuming this was in a `depends:` field, the meaning would be the same for both versions.

**Comment by hannesm** [comment]
@AltGr thanks for clarifying, yes this was in a `depends:` field

**Pull request merged**
