### PR TITLE
Package polynomial.0.4.0

### PR DESCRIPTION
**Pull request by dannywillems**
### `polynomial.0.4.0`
Polynomials over finite fields
Polynomials over finite fields

---
* Homepage: https://gitlab.com/nomadic-labs/cryptography/ocaml-polynomial
* Source repo: git+https://gitlab.com/nomadic-labs/cryptography/ocaml-polynomial.git
* Bug tracker: https://gitlab.com/nomadic-labs/cryptography/ocaml-polynomial/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by dannywillems** [comment]
We will make a release 1.0.0 in the near future.

**Comment by dannywillems** [comment]
dune dependency changed upstream too

**Comment by dannywillems** [comment]
Made a new release with the potential bugfix detected by the CI with https://github.com/ocaml/opam-repository/pull/22545/commits/80c5e53c51777b8784001d82ea9670bba86b0cba

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
