### PR TITLE
[new release] eqaf (2 packages) (0.10)

### PR DESCRIPTION
**Pull request by dinosaure**
Constant-time equal function on string

- Project page: <a href="https://github.com/mirage/eqaf">https://github.com/mirage/eqaf</a>
- Documentation: <a href="https://mirage.github.io/eqaf/">https://mirage.github.io/eqaf/</a>

##### CHANGES:

- Implement functions provided by `eqaf` on bytes (@FantomeBeignet, mirage/eqaf#41)
- Choose the right clock on MSVC systems (@dra27, mirage/eqaf#40)
- Fix the lower bounds about base64 (@hannesm, mirage/eqaf#45)
- Split `eqaf` and `eqaf-cstruct` (@dinosaure, @hannesm, mirage/eqaf#43)

### CODE REVIEW

**Comment by hannesm** [comment]
I fixed revdeps in #26099

**Comment by hannesm** [comment]
the repo CI restart worked nicely, now I opened #26107 to make the remaining build failures restrictions. There's still solver timeouts and fetch failures, but nothing I can do.

**Comment by hannesm** [comment]
Since #26107 is merged, I restarted the CI here. Once finished, I guess this is ready to be merged.

**Comment by dinosaure** [comment]
Errors seems unrelated to this release, seems ok to merge 👍

**Comment by hannesm** [comment]
Yes, I agree with @dinosaure. Good to merge :)

**Pull request merged**
