### PR TITLE
added ppx_meta_conv.2.5.0

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
Ah, it requires ppxx.1.3.1 pulled first.

**Comment by yallop** [comment]
We can restart the Travis build when #7796 is merged.  Is it possible to relax the OCaml version constraint in #7796?

**Comment by yallop** [comment]
#7796 is merged.  I've restarted the build.

**Comment by yallop** [comment]
There's still a [dependency issue](https://travis-ci.org/ocaml/opam-repository/jobs/177269550):

```
Package is unavailable on this configuration, skipping:
The following dependencies couldn't be met:
  - ppx_meta_conv -> spotlib >= 3.0.0 -> ppx_test >= 1.3.1
Your request can't be satisfied:
  - ppx_test is not available because your system doesn't comply with ocaml-version = "4.03.0".
  - ppx_test>=1.3.1 is not available because your system doesn't comply with ocaml-version = "4.03.0".
```

**Comment by camlspotter** [comment]
Should be fixed when https://github.com/ocaml/opam-repository/pull/7857 is merged, but currently we have an issue of `omake` installation.

**Comment by yallop** [comment]
I've restarted the build now that #7964 is merged.

**Comment by yallop** [comment]
The build still has the [same problem](https://github.com/ocaml-omake/omake/issues/71).

**Comment by yallop** [comment]
I've restarted the build again now that #8058 is merged.

**Comment by yallop** [comment]
The [4.04 build](https://travis-ci.org/ocaml/opam-repository/jobs/177269550) is failing with a new problem, apparently that it expects `tiny_json` to be a dependency (not just a `depopt`):

```
# ocamlfind: Package `tiny_json' not found
# Package tiny_json is not available...
# ocamlfind: Package `tiny_json' not found
# ocamlfind: Package `tiny_json' not found
# *** omake: targets were not rebuilt because of errors:
#    <scanner tiny_json/scan-ocaml-json_conv.ml>
#       depends on: tiny_json/json_conv.ml
#    <scanner tiny_json/scan-ocaml-json_conv.mli>
#       depends on: tiny_json/json_conv.mli
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=/home/travis/.opam/4.04.0\"' terminated with error code 2")
```

The [4.03.0 build](https://travis-ci.org/ocaml/opam-repository/jobs/177269551) still has the same problem:

```
# Error: Files ppx_test.cmo and /home/travis/.opam/4.03.0/lib/ppxx/ppxx.cmo
#        make inconsistent assumptions over interface Ppxx
```

**Comment by yallop** [comment]
I've made `tiny-json` and `sexplib` non-optional and the [4.04. build is now passing](https://travis-ci.org/ocaml/opam-repository/jobs/183910177).

The [4.03 build](https://travis-ci.org/ocaml/opam-repository/jobs/183910180) still has the same problem.

**Comment by avsm** [comment]
This now appears to pass (the status fields here are not updated as they've hit the GitHub limit of maximum updates per commit, so will forever be marked as broken). Merging.

**Pull request merged**
