### PR TITLE
Fix patch level for aez

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by avsm** [comment]
hm this failed to put the META in the right place

**Comment by avsm** [comment]
@AltGr: ping on this

**Comment by AltGr** [comment]
Arg, I get it: the patch just adds a file, so it actually applies with `-p0` as well as `-p1`. Since opam 1.2 tries all values in order, it will end up using `-p0` and creating `b/META`.
Since there is actually no reason to use a patch at all for that, the fix is simple, but it might happen at other places.

**Comment by avsm** [comment]
Makes sense; will keep an eye out for similar errors.

**Pull request merged**
