### PR TITLE
Mecab 0.0.0

### PR DESCRIPTION
**Pull request by akabe**
An OCaml binding of MeCab, a part-of-speech and morphological analyzer.

MeCab is a open-sourced part-of-speech and morphological analyzer independent from languages, dictionaries, and corpuses, developed by a joint project team of Graduate School of Informatics in Kyoto University and NTT Communication Science Laboratories.

https://akabe.github.io/ocaml-mecab/

### CODE REVIEW

**Comment by akabe** [comment]
Strange. It seems that OPAM v2 does **not** execute `"source" "centos"` and `"source" "alpine"` in `depexts` section. OPAM v1.2 does. Is `depexts` behavior in v2 different from v1.2?

OPAM 1.2, OCaml 4.05, Alpine 3.6:

```
# Installed packages for 4.05.0:
base-bigarray    base  Bigarray library distributed with the OCaml compiler
base-threads     base  Threads library distributed with the OCaml compiler
base-unix        base  Unix library distributed with the OCaml compiler
depext          1.0.5  Query and install external dependencies of OPAM packages
ocamlbuild     0.11.0  OCamlbuild is a build system with builtin rules to easily
travis-opam     1.0.3  Travis CI (Continuous Integration) helpers
opam depext -uivyj 2 mecab.0.0.0
# Detecting depexts using flags: x86_64 linux alpine
# The following system packages are needed:
#  - m4
# The following scripts need to be run:
#  - https://gist.githubusercontent.com/akabe/e649732722c4d0858afc4aaa33900bf1/raw/opam-src-mecab.sh
The following command needs to be run through "sudo":
    apk update
```

OPAM 2, OCaml 4.05, Alpine 3.6:

```
=-=- Repository configuration for switch ocaml-base-compiler.4.05.0 -=-=-=-=-=-=
 1 default file:///home/opam/src
# Packages matching: installed
# Name              # Installed # Synopsis
base-bigarray       base        Bigarray library distributed with the OCaml compiler
base-threads        base        Threads library distributed with the OCaml compiler
base-unix           base        Unix library distributed with the OCaml compiler
depext              1.0.5       pinned to version 1.0.5 at git+https://github.com/AltGr/opam-depext.git#opam-2-beta4
ocaml               4.05.0      The OCaml compiler (virtual package)
ocaml-base-compiler 4.05.0      Official 4.05.0 release
ocamlbuild          0.11.0      OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
travis-opam         1.0.3       Travis CI (Continuous Integration) helpers
/bin/sh: lsb_release: not found
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=alpine, os-version=3.6.2, os-family=alpine
m4
# The following system packages are needed:
The following command needs to be run through "sudo":
    apk update
```

**Comment by akabe** [comment]
@avsm Has OPAM v2 been updated recently? Or, are my opam files wrong? I have no idea that OPAM v2 ignores `source` in `depext` section.

**Comment by avsm** [comment]
Opam2 depext does indeed deprecate the `source` tag. The issue is that it's quite dangerous to execute arbitrary shell code, and now that opam2 has sandboxing, we need a better way to handle such ad-hoc dependencies.  I'm not sure what that way is yet as opam2-depext is still under development, but suggestions are welcome.

**Comment by avsm** [comment]
Thanks! You may want to announce this on <https://discuss.ocaml.org>, where we have a Community category and an `announce` tag for this purpose.

**Pull request merged**
