### PR TITLE
Ctypes 0.4.0 tgls fix

### PR DESCRIPTION
**Pull request by yallop**
See #3719.

/cc @dbuenzli

### CODE REVIEW

**Comment by dbuenzli** [comment]
@yallop I'm trying to make a new release of tgls to support 0.4.0 but my tests fail with this 
```
+ ocamlfind ocamlc -linkpkg -g -thread -cclib '-framework OpenGL' -package tsdl src/tgl3.cmo test/trigl3.cmo -o test/trigl3.byte
File "_none_", line 1:
Error: Files /Users/dbuenzli/.opam/doc/lib/tsdl/tsdl.cma(Tsdl)
       and /Users/dbuenzli/.opam/doc/lib/ctypes/ctypes-foreign-threaded.cma(Foreign)
       make inconsistent assumptions over interface Foreign
```

Do you have an idea of what may be going wrong ?

**Comment by dbuenzli** [comment]
(I did reinstall tsdl with 0.4.0)

**Comment by yallop** [comment]
@dbuenzli: is it possible that the library was partly built with `-thread` and partly without?  That might cause difficulties, since the ctypes `META` file selects different implementations of `Foreign` according to whether `-thread` is enabled.

**Comment by dbuenzli** [comment]
Actually this also happens on the test suite of `tsdl`. I didn't tag tsdl.ml and tsdl.mli with `thread` but even if I do the problem occurs. Here's the full build log, I see -thread being used everywhere: 

```
> ./build tests.otarget
ocamlfind ocamlopt unix.cmxa -I /Users/dbuenzli/.opam/doc/lib/ocaml/ocamlbuild /Users/dbuenzli/.opam/doc/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /Users/dbuenzli/.opam/doc/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
File "_tags", line 6, characters 44-60:
Warning: the tag "link_consts_stub" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 11, characters 16-30:
Warning: the tag "sdl_consts_dep" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
ocamlfind ocamldep -modules test/test.ml > test/test.ml.depends
ocamlfind ocamldep -modules test/fmts.ml > test/fmts.ml.depends
ocamlfind ocamldep -package ctypes -modules src/tsdl.mli > src/tsdl.mli.depends
ocamlfind ocamlc -c -g -annot -bin-annot -thread -package ctypes -I src -I test -I support -o src/tsdl.cmi src/tsdl.mli
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I test -I support -I src -o test/fmts.cmo test/fmts.ml
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I test -I support -I src -o test/test.cmo test/test.ml
ocamlfind ocamldep -package ctypes -modules src/tsdl.ml > src/tsdl.ml.depends
ocamlfind ocamldep -modules support/consts.ml > support/consts.ml.depends
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I support -I test -I src -o support/consts.cmo support/consts.ml
ocamlfind ocamlc -ccopt -DHAS_SDL2 -ccopt -D_THREAD_SAFE -ccopt -I/usr/local/include/SDL2 -c support/consts_stub.c
mv consts_stub.o support/consts_stub.o
ocamlfind ocamlc -linkpkg -g -custom -thread support/consts.cmo support/consts_stub.o -o support/consts.byte
support/consts.byte src/tsdl_consts.ml
ocamlfind ocamldep -modules src/tsdl_consts.ml > src/tsdl_consts.ml.depends
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I src -I test -I support -o src/tsdl_consts.cmo src/tsdl_consts.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -I src -I test -I support -o src/tsdl_consts.cmx src/tsdl_consts.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -package ctypes -I src -I test -I support -o src/tsdl.cmx src/tsdl.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -I test -I support -I src -o test/fmts.cmx test/fmts.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -I test -I support -I src -o test/test.cmx test/test.ml
ocamlfind ocamldep -modules test/min.ml > test/min.ml.depends
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I test -I support -I src -o test/min.cmo test/min.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -I test -I support -I src -o test/min.cmx test/min.ml
ocamlfind ocamldep -modules test/sdlevents.ml > test/sdlevents.ml.depends
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I test -I support -I src -o test/sdlevents.cmo test/sdlevents.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -I test -I support -I src -o test/sdlevents.cmx test/sdlevents.ml
ocamlfind ocamlopt -linkpkg -g -thread -ccopt -L/usr/local/lib -cclib -lSDL2 -package ctypes -package ctypes.foreign src/tsdl_consts.cmx src/tsdl.cmx test/fmts.cmx test/test.cmx -o test/test.native
+ ocamlfind ocamlopt -linkpkg -g -thread -ccopt -L/usr/local/lib -cclib -lSDL2 -package ctypes -package ctypes.foreign src/tsdl_consts.cmx src/tsdl.cmx test/fmts.cmx test/test.cmx -o test/test.native
File "_none_", line 1:
Error: Files src/tsdl.cmx
       and /Users/dbuenzli/.opam/doc/lib/ctypes/ctypes-foreign-threaded.cmxa
       make inconsistent assumptions over interface Foreign
Command exited with code 2.

```

**Comment by dbuenzli** [comment]
So where is that Foreign `ctypes-foreign-threaded.cmxa` talks about ? 

```
> ocamlobjinfo _build/src/tsdl.cmx | grep Foreign 
	36133f831957d7490991ccca9ed43195	Foreign
	--------------------------------	Foreign
> ocamlobjinfo /Users/dbuenzli/.opam/doc/lib/ctypes/ctypes-foreign-threaded.cmxa | grep Foreign
Name: Foreign
	Foreign
	bc48990fc1c79fd866d010fe185c736a	Foreign
> ocamlobjinfo /Users/dbuenzli/.opam/doc/lib/ctypes/foreign.cmi | grep Foreign 
Unit name: Foreign
	36133f831957d7490991ccca9ed43195	Foreign
```
I suspect there's a problem with ctypes' install.

**Comment by yallop** [comment]
Interesting.  I can build tsdl and its tests here without problems:

```
$ git clone https://github.com/dbuenzli/tsdl.git
git clone https://github.com/dbuenzli/tsdl.git
Cloning into 'tsdl'...
remote: Counting objects: 312, done.        
remote: Compressing objects: 100% (29/29), done.        
remote: Total 312 (delta 6), reused 0 (delta 0), pack-reused 283        
Receiving objects: 100% (312/312), 237.96 KiB | 0 bytes/s, done.
Resolving deltas: 100% (184/184), done.
Checking connectivity... done.
```

```
$ opam install ctypes.0.4.0 ctypes-foreign.0.4.0
opam install ctypes.0.4.0 ctypes-foreign.0.4.0
The following actions will be performed:
  ∗  install ctypes-foreign 0.4.0
  ∗  install ctypes         0.4.0
===== ∗  2 =====

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed ctypes-foreign.0.4.0
∗  installed ctypes.0.4.0
Done.
```

```
$ cd tsdl/
cd tsdl/
```

```
$ ocaml pkg/git.ml 
ocaml pkg/git.ml 
File "pkg/topkg-ext.ml", line 42, characters 12-25:
Warning 3: deprecated: String.create
Use Bytes.create instead.
```

```
$ ocaml pkg/build.ml  native=true native-dynlink=true
ocaml pkg/build.ml  native=true native-dynlink=true
ocamlfind ocamlopt unix.cmxa -I /home/jeremy/.opam/4.02.1/lib/ocaml/ocamlbuild /home/jeremy/.opam/4.02.1/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /home/jeremy/.opam/4.02.1/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
File "_tags", line 6, characters 44-60:
Warning: the tag "link_consts_stub" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 11, characters 16-30:
Warning: the tag "sdl_consts_dep" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
ocamlfind ocamldep -modules support/consts.ml > support/consts.ml.depends
ocamlfind ocamlc -c -bin-annot -thread -I support -I src -I test -o support/consts.cmo support/consts.ml
ocamlfind ocamlc -ccopt -DHAS_SDL2 -ccopt -D_REENTRANT -ccopt -I/usr/include/SDL2 -c support/consts_stub.c
mv consts_stub.o support/consts_stub.o
ocamlfind ocamlc -linkpkg -custom -thread support/consts.cmo support/consts_stub.o -o support/consts.byte
support/consts.byte src/tsdl_consts.ml
ocamlfind ocamldep -modules src/tsdl_consts.ml > src/tsdl_consts.ml.depends
ocamlfind ocamlc -c -bin-annot -thread -I src -I support -I test -o src/tsdl_consts.cmo src/tsdl_consts.ml
ocamlfind ocamldep -package ctypes -modules src/tsdl.ml > src/tsdl.ml.depends
ocamlfind ocamldep -package ctypes -modules src/tsdl.mli > src/tsdl.mli.depends
ocamlfind ocamlc -c -bin-annot -thread -package ctypes -I src -I support -I test -o src/tsdl.cmi src/tsdl.mli
ocamlfind ocamlopt -c -bin-annot -thread -I src -I support -I test -o src/tsdl_consts.cmx src/tsdl_consts.ml
ocamlfind ocamlopt -c -bin-annot -thread -package ctypes -I src -I support -I test -o src/tsdl.cmx src/tsdl.ml
ocamlfind ocamlopt -a -thread -ccopt -Wl,-no-as-needed -cclib -lSDL2 -package ctypes -package ctypes.foreign src/tsdl_consts.cmx src/tsdl.cmx -o src/tsdl.cmxa
ocamlfind ocamlc -c -bin-annot -thread -package ctypes -I src -I support -I test -o src/tsdl.cmo src/tsdl.ml
ocamlfind ocamlc -a -custom -thread -ccopt -Wl,-no-as-needed -cclib -lSDL2 -dllib -ltsdl -package ctypes -package ctypes.foreign src/tsdl_consts.cmo src/tsdl.cmo -o src/tsdl.cma
ocamlfind ocamlopt -shared -thread -ccopt -Wl,-no-as-needed -cclib -lSDL2 -package ctypes -package ctypes.foreign src/tsdl.cmx -o src/tsdl.cmxs
ocamlfind ocamldep -package compiler-libs.toplevel -modules src/tsdl_top.ml > src/tsdl_top.ml.depends
ocamlfind ocamlc -c -bin-annot -thread -package compiler-libs.toplevel -I src -I support -I test -o src/tsdl_top.cmo src/tsdl_top.ml
+ ocamlfind ocamlc -c -bin-annot -thread -package compiler-libs.toplevel -I src -I support -I test -o src/tsdl_top.cmo src/tsdl_top.ml
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/jeremy/.opam/4.02.1/lib/ocaml/compiler-libs, /home/jeremy/.opam/4.02.1/lib/ocaml
ocamlfind ocamlopt -c -bin-annot -thread -package compiler-libs.toplevel -I src -I support -I test -o src/tsdl_top.cmx src/tsdl_top.ml
+ ocamlfind ocamlopt -c -bin-annot -thread -package compiler-libs.toplevel -I src -I support -I test -o src/tsdl_top.cmx src/tsdl_top.ml
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/jeremy/.opam/4.02.1/lib/ocaml/compiler-libs, /home/jeremy/.opam/4.02.1/lib/ocaml
ocamlfind ocamlopt -a -thread -package compiler-libs.toplevel src/tsdl_top.cmx -o src/tsdl_top.cmxa
+ ocamlfind ocamlopt -a -thread -package compiler-libs.toplevel src/tsdl_top.cmx -o src/tsdl_top.cmxa
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/jeremy/.opam/4.02.1/lib/ocaml/compiler-libs, /home/jeremy/.opam/4.02.1/lib/ocaml
ocamlfind ocamlc -a -thread -package compiler-libs.toplevel src/tsdl_top.cmo -o src/tsdl_top.cma
+ ocamlfind ocamlc -a -thread -package compiler-libs.toplevel src/tsdl_top.cmo -o src/tsdl_top.cma
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/jeremy/.opam/4.02.1/lib/ocaml/compiler-libs, /home/jeremy/.opam/4.02.1/lib/ocaml
ocamlfind ocamlopt -shared -thread -package compiler-libs.toplevel src/tsdl_top.cmx -o src/tsdl_top.cmxs
+ ocamlfind ocamlopt -shared -thread -package compiler-libs.toplevel src/tsdl_top.cmx -o src/tsdl_top.cmxs
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/jeremy/.opam/4.02.1/lib/ocaml/compiler-libs, /home/jeremy/.opam/4.02.1/lib/ocaml
ocamlfind ocamlc -c src/tsdl_stubs.c
mv tsdl_stubs.o src/tsdl_stubs.o
ocamlfind ocamlmklib -o src/tsdl -ldopt -Wl,-no-as-needed -lSDL2 src/tsdl_stubs.o
```

```
$ ./build tests.otarget
./build tests.otarget
File "_tags", line 6, characters 44-60:
Warning: the tag "link_consts_stub" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 11, characters 16-30:
Warning: the tag "sdl_consts_dep" is not used in any flag declaration, so it will have no effect; it may be a typo. Otherwise use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
ocamlfind ocamldep -modules test/test.ml > test/test.ml.depends
ocamlfind ocamldep -modules test/fmts.ml > test/fmts.ml.depends
ocamlfind ocamlc -c -g -annot -bin-annot -thread -package ctypes -I src -I support -I test -o src/tsdl.cmi src/tsdl.mli
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I test -I support -I src -o test/fmts.cmo test/fmts.ml
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I test -I support -I src -o test/test.cmo test/test.ml
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I support -I src -I test -o support/consts.cmo support/consts.ml
ocamlfind ocamlc -linkpkg -g -custom -thread support/consts.cmo support/consts_stub.o -o support/consts.byte
support/consts.byte src/tsdl_consts.ml
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I src -I support -I test -o src/tsdl_consts.cmo src/tsdl_consts.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -I src -I support -I test -o src/tsdl_consts.cmx src/tsdl_consts.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -package ctypes -I src -I support -I test -o src/tsdl.cmx src/tsdl.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -I test -I support -I src -o test/fmts.cmx test/fmts.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -I test -I support -I src -o test/test.cmx test/test.ml
ocamlfind ocamldep -modules test/min.ml > test/min.ml.depends
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I test -I support -I src -o test/min.cmo test/min.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -I test -I support -I src -o test/min.cmx test/min.ml
ocamlfind ocamldep -modules test/sdlevents.ml > test/sdlevents.ml.depends
ocamlfind ocamlc -c -g -annot -bin-annot -thread -I test -I support -I src -o test/sdlevents.cmo test/sdlevents.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -thread -I test -I support -I src -o test/sdlevents.cmx test/sdlevents.ml
ocamlfind ocamlopt -linkpkg -g -thread -ccopt -Wl,-no-as-needed -cclib -lSDL2 -package ctypes -package ctypes.foreign src/tsdl_consts.cmx src/tsdl.cmx test/fmts.cmx test/test.cmx -o test/test.native
ocamlfind ocamlopt -linkpkg -g -thread -ccopt -Wl,-no-as-needed -cclib -lSDL2 -package ctypes -package ctypes.foreign src/tsdl_consts.cmx src/tsdl.cmx test/min.cmx -o test/min.native
ocamlfind ocamlopt -linkpkg -g -thread -ccopt -Wl,-no-as-needed -cclib -lSDL2 -package ctypes -package ctypes.foreign src/tsdl_consts.cmx src/tsdl.cmx test/fmts.cmx test/sdlevents.cmx -o test/sdlevents.native
ln -sf /tmp/tsdl/_build/test/test.native ..
ln -sf /tmp/tsdl/_build/test/min.native ..
ln -sf /tmp/tsdl/_build/test/sdlevents.native ..
```

**Comment by dbuenzli** [comment]
I see you are on linux, this is on osx, the question is shouldn't these two hashes be equal ? 

```
> ocamlobjinfo /Users/dbuenzli/.opam/doc/lib/ctypes/ctypes-foreign-threaded.cmxa | grep Foreign
Name: Foreign
	Foreign
	bc48990fc1c79fd866d010fe185c736a	Foreign
> ocamlobjinfo /Users/dbuenzli/.opam/doc/lib/ctypes/foreign.cmi | grep Foreign 
Unit name: Foreign
	36133f831957d7490991ccca9ed43195	Foreign

```

**Comment by yallop** [comment]
Yes.  They're the same for me.

```
$ ocamlobjinfo $(ocamlfind query ctypes)/foreign.cmi | grep Foreign
Unit name: Foreign
	97e9a6775c0c6bbbbdac55d53da2afec	Foreign
$ ocamlobjinfo $(ocamlfind query ctypes)/ctypes-foreign-unthreaded.cmxa | grep Foreign
Name: Foreign
	Foreign
	97e9a6775c0c6bbbbdac55d53da2afec	Foreign
$ ocamlobjinfo $(ocamlfind query ctypes)/ctypes-foreign-threaded.cmxa | grep Foreign
Name: Foreign
	Foreign
	97e9a6775c0c6bbbbdac55d53da2afec	Foreign
```

It does look like there's an installation problem.

**Comment by dbuenzli** [comment]
Ok, I'll post you ctypes install log.

**Comment by dbuenzli** [comment]
Continue discussion on ctypes's bt.

**Comment by avsm** [comment]
I'm merging this one as it's clearly correct.

**Pull request merged**
