### PR TITLE
frenetic.3.0.0: only enable async if cmdliner is present

### PR DESCRIPTION
**Pull request by planar**

### CODE REVIEW

**Comment by avsm** [comment]
Missing an async version constraint I think

```
# File "async/discovery.ml", line 99, characters 30-67:
# Error: This expression should not be a function, the expected type is
# PortSet.t
# Command exited with code 2.
```

/cc @natefoster

**Comment by planar** [comment]
Not `async`... I tried `async.112.24.00` (as in the Travis build) with `frenetic.3.0.0` and it worked. I'll have to investigate.

**Comment by planar** [comment]
Not `async` but `topology`. Maybe also another. We'll see what Travis does with this.

**Comment by planar** [comment]
After much experimenting, I found out that `frenetic.3.0.0` only works with `core` >= 112.06.00 if `cmdliner` is absent.

I don't know how to express this constraint. I've tried the obvious:
```
conflicts: [
  "cmdliner" & "core" {>= "112.06.00"}
]
```
But `opam` just tells me that `frenetic.3.0.0` is in conflict with all versions of `cmdliner`, regardless of `core` versions.

**Comment by planar** [comment]
@samoht Do you have a magic incantation for this case?

**Comment by samoht** [comment]
I don't think so. This seems similar to the negative predicate that we need in mirage: https://github.com/ocaml/opam/issues/2074#issuecomment-96608153

we "fixed" that by using a `mirage-no-xen` package in the (more expressive) `depends` field. So this could be solved by adding `no-cmldiner` package but that's extremely ugly... @AltGr or @rdicosmo do you have a better idea?

**Comment by planar** [comment]
> So this could be solved by adding `no-cmdliner` package but that's extremely ugly.

I don't think it's worth the trouble for what is an old version of `frenetic`. If there's no way to express the exact dependency, I'll just declare a conflict with `"core" {>= "112.06.00"}`.

**Comment by samoht** [comment]
Closing as there is no good way to fix the dependency issue.

**Comment by planar** [comment]
Reopening with the second-best solution.

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
