### PR TITLE
Add openblas depext for freebsd

### PR DESCRIPTION
**Pull request by mseri**
Spotted on https://github.com/ocaml/opam-repository/pull/17349

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>

### CODE REVIEW

**Comment by mseri** [comment]
I don't have access to freeBSD to check if I need to specify a specific include\library path

**Comment by mseri** [comment]
Thanks! Let's see how it goes. Unless they have changed policy, Fedora, RH and Centos had removed the pkg-config configuration for openblas a few releases back.

**Comment by kit-ty-kate** [comment]
> Thanks! Let's see how it goes. Unless they have changed policy, Fedora, RH and Centos had removed the pkg-config configuration for openblas a few releases back.

oh :/ arf, I see. Looking at the package content on fedora it indeed doesn't have any pkg-config file :( I'll put back the file with some tweaks

**Comment by mseri** [comment]
Yeah, the portability of blas/lapack is a nightmare... If one day I will have the time, I plan to modify owl to bundle its own version

**Comment by mseri** [comment]
It's green!!!!

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
