### PR TITLE
modelica_ml.0.1.1 - via opam-publish

### PR DESCRIPTION
**Pull request by choeger**
Modelica abstract syntax and parser

Modelica.ml is a Modelica frontend implemented in OCaml. It is written with compilation in mind, but should also be useful for other applications. Currently, only abstract syntax, parsing and pretty printing are implemented. Patches welcome!

---
* Homepage: https://github.com/choeger/modelica.ml
* Source repo: https://github.com/choeger/modelica.ml.git
* Bug tracker: https://github.com/choeger/modelica.ml/issues

---
Pull-request generated by opam-publish v0.2.1

### CODE REVIEW

**Comment by choeger** [comment]
It seems the build failed on opam 1.1 due to some problem with ppx_deriving. What now?

**Comment by AltGr** [comment]
Indeed, this is an issue with `ppx_deriving`, and there should be no trouble otherwise for merging this.

`ppx_deriving` uses `version = "%{version}%"` in `pkg/META.in`, which is perfectly valid in 1.2 because it will default to `%{<current-package>:version}%`, but it wasn't accepted yet in 1.1.

**Comment by camlspotter** [comment]
I got the same trouble: https://github.com/ocaml/opam-repository/issues/3395

What should we do? Is there a way to declare the minimum `opam` version in `opam` file? And should it be declared in the `opam` file of `ppx_deriving`, or of packages which use `ppx_deriving`?

I am bit confused: why `ppx_deriving.1.1` could pass this Travis check and merged into trunk?

**Comment by yallop** [comment]
I'm restarting the failed Travis build now that #3397 is merged.

**Pull request merged**
