### PR TITLE
[new release] bimage, bimage-unix, bimage-gtk and bimage-sdl (0.2.1)

### PR DESCRIPTION
**Pull request by zshipko**
A simple, efficient image-processing library

- Project page: <a href="https://github.com/zshipko/ocaml-bimage">https://github.com/zshipko/ocaml-bimage</a>
- Documentation: <a href="https://zshipko.github.io/ocaml-bimage/doc">https://zshipko.github.io/ocaml-bimage/doc</a>

##### CHANGES:

- Add Func Expr
- Rewrite ops as exprs
- Update stb-image/stb-image-write

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I just fixed a missing dependency in `bimage-sdl`.
```
#=== ERROR while compiling bimage-sdl.0.2.1 ===================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/zshipko/ocaml-bimage/releases/download/v0.2.1/bimage-v0.2.1.tbz)
# path                 ~/.opam/4.07/.opam-switch/build/bimage-sdl.0.2.1
# command              ~/.opam/4.07/bin/dune runtest -p bimage-sdl
# exit-code            1
# env-file             ~/.opam/log/bimage-sdl-29-ffb3fd.env
# output-file          ~/.opam/log/bimage-sdl-29-ffb3fd.out
### output ###
# File "test/dune", line 2, characters 12-23:
# 2 |  (libraries bimage-unix)
#                 ^^^^^^^^^^^
# Error: Library "bimage-unix" not found.
# Hint: try: dune external-lib-deps --missing -p bimage-sdl @runtest
```
Also would it be ok to change all the constraint dependencies to sub-packages to be `{= version}` instead of `{>= "0.1"}`. I see in the revdeps that previous versions don't seem to be compatible the newer ones

**Comment by zshipko** [comment]
Awesome, thank you! I wasn't aware of `{= version}` and forgot to update that field

**Comment by zshipko** [comment]
Actually, I noticed that `bimage-sdl` shouldn't even be running those tests. I made some updates, including the version one you mentioned. Let me know if there are any issues.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
