### PR TITLE
Release xapi-rrd 1.0.1, using the ppx derivers for rpc

### PR DESCRIPTION
**Pull request by mseri**
This should fix some random issues with the `xapi-rrd` package failing to find the `Jsonrpc` implementation.

Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

### CODE REVIEW

**Comment by avsm** [comment]
could you merge this with the master branch of opam-repository, so that the shared-block-ring fix in #9509 will be available? thanks!

**Comment by mseri** [comment]
Are you sure that ' {<= "1.0.0"}' is correct there? Shouldn't it be >=?

**Comment by avsm** [comment]
@mseri who was that last comment aimed at, and which package? :-)

i have fixed a shared-block-ring 2.3 failure in #9542

**Comment by mseri** [comment]
@avsm ops, sorry. I was talking about shared block ring, the line `"mirage-clock-unix" {<= "1.0.0"}` specifically. It seemed to me that `mirage-clock-unix` was introduced in `1.0.0`, I was asking about the `<=` there. I will wait for your PR to be merged and rebase on master again.

**Comment by avsm** [comment]
sounds good -- #9542 is merged now :)

**Comment by mseri** [comment]
@avsm I am not sure what to do about the few remaining failures: 

- `jitsu-xapi` fails installing an older version of `xen-api-client` (due to the constraints I guess), I thought that  updating the constraints in `xen-api-client` would solve the issue but only changed the error message.

- `xapi-rrd-transport` is failing because of `xen-gnt` missing the unix subpackage and only in a couple of cases, I don't know what to do to fix that (https://ci.ocaml.io/log/saved/docker-build-bc87d6c27638105a73b858a5ed1d014d/af85260353dc9f5eee35aba7b3078eb9f0872ff5)

- `xapi-rrd` and `xen-api-client` are failing in a couple of cases because opam tries to install a very old version of async (that should be avoided due to the conflicts stanza in xen-api-client I believe) and fails to compile that specific dependency (https://ci.ocaml.io/log/saved/docker-build-77ce1f5b3e7e2013e7f3e340a3d1512b/499424317bd0c54d2dcc1ea3e0384ac646544b07, https://ci.ocaml.io/log/saved/docker-build-e15e7d8350d77a52236d7d0dfb8644f8/e3b38538b4100123497903c1fb25e3cb2ab2976f)

Do you have suggestions?

**Comment by avsm** [comment]
cc @djs55 re: xen-gnt

**Comment by djs55** [comment]
Re: `xen-gnt`: you're still using the old 2.2.3, probably because of version constraints somewhere else? There is an "unofficial" optional dependency on the `xenctrl.h` header (enforced by the `configure` script) but the `opam` format cannot express the notion of an optional dependency on an .rpm -- it would have to be a `depext` (breaking other users) or not a `depext` (breaking these cases):
```
- Looking for xenctrl.h: missing
- ocaml setup.ml -configure --disable-tests --disable-xenctrl
```
I think you can't really fix this with the old packages -- we just have to live with it.

For the future you should depend on `xen-gnt-unix` which, since it is a first class `opam` package, has an official `depext` in the `opam` file for `xen-devel` so it should just work.

**Comment by mseri** [comment]
Thanks! Looks like `xen-gnt-unix` does not contain breaking changes. Locally adding these two tiny patches and updating the opam files worked. Let's see if it does the trick here :crossed_fingers:

**Comment by mseri** [comment]
The xen-gnt problem is gone, thanks. The remaining failures are a conflict on systemd lib version in alpine that is out of control for me, and a failure in compiling an old version of async (this is funny because that version should be excluded by the conflicts requirements)

**Comment by avsm** [comment]
the rest of the problems can be fixed in a separate PR. thanks for this!

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
