### PR TITLE
Replace contact@ocamlpro.com maintainer email by github issue url.

### LINKED ISSUE #6864: New mail for no-maintainer packages
Hi,

   When OPAM was first released, we populated the repository with many packages with "contact@ocamlpro.com" as maintainer, with the hope that the community would take over the maintenance of all these packages. After a few years now, there are still a few of them that are orphans. As OCamlPro does not have the manpower to do the maintenance for these packages, and we keep receiving queries for that, I would like to change the maintainer email for these packages with a better one. A natural one would be one of the "platform" mailing-lists, for example "platform@lists.ocaml.org". Would it be ok ? Should I use another one ? Any suggestion welcome !

### PR DESCRIPTION
**Pull request by dbuenzli**
/cc @lefessan

The change was automated via: 
```
for f in $(git grep -l contact@ocamlpro.com | grep -v ocp); do opam-ed --inplace --preserve 'replace maintainer "https://github.com/ocaml/opam-repository/issues"' -f $f ; done
```
Closes #6864.

### CODE REVIEW

**Comment by dbuenzli** [comment]
I refined the PR to leave out `ocp-*` package from the change (see edited cli).

**Comment by avsm** [comment]
I suspect we should just remove the maintainer field if one doesn't exist...

**Comment by dbuenzli** [comment]
@avsm if you don't suspect but are sure I can change the PR. I just followed what people seemed to agree on in #6864.

**Comment by avsm** [comment]
Happy to go with this -- just thinking about how to remove redundant metadata in the future, but first we need to revise opam-lint to not error, and other similar changes.

**Comment by avsm** [comment]
thanks @dbuenzli !

**Pull request merged**
