### PR TITLE
toml.6.0 and toml_cconv.6.0

### PR DESCRIPTION
**Pull request by zapashcanon**
Hi,

As there has been no activity for two years on [To.ml](https://github.com/ocaml-toml/To.ml) and got no answer from the author after sending him an e-mail, we [forked](https://github.com/ocamlpro/toml) the repository. I guess it is OK to release the new version under the same name for the `toml` package ? For `toml-cconv` we renamed it `toml_cconv`.

I updated all rev-deps opam files to use `< "6.0"` as the structure of the library changed a bit.

### CODE REVIEW

**Comment by zapashcanon** [comment]
The failures are coming from other packages that are missing a lower bound on OCaml.

**Comment by avsm** [comment]
@c-cube, are you a maintainer of the original package? You were the last commit to the upstream repository.

**Comment by c-cube** [comment]
It seems I do have access to the repo. I forgot I did, apparently. @zapashcanon I could try to give you write access if you so wish.

**Comment by zapashcanon** [comment]
After discussing this in private with @c-cube I now have access to the ocaml-toml organization. I'm closing this and will open a new one.

**Comment by avsm** [comment]
Great, glad to see consensus here. Thanks very much indeed @c-cube @zapashcanon

**Pull request closed without merging**
