### PR TITLE
Release v0.16 of Core

### PR DESCRIPTION
**Pull request by dkalinichenko-js**
This PR adds Core v0.16 & dependencies.

### CODE REVIEW

**Comment by mseri** [comment]
Is this behaviour expected?
```
#=== ERROR while compiling sihl.0.1.9 =========================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/sihl.0.1.9
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p sihl -j 255 @install
# exit-code            1
# env-file             ~/.opam/log/sihl-7-a390c6.env
# output-file          ~/.opam/log/sihl-7-a390c6.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I sihl/core/.sihl_core.objs/byte -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/conformist -I /home/opam/.opam/5.0/lib/containers -I /home/opam/.opam/5.0/lib/containers/monomorphic -I /home/opam/.opam/5.0/lib/either -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/hmap -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/lwt/unix -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocplib-endian -I /home/opam/.opam/5.0/lib/ocplib-endian/bigstring -I /home/opam/.opam/5.0/lib/parsexp -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/sexplib -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/tsort -intf-suffix .ml -no-alias-deps -open Sihl_core__ -o sihl/core/.sihl_core.objs/byte/sihl_core__Command.cmo -c -impl sihl/core/command.ml)
# File "sihl/core/command.ml", line 41, characters 2-20:
# 41 |   Caml.print_endline
#        ^^^^^^^^^^^^^^^^^^
# Error: Unbound module Caml
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I sihl/core/.sihl_core.objs/byte -I sihl/core/.sihl_core.objs/native -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/conformist -I /home/opam/.opam/5.0/lib/containers -I /home/opam/.opam/5.0/lib/containers/monomorphic -I /home/opam/.opam/5.0/lib/either -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/hmap -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/lwt/unix -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocplib-endian -I /home/opam/.opam/5.0/lib/ocplib-endian/bigstring -I /home/opam/.opam/5.0/lib/parsexp -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/sexplib -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/tsort -intf-suffix .ml -no-alias-deps -open Sihl_core__ -o sihl/core/.sihl_core.objs/native/sihl_core__Command.cmx -c -impl sihl/core/command.ml)
# File "sihl/core/command.ml", line 41, characters 2-20:
# 41 |   Caml.print_endline
#        ^^^^^^^^^^^^^^^^^^
# Error: Unbound module Caml
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I sihl/core/.sihl_core.objs/byte -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/conformist -I /home/opam/.opam/5.0/lib/containers -I /home/opam/.opam/5.0/lib/containers/monomorphic -I /home/opam/.opam/5.0/lib/either -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/hmap -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/lwt/unix -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocplib-endian -I /home/opam/.opam/5.0/lib/ocplib-endian/bigstring -I /home/opam/.opam/5.0/lib/parsexp -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/sexplib -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/tsort -intf-suffix .ml -no-alias-deps -open Sihl_core__ -o sihl/core/.sihl_core.objs/byte/sihl_core__Random.cmo -c -impl sihl/core/random.ml)
# File "sihl/core/random.ml", line 1, characters 9-30:
# 1 | let () = Caml.Random.self_init ()
#              ^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Caml
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I sihl/core/.sihl_core.objs/byte -I sihl/core/.sihl_core.objs/native -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/conformist -I /home/opam/.opam/5.0/lib/containers -I /home/opam/.opam/5.0/lib/containers/monomorphic -I /home/opam/.opam/5.0/lib/either -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/hmap -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/lwt/unix -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocplib-endian -I /home/opam/.opam/5.0/lib/ocplib-endian/bigstring -I /home/opam/.opam/5.0/lib/parsexp -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/sexplib -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/tsort -intf-suffix .ml -no-alias-deps -open Sihl_core__ -o sihl/core/.sihl_core.objs/native/sihl_core__Random.cmx -c -impl sihl/core/random.ml)
# File "sihl/core/random.ml", line 1, characters 9-30:
# 1 | let () = Caml.Random.self_init ()
#              ^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Caml
[...]
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I sihl/user/.sihl_user.objs/byte -I /home/opam/.opam/5.0/lib/alcotest -I /home/opam/.opam/5.0/lib/alcotest/engine -I /home/opam/.opam/5.0/lib/alcotest/stdlib_ext -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/astring -I /home/opam/.opam/5.0/lib/base -I /home/opam/.opam/5.0/lib/base/base_internalhash_types -I /home/opam/.opam/5.0/lib/base/caml -I /home/opam/.opam/5.0/lib/base/shadow_stdlib -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/biniou -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/camlp-streams -I /home/opam/.opam/5.0/lib/caqti -I /home/opam/.opam/5.0/lib/caqti-lwt -I /home/opam/.opam/5.0/lib/cmdliner -I /home/opam/.opam/5.0/lib/conformist -I /home/opam/.opam/5.0/lib/containers -I /home/opam/.opam/5.0/lib/containers/monomorphic -I /home/opam/.opam/5.0/lib/digestif -I /home/opam/.opam/5.0/lib/easy-format -I /home/opam/.opam/5.0/lib/either -I /home/opam/.opam/5.0/lib/eqaf -I /home/opam/.opam/5.0/lib/fieldslib -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/hmap -I /home/opam/.opam/5.0/lib/jwto -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/lwt/unix -I /home/opam/.opam/5.0/lib/ocaml-compiler-libs/common -I /home/opam/.opam/5.0/lib/ocaml-compiler-libs/shadow -I /home/opam/.opam/5.0/lib/ocaml/compiler-libs -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocplib-endian -I /home/opam/.opam/5.0/lib/ocplib-endian/bigstring -I /home/opam/.opam/5.0/lib/parsexp -I /home/opam/.opam/5.0/lib/ppx_derivers -I /home/opam/.opam/5.0/lib/ppx_deriving/api -I /home/opam/.opam/5.0/lib/ppx_deriving/create -I /home/opam/.opam/5.0/lib/ppx_deriving/enum -I /home/opam/.opam/5.0/lib/ppx_deriving/eq -I /home/opam/.opam/5.0/lib/ppx_deriving/fold -I /home/opam/.opam/5.0/lib/ppx_deriving/iter -I /home/opam/.opam/5.0/lib/ppx_deriving/make -I /home/opam/.opam/5.0/lib/ppx_deriving/map -I /home/opam/.opam/5.0/lib/ppx_deriving/ord -I /home/opam/.opam/5.0/lib/ppx_deriving/runtime -I /home/opam/.opam/5.0/lib/ppx_deriving/show -I /home/opam/.opam/5.0/lib/ppx_deriving/std -I /home/opam/.opam/5.0/lib/ppx_deriving_yojson/runtime -I /home/opam/.opam/5.0/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.0/lib/ppxlib -I /home/opam/.opam/5.0/lib/ppxlib/ast -I /home/opam/.opam/5.0/lib/ppxlib/astlib -I /home/opam/.opam/5.0/lib/ppxlib/print_diff -I /home/opam/.opam/5.0/lib/ppxlib/stdppx -I /home/opam/.opam/5.0/lib/ppxlib/traverse_builtins -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/ptime/clock/os -I /home/opam/.opam/5.0/lib/re -I /home/opam/.opam/5.0/lib/re/str -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/safepass -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/sexplib -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/stdlib-shims -I /home/opam/.opam/5.0/lib/stringext -I /home/opam/.opam/5.0/lib/tsort -I /home/opam/.opam/5.0/lib/uri -I /home/opam/.opam/5.0/lib/uuidm -I /home/opam/.opam/5.0/lib/uutf -I /home/opam/.opam/5.0/lib/yojson -I sihl/core/.sihl_core.objs/byte -I sihl/database/.sihl_database.objs/byte -I sihl/migration/.sihl_migration.objs/byte -I sihl/repository/.sihl_repository.objs/byte -I sihl/token/.sihl_token.objs/byte -I sihl/utils/.sihl_utils.objs/byte -no-alias-deps -open Sihl_user__ -o sihl/user/.sihl_user.objs/byte/sihl_user.cmi -c -intf sihl/user/sihl_user.pp.mli)
# File "sihl/user/sihl_user.mli", line 31, characters 9-30:
# 31 | val pp : Caml.Format.formatter -> t -> unit
#               ^^^^^^^^^^^^^^^^^^^^^
# Alert deprecated: module Caml
# [since v0.16] use Stdlib instead of Caml
```

Same package, same compilation flags, but it shows both a deprecation warning and a failure for the same module.

**Comment by dkalinichenko-js** [comment]
`Caml` should be deprecated, not removed. The code must be broken due to some library reorganization. I remember getting this error in testing, I must have missed some versions of `sihl` to put version bounds on. I'll do it shortly.

**Comment by mseri** [comment]
Do you know why it sometimes fails as removed? Is it really a sihl issue or we may see it in other revdeps?

**Comment by mseri** [comment]
Please next time add the upper bounds in a separate PR so that we can merge them fast and avoid unnecessary rebuilds

**Comment by dkalinichenko-js** [comment]
I'm not sure, I think it may be due to the Core module not being open when it previously was. It's definitely not specific to sihl, but it should be relatively rare.

**Comment by avsm** [comment]
Looked through the previous run and it looks fine to go in; can fix any straggling upper bounds in a separate PR.  Thanks for the smaller PR this time around!  Now onto Core_extended and friends :-)

**Pull request merged**
