### PR TITLE
various patchs for Alt-Ergo 2.0.0

### PR DESCRIPTION
**Pull request by OCamlPro-Iguernlala**

### CODE REVIEW

**Comment by OCamlPro-Iguernlala** [comment]
@avsm @AltGr What's wrong with this PR ? Everything was fine a few days ago, and it was not merged while other PR were.

And now, all builds fail.

**Comment by avsm** [comment]
I've not had a chance to look at what these patches are for, why they're not upstream instead, and whether upstream knows about them and is ok with them if they are going to be patched into opam-repository directly.  Any explanations appreciated -- we prefer not to maintain ongoing patchsets in this repository directly if possible.

**Comment by OCamlPro-Iguernlala** [comment]
There are two patchs in configure and Makefile:
- the first one adds detection of num's installation path
- the second one replaces "echo"s in the Makefile by "printf" because of issues related to interpretation of "\n" on some systems.

These two patchs are already integrated upstream. And since I'm the maintenainer of the package and the soft, I'm ok with them :-)

**Comment by avsm** [comment]
Thanks for the clarification :)

**Pull request merged**
