### PR TITLE
Fix constraints in vg.0.9.0 to allow to use jsoo.3.0.0.

### PR DESCRIPTION
**Pull request by dbuenzli**

### CODE REVIEW

**Comment by dbuenzli** [comment]
Ping.

**Comment by avsm** [comment]
I'd prefer to fix this with something that doesn't make packages in the repository uninstallable...

**Comment by dbuenzli** [comment]
I don't have the time to look into that right now maybe @andrewray has an idea whether simply changing the metadata for these packages can unlock the situation without needing a release for `jsoo3` (unfortunately the whole process was not documented by the jsoo maintainers).

**Comment by andrewray** [comment]
I'm almost certain it can be fixed with some metadata changes.  I'll take a look.

**Comment by dbuenzli** [comment]
Closing this in favour of https://github.com/ocaml/opam-repository/pull/10198

**Pull request closed without merging**
