### PR TITLE
+ ocaml-mysql 1.2.2

### PR DESCRIPTION
**Pull request by ygrek**

### CODE REVIEW

**Comment by ygrek** [comment]
I guess build fails due to libmysqlclient-dev not present on current debian. Should use libmariadbclient-dev instead. The question is how to update conf-mysql - upgrade version or create alternative conf-mariadb package?

**Comment by samoht** [comment]
> I guess build fails due to libmysqlclient-dev not present on current debian. Should use libmariadbclient-dev instead. The question is how to update conf-mysql - upgrade version or create alternative conf-mariadb package?

Did that changed on every version of Debian?

**Comment by ygrek** [comment]
No, only in stretch (current stable). Previous stable (jessie) is using libmysqlclient-dev. ocaml-mysql will work with both (and I hate to have package uninstallable because of conf-* not up-to-date, in my opinion it should not be a fatal error, but a warning, or opam should have --force option to allow install anyway if deps fail).

**Comment by ygrek** [comment]
I have created conf-mariadb and made it alternative dependency for ocaml-mysql

**Comment by ygrek** [comment]
apparently conf-mariadb in homebrew doesn't provide mysql_config unlike all other mariadb development packages..

**Comment by samoht** [comment]
yes I saw that. Not necessary a blocking issue for merge ... but I am more concerned with Datakit CI which seems down...

**Comment by ygrek** [comment]
Please let me know if I need to do anything to get this merged

**Comment by ygrek** [comment]
`    apt-get install -qq -yy libmariadbclient-dev libmysqlclient-dev`

depext decides to install both.. Looks like it doesn't like alternatives much

**Comment by samoht** [comment]
@avsm @AltGr a good example on why we need better depexts.

I think I am ok to merge the package, although the situation is clearly not perfect. @ygrek as maintainer of the package, I will let you decide if having depext at all is a good idea in the present situation or not.

**Comment by ygrek** [comment]
I think I will remove dependency on conf-* and add install-fail message explaining situation until alternative depexts will be working

**Comment by AltGr** [comment]
Once I get [the detailed OS variables](https://github.com/ocaml/opam/issues/3058) (please check and report, I have had no feedback yet, which also means it remains low priority) sorted out, and the improved `depexts:` expressivity, you should be able to write something like:

    depexts: [
      "libmariadbclient-dev" { distribution = "debian" & dist-version >= "9" | distribution = "ubuntu" & ... }
      "libmysqlclient-dev" { distribution = "debian" & dist-version < "9" | ... }
      ...
    ]

This means not using the `conf` packages though (or a specific `mariadb-or-mysql` one). Being able to use `depends: [ "conf-mysql" | "conf-mariadb" ]` would be much more difficult, and require an advanced version of [the planned depexts design](https://github.com/ocaml/opam/blob/master/doc/design/depexts-plugins) : opam would need to check the depexts of all packages in advance, triaging through the host package manager the installed, available but not installed, and unavailable ones, then call its solver with the packages with unavailable depexts removed, and call the host package manager again on any remaining uninstalled ones.

This way, only the `conf-*db` package that is compatible with the system would be seen as available by opam's solver, and the right branch of the disjunction would get chosen: there is no way to do this without a preliminary query to the host PM.

All the difficulty, apart from having good depexts specification on the repo, remains in having reliable and fast interaction with the host PM, on all platforms. [opam-depext](https://github.com/ocaml/opam-depext) is still much simpler than that.

**Comment by ygrek** [comment]
I still feel this (describing system and system packages in opam files) goes in wrong direction (too many moving things). I don't have any constructive ideas how to solve the original problem. Maybe it is fine to aim for 95% working and fail in remaining exotic system setups. To me it seems that showing suggested depexts (it is already case iirc) and allowing to force install of packages (e.g. when conf-* package is wrong and user wants to compile binding anyway) would go long way.

**Pull request merged**
