### PR TITLE
[new release] tls, tls-mirage, tls-lwt and tls-async (0.17.1)

### PR DESCRIPTION
**Pull request by hannesm**
Transport Layer Security purely in OCaml

- Project page: <a href="https://github.com/mirleft/ocaml-tls">https://github.com/mirleft/ocaml-tls</a>
- Documentation: <a href="https://mirleft.github.io/ocaml-tls/doc">https://mirleft.github.io/ocaml-tls/doc</a>

##### CHANGES:

* tls-async: update to 0.16 series (mirleft/ocaml-tls#476 @tmcgilchrist, review by @torinnd)
* avoid Cstruct.copy (@hannesm)

### CODE REVIEW

**Comment by hannesm** [comment]
CI failures are unrelated (mostly "Cancelled")

**Comment by hannesm** [comment]
There's one failure that may be addressed in a separate PR by those who feel responsible for "core":

```
#=== ERROR while compiling core.v0.16.0 =======================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-variants.5.1.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/5.1/.opam-switch/build/core.v0.16.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p core -j 127
# exit-code            1
# env-file             ~/.opam/log/core-6-ca52bd.env
# output-file          ~/.opam/log/core-6-ca52bd.out
### output ###
# File "core/src/dune", line 11, characters 48-56:
# 11 |  (c_names bigstring_stubs md5_stubs array_stubs gc_stubs time_ns_stubs)
#                                                      ^^^^^^^^
# (cd _build/default/core/src && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_LARGEFILE64_SOURCE -g -I /home/opam/.opam/5.1/lib/ocaml -I /home/opam/.opam/5.1/lib/base -I /home/opam/.opam/5.1/lib/base/base_internalhash_types -I /home/opam/.opam/5.1/lib/base/caml -I /home/opam/.opam/5.1/lib/base/md5 -I /home/opam/.opam/5.1/lib/base/shadow_stdlib -I /home/opam/.opam/5.1/lib/base_bigstring -I /home/opam/.opam/5.1/lib/base_quickcheck -I /home/opam/.opam/5.1/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/opam/.opam/5.1/lib/bin_prot -I /home/opam/.opam/5.1/lib/bin_prot/shape -I /home/opam/.opam/5.1/lib/fieldslib -I /home/opam/.opam/5.1/lib/int_repr -I /home/opam/.opam/5.1/lib/jane-street-headers -I /home/opam/.opam/5.1/lib/parsexp -I /home/opam/.opam/5.1/lib/ppx_assert/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_bench/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_compare/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_expect/collector -I /home/opam/.opam/5.1/lib/ppx_expect/common -I /home/opam/.opam/5.1/lib/ppx_expect/config -I /home/opam/.opam/5.1/lib/ppx_expect/config_types -I /home/opam/.opam/5.1/lib/ppx_hash/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_here/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_inline_test/config -I /home/opam/.opam/5.1/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_log/types -I /home/opam/.opam/5.1/lib/ppx_module_timer/runtime -I /home/opam/.opam/5.1/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_stable_witness/runtime -I /home/opam/.opam/5.1/lib/ppx_stable_witness/stable_witness -I /home/opam/.opam/5.1/lib/sexplib -I /home/opam/.opam/5.1/lib/sexplib0 -I /home/opam/.opam/5.1/lib/splittable_random -I /home/opam/.opam/5.1/lib/stdio -I /home/opam/.opam/5.1/lib/time_now -I /home/opam/.opam/5.1/lib/typerep -I /home/opam/.opam/5.1/lib/variantslib -I ../../base_for_tests/src -I ../../command/src -I ../../filename_base/src -I ../../heap_block -I ../../univ_map/src -I ../../validate/src -o gc_stubs.o -c gc_stubs.c)
# In file included from /home/opam/.opam/5.1/lib/ocaml/caml/fail.h:24,
#                  from gc_stubs.c:2:
# gc_stubs.c: In function 'core_gc_minor_collections':
# gc_stubs.c:34:19: error: 'caml_stat_minor_collections' undeclared (first use in this function); did you mean 'caml_stat_major_collections'?
#    34 |   return Val_long(caml_stat_minor_collections);
#       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
# /home/opam/.opam/5.1/lib/ocaml/caml/mlvalues.h:76:47: note: in definition of macro 'Val_long'
#    76 | #define Val_long(x)     ((intnat) (((uintnat)(x) << 1)) + 1)
#       |                                               ^
# gc_stubs.c:34:19: note: each undeclared identifier is reported only once for each function it appears in
#    34 |   return Val_long(caml_stat_minor_collections);
#       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
# /home/opam/.opam/5.1/lib/ocaml/caml/mlvalues.h:76:47: note: in definition of macro 'Val_long'
#    76 | #define Val_long(x)     ((intnat) (((uintnat)(x) << 1)) + 1)
#       |                                               ^
# (cd _build/default && /home/opam/.opam/5.1/bin/ocamlc.opt -w -40 -g -bin-annot -I core/src/.core.objs/byte -I /home/opam/.opam/5.1/lib/base -I /home/opam/.opam/5.1/lib/base/base_internalhash_types -I /home/opam/.opam/5.1/lib/base/caml -I /home/opam/.opam/5.1/lib/base/md5 -I /home/opam/.opam/5.1/lib/base/shadow_stdlib -I /home/opam/.opam/5.1/lib/base_bigstring -I /home/opam/.opam/5.1/lib/base_quickcheck -I /home/opam/.opam/5.1/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/opam/.opam/5.1/lib/bin_prot -I /home/opam/.opam/5.1/lib/bin_prot/shape -I /home/opam/.opam/5.1/lib/fieldslib -I /home/opam/.opam/5.1/lib/int_repr -I /home/opam/.opam/5.1/lib/jane-street-headers -I /home/opam/.opam/5.1/lib/parsexp -I /home/opam/.opam/5.1/lib/ppx_assert/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_bench/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_compare/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_expect/collector -I /home/opam/.opam/5.1/lib/ppx_expect/common -I /home/opam/.opam/5.1/lib/ppx_expect/config -I /home/opam/.opam/5.1/lib/ppx_expect/config_types -I /home/opam/.opam/5.1/lib/ppx_hash/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_here/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_inline_test/config -I /home/opam/.opam/5.1/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_log/types -I /home/opam/.opam/5.1/lib/ppx_module_timer/runtime -I /home/opam/.opam/5.1/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_stable_witness/runtime -I /home/opam/.opam/5.1/lib/ppx_stable_witness/stable_witness -I /home/opam/.opam/5.1/lib/sexplib -I /home/opam/.opam/5.1/lib/sexplib0 -I /home/opam/.opam/5.1/lib/splittable_random -I /home/opam/.opam/5.1/lib/stdio -I /home/opam/.opam/5.1/lib/time_now -I /home/opam/.opam/5.1/lib/typerep -I /home/opam/.opam/5.1/lib/variantslib -I base_for_tests/src/.base_for_tests.objs/byte -I command/src/.command.objs/byte -I filename_base/src/.filename_base.objs/byte -I heap_block/.heap_block.objs/byte -I univ_map/src/.univ_map.objs/byte -I validate/src/.validate.objs/byte -intf-suffix .ml -no-alias-deps -open Core__ -o core/src/.core.objs/byte/core__String_id.cmo -c -impl core/src/string_id.pp.ml)
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# 
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# 
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# 
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# 
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# 
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# (cd _build/default && /home/opam/.opam/5.1/bin/ocamlopt.opt -w -40 -g -I core/src/.core.objs/byte -I core/src/.core.objs/native -I /home/opam/.opam/5.1/lib/base -I /home/opam/.opam/5.1/lib/base/base_internalhash_types -I /home/opam/.opam/5.1/lib/base/caml -I /home/opam/.opam/5.1/lib/base/md5 -I /home/opam/.opam/5.1/lib/base/shadow_stdlib -I /home/opam/.opam/5.1/lib/base_bigstring -I /home/opam/.opam/5.1/lib/base_quickcheck -I /home/opam/.opam/5.1/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/opam/.opam/5.1/lib/bin_prot -I /home/opam/.opam/5.1/lib/bin_prot/shape -I /home/opam/.opam/5.1/lib/fieldslib -I /home/opam/.opam/5.1/lib/int_repr -I /home/opam/.opam/5.1/lib/jane-street-headers -I /home/opam/.opam/5.1/lib/parsexp -I /home/opam/.opam/5.1/lib/ppx_assert/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_bench/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_compare/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_expect/collector -I /home/opam/.opam/5.1/lib/ppx_expect/common -I /home/opam/.opam/5.1/lib/ppx_expect/config -I /home/opam/.opam/5.1/lib/ppx_expect/config_types -I /home/opam/.opam/5.1/lib/ppx_hash/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_here/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_inline_test/config -I /home/opam/.opam/5.1/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_log/types -I /home/opam/.opam/5.1/lib/ppx_module_timer/runtime -I /home/opam/.opam/5.1/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.1/lib/ppx_stable_witness/runtime -I /home/opam/.opam/5.1/lib/ppx_stable_witness/stable_witness -I /home/opam/.opam/5.1/lib/sexplib -I /home/opam/.opam/5.1/lib/sexplib0 -I /home/opam/.opam/5.1/lib/splittable_random -I /home/opam/.opam/5.1/lib/stdio -I /home/opam/.opam/5.1/lib/time_now -I /home/opam/.opam/5.1/lib/typerep -I /home/opam/.opam/5.1/lib/variantslib -I base_for_tests/src/.base_for_tests.objs/byte -I base_for_tests/src/.base_for_tests.objs/native -I command/src/.command.objs/byte -I command/src/.command.objs/native -I filename_base/src/.filename_base.objs/byte -I filename_base/src/.filename_base.objs/native -I heap_block/.heap_block.objs/byte -I heap_block/.heap_block.objs/native -I univ_map/src/.univ_map.objs/byte -I univ_map/src/.univ_map.objs/native -I validate/src/.validate.objs/byte -I validate/src/.validate.objs/native -intf-suffix .ml -no-alias-deps -open Core__ -o core/src/.core.objs/native/core__String_id.cmx -c -impl core/src/string_id.pp.ml)
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# 
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# 
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# 
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# 
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
# 
# File "_none_", line 1:
# Warning 73 [generative-application-expects-unit]: A generative functor
# should be applied to '()'; using '(struct end)' is deprecated.
```

So, eventually the core 0.16.0 needs an upper bound on OCaml. This has been discovered by @tmcgilchrist in https://github.com/mirleft/ocaml-tls/pull/477 (and previously https://github.com/mirleft/ocaml-tls/pull/476) -- but I won't include random constraints to tls-async; they rather belong to the `core` package.

**Comment by hannesm** [comment]
..and I can't spot which CI is still in process... as said earlier, ready to be merged :)

**Comment by dkalinichenko-js** [comment]
This used Core v0.16.0 for some reason, Core v0.16.1 should fix this.

**Comment by samoht** [comment]
> Need to add a version bound on Core v0.16.0.

Probably better to make 0.16.0 unavailable on OCaml 5?

**Comment by mseri** [comment]
Only 5.1 is affected in principle

**Comment by tmcgilchrist** [comment]
> I won't include random constraints to tls-async; they rather belong to the core package.

I've come around to this point of view, I think core v0.16.0 should be marked as unavailable on 5.1 and force it to use v0.16.1. Too many of my core/async dependencies are now broken because of this.

**Comment by dkalinichenko-js** [comment]
> Need to add a version bound on Core v0.16.0.

This was meant for me (to stop v0.16.0 being available on 5.1), sorry for the miscommunication!

**Comment by mseri** [comment]
As long as my fix is fine with you, that was not a problem whatsoever

**Pull request merged**
