### PR TITLE
ppx_deriving: adjust lower bound on cppo version

### PR DESCRIPTION
**Pull request by damiendoligez**

### CODE REVIEW

**Comment by dsheets** [comment]
This seems surprising. They really don't work with 4.02.3?

**Comment by whitequark** [comment]
@damiendoligez That shouldn't be the case. What prompts this PR?

**Comment by damiendoligez** [comment]
Indeed I made a mistake, the problem is not with OCaml but with old versions of `cppo`. I've updated the PR accordingly.

**Pull request merged**
