### PR TITLE
+async_ssl 112.24.02

### PR DESCRIPTION
**Pull request by trefis**
Fixes janestreet/async_ssl#2 .
Also makes the package unavailable on OS X until janestreet/async_ssl#3 is resolved.

In this case, the two previous versions of the package are clearly broken. Should I remove them?

### CODE REVIEW

**Comment by avsm** [comment]
Yeah I think removing the previous two packages is safest, since there's no conceivable use for them.

**Comment by trefis** [comment]
Done.

**Comment by avsm** [comment]
@AltGr any idea what the 1.1 failures here are?

**Comment by trefis** [comment]
Ping :)

**Comment by yallop** [comment]
I think you need to bump the opam-version field to 1.2, since 1.1 doesn't support '!='.

**Comment by yallop** [comment]
Thanks.

**Pull request merged**
