### PR TITLE
Package curses.1.0.7

### PR DESCRIPTION
**Pull request by mbacarella**
### `curses.1.0.7`
Bindings to curses/ncurses
Tools for building terminal-based user interfaces

---
* Homepage: https://github.com/mbacarella/curses
* Source repo: git+https://github.com/mbacarella/curses
* Bug tracker: http://github.com/mbacarella/curses/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by mbacarella** [comment]
Makefile had the wrong VERSION. Syncs up with opam version now.
https://github.com/mbacarella/curses/issues/2

**Comment by kit-ty-kate** [comment]
`1.0.7` seems to be more than a year old: https://github.com/mbacarella/curses/tags Did you mean to release 1.0.8? (in which case the tag is missing)

**Comment by mbacarella** [comment]
argh. Yes I meant 1.0.8. Pushed that to the curses repo. Should I close this PR and run opam publish again?

**Comment by kit-ty-kate** [comment]
> Should I close this PR and run opam publish again?

It's probably the easiest, yes.

**Pull request closed without merging**
