### PR TITLE
[new release] smtml (0.1.0)

### PR DESCRIPTION
**Pull request by filipeom**
# Smt.ml Release Notes

**Repo**: https://github.com/formalsec/smtml

**Documentation**: https://formalsec.github.io/smtml/

In this PR we:

- Rename the project from the uninspiring `encoding` to `smtml` 
- Release a new major version of the library  

## Version 0.1.0 

See [CHANGES](https://github.com/formalsec/smtml/blob/main/CHANGES.md)

### CODE REVIEW

**Comment by mseri** [comment]
Please do not rename or rewrite the tarballs for the old packages.

We usually add a deprecation message saying that the package has been renamed, and create a new transition package, `encoding.transition`, if you want, that depends on `smtml` and informs the users of the change.

**Comment by mseri** [comment]
The old releases should still be downloadable from https://archive.softwareheritage.org/browse/snapshot/701305241f06e5581d8a24f0936cf12b89d34645/releases/?origin_url=opam%2Bhttps://opam.ocaml.org/packages/encoding/

Version 0.0.4 is still available cached from https://opam.robur.coop/cache/md5/79/79eace174880a378ca634f3b6d6dca2b but not the other 3.

**Comment by filipeom** [comment]
I've removed the package renaming and added a deprecation message. However, now it's complaining about possible name collisions. Am I required to change the new package name?

**Comment by mseri** [comment]
The collision is not a problem

**Pull request merged**
