### PR TITLE
+ocaml-src.4.06.1

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
I don't know why opam 1.2 and alpine 3.6 does not work in the datakit CI.  the conf-m4 package has on alpine a dependency onto the alpine m4 package, which doesn't seem to get installed in the ci run.  arm64 ci seems to be out of disk space.

**Comment by jpdeplaix** [comment]
There is a problem with the alpine image on both CIs:
* On x86_64 the docker image itself is not right and needs to be fixed
* On AM64 this issue occures https://github.com/ocaml/opam/issues/3227

I've just made some space from the disk so that should be taken care of.

**Comment by hannesm** [comment]
@jpdeplaix thanks!  AFAICT the CI fails in other PRs with the same issues, so this can be safely merged.  would be great if someone would do so :)

**Comment by jpdeplaix** [comment]
Yep, sounds good. Thanks !

**Pull request merged**
