### PR TITLE
[new release] randoml (0.1.3)

### PR DESCRIPTION
**Pull request by mimoo**
Generating cryptographically-secure random numbers

- Project page: <a href="https://github.com/mimoo/randoml">https://github.com/mimoo/randoml</a>

##### CHANGES:

Fix vendoring of rust dependencies for release (bis)

### CODE REVIEW

**Comment by mseri** [comment]
https://github.com/mimoo/randoml/blob/583d86b55d63ad6ed5fce097df4d105918ee7a35/lib/rand/dune#L3: I think you need to copy `vendor` into _build, otherwise you are running `cargo build` without the vendored sources present.
Also, you don't need the quotes there in the dune file.

**Comment by mseri** [comment]
To test it, you can run `opam install -t .` from the root of the project

**Comment by mimoo** [comment]
ok thanks for the pointers! I'll get it right before submitting here :) thanks a lot

**Comment by mimoo** [comment]
I think the issue is that it's not copying the `.cargo` folder in `_build`

**Comment by mimoo** [comment]
and I need `vendor` in `(dirs :standard \ "target" "vendor")` because it has some broken dune files in it

**Pull request closed without merging**
