### PR TITLE
CamlPDF Version 2.2.1

### PR DESCRIPTION
**Pull request by johnwhitington**

### CODE REVIEW

**Comment by avsm** [comment]
```
[camlpdf.2.2.1] https://github.com/johnwhitington/camlpdf/archive/v2.2.1.zip downloaded
[ERROR] Bad checksum for
        /home/travis/.opam/packages.dev/cpdf.2.2.1/v2.2.1.tar.gz:
          - 5c0caa7bed9452cf7d1ed0492929824d [expected result]
          - 11e29f8d3448dcdbb96a6ee622425201 [actual result]
        This may be fixed by running `opam update`.
```

**Comment by johnwhitington** [comment]
Thansk.

In the report above, why is the build of camlpdf checking the checksum against cpdf rather than camlpdf? This seems to be a mistake at your end...

I have just checked by manual downloading, and the urls and md5 sums for the url files for both cpdf and camlpdf are correct.

**Comment by yallop** [comment]
The output is slightly confusing, but it's reporting that downloading the archive and verifying the checksum has succeeded for camlpdf:
```
[camlpdf.2.2.1] https://github.com/johnwhitington/camlpdf/archive/v2.2.1.zip downloaded
```
but failed for cpdf:
```
[ERROR] Bad checksum for
        /home/travis/.opam/packages.dev/cpdf.2.2.1/v2.2.1.tar.gz:
          - 5c0caa7bed9452cf7d1ed0492929824d [expected result]
          - 11e29f8d3448dcdbb96a6ee622425201 [actual result]
        This may be fixed by running `opam update`.
```

Checksum verification is failing because the `url` file gives the URL for the `tar.gz` archive but the checksum for the `zip` file:

```
$ wget -q  https://github.com/johnwhitington/cpdf-source/archive/v2.2.1.tar.gz -O - | md5sum
11e29f8d3448dcdbb96a6ee622425201  -
```

```
$ wget -q  https://github.com/johnwhitington/cpdf-source/archive/v2.2.1.zip -O - | md5sum
5c0caa7bed9452cf7d1ed0492929824d  -
```

**Comment by johnwhitington** [comment]
Thanks for the explanation, Jeremy. Fixed by changing to .zip (both camlpdf and cpdf now use .zip)

**Comment by yallop** [comment]
Thanks, @johnwhitington.

One remaining issue — it appears that `graphicspdf` may need an additional constraint to exclude the new version of `camlpdf`:

```
# ocamlfind ocamlc -package camlpdf -c -g graphicspdf.ml
# File "graphicspdf.ml", line 101, characters 62-67:
# Error: This expression has type Pdftext.standard_font
#        but an expression was expected of type Pdftext.encoding
```

**Comment by johnwhitington** [comment]
Have added GraphicsPDF, fixed, and now synced in version number with CamlPDF.

**Pull request merged**
