### PR TITLE
ocamlbuild.0.10.0

### PR DESCRIPTION
**Pull request by gasche**
<https://github.com/ocaml/ocamlbuild/releases/tag/0.10.0>

### CODE REVIEW

**Comment by gasche** [comment]
I don't understand why the CI complains -- it says that `curl` failed?

**Comment by samoht** [comment]
Probably a network glitch, I have restarted the failed jobs

**Comment by samoht** [comment]
The url is wrong:
```
https://github.com/ocaml/ocamlbuild/archive/0.10.tar.gz
```
Need one more 0.

**Comment by gasche** [comment]
Indeed, sorry...

**Pull request merged**
