### PR TITLE
telegraml.1.1 - via opam-publish

### PR DESCRIPTION
**Pull request by nv-vn**
Telegram Bot API for OCaml
An implementation of the Telegram Bot API in 100% OCaml,
using Lwt for asynchronous operations and Cohttp for networking.
Implements most basic functionality present in the API, plus
convenience modules for error handling and defining commands.

---
* Homepage: https://github.com/nv-vn/telegraml
* Source repo: https://github.com/nv-vn/telegraml.git
* Bug tracker: https://github.com/nv-vn/telegraml/issues

---

Pull-request generated by opam-publish v0.3.1

### CODE REVIEW

**Comment by nv-vn** [comment]
Hm, looks like I'll need to add a version constraint into the OPAM file. If I had some more time on my hands, I'd go back and test previous versions of dependencies to see what constraints I can lower, but I can't do so at the current moment.

**Comment by nv-vn** [comment]
Oh crap, forgot quotes!

**Comment by yallop** [comment]
The uninstall step is leaving some files behind, [according to Travis](https://travis-ci.org/ocaml/opam-repository/jobs/120808791):

```
[WARNING] Directory /home/travis/.opam/system/lib/telegraml is not empty, not
          removing
```

**Comment by nv-vn** [comment]
Interesting, this seems to have been present in version 1.0 as well... running `make uninstall` from the directory removes everything on its own for me, so I'm not exactly sure what the issue is here. Is there any simple way to see what the files being left behind are?

**Comment by nv-vn** [comment]
Huh, I updated it and merged with the origin/master branch a couple minutes ago with a fix (hopefully). Not sure why Github doesn't show it as having updated yet

**Comment by yallop** [comment]
Travis seems to have missed the update.  I'll close and reopen the PR to trigger a build.

**Comment by yallop** [comment]
The problem seems to be that calling `make uninstall` from a freshly-unpacked tarball (i.e. the `TelegraML-1.1` directory without build artifacts) doesn't actually uninstall anything.  Invoking `ocamlfind` directly from the `remove` field of the `opam` file should fix it:

```
remove: ["ocamlfind" "remove" "telegraml"]
```

**Comment by nv-vn** [comment]
Thanks, just changed that. Hopefully it should work now

**Comment by nv-vn** [comment]
One of the jobs seems to have failed on its own:
```
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/precise/Release.gpg  Connection failed [IP: 91.189.91.14 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "bash -e .travis-ci-install.sh" failed and exited with 100 during .
Your build has been stopped.
```
Closing and reopening to relaunch a build

**Pull request merged**
