### PR TITLE
Constrain async_ssl 113.33.00 to ctypes versions between 0.4.0 and 0.6.0

### PR DESCRIPTION
**Pull request by yallop**
Split from #6664 to ease testing.

### CODE REVIEW

**Comment by dsheets** [comment]
`ppx_jane.113.33.03` fails on OCaml 4.02.3 with

> Cannot load /Users/travis/.opam/4.02.3/lib/ppx_variants_conv/./ppx_variants_conv.cmxs: error loading shared library: dlopen(/Users/travis/.opam/4.02.3/lib/ppx_variants_conv/./ppx_variants_conv.cmxs, 138): Symbol not found: _camlPpx_core

**Comment by diml** [comment]
The problem is that ppx\_jane 113.33.03 should depend on ppx\_variants\_conv 113.33.03. We never use dynamic linking in the build of JS packages. I'll look into updating the constraints

**Comment by samoht** [comment]
@yallop can you rebase this PR now that #6710 is in?

**Comment by yallop** [comment]
Rebased.

**Comment by samoht** [comment]
```
#=== ERROR while installing async_ssl.113.33.01 ===============================#
# opam-version 1.2.2
# os           linux
# command      ./configure --prefix /home/travis/.opam/system
# path         /home/travis/.opam/system/build/async_ssl.113.33.01
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/async_ssl.113.33.01/async_ssl-3599-e41c13.env
# stdout-file  /home/travis/.opam/system/build/async_ssl.113.33.01/async_ssl-3599-e41c13.out
# stderr-file  /home/travis/.opam/system/build/async_ssl.113.33.01/async_ssl-3599-e41c13.err
### stderr ###
# ocamlfind: Package `ctypes.foreign.threaded' not found
# W: Field 'pkg_ctypes_foreign_threaded' is not set: Command ''/home/travis/.opam/system/bin/ocamlfind' query -format %d ctypes.foreign.threaded > '/tmp/oasis-fc519b.txt'' terminated with error code 2
# E: Cannot find findlib package ctypes.foreign.threaded
# E: Failure("1 configuration error")
```

**Comment by yallop** [comment]
I don't know why that failure is occurring.

**Comment by diml** [comment]
It installed ctypes 0.3.4, maybe ctypes.foreign.threaded wasn't available in this version? async\_ssl 113.33.00 depends on ctypes >= 0.4.0 and it seems this constraint was lost in subsequent versions

**Comment by samoht** [comment]
Good spot, the CI is indeed installing an older version of ctypes:
```
install ctypes            0.3.4
```

@yallop can you add lower bounds on the constraints as well? Thanks!

**Comment by yallop** [comment]
I've added the lower bounds to 133.33.01 and split out the changes into #6729 to avoid the OS X Travis timeout.

**Comment by samoht** [comment]
All merged now, thanks!

**Pull request merged**
