### PR TITLE
objsize 0.18 for OCaml 4.03

### PR DESCRIPTION
**Pull request by gdsfh**

### CODE REVIEW

**Comment by gdsfh** [comment]
Can you please tell me why one of builds, https://travis-ci.org/ocaml/opam-repository/jobs/127029864 , has failed?  I see no apparent reason.

**Comment by dsheets** [comment]
You need to use `hg://https://...` in the `dev-repo` fields. This isn't correct URI syntax but older opams only understand this form where the newer versions have been taught about `hg+https://`.

**Comment by gdsfh** [comment]
@dsheets, thanks!

Should I squash these 4 commits to not pollute history?

**Comment by dsheets** [comment]
GitHub has merge+squash now. Thanks! :-)

**Pull request merged**
