### PR TITLE
Add a conf-liblz4 package and clean the lz4 package descriptions

### PR DESCRIPTION
**Pull request by kit-ty-kate**
cc @whitequark @UnixJunkie

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Arf `liblz4-dev` on Ubuntu 14.04 doesn't have any pkg-config file.. :((

**Comment by UnixJunkie** [comment]
You can probably get away by compiling a C program that includes lz4.h and that links against lz4.
If the program compiles, it means lz4-dev is present and usable on the system.

**Comment by mseri** [comment]
Is it wort the hassle? Trusty end of suppport is in less than one year

**Comment by UnixJunkie** [comment]
Is pkg-config really that portable?
Is it available on windows and BSDs?

**Comment by mseri** [comment]
It is definitely available in OpenBSD and FreeBSD, I believe also in NetBSD. No idea about windows.

**Comment by mseri** [comment]
At least since xenial, it contains the metadata for `pkg-config`:
```
$ apt-file list liblz4-dev
liblz4-dev: /usr/include/lz4.h
liblz4-dev: /usr/include/lz4frame.h
liblz4-dev: /usr/include/lz4hc.h
liblz4-dev: /usr/lib/x86_64-linux-gnu/liblz4.a
liblz4-dev: /usr/lib/x86_64-linux-gnu/liblz4.so
liblz4-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/liblz4.pc
liblz4-dev: /usr/share/doc/liblz4-dev/changelog.Debian.gz
liblz4-dev: /usr/share/doc/liblz4-dev/copyright
```

I think we should merge this PR, especially given that in 6 months Trusty will no longer be supported.

**Comment by hcarty** [comment]
Makes sense to me.  Thanks all!

**Pull request merged**
