### PR TITLE
added packages/oranger/oranger.0.9.11

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
this one tries to download a released version of ranger, rather than trying to do a git checkout

**Comment by UnixJunkie** [comment]
From the CI tests:
```
# +wget https://github.com/imbs-hl/ranger/archive/0.9.11.tar.gz
# --2018-09-21 01:31:46--  https://github.com/imbs-hl/ranger/archive/0.9.11.tar.gz
# Resolving github.com... failed: nodename nor servname provided, or not known.
# wget: unable to resolve host address ‘github.com’
```

**Comment by mseri** [comment]
I think this will never work, I think the opam sandbox does not allow you to access the network

**Comment by rjbou** [comment]
@UnixJunkie You can use [`estra-xources`](https://opam.ocaml.org/doc/Manual.html#opamsection-extra-sources) field.

**Comment by mseri** [comment]
Oh, neat!

**Comment by UnixJunkie** [comment]
@rjbou I am trying the extra-sources field. Thanks for suggesting it.

**Comment by UnixJunkie** [comment]
Thanks, I pushed a fix.

**Comment by mseri** [comment]
It seems to have worked!

**Comment by mseri** [comment]
Thanks

**Pull request merged**
