### PR TITLE
Update lemonade to 0.3.0

### PR DESCRIPTION
**Pull request by michipili**

### CODE REVIEW

**Comment by michipili** [comment]
The error 039 is the usual false positive showing up when using BSD Make! :)

**Comment by michipili** [comment]
I reviewed the errors, they are failed builds unable to install bmake and would need a simple retry.

**Comment by michipili** [comment]
Just a gentle ping on this! :)

**Comment by samoht** [comment]
I've just restarted the builds. If that still fails, can you try to add `dist: trusty` in the `.travis.yml` to see if we can use the [new](http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/) Trusty builds? Thanks!

**Comment by michipili** [comment]
@samoht Builds failed again for the same (bad) reason, so let us try this again with *trusty*!

**Comment by michipili** [comment]
Now most of the builds succeeded, but two Linux builds failed because of what look a desynchronised index for the repository.

**Comment by samoht** [comment]
@avsm There is no 4.00.1 in your Trusty PPAs?

```
++sed -n 's/^Version: \(4.00\)/\1/p'
+sudo apt-get install -y ocaml= ocaml-base= ocaml-native-compilers= ocaml-compiler-libs= ocaml-interp= ocaml-base-nox= ocaml-nox= camlp4= camlp4-extra= opam
```

**Comment by avsm** [comment]
I can't rebuild those unfortunately, due to a Launchpad limitation.  Time to switch to the Travis/Docker support...

**Comment by michipili** [comment]
> I can't rebuild those unfortunately, due to a Launchpad limitation. Time to switch to the Travis/Docker support...

But meanwhile, how do we run tests? :)

**Comment by michipili** [comment]
Just a gentle ping on this! :)

**Comment by samoht** [comment]
Can you revert the `trusty` bits? I'm fine to merge the PR and thanks for taking part to that experiment!

**Comment by michipili** [comment]
@samoht I removed the commit with trusty bits. Happy to have taken part to the experiment! :)

**Comment by samoht** [comment]
> @avsm I can't rebuild those unfortunately, due to a Launchpad limitation. Time to switch to the Travis/Docker support...

I'm not sure how we do that. What plan do you have in mind?

**Pull request merged**
