### PR TITLE
github 0.9.4 is in conflict with cohttp 0.18.0

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by rgrinberg** [comment]
@dsheets i thought this wasn't supposed to happened?

**Comment by avsm** [comment]
older versions of github will definitely conflict. 1.0 will work with any version of cohttp

**Comment by avsm** [comment]
@samoht dont previous github versions also need this conflict

**Comment by samoht** [comment]
@avsm older versions already have an upper bound on an older cohttp version.

**Pull request merged**
