### PR TITLE
add bun versions 0.3.1 and 0.3.2

### PR DESCRIPTION
**Pull request by yomimono**

### CODE REVIEW

**Comment by yomimono** [comment]
CI failures are because `bun` now has tests (yay!) but they require pins of some of *crowbar's* test dependencies, because `opam install -t` wants to install them since `bun` has a test dependency on `crowbar`.

I'll remove the `build-test` stanzas from the `opam` files for submission into `opam-repository` for now.

**Comment by kit-ty-kate** [comment]
`afl` is failing on Debian Testing & Unstable but not on stable :/ Do you have any idea why ?

**Comment by yomimono** [comment]
Hm, no, wasn't it passing last week when I added `AFL_NO_X86`?  I'll look into it.

**Comment by kit-ty-kate** [comment]
Since last week the CI got fixed and we are now able to test all distros. Debian Testing & Sid weren't tested back then :/

**Comment by yomimono** [comment]
Oh, that makes sense. I'll try to get this sorted tonight.

**Comment by yomimono** [comment]
The problems with `afl` in Debian are being addressed upstream - see the conversation on the afl-users list at https://groups.google.com/forum/#!topic/afl-users/cCzDOLjt1VI , with links to the bug reports in the Debian repository.

**Comment by kit-ty-kate** [comment]
Wow thanks a lot ! Merging this now. Sorry to have waited a bit.

**Comment by yomimono** [comment]
No problem, thanks for drawing my attention to it!

**Pull request merged**
