### PR TITLE
Package sklearn.sk0.22-0.3.0

### PR DESCRIPTION
**Pull request by lehy**
### `sklearn.sk0.22-0.3.0`
Scikit-learn machine learning library for OCaml
Scikit-learn machine learning library for OCaml
These are bindings to Python's scikit-learn machine learning library:
- Simple and efficient tools for predictive data analysis
- Accessible to everybody, and reusable in various contexts
- Built on NumPy, SciPy, and matplotlib
- Open source, commercially usable - BSD license

---
* Homepage: https://github.com/lehy/ocaml-sklearn
* Source repo: git+https://github.com/lehy/ocaml-sklearn.git
* Bug tracker: https://github.com/lehy/ocaml-sklearn/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by lehy** [comment]
I suppose this is failing until #16620 and #16621 are merged, since it depends on it. (Guessing, since I cannot see an error log above).

**Comment by hannesm** [comment]
I'm slightly surprised by the version: if I understand opam correctly, this is package `sklearn` and version `sk0.22-0.3.0` -- where previous releases were `0.22-0.1.3` and `0.22-0.2.0` -- the `sk0.` prefix looks suspicious to me, is this intentional?

**Comment by lehy** [comment]
> I'm slightly surprised by the version: if I understand opam correctly, this is package `sklearn` and version `sk0.22-0.3.0` -- where previous releases were `0.22-0.1.3` and `0.22-0.2.0` -- the `sk0.` prefix looks suspicious to me, is this intentional?

Yes it is, see details in https://github.com/ocaml/opam-repository/pull/16620#issuecomment-643162045 .

**Comment by mseri** [comment]
@lehy now that #16620 and #16621 have been merged, can you rebase and force-push to have a fresh CI run?

Once this is merged consider announcing these releases in discuss.ocaml.org, we have a community category and an annoucement tag for this purpose

**Comment by lehy** [comment]
Yes, will do asap, thanks!

**Comment by lehy** [comment]
Rebase done.

**Comment by mseri** [comment]
Thanks. I'll wait for the big CI run, and if the tests look good I'll merge

**Comment by mseri** [comment]
Looks good, thank you very much.

Feel free to announce this and the other packages on the discuss.ocaml.org forum. We have a community category and an announcement tag for this purpose. There are many computationally oriented people in the community that will find this quite interesting

**Pull request merged**
