### PR TITLE
[new release] tyxml-ppx, tyxml-syntax, tyxml and tyxml-jsx (4.4.0)

### PR DESCRIPTION
**Pull request by Drup**
:tada: A reasonable tyxml release :tada: 

------

CHANGES:

* Add support for Reason's JSX syntax with a new `tyxml-jsx` package
  (ocsigen/tyxml#254 by Joris Giovannangeli and Gabriel Radanne
   with help from Ulrik Strid and Louis Roché)
* Modernize the handling of toplevel printers for utop.
  (Gabriel Radanne)

## Elements and attributes

* Add `allowfullscreen`, `allowpaymentrequest`, `referrerpolicy` attributes
  (ocsigen/tyxml#242 by Thibault Suzanne)
* Allow `crossorigin` attribute for script element
  (ocsigen/tyxml#243 by Thibault Suzanne)
* Greatly improved support of whitespaces in the PPX
  (ocsigen/tyxml#225 by Jules Aguillon)
* Add preliminary support for ARIA attributes
  (ocsigen/tyxml#253 by Stéphane Legrand and Gabriel Radanne)
* Add `template` element
  (ocsigen/tyxml#239 Stéphane Legrand)

* Several bug fixes for types and PPX

### CODE REVIEW

**Comment by Drup** [comment]
> [](https://github.com/ocaml/opam-repository/commit/8f0ae2725405885cae03e8f5f54549187ce30f34)
> 
> A pull request by opam-seasoned @Drup.

aww :blush:

**Comment by kit-ty-kate** [comment]
Eliom is not compatible with this release of tyxml. I'll open a PR to add the appropriate constraints.
```
# File "src/lib/eliom_shared_content.eliom", lines 342-393, characters 2-5:
# Error: Signature mismatch:
#        ...
#        The value `string_of_referrerpolicy' is required but not provided
#        File "lib/html_sigs.mli", lines 1219-1220, characters 2-52:
#          Expected declaration
```

**Comment by kit-ty-kate** [comment]
@Drup could you confirm the revdeps failure on eliom is not an issue?
Could you also return the minor fix on the package description upstream?

**Comment by Drup** [comment]
Indeed, eliom needs to be adapted to the new version. I'll fix the dune dep upstream. Thanks!

Feel free to push the other bunch of patches in this PR too. :)

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
