### PR TITLE
Switch to Trusty Beta

### PR DESCRIPTION
**Pull request by yallop**
Details: https://docs.travis-ci.com/user/ci-environment/

### CODE REVIEW

**Comment by dsheets** [comment]
Does this close #5341?

**Comment by yallop** [comment]
It does.  We should have a separate issue to track the multi-distribution Docker-based builds.

**Comment by samoht** [comment]
Seems that this does not support OCaml 4.00 and 3.12

**Comment by yallop** [comment]
Yes, some more work is needed here.

**Comment by yallop** [comment]
I don't have time to work on this for the moment, so I'm closing.

**Comment by toots** [comment]
Well, are you guys taking contributions to this or is it closed as won't fix?

**Comment by OCamlPro-Henry** [comment]
@toots If you are able to fix ocaml-4.00 and ocaml-3.12, contributions are welcome !

**Pull request closed without merging**
