### PR TITLE
+opam2web.1.5.0

### PR DESCRIPTION
**Pull request by avsm**
required for https://github.com/ocaml/ocaml.org/pull/912

### CODE REVIEW

**Comment by Chris00** [comment]
The [package listing](https://ocaml.org/) seems to be wrong, even with the updated version...

**Comment by avsm** [comment]
@Chris00 I didnt quite understand the comment above -- how is it wrong, and should this release not be merged into opam? The last release seems to have been close to 2 years ago. cc @altgr

**Comment by Chris00** [comment]
I was surprised to see only z... packages.  It is fine now.

**Comment by AltGr** [comment]
The deployed version (on opam.ocaml.org) is actually the one from https://github.com/AltGr/opam2web (master) — this since I had to do quickfixes due to performance/memory issues. Sorry for the confusion.

**Comment by Chris00** [comment]
Since opam2web.1.5.0 is not yet released, could you please push them to the main repository so they can be incorporated into the new release and all versions are kept in sync?  Thanks.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam2web/pull/152 It's probably better to make a new 1.5 release with these changes.

**Comment by avsm** [comment]
I have cut a new 1.5.0 release and refreshed this PR

**Comment by avsm** [comment]
@AltGr - should be able to switch the ocaml.org deployed version to this now

**Comment by AltGr** [comment]
Done, bound back to this repo's master.

**Pull request merged**
