### PR TITLE
Coq 8.19.2 (coq-core,coq-stdlib,coqide-server,coq)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
It seems there were some network errors in CI.

**Comment by SkySkimmer** [comment]
Let's try rerunning

**Comment by SkySkimmer** [comment]
Let's try without coqide

**Comment by erikmd** [comment]
Indeed: the Opam-CI check is green now :heavy_check_mark:

**Comment by mseri** [comment]
Thanks, feel free to re-submit coqide as a separate PR

**Pull request merged**
