### PR TITLE
Add KreMLin 1.0.0

### PR DESCRIPTION
**Pull request by R1kM**
This PR adds a new version of KreMLin.
Note, the latest (non-dev) version of fstar that this package depends on is currently missing some constraints, this should probably not be merged before the issue https://github.com/FStarLang/FStar/issues/2430 is resolved.
cc @protz

### CODE REVIEW

**Comment by R1kM** [comment]
The fstar issue mentioned above is currently being addressed by #20490

**Comment by mseri** [comment]
👍 As soon as https://github.com/ocaml/opam-repository/pull/20490 is merged I will remove the `don't-merge` label

**Comment by mseri** [comment]
Can you rebase on the opam-repository master to test with the latest f* changes?

**Comment by mseri** [comment]
Fails everywhere with:
```
# ⚙ KreMLin auto-detecting tools. Here's what we found:
# readlink is: readlink
# ⚙ KreMLin will drive F*. Here's what we found:
# FSTAR_HOME is /home/opam/.opam/4.08 (via fstar.exe in PATH)
# Detected an OPAM setup of F*
# fstar is: /home/opam/.opam/4.08/bin/fstar.exe /home/opam/.opam/4.08/lib/kremlin/runtime/WasmSupport.fst /home/opam/.opam/4.08/lib/fstar/FStar.UInt128.fst --trace_error --cache_checked_modules --expose_interfaces --include /home/opam/.opam/4.08/lib/kremlin --include /home/opam/.opam/4.08/include/
# Fatal error: exception Sys_error("/home/opam/.opam/4.08/share/kremlin/misc//Makefile.basic: No such file or directory")
# make[1]: *** [Makefile:103: dist/generic/Makefile.include] Error 2
# make[1]: Leaving directory '/home/opam/.opam/4.08/.opam-switch/build/kremlin.1.0.0/kremlib'
# make: *** [Makefile:29: kremlib] Error 2
```
There are also a number of warnings, but those are probably known already: see e.g. on https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/1c072e546a2f275f40275ddf5e37808725ac3147/variant/opam-2.1,compilers,4.12,kremlin.1.0.0

**Comment by R1kM** [comment]
Thanks for the heads-up. I'll debug this locally, please feel free to mark this as "do not merge" for now.

**Comment by R1kM** [comment]
The previous issue should be fixed

**Comment by R1kM** [comment]
I also fixed the issue related to packages lower bounds, the remaining CI issue seems related to the CI infrastructure (on centos8)

**Comment by mseri** [comment]
Thanks. Looks fine

**Pull request merged**
