### PR TITLE
pfff.0.29

### PR DESCRIPTION
**Pull request by juergenhoetzel**
Added upstream OCaml 4.02.0 patches

### CODE REVIEW

**Comment by yallop** [comment]
The [3.12](https://travis-ci.org/ocaml/opam-repository/jobs/83965967) and [4.00.1](https://travis-ci.org/ocaml/opam-repository/jobs/83965965)) Travis builds are failing because `|>` (which was introduced in 4.01.0) is unavailable:

```
### stderr ###
# File "unit_prolog_php.ml", line 29, characters 2-4:
# Error: Unbound value |>
```

Could you please fix the opam version constraint and the other errors in the opam file?

**Comment by juergenhoetzel** [comment]
Done

**Comment by avsm** [comment]
```
[ERROR] At ~/.opam/repo/default/packages/pfff/pfff.0.29/opam:25:43:
  Not a recognised version-control URL
```

This needs to be:

```
dev-repo: "https://github.com/facebook/pfff.git"
```

(note the `.git` at the end)

**Comment by juergenhoetzel** [comment]
Sorry: I was not aware of the repo-url-typo, because I was able to clone from this URL.

**Comment by avsm** [comment]
Thanks! It's just the detection logic in OPAM, since it's difficult to disambiguate an `https://` URL in terms of the vcs-method (without putting in a GitHub-specific hack)

**Pull request merged**
