### PR TITLE
[hotfix] OCADml (0.3.0)

### PR DESCRIPTION
**Pull request by geoffder**
Types and functions for building CAD packages in OCaml

- Project page: <a href="https://github.com/OCADml/OCADml">https://github.com/OCADml/OCADml</a>
- Documentation: <a href="https://OCADml.github.io/OCADml">https://OCADml.github.io/OCADml</a>

##### CHANGES:

- add gg library dependency
- replaced vector (V{2,3,4}.t), matrix (Affine{2,3}), and bounding box types
 with those from gg
- protect bezier memoization with mutex (OCaml 5 compatibility)

### CODE REVIEW

**Comment by geoffder** [comment]
Unfortunately found an correctness issue that I thought was worthy of a hotfix, sorry for the extra trouble!

**Comment by mseri** [comment]
can you please release it as 0.3.1 and, if you really want to remove it, mark this version `available: false`?

**Comment by geoffder** [comment]
Ok I'll do that instead. I'd really rather have this one unavailable.

**Comment by geoffder** [comment]
Added `availability: false`, I'll make a PR for v0.3.1.

**Comment by kit-ty-kate** [comment]
Thanks. Please remember in the future that tags should never change after a release as it breaks your end users and ourselves. If something really bad happens you can either remove it if it's really bad, patch it using opam's `patches:` field if you can't do otherwise or simply make a new release (preferred solution)

**Comment by geoffder** [comment]
Roger, will (not) do. I should have asked first before assuming it would be fine just because it was soon after the merge.

**Pull request merged**
