### PR TITLE
wcs-ocaml version 2017-05-26.05

### PR DESCRIPTION
**Pull request by mandel**
Could you please merge the new version of wcs-ocaml?

Thanks

### CODE REVIEW

**Comment by mseri** [comment]
I think sedlex needs some bouds or a new release. The installation is failing before even trying to compile wcs-ocaml with 
```
# File "ppx_sedlex.ml", line 11, characters 5-24:
# Error: Unbound module Ast_convenience_405
# make[1]: *** [sedlex.cma] Error 2
# make: *** [all] Error 2

```

If I recall correctly, the master version of sedlex is fixed but I may be wrong

**Comment by mseri** [comment]
See here: 
https://github.com/alainfrisch/sedlex/issues/64

Ping also @pmetzger that may know what we need to do

**Comment by mseri** [comment]
Sedlex should be fine now. To retrigger the CI can you please rebase on the current opam-repository master?

**Comment by mandel** [comment]
The tests require Watson Assistant credentials.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Pull request merged**
