### PR TITLE
Package radare2.0.0.5

### PR DESCRIPTION
**Pull request by XVilka**
- Migrated from the `Yojson.Basic` interface to `Yojson.Safe`
- Expose `Yojson.t` instead of the `Yojson.Basic.t`

### CODE REVIEW

**Comment by XVilka** [comment]
Travis failure is network?
```
[yojson.1.7.0] downloaded from https://github.com/ocaml-community/yojson/releases/download/1.7.0/yojson-1.7.0.tbz
[ERROR] The sources of the following couldn't be obtained, aborting:
          - dune.2.6.0:
            https://github.com/ocaml/dune/releases/download/2.6.0/dune-2.6.0.tbz
            (Download command failed: "/usr/local/bin/wget
        --content-disposition -t 3
            -O
            /Users/travis/.opam/ocaml-system/.opam-switch/sources/dune.2.6.0/dune-2.6.0.tbz.part
            https://github.com/ocaml/dune/releases/download/2.6.0/dune-2.6.0.tbz
        -U
            opam/2.0.7" exited with code 4)
'opam install --deps-only radare2.0.0.5' failed.
The command "bash -e .travis-ci.sh" exited with 40.
```

**Comment by XVilka** [comment]
The failures are only because Debian removed the radare2 package in anything but "testing":
```
 # OS package update successful
The following command needs to be run through "sudo":
    apt-get install -qq -yy m4 radare2
E: Package 'radare2' has no installation candidate
OS package installation failed
```

**Comment by XVilka** [comment]
Let me know if I need to do anything to get this merged.

**Comment by kit-ty-kate** [comment]
We can't test much because the required system package is not available under debian stable but it should be ok.

I've fixed a constraint as your `dune-project` file says this package requires at least dune 2.0. Could you return the fix upstream?

Thanks!

**Comment by XVilka** [comment]
Thank you! I am sure will.

**Pull request merged**
